### ISSUE TITLE
init_process_group problem (hangs always in two machines)

### ISSUE THREAD

**Issue by jtovartr** [pytorch/pytorch#100167]
### 🐛 Bug

Hi everyone, 

Im triying to use pytorch distributed but init_process_group hangs always in all machines.

Here is my master script:

```
import os
import torch
import torch.distributed as dist

def setup():
    os.environ['MASTER_ADDR'] = '192.168.43.51'
    os.environ['MASTER_PORT'] = '8000'
    os.environ['RANK'] = '0'
    os.environ['WORLD_SIZE'] = '2'

    # initialize the process group
    dist.init_process_group(backend='gloo', init_method='tcp://192.168.43.51:8000',rank=0,world_size=2)
    print("Connected ...")

if __name__ == "__main__":
	setup()
```
And my client script:

```
import os
import torch
import torch.distributed as dist

def setup():
    os.environ['MASTER_ADDR'] = '192.168.43.51'
    os.environ['MASTER_PORT'] = '8000'
    os.environ['RANK'] = '1'
    os.environ['WORLD_SIZE'] = '2'

    # initialize the process group
    dist.init_process_group(backend='gloo', init_method='tcp://192.168.43.51:8000',rank=1,world_size=2)
    print("Connected ...")

if __name__ == "__main__":
	setup()
```

When I launch both (`python3 master.py` and `python3 client.py`) the init_process_group hangs. I have enabled the port in my firewall. Both machines can make a ping and I can launch a telnet connection in the client machine to the master machine when the master script is running.

### Versions

PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.0
Libc version: glibc-2.31

Python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-71-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] flake8==4.0.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.1
[pip3] numpydoc==1.4.0
[pip3] torch==1.13.1
[pip3] torchvision==0.14.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] numpydoc                  1.4.0            py39h06a4308_0  
[conda] torch                     1.13.1                   pypi_0    pypi
[conda] torchvision               0.14.1                   pypi_0    pypi

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by Aidyn-A** [comment]
You are supplying too much information that conflicts with each other. 
Use either `env` method:
```Python
def setup():
    os.environ['MASTER_ADDR'] = '192.168.43.51'
    os.environ['MASTER_PORT'] = '8000'
    os.environ['RANK'] = '<rank>'
    os.environ['WORLD_SIZE'] = '2'

    dist.init_process_group(backend='gloo')
    print("Connected ...")
```

or `tcp`:
```Python
def setup():
    dist.init_process_group(backend='gloo', init_method='tcp://192.168.43.51:8000', rank=<rank>, world_size=2)
    print("Connected ...")
```
but not both.

**Comment by jtovartr** [comment]
@Aidyn-A I have tried both proposals but it does not work. The result is the same, it always hangs.

**Comment by kumpera** [comment]
try enabling higher logging levels for distributed to get better sense of what's going on: TORCH_DISTRIBUTED_DEBUG="INFO" or "DETAIL"

**Comment by jtovartr** [comment]
Hi, I solved my problem by specifying in both the client and master code the variables:

**Master node:**

```
- GLOO_SOCKET_IFNAME = <master network interface name>
- TP_SOCKET_FINAME = <master network interface name>
```

The following rule must be introduced to the firewall: `sudo ufw allow from <client IP>`

**Client node:**

```
- GLOO_SOCKET_IFNAME = <client network interface name>
- TP_SOCKET_FINAME = <client network interface name>
```

The following rule must be introduced to the firewall: `sudo ufw allow from <master IP>`
