### ISSUE TITLE
Quadro m2000m not able to get pytorch working with gpu

### ISSUE THREAD

**Issue by theja2289** [pytorch/pytorch#10109]
@peterjc123  Could you please help me with this, also let me know if I have to compile it from source. 

If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

## Issue description
I'm not able to get pytorch working with cuda. 

## Code example
if torch.cuda.device_count() > 0:
    print("Let's use", torch.cuda.device_count(), "GPUs!")
else:
    print("no usable gpus")
    
import torch
a = torch.cuda.FloatTensor([1.])
print(a)

Let's use 1 GPUs!
tensor([1.], device='cuda:0')

it works in the above case, but something goes wrong below 

returns: test images, test predicted keypoints, test ground truth keypoints
test_images, test_outputs, gt_pts = net_sample_output()

print out the dimensions of the data to see if they make sense
print(test_images.data.size())
print(test_outputs.data.size())
print(gt_pts.size())

**gives the following error:**

RuntimeError                              Traceback (most recent call last)
<ipython-input-10-07f935a80088> in <module>()
      1 # call the above function
      2 # returns: test images, test predicted keypoints, test ground truth keypoints
----> 3 test_images, test_outputs, gt_pts = net_sample_output()
      4 
      5 # print out the dimensions of the data to see if they make sense

<ipython-input-8-d706d278b7b4> in net_sample_output()
     24 
     25         # forward pass to get net output
---> 26         output_pts = net(images)
     27 
     28         # reshape to batch_size x 68 x 2 pts

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~\udacity\P1_Facial_Keypoints\models.py in forward(self, x)
     72         ## Conv layers
     73 
---> 74         x = self.pool(F.elu(self.conv1(x)))
     75         x = self.dropout1(x)
     76         #if log:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\pooling.py in forward(self, input)
    140         return F.max_pool2d(input, self.kernel_size, self.stride,
    141                             self.padding, self.dilation, self.ceil_mode,
--> 142                             self.return_indices)
    143 
    144 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\functional.py in max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode, return_indices)
    394     See :class:`~torch.nn.MaxPool2d` for details.
    395     """
--> 396     ret = torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
    397     return ret if return_indices else ret[0]
    398 

RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at c:\new-builder_2\win-wheel\pytorch\aten\src\thcunn\generic/SpatialDilatedMaxPooling.cu:152

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

C:\Users\vpokala\AppData\Local\Continuum\anaconda3\Lib\site-packages
(base) λ python collect_env.py
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 7 Professional
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: Quadro M2000M
Nvidia driver version: 385.54
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     0.4.1<pip>
[conda] torchvision               0.2.1<pip>

**Comment by peterjc123** [comment]
@theja2289 No, you don't need to. Just wait for a few hours. I'm in the process of rebuilding the CUDA packages. Sorry for the inconveniences.

**Comment by theja2289** [comment]
No worries @peterjc123 , thanks for responding so fast :)

**Comment by theja2289** [comment]
I even tried to build from source, getting this error while building from source no idea why the slash is different.
![image](https://user-images.githubusercontent.com/10782347/43510879-d97af466-952b-11e8-957c-c86ee62cddbd.png)

![image](https://user-images.githubusercontent.com/10782347/43510947-01f8f334-952c-11e8-8375-1d9c86402594.png)

**Comment by peterjc123** [comment]
@theja2289 No, it is not related to the error. The real error is that the program cannot find `cl.exe`. I don't know how you activated the environment. You should build the binaries in `x64 Native Tools Command Prompt for VS 2017`.

**Comment by theja2289** [comment]
Attached the output from the build, could you please let me know if this build went through correctly.
I used 
```
set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1

call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.14
python setup.py install
```

[output.txt](https://github.com/pytorch/pytorch/files/2248878/output.txt)

![image](https://user-images.githubusercontent.com/10782347/43513827-9e06d974-9533-11e8-967b-c834aec6dcb5.png)

**Comment by theja2289** [comment]
It looks like it's related to issue #10094, reverted back 0.4.0 and it resolves the issue.

**Comment by soumith** [comment]
The new binaries are updated for Windows.

If you have previously installed via anaconda, you have to do:

```
conda uninstall -y pytorch
conda clean -t -y
```

and then reinstall pytorch.


If you have installed via `pip` command on https://pytorch.org, first uninstall pytorch via `pip uninstall torch` and then rerun that command (so that the new wheel is downloaded and installed)
