### ISSUE TITLE
Unknow error when using `make_graphed_callables`

### ISSUE THREAD

**Issue by ftxj** [pytorch/pytorch#102830]
### 🐛 Describe the bug

When I try to run the following code, 
```python
import torch

def test_func(t1: torch.Tensor, t2: torch.Tensor):
    return t1 + t2

r1 = torch.randn([1, 4, 8, 3, 3]).to('cuda')
r2 = torch.randn([1, 4, 8, 3, 3]).to('cuda')
tmp = torch.randn([1, 4, 8, 2]).to('cuda').requires_grad_()
r2[..., 1, 1] = tmp[..., 1]

cudagraph_func = torch.cuda.make_graphed_callables(test_func, (r1, r2))
```

I got the error msg:
```
    result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: operation would make the legacy stream depend on a capturing blocking stream
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Versions

PyTorch version: 2.0.0a0+1767026
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-131-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY

**Comment by ngimel** [comment]
Do all the work before the graph capture on the side stream.

**Comment by ftxj** [comment]
What does "do all the work" and "side stream" here? Does this error a bug, or just incorrectly using by myself?

**Comment by ftxj** [comment]
> Do all the work before the graph capture on the side stream.

Thanks! It works!
