### ISSUE TITLE
torch.cuda.is_available() returns False on GTX 1650 with cuda 11.7 and torch==2.0.0+cpu

### ISSUE THREAD

**Issue by hairlinebrockeb** [pytorch/pytorch#102936]
### 🐛 Describe the bug

i get False when i run torch.cuda.is_available() 

nvidia-smi
**+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  | 00000000:01:00.0  On |                  N/A |
| 30%   39C    P0              15W /  75W |   1145MiB /  4096MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+**

i even installed 11.7 and it still shows 12.2

when i run pip show torch it gives me version 2.0.1 + cu117 which is why i installed cuda 11.7 but i previously had 12.2
**C:\Users\ambsu>pip show torch
Name: torch
Version: 2.0.1+cu117**

py -m torch.utils.collect_env
gives 
**Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.0+cpu
[pip3] torchaudio==2.0.2+cu118
[pip3] torchvision==0.15.2
[conda] Could not collect**

everything is showing different versions

### Error logs

**Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.0+cpu
[pip3] torchaudio==2.0.2+cu118
[pip3] torchvision==0.15.2
[conda] Could not collect**

nvidia-smi
**+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  | 00000000:01:00.0  On |                  N/A |
| 30%   39C    P0              15W /  75W |   1145MiB /  4096MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+**

### Minified repro

import torch

print(torch.cuda.is_available()) # False

### Versions

cuda 11.7 gtx
torch 2.0.1 and 2.0.0

**Comment by skudtarkar16** [comment]
Did you find any solution? I have exact same issue as yours.

**Comment by hairlinebrockeb** [comment]
no

**Comment by hairlinebrockeb** [comment]
i literally have cuda 11.7 and torch 2.0.1+cu117 and its not working
this shit is bugged

**Comment by hairlinebrockeb** [comment]
>>> import torch
>>> torch.__version__
'2.0.0+cpu'
>>> exit()

C:\Users\ambsu\Downloads\fnticks>pip uninstall torch
Found existing installation: torch 2.0.1+cu117

**Comment by janeyx99** [comment]
The problem here is probably due to the fact that the installed torch is for CPU and not for CUDA. Could you retry using the install commands on https://pytorch.org/get-started/locally/ with the CUDA version you have?

**Comment by SnowyField1906** [comment]
it worked for me when upgrading my NVIDIA driver then running this command line `pip install torchaudio torch==2.0.1+cu118 torchvision ninja --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu118 --user`

**Comment by DrMohsenRezaei** [comment]
> it worked for me when upgrading my NVIDIA driver then running this command line `pip install torchaudio torch==2.0.1+cu118 torchvision ninja --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu118 --user`

yes exactly, I will install different command but just above command make it correct, thanke you friend.

**Comment by jeb2112** [comment]
I've got the GTX 1650 and had a similar problem. I had installed pytorch 2.2.0 and cuda-12.2 by default via the setup.py of a new python package I wanted to use, but it wouldn't detect the GPU. Meanwhile, I had this other much older working pytorch env way back at 1.5.1 and cuda 9.2, which now suddenly became broken and wouldn't detect the gpu. But I also had a working tensorflow env at 2.15 and cuda 12.2, that suddenly now was broken and wouldn't detect the GPU. It's embarrassing to say this, but after rebooting these errors cleared up. I don't expect anyone else to stumble upon this exact combination of cause and effects, but I'm posting just in case.
