### ISSUE TITLE
cuda runtime error(59): device-side assert when running torch.topk

### ISSUE THREAD

**Issue by Ai-is-light** [pytorch/pytorch#10303]
The code and dataset were the same as before, but I got the following error. However they could work well about a half mouth ago.
the pytorch's version is 0.3.1, BUT I find the version 0.4.0 also meeting with the same error
raceback (most recent call last):
File "main.py", line 341, in
main()
File "main.py", line 141, in main
train(train_loader, model, criterion, optimizer, epoch)
File "main.py", line 192, in train
prec1, prec5 = accuracy(output.data, target, topk=(1,5))
File "main.py", line 329, in accuracy
_, pred = output.topk(maxk, 1, True, True)
RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/torch/lib/THC/generic/THCTensorTopK.cu:21
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion t >= 0 && t < n_classes failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [1,0,0] Assertion t >= 0 && t < n_classes failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [2,0,0] Assertion t >= 0 && t < n_classes failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [3,0,0] Assertion t >= 0 && t < n_classes failed.
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.c line=184 error=59 : device-side assert triggered
terminate called after throwing an instance of 'std::runtime_error'
what(): cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCStorage.c:184
Aborted (core dumped)

**Comment by zou3519** [comment]
Looks like topk is failing? Could you please post a minimal reproducible example as well as let us know what pytorch version you're using? We fixed a few topk bugs recently.

**Comment by Ai-is-light** [comment]
@zou3519 Thanks! Looking forward to your any replies.
The code and dataset were the same as before, but I got the following error. However they could work well about a half mouth ago.
the pytorch's version is 0.3.1, BUT I find the version 0.4.0 also meeting with the same error
raceback (most recent call last):
File "main.py", line 341, in 
main()
File "main.py", line 141, in main
train(train_loader, model, criterion, optimizer, epoch)
File "main.py", line 192, in train
prec1, prec5 = accuracy(output.data, target, topk=(1,5))
File "main.py", line 329, in accuracy
_, pred = output.topk(maxk, 1, True, True)
RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/torch/lib/THC/generic/THCTensorTopK.cu:21
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion t >= 0 && t < n_classes failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [1,0,0] Assertion t >= 0 && t < n_classes failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [2,0,0] Assertion t >= 0 && t < n_classes failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [3,0,0] Assertion t >= 0 && t < n_classes failed.
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.c line=184 error=59 : device-side assert triggered
terminate called after throwing an instance of 'std::runtime_error'
what(): cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCStorage.c:184
Aborted (core dumped)

**Comment by zou3519** [comment]
Oh I see. The assert is actually in NLLLoss. The problem is that there exists some target value in your `target` tensor that is not in the range [0, n_classes). Could you assert this in your code and see if that assert is triggered?

**Comment by Ai-is-light** [comment]
Thanks for your advice.
I will check it

**Comment by soumith** [comment]
closing via https://github.com/pytorch/pytorch/issues/10303#issuecomment-411853972

**Comment by KasperJuunge** [comment]
I kind of had the same problem. I was trying to modify the transfer learning tutorial (https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html) with the hymenoptera dataset (bees and ants dataset) to make it fit to my project. The problem was that i had 3 classes and the tutorial has 2.  So i found that you have to define the number of outputs from the fully connected network (the output layer). So the only thing i had to do was changing "model_ft.fc = nn.Linear(num_ftrs, 2)" to "model_ft.fc = nn.Linear(num_ftrs, 3)". Hope it helps somebody :)

**Comment by JustusWest** [comment]
@KasperJuunge that fixed my code! Thanks so much for your comment
