### ISSUE TITLE
Different results when using function argmax or argmin for data type ".cuda()" and ".cpu()"

### ISSUE THREAD

**Issue by heylfda** [pytorch/pytorch#10370]
## Issue description

I got different results when using the function argmax, for the tensor like this. This tensor has shape (3, 4). **I want to get the place which the first "1" apperence.** But I got different results when using cuda tensor and cpu tensor. And I got this difference when using version 0.4.0, then I change to 0.4.1, but this difference still exists.
The input tensor:
```
1, 1, 1, 1
0, 1, 1, 1
1, 1, 1, 1
```
And I want the output like this, and it done when using cpu:
```
0
1
0
```
But got this when using cuda:
```
0
2
0
```

## Code example
using cpu:
```
Input:
t = torch.ones(3, 4).cpu()
t[1, 0] = 0
print(t.argmax(1, keepdim=True))
Out:
tensor([[0],
        [1],
        [0]])
```

using cuda:
```
Input:
t = torch.ones(3, 4).cuda()
t[1, 0] = 0
print(t.argmax(1, keepdim=True))
Out:
tensor([[0],
        [2],
        [0]], device='cuda:0')
```

## System Info
```
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.2 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/local/MATLAB/R2016b/bin/glnxa64/libcudnn.so.4.0.7
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] msgpack-numpy (0.4.1)
[pip3] numpy (1.13.3)
[pip3] torch (0.4.0)
[pip3] torchfile (0.1.0)
[pip3] torchvision (0.1.9)
[conda] pytorch                   0.4.1           py35_cuda9.0.176_cudnn7.1.2_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.2.1                    py35_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
```

**Comment by zou3519** [comment]
This is expected because we do not guarantee stable reductions. It makes sense to optimize GPU code differently from CPU code, resulting in edge cases like this.

We should add some extra docs explaining this though (maybe a CUDA gotchas section).

**Comment by krishnakalyan3** [comment]
@zou3519 can you please let me know where I could add this section in the docs?

Maybe 
https://pytorch.org/docs/stable/notes/cuda.html# 
Adding a gotchas section here?

**Comment by simonm3** [comment]
I note that on CPU pytorch argmax gets the last value found whereas numpy argmax gets the first value found. On GPU they seem to be the same. I would guess there is no big speed up either way in which case would be good to be consistent with numpy.

e.g.

> a=[1,2, 99, 99]
> np.argmax(a), torch.argmax(torch.Tensor(a))

(2, tensor(3))

> a=[1,2, 99, 99]
> np.argmax(a), torch.argmax(torch.Tensor(a).cuda())

(2, tensor(2, device='cuda:0'))

**Comment by bgoodman44** [comment]
Should note that the numpy documentation explicitly states that the first index of occurrence will be returned:

> Notes
> 
> In case of multiple occurrences of the maximum values, the indices corresponding to the first occurrence are returned.

https://docs.scipy.org/doc/numpy-1.16.1/reference/generated/numpy.argmax.html?highlight=argmax#numpy.argmax

Any effecient work-arounds to get the first index that people have devised?

**Comment by chia-an** [comment]
> I note that on CPU pytorch argmax gets the last value found whereas numpy argmax gets the first value found.

If the function always gives the index of the last maximum value, then flipping the tensor along the given dimension before calling argmax should give the index (after flipping) of the first maximum value. This is the work-around I use in my case.

E.g.
```
x = [[1, 4, 4, 3], [5, 5, 2, 5]]
n = 4  # the size of the dimension where we want to take the argmax

# Need to map the flipped indexs to the original ones.
n - 1 - torch.tensor(x).flip(dims=(1,)).argmax(dim=1)
```
Output: `tensor([1, 0])`

```
x = [[1, 4, 4, 3], [5, 5, 2, 5]]
np.argmax(np.array(x), axis=1)
```
Output: `array([1, 0])`

**Comment by VitalyFedyunin** [comment]
Note: as PyTorch doesn't support negative strides at this moment, `flip` operation makes the full copy of Tensor and might affect performance.

**Comment by choidongyeon** [comment]
I would like to work on this issue. Just to confirm - it seems that in the most recent version, the CPU and CUDA version values match but point to the last argmax/min instance, rather than the first. We would want the indices of the first instance, right?

**Comment by VitalyFedyunin** [comment]
Yes, we would love to have similar to numpy behavior. but without sacrificing performance

**Comment by mruberry** [comment]
This is now fixed! Both the CPU and CUDA argmin/argmax should now return the FIRST minimum/maximum, consistent with NumPy.
