### ISSUE TITLE
Frequent HSDP Distributed Checkpointing leads to GPU OOM Errors

### ISSUE THREAD

**Issue by supriyogit** [pytorch/pytorch#103884]
### 🐛 Describe the bug

Periodic HSDP checkpointing of model, optimizer, and data loader states is causing an increase in both
(1) Reserved (tracked using: torch.cuda.memory_reserved(device=torch.cuda.current_device())) and
(2) Allocated (tracked using: torch.cuda.memory_allocated(device=torch.cuda.current_device()))
GPU memory usage. The memory requirements do not go down even after the checkpoint has been written and over a period of time leads to OOM errors. 

To analyze the issue we performed GPU memory profiling of HSDP checkpointing using a 3B parameter decoder model with and without checkpointing:

GPU Memory Profile of the 3B parameter decoder model (using HSDP on 4 GPUs) is shown below. 

Memory usage is held steady throughout the 100 steps of training.
![3b_hsdp_nockp_mem_profile](https://github.com/pytorch/pytorch/assets/110467/ed574a1b-a44a-4a29-8026-cd68ef4100b1)

However, with checkpointing (every 5 steps) the memory usage changes as shown below. You can observe an increase of roughly 10GB in reserved memory and about 3.66GB in the allocated memory.
![3b_hsdp_fsdp_mem_profile_with_ckp_wstate](https://github.com/pytorch/pytorch/assets/110467/cc8c3856-b0c0-4cd8-b3c6-ff23c4bcb5f3)

For DCP writing, we use the following to get the model and optimizer states:

```
with FSDP.state_dict_type(
                        model,
                        StateDictType.SHARDED_STATE_DICT,
                ):
                    model_state = model.state_dict()
                    optim_state = FSDP.sharded_optim_state_dict(model, optimizer, group=shard_group)
```
Fix 1: We observed that the `model_state` and `optim_state `were not references to the actual states but there was some copying involved. So, we performed active memory management by deleting the states (model, opt, and loader) after writing the checkpoint. This helped reduce the allocated memory after completion of checkpoint writing. However, the reserved memory continues to grow as shown in the plot  below. Note, we do torch.cuda.empty_cache() once before the start of training.

![3b_hsdp_fsdp_mem_profile_with_ckp](https://github.com/pytorch/pytorch/assets/110467/182c5390-cf55-4171-a18c-2c9ed553e7f3)

Checkpoint writing is performed using:
```
state_dict = {
            'model_state': model_state,
            'optimizer_state': optimizer_state,
        }
 save_state_dict(state_dict=state_dict, storage_writer=writer, process_group=process_group, planner=DefaultSavePlanner())
```

### Versions

Python nightlies.

cc @zhaojuanmao @mrshenli @rohan-varma @awgu

**Comment by fegin** [comment]
@supriyogit Can you confirm 2 things for the debugging purpose? 1) Does FSDP have the same issue? 2) If we skip the optimizer state_dict save (not calling optimizer state_dict at all), does the same issue happen?

**Comment by supriyogit** [comment]
@fegin Setting the following environment for controlling the behavior of the caching memory allocator:
```
import os
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'
```
seems to have stopped the growth of the reserved memory. 
![3b_hsdp_with_fix_ckp](https://github.com/pytorch/pytorch/assets/110467/77be0b3b-8056-45f2-aab5-a0c930af0136)

I am monitoring a 3B parameter model training run. After writing about 40 checkpoints the reserved memory is still held at a constant value.

**Comment by lessw2020** [comment]
@fegin - I recommended they try expandable segments for the Cuda Caching Allocator.  (looks like @supriyogit already posted the code I sent above). 
This appears to have resolved this issue - it means the checkpointing was likely in an N+1 allocation cycle, and thus res memory was steadily growing. 
Will double check if anything else is needed here but this is close to being resolved.

**Comment by lessw2020** [comment]
I queried IBM / @supriyogit if anything else outstanding on this w/ no response via slack, so looks like this issue is resolved.
"After writing about 40 checkpoints the reserved memory is still held at a constant value."

The fix was to enable expandable segments for the PT Cuda Caching Allocator via above code snippet.  Expandable segments helps deal with issues related to N+1 size allocation cycles. 
This isn't a specific issue with PT dist checkpointing so no follow up needed on dist side.

Hopefully expandable segments will soon be the default, so no need to manually enable in future.

**Comment by supriyogit** [comment]
Tested the above fix also on 3B parameter model using FSDP. The reserved memory stays fairly constant over 250 steps (or 25 ckp writes).
![3b_fsdp_with_fix_ckp](https://github.com/pytorch/pytorch/assets/110467/918b5be9-076f-4636-802d-9a85317ecb5e)
