### ISSUE TITLE
Tensor to_sparse fails on large matrices

### ISSUE THREAD

**Issue by elexunix** [pytorch/pytorch#104107]
### 🐛 Describe the bug

```>>> import torch
>>> torch.randn(46000, 46000, device='cuda:3').to_sparse()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.```

### Versions

```Collecting environment information...                                                                                                                                                                              
PyTorch version: 1.13.0a0+936e930                                                                                                                                                                            
Is debug build: False                                                                                                                                                                                              
CUDA used to build PyTorch: 11.8                                                                                                                                                                                   
ROCM used to build PyTorch: N/A                                                                                                                                                                                    
                                                                                                                                                                                                                   
OS: Ubuntu 20.04.5 LTS (x86_64)                                                                                                                                                                                    
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0                                                                                                                                                                 
Clang version: Could not collect                                                                                                                                                                                   
CMake version: version 3.24.1      
Libc version: glibc-2.31                                                                                 
                                                    
Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.111-14-x86_64-with-glibc2.29
Is CUDA available: True               
CUDA runtime version: 11.8.89           
CUDA_MODULE_LOADING set to: LAZY        
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0  
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0                                               
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0                                                
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0                                                                                                                                                              
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:                                                                                                                                                                                                               
Architecture:                    x86_64                                                                                                                                                                            
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          54
On-line CPU(s) list:             0-53
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       54
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7662 64-Core Processor
Stepping:                        0
CPU MHz:                         1996.014
BogoMIPS:                        3992.02
Virtualization:                  AMD-V
L1d cache:                       3.4 MiB
L1i cache:                       3.4 MiB
L2 cache:                        27 MiB
L3 cache:                        864 MiB
NUMA node0 CPU(s):               0-53
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_
tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch 
osvw perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr wbnoinvd arat npt nrip_save umip rdpid arch
_capabilities

Versions of relevant libraries:
[pip3] functorch==1.13.0a0+936e930
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.22.2
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.13.0a0+936e930
[pip3] torch-tensorrt==1.3.0a0
[pip3] torchtext==0.13.0a0+fae8e8c
[pip3] torchvision==0.15.0a0
[conda] Could not collect```

**Comment by alexsamardzic** [comment]
On a quick look, it seems to me that the problem occurs in `nonzero_cuda_out_impl()` function, in `aten/src/ATen/native/cuda/Nonzero.cu`.  In particular, invalid memory access is reported by `cub::DeviceReduce::Sum` call there.  Apparently, CUB reductions use 32-bit integer for size of array that reduction is applied to. This array here is array of values of original dense tensor, and its size is $46000^2= 2116000000$, that is close to `INT_MAX` so maybe CUB is having some kind of issue with reductions over that big arrays.

**Comment by alexsamardzic** [comment]
Issue [reported](https://github.com/NVIDIA/cub/issues/726) to CUB repo, minimal reproducible example posted there.

**Comment by alexsamardzic** [comment]
Apparently the problem is fixed in the CUB in the meantime, so now it should be about updating CUB in the PyTorch source tree.

**Comment by elexunix** [comment]
So will it work in this concrete case (where 46k^2 is close to int_max) or even when n^2 > int_max?

**Comment by elexunix** [comment]
Then it is probably not important, since 47k^2 is already > `INT_MAX`, and with 45k^2 it works..
Is there any plan to switch to int64_t in CUB in future?
It seems like it doesn't work even when there are no nonzero elements:
```
>>> torch.sparse_coo_tensor([[], []], [], (50000, 50000), device='cuda').nonzero()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NotImplementedError: Could not run 'aten::nonzero' with arguments from the 'SparseCUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::nonzero' is only available for these backends: [CPU, CUDA, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

CPU: registered at aten/src/ATen/RegisterCPU.cpp:31034 [kernel]
CUDA: registered at aten/src/ATen/RegisterCUDA.cpp:43986 [kernel]
BackendSelect: fallthrough registered at ../aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:144 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ../aten/src/ATen/functorch/DynamicLayer.cpp:491 [backend fallback]
Functionalize: registered at ../aten/src/ATen/FunctionalizeFallbackKernel.cpp:280 [backend fallback]
Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ../aten/src/ATen/ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ../aten/src/ATen/native/NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at ../aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:63 [backend fallback]
AutogradOther: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradCPU: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradCUDA: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradHIP: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradXLA: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradMPS: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradIPU: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradXPU: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradHPU: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradVE: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradLazy: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradMeta: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradMTIA: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradPrivateUse1: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradPrivateUse2: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradPrivateUse3: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradNestedTensor: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
Tracer: registered at ../torch/csrc/autograd/generated/TraceType_0.cpp:16728 [kernel]
AutocastCPU: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:487 [backend fallback]
AutocastCUDA: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:354 [backend fallback]
FuncTorchBatched: registered at ../aten/src/ATen/functorch/BatchRulesDynamic.cpp:64 [kernel]
FuncTorchVmapMode: fallthrough registered at ../aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at ../aten/src/ATen/LegacyBatchingRegistrations.cpp:1073 [backend fallback]
VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ../aten/src/ATen/functorch/TensorWrapper.cpp:210 [backend fallback]
PythonTLSSnapshot: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:152 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ../aten/src/ATen/functorch/DynamicLayer.cpp:487 [backend fallback]
PythonDispatcher: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:148 [backend fallback]
```

**Comment by alexsamardzic** [comment]
> Then it is probably not important, since 47k^2 is already > `INT_MAX`, and with 45k^2 it works.. Is there any plan to switch to int64_t in CUB in future? 

This is a question for CUB team.  According to the comments [here](https://github.com/NVIDIA/cub/issues/584) it seems it is considered.

> It seems like it doesn't work even when there are no nonzero elements:
>  ...

Not sure about reasoning behind `nonzero()` being not implemented for sparse tensors, maybe someone else of sparse maintainers could provide a hint.

**Comment by amjames** [comment]
> Not sure about reasoning behind `nonzero()` being not implemented for sparse tensors, maybe someone else of sparse maintainers could provide a hint.


No particularly important reason why `nonzero()` is not implemented. It is a bit more complicated than in seems on the surface as the sparse tensor's `nnz` atributue tracks the number of materialized values, some of which may be zero, but the end result would be to forward the `nonzero()` call onto values which would give the correct answer under the sparse-dense conversion equivalence principle, that is `sparse.nonzero() == sparse.to_dense().nonzero()`. 

The main reason it does not have an implementation is that we have not needed and implementation of it, and there has not been a user request for it. 

I don't think that it's addition would resolve the issue at hand though, the nonzero call causing the originally reported error is not dispatched from a sparse `self` it is called in the `to_sparse()` transformation  and dispatched to the dense kernal from the dense `self` which we are attempting to convert to a sparse layout.
