### ISSUE TITLE
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Hzzhang-nlp** [pytorch/pytorch#104259]
### 🐛 Describe the bug

import torch，then:
import torch，then:

### Versions

import torch，then:
![image](https://github.com/pytorch/pytorch/assets/39661319/561c5a45-8396-4377-ae8e-2b483825bc34)

**Comment by Hzzhang-nlp** [comment]
torch2.0.1

**Comment by malfet** [comment]
@Hzzhang-nlp please run `python3 -mtorch.utils.collect_env` and report results here.
Also, what Linux flavor are you using?

**Comment by td-anne** [comment]
I receive the same error in what appears to be the same circumstances:

In a fresh virtualenv, I follow the instructions on the web:
```
$ pip install torch torchvision
```
I then try
```python
import torch
```
only to receive
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anne/.cache/pypoetry/virtualenvs/transformers-test-hTrBSg_k-py3.8/lib/python3.8/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
```

Unfortunately, because `torch` cannot be imported, `torch.utils.collect_env` cannot be imported either, with the same error message.

Very likely there is some piece of compiled binary code missing on my system, that would be necessary to run these wheels. If the installation instructions told me what it was I would be happy to install it. The system is an Ubuntu 20.04.6 system, It does appear to have the CUDA development packages installed, but not `libcudnn`. Presumably this is needed? (Or `libcudnn-dev`?)

I realize that it's probable that PyTorch cannot be made to work without some particular version of some particular binary non-python library. I would appreciate some guidance in the install instructions on how to resolve this (what library? what version?) or at least some indication that binary libraries are going to be needed.

**Comment by Hzzhang-nlp** [comment]
Okay, have you solved your problem?

**Comment by ptrblck** [comment]
> It does appear to have the CUDA development packages installed, but not libcudnn. Presumably this is needed? (Or libcudnn-dev?)

No, since the PyTorch binaries either ship with the required dependencies directly (e.g. if you install the nightly binary) or pull the dependencies.

`pip install torch` will pull the required CUDA libraries in a new and empty virtual environment:
```python
pip list | grep torch
(tmp) pbialecki@ptrblck-srv:~$ pip install torch
Collecting torch
  Downloading torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl (619.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 58.4 MB/s eta 0:00:00
...
Collecting nvidia-cudnn-cu11==8.5.0.96 (from torch)
  Downloading nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (557.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 58.5 MB/s eta 0:00:00
Collecting nvidia-cublas-cu11==11.10.3.66 (from torch)
  Downloading nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 58.5 MB/s eta 0:00:00
...
Successfully installed MarkupSafe-2.1.3 cmake-3.26.4 filelock-3.12.2 jinja2-3.1.2 lit-16.0.6 mpmath-1.3.0 networkx-3.1 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-cupti-cu11-11.7.101 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 nvidia-cufft-cu11-10.9.0.58 nvidia-curand-cu11-10.2.10.91 nvidia-cusolver-cu11-11.4.0.1 nvidia-cusparse-cu11-11.7.4.91 nvidia-nccl-cu11-2.14.3 nvidia-nvtx-cu11-11.7.91 sympy-1.12 torch-2.0.1 triton-2.0.0 typing-extensions-4.7.0
```
Smoke test:
```
(tmp) pbialecki@ptrblck-srv:~$ python -c "import torch; print(torch.__version__); print(torch.backends.cudnn.version())"
2.0.1+cu117
8500

(tmp) pbialecki@ptrblck-srv:~$ ls /home/pbialecki/miniforge3/envs/tmp/lib/python3.10/site-packages/nvidia/cudnn/lib/
__init__.py              libcudnn_adv_train.so.8  libcudnn_cnn_train.so.8  libcudnn_ops_train.so.8  __pycache__
libcudnn_adv_infer.so.8  libcudnn_cnn_infer.so.8  libcudnn_ops_infer.so.8  libcudnn.so.8
```
As you can see cuDNN is downloaded from PyPI and the libraries are installed into the `tmp` virtual environment.

**Comment by Hzzhang-nlp** [comment]
> @Hzzhang-nlp please run `python3 -mtorch.utils.collect_env` and report results here. Also, what Linux flavor are you using?

![image](https://github.com/pytorch/pytorch/assets/39661319/7d3dca0f-2c12-4a5a-b3cc-b24ee4871f22)

**Comment by Hzzhang-nlp** [comment]
but torch<2.0,can be successed!

![image](https://github.com/pytorch/pytorch/assets/39661319/6b88d1c8-4fd0-4cd2-aae9-a33d4d8fdf41)

**Comment by softmare** [comment]
I had experienced the same error in virtual envirenment using poetry when I try to import torch 2.0.1 version.
After I found this page, I tried importing torch 2.0.1 without virtual env and it worked.
And poetry venv with torch 1.13.1 also worked well.

Following is my ```-mtorch.utils.collect_env``` output outside of venv.
```
$ python3 -mtorch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Pop!_OS 22.04 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1070
Nvidia driver version: 525.116.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 3 3300X 4-Core Processor
CPU family:                      23
Model:                           113
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     4349.2178
CPU min MHz:                     2200.0000
BogoMIPS:                        7585.91
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
Virtualization:                  AMD-V
L1d cache:                       128 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        2 MiB (4 instances)
L3 cache:                        16 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] torch==2.0.1
[conda] Could not collect
```

**Comment by jloveric** [comment]
Seeing the same issue on Ubuntu 23.04 - currently using poetry.

**Comment by bm371613** [comment]
I'm facing the same or very similar issue. If I install the latest torch (2.0.1) with `poetry add`, some `.so` files are missing. If I use `pip install` or `poetry add torch==2.0.0`, it works.

I don't have the python packaging expertise to be sure whether I should blame poetry or torch, but I suppose it is torch.

I reproduced the problem with this Dockerfile

```
FROM python:3.10
ARG DEPENDENCY
RUN pip install poetry==1.5.1  # latest
RUN poetry new -n --name project /project
WORKDIR /project
RUN poetry add $DEPENDENCY
RUN poetry run python -m torch.utils.collect_env
```
and commands
- `docker build --no-cache --build-arg DEPENDENCY='torch==2.0.0' .` (good)
- `docker build --no-cache --build-arg DEPENDENCY='torch==2.0.1' .` (bad)

With 2.0.0, the `poetry add` output contains

```
Package operations: 22 installs, 0 updates, 0 removals

  • Installing cmake (3.27.2)
  • Installing filelock (3.12.2)
  • Installing lit (16.0.6)
  • Installing markupsafe (2.1.3)
  • Installing mpmath (1.3.0)
  • Installing jinja2 (3.1.2)
  • Installing networkx (3.1)
  • Installing nvidia-cublas-cu11 (11.10.3.66)
  • Installing nvidia-cuda-cupti-cu11 (11.7.101)
  • Installing nvidia-cuda-nvrtc-cu11 (11.7.99)
  • Installing nvidia-cuda-runtime-cu11 (11.7.99)
  • Installing nvidia-cudnn-cu11 (8.5.0.96)
  • Installing nvidia-cufft-cu11 (10.9.0.58)
  • Installing nvidia-curand-cu11 (10.2.10.91)
  • Installing nvidia-cusolver-cu11 (11.4.0.1)
  • Installing nvidia-cusparse-cu11 (11.7.4.91)
  • Installing nvidia-nccl-cu11 (2.14.3)
  • Installing nvidia-nvtx-cu11 (11.7.91)
  • Installing sympy (1.12)
  • Installing triton (2.0.0)
  • Installing typing-extensions (4.7.1)
  • Installing torch (2.0.0)
```

wheras with `2.0.1` it's only

```
Package operations: 8 installs, 0 updates, 0 removals

  • Installing markupsafe (2.1.3)
  • Installing mpmath (1.3.0)
  • Installing filelock (3.12.2)
  • Installing jinja2 (3.1.2)
  • Installing networkx (3.1)
  • Installing sympy (1.12)
  • Installing typing-extensions (4.7.1)
  • Installing torch (2.0.1)
```

and the last command fails with `OSError: libcurand.so.10: cannot open shared object file: No such file or directory`.

**Comment by bm371613** [comment]
related issue https://github.com/pytorch/pytorch/issues/105731

**Comment by Kurt-von-Laven** [comment]
@bm371613, that looks right to me. RolnickLab/ami-ml#8 arrived at the same conclusion, and that was my instinct as well.

**Comment by lewisbails** [comment]
Doesn't look like the issue was resolved in time for 2.1.0

```
$ curl -s  https://pypi.org/pypi/torch/2.1.0/json | jq '.info.requires_dist[]' -r
filelock
typing-extensions
sympy
networkx
jinja2
fsspec
opt-einsum (>=3.3) ; extra == 'opt-einsum'
```

**Comment by jhirschibar** [comment]
`poetry add` provides dependency packages, but not the cudnn runtime binaries. So after running `poetry add torch`, I manually `pip uninstall torch` and then `pip install torch` again. 

Torch then successfully imports and CUDA is available.

**Comment by gbpoole** [comment]
Any update on this?  Would be good to know that it'll be addressed for the next release.

**Comment by koder-ua** [comment]
Still get this issue with pip and torch 2.1.2

**Comment by alihassanijr** [comment]
This might not apply to everyone, but I hit this issue trying to install a different version of PyTorch locally while I had another version of PyTorch installed system-wide, with all the dependencies.

I just had the idea that I'd do the same for CUDNN, and it worked. Can't speak to why it worked though; I don't know how cudnn is being linked here, but what I did notice is that my docker image already had a cuda toolkit installed systemwide, and it included your average cuBLAS, and cuFFT, but not cuDNN. However, the system-wide torch which was installed through pypi had picked up all the nvidia dependencies, including cuDNN. It's almost as if python refused to link the system-wide pypi channel libcudnn and only picked up the local pypi channel cudnn.

Anyways, this is what did it for me:

```
pip3 install -U nvidia-cudnn-cu12==8.9.7.29
```

but only because the system-wide cudnn was a different version. It might be different for everyone else here.

**Comment by Aedelon** [comment]
Same problem but it works with torch 1.13.1

**Comment by codenoid** [comment]
If you are using 22.04, try this 

```bash
sudo apt install nvidia-cudnn
```

**Comment by wangly0276** [comment]
You can try to reinstall torch again after installing all the installation packages of the model.

**Comment by liujf69** [comment]
similar issue when using torch 2.0.1
Traceback (most recent call last):
  File "/usr/local/conda/bin/torchrun", line 5, in <module>
    from torch.distributed.run import main
  File "/home/hadoop-waimai-aigc/.local/lib/python3.9/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

**Comment by zchuz** [comment]
I encountered a similar issue on Ubuntu 22.04.
Copying libcudnn.so.8 to the PyTorch installation directory resolved the problem.

```
cp /xxxx/libcudnn.so.8  /xxxx/anaconda3/envs/your_env_name/lib/your_python_version/site-packages/torch/lib/

```

**Comment by alexlyzhov** [comment]
Same problem with poetry and torch, I wasted a lot of time with this...

I tried `poetry add torch==2.0.0` and it finally worked, but versions above that such as 2.1.0, 2.2.0, 2.3.0 all resulted in this error.

The version of poetry is 1.8.2

**Comment by amit9oct** [comment]
> This might not apply to everyone, but I hit this issue trying to install a different version of PyTorch locally while I had another version of PyTorch installed system-wide, with all the dependencies.
> 
> I just had the idea that I'd do the same for CUDNN, and it worked. Can't speak to why it worked though; I don't know how cudnn is being linked here, but what I did notice is that my docker image already had a cuda toolkit installed systemwide, and it included your average cuBLAS, and cuFFT, but not cuDNN. However, the system-wide torch which was installed through pypi had picked up all the nvidia dependencies, including cuDNN. It's almost as if python refused to link the system-wide pypi channel libcudnn and only picked up the local pypi channel cudnn.
> 
> Anyways, this is what did it for me:
> 
> ```
> pip3 install -U nvidia-cudnn-cu12==8.9.7.29
> ```
> 
> but only because the system-wide cudnn was a different version. It might be different for everyone else here.

This worked for me. Even when this version was flagged incompatible by `pip`

**Comment by tejuafonja** [comment]
>pip  install -U nvidia-cudnn-cu12==8.9.7.29

This worked for me too (even with the flag)
`torch 2.3.1 requires nvidia-cudnn-cu12==8.9.2.26; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 8.9.7.29 which is incompatible.`

**Comment by fkxxyz** [comment]
I've encountered a similar issue, which was caused by manually uninstalling pytorch dependencies.
Uninstall all nvidia related packages and reinstall, it worked

```
pip uninstall torch $(pip list | grep nvidia- | cut -d' ' -f1 | xargs)
pip install torch --index-url https://download.pytorch.org/whl/cu117
```

**Comment by Metal079** [comment]
getting a similar issue in ubuntu running on wsl2, ive tried all the fixes here with no luck

**Comment by felso** [comment]
I have the same issue on Fedora 40. My workaround was to create a symlink for the Nvidia directory that contains the headers.

From the root of the project run the following command:

```
ln -s ../../../lib/python3.12/site-packages/nvidia .venv/lib64/python3.12/site-packages/nvidia
```

**Comment by felso** [comment]
I think I know what's going on. My project was initially created with PyCharm. PyCharm creates a virtual environment with a lib directory and a separate lib64 directory. The python3 command creates virtual environments with a lib directory and a lib64 symlink that targets the lib directory.

So, you can either recreate your virtual environment with the python3 command.
```bash
rm -rf .venv
python3  -m venv .venv
```

 Or you can delete the lib64 directory and create a symlink in its place like so.
```bash
rm -rf .venv/lib64
ln -s lib .venv/lib46
```

Either way, you'll need to activate your virtual environment and reinstall your PyTorch dependencies (and maybe others).

**Comment by worthy7** [comment]
![image](https://github.com/user-attachments/assets/00a203f5-2d5f-4bfb-a471-cbadcf9c5e36)
Torch 2.1.0 does not show that it has dependecies on the nvidia libraries at least in poetry.

Should it? Is that the root cause here?

**Comment by skyswordx** [comment]
if u use **conda to manage ur pytorch env**, changes to LD_LIBRARY_PATH **in bashrc profile** or **export it in terminal** would **NOT** take effect. Instead, u need to activate the conda env first and then **change the LD_LIBRARY_PATH in conda config** with following command:
```bash
conda env config vars set LD_LIBRARY_PATH=<your/path/to/missing/lib>
```
then reactivate the env 

to find where are ur missing libfiles, u can use 
```bash
sudo find / -name 'libcudnn.so.8'
```

by the way, pytorch-gpu package has contained some cuda lib

**Comment by Boatsure** [comment]
Jetson Orin NX same issue
Jetpack6.1 = Ubuntu22.04+python3.10
nvcc -V outputs as follows:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Aug_14_10:14:07_PDT_2024
Cuda compilation tools, release 12.6, V12.6.68
Build cuda_12.6.r12.6/compiler.34714021_0
```
nvidia-smi outputs as follows:
`NVIDIA-SMI 540.4.0                Driver Version: 540.4.0      CUDA Version: 12.6`

After I pip install the Pytorch v2.1.0 or Pytorch v2.3.0 whl in Pyorch-for-Jetson, python import reports `ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory`.

**Comment by kairin** [comment]
> If you are using 22.04, try this
> 
> ```shell
> sudo apt install nvidia-cudnn
> ```

thank you.

it looks like this step resolved my tenssorrt not imported.

https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/issues/33#issuecomment-2524813593

**Comment by mategyerek** [comment]
> `poetry add` provides dependency packages, but not the cudnn runtime binaries. So after running `poetry add torch`, I manually `pip uninstall torch` and then `pip install torch` again (since pip brings the cuda binaries too)
> 
> Torch then successfully imports and CUDA is available.

Did this, then copied the missing files (`libcudnn.so.9` and `libnccl.so.2`) form poetry's cache directory to the directory the error message said they are missing from. I am sure this is not the best solution, but it worked for me.

**Comment by ZubairKhan001** [comment]
Downgrading torch version solved the issue.
