### ISSUE TITLE
Docker build with CUDNN6 not working.

### ISSUE THREAD

**Issue by angusturner** [pytorch/pytorch#1065]
I have been trying to get a build with working Conv1d with dilations, as per issue #967. 
On Ubuntu 16.04, the dockerized CUDNN6 build throws the following error. 

```
True
CUDNN  VERSION 6005
Float
THCudaCheck FAIL file=/tmp/pip-8e667l95-build/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu line=246 error=8 : invalid device function
Traceback (most recent call last):
  File "test_dilation.py", line 33, in <module>
    output.backward(output.data)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/autograd/variable.py", line 146, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
RuntimeError: cuda runtime error (8) : invalid device function at /tmp/pip-8e667l95-build/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:246
```

**Comment by ngimel** [comment]
What GPU are you using? Dockerfile builds pytorch for 3.5 5.2 6.0 6.1+PTX architectures, if yours is different add it to corresponding line in Dockerfile.

**Comment by angusturner** [comment]
I'm using an amazon g2.2 instance with GRID K520. CUDA 8.061. Building from source works, however I still encounter issue #967, so I thought I may as well test the docker images. However these both error, as above ^.

I have been trying for days to find a fix to slow dilated Conv1d (#967), because I need to train a model on GPU. But despite many clean installs and different versions of pytorch I have had no luck. Any help would be greatly appreciated.

**Comment by ngimel** [comment]
That's compute capability 3.0. So either change Dockerfile, or download cudnn v6 and build from source (in the source build that you show in #967 your cudnn version is 5.1).

**Comment by angusturner** [comment]
Ok thank you. Will building from source with cudnn v6.

**Comment by angusturner** [comment]
Is CuDNN 6 publicly available? Through the Nvidia site the newest I can find is 5.1?

**Comment by ngimel** [comment]
https://www.google.com/search?q=download+cudnn+v6

**Comment by angusturner** [comment]
CUDNN v6 + building from source fixed my issue. Not sure whether this issue still exists for the docker build though.

**Comment by soumith** [comment]
the main dockerfile is now built with cudnn v6. Also the binaries are built with support for 3.0. 
I think this issue can be closed.
