### ISSUE TITLE
[ppc64le/pytorch] build break due to #10478

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#10698]
ppc64le build breaks after #10478.  
I am building with :  

export USE_SYSTEM_NCCL=TRUE
export NCCL_ROOT_DIR=/usr/local/cuda/
export NCCL_LIB_DIR=/usr/local/cuda/lib64
export NCCL_INCLUDE_DIR=/usr/local/cuda/include

I have NCCL2 from nvidia 
cuda 9.2 
cudnn 7

here is the log : 
/pytorch/torch/lib/c10d/test/ProcessGroupNCCLTest.cpp: In member function ‘std::vector<at::Tensor> NCCLTest::getTensors()’:
/pytorch/torch/lib/c10d/test/ProcessGroupNCCLTest.cpp:99:49: error: no matching function for call to ‘at::Tensor::toBackend(const at::DeviceType&)’
       outputs[i] = inputs_[i].toBackend(at::kCPU);
                                                 ^
/pytorch/torch/lib/c10d/test/ProcessGroupNCCLTest.cpp:99:49: note: candidate is:
In file included from /pytorch/torch/lib/tmp_install/include/ATen/NativeFunctions.h:7:0,
                 from /pytorch/torch/lib/tmp_install/include/ATen/Functions.h:11,
                 from /pytorch/torch/lib/tmp_install/include/ATen/ATen.h:13,
                 from /pytorch/torch/lib/c10d/../c10d/ProcessGroup.hpp:7,
                 from /pytorch/torch/lib/c10d/../c10d/ProcessGroupNCCL.hpp:8,
                 from /pytorch/torch/lib/c10d/test/ProcessGroupNCCLTest.cpp:5:
/pytorch/torch/lib/tmp_install/include/ATen/TensorMethods.h:38:15: note: at::Tensor at::Tensor::toBackend(at::Backend) const
 inline Tensor Tensor::toBackend(Backend b) const {
               ^
/pytorch/torch/lib/tmp_install/include/ATen/TensorMethods.h:38:15: note:   no known conversion for argument 1 from ‘const at::DeviceType’ to ‘at::Backend’
/pytorch/torch/lib/c10d/test/ProcessGroupNCCLTest.cpp: In member function ‘std::vector<std::vector<at::Tensor> > NCCLTest::getOutputTensors()’:
/pytorch/torch/lib/c10d/test/ProcessGroupNCCLTest.cpp:118:58: error: no matching function for call to ‘at::Tensor::toBackend(const at::DeviceType&)’
         outputs[i][j] = outputs_[i][j].toBackend(at::kCPU);
                                                         ^

I noticed there is another reported build break pointing to backend() == kCPU as well ( #10678)

**Comment by ezyang** [comment]
Can you please check if https://github.com/pytorch/pytorch/pull/10704 solves the problem for you

**Comment by avmgithub** [comment]
@ezyang , I was the one that just submitted the PR.  yes,  it builds fine with those changes.   I just need your review to make sure those changes are valid to function properly.

**Comment by avmgithub** [comment]
@ezyang oops,  looks like I opened a duplicate PR to yours

**Comment by avmgithub** [comment]
@ezyang I confirm your change fixes the build.
