### ISSUE TITLE
c10d clients connecting to c10d server

### ISSUE THREAD

**Issue by marwage** [pytorch/pytorch#107033]
### 🐛 Describe the bug

Hi everyone,

I am running a distributed training with PyTorch and I want to scale resources during training and therefore I am using the elastic version of `torchrun`.
I am running the following command. I don't think the actual python code is important. At first `c10d` did always bind only to IPv6 even though there is no IPv6. I got a step further after changing from the hostname to the complete domain name. No it gets to `torch.distributed.init` but gets stuck and I cannot make sense of it.

Start command
```
torchrun \
    --nnodes=1:16 \
    --nproc-per-node=4 \
    --max-restarts=3 \
    --rdzv-id=training-rdvz \
    --rdzv-backend=c10d \
    --rdzv-endpoint=hostname.example.com:29400
```
First c10d output
```
[I socket.cpp:442] [c10d - debug] The server socket will attempt to listen on an IPv6 address.
[I socket.cpp:492] [c10d - debug] The server socket is attempting to listen on [::]:29400.
[I socket.cpp:566] [c10d] The server socket has started to listen on [::]:29400.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (komodo01.doc.res.ic.ac.uk, 29400).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [192.168.0.78]:29400.
[I socket.cpp:295] [c10d - debug] The server socket on [::]:29400 has accepted a connection from [::ffff:127.0.0.1]:52270.
[I socket.cpp:787] [c10d] The client socket has connected to [192.168.0.78]:29400 on [::ffff:127.0.0.1]:52270.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (komodo01.doc.res.ic.ac.uk, 29400).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [192.168.0.78]:29400.
[I socket.cpp:295] [c10d - debug] The server socket on [::]:29400 has accepted a connection from [::ffff:127.0.0.1]:52272.
[I socket.cpp:787] [c10d] The client socket has connected to [192.168.0.78]:29400 on [::ffff:127.0.0.1]:52272.
```
Error
```
> initializing torch distributed ...
[I socket.cpp:442] [c10d - debug] The server socket will attempt to listen on an IPv6 address.
[I socket.cpp:492] [c10d - debug] The server socket is attempting to listen on [::]:42163.
[I socket.cpp:566] [c10d] The server socket has started to listen on [::]:42163.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (192.168.0.78, 42163).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [::ffff:192.168.0.78]:42163.
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [::ffff:192.168.0.78]:42163.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (192.168.0.78, 42163).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [::ffff:192.168.0.78]:42163.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (192.168.0.78, 42163).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [::ffff:192.168.0.78]:42163.
[W socket.cpp:601] [c10d] The client socket has failed to connect to [::ffff:192.168.0.78]:42163 (errno: 110 - Connection timed out).
[I socket.cpp:633] [c10d - debug] The client socket will attempt to connect to an IPv4 address of (192.168.0.78, 42163).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [::ffff:192.168.0.78]:42163 (errno: 110 - Connection timed out).
[I socket.cpp:633] [c10d - debug] The client socket will attempt to connect to an IPv4 address of (192.168.0.78, 42163).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [::ffff:192.168.0.78]:42163 (errno: 110 - Connection timed out).
[I socket.cpp:633] [c10d - debug] The client socket will attempt to connect to an IPv4 address of (192.168.0.78, 42163).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [::ffff:192.168.0.78]:42163 (errno: 110 - Connection timed out).
[I socket.cpp:633] [c10d - debug] The client socket will attempt to connect to an IPv4 address of (192.168.0.78, 42163).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to 192.168.0.78:42163.
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to 192.168.0.78:42163.
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to 192.168.0.78:42163.
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to 192.168.0.78:42163.
[W socket.cpp:601] [c10d] The client socket has failed to connect to 192.168.0.78:42163 (errno: 110 - Connection timed out).
[E socket.cpp:657] [c10d] The client socket has failed to connect to any network address of (192.168.0.78, 42163).
[W socket.cpp:601] [c10d] The client socket has failed to connect to 192.168.0.78:42163 (errno: 110 - Connection timed out).
[E socket.cpp:657] [c10d] The client socket has failed to connect to any network address of (192.168.0.78, 42163).
[W socket.cpp:601] [c10d] The client socket has failed to connect to 192.168.0.78:42163 (errno: 110 - Connection timed out).
[E socket.cpp:657] [c10d] The client socket has failed to connect to any network address of (192.168.0.78, 42163).
Traceback (most recent call last):
Traceback (most recent call last):
[W socket.cpp:601] [c10d] The client socket has failed to connect to 192.168.0.78:42163 (errno: 110 - Connection timed out).
  File "pretrain_gpt.py", line 326, in <module>
  File "pretrain_gpt.py", line 326, in <module>
[E socket.cpp:657] [c10d] The client socket has failed to connect to any network address of (192.168.0.78, 42163).
Traceback (most recent call last):
  File "pretrain_gpt.py", line 326, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/workspace/Megatron-DeepSpeed/megatron/training.py", line 101, in pretrain
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/workspace/Megatron-DeepSpeed/megatron/training.py", line 101, in pretrain
Traceback (most recent call last):
  File "pretrain_gpt.py", line 326, in <module>
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/Megatron-DeepSpeed/megatron/initialize.py", line 79, in initialize_megatron
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/workspace/Megatron-DeepSpeed/megatron/training.py", line 101, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/Megatron-DeepSpeed/megatron/initialize.py", line 79, in initialize_megatron
    finish_mpu_init()
 File "/workspace/Megatron-DeepSpeed/megatron/initialize.py", line 60, in finish_mpu_init
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/Megatron-DeepSpeed/megatron/initialize.py", line 79, in initialize_megatron
    _initialize_distributed()
    ¦   ¦ File "/workspace/Megatron-DeepSpeed/megatron/initialize.py", line 222, in _initialize_distributed
finish_mpu_init()finish_mpu_init()

  File "/workspace/Megatron-DeepSpeed/megatron/initialize.py", line 60, in finish_mpu_init
  File "/workspace/Megatron-DeepSpeed/megatron/initialize.py", line 60, in finish_mpu_init
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/workspace/Megatron-DeepSpeed/megatron/training.py", line 101, in pretrain
    _initialize_distributed()
  File "/workspace/Megatron-DeepSpeed/megatron/initialize.py", line 222, in _initialize_distributed
    _initialize_distributed()
  File "/workspace/Megatron-DeepSpeed/megatron/initialize.py", line 222, in _initialize_distributed
    torch.distributed.init_process_group(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
    ¦   torch.distributed.init_process_group(initialize_megatron(extra_args_provider=extra_args_provider,

  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
  File "/workspace/Megatron-DeepSpeed/megatron/initialize.py", line 79, in initialize_megatron
    torch.distributed.init_process_group(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
    finish_mpu_init()
  File "/workspace/Megatron-DeepSpeed/megatron/initialize.py", line 60, in finish_mpu_init
    store, rank, world_size = next(rendezvous_iterator)
    ¦ File "/usr/local/lib/python3.8/dist-packages/torch/distributed/rendezvous.py", line 200, in _tcp_rendezvous_handler
_initialize_distributed()
  File "/workspace/Megatron-DeepSpeed/megatron/initialize.py", line 222, in _initialize_distributed
    store, rank, world_size = next(rendezvous_iterator)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/rendezvous.py", line 200, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store
    ¦   return TCPStore(torch.distributed.init_process_group(

RuntimeError  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
:     The client socket has failed to connect to any network address of (192.168.0.78, 42163). The client socket has failed to connect to 192.168.0.78:42163 (errno: 110 - Connection timed out).store = _create_c10d_store(result.hostname,  +++result.port, rank, world_size, timeout)

  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store
    store, rank, world_size = next(rendezvous_iterator)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/rendezvous.py", line 200, in _tcp_rendezvous_handler
    return TCPStore(
RuntimeError: The client socket has failed to connect to any network address of (192.168.0.78, 42163). The client socket has failed to connect to 192.168.0.78:42163 (errno: 110 - Connection timed out).
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
    store, rank, world_size = next(rendezvous_iterator)RuntimeError
: The client socket has failed to connect to any network address of (192.168.0.78, 42163). The client socket has failed to connect to 192.168.0.78:42163 (errno: 110 - Connection timed out).  File "/usr/local/lib/python3.8/dist-packages/  +++torch/distributed/rendezvous.py", line 200, in _tcp_rendezvous_handler

    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
RuntimeError: The client socket has failed to connect to any network address of (192.168.0.78, 42163). The client socket has failed to connect to 192.168.0.78:42163 (errno: 110 - Connection timed out).
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 79) of binary: /usr/bin/python3
[I socket.cpp:295] [c10d - debug] The server socket on [::]:29400 has accepted a connection from [komodo03.doc.res.ic.ac.uk]:60770.
[I socket.cpp:295] [c10d - debug] The server socket on [::]:29400 has accepted a connection from [komodo03.doc.res.ic.ac.uk]:60780.
```

### Versions

PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-155-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration:
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          48
On-line CPU(s) list:             0-47
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7402P 24-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1490.850
CPU max MHz:                     2800.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        5589.71
Virtualization:                  AMD-V
L1d cache:                       768 KiB
L1i cache:                       768 KiB
L2 cache:                        12 MiB
L3 cache:                        128 MiB
NUMA node0 CPU(s):               0-47
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid ap
erfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext
 perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_
mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.1+cu118
[pip3] torchvision==0.15.1+cu118
[pip3] triton==2.0.0
[conda] Could not collect

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @dzhulgakov

**Comment by H-Huang** [comment]
Can you validate whether the IPv4 address that it is connecting in the logs is correct?

>  I got a step further after changing from the hostname to the complete domain name. No it gets to torch.distributed.init but gets stuck and I cannot make sense of it.

If you are setting `--rdzv-endpoint=hostname.example.com:29400` that means there is going to be a DNS lookup for hostname.example.com. I would first make sure that it is resolving to the correct IP address and manually pinging that IP address from another machine.

**Comment by marwage** [comment]
Thank you for your help! It turned out that the `/etc/hosts` was messed up
