### ISSUE TITLE
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by albertwujj** [pytorch/pytorch#10910]
When I import torch, I get: "ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory"

I downloaded pytorch through anaconda, using 
> conda install -c pytorch pytorch

Then, i tried 
> conda uninstall pytorch
> conda install pytorch cuda90 -c pytorch

Same error.

I also tried creating a libcudart.so.9.0 symlink to the libcudart.so.9.2 file I had in my Anaconda package, in which case I get the error 
>ImportError: /home/paperspace/anaconda3/lib/python3.6/site-packages/torch/../../../libcudart.so.9.0: version `libcudart.so.9.0' not found (required by /home/paperspace/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)

**Comment by soumith** [comment]
I think I know what's going on. `anaconda` changed cudatoolkit from `9.0` to `9.2` 3 days ago.
We have to publish new PyTorch binaries, I'll work on that now.

**Comment by albertwujj** [comment]
Ok, great. For now i fixed it with: 
> conda install -c anaconda cudatoolkit==9.0

**Comment by soumith** [comment]
i'm keeping the issue open until the new binaries are pushed.

**Comment by jnorwood** [comment]
I ran into this yesterday also.  It wasn't obvious to me what to do, but someone, maybe on stack overflow, pointed out that you can select (for example cuda 9.2) on the pytorch installation page, and it then it generates the correct command to run.  I tried the command below, after uninstalling the previously installed pytorch, torchvision and cuda toolkit, and it fixed this same problem for me.
conda install pytorch torchvision cuda92 -c pytorch

**Comment by albertwujj** [comment]
Again for visibility, simply

conda install -c anaconda cudatoolkit==9.0

worked for me.

**Comment by albertwujj** [comment]
Again for visibility, simply

conda install -c anaconda cudatoolkit==9.0

worked for me.

**Comment by soumith** [comment]
We uploaded new binaries now, and reinstalling pytorch from conda fixes this issue.

**Comment by SaidaSaad** [comment]
Hello 
I have cuda 10 on my machine with RTX 2080 and I have the same error 
Should i install cuda 9 to solve this problem , if yes how can i switch from cuda 10 to cuda 9 after installtion 
or it is better to remove cuda 10 and install 9

**Comment by lawrencekiba** [comment]
> Hello
> I have cuda 10 on my machine with RTX 2080 and I have the same error
> Should i install cuda 9 to solve this problem , if yes how can i switch from cuda 10 to cuda 9 after installtion
> or it is better to remove cuda 10 and install 9

I'm also struggling from this issue as well since building from source & I have CUDA 10 with RTX2080.

Nonetheless I believe installing cuda 9 isn't entirely possible because RTX2080 will only work properly with CUDA 10 & above.

**Comment by mwillwork** [comment]
I'm also struggling with this issue with CUDA 10.

**Comment by soumith** [comment]
@mwillwork what is the install command that you have used?

**Comment by mwillwork** [comment]
@soumith - I installed torchvision after installing pytorch which overrode the pytorch installation. After uninstalling torchvision and torch and reinstalling, things worked.

**Comment by AloshkaD** [comment]
Having the same issue. I installed cudatoolkit 10 using ```conda install -c anaconda cudatoolkit``` and  pytorch using ```conda install pytorch torchvision cudatoolkit=10.0 -c pytorch```. I previously had cuda9 but because I got the RTX 20180ti I was forced to switch to cuda 10. Now I'm getting ```ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory```

**Comment by Holmeyoung** [comment]
```
Tesla P40
cuda 10
CentOS 7
Python 3.6.5
```

When i updated pytorch, i met the same error, and i solved this by
```bash
pip uninstall torch
pip uninstall torchvision
pip install torch
pip install torchvision
```
I have cuda10, but i install the cuda9 version, so the error appear.
Find the right install command here
https://pytorch.org/get-started/locally/

If you reinstall torch in `a terminal` but run python script in `b terminal`, the torch version may not change, so do all in one terminal or start a new one.

**Comment by Plwy** [comment]
met the same error.i solved this by
`pip3 uninstall torch
 pip3 uninstall torchvision
 pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
`
thanks @Holmeyoung
