### ISSUE TITLE
Getting error when trying to use pytorch 1.12.1 with jetpack version 5.1.1

### ISSUE THREAD

**Issue by MadhuriPatil1694** [pytorch/pytorch#110707]
### 🐛 Describe the bug

When I am using Cuda 11.4 with the PyTorch 1.12 model on jetpack 5.1.1, I am getting error …
```cpp
**torch::Device device_ = torch::kCUDA
if (device_.is_cuda()) {
  c10::cuda::getCurrentCUDAStream().synchronize();
}
const auto inputs = torch::from_blob(working_img.data, {working_img.rows, working_img.cols, 3}, torch::kUInt8).to(device_, torch::kFloat).permute({2, 0, 1}).contiguous();
```
throws error
```
[ERROR] [1696585409.990943029]: Segmentation error: CUDA error: no kernel image is available for execution on the device
Exception raised from launch_legacy_kernel at /pytorch/aten/src/ATen/native/cuda/CUDALoops.cuh:155 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits, std::allocator >) + 0xa0 (0xffff866e1e28 in /usr/local/lib/libc10.so)
frame #1: void at::native::gpu_kernel_impl<__nv_hdl_wrapper_t<false, true, __nv_dl_tag<void ()(at::TensorIteratorBase&), &at::native::(anonymous namespace)::direct_copy_kernel_cuda, 7u>, float (float)> >(at::TensorIteratorBase&, __nv_hdl_wrapper_t<false, true, __nv_dl_tag<void ()(at::TensorIteratorBase&), &at::native::(anonymous namespace)::direct_copy_kernel_cuda, 7u>, float (float)> const&) + 0xce8 (0xffff87bf0160 in /usr/local/lib/libtorch_cuda.so)
frame #2: void at::native::gpu_kernel<__nv_hdl_wrapper_t<false, true, _nv_dl_tag<void ()(at::TensorIteratorBase&), &at::native::(anonymous namespace)::direct_copy_kernel_cuda, 7u>, float (float)> >(at::TensorIteratorBase&, __nv_hdl_wrapper_t<false, true, __nv_dl_tag<void ()(at::TensorIteratorBase&), &at::native::(anonymous namespace)::direct_copy_kernel_cuda, 7u>, float (float)> const&) + 0x350 (0xffff87bf0840 in /usr/local/lib/libtorch_cuda.so)
frame #3: at::native::(anonymous namespace)::direct_copy_kernel_cuda(at::TensorIteratorBase&) + 0x318 (0xffff87bccdf8 in /usr/local/lib/libtorch_cuda.so)
frame #4: at::native::copy_device_to_device(at::TensorIterator&, bool) + 0x82c (0xffff87bcd8a4 in /usr/local/lib/libtorch_cuda.so)
frame #5: + 0x14a2b08 (0xffff87bcfb08 in /usr/local/lib/libtorch_cuda.so)
frame #6: + 0xc04af0 (0xffff8e677af0 in /usr/local/lib/libtorch_cpu.so)
frame #7: at::native::copy(at::Tensor&, at::Tensor const&, bool) + 0x74 (0xffff8e678464 in /usr/local/lib/libtorch_cpu.so)
frame #8: at::ops::copy::call(at::Tensor&, at::Tensor const&, bool) + 0x154 (0xffff8efd250c in /usr/local/lib/libtorch_cpu.so)
frame #9: at::native::clone(at::Tensor const&, c10::optionalc10::MemoryFormat) + 0x178 (0xffff8e90afd0 in /usr/local/lib/libtorch_cpu.so)
frame #10: + 0x1874918 (0xffff8f2e7918 in /usr/local/lib/libtorch_cpu.so)
frame #11: at::_ops::clone::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::optionalc10::MemoryFormat) + 0x9c (0xffff8ed1e4cc in /usr/local/lib/libtorch_cpu.so)
frame #12: + 0x2787574 (0xffff901fa574 in /usr/local/lib/libtorch_cpu.so)
frame #13: + 0x2787b14 (0xffff901fab14 in /usr/local/lib/libtorch_cpu.so)
frame #14: at::_ops::clone::call(at::Tensor const&, c10::optionalc10::MemoryFormat) + 0x148 (0xffff8ed8b578 in /usr/local/lib/libtorch_cpu.so)
frame #15: at::native::contiguous(at::Tensor const&, c10::MemoryFormat) + 0x80 (0xffff8e911158 in /usr/local/lib/libtorch_cpu.so)
frame #16: + 0x19a2e48 (0xffff8f415e48 in /usr/local/lib/libtorch_cpu.so)
frame #17: at::_ops::contiguous::call(at::Tensor const&, c10::MemoryFormat) + 0x148 (0xffff8f0b68d8 in /usr/local/lib/libtorch_cpu.so)
frame #18: at::TensorBase::__dispatch_contiguous(c10::MemoryFormat) const + 0x3c (0xffff8e4ece7c in /usr/local/lib/libtorch_cpu.so)
frame #19: at::TensorBase::contiguous(c10::MemoryFormat) const + 0x64 (0xffff935f15c0 in /media/nvidia/external_drive/catkin_ws/devel/lib/libfox_rt_path_segmentation.so)
frame #20: at::Tensor::contiguous(c10::MemoryFormat) const + 0x40 (0xffff935f199c in /media/nvidia/external_drive/catkin_ws/devel/lib/libfox_rt_path_segmentation.so)
frame #21: SegmentationDriver::segmentImage(cv::Mat const&, std::vector<ObjectSegmentationProperties, std::allocator > const&) + 0x268 (0xffff935ebc10 in /media/nvidia/external_drive/catkin_ws/devel/lib/libfox_rt_path_segmentation.so)
frame #22: + 0x2f228 (0xaaaab5ddf228 in /media/nvidia/external_drive/catkin_ws/devel/lib/fox_rt_path_segmentation/fox_rt_path_segmentation_node)
frame #23: + 0x459b4 (0xaaaab5df59b4 in /media/nvidia/external_drive/catkin_ws/devel/lib/fox_rt_path_segmentation/fox_rt_path_segmentation_node)
frame #24: + 0x4461c (0xaaaab5df461c in /media/nvidia/external_drive/catkin_ws/devel/lib/fox_rt_path_segmentation/fox_rt_path_segmentation_node)
frame #25: + 0x433e4 (0xaaaab5df33e4 in /media/nvidia/external_drive/catkin_ws/devel/lib/fox_rt_path_segmentation/fox_rt_path_segmentation_node)
frame #26: + 0x41320 (0xaaaab5df1320 in /media/nvidia/external_drive/catkin_ws/devel/lib/fox_rt_path_segmentation/fox_rt_path_segmentation_node)
frame #27: + 0x45df0 (0xaaaab5df5df0 in /media/nvidia/external_drive/catkin_ws/devel/lib/fox_rt_path_segmentation/fox_rt_path_segmentation_node)
frame #28: + 0x44948 (0xaaaab5df4948 in /media/nvidia/external_drive/catkin_ws/devel/lib/fox_rt_path_segmentation/fox_rt_path_segmentation_node)
frame #29: + 0x494e4 (0xaaaab5df94e4 in /media/nvidia/external_drive/catkin_ws/devel/lib/fox_rt_path_segmentation/fox_rt_path_segmentation_node)
frame #30: + 0x480e4 (0xaaaab5df80e4 in /media/nvidia/external_drive/catkin_ws/devel/lib/fox_rt_path_segmentation/fox_rt_path_segmentation_node)
frame #31: ros::SubscriptionQueue::call() + 0x9a4 (0xffff934f6e6c in /opt/ros/noetic/lib/libroscpp.so)
frame #32: ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) + 0x274 (0xffff934a2a6c in /opt/ros/noetic/lib/libroscpp.so)
frame #33: ros::CallbackQueue::callOne(ros::WallDuration) + 0x1d8 (0xffff934a3780 in /opt/ros/noetic/lib/libroscpp.so)
frame #34: ros::AsyncSpinnerImpl::threadFunc() + 0x64 (0xffff934f98bc in /opt/ros/noetic/lib/libroscpp.so)
frame #35: + 0x10624 (0xffff85e06624 in /lib/aarch64-linux-gnu/libboost_thread.so.1.71.0)
frame #36: + 0x7624 (0xffff93342624 in /lib/aarch64-linux-gnu/libpthread.so.0)
frame #37: + 0xd149c (0xffff863fd49c in /lib/aarch64-linux-gnu/libc.so.6)
```
### Versions

pytorch build from source v1.12
cuda 11.4
jetpack 5.1

cc @malfet @seemethere @ptrblck @snadampal

**Comment by MadhuriPatil1694** [comment]
its build from source successfully using steps 
git clone https://github.com/pytorch/pytorch.git
cd pytorch/
git checkout v1.12
mkdir build install
cd build
cmake  -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DPYTHON_EXECUTABLE:PATH=`which python3` -DUSE_NCCL=OFF -DUSE_DISTRIBUTED=OFF -DUSE_QNNPACK=OFF -DUSE_PYTORCH_QNNPACK=OFF -Wno-dev -DCMAKE_INSTALL_PREFIX:PATH=../install ..
make install
`

**Comment by MadhuriPatil1694** [comment]
> @MadhuriPatil1694 can you share a full config log? I.e. looks like CUDA was not found during the build) Also, is the problem still reproducible with PyTorch-2.1 and CUDA-11.8 (there is not much one can do about PyTorch-1.12 build issues)

but I have used the identical versions on Jetpack 5.0.1 and it worked I didn't have any issues. Also, I cannot upgrade cuda from 11.4 to 11.8 as most of the things developed until now are failing with this upgrade. So it will take more time but if nothing works I will go for this option

**Comment by MadhuriPatil1694** [comment]
Also do you have any idea if I can build pytorch 2.1 on arm64 ,as its first requirement looks like it needs c++17

**Comment by ptrblck** [comment]
@MadhuriPatil1694 I don't know if you need a custom build, but you can download the PyTorch Jetson wheels from [here](https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048) or [here](https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html).

**Comment by MadhuriPatil1694** [comment]
> Copy.cu.o

yes its sm_87 
$cuobjdump -lelf /mnt/nvme0n1/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/Copy.cu.o
ELF file    1: Copy.cu.1.sm_87.cubin

**Comment by MadhuriPatil1694** [comment]
> @MadhuriPatil1694 I don't know if you need a custom build, but you can download the PyTorch Jetson wheels from [here](https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048) or [here](https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html).

I tried but it doesn't install libtorch library which I need for compiling Pytorch in c++

**Comment by MadhuriPatil1694** [comment]
solved the issue the main reason is in Jetpack 5.1 they have changed some of the folder structure and names for example usr/local/lib64/stubs, where caffe2 stores some cuda-related libraries to usr/local/lib64/stubs_  So I was looking at wrong folder. Thanks everyone for there input.
