### ISSUE TITLE
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1331, unhandled cuda error (run with NCCL_DEBUG=INFO for details)

### ISSUE THREAD

**Issue by mlinmg** [pytorch/pytorch#111187]
### 🐛 Describe the bug

When I try to finetune with ddp([LLaMA-Factory](https://github.com/hiyouga/LLaMA-Factory)) in wsl2(win10 host), I get this error:
```
DESKTOP-VMBL43V:1354:1354 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
DESKTOP-VMBL43V:1354:1354 [0] NCCL INFO Bootstrap : Using eth0:172.23.125.43<0>
DESKTOP-VMBL43V:1354:1354 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
DESKTOP-VMBL43V:1354:1354 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation
DESKTOP-VMBL43V:1354:1354 [0] NCCL INFO cudaDriverVersion 11080
DESKTOP-VMBL43V:1355:1355 [1] NCCL INFO cudaDriverVersion 11080
NCCL version 2.18.5+cuda11.8
DESKTOP-VMBL43V:1355:1355 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
DESKTOP-VMBL43V:1355:1355 [1] NCCL INFO Bootstrap : Using eth0:172.23.125.43<0>
DESKTOP-VMBL43V:1355:1355 [1] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
DESKTOP-VMBL43V:1355:1355 [1] NCCL INFO NET/Plugin : No plugin found, using internal implementation
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO NET/IB : No device found.
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO NET/Socket : Using [0]eth0:172.23.125.43<0>
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO Using network Socket
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO NET/IB : No device found.
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO NET/Socket : Using [0]eth0:172.23.125.43<0>
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO Using network Socket
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO comm 0x7aef8cc0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId 4000 commId 0xfab41a312f23304f - Init START
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO comm 0x7e10b200 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 1000 commId 0xfab41a312f23304f - Init START
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO NCCL_IGNORE_DISABLED_P2P set by environment to 1.
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO NCCL_IGNORE_DISABLED_P2P set by environment to 1.
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO Channel 00/02 :    0   1
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO Channel 01/02 :    0   1
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO P2P Chunksize set to 131072
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO P2P Chunksize set to 131072
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO Channel 00 : 0[0] -> 1[1] via SHM/direct/direct
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO Channel 01 : 0[0] -> 1[1] via SHM/direct/direct
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO Channel 00 : 1[1] -> 0[0] via SHM/direct/direct
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO Channel 01 : 1[1] -> 0[0] via SHM/direct/direct

DESKTOP-VMBL43V:1354:1395 [0] transport.cc:154 NCCL WARN Cuda failure 'invalid argument'
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO init.cc:1079 -> 1
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO init.cc:1358 -> 1
DESKTOP-VMBL43V:1354:1395 [0] NCCL INFO group.cc:65 -> 1 [Async thread]
DESKTOP-VMBL43V:1354:1354 [0] NCCL INFO group.cc:406 -> 1
DESKTOP-VMBL43V:1354:1354 [0] NCCL INFO group.cc:96 -> 1

DESKTOP-VMBL43V:1355:1396 [1] transport.cc:154 NCCL WARN Cuda failure 'invalid argument'
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO init.cc:1079 -> 1
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO init.cc:1358 -> 1
DESKTOP-VMBL43V:1355:1396 [1] NCCL INFO group.cc:65 -> 1 [Async thread]
DESKTOP-VMBL43V:1355:1355 [1] NCCL INFO group.cc:406 -> 1
DESKTOP-VMBL43V:1355:1355 [1] NCCL INFO group.cc:96 -> 1
Traceback (most recent call last):
  File "/mnt/c/Users/marco/Desktop/finetunegpl/LLaMA-Efficient-Tuning/src/train_bash.py", line 14, in <module>
    main()
  File "/mnt/c/Users/marco/Desktop/finetunegpl/LLaMA-Efficient-Tuning/src/train_bash.py", line 5, in main
    run_exp()
  File "/mnt/c/Users/marco/Desktop/finetunegpl/LLaMA-Efficient-Tuning/src/llmtuner/tuner/tune.py", line 26, in run_exp
    run_sft(model_args, data_args, training_args, finetuning_args, generating_args, callbacks)
  File "/mnt/c/Users/marco/Desktop/finetunegpl/LLaMA-Efficient-Tuning/src/llmtuner/tuner/sft/workflow.py", line 29, in run_sft
    dataset = preprocess_dataset(dataset, tokenizer, data_args, training_args, stage="sft")
  File "/mnt/c/Users/marco/Desktop/finetunegpl/LLaMA-Efficient-Tuning/src/llmtuner/dsets/preprocess.py", line 216, in preprocess_dataset
    with training_args.main_process_first(desc="dataset map pre-processing"):
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/site-packages/transformers/training_args.py", line 2084, in main_process_first
    dist.barrier()
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3696, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1331, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.5
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'invalid argument'
Traceback (most recent call last):
  File "/mnt/c/Users/marco/Desktop/finetunegpl/LLaMA-Efficient-Tuning/src/train_bash.py", line 14, in <module>
    main()
  File "/mnt/c/Users/marco/Desktop/finetunegpl/LLaMA-Efficient-Tuning/src/train_bash.py", line 5, in main
    run_exp()
  File "/mnt/c/Users/marco/Desktop/finetunegpl/LLaMA-Efficient-Tuning/src/llmtuner/tuner/tune.py", line 26, in run_exp
    run_sft(model_args, data_args, training_args, finetuning_args, generating_args, callbacks)
  File "/mnt/c/Users/marco/Desktop/finetunegpl/LLaMA-Efficient-Tuning/src/llmtuner/tuner/sft/workflow.py", line 29, in run_sft
    dataset = preprocess_dataset(dataset, tokenizer, data_args, training_args, stage="sft")
  File "/mnt/c/Users/marco/Desktop/finetunegpl/LLaMA-Efficient-Tuning/src/llmtuner/dsets/preprocess.py", line 216, in preprocess_dataset
    with training_args.main_process_first(desc="dataset map pre-processing"):
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/site-packages/transformers/training_args.py", line 2093, in main_process_first
    dist.barrier()
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3696, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1331, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.5
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'invalid argument'
DESKTOP-VMBL43V:1355:1355 [1] NCCL INFO comm 0x7aef8cc0 rank 1 nranks 2 cudaDev 1 busId 4000 - Abort COMPLETE
DESKTOP-VMBL43V:1354:1354 [0] NCCL INFO comm 0x7e10b200 rank 0 nranks 2 cudaDev 0 busId 1000 - Abort COMPLETE
[2023-10-13 07:17:04,991] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1354) of binary: /home/marco/miniconda3/envs/lama/bin/python
Traceback (most recent call last):
  File "/home/marco/miniconda3/envs/lama/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/marco/miniconda3/envs/lama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
src/train_bash.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-10-13_07:17:04
  host      : DESKTOP-VMBL43V.
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1355)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-13_07:17:04
  host      : DESKTOP-VMBL43V.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1354)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

```
the command I use is `accelerate launch src/train_bash.py --stage sft --model_name_or_path /mnt/c/Users/marco/Desktop/finetunegpl/sheep-duck-llama-2-13b/ --do_train --finetuning_type lora --template default --flash_attn  --shift_attn  --dataset_dir data --dataset lima --cutoff_len 1024 --learning_rate 5e-05 --num_train_epochs 3.0 --max_samples 100000 --per_device_train_batch_size 4 --gradient_accumulation_steps 4 --lr_scheduler_type cosine --max_grad_norm 1.0 --logging_steps 5 --save_steps 100 --warmup_steps 0 --lora_rank 128 --lora_dropout 0.1 --lora_target q_proj,v_proj --resume_lora_training  --output_dir saves\Custom\lora\2023-10-13-02-59-59 --fp16  --plot_loss`

### Versions

PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090 Ti
GPU 1: NVIDIA GeForce RTX 3090 Ti

Nvidia driver version: 522.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 5 5500
CPU family:                      25
Model:                           80
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        7599.71
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr arat umip vaes vpclmulqdq rdpid fsrm
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        3 MiB (6 instances)
L3 cache:                        16 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.1.0+cu118
[pip3] torchaudio==2.1.0+cu118
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     2.1.0+cu118              pypi_0    pypi
[conda] torchaudio                2.1.0+cu118              pypi_0    pypi
[conda] torchvision               0.16.0+cu118             pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by mlinmg** [comment]
[This](https://github.com/NVIDIA/nccl/issues/1024?notification_referrer_id=NT_kwDOB0HvlbQ4MDQxMTc5Nzg5OjEyMTc2MTY4NQ) had been said by the nvidia guys, so you must change the version of nccl boundled with torch.
I'm trying to compile it myself to see if if this will fix it but it not an easy task for me

**Comment by iremyux** [comment]
Hi @mlinmg , 
It seems like you used WSL and not native Windows. Since we aim to keep those two backlogs separate, I am removing the `module:windows` label.

**Comment by JerryDaHeLian** [comment]
I have encountered the same problem, has anyone solved it?

**Comment by mlinmg** [comment]
Are you using wsl? Try to either install torch nightly or try it on a different os. This solved for me

**Comment by legel** [comment]
This problem could be solved by the PyTorch maintainers by simply upgrading wheels for PyTorch to include NCCL 2.19.3, which has the key fix for NCCL commited from [here](https://github.com/NVIDIA/nccl/commit/4365458757e4107ecbf629b2fd6e0e19a5d237c2).  

Until then...
![bleeding_edge](https://github.com/pytorch/pytorch/assets/1915466/22f647d7-c5e1-4f1e-ac65-9988475d1e6f)



On the bright side, I've solved it, my 2 GPUs are now running NCCL delightfully, and soon-ish so could yours too... :rocket: 

From a high-level, here is where I landed that works:
```
>>> import torch
>>> torch.__version__
'2.3.0a0+git49af19c'
>>> torch.cuda.nccl.version()
(2, 19, 3)
```

Getting there is your own personal spiritual journey with your computer.

I can give you a few X's on the map, and definitely say, **proceed with caution and at your own risk**.
If you're new to this business, just know that a lion could jump out from the jungle at any time and eat your _visual display_.

1. Update to latest CUDA, e.g. 12.3  
  [Guide](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#) | [Download](https://developer.nvidia.com/cuda-downloads) 
  _This may not be necessary, but since we're updating everything else, this is a safe and advisable move._
  e.g.
  ```
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
    sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
    wget https://developer.download.nvidia.com/compute/cuda/12.3.1/local_installers/cuda-repo-ubuntu2204-12-3-local_12.3.1-545.23.08-1_amd64.deb
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
    sudo dpkg -i cuda-keyring_1.1-1_all.deb
    sudo apt-get update
    sudo apt-get -y install cuda-toolkit-12-3
    sudo apt-get install -y cuda-drivers
    sudo reboot
    nvidia-smi
  ```

2. Update to latest NCCL, e.g. 2.19.3
  [Guide](https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html) | [Download](https://developer.nvidia.com/nccl/nccl-download)
  
3. Uninstall current version of Torch
 ``` pip uninstall torch torchvision torchaudio```

4. Here comes the fun: we have to build Torch from source _properly pointing to our new CUDA and new NCCL_.
  First download the latest version of Torch from source:
  ```
    git clone --recursive https://github.com/pytorch/pytorch
    cd pytorch
  ```

5. Now we need to make sure the PyTorch build properly points to your latest CUDA and NCCL installations.
    On an Ubuntu machine, you would need to export visibility of your new CUDA toolkit like so:
  ```
    export CUDA_HOME=/usr/local/cuda-12.3
    export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
    export PATH=${CUDA_HOME}/bin:${PATH}
  ```

6. It's important to delete old CUDA installations now because I found PyTorch installer would cling to that.
   Inside the `/usr/local/` directory (on Ubuntu) look for older CUDA version and delete those files. 

7. It turns out we need to manually override PyTorch build with env variables for our local installation of NCCL.
    After a lot of trial and error, I give you the documentation:
    ```
    export NCCL_LIB_DIR=/usr/lib/x86_64-linux-gnu
    export NCCL_INCLUDE_DIR=/usr/include
    export USE_NCCL=1
    export USE_SYSTEM_NCCL=1 
    ```

8.  Now, everything should be ready to run the official installation of Torch for Python with your custom linked NCCL.
    Inside the pytorch repository that you cloned from git, run:
    ```python setup.py install```
    
    (Optionally, confirm "USE_NCCL = 1" and CUDA == 12.3 at the start of the Torch build print outs)
    
    Grab a cup of coffee / tea / glass of wine / watch an episode of Saturday Night Live / write a letter to the Torch maintainers thanking them / ... for about one hour
    
9.  If you then `cd ..` out of the `pytorch` directory and run `python` and then `import torch`  -> `print(torch.__version__)` you should see your latest version of `torch`.  As well, you should be able to print `torch.cuda.nccl.version()` to see `(2, 19, 3)` (or later).

That will do it!  In my case, for my computer vision project working with millions of images of _Plantae_, I also had to build `torchvision` from source.  Fortunately that only took a few minutes.

![go_frodo](https://github.com/pytorch/pytorch/assets/1915466/ab313ee6-44b3-4c36-be6f-00cedf9d34df)

**Comment by zhentongLi** [comment]
[INFO|trainer.py:394] 2023-12-18 21:06:08,355 >> The model is loaded in 8-bit precision. To train this model you need to add additional modules inside the model such as adapters using `peft` library and freeze the model weights. Please check  the examples in https://github.com/huggingface/peft for more details.
[2023-12-18 21:06:09,744] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.12.5, git-hash=unknown, git-branch=unknown
Traceback (most recent call last):
  File "/root/gentle/Llama2-Chinese/train/sft/finetune_clm_lora.py", line 691, in <module>
    main()
  File "/root/gentle/Llama2-Chinese/train/sft/finetune_clm_lora.py", line 652, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/transformers/trainer.py", line 1659, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/accelerate/accelerator.py", line 1209, in prepare
    result = self._prepare_deepspeed(*args)
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/accelerate/accelerator.py", line 1582, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 259, in __init__
    self._configure_distributed_model(model)
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1132, in _configure_distributed_model
    self._broadcast_model()
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1052, in _broadcast_model
    dist.broadcast(p, groups._get_broadcast_src_rank(), group=self.seq_data_parallel_group)
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 224, in broadcast
    return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 196, in broadcast
    return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/testenv_llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1910, in broadcast
    work = group.broadcast([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.6
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
Last error:
nvmlInit_v2() failed: Driver/library version mismatch
[2023-12-18 21:06:12,237] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 41823
[2023-12-18 21:06:12,238] [ERROR] [launch.py:321:sigkill_handler] ['/opt/conda/envs/testenv_llama/bin/python', '-u', 'finetune_clm_lora.py', '--local_rank=0', '--model_name_or_path', '../../Llama-2-7b-chat-hf', '--train_files', '../../data/train_sft.csv', '--validation_files', '../../data/dev_sft.csv', '../../data/dev_sft_sharegpt.csv', '--per_device_train_batch_size', '4', '--per_device_eval_batch_size', '4', '--do_train', '--do_eval', '--use_fast_tokenizer', 'false', '--output_dir', 'output_model_lora', '--evaluation_strategy', 'steps', '--max_eval_samples', '800', '--learning_rate', '1e-4', '--gradient_accumulation_steps', '8', '--num_train_epochs', '10', '--warmup_steps', '400', '--load_in_bits', '4', '--lora_r', '8', '--lora_alpha', '32', '--target_modules', 'q_proj,k_proj,v_proj,o_proj,down_proj,gate_proj,up_proj', '--logging_dir', 'output_model_lora/logs', '--logging_strategy', 'steps', '--logging_steps', '10', '--save_strategy', 'steps', '--preprocessing_num_workers', '10', '--save_steps', '20', '--eval_steps', '20', '--save_total_limit', '2000', '--seed', '42', '--disable_tqdm', 'false', '--ddp_find_unused_parameters', 'false', '--block_size', '2048', '--report_to', 'tensorboard', '--overwrite_output_dir', '--deepspeed', 'ds_config_zero2.json', '--ignore_data_skip', 'true', '--fp16', '--gradient_checkpointing', '--fp16_full_eval', '--ddp_timeout', '18000000'] exits with return code = 1

When finetuning llama with lora, there are some problems above.
Could you solve this problem? What shuold I do next?

**Comment by HouseYeung** [comment]
> This problem could be solved by the PyTorch maintainers by simply upgrading wheels for PyTorch to include NCCL 2.19.3, which has the key fix for NCCL commited from [here](https://github.com/NVIDIA/nccl/commit/4365458757e4107ecbf629b2fd6e0e19a5d237c2).
> 
> Until then... ![bleeding_edge](https://private-user-images.githubusercontent.com/1915466/291015745-22f647d7-c5e1-4f1e-ac65-9988475d1e6f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTcwMzUsIm5iZiI6MTcwNDkxNjczNSwicGF0aCI6Ii8xOTE1NDY2LzI5MTAxNTc0NS0yMmY2NDdkNy1jNWUxLTRmMWUtYWM2NS05OTg4NDc1ZDFlNmYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMTk1ODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGFhMTkyYzc1Zjk4NmQ1NmZlNzhjYmU4YzAwNTk4NWM1ZDMwYzcxZDhiYjY4ZWZlNDdjOGMzY2U5YTBmNGMwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lsWkdd1GJDjCtAxh88Hc7Dj3EMb9uhYATJpfbXdRP5A)
> 
> On the bright side, I've solved it, my 2 GPUs are now running NCCL delightfully, and soon-ish so could yours too... 🚀
> 
> From a high-level, here is where I landed that works:
> 
> ```
> >>> import torch
> >>> torch.__version__
> '2.3.0a0+git49af19c'
> >>> torch.cuda.nccl.version()
> (2, 19, 3)
> ```
> 
> Getting there is your own personal spiritual journey with your computer.
> 
> I can give you a few X's on the map, and definitely say, **proceed with caution and at your own risk**. If you're new to this business, just know that a lion could jump out from the jungle at any time and eat your _visual display_.
> 
> 1. Update to latest CUDA, e.g. 12.3
>    [Guide](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#) | [Download](https://developer.nvidia.com/cuda-downloads)
>    _This may not be necessary, but since we're updating everything else, this is a safe and advisable move._
>    e.g.
> 
> ```
>   wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
>   sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
>   wget https://developer.download.nvidia.com/compute/cuda/12.3.1/local_installers/cuda-repo-ubuntu2204-12-3-local_12.3.1-545.23.08-1_amd64.deb
>   wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
>   sudo dpkg -i cuda-keyring_1.1-1_all.deb
>   sudo apt-get update
>   sudo apt-get -y install cuda-toolkit-12-3
>   sudo apt-get install -y cuda-drivers
>   sudo reboot
>   nvidia-smi
> ```
> 
> 2. Update to latest NCCL, e.g. 2.19.3
>    [Guide](https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html) | [Download](https://developer.nvidia.com/nccl/nccl-download)
> 3. Uninstall current version of Torch
>    ` pip uninstall torch torchvision torchaudio`
> 4. Here comes the fun: we have to build Torch from source _properly pointing to our new CUDA and new NCCL_.
>    First download the latest version of Torch from source:
> 
> ```
>   git clone --recursive https://github.com/pytorch/pytorch
>   cd pytorch
> ```
> 
> 5. Now we need to make sure the PyTorch build properly points to your latest CUDA and NCCL installations.
>    On an Ubuntu machine, you would need to export visibility of your new CUDA toolkit like so:
> 
> ```
>   export CUDA_HOME=/usr/local/cuda-12.3
>   export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
>   export PATH=${CUDA_HOME}/bin:${PATH}
> ```
> 
> 6. It's important to delete old CUDA installations now because I found PyTorch installer would cling to that.
>    Inside the `/usr/local/` directory (on Ubuntu) look for older CUDA version and delete those files.
> 7. It turns out we need to manually override PyTorch build with env variables for our local installation of NCCL.
>    After a lot of trial and error, I give you the documentation:
>    ```
>    export NCCL_LIB_DIR=/usr/lib/x86_64-linux-gnu
>    export NCCL_INCLUDE_DIR=/usr/include
>    export USE_NCCL=1
>    export USE_SYSTEM_NCCL=1 
>    ```
> 8. Now, everything should be ready to run the official installation of Torch for Python with your custom linked NCCL.
>    Inside the pytorch repository that you cloned from git, run:
>    `python setup.py install`
>    (Optionally, confirm "USE_NCCL = 1" and CUDA == 12.3 at the start of the Torch build print outs)
>    Grab a cup of coffee / tea / glass of wine / watch an episode of Saturday Night Live / write a letter to the Torch maintainers thanking them / ... for about one hour
> 9. If you then `cd ..` out of the `pytorch` directory and run `python` and then `import torch`  -> `print(torch.__version__)` you should see your latest version of `torch`.  As well, you should be able to print `torch.cuda.nccl.version()` to see `(2, 19, 3)` (or later).
> 
> That will do it! In my case, for my computer vision project working with millions of images of _Plantae_, I also had to build `torchvision` from source. Fortunately that only took a few minutes.
> 
> ![go_frodo](https://private-user-images.githubusercontent.com/1915466/291017235-ab313ee6-44b3-4c36-be6f-00cedf9d34df.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTcwMzUsIm5iZiI6MTcwNDkxNjczNSwicGF0aCI6Ii8xOTE1NDY2LzI5MTAxNzIzNS1hYjMxM2VlNi00NGIzLTRjMzYtYmU2Zi0wMGNlZGY5ZDM0ZGYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMTk1ODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRlZTRkYzhhNzA3NzJhNWZkZDYyMjI2YzQ2MjViZjZkYjI3YTJiOTJlMjE2ZTMyMTIxNDEwODE4ZGVkOWY4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SUhqOy0eBDjBapcO0uRgzODvWJd3g-JboIJDyHxqryA)

Thank You, I try pip install --upgrade nvidia-nccl-cu12==2.19.3 and it also works

**Comment by legel** [comment]
The Pytorch maintainers have since updated the NCCL wheel as show [here](https://github.com/pytorch/pytorch/issues/116977#issuecomment-1898972336) so I recommend just installing the pre-built binary for PyTorch 2.2.0 as of today using conda or pip.

**Comment by Pashisfisuta** [comment]
The error message torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1691, remote process exited or there was a network error, NCCL version 2.19.3 indicates an issue with communication between processes during distributed training using PyTorch's NCCL backend. Here's a breakdown of the error and potential solutions:

Error Breakdown:

torch.distributed.DistBackendError: This indicates an error with the distributed backend used for communication between processes.
NCCL error: This points to a specific issue with the NCCL library, which PyTorch uses for communication in distributed training.
Line 1691, ProcessGroupNCCL.cpp: This refers to the line number in the PyTorch source code where the error originates.
remote process exited or there was a network error: This suggests that either one of the processes involved in the training has exited unexpectedly or there's a network issue preventing communication.
ncclRemoteError: A call failed possibly due to a network error or a remote process exiting prematurely: This reinforces the idea of a network issue or a process crash causing the communication failure.
Potential Solutions:

Network Issues:

Check Network Connectivity: Ensure that all machines participating in the distributed training can communicate with each other on the network. Verify firewall settings and network configuration if necessary.
Network Stability: Use a reliable network connection to minimize disruptions during training.
Process Crashes:

Resource Management: Make sure all processes have sufficient resources (memory, CPU, GPU) allocated to them. Adjust batch sizes or model complexity if resource limitations are causing crashes. Use tools like nvidia-smi to monitor GPU memory usage.
Error Handling: Consider implementing error handling mechanisms in your training script to detect and potentially restart crashed processes.
NCCL Version Compatibility:

Check NCCL Versions: Ensure that all machines participating in the training have the same NCCL version installed. Mismatched versions can lead to communication issues. You can check the NCCL version using nvcc --version or querying the system package manager.
Debugging and Logging:

Increase Verbosity: Increase the verbosity level of your distributed training script to obtain more detailed logs about NCCL operations. This might help pinpoint the location of the communication failure.
Profiling: Use profiling tools to identify potential bottlenecks or resource limitations that might be causing process crashes.
Alternative Communication Backends:

Backend Choice: If NCCL issues persist, consider trying a different distributed communication backend like Gloo or MPI (if it's supported in your environment).
Additional Tips:

Environment Variables: Explore using environment variables like NCCL_DEBUG=INFO to activate more verbose NCCL logging.
Software Updates: Update PyTorch and NCCL to their latest stable versions to benefit from bug fixes and potential improvements.
By following these steps and carefully examining the specific context of your training environment, you should be able to identify the root cause of the NCCL error and successfully run your distributed PyTorch training.

**Comment by dshwei** [comment]
I  also had this  problem :

Socket recv failed while polling for opId=0x7f0c84227ac0
Traceback (most recent call last):
  File "/demo/project/NL2SQL/starcoder-git/codellama/finetune_sft_dataset_0.py", line 499, in <module>
    main(args)
  File "/demo/project/NL2SQL/starcoder-git/codellama/finetune_sft_dataset_0.py", line 488, in main
    run_training(args, train_dataset,valid_dataset = valid_dataset)
  File "/demo/project/NL2SQL/starcoder-git/codellama/finetune_sft_dataset_0.py", line 459, in run_training
    trainer.train()
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/transformers/trainer.py", line 2275, in _maybe_log_save_evaluate
    tr_loss_scalar = self._nested_gather(tr_loss).mean().item()
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/transformers/trainer.py", line 3421, in _nested_gather
    tensors = distributed_concat(tensors)
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/transformers/trainer_pt_utils.py", line 204, in distributed_concat
    dist.all_gather(output_tensors, tensor)
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2806, in all_gather
    work = default_pg.allgather([tensor_list], [tensor])
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, internal error - please report this issue to the NCCL developers, NCCL version 2.18.1
ncclInternalError: Internal check failed.
Last error:
Socket recv failed while polling for opId=0x7f86ac227ac0


**my  question is resloved by change  os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:64"   to   os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"**

**Comment by CivenResun** [comment]
maybe the underlying connection was not established successfully. For example, my two containers, one on h100 machine and the other on a100 machine. But containers on h100 not be allocated enough VFs，so the above issues have arisen.

**Comment by drx-code** [comment]
> maybe the underlying connection was not established successfully. For example, my two containers, one on h100 machine and the other on a100 machine. But containers on h100 not be allocated enough VFs，so the above issues have arisen.

So how to solve this problem with contianers on h100? I also encounter this issue.

**Comment by oroojlooy** [comment]
Same issue with `NCCL==2.20.5` and `Pytorch==2.4.1` on a H100 cluster. Weird observation is that it works fine on some H100 nodes, and does not work on some other, while all nodes are built by the same image. 
Any workaround to fix this?

**Comment by tanjiu** [comment]
> H100 集群上`NCCL==2.20.5`也存在同样的问题。奇怪的是，它在某些 H100 节点上运行良好，而在其他节点上则无法运行，而所有节点都是由同一映像构建的。 有什么解决方法可以解决这个问题吗？`Pytorch==2.4.1`

我也遇到了一样的问题

**Comment by yajunDai** [comment]
> Same issue with `NCCL==2.20.5` and `Pytorch==2.4.1` on a H100 cluster. Weird observation is that it works fine on some H100 nodes, and does not work on some other, while all nodes are built by the same image. Any workaround to fix this?



> Same issue with `NCCL==2.20.5` and `Pytorch==2.4.1` on a H100 cluster. Weird observation is that it works fine on some H100 nodes, and does not work on some other, while all nodes are built by the same image. Any workaround to fix this?

have you solved. i meet the same question.

**Comment by tanjiu** [comment]
> > Same issue with `NCCL==2.20.5` and `Pytorch==2.4.1` on a H100 cluster. Weird observation is that it works fine on some H100 nodes, and does not work on some other, while all nodes are built by the same image. Any workaround to fix this?
> 
> > Same issue with `NCCL==2.20.5` and `Pytorch==2.4.1` on a H100 cluster. Weird observation is that it works fine on some H100 nodes, and does not work on some other, while all nodes are built by the same image. Any workaround to fix this?
> 
> have you solved. i meet the same question.


change pytorch version can solve it

**Comment by lihaoling** [comment]
> > > Same issue with  and  on a H100 cluster. Weird observation is that it works fine on some H100 nodes, and does not work on some other, while all nodes are built by the same image. Any workaround to fix this?`NCCL==2.20.5``Pytorch==2.4.1`
> > 
> > 
> > > Same issue with  and  on a H100 cluster. Weird observation is that it works fine on some H100 nodes, and does not work on some other, while all nodes are built by the same image. Any workaround to fix this?`NCCL==2.20.5``Pytorch==2.4.1`
> > 
> > 
> > have you solved. i meet the same question.
> 
> change pytorch version can solve it

Same issue with `NCCL version 2.20.5 ` and `Pytorch==2.4.1`

What's the right version to change to?

**Comment by zhliu0106** [comment]
I tried pip install --upgrade nvidia-nccl-cu12, and it works

**Comment by wangxidong06** [comment]
> > > Same issue with `NCCL==2.20.5` and `Pytorch==2.4.1` on a H100 cluster. Weird observation is that it works fine on some H100 nodes, and does not work on some other, while all nodes are built by the same image. Any workaround to fix this?`NCCL==2.20.5`和`Pytorch==2.4.1`在H100群集上的相同问题。怪异的观察结果是，它在某些H100节点上工作正常，并且在其他节点上不起作用，而所有节点都是由同一图像构建的。有什么解决方法可以解决这个问题吗？
> > 
> > 
> > > Same issue with `NCCL==2.20.5` and `Pytorch==2.4.1` on a H100 cluster. Weird observation is that it works fine on some H100 nodes, and does not work on some other, while all nodes are built by the same image. Any workaround to fix this?`NCCL==2.20.5`和`Pytorch==2.4.1`在H100群集上的相同问题。怪异的观察结果是，它在某些H100节点上工作正常，并且在其他节点上不起作用，而所有节点都是由同一图像构建的。有什么解决方法可以解决这个问题吗？
> > 
> > 
> > have you solved. i meet the same question.你解决了吗？我遇到同样的问题。
> 
> change pytorch version can solve it更换pytorch版本即可解决

which pytorch version?

**Comment by tonyzyl** [comment]
> Same issue with `NCCL==2.20.5` and `Pytorch==2.4.1` on a H100 cluster. Weird observation is that it works fine on some H100 nodes, and does not work on some other, while all nodes are built by the same image. Any workaround to fix this?

Same versions on a H100 cluster, I have tried both upgrade/downgrade nvidia-nccl but that didn't work. It was solved by installing pytorch with cu118 (cu121 and cu124 fails)

**Comment by Osilly** [comment]
Same problem in H800 cluster, some nodes are working but some are not. So how to solve it?

**Comment by wangxidong06** [comment]
I guess it's because of the cross-node parallel socket communication problem, so I found the socket through ifconfig and forced it to be solved by

export NCCL_SOCKET_IFNAME="your_socket_name"

**Comment by JoyKing9327** [comment]
> I tried pip install --upgrade nvidia-nccl-cu12, and it works

I have the same error. This  solution solves my problem.

**Comment by yuweih205** [comment]
> > 我尝试了 pip install --upgrade nvidia-nccl-cu12，它有效
> 
> 我遇到了同样的错误。这个解决方案解决了我的问题。
what is your cuda and torch version
