### ISSUE TITLE
Core dumped after materializing a model on `meta` device to `cuda` (ROCm)

### ISSUE THREAD

**Issue by IlyasMoutawwakil** [pytorch/pytorch#112012]
### 🐛 Describe the bug

I created a model on `meta` device and materialized it on `cuda` device (ROCm machine).
But when I run the forward pass:

```python
from transformers import AutoModelForMaskedLM
import torch

with torch.device("meta"):
    model = AutoModelForMaskedLM.from_pretrained("bert-base-uncased")

model.to_empty(device="cuda")

dummy_input = {
    "input_ids": torch.randint(1, 10, (1, 128), device="cuda"),
    "attention_mask": torch.ones((1, 128), device="cuda"),
}

model(**dummy_input)
```

I get the following error:
```
/pytorch/aten/src/ATen/native/hip/Indexing.hip:1294: indexSelectLargeIndex: Device-side assertion `srcIndex < srcSelectDimSize' failed.
/pytorch/aten/src/ATen/native/hip/Indexing.hip:1294: indexSelectLargeIndex: Device-side assertion `srcIndex < srcSelectDimSize' failed.
/pytorch/aten/src/ATen/native/hip/Indexing.hip:1294: indexSelectLargeIndex: Device-side assertion `srcIndex < srcSelectDimSize' failed.
/pytorch/aten/src/ATen/native/hip/Indexing.hip:1294: indexSelectLargeIndex: Device-side assertion `srcIndex < srcSelectDimSize' failed.
:0:rocdevice.cpp            :2778: 1958784824956 us: 3375 : [tid:0x7f9943fff640] Callback: Queue 0x7f9840200000 aborting with error : HSA_STATUS_ERROR_EXCEPTION: An HSAIL operation resulted in a hardware exception. code: 0x1016
Aborted (core dumped)
```

Which works fine on an NVIDIA machine `cu118`
### Versions

PyTorch version: 2.1.0+rocm5.6
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.6.31061-8c743ae5d

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Instinct MI250X/MI250
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.6.31061
MIOpen runtime version: 2.20.0
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      48 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             128
On-line CPU(s) list:                0-127
Vendor ID:                          AuthenticAMD
Model name:                         AMD EPYC 7763 64-Core Processor
CPU family:                         25
Model:                              1
Thread(s) per core:                 1
Core(s) per socket:                 64
Socket(s):                          2
Stepping:                           1
Frequency boost:                    enabled
CPU max MHz:                        3529.0520
CPU min MHz:                        1500.0000
BogoMIPS:                           4890.97
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                     AMD-V
L1d cache:                          4 MiB (128 instances)
L1i cache:                          4 MiB (128 instances)
L2 cache:                           64 MiB (128 instances)
L3 cache:                           512 MiB (16 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-63
NUMA node1 CPU(s):                  64-127
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton-rocm==2.1.0
[pip3] torch==2.1.0+rocm5.6
[pip3] torchaudio==2.1.0+rocm5.6
[pip3] torchvision==0.16.0+rocm5.6
[conda] Could not collect

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by hongxiayang** [comment]
I am able to reproduce this. Will look into it.

**Comment by hongxiayang** [comment]
@IlyasMoutawwakil  I compared the behaviors of your code on Nvidia GPU and AMD Gpu, and found that, after the model is loaded to("meta"), and then sent to "cuda" with the model.to_empty( ) call, the parameters in NVidia side are zeroed out, while on AMD side, they are garbage values (example model.bert.encoder.layer[1].attention.self.query.weight), there is why the index exception happened when doing an embedding lookup.

So, the question is:

Why you want to do this? 
Is this supposed to be undefined behavior anyway, since meta device is used to contain the shape only, without real data. 

So, when you loaded the model to the meta device, it does not contain storage, nor the valid model parameters. So, we should not expect when .to_empty("cuda") is called, the valid parameter will be there anyway. Therefore it is undefined.

**Comment by IlyasMoutawwakil** [comment]
I don't see how that would cause an index exception, shouldn't it just return one of the garbage values in the lookup table ?
I use this feature to benchmark model/hardware performance without downloading, loading or initializing the weights, ie a fast way to materialize a model.

**Comment by hongxiayang** [comment]
@IlyasMoutawwakil 

I have updated your test script with below dummy_input, and now it ran fine:
```
dummy_input = {
    "input_ids": torch.randint(1, 10, (1, 128), device="cuda"),
    "attention_mask": torch.ones((1, 128), device="cuda"),
    "token_type_ids": torch.randint(0, 1, (1, 128), device="cuda"),
    "position_ids": torch.randint(0, 1, (1, 128), device="cuda"),
    #below also works fine
    #"token_type_ids": torch.Tensor(1,128).to(torch.int64).fill_(0).to("cuda"),
    #"position_ids": torch.Tensor(1,128).to(torch.int64).fill_(0).to("cuda"),
}
```

Can you update on your side and confirm?
Thanks.

**Comment by hongxiayang** [comment]
The problem is that, if no such parameters are sent, below code will create those parameter with undefined numbers that are much bigger than the corresponding embedding's original size.
![image](https://github.com/pytorch/pytorch/assets/62075498/5d0a9087-2db1-4c48-9c1f-9ff20b08aa12)

**Comment by hongxiayang** [comment]
@IlyasMoutawwakil  Please confirm. We are planning to close this issue in a few days if there is no response. Thanks.

**Comment by IlyasMoutawwakil** [comment]
Thank you @hongxiayang I confirm it works when all inputs are specified
