### ISSUE TITLE
Ubuntu 16.04 setup.py error - Failed to run 'bash ../tools/build_pytorch_libs.sh

### ISSUE THREAD

**Issue by nicksterlingtek** [pytorch/pytorch#11213]
Hello, I have been trying to install pytorch for roughly a week now, and I created a dual boot just for that purpose. The setup.py tool runs until it gets to 100% and then I get the following error. If anybody has any recommendations, I would be appreciate a ton!

$ python setup.py install

...

[100%] Linking CXX executable ../../bin/test_api
/usr/bin/ld: warning: libnvidia-fatbinaryloader.so.396.44, needed by /usr/lib/x86_64-linux-gnu/libcuda.so, not found (try using -rpath or -rpath-link)
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Get_FatBinary_From_Object'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_section_header'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `gpuInfoRunsOn'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf_end'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_shnum'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `fatBinaryCtl'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_symbol_shndx'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Free_Fatbinary'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_string_at_offset'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_symbol_shndx'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `fatBinaryCtl_Compile'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_file_header'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `fatBinaryCtl_PickCandidate'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_string_at_offset'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Start'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_typed_section_header'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Finish'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `gpucompSetLogLine'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Next_Library_Member'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_section_name'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf_is_64bit'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf_size'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `fatBinaryCtl_Delete'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_symbol_name'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_shnum'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Add_Cubin'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_section_contents'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_section_header'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_named_section_header'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Delete'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Finish_Reading_Library'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_typed_section_header'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `gpucompRestoreLogLine'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_file_header'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Load_Host_Object'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Start_Reading_Library'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Free_Host_Object'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_named_section_header'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_symbol_name'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_section_name'
/usr/lib/x86_64-linux-gnu/libcuda.so: undefined reference to `fatBinaryCtl_Create'
collect2: error: ld returned 1 exit status
caffe2/torch/CMakeFiles/test_api.dir/build.make:345: recipe for target 'bin/test_api' failed
make[2]: *** [bin/test_api] Error 1
CMakeFiles/Makefile2:3810: recipe for target 'caffe2/torch/CMakeFiles/test_api.dir/all' failed
make[1]: *** [caffe2/torch/CMakeFiles/test_api.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 libshm gloo THD c10d'

**Comment by AshStuff** [comment]
did you try `bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 libshm gloo THD c10d` ?

**Comment by ashar-ali** [comment]
I am also facing the exact same issue. Were you able to solve this?

**Comment by nicksterlingtek** [comment]
Have not been able to solve. Still working at it. Uninstalled and reinstalled the cuDNN libraries but same error.

**Comment by deepali-c** [comment]
Please check if library `libnvidia-fatbinaryloader.so.396.44` is present on the system and if its path is on LD_LIBRARY_PATH.

**Comment by nicksterlingtek** [comment]
Thank you @deepali-c! I did this .....

$ sudo cp /usr/lib/nvidia-396/libnvidia-fatbinaryloader.so.396.44 /usr/local/cuda-9.2/lib64/
$ ./tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 libshm gloo THD c10d

OUTPUT

-- Found a library with BLAS API (mkl).
-- Found a library with LAPACK API. (mkl)
-- Found CUDA: /usr/local/cuda-9.2 (found suitable version "9.2", minimum required is "5.5") 
-- CuDNN not found. Compiling without CuDNN support
disabling ROCM because NOT USE_ROCM is set
-- MIOpen not found. Compiling without MIOpen support
-- Could NOT find MKLDNN (missing: MKLDNN_INCLUDE_DIR MKLDNN_LIBRARY) 
-- MKLDNN not found. Compiling without MKLDNN support
-- GCC 5.4.0: Adding gcc and gcc_s libs to link line
CMake Error at third_party/sleef/CMakeLists.txt:27 (message):
  SLEEF does not allow in-source builds.

  You can refer to doc/build-with-cmake.md for instructions on how provide a
  separate build directory.  Note: Please remove autogenerated file
  `CMakeCache.txt` and directory `CMakeFiles` in the current directory.


-- Configuring incomplete, errors occurred!
See also "/media/nick/Windows/Development/workspaces/pytorch/CMakeFiles/CMakeOutput.log".
See also "/media/nick/Windows/Development/workspaces/pytorch/CMakeFiles/CMakeError.log".

**Comment by AshStuff** [comment]
@nicksterlingtek did you try after deleting `CMakeCache.txt` and `CMakeFiles` ? did you try installing `SLEEF` separately and then installing pytorch ?

**Comment by nicksterlingtek** [comment]
Thank you, @AshStuff. I ended up installing Ubuntu 18.04 and this allowed me initially to get around this error (but install did not show up in the conda env). I have a similar error now, but it is not SLEEF-related, although I have been deleting the cache.

**Comment by vfdev-5** [comment]
I experience the same error on MacOSX 10.13. Following installation description from [here](https://github.com/pytorch/pytorch#from-source), I got 
```
[ 81%] Linking CXX shared library ../lib/libcaffe2_gpu.dylib
ld: warning: directory not found for option '-L/Users/vfomin/Documents/ML/pytorch/torch/lib/tmp_install/lib'
Undefined symbols for architecture x86_64:
  "_MPI_Comm_free", referenced from:
      caffe2::MPICommonWorldWrapper::~MPICommonWorldWrapper() in mpi_ops_gpu.cc.o
  "_MPI_Comm_rank", referenced from:
      caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
  "_MPI_Comm_size", referenced from:
      caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
  "_MPI_Comm_split", referenced from:
      caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
  "_MPI_Finalized", referenced from:
      caffe2::MPICommonWorldWrapper::~MPICommonWorldWrapper() in mpi_ops_gpu.cc.o
  "caffe2::TypeIdentifier caffe2::TypeMeta::Id<caffe2::MPICommonWorldWrapper>()", referenced from:
      caffe2::MPICreateCommonWorldOp<caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
  "_ompi_mpi_comm_null", referenced from:
      caffe2::MPICreateCommonWorldOp<caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
      void caffe2::TypeMeta::_Ctor<caffe2::MPICommonWorldWrapper>(void*, unsigned long) in mpi_ops_gpu.cc.o
      caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcaffe2_gpu.dylib] Error 1
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack caffe2 libshm THD'
```

**Comment by tastyminerals** [comment]
> @nicksterlingtek did you try after deleting `CMakeCache.txt` and `CMakeFiles` ? did you try installing `SLEEF` separately and then installing pytorch ?
Installing SLEEF manually from source does and after that running the clean build again does not solve this issue.

**Comment by sungwonida** [comment]
I've got the same issue under macOS 10.13.6. I use CUDA 9.2, cuDNN 7.2.1, llvm 9.0.  
My compilation ended up with logs below.

```console
[ 78%] Linking CXX shared library ../lib/libcaffe2_gpu.dylib
ld: warning: directory not found for option '-L/Users/USER/Development/pytorch/pytorch/torch/lib/tmp_install/lib'
Undefined symbols for architecture x86_64:
  "_MPI_Comm_rank", referenced from:
      caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
  "_MPI_Comm_size", referenced from:
      caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
  "_MPI_Comm_split", referenced from:
      caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
  "_ompi_mpi_comm_null", referenced from:
      caffe2::MPICreateCommonWorldOp<caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
      caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcaffe2_gpu.dylib] Error 1
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-qnnpack caffe2'
```

**Comment by zhonhel** [comment]
same issue....

**Comment by bpinaya** [comment]
I had the same issue, a fresh install solved it (removing the pytorch directory and doing the install steps from scratch).
Using CUDA 9.2, cudnn 7.3.1.20

**Comment by my-hello-world** [comment]
I had the same issue

**Comment by oracleyue** [comment]
> I've got the same issue under macOS 10.13.6. I use CUDA 9.2, cuDNN 7.2.1, llvm 9.0.
> My compilation ended up with logs below.
> 
> ```
> [ 78%] Linking CXX shared library ../lib/libcaffe2_gpu.dylib
> ld: warning: directory not found for option '-L/Users/USER/Development/pytorch/pytorch/torch/lib/tmp_install/lib'
> Undefined symbols for architecture x86_64:
>   "_MPI_Comm_rank", referenced from:
>       caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
>   "_MPI_Comm_size", referenced from:
>       caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
>   "_MPI_Comm_split", referenced from:
>       caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
>   "_ompi_mpi_comm_null", referenced from:
>       caffe2::MPICreateCommonWorldOp<caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
>       caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [lib/libcaffe2_gpu.dylib] Error 1
> make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
> make: *** [all] Error 2
> Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-qnnpack caffe2'
> ```

This is most likely due to your current openmpi library is not CUDA-aware. You have to reinstall it by compiling from source; or, if you have only one GPU, disable the MPI config in compilation.

**Comment by HerculesJack** [comment]
Hi, I just solved this issue. See #17139.

**Comment by qmpzzpmq** [comment]
@sungwonida Have you fix it? I have the same issue

**Comment by qmpzzpmq** [comment]
@vfdev-5 Have you fix it? I have the same issue

**Comment by Noirai** [comment]
> > I've got the same issue under macOS 10.13.6. I use CUDA 9.2, cuDNN 7.2.1, llvm 9.0.
> > My compilation ended up with logs below.
> > ```
> > [ 78%] Linking CXX shared library ../lib/libcaffe2_gpu.dylib
> > ld: warning: directory not found for option '-L/Users/USER/Development/pytorch/pytorch/torch/lib/tmp_install/lib'
> > Undefined symbols for architecture x86_64:
> >   "_MPI_Comm_rank", referenced from:
> >       caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
> >   "_MPI_Comm_size", referenced from:
> >       caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
> >   "_MPI_Comm_split", referenced from:
> >       caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
> >   "_ompi_mpi_comm_null", referenced from:
> >       caffe2::MPICreateCommonWorldOp<caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
> >       caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
> > ld: symbol(s) not found for architecture x86_64
> > clang: error: linker command failed with exit code 1 (use -v to see invocation)
> > make[2]: *** [lib/libcaffe2_gpu.dylib] Error 1
> > make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
> > make: *** [all] Error 2
> > Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-qnnpack caffe2'
> > ```
> 
> This is most likely due to your current openmpi library is not CUDA-aware. You have to reinstall it by compiling from source; or, if you have only one GPU, disable the MPI config in compilation.

Same problem here, macOS 10.13 / CUDA 10. I have compiled open-mpi with cuda support from source (4.0.0) but the error still occurred.

**Comment by Noirai** [comment]
Found the solution:
1. Build OpenMPI from source
(Get OpenMPI-4.0.0 and compile using Intel Fortran Compiler. You can get the compiler by installing the trail version of Intel Parallel Studio XE, and follow this guide https://github.com/firemodels/fds/wiki/Installing-Open-MPI-on-OS-X)
2. Instead of using clang (I'm on macOS) to compile pytorch directly, use mpicc/mpicxx and change the wrapper compiler to clang:
sudo MACOSX_DEPLOYMENT_TARGET=10.9 CC=mpicc CXX=mpicxx OMPI_CXX=clang++ OMPI_MPICC=clang python setup.py install

Successfully compiled on macOS 10.13 / CUDA 10. 
Maybe a similar solution could be applied to Ubuntu as well.

**Comment by TomHeaven** [comment]
@Noirai That works for me!

**Comment by ezyang** [comment]
I am not sure how many people on this issue got exactly the "undefined reference to elfLink_Get_FatBinary_From_Object" error. If you got *specifically* that error, please emoji this comment.

**Comment by hoonkai** [comment]
@Noirai Unfortunately that doesn't work for me. I've already compiled OpenMPI (with CUDA) and I'm getting the following:

```
[ 81%] Linking CXX shared library ../lib/libcaffe2_gpu.dylib
Undefined symbols for architecture x86_64:
  "_MPI_Allgather", referenced from:
      caffe2::MPIAllgatherOp<float, caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
  "_MPI_Allreduce", referenced from:
      caffe2::MPIAllreduceOp<float, caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
  "_MPI_Bcast", referenced from:
      caffe2::MPIBroadcastOp<caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
  "_MPI_Comm_rank", referenced from:
      caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
  "_MPI_Comm_size", referenced from:
      caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
  "_MPI_Comm_split", referenced from:
      caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
  "_MPI_Recv", referenced from:
      caffe2::MPIReceiveTensorOp<caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
  "_MPI_Reduce", referenced from:
      caffe2::MPIReduceOp<float, caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
  "_MPI_Send", referenced from:
      caffe2::MPISendTensorOp<caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
  "_ompi_mpi_char", referenced from:
      caffe2::MPIBroadcastOp<caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
      caffe2::MPISendTensorOp<caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
      caffe2::MPIReceiveTensorOp<caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
  "_ompi_mpi_comm_null", referenced from:
      caffe2::MPICreateCommonWorldOp<caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
      caffe2::MPICommonWorldWrapper::MPICommonWorldWrapper(ompi_communicator_t*, int, int) in mpi_ops_gpu.cc.o
  "_ompi_mpi_float", referenced from:
      caffe2::MPIReduceOp<float, caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
      caffe2::MPIAllgatherOp<float, caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
      caffe2::MPIAllreduceOp<float, caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
  "_ompi_mpi_op_sum", referenced from:
      caffe2::MPIReduceOp<float, caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
      caffe2::MPIAllreduceOp<float, caffe2::CUDAContext>::RunOnDevice() in mpi_ops_gpu.cc.o
ld: symbol(s) not found for architecture x86_64
```

I get the same errors as @vfdev-5 if Open MPI wasn't compiled with CUDA though.
