### ISSUE TITLE
bsr_dense_mm produces invalid tensor when out argument is a non-contiguous tensor

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#113754]
## Issue description

As in the title.

## Code example

```python
>>> import torch
>>> from torch.sparse._triton_ops import bsr_dense_mm
>>> dtype = torch.float16
>>> M, K, N = (16, 16, 16)
>>> bsr = torch.ones((M, K), dtype=dtype, device='cuda').to_sparse_bsr(16)
<stdin>:1: UserWarning: Sparse BSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at ../aten/src/ATen/SparseCsrTensorImpl.cpp:53.)
>>> dense = torch.ones((K, N), dtype=dtype, device='cuda')
>>> out = torch.empty((M, N), dtype=dtype, device='cuda').transpose(-1, -2).contiguous().transpose(-1, -2)
>>> r = bsr_dense_mm(bsr, dense, out=out)
>>> r[0, 0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paperspace/miniconda3/envs/nightly20231114py310/lib/python3.10/site-packages/torch/_tensor.py", line 445, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/home/paperspace/miniconda3/envs/nightly20231114py310/lib/python3.10/site-packages/torch/_tensor_str.py", line 664, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/home/paperspace/miniconda3/envs/nightly20231114py310/lib/python3.10/site-packages/torch/_tensor_str.py", line 595, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/paperspace/miniconda3/envs/nightly20231114py310/lib/python3.10/site-packages/torch/_tensor_str.py", line 329, in _tensor_str
    self = self.float()
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

The expected result is the same as when out argument is a contiguous tensor:
```python
>>> out = torch.empty((M, N), dtype=dtype, device='cuda')
>>> r = bsr_dense_mm(bsr, dense, out=out)
>>> r[0, 0]
tensor(16., device='cuda:0', dtype=torch.float16)
```

This is likely a Triton issue.

## System Info

- PyTorch version: nightly20231114py310
- Triton version: 2.1.0+6e4932cda8

cc @alexsamardzic @nikitaved @cpuhrsch @amjames @bhosmer

**Comment by amjames** [comment]
Is it possible this is related to https://github.com/openai/triton/issues/2229

AFAIK the commit pin has not yet been moved past the fix for that issue. 

There was a bug where some dynamic params to the kernel were treated like constexpr if the kernel had a lot of params. In the repo I posted for that issue some of the final stride params were given constant value of 1 rather than their actual value at runtime.

**Comment by pearu** [comment]
After testing the issue against https://github.com/openai/triton/pull/2262, I confirm that it indeed fixes this issue as well.

Otherwise, I now have also a fix to bsr_dense_mm kernel to support both C and F-contiguous outputs, just for the case if it takes too long to update the triton pin.

**Comment by cpuhrsch** [comment]
Let's land the fix to our kernel first, because moving the Triton pin can take quite some time.
