### ISSUE TITLE
torch.compile CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#113788]
### 🐛 Describe the bug

```
  File "torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "foo.py", line 710, in forward
    def forward(self, x, task_info=None):
  File "torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/backends/distributed.py", line 247, in forward
    x = self.submod(*args)
  File "torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 2836, in forward
    return compiled_fn(full_args)
  File "torch/_functorch/aot_autograd.py", line 1224, in g
    return f(*args)
  File "torch/_functorch/aot_autograd.py", line 2403, in debug_compiled_function
    return compiled_function(*args)
  File "torch/_functorch/aot_autograd.py", line 1900, in runtime_wrapper
    all_outs = call_func_with_args(
  File "torch/_functorch/aot_autograd.py", line 1249, in call_func_with_args
    out = normalize_as_list(f(args))
  File "torch/_functorch/aot_autograd.py", line 1224, in g
    return f(*args)
  File "torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "torch/_functorch/aot_autograd.py", line 2168, in forward
    fw_outs = call_func_with_args(
  File "torch/_functorch/aot_autograd.py", line 1249, in call_func_with_args
    out = normalize_as_list(f(args))
  File "torch/_inductor/compile_fx.py", line 248, in run
    return model(new_inputs)
  File "/tmp/tmpa69uq6d9/hx/chxb54dg3bfkyer77ywbztmwwszekrfkk6qsbcauqajkfkmmfvul.py", line 12300, in call
    extern_kernels.bmm(buf1198, as_strided(buf1199, (8, 192, 384), (0, 384, 1)), out=buf1200)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmStridedBatchedExFix(handle, opa, opb, (int)m, (int)n, (int)k, (void*)&falpha, a, CUDA_R_16BF, (int)lda, stridea, b, CUDA_R_16BF, (int)ldb, strideb, (void*)&fbeta, c, CUDA_R_16BF, (int)ldc, stridec, (int)num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
Exception raised from bgemm<c10::BFloat16> at ../aten/src/ATen/cuda/CUDABlas.cpp:300 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x1555394d2d8c in torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xfa (0x155539498f6a in torch/lib/libc10.so)
frame #2: <unknown function> + 0x3053fa9 (0x1554e065bfa9 in torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0x3088366 (0x1554e0690366 in torch/lib/libtorch_cuda.so)
frame #4: at::native::structured_bmm_out_cuda::impl(at::Tensor const&, at::Tensor const&, at::Tensor const&) + 0x76 (0x1554e0691646 in torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x2d64016 (0x1554e036c016 in torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x4374955 (0x155505227955 in torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x3c50b8d (0x155504b03b8d in torch/lib/libtorch_cpu.so)
frame #8: at::_ops::bmm_out::call(at::Tensor const&, at::Tensor const&, at::Tensor&) + 0x17c (0x155503001ecc in torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x64b133 (0x155509a08133 in torch/lib/libtorch_python.so)
````

### Versions

PyTorch 2.0.1

cc @ezyang @gchanan @zou3519 @kadeng @mrshenli @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @msaroufim @bdhirsh @anijain2305 @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @muchulee8 @aakhundov @ColinPeppler @kiukchung @lucasllc @d4l3k

**Comment by ezyang** [comment]
if you're able to get the stride on buf1198 that probably would be helpful for NVIDIA to repro

**Comment by pritamdamania87** [comment]
@ezyang `buf1198.size()=torch.Size([8, 384, 192]) buf1198.stride()=(73728, 1, 384) buf1199.size()=torch.Size([1, 192, 24, 16]) buf1199.stride()=(73728, 384, 16, 1)`

However, when I run the file locally it doesn't fail at this line, but instead fails here (similar to https://github.com/pytorch/pytorch/issues/113740):

```
  File "/tmp/tmpa69uq6d9/hx/chxb54dg3bfkyer77ywbztmwwszekrfkk6qsbcauqajkfkmmfvul.py", line 13479, in call
    assert_size_stride(buf1711, (8, 480, 1, 30), (14400, 1, 14400, 480))
AssertionError: expected size 480==480, stride 30==1 at dim=1
```

**Comment by pritamdamania87** [comment]
`torch._dynamo.config.optimize_ddp=False` seems to mitigate this issue.

**Comment by wconstab** [comment]
@pritamdamania87 same comment here:

"can you please either attach a repro or confirm if this is fixed by enabling optimize_ddp_lazy_compile=True? lazy compile was designed to help with cases where sizes/strides didn't match "

**Comment by eellison** [comment]
This was fixed recently by https://github.com/pytorch/pytorch/pull/120523.
