### ISSUE TITLE
torch.compile CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#113786]
### 🐛 Describe the bug

```
  File "torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "foo.py", line 710, in forward
    def forward(self, x, task_info=None):
  File "torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/backends/distributed.py", line 247, in forward
    x = self.submod(*args)
  File "torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 2836, in forward
    return compiled_fn(full_args)
  File "torch/_functorch/aot_autograd.py", line 1224, in g
    return f(*args)
  File "torch/_functorch/aot_autograd.py", line 2403, in debug_compiled_function
    return compiled_function(*args)
  File "torch/_functorch/aot_autograd.py", line 1900, in runtime_wrapper
    all_outs = call_func_with_args(
  File "torch/_functorch/aot_autograd.py", line 1249, in call_func_with_args
    out = normalize_as_list(f(args))
  File "torch/_functorch/aot_autograd.py", line 1224, in g
    return f(*args)
  File "torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "torch/_functorch/aot_autograd.py", line 2168, in forward
    fw_outs = call_func_with_args(
  File "torch/_functorch/aot_autograd.py", line 1249, in call_func_with_args
    out = normalize_as_list(f(args))
  File "torch/_inductor/compile_fx.py", line 248, in run
    return model(new_inputs)
  File "/tmp/tmpcpxlo7gw/hx/chxb54dg3bfkyer77ywbztmwwszekrfkk6qsbcauqajkfkmmfvul.py", line 12291, in call
    buf1197 = aten.convolution(buf1193, buf1196, None, (1, 1), (0, 0), (1, 1), False, (0, 0), 1)
  File "torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
Exception raised from getCudnnHandle at ../aten/src/ATen/cudnn/Handle.cpp:48 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x1555394d2d8c in torch/lib/libc10.so)
frame #1: <unknown function> + 0xd2cc13 (0x1554de334c13 in torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xf05b5a (0x1554de50db5a in torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xf06b23 (0x1554de50eb23 in torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xeea65e (0x1554de4f265e in torch/lib/libtorch_cuda.so)
frame #5: at::native::cudnn_convolution(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) + 0xaa (0x1554de4f2cca in torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x2d420b4 (0x1554e034a0b4 in torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x2d421a4 (0x1554e034a1a4 in torch/lib/libtorch_cuda.so)
frame #8: at::_ops::cudnn_convolution::call(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) + 0x250 (0x155503010620 in torch/lib/libtorch_cpu.so)
frame #9: at::native::_convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool, bool) + 0xfa7 (0x155502385eb7 in torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x25622ca (0x1555034152ca in torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x2562399 (0x155503415399 in torch/lib/libtorch_cpu.so)
frame #12: at::_ops::_convolution::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long, bool, bool, bool, bool) + 0x29b (0x155502b4050b in torch/lib/libtorch_cpu.so)
frame #13: at::native::convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long) + 0x15a (0x15550237c50a in torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x2561b30 (0x155503414b30 in torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x2561bb7 (0x155503414bb7 in torch/lib/libtorch_cpu.so)
frame #16: at::_ops::convolution::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long) + 0x14a (0x155502b0186a in torch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x39de272 (0x155504891272 in torch/lib/libtorch_cpu.so)
frame #18: <unknown function> + 0x3a585f0 (0x15550490b5f0 in torch/lib/libtorch_cpu.so)
frame #19: c10::Dispatcher::callBoxed(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*) const + 0x23c (0x155501fbe33c in torch/lib/libtorch_cpu.so)
frame #20: torch::jit::invokeOperatorFromPython(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, pybind11::args, pybind11::kwargs const&, c10::optional<c10::DispatchKey>) + 0x4cd (0x155509cab4ad in torch/lib/libtorch_python.so)
frame #21: torch::jit::_get_operation_for_overload_or_packet(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, c10::Symbol, pybind11::args, pybind11::kwargs const&, bool, c10::optional<c10::DispatchKey>) + 0x6a8 (0x155509cabef8 in torch/lib/libtorch_python.so)
frame #22: <unknown function> + 0x7d695b (0x155509b9395b in torch/lib/libtorch_python.so)
frame #23: <unknown function> + 0x3dc8db (0x1555097998db in torch/lib/libtorch_python.so)
```

### Versions

Pytorch 2.0.1

cc @ezyang @gchanan @zou3519 @kadeng @mrshenli @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @msaroufim @bdhirsh @anijain2305 @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @muchulee8 @aakhundov @ColinPeppler @kiukchung @lucasllc @d4l3k

**Comment by ezyang** [comment]
ditto here, sizes and strides of the call that is failing. You should be able to edit the generated file directly, assuming that if you run it it also repros.

**Comment by pritamdamania87** [comment]
@ezyang 

```
buf1193.size()=torch.Size([8, 48, 24, 16]) buf1196.size()=torch.Size([192, 48, 1, 1])
buf1197 = aten.convolution(buf1193, buf1196, None, (1, 1), (0, 0), (1, 1), False, (0, 0), 1)
````

However, when I run the file locally it doesn't fail at this line, but instead fails here (similar to https://github.com/pytorch/pytorch/issues/113740):

```
  File "/tmp/tmpcpxlo7gw/hx/chxb54dg3bfkyer77ywbztmwwszekrfkk6qsbcauqajkfkmmfvul.py", line 13479, in call
    assert_size_stride(buf1711, (8, 480, 1, 30), (14400, 1, 14400, 480))
AssertionError: expected size 480==480, stride 30==1 at dim=1
```

**Comment by ysj-xuanyuan** [comment]
I had the same problem when using `torch.compile(model,mode="max-autotune")`. But `torch.compile(model) `works fine. Tried some of the above and still no solution. Any good solution please?

**Comment by wconstab** [comment]
@pritamdamania87 can you please either attach a repro or confirm if this is fixed by enabling optimize_ddp_lazy_compile=True?  lazy compile was designed to help with cases where sizes/strides didn't match

**Comment by pritamdamania87** [comment]
We have a workaround currently with `torch._dynamo.config.optimize_ddp=False` and currently this is not a perf issue. If we do indeed need to use the ddp optimizer later, we can try and enable that flag.

**Comment by wconstab** [comment]
Ok- we'll close the issue for now as it is in actionable without a repro.

**Comment by wconstab** [comment]
Well on second thought, we can at least try to make our own repro if we can reverse engineer, otherwise close if not

**Comment by eellison** [comment]
This was fixed recently by https://github.com/pytorch/pytorch/pull/120523.
