### ISSUE TITLE
`torch.distributed.destroy_process_group()` hangs after CUDA graph capture of NCCL operations

### ISSUE THREAD

**Issue by cbcase** [pytorch/pytorch#115388]
### 🐛 Describe the bug

When I use the CUDA graphs API to capture execution of a model that performs NCCL collectives as part of that execution, it puts the NCCL process group into a state where it cannot cleanly exit -- a call to `destroy_process_group()` hangs. Squinting at a profile, it looks like it is a hang in `ncclCommDestroy`. Here is a fairly small reproducer:

```
import os

import torch
import torch.distributed as dist

class Model(torch.nn.Module):
    def __init__(self, dim, nlayers):
        super().__init__()
        self.layers = torch.nn.ModuleList()
        for _ in range(nlayers):
            self.layers.append(torch.nn.Linear(dim, dim, bias=False))

    @torch.inference_mode()
    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
            dist.all_reduce(x)
        return x

def main():
    os.environ["NCCL_ASYNC_ERROR_HANDLING"] = "0"
    dist.init_process_group(backend="nccl")
    rank = dist.get_rank()
    my_device = f"cuda:{rank}"
    torch.cuda.set_device(my_device)

    model = Model(2048, 12)
    model.cuda()

    g = torch.cuda.CUDAGraph()
    static_input = torch.empty((1024, 2048), dtype=torch.float32, device=my_device)
    s = torch.cuda.Stream()
    s.wait_stream(torch.cuda.current_stream())
    # Warmup
    with torch.cuda.stream(s):
        for _ in range(11):
            static_output = model(static_input)
    torch.cuda.current_stream().wait_stream(s)
    with torch.cuda.graph(g):
        static_output = model(static_input)

    torch.cuda.synchronize()
    print("Calling destroy_process_group()...")
    dist.destroy_process_group()
    print("Done.")

if __name__ == "__main__":
    main()
```
Assuming this file is `test.py`, I ran it with:
```
torchrun --standalone --nproc-per-node 2 test.py
```
and you see both processes hang with `Calling destroy_process_group()...`.

A few more notes:
- It doesn't appear to matter whether you every replay the graph (I don't in the example above)
- But if you remove the graph capture itself, it exits cleanly
- And if you remove the `dist.all_reduce()` call inside the model definition, it also exits cleanly

For long-running training jobs, this isn't much of an issue, but for various testing and inference workloads, it is useful to have short-lived process groups (usually spawned with `torch.multiprocessing`), and it's important to clean those up without needing to tear down the parent process as well.

### Versions

Collecting environment information...
PyTorch version: 2.1.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.4
Libc version: glibc-2.31

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A5000
GPU 1: NVIDIA RTX A5000
GPU 2: NVIDIA RTX A5000
GPU 3: NVIDIA RTX A5000

Nvidia driver version: 535.54.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              1
Core(s) per socket:              64
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7513 32-Core Processor
Stepping:                        1
CPU MHz:                         2599.998
BogoMIPS:                        5199.99
Virtualization:                  AMD-V
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        32 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr wbnoinvd arat npt lbrv nrip_save tsc_scale vmcb_clean pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq rdpid arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] torch==2.1.0+cu121
[pip3] torch-tb-profiler==0.4.1
[pip3] torchaudio==2.1.0+cu121
[pip3] torchvision==0.16.0+cu121
[pip3] triton==2.1.0
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] torch                     2.1.0+cu121              pypi_0    pypi
[conda] torch-tb-profiler         0.4.1                    pypi_0    pypi
[conda] torchaudio                2.1.0+cu121              pypi_0    pypi
[conda] torchvision               0.16.0+cu121             pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by wconstab** [comment]
Repro's for me. taking a look

**Comment by eqy** [comment]
@wconstab 
That check was added [here](https://github.com/pytorch/pytorch/pull/110665) because eager-mode NCCL will issue event queries which will crash during graph capture. It should not deadlock unless the number of event queries is not being decremented somewhere...

**Comment by GuWei007** [comment]
> Repro's for me. taking a look
> 
> I've added these 3 envs to aid in debugging. I also want to point out that we're in the process of flipping MONITORING on by default, which will convert this hang into a crash (slightly less annoying, but obviously not a fix for your issue) `TORCH_CPP_LOG_LEVEL=INFO TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC=5 TORCH_NCCL_ENABLE_MONITORING=1`
> 
> The info logs point to something interesting:
> 
> ```
> [rank0]:[W CUDAGraph.cpp:145] Warning: Waiting for pending NCCL work to finish before starting graph capture. (function operator())
> [rank1]:[W CUDAGraph.cpp:145] Warning: Waiting for pending NCCL work to finish before starting graph capture. (function operator())
> Calling destroy_process_group()...
> Calling destroy_process_group()...
> ```
> 
> cc @eellison @fduwjj
> 
> Actually, i want to refine the issue at this point. What do you expect to happen here-
> 
> (1) it should not hang. We agree, and that's actually why we introduced the heartbeat monitor. (Sometimes, nccl/CUDA APIs themselves hang when we call them, and we work offline with NV on whether those are bugs or whether we need to change how we use the APIs. But in the mean time, we claim that after enabling heartbeat monitoring we will never hang in the watchdog/PG destructor. So that particular issue should be solved now, since the PR to enable heartbeat monitoring has already landed (#115577) and I've verified it kills the program as expected in your case.
> 
> (2) are we using cudagraphs correctly here? if so, why is it 'waiting for nccl ops to finish' and what do we need to do to fix that? (cc @eellison)

Where can I find the documentation and application scenario description of TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC? This environment variable is very valuable for me to analyze hang

**Comment by wconstab** [comment]
There isn't a whole lot of documentation for this yet, but there is something here
https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.hpp#L77

You can see the implementation of the monitor thread here:
https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L1234

The monitor thread actually runs all the time, and the env `TORCH_NCCL_ENABLE_MONITORING` governs whether it just prints a warning when it detects a hang (0) or actually terminates the process (1).  The timeout value governs how long it waits for watchdog activity before it declares a hang.

**Comment by grimoire** [comment]
I have met a similar problem.

`graph.reset()` before destroying pg would trigger use-count assert:
```
terminate called after throwing an instance of 'c10::Error'
  what():  uc >= 0 INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":2138, please report a bug to PyTorch.
```

And `del graph` at the end of each process works on me.

**Comment by wconstab** [comment]
@grimoire are you saying that if you put `del graph` into the repro script at the top of the issue, it stops hanging? Can you be more specific about which line you insert it after?

@eellison can you take a look at whether we need to do something 'atexit' from the context manager to decrement the cudagraph counter in C10d?

**Comment by grimoire** [comment]
@wconstab 

Sure. Add either `del g` or `g.reset()` in the script provided by @cbcase works on `torch==2.2.2 A100`. `g.reset()` failed on `torch==2.1.0 V100`

```python
    torch.cuda.synchronize()
    print("Calling destroy_process_group()...")
    del g
    # g.reset()
    dist.destroy_process_group()
    print("Done.")
```

```
Calling destroy_process_group()...
Calling destroy_process_group()...
Done.
Done.
```

**Comment by victbr** [comment]
Probably the same issue. Unlike using torchrun, I use multiprocess to set up the environment. 

In my case, `dist.destroy_process_group()` did not cause a hang; however, the process failed to terminate properly. Inserting del graph either before or after `dist.destroy_process_group()` resolved the issue. JUst omitting `dist.destroy_process_group()` also work for me. 

There might be a problem in the cleanup phase.

```python
import torch
from torch import distributed as dist
from multiprocessing import Process
import os

def main(rank, world_size):
    os.environ["NCCL_ASYNC_ERROR_HANDLING"] = "0"
    dist.init_process_group(backend="nccl",
                            world_size=world_size,
                            rank=rank
                            )
    torch.cuda.set_device(rank)
    group = dist.group.WORLD
    bsz = 1
    N = 1
    data = torch.randn((bsz, N)).cuda()
    W = torch.randn((N,N)).cuda()
    static_output = torch.empty(bsz,N).cuda()

    with torch.inference_mode():
        s = torch.cuda.Stream()
        s.wait_stream(torch.cuda.current_stream())
        for _ in range(11):
            with torch.cuda.stream(s):
                data *= rank
                dist.all_reduce(data, group=group)
                torch.matmul(data, W, out=data)
        torch.cuda.current_stream().wait_stream(s)
        g = torch.cuda.CUDAGraph()
        mem_pool = None
        with torch.cuda.graph(g, pool=mem_pool):
            data *= rank
            dist.all_reduce(data, group=group)
            temp = data @ W
            static_output.copy_(temp)

        data2 = torch.randn((bsz, N)).cuda()
        W2 = torch.randn((N,N)).cuda()
        data.copy_(data2)
        W.copy_(W2)
        g.replay()
        data2 *= rank
        dist.all_reduce(data2, group=group)
        data3 = data2 @ W2
        assert torch.allclose(static_output, data3), f"{static_output=}, {data3=}"
        dist.destroy_process_group()
        del g
def allreduce_test():
    world_size = 4
    procs = [Process(target=main, args=(rank, world_size)) for rank in range(world_size)]
    for p in procs:
        p.start()
    for p in procs:
        p.join()
    print("finish")
if __name__ == "__main__":
    allreduce_test()
    pass
``` 
I ran with `python <filename>`. on `torch==2.1.0 A100`

**Comment by kwen2501** [comment]
Reason:
When CUDA Graph is on with NCCL operations, NCCL would internally allocate some resources for Graph replay in future. Such allocation calls for free at some point. Today NCCL frees them when the communicator is being destroyed, i.e. when user calls `destroy_process_group`. But during the communicator destruction, NCCL wants to make sure there is no more use of those resources, thus it checks whether the graph object has been destroyed, and wait if not. 

That causes a deadlock if user code does not have a `del graph` before `destroy_process_group`, because the graph object is not garbage-collected until the end of the scope.
