### ISSUE TITLE
No cuda device, but "CUDA driver version is insufficient for CUDA runtime version"

### ISSUE THREAD

**Issue by RangoHU** [pytorch/pytorch#1159]
I am a beginner of pyTorch. I installed a non-cuda pyTorch on my machine, which clearly has no gpu installed, and run the simplest backward() function. But it didn't work out with the following exception:

THCudaCheck FAIL file=torch/csrc/autograd/engine.cpp line=353 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/.local/lib/python2.7/site-packages/torch/autograd/variable.py", line 146, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/autograd/engine.cpp:353

How can I fix it? Thanks!

**Comment by soumith** [comment]
hi there. this is an issue with our current binaries. it will be fixed in 5 hours.

**Comment by RangoHU** [comment]
Got that, thanks!

**Comment by apaszke** [comment]
It's actually a duplicate of #1154, so let's use that issue to track this.

**Comment by tengerye** [comment]
Hi, I don't know why but I do encounter this problem again. It is described at [here](https://github.com/milesial/Pytorch-UNet/issues/8).

**Comment by agadav** [comment]
Dear all, 
I am new with torch.

I also face the error: “RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/cuda/Module.cpp:107”

I am running a code which needs torch version 0.3.x instead of the newest one.
I am using CPU, even though the code was written with CUDA. 
I installed via conda install pytorch=0.3.1 -c pytorch and then I used  pip to install torchvision.

If it is any help, the problem is at line:  
netG.load_state_dict(torch.load(opt.netG))

I would really appreciate it if you could help me.

Thanks in advance!

**Comment by agadav** [comment]
Hi, thank you very much for your reply!

I actually tried using both:
netG.load_state_dict(torch.load(opt.netG, map_location=lambda storage, loc: storage)) 
and
netG.load_state_dict(torch.load(opt.netG, map_location='cpu')).

Unfortunately, then I get in both cases the error: 
KeyError: 'unexpected key "dense_block1.denselayer1.norm.1.weight" in state_dict'.

**Comment by soumith** [comment]
@agadav the error `KeyError: 'unexpected key "dense_block1.denselayer1.norm.1.weight" in state_dict'.` is much more specific and unrelated to the CUDA driver issue that you pointed out

**Comment by tengerye** [comment]
I located my problem: poorness. :sob: 

My problem was solved in better (and more expensive) GPUs.

**Comment by vijay180396** [comment]
CUDA status Error: file: ..\..\src\dark_cuda.c : cuda_set_device() : line: 39 : build time: Mar 26 2020 - 11:11:34

 CUDA Error: CUDA driver version is insufficient for CUDA runtime version
