### ISSUE TITLE
When I put the convolutional layer to cuda, I meet the error

### ISSUE THREAD

**Issue by huahangc** [pytorch/pytorch#116000]
### 🐛 Describe the bug

```
import torch

a = torch.rand(1, 1, 10, 10)
b = torch.nn.Conv2d(1, 1, 1, 1)
b.cuda()(a.cuda())
```
raise python: symbol lookup error: /home/hh/anaconda3/envs/aio/lib/python3.10/site-packages/torch/lib/../../nvidia/cudnn/lib/libcudnn_cnn_infer.so.8: undefined symbol: _ZN15TracebackLoggerC1EPKc, version libcudnn_ops_infer.so.8, but if i use the nn.Linear this error wont appear. How can I solve that?

### Versions

Collecting environment information…
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.21.0
Libc version: glibc-2.31

Python version: 3.10.12 (main, Jul 5 2023, 18:54:27) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.3.58
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-PCIE-40GB
Nvidia driver version: 525.125.06
cuDNN version: Probably one of the following:
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
Address sizes: 46 bits physical, 48 bits virtual
CPU(s): 64
On-line CPU(s) list: 0-63
Thread(s) per core: 2
Core(s) per socket: 16
Socket(s): 2
NUMA node(s): 2
Vendor ID: GenuineIntel
CPU family: 6
Model: 79
Model name: Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz
Stepping: 1
CPU MHz: 1200.000
CPU max MHz: 3000.0000
CPU min MHz: 1200.0000
BogoMIPS: 4199.65
Virtualization: VT-x
L1d cache: 1 MiB
L1i cache: 1 MiB
L2 cache: 8 MiB
L3 cache: 80 MiB
NUMA node0 CPU(s): 0-15,32-47
NUMA node1 CPU(s): 16-31,48-63
Vulnerability Itlb multihit: KVM: Mitigation: VMX disabled
Vulnerability L1tf: Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds: Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown: Mitigation; PTI
Vulnerability Mmio stale data: Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed: Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1: Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2: Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds: Not affected
Vulnerability Tsx async abort: Mitigation; Clear CPU buffers; SMT vulnerable
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] torch==2.1.2
[pip3] triton==2.1.0
[conda] cudatoolkit 11.1.1 ha002fc5_10 conda-forge
[conda] numpy 1.26.2 pypi_0 pypi
[conda] torch 2.1.2 pypi_0 pypi
[conda] triton 2.1.0 pypi_0 pypi

**Comment by kandeldeepak46** [comment]
The bug you're experiencing is a symbol lookup error when using torch.nn.Conv2d on the GPU with PyTorch 2.1.2 and cuDNN 12.1. It seems that the specific error is:

/home/hh/anaconda3/envs/aio/lib/python3.10/site-packages/torch/lib/../../nvidia/cudnn/lib/libcudnn_cnn_infer.so.8: undefined symbol: _ZN15TracebackLoggerC1EPKc, version libcudnn_ops_infer.so.8

This means that PyTorch is trying to find a symbol called _ZN15TracebackLoggerC1EPKc in the library libcudnn_ops_infer.so.8, but the symbol is not present. This can happen for several reasons, including:

Mismatch between cuDNN versions: While you have cuDNN 12.1 installed, there might be a mismatch between the cuDNN version used to build PyTorch (cu121) and the cuDNN version available on your system.
Incorrect library path: The path to the cuDNN libraries might be incorrect in your environment.
Damaged or incomplete cuDNN installation: The cuDNN installation might be corrupted or incomplete.
Here are some steps you can take to troubleshoot and fix the bug:

Verify cuDNN version: Check the cuDNN version used to build PyTorch by running python -c "import torch; print(torch.version.cuda)". Compare it with the cuDNN version you have installed on your system. Make sure they match.
Set the CUDA_VISIBLE_DEVICES environment variable: This variable tells PyTorch which GPUs to use. Try setting it to your desired GPU number (e.g., CUDA_VISIBLE_DEVICES=0).
Reinstall cuDNN: Try reinstalling cuDNN to ensure it's properly installed and configured. Use the appropriate installation guide for your operating system and CUDA version.
Clean the PyTorch cache: Run python -m torch.utils.cpp_extension.build -c clean to clean the PyTorch cache and rebuild the necessary extensions.
Update PyTorch: Consider updating PyTorch to a newer version that might have better compatibility with cuDNN 12.1.
If the issue persists after trying these steps, please provide more information about your system configuration and the exact commands you're running. This will help me diagnose the problem further.

**Comment by huahangc** [comment]
@kandeldeepak46 thanks for your replying. I have solved this problem by creating a new account and re-download the anaconda and pytorch in Ubuntu 20.0.4.
