### ISSUE TITLE
GPU tests can fail with invalid memory access due to compiler generating invalid code

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#116289]
### 🐛 Describe the bug
Initially was reported only on 2.2, but happen on trunk as well, see https://github.com/pytorch/pytorch/actions/runs/7342826148/job/19993362477 for example

HUD link:
https://hud.pytorch.org/hud/pytorch/pytorch/release%2F2.2/1?per_page=50&name_filter=linux-focal-cuda12.1-py3.10-gcc9-sm86

Repro:
``python test/test_ops.py -k test_dtypes__refs_nextafter_cuda``
or
``CUDA_LAUNCH_BLOCKING=1 python test/test_ops.py TestCommonCUDA``

Error:
```
CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    test_dtypes_nextafter_cuda errored - num_retries_left: 3
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 916, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 970, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 1145, in only_fn
    return fn(self, *args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_ops.py", line 1458, in test_dtypes
    self.fail(msg)
AssertionError: The supported dtypes for nextafter on device type cuda are incorrect!
The following dtypes did not work in forward but are listed by the OpInfo: {torch.float64, torch.bfloat16}.
Unexpected failures raised the following errors:
torch.float64 - CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

torch.bfloat16 - CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2652, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2652, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 416, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 922, in test_wrapper
    raise Exception(
Exception: Caused by sample input at index 8: SampleInput(input=Tensor[size=(0, 1, 3), device="cuda:0", dtype=torch.float32], args=TensorList[Tensor[size=(0, 10, 3), device="cuda:0", dtype=torch.float32]], kwargs={}, broadcasts_input=True, name='')

To execute this test, run the following from the base repo dir:
     python test/test_ops.py -k test_dtypes_nextafter_cuda

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

ETEST SUITE EARLY TERMINATION due to torch.cuda.synchronize() failure
CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    test_dtypes_nextafter_cuda errored - num_retries_left: 2
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2826, in setUp
    set_rng_seed(SEED)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1852, in set_rng_seed
    torch.manual_seed(seed)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/random.py", line 40, in manual_seed
    torch.cuda.manual_seed_all(seed)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/random.py", line 126, in manual_seed_all
    _lazy_call(cb, seed_all=True)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/__init__.py", line 232, in _lazy_call
    callable()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/random.py", line 124, in cb
    default_generator.manual_seed(seed)
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


ETEST SUITE EARLY TERMINATION due to torch.cuda.synchronize() failure
CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    test_dtypes_nextafter_cuda errored - num_retries_left: 1
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2826, in setUp
    set_rng_seed(SEED)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1852, in set_rng_seed
    torch.manual_seed(seed)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/random.py", line 40, in manual_seed
    torch.cuda.manual_seed_all(seed)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/random.py", line 126, in manual_seed_all
    _lazy_call(cb, seed_all=True)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/__init__.py", line 232, in _lazy_call
    callable()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/random.py", line 124, in cb
    default_generator.manual_seed(seed)
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


ETEST SUITE EARLY TERMINATION due to torch.cuda.synchronize() failure
CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    test_dtypes_nextafter_cuda errored - num_retries_left: 0

======================================================================
ERROR [0.004s]: test_dtypes_nextafter_cuda (__main__.TestCommonCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2826, in setUp
    set_rng_seed(SEED)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1852, in set_rng_seed
    torch.manual_seed(seed)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/random.py", line 40, in manual_seed
    torch.cuda.manual_seed_all(seed)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/random.py", line 126, in manual_seed_all
    _lazy_call(cb, seed_all=True)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/__init__.py", line 232, in _lazy_call
    callable()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/random.py", line 124, in cb
    default_generator.manual_seed(seed)
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


----------------------------------------------------------------------
Ran 1436 tests in 218.112s

FAILED (errors=1, skipped=597, expected failures=5)
```

### Versions

cc @ptrblck @seemethere @malfet @pytorch/pytorch-dev-infra @mruberry @ZainRizvi

**Comment by huydhn** [comment]
For more context, a similar issue happened in trunk for a few commits https://hud.pytorch.org/hud/pytorch/pytorch/main/3?per_page=50&name_filter=linux.4xlarge.nvidia.gpu then stopped after https://hud.pytorch.org/pytorch/pytorch/commit/2a440348958b3f0a2b09458bd76fe5959b371c0c.  There is no obvious pattern of which trunk commit fixed the issue (if there is any).  More debug is needed

**Comment by eqy** [comment]
CC @ptrblck @nWEIdia in case this is the same IMA issue we have seen earlier---it might be the same race we are seeing during builds that we were also observing.

**Comment by nWEIdia** [comment]
@eqy Yes, telling from the failed kernel name: "NextAfter" is one of the kernels that would give IMA. I would compare the binaries and provide a confirmation later.

**Comment by nWEIdia** [comment]
@huydhn Could you please remind me how to get the wheel from https://github.com/pytorch/pytorch/actions/runs/7251103700/job/19752749109? 

There is one thing I am not sure: all commits had the same error, which means it is deterministic? Is there any possibility that the jobs were pulling from the same bad wheel?

**Comment by nWEIdia** [comment]
@eqy @huydhn 
Good: wget https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/7226203347/linux-focal-cuda12.1-py3.10-gcc9-sm86/artifacts.zip
Bad: wget https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/7251103700/linux-focal-cuda12.1-py3.10-gcc9-sm86/artifacts.zip

Compared the above two binaries. The conclusion is that it bears the same signature as the IMA we encountered internally. 
The issue can go away by itself by a rebuilding and in the long run would be fixed by cuda upgrade.

One thing I am not sure, as I said, is why it appears so deterministic? Could we try a rebuild and test manually?

**Comment by huydhn** [comment]
> @huydhn Could you please remind me how to get the wheel from https://github.com/pytorch/pytorch/actions/runs/7251103700/job/19752749109?
> 
> There is one thing I am not sure: all commits had the same error, which means it is deterministic? Is there any possibility that the jobs were pulling from the same bad wheel?

Hey @nWEIdia, it's nice to see you.  Happy Holidays!

For that job, you can find the artifacts on HUD commit page https://hud.pytorch.org/pytorch/pytorch/commit/da4bf36936e58559c46ccfbe0d97670663f2bfe1.  You can search for the job name and the show artifacts links there

![Screenshot 2023-12-25 at 17 51 52](https://github.com/pytorch/pytorch/assets/475357/fd7d99d7-6263-4f42-aea2-6bb2472535f8)

**Comment by huydhn** [comment]
> One thing I am not sure, as I said, is why it appears so deterministic? Could we try a rebuild and test manually?

Let me try this out and report the results back, the devgpu has cuda 12.1

**Comment by atalman** [comment]
Hey @nWEIdia, it's nice to see you. Merry Christmas! Thank you for the help!

**Comment by malfet** [comment]
Sorry for jumping into the conversation late. I wonder if the failure we are seeing is somehow related to the polluted cache between main and release/2.2 branches. Trying to repro it using the local build right now. Just curios, what is IMA?

**Comment by eqy** [comment]
> what is IMA?

"Illegal Memory Access"

**Comment by malfet** [comment]
One line reproducer:
```
$ python3 -c "import torch;print(torch.nextafter(torch.tensor([-4.5149, -5.9053, -0.9516, -2.3615,  1.5591], device='cuda:0'), torch.tensor(3.8075, device='cuda:0')))"
```
Reproduce 100% of time in the affected CI binaries. Does not reproduce with local build on A100

**Comment by eqy** [comment]
For reference, the compiler fix in LLVM that needs to be backported: https://reviews.llvm.org/D72469

**Comment by atalman** [comment]
Looks like we have same issue in the main branch now: https://github.com/pytorch/pytorch/actions/runs/7343316231/job/19994267389#step:16:10471

**Comment by malfet** [comment]
Removed 2.2 only prefixes, added `triage review` - need to understand how to detect/prevent those

**Comment by malfet** [comment]
> For reference, the compiler fix in LLVM that needs to be backported: https://reviews.llvm.org/D72469

Not sure if reviews.llvm.org are down for everyone or just for me (I though it should be alive until Oct 2024), but here is commit this diff references: https://github.com/llvm/llvm-project/commit/f7e9f4f4c50245d10ca9869a9f8f3d431dfb6948

**Comment by nWEIdia** [comment]
> > @huydhn Could you please remind me how to get the wheel from https://github.com/pytorch/pytorch/actions/runs/7251103700/job/19752749109?
> > There is one thing I am not sure: all commits had the same error, which means it is deterministic? Is there any possibility that the jobs were pulling from the same bad wheel?
> 
> Hey @nWEIdia, it's nice to see you. Happy Holidays!
> 
> For that job, you can find the artifacts on HUD commit page https://hud.pytorch.org/pytorch/pytorch/commit/da4bf36936e58559c46ccfbe0d97670663f2bfe1. You can search for the job name and the show artifacts links there
> 
> ![Screenshot 2023-12-25 at 17 51 52](https://private-user-images.githubusercontent.com/475357/292789240-fd7d99d7-6263-4f42-aea2-6bb2472535f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzQyMDgsIm5iZiI6MTcwMzgzMzkwOCwicGF0aCI6Ii80NzUzNTcvMjkyNzg5MjQwLWZkN2Q5OWQ3LTYyNjMtNGY0Mi1hZWEyLTZiYjI0NzI1MzVmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQwNzExNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDE3NWMzNDIzMDcxMzZmYTEwZmI5Y2U1MWNhNzBhYmY0MzE4MGQ0OGYzYjFkMzlkOWU1YTZkYjdiMWFiNDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZL6Sau_rwG28d_g3uOr-Lr35qB_87wKoIaG9QfBmfv8)

Thanks @huydhn for the tips! I was able to download and compare them. 
Nice to be collaborating with you again, happy holidays!

**Comment by nWEIdia** [comment]
> Hey @nWEIdia, it's nice to see you. Merry Christmas! Thank you for the help!

Hi @atalman, nice to be able to collaborate again, happy holidays!

**Comment by nWEIdia** [comment]
> Removed 2.2 only prefixes, added `triage review` - need to understand how to detect/prevent those

For future reference, if the illegal memory accesses are happening for the following six kernels, it is high probability the same issue: 
1) elementwise atan2 kernel 
2) elementwise binary_internal_mul functor
3) elementwise next_after kernel
4) ReduceOp and_kernel
5) elementwise binary functor-bitwise 
6) elementwise Maximum kernel 

The earliest binary I'm aware of was py3.10 cu12.1 20230828 nightly wheel https://download.pytorch.org/whl/nightly/cu121/torch-2.1.0.dev20230828%2Bcu121-cp310-cp310-linux_x86_64.whl (atan2 kernel IMA). 

We should be able to iterate through the nightlies earlier than 08282023 to detect anomalies.

**Comment by atalman** [comment]
For reference Here are most recent failures on trunk: https://github.com/pytorch/pytorch/actions/runs/7342833266/job/19993362426

```
==================================== RERUNS ====================================
_____________________ TestCommonCUDA.test_dtypes_all_cuda ______________________
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 917, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 971, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 1146, in only_fn
    return fn(self, *args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_ops.py", line 1460, in test_dtypes
    self.fail(msg)
  File "/opt/conda/envs/py_3.10/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: The supported dtypes for all on device type cuda are incorrect!
The following dtypes did not work in forward but are listed by the OpInfo: {torch.int8, torch.float64, torch.int16, torch.int32, torch.complex64, torch.int64, torch.bfloat16, torch.complex128, torch.float16, torch.uint8, torch.bool}.
Unexpected failures raised the following errors:
torch.int8 - CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by atalman** [comment]
Hi @nWEIdia could you please point us to the details on method you use to detect this issue in the built binary. We probably want to add this test in ``https://github.com/pytorch/builder/blob/main/check_binary.sh`` so that we can detect this right after building.  I adde this test ``https://github.com/pytorch/builder/blob/main/.github/scripts/validate_test_ops.sh`` to validate the binaries, but its quite slow. We want to have something quicker if possible.

**Comment by nWEIdia** [comment]
> Hi @nWEIdia could you please point us to the details on method you use to detect this issue in the built binary. We probably want to add this test in `https://github.com/pytorch/builder/blob/main/check_binary.sh` so that we can detect this right after building. I adde this test `https://github.com/pytorch/builder/blob/main/.github/scripts/validate_test_ops.sh` to validate the binaries, but its quite slow. We want to have something quicker if possible.

Hi @atalman Happy New Year! 
We can do the detection from several angles: 1) Unit test or one-line reproducer, @malfet has provided one for nextafter kernel, it will apply to future occurrences of nextafter kernel. For atan2,  the following would produce IMA 
`import torch
x = (torch.randn((2,1,1), dtype=torch.float, device="cuda")*5).to(torch.float32)
y=(torch.randn((), dtype=torch.float, device="cuda")*5).to(torch.float32)
print(torch.atan2(x,y))`
I could try to come up with one line reproducer (tests) for the other four kernels. 

2) For nightly wheels, we could compare the binary across the different python versions. In the past, python 3.8, 3.9 produced good ones but 3.10 did not. The tool we use here was cuobjdump (thanks to @ptrblck !), like "cuobjdump -arch sm_86 -symbols libtorch_cuda.so" and compare the output between good and bad. 
This is unfortunately happening non-deterministically across different sm_XX so we may need to check for different "XX" values. However the disadvantage of this approach is that it needs a baseline to compare and tell. While the unit tests would not rely on any baseline.

**Comment by atalman** [comment]
@nWEIdia yes option 1 sounds like good and straight forward approach. Perhaps we can do this, and add it to the nightly binary validations.

**Comment by nWEIdia** [comment]
> For reference Here are most recent failures on trunk: https://github.com/pytorch/pytorch/actions/runs/7342833266/job/19993362426.
> 
> ```
> ==================================== RERUNS ====================================
> _____________________ TestCommonCUDA.test_dtypes_all_cuda ______________________
> Traceback (most recent call last):
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 917, in test_wrapper
>     return test(*args, **kwargs)
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 971, in dep_fn
>     return fn(slf, *args, **kwargs)
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 1146, in only_fn
>     return fn(self, *args, **kwargs)
>   File "/var/lib/jenkins/workspace/test/test_ops.py", line 1460, in test_dtypes
>     self.fail(msg)
>   File "/opt/conda/envs/py_3.10/lib/python3.10/unittest/case.py", line 675, in fail
>     raise self.failureException(msg)
> AssertionError: The supported dtypes for all on device type cuda are incorrect!
> The following dtypes did not work in forward but are listed by the OpInfo: {torch.int8, torch.float64, torch.int16, torch.int32, torch.complex64, torch.int64, torch.bfloat16, torch.complex128, torch.float16, torch.uint8, torch.bool}.
> Unexpected failures raised the following errors:
> torch.int8 - CUDA error: an illegal memory access was encountered
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> ```

This test_dtypes_all_cuda (python test/test_ops.py -k test_dtypes_all_cuda) is mapped to Reduction Op (and_kernel). 
BTW, this job option does not take long. We can test whether using this is acceptable turn-around time. 

But what is the difference between this build (https://github.com/pytorch/pytorch/actions/runs/7342833266/job/19992583754) and sm86 build (e.g. https://github.com/pytorch/pytorch/actions/runs/7342833266/job/19992584648)? For sm86 build, I was able to get cuobjdump output, but for this job's build (without sm86 postfix), cuobjdump outputs nothing. Did the symbols all get stripped in this kind of job build?

**Comment by nWEIdia** [comment]
> @nWEIdia yes option 1 sounds like good and straight forward approach. Perhaps we can do this, and add it to the nightly binary validations.

Please help review https://github.com/pytorch/builder/pull/1663

**Comment by nWEIdia** [comment]
> But what is the difference between this build (https://github.com/pytorch/pytorch/actions/runs/7342833266/job/19992583754) and sm86 build (e.g. https://github.com/pytorch/pytorch/actions/runs/7342833266/job/19992584648)? For sm86 build, I was able to get cuobjdump output, but for this job's build (without sm86 postfix), cuobjdump outputs nothing. Did the symbols all get stripped in this kind of job build?

@atalman @huydhn could you please help check whether "cuobjdump -arch sm_86 -symbols libtorch_cuda.so" could be used in both build jobs? I checked the sm86 job could have meaningful output for us to detect IMA. The other job seems to output empty string (what sm_XX is used for that job?) 

Trying to detect it without using unit tests (as unit test would need to run on all relevant sm_XX first before detecting IMA). The cuobjdump would be able to detect before running tests. I am testing a way to not rely on "baseline" and just string pattern match. But this would require cuobjdump to be able to output something. 

The non-sm86 seems to not contain symbols.

**Comment by ZainRizvi** [comment]
I see a lot of activity related to this bug. Is it still an open issue or has this been fixed?

**Comment by nWEIdia** [comment]
The "Use jemalloc for cuda builds" commit was applied to the build process as a workaround. I don't believe we have encountered issues after this commit. 
However, if we want to roll back this workaround, we have to wait for cuda 12.4.1 (currently cuda 12.4.0 was used for binary). 
Also, even if we moved to cuda 12.4.1, this workaround can co-exist with cuda 12.4.1. 

I consider this issue "fixed". So I will close it.
