### ISSUE TITLE
`torch.compile` cannot be used in official Docker runtime images

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#116696]
### 📚 The doc issue

We need to specify that we could not use `torch.compile` in official Pytorch runtime docker images.

For CPU images `g++` is missing and for GPU flavour it cannot find  `libcuda.so`.

I don't know if it is the best choice to rely on the `devel`  image size overhead just to let user compile their models.

/cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @atalman @malfet 

### Suggest a potential alternative/fix

Advertise this in the documentation or add what it is required to the `runtime` images to let user compile models

**Comment by jansel** [comment]
@malfet who manages publishing of our official docker images? I assume it is the releng team?

**Comment by malfet** [comment]
@jansel Yes, but I think it warrants a bit of a discussion: what's the difference between runtime and devel flavors in pt-2 era

**Comment by jansel** [comment]
Are we including Triton in the docker images?  Is there are reason not to?

**Comment by bhack** [comment]
As we don't let to serialize the compiled model https://github.com/pytorch/pytorch/issues/101107 I think that we need to let developers to compile with the runtime image without the dev image size/download overhead.

**Comment by bhack** [comment]
`runtime` currently is `3.24 GB` compressed `devel` is `8.25GB` compressed when you are orchestrating a lot of these images on a cluster it will still make the difference.

**Comment by bhack** [comment]
Also nightly `ghcr.io/pytorch/pytorch-nightly:2.3.0.dev20240207-cuda12.1-cudnn8-runtime` doesn't have libcuda in the LD_PATH

**Comment by bhack** [comment]
> Also nightly `ghcr.io/pytorch/pytorch-nightly:2.3.0.dev20240207-cuda12.1-cudnn8-runtime` doesn't have libcuda in the LD_PATH

Compiling on pytorch nightly is also a broken cause:
 https://github.com/openai/triton/pull/3053

Can we cherry-pick or update the Triton commit sha?

**Comment by atalman** [comment]
This error can be seen in this docker validation workflow: https://github.com/pytorch/builder/actions/runs/8637745397/job/23680662793

cc @malfet @seemethere @juliagmt-google

**Comment by bhack** [comment]
Can we target this for 2.5?

**Comment by malfet** [comment]
IMO this sounds like a bug that should have been addressed a while back.. 
@bhack do you have a reproduce of what is not working? And again, we are talking probably about devel here, don't we?

**Comment by bhack** [comment]
Try this both on cpu and gpu:
```bash
docker run -it --rm pytorch/pytorch:2.4.0-cuda12.4-cudnn9-runtime python -c "
import torch
def foo(x, y):
    a = torch.sin(x)
    b = torch.cos(y)
    return a + b
opt_foo1 = torch.compile(foo)
print(opt_foo1(torch.randn(10, 10), torch.randn(10, 10)))
"
```

**Comment by malfet** [comment]
I've just tried this one, and it works:
```
docker run --gpus all --rm ghcr.io/pytorch/pytorch-nightly:2.5.0.dev20240823-cuda12.1-cudnn9-devel bash -c 'printf "import torch\n@torch.compile\ndef convert(x):\n\treturn x.to(dtype=torch.float)\n\nx=torch.rand(32, 32, device=\"cuda\")\ny=convert(x)\nprint(torch.__version__, y)"|python'

==========
== CUDA ==
==========

CUDA Version 12.1.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

2.5.0.dev20240822 tensor([[0.3741, 0.0990, 0.6192,  ..., 0.7407, 0.6721, 0.9008],
        [0.1230, 0.2030, 0.5261,  ..., 0.7884, 0.4359, 0.2507],
        [0.3178, 0.4473, 0.3432,  ..., 0.3577, 0.2864, 0.1584],
        ...,
        [0.2009, 0.7186, 0.9956,  ..., 0.9208, 0.3704, 0.5997],
        [0.6974, 0.0161, 0.9787,  ..., 0.5535, 0.9135, 0.9818],
        [0.5700, 0.8907, 0.9232,  ..., 0.8692, 0.7148, 0.3721]],
       device='cuda:0')
```

**Comment by bhack** [comment]
> Sorry, I misread the title, ask here is to add `gcc` to `runtime` images, because `torch.compile` needs it...

Yes also we need to extra test it for the CUDA image as some months ago the runtime had some issue to find `libcuda`

**Comment by bhack** [comment]
Probably the best solution is to regularly rely on runtime images directly in the CI for `torch.compile` tests.

**Comment by kit1980** [comment]
I changed to 2.6.0 milestone as there is no fix.

**Comment by kit1980** [comment]
I removed the milestone. If somebody is actively working on it, please add it back.

**Comment by bhack** [comment]
I think that we need to just install `g++` in the `Dockerfile`. @atalman  I am a bit lost recently with all the `Dockerilfes`. What is the one we could change?

**Comment by bhack** [comment]
> e: libcuda.so - it should never be part of the image but rather added there by nvidia-runtime (i.e. --gpus 0,1 would guarantee that libcuda is added into the image)

It don't remember correctly this point.. Probably it was related to bugs we had with Triton and libcuda paths like https://github.com/triton-lang/triton/pull/2892...

**Comment by bhack** [comment]
We have a PR for this at https://github.com/pytorch/pytorch/pull/138612

**Comment by andravin** [comment]
@malfet @bhack 

Triton Language now links against libcuda.so.1, merged in PR https://github.com/triton-lang/triton/pull/8668 (commit 3d3c4e4), so torch.compile should work on CUDA runtime images that lack libcuda.so once PyTorch uses that version.

**Comment by andravin** [comment]
Installing g++ in the container is enough to fix the issue and adds 187 MB of additional disk space.

Command:

```bash
docker run --rm --gpus all ghcr.io/pytorch/pytorch-nightly:2.10.0.dev20251209-cuda12.9-cudnn9-runtime \
  bash -c "apt-get update -qq && apt-get install -y g++ && python -c \"
import torch
@torch.compile
def f(x, y):
    return x @ y + torch.sin(x)
x = torch.randn(1024, 1024, device='cuda')
y = torch.randn(1024, 1024, device='cuda')
result = f(x, y)
torch.cuda.synchronize()
print('SUCCESS!')
\""
```

Result:

```
...text
After this operation, 187 MB of additional disk space will be used.
...
SUCCESS!
```
