### ISSUE TITLE
Illegal Memory Access, DistributedDataParallel

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#11680]
## Issue description

```
$ python3 -m torch.distributed.launch --nproc_per_node=2 --master_port=1234 abcd.py
Traceback (most recent call last):
  File "abcd.py", line 14, in <module>
    output, _ = model(input_)
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 221, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 192, in forward
    output, hidden = func(input, self.all_weights, hx, batch_sizes)
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 324, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 288, in forward
    dropout_ts)
RuntimeError: CuDNN error: CUDNN_STATUS_EXECUTION_FAILED
THCudaCheck FAIL file=/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp line=195 error=77 : an illegal memory access was encountered
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/distributed/__init__.py", line 41, in destroy_process_group
    torch._C._dist_destroy_process_group()
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:195 at /pytorch/torch/lib/THD/process_group/General.cpp:26
^CTraceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 209, in <module>
    main()
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 205, in main
    process.wait()
  File "/usr/lib/python3.6/subprocess.py", line 1457, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1404, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

## Code example

```python
import argparse
import torch

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--local_rank", type=int)
    args = parser.parse_args()

    torch.distributed.init_process_group(backend='nccl')
    model = torch.nn.LSTM(10, 10).cuda()
    model = torch.nn.parallel.DistributedDataParallel(
        model, device_ids=[args.local_rank], output_device=args.local_rank)
    input_ = torch.randn(10, 64, 10).cuda()
    output, _ = model(input_)
    output.sum().backward()
    if args.local_rank == 0:
        torch.save(model.module.state_dict(), 'model.pt')
```

## System Info

Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB
GPU 2: Tesla P100-PCIE-16GB
GPU 3: Tesla P100-PCIE-16GB

Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.3

**Comment by PetrochukM** [comment]
Changing a couple lines, I get this error:
```
THCudaCheck FAIL file=/pytorch/aten/src/THC/generated/../THCReduceAll.cuh line=317 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "abcd.py", line 15, in <module>
    output.sum().backward()
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/generated/../THCReduceAll.cuh:317
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/distributed/__init__.py", line 41, in destroy_process_group
    torch._C._dist_destroy_process_group()
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:195 at /pytorch/torch/lib/THD/process_group/General.cpp:26
^CTraceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 209, in <module>
    main()
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 205, in main
    process.wait()
  File "/usr/lib/python3.6/subprocess.py", line 1457, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1404, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

```
import argparse
import torch

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--local_rank", type=int)
    args = parser.parse_args()

    torch.distributed.init_process_group(backend='nccl')
    model = torch.nn.LSTM(10, 10).cuda()
    input_ = torch.randn(10, 64, 10).cuda(non_blocking=True)
    model = torch.nn.parallel.DistributedDataParallel(
        model, device_ids=[args.local_rank], output_device=args.local_rank)
    output, _ = model(input_)
    output.sum().backward()
    if args.local_rank == 0:
        torch.save(model.module.state_dict(), 'model.pt')
```

**Comment by PetrochukM** [comment]
Leaving this issue up because the error is not super clear. The problem was ``dim=0`` not ``dim=1``.

**Comment by ngimel** [comment]
`model = torch.nn.LSTM(10, 10).cuda()` without first setting device to args.local_rank is problematic.

**Comment by PetrochukM** [comment]
Thanks! This worked, sorry I missed that.
