### ISSUE TITLE
CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by robintibor** [pytorch/pytorch#1171]
Hi,
I get a CUDNN_STATUS_NOT_INITIALIZED error when running a modified version of <a href="http://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html">Training a classifier — PyTorch Tutorials documentation</a>:
```
$ python3.5 pytorch_cudnn.py
Files already downloaded and verified
Files already downloaded and verified
Cudnn version: 6020
Traceback (most recent call last):
  File "pytorch_cudnn.py", line 72, in <module>
    outputs = net(inputs)
  File "/home/schirrmr/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "pytorch_cudnn.py", line 39, in forward
    x = self.pool(F.relu(self.conv1(x)))
  File "/home/schirrmr/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/schirrmr/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/home/schirrmr/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 39, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_NOT_INITIALIZED
```

This is the pytorch_cudnn.py file, it runs fine without the calls to .cuda(). My theano programs run fine with cudnn.
```python
import torch
import torchvision
import torchvision.transforms as transforms
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.backends import cudnn


transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool  = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1   = nn.Linear(16 * 5 * 5, 120)
        self.fc2   = nn.Linear(120, 84)
        self.fc3   = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = Net()


criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

print("Cudnn version: {:d}".format(cudnn.version()))
net.cuda()

for epoch in range(2):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # get the inputs
        inputs, labels = data
        # move to GPU
        inputs = inputs.cuda()
        labels = labels.cuda()
        # wrap them in Variable
        inputs, labels = Variable(inputs), Variable(labels)

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.data[0]
        if i % 2000 == 1999:    # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' % (epoch+1, i+1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training')
```

**Comment by ngimel** [comment]
Do your theano scripts run with the same cudnn version? This error most often means insufficient driver version for the cudnn build you are trying to use.

**Comment by soumith** [comment]
@robintibor i think you installed pytorch + Cuda 8.0, but your nvidia driver is insufficient. Either upgrade your NVIDIA driver or install pytorch + cuda 7.5 (it is a different command on the website http://pytorch.org )

**Comment by robintibor** [comment]
@soumith Thanks for the hint, unfortunately this does not seem to solve the problem. Actually I had done the opposite, installed pytorch for cuda 7.5 but we already have cuda 8.0 installed. I now uninstalled pytorch and reinstalled everything for cuda 8.0, however still end up with the same error message. However, as @ngimel hinted, theano and pytorch seem to be using different cudnn versions. So is there anything I could try to further diagnose the problem?

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Wed_May__4_21:01:56_CDT_2016
Cuda compilation tools, release 8.0, V8.0.26
```

```
$ python3.5 pytorch_cudnn.py 
Files already downloaded and verified
Files already downloaded and verified
Cudnn version: 6020
Traceback (most recent call last):
  File "pytorch_cudnn.py", line 72, in <module>
    outputs = net(inputs)
  File "/home/schirrmr/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "pytorch_cudnn.py", line 39, in forward
    x = self.pool(F.relu(self.conv1(x)))
  File "/home/schirrmr/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/schirrmr/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/home/schirrmr/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 39, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_NOT_INITIALIZED
```

```
$ python3.5 -c 'from theano.sandbox.cuda import dnn_version; print(dnn_version())'
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10). Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX TITAN Black (CNMeM is disabled, cuDNN 5005)
(5005, 5005)
```
(I usually use an older version of theano (0.8.2) with python2.7 in case that matters)

For reinstalling, these were my uninstallation and installation instructions (a bit complicated due to some proxy stuff):

```
$ pip3.5 uninstall torch
$ rm ~/.local/lib/python3.5/site-packages/torchvision-0.1.8-py3.5.egg
```

```
$ wget http://download.pytorch.org/whl/cu80/torch-0.1.11.post5-cp35-cp35m-linux_x86_64.whl
$ pip3.5 install torch-0.1.11.post5-cp35-cp35m-linux_x86_64.whl --user
$ git clone https://github.com/pytorch/vision.git
$ cd vision
$ python3.5 setup.py install --user
```

There were no error messages during these installations.

**Comment by ngimel** [comment]
Your cuda 8 seems old (8.0.26, that's probably release candidate).  You need later driver version for cudnn v6.

**Comment by robintibor** [comment]
Hm ok @ngimel I could ask our admin to upgrade CUDA, but actually we have cudnn 5, as also theano is also showing (see last post). 

```
$ head -60 /usr/local/cuda/include/cudnn.h
[...]
#if !defined(CUDNN_H_)
#define CUDNN_H_

#define CUDNN_MAJOR      5
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 5
$ ls -ahl /usr/local/cuda/lib64/ | grep 'cudnn'
lrwxrwxrwx  1 1000 1000   13 Apr 25  2016 libcudnn.so -> libcudnn.so.5
lrwxrwxrwx  1 1000 1000   17 Apr 25  2016 libcudnn.so.5 -> libcudnn.so.5.0.5
-rwxr-xr-x  1 1000 1000  75M Apr 22  2016 libcudnn.so.5.0.5
-rw-r--r--  1 1000 1000  66M Apr 22  2016 libcudnn_static.a
```

Any reason why pytorch might say this is version 6020?

**Comment by soumith** [comment]
pytorch ships it's own cudnn

**Comment by robintibor** [comment]
Ok. Until our admin can install the new cuda version, I have replaced the libcudnn-file in the torch lib folder with the older version and then the code from above runs without error... Is this setup likely to cause some bugs later? :) 

```
$ cp /usr/local/cuda-8.0/lib64/libcudnn.so.5.0.5 ~/.local/lib/python3.5/site-packages/torch/lib/libcudnn.so.6
$ python3.5 pytorch_cudnn.py 
Files already downloaded and verified
Files already downloaded and verified
Cudnn version: 5005
[1,  2000] loss: 2.183
[1,  4000] loss: 1.824
[1,  6000] loss: 1.671
[1,  8000] loss: 1.574
[1, 10000] loss: 1.519
[1, 12000] loss: 1.444
[2,  2000] loss: 1.383
[2,  4000] loss: 1.322
[2,  6000] loss: 1.318
[2,  8000] loss: 1.309
[2, 10000] loss: 1.258
[2, 12000] loss: 1.264
Finished Training
```

**Comment by ngimel** [comment]
Yes, cudnn v6 is not binary compatible with cudnn v5, so if you just drop in the new library (instead of compiling against it), you are likely to see bugs. In particular, cudnnConvolution*AlgoPerf_t structure was changed, so once you start using cudnnFind routines (that happens if torch.backends.cudnn.benchmark is set to true), anything could happen.

**Comment by soumith** [comment]
@robintibor if you want to use pytorch in the meanwhile, especially the latest version, i think you can simply install the CUDA 7.5 version of pytorch (pytorch packages all the libraries it needs, you dont need a system CUDA of a particular version). With your particular driver version, I think that would be sufficient and work.

**Comment by robintibor** [comment]
Indeed that works @soumith  thanks so much. Apparently even uses cudnn6 from the prints.

```
$ python3.5 pytorch_cudnn.py
Files already downloaded and verified
Files already downloaded and verified
Cudnn version: 6020
[1,  2000] loss: 2.172
[1,  4000] loss: 1.851
...
```

So that also means my earlier comment was wrong and I never installed for cuda 7.5 but whatever, it works now :)
