### ISSUE TITLE
RuntimeError: NCCL Error 1: unhandled cuda error

### ISSUE THREAD

**Issue by chenwc07** [pytorch/pytorch#11756]
## Issue description
Get `NCCL Error 1: unhandled cuda error` when using DataParallel
I wonder  what's wrong with it because it works when using only 1 GPU, and cuda9/cuda8 got the same problem

## Code example
I ran:
`testdata = torch.rand(12,3,112,112)`
`model = torch.nn.DataParallel(model, device_ids=[0,1,2,3]).cuda()`
`out = model(testdata)`

then i got:
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-f69e71bd3d26> in <module>()
----> 1 out = model(testdata)

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    120         if len(self.device_ids) == 1:
    121             return self.module(*inputs[0], **kwargs[0])
--> 122         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
    123         outputs = self.parallel_apply(replicas, inputs, kwargs)
    124         return self.gather(outputs, self.output_device)

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py in replicate(self, module, device_ids)
    125 
    126     def replicate(self, module, device_ids):
--> 127         return replicate(module, device_ids)
    128 
    129     def scatter(self, inputs, kwargs, device_ids):

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/replicate.py in replicate(network, devices, detach)
     10     params = list(network.parameters())
     11     param_indices = {param: idx for idx, param in enumerate(params)}
---> 12     param_copies = Broadcast.apply(devices, *params)
     13     if len(params) > 0:
     14         param_copies = [param_copies[i:i + len(params)]

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/_functions.py in forward(ctx, target_gpus, *inputs)
     17         ctx.num_inputs = len(inputs)
     18         ctx.input_device = inputs[0].get_device()
---> 19         outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
     20         non_differentiables = []
     21         for idx, input_requires_grad in enumerate(ctx.needs_input_grad[1:]):

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/cuda/comm.py in broadcast_coalesced(tensors, devices, buffer_size)
     38         corresponding to indices from ``devices``.
     39     """
---> 40     return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
     41 
     42 

 **RuntimeError: NCCL Error 1: unhandled cuda error**

## System Info

- PyTorch
- How you installed PyTorch : conda
- OS: ubuntu-server-16.04
- PyTorch version: 0.4.1
- Python version: 3.5
- CUDA/cuDNN version: cuda8, cudnn6 and cuda9,cudnn7 got the same problem
- GPU models and configuration: Nvidia Titan Xp * 4
- GCC version (if compiling from source): 5.4
- CMake version:
- Versions of any other relevant libraries:

**Comment by chenwc07** [comment]
I forget to mention that the same DataParallel code can work perfectly on Nvidia GeForce Titan x *4

**Comment by pietern** [comment]
@chenwc07 Very weird that it works on Titan X and doesn't work on Titan Xp...

Can you try running with CUDA_LAUNCH_BLOCKING=1 to make sure the error from _broadcast_coalesced is not an error that actually happened elsewhere but only surfaces at that call?

**Comment by chenwc07** [comment]
@pietern I ran it with CUDA_LAUNCH_BLOCKING=1, and got the same error. I ran  it on jupyter yesterday and on terminal today and get extra error output. The  terminal outputs: 
Traceback (most recent call last):
  File "test_cuda.py", line 26, in <module>
    out = model(testdata)
  File "/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 122, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 127, in replicate
    return replicate(module, device_ids)
  File "/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/replicate.py", line 12, in replicate
    param_copies = Broadcast.apply(devices, *params)
  File "/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/_functions.py", line 19, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/cuda/comm.py", line 40, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: NCCL Error 1: unhandled cuda error
terminate called after throwing an instance of 'at::Error'
  what():  CUDA error: invalid device pointer (CudaCachingDeleter at /opt/conda/conda-bld/pytorch_1532576128691/work/aten/src/THC/THCCachingAllocator.cpp:498)
frame #0: THStorage_free + 0x44 (0x7f97187aa314 in /home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/lib/libcaffe2.so)
frame #1: THTensor_free + 0x2f (0x7f9718849a1f in /home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/lib/libcaffe2.so)
frame #2: at::CUDAFloatTensor::~CUDAFloatTensor() + 0x9 (0x7f96fc40bce9 in /home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/lib/libcaffe2_gpu.so)
frame #3: torch::autograd::Variable::Impl::~Impl() + 0x291 (0x7f971a394931 in /home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so)
frame #4: torch::autograd::Variable::Impl::~Impl() + 0x9 (0x7f971a394aa9 in /home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x770ea9 (0x7f971a3adea9 in /home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x770f54 (0x7f971a3adf54 in /home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so)
<omitting python frames>
frame #20: __libc_start_main + 0xf0 (0x7f972ed46830 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)

**Comment by pietern** [comment]
Thanks for the report. This smells like a double free of GPU memory.

Can you confirm this ran fine on the Titan X when run in exactly the same environment (code version, dependencies, CUDA version, NVIDIA driver, etc)?

**Comment by SsnL** [comment]
@chenwc07 Any chance that you are using the file system initialization method? I have a similar problem where `allgather` raises
```
:   File "/private/home/ssnl/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 874, in all_gather
:     work = _default_pg.allgather([tensor_list], [tensor])
: RuntimeError: NCCL error in: /scratch/ssnl/sftp/pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:269, unhandled system error
``` 
with file system init, but works fine with tcp init.

**Comment by chenwc07** [comment]
@SsnL I don't think so because the 4 GPU are on the same machine.

**Comment by chenwc07** [comment]
I found everything is going well when device_ids=[0,2,3] today! So I doubt there may be something wrong with the GPU1. Then I test the GPU one by one using another simple code like:
`os.environ["CUDA_VISIBLE_DEVICES"] = '1'`
`model.cuda(0)`
`data = data.cuda(0)`
`output = model(data)`

then I get the error message:

RuntimeError                              Traceback (most recent call last)
<ipython-input-11-5a67f555efe4> in <module>()
      6         labels = labels.cuda(0)
      7 
----> 8         outputs = model(images)
      9         loss = criterion(outputs, labels)
     10 

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

<ipython-input-7-f744eb62f792> in forward(self, x)
     34         out = self.avgpool(out)
     35         out = out.view(out.size(0), -1)
---> 36         out = self.fc(out)
     37         return out

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/linear.py in forward(self, input)
     53 
     54     def forward(self, input):
---> 55         return F.linear(input, self.weight, self.bias)
     56 
     57     def extra_repr(self):

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/functional.py in linear(input, weight, bias)
   1022     if input.dim() == 2 and bias is not None:
   1023         # fused op is marginally faster
-> 1024         return torch.addmm(bias, input, weight.t())
   1025 
   1026     output = input.matmul(weight.t())

RuntimeError: cublas runtime error : resource allocation failed at /opt/conda/conda-bld/pytorch_1532576128691/work/aten/src/THC/THCGeneral.cpp:333

So there maybe something wrong with my GPU1 or there maybe a bug from pytorch?

**Comment by chenwc07** [comment]
I also try the code like:
`os.environ["CUDA_VISIBLE_DEVICES"] = '1'`
`model = torch.nn.DataParallel(model, device_ids=[0]).cuda()`
`output = model(data)`

the output is:
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-f28dce7458d6> in <module>()
      2     adjust_learning_rate(optimizer, epoch, [15, 30], 0.001, 5e-4)
      3     # train for one epoch
----> 4     train(train_loader, model, criterion, optimizer, epoch)
      5     if epoch%2 == 0:
      6         validate(val_loader,model=model,criterion=criterion)

/home/developers/chenweicong/projects/ECO/ECO-pytorch/train_and_val.py in train(train_loader, model, criterion, optimizer, epoch)
     39 
     40         # compute output, output size: [batch_size, num_class]
---> 41         output = model(input_var)
     42 
     43         loss = criterion(output, target_var)

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    119         inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
    120         if len(self.device_ids) == 1:
--> 121             return self.module(*inputs[0], **kwargs[0])
    122         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
    123         outputs = self.parallel_apply(replicas, inputs, kwargs)

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

/home/developers/chenweicong/projects/ECO/ECO-pytorch/ECO_model.py in forward(self, input)
     19         sample_len = 3
     20         input_var = input.view((-1, sample_len) + input.size()[-2:])
---> 21         output = self.base_model(input_var)
     22 
     23         return output

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

/home/developers/chenweicong/projects/ECO/ECO-pytorch/tf_model_zoo/ECO/pytorch_load.py in forward(self, input)
    125                     data_dict[op[2]] = getattr(self, op[0])(inception_3c_transpose_output)
    126                 else:
--> 127                     data_dict[op[2]] = getattr(self, op[0])(data_dict[op[-1]])
    128                     # getattr(self, op[0]).register_backward_hook(get_hook(op[0]))
    129             elif op[1] == 'InnerProduct':

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/batchnorm.py in forward(self, input)
     64             input, self.running_mean, self.running_var, self.weight, self.bias,
     65             self.training or not self.track_running_stats,
---> 66             exponential_average_factor, self.eps)
     67 
     68     def extra_repr(self):

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/functional.py in batch_norm(input, running_mean, running_var, weight, bias, training, momentum, eps)
   1252     return torch.batch_norm(
   1253         input, weight, bias, running_mean, running_var,
-> 1254         training, momentum, eps, torch.backends.cudnn.enabled
   1255     )
   1256 

RuntimeError: CuDNN error: CUDNN_STATUS_INTERNAL_ERROR

I should mention that everything is going well when os.environ["CUDA_VISIBLE_DEVICES"] = '0/2/3'

**Comment by SsnL** [comment]
Oh my bad. I thought you were using distributed because it is labelled as distributed.

**Comment by pietern** [comment]
@chenwc07 This looks like a problem with device 1... Try running `nvidia-smi -q` and looks for anything unusual, maybe something shows up.

@mruberry @ngimel What do you think?

**Comment by mcarilli** [comment]
@chenwc07 I thought the typical usage of DataParallel was to either call .cuda() on your model before wrapping it in DataParallel, or not to call .cuda() on your model at all (because DataParallel will do it for you under the hood).

Can you try one of the following:
```
testdata = torch.rand(12,3,112,112)
model = torch.nn.DataParallel(model.cuda(), device_ids=[0,1,2,3])
out = model(testdata)
```
or just 
```
testdata = torch.rand(12,3,112,112)
model = torch.nn.DataParallel(model, device_ids=[0,1,2,3])
out = model(testdata)
```

This is probably irrelevant (especially since `torch.nn.DataParallel(model, device_ids=[0,1,2,3]).cuda()` seems to work on P100s) but it's easy to test.

**Comment by chenwc07** [comment]
@mcarilli  Thank you for your reply.
The first code outputs the same error: 

RuntimeError: NCCL Error 1: unhandled cuda error

and the second code comes to:

TypeError                                 Traceback (most recent call last)
<ipython-input-14-b9a0b7bacb33> in <module>()
      2     adjust_learning_rate(optimizer, epoch, [15, 30, 45], 0.001, 5e-4)
      3     # train for one epoch
----> 4     train(train_loader, model, criterion, optimizer, epoch)
      5     if epoch%2 == 0:
      6         validate(val_loader,model=model,criterion=criterion)

/home/developers/chenweicong/projects/ECO/ECO-pytorch/train_and_val.py in train(train_loader, model, criterion, optimizer, epoch)
     39 
     40         # compute output, output size: [batch_size, num_class]
---> 41         output = model(input_var)
     42 
     43         loss = criterion(output, target_var)

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    120         if len(self.device_ids) == 1:
    121             return self.module(*inputs[0], **kwargs[0])
--> 122         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
    123         outputs = self.parallel_apply(replicas, inputs, kwargs)
    124         return self.gather(outputs, self.output_device)

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py in replicate(self, module, device_ids)
    125 
    126     def replicate(self, module, device_ids):
--> 127         return replicate(module, device_ids)
    128 
    129     def scatter(self, inputs, kwargs, device_ids):

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/replicate.py in replicate(network, devices, detach)
     10     params = list(network.parameters())
     11     param_indices = {param: idx for idx, param in enumerate(params)}
---> 12     param_copies = Broadcast.apply(devices, *params)
     13     if len(params) > 0:
     14         param_copies = [param_copies[i:i + len(params)]

/home/zhangd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/parallel/_functions.py in forward(ctx, target_gpus, *inputs)
     11     def forward(ctx, target_gpus, *inputs):
     12         if not all(input.is_cuda for input in inputs):
---> 13             raise TypeError('Broadcast function not implemented for CPU tensors')
     14         ctx.target_gpus = target_gpus
     15         if len(inputs) == 0:

TypeError: Broadcast function not implemented for CPU tensors

so I think I still have to call .cuda() before or after DataParallel.

**Comment by chenwc07** [comment]
@pietern Can't find anything unusual. Maybe I should test the device using another framework like tensorflow?

**Comment by pietern** [comment]
@chenwc07 I think above shows that device 1 in your setup is broken... Can you try running a model on that device exclusively, without using the DataParallel wrapper? If you still get the same unhandled CUDA error then that would confirm the device being broken.

**Comment by chenwc07** [comment]
@pietern I have tried that and the error is:

RuntimeError: cublas runtime error : resource allocation failed at /opt/conda/conda-bld/pytorch_1532576128691/work/aten/src/THC/THCGeneral.cpp:333

**Comment by pietern** [comment]
@chenwc07 I am 99% sure this is a broken device and not a PyTorch problem.

@mcarilli Can you confirm?

**Comment by ngimel** [comment]
Yes, this error message looks like hardware problem, not sw.

**Comment by pietern** [comment]
Thanks @ngimel. Closing the issue.

**Comment by chenwc07** [comment]
Thanks everyone for your reply!

**Comment by Lmy0217** [comment]
@chenwc07 I got the same error with GPU. It is going well when I ran my code in GPU0, but got error when I ran same code in GPU1. The error is `RuntimeError: cublas runtime error : resource allocation failed at /pytorch/aten/src/THC/THCGeneral.cpp:333`. Is it something wrong in device or hardware? Do you sovled it?

**Comment by nwpuhq** [comment]
This is not a hardware problem,at least i am not.

**Comment by Lmy0217** [comment]
@chenwc07 @nwpuhq The GPU that reported error has been returned to the factory for repair. I think there is a hardware problem. The new GPU will no longer report errors.

**Comment by arash-ashtari** [comment]
I have the same problem!!!I think it is not a hardware problem.

**Comment by chenwc07** [comment]
In my case, it is a hardware problem. I have changed the broken GPU and the problem was solved.

**Comment by brando90** [comment]
> Yes, this error message looks like hardware problem, not sw.

@ngimel How do you know this is a hardware problem?

I'm trying to figure out if mine is also a hardware problem:

```
Traceback (most recent call last):
  File "/home/miranda9/ML4Coq/ml4coq-proj/embeddings_zoo/tree_nns/main_brando.py", line 277, in <module>
    main_distributed()
  File "/home/miranda9/ML4Coq/ml4coq-proj/embeddings_zoo/tree_nns/main_brando.py", line 187, in main_distributed
    spawn_return = mp.spawn(fn=train, args=(opts,), nprocs=opts.world_size)
  File "/home/miranda9/miniconda3/envs/automl-meta-learning/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/miranda9/miniconda3/envs/automl-meta-learning/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/miranda9/miniconda3/envs/automl-meta-learning/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/miranda9/miniconda3/envs/automl-meta-learning/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/miranda9/ML4Coq/ml4coq-proj/embeddings_zoo/tree_nns/main_brando.py", line 210, in train
    tactic_predictor = move_to_ddp(rank, opts, tactic_predictor)
  File "/home/miranda9/ultimate-utils/ultimate-utils-project/uutils/torch/distributed.py", line 162, in move_to_ddp
    model = DistributedDataParallel(model, find_unused_parameters=True, device_ids=[opts.gpu])
  File "/home/miranda9/miniconda3/envs/automl-meta-learning/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 446, in __init__
    self._sync_params_and_buffers(authoritative_rank=0)
  File "/home/miranda9/miniconda3/envs/automl-meta-learning/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 457, in _sync_params_and_buffers
    self._distributed_broadcast_coalesced(
  File "/home/miranda9/miniconda3/envs/automl-meta-learning/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1155, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1614378083779/work/torch/lib/c10d/ProcessGroupNCCL.cpp:825, unhandled cuda error, NCCL version 2.7.8
ncclUnhandledCudaError: Call to CUDA function failed.
```

**Comment by lcxywfe** [comment]
I met the savme issue with PyTorch 1.8, but 1.7 is OK.

**Comment by jamfly** [comment]
Does someone know how to fix it? I encounter the same problem with PyTorch 1.8, but 1.7 is workable. My GPU is RTX A5000.

**Comment by xuelianl** [comment]
In my case, it worked after adding the command `export CUDA_VISIBLE_DEVICES=0` at the beginning of my script.
