### ISSUE TITLE
[c10d] Make nonblocking mode the default for NCCL APIs

### ISSUE THREAD

**Issue by kwen2501** [pytorch/pytorch#117749]
### 🚀 The feature, motivation and pitch

Here "nonblocking" refers to whether a NCCL API call would immediately return or block the host CPU (Traditionally, some NCCL APIs such as `ncclCommInitRank` may block for a little when rendezvous is performed.) 

Ideally, we would like to make nonblocking mode the default. That would enable us to bail out of hangs in calls like `ncclCommInitRank`. Or, if the user wants the main thread to do other stuff while NCCL is initializing, this would also help as it puts NCCL init to the background.

This knob is control by PyTorch here:
https://github.com/pytorch/pytorch/blob/26956980c6953b42e57ad889b87444c4abccec1c/torch/csrc/distributed/c10d/NCCLUtils.cpp#L90-L97

### Additional context

Would also like to see if we can consolidate code like this:
https://github.com/pytorch/pytorch/blob/26956980c6953b42e57ad889b87444c4abccec1c/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L2478-L2487

That is, use one macro that works for both cases.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

**Comment by shuqiangzhang** [comment]
For smaller blast radius and smoother rollout the nonblocking mode NCCL calls, It is better to keep blocking mode as default for now and enable nonblocking mode one use case at a time at the beginning. E.g., for use cases that comm init time optimization is needed. Once we have more successful use cases, we can then consider making nonblocking default

**Comment by awgu** [comment]
Are there any known limitations of nonblocking mode? I passed `device_id` to `init_process_group()` and passed `TORCH_NCCL_USE_COMM_NONBLOCKING=1` and then hit this:
```
E                 File "/.../lib/python3.12/site-packages/torch/distributed/tensor/_api.py", line 340, in __torch_dispatch__
E                   return DTensor._op_dispatcher.dispatch(
E                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E                 File "/.../lib/python3.12/site-packages/torch/distributed/tensor/_dispatch.py", line 199, in dispatch
E                   random._rng_tracker = random.OffsetBasedRNGTracker(mesh.device_type)
E                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E                 File "/.../lib/python3.12/site-packages/torch/distributed/tensor/_random.py", line 167, in __init__
E                   dist.broadcast(rng_state, 0)
E                 File "/.../lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
E                   return func(*args, **kwargs)
E                          ^^^^^^^^^^^^^^^^^^^^^
E                 File "/.../lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2417, in broadcast
E                   work = default_pg.broadcast([tensor], opts)
E                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E               torch.distributed.DistBackendError: NCCL timeout in communicator initialization.
```
fwiw, I did not wait long, so it did not seem like a normal timeout. I cannot easily provide a repro though.

**Comment by kwen2501** [comment]
Did it happen during `parallelize_module` call or during a `torch.rand` op?
In either case, there was a bug around `RNGTracker` in PyTorch 2.6 and it is now fixed in main:
https://github.com/pytorch/pytorch/pull/147025

In case the bug you see is different, here is a potential issue:
```
E                 File "/.../lib/python3.12/site-packages/torch/distributed/tensor/_random.py", line 167, in __init__
E                   dist.broadcast(rng_state, 0)
```
i.e. `dist.broadcast` call uses the default group (no `group=` provided). But in reality, the RNGTracker creation may be just along one of the device mesh dimensions. So, if the rest of the world is not calling `dist.broadcast`, user can hit a collective timeout or NCCL comm init timeout.
