### ISSUE TITLE
crash when trying to divide or multiply a large tensor on voltas, but not on pascal

### ISSUE THREAD

**Issue by alexeib** [pytorch/pytorch#11788]
pytorch version: 0.5.0a0+b790bd4

 import torch; (torch.randn(547687296).cuda() / 2).sum()

on pascal:
tensor(6841.8892, device='cuda:0')

on volta:
THCudaCheck FAIL file=/private/home/myleott/src/pytorch/aten/src/THC/generated/../THCReduceAll.cuh line=317 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /private/home/myleott/src/pytorch/aten/src/THC/generated/../THCReduceAll.cuh:317

any idea what's wrong?

**Comment by soumith** [comment]
cc: @ngimel @csarofeen any clue / help?

**Comment by csarofeen** [comment]
We will take a look.

**Comment by colesbury** [comment]
Might be a bug in division that gets reported during the sum() synchronization. I'll take a look

**Comment by csarofeen** [comment]
@colesbury I think so, as when I change to mul everything is fine.

**Comment by alexeib** [comment]
i think i've tried mult by 1/2 instead of div by 2 and it still crashed

**Comment by csarofeen** [comment]
I am on a CUDA 10 build but...
```.py
import torch
tens = torch.cuda.FloatTensor(547687296).uniform_()
print("This works", tens.sum() )
tens.mul_(2)
print("This also works", tens.sum() )
tens = tens*2
print("This still works", tens.sum() )
```

**Comment by colesbury** [comment]
Oh, I see the bug. `gpu_unary_kernel` isn't handling arrays larger than 2^31-1 bytes.  Should be an easy fix.

**Comment by alexeib** [comment]
> I am on a CUDA 10 build but...
> 
> ```python
> import torch
> tens = torch.cuda.FloatTensor(547687296).uniform_()
> print("This works", tens.sum() )
> tens.mul_(2)
> print("This also works", tens.sum() )
> tens = tens*2
> print("This still works", tens.sum() )
> ```

If i try to multiply by *2* then it works

```
>>> import torch; (torch.randn(547687296).cuda() * 2).sum()
tensor(51430.5391, device='cuda:0')
```

but if i multiply by *1/2* then it does not

```
>>> import torch; (torch.randn(547687296).cuda() * 1/2).sum()
THCudaCheck FAIL file=/private/home/myleott/src/pytorch/aten/src/THC/generated/../THCReduceAll.cuh line=317 error=77 : an illegal memory access was encountered
```

**Comment by alexeib** [comment]
> I am on a CUDA 10 build but...
> 
> ```python
> import torch
> tens = torch.cuda.FloatTensor(547687296).uniform_()
> print("This works", tens.sum() )
> tens.mul_(2)
> print("This also works", tens.sum() )
> tens = tens*2
> print("This still works", tens.sum() )
> ```

yeah you are right. its because i multiplied by 1/2 which does mult by 1 and then div by 2 :P
