### ISSUE TITLE
ROCM5.7+ fails with convolutional networks

### ISSUE THREAD

**Issue by tvaranka** [pytorch/pytorch#117847]
### 🐛 Describe the bug

Using ROCM5.7+ UNet fails. It manages to run the network forward, but backward results in the error.
```python3
import diffusers
import torch

unet = diffusers.UNet2DConditionModel().cuda()
out = unet(torch.randn(1, 4, 64, 64).cuda(), 0, torch.randn(1, 1, 1280).cuda())
out.sample.sum().backward()

MIOpen Error: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/hip/handlehip.cpp:643: Failed getting available memory: invalid argument
MIOpen Error: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/hip/handlehip.cpp:643: Failed getting available memory: invalid argument
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: miopenStatusUnknownError
```

Also for a particular operation like group convolution ROCM5.7+ fails:
```python3
import torch
import torch.nn.functional as F

F.conv2d(torch.ones(1, 3, 512, 512).cuda(), torch.ones(3, 1, 5, 5).cuda(), groups=3, padding=0, stride=1)

MIOpen Error: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/hip/handlehip.cpp:643: Failed getting available memory: invalid argument
MIOpen Error: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/hip/handlehip.cpp:643: Failed getting available memory: invalid argument
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: miopenStatusUnknownError
```

This problem does not occur with ROCM5.6.

To reproduce use the container rocm/pytorch:rocm5.7_ubuntu20.04_py3.9_pytorch_1.12.1 or rocm/pytorch:latest (for diffusers `pip install diffusers`).

Possibly related https://github.com/pytorch/pytorch/issues/111536

Using MI250X

### Versions

Collecting environment information...
PyTorch version: 1.12.1+git2278830
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.7.31921-d1770ee1b

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.7.0 23352 d1e13c532a947d0cbfc94759c00dcf152294aa13)
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.14.21-150400.24.81_12.0.75-cray_shasta_c-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to:
GPU models and configuration: AMD Instinct MI250XNoGCNArchNameOnOldPyTorch
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.7.31921
MIOpen runtime version: 2.20.0
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      48 bits physical, 48 bits virtual
CPU(s):                             128
On-line CPU(s) list:                0-127
Thread(s) per core:                 2
Core(s) per socket:                 64
Socket(s):                          1
NUMA node(s):                       4
Vendor ID:                          AuthenticAMD
CPU family:                         25
Model:                              48
Model name:                         AMD EPYC 7A53 64-Core Processor
Stepping:                           1
Frequency boost:                    enabled
CPU MHz:                            2000.000
CPU max MHz:                        2000.0000
CPU min MHz:                        1500.0000
BogoMIPS:                           3992.60
Virtualization:                     AMD-V
L1d cache:                          2 MiB
L1i cache:                          2 MiB
L2 cache:                           32 MiB
L3 cache:                           256 MiB
NUMA node0 CPU(s):                  0-15,64-79
NUMA node1 CPU(s):                  16-31,80-95
NUMA node2 CPU(s):                  32-47,96-111
NUMA node3 CPU(s):                  48-63,112-127
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Mitigation; safe RET, no microcode
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.4
[pip3] numpy==1.20.3
[pip3] torch==1.12.1+git2278830
[pip3] torchvision==0.13.1+f15c117
[conda] mkl                       2022.0.1           h06a4308_117
[conda] mkl-include               2022.0.1           h06a4308_117
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] torch                     1.12.1+git2278830          pypi_0    pypi
[conda] torchvision               0.13.1+f15c117           pypi_0    pypi

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jeffdaily** [comment]
Which version of ROCm do you have installed on your host?  Your container is rocm 5.7.  I suspect your host version of rocm is too old, causing an incompatibility between the host rocm driver and your container's rocm.  Please try upgrading rocm on your host and try again.  Let us know.

**Comment by tvaranka** [comment]
This was indeed the issue. I only had ROCm 5.6.1, however I am not able to upgrade the version on the cluster so I will stick to using 5.6. Thank you very much!

**Comment by jinz2014** [comment]
@tvaranka  which command did you type to list the environment information ?

**Comment by tvaranka** [comment]
@jinz2014 None of the solutions on google worked for me for some reason. The cluster I am using has lmod, so I did `module spider rocm`, from which I was able to see the different versions. But there has to be a better way...
