### ISSUE TITLE
TestDecompCUDA.test_quick_all_cuda_float32 fails with cuda illegal memory access

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#118135]
### 🐛 Describe the bug

```python
root@227e610971a2:/opt/pytorch/pytorch# python test/test_decomp.py -v -k test_quick_all_cuda_float32
test_quick_all_cuda_float32 (__main__.TestDecompCUDA) ... ERROR
TEST SUITE EARLY TERMINATION due to torch.cuda.synchronize() failure
CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


======================================================================
ERROR: test_quick_all_cuda_float32 (__main__.TestDecompCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 920, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 1152, in only_fn
    return fn(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1317, in wrapper
    fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1877, in wrapper
    fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/test_decomp.py", line 500, in test_quick
    self.do_cross_ref(device, dtype, op, run_all=False)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1368, in wrapper
    fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/test_decomp.py", line 800, in do_cross_ref
    func(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/test_decomp.py", line 730, in __torch_dispatch__
    op_assert_equal(self.test_case, func, self.test_dtype, orig, decomp, args, kwargs)
  File "/opt/pytorch/pytorch/test/test_decomp.py", line 221, in op_assert_equal
    orig.dtype, decomp.dtype, f"Operation: {op}, orig.dtype: {orig.dtype}, decomp.dtype: {decomp.dtype}, {args}, {kwargs}")
  File "/opt/pytorch/pytorch/torch/_tensor.py", line 463, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/opt/pytorch/pytorch/torch/_tensor_str.py", line 677, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/opt/pytorch/pytorch/torch/_tensor_str.py", line 597, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/opt/pytorch/pytorch/torch/_tensor_str.py", line 349, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/opt/pytorch/pytorch/torch/_tensor_str.py", line 137, in __init__
    nonzero_finite_vals = torch.masked_select(
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2707, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2707, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 416, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1368, in wrapper
    fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 926, in test_wrapper
    raise Exception(
Exception: Caused by sample input at index 4: SampleInput(input=Tensor[size=(2,), device="cuda:0", dtype=torch.float32], args=(), kwargs={}, broadcasts_input=False, name='')

To execute this test, run the following from the base repo dir:
     python test/test_decomp.py -k test_quick_all_cuda_float32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 1.640s

FAILED (errors=1)
```

### Versions

A100, cuda 12.3 update 2

fails on https://github.com/pytorch/pytorch/commit/40890ba8e7d93d6a184d5f3c35efbf29ff1c5310
worked on https://github.com/pytorch/pytorch/commit/c3780010a58a84920335296ee5f091a0db18259f

cc @ezyang @gchanan @zou3519 @kadeng @ptrblck @eqy @malfet @atalman

**Comment by xwang233** [comment]
Also,

```python
root@227e610971a2:/opt/pytorch/pytorch# python test/test_ops_jit.py -v -k test_variant_consistency_jit_all_cuda_float32 
test_variant_consistency_jit_all_cuda_float32 (__main__.TestJitCUDA) ... ERROR
TEST SUITE EARLY TERMINATION due to torch.cuda.synchronize() failure
CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


======================================================================
ERROR: test_variant_consistency_jit_all_cuda_float32 (__main__.TestJitCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_comparison.py", line 1231, in not_close_error_metas
    pair.compare()
  File "/opt/pytorch/pytorch/torch/testing/_comparison.py", line 713, in compare
    self._compare_values(actual, expected)
  File "/opt/pytorch/pytorch/torch/testing/_comparison.py", line 840, in _compare_values
    compare_fn(
  File "/opt/pytorch/pytorch/torch/testing/_comparison.py", line 1022, in _compare_regular_values_close
    if torch.all(matches):
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1926, in freeze_rng_state
    yield
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_jit.py", line 160, in runAndSaveRNG
    results = func(*inputs, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/jit_metaprogramming_utils.py", line 396, in script_fn
    self.assertExportImport(fn.graph, tensors)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_jit.py", line 148, in assertExportImport
    self.assertExportImportModule(m, inputs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_jit.py", line 154, in assertExportImportModule
    self.assertEqual(a, b, "Results of original model and "
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 3547, in assertEqual
    error_metas = not_close_error_metas(
  File "/opt/pytorch/pytorch/torch/testing/_comparison.py", line 1238, in not_close_error_metas
    f"Comparing\n\n"
  File "/opt/pytorch/pytorch/torch/testing/_comparison.py", line 381, in __repr__
    body = [
  File "/opt/pytorch/pytorch/torch/testing/_comparison.py", line 382, in <listcomp>
    f"    {name}={value!s},"
  File "/opt/pytorch/pytorch/torch/_tensor.py", line 463, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/opt/pytorch/pytorch/torch/_tensor_str.py", line 677, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/opt/pytorch/pytorch/torch/_tensor_str.py", line 597, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/opt/pytorch/pytorch/torch/_tensor_str.py", line 349, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/opt/pytorch/pytorch/torch/_tensor_str.py", line 133, in __init__
    value_str = f"{value}"
  File "/opt/pytorch/pytorch/torch/_tensor.py", line 959, in __format__
    return self.item().__format__(format_spec)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pytorch/pytorch/test/test_ops_jit.py", line 83, in test_variant_consistency_jit
    self.indiv_variant_test_jit(device, dtype, op, sample, func_type, variant, has_fake_function)
  File "/opt/pytorch/pytorch/test/test_ops_jit.py", line 118, in indiv_variant_test_jit
    check_against_reference(self,
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_jit.py", line 91, in check_against_reference
    outputs_test = self.runAndSaveRNG(func, nograd_inputs, kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_jit.py", line 159, in runAndSaveRNG
    with freeze_rng_state():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1938, in freeze_rng_state
    torch.cuda.set_rng_state(cuda_rng_state)
  File "/opt/pytorch/pytorch/torch/cuda/random.py", line 74, in set_rng_state
    _lazy_call(cb)
  File "/opt/pytorch/pytorch/torch/cuda/__init__.py", line 246, in _lazy_call
    callable()
  File "/opt/pytorch/pytorch/torch/cuda/random.py", line 72, in cb
    default_generator.set_state(new_state_copy)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 920, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/test_ops_jit.py", line 85, in test_variant_consistency_jit
    variant_error_info = dedent(f"""
  File "/opt/pytorch/pytorch/torch/testing/_internal/opinfo/core.py", line 218, in __repr__
    return self._repr_helper(lambda x: x)
  File "/opt/pytorch/pytorch/torch/testing/_internal/opinfo/core.py", line 208, in _repr_helper
    f"input={formatter(self.input)}",
  File "/opt/pytorch/pytorch/torch/_tensor.py", line 960, in __format__
    return object.__format__(self, format_spec)
  File "/opt/pytorch/pytorch/torch/_tensor.py", line 463, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/opt/pytorch/pytorch/torch/_tensor_str.py", line 677, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/opt/pytorch/pytorch/torch/_tensor_str.py", line 597, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/opt/pytorch/pytorch/torch/_tensor_str.py", line 349, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/opt/pytorch/pytorch/torch/_tensor_str.py", line 138, in __init__
    tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2707, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2707, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 416, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1368, in wrapper
    fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 926, in test_wrapper
    raise Exception(
Exception: Caused by sample input at index 4: SampleInput(input=Tensor[size=(2,), device="cuda:0", dtype=torch.float32], args=(), kwargs={}, broadcasts_input=False, name='')

To execute this test, run the following from the base repo dir:
     python test/test_ops_jit.py -k test_variant_consistency_jit_all_cuda_float32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 1.929s

FAILED (errors=1)
```

**Comment by xwang233** [comment]
and
```
TestInductorOpInfoCUDA.test_comprehensive_all_cuda_float32
TestCommonCUDA.test_out_warning_all_cuda
TestCommonCUDA.test_dtypes_all_cuda
TestCommonCUDA.test_python_ref__refs_all_cuda_float32
TestCommonCUDA.test_out_all_cuda_float32
TestCommonCUDA.test_noncontiguous_samples_all_cuda_float32
TestCompositeComplianceCUDA.test_operator_all_cuda_float32
TestReductionsCUDA.test_all_any_vs_numpy_cuda_float32
TestCommonCUDA.test_variant_consistency_eager_all_cuda_float32
```

and a few others

**Comment by xwang233** [comment]
https://github.com/pytorch/pytorch/commit/01abb5af2197cb517fc9b6f241d7dfcc4c66f597

Reverting this commit fixes the issue. 

cc @jeffdaily

**Comment by jeffdaily** [comment]
The PR had a clean CI signal.  Were these tests not covered by ciflow/trunk?

**Comment by jeffdaily** [comment]
@xwang233 what kind of GPU is this failing on?  Can you share the output of ./torch/utils/collect_env.py ?

**Comment by xwang233** [comment]
> Versions
> A100, cuda 12.3 update 2
> fails on https://github.com/pytorch/pytorch/commit/40890ba8e7d93d6a184d5f3c35efbf29ff1c5310
> worked on https://github.com/pytorch/pytorch/commit/c3780010a58a84920335296ee5f091a0db18259f

It's likely that pytorch CI on github doesn't have A100?

**Comment by eqy** [comment]
CC @malfet @atalman

**Comment by malfet** [comment]
@xwang233 we do run some tests on A100, but not all, though we run nothing on CUDA-12.3.
So it feels like a regression in the compiler/runtime (though it sounds very strange)

Rebuilding PyTorch with 12.3 to see what is going on

**Comment by xwang233** [comment]
Update: the IMA issue disappeared on today's build. It might be a false alarm to accuse https://github.com/pytorch/pytorch/commit/01abb5af2197cb517fc9b6f241d7dfcc4c66f597 #115214 . We need further investigation on that.

**Comment by nWEIdia** [comment]
Update: we checked the binary and found that it won't pass https://github.com/pytorch/builder/blob/main/.github/scripts/validate_test_ops.sh#L25 so it is likely the same old issue built without jemalloc workaround. 
We further checked the symbols and projected that this IMA would come from ReduceOp's and_kernel_cuda. 
Below is the compute-sanitizer output that confirms it was indeed coming from that kernel. 
 
```
Invalid _global_ read of size 16 bytes
=========     at void at::native::reduce_kernel<(int)512, (int)1, at::native::ReduceOp<float, at::native::func_wrapper_t<bool, at::native::and_kernel_cuda(at::TensorIterator &)::[lambda() (instance 1)]::operator ()() const::[lambda() (instance 7)]::operator ()() const::[lambda(float, float) (instance 1)]>, unsigned int, bool, (int)4>>(T3)+0x60
=========     by thread (1,0,0) in block (0,0,0)
=========     Address 0x20 is out of bounds
=========     and is 140284560146400 bytes before the nearest allocation at 0x7f968b600000 of size 2097152 bytes
```

**Comment by malfet** [comment]
Update: can not reproduce it on my end:
```
$ python3 test/test_decomp.py -v -k test_quick_all_cuda_float32
test_quick_all_cuda_float32 (__main__.TestDecompCUDA) ... ok

----------------------------------------------------------------------
Ran 1 test in 8.582s

OK
nshulga@ip-10-200-84-248:~/git/pytorch/pytorch$ python3
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__config__.show())
PyTorch built with:
  - GCC 9.4
  - C++ Version: 201703
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.3
  - NVCC architecture flags: -gencode;arch=compute_80,code=sm_80
  - CuDNN 8.9.2  (built against CUDA 12.1)
  - Build settings: BLAS_INFO=atlas, BUILD_TYPE=Release, CUDA_VERSION=12.3, CUDNN_VERSION=8.9.2, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=1 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.0, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=OFF, USE_MKLDNN=ON, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 
 >>> torch.version.git_version
'7e154a279eba3b317a9112b03bdca442531857e0'
```
