### ISSUE TITLE
torch.bmm fails when multiplying a batch of sparse matrices by a dense tensor

### ISSUE THREAD

**Issue by Franblueee** [pytorch/pytorch#119076]
### 🐛 Describe the bug

When I try to multiply a batch of sparse matrices of shape (B, N, N) by a dense tensor of shape (B, N, 1) using ```torch.bmm```, the following error is thrown:
```RuntimeError: CUDA error: misaligned address```

However, no error is thrown when multiplying the batch of sparse matrices by a dense tensor of shape (B, N, D), with D>1. 

Code to reproduce the first case: 

```
import torch

n_nodes = 10
n_edges = 20
batch_size = 2

sparse_list = []
for i in range(batch_size):
    indices = torch.randint(0, n_nodes, (2, n_edges))
    values = torch.randn(n_edges)
    size = (n_nodes, n_nodes)
    sparse_list.append(torch.sparse_coo_tensor(indices, values, size))

batch_sparse_tensor = torch.stack(sparse_list).coalesce()

device = torch.device('cuda:1')

batch_sparse_tensor = batch_sparse_tensor.to(device)

f_random = torch.randn(batch_size, n_nodes, 1).to(device)

torch.bmm(batch_sparse_tensor, f_random)
```

Code to reproduce the second case:

```
import torch

n_nodes = 10
n_edges = 20
batch_size = 2
D=100

sparse_list = []
for i in range(batch_size):
    indices = torch.randint(0, n_nodes, (2, n_edges))
    values = torch.randn(n_edges)
    size = (n_nodes, n_nodes)
    sparse_list.append(torch.sparse_coo_tensor(indices, values, size))

batch_sparse_tensor = torch.stack(sparse_list).coalesce()

device = torch.device('cuda:1')

batch_sparse_tensor = batch_sparse_tensor.to(device)

h_random = torch.randn(batch_size, n_nodes, ).to(device)

torch.bmm(batch_sparse_tensor, h_random)
```

### Versions

PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: AlmaLinux 8.8 (Sapphire Caracal) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-477.21.1.el8_8.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 535.104.05
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] torch==2.1.2
[pip3] torch_geometric==2.4.0
[pip3] torchvision==0.16.2
[pip3] triton==2.1.0
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] torch                     2.1.2                    pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torchvision               0.16.2                   pypi_0    pypi
[conda] triton

**Comment by GrahamHulsey** [comment]
I am getting the same error with torch 2.6.0 and CUDA 12.2. torch.bmm(sparse_coo_matrix, dense_tensor) gives the cuda misalgned error, although the error is sporadic. Sometimes the code works, sometimes it doesn't. Have there been any updates on this?

**Comment by GrahamHulsey** [comment]
Just for reference if anyone comes across this issue and is looking for a workaround, here's what worked for me. If A is a sparse_c00 tensor and input is a dense tensor, you can pad the dense tensor with a column of 0s, apply torch.bmm(), and then drop the second column of the result. You may need to do some additional reshaping as needed.

`inp_padded = torch.cat(
                    [input, torch.zeros(input.size(0), input.size(1), 1, device=input.device)],
                    dim=2)
    
    Ax = torch.bmm(A_test, inp_padded)[:, :, :1].squeeze(2)`
