### ISSUE TITLE
c++ libtroch Exception when tensor do  repeat_interleave  then do torch::mm

### ISSUE THREAD

**Issue by heyfavour** [pytorch/pytorch#121293]
### 🐛 Describe the bug

    try{
        image = torch::rand({12, 3}).to(device);
        cell= torch::rand({3, 3}).to(device);
        image = torch::repeat_interleave(image,12,0).to(device);
        shift = torch::mm(image, cell);
    } catch (std::exception& e){
        std::cout << e.what() << std::endl;
    }
it will raise :
******************************
CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
Exception raised from gemm<float> at ../aten/src/ATen/cuda/CUDABlas.cpp:426 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f8017a27617 in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f80179e298d in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libc10.so)
frame #2: <unknown function> + 0x3392dde (0x7f7fb2456dde in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0x33bde1e (0x7f7fb2481e1e in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cuda.so)
frame #4: at::native::structured_mm_out_cuda::impl(at::Tensor const&, at::Tensor const&, at::Tensor const&) + 0x4a (0x7f7fb248238a in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x3140de0 (0x7f7fb2204de0 in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x3140e50 (0x7f7fb2204e50 in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cuda.so)
frame #7: at::_ops::mm::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&) + 0x6e (0x7f7ffa6ad68e in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x440e621 (0x7f7ffc287621 in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x440f1e3 (0x7f7ffc2881e3 in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cpu.so)
frame #10: at::_ops::mm::call(at::Tensor const&, at::Tensor const&) + 0x161 (0x7f7ffa6faa01 in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cpu.so)
frame #11: ./main() [0x4392fa]
frame #12: ./main() [0x431b5e]
frame #13: ./main() [0x43325e]
frame #14: __libc_start_main + 0xf5 (0x7f7faeb35555 in /lib64/libc.so.6)
frame #15: ./main() [0x42fde9]

terminate called after throwing an instance of 'c10::Error'
  what():  Expected a proper Tensor but got None (or an undefined Tensor in C++) for argument #1 'other'
Exception raised from checked_cast_variable at ../torch/csrc/autograd/VariableTypeManual.cpp:60 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f8017a27617 in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f80179e298d in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libc10.so)
frame #2: <unknown function> + 0x562db06 (0x7f7ffd4a6b06 in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x42f13ef (0x7f7ffc16a3ef in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x42f1c26 (0x7f7ffc16ac26 in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cpu.so)
frame #5: at::_ops::add_Tensor::call(at::Tensor const&, at::Tensor const&, c10::Scalar const&) + 0x169 (0x7f7ffa57abc9 in /home12ssd/laspgpu/packages_cuda121/libtorch/lib/libtorch_cpu.so)
frame #6: ./main() [0x436302]
frame #7: ./main() [0x43021f]
frame #8: ./main() [0x431c3f]
frame #9: ./main() [0x43325e]
frame #10: __libc_start_main + 0xf5 (0x7f7faeb35555 in /lib64/libc.so.6)
frame #11: ./main() [0x42fde9]

****************************** 
same error will happen in libtorch 2.2.1-cuda12.1
but libtorch 2.1.1-cuda18.1 is norm

### Versions

Collecting environment information...                                                                                               
PyTorch version: 2.1.2                                                                                                              
Is debug build: False                                                                                                               
CUDA used to build PyTorch: 12.1                                                                                                    
ROCM used to build PyTorch: N/A                                                                                                     
                                                                                                                                    
OS: CentOS Linux release 7.9.2009 (Core) (x86_64)                                                                                   
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)                                                                                 
Clang version: Could not collect                                                                                                    
CMake version: version 3.28.3                                                                                                       
Libc version: glibc-2.17                                                                                                            
                                                                                                                                    
Python version: 3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0] (64-bit runtime)                                                  
Python platform: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17                                                                 
Is CUDA available: True                                                                                                             
CUDA runtime version: 12.1.66                                                                                                       
CUDA_MODULE_LOADING set to: LAZY                                                                                                    
GPU models and configuration:                                                                                                       
GPU 0: NVIDIA A100 80GB PCIe                                                                                                        
GPU 1: NVIDIA A100 80GB PCIe                                                                                                        
GPU 2: NVIDIA A100 80GB PCIe                                                                                                        
GPU 3: NVIDIA A100 80GB PCIe                                                                                                        
GPU 4: NVIDIA GeForce RTX 4090                                                                                                      
GPU 5: NVIDIA GeForce RTX 4090                                                                                                      
GPU 6: NVIDIA GeForce RTX 4090                                                                                                      
GPU 7: NVIDIA GeForce RTX 4090                                                                                                      
                                                                                                                                    
Nvidia driver version: 530.30.02                                                                                                    
cuDNN version: Could not collect                                                                                                    
HIP runtime version: N/A                                                                                                            
MIOpen runtime version: N/A                                                                                                         
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    1
Core(s) per socket:    24
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
Stepping:              4
CPU MHz:               3399.884
CPU max MHz:           3700.0000
CPU min MHz:           1200.0000
BogoMIPS:              5400.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              33792K
NUMA node0 CPU(s):     0-23
NUMA node1 CPU(s):     24-47
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear spec_ctrl intel_stibp flush_l1d

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.1.2
[pip3] torchaudio==2.1.2
[pip3] torchvision==0.16.2
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.8           py311h5eee18b_0  
[conda] mkl_random                1.2.4           py311hdb19cb5_0  
[conda] numpy                     1.26.4          py311h08b1b3b_0  
[conda] numpy-base                1.26.4          py311hf175353_0  
[conda] pytorch                   2.1.2           py3.11_cuda12.1_cudnn8.9.2_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.1.2               py311_cu121    pytorch
[conda] torchtriton               2.1.0                     py311    pytorch
[conda] torchvision               0.16.2              py311_cu121    pytorch

**Comment by lmuellender** [comment]
Hi @heyfavour, since you closed this issue as completed, what solved the problem for you? I'm getting the same exact error and backtrace up until frame #10, when trying to run backprop through a TorchScript-compiled model. I'm also using Pytorch/Libtorch 2.1.2 with CUDA 12.1.

**Comment by heyfavour** [comment]
> Hi @heyfavour, since you closed this issue as completed, what solved the problem for you? I'm getting the same exact error and backtrace up until frame #10, when trying to run backprop through a TorchScript-compiled model. I'm also using Pytorch/Libtorch 2.1.2 with CUDA 12.1.

use pytorch==2.1.2 with cuda 11.8,it will be ok

**Comment by lmuellender** [comment]
Ok, that solved it for me as well now. However, since newer CUDA versions seem to produce this bug, I would vote to reopen this issue since reverting to an older CUDA version isn't really a viable long-term solution.
