### ISSUE TITLE
 UserWarning: Plan failed with a cudnnException

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#121834]
### 🐛 Describe the bug

Compiling this `forward` https://github.com/yoxu515/aot-benchmark/blob/paot/networks/engines/aotv3_engine.py#L35-L110

I got this warning.
 
 

### Error logs

```python
UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at /opt/conda/conda-bld/pytorch_1710229288018/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
 ```

And after few inputs I got:
https://github.com/pytorch/pytorch/issues/121504#issuecomment-1992229958 
/cc @ezyang @gchanan @zou3519 @kadeng @csarofeen @ptrblck @xwang233 @msaroufim @bdhirsh @anijain2305 @chauhang @williamwen42 
 
Here in the attachment the generated inductor[
[c5nhr6q2xpuk52rh5thx56utuj6tjvxobjgjbd3rsdjvwggjys3d.py.txt](https://github.com/pytorch/pytorch/files/14591728/c5nhr6q2xpuk52rh5thx56utuj6tjvxobjgjbd3rsdjvwggjys3d.py.txt)
](url)

### Versions

Last official pytorch-nightly image.

**Comment by bhack** [comment]
Lowering the input resolution a bit in another run I don't https://github.com/pytorch/pytorch/issues/121504#issuecomment-1992229958 (as documented in that ticket) and I see these extra messages in the log:

```python
/tmp/torchinductor_root/py/cpylrdfke46tta45o5xnxi77ex3ja2o5vdxsbjbcnp66kgd7vwqd.py:615: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at /opt/conda/conda-bld/pytorch_1710229288018/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  buf3 = extern_kernels.convolution(buf0, buf1, stride=(1, 1), padding=(1, 1), dilation=(1, 1), transposed=False, output_padding=(0, 0), groups=1, bias=None)
/tmp/torchinductor_root/py/cpylrdfke46tta45o5xnxi77ex3ja2o5vdxsbjbcnp66kgd7vwqd.py:644: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at /opt/conda/conda-bld/pytorch_1710229288018/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  buf13 = extern_kernels.convolution(buf10, buf11, stride=(1, 1), padding=(1, 1), dilation=(1, 1), transposed=False, output_padding=(0, 0), groups=1, bias=None)
/tmp/torchinductor_root/rd/crdjdt7nq5zpiv2qjswdnkkjyqhawkfoeb5jm6t3lthc3dr3vmbq.py:615: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at /opt/conda/conda-bld/pytorch_1710229288018/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  buf3 = extern_kernels.convolution(buf0, buf1, stride=(1, 1), padding=(1, 1), dilation=(1, 1), transposed=False, output_padding=(0, 0), groups=1, bias=None)
  ```

**Comment by jansel** [comment]
@ezyang do you know who is the right person to look at this.  The warning is coming from the eager convolution kernel.

**Comment by ezyang** [comment]
It sounds like something is wrong with our size/stride meta. cc @eellison

**Comment by eellison** [comment]
I think you are linking the wrong inductor code. There is no conv in that output. Can you please include include a full repro ?

**Comment by bhack** [comment]
I have many inductor code when I am compiling that forward on a clean env.
What I need to share?

**Comment by bhack** [comment]
If you want instead to reproduce it from the source code @williamwen42 has already some instruction at
https://github.com/pytorch/pytorch/issues/121504#issuecomment-1995862175
As we are already reproducing many compiler issue on the same model/repo.

**Comment by eellison** [comment]
If you run with `TORCH_COMPILE_DEBUG=1` and dump the full output that will be sufficient to repro here.

> I have many inductor code `.py` when I am compiling that forward on a clean env. What I need to share?

**Comment by bhack** [comment]
> If you run with TORCH_COMPILE_DEBUG=1 and dump the full output that will be sufficient to repro here.

You can find it here:
[compile_dump.txt](https://github.com/pytorch/pytorch/files/14751094/compile_dump.txt)

**Comment by eellison** [comment]
Looking at the dump here - the warning happens prior to dynamo tracing so I'm not sure that it is a fake tensor issue.

```
/opt/conda/lib/python3.10/site-packages/torch/functional.py:512: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1710315938922/work/aten/src/ATen/native/TensorShape.cpp:3587.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/opt/conda/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at /opt/conda/conda-bld/pytorch_1710315938922/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
I0326 01:09:10.597000 132385496905536 torch/_dynamo/logging.py:55] [0/0] Step 1: torchdynamo start tracing forward /workspace/./networks/layers/attention.py:310
````

**Comment by bhack** [comment]
> Looking at the dump here - the warning happens prior to dynamo tracing so I'm not sure that it is a fake tensor (or pt2) issue.

But I could confirm that with decorating with `@torch.compile` that `forward` we don't have that warning.

**Comment by bhack** [comment]
P.s. I meant without decorating.

**Comment by nagadomi** [comment]
I got this warning after updating to PyTorch 2.3.0 today.
This warning only appears when `nn.Conv2d(8, 1, 3)` is called with fp16.

reproduction code
```python
import torch
import torch.nn as nn

conv_no_warn = nn.Conv2d(8, 3, kernel_size=3, stride=1, padding=0).eval().cuda()
conv_warn = nn.Conv2d(8, 1, kernel_size=3, stride=1, padding=0).eval().cuda()
x = torch.rand((1, 8, 546, 392)).cuda()

with torch.inference_mode(), torch.autocast(device_type="cuda"):
    # No warning
    conv_no_warn(x)
    # UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED
    conv_warn(x)
```

**Comment by agunapal** [comment]
Seeing this consistently with `max-autotune` mode of `torch.compile` in PyTorch 2.3.0

**Comment by atalman** [comment]
This can be seen here:
```
Testing smoke_test_conv2d with cuda for torch.float16
/opt/conda/envs/conda-env-8819486240_pypi/lib/python3.11/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
```
https://github.com/pytorch/builder/actions/runs/8819486240/job/24210862873#step:11:4098

**Comment by nagadomi** [comment]
I had used `torch 2.3.0+cu118`, so I tried `cu121` version and the above reproduction code did not produce any warning.
Then I reverted to cu118 version and the warning no longer appears in the above reproduced code.
However, my more complex application still produced warnings,
so I tried running it with `python -W error ..` command, I found that the module that produced the warning had changed from before.

**Comment by mvpatel2000** [comment]
> Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)

also encountering this in eager mode in our unit tests to upgrade to torch 2.3

**Comment by johnnynunez** [comment]
with pytorch 2.3.0 with ultralytics yolov8 same problem

**Comment by golemme** [comment]
With pytorch 2.3.0 and ultralytics yolov8 I'm getting  UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,

**Comment by Skylion007** [comment]
Does building with this PR fix the issue? https://github.com/pytorch/pytorch/pull/120642

**Comment by johnnynunez** [comment]
> Does building with this PR fix the issue? #120642

No, I'm using cudnn 9.1

**Comment by eellison** [comment]
Cc @eqy

**Comment by golemme** [comment]
Using version 12.2 for cuda and cudnn on windows 10.

**Comment by eqy** [comment]
Sorry for missing this. Previously PyTorch didn't warn about these kinds of (recoverable) cuDNN failures as they were considered common enough that reporting them would be noisy. https://github.com/pytorch/pytorch/pull/120719 added warnings for these alongside changing some other printing changes. However this PR was reverted so did we just get unlucky with the branch cut for a release?

Additionally I couldn't tell if there was an actual crash (unexpected and I would investigate) reported here or just warnings (which unfortunately would be expected behavior with #120719).

**Comment by SkyeOfBreeze** [comment]
I can't speak for anyone else here, but this seems to fit the bug that I am having, and it does cause it to crash.

I was following this tutorial: https://pytorch.org/hub/pytorch_vision_deeplabv3_resnet101/

```
torch                     2.3.0+cu118
torchaudio                2.3.0+cu118
torchvision               0.18.0+cu118
```

relevant section from the sample code
```
# move the input and model to GPU for speed if available
if torch.cuda.is_available():
    input_batch = input_batch.to('cuda')
    model.to('cuda')

with torch.no_grad():
    output = model(input_batch)['out'][0]
output_predictions = output.argmax(0)
```

```
Traceback (most recent call last):
  File "S:\opencv-training\segment-deep.py", line 35, in <module>
    output = model(input_batch)['out'][0]
    ...
 File "C:\Python312\Lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
```

I don't know what versions the google colab was using, but that worked for my purposes of evaluating that specific demo

**Comment by Josh-XT** [comment]
I started getting this after updating to 2.3.0 today as well.

**Comment by nagadomi** [comment]
@eqy 
This issue just shows a warning, but what can I fix on my code? (without model re-training)
If the warning is only useful for development time, I think it should be controlled by environment variable, e.g. `TORCH_LOGS=cudnn`.

**Comment by eqy** [comment]
@nagadomi the change has already been reverted so future versions should not show these warnings but unfortunately it looks like the release branch needs to be updated with the revert commit

**Comment by zaptrem** [comment]
Does this affect performance or accuracy? I have the same issue but don't want to touch anything on active training runs if I can avoid it.

**Comment by eqy** [comment]
This should not affect performance or accuracy unless you are seeing a crash @zaptrem

**Comment by hanieh11** [comment]
causes crash and core dump in my case, using:
CUDA 12.4 update 1
Pytorch: 2.3

**Comment by eqy** [comment]
> causes crash and core dump in my case, using: CUDA 12.4 update 1 Pytorch: 2.3

That's unexpected, would you have a reproducer for this example?

**Comment by L1pp** [comment]
I've encountered the same issue while using the latest official Docker image "pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime". Here is the warning message:

/opt/conda/lib/python3.10/site-packages/torch/autograd/graph.py:744: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at /opt/conda/conda-bld/pytorch_1712608935911/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  
System Info:
Docker Image: pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime
GPU: NVIDIA GeForce RTX 3090
Operating System: Ubuntu 22.04.4 LTS

The specific training model is the official resnet18. It is worth noting that this error did not affect the progress of training.
So based on the above content, does this warning not affect the actual effect?
I am just providing feedback that this error message still needs to be resolved in the official version of pytorch 2.3.0.

**Comment by eqy** [comment]
We are looking to get this resolved in 2.3.1, and yes the warning alone should not affect the results of training. It is basically saying that the first selected cuDNN algorithm could not run the workload---in this case the next selected cuDNN algorithm will be tried.

**Comment by pbagwell-phioptics** [comment]
See https://github.com/facebookresearch/detectron2/discussions/5284#discussioncomment-9374369

**Comment by weidehai** [comment]
I encountered the same problem
torch                     2.3.0                    pypi_0    pypi
torchvision               0.18.0                   pypi_0    pypi

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

NVIDIA-SMI 550.67                 Driver Version: 550.67         CUDA Version: 12.4   

Ubuntu 22.04.1 LTS

UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)

I don't know if it will affect the final execution result of the program

**Comment by atalman** [comment]
Closing this since cherry-picking PR posted: https://github.com/pytorch/pytorch/pull/125790
Pending validation for 2.3.1 rc1

**Comment by nmahammad** [comment]
i had the same issue : '' torch/nn/modules/conv.py:952: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv_transpose2d(
 ''

**Comment by stanleylcao** [comment]
I have also just got this error. I don't believe I saw this yesterday? Maybe it resurfaced?

**Comment by nmahammad** [comment]
In my case the torch version is not even 2.3 , it is 2.2.1 and it started to have that issue starting from yesterday, can it be related to an internal problem in my GPU ?

**Comment by nmahammad** [comment]
Update : venv/lib/python3.9/site-packages/torch/autograd/graph.py:744: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass   --- now the error is a bit different

**Comment by rafa-br34** [comment]
I get this, but it doesn't seem to interfere with training.
```
/home/rafa/Python3_11_6_VEnv/lib/python3.11/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
/home/rafa/Python3_11_6_VEnv/lib/python3.11/site-packages/torch/autograd/graph.py:744: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/home/rafa/Python3_11_6_VEnv/lib/python3.11/site-packages/torch/nn/modules/conv.py:952: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv_transpose2d(
```

**Comment by HoseinHashemi** [comment]
I get the same UserWarning with Pytorch 2.3.0 and CUDA11.8

**Comment by GKaviani** [comment]
I have similar problem (to some extent)

I got the error while using resnet3d that gets sequence of video/frames with batchsize 15 , sequence length 15 on following version of torch and cudnn: 

pytorch                   2.3.0           py3.10_cuda12.1_cudnn8.9.2_0    pytorch
pytorch-cuda              12.1                 ha16c6d3_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torchaudio                2.3.0               py310_cu121    pytorch
torchmetrics              1.4.0.post0        pyhd8ed1ab_0    conda-forge
torchtriton               2.3.0                     py310    pytorch
torchvision               0.18.0              py310_cu121    pytorch
cuda-cudart               12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.4.127                      0    nvidia
cuda-runtime              12.1.0                        0    nvidia
pytorch                   2.3.0           py3.10_cuda12.1_cudnn8.9.2_0    pytorch
pytorch-cuda              12.1                 ha16c6d3_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch

___________________________________________________________________
```
user/anaconda3/envs/DARai/lib/python3.10/site-packages/torch/nn/modules/conv.py:605: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at /opt/conda/conda-bld/pytorch_1712608935911/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv3d(

```

**Comment by nmahammad** [comment]
The issue was solved when I downgraded torch to 2.2.2

**Comment by atalman** [comment]
Validated with 2.3.1 rc: https://github.com/pytorch/builder/actions/runs/9288567412/job/25566399559

**Comment by leng-yue** [comment]
Does this cause any performance degrade?

**Comment by eqy** [comment]
Should not cause performance degradation as after the first iteration the failing config will be skipped.
Please note it is fixed in 2.3.1.

**Comment by HoseinHashemi** [comment]
> Does this cause any performance degrade?

I have not noticed any performance degradation yet. You only get the warning at the first iteration anyway.

**Comment by mahao18cm** [comment]
/root/miniconda3/envs/flownet2/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a CuDNNError: cuDNN error: CUDNN_STATUS_BAD_PARAM
Exception raised from run_conv_plan at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:374 (most recent call first):

It  really works now? But i still failed.

**Comment by tjasmin111** [comment]
**June 2024 Solution**: Upgrade torch version to 2.3.1 to fix it:

`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

**Comment by davy-blavette** [comment]
> **June 2024 Solution**: Upgrade torch version to 2.3.1 to fix it:
> 
> `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118

**Comment by freckletonj** [comment]
it looks like this is an issue when the input channels `==1`?

**Comment by mahao18cm** [comment]
> it looks like this is an issue when the input channels `==1`?
maybe this problem is caused by cv2. I has solved this problems

**Comment by BarakeelFanseuKamhoua** [comment]
Please was this solved? I have torch 2.3.0+cu121 and encountering the same issue.

**Comment by johnnynunez** [comment]
> Please was this solved? I have torch 2.3.0+cu121 and encountering the same issue.

use 2.4.0 or 2.4.1

**Comment by iamstarlee** [comment]
> I get the same UserWarning with Pytorch 2.3.0 and CUDA11.8

Pytorch 2.3.0 with CUDA12.1 doesn't work either.

**Comment by keyu-tian** [comment]
> > I get the same UserWarning with Pytorch 2.3.0 and CUDA11.8
> 
> Pytorch 2.3.0 with CUDA12.1 doesn't work either.

fixed with pytorch>=2.3.1

**Comment by RifatMamayusupov** [comment]
> > **June 2024 Solution**: Upgrade torch version to 2.3.1 to fix it:
> > `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`
> 
> pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118

Thanks bro, it works to me .

**Comment by guotong1988** [comment]
```
torch                    2.4.1+cu118
torchvision              0.19.1+cu118
```
fixed

**Comment by 80boys** [comment]
pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118

**Comment by amirrezasadeqi** [comment]
> > **June 2024 Solution**: Upgrade torch version to 2.3.1 to fix it:
> > `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`
> 
> pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118

solved the same problem with YOLO from ultralytics! thanks
