### ISSUE TITLE
Tensor creation under FakeMode requires real device

### ISSUE THREAD

**Issue by SherlockNoMad** [pytorch/pytorch#122109]
### 🚀 The feature, motivation and pitch

On a CPU-only machine, creating a tensor on a fake cuda device invokes CUDA device initialization: “RuntimeError: Found no NVIDIA driver on your system.” 

```
import torch
from torch._subclasses.fake_tensor import FakeTensorMode

torch.cuda.is_available()  # returns False
device = torch.device("cuda:0")

with FakeTensorMode():
   t1 = torch.empty(10, device=device)
   t2 = torch.ones(10, device=device)
   t3 = torch.zeros(10, device=device)
   t4 = torch.rand(10, device=device)
   t5 = torch.tensor([1,2,3], device=device)
```

Fake tensor creation shouldn’t require real physical device. 

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @eellison

**Comment by suo** [comment]
Marking as high priority as this issue is blocking internal workloads + assigning @zou3519 as he is dispatcher STO.

For extra context, two requirements are clashing here:
- Model publishing/export needs to be able to runnable from a CPU-only machine, where CUDA is not available.
- PT2's programming model assumes devices are constant and explicit, so we need to trace using the "correct" devices.

Internal models often have orchestration of multiple CUDA cards in a single model, so we need to exercise care in making sure everything is on the right device. The only way we have of expressing this is to put everything on the correct FakeTensors and trace it, but when we try that we are running into this issue.

Internal doc with more details: https://docs.google.com/document/d/1rwXAc_V8TnBgU5fFNbgLAUTyGHfVFj5Zorxiy8Wd49Q/edit#heading=h.2k3yvqyjsctm

**Comment by zou3519** [comment]
This is fairly non-trivial. Here are the things that we'd need to work through:
1. The way torch.tensor(data, device="cuda") works is that we disable FakeTensorMode, move the data to cuda, re-enable FakeTensorMode, and then call lift_fresh on the moved data. This is fixable -- we can introduce an option to control the behavior of torch.tensor to instead call lift_fresh first and then move the data to cuda.
2. (help wanted) For torch.empty(3, device="cuda"): the cuda init happens in libtorch_python, before we enter the Dispatcher. This is because the cuda init logic has a dependency on Python. Because it happens before we enter the Dispatcher, FakeTensorMode never has a chance to avoid the cuda init.

For (2)... a strawman proposal is that in cuda init, we check if FakeTensorMode is active, and skip it entirely. This doesn't feel good to me and I'm worried it'll run us into composability problems (e.g. if someone calls torch.empty() under FakeTensorMode, but also under no_dispatch(), we do want to do CUDA init).

Thoughts? @ezyang @eellison @bdhirsh

**Comment by ezyang** [comment]
I'm taking a look.

**Comment by ezyang** [comment]
So I fixed the first three by addressing (2). torch.tensor doesn't work because we need (1) (Richard, maybe you still plan on doing that?)

There's also some refactoring on torch.cuda API we probably have to do. Specifically, if you set_device, maybe we should make this lazy? Or maybe lazy inside of fake tensor mode. The current posted PR manually avoids invoking current_device from FakeTensor itself which is just enough for the test, but something more robust probably has to be done at the torch.cuda API level.

**Comment by zou3519** [comment]
Thanks for doing (2). I couldn't figure out how to check if the mode was available from C++.

 Let me try torch.tensor again and I'll come back here
