### ISSUE TITLE
Max-autotune template misaligned address

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#125437]
### 🐛 Describe the bug

```
import torch

@torch.compile(mode="max-autotune")
def foo(x, y):
    return x @ y


x = torch.empty_strided((50257, 32768), ((1, 50304)), dtype=torch.bfloat16, device='cuda')
y = torch.empty_strided((32768, 768), (768, 1), dtype=torch.bfloat16, device='cuda')

foo(x, y)
```

Gives

```
torch._dynamo.exc.InternalTorchDynamoError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

This repro comes from llm.c with mode='max-autotune' so would be good to fix.

### Versions

master

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by eellison** [comment]
cc @shunting314, the stride here for the input `50304` instead of `50257` is coming from comprehensive padding. The misaligned address error goes away with `TORCHINDUCTOR_COMPREHENSIVE_PADDING=0`. Would you mind taking a look ?

**Comment by shunting314** [comment]
I'll take a look. But it's strange to me since stride 50304 should be better for alignment compared to 50257. Probably some other issue gets trigged.

**Comment by shunting314** [comment]
Not sure if the stack trace is accurate, right now it fail in torch.cuda.random module: https://gist.github.com/shunting314/bcb7b72aecac95c63d115058a111aa03 .

The root cause should not be related to comprehensive padding since the padding here looks valid. I'll try adding torch.cuda.synchronize. Maybe that can help

**Comment by shunting314** [comment]
ok, here is the pure triton repro: https://gist.github.com/shunting314/cb04b62434ddedac0cc1ad5f6685f5c5 

Looks like the triton matmul kernel does not support non-contiguous input tensors well. We get misaligned memory access even though the tensor is padded to be more aligned.. cc @htyu

**Comment by htyu** [comment]
Padding to 50304 makes sense but I think you may want to align `M` with `stride_ak1` to ensure that pointer `A` moves in an aligned way. So setting `M` to 50304 should fix the issue.

**Comment by shunting314** [comment]
> Padding to 50304 makes sense but I think you may want to align M with stride_ak to ensure that pointer A moves in an aligned way.

Hmm, this actually force the tensor to be contiguous, no?

For more context, sometimes in inductor we want to pad tensors without changing tensor shape (i.e. just change strides). That's how this kernel comes from.

And it's a bit surprise that different M here would cause mis aligned memory access.

**Comment by shunting314** [comment]
Also changing M to from 50257 to 50304 has the risk to do out of range memory access for tensor A and the output tensor.

**Comment by htyu** [comment]
I'm trying to understand the kernel more. The `x` tensor there sounds like a transposed view, iiuc.

`x = torch.empty_strided((50257, 32768), ((1, 50304)), dtype=torch.bfloat16, device='cuda')`

Does the `stride(1)` give the correct element when moving down that direction? It looks like skipping 50304 elements is not going to give the same element on the next column?

**Comment by shunting314** [comment]
> Does the stride(1) give the correct element when moving down that direction? It looks like skipping 50304 elements is not going to give the same element on the next column?

The tensor is column major. There are some padded elements between 2 columns.

**Comment by htyu** [comment]
> The tensor is column major. There are some padded elements between 2 columns.

So my understanding is that in the global memory there are 32768 groups of 50257 consecutive elements: 

`50257 elems,  50257  elems, ....... 50257 elems `

Where are the padding between two columns?

**Comment by shunting314** [comment]
Here is the code  (https://gist.github.com/shunting314/cb04b62434ddedac0cc1ad5f6685f5c5#file-t-py-L76 )
```
x = torch.empty_strided((50257, 32768), ((1, 50304)), dtype=torch.bfloat16, device='cuda')
```
that creates the X tensor.

You can see that the stride(1) is 50304. It's larger than 50257. Between each of the 50257 elements you wrote above, there are gonna to be (50304 - 50257) elements get padded in.

**Comment by htyu** [comment]
> Here is the code (https://gist.github.com/shunting314/cb04b62434ddedac0cc1ad5f6685f5c5#file-t-py-L76 )
> 
> ```
> x = torch.empty_strided((50257, 32768), ((1, 50304)), dtype=torch.bfloat16, device='cuda')
> ```
> 
> that creates the X tensor.
> 
> You can see that the stride(1) is 50304. It's larger than 50257. Between each of the 50257 elements you wrote above, there are gonna to be (50304 - 50257) elements get padded in.

So `torch.empty_strided` automatically adds padding when stride and shape doesn't match? Will the padding be all zeros? If so changing `M` to 50304 should be safe?

**Comment by shunting314** [comment]
> So torch.empty_strided automatically adds padding when stride and shape don't match? Will the padding be all zeros? If so changing M to 50304 should be safe?

The padding can be anything. Changing strides is more transparent to changing shape here. Changing M can cause out of range access for the output of the matmul. (tensor z in my paste)

**Comment by htyu** [comment]
Thanks for the explanation. Indeed changing `M` can cause a problem to the output tensor which is not padded.

I took a deeper look at the IR and generated PTX. It appears that the following line caused the misalignment issue:
`
   ram = tl.max_contiguous(tl.multiple_of(rm % M, BLOCK_M), BLOCK_M)`

, in particular the modulo operation, which leads to accessing the padding area as the start address of a tile for a program. Replacing `M` there with the aligned row count `50304` works, and it shouldn't affect the output tensor as the mask is not changed?

**Comment by eellison** [comment]
@shunting314 @htyu I'm now realizing that about half the huggingface models are failing in max-autotune due to this. we should try to land a fix imminently if possible, or if dont have line of sight, turn off padding w max autotune. (seems like we do have a fix in line of sight)

**Comment by htyu** [comment]
Maybe a quick fix is to disable padding for matmul or enable padding for the output as well?

**Comment by shunting314** [comment]
@htyu changing
```
 ram = tl.max_contiguous(tl.multiple_of(rm % M, BLOCK_M), BLOCK_M)
```
to 
```
ram = rm % M
```
(i.e. removing the compiler hints) makes it work.

Do you know how the hint affect the generated PTX from triton?

**Comment by htyu** [comment]
Actually removing any of the hints i.e, `tl.multiple_of` or `tl.max_contiguous` would make it work. The cost would be to lose vectorizaiton as the memory accesses are not considered aligned or continous.

**Comment by shunting314** [comment]
> The cost would be to lose vectorizaiton as the memory accesses are not considered aligned or continous.

But not doing padding would also lose vectorization since the tensor shape is bad, right?

**Comment by shunting314** [comment]
BTW, @htyu can you help me understand when it's safe to apply `tl.multiple_of` or `tl.max_contiguous` here?

```
ram = tl.max_contiguous(tl.multiple_of(rm % M, BLOCK_M), BLOCK_M)
```

I think we can apply them only when it's safe. That probably can be a proper fix.

**Comment by shunting314** [comment]
> Maybe a quick fix is to disable padding 

If we want a quick fix, we can disable padding for max-autotune. But I think the padding here looks just valid. It just triggers some other hidden bugs.

**Comment by shunting314** [comment]
Here is some perf test:

1. Changing stride_ak from 50304 to 50257 (i.e. cancel padding), perf is 27.69ms. In this case I think even if we can apply the compiler hint, that does not help with vectorization because stride_ak is an odd number.
2. Keeps padding, but remove the compiler hints, perf is 25.33ms

**Comment by htyu** [comment]
> BTW, @htyu can you help me understand when it's safe to apply `tl.multiple_of` or `tl.max_contiguous` here?
> 
> ```
> ram = tl.max_contiguous(tl.multiple_of(rm % M, BLOCK_M), BLOCK_M)
> ```
> 
> I think we can apply them only when it's safe. That probably can be a proper fix.

`tl.multiple_of` is to indicate the compiler that the first value of the `rm % M` value range always starts at the boundary of `BLOCK_M`. This is not true in this case.

`tl.max_contiguous` tells the compiler that the value range of `rm % M` ranges from 0 to `BLOCK_M`. This is true.

Removing either of them will prevent vectorization. 

I think removing `tl.multiple_of` should be a good workaround for now. For better performance, perhaps checking if padding presents and replacing the `M` in `rm % M` to include the padding should work.

**Comment by htyu** [comment]
> Here is some perf test:
> 
> 1. Changing stride_ak from 50304 to 50257 (i.e. cancel padding), perf is 27.69ms. In this case I think even if we can apply the compiler hint, that does not help with vectorization because stride_ak is an odd number.
> 2. Keeps padding, but remove the compiler hints, perf is 25.33ms

How about changing `rm % M` to `rm % 50304 `?

**Comment by shunting314** [comment]
> tl.multiple_of is to indicate the compiler that the first value of the rm % M value range always starts at the boundary of BLOCK_M. This is not true in this case.

Why this is not true? rm is defined as `rm = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)` . The first value is `pid_m * BLOCK_M` . This value should be less than M so `pid_m * BLOCK_M % M` should be `pid_m * BLOCK_M` and is a multiple of BLOCK_M. Anything is missing here?

**Comment by shunting314** [comment]
> How about changing rm % M to rm % 50304 ?

That further improve the perf to 15.59ms.
But there are a few things to mention
1. rm % 50304 is not always in bound. The last row may not have extra items after it.
2. cublas has perf 8.34ms here.

**Comment by htyu** [comment]
> rm % 50304 is not always in bound. The last row may not have extra items after it.

The source tensor X does not have an out-of-bound issue but the value may be wrong as padding isn't always zero? Maybe we masking in `tl.load` can be tweaked to fix that.

The output tensor would not have an out-of-bound issue as the current masking should prevent that right?

> cublas has perf 8.34ms here.

Wow, this is on A100 or H100? On the Triton side there is definitely some more tuning we can do, like split-K.

**Comment by shunting314** [comment]
> The source tensor X does not have an out-of-bound issue but the value may be wrong as padding isn't always zero? Maybe we masking in tl.load can be tweaked to fix that.

Sorry, I actually mean the last column of X. For X, all columns except the last column can be guaranteed to have (PADDED_M  - M) padding items. Mask should work, but I think all the `rm % M` thing here is just to avoid mask..

**Comment by shunting314** [comment]
> Wow, this is on A100 or H100? On the Triton side there is definitely some more tuning we can do, like split-K.

A100.

**Comment by shunting314** [comment]
A WIP fix. It fixes the issue for mm (also addmm which uses the same template), but I'll check other kernels (bmm, mm_plus_mm).

**Comment by shunting314** [comment]
BTW, triton.ops.matmul has the same issue. Repro: 
https://gist.github.com/shunting314/34a1c3b0f91607ffd689b92205f3edb1 .

It can not handle non-contiguous input properly

@htyu , I can land my fix first. But we'd better figure out the root cause and fix/improve it for both inductor and triton.

**Comment by htyu** [comment]
> For X, all columns except the last column can be guaranteed to have (PADDED_M - M) padding items. 

I see. That's an issue.

> cublas has perf 8.34ms here.

Did you get the number from the inductor? Does inductor by default use cublas?

**Comment by shunting314** [comment]
> Did you get the number from the inductor? Does inductor by default use cublas?

I get the number via:
```
ms2 = do_bench(lambda: x @ y)
```

Inductor by default does not have max-autotune enabled and use cublas for matmul
