### ISSUE TITLE
"torch.matrix_exp" performs differently on cpu and gpu

### ISSUE THREAD

**Issue by Redmept1on** [pytorch/pytorch#126749]
### 🐛 Describe the bug

**Describe the bug**
When dealing with inf and nan, "torch.matrix_exp" gets different output on the cpu and gpu
**To Reproduce**
```python
import torch
import numpy as np

input_tensor=torch.tensor(np.array([[float('inf'), float('nan'), 5],[float('inf'), float('nan'), 5],[float('inf'), float('nan'), 5]], dtype=np.float32))

cpu = torch.matrix_exp(input_tensor)
print(cpu)

input_tensor = input_tensor.cuda()
gpu = torch.matrix_exp(input_tensor)
print(gpu)
```

![image](https://github.com/pytorch/pytorch/assets/84373897/ecda6efd-2063-4799-bc62-652fa1a0ab69)

**Version** 
- torch                        2.0.0+cu117
- UBUNTU 18.04

### Versions

PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (GCC) 9.3.0
Clang version: 10.0.0-4ubuntu1~18.04.2 
CMake version: version 3.27.2
Libc version: glibc-2.27

Python version: 3.11.0 (main, Aug 31 2023, 06:45:10) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-197-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA TITAN RTX
GPU 1: NVIDIA TITAN RTX

Nvidia driver version: 525.147.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              48
On-line CPU(s) list: 0-47
Thread(s) per core:  2
Core(s) per socket:  12
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz
Stepping:            4
CPU MHz:             1011.552
BogoMIPS:            5200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            19712K
NUMA node0 CPU(s):   0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46
NUMA node1 CPU(s):   1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] onnx==1.15.0
[pip3] tf2onnx==1.15.1
[pip3] torch==2.0.0+cu117
[pip3] torchvision==0.15.0+cu117
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.6           py311ha02d727_1  
[conda] mkl_random                1.2.2           py311ha02d727_1  
[conda] numpy                     1.24.3          py311h08b1b3b_1  
[conda] numpy-base                1.24.3          py311hf175353_1  
[conda] numpydoc                  1.5.0           py311h06a4308_0  
[conda] pytorch                   2.0.1           cpu_py311h6d93b4c_0

**Comment by ZailiWang** [comment]
I'm not reproducing the difference with a recent nightly version. 
```
tensor([[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]])
tensor([[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]], device='cuda:0')
```
Would you verify again with latest nightly env?

**Comment by Redmept1on** [comment]
I tried again with latest nightly env, the result is same as yours. Thanks for your solution.
A lot of my work has been done under Pytorch version 2.0.0, so I think this is a Nans and Infs issue and should be fixed.

**Comment by janeyx99** [comment]
Closing as this works now; thanks @ZailiWang for reproing!

**Comment by Redmept1on** [comment]
Hello, I would like to ask, for pytorch, if these problems are solved in the latest version of pytorch, it will not be identified as bugs in the past version such as torch2.0.0 and fix these problems, right?

**Comment by janeyx99** [comment]
Yes we do not go fix past versions, as that has implications on stability/BC-breakingness and how versioning works. For new releases like 2.3.0, we do release point releases like 2.3.1 fixing critical bugs found in 2.3.0.

**Comment by Redmept1on** [comment]
Thanks for response!
