### ISSUE TITLE
Incorrect behavior of dtensor full_tensor for TP+FSDP2

### ISSUE THREAD

**Issue by vermouth1992** [pytorch/pytorch#129229]
### 🐛 Describe the bug

```python
import torch
import os
os.environ['NCCL_DEBUG'] = 'WARN'
from torch import nn
from torch import distributed as dist
from torch.distributed.device_mesh import init_device_mesh

from torch.distributed.tensor.parallel import parallelize_module, RowwiseParallel
from torch.distributed._tensor import Replicate

device = 'cuda' if torch.cuda.is_available() else 'cpu'
backend = 'nccl' if device == 'cuda' else 'gloo'

rank = int(os.environ["RANK"])
world_size = int(os.environ["WORLD_SIZE"])
local_rank = int(os.environ["LOCAL_RANK"])
dist.init_process_group(backend=backend, world_size=world_size)
if device == 'cuda':
    torch.cuda.set_device(local_rank)

device_mesh = init_device_mesh(device, [2, 2], mesh_dim_names=['dp', 'tp'])
tp_mesh = device_mesh['tp']

def print_on_all_rank(string=None):
    rank = dist.get_rank()
    for i in range(world_size):
        if i == rank:
            print(f'Global rank: {rank}, tp_rank: {device_mesh["tp"].get_local_rank()}, dp_rank: {device_mesh["dp"].get_local_rank()}')
            if string is not None:
                print(string)
        dist.barrier()

with torch.device(device):
    model = nn.Embedding(num_embeddings=4, embedding_dim=1)
    # hardcode the weights to visualize and reproduce
    model.weight.data[0, 0] = 0.
    model.weight.data[1, 0] = 1.
    model.weight.data[2, 0] = 2.
    model.weight.data[3, 0] = 3.


# apply tp
model = parallelize_module(
    model,
    tp_mesh,
    parallelize_plan=RowwiseParallel(
        input_layouts=Replicate(),
        output_layouts=Replicate(),
    ),
)

# apply fsdp2
from torch.distributed._composable.fsdp import fully_shard

model = fully_shard(model, mesh=device_mesh['dp'], reshard_after_forward=True)
# The following line doesn't work with 2.3.1. Use nightly instead
model.unshard()

# print embedding weights on each rank
print_on_all_rank(model.weight)

full_tensor = model.weight.full_tensor()

if rank == 0:
    print(full_tensor)

dist.barrier()
```

I am trying to use TP+FSDP2. However, I find that the behavior of dtensor's full_tensor has incorrect semantic meaning. Here is an example above. There is only an embedding layer with initial parameters [0,1,2,3]. After call TP and FSDP sharding, we observe that 
tp_rank 0, dp_rank 0 has 0
tp_rank 1, dp_rank 0 has 2
tp_rank 0, dp_rank 1 has 1
tp_rank 1, dp_rank 1 has 3
This is correct according to the resharding order (first tp, then FSDP).
However, when we call full_tensor, the weights becomes [0, 2, 1, 3], which has different semantic meaning as the sharded embedding layer.

To run the above code,
```bash
torchrun --node_rank=0 --nproc_per_node=4 --nnodes=1 --standalone playground.py
```
This can be reproduced on either CPU or GPU. Thank you for your help!

Here is the output of my run.

Global rank: 0, tp_rank: 0, dp_rank: 0
DTensor(local_tensor=tensor([[0.]], device='cuda:0'), device_mesh=DeviceMesh([[0, 1], [2, 3]], mesh_dim_names=['dp', 'tp']), placements=(Shard(dim=0), Shard(dim=0)))
Global rank: 1, tp_rank: 1, dp_rank: 0
DTensor(local_tensor=tensor([[2.]], device='cuda:1'), device_mesh=DeviceMesh([[0, 1], [2, 3]], mesh_dim_names=['dp', 'tp']), placements=(Shard(dim=0), Shard(dim=0)))
Global rank: 2, tp_rank: 0, dp_rank: 1
DTensor(local_tensor=tensor([[1.]], device='cuda:2'), device_mesh=DeviceMesh([[0, 1], [2, 3]], mesh_dim_names=['dp', 'tp']), placements=(Shard(dim=0), Shard(dim=0)))
Global rank: 3, tp_rank: 1, dp_rank: 1
DTensor(local_tensor=tensor([[3.]], device='cuda:3'), device_mesh=DeviceMesh([[0, 1], [2, 3]], mesh_dim_names=['dp', 'tp']), placements=(Shard(dim=0), Shard(dim=0)))
NCCL version 2.20.5+cuda12.4
tensor([[0.],
        [2.],
        [1.],
        [3.]], device='cuda:0', grad_fn=<_ToTorchTensorBackward>)

### Versions

Collecting environment information...
PyTorch version: 2.3.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.29.5
Libc version: glibc-2.31

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.10.135.bsk.6-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H800
GPU 1: NVIDIA H800
GPU 2: NVIDIA H800
GPU 3: NVIDIA H800

Nvidia driver version: 535.129.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   52 bits physical, 57 bits virtual
CPU(s):                          180
On-line CPU(s) list:             0-179
Thread(s) per core:              2
Core(s) per socket:              45
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           143
Model name:                      Intel(R) Xeon(R) Platinum 8457C
Stepping:                        8
CPU MHz:                         2599.851
BogoMIPS:                        5199.70
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       4.2 MiB
L1i cache:                       2.8 MiB
L2 cache:                        180 MiB
L3 cache:                        195 MiB
NUMA node0 CPU(s):               0-89
NUMA node1 CPU(s):               90-179
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx_vnni avx512_bf16 wbnoinvd arat avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid cldemote movdiri movdir64b fsrm md_clear serialize tsxldtrk arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pytorch-triton==3.0.0+45fff310c8
[pip3] torch==2.3.1
[pip3] torchaudio==2.4.0.dev20240620+cu121
[pip3] torchvision==0.20.0.dev20240620+cu121
[pip3] triton==2.3.1
[conda] Could not collect
```[tasklist]
### Tasks
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @rohan-varma

**Comment by vermouth1992** [comment]
I guess this also might be the reason when we save the mode using dcp, merge it with format_utils and then load it into a single GPU model, the output can't match with the distributed model.

**Comment by awgu** [comment]
Hey @vermouth1992, thanks for trying out FSDP2!

This is a known issue (e.g. search for "strided sharding" in https://github.com/pytorch/pytorch/issues/120003 or see more discussion in https://github.com/pytorch/pytorch/issues/114299#issuecomment-2132254189). Like you saw, the issue is that `DTensor` with `(Shard(0), Shard(0))` placement follows left-to-right sharding order, so for device mesh like `(dp, tp)`, `DTensor` would assume sharding first with FSDP then TP, which differs from our actual sharding order of TP then FSDP.

We definitely want to fix this since it blocks 2D correctness when loading a model with different parallelism or saving a model to different parallelism. The current plan is to introduce a strided sharding placement that can capture that the sharding is not representing contiguous left-to-right strides. cc: @wanchaol @XilunWu  on the precise plan and timeline

**Comment by vermouth1992** [comment]
Is there any workaround currently besides manually allgather local tensors?

**Comment by awgu** [comment]
Is your goal just to support the semantics of `.full_tensor`, or is it more broadly loading a model or something like that?

**Comment by vermouth1992** [comment]
Got it! That's actually exactly what we need currently and bf16 is even better than fp32 since we need the weights to perform generation during training. For generation, bf16 is perfectly fine.

We will wait for the fix in order to use dcp.save. Is there any timeline of the fix?

**Comment by vermouth1992** [comment]
> Is this for debugging, or is this performance critical?
> 
> We have a `fsdp_module.unshard()` API that can all-gather along DP, but it does so for all of the `fsdp_module`'s managed parameters together.
> 
> https://github.com/pytorch/pytorch/blob/b0ae0db8156f186eaed69b0332d8698a8dfc799a/torch/distributed/_composable/fsdp/fully_shard.py#L174
> 
> 
> You can call `fsdp_module.reshard()` after to reshard parameters (including freeing the all-gathered ones). Note though, that we do not support writing back, so changes to the all-gathered parameters would not be reflected to the sharded parameters.
> Edit: However, this `unshard()` would all-gather in bf16 if you used mixed precision with `param_dtype=torch.bfloat16`, so this might not be what you want.

Hi @awgu, thanks for your solution. It turns out that unshard API doesn't exist in the 2.3.1 stable version. So I used the latest nightly 2.5.0.dev20240621+cu121. I added ``model.reshard`` after calling `fully_shard` and it throws the following error

```bash
[rank0]:   File "/opt/tiger/verl/examples/dtensor/playground.py", line 60, in <module>
[rank0]:     model.unshard()
[rank0]:   File "/usr/local/lib/python3.9/dist-packages/torch/distributed/_composable/fsdp/fully_shard.py", line 199, in unshard
[rank0]:     handle.wait()
[rank0]:   File "/usr/local/lib/python3.9/dist-packages/torch/distributed/_composable/fsdp/fully_shard.py", line 372, in wait
[rank0]:     self._fsdp_param_group.wait_for_unshard()
[rank0]:   File "/usr/local/lib/python3.9/dist-packages/torch/distributed/_composable/fsdp/_fsdp_param_group.py", line 245, in wait_for_unshard
[rank0]:     self._wait_all_gather_streams_on_event(all_gather_copy_out_event)
[rank0]:   File "/usr/local/lib/python3.9/dist-packages/torch/distributed/_composable/fsdp/_fsdp_param_group.py", line 249, in _wait_all_gather_streams_on_event
[rank0]:     self.comm_ctx.all_gather_copy_in_stream.wait_event(event)
[rank0]: AttributeError: 'FSDPCommContext' object has no attribute 'all_gather_copy_in_stream'
```

Which nightly version should I use in order to make this work? Thanks!

**Comment by awgu** [comment]
This is probably a bug. Would it be easy to give me a repro? I can probably fix it today.

**Comment by vermouth1992** [comment]
> This is probably a bug. Would it be easy to give me a repro? I can probably fix it today.

I just updated the code snippet above to use model.unshard for you to reproduce

**Comment by awgu** [comment]
@vermouth1992 In the mean time, can you try to run the following before `model.unshard`?
```
fsdp_state = fully_shard.state(model)
fsdp_state._lazy_init()
model.unshard()
```

**Comment by vermouth1992** [comment]
Nice. It actually works :)

```bash
DTensor(local_tensor=tensor([[0.],
        [1.]], device='cuda:0'), device_mesh=DeviceMesh([0, 1], mesh_dim_names=('tp',)), placements=(Shard(dim=0),))
Global rank: 1, tp_rank: 1, dp_rank: 0
DTensor(local_tensor=tensor([[2.],
        [3.]], device='cuda:1'), device_mesh=DeviceMesh([0, 1], mesh_dim_names=('tp',)), placements=(Shard(dim=0),))
Global rank: 2, tp_rank: 0, dp_rank: 1
DTensor(local_tensor=tensor([[0.],
        [1.]], device='cuda:2'), device_mesh=DeviceMesh([2, 3], mesh_dim_names=('tp',)), placements=(Shard(dim=0),))
Global rank: 3, tp_rank: 1, dp_rank: 1
DTensor(local_tensor=tensor([[2.],
        [3.]], device='cuda:3'), device_mesh=DeviceMesh([2, 3], mesh_dim_names=('tp',)), placements=(Shard(dim=0),))
tensor([[0.],
        [1.],
        [2.],
        [3.]], device='cuda:0', grad_fn=<_ToTorchTensorBackward>)
```

**Comment by awgu** [comment]
I opened a PR https://github.com/pytorch/pytorch/pull/129241 to fix the AttributeError: 'FSDPCommContext' object has no attribute 'all_gather_copy_in_stream' issue.

> Also, the full_tensor seems correct, too. So, I guess this might be the workaround to save dcp as well.

I think that makes sense 🤔  You can go `FSDPModule` by `FSDPModule` calling `.unshard()` to get tensor-parallel-only `DTensor`s and save those, making sure to `reshard()` after saving that module's parameters to avoid using too much GPU memory.

**Comment by awgu** [comment]
@vermouth1992 We have done some work to minimize the performance penalty of per-parameter sharding. Concretely, the main cost in our implementation is from extra device copies around all-gather, mainly the "all-gather copy-out". In short, we would incur an extra memory read/write for each parameter in forward (and in backward if `reshard_after_forward=True`).

For example, for the same FSDP "wrapping", we still run the same all-gather/reduce-scatter kernels, just with the data permuted due to the different sharding approach.

We improved some things to make our backward pass faster (somewhat similar to yaFSDP if you saw that recently), so overall, we may even be able to get slight speedups over FSDP1 at times (e.g. see the benchmarks in https://github.com/pytorch/torchtitan/pull/165).

---

Note that while we use `DTensor` to represent the sharded parameters, we are not actually using `DTensor` to do all-gathers/reduce-scatters. We are manually implementing "batched all-gathers/reduce-scatters" that allow us to group together parameters/gradients into one NCCL kernel in the same way as flat-parameter sharding.

**Comment by vermouth1992** [comment]
@awgu Filed a new issue regarding model.unshard and dcp. It seems that calling dcp get_model_state_dict makes the model fully sharded again, and makes checkpoint still incorrect :(

**Comment by awgu** [comment]
This should be correct after strided sharding support, which is landed.

**Comment by 23Uday** [comment]
@awgu. Do you have a recommended way of saving a FSDP2 model with full state dictionary?
