### ISSUE TITLE
torch.distributed hangs at first barrier call after upgrading to 2.4

### ISSUE THREAD

**Issue by denizokt** [pytorch/pytorch#131952]
### 🐛 Describe the bug

Hi all, we are using torch.distributed using slurm as a backend. We recently upgraded from PyTorch 2.1 to 2.4 and our training script hangs at the first collective, even though I can confirm all the ranks get there.

I have the following reproducer script that works for 2.1 but not for 2.4:

```python
import subprocess
import torch
import torch.distributed
import os
import random

def get_slurm_master_port():
    job_id = int(os.environ.get("SLURM_JOB_ID", -1))
    MIN_MASTER_PORT, MAX_MASTER_PORT = (20000, 60000)
    rng = random.Random(job_id)
    return rng.randint(MIN_MASTER_PORT, MAX_MASTER_PORT)

def get_slurm_master_addr():
    hostnames = subprocess.check_output(
        ["scontrol", "show", "hostnames", os.environ["SLURM_JOB_NODELIST"]]
    )
    return hostnames.split()[0].decode("utf-8")

def get_local_world_size() -> int:
    return int(os.environ["SLURM_NTASKS_PER_NODE"])

def get_local_rank() -> int:
    return int(os.environ["SLURM_LOCALID"])

def get_device_from_env() -> torch.device:
    gpu_rank = get_local_rank()
    device = torch.device(f"cuda:{gpu_rank}")
    torch.cuda.set_device(device)
    return device

if __name__ == "__main__":
    os.environ["RANK"] = os.environ["SLURM_PROCID"]
    os.environ["LOCAL_RANK"] = str(get_local_rank())
    os.environ["WORLD_SIZE"] = os.environ["SLURM_NTASKS"]
    os.environ["MASTER_ADDR"] = str(get_slurm_master_addr())
    os.environ["MASTER_PORT"] = str(get_slurm_master_port())
    os.environ["LOCAL_WORLD_SIZE"] = str(get_local_world_size())

    device = get_device_from_env()
    torch.distributed.init_process_group(
        init_method=None, backend="nccl",
    )

    print(f"Rank: {torch.distributed.get_rank()}", flush=True)
    torch.distributed.barrier()
    print(f"After barrier", flush=True)
```

Is there anything I am missing? Thank you! 

### Versions

```
Collecting environment information...                                                      
PyTorch version: 2.4.0                                                                     
Is debug build: False                                                                      
CUDA used to build PyTorch: 12.1                                                           
ROCM used to build PyTorch: N/A                                                            
                                                                                           
OS: Ubuntu 20.04.6 LTS (x86_64)                                                            
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0                                         
Clang version: Could not collect                                                           
CMake version: version 3.30.1                                                              
Libc version: glibc-2.31                                                                   
                                                                                           
Python version: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.
4.0] (64-bit runtime)                                                                      

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.8
[pip3] mypy==1.10.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] torch==2.4.0
[pip3] torchmetrics==1.4.0.post0
[pip3] torchtext==0.6.0
[pip3] torchvision==0.19.0
[pip3] triton==3.0.0
[conda] blas                      1.0                         mkl    conda-forge
[conda] cudatoolkit               11.8.0              h4ba93d1_13    conda-forge
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] libopenvino-pytorch-frontend 2024.2.0             he02047a_1    conda-forge
[conda] mkl                       2022.1.0           hc2b9512_224    anaconda
[conda] msgpack-numpy             0.4.8              pyhd8ed1ab_0    conda-forge
[conda] numpy                     1.26.4          py310hb13e2d6_0    conda-forge
[conda] pytorch                   2.4.0           py3.10_cuda12.1_cudnn9.1.0_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchmetrics              1.4.0.post0        pyhd8ed1ab_0    conda-forge
[conda] torchtext                 0.6.0                      py_1    pytorch
[conda] torchtriton               3.0.0                     py310    pytorch
[conda] torchvision               0.19.0              py310_cu121    pytorch
```

**Comment by denizokt** [comment]
UPDATE: This works on single node. Not on multinode.

**Comment by dbfancier** [comment]
> UPDATE: This works on single node. Not on multinode. The gloo backend works fine. It's only NCCL that doesn't work.
> 
> UPDATE: Closing because I suspect it's something on our side.

We seem to have a similar problem, would you like share how you solved it ?

**Comment by denizokt** [comment]
> > UPDATE: This works on single node. Not on multinode. The gloo backend works fine. It's only NCCL that doesn't work.
> > UPDATE: Closing because I suspect it's something on our side.
> 
> We seem to have a similar problem, would you like share how you solved it ?

Turns out the specific version of NCCL that the default PyTorch 2.4 was pinned to had a bug for the particular network config we had. We compiled a new PyTorch with an updated version of NCCL.
