### ISSUE TITLE
Bug Report: Distributed Process Group Hangs with NCCL and GLOO Backends

### ISSUE THREAD

**Issue by zhanghb55** [pytorch/pytorch#132003]
#### Environment
- **PyTorch version**: 2.4.0
- **CUDA version**: 12.4

#### Description
When running a distributed training script using `torchrun` with a mixed backend setup (NCCL and GLOO), the script hangs indefinitely after a few ranks have communicated. Specifically, the script hangs after Rank 2 sends a tensor to Rank 3 using NCCL.

#### Command
```sh
torchrun --nproc_per_node=5 --master_addr=localhost --master_port=29501 test.py
```

#### Log Output
```
W0729 03:35:32.842631 140034607273792 torch/distributed/run.py:779] 
W0729 03:35:32.842631 140034607273792 torch/distributed/run.py:779] *****************************************
W0729 03:35:32.842631 140034607273792 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0729 03:35:32.842631 140034607273792 torch/distributed/run.py:779] *****************************************
Rank 0 sent tensor tensor([1.], device='cuda:0') to Rank 1 using NCCL
Rank 1 received tensor tensor([1.], device='cuda:1') from Rank 0 using NCCL
[rank0]:[W729 03:35:39.435986437 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
Rank 1 sent tensor tensor([1.], device='cuda:1') to Rank 2 using NCCL
Rank 2 received tensor tensor([1.], device='cuda:2') from Rank 1 using NCCL
```

#### Code
```python
import os
import torch
import torch.distributed as dist

def worker(rank, world_size):
    # Initialize the process group without specifying the backend
    dist.init_process_group(backend=None, rank=rank, world_size=world_size)
    
    # Set the CUDA device for the current process based on the rank (only for ranks < 4)
    if rank < 4:
        torch.cuda.set_device(rank % torch.cuda.device_count())
    
    # Create an NCCL process group, including ranks 0, 1, 2, 3
    if rank < 4:
        group_nccl = dist.new_group(ranks=[0, 1, 2, 3], backend="nccl")
    
    # Create a GLOO process group, including ranks 3, 4
    if rank >= 3:
        group_gloo = dist.new_group(ranks=[3, 4], backend="gloo")
    
    if rank == 0:
        tensor = torch.tensor([1.0]).cuda()
        dist.send(tensor=tensor, dst=1, group=group_nccl)
        print(f"Rank {rank} sent tensor {tensor} to Rank 1 using NCCL")
    elif rank == 1:
        tensor = torch.tensor([0.0]).cuda()
        dist.recv(tensor=tensor, src=0, group=group_nccl)
        print(f"Rank {rank} received tensor {tensor} from Rank 0 using NCCL")
        dist.send(tensor=tensor, dst=2, group=group_nccl)
        print(f"Rank {rank} sent tensor {tensor} to Rank 2 using NCCL")
    elif rank == 2:
        tensor = torch.tensor([0.0]).cuda()
        dist.recv(tensor=tensor, src=1, group=group_nccl)
        print(f"Rank {rank} received tensor {tensor} from Rank 1 using NCCL")
        dist.send(tensor=tensor, dst=3, group=group_nccl)
        print(f"Rank {rank} sent tensor {tensor} to Rank 3 using NCCL")
    elif rank == 3:
        tensor_nccl = torch.tensor([0.0]).cuda()
        dist.recv(tensor=tensor_nccl, src=2, group=group_nccl)
        print(f"Rank {rank} received tensor {tensor_nccl} from Rank 2 using NCCL")

        tensor_gloo = tensor_nccl.cpu()
        dist.send(tensor=tensor_gloo, dst=4, group=group_gloo)
        print(f"Rank {rank} sent tensor {tensor_gloo} to Rank 4 using GLOO")
    elif rank == 4:
        tensor = torch.tensor([0.0])
        dist.recv(tensor=tensor, src=3, group=group_gloo)
        print(f"Rank {rank} received tensor {tensor} from Rank 3 using GLOO")

def main():
    world_size = int(os.environ['WORLD_SIZE'])
    rank = int(os.environ['RANK'])
    worker(rank, world_size)

if __name__ == "__main__":
    main()
```

### Versions

torchrun --nproc_per_node=5 --master_addr=localhost --master_port=29501 test.py

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by awgu** [comment]
<img width="999" alt="Screenshot 2024-07-29 at 6 11 13 PM" src="https://github.com/user-attachments/assets/68112168-063b-4a49-9674-fcc48cd8c494">
It looks like your code as-is is not supported since only a strict subset of ranks are entering `new_group`.

**Comment by zhenyuhe00** [comment]
Same issue.

**Comment by mathmax12** [comment]
Facing the same issue.

**Comment by yitianlian** [comment]
same issue

**Comment by mohsenhariri** [comment]
second this

**Comment by Armarella** [comment]
same issue

**Comment by JohnConnor123** [comment]
Same in vllm

**Comment by sh0416** [comment]
@JohnConnor123 FYI, I resolved it by downgrading vllm version and torch version. It works on torch==2.4.1 and vllm==0.6.3.post1

**Comment by kwen2501** [comment]
As @awgu mentioned, the `new_group` API requires all ranks in the globe to enter the call (this hasn't changed over the recent versions). Otherwise, there is risk of hang.

**Comment by kwen2501** [comment]
We will update the thread if PyTorch comes up with an API to support group creation without global requirement.

**Comment by vitkl** [comment]
I see the same issue and I am using PyTorch Lightning DDP.

**Comment by tmacsyf** [comment]
same issue

**Comment by ai-nikolai** [comment]
same issue. 

```
vllm==0.6.6.post1
torch==2.5.1
```

**Comment by ecgbeald** [comment]
same issue

**Comment by CiaoHe** [comment]
same issue vllm==0.7.3, torch==2.5.1
