### ISSUE TITLE
2:4 semi structured sparsity matmul not supported on hopper

### ISSUE THREAD

**Issue by OrenLeung** [pytorch/pytorch#132009]
### 🐛 Describe the bug

i am trying to benchmark semi structured matmuls on hopper (sm90) and trying out the pytorch semi structured tutorial to get a understand of the torch sparsity APIs but unfortunately pytorch sparsity doesnt support anything besides sm80. i tried both the cutlass code path and the cusparseLt code path but none of them work.

https://pytorch.org/tutorials/prototype/semi_structured_sparse.html

## error msg
```python
python3 structured.py 
Traceback (most recent call last):
  File "/home/ubuntu/clusterMAX/structured.py", line 51, in <module>
    linear.weight = torch.nn.Parameter(to_sparse_semi_structured(linear.weight))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/sparse/semi_structured.py", line 378, in to_sparse_semi_structured
    return SPARSE_SUBCLASS.from_dense(original_tensor)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/sparse/semi_structured.py", line 537, in from_dense
    packed=torch._cslt_compress(original_tensor),
RuntimeError: CUDA error: architecture mismatch when calling `cusparseLtInit(&handle)`
```

## reprod
```python
import torch
from torch.sparse import to_sparse_semi_structured, SparseSemiStructuredTensor
from torch.utils.benchmark import Timer
SparseSemiStructuredTensor._FORCE_CUTLASS = False

# mask Linear weight to be 2:4 sparse
mask = torch.Tensor([0, 0, 1, 1]).tile((3072, 2560)).cuda().bool()
linear = torch.nn.Linear(10240, 3072).half().cuda().eval()
linear.weight = torch.nn.Parameter(mask * linear.weight)

x = torch.rand(3072, 10240).half().cuda()

with torch.inference_mode():
    dense_output = linear(x)
    dense_t = Timer(stmt="linear(x)",
                    globals={"linear": linear,
                             "x": x}).blocked_autorange().median * 1e3

    # accelerate via SparseSemiStructuredTensor
    linear.weight = torch.nn.Parameter(to_sparse_semi_structured(linear.weight))

    sparse_output = linear(x)
    sparse_t = Timer(stmt="linear(x)",
                    globals={"linear": linear,
                             "x": x}).blocked_autorange().median * 1e3

    # sparse and dense matmul are numerically equivalent
    assert torch.allclose(sparse_output, dense_output, atol=1e-3)
    print(f"Dense: {dense_t:.3f}ms Sparse: {sparse_t:.3f}ms | Speedup: {(dense_t / sparse_t):.3f}x")
```

### Versions

h100, nightly

**Comment by OrenLeung** [comment]
when trying the cutblass code path with `SparseSemiStructuredTensor._FORCE_CUTLASS = True`, i run into this error msg `Supported only on GPUs with compute capability 8.x` located at
https://github.com/pytorch/pytorch/blob/5b3b2b9cc79ebb45ded342b246d45853a79243ba/aten/src/ATen/native/sparse/cuda/SparseSemiStructuredOps.cu#L539

i tried removed the sm8x check and it works but unfortunately, sparse becomes slower than dense as the cutlass is using sm80 style https://github.com/pytorch/pytorch/blob/5b3b2b9cc79ebb45ded342b246d45853a79243ba/aten/src/ATen/native/sparse/cuda/SparseSemiStructuredOps.cu#L55-L59

```bash
Dense: 0.283ms Sparse: 0.385ms | Speedup: 0.737x
```

**Comment by OrenLeung** [comment]
@bilal2vec any *spare* cycles to to update `cuSparseLT` to 0.6.2?

**Comment by robogast** [comment]
Just a small comment: cusparselt release 3.6 now seems to support native structured sparsity on hopper:
![image](https://github.com/user-attachments/assets/67fdd648-e482-4ee6-ad14-2c419cbe83ec)
