### ISSUE TITLE
Problems with GPU capability "cuda runtime error (8) : invalid device function"

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#13207]
I installed master of PyTorch from sources as:
`TORCH_CUDA_ARCH_LIST=5.2 python3 setup.py install` (because of https://github.com/pytorch/pytorch/issues/4716)

I'm getting:
```python
import torch

print(torch.cuda.get_device_name(0))
# 'TITAN X (Pascal)'

print(torch.cuda.get_device_capability(0))
# (6, 1)

torch.rand(2, 2).cuda().sum()
# RuntimeError: CUDA error: invalid device function
```

Compilation succeeds fine, so `TORCH_CUDA_ARCH_LIST` seems to have worked during compilation, but not during execution.

Did I specify `TORCH_CUDA_ARCH_LIST` wrong? Should it have been 6.1? Or did `TORCH_CUDA_ARCH_LIST` not work?

**Comment by SsnL** [comment]
Yeah the device arch is not backward compatible. You have to put every compute capability in `TORCH_CUDA_ARCH_LIST`. However, I think we automatically capability of all available GPUs... We should fix it if we are not. And yes, a better error will be great.

**Comment by vadimkantorov** [comment]
@SsnL Is it not forward-compatible as well? Can't 5.2-compiled code run on 6.1? (it seems it can't, but it's strange)

The reason I was putting it manually is https://github.com/pytorch/pytorch/issues/4716. I'm using a machine which also has a small desktop GPU with capability of 2.0, and compilation fails, since it tries to target it as well.

**Comment by soumith** [comment]
@vadimkantorov CUDA CAPABILITY 5.2 has shfl_xor instructions. CUDA CAPABILITY 2.0 / 2.1 will be 2.0 or 2.1(2.0, not 5.2.

**Comment by vadimkantorov** [comment]
@soumith You are right, and because of that I manually set 5.2 and it compiled well. However in runtime it still fails. Had to recompile again with setting 6.1, then it works.

I was confused that 5.2 does not seem to be forward-compatible with 6.1 in runtime (and that PyTorch doesn't error out nicely)
and my old grievance is https://github.com/pytorch/pytorch/issues/4716 which doesn't catch trying to implicitly compile for 2.0 on machines with a small desktop gpu.

**Comment by soumith** [comment]
if you want forward-compatibility, you can set "5.2+PTX", and then it'll JIT-compile all of the CUDA kernels for 6.1. It's not an ideal thing to do, it's better to set "5.2,6.1"

**Comment by vadimkantorov** [comment]
Got it. Then maybe the only actionable feature request in this issue is a nice error from PyTorch if capability is absent (though it would require parsing TORCH_CUDA_ARCH_LIST syntax?)
