### ISSUE TITLE
Memory error for batched inverse

### ISSUE THREAD

**Issue by MarcoForte** [pytorch/pytorch#13276]
## 🐛 Bug

There seems to be a limit of N=256x256 for the number of batches one can invert on the gpu. I don't think this limit corresponds properly to available memory. Because I can run a N=256x256 -1 batched inverse on a gpu with less availiable memory. I have tested tensorflow on google collab and it allows batched inverse of size N=6144x6144.

## To Reproduce

```
import torch
N = 256
x = torch.randn(N*N , 2, 2).cuda()
y = torch.inverse(x)
print(y.cpu().numpy())
```

Error:

> ----> 1 y.cpu().numpy()
> 
> RuntimeError: cuda runtime error (9) : invalid configuration argument at /opt/conda/conda-bld/pytorch-nightly_1540802486426/work/aten/src/THC/THCTensorCopy.cu:205

## Expected behavior
It works if I reduce the batch dimension by one.
`x = torch.randn(N*N -1 , 2, 2).cuda()
`
## Environment

> PyTorch version: 1.0.0.dev20181029
> Is debug build: No
> CUDA used to build PyTorch: 8.0.61
> 
> OS: Ubuntu 16.04.4 LTS
> GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
> CMake version: version 3.11.0
> 
> Python version: 3.6
> Is CUDA available: Yes
> CUDA runtime version: 9.1.85
> GPU models and configuration: 
> GPU 0: GeForce GTX 1080
> GPU 1: GeForce GTX 1080
> 
> Nvidia driver version: 387.26
> cuDNN version: Probably one of the following:
> /usr/local/MATLAB/R2016b/bin/glnxa64/libcudnn.so.4.0.7
> /usr/local/cuda-9.1/lib64/libcudnn.so
> /usr/local/cuda-9.1/lib64/libcudnn.so.7
> /usr/local/cuda-9.1/lib64/libcudnn.so.7.0.5
> /usr/local/cuda-9.1/lib64/libcudnn.so.7.1.1
> /usr/local/cuda-9.1/lib64/libcudnn_static.a
> 
> Versions of relevant libraries:
> [pip] Could not collect
> [conda] cuda80                    1.0                           0    soumith
> [conda] cuda91                    1.0                  h4c16780_0    pytorch
> [conda] guided-filter-pytorch     1.1.1                     <pip>
> [conda] magma-cuda91              2.3.0                         1    pytorch
> [conda] pytorch-nightly           1.0.0.dev20181029 py3.6_cuda8.0.61_cudnn7.1.2_0  [cuda80]  pytorch
> [conda] torch                     0.4.0                     <pip>
> [conda] torch                     0.3.1                     <pip>

**Comment by zou3519** [comment]
Could you run with CUDA_LAUNCH_BLOCKING=1 and then report back what the error message is?

**Comment by MarcoForte** [comment]
Hi, I basically get the same error, more fully

> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch-nightly_1540802486426/work/aten/src/THC/THCTensorCopy.cu line=205 error=9 : invalid configuration argument
> Traceback (most recent call last):
>   File "inverse test.py", line 25, in <module>
>     print(y.cpu().numpy())
> RuntimeError: cuda runtime error (9) : invalid configuration argument at /opt/conda/conda-bld/pytorch-nightly_1540802486426/work/aten/src/THC/THCTensorCopy.cu:205
>

**Comment by vishwakftw** [comment]
@zou3519 could this be MAGMA related?

**Comment by vishwakftw** [comment]
I am not able to reproduce this. I tested it on a system with the following config:
```
PyTorch version: 1.0.0a0+bb703b1
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce 940M
Nvidia driver version: 396.54
cuDNN version: Probably one of the following:
/usr/local/cuda-9.2/lib64/libcudnn.so
/usr/local/cuda-9.2/lib64/libcudnn.so.7
/usr/local/cuda-9.2/lib64/libcudnn.so.7.2.1
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.15.0)
[pip] torch (1.0.0a0+bb703b1, /media/vishwak/Official/Projects/pytorch)
[pip] torchvision (0.2.1)
[conda] torch                     1.0.0a0+bb703b1           <pip>
```
MAGMA 2.3.0 installed from source.

It's highly likely that it is a MAGMA related issue.

**Comment by MarcoForte** [comment]
I installed pytorch from source following the instructions. But I still get the same error
```
PyTorch version: 1.0.0a0+47c0d88
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
CMake version: version 3.12.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080

Nvidia driver version: 387.26
cuDNN version: Probably one of the following:
/usr/local/MATLAB/R2016b/bin/glnxa64/libcudnn.so.4.0.7
/usr/local/cuda-9.1/lib64/libcudnn.so
/usr/local/cuda-9.1/lib64/libcudnn.so.7
/usr/local/cuda-9.1/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.1/lib64/libcudnn.so.7.1.1
/usr/local/cuda-9.1/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda80                    1.0                           0    soumith
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] guided-filter-pytorch     1.1.1                     <pip>
[conda] magma-cuda91              2.3.0                         1    pytorch
[conda] pytorch-nightly           1.0.0.dev20181029 py3.6_cuda8.0.61_cudnn7.1.2_0  [cuda80]  pytorch
[conda] torch                     0.3.1                     <pip>
[conda] torch                     1.0.0a0+47c0d88           <pip>
[conda] torch                     0.4.0                     <pip>
[conda] torch-nightly             1.0.0.dev20181029           <pip>

```

**Comment by zou3519** [comment]
I have another independent report that this can be reproduced using the magma build that is installed alongside pytorch (magma-cudaXX) where XX is the cuda version. It could be a bug in the magma version we ship with

**Comment by vishwakftw** [comment]
Although there were no errors in my system, this is what happened with MAGMA installed from source (as is the case with my system):
```python
import torch
N = 256
x = torch.randn(N * N, 2, 2).cuda()
y = torch.inverse(x)
torch.matmul(y, x)  # this is not a batch of identity matrices, in fact y == x
```
I think we don't have to concern ourselves with the MAGMA install now; I'll recheck the code.

**Comment by vishwakftw** [comment]
I have confirmed that it is a MAGMA library issue. I did this by installing MAGMA from scratch and running the test pertaining to `getri` (`testing_(s)dgetri_batched.cpp`) with batch size 65536 and matrix dim 2. This is the result:
```
% MAGMA 2.3.0  compiled for CUDA capability >= 6.0, 32-bit magma_int_t, 64-bit pointer.
% CUDA runtime 8000, driver 9010. OpenMP threads 40. 
% device 0: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 1: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 2: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 3: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% Sat Nov  3 10:51:57 2018
% Usage: ./testing/testing_dgetri_batched [options] [-h|--help]

% batchCount   N    CPU Gflop/s (ms)    GPU Gflop/s (ms)   ||I - A*A^{-1}||_1 / (N*cond(A))
%===============================================================================
     65536     2     ---   (  ---  )      0.02 (  59.16)   9.01e+15   failed
```

Whereas, for a batch size of 65535 (256 * 256 - 1):
```
% MAGMA 2.3.0  compiled for CUDA capability >= 6.0, 32-bit magma_int_t, 64-bit pointer.
% CUDA runtime 8000, driver 9010. OpenMP threads 40. 
% device 0: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 1: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 2: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 3: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% Sat Nov  3 10:55:07 2018
% Usage: ./testing/testing_dgetri_batched [options] [-h|--help]

% batchCount   N    CPU Gflop/s (ms)    GPU Gflop/s (ms)   ||I - A*A^{-1}||_1 / (N*cond(A))
%===============================================================================
     65535     2     ---   (  ---  )      0.01 (  81.19)   1.14e-16   ok
```

Analogous results were found for single precision.
```
% MAGMA 2.3.0  compiled for CUDA capability >= 6.0, 32-bit magma_int_t, 64-bit pointer.
% CUDA runtime 8000, driver 9010. OpenMP threads 40. 
% device 0: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 1: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 2: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 3: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% Sat Nov  3 10:57:57 2018
% Usage: ./testing/testing_sgetri_batched [options] [-h|--help]

% batchCount   N    CPU Gflop/s (ms)    GPU Gflop/s (ms)   ||I - A*A^{-1}||_1 / (N*cond(A))
%===============================================================================
     65536     2     ---   (  ---  )      0.04 (  31.38)   1.68e+07   failed
```

```
% MAGMA 2.3.0  compiled for CUDA capability >= 6.0, 32-bit magma_int_t, 64-bit pointer.
% CUDA runtime 8000, driver 9010. OpenMP threads 40. 
% device 0: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 1: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 2: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 3: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% Sat Nov  3 10:57:49 2018
% Usage: ./testing/testing_sgetri_batched [options] [-h|--help]

% batchCount   N    CPU Gflop/s (ms)    GPU Gflop/s (ms)   ||I - A*A^{-1}||_1 / (N*cond(A))
%===============================================================================
     65535     2     ---   (  ---  )      0.02 (  44.71)   6.15e-08   ok
```

**Comment by vishwakftw** [comment]
I have opened an issue in MAGMA's BitBucket repository https://bitbucket.org/icl/magma/issues/10/getri_outofplace_batched-fails-when

**Comment by soumith** [comment]
@vishwakftw would Magma 2.4 fix it, instead of 2.3? I'm asking because Magma's batch inverse routines are much faster than CuBLAS's routines for large batch size / large matrix size (according to @martinarjovsky ), so I'd avoid moving to cublas for this.

**Comment by vishwakftw** [comment]
Let me try installing MAGMA 2.4 and see if the issue persists. I don't think this has been addressed based on the release notes for 2.4, so I'll check manually.

Thanks for the comment about cuBLAS.

**Comment by vishwakftw** [comment]
@soumith MAGMA v2.4.0 still has the bug, as suspected. Below are the results:

Double-precision:
```
% MAGMA 2.4.0  compiled for CUDA capability >= 6.0, 32-bit magma_int_t, 64-bit pointer.
% CUDA runtime 8000, driver 9010. OpenMP threads 40. 
% device 0: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 1: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 2: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 3: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% Sun Nov  4 14:03:28 2018
% Usage: ./testing/testing_dgetri_batched [options] [-h|--help]

% batchCount   N    CPU Gflop/s (ms)    GPU Gflop/s (ms)   ||I - A*A^{-1}||_1 / (N*cond(A))
%===============================================================================
     65536     2     ---   (  ---  )     14.69 (   0.08)   9.01e+15   failed
     65535     2     ---   (  ---  )      1.28 (   0.87)   1.45e-16   ok
```

Single-precision:
```
% MAGMA 2.4.0  compiled for CUDA capability >= 6.0, 32-bit magma_int_t, 64-bit pointer.
% CUDA runtime 8000, driver 9010. OpenMP threads 40. 
% device 0: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 1: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 2: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% device 3: GeForce GTX 1080 Ti, 1582.0 MHz clock, 11178.5 MiB memory, capability 6.1
% Sun Nov  4 14:03:58 2018
% Usage: ./testing/testing_sgetri_batched [options] [-h|--help]

% batchCount   N    CPU Gflop/s (ms)    GPU Gflop/s (ms)   ||I - A*A^{-1}||_1 / (N*cond(A))
%===============================================================================
     65536     2     ---   (  ---  )     14.65 (   0.08)   1.68e+07   failed
     65535     2     ---   (  ---  )      1.41 (   0.79)   7.21e-08   ok
```

**Comment by mscipio** [comment]
Any news on this? It seem that this problem is still present in pytorch 1.0.0 (I have just installed the new version using conda and cuda 10.0)

**Comment by vishwakftw** [comment]
Hi @mscipio, I have confirmed with MAGMA developers that this is an actual issue. A tentative workaround would be to use mini-batching.

**Comment by mscipio** [comment]
Too bad ... I am just wondering if, in the meantime, it would be possible to try to use _cublas.cublasSgetrfBatched_ + _cublas.cublasSgetriBatched_ from scikit-cuda library ... do you know of any way I can pass the right pointers from torch tensors to these functions?

**Comment by mscipio** [comment]
So far I solved this way:
`
def batchedInv(self, batchedTensor):
        if batchedTensor.shape[0] >= 256 * 256 - 1:
            temp = []
            for t in torch.split(batchedTensor, 256 * 256 - 1):
                temp.append(torch.inverse(t))
            return torch.cat(temp)
        else:
            return torch.inverse(batchedTensor)
`
If you have suggestion for smarter approaches, I am here to learn!

**Comment by vishwakftw** [comment]
Closed by 4c03ac7ac4d6fe9bc428f20834da053f9701c3c6
