### ISSUE TITLE
SparseSemiStructuredTensor fails on H100

### ISSUE THREAD

**Issue by tlrmchlsmth** [pytorch/pytorch#132928]
### 🐛 Describe the bug

The following code fails if I run it on an H100. It fails for both the CUTLASS and cuSPARSELt backends, but hits a different error in each case. It works if I run on an A100. It also works on an L40S.

It looks like this code is not enabled for SM90 systems but I don't see any reason for that.

```
import torch
from torch.sparse import to_sparse_semi_structured

def run_sparse_matmul(M, N, K, force_cutlass=False, dtype=torch.float16, device='cuda'):
    torch.sparse.SparseSemiStructuredTensor._FORCE_CUTLASS = force_cutlass

    # Create sparse semi-structured matrix
    x = torch.randn(M, N, dtype=dtype, device=device)
    dense_weights = torch.randn(K, N, dtype=dtype, device=device)
    sparse_weights = to_sparse_semi_structured(dense_weights)

    torch.nn.functional.linear(x, sparse_weights)

# Fails with:
# sparse_semi_structured_mad_op : Supported only on GPUs with compute capability 8.x
run_sparse_matmul(64, 64, 64, True)

# Fails with:
# CUDA error: architecture mismatch when calling `cusparseLtInit(&handle)`
run_sparse_matmul(64, 64, 64, False)
```

### Versions

PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.5.0-35-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.5.82
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3
GPU 2: NVIDIA H100 80GB HBM3
GPU 3: NVIDIA H100 80GB HBM3
GPU 4: NVIDIA H100 80GB HBM3
GPU 5: NVIDIA H100 80GB HBM3
GPU 6: NVIDIA H100 80GB HBM3
GPU 7: NVIDIA H100 80GB HBM3

Nvidia driver version: 555.42.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 57 bits virtual
Byte Order:                         Little Endian
CPU(s):                             128
On-line CPU(s) list:                0-127
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) Platinum 8462Y+
CPU family:                         6
Model:                              143
Thread(s) per core:                 2
Core(s) per socket:                 32
Socket(s):                          2
Stepping:                           8
CPU max MHz:                        4100.0000
CPU min MHz:                        800.0000
BogoMIPS:                           5600.00
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hfi vnmi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr ibt amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          3 MiB (64 instances)
L1i cache:                          2 MiB (64 instances)
L2 cache:                           128 MiB (64 instances)
L3 cache:                           120 MiB (2 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-31,64-95
NUMA node1 CPU(s):                  32-63,96-127
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI BHI_DIS_S
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] mypy==1.9.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] onnx==1.14.1
[pip3] onnxruntime==1.18.1
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] triton==3.0.0
[conda] Could not collect

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jcaip

**Comment by alexsamardzic** [comment]
Speaking for CUTLASS part, the only reason that the functionality is enabled for 8.x architectures only is simply that I had no opportunity to test/validate code on a Hopper GPU.  The CUTLASS-based sparse semi-structured implementation is based on some [upstream changes](https://github.com/NVIDIA/cutlass/pull/1189) that apply to Ampere architecture only, and I'm not sure what would be the status of this in CUTLASS for Hopper.

**Comment by quanta42** [comment]
Also having similar issue, on h100 with PyTorch version: 2.4.0+cu124:

`
print(torch.__config__.show())
PyTorch built with:
  - GCC 9.4
  - C++ Version: 201703
  - Intel(R) MKL-DNN v3.4.2 (Git Hash 1137e04ec0b5251ca2b4400a4fd3c667ce843d67)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.4
  - NVCC architecture flags: -gencode;arch=compute_90,code=sm_90
  - CuDNN 90.2.1  (built against CUDA 12.5)
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=12.4, CUDNN_VERSION=9.2.1, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=1 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=open, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.4.0, USE_CUDA=ON, USE_CUDNN=ON, **USE_CUSPARSELT=ON**, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=OFF, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,
`
however when trying to use _cslt_sparse_mm, I get:
`
result = torch._cslt_sparse_mm(sparse_matrix, dense_matrix)
**NotImplementedError: Could not run 'aten::_cslt_sparse_mm' with arguments from the 'SparseCUDA' backend**. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_cslt_sparse_mm' is only available for these backends: [CUDA, Meta, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastXPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CUDA: registered at /opt/pytorch/build/aten/src/ATen/RegisterCUDA.cpp:44681 [kernel]
Meta: registered at /dev/null:241 [kernel]
BackendSelect: fallthrough registered at /opt/pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /opt/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at /opt/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:497 [backend fallback]
Functionalize: registered at /opt/pytorch/aten/src/ATen/FunctionalizeFallbackKernel.cpp:349 [backend fallback]
Named: registered at /opt/pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at /opt/pytorch/aten/src/ATen/ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at /opt/pytorch/aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ZeroTensor: registered at /opt/pytorch/aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at /opt/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradCPU: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradCUDA: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradHIP: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradXLA: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradMPS: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradIPU: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradXPU: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradHPU: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradVE: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradLazy: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradMTIA: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradPrivateUse1: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradPrivateUse2: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradPrivateUse3: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradMeta: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
AutogradNestedTensor: registered at /opt/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:18032 [autograd kernel]
Tracer: registered at /opt/pytorch/torch/csrc/autograd/generated/TraceType_0.cpp:17004 [kernel]
AutocastCPU: fallthrough registered at /opt/pytorch/aten/src/ATen/autocast_mode.cpp:209 [backend fallback]
AutocastXPU: fallthrough registered at /opt/pytorch/aten/src/ATen/autocast_mode.cpp:351 [backend fallback]
AutocastCUDA: fallthrough registered at /opt/pytorch/aten/src/ATen/autocast_mode.cpp:165 [backend fallback]
FuncTorchBatched: registered at /opt/pytorch/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:731 [backend fallback]
BatchedNestedTensor: registered at /opt/pytorch/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:758 [backend fallback]
FuncTorchVmapMode: fallthrough registered at /opt/pytorch/aten/src/ATen/functorch/VmapModeRegistrations.cpp:27 [backend fallback]
Batched: registered at /opt/pytorch/aten/src/ATen/LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at /opt/pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at /opt/pytorch/aten/src/ATen/functorch/TensorWrapper.cpp:207 [backend fallback]
PythonTLSSnapshot: registered at /opt/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at /opt/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:493 [backend fallback]
PreDispatch: registered at /opt/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at /opt/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:157 [backend fallback]
`
using libcusparselt: 0.6.2.3-1

Do I need to use another version of libcusparselt?

**Comment by jcaip** [comment]
@quanta42 Can you share a bit of code to reproduce? 

Also just FYI , I'm working on upgrading cuSPARSELt to 0v.6.2 to add fp8 + hopper support, hoping to get this into the nightlies by the end of the week :)

**Comment by quanta42** [comment]
> @quanta42 Can you share a bit of code to reproduce?
> 
> Also just FYI , I'm working on upgrading cuSPARSELt to 0v.6.2 to add fp8 + hopper support, hoping to get this into the nightlies by the end of the week :)

I tried like this, using ops directly:

compressed_A = torch.randn((128, 128), device='cuda')
dense_B = torch.randn((128, 128), device='cuda')
result = torch.ops.aten._cslt_sparse_mm(compressed_A, dense_B)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/venv/lib/python3.10/site-packages/torch/_ops.py", line 1061, in __call__
    return self_._op(*args, **(kwargs or {}))
RuntimeError: CUDA error: operation not supported when calling `cusparseLtStructuredDescriptorInit( &handle, &sparse_input_descriptor, m, k, k, 16, input_type, CUSPARSE_ORDER_ROW, CUSPARSELT_SPARSITY_50_PERCENT)`

**Comment by jcaip** [comment]
Yeah the tests were failing with fp32 + cusparselt 0.6.2, but from what I saw the bfloat/float16 tests were passing. Can you use bfloat/float16 for your use case?  

FYI we have a `_cslt_compress`, which will compress  a dense matrix, I think there's a chance cuspareslt may be complaining about this. If you run with CUSPARSELT_LOG_LEVEL=5 you can see more info.

**Comment by quanta42** [comment]
> Yeah the tests were failing with fp32 + cusparselt 0.6.2, but from what I saw the bfloat/float16 tests were passing. Can you use bfloat/float16 for your use case?
> 
> FYI we have a `_cslt_compress`, which will compress a dense matrix, I think there's a chance cuspareslt may be complaining about this. If you run with CUSPARSELT_LOG_LEVEL=5 you can see more info.

Thank you, this works.

import torch

import os
os.environ["CUSPARSELT_LOG_LEVEL"] = "5"

compressed_A = torch.randn((128, 128), dtype=torch.bfloat16, device='cuda')
dense_B = torch.randn((128, 128), dtype=torch.bfloat16, device='cuda')

compressed_A = torch.ops.aten._cslt_compress(compressed_A)

result = torch.ops.aten._cslt_sparse_mm(compressed_A, dense_B)

print(result)

**Comment by quanta42** [comment]
@jcaip out of curiosity, do you know anyone that could help me on streamlining docker images with PyTorch? https://discuss.pytorch.org/t/customizing-pytorch-images-on-different-arch/208368

**Comment by jcaip** [comment]
https://github.com/pytorch/pytorch/pull/134022 should fix this issue, nightlies should have 0.6.2 from now on

**Comment by sixt99** [comment]
Hi, I am still getting:

RuntimeError: sparse_semi_structured_mad_op : Supported only on GPUs with compute capability 8.x

when running the code mentioned at the beginning of this post. Is there any alternative to run 2:4 sparsity (in LLMs, specifically)? Maybe torchAO?
