### ISSUE TITLE
torch.distributed.new_group got stuck

### ISSUE THREAD

**Issue by sandyhouse** [pytorch/pytorch#134314]
### 🐛 Describe the bug

```python
# test.py
import torch
import os
rank = int(os.getenv("LOCAL_RANK"))
torch.distributed.init_process_group('nccl', device_id=torch.device(rank))
g = torch.distributed.new_group(ranks=[0])
torch.distributed.barrier()
print("Done!")
```

When I ran the above program using two GPU cards, the program hung. 

The command I used was:
```shell
torchrun --nproc-per-node 2 test.py
```

I found that this issue occurred because the process with rank=1, not being a member of the new_group, directly called ncclCommSplit to create a child communicator for the new group. However, for the process with rank=0, the communicator for the new group is only created when the first communication operation is called, causing the process with rank=0 to keep waiting on the orignal communicator for other processes  to create the communicator for the new group. In other words, this violates the convention that all ranks must call ncclCommSplit on the original communicator. 

Additionally, I think the RFC at https://github.com/pytorch/pytorch/issues/130407 could fix this issue.

### Versions

Collecting environment information...
PyTorch version: 2.4.0a0+f70bd71a48.nv24.06
Is debug build: False
CUDA used to build PyTorch: 12.5
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.3
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-125.006-shopee-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.5.40
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3
GPU 2: NVIDIA H100 80GB HBM3
GPU 3: NVIDIA H100 80GB HBM3
GPU 4: NVIDIA H100 80GB HBM3
GPU 5: NVIDIA H100 80GB HBM3
GPU 6: NVIDIA H100 80GB HBM3
GPU 7: NVIDIA H100 80GB HBM3

Nvidia driver version: 550.90.07
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      52 bits physical, 57 bits virtual
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) Platinum 8468
CPU family:                         6
Model:                              143
Thread(s) per core:                 2
Core(s) per socket:                 48
Socket(s):                          2
Stepping:                           8
CPU max MHz:                        3800.0000
CPU min MHz:                        800.0000
BogoMIPS:                           4200.00
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr avx512_fp16 flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          4.5 MiB (96 instances)
L1i cache:                          3 MiB (96 instances)
L2 cache:                           192 MiB (96 instances)
L3 cache:                           210 MiB (2 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-47,96-143
NUMA node1 CPU(s):                  48-95,144-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] onnx==1.16.0
[pip3] optree==0.11.0
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-triton==3.0.0+989adb9a2
[pip3] torch==2.4.0a0+f70bd71a48.nv24.6
[pip3] torch-tensorrt==2.4.0a0
[pip3] torchvision==0.19.0a0
[conda] Could not collect

**Comment by tianyu-l** [comment]
@wconstab @shuqiangzhang @kwen2501 @H-Huang

**Comment by tianyu-l** [comment]
would https://github.com/pytorch/pytorch/pull/134617 solve this?

**Comment by wz337** [comment]
@sandyhouse Just curious why do you need a group on rank 0 only?
As for new group creation, `new_group` doesn't use ncclCommSplit. To use ncclCommSplit, you can use this new API, `split_group`, here: https://github.com/pytorch/pytorch/blob/main/torch/distributed/distributed_c10d.py#L4303

**Comment by sandyhouse** [comment]
When training LLM models, pipeline parallelism is typically used. In pipeline parallelism, when sharing embedding parameters, a communication group needs to be established for the first and the last rank, similar to our example. @wz337 

> Just curious why do you need a group on rank 0 only?

**Comment by wz337** [comment]
> When training LLM models, pipeline parallelism is typically used. In pipeline parallelism, when sharing embedding parameters, a communication group needs to be established for the first and the last rank, similar to our example. @wz337
> 
> > Just curious why do you need a group on rank 0 only?

Thanks for the context. I've tried your script on PyTorch version: 2.5.0a0+git3541e45. It is working for me. Do you want to try it at the latest nightly?

**Comment by sandyhouse** [comment]
OK. I will have a try. @wz337

**Comment by lrq619** [comment]
I've also encountered this problem, however, since I am running vllm and there are other modules depending on torch==0.2.3, I cannot easily upgrade to latest version, is there any work around for this problem?

**Comment by kwen2501** [comment]
The hang in the original program is probably at the `barrier()` call. 
This was the fix: https://github.com/pytorch/pytorch/pull/134617
-- pull around the same time this issue was filed, so probably would only be included in torch 2.5 releases.

> is there any work around for this problem
I don't really recommend this, but you can pass the exact device id of the instant process to the barrier() call. See doc about its signature [here](https://pytorch.org/docs/stable/distributed.html#torch.distributed.barrier).

**Comment by TXacs** [comment]
I got the same problem on arm cpu with mpi backend. My torch version is 2.2.1, how can I solve it?
And I didn't set device_id , also got stuck
