### ISSUE TITLE
   torch._C._cuda_init() RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by kekekeke8** [pytorch/pytorch#134542]
### 🐛 Describe the bug

always get error like below：

python3.9/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

when run  below code:
import torch
print("CUDA Available:", torch.cuda.is_available())
print("CUDA Device Count:", torch.cuda.device_count())
print("CUDA Device Name:", torch.cuda.get_device_name() if torch.cuda.is_available() else "No CUDA device detected")
print(torch.__version__)
print(torch.cuda.current_device())

results:

CUDA Available: True
CUDA Device Count: 1
CUDA Device Name: NVIDIA GeForce RTX 3090
1.11.0
0

### Versions

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] numpy==1.21.2
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl    conda-forge
[conda] cudatoolkit               11.3.1               h2bc3f7f_2    defaults
[conda] efficientnet-pytorch      0.7.1                    pypi_0    pypi
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-service               2.4.0            py39h7f8727e_0    defaults
[conda] mkl_fft                   1.3.1            py39hd3c417c_0    defaults
[conda] mkl_random                1.2.2            py39h51133e4_0    defaults
[conda] numpy                     1.21.2           py39h20f2e39_0    defaults
[conda] numpy-base                1.21.2           py39h79a1101_0    defaults
[conda] pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.11.0               py39_cu113    pytorch
[conda] torchvision               0.12.0               py39_cu113    pytorch

cc @ptrblck @msaroufim

**Comment by trandangtrungduc** [comment]
Try checking torch installation path using `torch.__path__` [like this](https://discuss.pytorch.org/t/torch-cuda-is-available-is-true-but-no-cuda-gpus-are-available/191580).
Or set the correct device, e.g: `torch.cuda.set_device(0)`

**Comment by kekekeke8** [comment]
torch.__path__ is below:
['/root/miniconda3/envs/distillation/lib/python3.9/site-packages/torch']

  add "torch.cuda.set_device(0)" in project, still same error. did not know why.

when run command  "nvidia-smi", the result is below:

Tue Aug 27 19:23:14 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 495.44       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:A1:00.0 Off |                  N/A |
| 30%   33C    P8    39W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by trandangtrungduc** [comment]
You can add `torch.cuda.current_device()` or `torch.cuda._lazy_init()` or `torch.cuda.init()` after `import torch` and before `torch._C._cuda_init()`

**Comment by kekekeke8** [comment]
after add "torch.cuda.init()" , it gives below error.  but all cuda memory 80G
 
 images = torch.stack(images, dim=0).to(args.device)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by kekekeke8** [comment]
even using 4 GPU,  320G total, still same error.  dataset just CIFAR10.

**Comment by trandangtrungduc** [comment]
I'm not sure about this, the problem might come from your model size being too big. Try reducing some things like batch size,... Also check GPU utilization to make sure there is no cached in GPU by killing the process.

**Comment by kekekeke8** [comment]
yes. tried the latest version, It works now. Thanks @hvaara @trandangtrungduc

**Comment by hvaara** [comment]
You're welcome! Feel free to ask on https://discuss.pytorch.org/ if you need support or help with issues that aren't bugs 🙂

@pytorchbot close
