### ISSUE TITLE
[MPS] Possible persistent infinite loop in `nn.ReplicationPad1d`

### ISSUE THREAD

**Issue by hvaara** [pytorch/pytorch#135442]
### 🐛 Describe the bug

⚠️ Please don't try to reproduce unless you're prepared to reboot your system.

Edge-case input leads to what seems to be a persistent infinite loop. This issue was discovered in #134184 and left as follow-up work. There is also a correctness bug in `nn.ReplicationPad1d` that will be reported in a separate issue.

`shape = [65536, 2, 4]` in the MRE below, results in 100% GPU utilization, which will persist even if the Python process is killed. Other shapes (eg. `shape = [65535, 2, 4]` or `shape = [65537, 2, 4]`) will not produce this behavior.

```python
import torch

device = 'mps'

shape = [65536, 2, 4]
pl, pr = 3, 4

x = torch.randn(shape, device=device, requires_grad=True)
model = torch.nn.ReplicationPad1d((pl, pr))

out = model(x)

g = torch.randn_like(out)
out.backward(g)

print(x.grad[:, :, 1 : -1])
```

### Versions

PyTorch version: 2.5.0a0+git042f2f7
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.6.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.30.1
Libc version: N/A

Python version: 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-14.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.15.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.12.1
[pip3] torch==2.5.0a0+git042f2f7
[pip3] torch-tb-profiler==0.4.3
[pip3] torchvision==0.20.0a0+0d80848
[pip3] triton==3.0.0
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] torch                     2.5.0a0+git042f2f7           dev_0    <develop>
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchfix                  0.4.0                    pypi_0    pypi
[conda] torchvision               0.20.0a0+0d80848           dev_0    <develop>
[conda] triton                    3.0.0                    pypi_0    pypi

**Comment by hvaara** [comment]
Does anyone know of a way to list and kill processes running on the GPU on Mac? (or whatever the technically correct way of saying that is)

**Comment by qqaatw** [comment]
> Does anyone know of a way to list and kill processes running on the GPU on Mac? (or whatever the technically correct way of saying that is)

Here is the conversation we had previously, which could be helpful:

<img width="683" alt="image" src="https://github.com/user-attachments/assets/5ef7fac0-1b81-4c1b-98c3-4ae2bd29ff12">

**Comment by malfet** [comment]
@hvaara I've removed edge cases, because I don't see anything out of the ordinary with input parameters. Something tells me this could be easily resolved by sharding, as MPS is known to use 16-bit indices in the past, see https://github.com/pytorch/pytorch/issues/116769#issuecomment-1888302095

**Comment by jhavukainen** [comment]
I can't seem to reproduce the issue locally. I've tested on MacOS14.6 (M1 Ultra) and MacOS15 M3 Pro so far but neither has gotten stuck. But the behavior of having resources left tied up sounds like a concerning issue here.

**Comment by hvaara** [comment]
I have an an M3 Max 128 GB Macbook Pro. Running `macOS 14.6.1`. I just reinstalled PyTorch from current main (042f2f7746a064f1527d95d1f1d712b4f0b34186) to verify it wasn't a one-off issue on my machine. I got the same error again.

I know someone with the same specs as me. I can ask to see if he can reproduce.

Please feel free to tell me what to do if there's anything that can help with debugging this.

**Comment by jhavukainen** [comment]
Ok that's great if you can get someone with the same hardware to try reproing it as well much appreciated! 

In the meanwhile I'm making a clean install of 14.6.1 in case the minor update has had something to do with this and see if I can source a M3 Max 128 GB MBP in case it turns out to be relevant here.

**Comment by hvaara** [comment]
He said he'd take a look later (thanks for answering the 🦇☎️ @bghira 🤣)

It's easy to see when you've hit the bug, because the last print statement (`print(x.grad[:, :, 1 : -1])`) never prints anything. Everything up to that point will execute fine. If it freezes up, pressing `^C` has no effect. `^Z` works fine. Killing the process works and the process dies just fine (no zombie process). If you pressed `^Z`, executing `fg` after killing the process will show that the process has been terminated.

**Comment by bghira** [comment]
```
[:)] % python repro.py 
^C^C^C^C^C
```

yep

beta 24A5331b, Darwin Kernel Version 24.0.0: Mon Aug 12 21:29:10 PDT 2024;

torch 2.4.1

**Comment by hvaara** [comment]
Thanks for the repro, @bghira!

@jhavukainen seems this is at least reproducible on M3 Max 128GB. And it's persistent across PyTorch and macOS versions (that's a Sequoia build).

**Comment by kit1980** [comment]
Is there a PR fixing this? Is milestone 2.5 still relevant?

**Comment by hvaara** [comment]
> Is there a PR fixing this? Is milestone 2.5 still relevant?

There is no PR for this yet, and the bug is still live. It's not entirely clear to me if this is verified as a PyTorch bug yet. It could possibly be in a dependency (MPS or elsewhere in macOS).

@jhavukainen were you able to repro? Any additional info on this you can share with us?

Regardless, I think targeting 2.5.0 for a fix is too optimistic.

**Comment by kit1980** [comment]
OK, I removed the milestone for now.

**Comment by hvaara** [comment]
I just verified this is still a live bug.

```
PyTorch version: 2.8.0a0+gitc52a002
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.5 (arm64)
GCC version: Could not collect
Clang version: 17.0.0 (clang-1700.0.13.3)
CMake version: version 3.31.1
Libc version: N/A

Python version: 3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:19:53) [Clang 18.1.8 ] (64-bit runtime)
Python platform: macOS-15.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] mypy==1.13.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.2
[pip3] onnx==1.17.0
[pip3] onnx2torch==1.5.15
[pip3] onnxruntime==1.21.1
[pip3] onnxscript==0.1.0.dev20240817
[pip3] optree==0.13.0
[pip3] torch==2.8.0a0+gitc52a002
[pip3] torchaudio==2.6.0a0+1a8f621
[pip3] torchvision==0.22.0a0+966da7e
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] onnx2torch                1.5.15                   pypi_0    pypi
[conda] optree                    0.13.0                   pypi_0    pypi
[conda] torch                     2.8.0a0+gitc52a002           dev_0    <develop>
[conda] torchaudio                2.6.0a0+1a8f621           dev_0    <develop>
[conda] torchvision               0.22.0a0+966da7e           dev_0    <develop>
```

**Comment by hvaara** [comment]
Adding another data point: Still a live bug.

<details><summary>Env info</summary>

```
PyTorch version: 2.12.0a0+gitb16bd15
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 26.3 (arm64)
GCC version: Could not collect
Clang version: 17.0.0 (clang-1700.6.3.2)
CMake version: version 4.1.2
Libc version: N/A

Python version: 3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:19:53) [Clang 18.1.8 ] (64-bit runtime)
Python platform: macOS-26.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
Is XPU available: False
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
Caching allocator config: N/A

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] flake8==7.2.0
[pip3] mypy==1.13.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] onnx==1.17.0
[pip3] onnx2torch==1.5.15
[pip3] onnxruntime==1.21.1
[pip3] onnxscript==0.1.0.dev20240817
[pip3] optree==0.13.0
[pip3] pytorch_sphinx_theme==0.0.24
[pip3] torch==2.12.0a0+gitb16bd15
[pip3] torchaudio==2.6.0a0+1a8f621
[pip3] torchbench==0.1
[pip3] torchvision==0.26.0a0+d63f7ed
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] onnx2torch                1.5.15                   pypi_0    pypi
[conda] optree                    0.13.0                   pypi_0    pypi
[conda] pytorch-sphinx-theme      0.0.24                   pypi_0    pypi
[conda] torch                     2.12.0a0+gitb16bd15          pypi_0    pypi
[conda] torchaudio                2.6.0a0+1a8f621           dev_0    <develop>
[conda] torchbench                0.1                       dev_0    <develop>
[conda] torchvision               0.26.0a0+d63f7ed           dev_0    <develop>
```

</details>

**Comment by Isalia20** [comment]
PR is merged, should be resolved on main or on next nightly build
