### ISSUE TITLE
torch.nn.InstanceNorm2d returns nan with negative eps values for tensor with float16 dtype on cpu

### ISSUE THREAD

**Issue by jiren-the-gray** [pytorch/pytorch#135542]
### 🐛 Describe the bug

When I run this code on a tensor of type float16 of shape (1, 3, 256, 256) on torch.nn.InstanceNorm2d, I get a tensor with nan values from cpu but gpu can produce non-nan tensor. I am providing the tensor in a pickle file which can be downloaded from here: [link](https://drive.google.com/file/d/1-Qm6x7APyxGWSu92svOY3l_mBirlgsdp/view?usp=drive_link)

Minimal repro:

```python
import torch
import pickle

with open('input_instancenorm2d.pickle', 'rb') as f:
  input_dict = pickle.load(f)

a = torch.tensor(input_dict['input'], dtype=torch.float16)
print(a.shape)
# torch.Size([1, 3, 256, 256])
print(a.dtype)
# torch.float16
num_features = 3
eps = -0.5
m = torch.nn.InstanceNorm2d(num_features=num_features, eps=eps)
output_cpu = m(a)
output_gpu = m.cuda()(a.cuda())
print(output_cpu[0][0][0][0])
# tensor(nan, dtype=torch.float16)
print(output_gpu[0][0][0][0])
# tensor(-1.0039, device='cuda:0', dtype=torch.float16)
```

It can also be reproduced on [colab](https://colab.research.google.com/drive/1X0AowednmpH79htWyiti3V8gG80pvpwq?usp=sharing). Just need to upload the pickle file to the files tab after connecting to a runtime.

Note: I found the tensor with fuzzing.

### Versions

Collecting environment information...
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 15.0.0 (git@github.com:llvm/llvm-project.git 4ba6a9c9f65bbc8bd06e3652cb20fd4dfc846137)
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-117-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 555.42.02
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Byte Order:                           Little Endian
Address sizes:                        39 bits physical, 48 bits virtual
CPU(s):                               24
On-line CPU(s) list:                  0-23
Thread(s) per core:                   1
Core(s) per socket:                   16
Socket(s):                            1
NUMA node(s):                         1
Vendor ID:                            GenuineIntel
CPU family:                           6
Model:                                183
Model name:                           13th Gen Intel(R) Core(TM) i7-13700KF
Stepping:                             1
CPU MHz:                              5333.317
CPU max MHz:                          5800.0000
CPU min MHz:                          800.0000
BogoMIPS:                             6835.20
Virtualization:                       VT-x
L1d cache:                            384 KiB
L1i cache:                            256 KiB
L2 cache:                             16 MiB
NUMA node0 CPU(s):                    0-23
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Mitigation; Clear Register File
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI BHI_DIS_S
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.11.0
[pip3] torch==2.4.0
[pip3] triton==3.0.0
[conda] numpy                     1.26.4          py310heeff2f4_0  
[conda] numpy-base                1.26.4          py310h8a23956_0  
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi

**Comment by CaoE** [comment]
@jiren-the-gray This should be caused by std::sqrt taking negative values. https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/Normalization.cpp#L108.
May I know In what cases is eps negative?

**Comment by jiren-the-gray** [comment]
@CaoE I found the negative eps value by fuzzing.

**Comment by jiren-the-gray** [comment]
@CaoE I was able to reproduce the same issue with `InstanceNorm3d` and a float16 dtype with a positive eps as well.

I am providing a safetensors file instead of pickle so that it can be safely reproduced here: [instancenorm3d.safetensors](https://drive.google.com/file/d/1w8cHlHnUuxQZd_4_rak18dLH6IQoCf6H/view?usp=sharing)

Updated the [colab](https://colab.research.google.com/drive/1X0AowednmpH79htWyiti3V8gG80pvpwq?usp=sharing) as well, need to add the safetensors file to the files tab to execute.

Minimal repro:

```python
import torch
import numpy as np
from safetensors import safe_open

with safe_open("instancenorm3d.safetensors", framework="pt", device='cpu') as f:
    input_tensor = f.get_tensor('input')

num_features = 16
eps = 0.2541456040680159

m = torch.nn.InstanceNorm3d(num_features=num_features, eps=eps)

out_cpu = m(input_tensor)
out_gpu = m.cuda()(input_tensor.cuda())

print(f"Nan elements in out_cpu: {torch.count_nonzero(torch.isnan(out_cpu)).item()}") # 5308416
print(f"Nan elements in out_gpu: {torch.count_nonzero(torch.isnan(out_gpu)).item()}") # 0

np.testing.assert_allclose(out_cpu.numpy(), out_gpu.cpu().numpy(), atol=100, equal_nan=True)

# AssertionError: 
# Not equal to tolerance rtol=1e-07, atol=100

# x and y nan location mismatch:
#  x: array([[[[nan, nan, nan, ..., nan, nan, nan],
#          [nan, nan, nan, ..., nan, nan, nan],
#          [nan, nan, nan, ..., nan, nan, nan],...
#  y: array([[[[ 9.9121e-02,  1.9688e+00,  2.3315e-01, ...,  8.0615e-01,
#            1.1758e+00,  1.6028e-01],
#          [-4.2139e-01,  1.1787e+00,  4.1565e-02, ...,  8.2568e-01,...
```

Please take a look at this.

**Comment by CaoE** [comment]
Hi @jiren-the-gray.  CUDA directly calculates `c10::cuda::compat::rsqrt(var + eps)`. If var + eps < 0 (try smaller eps, e.g., -5) you may also get nan on CUDA.
We can align CPU with CUDA, which should be able to fix the two issues.

**Comment by CaoE** [comment]
@jiren-the-gray Could you please try https://github.com/pytorch/pytorch/pull/136824 ?

**Comment by jiren-the-gray** [comment]
@CaoE Thank you! I tried your PR and it fixes the issue for both cases!

It also improves #136680, now the assertion passes until `atol = 1e-3`. It still fails if we use `atol = 1e-4` though, but that might be expected.

**Comment by jiren-the-gray** [comment]
@CaoE I was checking if this avoids regression, running this code generates 2 `nan` values on both CPU and GPU in torch 2.4.0.

```python
import torch
input_tensor = torch.tensor([[-1.8697,  0.9572],[ 0.4234,  0.7167]])
m = torch.nn.InstanceNorm1d(num_features=2, eps=-0.21608928864678084)
out_cpu = m(input_tensor)
out_gpu = m.cuda()(input_tensor.cuda())
assert torch.count_nonzero(torch.isnan(out_cpu)).item() == torch.count_nonzero(torch.isnan(out_gpu)).item()
```
But it does not produce any `nan` in the build of your PR in on CPU. I am having trouble building with CUDA on my machine, could you please check to see if the behavior is consistent with GPU after the new change?

**Comment by CaoE** [comment]
@jiren-the-gray After the new change, this code generates 0 nan values on CPU and 2 nan values on CUDA.
As mentioned above,  If var + eps < 0 you will also get nan on CUDA.

**Comment by CaoE** [comment]
@jiren-the-gray I removed the check of var + eps <= 0. The behavior on CPU should be same as CUDA.
