### ISSUE TITLE
BUG: `torch.cuda.is_available()` returns `False` in certain torch, CUDA and driver version

### ISSUE THREAD

**Issue by DicardoX** [pytorch/pytorch#135508]
### 🐛 Describe the bug

Hi, I'm trying to create a Docker container with the following (**minimal reproducible**) CUDA `12.4.1` Dockerfile (host info: Driver Version: `550.107.02`     CUDA Version: `12.4`):

```
FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

# Install common tool & conda
RUN apt-get update && apt-get install -y \
    software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt install -y python3.10 \
    && rm -rf /var/lib/apt/lists/*

RUN apt update && \
    apt install wget -y && \
    apt install git -y && \
    apt install curl -y && \
    apt install vim -y && \
    apt install bc && \
    apt-get install net-tools -y && \
    apt install ssh -y && \
    wget --quiet https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh && \
    mkdir -p /opt/conda/envs/finetune && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc


# Workspace
WORKDIR /app

# Install conda finetune env
# COPY requirements.txt requirements.txt
RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda create --name finetune python=3.10 -y && \
    conda activate finetune && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

# Cuda path
ENV CUDA_PATH=/usr/local/cuda
ENV LD_LIBRARY_PATH=$CUDA_PATH/lib64:$CUDA_PATH/compat:/usr/lib/x86_64-linux-gnu:$CUDA_PATH/targets/x86_64-linux/lib/stubs/:$LD_LIBRARY_PATH
ENV CUDNN_PATH=/usr/include
# Transformer engine path
ENV NVTE_FRAMEWORK=pytorch

# Copy workspace
COPY . .

# Enterpoint for bash shell
ENTRYPOINT ["/bin/bash"]
```

This just create a basic `nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04` image and install `conda` and `pip`. Then, I run the container with the following command:

```
docker run --runtime=nvidia -it --rm --gpus all --shm-size 64g --network=host --privileged --volume [USER_PATH]/.cache:/root/.cache --env NVIDIA_DISABLE_REQUIRE=1 username/imagename:tag
```

Then, inside the container, I install the latest stable torch (`2.4.1`) by:

```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
```

After that, I run the simplest torch cuda test by:

```
python -c "import torch; print(torch.cuda.is_available())"
```

What I got is:

```
/opt/conda/envs/finetune/lib/python3.10/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
False
```

This is quite strange, since if I simlply turn to use the base image `nvidia/cuda:12.5.1-cudnn-devel-ubuntu22.04`, I can got the correct result that `torch.cuda.is_available()` returns `True`.

Any advice will be sincerely appreciated, thx!

### Versions

Collecting environment information...
/opt/conda/envs/finetune/lib/python3.10/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 2.4.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 12.4.131
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: NVIDIA A40
GPU 1: NVIDIA A40

Nvidia driver version: 550.107.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          64
On-line CPU(s) list:             0-63
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7302 16-Core Processor
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     3000.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        5988.80
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es
Virtualization:                  AMD-V
L1d cache:                       1 MiB (32 instances)
L1i cache:                       1 MiB (32 instances)
L2 cache:                        16 MiB (32 instances)
L3 cache:                        256 MiB (16 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-15,32-47
NUMA node1 CPU(s):               16-31,48-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] torch==2.4.1+cu124
[pip3] torchaudio==2.4.1+cu124
[pip3] torchvision==0.19.1+cu124
[pip3] triton==3.0.0
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] torch                     2.4.1+cu124              pypi_0    pypi
[conda] torchaudio                2.4.1+cu124              pypi_0    pypi
[conda] torchvision               0.19.1+cu124             pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi

**Comment by Megan0704-1** [comment]
From your error message "Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)"

it looks like there's a mismatch between the CUDA version in your container and the NVIDIA driver version on your host machine.

To confirm, could you please check the NVIDIA driver version on your host by running:

```nvidia-smi```

**Comment by malfet** [comment]
Did you run `collect_env` inside or outside of your container? It feels like container setup is somehow wrong in one of the case. Can you compile and run simple hello.cu in that container
```cuda
#include <stdio.h>
__global__ void kernel() {
  printf("Hello World of CUDA %d\n", threadIdx.x);
}

int main() {
   kernel<<<1,1>>>();
  return cudaDeviceSynchronize();
}
```

**Comment by DicardoX** [comment]
> From your error message "Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)"
> 
> it looks like there's a mismatch between the CUDA version in your container and the NVIDIA driver version on your host machine.
> 
> To confirm, could you please check the NVIDIA driver version on your host by running:
> 
> `nvidia-smi`

The result of `nvidia-smi` on the host is as follows:

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.107.02             Driver Version: 550.107.02     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A40                     On  |   00000000:21:00.0 Off |                    0 |
|  0%   47C    P0             79W /  300W |     477MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A40                     On  |   00000000:81:00.0 Off |                    0 |
|  0%   33C    P8             21W /  300W |       4MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A   1154239      C   ./server                                      468MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by DicardoX** [comment]
> Did you run `collect_env` inside or outside of your container? It feels like container setup is somehow wrong in one of the case. Can you compile and run simple [hello.cu](https://gist.github.com/malfet/cae27d3eb5caf3627539471b8a766eec) in that container (or run `nvidia-smi` and share the output here)
> 
> ```cuda-c++
> #include <stdio.h>
> __global__ void kernel() {
>   printf("Hello World of CUDA %d\n", threadIdx.x);
> }
> 
> int main() {
>    kernel<<<1,1>>>();
>   return cudaDeviceSynchronize();
> }
> ```

The `collect_env.py` script is executed inside the container. I have compile and run the `hello.cu` and the result is as follows:

```
(finetune) root@a40-01:/app# nvcc hello.cu -o hello
(finetune) root@a40-01:/app# ./hello
Hello World of CUDA 0
```

**Comment by DicardoX** [comment]
Thank you guys, I have found the reason and solution:

The root reason is that the host driver version is:

> If hosts have new enough driver then there is no need to use compat lib.

By removing `/usr/local/cuda/compat` inside the envvar `LD_LIBRARY_PATH`, the mismatch error won't occur. Thanks again!

Ref: https://github.com/NVIDIA/nvidia-docker/issues/1256
