### ISSUE TITLE
On AMD GPUs (ROCm 5.7-6.2), cannot call `torch.unique()` on a floating-point tensor

### ISSUE THREAD

**Issue by amorehead** [pytorch/pytorch#136323]
### 🐛 Describe the bug

When `gt_features["asym_id"]` (which represents a `torch.float32` tensor of shape [B, N] which at some indices may contain `float("inf")`) is used in the function call
```python
_, asym_id_counts = torch.unique(
    gt_features["asym_id"], sorted=True, return_counts=True, dim=-1
)
```
the following memory aperture violation error is raised and crashes my training script without reporting any meaningful error logs to debug:
```bash
GPU core dump failed
:0:rocdevice.cpp            :2984: 755288871640 us: [pid:3284099 tid:0x1500bc5ff640] Callback: Queue 0x14ff2d600000 aborting with error : HSA_STATUS_ERROR_MEMORY_APERTURE_VIOLATION: The agent attempted to access memory beyond the largest legal address. code: 0x29
```
I've fixed this issue by instead casting `gt_features["asym_id"]` as a `torch.int` tensor instead and replacing `inf` with a large integer value (i.e., `int(1e6)`). However, on NVIDIA cards such as an A100, I did not encounter any such memory exceptions. In fact, my training script (i.e., the same script) runs just fine on NVIDIA GPUs. I've included this patch in [another GitHub repository](https://github.com/lucidrains/alphafold3-pytorch/pull/272) as a proof of concept that this (casting) solution is a temporary workaround.

### Versions

Collecting environment information...
PyTorch version: 2.3.0a0+git96dd291
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 6.2.41133-dd7f95766

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 18.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-6.2.0 24292 26466ce804ac523b398608f17388eb6d605a3f09)
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.14.21-150500.55.49_13.0.57-cray_shasta_c-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Instinct MI250X (gfx90a:sramecc+:xnack-)
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 6.2.41133
MIOpen runtime version: 3.2.0
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        48 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               128
On-line CPU(s) list:                  0-127
Vendor ID:                            AuthenticAMD
Model name:                           AMD EPYC 7A53 64-Core Processor
CPU family:                           25
Model:                                48
Thread(s) per core:                   2
Core(s) per socket:                   64
Socket(s):                            1
Stepping:                             1
Frequency boost:                      enabled
CPU max MHz:                          3541.0149
CPU min MHz:                          1500.0000
BogoMIPS:                             3992.57
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                       AMD-V
L1d cache:                            2 MiB (64 instances)
L1i cache:                            2 MiB (64 instances)
L2 cache:                             32 MiB (64 instances)
L3 cache:                             256 MiB (8 instances)
NUMA node(s):                         4
NUMA node0 CPU(s):                    0-15,64-79
NUMA node1 CPU(s):                    16-31,80-95
NUMA node2 CPU(s):                    32-47,96-111
NUMA node3 CPU(s):                    48-63,112-127
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Vulnerable: Safe RET, no microcode
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] adam-atan2-pytorch==0.0.12
[pip3] alphafold3-pytorch-lightning-hydra==0.5.25
[pip3] frame-averaging-pytorch==0.1.2
[pip3] lion-pytorch==0.2.2
[pip3] mypy==1.8.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] optree==0.9.1
[pip3] pytorch-lightning==2.4.0
[pip3] rotary-embedding-torch==0.8.3
[pip3] torch==2.3.0a0+git96dd291
[pip3] torch-geometric==2.6.0
[pip3] torchmetrics==1.4.2
[pip3] torchtyping==0.1.5
[pip3] torchvision==0.18.0a0+68ba7ec
[pip3] triton==2.3.0
[conda] Could not collect

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by amorehead** [comment]
Hi, @naromero77amd. Have you discovered anything more about what might be causing this issue?

**Comment by naromero77amd** [comment]
Hi @amorehead , I haven't had time to dig into this one. But it is in my queue.

**Comment by hongxiayang** [comment]
@amorehead Can you test this to see this is a problem? I used this and it works fine:
```
import torch

# Create a tensor with inf values
tensor_with_inf = torch.tensor([1.0, 2.0, float('inf'), 2.0, float('inf')]).to("cuda:0")

# Use torch.unique to find unique values
unique_values = torch.unique(tensor_with_inf)
print(unique_values)


# Create an empty 2x3 tensor
tensor_with_inf = torch.empty(2, 3).cuda(0)

# Assign inf to all elements
tensor_with_inf[:] = float('inf')
tensor_with_inf[0][0]=2.3

unique_values = torch.unique(tensor_with_inf)

print(unique_values)
```

**Comment by naromero77amd** [comment]
@amorehead Please let us know if you are able to test with the above reproducer. The current plan is to close this issue in a week due to inactivity.

**Comment by amorehead** [comment]
Hi, @hongxiayang and @naromero77amd. Apologies for my delayed response. @hongxiayang, I've run your proposed workaround above on my ROCm SLURM cluster, and I received the following output:
```python
tensor([1., 2., inf], device='cuda:0')
tensor([2.3000,    inf], device='cuda:0')
case 3
(tensor([[2.3000,    inf],
        [   inf,    inf]], device='cuda:0'), tensor([1, 2], device='cuda:0'))
```

As such, I believe this solves my issue. Thanks a ton!
