### ISSUE TITLE
[c10d] ProcessGroupNCCL support setting custom stream for communication

### ISSUE THREAD

**Issue by HOOLoLo** [pytorch/pytorch#138074]
### 🚀 The feature, motivation and pitch

Currently, ProcessGroupNCCL uses only one stream per device for communication, which is created at getNCCLComm function.
However, in some cases, I want to issue the communication kernel on different streams.   

The feature is motivated by the case of PipeFusion in xDiT project :  https://github.com/xdit-project/xDiT/blob/main/xfuser/model_executor/pipelines/pipeline_pixart_sigma.py#L464
( Currently the case of the project works well because the size of send data is smaller than 64MB. The send kernel of NCCL will ignore the recv kernel and complete when the data is smaller than 64MB)

Here is a small case of the logic ( I have made the send tensor large, so running this case by `torchrun --nproc_per_node 4 test.py`  will cause it to hang) :

```
import torch
import torch.distributed as dist
import os
 
if __name__ == '__main__':
    if torch.cuda.is_available() is False:
        raise EnvironmentError("not find GPU device for training")
 
    dist_url = 'env://'
    rank = int(os.environ["RANK"])
    world_size = int(os.environ["WORLD_SIZE"])
    local_rank = int(os.environ['LOCAL_RANK'])
    device = "cuda"
 
    print("rank: ", rank)
    print("world_size: ", world_size)
    print("local rank: ", local_rank)
 
    torch.cuda.set_device(local_rank)
 
    dist.init_process_group(
        backend='nccl',
        init_method='env://',
        world_size=world_size,
        rank=rank
    )
 
    dist.barrier()
 
    torch.manual_seed(0)
    batch = 100
    seq_len = 64
    head_num = 40
    head_size = 128
    dtype = torch.float16
    time_cnt = 2
    patch_cnt = world_size
 
    send_tensor = torch.rand([batch, seq_len, head_num, head_size], dtype=dtype, device = 'cuda')
 
    next_rank = (rank + 1) % world_size
    prev_rank = (rank + world_size - 1) % world_size
 
    for t in range(time_cnt):
        for p in range(patch_cnt):
            if not (rank == 0 and t == 0):
                print(f"rank:{rank} recv start, t:{t}, p:{p}")
                ops = []
                recv_prev_dim_tensor = torch.empty((1), device=device, dtype=torch.int64)
                recv_prev_dim_op = torch.distributed.P2POp(
                    torch.distributed.irecv,
                    recv_prev_dim_tensor,
                    prev_rank,
                    group=None,
                )
                ops.append(recv_prev_dim_op)
                reqs = dist.batch_isend_irecv(ops)
                for req in reqs:
                    req.wait()
                torch.cuda.synchronize()
 
                ops = []
                recv_prev_shape_tensor = torch.empty(torch.Size(recv_prev_dim_tensor), device=device, dtype=torch.int64)
                recv_prev_shape_op = torch.distributed.P2POp(
                    torch.distributed.irecv,
                    recv_prev_shape_tensor,
                    prev_rank,
                    group=None,
                )
                ops.append(recv_prev_shape_op)
 
                reqs = dist.batch_isend_irecv(ops)
                for req in reqs:
                    req.wait()
                torch.cuda.synchronize()
 
                recv_tensor = torch.zeros(torch.Size(recv_prev_shape_tensor), device=device, dtype=dtype)
                recv_req = torch.distributed.irecv(
                    recv_tensor,
                    src=prev_rank,
                    group=None,
                ).wait()
                print(f"rank:{rank} recv end, t:{t}, p:{p} end")
 
            if not (t == time_cnt - 1 and rank == world_size -1):
                print(f"rank:{rank} send start, t:{t}, p:{p}")
                ops = []
                send_next_dim_tensor = torch.tensor(send_tensor.dim(), device=device, dtype=torch.int64)
                send_next_dim_op = torch.distributed.P2POp(
                    torch.distributed.isend,
                    send_next_dim_tensor,
                    next_rank,
                    group=None,
                )
                ops.append(send_next_dim_op)
                reqs = dist.batch_isend_irecv(ops)
                for req in reqs:
                    req.wait()
                torch.cuda.synchronize()
 
                ops = []
                send_next_shape_tensor = torch.tensor(send_tensor.size(), device=device, dtype=torch.int64)
                send_next_shape_op = torch.distributed.P2POp(
                    torch.distributed.isend,
                    send_next_shape_tensor,
                    next_rank,
                    group=None,
                )
                ops.append(send_next_shape_op)
                reqs = dist.batch_isend_irecv(ops)
                for req in reqs:
                    req.wait()
                torch.cuda.synchronize()
 
                torch.distributed.isend(
                    send_tensor,
                    dst=next_rank,
                    group=None,
                )
                print(f"rank:{rank} send end, t:{t}, p:{p} end")
 
    print(f"rank:{rank} success")
 
    dist.destroy_process_group()
```

Below is a graph briefly discribing the logic:
![image](https://github.com/user-attachments/assets/e4958a8c-2e88-468d-9d62-978a2f30a6b4)

In the graph we can see that, in the Outer loop, each rank receives data, performs some computation, and than sends the result to the next peer. (except for the rank 0 in iter 0, which only sends data).
 
In the  inner loop, the `recv -> forward -> send` operations are divided into several patches(4 patches in the graph meaning 4 iterations of the inner loop). The first send of the last rank (rank 3) will wait for the receive kernel of rank 0, which is only  issued when rank 0 moves to the next iteration of the outer loop. However this creates a barrier for the second receive of rank3 , resulting in a chain that prevents rank 0 from completing the last send in inner loop. This, in turn, blocks rank 0 from advancing to the next iteration of the outer loop, eventually leading to a deadlock.

I think if i can issue the communication kernels to different streams, it may be much easier to handle this case(since the send and recv operations between each patches are independent). 

Or do you have any idea about how to implement this logic by current API?

@kwen2501  @wconstab 

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by fduwjj** [comment]
cc: @kwen2501 do you mind taking a look?

**Comment by fduwjj** [comment]
Maybe would creating two different PGs can help here? @HOOLoLo

**Comment by HOOLoLo** [comment]
@fduwjj Yes, thx a lot. I solved the problem by pairing up the ranks and creating group for each pair.
