### ISSUE TITLE
The right way to distribute the training over multiple GPUs and nodes.

### ISSUE THREAD

**Issue by curry111** [pytorch/pytorch#13826]
Hi guys :relaxed: I read a lot about how to distribute my training over multiple GPUs and nodes in pytorch Documentations. And I am confused, I had to read about multiprocessing in general(because i didn't have any knowledge about it :sweat_smile:) I don't know if my code is right or not but every time i run it i see error
`THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525812548180/work/aten/src/THC/THCTensorRandom.cu line=25 error=46 : all CUDA-capable devices are busy or unavailable
`
And
`RuntimeError: cuda runtime error (46) : all CUDA-capable devices are busy or unavailable at /opt/conda/conda-bld/pytorch_1525812548180/work/aten/src/THC/THCTensorRandom.cu:25
`
```
def run(rank, size):
    device = torch.device("cuda")
    dataset = datasets.MNIST('./data', train=True,
                             transform=transforms.Compose([
                                 transforms.ToTensor(),
                                 transforms.Normalize((0.1307,), (0.3081,))]))
    # from torch.utils.data.distributed import DistributedSampler
    train_sampler = DistributedSampler(dataset)
    train_loader = torch.utils.data.DataLoader(dataset, batch_size=128, 
                                                                       num_workers=4,
                                                                       pin_memory=True, 
                                                                       sampler=train_sampler)
    torch.manual_seed(1234)

    model = Net().cuda()
    model = torch.nn.parallel.DistributedDataParallel(model)
    optimizer = optim.SGD(model.parameters(),
                          lr=0.01, momentum=0.5)

    for epoch in range(10):
        epoch_loss = 0.0
        train_sampler.set_epoch(epoch)
        for data, target in train_loader:
            data, target = data.to(device), target.to(device)
            optimizer.zero_grad()
            output = model(data)
            loss = F.nll_loss(output, target)
            epoch_loss += loss.item()
            loss.backward()
            optimizer.step()
        print('Rank ', dist.get_rank(), ', epoch ',
              epoch, ': ', epoch_loss / num_batches)

```
### Initializing processes group 
```
def init_processes(rank, size, fn, backend='gloo'):
    """ Initialize the distributed environment. """
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '29500'
    dist.init_process_group(backend, rank=rank, world_size=size)
    fn(rank, size)
```
### Creating 4 processes (for 2 nodes and each node has 2 GPUs)
```
size = 4
processes = []
for rank in range(size):
    p = Process(target=init_processes, args=(rank, size, run))
    processes.append(p)
    p.start()
```
I also read [distributed imagenet example](https://github.com/pytorch/examples/blob/master/imagenet/main.py) to try to do the same.
Is that the correct way of using distributed training and DistributedDataParallel() :sweat_smile:?

PS: btw the first error appears 3 times the second error appears 4 times(I only took the last line of the second error). Both errors appear at the same time
I also tried to google that error but I could not use it to fix my error

**Comment by manjunaths** [comment]
How are you binding the processes to the individual GPUs ? I had a problem where all my processes where running on a single GPU instead of one on each GPU. I am using a different backend and my launch mechanism is also different. Can you try and assign a different GPU number (using os.environ['CUDA_VISIBLE_DEVICES'] before the process in the for loop) to different processes ?

**Comment by lliimsft** [comment]
Try something like: device = torch.device("cuda", args.local_rank)

**Comment by curry111** [comment]
@lliimsft @manjunaths  Thank you so much and sorry for the late reply. actually I gave up on trying to distributed my training but I gave it a shot yesterday. I changed a lot of things in my code and I added your advice and it worked. the problem now is that it prints the `loss.item()` for every GPU/node
for example: training on 2 GPUs
```
2 GPUs
GPU :  1
2 GPUs
GPU :  0
Loss in epoch 0  =  2.16241826098016
Loss in epoch 0  =  2.1587327145515602
Loss in epoch 1  =  1.2776704367170943
Loss in epoch 1  =  1.2715401794048067
Loss in epoch 2  =  0.8121602121819841
Loss in epoch 2  =  0.8152065771691342
Loss in epoch 3  =  0.663035316162921
Loss in epoch 3  =  0.6598308266477382
```
My training function looks like this
```
def train(model, device, train_loader, optimizer,criteration, epochs):
    model.train()
    print("2 GPUs")
    print("GPU : ",args.local_rank)
    model = torch.nn.parallel.DistributedDataParallel(model,
                                                  device_ids=[args.local_rank],
                                                  output_device=args.local_rank)
    for epoch in range(epochs):
        LOSS = 0
        for batch_idx, (data, target) in enumerate(train_loader):
            data, target = data.to(device), target.to(device)
            optimizer.zero_grad()
            output = model(data)
            loss = criteration(output, target)
            loss.backward()
            optimizer.step()
            LOSS += loss.item()
        print("Loss in epoch", epoch," = ", LOSS/len(train_loader))
```
Is there a way of printing the average loss over the GPUs/nodes for every epoch?

**Comment by manjunaths** [comment]
Hey @curry111 ,

For that can you try the code at [this repository](https://github.com/diux-dev/imagenet18) ? The file train_imagenet_nv.py contains the relevant code in the function `distributed_predict`.

Here is the part that I think is relevant

```
    metrics = torch.tensor([batch_size, valid_batches, loss, corr1, corr5]).float().cuda()
    batch_total, valid_batches, reduced_loss, corr1, corr5 = dist_utils.sum_tensor(metrics).cpu().numpy()
    reduced_loss = reduced_loss/valid_batches
```

The _reduced loss_ is what you are looking for. Does this help ?

**Comment by leo-mao** [comment]
@curry111 I think my code archive exactly what you want in same situation.
```
def summary_print(rank, loss, accuracy, average_epoch_time, tot_time):
    import logging
    size = float(dist.get_world_size())
    summaries = torch.tensor([loss, accuracy, average_epoch_time, tot_time], requires_grad=False, device='cuda')
    dist.reduce(summaries, 0, op=dist.ReduceOp.SUM)
    if rank == 0:
        summaries /= size
        logging.critical('\n[Summary]System : Average epoch time(ex. 1.): {:.2f}s, Average total time : {:.2f}s '
                         'Average loss: {:.4f}\n, Average accuracy: {:.2f}%'
                         .format(summaries[2], summaries[3], summaries[0], summaries[1] * 100))
```
just check out my [github repository](https://github.com/leo-mao/dist-mnist/blob/tensorflow-tutorial-amended/torch-dist/mnist-multiprocessing.py)
