### ISSUE TITLE
Backpropagation with ISTFT is broken in torch 2.5 using MPS

### ISSUE THREAD

**Issue by lminer** [pytorch/pytorch#138525]
### 🐛 Describe the bug

ISTFT does not appear to be working in version 2.5 of torch when run as part of a model using MPS. I've noticed that this warning doesn't appear anymore and am wondering if for some reason torch is trying to run unfold_backward on MPS.

Here's the warning:
```
UserWarning: The operator 'aten::unfold_backward' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications.
```

Here is the error
```
  return _VF.stft(  # type: ignore[attr-defined]
/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:891: failed assertion `[MPSNDArray, initWithBufferImpl:offset:descriptor:isForNDArrayAlias:isUserBuffer:] Error: buffer is not large enough. Must be 16547328 bytes
```

Here is code to reproduce:
```python
import torch


class STFTModel(torch.nn.Module):
    def __init__(
        self,
        n_fft: int = 1024,
        n_hop: int = 256,
        input_channels: int = 2,
    ):
        super().__init__()
        self.n_fft = n_fft
        self.n_hop = n_hop
        self.conv = torch.nn.Conv2d(
            in_channels=input_channels * 2,
            out_channels=input_channels * 2,
            kernel_size=(3, 3),
            padding=(1, 1),
            bias=False,
        )

    def forward(self, x):
        b, c, t = x.size()
        x = x.reshape(-1, t)
        stft_output = torch.stft(
            x,
            n_fft=self.n_fft,
            hop_length=self.n_hop,
            center=True,
            onesided=True,
            pad_mode="reflect",
            return_complex=True,
        )
        _, f, frames = stft_output.shape
        stft_output = stft_output.reshape(b, c, f, frames).permute(0, 1, 3, 2)
        out = torch.stack([torch.real(stft_output), torch.imag(stft_output)], dim=-1)
        out = torch.permute(out, (0, 1, 4, 2, 3))
        out = torch.reshape(out, (-1, c * 2, frames, f)).contiguous()
        out = self.conv(out)
        t2 = out.shape[2]
        out = torch.reshape(out, (b, c, 2, t2, f))
        out = torch.permute(out, (0, 1, 4, 3, 2))
        out = torch.view_as_complex(out.contiguous())
        out = out.reshape(-1, f, t2)
        out = torch.istft(
            out,
            n_fft=self.n_fft,
            hop_length=self.n_hop,
            center=True,
            onesided=True,
            length=t,
        )
        return out.reshape(b, c, t)


device = torch.device("mps")
model = STFTModel().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = torch.nn.MSELoss()
num_samples = 100
batch_size = 16
input_length = 16000

for _ in range(5):
    for _ in range(num_samples // batch_size):
        x = torch.randn(batch_size, 2, input_length).to(device)
        target = torch.randn(batch_size, 2, input_length).to(device)
        output = model(x)
        loss = criterion(output, target)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
```

### Versions

Collecting environment information...
PyTorch version: 2.5.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.0.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.3)
CMake version: version 3.30.5
Libc version: N/A

Python version: 3.11.10 | packaged by conda-forge | (main, Oct 16 2024, 01:26:25) [Clang 17.0.6 ] (64-bit runtime)
Python platform: macOS-15.0.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pytorch-lightning==2.4.0
[pip3] torch==2.5.0
[pip3] torchaudio==2.3.1
[pip3] torchmetrics==1.5.0
[pip3] torchvision==0.18.1
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] pytorch-lightning         2.4.0                    pypi_0    pypi
[conda] torch                     2.5.0                    pypi_0    pypi
[conda] torchaudio                2.3.1                    pypi_0    pypi
[conda] torchmetrics              1.5.0                    pypi_0    pypi
[conda] torchvision               0.18.1                   pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by malfet** [comment]
Can't repro it on the nightly, trying 2.5.0 now...

**Comment by malfet** [comment]
I can repro it, but it's fixed after https://github.com/pytorch/pytorch/pull/138314

So closing as duplicate of https://github.com/pytorch/pytorch/issues/137800
