### ISSUE TITLE
[ROCm] PyTorch TunableOps results in Memory Access Fault 

### ISSUE THREAD

**Issue by nikhil-tensorwave** [pytorch/pytorch#139116]
### 🐛 Describe the bug

We are seeing a Memory Access Fault by GPU Node error when running the below script `run.py` with PyTorch TunableOps enabled. All the testing was done on systems with 8xMI300X GPUs with ROCm 6.2.1 and the latest compatible GPU firmware. Running the script without TunableOps enabled works.

Error message:
```
Memory access fault by GPU node-2 (Agent handle: 0x562ee1524aa0) on address 0x7f2cf1201000. Reason: Unknown.
```
The specific GPU node number changes, and this was reproduced on multiple systems.

Steps to reproduce:
```
pip install -r requirements.txt
PYTORCH_TUNABLEOP_ENABLED=1  python3 run.py
```

`run.py`:
```
#!/usr/bin/env python
from __future__ import annotations

import argparse
import functools
import random
import statistics
import time

import torch

from torch.profiler import profile, record_function, ProfilerActivity

def main():

    parameters = {
        "batch_size": 7_200_000,
        "num_blocks": 1,
        "linear1_width": 16
    }

    test(parameters, "bfloat16", True)

def test(
    parameters,
    dtype: str,
    padded: bool,
    width: int = 12,
    n: int = 10,
) -> None:
    torch.manual_seed(17)

    dtype = getattr(torch, dtype)
    batch = parameters.pop("batch_size")
    model = BaseModel(in_width=width, out_width=1, **parameters).cuda()
    inputs = torch.empty((batch, width), device="cuda", dtype=dtype).normal_()

    autocast = functools.partial(
        torch.autocast,
        device_type="cuda",
        dtype=dtype,
        enabled=dtype in [torch.bfloat16, torch.float16],
    )
    with autocast():
        outputs = model(inputs)
    del outputs

    optimizer = torch.optim.Adam(
        params=model.parameters(),
        lr=0.001,
    )

    times = []
    for _ in range(n):
        batch_inputs = inputs if padded else inputs[: -random.randrange(1, 101)]

        start = time.time()
        optimizer.zero_grad(set_to_none=True)
        with autocast():
            with profile(activities=[
                    ProfilerActivity.CPU, ProfilerActivity.CUDA], record_shapes=True) as prof:
                with record_function("model_inference"):
                    fwd = model(inputs)
        print("Foward")
        with profile(activities=[
                ProfilerActivity.CPU, ProfilerActivity.CUDA], record_shapes=True) as prof:
            with record_function("model_output"):
                outputs = fwd.mean().backward()
        print("Backward")
        optimizer.step()
        torch.cuda.synchronize()
        duration = time.time() - start
        times.append(duration)

    return statistics.median(times)

class BaseModel(torch.nn.Module):
    def __init__(
        self,
        num_blocks: int,
        linear1_width: int,
        in_width: int,
        out_width: int,
        relu_leak: float = 0.1,
    ) -> None:
        super().__init__()
        self.num_blocks = num_blocks
        self.relu_leak = relu_leak
        self.block = Block(
                    in_width=in_width,
                    linear1_width=linear1_width,
                    relu_leak=self.relu_leak,
                )

        self.output = torch.nn.Linear(
            in_features=linear1_width,
            out_features=out_width,
        )

    def forward(self, inputs: torch.Tensor) -> torch.Tensor:
        return self.output(self.block(inputs))

class Block(torch.nn.Module):
    def __init__(
        self,
        in_width: int,
        linear1_width: int,
        relu_leak: float,
    ) -> None:
        super().__init__()
        self.relu_leak = relu_leak
        self.linear1 = torch.nn.Linear(
            in_features=in_width,
            out_features=linear1_width,
        )

    def forward(
        self, inputs: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        leaky_relu = functools.partial(
            torch.nn.functional.leaky_relu, negative_slope=self.relu_leak
        )
        l1 = leaky_relu(self.linear1(inputs))
        output = leaky_relu(l1)
        return output

if __name__ == "__main__":
    main()
```

`requirements.txt`:
```
filelock==3.13.1
fsspec==2024.2.0
Jinja2==3.1.3
MarkupSafe==2.1.5
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.3
pillow==10.2.0
pytorch-triton-rocm==3.0.0
sympy==1.12
torch==2.4.1+rocm6.1
torchaudio==2.4.1+rocm6.1
torchvision==0.19.1+rocm6.1
typing_extensions==4.9.0
```

### Versions

pytorch-triton-rocm==3.0.0
torch==2.4.1+rocm6.1
torchaudio==2.4.1+rocm6.1
torchvision==0.19.1+rocm6.1

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @hliuca

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

**Comment by nikhil-tensorwave** [comment]
We also saw this error on the following PyTorch versions:
```
torch==2.5.0+rocm6.2 (from stable PyTorch)
torch==2.6.0.dev20240921+rocm6.2 (from nightly PyTorch)
```

We also tried the following rocm/pytorch container:
`rocm/pytorch:rocm6.2.1_ubuntu22.04_py3.10_pytorch_release_2.3.0`
which had `torch==2.3.0a0+git1b935e2`.

In the rocm/pytorch container, we were able to run `run.py` with TunableOps enabled and without a Memory Access Fault.

**Comment by hliuca** [comment]
@nikhil-tensorwave https://github.com/pytorch/pytorch/pull/138791

This PR is supposed to fix TuanbleOp mem issue. It has not landed :-)

**Comment by jeffdaily** [comment]
We're finding that the size calculations for the buffer rotation feature of TunableOp are incorrect.  PR #138791 addresses an OOM issue.  We need a hotfix PR for this new issue.

**Comment by hliuca** [comment]
@jeffdaily confirm the OOM issue solved. but this one seems a different one,


PYTORCH_TUNABLEOP_ENABLED=1 PYTORCH_TUNABLEOP_VERBOSE=3 PYTORCH_TUNABLEOP_MAX_TUNING_ITERATIONS=5 python3 run.py

GemmTunableOp_BFloat16_NN(nn_16_7200000_1) -> Gemm_Rocblas_684,0.134859
missing params_signature, returning null ResultEntry for GemmTunableOp_BFloat16_NN,nn_16_1_7200000
finding fastest for GemmTunableOp_BFloat16_NN(nn_16_1_7200000) out of 2801 candidates
Rotating buffer 32 MiB. Needed Size: 219 MiB. Needed number of param copies: 1
GPU core dump failed
Memory access fault by GPU node-2 (Agent handle: 0x88b6bc0) on address 0x7f4f81801000. Reason: Unknown.
Aborted (core dumped)

**Comment by hliuca** [comment]
@nikhil-tensorwave @jeffdaily for this run.py, the matrix size is large, 16_7200000_1,

it requires workspace 219MB, and the default HIPBLASLT_WORKSPACE_SIZE is 32MB (32*1024).

a workaround is to increase workspace (kb),
"**HIPBLASLT_WORKSPACE_SIZE=262144**"

PYTORCH_TUNABLEOP_ENABLED=1 PYTORCH_TUNABLEOP_VERBOSE=3 HIPBLASLT_WORKSPACE_SIZE=262144 python3 run.py

@jeffdaily  should we increase default hipblaslt workspace size or add some explanations in README,
https://github.com/pytorch/pytorch/tree/main/aten/src/ATen/cuda/tunable

**Comment by jeffdaily** [comment]
@hliuca indeed this is a different issue.  #139137 will fix it.  Tested locally.  Waiting for CI and upstream reviewer.
