### ISSUE TITLE
RuntimeError: CuDNN error: CUDNN_STATUS_INTERNAL_ERROR when using 3D ver. of torchvision.models.resnet50

### ISSUE THREAD

**Issue by kenshohara** [pytorch/pytorch#14019]
## 🐛 Bug
I implemented 3D version of torchvision.models.resnet50 by just replacing Conv2d and BatchNorm2d with Conv3d and BatchNorm3d, respectively.
But I got RuntimeError: CuDNN error: CUDNN_STATUS_INTERNAL_ERROR,
when ```torch.backends.cudnn.benchmark = True```.
If ```torch.backends.cudnn.benchmark = False```,
it works correctly.

## To Reproduce

Executing this script.
https://gist.github.com/kenshohara/fb50d6dbc3603a93ff098f53f3c3165d

## Expected behavior

No error occurred.

## Environment

Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)
GPU 2: TITAN X (Pascal)
GPU 3: TITAN X (Pascal)

Nvidia driver version: 410.73
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch                   0.4.1           py37_cuda9.2.148_cudnn7.1.4_1  [cuda92]  pytorch
[conda] torchvision               0.2.1                    py37_1    pytorch

I also tried a different environment, but the same error occurred.

Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: 
GPU 0: TITAN V
GPU 1: TITAN V

Nvidia driver version: 410.72
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch                   0.4.1           py37_cuda9.2.148_cudnn7.1.4_1  [cuda92]  pytorch
[conda] torchvision               0.2.1                    py37_1    pytorch

## Additional context

In addition, when I execute the script in the following environment,
I got RuntimeError: cublas runtime error : resource allocation failed at /opt/conda/conda-bld/pytorch_1532582123400/work/aten/src/THC/THCGeneral.cpp:333,
even setting ```torch.backends.cudnn.benchmark = False```

Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: TITAN V
GPU 1: TITAN V

Nvidia driver version: 410.72
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch                   0.4.1           py37_cuda9.2.148_cudnn7.1.4_1  [cuda92]  pytorch
[conda] torchvision               0.2.1                    py37_1    pytorch

**Comment by kmyfoer** [comment]
I also encounter the same Error!

**Comment by soumith** [comment]
cc: @csarofeen , there's a repro script, would any of you help looking into this?

**Comment by jmandivarapu1** [comment]
I also encounter the same Error!

**Comment by csarofeen** [comment]
pytorch 0.4.1 installs with cuDNN 7.1.4 which I can reproduce this bug on. I've tried the next closest version I could reasonably find 7.2.1 in which this error no longer exists. I also cannot reproduce it any later than that.

I believe the only option you reasonably have is to compile PyTorch from source with a newer cuDNN than 7.1.4.

**Comment by kenshohara** [comment]
Thank you. I'll try to compile PyTorch with a newer cuDNN.

**Comment by soumith** [comment]
closing with solution "upgrade CuDNN, or upgrade PyTorch to use 1.0 Preview"

**Comment by kenshohara** [comment]
I confirmed that the script works well when using PyTorch 1.0 Preview with cuDNN 7.4!
Thank you!
