### ISSUE TITLE
Weird Memory Leak (OOM) after minor code change [CUDA]

### ISSUE THREAD

**Issue by enrico-stauss** [pytorch/pytorch#140792]
### 🐛 Describe the bug

I am sparsely working on an older project of mine and after a commit that I made a few days ago, I'm experiencing a nasty memory leak which very quickly leads to a CUDA OOM:
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.00 MiB. GPU 0 has a total capacity of 22.17 GiB of which 98.38 MiB is free. Process 21115 has 22.04 GiB memory in use. Of the allocated memory 16.27 GiB is allocated by PyTorch, and 2.52 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

I tried a bunch of stuff, like setting the suggested env var (with the single effect that the `reserved but unallocated memory` increased to ~4GiB at the point of the OOM error) or executing `torch.cuda.emtpty_cache()` (which showed in the memory usage graph, but still resulted in the OOM error after the same time).

I couldn't even believe that [this commit](https://github.com/enrico-stauss/point-frustums-public/commit/d97cacee8cb0d8519ca4c46b6f2fc06e3c75af43#diff-aa2d29ed63aaa622359736cb90e0f9dfce7f76674b6d320e99e8049410fb9315R343-R354) could be responsible for the OOM error, but after rolling it back, the error is gone.

Here is the relevant part of the diff:
```diff
-         x[..., 1] = (x[..., 1] - center_pol_azi[..., 0]) / self.discretization.delta_pol
-         x[..., 2] = (x[..., 2] - center_pol_azi[..., 1]) / self.discretization.delta_azi
+         x[..., 1] = (x[..., 1] - center_pol_azi[..., 0]) * x[..., 0]
+         x[..., 2] = (x[..., 2] - center_pol_azi[..., 1]) * x[..., 0]
          return x

def _decode_center(self, x: torch.Tensor, idx_feat: Optional[torch.Tensor] = None) -> torch.Tensor:
         center_pol_azi = center_pol_azi[idx_feat, :]
         x = x.clone()
-        x[..., 1] = (x[..., 1] * self.discretization.delta_pol) + center_pol_azi[..., 0]
-        x[..., 2] = (x[..., 2] * self.discretization.delta_azi) + center_pol_azi[..., 1]
+        x[..., 1] = (x[..., 1] / x[..., 0]) + center_pol_azi[..., 0]
+        x[..., 2] = (x[..., 2] / x[..., 0]) + center_pol_azi[..., 1]
```

For reference, here is the memory consumption graph of 3 distinct runs:
![image](https://github.com/user-attachments/assets/d78578d9-fbe5-4881-9bac-ae5fca205f6d)
where `divine-lion-70` marks the first occurence, `glad-firebrand-79` the last occurrence (with similar model config, interrupted by hand) and `vital-dew-80` the run after rolling said commit back.

You could in principle reproduce the issue but it would require downloading and unpacking the NuScenes dataset. Then you'd clone and install the repo and afterwards it would be as simple as executing:
```bash
point-frustums fit --config=configs/point_frustums.yaml
```

I'd hope though, that you can somehow just explain why these methods could possibly produce a memory leak:
```python
    def _encode_center(self, x: torch.Tensor, *, idx_feat: Optional[torch.Tensor] = None) -> torch.Tensor:
        """
        Encode the M spherical center coordinates w.r.t. the angular position of the feature vectors. Scale the angular
        delta furthermore with the distance.
        :param x:
        :param idx_feat:
        :return:
        """
        center_pol_azi = self.feature_vectors_angular_centers
        if idx_feat is not None:
            center_pol_azi = center_pol_azi[idx_feat, :]
        x = x.clone()
        x[..., 1] = (x[..., 1] - center_pol_azi[..., 0]) * x[..., 0]
        x[..., 2] = (x[..., 2] - center_pol_azi[..., 1]) * x[..., 0]
        return x

    def _decode_center(self, x: torch.Tensor, idx_feat: Optional[torch.Tensor] = None) -> torch.Tensor:
        """
        Decode the M spherical center coordinates w.r.t. the angular position of the feature vectors. Scale the angular
        delta furthermore with the distance.
        :param x:
        :param idx_feat:
        :return:
        """
        center_pol_azi = self.feature_vectors_angular_centers
        if idx_feat is not None:
            center_pol_azi = center_pol_azi[idx_feat, :]
        x = x.clone()
        x[..., 1] = (x[..., 1] / x[..., 0]) + center_pol_azi[..., 0]
        x[..., 2] = (x[..., 2] / x[..., 0]) + center_pol_azi[..., 1]
        return x
```

### Versions

```
Collecting environment information...
PyTorch version: 2.2.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1072-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA L4
Nvidia driver version: 535.216.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Byte Order:                           Little Endian
Address sizes:                        48 bits physical, 48 bits virtual
CPU(s):                               16
On-line CPU(s) list:                  0-15
Thread(s) per core:                   2
Core(s) per socket:                   8
Socket(s):                            1
NUMA node(s):                         1
Vendor ID:                            AuthenticAMD
CPU family:                           25
Model:                                1
Model name:                           AMD EPYC 7R13 Processor
Stepping:                             1
CPU MHz:                              2649.998
BogoMIPS:                             5299.99
Hypervisor vendor:                    KVM
Virtualization type:                  full
L1d cache:                            256 KiB
L1i cache:                            256 KiB
L2 cache:                             4 MiB
L3 cache:                             32 MiB
NUMA node0 CPU(s):                    0-15
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Mitigation; safe RET, no microcode
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save vaes vpclmulqdq rdpid

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] numpy-quaternion==2023.0.3
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==8.9.2.26
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-nccl-cu12==2.19.3
[pip3] nvidia-nvjitlink-cu12==12.5.40
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pytorch-lightning==2.2.0.post0
[pip3] torch==2.2.1+cu121
[pip3] torch-tb-profiler==0.4.3
[pip3] torchmetrics==1.3.1
[pip3] torchvision==0.17.1+cu121
[pip3] triton==2.2.0
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] numpy-quaternion          2023.0.3                 pypi_0    pypi
[conda] nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
[conda] nvidia-nccl-cu12          2.19.3                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.5.40                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
[conda] pytorch-lightning         2.2.0.post0              pypi_0    pypi
[conda] torch                     2.2.1+cu121              pypi_0    pypi
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchmetrics              1.3.1                    pypi_0    pypi
[conda] torchvision               0.17.1+cu121             pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi
```

cc @ptrblck @msaroufim

**Comment by enrico-stauss** [comment]
I was able to resolve the memory leak. 
The issue seems to have been cloning/reusing a tensor with a large computation graph attached.
It took me a bit to figure this out as I did the same before the change. Making the computation that goes in slightly more complicated resulted in this behavior. I still don't fully understand why that is the case.

However ... it is resolved so I'm happy 😄
