### ISSUE TITLE
FlexAttention: `CUDA error: an illegal memory access was encountered`

### ISSUE THREAD

**Issue by ViktorooReps** [pytorch/pytorch#141183]
### 🐛 Describe the bug

I am trying out FlexAttention (nightly build) for complex masking and I get `RuntimeError: CUDA error: an illegal memory access was encountered` for long enough inputs. I am pretty sure that the inputs are not long enough to cause OOM, even if the mask is materialized (which it should not, due to `_compile=True`). The code works as expected with simple sliding window and causal attention patterns.

The code in question:
```python
import pandas as pd
import torch

from torch.nn.attention.flex_attention import flex_attention, create_block_mask

from tqdm.auto import tqdm

from typing import Iterator

from torch.nn.functional import scaled_dot_product_attention

torch._dynamo.config.cache_size_limit = 1000



def create_mask_mod(context_size: int, stm_window_size: int, mem_freq: int):
    """
    Designed for the use on the input that consists of the concatenation of memory states and context states.
    Does not support padding!
    """
    n_mem = (context_size // mem_freq) + (context_size % mem_freq > 0)  # for block_size = 4: 0, 4, 8, 12, ...
    main_start = n_mem

    mem_end = main_start

    def causal_window_mask_with_mem(b, h, q_idx, kv_idx):
        # differentiator of main from mem parts
        is_mem_kv = (kv_idx < mem_end)
        is_mem_q = (q_idx < mem_end)

        # only valid for mem part
        mem_kv_idx = kv_idx * mem_freq
        mem_q_idx = q_idx * mem_freq

        # the first tokens are mem, so we realign with 0
        # only valid for main part
        main_kv_idx = kv_idx - main_start
        main_q_idx = q_idx - main_start

        main2main_causal = (main_kv_idx <= main_q_idx)
        main2main_windowed = (main_q_idx - main_kv_idx < stm_window_size)

        # without window when attending to mem
        main2mem_causal = (mem_kv_idx <= main_q_idx)
        mem2mem_causal = (mem_kv_idx <= mem_q_idx)

        mem2main_causal = (
                    main_kv_idx < mem_q_idx)  # not <=!! we restrict attending to immediate token: 0 does not attend to 0 etc.
        mem2main_windowed = (
                    mem_q_idx - main_kv_idx <= stm_window_size)  # not <!! extend window by 1 since we took 1 token off other side
        # return q_idx >= kv_idx  # if I uncomment this it works!
        return (
                (~is_mem_kv & ~is_mem_q & main2main_causal & main2main_windowed)
                | (is_mem_kv & ~is_mem_q & main2mem_causal)
                | (is_mem_kv & is_mem_q & mem2mem_causal)
                | (~is_mem_kv & is_mem_q & mem2main_causal & mem2main_windowed)
        )

    return causal_window_mask_with_mem


# benchmark forward
batch_size = 1

block_size = 128
window_size = block_size * 8
compile_warmup = 25
n_trials = 100

min_blocks = 1
max_blocks = 1000

# llama3 8b
kv_heads = 8
q_heads = 32
head_dim = 4096 // q_heads

data = []
context_sizes = [block_size * i for i in range(min_blocks, max_blocks, 50)]

mem_freqs = [2, 8, 32, 128]


def benchmark(
        attn_impl, input_len: int, res_base: dict, do_compile: bool = True, dtype=torch.float16,
        **extra_kwargs
) -> Iterator[dict]:
    torch.compiler.reset()
    torch.cuda.empty_cache()
    attn_impl = torch.compile(attn_impl) if do_compile else attn_impl

    # compilation warmup
    if do_compile:
        for _ in range(compile_warmup):
            torch.cuda.empty_cache()

            input_k = torch.randn(size=(batch_size, kv_heads, input_len, head_dim), dtype=dtype, device='cuda')
            input_v = torch.randn(size=(batch_size, kv_heads, input_len, head_dim), dtype=dtype, device='cuda')
            input_q = torch.randn(size=(batch_size, q_heads, input_len, head_dim), dtype=dtype, device='cuda')

            with torch.no_grad():
                assert attn_impl(input_q, input_k, input_v, **extra_kwargs).sum() is not None
        torch.cuda.synchronize(device=None)

    for _ in range(n_trials):
        torch.cuda.empty_cache()

        input_k = torch.randn(size=(batch_size, kv_heads, input_len, head_dim), dtype=dtype, device='cuda')
        input_v = torch.randn(size=(batch_size, kv_heads, input_len, head_dim), dtype=dtype, device='cuda')
        input_q = torch.randn(size=(batch_size, q_heads, input_len, head_dim), dtype=dtype, device='cuda')

        torch.cuda.reset_peak_memory_stats()
        torch.cuda.synchronize(device=None)

        with torch.autograd.profiler.profile(use_device='cuda') as prof:
            with torch.no_grad():
                assert attn_impl(input_q, input_k, input_v, **extra_kwargs).sum() is not None
                torch.cuda.synchronize(device=None)

        peak_mem = torch.cuda.max_memory_allocated()

        time_ns = prof.profiling_end_time_ns - prof.profiling_start_time_ns

        # Record results
        yield {
            **res_base,
            'time_taken_ms': time_ns / 1e6,
            'memory_used_mb': peak_mem / 1024 / 1024
        }


# causal window attention with memory

for context_size in tqdm(context_sizes):
    try:
        for mem_freq in tqdm(mem_freqs, leave=False):
            mem_size = (context_size // mem_freq) + (context_size % mem_freq > 0)
            mask = create_block_mask(
                create_mask_mod(context_size, window_size, mem_freq),
                None, None, context_size + mem_size, context_size + mem_size, device='cuda', BLOCK_SIZE=block_size,
                _compile=True
            )

            for res in benchmark(
                    flex_attention, context_size,
                    {'impl': f'flex_window_mem_compr{mem_freq}', 'context_length': context_size},
                    enable_gqa=True, block_mask=mask
            ):
                data.append(res)
    except Exception as e:
        print('Exc!')
        print(str(e), e.__class__.__name__)


df = pd.DataFrame(data)
df.to_csv('perf.csv')
```

## A bit on the mask:

The desired attention pattern looks like this (for `block_size=8`, `mem_freq=4` and `context_size=130`):
![pattern](https://github.com/user-attachments/assets/9d6691e5-9dfd-4afe-b25e-3c323bc55370)

The first `(context_size // mem_freq) + (context_size % mem_freq > 0)` tokens are `mem`, the others are `main` tokens. Every token (`mem` and `main`) should be able to attend to any `mem` token (respecting causal relationship) and to other tokens within the sliding window. The real position of `mem` tokens is every `mem_freq` (0, 4, 8, .... for `mem_freq=4`), but they are moved to the front to increase sparsity.

### Versions

```
PyTorch version: 2.6.0.dev20241120+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (conda-forge gcc 12.1.0-17) 12.1.0
Clang version: Could not collect
CMake version: version 3.30.3
Libc version: glibc-2.35

Python version: 3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.5.0-45-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA H100 80GB HBM3
Nvidia driver version: 550.90.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.8.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      52 bits physical, 57 bits virtual
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          AuthenticAMD
Model name:                         AMD EPYC 9454 48-Core Processor
CPU family:                         25
Model:                              17
Thread(s) per core:                 2
Core(s) per socket:                 48
Socket(s):                          2
Stepping:                           1
Frequency boost:                    enabled
CPU max MHz:                        3810.7910
CPU min MHz:                        1500.0000
BogoMIPS:                           5492.24
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp ibrs_enhanced vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl vnmi avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid overflow_recov succor smca fsrm flush_l1d
Virtualization:                     AMD-V
L1d cache:                          3 MiB (96 instances)
L1i cache:                          3 MiB (96 instances)
L2 cache:                           96 MiB (96 instances)
L3 cache:                           512 MiB (16 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-47,96-143
NUMA node1 CPU(s):                  48-95,144-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Mitigation; Safe RET
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced / Automatic IBRS; IBPB conditional; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-cusparselt-cu12==0.6.2
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pytorch-triton==3.1.0+cf34004b8a
[pip3] torch==2.6.0.dev20241120+cu124
[pip3] torchaudio==2.5.0.dev20241120+cu124
[pip3] torchvision==0.20.0.dev20241120+cu124
[pip3] triton==3.1.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-cusparselt-cu12    0.6.2                    pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] pytorch-triton            3.1.0+cf34004b8a          pypi_0    pypi
[conda] torch                     2.6.0.dev20241120+cu124          pypi_0    pypi
[conda] torchaudio                2.5.0.dev20241120+cu124          pypi_0    pypi
[conda] torchvision               0.20.0.dev20241120+cu124          pypi_0    pypi
[conda] triton                    3.1.0                    pypi_0    pypi
```

cc @chauhang @penguinwu @zou3519 @ydwu4 @bdhirsh @yf225 @Chillee @drisspg @yanboliang @BoyuanFeng

**Comment by ViktorooReps** [comment]
@drisspg could you have a look?

**Comment by ViktorooReps** [comment]
Here are 2 concrete examples of context sizes:

```python
context_sizes = [128 * 10, 128 * 100]
mem_freqs = [32]
```

The first one works, the other does not

**Comment by ViktorooReps** [comment]
Not sure if it helps, but here is the output if I supress errors with:

```python
import torch._dynamo
torch._dynamo.config.suppress_errors = True
```

```
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] WON'T CONVERT create_block_mask /mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/nn/attention/flex_attention.py line 810 
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] due to: 
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] Traceback (most recent call last):
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1188, in __call__
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     result = self._inner_convert(
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]              ^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 549, in __call__
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return _compile(
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1035, in _compile
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     raise InternalTorchDynamoError(
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 985, in _compile
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     guarded_code = compile_inner(code, one_graph, hooks, transform)
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 712, in compile_inner
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return _compile_inner(code, one_graph, hooks, transform)
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return function(*args, **kwargs)
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 747, in _compile_inner
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     out_code = transform_code_object(code, transform)
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1348, in transform_code_object
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     transformations(instructions, code_options)
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 222, in _fn
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     cuda_rng_state = torch.cuda.get_rng_state()
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/cuda/random.py", line 42, in get_rng_state
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return default_generator.get_state()
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] torch._dynamo.exc.InternalTorchDynamoError: RuntimeError: CUDA error: an illegal memory access was encountered
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] 
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] 
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] Traceback (most recent call last):
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1188, in __call__
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     result = self._inner_convert(
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]              ^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 549, in __call__
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return _compile(
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1035, in _compile
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     raise InternalTorchDynamoError(
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 985, in _compile
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     guarded_code = compile_inner(code, one_graph, hooks, transform)
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 712, in compile_inner
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return _compile_inner(code, one_graph, hooks, transform)
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return function(*args, **kwargs)
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 747, in _compile_inner
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     out_code = transform_code_object(code, transform)
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1348, in transform_code_object
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     transformations(instructions, code_options)
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 222, in _fn
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     cuda_rng_state = torch.cuda.get_rng_state()
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/cuda/random.py", line 42, in get_rng_state
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return default_generator.get_state()
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] torch._dynamo.exc.InternalTorchDynamoError: RuntimeError: CUDA error: an illegal memory access was encountered
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] 
W1121 00:02:32.621000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] 
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] WON'T CONVERT create_mask /mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/nn/attention/flex_attention.py line 763 
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] due to: 
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] Traceback (most recent call last):
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1188, in __call__
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     result = self._inner_convert(
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]              ^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 549, in __call__
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return _compile(
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1035, in _compile
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     raise InternalTorchDynamoError(
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 985, in _compile
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     guarded_code = compile_inner(code, one_graph, hooks, transform)
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 712, in compile_inner
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return _compile_inner(code, one_graph, hooks, transform)
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return function(*args, **kwargs)
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 747, in _compile_inner
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     out_code = transform_code_object(code, transform)
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1348, in transform_code_object
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     transformations(instructions, code_options)
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 222, in _fn
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     cuda_rng_state = torch.cuda.get_rng_state()
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/cuda/random.py", line 42, in get_rng_state
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return default_generator.get_state()
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] torch._dynamo.exc.InternalTorchDynamoError: RuntimeError: CUDA error: an illegal memory access was encountered
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] 
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] 
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] Traceback (most recent call last):
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1188, in __call__
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     result = self._inner_convert(
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]              ^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 549, in __call__
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return _compile(
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1035, in _compile
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     raise InternalTorchDynamoError(
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 985, in _compile
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     guarded_code = compile_inner(code, one_graph, hooks, transform)
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 712, in compile_inner
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return _compile_inner(code, one_graph, hooks, transform)
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return function(*args, **kwargs)
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 747, in _compile_inner
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     out_code = transform_code_object(code, transform)
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1348, in transform_code_object
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     transformations(instructions, code_options)
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 222, in _fn
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     cuda_rng_state = torch.cuda.get_rng_state()
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]   File "/mloscratch/homes/shcherba/conda/envs/char-llm/lib/python3.11/site-packages/torch/cuda/random.py", line 42, in get_rng_state
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]     return default_generator.get_state()
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] torch._dynamo.exc.InternalTorchDynamoError: RuntimeError: CUDA error: an illegal memory access was encountered
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257] 
W1121 00:02:32.628000 123244 site-packages/torch/_dynamo/convert_frame.py:1257]
```

**Comment by ViktorooReps** [comment]
This works:
```python
mem2main_dist = mem_q_idx - mem_kv_idx # mem_q_idx - main_kv_idx
mem2main_windowed = (mem2main_dist <= stm_window_size)  # (2)
```

This does not:
```python
mem2main_dist = mem_q_idx - main_kv_idx
mem2main_windowed = (mem2main_dist <= stm_window_size)  # (2)
```

I feel like I am going crazy

**Comment by ViktorooReps** [comment]
This works:

```python
mem2main_causal_lagged = (main_kv_idx + 24 * stm_window_size < mem_q_idx)

case_main2main = (~is_mem_kv & ~is_mem_q & main2main_causal & main2main_windowed)
case_main2mem = (is_mem_kv & ~is_mem_q & main2mem_causal)
case_mem2mem = (is_mem_kv & is_mem_q & mem2mem_causal)
case_mem2main = (~is_mem_kv & is_mem_q & mem2main_causal & ~mem2main_causal_lagged)
return case_main2main | case_main2mem | case_mem2mem | case_mem2main  # (3)
```

This does not (and with anything less than 23 does not work either):

```python
mem2main_causal_lagged = (main_kv_idx + 23 * stm_window_size < mem_q_idx)

case_main2main = (~is_mem_kv & ~is_mem_q & main2main_causal & main2main_windowed)
case_main2mem = (is_mem_kv & ~is_mem_q & main2mem_causal)
case_mem2mem = (is_mem_kv & is_mem_q & mem2mem_causal)
case_mem2main = (~is_mem_kv & is_mem_q & mem2main_causal & ~mem2main_causal_lagged)
return case_main2main | case_main2mem | case_mem2mem | case_mem2main  # (3)
```

The range of `main_kv_idx` and `mem_q_idx` is [0, 200 * 128), `stm_window_size = 1024`. I am guessing the cases where I don't get the error are the cases when the compiler removes the statement completely.

I suspect the issue is the multiplication operation to compute `mem_q_idx`. Not sure why this operation works fine then:
```
main2mem_causal = (mem_kv_idx <= main_q_idx)
```

**Comment by ViktorooReps** [comment]
Here is what `cuda-gdb` gives me:
```
CUDA Exception: Warp Illegal Address                                                                                           | 0/1 [00:00<?, ?it/s]

Thread 1 "python" received signal CUDA_EXCEPTION_14, Warp Illegal Address.
[Switching focus to CUDA kernel 0, grid 783, block (6,28,0), thread (64,0,0), device 0, sm 26, warp 3, lane 0]
0x000073137780fe50 in triton_tem_fused_0<<<(200,32,1),(256,1,1)>>> () at /tmp/torchinductor_shcherba/4w/c4wxcx6grm5mdf7cs7cte5z5yvvg6bvgjklli7xfjxr6kwefpzbt.py:480
480             v = tl.load(V_block_ptr)
```

Here is the file: https://gist.github.com/ViktorooReps/21eb6608a457dec741db58c6bd7a1617

**Comment by drisspg** [comment]
hmmm this might be a triton bug, whats the most minimal example you have? I want to extract some stuff for the triton team

**Comment by ViktorooReps** [comment]
OMG I am running `flex_attention` on lengths of `context_length` and create my mask for lengths of `context_length + mem_size`. Sorry for wastiing your time..  🤦‍♂️

Maybe it would be a good idea to add an if statement in `flex_attention` to check that the input shape is supported by the passed mask? @drisspg 

I am closing the issue, everything works now

**Comment by drisspg** [comment]
We should have guards when the lengths you pass in are longer than the block mass bounds. However, there are valid use cases where you create block masks with larger sizes and you pass in smaller QKV context links and the block mask remains valid.

I do imagine this is annoying to debug though when you're not in that case. :/

**Comment by ViktorooReps** [comment]
Hmm, here the mask was larger than the inputs. I don't see why would it throw errors then if smaller inputs should be ok, considering that the mask itself is not that complicated

**Comment by drisspg** [comment]
Maybe I worded it incorrectly, taking just one of the block_mask attributes `kv_indices`
 
 The shape is B,H, ceil(Q_LEN,BLOCK_SIZE), ceil(KV_LEN,BLOCK_SIZE), assuming you created it with `create_block_mask`
 
 When iterating along the k dim we only iterate across kv_blocks until we reach the end of the inputs not the KV_LEN that was given at when creating the block_mask. 
 
 ```Shell
 >>> create_block_mask(causal_mask,None,None,1,512)
BlockMask(
    kv_num_blocks=torch.Size([1, 1, 1]),
    kv_indices=torch.Size([1, 1, 1, 4]),
    full_kv_num_blocks=torch.Size([1, 1, 1]),
    full_kv_indices=torch.Size([1, 1, 1, 4]),
    q_num_blocks=torch.Size([1, 1, 4]),
    q_indices=torch.Size([1, 1, 4, 1]),
    full_q_num_blocks=torch.Size([1, 1, 4]),
    full_q_indices=torch.Size([1, 1, 4, 1]),
    BLOCK_SIZE=(128, 128),
    shape=(1, 1, 128, 512),
    sparsity=75.00%,
    mask_mod=causal_mask
)
>>> create_block_mask(causal_mask,None,None,1,512).kv_indices
tensor([[[[0, 1, 2, 3]]]], device='cuda:0', dtype=torch.int32)
>>> create_block_mask(causal_mask,None,None,1,512).kv_num_blocks
tensor([[[1]]], device='cuda:0', dtype=torch.int32)
```

This is essentially saying that if your Q length is size 1 and your are doing causal masking the only possible attention scores that contribute to the final output are in the first [Q_BLOCK, KV_BLOCK]. This mask is correct for all values of query, key, value where query.size(-2) == 1 and key.size(-2) <= 512

Hence why we dont error when query.size(-2) and key.size(-2) dont match what was given to `creaet_block_mask`
