### ISSUE TITLE
RNN have CuDNN error: CUDNN_STATUS_SUCCESS with Tesla T4

### ISSUE THREAD

**Issue by fuzihaofzh** [pytorch/pytorch#14260]
## 🐛 Bug

rnn cannot work on Tesla T4.

## To Reproduce
System: Ubuntu 18.04.1 LTS
CUDA Version: 10.0.130
GPU: Tesla T4

run the code:
```
import torch
import torch.nn as nn
a = torch.randn(5, 3, 10) # This can be sent into GPU correctly!
rnn = nn.RNN(10, 20, 2)
rnn.cuda()
```
The error is:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-951688d61d0c> in <module>
----> 1 rnn.cuda()

~/ProgramFiles/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in cuda(s
elf, device)
    256             Module: self
    257         """
--> 258         return self._apply(lambda t: t.cuda(device))
    259
    260     def cpu(self):

~/ProgramFiles/miniconda3/lib/python3.7/site-packages/torch/nn/modules/rnn.py in _apply(se
lf, fn)
    110     def _apply(self, fn):
    111         ret = super(RNNBase, self)._apply(fn)
--> 112         self.flatten_parameters()
    113         return ret
    114
~/ProgramFiles/miniconda3/lib/python3.7/site-packages/torch/nn/modules/rnn.py in flatten_p
arameters(self)
    103                     weight_arr, weight_stride0,
    104                     self.input_size, rnn.get_cudnn_mode(self.mode), self.hidden_si
ze, self.num_layers,
--> 105                     self.batch_first, bool(self.bidirectional))
    106
    107             self._param_buf_size = weight_buf.size(0)

RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS
```

## Expected behavior

Expect rnn is sent to GPU

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 0.4.1.post2
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version:  3.7
 - CUDA/cuDNN version: 10.0.130
 - GPU models and configuration:
GPU 0: Tesla T4
 - Any other relevant information:

**Comment by soumith** [comment]
this is so strange. Something to keep in mind, we didn't actually ship 0.4.1.post2 for CUDA10.
Can you try 1.0.0 CUDA10 version from https://pytorch.org

**Comment by rajatvd** [comment]
I experienced the same issue when moving an RNN to an Nvidia RTX 2070 GPU. 

* CUDA 9.0
* cuDNN 7201
* pytorch 0.5.0a0
* Linux
* Python 3.6


Also got this error

`torch.backends.cudnn.CuDNNError: 4: b'CUDNN_STATUS_INTERNAL_ERROR'` 

when using Nvidia GTX 1080 ti.

**Comment by rajatvd** [comment]
Updating to the CUDA 10 compiled version of pytorch along with CUDA 10 runtime resolved this issue for me.

**Comment by abdelrahmanabdelnabi** [comment]
I am facing a similar issue when using the Tesla T4 GPU on google colab. The error i get is different however.

The error is:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-33-e4fc2d268128> in <module>()
----> 1 model = train_model(model, dataloaders_dict['train'], criterion, optimizer, epoch_n, dataloaders_dict['valid'])

2 frames
<ipython-input-31-3a065a40fb11> in train_model(model, train_loader, criterion, optimizer, epoch_n, validation_loader)
     27             loss = criterion(outputs, labels)
     28 
---> 29             loss.sum().backward()
     30             optimizer.step()
     31             _, preds = torch.max(outputs, 1)

/usr/local/lib/python3.6/dist-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    100                 products. Defaults to ``False``.
    101         """
--> 102         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    103 
    104     def register_hook(self, hook):

/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     88     Variable._execution_engine.run_backward(
     89         tensors, grad_tensors, retain_graph, create_graph,
---> 90         allow_unreachable=True)  # allow_unreachable flag
     91 
     92 

RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

I tried installing the CUDA 10 version of pytorch by running the following but this didn't fix my issue.
```
pip uninstall torch
pip install torch==1.0.1 -f https://download.pytorch.org/whl/cu100/stable # CUDA 10.0 build
```

**Comment by soumith** [comment]
@abdelrahmanabdelnabi can you try 1.1, i.e `pip install torch==1.1.0 -f https://download.pytorch.org/whl/cu100/stable` and see if it fixes the issue?

**Comment by abdelrahmanabdelnabi** [comment]
@soumith I tried it, but unfortunately it didn't fix the issue.

The code was working fine without any errors on nividia Tesla K80 on google colab. But since colab started rolling out the Tesla T4 recently, this error showed up on the first run on T4 GPUs. Do you think this is an issue with pytorch or CuDNN?

Here is the relevant part of the code where the error happens:

```
model = resnet101(sample_size=input_size, sample_duration=sample_duration)
```

```
def train_model(model, train_loader, criterion, optimizer, epoch_n, validation_loader):
    model = model.to(device)
    iterations = 0
    last_valid_acc = 0.0
    
    for epoch in range(epoch_n):
        model.train()
        print('=========================epoch %i=====================' % epoch)
        epoch_loss = 0.0
        running_loss = 0.0
        epoch_corrects = 0
        for i, data in enumerate(tqdm(train_loader)):
            inputs, labels = data
            inputs = inputs.to(device)
            labels = labels.to(device)
            
            optimizer.zero_grad()

            outputs = model(inputs)
            loss = criterion(outputs, labels)
            
            loss.sum().backward()
            optimizer.step()
            _, preds = torch.max(outputs, 1)
            epoch_corrects += torch.sum(preds == labels.data)
            .....
```

we are using the `resnet101` model from [this repo](https://github.com/kenshohara/3D-ResNets-PyTorch)

The error happens in the `backward()` call on line `loss.sum().backward()`

**Comment by soumith** [comment]
my command was incorrect. I updated it now to `pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl`, can you give that a try?
I will try in colab on my end as well

**Comment by soumith** [comment]
the snippet at the top works fine for me in Colab on T4.

<img width="1021" alt="Screen Shot 2019-05-01 at 10 42 43 AM" src="https://user-images.githubusercontent.com/1310570/57022708-ebe40d00-6bfd-11e9-9ab8-80ed2eb7313c.png">

**Comment by abdelrahmanabdelnabi** [comment]
@soumith It is working now. Thank you so much!

**Comment by ak9250** [comment]
I am getting the same error in google colab 
![Screen Shot 2019-05-12 at 11 40 02 PM](https://user-images.githubusercontent.com/6818285/57594693-4ee37700-750f-11e9-94e5-0e089d5cfd39.png)

**Comment by xinliweiyuan** [comment]
I had the same problem.  It is the problem of Cudnn. Before Cuda 1.0, the RNN doesn't support Cudnn, everything works fine. 

In [4]: a = torch.randn([30, 5])                                                                  
In [5]: a.to(torch.device('cuda'))     
it works fine. 

In [2]: rnn = torch.nn.GRU(100, 32)                                                               
In [3]: rnn.to(torch.device('cuda')) 
If I wanna create a rnn to cuda, error happens.
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED.

So it is definitely the Bug of new version Cuda 1.0. It works fine until I update the Cuda version. But an early version of Cuda 1.0 still works fine.  Cuda 1.0 has some changes in later released packages. The jit is proposed to accelerate rnn. Depends on whether Cudnn is applied.

**Comment by xinliweiyuan** [comment]
By the way, Cuda 1.1 still has the same issues. I tried on Cuda 10.0 and 9.0, the problem is the same.
@soumith .

**Comment by abdelrahmanabdelnabi** [comment]
@ak9250 you did not install the correct version of this command judging from the output of pip. You have to uninstall pytorch first using `pip3 uninstall pytorch` then install the correct version using the command you used.

**Comment by liuyyy111** [comment]
I have the same problem on T4

CUDA version is 11.2
PyTorch version is 0.4.1

**Comment by Rushil231100** [comment]
I encountered the same problem , have you found the solution ?@liuyyy111

**Comment by liuyyy111** [comment]
> I encountered the same problem , have you found the solution ?@liuyyy111

Sorry, I did not continue to struggle with this issue at the time. Due to time constraints, I directly use another server to train the model.
