### ISSUE TITLE
[libtorch] FindCUDA error when running cmake

### ISSUE THREAD

**Issue by cindycia** [pytorch/pytorch#14333]
## ❓ Questions and Help
I am trying to link libtorch with my project using CMakeList.txt. But cmake gives me the following error when executing 
```
project(my_project CXX CUDA) 
find_package(Torch REQUIRED)
```

> – Caffe2: CUDA detected: 9.0.176
> – Caffe2: CUDA nvcc is: /usr/local/cuda-9.0/bin/nvcc
> – Caffe2: CUDA toolkit directory: /usr/local/cuda-9.0
> – Caffe2: Header version is: 9.0
> CMake Error at /opt/libtorch/share/cmake/Caffe2/public/cuda.cmake:59 (message):
> FindCUDA says CUDA version is (usually determined by nvcc), but the CUDA
> headers say the version is 9.0. This often occurs when you set both
> CUDA_HOME and CUDA_NVCC_EXECUTABLE to non-standard locations, without also
> setting PATH to point to the correct nvcc. Perhaps, try re-running this
> command again with PATH=/usr/local/cuda-9.0/bin:$PATH. See above log
> messages for more diagnostics, and see
> https://github.com/pytorch/pytorch/issues/8092 for more details.
> Call Stack (most recent call first):
> /opt/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
> /opt/libtorch/share/cmake/Torch/TorchConfig.cmake:39 (find_package)

I am using:

- Ubuntu 18.04
- Cmake 3.12.4
- CUDA 9.0.176
- libtorch 1.0.0.dev20181121

**Comment by cindycia** [comment]
I solved the problem by changing STREQUAL to STRLESS_EQUAL at /opt/libtorch/share/cmake/Caffe2/public/cuda.cmake:59

Now I can pass the configuration stage, but not the generation stage. New errors becomes:

> CMake Error:
>   Error evaluating generator expression:
> 
>     $<TARGET_PROPERTY:caffe2,INTERFACE_SYSTEM_INCLUDE_DIRECTORIES>
> 
>   Target "caffe2" not found.
> 
> 
> CMake Error:
>   Error evaluating generator expression:
> 
>     $<TARGET_PROPERTY:caffe2_gpu,INTERFACE_SYSTEM_INCLUDE_DIRECTORIES>
> 
>   Target "caffe2_gpu" not found.
> 
> 
> CMake Error:
>   Error evaluating generator expression:
> 
>     $<TARGET_PROPERTY:caffe2,INTERFACE_SYSTEM_INCLUDE_DIRECTORIES>
> 
>   Target "caffe2" not found.
> 
> 
> CMake Error:
>   Error evaluating generator expression:
> 
>     $<TARGET_PROPERTY:caffe2_gpu,INTERFACE_SYSTEM_INCLUDE_DIRECTORIES>
> 
>   Target "caffe2_gpu" not found.
> 
> 
> -- Generating done
> -- Build files have been written to: /home/panpan/workspace/catkin_ws/build
> Makefile:4460: recipe for target 'cmake_check_build_system' failed
> make: *** [cmake_check_build_system] Error 1
> Invoking "make cmake_check_build_system" failed

I am using catkin_make instead of cmake:
`catkin_make CMAKE_BUILD_TYPE=Release -j12 -DCUDA_HOST_COMPILER=/usr/bin/gcc-5
Only one package in my catkin workspace is using libtorch.

**Comment by vishwakftw** [comment]
Could you try with the latest nightly build? https://github.com/pytorch/pytorch/pull/14302 also tried to fix a similar bug.

**Comment by cindycia** [comment]
> Could you try with the latest nightly build? #14302 also tried to fix a similar bug.

Thanks for your reply~

I downloaded libtorch today only, from this link: https://download.pytorch.org/libtorch/nightly/cu90/libtorch-shared-with-deps-latest.zip

Is it the latest nightly build? Or do you know where can I get it?

**Comment by vishwakftw** [comment]
Oh I am sorry. I didn't realize that you required LibTorch. Maybe you could try installing LibTorch from source, as specified [here](https://raw.githubusercontent.com/pytorch/pytorch/master/docs/libtorch.rst).

**Comment by cindycia** [comment]
> Oh I am sorry. I didn't realize that you required LibTorch. Maybe you could try installing LibTorch from source, as specified [here](https://raw.githubusercontent.com/pytorch/pytorch/master/docs/libtorch.rst).

Will try that. Thanks.

**Comment by qchenclaire** [comment]
> > Oh I am sorry. I didn't realize that you required LibTorch. Maybe you could try installing LibTorch from source, as specified [here](https://raw.githubusercontent.com/pytorch/pytorch/master/docs/libtorch.rst).
> 
> Will try that. Thanks.

Does that work? I came across the same problem

**Comment by ezyang** [comment]
@qchenclaire This is a pretty old bug. If you have a problem, I suggest filing a new bug.

@cindycia, I'm going to close this under the assumption that you got it to work; reopen if that's not true.
