### ISSUE TITLE
Loading sparse tensors in a `DataLoader` raises CUDA initialization error since `2.5.0`

### ISSUE THREAD

**Issue by douglas-boubert** [pytorch/pytorch#144687]
### 🐛 Describe the bug

```python
import torch
from torch.utils.data import Dataset, DataLoader


def create_sparse_tensor():
    tensor = torch.randn(5, 5)
    sparse_tensor = tensor.to_sparse().to("cpu")
    torch.save(sparse_tensor, "sparse_tensor.pth")


class OperatorDataset(Dataset):
    def __init__(self):
        self.files = ["sparse_tensor.pth"]
        
    def __len__(self):
        return len(self.files)
    
    def __getitem__(self, idx):
        _ = torch.load(self.files[idx], weights_only=True, map_location="cpu")
        return None


if __name__ == '__main__':
    print(torch.__version__)

    create_sparse_tensor()
    
    dataset = OperatorDataset()
    
    dataloader = DataLoader(
        dataset,
        batch_size=None,
        num_workers=1,
        pin_memory=True,
    )
    
    for sparse_tensor in dataloader:
        # Error raised here
        pass
```

This code snippet succeeds on PyTorch 2.4.1 and fails on 2.5.0, 2.5.1 and the latest nightly:

```
2.5.1+cu124
Traceback (most recent call last):
  File "/home/douglas/minimum_working_example.py", line 37, in <module>
    for sparse_tensor in dataloader:
  File "/home/douglas/miniconda3/envs/torch_sparse/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/home/douglas/miniconda3/envs/torch_sparse/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
  File "/home/douglas/miniconda3/envs/torch_sparse/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/home/douglas/miniconda3/envs/torch_sparse/lib/python3.10/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/douglas/miniconda3/envs/torch_sparse/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/douglas/miniconda3/envs/torch_sparse/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    data = self.dataset[possibly_batched_index]
  File "/home/douglas/projects/gen11/research-lethe/minimum_working_example.py", line 19, in __getitem__
    _ = torch.load(self.files[idx], weights_only=True, map_location="cpu")
  File "/home/douglas/miniconda3/envs/torch_sparse/lib/python3.10/site-packages/torch/serialization.py", line 1351, in load
    return _load(
  File "/home/douglas/miniconda3/envs/torch_sparse/lib/python3.10/site-packages/torch/serialization.py", line 1851, in _load
    torch._utils._validate_loaded_sparse_tensors()
  File "/home/douglas/miniconda3/envs/torch_sparse/lib/python3.10/site-packages/torch/_utils.py", line 254, in _validate_loaded_sparse_tensors
    torch._validate_sparse_coo_tensor_args(
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Versions

Collecting environment information...
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Rocky Linux release 8.8 (Green Obsidian) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.28

Python version: 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-477.13.1.el8_8.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe
GPU 2: NVIDIA A100 80GB PCIe
GPU 3: NVIDIA A100 80GB PCIe

Nvidia driver version: 530.30.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  1
Core(s) per socket:  16
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Gold 6326 CPU @ 2.90GHz
Stepping:            6
CPU MHz:             3500.000
CPU max MHz:         3500.0000
CPU min MHz:         800.0000
BogoMIPS:            5800.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            24576K
NUMA node0 CPU(s):   0-15
NUMA node1 CPU(s):   16-31
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==2.2.1
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] torch==2.5.1
[pip3] torchaudio==2.5.1
[pip3] torchvision==0.20.1
[pip3] triton==3.1.0
[conda] numpy                     2.2.1                    pypi_0    pypi
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] torch                     2.5.1                    pypi_0    pypi
[conda] torchaudio                2.5.1                    pypi_0    pypi
[conda] torchvision               0.20.1                   pypi_0    pypi
[conda] triton                    3.1.0                    pypi_0    pypi

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jcaip @andrewkho @divyanshk @SsnL @VitalyFedyunin @dzhulgakov @ptrblck @msaroufim @eqy

**Comment by pearu** [comment]
Try updating your test script as follows:
```
...
if __name__ == '__main__':
    torch.multiprocessing.set_start_method("spawn")
    ...
```

**Comment by douglas-boubert** [comment]
> Try updating your test script as follows:
> 
> ...
> if __name__ == '__main__':
>     torch.multiprocessing.set_start_method("spawn")
>     ...

Adding this line (or passing `multiprocessing_context = "spawn"` to the `DataLoader`) solves the error, but comes with non-negligible overhead. This working on `2.4.1` and before and not from `2.5.0` and later feels like a significant regression, so I'd really appreciate someone taking a deeper look!

**Comment by andrewkho** [comment]
@douglas-boubert can you try adding the option 'multiprocessing_context="forkserver"' to the DataLoader constructor?

**Comment by douglas-boubert** [comment]
> [@douglas-boubert](https://github.com/douglas-boubert) can you try adding the option 'multiprocessing_context="forkserver"' to the DataLoader constructor?

This resolves the error with a similar added overhead to using `multiprocessing_context="spawn"`.

**Comment by pearu** [comment]
> This resolves the error with a similar added overhead...

How large is the added overhead? Does the overhead also appear when using PyTorch 2.4.1 with `multiprocessing_context = "spawn"` (or `"forkserver"`)?

FWIW, I confirm that this issue appears only when loading sparse tensors, the test works fine with strided tensors.

**Comment by douglas-boubert** [comment]
> [@douglas-boubert](https://github.com/douglas-boubert) My understanding is that this should be startup overhead, but throughput after startup should be identical, can you confirm that's the case?
> 
> In general, having CUDA running in multiprocess workers isn't supported. With context="forkserver" and "spawn" it will re-initialize the context, and in your case it's probably running with "fork". (as an aside, "fork" will no longer be the default in [python 3.14](https://docs.python.org/3.14/whatsnew/3.14.html#multiprocessing), as it is incompatible with multi-threading in general).

The overhead is in start-up (about 10 seconds) and shut-down (about 120 seconds!) on the first epoch with 16 workers (measured with python `3.10` and torch `2.4.1`). Subsequent epochs don't have this overhead. Throughput after start-up is identical for `"fork"` and `"forkserver"`, but `"spawn"` seems to be a bit slower. I am using a quite complex custom Dataset which may be the culprit of the extreme timing of the first epoch.

Thanks for pointing out that `"forkserver"` will be default from `3.14`. It makes the bitter pill of the initial overhead easier to swallow!

> For this particular use case, it's during torch.load. Is CUDA necessary here? cc [@albanD](https://github.com/albanD) I'm not sure who the best person is for this.
> 
> ```
> File "/home/douglas/miniconda3/envs/torch_sparse/lib/python3.10/site-packages/torch/_utils.py", line 254, in _validate_loaded_sparse_tensors
>     torch._validate_sparse_coo_tensor_args(
> RuntimeError: CUDA error: initialization error
> ```

This is what concerns me - the workers shouldn't need access to CUDA to load sparse tensors on CPU.

**Comment by pearu** [comment]
The culprit of
```
RuntimeError: CUDA error: initialization error
```
starts from
https://github.com/pytorch/pytorch/blob/7e1c1e65ebf52a1b26d24a7bd2a234e3a5101f48/aten/src/ATen/native/sparse/SparseTensor.cpp#L399-L405
where `is_pinned` call sequence fails at
https://github.com/pytorch/pytorch/blob/7e1c1e65ebf52a1b26d24a7bd2a234e3a5101f48/c10/cuda/CUDAFunctions.cpp#L221

**Comment by pearu** [comment]
Here is a simple reproducer of the issue:
```python
# File: test_fork.py
import torch
import os
t = torch.tensor([1, 2])
print(f'1: {t.is_pinned()}')
os.fork()
print(f'2: {t.is_pinned()}')
```
results
```
1: False
2: False
Traceback (most recent call last):
  File "/home/pearu/test/pytorch/test_fork.py", line 6, in <module>
    print(f'2: {t.is_pinned()}')
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by albanD** [comment]
I think the real regression here is that checking if a Tensor is pinned is initializing cuda in the first place.
If cuda is not initialized, pinned should just return False without initializing.
And from there, forking is still fine because cuda was never initialized.

**Comment by pearu** [comment]
@albanD , I agree. However, from reading the code and some debugging, I think "checking if a Tensor is pinned is initializing cuda" is inaccurate: when `is_pinned` is called, the ATen/C10 state of cuda within fork is a copy of the original process and if the original process has cuda initialized then for the fork the cuda state is also *apparently* initialized while *actually* it is not. For example, the reproducer in https://github.com/pytorch/pytorch/issues/144687#issuecomment-2592802676 fails because the first `is_pinned` initializes CUDA but the following example (where the cuda is not initialized in the original process) works fine:
```python
import torch
import os
t = torch.tensor([1, 2])
# print(f'1: {t.is_pinned()}')
os.fork()
print(f'2: {t.is_pinned()}')
```
Output:
```
2: False
2: False
```

**Comment by albanD** [comment]
I'm still not sure what changed. 
This code hasn't changed in many years https://github.com/pytorch/pytorch/blame/main/aten/src/ATen/cuda/detail/CUDAHooks.cpp#L117-L126

Did we change the meaning of `at::cuda::is_available()` from returning False pre-initialization to now return True?

cc @ngimel

**Comment by douglas-boubert** [comment]
There have been some recent (post `2.4.1`) changes to `isPinnedPtr`: https://github.com/pytorch/pytorch/blame/main/aten/src/ATen/Context.h#L94-L105

On line 98 it calls `at::getAccelerator`, which is mentioned in this recent open issue: https://github.com/pytorch/pytorch/issues/144152

> Indeed, since 2.5.0, torch.device(0) calls at::getAccelerator, which ends up calling cudaGetDeviceCount and thus initializing CUDA and preventing forks

**Comment by michael-diggin** [comment]
Hi @albanD - sorry to bother but I'm wondering if there's any update on this issue? I can see there's a PR that would fix it from a few weeks ago.

**Comment by albanD** [comment]
Hey!
This has been solved for the upcoming 2.7 release!
