### ISSUE TITLE
dist.all_gather_object causes OOM when gathering string lists, attempting to allocate >1EB memory. wo informative error message

### ISSUE THREAD

**Issue by qsh-zh** [pytorch/pytorch#145965]
### 🐛 Describe the bug

I've encountered an Out of Memory (OOM) error when using dist.all_gather_object to gather lists of strings across multiple tasks. 

For example, 
I use dcp to load checkpoint, and run into the following error 
```shell
[rank112]:     dcp.load(
[rank112]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/logger.py", line 83, in wrapper
[rank112]:     result = func(*args, **kwargs)
[rank112]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/utils.py", line 429, in inner_func
[rank112]:     return func(*args, **kwargs)
[rank112]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/state_dict_loader.py", line 154, in load
[rank112]:     keys = _all_gather_keys(state_dict, process_group)
[rank112]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/utils.py", line 49, in _all_gather_keys
[rank112]:     dist.all_gather_object(gathered_keys, keys, group=group)
[rank112]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
[rank112]:     return func(*args, **kwargs)
[rank112]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2728, in all_gather_object
[rank112]:     input_tensor.resize_(max_object_size)
[rank112]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate more than 1EB memory.
```

it should be noted that 
```shell
[rank112]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/utils.py", line 49, in _all_gather_keys
[rank112]:     dist.all_gather_object(gathered_keys, keys, group=group)
```
only try to all gather a list of string. It is hard to believe it tries to allocate more than 1EB memory. 

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.4
Libc version: glibc-2.35

Python version: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1055-aws-x86_64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: 12.6.77
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3
GPU 2: NVIDIA H100 80GB HBM3
GPU 3: NVIDIA H100 80GB HBM3
GPU 4: NVIDIA H100 80GB HBM3
GPU 5: NVIDIA H100 80GB HBM3
GPU 6: NVIDIA H100 80GB HBM3
GPU 7: NVIDIA H100 80GB HBM3

Nvidia driver version: 550.54.15
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      48 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          AuthenticAMD
Model name:                         AMD EPYC 7R13 Processor
CPU family:                         25
Model:                              1
Thread(s) per core:                 2
Core(s) per socket:                 48
Socket(s):                          2
Stepping:                           1
BogoMIPS:                           5300.00
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save vaes vpclmulqdq rdpid
Hypervisor vendor:                  KVM
Virtualization type:                full
L1d cache:                          3 MiB (96 instances)
L1i cache:                          3 MiB (96 instances)
L2 cache:                           48 MiB (96 instances)
L3 cache:                           384 MiB (12 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-47,96-143
NUMA node1 CPU(s):                  48-95,144-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Vulnerable, no microcode
Vulnerability Spec store bypass:    Vulnerable
Vulnerability Spectre v1:           Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:           Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] DISTS-pytorch==0.1
[pip3] flake8==7.1.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] nvidia-cudnn-frontend==1.7.0
[pip3] nvidia-nccl-cu12==2.22.3
[pip3] nvidia-pytriton==0.5.13
[pip3] nvtx==0.2.10
[pip3] onnx==1.16.2
[pip3] onnx-graphsurgeon==0.5.2
[pip3] onnxruntime==1.20.0
[pip3] optree==0.13.0
[pip3] pynvjitlink==0.3.0
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-triton==3.0.0+dedb7bdf3
[pip3] slangtorch==1.3.1
[pip3] torch==2.5.0a0+e000cf0ad9.nv24.10
[pip3] torch_automated_profiler==1.10.0
[pip3] torch-fidelity==0.3.0
[pip3] torch-optimizer==0.3.0
[pip3] torch_tensorrt==2.5.0a0
[pip3] torchmetrics==1.6.0
[pip3] torchprofile==0.0.4
[pip3] torchvision==0.20.0a0
[pip3] tritonclient==2.51.0
[conda] Could not collect

**Comment by ptrblck** [comment]
Similar issue reported [here](https://discuss.pytorch.org/t/error-torch-cuda-outofmemoryerror-cuda-out-of-memory-tried-to-allocate-more-than-1eb-memory/215712). 
CC @kwen2501 @eqy

**Comment by kwen2501** [comment]
The object size comes from an all-gather across ranks. It could be possible that the all-gather has data corruption, or the result being accessed before the all-gather actually finishes.

Also cc DCP team @LucasLLC

**Comment by kwen2501** [comment]
Hi @qsh-zh it seems to me the code at question is just doing a safety check:
https://github.com/pytorch/pytorch/blob/18a7a04c4adecda3be17dd364d48d484fd1dcdba/torch/distributed/checkpoint/state_dict_loader.py#L158-L163

If it is not too much hassle, you can delete that block and replace it with:
```
keys = list(state_dict.keys())
```
as in the `no_dist` case.

**Comment by qsh-zh** [comment]
@kwen2501  thank you for your response. Indeed we can remove the safety check for dcp.

However, it will be nicer if we can make `dist.all_gather_object` safer. 

> It could be possible that the all-gather has data corruption, or the result being accessed before the all-gather finishes.

anything we can do to avoid corruption or accessing data before finishing all-gather

**Comment by kwen2501** [comment]
That requires more debugging effort. Do you have a way to stably reproduce the error?

**Comment by qsh-zh** [comment]
thanks @kwen2501 

from  @mikolajblaz
```
From my experience it can be caused by improper application logic which messes up the order of collective calls so they don't match.
Part of all_gather_object is exchange of sizes to allocate and if some ranks calls some other collective instead of all_gather_object (e.g. a barrier), it gets interpreted as a size on ranks that called all_gather_object and blows everything up.
```.

`dcp` or `all_gather_object` code is ok,  but users need to be careful when calling them and complaining error can be misleading. 


in my checkpoint case, I have several checkpoint to load. After I make sure the loading order are same for all gpus and insert proper barrier after load one checkpoint, it works now. Otherwise, one gpu can is doing all gather while other gpu may doing other collectives. and pytorch complains `CUDA out of memory. Tried to allocate more than 1EB memory.` 

feel free to close to the issue.
