### ISSUE TITLE
flex_attention throws `CUDA error: an illegal memory access was encountered`

### ISSUE THREAD

**Issue by mauriceweiler** [pytorch/pytorch#147268]
### 🐛 Describe the bug

When calling torch.compiled `flex_attention` after a `max_pool2d` operation I encounter an error:
```
RuntimeError: CUDA error: an illegal memory access was encountered
```
To align the data layout expected by `flex_attention` and `max_pool2d` I am using `.reshape` and `.moveaxis` operations.
I observed that the issue is fixed when calling `.contiguous` after both `.moveaxis` ops but reoccurs when calling `.clone()` afterwards.

To reproduce this issue, run `python reproducer.py --setting N`, where N=0,...,3:
- [N=0]: This version uses `.contiguous` and runs without error.
- [N=1]: Here we switch off `.contiguous` after `.moveaxis`, resulting in the illegal memory access error.
- [N=2]: If we `.clone` the feature tensor after the pooling operation it breaks again, despite using `.contiguous`.
- [N=3]: If we only use the first `.contiguous`, there is yet another error `torch._inductor.exc.InductorError: LoweringException: AssertionError: Query must be contiguous in the last dimension`

`reproducer.py`:
``` python
import argparse
import torch
from torch.nn.attention.flex_attention import flex_attention, create_block_mask

flex_attention_compiled = torch.compile(flex_attention)

def pool(feat, kernel_size, stride, padding, CONTIGUOUS_1, CONTIGUOUS_2, CLONE):
    B,H,N,C = feat.shape
    X = int(N**.5)
    feat = feat.reshape(B*H,X,X,C)   # reshape to square pixel grid, treat heads as batch dimension
    feat = feat.moveaxis(-1,1)       # (BH,C,X,X), as required for pytorch grid ops like pool2d
    if CONTIGUOUS_1: # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        feat = feat.contiguous()     # <<< REQUIRED TO PREVENT ILLEGAL MEMORY ACCESS ERROR !!! <<<<<
    feat = torch.nn.functional.max_pool2d(feat, kernel_size, stride, padding)
    feat = feat.moveaxis(1,-1)       # (BH,C,X',X')
    if CONTIGUOUS_2: # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        feat = feat.contiguous()     # <<< REQUIRED TO PREVENT ILLEGAL MEMORY ACCESS ERROR !!! <<<<<
    feat = feat.reshape(B,H,-1,C)    # (B,H,N',C), as required by flex_attention
    if CLONE: # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        feat = feat.clone()          # <<< REINTRODUCES ERROR EVEN WHEN .contiguous IS USED !!! <<<<
    return feat


if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('--setting',
                        help = 'switches between experimental settings 0,...,3',
                        type = int)
    args = parser.parse_args()

    # Everything works out when using .contiguous after both .moveaxis in pool
    if args.setting == 0:
        CONTIGUOUS_1 = True
        CONTIGUOUS_2 = True
        CLONE        = False
    # Switching off .contiguous yields:
    # RuntimeError: CUDA error: an illegal memory access was encountered
    # (this works when not compiling flex_attention)
    elif args.setting == 1:
        CONTIGUOUS_1 = False
        CONTIGUOUS_2 = False
        CLONE        = False
    # Adding a .clone() before passing features into flex_attention again leads to an illegal memory
    # error despite using .contiguous.
    elif args.setting == 2:
        CONTIGUOUS_1 = True
        CONTIGUOUS_2 = True
        CLONE        = True
    # When using only the first .contiguous, we get yet another error:
    # torch._inductor.exc.InductorError: LoweringException: AssertionError: Query must be contiguous in the last dimension
    elif args.setting == 3:
        CONTIGUOUS_1 = True
        CONTIGUOUS_2 = False
        CLONE        = True
    else:
        raise ValueError('Invalid setting passed, should be in 0,...,3.')


    B = 64
    H =  8
    C = 64
    N = 32**2

    feat = torch.randn(B,H,N,C).cuda()
    feat = pool(feat, kernel_size=5, stride=1, padding=0,
                CONTIGUOUS_1=CONTIGUOUS_1, CONTIGUOUS_2=CONTIGUOUS_2, CLONE=CLONE)
    print('pool:', feat.shape, feat[0,0,0,0])
    feat = flex_attention_compiled(feat, feat, feat)
    print('attn:', feat.shape, feat[0,0,0,0]) # accessing feat is required to surface the error
```
@BoyuanFeng 

### Error logs

Illegal memory access error for `python reproducer --setting 1` and `python reproducer --setting 2`:
```
  File ".../reproducer_illegal_memory_error.py", line 71, in <module>
    print('attn:', feat.shape, feat[0,0,0,0]) # accessing feat is required to surface the error
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/torch/_tensor.py", line 590, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/torch/_tensor_str.py", line 702, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File ".../.venv/lib/python3.13/site-packages/torch/_tensor_str.py", line 621, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File ".../.venv/lib/python3.13/site-packages/torch/_tensor_str.py", line 353, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File ".../.venv/lib/python3.13/site-packages/torch/_tensor_str.py", line 145, in __init__
    nonzero_finite_vals = torch.masked_select(
        tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0)
    )
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

For `python reproducer --setting 3` we get another error `torch._inductor.exc.InductorError: LoweringException: AssertionError: Query must be contiguous in the last dimension`:
```
Traceback (most recent call last):
  File ".../reproducer_illegal_memory_error.py", line 70, in <module>
    feat = flex_attention_compiled(feat, feat, feat)
  File ".../.venv/lib/python3.13/site-packages/torch/_dynamo/eval_frame.py", line 589, in _fn
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/torch/_inductor/compile_fx.py", line 752, in _compile_fx_inner
    raise InductorError(e, currentframe()).with_traceback(
        e.__traceback__
    ) from None
  File ".../.venv/lib/python3.13/site-packages/torch/_inductor/compile_fx.py", line 737, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
        gm, example_inputs, inputs_to_check, **graph_kwargs
    )
  File ".../.venv/lib/python3.13/site-packages/torch/_inductor/compile_fx.py", line 1405, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/torch/_inductor/compile_fx.py", line 1060, in codegen_and_compile
    graph.run(*example_inputs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/torch/_inductor/graph.py", line 855, in run
    return super().run(*args)
           ~~~~~~~~~~~^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/torch/fx/interpreter.py", line 171, in run
    self.env[node] = self.run_node(node)
                     ~~~~~~~~~~~~~^^^^^^
  File ".../.venv/lib/python3.13/site-packages/torch/_inductor/graph.py", line 1440, in run_node
    result = super().run_node(n)
  File ".../.venv/lib/python3.13/site-packages/torch/fx/interpreter.py", line 236, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/torch/_inductor/graph.py", line 1143, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
        e.__traceback__
    ) from None
  File ".../.venv/lib/python3.13/site-packages/torch/_inductor/graph.py", line 1133, in call_function
    out = lowerings[target](*args, **kwargs)  # type: ignore[index]
  File ".../.venv/lib/python3.13/site-packages/torch/_inductor/lowering.py", line 462, in wrapped
    out = decomp_fn(*args, **kwargs)
  File ".../.venv/lib/python3.13/site-packages/torch/_inductor/kernel/flex_attention.py", line 1260, in flex_attention
    assert q_strides[-1] == 1, "Query must be contiguous in the last dimension"
           ^^^^^^^^^^^^^^^^^^
torch._inductor.exc.InductorError: LoweringException: AssertionError: Query must be contiguous in the last dimension
  target: flex_attention
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='arg0_1', layout=FixedLayout('cuda:0', torch.float32, size=[64, 8, 784, 64], stride=[401408, 50176, 1, 784]))
  ))
  args[1]: TensorBox(StorageBox(
    InputBuffer(name='arg0_1', layout=FixedLayout('cuda:0', torch.float32, size=[64, 8, 784, 64], stride=[401408, 50176, 1, 784]))
  ))
  args[2]: TensorBox(StorageBox(
    InputBuffer(name='arg0_1', layout=FixedLayout('cuda:0', torch.float32, size=[64, 8, 784, 64], stride=[401408, 50176, 1, 784]))
  ))
  args[3]: Subgraph(name='sdpa_score0', graph_module=<lambda>(), graph=None)
  args[4]: (1, 1, TensorBox(StorageBox(
    ComputedBuffer(name='buf2', layout=FlexibleLayout('cuda:0', torch.int32, size=[1, 1, 1], stride=[1, 1, 1]), data=Pointwise(device=device(type='cuda', index=0), dtype=torch.int32, inner_fn=<function _full.<locals>.inner_fn at 0x7f29d51ee660>, ranges=[1, 1, 1]))
  )), TensorBox(StorageBox(
    ComputedBuffer(name='buf3', layout=FlexibleLayout('cuda:0', torch.int32, size=[1, 1, 1, 1], stride=[1, 1, 1, 1]), data=Pointwise(device=device(type='cuda', index=0), dtype=torch.int32, inner_fn=<function _full.<locals>.inner_fn at 0x7f29d51efba0>, ranges=[1, 1, 1, 1]))
  )), None, None, TensorBox(StorageBox(
    ComputedBuffer(name='buf4', layout=FlexibleLayout('cuda:0', torch.int32, size=[1, 1, 1], stride=[1, 1, 1]), data=Pointwise(device=device(type='cuda', index=0), dtype=torch.int32, inner_fn=<function make_pointwise.<locals>.inner.<locals>.inner_fn at 0x7f29d52087c0>, ranges=[1, 1, 1]))
  )), TensorBox(StorageBox(
    ComputedBuffer(name='buf5', layout=FlexibleLayout('cuda:0', torch.int32, size=[1, 1, 1, 1], stride=[1, 1, 1, 1]), data=Pointwise(device=device(type='cuda', index=0), dtype=torch.int32, inner_fn=<function make_pointwise.<locals>.inner.<locals>.inner_fn at 0x7f29d5208ea0>, ranges=[1, 1, 1, 1]))
  )), None, None, 1073741824, 1073741824, Subgraph(name='sdpa_mask0', graph_module=<lambda>(), graph=None))
  args[5]: 0.125
  args[6]: {'PRESCALE_QK': False, 'ROWS_GUARANTEED_SAFE': False, 'BLOCKS_ARE_CONTIGUOUS': False, 'WRITE_DQ': True, 'OUTPUT_LOGSUMEXP': True}
  args[7]: ()
  args[8]: ()

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

### Versions

```
Collecting environment information...
PyTorch version: 2.7.0.dev20250213+cu126
Is debug build: False
CUDA used to build PyTorch: 12.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 24.04.2 LTS (x86_64)
GCC version: (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.39

Python version: 3.13.1 (main, Dec 19 2024, 14:32:25) [Clang 18.1.8 ] (64-bit runtime)
Python platform: Linux-6.8.0-52-generic-x86_64-with-glibc2.39
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe
GPU 2: NVIDIA A100 80GB PCIe
GPU 3: NVIDIA A100 80GB PCIe
GPU 4: NVIDIA A100 80GB PCIe
GPU 5: NVIDIA A100 80GB PCIe
GPU 6: NVIDIA A100 80GB PCIe
GPU 7: NVIDIA A100 80GB PCIe

Nvidia driver version: 550.120
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        43 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               128
On-line CPU(s) list:                  0-127
Vendor ID:                            AuthenticAMD
Model name:                           AMD EPYC 7532 32-Core Processor
CPU family:                           23
Model:                                49
Thread(s) per core:                   2
Core(s) per socket:                   32
Socket(s):                            2
Stepping:                             0
Frequency boost:                      enabled
CPU(s) scaling MHz:                   119%
CPU max MHz:                          2400.0000
CPU min MHz:                          1500.0000
BogoMIPS:                             4799.85
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
Virtualization:                       AMD-V
L1d cache:                            2 MiB (64 instances)
L1i cache:                            2 MiB (64 instances)
L2 cache:                             32 MiB (64 instances)
L3 cache:                             512 MiB (32 instances)
NUMA node(s):                         2
NUMA node0 CPU(s):                    0-31,64-95
NUMA node1 CPU(s):                    32-63,96-127
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec rstack overflow:   Mitigation; Safe RET
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==2.2.3
[pip3] nvidia-cublas-cu12==12.6.4.1
[pip3] nvidia-cuda-cupti-cu12==12.6.80
[pip3] nvidia-cuda-nvrtc-cu12==12.6.77
[pip3] nvidia-cuda-runtime-cu12==12.6.77
[pip3] nvidia-cudnn-cu12==9.5.1.17
[pip3] nvidia-cufft-cu12==11.3.0.4
[pip3] nvidia-curand-cu12==10.3.7.77
[pip3] nvidia-cusolver-cu12==11.7.1.2
[pip3] nvidia-cusparse-cu12==12.5.4.2
[pip3] nvidia-cusparselt-cu12==0.6.3
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.6.85
[pip3] nvidia-nvtx-cu12==12.6.77
[pip3] pytorch-triton==3.2.0+git4b3bb1f8
[pip3] torch==2.7.0.dev20250213+cu126
[pip3] torchaudio==2.6.0.dev20250213+cu126
[pip3] torchvision==0.22.0.dev20250213+cu126
[conda] Could not collect
```

cc @chauhang @penguinwu @zou3519 @ydwu4 @bdhirsh @Chillee @drisspg @yanboliang @BoyuanFeng

**Comment by drisspg** [comment]
Thanks for finding this! Here is the fix: https://github.com/pytorch/pytorch/pull/147918

**Comment by mauriceweiler** [comment]
Thanks for the fix! I can confirm the issue is resolved in today's nightly.
