### ISSUE TITLE
FlexAttention compiled has illegal memory access or device-side assert even though all tensors are contiguous

### ISSUE THREAD

**Issue by leijurv** [pytorch/pytorch#147551]
### 🐛 Describe the bug

```python
import torch
import torch.nn.attention.flex_attention
flex_compiled = torch.compile(torch.nn.attention.flex_attention.flex_attention)
torch.set_default_device("cuda")
print(torch.__version__)

if False:
    # these params trigger device-side assert:
    BATCH = 64
    HEADS = 64
    SEQ_LEN = 64
    D_HEAD = 64
    BAND = 64
else:
    # these params trigger illegal memory access:
    BATCH = 64
    HEADS = 64
    SEQ_LEN = 256
    D_HEAD = 64
    BAND = 64

Q = torch.randn((BATCH, HEADS, SEQ_LEN, D_HEAD), requires_grad=True)
K = torch.randn((BATCH, HEADS, SEQ_LEN, D_HEAD), requires_grad=True)
V = torch.randn((BATCH, HEADS, SEQ_LEN, D_HEAD), requires_grad=True)
rel_bias = torch.randn((BATCH, HEADS, SEQ_LEN, BAND), requires_grad=True)

def score_mod(score, b, h, q_idx, kv_idx):
    return score + rel_bias[b, h, q_idx, q_idx - kv_idx]

def local_mask(b, h, q_idx, kv_idx):
    causal_mask = q_idx >= kv_idx
    window_mask = q_idx - kv_idx < BAND
    return causal_mask & window_mask

flex_compiled(Q, K, V, score_mod=score_mod,
    block_mask=torch.nn.attention.flex_attention.create_block_mask(
        local_mask, B=BATCH, H=HEADS, Q_LEN=SEQ_LEN, KV_LEN=SEQ_LEN
    ),
)
```

Run with `CUDA_LAUNCH_BLOCKING=1`

```
2.7.0.dev20250220+cu124
Traceback (most recent call last):
  File "/home/ubuntu/repro2.py", line 35, in <module>
    flex_compiled(Q, K, V, score_mod=score_mod,
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 585, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/attention/flex_attention.py", line 1161, in flex_attention
    def flex_attention(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 764, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1199, in forward
    return compiled_fn(full_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 312, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 126, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 100, in g
    return f(*args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1847, in forward
    fw_outs = call_func_at_runtime_with_args(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 126, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 492, in wrapper
    return compiled_fn(runtime_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 686, in inner_fn
    outs = compiled_fn(args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_inductor/output_code.py", line 460, in __call__
    return self.current_callable(inputs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_inductor/utils.py", line 2348, in run
    return model(new_inputs)
  File "/tmp/torchinductor_ubuntu/hl/chlfd7hdtv2xyfko4hkkkgsy232itg4iclcanvyruwr6r2ortqxu.py", line 548, in call
    triton_tem_fused_0.run(primals_1, primals_2, primals_3, buf0, primals_5, primals_4, primals_7, primals_8, primals_6, buf1, grid=torch._inductor.kernel.flex_attention.flex_attention_grid(64, 64, 256, 64, meta0), stream=stream0)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 956, in run
    return launcher(
  File "<string>", line 6, in launcher
  File "/home/ubuntu/.local/lib/python3.10/site-packages/triton/backends/nvidia/driver.py", line 444, in __call__
    self.launch(*args, **kwargs)
RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered
```

If I add extra padding to either side of `rel_bias`, like this: `rel_bias = torch.randn((BATCH+2, HEADS, SEQ_LEN, BAND), requires_grad=True)[1:-1]`, it "fixes" the illegal memory access case, but not the device-side assert case.

Additionally, even with that `rel_bias` padding workaround, these parameters cause the illegal memory access to occur now in the backward pass (just add `.sum().backward()`):
```
BATCH = 128
HEADS = 6
SEQ_LEN = 128
D_HEAD = 16
BAND = 16
```

<details><summary>Backward pass log</summary>

```
2.7.0.dev20250220+cu124
Traceback (most recent call last):
  File "/home/ubuntu/repro2.py", line 45, in <module>
    ).sum().backward()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_tensor.py", line 639, in backward
    return handle_torch_function(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/overrides.py", line 1721, in handle_torch_function
    result = mode.__torch_function__(public_api, types, args, kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/_device.py", line 104, in __torch_function__
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_tensor.py", line 648, in backward
    torch.autograd.backward(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 353, in backward
    _engine_run_backward(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/autograd/graph.py", line 824, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 307, in apply
    return user_fn(self, *args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1982, in backward
    return impl_fn()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1968, in impl_fn
    out = CompiledFunction._backward_impl(ctx, all_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2088, in _backward_impl
    out = call_func_at_runtime_with_args(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 126, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 764, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_inductor/output_code.py", line 460, in __call__
    return self.current_callable(inputs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_inductor/utils.py", line 2348, in run
    return model(new_inputs)
  File "/tmp/torchinductor_ubuntu/gh/cgh4rpnwzkagkm7cznka43dnr5bxpncxulpr3n2tdnbcrst2hpqc.py", line 1027, in call
    triton_tem_fused_zeros_2.run(primals_1, primals_2, primals_3, getitem_1, buf2, tangents_1, buf4, buf5, primals_5, primals_4, primals_9, primals_10, primals_7, primals_8, primals_11, primals_12, primals_6, buf0, buf6, grid=torch._inductor.kernel.flex_attention.flex_attention_backward_grid(128, 6, 128, 16, 6, 128, meta0), stream=stream0)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 956, in run
    return launcher(
  File "<string>", line 6, in launcher
  File "/home/ubuntu/.local/lib/python3.10/site-packages/triton/backends/nvidia/driver.py", line 444, in __call__
    self.launch(*args, **kwargs)
RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered
```
</details>

### Versions

<details><summary>Env</summary>

```
Collecting environment information...
PyTorch version: 2.7.0.dev20250220+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.31.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jan 17 2025, 14:35:34) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.4.131
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3

Nvidia driver version: 565.57.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        52 bits physical, 57 bits virtual
Byte Order:                           Little Endian
CPU(s):                               52
On-line CPU(s) list:                  0-51
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Xeon(R) Platinum 8480+
CPU family:                           6
Model:                                143
Thread(s) per core:                   2
Core(s) per socket:                   26
Socket(s):                            1
Stepping:                             8
BogoMIPS:                             4000.00
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx_vnni avx512_bf16 wbnoinvd arat vnmi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b fsrm md_clear serialize tsxldtrk avx512_fp16 arch_capabilities
Virtualization:                       VT-x
Hypervisor vendor:                    KVM
Virtualization type:                  full
L1d cache:                            1.6 MiB (52 instances)
L1i cache:                            1.6 MiB (52 instances)
L2 cache:                             104 MiB (26 instances)
L3 cache:                             16 MiB (1 instance)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-51
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Unknown: No mitigations
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI SW loop, KVM SW loop
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] flake8==4.0.1
[pip3] numpy==1.21.5
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-cusparselt-cu12==0.6.2
[pip3] nvidia-nccl-cu12==2.25.1
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pytorch-triton==3.2.0+git4b3bb1f8
[pip3] torch==2.7.0.dev20250220+cu124
[pip3] triton==3.2.0+gitb99a3006
[conda] Could not collect
```
</details>

cc @chauhang @penguinwu @zou3519 @ydwu4 @bdhirsh @Chillee @drisspg @yanboliang @BoyuanFeng

**Comment by anijain2305** [comment]
cc @drisspg

**Comment by drisspg** [comment]
There are a number of problems w/ the code you pasted, here is a guess at what you might want

The two main changes:
1. In your block-mask func you need to have the absolute valu or else you would get something like (0 - Seq_ln) which will always be less than band
2. in your score-mod I am not exactly sure which rel_bias band you want added to what but again the errors are specifically from this line since you are trying to load rel_bias at psoition 64 or 256 (max-seq-len) but there arent enough elements



```py
import torch
import torch.nn.attention.flex_attention
flex_compiled = torch.compile(torch.nn.attention.flex_attention.flex_attention)
torch.set_default_device("cuda")
print(torch.__version__)

if False:
    # these params trigger device-side assert:
    BATCH = 64
    HEADS = 64
    SEQ_LEN = 64
    D_HEAD = 64
    BAND = 64
else:
    # these params trigger illegal memory access:
    BATCH = 64
    HEADS = 64
    SEQ_LEN = 256
    D_HEAD = 64
    BAND = 64

Q = torch.randn((BATCH, HEADS, SEQ_LEN, D_HEAD), requires_grad=True)
K = torch.randn((BATCH, HEADS, SEQ_LEN, D_HEAD), requires_grad=True)
V = torch.randn((BATCH, HEADS, SEQ_LEN, D_HEAD), requires_grad=True)
rel_bias = torch.randn((BATCH, HEADS, SEQ_LEN, BAND), requires_grad=True)

def score_mod(score, b, h, q_idx, kv_idx):
    band_idx = torch.abs(q_idx - kv_idx) % BAND
    return score + rel_bias[b, h, q_idx, band_idx]

def local_mask(b, h, q_idx, kv_idx):
    causal_mask = q_idx >= kv_idx
    window_mask = torch.abs(q_idx - kv_idx) < BAND
    return causal_mask & window_mask

flex_compiled(Q, K, V, score_mod=score_mod,
    block_mask=torch.nn.attention.flex_attention.create_block_mask(
        local_mask, B=BATCH, H=HEADS, Q_LEN=SEQ_LEN, KV_LEN=SEQ_LEN
    ),
)

```

**Comment by leijurv** [comment]
@drisspg The `causal_mask = q_idx >= kv_idx` line guarantees that q_idx-kv_idx can't be negative.

Therefore, shouldn't `causal_mask & window_mask` guarantee that the `rel_bias[b, h, q_idx, q_idx - kv_idx]` is in range? Since q_idx-kv_idx will always be >=0 and <BAND

**Comment by leijurv** [comment]
I suspect the real issue here is that score_mod is being evaluated even when mask_mod returns false, which I think ought to be considered a bug. Clearly the mask_mod is evaluated per each element, since it does mask at a finer grain than a block of 128. I believe that calling score_mod should be guarded behind that check, rather than running unconditionally.

**Comment by leijurv** [comment]
Also my original issue did mention padding the rel_bias to allow these spurious out of bounds reads:

> If I add extra padding to either side of rel_bias, like this:

**Comment by drisspg** [comment]
Sorry I was so terse I misread the initial issue

This has been a long standing issue that is tracked elsewhere -> tldr is that we evaluate all positions of the score_mod in partial blocks and this can lead to IMA's I will re-bump this but so far users have been able to work around.


cc @danielvegamyhre  This might be a good one to pick up if you are interested

**Comment by rmmr** [comment]
@drisspg How could one work around this? Also were is this issue tracked. I believe i'm running into this one too.

**Comment by leijurv** [comment]
The `mask_mod` already overrides the score to -inf within the block, so I imagined that a `torch.where` (or equivalent) to fill the masked values with negative infinity is probably already present? The problem is that before this operation the score_mod has already been called. Hopefully, it's just rearranging some code so that when the q_idx,kv_idx pair is masked out the score_mod is not called at all (rather than called then overridden to -inf).

**Comment by drisspg** [comment]
So for a user try to work around this, my claim:

```Py
def score_mod(score, b, h, q_idx, kv_idx):
    return score + rel_bias[b, h, q_idx, q_idx - kv_idx] # this is the bad line since rel-bias is being indexed for OOB values in the partial blocks

def local_mask(b, h, q_idx, kv_idx):
    causal_mask = q_idx >= kv_idx
    window_mask = q_idx - kv_idx < BAND
    return causal_mask & window_mask

```
So a user can re-write this 
```Py
def score_mod(score, b, h, q_idx, kv_idx):
	causal_mask = q_idx >= kv_idx)
 	window_mask = q_idx - kv_idx < BAND
	return score + torch.where(causal_mask & window_mask, rel_bias[b, h, q_idx, q_idx - kv_idx], float('-inf')
```

So that in the partial blocks we don't end up loading from the no no places. We plan to fix this though internal to Flex

**Comment by rmmr** [comment]
Turns out my issue was different. With regards to the score mod having to "reapply" the causual mask, i can concur this is needed to make things work. An example of my mask mods / score mods:

```
q_batch: torch.Tensor # provided externally
kv_batch: torch.Tensor # provided externally

def batch_causual_mask_mod(
            b: torch.Tensor,
            h: torch.Tensor,
            q_idx: torch.Tensor,
            kv_idx: torch.Tensor,
        ):
            q_idx_batch = q_batch[q_idx]
            kv_idx_batch = kv_batch[kv_idx]
            batch_mask = (
                (q_idx_batch == kv_idx_batch)
                & (q_idx_batch != -1)
                & (kv_idx_batch != -1)
            )

            causual_mask = q_idx >= kv_idx
            return batch_mask & causual_mask

# Factory
def rel_pe_score_mod(
    num_heads: int,
    block_size: Optional[int] = None,
    causual: bool = False,
) -> ScoreModSignature:

    def score_mod(
        score: torch.Tensor,
        b: torch.Tensor,
        h: torch.Tensor,
        q_idx: torch.Tensor,
        kv_idx: torch.Tensor,
    ):
        scale = torch.exp2(-((h + 1) * 8.0 / num_heads))
        q, kv = (
            (q_idx // block_size, kv_idx // block_size)
            if block_size is not None
            else (q_idx, kv_idx)
        )
        bias = (kv - q) * scale
        score = score + bias
        if causual:
            score = torch.where(q >= kv, score, -float("inf"))
        return score

    return score_mod


```

So in short, even though the mask mod provides causual masking, it seems that for now the score mod needs to apply this (too).

**Comment by cora-codes** [comment]
Interestingly, even with an extremely paranoid relative attention version, I'm getting illegal memory access errors _during autotune_ 😱:

```python
        def score_mod(score, b, h, q_idx, kv_idx):
            causal_mask = q_idx >= kv_idx
            window_mask = q_idx - kv_idx < 256
            return score + torch.where(
                causal_mask & window_mask,
                rel_bias[torch.clamp(b, 0, 31), torch.clamp(h, 0, 23), torch.clamp(q_idx, 0, 4095), torch.clamp(q_idx - kv_idx, 0, 255)],
                float("-inf"),
            )
```

Also, I'm calling `contiguous()` everywhere.

(You can see: https://gist.github.com/cora-codes/c5eb8e3e7130255973241009b3ca10b8 for the full traceback)

`2.8.0.dev20250327+cu126`

**Comment by drisspg** [comment]
W/
```Py
import torch
import torch.nn.attention.flex_attention
flex_compiled = torch.compile(torch.nn.attention.flex_attention.flex_attention, mode="max-autotune-no-cudagraphs")
torch.set_default_device("cuda")
print(torch.__version__)

if False:
    # these params trigger device-side assert:
    BATCH = 64
    HEADS = 64
    SEQ_LEN = 64
    D_HEAD = 64
    BAND = 64
else:
    # these params trigger illegal memory access:
    BATCH = 32
    HEADS = 24
    SEQ_LEN = 4096
    D_HEAD = 64
    BAND = 256

Q = torch.randn((BATCH, HEADS, SEQ_LEN, D_HEAD), requires_grad=True)
K = torch.randn((BATCH, HEADS, SEQ_LEN, D_HEAD), requires_grad=True)
V = torch.randn((BATCH, HEADS, SEQ_LEN, D_HEAD), requires_grad=True)
rel_bias = torch.randn((BATCH, HEADS, SEQ_LEN, BAND), requires_grad=True)

def score_mod(score, b, h, q_idx, kv_idx):
    causal_mask = q_idx >= kv_idx
    window_mask = q_idx - kv_idx < 256
    return score + torch.where(
        causal_mask & window_mask,
        rel_bias[torch.clamp(b, 0, 31), torch.clamp(h, 0, 23), torch.clamp(q_idx, 0, 4095), torch.clamp(q_idx - kv_idx, 0, 255)],
        float("-inf"),
    )


def local_mask(b, h, q_idx, kv_idx):
    causal_mask = q_idx >= kv_idx
    window_mask = q_idx - kv_idx < BAND
    return causal_mask & window_mask

cbm = torch.compile(torch.nn.attention.flex_attention.create_block_mask)

out = flex_compiled(Q, K, V, score_mod=score_mod,
    block_mask=cbm(
        local_mask, B=BATCH, H=HEADS, Q_LEN=SEQ_LEN, KV_LEN=SEQ_LEN
    ),
)

```
?

**Comment by cora-codes** [comment]
It only happens during backward so `out.sum().backward()` is required to see it

**Comment by cora-codes** [comment]
Eating my words, because that works for me... (but benchmarking does take 1772.9214 seconds) - odd. I will keep looking at this - I'm very confident something is going wrong

**Comment by cora-codes** [comment]
OK, I've got a reproduction - it's because of an interaction with `torch.autocast`:

```
import torch
import torch.nn.attention.flex_attention

# flex_compiled = torch.compile(
#     torch.nn.attention.flex_attention.flex_attention, mode="max-autotune-no-cudagraphs"
# )
torch.set_default_device("cuda")
print(torch.__version__)

if False:
    # these params trigger device-side assert:
    BATCH = 64
    HEADS = 64
    SEQ_LEN = 64
    D_HEAD = 64
    BAND = 64
else:
    # these params trigger illegal memory access:
    BATCH = 32
    HEADS = 24
    SEQ_LEN = 4096
    D_HEAD = 16
    BAND = 256

Q = torch.randn(
    (BATCH, HEADS, SEQ_LEN, D_HEAD), requires_grad=True
)
K = torch.randn(
    (BATCH, HEADS, SEQ_LEN, D_HEAD), requires_grad=True
)
V = torch.randn(
    (BATCH, HEADS, SEQ_LEN, D_HEAD), requires_grad=True
)
# rel_bias = torch.randn(
#     (BATCH, HEADS, SEQ_LEN, BAND), dtype=torch.bfloat16, requires_grad=True
# )

rel_embed = torch.zeros((HEADS, BAND, D_HEAD), device=torch.device("cuda"))


@torch.compile(mode="max-autotune-no-cudagraphs")
def main(Q, K, V, rel_embed):

    with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
        rel_bias = (Q @ rel_embed.unsqueeze(0).transpose(-1, -2)).contiguous().to(torch.float32)

        def score_mod(score, b, h, q_idx, kv_idx):
            causal_mask = q_idx >= kv_idx
            window_mask = q_idx - kv_idx < 256
            return score + torch.where(
                causal_mask & window_mask,
                rel_bias[
                    torch.clamp(b, 0, 31),
                    torch.clamp(h, 0, 23),
                    torch.clamp(q_idx, 0, 4095),
                    torch.clamp(q_idx - kv_idx, 0, 255),
                ],
                float("-inf"),
            )

        out, _ = torch.nn.attention.flex_attention.flex_attention(
            Q,
            K,
            V,
            score_mod=score_mod,
            scale=1/D_HEAD,
            return_lse=True,
        )
    out.sum().backward()


main(Q, K, V, rel_embed)
```

**Comment by cora-codes** [comment]
Also, you might need `TORCHINDUCTOR_FORCE_DISABLE_CACHES=1`

**Comment by drisspg** [comment]
Yup an repro, not entirely sure its the same kinda IMA yet but investigating

**Comment by cora-codes** [comment]
Yeah, I can open a different issue to track it if you'd like

**Comment by aorenste** [comment]
The repro runs cleanly on every tested PyTorch version (2.12, 2.4 and current 2.12.0+cu132). No evidence the bug reproduces. Could the reporter confirm the issue is still relevant, or share a more deterministic repro?

Versions tested:

| PyTorch | Verdict |
|---|---|
| 2.12.0+cu132 | Passes |
| 2.12 | Different error (rc=1) |
| 2.4 | Different error (rc=1) |

_(Automated bisection — `bisect_version`.)_

**Comment by drisspg** [comment]
I fixed this
