### ISSUE TITLE
[HSDP2] `TORCH_NCCL_AVOID_RECORD_STREAMS` x `use_deterministic_algorithms` => NaN Gradient

### ISSUE THREAD

**Issue by leonardo0lyj** [pytorch/pytorch#147810]
### 🐛 Describe the bug

Hey Andrew @awgu,  as a big fan of FSDP2, I find an potential BC issue with `TORCH_NCCL_AVOID_RECORD_STREAMS = True` 😄

*Demand*
- HSDP (2D mesh in FSDP2)
- `TORCH_NCCL_AVOID_RECORD_STREAMS = True`
- `torch.use_deterministic_algorithms(True)`

*Result*
- After `.backward()`, sharded parameter gradient has NaN, non-deterministically.
- NaN only happens when both `TORCH_NCCL_AVOID_RECORD_STREAMS = True` and `torch.use_deterministic_algorithms(True)`

*Minimal Code*

```python3
class TestTorchHSDP(DTensorTestBase):

    @property
    def world_size(self) -> int:
        return 4

    @with_comms
    def test_torch_hsdp(self): 
        # NOTE: 
        # `TORCH_NCCL_AVOID_RECORD_STREAMS`x`use_deterministic_algorithms`=> grads have NaN
        #   0 x 0 => No
        #   0 x 1 => No
        #   1 x 0 => No
        #   1 x 1 => Yes
        
        os.environ["TORCH_NCCL_AVOID_RECORD_STREAMS"] = "1"
        os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
        torch.use_deterministic_algorithms(True)
        
        # mesh & fsdp2
        from torch.distributed.device_mesh import init_device_mesh # torch version: 2.4.1
        from torch.distributed._composable.fsdp import fully_shard, FSDPModule
        mesh = init_device_mesh("cuda", (2, 2), mesh_dim_names=("replicate", "shard"))
        
        # llama model
        from transformers import AutoConfig, LlamaModel # transformer version: 4.46.1 (same for other version)
        from transformers.models.llama.modeling_llama import LlamaDecoderLayer
        dir_path = os.path.dirname(os.path.realpath(__file__))
        config = AutoConfig.from_pretrained(os.path.join(dir_path, "../llama/llama_config.json"))
        config.num_hidden_layers = 4
        config.hidden_size = 32
        config.intermediate_size = 88
        config.max_position_embeddings = 32
        config.vocab_size = 512

        torch.manual_seed(0)
        model: nn.Module = LlamaModel(config).cuda()

        # fsdp
        fully_shard_fn = functools.partial(
            fully_shard,
            mesh=mesh,
            # reshard_after_forward? # same NaN
            # mixed precision? # same NaN
        )
        for submod in model.modules():
            if isinstance(submod, LlamaDecoderLayer):
                fully_shard_fn(submod)
        fully_shard_fn(model)
        # model.set_reshard_after_backward()? # same NaN

        # data
        torch.manual_seed(self.rank)
        
        # microbatches
        for i in range(99):
            if self.rank == 0:
                print(f"[DEBUG] microbatch {i}")

            input = torch.randint(low=0, high=config.vocab_size, size=(4, 4), device="cuda")
            output = model(input).last_hidden_state
            output.mean().backward()

            # check NaN grad
            fsdp_params = []
            for module in cast(nn.Module, model).modules():
                if isinstance(module, FSDPModule):
                    if fsdp_param_group := module._get_fsdp_state()._fsdp_param_group:
                        fsdp_params += fsdp_param_group.fsdp_params
            for fsdp_param in fsdp_params:
                sharded_param = fsdp_param.sharded_param
                if not sharded_param.requires_grad:
                    continue
                if sharded_param.grad is None:
                    continue
                local_grad = sharded_param.grad._local_tensor
                self.assertEqual(torch.isnan(local_grad).sum().item(), 0, msg=f"{local_grad}")
                replicate_grad = sharded_param.grad.full_tensor()
                self.assertEqual(torch.isnan(replicate_grad).sum().item(), 0, msg=f"{replicate_grad}")

```

*llama_config.json*
```json
{
    "architectures": [
      "LlamaForCausalLM"
    ],
    "bos_token_id": 1,
    "eos_token_id": 2,
    "hidden_act": "silu",
    "hidden_size": 4096,
    "initializer_range": 0.02,
    "intermediate_size": 11008,
    "max_position_embeddings": 2048,
    "model_type": "llama",
    "num_attention_heads": 32,
    "num_hidden_layers": 32,
    "pad_token_id": 0,
    "rms_norm_eps": 1e-06,
    "tie_word_embeddings": false,
    "torch_dtype": "float32",
    "transformers_version": "4.46.1",
    "use_cache": true,
    "vocab_size": 32000
  }
```

*Potential Culprit*
- Deterministic algorithm fills empty tensor (gradient reduce input/output) with [NaN value](https://pytorch.org/docs/stable/generated/torch.empty_like.html) 
- This NaN is exposed in sharded parameter grads when no record stream. 

I have been digging this issue for 3 days, still no idea yet. 🤔️ How do you think? Appreciated 🙏

### Versions

PyTorch version: 2.4.1+gitee1b680
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.28.3
Libc version: glibc-2.31

Python version: 3.11.10 (main, Nov 21 2024, 15:54:09) [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.15.120.bsk.2-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A800-SXM4-40GB
GPU 1: NVIDIA A800-SXM4-40GB
GPU 2: NVIDIA A800-SXM4-40GB
GPU 3: NVIDIA A800-SXM4-40GB

Nvidia driver version: 535.161.08
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   52 bits physical, 57 bits virtual
CPU(s):                          120
On-line CPU(s) list:             0-119
Thread(s) per core:              2
Core(s) per socket:              30
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8336C CPU @ 2.30GHz
Stepping:                        6
CPU MHz:                         2294.616
BogoMIPS:                        4589.23
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       2.8 MiB
L1i cache:                       1.9 MiB
L2 cache:                        75 MiB
L3 cache:                        108 MiB
NUMA node0 CPU(s):               0-59
NUMA node1 CPU(s):               60-119
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.12.1
[pip3] torch==2.4.1+gitee1b680
[pip3] torchdistx==0.3.0.dev0+cu121
[pip3] torchvision==0.17.0+b2383d4
[pip3] triton==3.0.0

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @zhaojuanmao @mrshenli @rohan-varma @chauhang

**Comment by awgu** [comment]
I have not had a chance to look into your repro, but I wanted to let you know that there was a CUDA sync correctness issue fixed in https://github.com/pytorch/pytorch/pull/140044 since seems you are using PyTorch 2.4.1.
