### ISSUE TITLE
Handle bugs in cudnnGet* better

### ISSUE THREAD

**Issue by chenyuntc** [pytorch/pytorch#1485]
Simple code to reproduce the problem:
```python
import torch
import torch.nn as nn
ec=nn.Conv3d(1,1,3,2,1).cuda()
input=torch.autograd.Variable(torch.ones(1,1,511,512,512),requires_grad=True).cuda()
ec(input).sum().backward()
```
it raises:
```
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```
Even if I add `contiguous`, it still doesn't work.  

- if I change input to torch.ones(1,1,510,512,512), it works fine. 

- if I set `requires_grad` to False, It raise another error:
```
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
```

I'm using:
torch: 0.1.12_1(pip install using binary)
cudnn 5.1, cuda 8
tested in GTX1080 and Titan X

------
I tried to update cudnn to v6, it still doesn't work(there is libcudnn.so.6 in `torch/lib` after install with wheel, but I still upgrade the system libcudnn to the latest version)

**Comment by ngimel** [comment]
Looks like cudnnGet* is returning the wrong algorithm. A workaround is to use ```torch.backends.cudnn.benchmark=True```

**Comment by chenyuntc** [comment]
@ngimel thanks, it works fine with `cudnn.benchmark=Ture`.

**Comment by Astrosun** [comment]
@ngimel , Thanks a lot for your answer. I have the same problem and it works fine for me.
Could you please elaborate more about this solution?

**Comment by fcalvet** [comment]
Run into a similar issue when switching from a tensor with shape [2,1,8,512,512] to one with shape [2,1,512,512,8] broke my script. 

Could this be somehow related to the expected shape for convolution being `minibatch×in_channels×iT×iH×iW `and not `minibatch×in_channels×iH×iW×iT`, with T<W and H ?
If so should a check be implemented to warn the user, regardless of the fix for this bug ?

The following error is raised, interestingly not in the forward pass but during the backward one:
```
`  File "train.py", line 90, in train_epoch
    loss.backward()
  File "/home/fcalvet/pytorch/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/fcalvet/pytorch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CuDNN error: CUDNN_STATUS_EXECUTION_FAILED
````

The fix `torch.backends.cudnn.benchmark=True` did work. So I would be curious to know more about this "cudnnGet* is returning the wrong algorithm" and how it could for example affect performance.

For reference, I'm using PyTorch 0.4.1 with CUDA 9.2 installed with pip on Linux

**Comment by gchanan** [comment]
removing "topic: crash" as this doesn't crash.

**Comment by mruberry** [comment]
Both of the shapes mentioned now appear to function properly. Please reopen if you're still seeing this issue.
