### ISSUE TITLE
Can not build pytorch tag v1.0.0 from source

### ISSUE THREAD

**Issue by BIGBALLON** [pytorch/pytorch#14930]
I got the error when i build pytorch from source (checkout v1.0.0)

System: Ubuntu 16.04
Cuda: 9.2
cudnn: 7.4.1

```
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn --use-qnnpack caffe2'
```

build log:

```bash
Building wheel torch-1.0.0a0+db5d313
running install
setup.py::run()
running build_deps
setup.py::build_deps::run()
+ SYNC_COMMAND=cp
++ command -v rsync
+ '[' -x /usr/bin/rsync ']'
+ SYNC_COMMAND='rsync -lptgoD'
+ CMAKE_COMMAND=cmake
++ command -v cmake3
+ [[ -x '' ]]
+ USE_CUDA=0
+ USE_FBGEMM=0
+ USE_ROCM=0
+ USE_NNPACK=0
+ USE_MKLDNN=0
+ USE_QNNPACK=0
+ USE_GLOO_IBVERBS=0
+ CAFFE2_STATIC_LINK_CUDA=0
+ RERUN_CMAKE=1
+ [[ 5 -gt 0 ]]
+ case "$1" in
+ USE_CUDA=1
+ shift
+ [[ 4 -gt 0 ]]
+ case "$1" in
+ USE_NNPACK=1
+ shift
+ [[ 3 -gt 0 ]]
+ case "$1" in
+ USE_MKLDNN=1
+ shift
+ [[ 2 -gt 0 ]]
+ case "$1" in
+ USE_QNNPACK=1
+ shift
+ [[ 1 -gt 0 ]]
+ case "$1" in
+ break
+ CMAKE_INSTALL='make install'
+ BUILD_SHARED_LIBS=ON
+ USER_CFLAGS=
+ USER_LDFLAGS=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
++ uname
+ '[' Linux == Darwin ']'
+++ dirname ../tools/build_pytorch_libs.sh
++ cd ../tools/..
+++ pwd
++ printf '%q\n' /home/bg/pytorch
+ BASE_DIR=/home/bg/pytorch
+ TORCH_LIB_DIR=/home/bg/pytorch/torch/lib
+ INSTALL_DIR=/home/bg/pytorch/torch/lib/tmp_install
+ THIRD_PARTY_DIR=/home/bg/pytorch/third_party
+ C_FLAGS=
+ C_FLAGS=' -DOMPI_SKIP_MPICXX=1'
+ LDFLAGS=
+ LD_POSTFIX=.so
++ uname
+ [[ Linux == \D\a\r\w\i\n ]]
+ [[ 0 -eq 1 ]]
+ LDFLAGS=' -Wl,-rpath,$ORIGIN'
+ CPP_FLAGS=' -std=c++11 '
+ THD_FLAGS=
+ [[ 0 -eq 1 ]]
+ CUDA_NVCC_FLAGS=' -DOMPI_SKIP_MPICXX=1'
+ [[ -z '' ]]
+ CUDA_DEVICE_DEBUG=0
+ '[' -z '' ']'
++ getconf _NPROCESSORS_ONLN
+ MAX_JOBS=8
+ BUILD_TYPE=Release
+ [[ -n '' ]]
+ [[ -n '' ]]
+ echo 'Building in Release mode'
Building in Release mode
+ mkdir -p /home/bg/pytorch/torch/lib/tmp_install
+ for arg in '"$@"'
+ [[ caffe2 == \c\a\f\f\e\2 ]]
+ build_caffe2
+ [[ -z '' ]]
+ EXTRA_CAFFE2_CMAKE_FLAGS=()
+ [[ -n '' ]]
+ [[ -n /usr/lib/python3/dist-packages ]]
+ EXTRA_CAFFE2_CMAKE_FLAGS+=("-DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH")
+ [[ 1 -eq 1 ]]
+ cmake /home/bg/pytorch -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_LIBRARY=/usr/lib/libpython3.5m.so.1.0 -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m -DBUILDING_WITH_TORCH_LIBS=ON -DTORCH_BUILD_VERSION=1.0.0a0+db5d313 -DCMAKE_BUILD_TYPE=Release -DBUILD_TORCH=ON -DBUILD_PYTHON=ON -DBUILD_SHARED_LIBS=ON -DBUILD_BINARY=OFF -DBUILD_TEST=ON -DINSTALL_TEST=ON -DBUILD_CAFFE2_OPS=ON -DONNX_NAMESPACE=onnx_torch -DUSE_CUDA=1 -DUSE_DISTRIBUTED=ON -DUSE_FBGEMM=0 -DUSE_NUMPY= -DNUMPY_INCLUDE_DIR=/usr/local/lib/python3.5/dist-packages/numpy/core/include -DUSE_SYSTEM_NCCL=OFF -DNCCL_INCLUDE_DIR= -DNCCL_ROOT_DIR= -DNCCL_SYSTEM_LIB= -DCAFFE2_STATIC_LINK_CUDA=0 -DUSE_ROCM=0 -DUSE_NNPACK=1 -DUSE_LEVELDB=OFF -DUSE_LMDB=OFF -DUSE_OPENCV=OFF -DUSE_QNNPACK=1 -DUSE_FFMPEG=OFF -DUSE_GLOG=OFF -DUSE_GFLAGS=OFF -DUSE_SYSTEM_EIGEN_INSTALL=OFF -DCUDNN_INCLUDE_DIR=/usr/include/ -DCUDNN_LIB_DIR=/usr/lib/x86_64-linux-gnu/ -DCUDNN_LIBRARY=/usr/lib/x86_64-linux-gnu/libcudnn.so.7 -DUSE_MKLDNN=1 -DNCCL_EXTERNAL=1 -DCMAKE_INSTALL_PREFIX=/home/bg/pytorch/torch/lib/tmp_install -DCMAKE_C_FLAGS= -DCMAKE_CXX_FLAGS= '-DCMAKE_EXE_LINKER_FLAGS= -Wl,-rpath,$ORIGIN ' '-DCMAKE_SHARED_LINKER_FLAGS= -Wl,-rpath,$ORIGIN ' -DTHD_SO_VERSION=1 -DCMAKE_PREFIX_PATH=/usr/lib/python3/dist-packages
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- std::exception_ptr is supported.
-- NUMA is available
-- Current compiler supports avx2 extension. Will build perfkernels.
-- Current compiler supports avx512f extension. Will build fbgemm.
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/home/bg/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- The BLAS backend of choice:MKL
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /usr/local/lib/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /usr/local/lib/libmkl_gnu_thread.so
--   Library mkl_core: /usr/local/lib/libmkl_core.so
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Brace yourself, we are building NNPACK
-- Found PythonInterp: /usr/bin/python3 (found version "3.5.2") 
-- Failed to find LLVM FileCheck
-- git Version: v1.4.0-505be96a
-- Version: 1.4.0
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Found Numa  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnuma.so)
-- Using third party subdirectory Eigen.
Python 3.5.2
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib/libpython3.5m.so.1.0 (found suitable version "3.5.2", minimum required is "2.7") 
-- Could NOT find pybind11 (missing: pybind11_DIR)
-- Could NOT find pybind11 (missing: pybind11_INCLUDE_DIR) 
-- Using third_party/pybind11.
-- MPI support found
-- MPI compile flags: 
-- MPI include path: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include/usr/lib/openmpi/include/openmpi/usr/lib/openmpi/include
-- MPI LINK flags path: -Wl,-rpath -Wl,/usr/lib/openmpi/lib -Wl,--enable-new-dtags -pthread
-- MPI libraries: /usr/lib/openmpi/lib/libmpi_cxx.so/usr/lib/openmpi/lib/libmpi.so
CMake Warning at cmake/Dependencies.cmake:619 (message):
  OpenMPI found, but it is not built with CUDA support.
Call Stack (most recent call first):
  CMakeLists.txt:201 (include)


-- Found CUDA: /usr/local/cuda (found suitable version "9.2", minimum required is "7.0") 
-- Caffe2: CUDA detected: 9.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.2
-- Found cuDNN: v7.4.1  (include: /usr/include/, library: /usr/lib/x86_64-linux-gnu/libcudnn.so.7)
-- Autodetected CUDA architecture(s): 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Could NOT find CUB (missing: CUB_INCLUDE_DIR) 
-- MPI include path: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include/usr/lib/openmpi/include/openmpi/usr/lib/openmpi/include
-- MPI libraries: /usr/lib/openmpi/lib/libmpi_cxx.so/usr/lib/openmpi/lib/libmpi.so
-- CUDA detected: 9.2
-- 
-- ******** Summary ********
--   CMake version         : 3.13.1
--   CMake command         : /usr/local/lib/python3.5/dist-packages/cmake/data/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   CXX flags             :  -fvisibility-inlines-hidden -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL
--   CMAKE_PREFIX_PATH     : /usr/lib/python3/dist-packages
--   CMAKE_INSTALL_PREFIX  : /home/bg/pytorch/torch/lib/tmp_install
--   CMAKE_MODULE_PATH     : /home/bg/pytorch/cmake/Modules;/home/bg/pytorch/cmake/public/../Modules_CUDA_fix
-- 
--   ONNX version          : 1.3.0
--   ONNX NAMESPACE        : onnx_torch
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
-- 
--   Protobuf compiler     : 
--   Protobuf includes     : 
--   Protobuf libraries    : 
--   BUILD_ONNX_PYTHON     : OFF
-- Found CUDA with FP16 support, compiling with torch.cuda.HalfTensor
-- Removing -DNDEBUG from compile flags
-- Compiling with MAGMA support
-- MAGMA INCLUDE DIRECTORIES: /home/bg/anaconda3/envs/czf/include
-- MAGMA LIBRARIES: /home/bg/anaconda3/envs/czf/lib/libmagma.a
-- MAGMA V2 check: 1
-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this machine.
-- No OMAP4 processor on this machine.
-- AVX compiler support found
-- AVX2 compiler support found
-- Atomics: using C11 intrinsics
-- Found a library with BLAS API (mkl).
-- Found a library with LAPACK API. (mkl)
-- Found CUDA: /usr/local/cuda (found suitable version "9.2", minimum required is "5.5") 
disabling ROCM because NOT USE_ROCM is set
-- MIOpen not found. Compiling without MIOpen support
CMake Deprecation Warning at third_party/ideep/mkl-dnn/CMakeLists.txt:21 (cmake_policy):
  The OLD behavior for policy CMP0048 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at third_party/ideep/mkl-dnn/CMakeLists.txt:22 (cmake_policy):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Detecting Intel(R) MKL: trying mklml_intel
-- Intel(R) MKL: include /usr/local/include
-- Intel(R) MKL: lib /home/bg/anaconda3/envs/czf/lib/libmklml_intel.so
-- Intel(R) MKL: OpenMP lib -fopenmp
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- VTune profiling environment is unset
CMake Warning (dev) at cmake/public/mkldnn.cmake:1 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable MKLDNN_ROOT is set to:

    /home/bg/pytorch/third_party/ideep/mkl-dnn

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:1309 (INCLUDE)
  CMakeLists.txt:201 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- GCC 5.4.0: Adding gcc and gcc_s libs to link line
-- Using python found in /usr/bin/python3
-- Configuring build for SLEEF-v3.2
   Target system: Linux-4.15.0-42-generic
   Target processor: x86_64
   Host system: Linux-4.15.0-42-generic
   Host processor: x86_64
   Detected C compiler: GNU @ /usr/bin/cc
-- Using option `-Wall -Wno-unused -Wno-attributes -Wno-unused-result -Wno-psabi -ffp-contract=off -fno-math-errno -fno-trapping-math` to compile libsleef
-- Building shared libs : OFF
-- MPFR : LIB_MPFR-NOTFOUND
-- GMP : LIBGMP-NOTFOUND
-- RUNNING_ON_TRAVIS : 0
-- COMPILER_SUPPORTS_OPENMP : 1
-- Using python found in /usr/bin/python3
-- /usr/bin/c++ /home/bg/pytorch/torch/abi-check.cpp -o /home/bg/pytorch/build/abi-check
-- Determined _GLIBCXX_USE_CXX11_ABI=1
-- Found CUDA: /usr/local/cuda (found suitable version "9.2", minimum required is "7.5") 
-- MPI_LIBRARIES: /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so
-- Building the gloo backend with TCP support only
-- MPI_LINK_FLAGS: -Wl,-rpath -Wl,/usr/lib/openmpi/lib -Wl,--enable-new-dtags -pthread
-- Found CUDA: /usr/local/cuda (found version "9.2") 
-- Building C10D with CUDA support
-- MPI_INCLUDE_PATH: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include;/usr/lib/openmpi/include/openmpi;/usr/lib/openmpi/include
-- MPI_LIBRARIES: /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so
-- MPIEXEC: /usr/bin/mpiexec
-- Include NCCL operators
-- Including IDEEP operators
-- Excluding image processing operators due to no opencv
-- Excluding video processing operators due to no opencv
-- Include Observer library
-- Using lib/python3.5/site-packages as python relative installation path
-- Automatically generating missing __init__.py files.
-- A previous caffe2 cmake run already created the __init__.py files.
CMake Warning at CMakeLists.txt:389 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.  Other settings may generate files that are not well
  tested.


-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.13.1
--   CMake command         : /usr/local/lib/python3.5/dist-packages/cmake/data/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   BLAS                  : MKL
--   CXX flags             :  -fvisibility-inlines-hidden -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL;ONNX_NAMESPACE=onnx_torch;MAGMA_V2;USE_C11_ATOMICS=1;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
--   CMAKE_PREFIX_PATH     : /usr/lib/python3/dist-packages
--   CMAKE_INSTALL_PREFIX  : /home/bg/pytorch/torch/lib/tmp_install
-- 
--   TORCH_VERSION         : 1.0.0
--   CAFFE2_VERSION        : 1.0.0
--   BUILD_ATEN_MOBILE     : OFF
--   BUILD_ATEN_ONLY       : OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 3.5.2
--     Python executable   : /usr/bin/python3
--     Pythonlibs version  : 3.5.2
--     Python library      : /usr/lib/libpython3.5m.so.1.0
--     Python includes     : /usr/include/python3.5m
--     Python site-packages: lib/python3/dist-packages
--   BUILD_CAFFE2_OPS      : ON
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ASAN              : OFF
--   USE_CUDA              : 1
--     CUDA static link    : 0
--     USE_CUDNN           : ON
--     CUDA version        : 9.2
--     cuDNN version       : 7.4.1
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     cudart library      : /usr/local/cuda/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
--     cublas library      : /usr/local/cuda/lib64/libcublas.so
--     cufft library       : /usr/local/cuda/lib64/libcufft.so
--     curand library      : /usr/local/cuda/lib64/libcurand.so
--     cuDNN library       : /usr/lib/x86_64-linux-gnu/libcudnn.so.7
--     nvrtc               : /usr/lib/x86_64-linux-gnu/libnvrtc.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--     USE_TENSORRT        : OFF
--   USE_ROCM              : 0
--   USE_EIGEN_FOR_BLAS    : 
--   USE_FBGEMM            : 0
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : ON
--   USE_MKLDNN            : ON
--   USE_MOBILE_OPENGL     : OFF
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : OFF
--   USE_NNPACK            : 1
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_QNNPACK           : 1
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : ON
--     USE_MPI             : ON
--     USE_GLOO            : ON
--     USE_GLOO_IBVERBS    : OFF
--   Public Dependencies  : Threads::Threads;caffe2::mkl;caffe2::mkldnn
--   Private Dependencies : qnnpack;nnpack;cpuinfo;/usr/lib/x86_64-linux-gnu/libnuma.so;fp16;/usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so;gloo;aten_op_header_gen;onnxifi_loader;rt;gcc_s;gcc;dl
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bg/pytorch/build
+ make install -j8
Scanning dependencies of target nccl_external
Scanning dependencies of target clog
Scanning dependencies of target js_embed
Scanning dependencies of target pthreadpool
Scanning dependencies of target benchmark
Scanning dependencies of target gtest
[  0%] Creating directories for 'nccl_external'
Scanning dependencies of target libprotobuf-lite
[  0%] Building CXX object third_party/protobuf/cmake/CMakeFiles/js_embed.dir/__/src/google/protobuf/compiler/js/embed.cc.o
[  0%] Building C object confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/src/threadpool-pthreads.c.o
[  0%] Building C object confu-deps/clog/CMakeFiles/clog.dir/src/clog.c.o
[  0%] Building CXX object third_party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  0%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/benchmark.cc.o
[  0%] No download step for 'nccl_external'
Scanning dependencies of target libprotobuf
/home/bg/pytorch/third_party/QNNPACK/deps/clog/src/clog.c: In function ‘clog_vlog_fatal’:
/home/bg/pytorch/third_party/QNNPACK/deps/clog/src/clog.c:120:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
    write(STDERR_FILENO, out_buffer, prefix_chars + format_chars + CLOG_SUFFIX_LENGTH);
    ^
/home/bg/pytorch/third_party/QNNPACK/deps/clog/src/clog.c: In function ‘clog_vlog_error’:
/home/bg/pytorch/third_party/QNNPACK/deps/clog/src/clog.c:196:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
    write(STDERR_FILENO, out_buffer, prefix_chars + format_chars + CLOG_SUFFIX_LENGTH);
    ^
/home/bg/pytorch/third_party/QNNPACK/deps/clog/src/clog.c: In function ‘clog_vlog_warning’:
/home/bg/pytorch/third_party/QNNPACK/deps/clog/src/clog.c:272:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
    write(STDERR_FILENO, out_buffer, prefix_chars + format_chars + CLOG_SUFFIX_LENGTH);
    ^
[  0%] No patch step for 'nccl_external'
[  0%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/arena.cc.o
/home/bg/pytorch/third_party/QNNPACK/deps/clog/src/clog.c: In function ‘clog_vlog_info’:
/home/bg/pytorch/third_party/QNNPACK/deps/clog/src/clog.c:348:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
    write(STDOUT_FILENO, out_buffer, prefix_chars + format_chars + CLOG_SUFFIX_LENGTH);
    ^
/home/bg/pytorch/third_party/QNNPACK/deps/clog/src/clog.c: In function ‘clog_vlog_debug’:
/home/bg/pytorch/third_party/QNNPACK/deps/clog/src/clog.c:424:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
    write(STDOUT_FILENO, out_buffer, prefix_chars + format_chars + CLOG_SUFFIX_LENGTH);
    ^
[  0%] No update step for 'nccl_external'
[  0%] No configure step for 'nccl_external'
[  0%] Performing build step for 'nccl_external'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[  0%] Linking C static library ../../lib/libclog.a
[  0%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/arena.cc.o
[  0%] Built target clog
[  0%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/arenastring.cc.o
Linking    libnccl.so.2.3.7                    > /home/bg/pytorch/build/nccl/lib/libnccl.so.2.3.7
[  0%] Linking C static library ../../lib/libpthreadpool.a
[  0%] Built target pthreadpool
Scanning dependencies of target gloo
[  0%] Linking CXX executable ../../../bin/js_embed
[  0%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/algorithm.cc.o
Archiving  libnccl_static.a                    > /home/bg/pytorch/build/nccl/lib/libnccl_static.a
/home/bg/pytorch/third_party/nccl/nccl/src
[  0%] Built target js_embed
Scanning dependencies of target onnxifi_loader
[  0%] Building C object third_party/onnx/CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
[  1%] No install step for 'nccl_external'
[  1%] Linking C static library ../../lib/libonnxifi_loader.a
[  1%] Completed 'nccl_external'
[  1%] Built target onnxifi_loader
[  1%] Built target nccl_external
Scanning dependencies of target onnxifi_dummy
Scanning dependencies of target mkldnn
[  1%] Building C object third_party/onnx/CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
[  1%] Linking C shared library ../../lib/libonnxifi_dummy.so
[  1%] Built target onnxifi_dummy
[  1%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/extension_set.cc.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/batch_normalization.cpp.o
[  1%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/arenastring.cc.o
[  1%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/allgather.cc.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/convolution.cpp.o
[  1%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/generated_message_table_driven_lite.cc.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/convolution_relu.cpp.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/deconvolution.cpp.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/eltwise.cpp.o
[  1%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/extension_set.cc.o
[  1%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/allreduce.cc.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/engine.cpp.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/inner_product.cpp.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/lrn.cpp.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/memory.cpp.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/memory_desc_wrapper.cpp.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/mkldnn_debug.cpp.o
[  1%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/pooling.cpp.o
[  1%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/generated_message_util.cc.o
[  1%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/allreduce_local.cc.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/primitive.cpp.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/primitive_attr.cpp.o
[  1%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/io/coded_stream.cc.o
[  1%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/barrier.cc.o
[  1%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/io/zero_copy_stream.cc.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/primitive_desc.cpp.o
[  1%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/broadcast.cc.o
[  1%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/generated_message_table_driven_lite.cc.o
[  1%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/primitive_iterator.cpp.o
[  2%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/io/zero_copy_stream_impl_lite.cc.o
[  2%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/message_lite.cc.o
[  3%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/query.cpp.o
[  3%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/repeated_field.cc.o
[  3%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/context.cc.o
[  3%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/reorder.cpp.o
[  3%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/atomicops_internals_x86_gcc.cc.o
[  3%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/rnn.cpp.o
[  3%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/atomicops_internals_x86_msvc.cc.o
[  3%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/bytestream.cc.o
[  3%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/scratchpad.cpp.o
[  3%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/gather.cc.o
[  3%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/softmax.cpp.o
[  3%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/stream.cpp.o
[  3%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/utils.cpp.o
[  3%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/reduce.cc.o
[  3%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/verbose.cpp.o
[  3%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/cpu_barrier.cpp.o
[  3%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/common.cc.o
[  3%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/int128.cc.o
[  3%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/generated_message_util.cc.o
[  3%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/cpu_batch_normalization_utils.cpp.o
[  3%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/io_win32.cc.o
[  3%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/once.cc.o
[  3%] Linking CXX static library ../../../lib/libgtest.a
[  3%] Built target gtest
[  3%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/scatter.cc.o
Scanning dependencies of target c10
[  3%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/colorprint.cc.o
[  4%] Building CXX object c10/CMakeFiles/c10.dir/Device.cpp.o
[  4%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/commandlineflags.cc.o
[  4%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/status.cc.o
[  4%] Building CXX object c10/CMakeFiles/c10.dir/DeviceType.cpp.o
[  4%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/cpu_concat.cpp.o
[  5%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/complexity.cc.o
[  5%] Building CXX object c10/CMakeFiles/c10.dir/Half.cpp.o
[  5%] Building CXX object c10/CMakeFiles/c10.dir/Stream.cpp.o
[  5%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/io/coded_stream.cc.o
[  5%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/types.cc.o
[  5%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/statusor.cc.o
[  5%] Building CXX object c10/CMakeFiles/c10.dir/core/Allocator.cpp.o
[  5%] Building CXX object c10/CMakeFiles/c10.dir/core/Scalar.cpp.o
[  6%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/common/linux.cc.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/core/Storage.cpp.o
[  6%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/console_reporter.cc.o
[  6%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/stringpiece.cc.o
[  6%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/io/zero_copy_stream.cc.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/core/StorageImpl.cpp.o
[  6%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/cpu_engine.cpp.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/core/TensorTypeId.cpp.o
[  6%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/io/zero_copy_stream_impl_lite.cc.o
[  6%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/counter.cc.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/core/TensorTypeIdRegistration.cpp.o
[  6%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/stringprintf.cc.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/core/dispatch/DeviceId.cpp.o
[  6%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/common/logging.cc.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/core/dispatch/DispatchKey.cpp.o
[  6%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/cpu_reducer.cpp.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/core/dispatch/DispatchTable.cpp.o
[  6%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/structurally_valid.cc.o
[  6%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/csv_reporter.cc.o
[  6%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/message_lite.cc.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/core/dispatch/Dispatcher.cpp.o
[  6%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/mpi/context.cc.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/core/dispatch/KernelRegistration.cpp.o
[  6%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/strutil.cc.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/core/dispatch/LayoutId.cpp.o
[  6%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/json_reporter.cc.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/core/dispatch/OpSchema.cpp.o
[  6%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/repeated_field.cc.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/core/dispatch/OpSchemaRegistration.cpp.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/impl/DeviceGuardImplInterface.cpp.o
[  6%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/atomicops_internals_x86_gcc.cc.o
[  6%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/reporter.cc.o
[  6%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/rendezvous/context.cc.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/util/Array.cpp.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/util/Backtrace.cpp.o
[  6%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/atomicops_internals_x86_msvc.cc.o
[  6%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/stubs/time.cc.o
[  6%] Building CXX object c10/CMakeFiles/c10.dir/util/C++17.cpp.o
[  6%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/cpu_reorder.cpp.o
[  6%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/sleep.cc.o
[  7%] Building CXX object c10/CMakeFiles/c10.dir/util/Exception.cpp.o
[  7%] Building CXX object c10/CMakeFiles/c10.dir/util/LeftRight.cpp.o
[  7%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/bytestream.cc.o
[  7%] Building CXX object c10/CMakeFiles/c10.dir/util/Logging.cpp.o
[  7%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/wire_format_lite.cc.o
[  7%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/rendezvous/file_store.cc.o
[  7%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/statistics.cc.o
[  7%] Building CXX object c10/CMakeFiles/c10.dir/util/Metaprogramming.cpp.o
[  7%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/common.cc.o
[  7%] Building CXX object c10/CMakeFiles/c10.dir/util/Optional.cpp.o
[  7%] Building CXX object c10/CMakeFiles/c10.dir/util/SmallVector.cpp.o
[  7%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/rendezvous/hash_store.cc.o
[  7%] Building CXX object c10/CMakeFiles/c10.dir/util/StringUtil.cpp.o
[  7%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/any.cc.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/int128.cc.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/io_win32.cc.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/once.cc.o
[  8%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/string_util.cc.o
[  8%] Building CXX object c10/CMakeFiles/c10.dir/util/Type.cpp.o
[  8%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/rendezvous/prefix_store.cc.o
[  8%] Building CXX object c10/CMakeFiles/c10.dir/util/TypeList.cpp.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/status.cc.o
[  8%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/rendezvous/store.cc.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/any.pb.cc.o
[  8%] Building CXX object c10/CMakeFiles/c10.dir/util/TypeTraits.cpp.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/statusor.cc.o
[  8%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/address.cc.o
[  8%] Building CXX object c10/CMakeFiles/c10.dir/util/UniqueVoidPtr.cpp.o
[  8%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/sysinfo.cc.o
[  8%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/buffer.cc.o
[  8%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/context.cc.o
[  8%] Building CXX object c10/CMakeFiles/c10.dir/util/flags_use_gflags.cpp.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/stringpiece.cc.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/stringprintf.cc.o
[  8%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/device.cc.o
[  8%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/pair.cc.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/api.pb.cc.o
[  8%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/unbound_buffer.cc.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/structurally_valid.cc.o
[  8%] Building CXX object c10/CMakeFiles/c10.dir/util/flags_use_no_gflags.cpp.o
[  8%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/tcp/address.cc.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/strutil.cc.o
[  8%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/timers.cc.o
[  8%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/tcp/buffer.cc.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/time.cc.o
[  8%] Building CXX object c10/CMakeFiles/c10.dir/util/intrusive_ptr.cpp.o
[  8%] Linking CXX static library ../../../lib/libbenchmark.a
[  8%] Built target benchmark
Scanning dependencies of target python_copy_files
[  8%] Building CXX object c10/CMakeFiles/c10.dir/util/typeid.cpp.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/wire_format_lite.cc.o
[  8%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/tcp/context.cc.o
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/compiler/importer.cc.o
[  9%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/compiler/parser.cc.o
[  9%] Linking CXX shared library ../lib/libc10.so
[  9%] Built target c10
[  9%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/descriptor.cc.o
[  9%] Linking CXX static library ../../../lib/libprotobuf-lite.a
[  9%] Built target libprotobuf-lite
[  9%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/descriptor.pb.cc.o
[  9%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o
[  9%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/descriptor_database.cc.o
[  9%] Built target python_copy_files
Scanning dependencies of target ATEN_CPU_FILES_GEN_TARGET
[  9%] Generating ../aten/src/ATen/CPUByteType.cpp, ../aten/src/ATen/CPUByteType.h, ../aten/src/ATen/CPUCharType.cpp, ../aten/src/ATen/CPUCharType.h, ../aten/src/ATen/CPUDoubleType.cpp, ../aten/src/ATen/CPUDoubleType.h, ../aten/src/ATen/CPUFloatType.cpp, ../aten/src/ATen/CPUFloatType.h, ../aten/src/ATen/CPUGenerator.h, ../aten/src/ATen/CPUHalfType.cpp, ../aten/src/ATen/CPUHalfType.h, ../aten/src/ATen/CPUIntType.cpp, ../aten/src/ATen/CPUIntType.h, ../aten/src/ATen/CPULongType.cpp, ../aten/src/ATen/CPULongType.h, ../aten/src/ATen/CPUShortType.cpp, ../aten/src/ATen/CPUShortType.h, ../aten/src/ATen/Declarations.yaml, ../aten/src/ATen/Functions.h, ../aten/src/ATen/LegacyTHDispatcher.h, ../aten/src/ATen/NativeFunctions.h, ../aten/src/ATen/RegisterCPU.cpp, ../aten/src/ATen/RegisterCPU.h, ../aten/src/ATen/SparseCPUByteType.cpp, ../aten/src/ATen/SparseCPUByteType.h, ../aten/src/ATen/SparseCPUCharType.cpp, ../aten/src/ATen/SparseCPUCharType.h, ../aten/src/ATen/SparseCPUDoubleType.cpp, ../aten/src/ATen/SparseCPUDoubleType.h, ../aten/src/ATen/SparseCPUFloatType.cpp, ../aten/src/ATen/SparseCPUFloatType.h, ../aten/src/ATen/SparseCPUIntType.cpp, ../aten/src/ATen/SparseCPUIntType.h, ../aten/src/ATen/SparseCPULongType.cpp, ../aten/src/ATen/SparseCPULongType.h, ../aten/src/ATen/SparseCPUShortType.cpp, ../aten/src/ATen/SparseCPUShortType.h, ../aten/src/ATen/TypeDefault.cpp, ../aten/src/ATen/TypeDefault.h, ../aten/src/ATen/TypeExtendedInterface.h, ../aten/src/ATen/CUDAByteType.cpp, ../aten/src/ATen/CUDAByteType.h, ../aten/src/ATen/CUDACharType.cpp, ../aten/src/ATen/CUDACharType.h, ../aten/src/ATen/CUDADoubleType.cpp, ../aten/src/ATen/CUDADoubleType.h, ../aten/src/ATen/CUDAFloatType.cpp, ../aten/src/ATen/CUDAFloatType.h, ../aten/src/ATen/CUDAGenerator.h, ../aten/src/ATen/CUDAHalfType.cpp, ../aten/src/ATen/CUDAHalfType.h, ../aten/src/ATen/CUDAIntType.cpp, ../aten/src/ATen/CUDAIntType.h, ../aten/src/ATen/CUDALongType.cpp, ../aten/src/ATen/CUDALongType.h, ../aten/src/ATen/CUDAShortType.cpp, ../aten/src/ATen/CUDAShortType.h, ../aten/src/ATen/RegisterCUDA.cpp, ../aten/src/ATen/RegisterCUDA.h, ../aten/src/ATen/SparseCUDAByteType.cpp, ../aten/src/ATen/SparseCUDAByteType.h, ../aten/src/ATen/SparseCUDACharType.cpp, ../aten/src/ATen/SparseCUDACharType.h, ../aten/src/ATen/SparseCUDADoubleType.cpp, ../aten/src/ATen/SparseCUDADoubleType.h, ../aten/src/ATen/SparseCUDAFloatType.cpp, ../aten/src/ATen/SparseCUDAFloatType.h, ../aten/src/ATen/SparseCUDAIntType.cpp, ../aten/src/ATen/SparseCUDAIntType.h, ../aten/src/ATen/SparseCUDALongType.cpp, ../aten/src/ATen/SparseCUDALongType.h, ../aten/src/ATen/SparseCUDAShortType.cpp, ../aten/src/ATen/SparseCUDAShortType.h
[  9%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/tcp/pair.cc.o
[  9%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/cpu_sum.cpp.o
[  9%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm_convolution.cpp.o
[  9%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm_convolution_utils.cpp.o
[  9%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm_inner_product.cpp.o
[  9%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/tcp/unbound_buffer.cc.o
[  9%] Linking CXX static library ../../../lib/libgloo.a
[  9%] Built target gloo
Scanning dependencies of target common
[  9%] Building C object sleef/src/common/CMakeFiles/common.dir/common.c.o
[  9%] Built target common
Scanning dependencies of target mkrename
[  9%] Building C object sleef/src/libm/CMakeFiles/mkrename.dir/mkrename.c.o
[  9%] Linking C executable ../../bin/mkrename
[  9%] Built target mkrename
Scanning dependencies of target mkdisp
[  9%] Building C object sleef/src/libm/CMakeFiles/mkdisp.dir/mkdisp.c.o
[  9%] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/cpu/gemm_u8s8s32x_convolution.cpp.o
[  9%] Linking C executable ../../bin/mkdisp
[  9%] Built target mkdisp
Scanning dependencies of target renamedsp256.h_generated
[  9%] Generating renamedsp256.h
[  9%] Built target renamedsp256.h_generated
Scanning dependencies of target headers
[  9%] Generating ../../../include/sleef.h
Generating sleef.h: mkrename 2 4 __m128d __m128 __m128i __m128i __SSE2__
Generating sleef.h: mkrename 2 4 __m128d __m128 __m128i __m128i __SSE2__ sse2
Generating sleef.h: mkrename 2 4 __m128d __m128 __m128i __m128i __SSE2__ sse4
Generating sleef.h: mkrename 4 8 __m256d __m256 __m128i struct\ {\ __m128i\ x,\ y;\ } __AVX__
Generating sleef.h: mkrename 4 8 __m256d __m256 __m128i struct\ {\ __m128i\ x,\ y;\ } __AVX__ avx
Generating sleef.h: mkrename 4 8 __m256d __m256 __m128i struct\ {\ __m128i\ x,\ y;\ } __AVX__ fma4
Generating sleef.h: mkrename 4 8 __m256d __m256 __m128i __m256i __AVX__ avx2
Generating sleef.h: mkrename 2 4 __m128d __m128 __m128i __m128i __SSE2__ avx2128
Generating sleef.h: mkrename 8 16 __m512d __m512 __m256i __m512i __AVX512F__
Generating sleef.h: mkrename 8 16 __m512d __m512 __m256i __m512i __AVX512F__ avx512f
[  9%] Generating include/renameavx2.h
Generating renameavx2.h: mkrename 4 8 avx2
[ 10%] Generating include/renameavx2128.h
Generating renameavx2128.h: mkrename 2 4 avx2128
[ 10%] Generating include/renamefma4.h
Generating renamefma4.h: mkrename 4 8 fma4
[ 10%] Generating include/renameavx.h
Generating renameavx.h: mkrename 4 8 avx
[ 10%] Generating include/renamesse4.h

...
...


[ 20%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/cpp/cpp_map_field.cc.o
[ 20%] Built target c10_registry_test
Scanning dependencies of target c10_OpSchema_test
[ 20%] Building CXX object c10/test/CMakeFiles/c10_OpSchema_test.dir/dispatch/OpSchema_test.cpp.o
[ 20%] Linking CXX executable ../../bin/c10_OpSchema_test
[ 20%] Built target c10_OpSchema_test
Scanning dependencies of target c10_InlineDeviceGuard_test
[ 21%] Building CXX object c10/test/CMakeFiles/c10_InlineDeviceGuard_test.dir/impl/InlineDeviceGuard_test.cpp.o
[ 21%] Linking CXX executable ../../bin/c10_InlineStreamGuard_test
[ 21%] Built target c10_InlineStreamGuard_test
Scanning dependencies of target c10_StreamGuard_test
[ 21%] Building CXX object c10/test/CMakeFiles/c10_StreamGuard_test.dir/StreamGuard_test.cpp.o
[ 21%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/cpp/cpp_message.cc.o
Skipping _th_multinomial Because of Arg: Generator * (Generator*) 
Skipping _th_normal Because of Arg: Generator * (Generator*) 
Skipping _th_normal Because of Arg: Generator * (Generator*) 
Skipping _th_normal Because of Arg: Generator * (Generator*) 
Skipping _th_tensor Because of Arg: Storage (Storage) 
Skipping _th_tensor Because of Arg: Storage (Storage) 
Skipping _thnn_rrelu_with_noise Because of Arg: Generator * (Generator*) 
Skipping _thnn_rrelu_with_noise_forward Because of Arg: Generator * (Generator*) 
[ 21%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/cpp/cpp_message_field.cc.o
Skipping _thnn_conv_transpose2d_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping _thnn_conv_transpose3d_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping _thnn_conv2d_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping _thnn_conv_depthwise2d_backward Because of Arg: std::array<bool,2> (std::array<bool,2>) 
Skipping _thnn_conv3d_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping _thnn_conv_dilated2d_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping _thnn_conv_dilated3d_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping _cudnn_rnn_backward Because of Arg: std::array<bool,4> (std::array<bool,4>) 
Skipping _cudnn_init_dropout_state because it is a factory method
Skipping _fused_dropout Because of Arg: Generator * (Generator *) 
Skipping arange because it is a factory method
Skipping bartlett_window because it is a factory method
Skipping bernoulli Because of Arg: Generator * (Generator *) 
Skipping bernoulli Because of Arg: Generator * (Generator *) 
Skipping blackman_window because it is a factory method
Skipping clamp Because of Arg: c10::optional<Scalar> (Scalar) 
Skipping clamp Because of Arg: c10::optional<Scalar> (Scalar) 
Skipping _convolution_double_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping cudnn_convolution_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping cudnn_convolution_transpose_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping cumsum Because of Arg: ScalarType (ScalarType) 
Skipping cumprod Because of Arg: ScalarType (ScalarType) 
Skipping einsum Because of Arg: std::string (std::string) 
Skipping empty because it is a factory method
Skipping empty_like because it is a factory method
Skipping empty_strided because it is a factory method
Skipping eye because it is a factory method
Skipping full because it is a factory method
Skipping full_like because it is a factory method
Skipping hann_window because it is a factory method
Skipping hamming_window because it is a factory method
Skipping _cufft_set_plan_cache_max_size Because of Ret: void (void)
Skipping _cufft_clear_plan_cache Because of Ret: void (void)
Skipping linspace because it is a factory method
Skipping logspace because it is a factory method
Skipping log_softmax Because of Arg: ScalarType (ScalarType) 
Skipping mean Because of Arg: ScalarType (ScalarType) 
Skipping mean Because of Arg: ScalarType (ScalarType) 
Skipping mean Because of Arg: ScalarType (ScalarType) 
Skipping mkldnn_convolution_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping miopen_convolution_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping miopen_convolution_transpose_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping native_batch_norm_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping ones because it is a factory method
Skipping ones_like because it is a factory method
Skipping rand because it is a factory method
Skipping rand_like because it is a factory method
Skipping randint because it is a factory method
Skipping randint_like because it is a factory method
Skipping randn because it is a factory method
Skipping randn_like because it is a factory method
Skipping randperm because it is a factory method
Skipping range because it is a factory method
Skipping rrelu Because of Arg: Generator * (Generator *) 
Skipping softmax Because of Arg: ScalarType (ScalarType) 
Skipping sum Because of Arg: ScalarType (ScalarType) 
Skipping sum Because of Arg: ScalarType (ScalarType) 
Skipping sum Because of Arg: ScalarType (ScalarType) 
Skipping prod Because of Arg: ScalarType (ScalarType) 
Skipping prod Because of Arg: ScalarType (ScalarType) 
Skipping prod Because of Arg: ScalarType (ScalarType) 
Skipping zeros because it is a factory method
Skipping zeros_like because it is a factory method
Skipping _standard_gamma Because of Arg: Generator * (Generator *) 
Skipping poisson Because of Arg: Generator * (Generator *) 
Skipping _sparse_sum Because of Arg: ScalarType (ScalarType) 
Skipping _sparse_sum Because of Arg: ScalarType (ScalarType) 
Skipping sparse_coo_tensor because it is a factory method
Skipping _sparse_coo_tensor_unsafe because it is a factory method
Skipping _sparse_coo_tensor_with_dims because it is a factory method
Skipping _sparse_coo_tensor_with_dims_and_tensors because it is a factory method
Skipping sparse_mask Because of Arg: SparseTensorRef (SparseTensorRef) 
Skipping to because it is a factory method
Skipping data_ptr Because of Ret: void* (void*)
Skipping multinomial Because of Arg: Generator * (Generator *) 
Skipping normal Because of Arg: Generator * (Generator *) 
Skipping normal Because of Arg: Generator * (Generator *) 
Skipping normal Because of Arg: Generator * (Generator *) 
Skipping rrelu_with_noise Because of Arg: Generator * (Generator *) 
Skipping thnn_conv_transpose2d_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping thnn_conv_transpose3d_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping thnn_conv2d_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping thnn_conv_depthwise2d_backward Because of Arg: std::array<bool,2> (std::array<bool,2>) 
Skipping thnn_conv3d_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping thnn_conv_dilated2d_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
Skipping thnn_conv_dilated3d_backward Because of Arg: std::array<bool,3> (std::array<bool,3>) 
[ 21%] Linking CXX executable ../../bin/c10_StreamGuard_test
[ 21%] Built target __aten_op_header_gen
[ 21%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/cpp/cpp_padding_optimizer.cc.o
[ 21%] Built target c10_StreamGuard_test
Scanning dependencies of target c10_DeviceGuard_test
[ 21%] Building CXX object c10/test/CMakeFiles/c10_DeviceGuard_test.dir/DeviceGuard_test.cpp.o
[ 21%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/cpp/cpp_primitive_field.cc.o
[ 21%] Linking CXX executable ../../bin/c10_InlineDeviceGuard_test
[ 21%] Built target c10_InlineDeviceGuard_test
Scanning dependencies of target c10_Half_test
[ 21%] Building CXX object c10/test/CMakeFiles/c10_Half_test.dir/util/Half_test.cpp.o

....
.....

.dir/__/aten/src/ATen/native/cudnn/GridSampler.cpp.o
[ 73%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/LossCTC.cpp.o
[ 73%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/RNN.cpp.o
[ 73%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/miopen/BatchNorm_miopen.cpp.o
[ 73%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/miopen/Conv_miopen.cpp.o
In file included from /usr/local/cuda/include/channel_descriptor.h:62:0,
                 from /usr/local/cuda/include/cuda_runtime.h:90,
                 from /usr/include/cudnn.h:64,
                 from /home/bg/pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:3,
                 from /home/bg/pytorch/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp:28:
/usr/local/cuda/include/cuda_runtime_api.h:1701:101: error: use of enum ‘cudaDeviceP2PAttr’ without previous declaration
 extern __host__ __cudart_builtin__ cudaError_t CUDARTAPI cudaDeviceGetP2PAttribute(int *value, enum cudaDeviceP2PAttr attr, int srcDevice, int dstDevice);
                                                                                                     ^
/usr/local/cuda/include/cuda_runtime_api.h:2952:102: error: use of enum ‘cudaFuncAttribute’ without previous declaration
 extern __host__ __cudart_builtin__ cudaError_t CUDARTAPI cudaFuncSetAttribute(const void *func, enum cudaFuncAttribute attr, int value);
                                                                                                      ^
In file included from /usr/local/cuda/include/channel_descriptor.h:62:0,
                 from /usr/local/cuda/include/cuda_runtime.h:90,
                 from /usr/include/cudnn.h:64,
                 from /home/bg/pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:3,
                 from /home/bg/pytorch/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp:28:
/usr/local/cuda/include/cuda_runtime_api.h:5821:92: error: use of enum ‘cudaMemoryAdvise’ without previous declaration
 extern __host__ cudaError_t CUDARTAPI cudaMemAdvise(const void *devPtr, size_t count, enum cudaMemoryAdvise advice, int device);
                                                                                            ^
/usr/local/cuda/include/cuda_runtime_api.h:5878:98: error: use of enum ‘cudaMemRangeAttribute’ without previous declaration
 extern __host__ cudaError_t CUDARTAPI cudaMemRangeGetAttribute(void *data, size_t dataSize, enum cudaMemRangeAttribute attribute, const void *devPtr, size_t count);
                                                                                                  ^
/usr/local/cuda/include/cuda_runtime_api.h:5915:102: error: use of enum ‘cudaMemRangeAttribute’ without previous declaration
 extern __host__ cudaError_t CUDARTAPI cudaMemRangeGetAttributes(void **data, size_t *dataSizes, enum cudaMemRangeAttribute *attributes, size_t numAttributes, const void *devPtr,
                                                                                                      ^
[ 73%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/sparse/cuda/SparseCUDATensor.cpp.o
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:200198: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:5048: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn --use-qnnpack caffe2'

```

**Comment by BIGBALLON** [comment]
I downgraded cudnn from 7.4.1 to 7.3.0, then it works..

**Comment by marcosmacedo** [comment]
> I downgraded cudnn from 7.4.1 to 7.3.0, then it works..

I had cudnn 7.6 and downgrading solved the issue. Thank you.
