### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device RTX5090D

### ISSUE THREAD

**Issue by yourbikun** [pytorch/pytorch#149845]
### 🐛 Describe the bug

I encountered problems when running PyTorch on an RTX 5090D in Ubuntu. I installed PyTorch (torch) and CUDA in a Conda environment, and the following issues occurred:

>>> import torch
>>> x = torch.tensor([0, 1, 1]).to(0)
>>> print(x.device)
cuda:0
>>> x != 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Versions

pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

**Comment by yourbikun** [comment]
Okay, it seems to be my own problem. I uninstalled the current graphics card driver, installed the graphics card driver from the latest CUDA 12.8.1, installed cuDNN, and finally installed the pre - released version of PyTorch. The problem has been solved.
