### ISSUE TITLE
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#149984]
### 🐛 Describe the bug

Found followin nccl error when validating release 2.7 cherry-pick: 
https://github.com/pytorch/pytorch/pull/149874

This is repro script:
https://gist.github.com/d4l3k/16a19b475952bc40ddd7f2febcc297b7

Running on g5.12xlarge machine. 

Repro with Release 2.7 RC1 : 

Normally getting:
```
torchrun --nproc-per-node=2 test.py
starting
starting
connected
connected
synchronizing
aborting
aborting
synchronizing
synchronized
completed
synchronized
completed
````

However after few tries received following failure:
```
Collective WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1000000) raised the following async exception: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.25.1
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
Last error:

Exception raised from checkForNCCLErrorsInternal at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2501 (most recent call first):
C++ CapturedTraceback:
#4 std::_Function_handler<std::shared_ptr<c10::LazyValue<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const> (), c10::SetStackTraceFetcher(std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) from Logging.cpp:0
#5 c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) from ??:0
#6 c10::DistBackendError::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) from :0
#7 c10d::ProcessGroupNCCL::checkForNCCLErrorsInternal(std::shared_ptr<c10d::NCCLComm>&) from ??:0
#8 c10d::ProcessGroupNCCL::WorkNCCL::checkAndSetException() from ??:0
#9 c10d::ProcessGroupNCCL::WorkNCCL::isStarted() from ??:0
#10 c10d::ProcessGroupNCCL::watchdogHandler() from ??:0
#11 c10d::ProcessGroupNCCL::ncclCommWatchdog() from ??:0
#12 execute_native_thread_routine from /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/src/c++11/thread.cc:82
#13 start_thread from ??:0
#14 __GI___clone from :0
```

Same issue with nightly and nccl 2.26.2:
```
 NCCL_DEBUG=WARN torchrun --nproc-per-node=2 test.py
/opt/conda/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:276: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
W0325 20:46:43.725000 94 site-packages/torch/distributed/run.py:766] 
W0325 20:46:43.725000 94 site-packages/torch/distributed/run.py:766] *****************************************
W0325 20:46:43.725000 94 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0325 20:46:43.725000 94 site-packages/torch/distributed/run.py:766] *****************************************
/opt/conda/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:276: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
/opt/conda/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:276: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
[W325 20:46:45.052437495 TCPStore.cpp:297] [c10d] Starting store with 1000000 workers but somaxconn is 4096.This might cause instability during bootstrap, consider increasing it.
starting
starting
NCCL version 2.26.2+cuda12.2
connected
connected
synchronizing
aborting
aborting
synchronizing
synchronized
completed
synchronized
completed
[W325 20:46:51.073905063 Module.cpp:186] symbolizing C++ stack trace for exception; if this hangs, rerun with TORCH_DISABLE_ADDR2LINE=1...
[E325 20:46:51.228036986 ProcessGroupNCCL.cpp:555] [Rank 1] Collective WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1000000) raised the following async exception: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.26.2
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
Last error:
Exception raised from checkForNCCLErrorsInternal at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2474 (most recent call first):
C++ CapturedTraceback:
#4 std::_Function_handler<std::shared_ptr<c10::LazyValue<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const> (), c10::SetStackTraceFetcher(std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) from Logging.cpp:0
#5 c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) from ??:0
#6 c10::DistBackendError::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) from :0
#7 c10d::ProcessGroupNCCL::checkForNCCLErrorsInternal(std::shared_ptr<c10d::NCCLComm>&) from ??:0
#8 c10d::ProcessGroupNCCL::WorkNCCL::checkAndSetException() from ??:0
#9 c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() from ??:0
#10 c10d::ProcessGroupNCCL::watchdogHandler() from ??:0
#11 c10d::ProcessGroupNCCL::ncclCommWatchdog() from ??:0
#12 execute_native_thread_routine from /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/src/c++11/thread.cc:82
#13 start_thread from ??:0
#14 __GI___clone from :0
```

Release 2.6 and nccl 2.21.5:
```
root@7be1ecef64c0 /]# NCCL_DEBUG=WARN torchrun --nproc-per-node=2 test.py
/opt/conda/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:275: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
W0325 21:16:42.796000 578 site-packages/torch/distributed/run.py:792] 
W0325 21:16:42.796000 578 site-packages/torch/distributed/run.py:792] *****************************************
W0325 21:16:42.796000 578 site-packages/torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0325 21:16:42.796000 578 site-packages/torch/distributed/run.py:792] *****************************************
/opt/conda/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:275: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
/opt/conda/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:275: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
[W325 21:16:44.104257883 TCPStore.cpp:280] [c10d] Starting store with 1000000 workers but somaxconn is 4096.This might cause instability during bootstrap, consider increasing it.
starting
starting
NCCL version 2.21.5+cuda12.4
connected
connected
synchronizing
aborting
aborting
synchronizing
synchronized
completed
synchronized
completed
[W325 21:16:50.611596175 Module.cpp:182] symbolizing C++ stack trace for exception; if this hangs, rerun with TORCH_DISABLE_ADDR2LINE=1...
[E325 21:16:50.765246490 ProcessGroupNCCL.cpp:552] [Rank 0] Collective WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1000000, NumelOut=1000000, Timeout(ms)=1000000) raised the following async exception: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.21.5
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
Last error:
Exception raised from checkForNCCLErrorsInternal at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2363 (most recent call first):
C++ CapturedTraceback:
#4 std::_Function_handler<std::shared_ptr<c10::LazyValue<std::string> const> (), c10::SetStackTraceFetcher(std::function<std::string ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) from Logging.cpp:0
#5 c10::Error::Error(c10::SourceLocation, std::string) from ??:0
#6 c10d::ProcessGroupNCCL::checkForNCCLErrorsInternal(std::shared_ptr<c10d::NCCLComm>&) from ??:0
#7 c10d::ProcessGroupNCCL::WorkNCCL::checkAndSetException() from ??:0
#8 c10d::ProcessGroupNCCL::WorkNCCL::isStarted() from ??:0
#9 c10d::ProcessGroupNCCL::watchdogHandler() from ??:0
#10 c10d::ProcessGroupNCCL::ncclCommWatchdog() from ??:0
#11 execute_native_thread_routine from thread48.o:0
#12 start_thread from ??:0
#13 __GI___clone from :0
```

### Versions

nightly 2.8

**Comment by atalman** [comment]
Nvidia-smi output:
```
nvidia-smi
Tue Mar 25 21:45:58 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.05             Driver Version: 550.127.05     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A10G                    On  |   00000000:00:1B.0 Off |                    0 |
|  0%   19C    P8             15W /  300W |       1MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A10G                    On  |   00000000:00:1C.0 Off |                    0 |
|  0%   19C    P8             15W /  300W |       1MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA A10G                    On  |   00000000:00:1D.0 Off |                    0 |
|  0%   20C    P8             15W /  300W |       1MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA A10G                    On  |   00000000:00:1E.0 Off |                    0 |
|  0%   19C    P8             15W /  300W |       1MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by atalman** [comment]
For nightly version, this is Linux x86 : NCCL version 2.26.2+cuda12.2

**Comment by H-Huang** [comment]
Does `NCCL_DEBUG=INFO` give more info about what the error is in nccl? I don't have the correct nccl/cuda versions on my machine to repro it, the script works for me (but I am using pretty old versions). cc @d4l3k

**Comment by atalman** [comment]
Hi @H-Huang have you tried executing this script sequentially few time in a row ? This is how I was able to repro it. If I run once or twice it usually passes.
