### ISSUE TITLE
Pytorch nightly Cuda 12.8 - 'too many resources requested for launch' with multiple layers of LayerNorm after strided Conv1d

### ISSUE THREAD

**Issue by Pyr-000** [pytorch/pytorch#150266]
### 🐛 Describe the bug

The current pytorch nightly build for CUDA 12.8: `2.8.0.dev20250327+cu128` yields the following error:
`RuntimeError: CUDA error: too many resources requested for launch`
When running a backward pass through a model with multiple strided Conv1d modules followed by LayerNorm modules.

The error does not seem to occur when the Conv1d modules have their stride set to 1. The error does not seem to occur when only one strided Conv1d followed by one LayerNorm is used.

(The issue does not occur when setting the device to CPU or replacing the LayerNorm module with e.g. RMSNorm)

Running the following example script:
```python
import torch

class PermuteModule(torch.nn.Module):
    def __init__(self, permutation):
        super(PermuteModule, self).__init__()
        self.permutation = permutation
    def forward(self, x:torch.Tensor) -> torch.Tensor:
        assert len(x.shape) == len(self.permutation), f"Dimension mismatch! Unable to permute {len(x.shape)} dim input with a {len(self.permutation)} dim permutation!"
        return x.permute(*self.permutation)

def test(n_layers:int, conv_stride:int):
    _sequence = []
    for _ in range(n_layers):
        # Conv1d inputs are (N x C x L), LayerNorm expects (* x C). Dims must be permuted between modules.
        _sequence += [
            PermuteModule((0,2,1)),
            torch.nn.Conv1d(in_channels=512, out_channels=512, groups=1, kernel_size=9, dilation=1, stride=conv_stride, padding=0, bias=False),
            PermuteModule((0,2,1)),
            torch.nn.LayerNorm(512),
            torch.nn.ReLU()
        ]
    model = torch.nn.Sequential(*_sequence).to(device="cuda")
    data = torch.randn((100,2048,512), device="cuda")
    out = model(data)
    loss = torch.nn.functional.mse_loss(out, torch.rand_like(out))
    loss.backward()

torch.autograd.set_detect_anomaly(True)
print(f"Torch version: {torch.__version__}")

print(f"layers=1, stride=1")
test(n_layers=1, conv_stride=1)
print(f"layers=2, stride=1")
test(n_layers=2, conv_stride=1)
print(f"layers=1, stride=2")
test(n_layers=1, conv_stride=2)
print(f"layers=2, stride=2")
test(n_layers=2, conv_stride=2)

# we will not reach this print statement.
print("DONE.")

```

Yields the output:
```bash
Torch version: 2.8.0.dev20250327+cu128
layers=1, stride=1
layers=2, stride=1
layers=1, stride=2
layers=2, stride=2
C:\Applications\Python\Python312\Lib\site-packages\torch\autograd\graph.py:824: UserWarning: Error detected in NativeLayerNormBackward0. Traceback of forward call that caused the error:
  File "C:\TWD\sample.py", line 38, in <module>
    test(n_layers=2, conv_stride=2)
  File "C:\TWD\sample.py", line 24, in test
    out = model(data)
  File "C:\Applications\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Applications\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Applications\Python\Python312\Lib\site-packages\torch\nn\modules\container.py", line 240, in forward
    input = module(input)
  File "C:\Applications\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Applications\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Applications\Python\Python312\Lib\site-packages\torch\nn\modules\normalization.py", line 217, in forward
    return F.layer_norm(
  File "C:\Applications\Python\Python312\Lib\site-packages\torch\nn\functional.py", line 2910, in layer_norm
    return torch.layer_norm(
 (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\autograd\python_anomaly_mode.cpp:127.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "C:\TWD\sample.py", line 38, in <module>
    test(n_layers=2, conv_stride=2)
  File "C:\TWD\sample.py", line 26, in test
    loss.backward()
  File "C:\Applications\Python\Python312\Lib\site-packages\torch\_tensor.py", line 648, in backward
    torch.autograd.backward(
  File "C:\Applications\Python\Python312\Lib\site-packages\torch\autograd\__init__.py", line 353, in backward
    _engine_run_backward(
  File "C:\Applications\Python\Python312\Lib\site-packages\torch\autograd\graph.py", line 824, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: too many resources requested for launch
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Versions

PyTorch version: 2.8.0.dev20250327+cu128
Is debug build: False
CUDA used to build PyTorch: 12.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro for Workstations (10.0.26100 64-bit)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.26100-SP0
Is CUDA available: True
CUDA runtime version: 12.8.93
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 5090
Nvidia driver version: 572.83
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Name: AMD Ryzen 9 7950X3D 16-Core Processor
Manufacturer: AuthenticAMD
Family: 107
Architecture: 9
ProcessorType: 3
DeviceID: CPU0
CurrentClockSpeed: 4201
MaxClockSpeed: 4201
L2CacheSize: 16384
L2CacheSpeed: None
Revision: 24834

Versions of relevant libraries:
[pip3] numpy==2.2.0
[pip3] torch==2.8.0.dev20250327+cu128
[pip3] torchaudio==2.6.0.dev20250330+cu128
[pip3] torchvision==0.22.0.dev20250330+cu128
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @ptrblck @eqy

**Comment by clementiens** [comment]
same question

 File "E:\anaconda3\envs\zlopenmmlab\lib\site-packages\torch\autograd\graph.py", line 824, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: too many resources requested for launch
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

**Comment by clementiens** [comment]
same question，and the device is 5090.

File "E:\anaconda3\envs\zlopenmmlab\lib\site-packages\torch\autograd\graph.py", line 824, in _engine_run_backward
return Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: too many resources requested for launch
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

**Comment by xsktno1** [comment]
same question，my device is rtx 5090.

Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: too many resources requested for launch
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

**Comment by stefan-it** [comment]
Holy Blackwell, I can also reproduce that error. Not just with this script, but e.g. fine-tuning with Flair library caused the same error.

It was definitely working with PyTorch 2.7, as I've pretrained lot of models with Transformers library with that PyTorch version  on my 5090.

**Comment by stefan-it** [comment]
Quick workaround is to downgrade to PyTorch 2.7 - can be done with:

```
pip install --pre torch==2.7.0.dev20250312 --index-url https://download.pytorch.org/whl/nightly/cu128
```

Then the example script from that issue here is running.

**Comment by callbarian** [comment]
Same here.
downgrading to 2.7 worked for me.
@stefan-it 
Thanks

**Comment by xsktno1** [comment]
@stefan-it 
Thanks

**Comment by clementiens** [comment]
> Holy Blackwell, I can also reproduce that error. Not just with this script, but e.g. fine-tuning with Flair library caused the same error.
> 
> It was definitely working with PyTorch 2.7, as I've pretrained lot of models with Transformers library with that PyTorch version on my 5090, see my post on the Model Hub: https://huggingface.co/posts/stefan-it/989004577410802

thanks，it work for me!

**Comment by lordlugo** [comment]
> Quick workaround is to downgrade to PyTorch 2.7 - can be done with:
> 
> ```
> pip install --pre torch==2.7.0.dev20250312 --index-url https://download.pytorch.org/whl/nightly/cu128
> ```
> 
> Then the example script from that issue here is running.

Thanks !

**Comment by weyn9q** [comment]
> Quick workaround is to downgrade to PyTorch 2.7 - can be done with:
> 
> ```
> pip install --pre torch==2.7.0.dev20250312 --index-url https://download.pytorch.org/whl/nightly/cu128
> ```
> 
> Then the example script from that issue here is running.

thanks. worked for me as well

**Comment by drisspg** [comment]
This reproduces for me on B200

**Comment by drisspg** [comment]
Suspect it this PR: https://github.com/pytorch/pytorch/pull/148605
trying reverting this PR now

**Comment by ahmadsharif1** [comment]
@drisspg apologies for causing the breakage. I didn't test on Blackwell. I can add launch_bounds so the register usage goes down to the appropriate level. My kernel does have higher register usage because it uses higher ILP to achieve higher throughput.

**Comment by zou3519** [comment]
@drisspg was the PR in 2.7.0? If so we may need to do something about it

**Comment by ahmadsharif1** [comment]
Update: I re-submitted my PR with `__launch_bounds__` which should resolve the issue: https://github.com/pytorch/pytorch/pull/150625 (it will hopefully be merged soon)

Also: @zou3519 I didn't find my original PR on the origin/releases/2.7 branch so we are probably safe there?

**Comment by jang-hs** [comment]
> Suspect it this PR: [#148605](https://github.com/pytorch/pytorch/pull/148605) trying reverting this PR now
> 
> cc [@eqy](https://github.com/eqy) Yeah, reverting this locally fixes the problem
> 
> With the gamma beta update I see multiple template instantiations w/
> 
> ```
> ptxas info    : Compiling entry function '_ZN2at6native53_GLOBAL__N__6575d66f_20_layer_norm_kernel_cu_9c5ada8a35GammaBetaBackwardCUDAKernelTemplateIddLj32ELj1ELj32ELb1ELb0EEEvllPKT_S5_PKT0_S8_PS3_S9_' for 'sm_100a'
> ptxas info    : Function properties for _ZN2at6native53_GLOBAL__N__6575d66f_20_layer_norm_kernel_cu_9c5ada8a35GammaBetaBackwardCUDAKernelTemplateIddLj32ELj1ELj32ELb1ELb0EEEvllPKT_S5_PKT0_S8_PS3_S9_
>     384 bytes stack frame, 496 bytes spill stores, 548 bytes spill loads
> ptxas info    : Used 255 registers, used 0 barriers, 384 bytes cumulative stack size
> ptxas info    : Compile time = 184.971 ms
> ```
> 
> which is likely the cause

Hello, I'm encountering the same issue when using 8 B200 GPUs on a single node. Could you please let me know if you rebuilt PyTorch locally by reverting to a commit before PR #148605, and how you resolved the error? I'm currently using Python 3.10. Thank you.

**Comment by ahmadsharif1** [comment]
> [@drisspg](https://github.com/drisspg)
> 
> > Suspect it this PR: [#148605](https://github.com/pytorch/pytorch/pull/148605) trying reverting this PR now
> > cc [@eqy](https://github.com/eqy) Yeah, reverting this locally fixes the problem
> > With the gamma beta update I see multiple template instantiations w/
> > ```
> > ptxas info    : Compiling entry function '_ZN2at6native53_GLOBAL__N__6575d66f_20_layer_norm_kernel_cu_9c5ada8a35GammaBetaBackwardCUDAKernelTemplateIddLj32ELj1ELj32ELb1ELb0EEEvllPKT_S5_PKT0_S8_PS3_S9_' for 'sm_100a'
> > ptxas info    : Function properties for _ZN2at6native53_GLOBAL__N__6575d66f_20_layer_norm_kernel_cu_9c5ada8a35GammaBetaBackwardCUDAKernelTemplateIddLj32ELj1ELj32ELb1ELb0EEEvllPKT_S5_PKT0_S8_PS3_S9_
> >     384 bytes stack frame, 496 bytes spill stores, 548 bytes spill loads
> > ptxas info    : Used 255 registers, used 0 barriers, 384 bytes cumulative stack size
> > ptxas info    : Compile time = 184.971 ms
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which is likely the cause
> 
> Hello, I'm encountering the same issue when using 8 B200 GPUs on a single node. `RuntimeError: CUDA error: too many resources requested for launch` Could you please let me know if you rebuilt PyTorch locally by reverting to a commit before PR [#148605](https://github.com/pytorch/pytorch/pull/148605), and how you resolved the error? I'm currently using Python 3.10. Thank you.

Are you using the nightly build?

If you are building from source, including this commit should fix the issue: https://github.com/pytorch/pytorch/commit/c6defa9443d241dd7a0baac4e708b6e906bd012c.

**Comment by drisspg** [comment]
Closing as fixed now

**Comment by hammafm82** [comment]
(python) C:\Comfy\python\Scripts>python xx.py
tensor([0., 0., 0.], device='cuda:0')
If you see tensor([0., 0., 0.], device='cuda:0'), then it works

(python) C:\Comfy\python\Scripts>python xx.py
Torch version: 2.8.0.dev20250504+cu128
layers=1, stride=1
layers=2, stride=1
layers=1, stride=2
layers=2, stride=2
DONE.

[START] Security scan
[DONE] Security scan
[ComfyUI-Manager] Logging failed: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Comfy\\ComfyUI\\user\\comfyui.log' -> 'C:\\Comfy\\ComfyUI\\user\\comfyui.prev.log'
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-05-08 07:43:39.318
** Platform: Windows
** Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
** Python executable: C:\Comfy\python\Scripts\python.exe
** ComfyUI Path: C:\Comfy\ComfyUI
** ComfyUI Base Folder Path: C:\Comfy\ComfyUI
** User directory: C:\Comfy\ComfyUI\user
** ComfyUI-Manager config path: C:\Comfy\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: C:\Comfy\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Comfy\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Comfy\ComfyUI\custom_nodes\comfyui-easy-use
   3.2 seconds: C:\Comfy\ComfyUI\custom_nodes\comfyui-manager

Checkpoint files will always be loaded safely.
Total VRAM 12282 MB, total RAM 98230 MB
pytorch version: 2.8.0.dev20250504+cu128
xformers version: 0.0.31+8fc8ec5a.d20250503
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 SUPER : cudaMallocAsync
Using xformers attention
Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
ComfyUI version: 0.3.32
ComfyUI frontend version: 1.18.9
[Prompt Server] web root: C:\Comfy\python\Lib\site-packages\comfyui_frontend_package\static
