### ISSUE TITLE
fully_shard() for huggingface 72B model: pytorch caches too much GPU memory

### ISSUE THREAD

**Issue by mingdianliu** [pytorch/pytorch#151936]
Dear Community,

I'm working on fine-tuning the Qwen2-VL model using `fully_shard()` and wrote a script for it. However, it will run into OOM when I try to fine tune 72B model with 128 GPUs.

I found it is due to pytorch cache. The allocated and reserved GPU memory is quite small while the cached GPU memory is even higher than 50GB. I had a shoot on torch.cuda.empty_cache() after each training iteration but the GPU memory cache during each training iteration is also high (~20GB). I wonder if it is a bug of FSDP2. If not, is there any method that can mitigate this issue?

I'd really appreciate any insights or suggestions you might have. Thanks in advance!

### My code

```
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import Qwen2VLForConditionalGeneration, Qwen2VLProcessor, AutoModelForVision2Seq, AutoConfig
from qwen_vl_utils import process_vision_info
from peft import LoraConfig, get_peft_model
from datasets import load_dataset
import numpy as np
from PIL import Image
import io
import logging
import os

from torch.nn.parallel import DistributedDataParallel as DDP
import torch.distributed as dist
import torch.distributed.checkpoint as dcp
from torch.distributed.device_mesh import init_device_mesh
from transformers.models.qwen2_vl.modeling_qwen2_vl import Qwen2VLDecoderLayer, Qwen2VLVisionBlock
from torch.distributed._composable.fsdp import fully_shard
from torch.distributed import init_process_group, destroy_process_group
from torch.distributed.checkpoint import DefaultLoadPlanner, DefaultSavePlanner
from torch.distributed._composable.fsdp import (
    CPUOffloadPolicy,
    fully_shard,
    MixedPrecisionPolicy,
)


# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# init dist
distributed_backend = "nccl" # gloo for cpu
dist.init_process_group(distributed_backend)

local_rank = int(os.environ["LOCAL_RANK"])
world_size = int(os.environ["WORLD_SIZE"])
device = torch.device(f"cuda:{local_rank}")
torch.cuda.set_device(device)


# model_name = "Qwen/Qwen2-VL-2B-Instruct"
# revision = "895c3a49bc3fa70a340399125c650a463535e71c"
model_name = "Qwen/Qwen2-VL-7B-Instruct"
revision = "a28a094eb66a9f2ac70eef346f040d8a79977472"
# model_name = "Qwen/Qwen2-VL-72B-Instruct"
# revision = "f9b556a74d58e6d9915f73227c21045c87342b42"

dataset_id = "HuggingFaceM4/ChartQA"
processor = Qwen2VLProcessor.from_pretrained(model_name, 
                                             revision=revision,
                                             )


# Configuration
class Config:
    dataset_id = "HuggingFaceM4/ChartQA"
    output_dir = "/tmp_ckpt"
    batch_size = 2
    num_epochs = 3
    learning_rate = 5e-5
    max_seq_length = 512
    lora_rank = 32
    lora_alpha = 64
    lora_dropout = 0.1
    device = "cuda" if torch.cuda.is_available() else "cpu"




system_message = """You are a Vision Language Model specialized in interpreting visual data from chart images.
Your task is to analyze the provided chart image and respond to queries with concise answers, usually a single word, number, or short phrase.
The charts include a variety of types (e.g., line charts, bar charts) and contain colors, labels, and text.
Focus on delivering accurate, succinct answers based on the visual information. Avoid additional explanation unless absolutely necessary."""

def format_data(sample):
    return [
        {
            "role": "system",
            "content": [{"type": "text", "text": system_message}],
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": sample["image"],
                },
                {
                    "type": "text",
                    "text": sample["query"],
                },
            ],
        },
        {
            "role": "assistant",
            "content": [{"type": "text", "text": sample["label"][0]}],
        },
    ]

# Training function
def train_model(model, train_loader, optimizer, config):
    model.train()
    total_steps = len(train_loader) * config.num_epochs
    step = 0

    scaler = torch.amp.GradScaler("cuda", enabled=True)

    for epoch in range(config.num_epochs):
        total_loss = 0
        for batch_idx, batch in enumerate(train_loader):

            inputs, labels = batch
            inputs = inputs.to(config.device)
            labels = labels.to(config.device)

            # Mixed precision training
            loss = model(**inputs, labels=labels).loss
            loss.backward() # no scaler
            optimizer.step()
            optimizer.zero_grad()
            
            step += 1
            logger.info(f"Epoch {epoch+1}/{config.num_epochs}, Step {step}/{total_steps}, Loss: {loss.item():.4f}")

            del loss



# Create a data collator to encode text and image pairs
def collate_fn(examples):
    # Get the texts and images, and apply the chat template
    texts = [
        processor.apply_chat_template(example, tokenize=False) for example in examples
    ]  # Prepare texts for processing
    image_inputs = [process_vision_info(example)[0] for example in examples]  # Process the images to extract inputs

    # Tokenize the texts and process the images
    batch = processor(
        text=texts, images=image_inputs, return_tensors="pt", padding=True
    )  # Encode texts and images into tensors

    # The labels are the input_ids, and we mask the padding tokens in the loss computation
    labels = batch["input_ids"].clone()  # Clone input IDs for labels
    labels[labels == processor.tokenizer.pad_token_id] = -100  # Mask padding tokens in labels

    # Ignore the image token index in the loss computation (model specific)
    if isinstance(processor, Qwen2VLProcessor):  # Check if the processor is Qwen2VLProcessor
        image_tokens = [151652, 151653, 151655]  # Specific image token IDs for Qwen2VLProcessor
    else:
        image_tokens = [processor.tokenizer.convert_tokens_to_ids(processor.image_token)]  # Convert image token to ID

    # Mask image token IDs in the labels
    for image_token_id in image_tokens:
        labels[labels == image_token_id] = -100  # Mask image token IDs in labels

    return batch, labels



# Main function
def main():

    config = Config()

    # Load model and processor
    logger.info("Loading model and processor...")

    hf_config = AutoConfig.from_pretrained(
                model_name, 
                revision=revision, 
                torch_dtype=torch.bfloat16,
                attn_implementation="flash_attention_2",
                )

    with torch.device("meta"):
        model = AutoModelForVision2Seq.from_config(hf_config, torch_dtype=torch.bfloat16)

    mp_policy=MixedPrecisionPolicy(param_dtype=torch.bfloat16, 
                                   reduce_dtype=torch.bfloat16, 
                                   output_dtype=torch.bfloat16, 
                                   cast_forward_inputs=True)
    offload_policy = CPUOffloadPolicy(pin_memory=False)

    # apply FSDP2
    device_mesh = init_device_mesh("cuda", (world_size,))
    for module in model.modules():
        if isinstance(module, Qwen2VLDecoderLayer):
            fully_shard(module, 
                        mesh=device_mesh, 
                        reshard_after_forward=True,
                        mp_policy=mp_policy,
                        # offload_policy=offload_policy,
                        )
    
    model = fully_shard(model, 
                        mesh=device_mesh, 
                        reshard_after_forward=True,
                        mp_policy=mp_policy,
                        # offload_policy=offload_policy,
                        )

    model.to_empty(device='cuda')

    model_state_dict = model.state_dict()

    model_dir = "/cache/fsdp_test/72B_8_files"

    # load qwen2-vl model
    dcp.load(
        state_dict=model_state_dict,
        checkpoint_id=model_dir,
        planner=DefaultLoadPlanner(allow_partial_load=True),
    )

    model = model.to(torch.bfloat16).cuda()
    

    # Load dataset
    logger.info("Loading dataset...")

    train_dataset, eval_dataset, test_dataset = load_dataset(
        config.dataset_id, split=['train[:10%]', 'val[:10%]', 'test[:10%]'])
    train_dataset = [format_data(sample) for sample in train_dataset]

    train_dataloader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=1,
        collate_fn=collate_fn,
        shuffle=True,
    )

    # Optimizer
    optimizer = torch.optim.AdamW(model.parameters(), lr=config.learning_rate)

    # Create output directory
    os.makedirs(config.output_dir, exist_ok=True)

    # Train
    logger.info("Starting training...")
    train_model(model, train_dataloader, optimizer, config)


if __name__ == "__main__":
    main()
    destroy_process_group()
    logger.info("Training completed.")
```

### Running command
`torchrun --nnodes=2 --nproc_per_node=8 qwenvl_train_fsdp.py`
`torchrun --nnodes=4 --nproc_per_node=8 qwenvl_train_fsdp.py`
`torchrun --nnodes=8 --nproc_per_node=8 qwenvl_train_fsdp.py`

### GPU memory monitor
The following is the screenshot of the result of `nvidia-smi`:

16 GPU:

![Image](https://github.com/user-attachments/assets/be24d977-156b-438c-a8d4-be61b26b4d57)

32 GPU:

![Image](https://github.com/user-attachments/assets/4b8f1ea9-150d-44f8-8ab4-c9a26c3dcd43)

64 GPU:

![Image](https://github.com/user-attachments/assets/45f3d7cb-b8bc-4044-a6f4-882c708aaf9c)

**Comment by fduwjj** [comment]
cc: @weifengpy

**Comment by mingdianliu** [comment]
Dear @weifengpy 

Thanks for your follow-up. I print the allocated/reserved memory at the end of training iteration. I found the cached GPU memory is partially due to the varying data sequence. I also tried to duplicate the first data as the training dataset. However, I  found this code will still run into OOM for 72B model with 32 GPUs. 

Looking forward to your insight. I will post the update here as long as I have some results.


### Converting safesensor to DCP

```
# -*- coding: utf-8 -*-
# Copyright (c) 2023-2025, Songlin Yang, Yu Zhang

import argparse
from pathlib import Path

import torch
import torch.distributed.checkpoint as DCP
from transformers import AutoModelForCausalLM

from transformers import (  # type: ignore
    AutoConfig,
    Qwen2VLForConditionalGeneration,
)


# model_name = "Qwen/Qwen2-VL-2B-Instruct"
# revision = "895c3a49bc3fa70a340399125c650a463535e71c"
# model_dir = "/cache/hf_cache/hub/models--Qwen--Qwen2-VL-2B-Instruct/snapshots/895c3a49bc3fa70a340399125c650a463535e71c"
# model_name = "Qwen/Qwen2-VL-7B-Instruct"
# revision = "a28a094eb66a9f2ac70eef346f040d8a79977472"
# model_dir = "/cache/hf_cache/hub/models--Qwen--Qwen2-VL-7B-Instruct/snapshots/a28a094eb66a9f2ac70eef346f040d8a79977472"
model_name = "Qwen/Qwen2-VL-72B-Instruct"
revision = "f9b556a74d58e6d9915f73227c21045c87342b42"
model_dir = "/cache/hf_cache/hub/models--Qwen--Qwen2-VL-72B-Instruct/snapshots/f9b556a74d58e6d9915f73227c21045c87342b42"


@torch.inference_mode()
def convert_hf_weights(model: str, checkpoint: str):
    print(f"Loading model from {model}")
    model = Qwen2VLForConditionalGeneration.from_pretrained(model_dir)
    state_dict = model.state_dict()

    print(f"Writing to DCP at '{checkpoint}'")
    # checkpoint.mkdir(parents=True, exist_ok=True)
    storage_writer = DCP.filesystem.FileSystemWriter(checkpoint, thread_count=32)
    DCP.save(state_dict, storage_writer=storage_writer)

if __name__ == "__main__":
    # parser = argparse.ArgumentParser(description="Convert huggingface-style model weights to DCP format.")
    # parser.add_argument("--model", type=str, required=True)
    # parser.add_argument("--checkpoint", type=Path, required=True)
    # args = parser.parse_args()

    # convert_hf_weights(args.model, args.checkpoint)

    convert_hf_weights(model_name, "/cache/DCP/72B_new")
```


### Generate a new training dataset

Delete the following code:
```
    train_dataset, eval_dataset, test_dataset = load_dataset(
        config.dataset_id, split=['train[:10%]', 'val[:10%]', 'test[:10%]'])
```

Add the following code in the same place:
```
    first_raw = load_dataset(
            config.dataset_id,
            split="train[:10]",
            cache_dir="/workspace/mingdian.liu@xiaopeng.com/cache/hf_cache",
        )[3]
    
    train_dataset = [first_raw] * 5096
```

**Comment by weifengpy** [comment]
thanks for the DCP script - I can repro now

TL;DR: I changed the wrapping to reduce memory usage, to cover Qwen2VLDecoderLayer (gate_proj/up_proj/down_proj) and `Qwen2VLVisionBlock`, `visual.merger`, `lm_head`, `embed_tokens`. see code at the end

long version

here is the memory snapshot from your repro (you can dump it by running the code below)
* fwd memory is usually high because Qwen2VLVisionBlock, lm_head, embed_tokens are too large
* bwd memory is too high because of holding activations for above big modules
* the star is the gpu after each iteration, that's why nvidia-smi and active/reserve memory are very different. we need to consider fwd/bwd/activation memory

<img width="1587" alt="Image" src="https://github.com/user-attachments/assets/fefec046-cc44-457d-b724-64550d5d245a" />

here is the memory snapshot with the new wrapping
* fwd and bwd memory are significantly reduced because of finer wrapping and activation checkpoint
* the peak memory appears at opt.step. parameters are fully sharded, meaning 7B x 2 (bf16) / 4 GPU = 3.5G. gradients are 3.5G. opt states are 3.5G x 2. intermediate tensors during opt.step are 3.5G. that's around 18G

<img width="1355" alt="Image" src="https://github.com/user-attachments/assets/f1ec5eb4-ac35-4b46-a26d-4e9f2d24edbf" />


code
```
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import Qwen2VLForConditionalGeneration, Qwen2VLProcessor, AutoModelForVision2Seq, AutoConfig
from qwen_vl_utils import process_vision_info
from peft import LoraConfig, get_peft_model
from datasets import load_dataset
import numpy as np
from PIL import Image
import io
import logging
import os

from torch.nn.parallel import DistributedDataParallel as DDP
import torch.distributed as dist
import torch.distributed.checkpoint as dcp
from torch.distributed.device_mesh import init_device_mesh
from transformers.models.qwen2_vl.modeling_qwen2_vl import Qwen2VLDecoderLayer, Qwen2VLVisionBlock
from torch.distributed._composable.fsdp import fully_shard
from torch.distributed import init_process_group, destroy_process_group
from torch.distributed.checkpoint import DefaultLoadPlanner, DefaultSavePlanner
from torch.distributed._composable.fsdp import (
    CPUOffloadPolicy,
    fully_shard,
    MixedPrecisionPolicy,
)
from torch.distributed.algorithms._checkpoint.checkpoint_wrapper import (
    checkpoint_wrapper as ptd_checkpoint_wrapper,
)
import pickle
torch.cuda.memory._record_memory_history(max_entries=1000000)



# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# init dist
distributed_backend = "nccl" # gloo for cpu
dist.init_process_group(distributed_backend)

local_rank = int(os.environ["LOCAL_RANK"])
world_size = int(os.environ["WORLD_SIZE"])
device = torch.device(f"cuda:{local_rank}")
torch.cuda.set_device(device)


# model_name = "Qwen/Qwen2-VL-2B-Instruct"
# revision = "895c3a49bc3fa70a340399125c650a463535e71c"
model_name = "Qwen/Qwen2-VL-7B-Instruct"
revision = "a28a094eb66a9f2ac70eef346f040d8a79977472"
# model_name = "Qwen/Qwen2-VL-72B-Instruct"
# revision = "f9b556a74d58e6d9915f73227c21045c87342b42"

dataset_id = "HuggingFaceM4/ChartQA"
processor = Qwen2VLProcessor.from_pretrained(model_name, 
                                             revision=revision,
                                             )


# Configuration
class Config:
    dataset_id = "HuggingFaceM4/ChartQA"
    output_dir = "your/path"
    batch_size = 2
    num_epochs = 1
    learning_rate = 5e-5
    max_seq_length = 512
    lora_rank = 32
    lora_alpha = 64
    lora_dropout = 0.1
    device = "cuda" if torch.cuda.is_available() else "cpu"




system_message = """You are a Vision Language Model specialized in interpreting visual data from chart images.
Your task is to analyze the provided chart image and respond to queries with concise answers, usually a single word, number, or short phrase.
The charts include a variety of types (e.g., line charts, bar charts) and contain colors, labels, and text.
Focus on delivering accurate, succinct answers based on the visual information. Avoid additional explanation unless absolutely necessary."""

def format_data(sample):
    return [
        {
            "role": "system",
            "content": [{"type": "text", "text": system_message}],
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": sample["image"],
                },
                {
                    "type": "text",
                    "text": sample["query"],
                },
            ],
        },
        {
            "role": "assistant",
            "content": [{"type": "text", "text": sample["label"][0]}],
        },
    ]

# Training function
def train_model(model, train_loader, optimizer, config):
    model.train()
    total_steps = len(train_loader) * config.num_epochs
    step = 0

    scaler = torch.amp.GradScaler("cuda", enabled=True)

    for epoch in range(config.num_epochs):
        total_loss = 0
        for batch_idx, batch in enumerate(train_loader):

            inputs, labels = batch
            inputs = inputs.to(config.device)
            labels = labels.to(config.device)

            # Mixed precision training
            loss = model(**inputs, labels=labels).loss
            loss.backward() # no scaler
            optimizer.step()
            optimizer.zero_grad()
            
            step += 1
            logger.info(f"Epoch {epoch+1}/{config.num_epochs}, Step {step}/{total_steps}, Loss: {loss.item():.4f}")

            del loss



# Create a data collator to encode text and image pairs
def collate_fn(examples):
    # Get the texts and images, and apply the chat template
    texts = [
        processor.apply_chat_template(example, tokenize=False) for example in examples
    ]  # Prepare texts for processing
    image_inputs = [process_vision_info(example)[0] for example in examples]  # Process the images to extract inputs

    # Tokenize the texts and process the images
    batch = processor(
        text=texts, images=image_inputs, return_tensors="pt", padding=True
    )  # Encode texts and images into tensors

    # The labels are the input_ids, and we mask the padding tokens in the loss computation
    labels = batch["input_ids"].clone()  # Clone input IDs for labels
    labels[labels == processor.tokenizer.pad_token_id] = -100  # Mask padding tokens in labels

    # Ignore the image token index in the loss computation (model specific)
    if isinstance(processor, Qwen2VLProcessor):  # Check if the processor is Qwen2VLProcessor
        image_tokens = [151652, 151653, 151655]  # Specific image token IDs for Qwen2VLProcessor
    else:
        image_tokens = [processor.tokenizer.convert_tokens_to_ids(processor.image_token)]  # Convert image token to ID

    # Mask image token IDs in the labels
    for image_token_id in image_tokens:
        labels[labels == image_token_id] = -100  # Mask image token IDs in labels

    return batch, labels



# Main function
def main():

    config = Config()

    # Load model and processor
    logger.info("Loading model and processor...")

    hf_config = AutoConfig.from_pretrained(
                model_name, 
                revision=revision, 
                torch_dtype=torch.bfloat16,
                attn_implementation="flash_attention_2",
                )

    with torch.device("meta"):
        model = AutoModelForVision2Seq.from_config(hf_config, torch_dtype=torch.bfloat16)

    mp_policy=MixedPrecisionPolicy(param_dtype=torch.bfloat16, 
                                   reduce_dtype=torch.bfloat16, 
                                   output_dtype=torch.bfloat16, 
                                   cast_forward_inputs=True)
    offload_policy = CPUOffloadPolicy(pin_memory=False)

    # apply FSDP2
    device_mesh = init_device_mesh("cuda", (world_size,))
    for module in model.modules():
        if isinstance(module, Qwen2VLDecoderLayer):
            ptd_checkpoint_wrapper(module.mlp.gate_proj, preserve_rng_state=False)
            fully_shard(module.mlp.gate_proj, 
                        mesh=device_mesh, 
                        reshard_after_forward=True,
                        mp_policy=mp_policy,
                        # offload_policy=offload_policy,
                        )
            ptd_checkpoint_wrapper(module.mlp.up_proj, preserve_rng_state=False)
            fully_shard(module.mlp.up_proj, 
                        mesh=device_mesh, 
                        reshard_after_forward=True,
                        mp_policy=mp_policy,
                        # offload_policy=offload_policy,
                        )
            ptd_checkpoint_wrapper(module.mlp.down_proj, preserve_rng_state=False)
            fully_shard(module.mlp.down_proj, 
                        mesh=device_mesh, 
                        reshard_after_forward=True,
                        mp_policy=mp_policy,
                        # offload_policy=offload_policy,
                        )
            ptd_checkpoint_wrapper(module, preserve_rng_state=False)
            fully_shard(module, 
                        mesh=device_mesh, 
                        reshard_after_forward=True,
                        mp_policy=mp_policy,
                        # offload_policy=offload_policy,
                        )
        if isinstance(module, Qwen2VLVisionBlock):
            ptd_checkpoint_wrapper(module, preserve_rng_state=False)
            fully_shard(module, 
                        mesh=device_mesh, 
                        reshard_after_forward=True,
                        mp_policy=mp_policy,
                        # offload_policy=offload_policy,
                        )
    

    ptd_checkpoint_wrapper(model.visual.merger.mlp[0], preserve_rng_state=False)
    fully_shard(model.visual.merger.mlp[0], 
        mesh=device_mesh, 
        reshard_after_forward=True,
        mp_policy=mp_policy,
        # offload_policy=offload_policy,
    )

    ptd_checkpoint_wrapper(model.visual.merger.mlp[2], preserve_rng_state=False)
    fully_shard(model.visual.merger.mlp[2], 
        mesh=device_mesh, 
        reshard_after_forward=True,
        mp_policy=mp_policy,
        # offload_policy=offload_policy,
    )

    ptd_checkpoint_wrapper(model.lm_head, preserve_rng_state=False)
    fully_shard(model.lm_head, 
        mesh=device_mesh, 
        reshard_after_forward=True,
        mp_policy=mp_policy,
        # offload_policy=offload_policy,
    )

    
    ptd_checkpoint_wrapper(model.model.embed_tokens, preserve_rng_state=False)
    fully_shard(model.model.embed_tokens, 
        mesh=device_mesh, 
        reshard_after_forward=True,
        mp_policy=mp_policy,
        # offload_policy=offload_policy,
    )
    
    fully_shard(model, 
        mesh=device_mesh, 
        reshard_after_forward=True,
        mp_policy=mp_policy,
        # offload_policy=offload_policy,
    )

    model.to_empty(device='cuda')

    model_state_dict = model.state_dict()

    model_dir = "your/path"

    # load qwen2-vl model
    dcp.load(
        state_dict=model_state_dict,
        checkpoint_id=model_dir,
        planner=DefaultLoadPlanner(allow_partial_load=True),
    )

    # model = model.to(torch.bfloat16).cuda()

    if torch.distributed.get_rank() == 0:
        print(f"model after wrapping: {model}")
        print("parameters:")
        for name, param in model.named_parameters():
            print(f"{name}, {param.dtype}, {param.numel()} ")
    

    # Load dataset
    logger.info("Loading dataset...")

    train_dataset, eval_dataset, test_dataset = load_dataset(
        config.dataset_id, split=['train[:10%]', 'val[:10%]', 'test[:10%]'])
    train_dataset = [format_data(sample) for sample in train_dataset][0:3]

    train_dataloader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=1,
        collate_fn=collate_fn,
        shuffle=True,
    )

    # Optimizer
    optimizer = torch.optim.AdamW(model.parameters(), lr=config.learning_rate)

    # Create output directory
    os.makedirs(config.output_dir, exist_ok=True)

    # Train
    logger.info("Starting training...")
    train_model(model, train_dataloader, optimizer, config)

    snapshot = torch.cuda.memory._snapshot()
    pickle.dump(snapshot, open(f"train_hf_rank{torch.distributed.get_rank()}.pickle", 'wb'))



if __name__ == "__main__":
    main()
    destroy_process_group()
    logger.info("Training completed.")

```

**Comment by mingdianliu** [comment]
@weifengpy Hi Weifeng, thanks for your prompt follow-up!

After posting the question here, I suddenly realize that I forgot to add activation checkpointing. After adding activation checkpointing to my code, it is working now. Let me clean the code and post it here later on. I believe some people are interested in training the big models from Huggingface with FSDP2. Hope my code is helpful to them.

BTW, the memory profiling result is interesting. I will share my owns as well. Want to discuss more with you about the profiling result.

> thanks for the DCP script - I can repro now
> 
> TL;DR: I changed the wrapping to reduce memory usage, to cover Qwen2VLDecoderLayer (gate_proj/up_proj/down_proj) and `Qwen2VLVisionBlock`, `visual.merger`, `lm_head`, `embed_tokens`. see code at the end. Feel free to use the wrapping on 72B model with multiple GPUs. If it still OOM, we can use memory snapshot to discuss
> 
> long version
> 
> here is the memory snapshot from your repro (you can dump it by running the code below)
> 
> * fwd memory is usually high because Qwen2VLVisionBlock, lm_head, embed_tokens are too large
> * bwd memory is too high because of holding activations for above big modules
> * the star is the gpu after each iteration, that's why nvidia-smi and active/reserve memory are very different. we need to consider fwd/bwd/activation memory
> 
> <img alt="Image" width="1587" src="https://private-user-images.githubusercontent.com/134637289/436813759-fefec046-cc44-457d-b724-64550d5d245a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDYyMTM3NzksIm5iZiI6MTc0NjIxMzQ3OSwicGF0aCI6Ii8xMzQ2MzcyODkvNDM2ODEzNzU5LWZlZmVjMDQ2LWNjNDQtNDU3ZC1iNzI0LTY0NTUwZDVkMjQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUwMlQxOTE3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMThlOGQyODdmYTY2YmU5ZDk5MWY1ZjAyNzNkNzZlYzc0YTNkZGIzYWYwYmI0NTRjYzk4OWQ4NTIwNWMzZWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7nhke5BV9KRMXipjrtST852Upm8CBvBlH9iAX_kXrGQ">
> here is the memory snapshot with the new wrapping
> 
> * fwd and bwd memory are significantly reduced because of finer wrapping and activation checkpoint
> * the peak memory appears at opt.step. parameters are fully sharded, meaning 7B x 2 (bf16) / 4 GPU = 3.5G. gradients are 3.5G. opt states are 3.5G x 2. intermediate tensors during opt.step are 3.5G. that's around 18G
> 
> <img alt="Image" width="1355" src="https://private-user-images.githubusercontent.com/134637289/436815179-f1ec5eb4-ac35-4b46-a26d-4e9f2d24edbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDYyMTM3NzksIm5iZiI6MTc0NjIxMzQ3OSwicGF0aCI6Ii8xMzQ2MzcyODkvNDM2ODE1MTc5LWYxZWM1ZWI0LWFjMzUtNGI0Ni1hMjZkLTRlOWYyZDI0ZWRiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUwMlQxOTE3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmEwNmU2NjBjODgxYTVlZjg0NmI5ZmUxYjRhYzQ1MDY1MjM2NmJjM2FjYTE4ZTc2ZTUwMDViMzEyZjcwNTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O_zrXOdv8Mi8gFiqwpL8lN5RR8STtIO3rNg5agpPJ_s">
> code
> 
> ```
> import torch
> import torch.nn as nn
> from torch.utils.data import Dataset, DataLoader
> from transformers import Qwen2VLForConditionalGeneration, Qwen2VLProcessor, AutoModelForVision2Seq, AutoConfig
> from qwen_vl_utils import process_vision_info
> from peft import LoraConfig, get_peft_model
> from datasets import load_dataset
> import numpy as np
> from PIL import Image
> import io
> import logging
> import os
> 
> from torch.nn.parallel import DistributedDataParallel as DDP
> import torch.distributed as dist
> import torch.distributed.checkpoint as dcp
> from torch.distributed.device_mesh import init_device_mesh
> from transformers.models.qwen2_vl.modeling_qwen2_vl import Qwen2VLDecoderLayer, Qwen2VLVisionBlock
> from torch.distributed._composable.fsdp import fully_shard
> from torch.distributed import init_process_group, destroy_process_group
> from torch.distributed.checkpoint import DefaultLoadPlanner, DefaultSavePlanner
> from torch.distributed._composable.fsdp import (
>     CPUOffloadPolicy,
>     fully_shard,
>     MixedPrecisionPolicy,
> )
> from torch.distributed.algorithms._checkpoint.checkpoint_wrapper import (
>     checkpoint_wrapper as ptd_checkpoint_wrapper,
> )
> import pickle
> torch.cuda.memory._record_memory_history(max_entries=1000000)
> 
> 
> 
> # Set up logging
> logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
> logger = logging.getLogger(__name__)
> 
> # init dist
> distributed_backend = "nccl" # gloo for cpu
> dist.init_process_group(distributed_backend)
> 
> local_rank = int(os.environ["LOCAL_RANK"])
> world_size = int(os.environ["WORLD_SIZE"])
> device = torch.device(f"cuda:{local_rank}")
> torch.cuda.set_device(device)
> 
> 
> # model_name = "Qwen/Qwen2-VL-2B-Instruct"
> # revision = "895c3a49bc3fa70a340399125c650a463535e71c"
> model_name = "Qwen/Qwen2-VL-7B-Instruct"
> revision = "a28a094eb66a9f2ac70eef346f040d8a79977472"
> # model_name = "Qwen/Qwen2-VL-72B-Instruct"
> # revision = "f9b556a74d58e6d9915f73227c21045c87342b42"
> 
> dataset_id = "HuggingFaceM4/ChartQA"
> processor = Qwen2VLProcessor.from_pretrained(model_name, 
>                                              revision=revision,
>                                              )
> 
> 
> # Configuration
> class Config:
>     dataset_id = "HuggingFaceM4/ChartQA"
>     output_dir = "your/path"
>     batch_size = 2
>     num_epochs = 1
>     learning_rate = 5e-5
>     max_seq_length = 512
>     lora_rank = 32
>     lora_alpha = 64
>     lora_dropout = 0.1
>     device = "cuda" if torch.cuda.is_available() else "cpu"
> 
> 
> 
> 
> system_message = """You are a Vision Language Model specialized in interpreting visual data from chart images.
> Your task is to analyze the provided chart image and respond to queries with concise answers, usually a single word, number, or short phrase.
> The charts include a variety of types (e.g., line charts, bar charts) and contain colors, labels, and text.
> Focus on delivering accurate, succinct answers based on the visual information. Avoid additional explanation unless absolutely necessary."""
> 
> def format_data(sample):
>     return [
>         {
>             "role": "system",
>             "content": [{"type": "text", "text": system_message}],
>         },
>         {
>             "role": "user",
>             "content": [
>                 {
>                     "type": "image",
>                     "image": sample["image"],
>                 },
>                 {
>                     "type": "text",
>                     "text": sample["query"],
>                 },
>             ],
>         },
>         {
>             "role": "assistant",
>             "content": [{"type": "text", "text": sample["label"][0]}],
>         },
>     ]
> 
> # Training function
> def train_model(model, train_loader, optimizer, config):
>     model.train()
>     total_steps = len(train_loader) * config.num_epochs
>     step = 0
> 
>     scaler = torch.amp.GradScaler("cuda", enabled=True)
> 
>     for epoch in range(config.num_epochs):
>         total_loss = 0
>         for batch_idx, batch in enumerate(train_loader):
> 
>             inputs, labels = batch
>             inputs = inputs.to(config.device)
>             labels = labels.to(config.device)
> 
>             # Mixed precision training
>             loss = model(**inputs, labels=labels).loss
>             loss.backward() # no scaler
>             optimizer.step()
>             optimizer.zero_grad()
>             
>             step += 1
>             logger.info(f"Epoch {epoch+1}/{config.num_epochs}, Step {step}/{total_steps}, Loss: {loss.item():.4f}")
> 
>             del loss
> 
> 
> 
> # Create a data collator to encode text and image pairs
> def collate_fn(examples):
>     # Get the texts and images, and apply the chat template
>     texts = [
>         processor.apply_chat_template(example, tokenize=False) for example in examples
>     ]  # Prepare texts for processing
>     image_inputs = [process_vision_info(example)[0] for example in examples]  # Process the images to extract inputs
> 
>     # Tokenize the texts and process the images
>     batch = processor(
>         text=texts, images=image_inputs, return_tensors="pt", padding=True
>     )  # Encode texts and images into tensors
> 
>     # The labels are the input_ids, and we mask the padding tokens in the loss computation
>     labels = batch["input_ids"].clone()  # Clone input IDs for labels
>     labels[labels == processor.tokenizer.pad_token_id] = -100  # Mask padding tokens in labels
> 
>     # Ignore the image token index in the loss computation (model specific)
>     if isinstance(processor, Qwen2VLProcessor):  # Check if the processor is Qwen2VLProcessor
>         image_tokens = [151652, 151653, 151655]  # Specific image token IDs for Qwen2VLProcessor
>     else:
>         image_tokens = [processor.tokenizer.convert_tokens_to_ids(processor.image_token)]  # Convert image token to ID
> 
>     # Mask image token IDs in the labels
>     for image_token_id in image_tokens:
>         labels[labels == image_token_id] = -100  # Mask image token IDs in labels
> 
>     return batch, labels
> 
> 
> 
> # Main function
> def main():
> 
>     config = Config()
> 
>     # Load model and processor
>     logger.info("Loading model and processor...")
> 
>     hf_config = AutoConfig.from_pretrained(
>                 model_name, 
>                 revision=revision, 
>                 torch_dtype=torch.bfloat16,
>                 attn_implementation="flash_attention_2",
>                 )
> 
>     with torch.device("meta"):
>         model = AutoModelForVision2Seq.from_config(hf_config, torch_dtype=torch.bfloat16)
> 
>     mp_policy=MixedPrecisionPolicy(param_dtype=torch.bfloat16, 
>                                    reduce_dtype=torch.bfloat16, 
>                                    output_dtype=torch.bfloat16, 
>                                    cast_forward_inputs=True)
>     offload_policy = CPUOffloadPolicy(pin_memory=False)
> 
>     # apply FSDP2
>     device_mesh = init_device_mesh("cuda", (world_size,))
>     for module in model.modules():
>         if isinstance(module, Qwen2VLDecoderLayer):
>             ptd_checkpoint_wrapper(module.mlp.gate_proj, preserve_rng_state=False)
>             fully_shard(module.mlp.gate_proj, 
>                         mesh=device_mesh, 
>                         reshard_after_forward=True,
>                         mp_policy=mp_policy,
>                         # offload_policy=offload_policy,
>                         )
>             ptd_checkpoint_wrapper(module.mlp.up_proj, preserve_rng_state=False)
>             fully_shard(module.mlp.up_proj, 
>                         mesh=device_mesh, 
>                         reshard_after_forward=True,
>                         mp_policy=mp_policy,
>                         # offload_policy=offload_policy,
>                         )
>             ptd_checkpoint_wrapper(module.mlp.down_proj, preserve_rng_state=False)
>             fully_shard(module.mlp.down_proj, 
>                         mesh=device_mesh, 
>                         reshard_after_forward=True,
>                         mp_policy=mp_policy,
>                         # offload_policy=offload_policy,
>                         )
>             ptd_checkpoint_wrapper(module, preserve_rng_state=False)
>             fully_shard(module, 
>                         mesh=device_mesh, 
>                         reshard_after_forward=True,
>                         mp_policy=mp_policy,
>                         # offload_policy=offload_policy,
>                         )
>         if isinstance(module, Qwen2VLVisionBlock):
>             ptd_checkpoint_wrapper(module, preserve_rng_state=False)
>             fully_shard(module, 
>                         mesh=device_mesh, 
>                         reshard_after_forward=True,
>                         mp_policy=mp_policy,
>                         # offload_policy=offload_policy,
>                         )
>     
> 
>     ptd_checkpoint_wrapper(model.visual.merger.mlp[0], preserve_rng_state=False)
>     fully_shard(model.visual.merger.mlp[0], 
>         mesh=device_mesh, 
>         reshard_after_forward=True,
>         mp_policy=mp_policy,
>         # offload_policy=offload_policy,
>     )
> 
>     ptd_checkpoint_wrapper(model.visual.merger.mlp[2], preserve_rng_state=False)
>     fully_shard(model.visual.merger.mlp[2], 
>         mesh=device_mesh, 
>         reshard_after_forward=True,
>         mp_policy=mp_policy,
>         # offload_policy=offload_policy,
>     )
> 
>     ptd_checkpoint_wrapper(model.lm_head, preserve_rng_state=False)
>     fully_shard(model.lm_head, 
>         mesh=device_mesh, 
>         reshard_after_forward=True,
>         mp_policy=mp_policy,
>         # offload_policy=offload_policy,
>     )
> 
>     
>     ptd_checkpoint_wrapper(model.model.embed_tokens, preserve_rng_state=False)
>     fully_shard(model.model.embed_tokens, 
>         mesh=device_mesh, 
>         reshard_after_forward=True,
>         mp_policy=mp_policy,
>         # offload_policy=offload_policy,
>     )
>     
>     fully_shard(model, 
>         mesh=device_mesh, 
>         reshard_after_forward=True,
>         mp_policy=mp_policy,
>         # offload_policy=offload_policy,
>     )
> 
>     model.to_empty(device='cuda')
> 
>     model_state_dict = model.state_dict()
> 
>     model_dir = "your/path"
> 
>     # load qwen2-vl model
>     dcp.load(
>         state_dict=model_state_dict,
>         checkpoint_id=model_dir,
>         planner=DefaultLoadPlanner(allow_partial_load=True),
>     )
> 
>     # model = model.to(torch.bfloat16).cuda()
> 
>     if torch.distributed.get_rank() == 0:
>         print(f"model after wrapping: {model}")
>         print("parameters:")
>         for name, param in model.named_parameters():
>             print(f"{name}, {param.dtype}, {param.numel()} ")
>     
> 
>     # Load dataset
>     logger.info("Loading dataset...")
> 
>     train_dataset, eval_dataset, test_dataset = load_dataset(
>         config.dataset_id, split=['train[:10%]', 'val[:10%]', 'test[:10%]'])
>     train_dataset = [format_data(sample) for sample in train_dataset][0:3]
> 
>     train_dataloader = torch.utils.data.DataLoader(
>         train_dataset,
>         batch_size=1,
>         collate_fn=collate_fn,
>         shuffle=True,
>     )
> 
>     # Optimizer
>     optimizer = torch.optim.AdamW(model.parameters(), lr=config.learning_rate)
> 
>     # Create output directory
>     os.makedirs(config.output_dir, exist_ok=True)
> 
>     # Train
>     logger.info("Starting training...")
>     train_model(model, train_dataloader, optimizer, config)
> 
>     snapshot = torch.cuda.memory._snapshot()
>     pickle.dump(snapshot, open(f"train_hf_rank{torch.distributed.get_rank()}.pickle", 'wb'))
> 
> 
> 
> if __name__ == "__main__":
>     main()
>     destroy_process_group()
>     logger.info("Training completed.")
> ```
