### ISSUE TITLE
pin_memory crashes for big tensors and leaks page locked memory

### ISSUE THREAD

**Issue by c-rizz** [pytorch/pytorch#152335]
### 🐛 Describe the bug

Allocating pinning large tensors (>2 GB on my machine) crashes with "CUDA error: invalid arguement". Also, it seems to allocate additional memory compared to the actual tensor size, maybe due to [150517](https://github.com/pytorch/pytorch/issues/150517). Memory that is not freed after the crash, requiring a reboot to clear.
This can be reproduced with the following:

```python
#!/usr/bin/env python3
import subprocess
subprocess.run("free -m",shell=True)
import gc
import time
import sys

import torch as th
print(f"imported torch")
subprocess.run("free -m",shell=True)
gbs = float(sys.argv[1])
t = th.zeros(int(gbs*(1024**3)),dtype=th.uint8,device="cpu")
print(f"allocated tensor")
print(f"size={t.size()}, numel={t.numel()} pinned={t.untyped_storage().is_pinned()}, nbytes={t.untyped_storage().nbytes()}")
subprocess.run("free -m",shell=True)

t.pin_memory()
print(f"Pinned tensor")
print(f"size={t.size()}, numel={t.numel()} pinned={t.untyped_storage().is_pinned()}, nbytes={t.untyped_storage().nbytes()}")
subprocess.run("free -m",shell=True)

del t
gc.collect()
time.sleep(1)
print(f"deleted tensor")
subprocess.run("free -m",shell=True)
```

On my machine allocating 10GB results in the following:
```
(venv) crizz@machine:~/testenv$ free -m
               total        used        free      shared  buff/cache   available
Mem:          128293       26972      100562           5        1836      101321
Swap:          31249           0       31249
(venv) crizz@machine:~/testenv$ ./test_pin.py 10
               total        used        free      shared  buff/cache   available
Mem:          128293       26977      100557           5        1836      101316
Swap:          31249           0       31249
imported torch
               total        used        free      shared  buff/cache   available
Mem:          128293       27197      100336           5        1836      101095
Swap:          31249           0       31249
allocated tensor
size=torch.Size([10737418240]), numel=10737418240 pinned=False, nbytes=10737418240
               total        used        free      shared  buff/cache   available
Mem:          128293       37725       89808           5        1836       90568
Swap:          31249           0       31249
Traceback (most recent call last):
  File "/home/crizz/testenv/./test_pin.py", line 17, in <module>
    t.pin_memory()
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

(venv) crizz@machine:~/testenv$ free -m
               total        used        free      shared  buff/cache   available
Mem:          128293       43573       83960           5        1836       84719
Swap:          31249           0       31249
```

As can be seen, 17Gb of memory remain occupied in memory, which correspond to 2^34 bytes, the next power of two after 10Gb.

With 2GB instead:
```
(venv) crizz@machine:~/testenv$ free -m
               total        used        free      shared  buff/cache   available
Mem:          128293       43375       84142           5        1852       84917
Swap:          31249           0       31249
(venv) crizz@machine:~/testenv$ ./test_pin.py 2
               total        used        free      shared  buff/cache   available
Mem:          128293       43387       84131           5        1852       84906
Swap:          31249           0       31249
imported torch
               total        used        free      shared  buff/cache   available
Mem:          128293       43622       83896           5        1852       84671
Swap:          31249           0       31249
allocated tensor
size=torch.Size([2147483648]), numel=2147483648 pinned=False, nbytes=2147483648
               total        used        free      shared  buff/cache   available
Mem:          128293       45813       81705           5        1852       82480
Swap:          31249           0       31249
Pinned tensor
size=torch.Size([2147483648]), numel=2147483648 pinned=False, nbytes=2147483648
               total        used        free      shared  buff/cache   available
Mem:          128293       48020       79495        2061        3913       80272
Swap:          31249           0       31249
deleted tensor
               total        used        free      shared  buff/cache   available
Mem:          128293       46203       81313        2061        3913       82090
Swap:          31249           0       31249
(venv) crizz@machine:~/testenv$ free -m
               total        used        free      shared  buff/cache   available
Mem:          128293       43736       83782           5        1852       84557
Swap:          31249           0       31249
```

The expected behaviour would be:

- Not occupying much more pinned memory than required
- Not crashing, especially in my case, where enough memory is actually available
- Most importantly, not leaving dangling locked memory, that is seemingly impossible to free up

Thanks!

### Versions

Collecting environment information...
PyTorch version: 2.7.0+cu126
Is debug build: False
CUDA used to build PyTorch: 12.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 24.04.1 LTS (x86_64)
GCC version: (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.39

Python version: 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-6.11.0-24-generic-x86_64-with-glibc2.39
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 570.133.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        52 bits physical, 57 bits virtual
Byte Order:                           Little Endian
CPU(s):                               64
On-line CPU(s) list:                  0-63
Vendor ID:                            AuthenticAMD
Model name:                           AMD Ryzen Threadripper 7970X 32-Cores
CPU family:                           25
Model:                                24
Thread(s) per core:                   2
Core(s) per socket:                   32
Socket(s):                            1
Stepping:                             1
Frequency boost:                      enabled
CPU(s) scaling MHz:                   30%
CPU max MHz:                          5352.0000
CPU min MHz:                          545.0000
BogoMIPS:                             7987.35
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp ibrs_enhanced vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic vgif x2avic v_spec_ctrl vnmi avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid overflow_recov succor smca fsrm flush_l1d debug_swap
Virtualization:                       AMD-V
L1d cache:                            1 MiB (32 instances)
L1i cache:                            1 MiB (32 instances)
L2 cache:                             32 MiB (32 instances)
L3 cache:                             128 MiB (4 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-63
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Mitigation; Safe RET
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==2.2.5
[pip3] nvidia-cublas-cu12==12.6.4.1
[pip3] nvidia-cuda-cupti-cu12==12.6.80
[pip3] nvidia-cuda-nvrtc-cu12==12.6.77
[pip3] nvidia-cuda-runtime-cu12==12.6.77
[pip3] nvidia-cudnn-cu12==9.5.1.17
[pip3] nvidia-cufft-cu12==11.3.0.4
[pip3] nvidia-curand-cu12==10.3.7.77
[pip3] nvidia-cusolver-cu12==11.7.1.2
[pip3] nvidia-cusparse-cu12==12.5.4.2
[pip3] nvidia-cusparselt-cu12==0.6.3
[pip3] nvidia-nccl-cu12==2.26.2
[pip3] nvidia-nvjitlink-cu12==12.6.85
[pip3] nvidia-nvtx-cu12==12.6.77
[pip3] torch==2.7.0
[pip3] triton==3.3.0
[conda] Could not collect

**Comment by FabianIsensee** [comment]
I also run into this issue and it's driving me crazy. Tested multiple nvidia drivers and pytorch versions to no avail.
Interestingly it just works on another workstation of mine, so the difference in hardware or software configuration may be relevant.

Workstation 1 (where it doesn't work):
AMD Ryzen 9800X3D, 64GB DDR5 6000MT/s, RTX 4090, Ubuntu 24.04

Workstation 2 (where it works):
AMD Ryzen 3950X, 64GB DDR4 3200 MT/s, RTX 3090, Ubuntu 22.04

repro:
```python
import torch
a = torch.zeros((7, 512, 512, 612), device='cpu', dtype=torch.float16, pin_memory=True)
```

On both systems there is ample RAM available

**Comment by FabianIsensee** [comment]
Was able to solve it by upgrading my kernel from 6.11 to 6.13. Seems to be a 6.11 related problem
Also see [here](https://forums.developer.nvidia.com/t/cudamallochost-with-large-memory-failed-with-invalid-argument/311048)

**Comment by FabianIsensee** [comment]
Did this solve your issue @c-rizz ? Would be valuable to know for other people stumbling upon this issue. And you may want to close it if the kernel is at fault since there is little the pytorch people can do about it

**Comment by smartparrot** [comment]
I also meet this issue, when I try to train llm using deepspeed in zero2/3 offload mode, it will run pin_memory of a very big cpu tensor which includes the whole llm's parameters and then fail like this:
### (x is cpu tensor)
Traceback (most recent call last):
  File "/pro/projects/mytests/pinmem3.py", line 25, in <module>
    x = x.pin_memory()
        ^^^^^^^^^^^^^^
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
###

test code to reproduce the issue is
###
import torch
import gc
import os
import psutil
import traceback

def print_mem(stage=""):
    """打印当前进程的 CPU 内存占用（MB）"""
    proc = psutil.Process(os.getpid())
    mem_mb = proc.memory_info().rss / 1024 / 1024
    print(f"[{stage}] CPU Mem: {mem_mb:.2f} MB")

if __name__ == "__main__":
    max_retries = 1
    print_mem("Before any allocation")

    for attempt in range(1, max_retries + 1):
        x = None
        try:
            # 分配 ~4GB (1e9 个 float32 元素)
            x = torch.randn(1 * 1024 * 1024 * 1024)
            print_mem(f"After allocation (try {attempt})")

            # 直接 pin_memory，不调用外部函数
            x = x.pin_memory()
            print_mem(f"After pin_memory (try {attempt})")

            # 检查结果
            if not x.is_pinned():
                raise RuntimeError("Tensor is not pinned!")
            if not x.is_contiguous():
                raise RuntimeError("Tensor is not contiguous!")

            print(f"✅ Try {attempt} succeeded: pinned={x.is_pinned()}, contiguous={x.is_contiguous()}")
            break  # 成功，跳出重试循环

        except Exception as err:
            print(f"❌ Try {attempt} failed: {err}")
            traceback.print_exc()

        finally:
            # 无论成功与否，都要释放 x 并回收
            if x is not None:

###

I have tried all kinds of ways, but it can not be solved.


MY environment :
OS: Ubuntu 24.04
uname -a
Linux smart 6.11.0-29-generic #29~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun 26 14:16:59 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Architecture:             x86_64
  CPU op-mode(s):         32-bit, 64-bit
  Address sizes:          46 bits physical, 48 bits virtual
  Byte Order:             Little Endian
CPU(s):                   64
  On-line CPU(s) list:    0-63
Vendor ID:                GenuineIntel
  BIOS Vendor ID:         Intel
  Model name:             Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz
    BIOS Model name:      Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz  CPU @
                           2.5GHz

I also tried one E5 CPU machine, ubuntu 22.04, pin 12 GB is OK, 16GB error, physical memory is 32GB.
tryied another two machines having no good result, mainly can not pin very big memory.

I think this is a very big problem which must be related to system and machine

**Comment by c-rizz** [comment]
I confirm the "Invalid Argument" issue  does not occur with kernel 6.14. However the excessive memory usage remains. I will add some info on issues [150517](https://github.com/pytorch/pytorch/issues/150517) and maybe [95823](https://github.com/pytorch/pytorch/issues/95823).

**Comment by ercanucan** [comment]
> Was able to solve it by upgrading my kernel from 6.11 to 6.13. Seems to be a 6.11 related problem. You have the same OS + kernel as me, so that may resolve it for you as well. Also see [here](https://forums.developer.nvidia.com/t/cudamallochost-with-large-memory-failed-with-invalid-argument/311048)

We also observed this crash while loading a model with large tensors using Linux kernel version 6.11.4 (Fedora 41) on an NVIDIA H200 (with driver v575).

The issue got resolved when we upgraded the kernel to 6.15.10 (Fedora 42) and NVIDIA driver v580 (and CUDA 13.0). So indeed it seems to be related to the Linux kernel version 6.11 and/or the corresponding driver combination.
