### ISSUE TITLE
pytorch for rtx 5080 unable to run inference

### ISSUE THREAD

**Issue by malleshk-web** [pytorch/pytorch#153944]
<img width="774" alt="Image" src="https://github.com/user-attachments/assets/ad73e38d-6389-4c4a-8ec8-995d12340b08" />

we are trying to run inference on rtx 5080 with torch using yolov8 facing issue like NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90 compute_37.

using tools like,
python                3.10
torch                   7.0+cu118
torchaudio          2.7.0+cu118
cuda version        12.9

cc @seemethere @malfet @osalpekar @atalman @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @ptrblck @msaroufim @eqy @jerryzh168

**Comment by malfet** [comment]
Please use https://discuss.pytorch.org to ask generic questions about using PyTorch

Closing, as to the best of my knowledge, CUDA-11.8 does not support Blackwell GPUs, one needs to use 12.8

@ptrblck , @svekars : should we update the error message to say that sm_120 needs CUDA-12.8?

**Comment by malleshk-web** [comment]
torch                  2.8.0.dev20250519+cu128
torchaudio             2.6.0.dev20250520+cu128
torchvision            0.22.0.dev20250520+cu128

I installed this version problem solved and working good RTX 5080 for inference 
https://webstorms.github.io/2025/02/06/5080-install.html


thank you
