### ISSUE TITLE
Add MPS support for ConvTranspose3d

### ISSUE THREAD

**Issue by AlokBharadwaj94** [pytorch/pytorch#154615]
### 🐛 Describe the bug

**Title:** Add MPS support for ConvTranspose3d (`aten::conv_transpose3d_forward`)

**Description:**
PyTorch’s MPS backend currently lacks an implementation of the 3D transposed convolution operator, causing:
RuntimeError: ConvTranspose 3D is not supported on MPS

This prevents models using `nn.ConvTranspose3d` from running on Apple Silicon GPUs.  [oai_citation:8‡GitHub](https://github.com/MIC-DKFZ/nnUNet/issues/2435?utm_source=chatgpt.com)

**Environment:**
- PyTorch version: 2.7.0 
- Platform: macOS 15.3.2 on Apple M2  
- Installed via: pip  
- MPS enabled: yes

**Reproduction steps:**
```python
import torch, torch.nn as nn
device = torch.device("mps")
layer  = nn.ConvTranspose3d(1,1,3).to(device)
input  = torch.randn(1,1,10,10,10, device=device)
output = layer(input)  # fails here
```

### Versions

Collecting environment information...
PyTorch version: 2.7.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.3.2 (arm64)
GCC version: Could not collect
Clang version: 17.0.0 (clang-1700.0.13.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.21 (main, Dec 11 2024, 10:21:40)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-15.3.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2

Versions of relevant libraries:
[pip3] torch==2.7.0
[conda] torch                     2.7.0                    pypi_0    pypi

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @kulinseth @malfet @DenisVieriu97 @jhavukainen

**Comment by colesbury** [comment]
Sounds useful. Maybe someone working on MPS support can comment?

**Comment by jhavukainen** [comment]
Took a quick glance at just removing the assert and recompiling and it seems like at least a basic ConvTranspose3D test produces outputs that agrees with CPU out of the box. Could be that this has been updated in some OS version since the assert to disable it was added in 2/2023. I'll grab this for myself to find out where the actual tests for this are and see if the current version passes them, and if there's some limitations on which OS version is required. 

If it looks good I'll add a PR to remove the assert.

**Comment by jhavukainen** [comment]
Opened a PR (https://github.com/pytorch/pytorch/pull/154696) that solves the provided test case by enabling the ConvTranspose3D support for FP32 and Complex64 dtypes. 

Unfortunately it seems that for FP16 and BF16 the discrepancy against CPU reference is too large but not obviously wrong to conclude if the mismatch is due to a bug or expected due to inherent differences of CPU vs. GPU accuracy without further study which I don't have time for right now. So they are left unsupported for the time being and the assert is tightened to only raise an issue if the op is called for those types.
