### ISSUE TITLE
Loading a PyTorch Model in C++ tutorial fails with No rule to make target '/usr/local/cuda/lib64/libculibos.a'

### ISSUE THREAD

**Issue by ly7969** [pytorch/pytorch#15476]
hi all
  Follow the tutorial(Loading a PyTorch Model in C++)
1.cmake
-- Caffe2: CUDA detected: 10.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda-10.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.0
-- Caffe2: Header version is: 10.0
-- Found cuDNN: v7.4.2  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX
-- Added CUDA NVCC flags for: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_70,code=compute_70
-- Configuring done
-- Generating done
2. make
make[2]: *** No rule to make target '/usr/local/cuda/lib64/libculibos.a', needed by 'example-app'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/example-app.dir/all' failed
make[1]: *** [CMakeFiles/example-app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

please ....

**Comment by ys0823** [comment]
I have the same problem with you, could you share with me the solving methods?

**Comment by mikehamer** [comment]
Bandaid solution:

In the file `/path/to/libtorch/share/cmake/Caffe2/Caffe2Targets.cmake`

Replace the references to `/usr/local/cuda/...`  with what ever path your CUDA is installed to

**Comment by soumith** [comment]
cc: @yf225 @kostmo @gchanan

**Comment by ezyang** [comment]
It sounds like `/usr/local/cuda` is incorrectly hardcoded. Another bandaid is to add a symlink `sudo ln -s /usr/local/cuda-10 /usr/local/cuda` (or similar)

**Comment by souljaboy764** [comment]
So basically the path for `libculibos.a` is hardcoded in `/path/to/libtorch/share/cmake/Caffe2/Caffe2Targets.cmake` as `/usr/local/cuda/lib64/libculibos.a`

As part of the CMake calls, the file `/path/to/libtorch/share/cmake/Caffe2/public/cuda.cmake` sets the value of `${CUDA_TOOLKIT_ROOT_DIR}` to your cuda home, which in my case was `/usr/local/cuda-9.0`

After changing the hardcoded path in `/path/to/libtorch/share/cmake/Caffe2/Caffe2Targets.cmake` from  `/usr/local/cuda/lib64/libculibos.a` to `${CUDA_TOOLKIT_ROOT_DIR}/lib64/libculibos.a` I am able to compile the example-app and run it successfully.

**Comment by ezyang** [comment]
@yf225 are you working on this?

**Comment by szagoruyko** [comment]
should be a simple fix, is `Caffe2Targets.cmake` automatically generated?

**Comment by beyondpie** [comment]
Hi, I download the latest version (1.1). The problem still exists, and I have to correct the path manually.  Anyone has the idea to automatically correct it ?

**Comment by rgommers** [comment]
This is fairly involved.

The root cause: `libculibos.a` and a number of other libs are referred to via `${CUDA_TOOLKIT_ROOT_DIR}/lib64/libname`. examples:
```
./cmake/Dependencies.cmake:
  820 :           caffe2::cudnn "${CUDA_TOOLKIT_ROOT_DIR}/lib64/libculibos.a" "dl")
  830 :           "${CUDA_TOOLKIT_ROOT_DIR}/lib64/libculibos.a" caffe2::cublas)
./cmake/TorchConfig.cmake.in:
   77 :     find_library(LIBNVTOOLSEXT libnvToolsExt.so PATHS ${CUDA_TOOLKIT_ROOT_DIR}/lib64/)
./cmake/public/cuda.cmake:
  219 :         "${CUDA_TOOLKIT_ROOT_DIR}/lib64/libcudart_static.a" rt dl)
  246 :         "${CUDA_TOOLKIT_ROOT_DIR}/lib64/libcurand_static.a")
  262 :         "${CUDA_TOOLKIT_ROOT_DIR}/lib64/libcufft_static.a")
  289 :         "${CUDA_TOOLKIT_ROOT_DIR}/lib64/libcublas_static.a")
```
There's 18 instances of that - those are all incorrect, CUDA install locations can vary. For example on Arch Linux:
```
$ locate libculibos.a
/opt/cuda/targets/x86_64-linux/lib/libculibos.a
$ locate libcufft_static.a
/opt/cuda/targets/x86_64-linux/lib/libcufft_static.a
```
On other distros it can be in other places.

The "official" way to get this right should be to use CMake's built-in support for CUDA. `FindCUDA` has been [deprecated since CMake 3.10](https://cmake.org/cmake/help/latest/module/FindCUDA.html). However, it's more complicated than that (submodules may not be able to upgrade etc) - there's a discussion on this in the README of [cmake/Modules_CUDA_fix](https://github.com/pytorch/pytorch/tree/master/cmake/Modules_CUDA_fix).

Eigen seems to get it right, it uses:
```
 27 
 28       if(CUDA_64_BIT_DEVICE_CODE AND (EXISTS "${CUDA_TOOLKIT_ROOT_DIR}/lib64"))
 29         link_directories("${CUDA_TOOLKIT_ROOT_DIR}/lib64")
 30       else()
 31         link_directories("${CUDA_TOOLKIT_ROOT_DIR}/lib")
 32       endif()
 33 
```

Perhaps the most pragmatic fix is to replace every instance of `${CUDA_TOOLKIT_ROOT_DIR}/lib64/` with a new variable, and make that point to the right place with logic like Eigen's. 

That still leaves a second problem, that `CUDA_TOOLKIT_ROOT_DIR` can't even figure out it's supposed to point to `/opt/cuda/...` rather than `/usr/local/cuda/`. However, having the user specify it and things working then would already be a major step forward.

Some more comments from `FindCUDA.cmake`:
```
# The script will prompt the user to specify ``CUDA_TOOLKIT_ROOT_DIR`` if
# the prefix cannot be determined by the location of nvcc in the system
# path and ``REQUIRED`` is specified to :command:`find_package`.  To use
# a different installed version of the toolkit set the environment variable
# ``CUDA_BIN_PATH`` before running cmake (e.g.
# ``CUDA_BIN_PATH=/usr/local/cuda1.0`` instead of the default
# ``/usr/local/cuda``) or set ``CUDA_TOOLKIT_ROOT_DIR`` after configuring.  If
# you change the value of ``CUDA_TOOLKIT_ROOT_DIR``, various components that
# depend on the path will be relocated.
#
# It might be necessary to set ``CUDA_TOOLKIT_ROOT_DIR`` manually on certain
# platforms, or to use a CUDA runtime not installed in the default
# location.  In newer versions of the toolkit the CUDA library is
# included with the graphics driver -- be sure that the driver version
# matches what is needed by the CUDA runtime version.
```

This is also a duplicate of gh-15063, which has some more info and a WIP PR (gh-15239). That PR doesn't address the issue discussed above, so it's not a solution - but it may be useful too. @pjh5 any comments on your PR and the above?

**Comment by pjh5** [comment]
That PR is pretty old and rotted, and iirc I was trying to also make all the CUDA logic prettier at the same time, which was a bad idea. The problem I was trying to fix was specific to the binaries: we used cmake to add culibos as a dependency when building libtorch, when then causes culibos to be listed as a dependency in the Caffe2Targets.cmake (as expected and correct). However we then manually finangle the binary ourselves and copy culibos into it, and then fudge the rpath to point to the culibos that we ship with the binary (e.g. https://github.com/pytorch/builder/blob/master/conda/pytorch-nightly/build.sh ). Now the generated dependency in Caffe2Targets.cmake should not exist, no matter what the path to culibos should be. 

I may have been wrong in my diagnosis; I was never that great at figuring out where c++ dependencies come from. I guess my theory could be tested easily by simply removing the lines from the Caffe2Targets.cmake and seeing if everything still works.

**Comment by rgommers** [comment]
> However we then manually finangle the binary ourselves and copy culibos into it, and then fudge the rpath to point to the culibos that we ship with the binary (e.g. https://github.com/pytorch/builder/blob/master/conda/pytorch-nightly/build.sh ). Now the generated dependency in Caffe2Targets.cmake should not exist, no matter what the path to culibos should be.

Ah yes. I don't quite see where that happens (the finangling, not the rpath changes), but  there's no `libculibos.a` in the nightly static or shared binaries and no linking to it from the `libcaffe` or `libtorch` shared libs. So that all looks fine.

Now of course the removal of that dependency is specific to the binaries, for anyone building from source the dependency should stay.

> I may have been wrong in my diagnosis; I was never that great at figuring out where c++ dependencies come from.

I think it's CMake not you:) It also hurts my head.

> I guess my theory could be tested easily by simply removing the lines from the Caffe2Targets.cmake and seeing if everything still works.

I'll give that a try.

**Comment by rgommers** [comment]
To add the info from gh-15828 (closed as a duplicate): instead of hardcoding `.a`, the library extension should be made platform-dependent with `CMAKE_SHARED_LIBRARY_SUFFIX` (on linux/macos it's `.a`, on Windows `.lib`).

**Comment by rgommers** [comment]
PR opened with a summary of the issue. Here are some more extensive notes, they may be helpful for people running into this issue or related ones:

Ensure your CUDA install is working. E.g. build `/opt/cuda/samples` (Arch Linux), see https://wiki.archlinux.org/index.php/GPGPU#CUDA

Ensure `CUDA_HOME` is set correctly:
```
$ echo $CUDA_HOME
/opt/cuda
```

And another check that things are as they should be:
```
$ sudo ldconfig -p | grep -i libcuda
        libcudart.so.10.1 (libc6,x86-64) => /opt/cuda/lib64/libcudart.so.10.1
        libcudart.so (libc6,x86-64) => /opt/cuda/lib64/libcudart.so
        libcuda.so.1 (libc6,x86-64) => /usr/lib/libcuda.so.1
        libcuda.so (libc6,x86-64) => /opt/cuda/lib64/libcuda.so
        libcuda.so (libc6,x86-64) => /usr/lib/libcuda.so
```

Now compiling `example_app` from the [Loading a PyTorch model in C++ tutorial](https://pytorch.org/tutorials/advanced/cpp_export.html) gives the `libculibos` error. It shouldn't be needed anyway, so remove it from `libtorch/share/cmake/Caffe2/Caffe2Targets.cmake`. This line:
```
INTERFACE_LINK_LIBRARIES "caffe2::cudart;c10_cuda;caffe2;caffe2::cufft;caffe2::curand;caffe2::cudnn;/usr/local/cuda/lib64/libculibos.a;dl;/usr/local/cuda/lib64/libculibos.a;caffe2::cublas"
```

Another issue can occur when you have a `conda` environment active, you may get
linker issues like `/path/to/ld: cannot find -lcuda`.

The `samples` tests above contain `-lcuda`, `-lcudart` and `-lcudart_static`,
so if you get the error, try deactivate all `conda` envs.

All files appear to be in the right place, so for `conda` it's an include path
issue. There are many issues with the linker `conda` ships (it's usually
located in `anaconda3/compiler_compat/` and is safe to rename to `_ld` or
remove).

```
/opt/cuda/include/cuda.h
/opt/cuda/lib/libcuda.so -> /usr/lib/libcuda.so
/opt/cuda/lib64/libcuda.so -> /usr/lib/libcuda.so
```

cmake -DCMAKE_PREFIX_PATH=/home/rgommers/code/tmp/issue15476/libtorch ..

Create a file `build_example.sh` with contents:
```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/home/rgommers/code/tmp/issue15476/libtorch ..
make
cd ..
./build/example_app model.pt
```

This will build the extension (ending with `[100%] Built target example-app`)
and load the model into it:
```
$ source build_example.sh
$ ./build/example_app model.pt
ok
```

Full build log for `example_app`:

<details>

```
$ source build_example.sh 
-- The C compiler identification is GNU 9.1.0
-- The CXX compiler identification is GNU 9.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda (found version "10.1") 
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /opt/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /opt/cuda
-- Caffe2: Header version is: 10.1
-- Found CUDNN: /usr/include  
-- Found cuDNN: v7.6.1  (include: /usr/include, library: /usr/lib/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Found torch: /home/rgommers/code/tmp/issue15476/libtorch/lib/libtorch.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rgommers/code/tmp/issue15476/build
Scanning dependencies of target example-app
[ 50%] Building CXX object CMakeFiles/example-app.dir/example-app.cpp.o
[100%] Linking CXX executable example-app
[100%] Built target example-app
```

</details>


This is how the generated `Caffe2Targets.cmake` looks (relevant line only):
```
INTERFACE_LINK_LIBRARIES "caffe2::cudart;c10_cuda;caffe2;caffe2::cufft;caffe2::curand;caffe2::cudnn;/usr/local/cuda/lib64/libculibos.a;dl;/usr/local/cuda/lib64/libculibos.a;caffe2::cublas"
```

For static linking, as done in the libtorch binaries build, the `libculibos.a`
entries should simply disappear.  For dynamic linking, there should be one
entry (without the full path).

```
INTERFACE_LINK_LIBRARIES "caffe2::cudart;c10_cuda;caffe2;caffe2::cufft;caffe2::curand;caffe2::cudnn;caffe2::cublas"
```

In `tools/setup_helpers/cmake.py`, `USE_CUDA_STATIC_LINK` (an env var that is
_only_ used by `pytorch/builder`, set to 1 there) sets `CAFFE2_STATIC_LINK_CUDA`.



To test, set `export CAFFE2_STATIC_LINK_CUDA=1` and rebuild. Then check the
generated `Caffe2Targets.cmake`.
Need to set `GLOO_USE_CUDA` as well (set to 0).


The ones that go wrong all use a `list(APPEND)` to collect libraries, and then
use them like so:
```
target_link_libraries(torch PUBLIC ${Caffe2_PUBLIC_DEPENDENCY_LIBS})
```

This is true not only for `libculibos.a` but also for Gloo which gets
`libcudart` wrong :
```
INTERFACE_LINK_LIBRARIES "/usr/local/cuda/lib64/libcudart.so;gloo;
```

It seems like this does preserve variables:
```
set_property(
      TARGET caffe2::cudart PROPERTY INTERFACE_LINK_LIBRARIES
      "${CUDA_TOOLKIT_ROOT_DIR}/lib64/libcudart_static.a" rt dl)
```

```
$ grin "usr/local/cuda"  # in libtorch from nightly binary
./share/cmake/Caffe2/Caffe2Targets.cmake:
   83 :   INTERFACE_LINK_LIBRARIES "caffe2::cudart;c10_cuda;caffe2;caffe2::cufft;caffe2::curand;caffe2::cudnn;/usr/local/cuda/lib64/libculibos.a;dl;/usr/local/cuda/lib64/libculibos.a;caffe2::cublas"
./share/cmake/Caffe2/Modules_CUDA_fix/upstream/FindCUDA.cmake:
   34 : # ``CUDA_BIN_PATH=/usr/local/cuda1.0`` instead of the default
   35 : # ``/usr/local/cuda``) or set ``CUDA_TOOLKIT_ROOT_DIR`` after configuring.  If
  939 :     list(APPEND CUDA_LIBRARIES -Wl,-rpath,/usr/local/cuda/lib)
./share/cmake/Gloo/GlooTargets.cmake:
   58 :   INTERFACE_LINK_LIBRARIES "/usr/local/cuda/lib64/libcudart.so;\$<LINK_ONLY:pthread>"
   74 :   INTERFACE_LINK_LIBRARIES "/usr/local/cuda/lib64/libcudart.so;gloo;/pytorch/build/nccl/lib/libnccl_static.a;dl;rt"
```

This is what `cmake/public/cuda.cmake` says:
```
# Create new style imported libraries.
# Several of these libraries have a hardcoded path if CAFFE2_STATIC_LINK_CUDA
# is set. This path is where sane CUDA installations have their static
# libraries installed. This flag should only be used for binary builds, so
# end-users should never have this flag set.
```

So obviously not all CUDA installs are "sane" ...

`libcudart` shows it better:
```
./share/cmake/Caffe2/Modules_CUDA_fix/upstream/FindCUDA.cmake:
  908 :         message(WARNING "Expecting to find librt for libcudart_static, but didn't find it.")
./share/cmake/Caffe2/public/cuda.cmake:
   15 :  # to a dynamic libcudart.so, but that's just wasteful
  198 :         "${CUDA_TOOLKIT_ROOT_DIR}/lib64/libcudart_static.a" rt dl)
./share/cmake/Gloo/GlooTargets.cmake:
   58 :   INTERFACE_LINK_LIBRARIES "/usr/local/cuda/lib64/libcudart.so;\$<LINK_ONLY:pthread>"
   74 :   INTERFACE_LINK_LIBRARIES "/usr/local/cuda/lib64/libcudart.so;gloo;/pytorch/build/nccl/lib/libnccl_static.a;dl;rt"
./share/cmake/Torch/TorchConfig.cmake:
   62 :       ${CUDA_TOOLKIT_ROOT_DIR}/lib/libcudart.dylib
```


This way the variable does not get expanded but used as is (see also `dl` vs
`"dl"` in the `target_link_libraries` approach:
```
if(CAFFE2_STATIC_LINK_CUDA)
    set_property(
        TARGET torch::cudart PROPERTY INTERFACE_LINK_LIBRARIES
        "${CUDA_TOOLKIT_ROOT_DIR}/lib64/libcudart_static.a" rt dl)
```

**Comment by WikiChao** [comment]
> Bandaid solution:
> 
> In the file `/path/to/libtorch/share/cmake/Caffe2/Caffe2Targets.cmake`
> 
> Replace the references to `/usr/local/cuda/...` with what ever path your CUDA is installed to

This solution works for me.
