### ISSUE TITLE
`nn.RNN(...).to('cuda')` fails with `cuDNN error: CUDNN_STATUS_BAD_PARAM` on GPU, but works on CPU

### ISSUE THREAD

**Issue by tinywisdom** [pytorch/pytorch#155798]
### 🐛 Describe the bug

I’d like to report an issue where a simple `nn.RNN` model runs correctly on CPU but fails on CUDA with a `cuDNN_STATUS_BAD_PARAM` error during model transfer `(.to('cuda'))`. This suggests a problem with cuDNN parameter initialization during `flatten_parameters()`.

## Minimal Reproduction
```python
import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size):
        super(MyModel, self).__init__()
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        out, _ = self.rnn(x)
        out = self.fc(out[:, -1, :])
        return out

def my_model_function():
    return MyModel(input_size=10, hidden_size=20, num_layers=2, output_size=5)

def GetInput():
    return torch.randn(4, 8, 10)

if __name__ == "__main__":
    # Runs fine on CPU
    model = my_model_function().to("cpu")
    input_tensor = GetInput().to("cpu")
    output = model(input_tensor)
    print(output.shape)
    print("CPU output ok!")

    # Fails on GPU
    cuda_model = my_model_function().to("cuda")
    cuda_input = GetInput().to("cuda")
    cuda_output = cuda_model(cuda_input)
    print(cuda_output.shape)
    print("GPU output ok!")
```

## Error Trace (sanitized)
```
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
  File ".../torch/nn/modules/rnn.py", line 271, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(...)
  File ".../torch/nn/modules/rnn.py", line 215, in _init_flat_weights
    self.flatten_parameters()
  File ".../torch/nn/modules/rnn.py", line 290, in _apply
    self._init_flat_weights()
  File ".../torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
  File ".../torch/nn/modules/module.py", line 1355, in to
    return self._apply(convert)
```

## Observations
+ The model uses only standard PyTorch modules (`nn.RNN` and `nn.Linear`).

+ Model runs fine on CPU.

+ Fails immediately upon `to('cuda')`, during the `RNN` weight flattening for `cuDNN`.

+ Error does not depend on input data or forward pass—it happens during `.to("cuda")`.

### Versions

<details> <summary>Click to expand log</summary>

```
PyTorch version: 2.7.1a0+gite2d141d
Is debug build: True
CUDA used to build PyTorch: 12.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.8.0-59-generic-x86_64-with-glibc2.35
Is CUDA available: True

torch.backends.cudnn.version(): 8907
```

</details>

**Comment by malfet** [comment]
@tinywisdom and what that GPU you are running it on?

Removing need reproduction, it fails on A10g with exactly the message

**Comment by tinywisdom** [comment]
> [@tinywisdom](https://github.com/tinywisdom) and what that GPU you are running it on?
> 
> Removing need reproduction, it fails on A10g with exactly the message

Thanks for your help. Both RTX A6000 and RTX 5880 Ada Generation have the same output.

**Comment by eqy** [comment]
@tinywisdom I could not repro the issue going as far back as cuDNN 9.8.0 on RTX 6000 Ada

Could you share which version of cuDNN etc. you are running with `python torch/utils/collect_env.py` or `torch.backends.cudnn.version()` ?

**Comment by malfet** [comment]
Ok, my local setup is on really CuDNN-8.9, which has this problem, but if I'm to update to cudnn-9, it all seems to be fine...

**Comment by tinywisdom** [comment]
> [@tinywisdom](https://github.com/tinywisdom) I could not repro the issue going as far back as cuDNN 9.8.0 on RTX 6000 Ada
> 
> Could you share which version of cuDNN etc. you are running with `python torch/utils/collect_env.py` or `torch.backends.cudnn.version()` ?

The output of `collect_env.py` is like:
```
Collecting environment information...
PyTorch version: 2.7.1a0+gite2d141d
Is debug build: True
CUDA used to build PyTorch: 12.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.8.0-59-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000
GPU 4: NVIDIA RTX 5880 Ada Generation
GPU 5: NVIDIA RTX 5880 Ada Generation
GPU 6: NVIDIA RTX 5880 Ada Generation
GPU 7: NVIDIA RTX 5880 Ada Generation

Nvidia driver version: 570.133.07
cuDNN version: Probably one of the following:
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn.so.8.9.7
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.7
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.7
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.7
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.7
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.7
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        52 bits physical, 57 bits virtual
Byte Order:                           Little Endian
CPU(s):                               64
On-line CPU(s) list:                  0-63
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Xeon(R) Gold 6426Y
CPU family:                           6
Model:                                143
Thread(s) per core:                   2
Core(s) per socket:                   16
Socket(s):                            2
Stepping:                             8
CPU max MHz:                          4100.0000
CPU min MHz:                          800.0000
BogoMIPS:                             5000.00
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect user_shstk avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req hfi vnmi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr ibt amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
Virtualization:                       VT-x
L1d cache:                            1.5 MiB (32 instances)
L1i cache:                            1 MiB (32 instances)
L2 cache:                             64 MiB (32 instances)
L3 cache:                             75 MiB (2 instances)
NUMA node(s):                         2
NUMA node0 CPU(s):                    0-15,32-47
NUMA node1 CPU(s):                    16-31,48-63
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI BHI_DIS_S
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] flake8==7.2.0
[pip3] mypy==1.15.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-cusparselt-cu12==0.6.2
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] onnx==1.18.0
[pip3] onnx-ir==0.1.1
[pip3] onnxruntime-gpu==1.20.0
[pip3] onnxruntime-training==1.17.1
[pip3] onnxscript==0.3.0
[pip3] optree==0.14.1
[pip3] pytorch-lightning==2.5.1
[pip3] pytorch-triton==3.1.0+5fe38ffd73
[pip3] torch==2.7.1a0+gite2d141d
[pip3] torch-xla==2.7.0
[pip3] torchaudio==2.6.0
[pip3] torchdata==0.11.0
[pip3] torchmetrics==1.7.0
[pip3] torchvision==0.22.1+59a3e1f
[pip3] triton==3.2.0
[conda] Could not collect
```

What's more: `torch.backends.cudnn.version()` is 8907? Is this the crux of the matter?

**Comment by eqy** [comment]
@tinywisdom I don't have a system with 8.9 offhand but I would guess so as that's the common factor in the reproductions so far

8.9 is quite old and I'm guessing there might have been a compatibility race-condition when we bumped to 9.1 and we stopped doing upstream + cuDNN 8.9 builds https://github.com/pytorch/pytorch/pull/122011

**Comment by tinywisdom** [comment]
@eqy 
Thanks a lot for the insight — really appreciate it!

You were absolutely right: after upgrading to cuDNN 9.3.0, the issue no longer occurs on my side. This strongly suggests it was indeed tied to compatibility quirks or regressions with cuDNN 8.9, just as you suspected.

Hopefully in the future, PyTorch’s installation or compatibility checks can include stricter enforcement or clearer guidance on supported cuDNN versions, so that similar runtime issues can be avoided earlier in the pipeline.

Thanks again for the fast and helpful response!
