### ISSUE TITLE
I kept got the OOM exception no matter how many resources we allocated to the program?

### ISSUE THREAD

**Issue by fooSynaptic** [pytorch/pytorch#15696]
## 🐛 Bug

I have four RTX-2080 on my machine. and i was start to train models with pytorch in my machine(i used tensorflow before), while i trying to use the cuda in pytorch, i kept got the OOM exception even
set three devices to the program, which make me very confused.

Is this a device drive issue？

My code is just the tutorial sample code from 
https://pytorch.org/tutorials/_downloads/a96a2daac1918ec72f68233dfe3f2c47/seq2seq_translation_tutorial.py

**Comment by fooSynaptic** [comment]
I can run my model on the gtx1080, which is the device drive issue in my view.
Any one can give some formal explaination?

**Comment by ailzhang** [comment]
Hmmm the example code runs fine on my Volta with CUDA10 pytorch conda binary. I don't have a Turing GPU to repro this issue atm. cc: @soumith

**Comment by ailzhang** [comment]
Closing as not reproducible, if you still have the problem, please reopen using `collect_env.py` outputs. Thanks!

**Comment by fooSynaptic** [comment]
@ailzhang I solved this issue with preview torch_nightly installed, Thank you.
