### ISSUE TITLE
libtorch consumes quite much more memory than  python inference

### ISSUE THREAD

**Issue by xinheblue** [pytorch/pytorch#15790]
We have a  model trained and tested in python, being able to process image with resolution of 4512*3000,
the machine is GTX 1070 Ti with 8G Memory

later we export the model with torch.jit.trace and infer with libtorch c++ api, we found that it can only process image less then 3007 * 1999, otherwise it complain about CUDA out of memory

what's the issue and how we can solve this problem

**Comment by ezyang** [comment]
Is it possible for you to post your model and/or share more details about how you are doing inference with the libtorch c++ API?

**Comment by xinheblue** [comment]
@ezyang the following is my test code for reproduction in my machine, with gtx 1070 ti, 8G memory, if the memory varies, you can change the IMAGE SIZE

#the python code for creating a model and export with jti
`import torch
import torch.nn as nn

class MyNet(nn.Module):

    def __init__(self, layer = 10):
        super(MyNet, self).__init__()
        layers = [
            nn.Conv2d(3, 24, kernel_size=3, stride=1, padding=1, dilation=1, bias=False),
            nn.BatchNorm2d(24),
            nn.LeakyReLU(0.2, inplace=True),
        ]

        for l in range(1, layer):
            layers += [nn.Conv2d(24,  24, kernel_size=3, stride=1, padding=2**l,  dilation=2**l,  bias=False),
                       nn.BatchNorm2d(24),
                       nn.LeakyReLU(0.2, inplace=True)]
        layers += [
            nn.Conv2d(24, 24, kernel_size=3, stride=1, padding=1, dilation=1, bias=False),
            nn.BatchNorm2d(24),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(24,  3, kernel_size=1, stride=1, padding=0, dilation=1)
        ]

        net = nn.Sequential(*layers)
        self.net = net

    def forward(self, x):
        out = self.net(x)
        return out

model = MyNet().cuda()

IMAGE_SIZE = 1300
example = torch.rand(1, 3, IMAGE_SIZE, IMAGE_SIZE).cuda()

out = model(example)

print("out shape", out.shape)

# Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.
traced_script_module = torch.jit.trace(model, example)

# save
traced_script_module.save("model.pt")`

#the code for test in libtorch c++, both tested in windows and linux, with cuda version of lib downloaded from pytorch.org

`#include <torch/script.h> // One-stop header.

#include <iostream>
#include <memory>

int main(int argc, const char* argv[]) {
  if (argc != 2) {
    std::cerr << "usage: example-app <path-to-exported-script-module>\n";
    return -1;
  }

  // Deserialize the ScriptModule from a file using torch::jit::load().
  std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(argv[1]);

  assert(module != nullptr);
  std::cout << "ok\n";

  // Create a vector of inputs.
  std::vector<torch::jit::IValue> inputs;
  inputs.push_back(torch::ones({1, 3, 1300, 1300}).to(at::kCUDA));

  // Execute the model and turn its output into a tensor.
  auto output = module->forward(inputs).toTensor().to(at::kCUDA);

  std::cout << output.slice(/*dim=*/1, /*start=*/0, /*end=*/5) << '\n';
}
`

#the same size of input, the python version print the result,while the c++ version complains about cuda memory error

**Comment by xinheblue** [comment]
in fact,in my machine, the c++ version, with the same model,can only process nearly half the resolution with the python version

**Comment by soumith** [comment]
we fixed this issue btw in latest nightly of libtorch. It had to do with not linking CuDNN with libtorch binaries.

Download the Preview build of libtorch and see if that fixes your issue.
The fixes will be part of 1.0.1 release.

**Comment by xinheblue** [comment]
@soumith I have tested the preview build in my application with both linux and windows system, the problem has been solved. Thank so much for the great work!

**Comment by dawnwch** [comment]
I have the same question, and I also download the Preview build of libtorch, but it does't work
