### ISSUE TITLE
Add official support for CUDA sm_120 (RTX 5090 / Blackwell architecture)

### ISSUE THREAD

**Issue by Abeer-2023** [pytorch/pytorch#159207]
## 🚀 The Feature

Please add official support for **CUDA Compute Capability sm_120**, which corresponds to NVIDIA’s Blackwell architecture (e.g., RTX 5090 GPUs).

## Motivation, Pitch

Many researchers and professionals have already adopted RTX 5090 and other Blackwell-based GPUs. Currently, the latest PyTorch stable releases support only up to sm_90. Running models on these new GPUs leads to errors like:

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

<img width="1270" height="919" alt="Image" src="https://github.com/user-attachments/assets/7a4d0606-427a-4f40-859e-15ce60c54549" />

### Alternatives

Users are forced to either build PyTorch from source or use experimental nightly builds with limited platform support.

Adding sm_120 support will:

- Enable full compatibility for cutting-edge hardware
- Support researchers and labs relying on high-performance GPUs
- Eliminate barriers for Windows and non-developer users

## Alternatives

Some workarounds exist (e.g., building from source with `TORCH_CUDA_ARCH_LIST="sm_120"`), but this is not ideal for most users.

## Additional context

NVIDIA has already released public drivers and CUDA 12.4+/12.5 toolkits that support sm_120. Nightly builds (as of early 2025) support sm_120 partially for Linux. However, **official support in stable PyTorch builds is still missing.**

A stable release with sm_120 support would be highly appreciated.

Thanks a lot for your great work!

### Additional context

 using PyTorch. I recently upgraded my hardware to an NVIDIA RTX 5090, which is based on the Blackwell architecture (sm_120).

Unfortunately, the current stable PyTorch release does not support this architecture, making it impossible to run or test models without building from source or switching to Linux with nightly builds. This presents a significant barrier to reproducibility and research progress, especially for Windows-based environments.

Adding official support for sm_120 in stable Windows builds would benefit a growing number of researchers, developers, and institutions already adopting RTX 50-series GPUs.

Thank you again for your continued efforts and support for the PyTorch community.

**Comment by malfet** [comment]
Can you run `python3 -mtorch.utils.collect_env` or at least tell me what PyTorch version you are trying to install, on what OS and how you've downloaded the binaries. 
Blackwell support was added in 2.7, but you need to install cuda-12.8 binaries, as 12.7 does not support them...

**Comment by Abeer-2023** [comment]
I am currently testing PyTorch on a workstation equipped with an NVIDIA RTX 5090 GPU (Blackwell architecture), running Windows 11 Pro, and I encountered a critical compatibility issue.

I installed PyTorch using the official pip command:
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124


This installed torch 2.6.0 with CUDA 12.4, but unfortunately this version does not support the RTX 5090 (compute capability sm_120). Any CUDA-related operation fails with the following runtime error:
RuntimeError: CUDA error: no kernel image is available for execution on the device
I understand from recent discussions that support for Blackwell GPUs was added in PyTorch 2.7.0 and requires CUDA 12.8. However, at the time of writing, there is no official Windows pip or conda binary for torch==2.7.0 with cu128.

I would appreciate it if you could provide the following:

-An estimated timeline for the official release of PyTorch 2.7.0 (or later) with CUDA 12.8 support for Windows.
-Any recommended workaround or nightly build that supports sm_120 on Windows in the meantime.

Unfortunately, I am unable to run python3 -m torch.utils.collect_env as the current build fails to initialize CUDA kernels on this GPU.

Thank you for your question.

**Comment by sangoi-exe** [comment]
@Abeer-2023 `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128`

<img width="968" height="621" alt="Image" src="https://github.com/user-attachments/assets/1b692e08-ed5b-43de-8aa0-befcfbb89469" />

**Comment by Abeer-2023** [comment]
unfortunately the problem is still . even if I change libraries to compatible with new GPU

<img width="668" height="321" alt="Image" src="https://github.com/user-attachments/assets/c6806864-46a7-4bf6-82b5-e3106186275d" />

<img width="1403" height="227" alt="Image" src="https://github.com/user-attachments/assets/524911af-5e26-4ded-8c87-d7fa719085c9" />

**Comment by Pete-LunaNova** [comment]
I have a server with 8 x Nvidia RTX Pro 6000 Blackwell GPUs installed and am currently passing them through to the vllm-openai docker image to run a deepseek model. If I restrict to just passing through 4 GPUs this works without issue. However if I pass through 8 GPUs it fails. 

I have entered the docker container and launched python3. Running `torch.cuda.device_count()` will return the correct number of GPUs. However if I run `torch.cuda.is_available()` it only returns `True` when 6 or fewer GPUs are passed through. With 7 or 8 it returns `False` and the following message:

```
/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py:174: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
```


I have tested this with the stock vllm-openai image `v0.10.0` and also modifying this to upgrade to cuda 12.9 and install the latest pytorch with the following command:

`pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu129`
_(curiously this returns that it is installing pytorch 2.7.1 and not 2.8.0 though)_

I would be grateful for any assistance to get all 8 GPUs working please. I’m happy to post as a separate issue if that is preferable.

**Comment by Pete-LunaNova** [comment]
If anyone else encounters problems running multiple Blackwell GPUs, as I've described above: it turns out it is caused by a current issue with HMM (Heterogenous Memory Management) initialization. There are 2 known workarounds:

1) Disable KASLR (Kernel Address Space Layout Randomization)
2) Disable HMM

The following Nvidia docs page has details on how to implement either of these options: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id5

**Comment by rebel47** [comment]
> unfortunately the problem is still . even if I change libraries to compatible with new GPU
> 
> <img alt="Image" width="668" height="321" src="https://private-user-images.githubusercontent.com/146803601/471967573-c6806864-46a7-4bf6-82b5-e3106186275d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkxMjA4NTEsIm5iZiI6MTc1OTEyMDU1MSwicGF0aCI6Ii8xNDY4MDM2MDEvNDcxOTY3NTczLWM2ODA2ODY0LTQ2YTctNGJmNi04MmI1LWUzMTA2MTg2Mjc1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyOVQwNDM1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWM5NjZlZmM4ZmM4Y2Q3YTAwZTJhYWYwNTA3MTNhYjMyMWZiYzJmZDU3MTk0YzNlNzZiMDc2MGVhMDVhYjIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.muXqCMY-6PwYKo55mVfTXu0pSzj9XQwMJrVvvXfKp40"> <img alt="Image" width="1403" height="227" src="https://private-user-images.githubusercontent.com/146803601/471968220-524911af-5e26-4ded-8c87-d7fa719085c9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkxMjA4NTEsIm5iZiI6MTc1OTEyMDU1MSwicGF0aCI6Ii8xNDY4MDM2MDEvNDcxOTY4MjIwLTUyNDkxMWFmLTVlMjYtNGRlZC04Yzg3LWQ3ZmE3MTkwODVjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyOVQwNDM1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmM1NDY5ZDEzNjU2ZDk3MGRjODViMzc3NDEzYmZjYTJhYjU1YTViZjdlNjY4NjUzMGFmNThjMGUxZDMwZGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XfbNqWNTf-LGtslnPH6WyupLwWAAgq3INllSAsN2vQU">

did you find any solutions??

**Comment by Abeer-2023** [comment]
Unfortantlly no , when I found message I thout the new archticture is
aviailable

I hope for you to find the solution as soon as possible


في اثنين، ٢٩ سبتمبر، ٢٠٢٥ في ٧:٣٨ ص، كتب Mohammad Ayaz Alam <
***@***.***>:

**Comment by flatwater-dev** [comment]
Hi — first time commenter. Sharing hardware data in hopes it helps.

RTX 5080 16GB, Ubuntu 24.04, PyTorch 2.11.0.dev20260112+cu128
Device capability: (12, 0) — sm_120 detected correctly.

Conv3d VAE memory bug confirmed — approximately 3x expected VRAM allocation during VAE encoding phase. Workaround active. Production workflow stable at 5600px long side with 7B FP16, blocks_to_swap=36, swap_io_components=True.

Use case: batch photography restoration for client archive work. Resolution ceiling directly impacts deliverable quality. A Conv3d fix would meaningfully expand what's possible on 16GB Blackwell hardware.

Happy to run specific tests or provide additional data if useful to the investigation. Thank you to everyone contributing to sm_120 support.

**Comment by NominekAI** [comment]
Update: cu128 nightly resolved this on Windows 11. pip install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu128 followed by pip install packaging. RTX Pro 4000 Blackwell (sm_120) now recognised with CUDA available: True. May be useful to others hitting this on Window

**Comment by Noctropolitan** [comment]
I'm trying to use ComfyUi with my RTX 5080, but I'm having really low it/s on Windows. Trying to fix the issue with no luck. Hitting the wall described in https://www.cloudrift.ai/blog/beating-cublas-on-rtx-5090 about MatMul/cuBLAS Inefficiency: Reports indicate that cuBLAS currently dispatches inefficient kernels for batch FP32 matmul workloads, using only ~40% of available compute on 50-series cards, resulting in a potential 60% performance loss.
RTX 5080, cu128, 112 TFLOPS vs ~200 it should have.
ms/iter: 6.74
NVIDIA-SMI 596.21  Driver Version: 596.21  CUDA Version: 13.2
The GPU has a correct performance in rasterization (like games) 98%.
I'm at ~4 it/s, benchmarks with my same GPU show that it should be much higher.
No energy limitation, no PCI bus issues.

Tested official repository, Hiroki Abe's, Wildminder's wheels, different pytorch versions, etc... Nothing works. Either performance stays the same, or it goes even worse with some stuff I've tried. I've been stuck with this for two straight weeks.
