### ISSUE TITLE
not support nvidia 5060

### ISSUE THREAD

**Issue by tuqizhao** [pytorch/pytorch#159446]
### 🐛 Describe the bug

1. nvidia 5060， lowest driver is 576.52, latest is 577.00, cuda 12.9 (can’t not down to 12.8 cause has no the driver)
PS C:\Users\Administrator> nvidia-smi.exe
Wed Jul 30 12:11:18 2025
±----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.52 Driver Version: 576.52 CUDA Version: 12.9 |

2. latest torch version is 2.7.1 cuda 12.8

import torch
torch.version
‘2.7.1+cu128’

run failed and get the error：

RuntimeError: CUDA error: device kernel image is invalid

CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.

For debugging consider passing CUDA_LAUNCH_BLOCKING=1

Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

### Versions

run hubert get the same error:

from os.path import dirname
from transformers import Wav2Vec2Processor, HubertModel
import soundfile as sf
import numpy as np
import torch
import os

import soundfile as sf
import numpy as np
import torch
from argparse import ArgumentParser
import librosa

local_path = os.path.join(os.getenv('HF_HOME',  os.path.join(os.getenv('USERPROFILE'), '.cache/huggingface'))
                              , 'hub/models--facebook--hubert-large-ls960-ft/snapshots/ece5fabbf034c1073acae96d5401b25be96709d8')

print("Loading the Wav2Vec2 Processor...")
wav2vec2_processor = Wav2Vec2Processor.from_pretrained(local_path)
print("Loading the HuBERT Model...")
hubert_model = HubertModel.from_pretrained(local_path, torch_dtype=torch.float16)
hubert_model.to("cuda:0")

def get_hubert_from_16k_wav(wav_16k_name):
    speech_16k, _ = sf.read(wav_16k_name)
    hubert = get_hubert_from_16k_speech(speech_16k)
    return hubert

@torch.no_grad()
def get_hubert_from_16k_speech(speech, device="cuda:0"):
    global hubert_model
    # hubert_model = hubert_model.to(device)
    if speech.ndim ==2:
        speech = speech[:, 0] # [T, 2] ==> [T,]
    input_values_all = wav2vec2_processor(speech, return_tensors="pt", sampling_rate=16000).input_values # [1, T]
    input_values_all = input_values_all.to(device, dtype=torch.float16)
    # For long audio sequence, due to the memory limitation, we cannot process them in one run
    # HuBERT process the wav with a CNN of stride [5,2,2,2,2,2], making a stride of 320
    # Besides, the kernel is [10,3,3,3,3,2,2], making 400 a fundamental unit to get 1 time step.
    # So the CNN is euqal to a big Conv1D with kernel k=400 and stride s=320
    # We have the equation to calculate out time step: T = floor((t-k)/s)
    # To prevent overlap, we set each clip length of (K+S*(N-1)), where N is the expected length T of this clip
    # The start point of next clip should roll back with a length of (kernel-stride) so it is stride * N
    kernel = 400
    stride = 320
    clip_length = stride * 1000
    num_iter = input_values_all.shape[1] // clip_length
    expected_T = (input_values_all.shape[1] - (kernel-stride)) // stride
    res_lst = []
    for i in range(num_iter):
        if i == 0:
            start_idx = 0
            end_idx = clip_length - stride + kernel
        else:
            start_idx = clip_length * i
            end_idx = start_idx + (clip_length - stride + kernel)
        input_values = input_values_all[:, start_idx: end_idx]
        hidden_states = hubert_model.forward(input_values).last_hidden_state # [B=1, T=pts//320, hid=1024]
        res_lst.append(hidden_states[0])
    if num_iter > 0:
        input_values = input_values_all[:, clip_length * num_iter:]
    else:
        input_values = input_values_all
    # if input_values.shape[1] != 0:
    if input_values.shape[1] >= kernel: # if the last batch is shorter than kernel_size, skip it            
        hidden_states = hubert_model(input_values).last_hidden_state # [B=1, T=pts//320, hid=1024]
        res_lst.append(hidden_states[0])
    ret = torch.cat(res_lst, dim=0) #.cpu() # [T, 1024]
    # assert ret.shape[0] == expected_T
    assert abs(ret.shape[0] - expected_T) <= 1
    if ret.shape[0] < expected_T:
        ret = torch.nn.functional.pad(ret, (0,0,0,expected_T-ret.shape[0]))
    else:
        ret = ret[:expected_T]
    return ret

def make_even_first_dim(tensor):
    size = list(tensor.size())
    if size[0] % 2 == 1:
        size[0] -= 1
        return tensor[:size[0]]
    return tensor

def main():
    parser = ArgumentParser()
    parser.add_argument('--wav', type=str, help='')
    args = parser.parse_args()

    wav_name = args.wav

    speech, sr = sf.read(wav_name)
    speech_16k = librosa.resample(speech, orig_sr=sr, target_sr=16000)
    print("SR: {} to {}".format(sr, 16000))
    # print(speech.shape, speech_16k.shape)

    hubert_hidden = get_hubert_from_16k_speech(speech_16k)
    hubert_hidden = make_even_first_dim(hubert_hidden).reshape(-1, 2, 1024)
    np.save(f'{dirname(wav_name)}/hu.npy', hubert_hidden.detach().cpu().numpy())

    print(hubert_hidden.shape)

if __name__ == '__main__':
    main()

============================== output ====================
File "/data_utils/hubert.py", line 96, in hubert.main
  File "d:\userbin\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data_utils/hubert.py", line 57, in hubert.get_hubert_from_16k_speech
  File "d:\userbin\Lib\site-packages\transformers\models\hubert\modeling_hubert.py", line 1231, in forward
    encoder_outputs = self.encoder(
        hidden_states,
    ...<3 lines>...
        return_dict=return_dict,
    )
  File "d:\userbin\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "d:\userbin\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\userbin\Lib\site-packages\transformers\models\hubert\modeling_hubert.py", line 872, in forward
    position_embeddings = self.pos_conv_embed(hidden_states)
  File "d:\userbin\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "d:\userbin\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\userbin\Lib\site-packages\transformers\models\hubert\modeling_hubert.py", line 74, in forward
    hidden_states = self.conv(hidden_states)
  File "d:\userbin\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "d:\userbin\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\userbin\Lib\site-packages\torch\nn\modules\conv.py", line 375, in forward
    return self._conv_forward(input, self.weight, self.bias)
                                     ^^^^^^^^^^^
  File "d:\userbin\Lib\site-packages\torch\nn\utils\parametrize.py", line 406, in get_parametrized
    return parametrization()
  File "d:\userbin\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "d:\userbin\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\userbin\Lib\site-packages\torch\nn\utils\parametrize.py", line 302, in forward
    x = self[0](*originals)
  File "d:\userbin\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "d:\userbin\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\userbin\Lib\site-packages\torch\nn\utils\parametrizations.py", line 325, in forward
    return torch._weight_norm(weight_v, weight_g, self.dim)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device kernel image is invalid
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @ptrblck @msaroufim @eqy @jerryzh168

**Comment by jlitz** [comment]
I have windows 11  and ran a  script with the following results:

(base) C:\Windows\System32>conda activate forge

(forge) C:\Windows\System32>python
Python 3.10.18 | packaged by Anaconda, Inc. | (main, Jun  5 2025, 13:08:55) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>>
>>> print("Torch version:", torch.__version__)
Torch version: 2.6.0.dev20241112+cu121
>>> print("CUDA version:", torch.version.cuda)
CUDA version: 12.1
>>> print("CUDA available:", torch.cuda.is_available())
CUDA available: True
>>> print("Device count:", torch.cuda.device_count())
Device count: 1
>>>
>>> if torch.cuda.is_available():
...     print("Device name:", torch.cuda.get_device_name(0))
...     # Try to run a CUDA operation
...     try:
...         x = torch.tensor([1.0], device="cuda")
...         print("Tensor on GPU:", x)
...     except Exception as e:
...         print("CUDA operation failed:", e)
... else:
...     print("CUDA is not available.")
...
C:\Users\jlitw\miniconda3\envs\forge\lib\site-packages\torch\cuda\__init__.py:235: UserWarning:
NVIDIA GeForce RTX 5060 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5060 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
Device name: NVIDIA GeForce RTX 5060 Ti
Tensor on GPU: CUDA operation failed: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by eqy** [comment]
@jlitz that appears to be a separate problem as `2.6.0.dev20241112+cu121` is too old to support Blackwell. Please install a CUDA 12.8+ wheel.

**Comment by jlitz** [comment]
I installed the 12.8 version and checked  to confirm still get error on image generation attempt
INSTALLED 12.8 
forgeflux) C:\FORGE\webui_forge_cu121_torch231>python -c "import torch; print(torch.__version__); print(torch.version.cuda)"
2.9.0.dev20250726+cu128
12.8

(forge) C:\Windows\System32>python
Python 3.10.18 | packaged by Anaconda, Inc. | (main, Jun  5 2025, 13:08:55) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>>
>>> print("Torch version:", torch.__version__)
Torch version: 2.9.0.dev20250729+cu128
>>> print("CUDA version:", torch.version.cuda)
CUDA version: 12.8
>>> print("CUDA available:", torch.cuda.is_available())
CUDA available: True
>>> print("Device count:", torch.cuda.device_count())
Device count: 1
>>>
>>> if torch.cuda.is_available():
...     print("Device name:", torch.cuda.get_device_name(0))
...     # Try to run a CUDA operation
...     try:
...         x = torch.tensor([1.0], device="cuda")
...         print("Tensor on GPU:", x)
...     except Exception as e:
...         print("CUDA operation failed:", e)
... else:
...     print("CUDA is not available.")
...
Device name: NVIDIA GeForce RTX 5060 Ti
Tensor on GPU: tensor([1.], device='cuda:0')

THE  COMPLETE RUN INFO 

[Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ... Current free memory is 9897.80 MB ... Done.
Traceback (most recent call last):
  File "C:\FORGE\webui_forge_cu121_torch231\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\FORGE\webui_forge_cu121_torch231\webui\modules\txt2img.py", line 131, in txt2img_function
    processed = processing.process_images(p)
  File "C:\FORGE\webui_forge_cu121_torch231\webui\modules\processing.py", line 842, in process_images
    res = process_images_inner(p)
  File "C:\FORGE\webui_forge_cu121_torch231\webui\modules\processing.py", line 962, in process_images_inner
    p.setup_conds()
  File "C:\FORGE\webui_forge_cu121_torch231\webui\modules\processing.py", line 1601, in setup_conds
    super().setup_conds()
  File "C:\FORGE\webui_forge_cu121_torch231\webui\modules\processing.py", line 503, in setup_conds
    self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, total_steps, [self.cached_uc], self.extra_network_data)
  File "C:\FORGE\webui_forge_cu121_torch231\webui\modules\processing.py", line 474, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps, hires_steps, shared.opts.use_old_scheduling)
  File "C:\FORGE\webui_forge_cu121_torch231\webui\modules\prompt_parser.py", line 189, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "C:\FORGE\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\FORGE\webui_forge_cu121_torch231\webui\backend\diffusion_engine\flux.py", line 86, in get_learned_conditioning
    cond_l, pooled_l = self.text_processing_engine_l(prompt)
  File "C:\FORGE\webui_forge_cu121_torch231\webui\backend\text_processing\classic_engine.py", line 272, in __call__
    z = self.process_tokens(tokens, multipliers)
  File "C:\FORGE\webui_forge_cu121_torch231\webui\backend\text_processing\classic_engine.py", line 305, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "C:\FORGE\webui_forge_cu121_torch231\webui\backend\text_processing\classic_engine.py", line 128, in encode_with_transformers
    self.text_encoder.transformer.text_model.embeddings.position_embedding = self.text_encoder.transformer.text_model.embeddings.position_embedding.to(dtype=torch.float32)
  File "C:\FORGE\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1173, in to
    return self._apply(convert)
  File "C:\FORGE\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 804, in _apply
    param_applied = fn(param)
  File "C:\FORGE\webui_forge_cu121_torch231\system\python\lib\site-packages\torch\nn\modules\module.py", line 1159, in convert
    return t.to(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions
.

**Comment by eqy** [comment]
That still looks like the the wrong binaries are being loaded due to an environment issue.
Does `python3 -c "import torch; print(torch._C._cuda_getArchFlags())"` show `sm120`? If not it means the installed 12.8 wheel binaries are not actually being loaded.

**Comment by jlitz** [comment]
Thanks for your help earlier. I wanted to follow up and let you know that the issue is resolved now.

It turned out the root cause was that the default stable PyTorch build (even with CUDA 12.1) didn’t include support for my GPU’s architecture — the RTX 5060 Ti (sm_120). Once I installed the nightly PyTorch build from https://download.pytorch.org/whl/nightly/cu121, and made sure my environment was using it instead of the bundled one in Forge FluX, the “no kernel image available” error went away.

I also had to fix some other things along the way: CUDA drivers weren’t properly installed after DDU, and Forge was using its own Python instead of the working Conda one. After pointing Forge to the right environment and making sure Git and dependencies were available, everything worked smoothly.

Appreciate your time — and hope this helps if others with new 50-series GPUs hit the same issue.

**Comment by Aidyn-A** [comment]
The issue got resolved in https://github.com/pytorch/pytorch/issues/159446#issuecomment-3138526431. Closing. Please re-open if the issue persists.
