### ISSUE TITLE
why libtorch use more memory than pytorch

### ISSUE THREAD

**Issue by dawnwch** [pytorch/pytorch#16255]
My model trained and tested by pytorch0.4.1 in ubuntu 16.04, the machine is GTX 1080Ti with 11G Memory. When we test the model, it require 1700MB memory.
we export the model with torch.jit.trace and infer with libtorch c++ api, we found that it require 6300MB memory.
If we want to  process image larger than 1280*720, it complain about CUDA out of memory.
We use the Preview build of libtorch.

**Comment by soumith** [comment]
is the libtorch also on Linux 16.04?
Afaik, the specific issue of CuDNN not being enabled has been fixed in the preview builds as of ~2 weeks ago. Which date's preview builds are you on?

Also, can you share your model's checkpoint that you loaded in libtorch?

**Comment by dawnwch** [comment]
the version of preview builds is 1.0.0.dev20190122

**Comment by dawnwch** [comment]
We use cuda9.0 and cudnn7.1.4

**Comment by pared** [comment]
I have similar problem,
can I describe it here, or should I create new issue?

**Comment by zou3519** [comment]
You can check if the libtorch has cudnn statically linked in via `nm lib/libcaffe2_gpu.so | grep sgemm_cudnn` or dynamically linked via `ldd lib/libtorch.so`.  Alternatively, one can run
```
torch::cuda::hasCuDNN()
```
and check if the value is true or false.

**Comment by pared** [comment]
@suo Thanks, here comes my case: 

I am using relatively small, fully convolutional model. I apply it to big input images. 
My Pytorch version: _1.0.0.dev20190104_
My Libtorch version: 1.0.0

Minimal working example:
Script producing model:
```
import torch
import torch.nn as nn
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 8, 3, 1)
        self.conv2 = nn.Conv2d(8, 16, 3, 1)

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        return x
    
model = Net().cuda()
inpt = torch.rand((1, 3, 20, 20)).cuda()
traced = torch.jit.trace(model, inpt)
model_name = 'sample_model.pth'
torch.jit.save(traced, model_name)
```
Script testing model in python:
```
import torch, time
model_name = 'sample_model.pth'
with torch.no_grad():
    traced_model = torch.jit.load(model_name).cuda()
    inpt = torch.rand((1,3,2000,2000)).cuda()
    traced_model(inpt)
    time.sleep(5)
```
Program testing model in C++:
```
#include <torch/script.h> 
#include <iostream>
#include "torch/torch.h"
#include <chrono>
#include <thread>

int main() {
  torch::NoGradGuard guard;
  std::string path = "sample_model.pth";
  torch::Device device(torch::kCUDA);

  std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(path);
  torch::TensorOptions options;
  options.is_variable(false).requires_grad(false);
  torch::Tensor inpt = torch::rand({1, 3, 2000, 2000}, options).to(device);
  module -> forward({inpt});
  std::this_thread::sleep_for(std::chrono::milliseconds(10000));
}
```

Memory usage in both cases:
 - Python:
![output_python](https://user-images.githubusercontent.com/10195618/51746417-57ba5500-20a6-11e9-9efd-c28f6d998d85.png)
 - Cpp:
![output_cpp](https://user-images.githubusercontent.com/10195618/51746426-5ee16300-20a6-11e9-8a31-2b3103d7e27a.png)

**Comment by suo** [comment]
Thanks @pared. Can you use Richard's method above to determine whether you have cudnn linked in, so we can rule that out as a cause?

**Comment by pared** [comment]
@suo I checked, it seems that CuDNN is not linked. Also, I am unable to compile ```torch::cuda::hasCuDNN()``` ('hasCuDNN' is not a member of 'torch::cuda')

@soumith thanks, after swapping current version with nightly, memory usage dropped to 900 MiB.

**Comment by suo** [comment]
Great! Good to hear.

**Comment by suo** [comment]
Whoops, realized that @dawnwch may still be having a problem. @dawnwch, can you follow the same steps to verify whether cudnn is linked in?

**Comment by suo** [comment]
Closing as this hasn't seen any movement. Feel free to reopen if you are still seeing issues

**Comment by adityadhakal** [comment]
Hi, I am having similar problem with CuDNN not being linked with libtorch. I am using 
libtorch nightly build 1.0.0.dev20190210
ubuntu 16.04
cuda 10.0
cuDNN 7.0
I tried compiling a program with `torch::cuda::hasCuDNN()` and I could not compile as well as I could not get any reply from `nm lib/libcaffe2_gpu.so | grep sgemm_cudnn` or `ldd lib/libtorch.so`.
Is there anyway of getting the nightly version that worked for @pared

**Comment by soumith** [comment]
@adityadhakal I've just verified that the stable libtorch and preview libtorch have the cudnn symbols. The link on the website is https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-latest.zip for stable, and https://download.pytorch.org/libtorch/nightly/cu90/libtorch-shared-with-deps-latest.zip for preview.

**Comment by dawnwch** [comment]
Hello, I still have the problem by using the preview builds(1.0.0.dev20190211).
I use `torch::cuda::cudnn_is_available()` to see if CuDNN being linked with libtorch, and the result is `True`.
The model I use is [https://github.com/dawnwch/for-a-libtorch-question](url) (There are ReflectionPad2d, Conv2d, InstanceNorml2d, ReLU,ConvTraansposed2d and Tanh in my model)and the test code is
```cpp
#include <torch/script.h>
#include <torch/torch.h>
#include <iostream>
#include <memory>

int main(int argc, const char* argv[]) {
    std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(argv[1]);
    assert(module != nullptr);
    torch::DeviceType device;
    device = torch::kCUDA;
    module->to(device);
    std::vector<torch::jit::IValue> inputs;
    inputs.push_back(torch::ones({1, 3, 1920, 1080}).to(device));
    at::Tensor output = module->forward(inputs).toTensor();
    std::cout << "Done" << std::endl;
    return 0;
}
```
The error is
```
CUDA out of memory. Tried to allocate 1.11 GiB (GPU 0; 10.91 GiB total capacity; 10.07 GiB already allocated; 121.38 MiB free; 10.18 MiB cached) (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:236)
```

Here is the gpu memory usage I test.
![image](https://user-images.githubusercontent.com/35034417/52633408-3effcb00-2eff-11e9-9628-94ff4d8d18be.png)
Hope for your replay and thanks for your help.

**Comment by DineshRajanT** [comment]
> The code for test in c++
> If we use `cv::resize(resized_image, resized_image, cv::Size(1920, 1080));` it complain about CUDA out of memory.
> 
> ```
> std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(argv[1]);
> assert(module != nullptr);
> 
> torch::DeviceType device_type;
> if (torch::cuda::is_available()) {
>     std::cout << "CUDA available! Training on GPU" << std::endl;
>     device_type = torch::kCUDA;
> } else {
>     std::cout << "Training on CPU" << std::endl;
>     device_type = torch::kCPU;
> }
> torch::Device device(device_type);
> module->to(device);
> 
> cv::Mat origin_image;
> origin_image = cv::imread(dir + fileName);
> 
> cv::Mat resized_image;
> cv::cvtColor(origin_image, resized_image, CV_BGR2RGB);
> cv::resize(resized_image, resized_image, cv::Size(1280, 720));
> 
> cv::Mat img_float;
> resized_image.convertTo(img_float, CV_32FC3, 1.0/255);
> 
> auto img_tensor = torch::from_blob(img_float.data, {1, img_float.rows, img_float.cols, 3}).to(device);
> img_tensor = img_tensor.permute({0, 3, 1, 2});
> 
> // Create a vector of inputs.
> std::vector<torch::jit::IValue> inputs;
> inputs.push_back(img_tensor);
> 
> auto output = module->forward(inputs).toTensor();
> 
> auto img_output = output[0];
> 
> auto img_uint = img_output.toType(torch::kU8);
> 
> auto img = cv::Mat(img_float.rows, img_float.cols, CV_8UC3, img_uint.data_ptr());
> cv::cvtColor(img, img, CV_RGB2BGR);
> ```

Were you able to save the torch tensor as image?

**Comment by pared** [comment]
@DineshRajanT 
The issue described here was not about saving tensor as an image. However, as I remember, in this case I have been creating `OpenCV`'s `Mat` object from tensors and using `OpenCV` to save it. `Mat` creation was happening in following line:
> auto img = cv::Mat(img_float.rows, img_float.cols, CV_8UC3, img_uint.data_ptr());

 Hope that helps.

**Comment by DineshRajanT** [comment]
> @DineshRajanT
> The issue described here was not about saving tensor as an image. However, as I remember, in this case I have been creating `OpenCV`'s `Mat` object from tensors and using `OpenCV` to save it. `Mat` creation was happening in following line:
> 
> > auto img = cv::Mat(img_float.rows, img_float.cols, CV_8UC3, img_uint.data_ptr());
> 
> Hope that helps.

Yes @pared ,but if I give 8UC3 I get a grayscale image in a grid form (3*3 grid) containing the inferred image in a grid.If I give 8UC1 which is a single channel image...I got rid of the grid,however I got only the grayscale image as [output.](url
![blurry](https://user-images.githubusercontent.com/37593528/105351306-66df2980-5c12-11eb-8fbf-d1554934db4b.jpg)
![gggg](https://user-images.githubusercontent.com/37593528/105351311-68105680-5c12-11eb-8800-1b128e9b7471.jpg)
![lmo___color](https://user-images.githubusercontent.com/37593528/105351313-68a8ed00-5c12-11eb-80a7-df512c05ce9b.jpg)


)
