### ISSUE TITLE
clamp incorrectness with mps backend

### ISSUE THREAD

**Issue by bjeurissen** [pytorch/pytorch#167767]
### 🐛 Describe the bug

Using the MPS backend I experienced the following incorrect behavior of torch.clamp:

```python
import torch

a = torch.zeros(1, device='mps')
# the following line triggers the incorrect behavior, when commented, the remainder of the script appears to work as expected
a_clamped = a.clamp(min=0.0)

b = torch.zeros(1, device='mps')
print(b)
c = b.clamp(min=1e-7)
print(c)

b = torch.zeros(1, device='mps')
print(b)
c = b.clamp(min=1e-7, max=None)
print(c)

b = torch.zeros(1, device='mps')
print(b)
c = b.clamp(min=1e-7, max=torch.inf)
print(c)

b = torch.zeros(1, device='mps')
print(b)
c = b.clamp_min(1e-7)
print(c)
```

produces the output:

```
tensor([0.], device='mps:0')
tensor([0.], device='mps:0')
tensor([0.], device='mps:0')
tensor([0.], device='mps:0')
tensor([0.], device='mps:0')
tensor([1.0000e-07], device='mps:0')
tensor([0.], device='mps:0')
tensor([1.0000e-07], device='mps:0')
```

when the the expected outcome, which it does output with the cpu backend, is:

```
tensor([0.], device='mps:0')
tensor([1.0000e-07], device='mps:0')
tensor([0.], device='mps:0')
tensor([1.0000e-07], device='mps:0')
tensor([0.], device='mps:0')
tensor([1.0000e-07], device='mps:0')
tensor([0.], device='mps:0')
tensor([1.0000e-07], device='mps:0')
```

The problem presents consistently on an M1 MacBook running macOS 26.0.1 on torch versions 2.7.1 (python 3.9.6), 2.8.0(python 3.9.6) and 2.9.1(python 3.14.0)

The problem presents consistently, but in a very peculiar way, e.g. commenting line 5, returns the output of the script to normal.

### Versions

The problem presents consistently different torch and python versions:

```
Collecting environment information...
PyTorch version: 2.7.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 26.0.1 (arm64)
GCC version: Could not collect
Clang version: 17.0.0 (clang-1700.3.19.1)
CMake version: version 4.1.2
Libc version: N/A

Python version: 3.9.6 (default, Aug  8 2025, 19:06:38)  [Clang 17.0.0 (clang-1700.3.19.1)] (64-bit runtime)
Python platform: macOS-26.0.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
Is XPU available: False
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1

Versions of relevant libraries:
[pip3] numpy==2.0.2
[pip3] torch==2.7.1
[conda] Could not collect
```

```
Collecting environment information...
PyTorch version: 2.8.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 26.0.1 (arm64)
GCC version: Could not collect
Clang version: 17.0.0 (clang-1700.3.19.1)
CMake version: version 4.1.2
Libc version: N/A

Python version: 3.9.6 (default, Aug  8 2025, 19:06:38)  [Clang 17.0.0 (clang-1700.3.19.1)] (64-bit runtime)
Python platform: macOS-26.0.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
Is XPU available: False
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1

Versions of relevant libraries:
[pip3] numpy==2.0.2
[pip3] torch==2.8.0
[conda] Could not collect
```

```
Collecting environment information...
PyTorch version: 2.9.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 26.0.1 (arm64)
GCC version: Could not collect
Clang version: 17.0.0 (clang-1700.3.19.1)
CMake version: version 4.1.2
Libc version: N/A

Python version: 3.14.0 (main, Oct  7 2025, 09:34:52) [Clang 17.0.0 (clang-1700.3.19.1)] (64-bit runtime)
Python platform: macOS-26.0.1-arm64-arm-64bit-Mach-O
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
Is XPU available: False
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1

Versions of relevant libraries:
[pip3] numpy==2.3.4
[pip3] torch==2.9.1
```

cc @kulinseth @malfet @DenisVieriu97 @jhavukainen

**Comment by jhavukainen** [comment]
Opened a PR for one possible way of fixing this. But I'm open for other suggestions if someone sees a better approach to fixing the keys. Thanks @bjeurissen for reporting the problem.

**Comment by bjeurissen** [comment]
Thanks! I am glad that it was a bug and that I am not losing my mind. I tested the fix in the PR and it indeed fixes the issue.

If I want to keep using 2.9.1 until this PR makes it into a release, exactly what clamp operations should I avoid?

**Comment by jhavukainen** [comment]
That's a great question:  In short calling the `clamp` with different scalar min values that are less than 1e-6 causes them all to get mapped to the first value you used. So in the test case they all map to using min value zero after uncommenting the line that causes the failure to start appearing.

But if you do have the control over which clamp op to call I think I have a reasonable workaround for you: So this specific issue arises in the `clamp_scalar_out_mps` function. However there is an alternative way to call clamp and giving the min (or max) value as a tensor, which ends up calling into `clamp_tensor_out_mps` which stores the tensor signature instead of the value to key. This prevents the issue. So here's how I'd rewrite the repro script you provided using tensors to store the values and produce the correct output with the already released pytorch wheels:

```
import torch

device='mps'
a = torch.zeros(1, device=device)

# Using tensor objects to pass in the min values circumvents the clamp_scalar_out_mps function that has the caching issue
zero_tensor = torch.tensor(0.0, device=device)
min_tensor = torch.tensor(1e-7, device=device)

a_clamped = a.clamp(min=zero_tensor)

b = torch.zeros(1, device=device)
print(b)
c = b.clamp(min=min_tensor)
print(c)

b = torch.zeros(1, device=device)
print(b)
c = b.clamp(min=min_tensor, max=None)
print(c)

b = torch.zeros(1, device=device)
print(b)
c = b.clamp(min=min_tensor, max=torch.inf)
print(c)

b = torch.zeros(1, device=device)
print(b)
c = b.clamp_min(min_tensor)
print(c)

# Produced output:
# tensor([0.], device='mps:0')
# tensor([1.0000e-07], device='mps:0')
# tensor([0.], device='mps:0')
# tensor([1.0000e-07], device='mps:0')
# tensor([0.], device='mps:0')
# tensor([1.0000e-07], device='mps:0')
# tensor([0.], device='mps:0')
# tensor([1.0000e-07], device='mps:0')

```

So it's slightly ungainly when you really only want to pass in scalar values but hopefully it does the trick and lets you proceed while waiting for the actual fix makes it way to the releases.
