### ISSUE TITLE
cuDNN error: CUDNN_STATUS_INTERNAL_ERROR on cudnn.benchmark = True

### ISSUE THREAD

**Issue by moderatelyfunctional** [pytorch/pytorch#16831]
Hi, I'm running PyTorch on an encoder/decoder architecture and am having a problem with cuDNN.

If I include
```python
import torch.backends.cudnn as cudnn
cudnn.benchmark = True
```
in my Python code, then I receive an error for CUDNN_STATUS_INTERNAL_ERROR.

The full stack trace is listed here.

```
    main()
  File "main.py", line 152, in main
    train_model(train_dataloader, val_dataloader)
  File "main.py", line 131, in train_model
    network_output = network(network_input)
  File "/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/model.py", line 133, in forward
    x = self.decoder(x)
  File "/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "model.py", line 54, in forward
    x = self.layer4(x)
  File "/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 757, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
```
If I comment out cuDNN, I can run the code without any problems. 

My system configurations are listed below.

 - PyTorch Version: 1.0.1
 - OS: Ubuntu 16.04
 - PyTorch 1.0.1 installed from pip3
 - Python version: 3.5
 - CUDA/cuDNN version: 10.0/7.402
 - GPU models and configuration: Nvidia GPU Titan X

## Additional context

I've tried `rm -rf ~/.nv`, rebuilt CUDA/cuDNN and reinstalled PyTorch but still cannot get it to work. Thanks for your help!

**Comment by soumith** [comment]
can you confirm that v1.0.0 works fine?

**Comment by moderatelyfunctional** [comment]
It also fails for v1.0.0. I installed it via pip3.

**Comment by soumith** [comment]
in that case, this is pretty weird. It shouldn't be failing on a Titan-X.
I see that you have CUDA10 installed on the system. Can you try installing our CUDA10 wheel? The command is at https://pytorch.org (use the selector wizard in get started and select pip and cuda10)

**Comment by soumith** [comment]
I uploaded new 1.0.1.post2 binaries, can you give those a shot?

**Comment by hyperfraise** [comment]
Same problem on current official 1.0.1 when pushing batch size to more than 3 per gpu (on multi gpu context). Works when batch_size/ngpu <= 3

**Comment by soumith** [comment]
I'd like to investigate this, any chance you can give me a small code snippet that's failing?

**Comment by FabianIsensee** [comment]
I have the exact same problem.
It **works** on pytorch 0.4.1 (cuDNN 7.1 I believe)
It does **not** work on pytorch 1.0.1.post2 (current stable release, cuDNN 7402)
It does **not** work on pytorch 1.0.0.dev20190220 (current nightly, cuDNN 7402)

My model is a very large 3D UNet that takes 224x224x224 shaped inputs. If you want to try it you will need 32GB of VRAM. It will **not** crash with smaller inputs such as 128x128x128 (which you could fit on your regular 12GB card).

Run this snippet to reprocude:

```
from torch.backends import cudnn
from copy import deepcopy
from torch import nn
import torch
import numpy as np
import torch.nn.functional


class ConvDropoutNormNonlin(nn.Module):
    def __init__(self, input_channels, output_channels,
                 conv_op=nn.Conv2d, conv_kwargs=None,
                 norm_op=nn.BatchNorm2d, norm_op_kwargs=None,
                 dropout_op=nn.Dropout2d, dropout_op_kwargs=None,
                 nonlin=nn.LeakyReLU, nonlin_kwargs=None):
        super(ConvDropoutNormNonlin, self).__init__()
        if nonlin_kwargs is None:
            nonlin_kwargs = {'negative_slope': 1e-2, 'inplace': True}
        if dropout_op_kwargs is None:
            dropout_op_kwargs = {'p': 0.5, 'inplace': True}
        if norm_op_kwargs is None:
            norm_op_kwargs = {'eps': 1e-5, 'affine': True, 'momentum': 0.1}
        if conv_kwargs is None:
            conv_kwargs = {'kernel_size': 3, 'stride': 1, 'padding': 1, 'dilation': 1, 'bias': True}

        self.nonlin_kwargs = nonlin_kwargs
        self.nonlin = nonlin
        self.dropout_op = dropout_op
        self.dropout_op_kwargs = dropout_op_kwargs
        self.norm_op_kwargs = norm_op_kwargs
        self.conv_kwargs = conv_kwargs
        self.conv_op = conv_op
        self.norm_op = norm_op

        self.conv = self.conv_op(input_channels, output_channels, **self.conv_kwargs)
        if self.dropout_op is not None and self.dropout_op_kwargs['p'] is not None and self.dropout_op_kwargs[
            'p'] > 0:
            self.dropout = self.dropout_op(**self.dropout_op_kwargs)
        else:
            self.dropout = None
        self.instnorm = self.norm_op(output_channels, **self.norm_op_kwargs)
        self.lrelu = nn.LeakyReLU(**self.nonlin_kwargs)

    def forward(self, x):
        x = self.conv(x)
        if self.dropout is not None:
            x = self.dropout(x)
        return self.lrelu(self.instnorm(x))


class StackedConvLayers(nn.Module):
    def __init__(self, input_feature_channels, output_feature_channels, num_convs,
                 conv_op=nn.Conv2d, conv_kwargs=None,
                 norm_op=nn.BatchNorm2d, norm_op_kwargs=None,
                 dropout_op=nn.Dropout2d, dropout_op_kwargs=None,
                 nonlin=nn.LeakyReLU, nonlin_kwargs=None, first_stride=None):
        '''
        stacks ConvDropoutNormLReLU layers. initial_stride will only be applied to first layer in the stack. The other parameters affect all layers
        :param input_feature_channels:
        :param output_feature_channels:
        :param num_convs:
        :param dilation:
        :param kernel_size:
        :param padding:
        :param dropout:
        :param initial_stride:
        :param conv_op:
        :param norm_op:
        :param dropout_op:
        :param inplace:
        :param neg_slope:
        :param norm_affine:
        :param conv_bias:
        '''
        self.input_channels = input_feature_channels
        self.output_channels = output_feature_channels

        if nonlin_kwargs is None:
            nonlin_kwargs = {'negative_slope': 1e-2, 'inplace': True}
        if dropout_op_kwargs is None:
            dropout_op_kwargs = {'p': 0.5, 'inplace': True}
        if norm_op_kwargs is None:
            norm_op_kwargs = {'eps': 1e-5, 'affine': True, 'momentum': 0.1}
        if conv_kwargs is None:
            conv_kwargs = {'kernel_size': 3, 'stride': 1, 'padding': 1, 'dilation': 1, 'bias': True}

        self.nonlin_kwargs = nonlin_kwargs
        self.nonlin = nonlin
        self.dropout_op = dropout_op
        self.dropout_op_kwargs = dropout_op_kwargs
        self.norm_op_kwargs = norm_op_kwargs
        self.conv_kwargs = conv_kwargs
        self.conv_op = conv_op
        self.norm_op = norm_op

        if first_stride is not None:
            self.conv_kwargs_first_conv = deepcopy(conv_kwargs)
            self.conv_kwargs_first_conv['stride'] = first_stride
        else:
            self.conv_kwargs_first_conv = conv_kwargs

        super(StackedConvLayers, self).__init__()
        self.blocks = nn.Sequential(
            *([ConvDropoutNormNonlin(input_feature_channels, output_feature_channels, self.conv_op,
                                     self.conv_kwargs_first_conv,
                                     self.norm_op, self.norm_op_kwargs, self.dropout_op, self.dropout_op_kwargs,
                                     self.nonlin, self.nonlin_kwargs)] +
              [ConvDropoutNormNonlin(output_feature_channels, output_feature_channels, self.conv_op,
                                     self.conv_kwargs,
                                     self.norm_op, self.norm_op_kwargs, self.dropout_op, self.dropout_op_kwargs,
                                     self.nonlin, self.nonlin_kwargs) for _ in range(num_convs - 1)]))

    def forward(self, x):
        return self.blocks(x)


class Upsample(nn.Module):
    def __init__(self, size=None, scale_factor=None, mode='nearest', align_corners=False):
        super(Upsample, self).__init__()
        self.align_corners = align_corners
        self.mode = mode
        self.scale_factor = scale_factor
        self.size = size

    def forward(self, x):
        return nn.functional.interpolate(x, size=self.size, scale_factor=self.scale_factor, mode=self.mode, align_corners=self.align_corners)


class Generic_UNet(nn.Module):
    def __init__(self, input_channels, base_num_features, num_classes, num_pool):
        super(Generic_UNet, self).__init__()

        self.nonlin_kwargs = {'negative_slope':1e-2, 'inplace':True}
        self.dropout_op_kwargs = {'p':0.0, 'inplace':True}
        self.norm_op_kwargs = {'eps':1e-5, 'affine':True}
        self.conv_kwargs = {'kernel_size':3,'padding':1, 'stride':1, 'dilation':1, 'bias':True}
        self.nonlin = nn.ReLU
        self.conv_op = nn.Conv3d
        self.norm_op = nn.InstanceNorm3d
        self.dropout_op = nn.Dropout3d
        self.num_classes = num_classes

        transpconv = nn.ConvTranspose3d

        self.conv_blocks_encoder = []
        self.conv_blocks_decoder = []
        self.transpConvs = []

        # encoder
        output_features = base_num_features
        input_features = input_channels
        for d in range(num_pool):
            # determine the first stride
            if d != 0:
                first_stride = 2
            else:
                first_stride = 1

            self.conv_blocks_encoder.append(StackedConvLayers(input_features, output_features, 2,
                                                              self.conv_op, self.conv_kwargs, self.norm_op,
                                                              self.norm_op_kwargs, self.dropout_op,
                                                              self.dropout_op_kwargs, self.nonlin, self.nonlin_kwargs,
                                                              first_stride))
            input_features = output_features
            output_features = int(np.round(output_features * 2))
            output_features = min(output_features, 480) # no more filters, otherwise we explode in num parameters

        # now the bottleneck.
        first_stride = 2
        final_num_features = output_features
        self.conv_blocks_encoder.append(nn.Sequential(
            StackedConvLayers(input_features, output_features, 2 - 1, self.conv_op, self.conv_kwargs,
                              self.norm_op, self.norm_op_kwargs, self.dropout_op, self.dropout_op_kwargs, self.nonlin,
                              self.nonlin_kwargs, first_stride),
            StackedConvLayers(output_features, final_num_features, 1, self.conv_op, self.conv_kwargs,
                              self.norm_op, self.norm_op_kwargs, self.dropout_op, self.dropout_op_kwargs, self.nonlin,
                              self.nonlin_kwargs)))

        # now lets build the decoder pathway
        for u in range(num_pool):
            nfeatures_from_down = final_num_features
            nfeatures_from_skip = self.conv_blocks_encoder[-(2 + u)].output_channels # self.conv_blocks_context[-1] is bottleneck, so start with -2
            n_features_after_tu_and_concat = nfeatures_from_skip * 2

            final_num_features = nfeatures_from_skip

            self.transpConvs.append(transpconv(nfeatures_from_down, nfeatures_from_skip, 2, 2, bias=False))

            self.conv_blocks_decoder.append(nn.Sequential(
                StackedConvLayers(n_features_after_tu_and_concat, nfeatures_from_skip, 2 - 1,
                                  self.conv_op, self.conv_kwargs, self.norm_op, self.norm_op_kwargs, self.dropout_op,
                                  self.dropout_op_kwargs, self.nonlin, self.nonlin_kwargs),
                StackedConvLayers(nfeatures_from_skip, final_num_features, 1, self.conv_op, self.conv_kwargs,
                                  self.norm_op, self.norm_op_kwargs, self.dropout_op, self.dropout_op_kwargs,
                                  self.nonlin, self.nonlin_kwargs)
            ))

        self.seg_output = self.conv_op(base_num_features, num_classes, 1, 1, 0, 1, 1, False)

        # register all modules properly
        self.conv_blocks_decoder = nn.ModuleList(self.conv_blocks_decoder)
        self.conv_blocks_encoder = nn.ModuleList(self.conv_blocks_encoder)
        self.transpConvs = nn.ModuleList(self.transpConvs)

    def forward(self, x):
        skips = []
        for d in range(len(self.conv_blocks_encoder) - 1):
            x = self.conv_blocks_encoder[d](x)
            skips.append(x)

        x = self.conv_blocks_encoder[-1](x)

        for u in range(len(self.transpConvs)):
            x = self.transpConvs[u](x)
            x = torch.cat((x, skips[-(u + 1)]), dim=1)
            x = self.conv_blocks_decoder[u](x)

        seg_output = self.seg_output(x)

        return seg_output


if __name__ == "__main__":
    cudnn.benchmark = True

    net = Generic_UNet(1, 30, 3, 5).cuda()

    a = torch.rand((1, 1, 224, 224, 224)).pin_memory().cuda()

    res = net(a)
    loss = res.sum()

    loss.backward()

```

Set `cudnn.benchmark = False` and this example will run on all pytorch versions.
I hope you can help. This seems to be a tricky one... :-)

Best,
Fabian

**Comment by ngimel** [comment]
Thank you for your investigation and repro @FabianIsensee. It's a cudnn bug present at least in cudnn 7.4 and 7.5. I'm trying to get information on workarounds. The failing call is most likely for decoder 4 convolution weight gradient (input size 1,30,224,224,224, output features = 3, filter size =1) - I'm certain on sizes and it being weight gradient, not exactly sure if it's decoder 4 or not.

**Comment by FabianIsensee** [comment]
Thank you @ngimel for investigating this! If there is anything I can do to help, I'd be happy to do so. This bug is hindering some experiments and it would also be in my interest to get it solved relatively quickly

**Comment by Olloxan** [comment]
Hi, I get this error, when I want to call the .cuda() method on a network which contains a GRU. I have a Windows system with Pytorch 1.0.1, CUDA 10 and cudnn 7.401

**Comment by mruberry** [comment]
We are working on a fix for this. Will update ASAP.

**Comment by FabianIsensee** [comment]
That's great to hear, thank you so much!

**Comment by CyFeng16** [comment]
Hi, I'm facing the same error.
I receive `RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR` error running on a multi-gpus server via NGC PyTorch docker image, while running the same code in my personal computer via PyTorch installed by conda gets success.

**Comment by mruberry** [comment]
@CyFeng16 can you post a code snippet that reproduces the error you're finding as well as instructions to run the snippet? 

Also, which NGC PyTorch docker image are you using?

**Comment by CyFeng16** [comment]
@mruberry Some additional info: 
- NGC docker within PyTorch version `1.1.0a0+be364ac` failed.(on server)
- Conda env within PyTorch version `1.0.1.post2` run perfectly.(on PC)
Apologize that could not share these codes for now.

**Comment by mruberry** [comment]
Thank you for reporting the issue, but without a snippet to reproduce the error you're seeing I don't know if we'll be able to fix your issue. While you're seeing the same error, the cause may be different.

**Comment by CyFeng16** [comment]
:label:  will report when I find a alternative way to solve the problem.

**Comment by mruberry** [comment]
We believe we have identified the root cause of this issue and are working on a fix in cuDNN.

**Comment by code-de** [comment]
Hey @mruberry, any updates so far?

**Comment by mruberry** [comment]
We are testing a fix that we expect will ship in a future version of cuDNN. Unfortunately I cannot be more specific than that at the moment.

**Comment by FingerRec** [comment]
In pytorch1.1, code works well

**Comment by soumith** [comment]
thanks for reporting @FingerRec

**Comment by CyFeng16** [comment]
@FingerRec glad to hear!

**Comment by ksarma** [comment]
I'm still able to reproduce what @FabianIsensee posted using pytorch 1.1.0a0+9eb0f43 (NGC 19.04)

This NGC image only uses cuDNN 7.5.0, not sure if 7.5.1 or 7.6 would fix

**Comment by ngimel** [comment]
@ksarma please use official pytorch 1.1 conda/pip packages or image from dockerhub/pytorch.

**Comment by ksarma** [comment]
@ngimel Apologies, was using what I thought was the latest pytorch image from NGC, but it turns out there was a new one yesterday (19.05) and the issue seems to be fixed :) This image has cuDNN 7.6.0 and pytorch 1.1.0a0+828a6a3

**Comment by JZPeterPan** [comment]
could also be a compatible problem of torch and cudnn, this could: help https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation/issues/12

**Comment by rave974** [comment]
> can you confirm that v1.0.0 works fine?

WHAT IS THE REASON OF THIS ERROR?

**Comment by Charlyo** [comment]
Still happening on torch==1.9.0+cu111 and cuda 11.4.

**Comment by niceblue88** [comment]
Yes *still* broken, at least for me. Pytorch 1.9, Cuda 11 and using Titan X in Windows 10. Benchmark = false works no problem reliably. Benchmark = true works for a bit (with double the speed of = false, which is great), but then randomly breaks for no seeming reason with CUDA ERROR. The fact that is works very well for a bit shows it can work very well (with 2x speed up), but clearly there is a bug somewhere that's been in there for at least 2 years now.

**Comment by cgsaxner** [comment]
> Yes _still_ broken, at least for me. Pytorch 1.9, Cuda 11 and using Titan X in Windows 10. Benchmark = false works no problem reliably. Benchmark = true works for a bit (with double the speed of = false, which is great), but then randomly breaks for no seeming reason with CUDA ERROR. The fact that is works very well for a bit shows it can work very well (with 2x speed up), but clearly there is a bug somewhere that's been in there for at least 2 years now.

I'm running into the same issue using PyTorch 1.9.1 and  CUDA 10.2 on Quadro RTX 8000.

**Comment by ShoufaChen** [comment]
The latest pytorch version: `1.10.1+cu111, cudnn8.0.5` still happens on both V100 and A100 GPUs. It works well on 3090.

**Comment by ngimel** [comment]
Please provide a self contained reproducible script triggering the problem. Pytorch 1.10.1 comes with cudnn 8.2, so I'm not sure why you are listing cudnn8.0.5

**Comment by niceblue88** [comment]
Please also have a look at my response on this problem in a related thread https://github.com/pytorch/pytorch/issues/45769#issuecomment-936316009

**Comment by ngimel** [comment]
It doesn't have self contained reproduucible script. Without it, the bug is not actionable for us.

**Comment by ShoufaChen** [comment]
@ngimel 
Thanks for your reply. For cudnn version, I use the https://anaconda.org/pytorch/pytorch/1.10.1/download/linux-64/pytorch-1.10.1-py3.8_cuda11.1_cudnn8.0.5_0.tar.bz2 . It seems that Pytorch1.10.1 also comes with cudnn 8.0.5.

I encounter this issue when using this [repo](https://github.com/lulutang0608/Point-BERT). The related issue is https://github.com/lulutang0608/Point-BERT/issues/14#issuecomment-1003677580.

**Comment by Rui-Ren** [comment]
@ShoufaChen Hi, I am running some experiments to test the K80 gpu and got the same error as you posted here https://github.com/lulutang0608/Point-BERT/issues/14#issuecomment-1003677580. Did you solve this error? Thanks.

**Comment by rave974** [comment]
the solution is to run inference in a loop, when error comes, run program again, resume until finish

**Comment by ShoufaChen** [comment]
@Rui-Ren  I am sorry that I didn't fix the problem. I just changed the pytorch version.

**Comment by Rui-Ren** [comment]
> 
Ok, thanks, I will add some retries there and see how it goes.

**Comment by GuoleiSun** [comment]
Hello, I faced the problem. It is very strange.
1. I faced the problem when my code is running on A100 with a specific batch size (2) and with 4 GPUs training. The code runs well on RTX 6000 and V100. It also works well if I use a different batch size (1,3,4) or different number of GPUs (1,2,3) on A100. 
2. Here is the shown error
"runner.outputs['loss'].backward()
  File "/cluster/apps/nss/gcc-6.3.0/python_gpu/3.8.5/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/cluster/apps/nss/gcc-6.3.0/python_gpu/3.8.5/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED"
