### ISSUE TITLE
 Using F.affine_grid caused cuDNN error: CUDNN_STATUS_EXECUTION_FAILED (PyTorch version: 1.0.1.post2)

### ISSUE THREAD

**Issue by xierc** [pytorch/pytorch#16935]
## 🐛 Bug
Hi, when I use **pytorch 1.0.1.post2**, the function `F.affine_grid` causes an error like it: 

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-21-37668468b031> in <module>()
      1 theta=torch.Tensor([[[1,1,1],[1,1,1]]]).cuda()
      2 import torch.nn.functional as F
----> 3 F.affine_grid(theta, torch.Size((1, 3, 2, 2)))

~/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py in affine_grid(theta, size)
   2613         output (Tensor): output Tensor of size (:math:`N \times H \times W \times 2`)
   2614     """
-> 2615     return vision.affine_grid_generator(theta, size)
   2616 
   2617 

~/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/vision.py in affine_grid_generator(theta, size)
      8     if theta.is_cuda and cudnn.enabled and cudnn.is_acceptable(theta) and len(size) == 4:
      9         N, C, H, W = size
---> 10         ret = torch.cudnn_affine_grid_generator(theta, N, C, H, W)
     11     else:
     12         ret = torch.affine_grid_generator(theta, size)

RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

```
If I set `torch.backends.cudnn.enabled=False`, there is no error but speed is slow.

I tried to roll back the version of pytorch to **1.0.0**, which worked well. In this version,  `torch.backends.cudnn.enabled=True`  is ok. 

So I guess there maybe some bugs in `F.affine_grid` with **pytorch 1.0.1.post2**

## To Reproduce

A simple code with calling `F.affine_grid` will Reproduce this error

```
import torch.nn.functional as F
import torch

theta=torch.Tensor([[[1,1,1],[1,1,1]]]).cuda()
F.affine_grid(theta, torch.Size((1, 3, 2, 2)))
```

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 14.04.5 LTS
GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
CMake version: version 3.2.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.44
GPU models and configuration: 
GPU 0: Tesla K40c
GPU 1: Tesla K40m

Nvidia driver version: 367.57
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10
/usr/local/lib/libcudnn.so.5.0.5

Versions of relevant libraries:
[pip3] numpy==1.15.0
[pip3] numpydoc==0.7.0
[pip3] torch==1.0.0
[pip3] torchvision==0.2.0
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2018.0.1             h19d6760_4    defaults
[conda] mkl-service               1.1.2            py36h17a0993_4    defaults
[conda] pytorch                   0.3.1           py36_cuda8.0.61_cudnn7.0.5_2    pytorch
[conda] torch                     1.0.0                     <pip>
[conda] torchvision               0.2.0            py36h17b6947_1    pytorch

**Comment by ailzhang** [comment]
This works fine for me with a fresh torch installed from conda.

**Comment by soumith** [comment]
@xierc note that you have `[conda] pytorch 0.3.1 py36_cuda8.0.61_cudnn7.0.5_2 pytorch` and `[pip3] torch==1.0.0`, not `1.0.1`

**Comment by huagl** [comment]
I got exactly the same problem too! And I tried to roll back the version of pytorch to 0.4.1, then it works well.

**Comment by wadesunyang** [comment]
i use pytorch 1.0.1.post2,  the same problem.
