### ISSUE TITLE
libtorch elevated memory usage.

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#17095]
## 🐛 Bug

Reported by @dawnwch over here: https://github.com/pytorch/pytorch/issues/16255#issuecomment-462730809

Original message pasted below.

cc: @yf225 can you help get to the bottom of this?

Hello, I still have the problem by using the preview builds(1.0.0.dev20190211).
I use `torch::cuda::cudnn_is_available()` to see if CuDNN being linked with libtorch, and the result is `True`.
The model I use is [https://github.com/dawnwch/for-a-libtorch-question](url) (There are ReflectionPad2d, Conv2d, InstanceNorml2d, ReLU,ConvTraansposed2d and Tanh in my model)and the test code is
```cpp
#include <torch/script.h>
#include <torch/torch.h>
#include <iostream>
#include <memory>

int main(int argc, const char* argv[]) {
    std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(argv[1]);
    assert(module != nullptr);
    torch::DeviceType device;
    device = torch::kCUDA;
    module->to(device);
    std::vector<torch::jit::IValue> inputs;
    inputs.push_back(torch::ones({1, 3, 1920, 1080}).to(device));
    at::Tensor output = module->forward(inputs).toTensor();
    std::cout << "Done" << std::endl;
    return 0;
}
```
The error is
```
CUDA out of memory. Tried to allocate 1.11 GiB (GPU 0; 10.91 GiB total capacity; 10.07 GiB already allocated; 121.38 MiB free; 10.18 MiB cached) (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:236)
```

Here is the gpu memory usage I test.
![image](https://user-images.githubusercontent.com/35034417/52633408-3effcb00-2eff-11e9-9628-94ff4d8d18be.png)
Hope for your replay and thanks for your help.

**Comment by yf225** [comment]
@dawnwch Thanks for opening the issue - could you also post the model source code? The `apple2orange-pytorch-model.pth` you provided in https://github.com/dawnwch/for-a-libtorch-question is only the state dict and is not reconstructable without the model source code.

Also some observations on peak memory usage:
```
                       torch.ones(1, 3, 1920, 1080)     torch.ones(1, 3, 1280, 720)                
JIT model loaded in Python          OOM                          5867779584 bytes
JIT model loaded in C++             OOM                          5867779584 bytes
```

I think the memory usage problem is more on the difference between JIT and non-JIT PyTorch code, and we need to dig deeper into it.

**Comment by dawnwch** [comment]
I use `with torch.no_grad(): ` in pytorch but not in libtorch, I think this is the reason for the difference in the amount of memory usage, please tell me how to implement this function in cpp.
if it doesn't work I'll post the model source code.

**Comment by yf225** [comment]
@dawnwch The equivalent to `with torch.no_grad()` in C++ is `torch::NoGradGuard no_grad`. For example:
Python:
```python
with torch.no_grad():
    module.weight += 1
```
C++:
```cpp
{
    torch::NoGradGuard no_grad;
    module->weight += 1;
}  // Note that anything out of this scope will still record gradients
``` 
Please try to out and let me know if it resolves the memory usage issue.

**Comment by dawnwch** [comment]
Thank you! By using `torch::NoGradGuard no_grad`, the memory usage is consistent with pytorch.

**Comment by nihui** [comment]
I met the same problem. resolved by adding no_grad guard. Thanks !

```
#include <torch/script.h>
#include <torch/torch.h>
#include <torch/utils.h>
#include <iostream>
#include <memory>

int main(int argc, const char* argv[]) {
    std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(argv[1]);

    torch::NoGradGuard no_grad; // just add this line to the same scope with the loaded module

    torch::Device device(torch::kCUDA, 0);
    module->to(device);

    std::vector<torch::jit::IValue> inputs;
    inputs.push_back(torch::ones({1, 3, 1920, 1080}).to(device));
    at::Tensor output = module->forward(inputs).toTensor();

    std::cout << "Done" << std::endl;

    return 0;
}
```
