### ISSUE TITLE
RuntimeError: Output size of the matrix multiplication is larger than currently supported by the MPS backend: 47616,190464, needs to be less than 2**32 elements.File a feature request for this use case against the MPS backend

### ISSUE THREAD

**Issue by scottharmon** [pytorch/pytorch#171026]
### 🐛 Describe the bug

!!! Exception during processing !!! Output size of the matrix multiplication is larger than currently supported by the MPS backend: 47616,190464, needs to be less than 2**32 elements.File a feature request for this use case against the MPS backend at https://github.com/pytorch/pytorch/issues
Traceback (most recent call last):
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 516, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 330, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 304, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 292, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 298, in decode
    images = vae.decode(samples["samples"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/sd.py", line 785, in decode
    out = self.process_output(self.first_stage_model.decode(samples, **vae_options).to(self.output_device).float())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/models/autoencoder.py", line 253, in decode
    dec = self.decoder(dec, **decoder_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 795, in forward
    h = self.mid.attn_1(h, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 381, in forward
    h_ = self.optimized_attention(q, k, v)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 290, in normal_attention
    r1 = slice_attention(q, k, v)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 262, in slice_attention
    s1 = torch.bmm(q[:, i:end], k) * scale
         ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Output size of the matrix multiplication is larger than currently supported by the MPS backend: 47616,190464, needs to be less than 2**32 elements.File a feature request for this use case against the MPS backend at https://github.com/pytorch/pytorch/issues

### Versions

nightly

cc @kulinseth @malfet @DenisVieriu97 @jhavukainen

**Comment by scottharmon** [comment]
This is easily reproduced from ComfyUI.  Just run the default template for video_hunyuan_video_1.5_720p_t2v

**Comment by AtinChing** [comment]
@scottharmon  I tried reproducing it via ComfyUI using the video_hunyuan_video_1.5_720p_t2v template, but it just gets stuck at
```bash
Using MixedPrecisionOps for text encoder
Requested to load QwenImageTEModel_
loaded completely; 95367431640625005117571072.00 MB usable, 8328.60 MB loaded, full load: True
CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load HunyuanVideo15
0 models unloaded.
loaded completely; 95367431640625005117571072.00 MB usable, 15881.76 MB loaded, full load: True
  0%|          | 0/20 [00:00<?, ?it/s]
```
It seems this needs some very strong hardware to run and test? Let me know if I'm doing something wrong.
(MacBook M4 Max)
Otherwise, do you have any other way to repro?

**Comment by scottharmon** [comment]
This is using the default video_kandinsky5_t2v

Adding extra search path custom_nodes /Users/scott/Documents/ComfyUI/custom_nodes
Adding extra search path download_model_base /Users/scott/Documents/ComfyUI/models
Adding extra search path custom_nodes /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes
Adding extra search path download_model_base /Volumes/home/AI
Adding extra search path checkpoints /Volumes/home/AI/checkpoints
Adding extra search path loras /Volumes/home/AI/loras
Adding extra search path vae /Volumes/home/AI/vae
Setting output directory to: /Users/scott/Documents/ComfyUI/output
Setting input directory to: /Users/scott/Documents/ComfyUI/input
Setting user directory to: /Users/scott/Documents/ComfyUI/user
[START] Security scan
[ComfyUI-Manager] Using uv as Python module for pip operations.
[DONE] Security scan
** ComfyUI startup time: 2025-12-29 21:55:12.213
** Platform: Darwin
** Python version: 3.12.11 (main, Aug 18 2025, 19:02:39) [Clang 20.1.4 ]
** Python executable: /Users/scott/Documents/ComfyUI/.venv/bin/python
** ComfyUI Path: /Applications/ComfyUI.app/Contents/Resources/ComfyUI
** ComfyUI Base Folder Path: /Applications/ComfyUI.app/Contents/Resources/ComfyUI
** User directory: /Users/scott/Documents/ComfyUI/user
** ComfyUI-Manager config path: /Users/scott/Documents/ComfyUI/user/__manager/config.ini
** Log path: /Users/scott/Documents/ComfyUI/user/comfyui.log
[ComfyUI-Manager] Skipped fixing the 'comfyui-frontend-package' dependency because the ComfyUI is outdated.
[PRE] ComfyUI-Manager
Checkpoint files will always be loaded safely.
Total VRAM 131072 MB, total RAM 131072 MB
pytorch version: 2.5.1
Mac Version (26, 1)
Set vram state to: SHARED
Device: mps
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
Python version: 3.12.11 (main, Aug 18 2025, 19:02:39) [Clang 20.1.4 ]
ComfyUI version: 0.6.0
[Prompt Server] web root: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/web_custom_versions/desktop_app
[START] ComfyUI-Manager
[ComfyUI-Manager] network_mode: public
[ComfyUI-Manager] The matrix sharing feature has been disabled because the `matrix-nio` dependency is not installed.
        To use this feature, please run the following command:
        /Users/scott/Documents/ComfyUI/.venv/bin/python -m pip install matrix-nio

Total VRAM 131072 MB, total RAM 131072 MB
pytorch version: 2.5.1
Mac Version (26, 1)
Set vram state to: SHARED
Device: mps
Blocked by policy: /Users/scott/Documents/ComfyUI/custom_nodes/ComfyUI-Manager
Traceback (most recent call last):
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 2149, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/scott/Documents/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite/__init__.py", line 6, in <module>
    from coreml_suite.nodes import (
  File "/Users/scott/Documents/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite/coreml_suite/nodes.py", line 4, in <module>
    from python_coreml_stable_diffusion.coreml_model import CoreMLModel
ModuleNotFoundError: No module named 'python_coreml_stable_diffusion'

Cannot import /Users/scott/Documents/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite module for custom nodes: No module named 'python_coreml_stable_diffusion'

Import times for custom nodes:
   0.0 seconds: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/websocket_image_save.py
   0.2 seconds (IMPORT FAILED): /Users/scott/Documents/ComfyUI/custom_nodes/ComfyUI-CoreMLSuite

Failed to initialize database. Please ensure you have installed the latest requirements. If the error persists, please report this as in future the database will be required: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Starting server

To see the GUI go to: http://127.0.0.1:8000
comfyui-frontend-package not found in requirements.txt
FETCH ComfyRegistry Data: 5/116
FETCH ComfyRegistry Data: 10/116
FETCH ComfyRegistry Data: 15/116
FETCH ComfyRegistry Data: 20/116
FETCH ComfyRegistry Data: 25/116
got prompt
Using split attention in VAE
Using split attention in VAE
FETCH ComfyRegistry Data: 30/116
FETCH ComfyRegistry Data: 35/116
FETCH ComfyRegistry Data: 40/116
FETCH ComfyRegistry Data: 45/116
FETCH ComfyRegistry Data: 50/116
FETCH ComfyRegistry Data: 55/116
VAE load device: mps, offload device: cpu, dtype: torch.bfloat16
FETCH ComfyRegistry Data: 60/116
FETCH ComfyRegistry Data: 65/116
FETCH ComfyRegistry Data: 70/116
Found quantization metadata version 1
Using MixedPrecisionOps for text encoder
FETCH ComfyRegistry Data: 75/116
FETCH ComfyRegistry Data: 80/116
FETCH ComfyRegistry Data: 85/116
FETCH ComfyRegistry Data: 90/116
FETCH ComfyRegistry Data: 95/116
FETCH ComfyRegistry Data: 100/116
FETCH ComfyRegistry Data: 105/116
FETCH ComfyRegistry Data: 110/116
FETCH ComfyRegistry Data: 115/116
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: /Users/scott/Documents/ComfyUI/user/__manager/cache/1514988643_custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
clip missing: ['text_projection.weight']
Requested to load Kandinsky5TEModel_
loaded completely; 95367431640625005117571072.00 MB usable, 8146.14 MB loaded, full load: True
CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float16
model weight dtype torch.bfloat16, manual cast: None
model_type FLOW
Requested to load Kandinsky5
loaded completely; 95367431640625005117571072.00 MB usable, 3829.39 MB loaded, full load: True
100%|██████████| 50/50 [10:54:42<00:00, 785.65s/it]  
Requested to load AutoencoderKL
loaded completely; 95367431640625005117571072.00 MB usable, 470.12 MB loaded, full load: True
!!! Exception during processing !!! Output size of the matrix multiplication is larger than currently supported by the MPS backend: 47616,190464, needs to be less than 2**32 elements.File a feature request for this use case against the MPS backend at https://github.com/pytorch/pytorch/issues
Traceback (most recent call last):
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 516, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 330, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 304, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 292, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 298, in decode
    images = vae.decode(samples["samples"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/sd.py", line 803, in decode
    out = self.process_output(self.first_stage_model.decode(samples, **vae_options).to(self.output_device).float())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/models/autoencoder.py", line 253, in decode
    dec = self.decoder(dec, **decoder_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 795, in forward
    h = self.mid.attn_1(h, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 381, in forward
    h_ = self.optimized_attention(q, k, v)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 290, in normal_attention
    r1 = slice_attention(q, k, v)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 262, in slice_attention
    s1 = torch.bmm(q[:, i:end], k) * scale
         ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Output size of the matrix multiplication is larger than currently supported by the MPS backend: 47616,190464, needs to be less than 2**32 elements.File a feature request for this use case against the MPS backend at https://github.com/pytorch/pytorch/issues

Prompt executed in 05:37:09

**Comment by scottharmon** [comment]
That did the trick, thanks
