### ISSUE TITLE
NCCL error: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.hpp:268, NCCL version 2.22.3 ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. Last error: socketStartConnect: Connect to IP<51423> failed

### ISSUE THREAD

**Issue by guotong1988** [pytorch/pytorch#171179]
### 🐛 Describe the bug

Trying to train multi-node multi-gpu LLM.

In my environment, only ports 40000-40050 are open (not blocked by the firewall). I tried to restrict the port the program uses, but it didn't work. I'm not sure where 51423 is coming from.

### Versions

2.6

cc @H-Huang @awgu @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @pragupta @msaroufim @dcci

**Comment by guotong1988** [comment]
run_sft.sh
```
#!/bin/bash

# SFT训练脚本
# 使用方法: bash run_sft.sh 或 ./run_sft.sh

# 设置脚本在遇到错误时退出
set -e

# 获取脚本所在目录
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# 创建日志目录
LOGS_DIR=".logs"
mkdir -p "${LOGS_DIR}"

# 生成日志文件名（带时间戳）
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
LOG_FILE="${LOGS_DIR}/sft_train_${TIMESTAMP}.log"

# 训练参数配置（可根据需要修改）
MODEL_NAME="/data/Qwen3-8B-Base"
OUTPUT_DIR="/data/outputs-sft-from-base/${TIMESTAMP}"
DATASET=""  # 留空使用默认数据集
# JSONL文件路径配置（优先于DATASET，如果设置了LLM_JSONL，将使用该文件）
# 示例: LLM_JSONL="llm.jsonl"  # 使用当前目录下的llm.jsonl文件
# 示例: LLM_JSONL="/path/to/llm.jsonl"  # 使用绝对路径
LLM_JSONL="llm.jsonl"  # 默认使用llm.jsonl文件
# 子集名称配置（支持多个子集，用空格分隔）
# 留空或不设置则使用所有默认子集（chinese_traditional, coig_pc, exam, finance, douban, human_value, logi_qa, ruozhiba, segmentfault, wiki, wikihow, xhs, zhihu）
# 示例: SUBSET_NAME="coig_pc exam finance"  # 只使用指定的子集
# 示例: SUBSET_NAME=""  # 使用所有默认子集
SUBSET_NAME=""
TEXT_COLUMN="text"

# 训练超参数
LEARNING_RATE=1e-5
BATCH_SIZE=1
GRADIENT_ACCUMULATION_STEPS=8  # 进一步增加梯度累积步数以减少显存（从4增加到8）
NUM_EPOCHS=1
MAX_SEQ_LENGTH=128  # 减小序列长度以节省显存（已改为256）
WARMUP_STEPS=100
SEED=42

# 训练配置
SAVE_STEPS=50000  # 增加保存间隔以减少I/O和显存峰值
LOGGING_STEPS=10
EVAL_STRATEGY="no"  # 可选: no, steps, epoch
EVAL_STEPS=500
SAVE_TOTAL_LIMIT=1  # 只保留1个检查点以节省磁盘和显存

# 性能优化选项（取消注释以启用）
# USE_BF16="--bf16"  # 使用bfloat16精度（推荐用于A100等GPU）
USE_FP16="--fp16"  # 使用float16精度
GRADIENT_CHECKPOINTING="--gradient_checkpointing"  # 启用梯度检查点以节省内存（重要：可节省约40-50%显存）
USE_8BIT_OPTIMIZER="--use_8bit_optimizer"  # 使用8-bit优化器（重要：可节省约50-75%优化器状态显存，需要安装bitsandbytes）
# PACKING="--packing"  # 启用序列打包以提高效率（会增加显存，暂时禁用）
# PIN_MEMORY="--dataloader_pin_memory"  # 启用数据加载器pin memory（会增加显存，暂时禁用）

# 其他选项
DATALOADER_NUM_WORKERS=1  # 减少数据加载器工作进程数以节省显存（从4减少到0）
MAX_STEPS=-1  # -1表示使用num_train_epochs

export CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7'
# 分布式训练配置
# 如果仍然OOM，可以尝试减少GPU数量，例如改为2或1
NPROC_PER_NODE=8  # 每个节点的进程数（GPU数量）

# 多机多卡训练配置（单机训练时保持默认值即可）
# 单机训练: NNODES=1, NODE_RANK=0, MASTER_ADDR="localhost"
# 多机训练示例（2台机器）:
#   节点0 (主节点): NNODES=2, NODE_RANK=0, MASTER_ADDR="192.168.1.100" (主节点IP)
#   节点1 (从节点): NNODES=2, NODE_RANK=1, MASTER_ADDR="192.168.1.100" (主节点IP)
NNODES=2  # 总节点数（单机训练为1，多机训练为节点总数）
NODE_RANK=1  # 当前节点编号（主节点为0，从节点从1开始递增）
MASTER_ADDR="33.106.194.28"  # 主节点IP地址（多机训练时改为主节点的实际IP）
MASTER_PORT="40000"  # 主节点端口（确保所有节点使用相同端口，且端口未被占用）

# NCCL环境变量配置（解决通信超时问题）
export NCCL_DEBUG=INFO  # 设置为INFO以获取更多调试信息，如果问题解决后可以改为WARN
export NCCL_TIMEOUT=7200  # 增加超时时间到7200秒（2小时），默认是1800秒（30分钟）
export NCCL_BLOCKING_WAIT=1  # 使用阻塞等待模式，更稳定
export NCCL_ASYNC_ERROR_HANDLING=1  # 启用异步错误处理，有助于诊断问题

# 端口范围限制配置（限制NCCL和PyTorch只使用防火墙开放的端口范围）
# 防火墙开放的端口范围：40000-40050
PORT_RANGE_START=40000
PORT_RANGE_END=40050

# 验证MASTER_PORT是否在允许的端口范围内
MASTER_PORT_INT=$(echo "${MASTER_PORT}" | sed 's/[^0-9]//g')
if [ -z "${MASTER_PORT_INT}" ] || [ "${MASTER_PORT_INT}" -lt "${PORT_RANGE_START}" ] || [ "${MASTER_PORT_INT}" -gt "${PORT_RANGE_END}" ]; then
    echo "错误: MASTER_PORT (${MASTER_PORT}) 不在防火墙开放的端口范围内 (${PORT_RANGE_START}-${PORT_RANGE_END})"
    echo "请将MASTER_PORT设置为 ${PORT_RANGE_START} 到 ${PORT_RANGE_END} 之间的值"
    exit 1
fi

# 设置NCCL使用TCP模式，并限制端口范围（通过环境变量）
export NCCL_SOCKET_NTHREADS=2  # socket线程数，减少端口使用
export NCCL_NSOCKS_PERTHREAD=4  # 每个线程的socket数，减少端口使用
# 注意：NCCL没有直接的端口范围限制环境变量，但我们可以通过减少socket数量来减少端口使用
# 如果仍然使用随机端口，可能需要配置系统级别的端口范围限制

# PyTorch分布式训练端口配置
# 注意：PyTorch和NCCL没有直接的端口范围限制环境变量
# 但我们可以通过以下方式减少端口使用：
# 1. 减少NCCL的socket数量（已设置NCCL_SOCKET_NTHREADS和NCCL_NSOCKS_PERTHREAD）
# 2. 强制使用TCP模式（已设置NCCL_IB_DISABLE=1和NCCL_P2P_DISABLE=1）
# 3. 如果仍然使用随机端口，需要使用系统级别的端口限制（见下方说明）
# 设置一个自定义环境变量用于Python代码中的端口范围检查
export TORCH_DISTRIBUTED_PORT_RANGE="${PORT_RANGE_START}-${PORT_RANGE_END}"  # 用于Python代码中的端口范围验证

# 系统级别端口范围限制（可选，需要root权限）
# 如果仍然遇到端口连接错误（如连接到55995等随机端口），可以使用以下方法：
# 
# 方法1: 使用iptables限制出站端口范围（推荐，但需要root权限）
# 注意：这会限制所有程序的出站TCP连接，请谨慎使用！
# sudo iptables -A OUTPUT -p tcp --dport ${PORT_RANGE_START}:${PORT_RANGE_END} -j ACCEPT
# sudo iptables -A OUTPUT -p tcp --sport ${PORT_RANGE_START}:${PORT_RANGE_END} -j ACCEPT
# sudo iptables -A OUTPUT -p tcp -j REJECT  # 拒绝其他端口的TCP连接
# 
# 方法2: 使用firewalld（CentOS/RHEL/Fedora）
# sudo firewall-cmd --add-port=${PORT_RANGE_START}-${PORT_RANGE_END}/tcp --permanent
# sudo firewall-cmd --reload
# 
# 方法3: 使用ufw（Ubuntu/Debian）
# sudo ufw allow ${PORT_RANGE_START}:${PORT_RANGE_END}/tcp
# 
# 方法4: 如果无法使用系统级别限制，可以尝试：
# - 增加防火墙开放的端口范围（如果可能）
# - 使用VPN或内网环境，避免防火墙限制
# - 联系系统管理员开放更多端口

# 根据训练模式设置不同的NCCL配置
if [ "${NNODES}" -eq 1 ]; then
    # 单机多卡训练配置
    export NCCL_IB_DISABLE=1  # 禁用InfiniBand（单机训练通常不需要）
    export NCCL_P2P_DISABLE=0  # 启用P2P通信（GPU间直接通信）
    export NCCL_SOCKET_IFNAME=^docker0,lo  # 排除docker和loopback接口
    export NCCL_TREE_THRESHOLD=0  # 强制使用ring算法，避免tree算法可能的问题
else
    # 多机多卡训练配置
    export NCCL_IB_DISABLE=1  # 多机训练时也禁用InfiniBand，强制使用TCP（更可控的端口使用）
    export NCCL_P2P_DISABLE=1  # 多机训练时禁用P2P（跨节点不支持P2P）
    # 多机训练时建议指定网络接口，例如：
    # export NCCL_SOCKET_IFNAME=eth0  # 替换为实际的网络接口名称（如eth0, enp0s8等）
    # 如果不指定，NCCL会自动选择，但可能选择错误的接口
    export NCCL_TREE_THRESHOLD=0  # 使用ring算法（多机训练时更稳定）
    # 强制使用TCP模式，避免使用其他可能使用随机端口的协议
    export NCCL_SOCKET_FAMILY=AF_INET  # 强制使用IPv4 TCP
    echo "多机训练NCCL配置: 已禁用P2P和InfiniBand，强制使用TCP模式，端口范围: ${PORT_RANGE_START}-${PORT_RANGE_END}"
fi

# Tokenization和数据处理优化（解决tokenization超时问题）
export TOKENIZERS_PARALLELISM=false  # 禁用tokenizer的多进程，避免与分布式训练冲突
export OMP_NUM_THREADS=1  # 限制OpenMP线程数，避免过度并行化
export MKL_NUM_THREADS=1  # 限制MKL线程数
# 这些设置可以避免在数据预处理阶段产生额外的进程竞争，确保所有分布式进程同步

# PyTorch分布式训练超时配置（确保与NCCL_TIMEOUT一致）
export TORCH_DISTRIBUTED_TIMEOUT=7200  # PyTorch分布式操作的超时时间（秒），与NCCL_TIMEOUT保持一致

# 构建torchrun命令
# 单机训练使用 --standalone，多机训练使用 --nnodes, --node_rank, --master_addr, --master_port
if [ "${NNODES}" -eq 1 ]; then
    # 单机多卡训练
    # 注意:
    # 1. 不再使用 --standalone，强制显式指定 master_addr 和 master_port（如 40000）
    # 2. 这样可以避免 torchrun 随机选择端口（例如 36505），统一使用 MASTER_PORT 配置
    TORCHRUN_CMD="/opt/conda/envs/python3.10.13/bin/torchrun \
        --nnodes=${NNODES} \
        --node_rank=${NODE_RANK} \
        --nproc_per_node=${NPROC_PER_NODE} \
        --master_addr=${MASTER_ADDR} \
        --master_port=${MASTER_PORT}"
    echo "使用单机多卡训练模式（显式 master_port=${MASTER_PORT}）"
else
    # 多机多卡训练
    TORCHRUN_CMD="/opt/conda/envs/python3.10.13/bin/torchrun --nnodes=${NNODES} --node_rank=${NODE_RANK} --nproc_per_node=${NPROC_PER_NODE} --master_addr=${MASTER_ADDR} --master_port=${MASTER_PORT}"
    echo "使用多机多卡训练模式: ${NNODES} 个节点, 当前节点 ${NODE_RANK}, 主节点 ${MASTER_ADDR}:${MASTER_PORT}"
fi

# 构建命令
CMD="${TORCHRUN_CMD} train_sft.py \
    --model_name ${MODEL_NAME} \
    --output_dir ${OUTPUT_DIR} \
    --learning_rate ${LEARNING_RATE} \
    --per_device_train_batch_size ${BATCH_SIZE} \
    --gradient_accumulation_steps ${GRADIENT_ACCUMULATION_STEPS} \
    --num_train_epochs ${NUM_EPOCHS} \
    --max_seq_length ${MAX_SEQ_LENGTH} \
    --warmup_steps ${WARMUP_STEPS} \
    --seed ${SEED} \
    --save_steps ${SAVE_STEPS} \
    --logging_steps ${LOGGING_STEPS} \
    --eval_strategy ${EVAL_STRATEGY} \
    --dataloader_num_workers ${DATALOADER_NUM_WORKERS} \
    --max_steps ${MAX_STEPS} \
    --save_total_limit ${SAVE_TOTAL_LIMIT}"

# 添加可选参数
# 优先使用LLM_JSONL文件（如果存在且设置了）
if [ -n "${LLM_JSONL}" ]; then
    if [ -f "${LLM_JSONL}" ]; then
        echo "检测到LLM_JSONL文件: ${LLM_JSONL}"
        CMD="${CMD} --dataset ${LLM_JSONL}"
    else
        echo "警告: LLM_JSONL文件不存在: ${LLM_JSONL}，将使用其他数据集配置"
        if [ -n "${DATASET}" ]; then
            CMD="${CMD} --dataset ${DATASET}"
        fi
    fi
elif [ -n "${DATASET}" ]; then
    CMD="${CMD} --dataset ${DATASET}"
fi

# 处理子集名称（支持多个子集）
if [ -n "${SUBSET_NAME}" ]; then
    # 将多个子集名称作为多个参数传递
    CMD="${CMD} --subset_name"
    for subset in ${SUBSET_NAME}; do
        CMD="${CMD} ${subset}"
    done
fi

if [ -n "${TEXT_COLUMN}" ]; then
    CMD="${CMD} --text_column ${TEXT_COLUMN}"
fi

if [ -n "${USE_BF16}" ]; then
    CMD="${CMD} ${USE_BF16}"
fi

if [ -n "${USE_FP16}" ]; then
    CMD="${CMD} ${USE_FP16}"
fi

if [ -n "${GRADIENT_CHECKPOINTING}" ]; then
    CMD="${CMD} ${GRADIENT_CHECKPOINTING}"
fi

if [ -n "${USE_8BIT_OPTIMIZER}" ]; then
    CMD="${CMD} ${USE_8BIT_OPTIMIZER}"
fi

if [ -n "${PACKING}" ]; then
    CMD="${CMD} ${PACKING}"
fi

if [ -n "${PIN_MEMORY}" ]; then
    CMD="${CMD} ${PIN_MEMORY}"
fi

if [ "${EVAL_STRATEGY}" != "no" ]; then
    CMD="${CMD} --eval_steps ${EVAL_STEPS}"
fi

# 打印配置信息（同时输出到终端和日志文件）
{
    echo "=========================================="
    echo "SFT训练配置"
    echo "=========================================="
    echo "模型路径: ${MODEL_NAME}"
    echo "输出目录: ${OUTPUT_DIR}"
    if [ -n "${LLM_JSONL}" ] && [ -f "${LLM_JSONL}" ]; then
        echo "数据集: ${LLM_JSONL} (JSONL文件)"
    elif [ -n "${DATASET}" ]; then
        echo "数据集: ${DATASET}"
    else
        echo "数据集: 默认数据集 (AI-ModelScope/COIG-CQIA)"
    fi
    if [ -n "${SUBSET_NAME}" ]; then
        echo "子集名称: ${SUBSET_NAME}"
    else
        echo "子集名称: 所有默认子集 (chinese_traditional, coig_pc, exam, finance, douban, human_value, logi_qa, ruozhiba, segmentfault, wiki, wikihow, xhs, zhihu)"
    fi
    echo "学习率: ${LEARNING_RATE}"
    echo "批次大小: ${BATCH_SIZE}"
    echo "梯度累积步数: ${GRADIENT_ACCUMULATION_STEPS} (有效批次大小: $((BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS * NPROC_PER_NODE)))"
    echo "训练轮数: ${NUM_EPOCHS}"
    echo "最大序列长度: ${MAX_SEQ_LENGTH}"
    echo "保存检查点限制: ${SAVE_TOTAL_LIMIT}"
    if [ -n "${USE_8BIT_OPTIMIZER}" ]; then
        echo "8-bit优化器: 已启用（可节省约50-75%优化器状态显存）"
    fi
    echo "随机种子: ${SEED}"
    echo "每个节点GPU数量: ${NPROC_PER_NODE}"
    echo "总节点数: ${NNODES}"
    echo "当前节点编号: ${NODE_RANK}"
    if [ "${NNODES}" -gt 1 ]; then
        echo "主节点地址: ${MASTER_ADDR}:${MASTER_PORT}"
        echo "总GPU数量: $((NPROC_PER_NODE * NNODES))"
    fi
    echo "端口范围限制: ${PORT_RANGE_START}-${PORT_RANGE_END} (防火墙开放范围)"
    echo "日志文件: ${LOG_FILE}"
    echo "=========================================="
    echo ""
} | tee -a "${LOG_FILE}"


# 检查训练脚本是否存在
if [ ! -f "train_sft.py" ]; then
    echo "错误: 未找到train_sft.py文件"
    exit 1
fi

# 多机训练检查
if [ "${NNODES}" -gt 1 ]; then
    echo "=========================================="
    echo "多机训练配置检查"
    echo "=========================================="
    echo "请确保："
    echo "1. 所有节点都已安装相同的环境和依赖"
    echo "2. 所有节点都能访问主节点 ${MASTER_ADDR}:${MASTER_PORT}"
    echo "3. 所有节点使用相同的训练脚本和参数"
    echo "4. 主节点 (NODE_RANK=0) 先启动，然后启动从节点"
    echo "5. 防火墙允许端口范围 ${PORT_RANGE_START}-${PORT_RANGE_END} 通信（包括 ${MASTER_PORT}）"
    echo "6. 如果仍然出现端口连接错误，请检查："
    echo "   - NCCL是否使用了额外的端口（查看NCCL_DEBUG日志）"
    echo "   - 系统是否支持端口范围限制（某些系统可能需要root权限配置）"
    echo "   - 考虑使用iptables或防火墙规则进一步限制端口使用"
    echo "=========================================="
    echo ""
    
    # 检查主节点地址
    if [ "${MASTER_ADDR}" = "localhost" ] && [ "${NODE_RANK}" -gt 0 ]; then
        echo "错误: 从节点不能使用 localhost 作为主节点地址"
        echo "请设置 MASTER_ADDR 为主节点的实际IP地址"
        exit 1
    fi
    
    # 启动顺序检查：从节点需要等待主节点准备好
    if [ "${NODE_RANK}" -eq 0 ]; then
        echo "=========================================="
        echo "主节点启动 (NODE_RANK=0)"
        echo "=========================================="
        echo "主节点将立即启动，请等待主节点完全启动后再启动从节点"
        echo "主节点启动后，会在 ${MASTER_ADDR}:${MASTER_PORT} 上监听连接"
        echo "建议等待 10-30 秒后再启动从节点"
        echo "=========================================="
        echo ""
    else
        echo "=========================================="
        echo "从节点启动 (NODE_RANK=${NODE_RANK})"
        echo "=========================================="
        echo "正在检查主节点 ${MASTER_ADDR}:${MASTER_PORT} 是否已准备好..."
        
        # 检查主节点端口是否在监听（最多等待5分钟）
        MAX_WAIT_TIME=300  # 5分钟
        WAIT_INTERVAL=2    # 每2秒检查一次
        ELAPSED_TIME=0
        MASTER_READY=0
        
        # 检查是否有nc或telnet命令可用
        if command -v nc &> /dev/null; then
            CHECK_CMD="nc -z -w 1 ${MASTER_ADDR} ${MASTER_PORT}"
        elif command -v telnet &> /dev/null; then
            CHECK_CMD="timeout 1 telnet ${MASTER_ADDR} ${MASTER_PORT} 2>&1 | grep -q 'Connected'"
        else
            # 如果没有nc或telnet，使用Python检查
            CHECK_CMD="python3 -c \"import socket; s=socket.socket(); s.settimeout(1); result=s.connect_ex(('${MASTER_ADDR}', ${MASTER_PORT})); s.close(); exit(0 if result == 0 else 1)\""
        fi
        
        while [ ${ELAPSED_TIME} -lt ${MAX_WAIT_TIME} ]; do
            if eval ${CHECK_CMD} &> /dev/null; then
                MASTER_READY=1
                echo "✓ 主节点已准备好！端口 ${MASTER_ADDR}:${MASTER_PORT} 正在监听"
                break
            else
                echo "等待主节点启动... (已等待 ${ELAPSED_TIME} 秒，最多等待 ${MAX_WAIT_TIME} 秒)"
                sleep ${WAIT_INTERVAL}
                ELAPSED_TIME=$((ELAPSED_TIME + WAIT_INTERVAL))
            fi
        done
        
        if [ ${MASTER_READY} -eq 0 ]; then
            echo "错误: 等待超时，主节点 ${MASTER_ADDR}:${MASTER_PORT} 在 ${MAX_WAIT_TIME} 秒内未准备好"
            echo "请检查："
            echo "1. 主节点是否已启动（NODE_RANK=0）"
            echo "2. 主节点地址 ${MASTER_ADDR} 是否正确"
            echo "3. 端口 ${MASTER_PORT} 是否被防火墙阻止"
            echo "4. 网络连接是否正常"
            exit 1
        fi
        
        echo "从节点准备就绪，即将连接到主节点..."
        echo "=========================================="
        echo ""
    fi
fi

# 执行训练命令（后台运行）
echo "开始执行训练..."
echo "命令: ${CMD}"
echo "日志文件: ${LOG_FILE}"
echo ""

# 多机训练时，主节点启动后等待几秒确保端口监听就绪
if [ "${NNODES}" -gt 1 ] && [ "${NODE_RANK}" -eq 0 ]; then
    echo "主节点正在启动，等待服务就绪..."
    # 使用 nohup 在后台运行，并将输出追加到日志文件
    nohup bash -c "${CMD}" >> "${LOG_FILE}" 2>&1 &
    TRAIN_PID=$!
    
    # 等待主节点启动并开始监听端口（最多等待30秒）
    echo "等待主节点服务启动（最多30秒）..."
    MASTER_STARTED=0
    for i in {1..30}; do
        sleep 1
        # 检查端口是否在监听
        if command -v nc &> /dev/null; then
            if nc -z -w 1 ${MASTER_ADDR} ${MASTER_PORT} 2>/dev/null; then
                MASTER_STARTED=1
                echo "✓ 主节点服务已启动，端口 ${MASTER_ADDR}:${MASTER_PORT} 正在监听"
                break
            fi
        elif command -v python3 &> /dev/null; then
            if python3 -c "import socket; s=socket.socket(); s.settimeout(1); result=s.connect_ex(('${MASTER_ADDR}', ${MASTER_PORT})); s.close(); exit(0 if result == 0 else 1)" 2>/dev/null; then
                MASTER_STARTED=1
                echo "✓ 主节点服务已启动，端口 ${MASTER_ADDR}:${MASTER_PORT} 正在监听"
                break
            fi
        fi
        if [ $((i % 5)) -eq 0 ]; then
            echo "  等待中... (${i}/30 秒)"
        fi
    done
    
    if [ ${MASTER_STARTED} -eq 0 ]; then
        echo "警告: 无法确认主节点端口是否已启动，但训练进程已启动"
        echo "如果从节点连接失败，请检查主节点日志: ${LOG_FILE}"
    else
        echo "主节点已就绪，现在可以启动从节点了"
        echo "建议等待 5-10 秒后再启动从节点，确保主节点完全初始化"
    fi
    echo ""
else
    # 单机训练或从节点，直接启动
    # 使用 nohup 在后台运行，并将输出追加到日志文件
    nohup bash -c "${CMD}" >> "${LOG_FILE}" 2>&1 &
    TRAIN_PID=$!
fi

# 等待一下确保进程启动
sleep 1

# 检查进程是否还在运行
if ps -p ${TRAIN_PID} > /dev/null 2>&1; then
    echo "训练已在后台启动！"
    echo "进程ID: ${TRAIN_PID}"
    echo "日志文件: ${LOG_FILE}"
    echo ""
    echo "查看日志: tail -f ${LOG_FILE}"
    echo "查看进程: ps -p ${TRAIN_PID}"
    echo ""
else
    echo "错误: 训练进程启动失败，请查看日志文件: ${LOG_FILE}"
    exit 1
fi



```

**Comment by guotong1988** [comment]
train_sft.py
```python
import argparse
import os
from dataclasses import dataclass
from datetime import timedelta
from typing import Optional, Union, List, Dict, Any

import torch
from datasets import Dataset, concatenate_datasets
from modelscope.msdatasets import MsDataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    set_seed,
    TrainerCallback,
)
from trl import SFTConfig, SFTTrainer


class NanDetectionCallback(TrainerCallback):
    """检测和处理训练过程中的NaN值，防止训练崩溃"""
    
    def __init__(self, skip_bad_batches: bool = True, max_nan_count: int = 5):
        """
        Args:
            skip_bad_batches: 如果检测到NaN，是否跳过当前batch
            max_nan_count: 连续NaN的最大次数，超过后停止训练
        """
        self.skip_bad_batches = skip_bad_batches
        self.max_nan_count = max_nan_count
        self.nan_count = 0
        self.last_valid_step = 0
        self.current_loss = None
        
    def on_backward(self, args, state, control, model=None, **kwargs):
        """在反向传播后检查梯度中的NaN"""
        if model is None:
            return control
            
        # 检查模型参数和梯度中是否有NaN
        has_nan = False
        for name, param in model.named_parameters():
            if param.grad is not None:
                if torch.isnan(param.grad).any() or torch.isinf(param.grad).any():
                    print(f"警告: 检测到NaN/Inf梯度 (参数: {name}, step {state.global_step})")
                    has_nan = True
                    # 将NaN梯度置零，防止传播
                    param.grad = torch.where(
                        torch.isnan(param.grad) | torch.isinf(param.grad),
                        torch.zeros_like(param.grad),
                        param.grad
                    )
        
        if has_nan:
            self.nan_count += 1
            if self.nan_count >= self.max_nan_count:
                print(f"错误: 连续NaN次数超过限制 ({self.max_nan_count})，停止训练")
                control.should_training_stop = True
        
        return control
        
    def on_step_end(self, args, state, control, model=None, logs=None, **kwargs):
        """在每个训练步骤结束时检查NaN"""
        if logs is None:
            return
            
        # 检查loss是否为NaN
        loss = logs.get("loss", None)
        if loss is not None:
            self.current_loss = loss
            # 处理loss可能是tensor或float的情况
            if isinstance(loss, torch.Tensor):
                is_nan = torch.isnan(loss) or torch.isinf(loss)
            else:
                is_nan = (loss != loss) or (abs(loss) == float('inf'))
            
            if is_nan:
                self.nan_count += 1
                print(f"警告: 检测到NaN/Inf loss (step {state.global_step}), 连续NaN次数: {self.nan_count}")
                print(f"当前loss值: {loss}")
                
                if self.nan_count >= self.max_nan_count:
                    print(f"错误: 连续NaN次数超过限制 ({self.max_nan_count})，停止训练")
                    control.should_training_stop = True
                    return control
            else:
                # 如果loss正常，重置NaN计数
                if self.nan_count > 0:
                    print(f"Loss恢复正常 (step {state.global_step}), loss={loss:.6f}")
                self.nan_count = 0
                self.last_valid_step = state.global_step
        
        # 检查entropy是否为NaN
        entropy = logs.get("entropy", None)
        if entropy is not None:
            # 处理entropy可能是tensor或float的情况
            if isinstance(entropy, torch.Tensor):
                is_nan = torch.isnan(entropy) or torch.isinf(entropy)
            else:
                is_nan = (entropy != entropy) or (abs(entropy) == float('inf'))
            
            if is_nan:
                print(f"警告: 检测到NaN/Inf entropy (step {state.global_step}), entropy={entropy}")
                # entropy的NaN通常会导致loss的NaN，增加计数
                if loss is None or (not isinstance(loss, torch.Tensor) and loss == loss):
                    # 如果loss还没变成NaN，提前警告
                    self.nan_count += 1
                    if self.nan_count >= self.max_nan_count:
                        print(f"错误: 连续NaN次数超过限制 ({self.max_nan_count})，停止训练")
                        control.should_training_stop = True
        
        return control
    
    def on_log(self, args, state, control, logs=None, **kwargs):
        """在日志记录时检查模型参数中的NaN"""
        if logs is None:
            return
            
        # 记录关键指标
        if self.nan_count > 0:
            print(f"当前NaN计数: {self.nan_count}/{self.max_nan_count}")
        
        return control


def format_dataset_for_sft(ds, text_column: str = "text", max_length: int = 2048, tokenizer=None):
    """将数据集格式化为SFT训练所需的格式（使用Qwen3 chat template）

    Args:
        ds: 数据集对象
        text_column: 文本列名，如果不存在则尝试从对话格式构建
        max_length: 最大序列长度
        tokenizer: 分词器，用于应用chat template（Qwen3系列）
    """
    # 打印原始数据集信息
    print(f"原始数据集大小: {len(ds)}")
    print(f"原始数据集列名: {ds.column_names}")
    if len(ds) > 0:
        print(f"第一个样本的键: {list(ds[0].keys())}")
        print(f"第一个样本示例（前200字符）: {str(ds[0])[:200]}")

    # 检查是否可以使用chat template
    use_chat_template = tokenizer is not None and hasattr(tokenizer, "apply_chat_template")
    if use_chat_template:
        print("使用Qwen3 chat template格式化数据")
    else:
        print("警告: 未提供tokenizer或tokenizer不支持chat template，将使用简单格式")

    def format_conversation(example):
        """格式化对话数据为文本格式（使用Qwen3 chat template）"""
        # 如果已经有text字段，检查是否已经是chat template格式
        if text_column in example and example[text_column]:
            text_val = example[text_column]
            if text_val and str(text_val).strip():
                # 如果已经包含chat template标记，直接返回
                if "<|im_start|>" in str(text_val) or "<|im_end|>" in str(text_val):
                    return {"text": str(text_val)}
                # 否则尝试用chat template重新格式化（如果有conversations信息）
                # 这里先返回原文本，后续可以改进

        # 尝试从对话格式构建（优先使用chat template）
        if "conversations" in example or "messages" in example:
            conversations = example.get("conversations") or example.get("messages", [])
            if isinstance(conversations, str):
                # 如果是字符串，尝试解析JSON
                import json
                try:
                    conversations = json.loads(conversations)
                except:
                    pass
            
            if isinstance(conversations, list) and len(conversations) > 0:
                # 构建messages列表用于chat template
                messages = []
                for msg in conversations:
                    if isinstance(msg, dict):
                        role = msg.get("role", msg.get("from", ""))
                        content = msg.get("content", msg.get("value", ""))
                        if role and content:
                            # 标准化角色名称
                            if role in ["user", "human"]:
                                messages.append({"role": "user", "content": str(content)})
                            elif role in ["assistant", "gpt", "bot"]:
                                messages.append({"role": "assistant", "content": str(content)})
                            else:
                                messages.append({"role": role, "content": str(content)})
                
                # 使用chat template格式化
                if messages and use_chat_template:
                    try:
                        formatted_text = tokenizer.apply_chat_template(
                            messages,
                            tokenize=False,
                            add_generation_prompt=False  # 训练时不需要generation prompt
                        )
                        return {"text": formatted_text}
                    except Exception as e:
                        print(f"警告: 使用chat template失败: {e}，回退到简单格式")
                        # 回退到简单格式
                        text_parts = []
                        for msg in messages:
                            role = msg.get("role", "")
                            content = msg.get("content", "")
                            if role == "user":
                                text_parts.append(f"用户: {content}")
                            elif role == "assistant":
                                text_parts.append(f"助手: {content}")
                            else:
                                text_parts.append(f"{role}: {content}")
                        if text_parts:
                            return {"text": "\n".join(text_parts)}
                elif messages:
                    # 没有chat template，使用简单格式
                    text_parts = []
                    for msg in messages:
                        role = msg.get("role", "")
                        content = msg.get("content", "")
                        if role == "user":
                            text_parts.append(f"用户: {content}")
                        elif role == "assistant":
                            text_parts.append(f"助手: {content}")
                        else:
                            text_parts.append(f"{role}: {content}")
                    if text_parts:
                        return {"text": "\n".join(text_parts)}

        # 尝试从prompt和response构建
        if "prompt" in example and "response" in example:
            prompt = example.get("prompt", "")
            response = example.get("response", "")
            if prompt or response:
                if use_chat_template:
                    try:
                        messages = [
                            {"role": "user", "content": str(prompt)},
                            {"role": "assistant", "content": str(response)}
                        ]
                        formatted_text = tokenizer.apply_chat_template(
                            messages,
                            tokenize=False,
                            add_generation_prompt=False
                        )
                        return {"text": formatted_text}
                    except Exception as e:
                        print(f"警告: 使用chat template失败: {e}，回退到简单格式")
                return {"text": f"用户: {prompt}\n助手: {response}"}

        # 尝试从input和output构建
        if "input" in example and "output" in example:
            input_text = example.get("input", "")
            output_text = example.get("output", "")
            if input_text or output_text:
                if use_chat_template:
                    try:
                        messages = [
                            {"role": "user", "content": str(input_text)},
                            {"role": "assistant", "content": str(output_text)}
                        ]
                        formatted_text = tokenizer.apply_chat_template(
                            messages,
                            tokenize=False,
                            add_generation_prompt=False
                        )
                        return {"text": formatted_text}
                    except Exception as e:
                        print(f"警告: 使用chat template失败: {e}，回退到简单格式")
                return {"text": f"用户: {input_text}\n助手: {output_text}"}

        # 尝试从instruction和output构建
        if "instruction" in example and "output" in example:
            instruction = example.get("instruction", "")
            output = example.get("output", "")
            if instruction or output:
                if use_chat_template:
                    try:
                        messages = [
                            {"role": "user", "content": str(instruction)},
                            {"role": "assistant", "content": str(output)}
                        ]
                        formatted_text = tokenizer.apply_chat_template(
                            messages,
                            tokenize=False,
                            add_generation_prompt=False
                        )
                        return {"text": formatted_text}
                    except Exception as e:
                        print(f"警告: 使用chat template失败: {e}，回退到简单格式")
                return {"text": f"用户: {instruction}\n助手: {output}"}

        # 如果都没有，尝试将所有非空字段拼接
        text_parts = []
        for key, value in example.items():
            if value and isinstance(value, (str, int, float)):
                text_parts.append(f"{key}: {value}")
        if text_parts:
            return {"text": "\n".join(text_parts)}

        # 如果都没有，返回空字符串
        return {"text": ""}

    # 应用格式化函数
    # 在分布式训练中，禁用多进程处理以确保所有进程同步
    # num_proc=1 确保每个进程独立处理，避免进程间竞争
    formatted_ds = ds.map(
        format_conversation, 
        remove_columns=ds.column_names,
        num_proc=1,  # 禁用多进程，避免在分布式训练中产生额外的进程竞争
        desc="格式化数据集"
    )
    print(f"格式化后数据集大小（过滤前）: {len(formatted_ds)}")

    # 检查格式化后的数据
    if len(formatted_ds) > 0:
        non_empty_count = sum(1 for i in range(min(10, len(formatted_ds))) if formatted_ds[i]["text"].strip())
        print(f"前10个样本中非空文本数量: {non_empty_count}")
        if non_empty_count > 0:
            print(f"第一个非空样本示例: {formatted_ds[0]['text'][:200]}")

    # 过滤空文本
    # 同样禁用多进程处理
    formatted_ds = formatted_ds.filter(
        lambda x: len(x["text"].strip()) > 0,
        num_proc=1,  # 禁用多进程
        desc="过滤空文本"
    )
    print(f"过滤后数据集大小: {len(formatted_ds)}")

    return formatted_ds


def load_dataset_for_sft(
        dataset_name_or_path: Optional[str] = None,
        subset_name: Optional[Union[str, List[str]]] = None,
        split: str = "train",
        text_column: str = "text",
        max_length: int = 2048,
        tokenizer=None,
) -> Dataset:
    """加载并格式化数据集用于SFT训练"""
    if dataset_name_or_path:
        # 如果是本地路径
        if os.path.exists(dataset_name_or_path):
            from datasets import load_dataset
            import json
            # 检查文件扩展名以确定加载方式
            if dataset_name_or_path.endswith('.jsonl'):
                # 从JSONL文件加载（逐行读取）
                print(f"从JSONL文件加载: {dataset_name_or_path}")
                data = []
                with open(dataset_name_or_path, 'r', encoding='utf-8') as f:
                    for line_num, line in enumerate(f, 1):
                        line = line.strip()
                        if line:  # 跳过空行
                            try:
                                data.append(json.loads(line))
                            except json.JSONDecodeError as e:
                                print(f"警告: 第 {line_num} 行JSON解析失败: {e}")
                                continue
                print(f"从JSONL文件读取了 {len(data)} 条记录")
                ds = Dataset.from_list(data)
            else:
                # 从JSON文件加载（使用datasets库）
                ds = load_dataset("json", data_files=dataset_name_or_path, split=split)
        else:
            # 尝试从ModelScope加载
            try:
                if subset_name:
                    if isinstance(subset_name, list):
                        # 加载多个子集并合并
                        datasets = []
                        for subset in subset_name:
                            print(f"加载子集: {subset}")
                            subset_ds = MsDataset.load(dataset_name_or_path, subset_name=subset, split=split)
                            if hasattr(subset_ds, 'to_hf_dataset'):
                                subset_ds = subset_ds.to_hf_dataset()
                            datasets.append(subset_ds)
                        print(f"合并 {len(datasets)} 个子集...")
                        ds = concatenate_datasets(datasets)
                    else:
                        ds = MsDataset.load(dataset_name_or_path, subset_name=subset_name, split=split)
                else:
                    ds = MsDataset.load(dataset_name_or_path, split=split)
                # 转换为HuggingFace Dataset格式（如果还不是）
                if hasattr(ds, 'to_hf_dataset'):
                    ds = ds.to_hf_dataset()
                # 如果已经是HuggingFace Dataset，直接使用
            except Exception as e:
                print(f"从ModelScope加载失败，尝试从HuggingFace加载: {e}")
                from datasets import load_dataset
                ds = load_dataset(dataset_name_or_path, split=split)
    else:
        # 使用默认数据集，加载所有可用的子集
        default_subsets = [
            'chinese_traditional',
            'coig_pc',
            'exam',
            'finance',
            'douban',
            'human_value',
            'logi_qa',
            'ruozhiba',
            'segmentfault',
            'wiki',
            'wikihow',
            'xhs',
            'zhihu'
        ]

        # 如果指定了subset_name，使用指定的；否则使用所有默认子集
        if subset_name:
            if isinstance(subset_name, str):
                subset_list = [subset_name]
            else:
                subset_list = subset_name
        else:
            subset_list = default_subsets

        print(f"使用默认数据集: AI-ModelScope/COIG-CQIA")
        print(f"加载子集: {subset_list}")

        datasets = []
        for subset in subset_list:
            try:
                print(f"正在加载子集: {subset}...")
                subset_ds = MsDataset.load('AI-ModelScope/COIG-CQIA', subset_name=subset, split='train')
                # 转换为HuggingFace Dataset格式（如果还不是）
                if hasattr(subset_ds, 'to_hf_dataset'):
                    subset_ds = subset_ds.to_hf_dataset()
                print(f"子集 {subset} 加载完成，大小: {len(subset_ds)}")
                datasets.append(subset_ds)
            except Exception as e:
                print(f"警告: 加载子集 {subset} 失败: {e}")
                continue

        if not datasets:
            raise ValueError("所有子集加载失败，请检查数据集名称和网络连接")

        print(f"合并 {len(datasets)} 个子集...")
        ds = concatenate_datasets(datasets)
        print(f"合并后数据集总大小: {len(ds)}")

    # 检查数据集是否为空
    if len(ds) == 0:
        print("警告: 加载的数据集为空！")
        print("请检查数据集路径或名称是否正确。")
        return ds

    # 格式化数据集（使用Qwen3 chat template）
    formatted_ds = format_dataset_for_sft(ds, text_column=text_column, max_length=max_length, tokenizer=tokenizer)

    # 清理原始数据集以释放内存
    del ds
    import gc
    gc.collect()

    if len(formatted_ds) == 0:
        print("警告: 格式化后的数据集为空！")
        print("可能的原因:")
        print("1. 数据集格式不符合预期")
        print("2. 所有数据都被过滤掉了")
        print("3. 数据格式解析失败")
        print(f"请检查原始数据集的列名和格式: {ds.column_names}")
        if len(ds) > 0:
            print(f"原始数据示例: {ds[0]}")

    return formatted_ds


@dataclass
class DataCollatorForCausalLM:
    """用于通用文本全量微调的 data collator。

    功能：
    - 使用 tokenizer 对样本中的 `text` 字段做截断和 padding
    - 构造 labels，并将 padding 位置的标签置为 -100（忽略这些位置的 loss）
    - 对非 padding 的 token 全量计算 loss，适用于通用语言建模目标
    """

    tokenizer: AutoTokenizer
    max_length: int = 2048

    def __call__(self, features: List[Dict[str, Any]]) -> Dict[str, torch.Tensor]:
        # 从样本中取出文本字段
        texts = [f["text"] for f in features]

        # 统一做 tokenize / 截断 / padding
        batch = self.tokenizer(
            texts,
            max_length=self.max_length,
            truncation=True,
            padding=True,
            return_tensors="pt",
        )

        # labels 初始与 input_ids 一致
        labels = batch["input_ids"].clone()

        # 将 padding 位置的 label 置为 -100，避免对 padding 计算 loss
        if "attention_mask" in batch:
            pad_mask = batch["attention_mask"] == 0
            labels[pad_mask] = -100

        batch["labels"] = labels
        return batch


def main() -> None:
    parser = argparse.ArgumentParser(description="SFT训练 (TRL)")
    parser.add_argument("--model_name", type=str, default="/data/Qwen3-32B",
                        help="模型路径或名称")
    parser.add_argument("--dataset", type=str, default=None,
                        help="数据集名称或路径，如果为None则使用默认数据集")
    parser.add_argument("--subset_name", default=None, nargs='+',
                        help="数据集子集名称（用于ModelScope），可以指定多个，用空格分隔。如果不指定，则使用所有默认子集")
    parser.add_argument("--text_column", type=str, default="text",
                        help="文本列名")
    parser.add_argument("--output_dir", type=str, default="./outputs-sft",
                        help="输出目录")
    parser.add_argument("--seed", type=int, default=42,
                        help="随机种子")
    parser.add_argument("--learning_rate", type=float, default=2e-5,
                        help="学习率")
    parser.add_argument("--per_device_train_batch_size", type=int, default=4,
                        help="每个设备的训练批次大小")
    parser.add_argument("--gradient_accumulation_steps", type=int, default=4,
                        help="梯度累积步数")
    parser.add_argument("--num_train_epochs", type=int, default=3,
                        help="训练轮数")
    parser.add_argument("--max_seq_length", type=int, default=2048,
                        help="最大序列长度")
    parser.add_argument("--bf16", action="store_true",
                        help="使用bfloat16精度")
    parser.add_argument("--fp16", action="store_true",
                        help="使用float16精度")
    parser.add_argument("--dataloader_num_workers", type=int, default=4,
                        help="数据加载器工作进程数")
    parser.add_argument("--dataloader_pin_memory", action="store_true",
                        help="启用数据加载器pin memory")
    parser.add_argument("--warmup_steps", type=int, default=100,
                        help="预热步数")
    parser.add_argument("--save_steps", type=int, default=500,
                        help="保存检查点的步数")
    parser.add_argument("--logging_steps", type=int, default=10,
                        help="日志记录步数")
    parser.add_argument("--eval_strategy", type=str, default="no",
                        choices=["no", "steps", "epoch"],
                        help="评估策略")
    parser.add_argument("--eval_steps", type=int, default=500,
                        help="评估步数（当eval_strategy=steps时）")
    parser.add_argument("--push_to_hub", action="store_true",
                        help="推送到HuggingFace Hub")
    parser.add_argument("--max_steps", type=int, default=-1,
                        help="最大训练步数，-1表示使用num_train_epochs")
    parser.add_argument("--gradient_checkpointing", action="store_true",
                        help="启用梯度检查点以节省内存")
    parser.add_argument("--packing", action="store_true",
                        help="启用序列打包以提高效率")
    parser.add_argument("--save_total_limit", type=int, default=3,
                        help="保存的检查点数量限制")
    parser.add_argument("--max_memory_MB", type=int, default=None,
                        help="每个GPU的最大显存限制（MB），用于模型加载时的内存管理")
    parser.add_argument("--use_8bit_optimizer", action="store_true",
                        help="使用8-bit优化器（bitsandbytes），可大幅减少优化器状态显存（节省约50-75%优化器显存）")
    parser.add_argument("--optim", type=str, default="adamw_torch",
                        help="优化器类型，如果使用8-bit优化器，应设置为adamw_8bit或paged_adamw_8bit")
    parser.add_argument("--max_grad_norm", type=float, default=1.0,
                        help="梯度裁剪的最大范数，用于防止梯度爆炸（默认1.0，设置为0禁用）")
    parser.add_argument("--skip_bad_batches", default=True,
                        help="当检测到NaN时跳过当前batch，防止训练崩溃（推荐启用）")
    parser.add_argument("--max_nan_count", type=int, default=5,
                        help="连续NaN的最大次数，超过后停止训练（默认5）")

    args = parser.parse_args()
    
    # 设置skip_bad_batches的默认值（如果用户没有指定，默认为True）
    # 如果用户指定了--skip_bad_batches，skip_bad_batches会被设置为True
    # 如果用户都没有指定，我们需要设置默认值为True
    if not hasattr(args, 'skip_bad_batches') or getattr(args, 'skip_bad_batches', None) is None:
        args.skip_bad_batches = True
    set_seed(args.seed)

    # 加载模型和分词器
    print(f"加载模型: {args.model_name}")
    tokenizer = AutoTokenizer.from_pretrained(args.model_name, use_fast=True, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        tokenizer.pad_token_id = tokenizer.eos_token_id

    # 检测分布式训练环境（torchrun会自动设置环境变量和初始化进程组）
    if "RANK" in os.environ and "WORLD_SIZE" in os.environ:
        rank = int(os.environ["RANK"])
        world_size = int(os.environ["WORLD_SIZE"])
        local_rank = int(os.environ.get("LOCAL_RANK", rank))
        master_addr = os.environ.get("MASTER_ADDR", "localhost")
        master_port = os.environ.get("MASTER_PORT", "40000")
        
        # 多机多卡训练相关环境变量
        node_rank = int(os.environ.get("NODE_RANK", 0))  # 当前节点编号（从0开始）
        nnodes = int(os.environ.get("NNODES", 1))  # 总节点数
        nproc_per_node = int(os.environ.get("NPROC_PER_NODE", world_size))  # 每个节点的进程数（GPU数）

        # 设置设备（必须在初始化进程组之前）
        torch.cuda.set_device(local_rank)
        device = torch.device(f"cuda:{local_rank}")
        
        # 设置NCCL超时时间（从环境变量读取，默认3600秒）
        nccl_timeout = int(os.environ.get("NCCL_TIMEOUT", "3600"))
        timeout = timedelta(seconds=nccl_timeout)
        
        # 端口范围限制配置（从环境变量读取，确保只使用防火墙开放的端口）
        port_range = os.environ.get("TORCH_DISTRIBUTED_PORT_RANGE", None)
        port_start = None
        port_end = None
        if port_range:
            # 解析端口范围（格式：40000-40050）
            try:
                port_start, port_end = map(int, port_range.split("-"))
                print(f"端口范围限制: {port_start}-{port_end}")
                # 验证MASTER_PORT是否在允许范围内
                master_port_int = int(master_port)
                if master_port_int < port_start or master_port_int > port_end:
                    print(f"警告: MASTER_PORT ({master_port}) 不在允许的端口范围内 ({port_start}-{port_end})")
                    print(f"建议将MASTER_PORT设置为 {port_start} 到 {port_end} 之间的值")
                else:
                    print(f"✓ MASTER_PORT ({master_port}) 在允许的端口范围内")
            except ValueError:
                print(f"警告: 无法解析端口范围: {port_range}，格式应为 'start-end' (例如: 40000-40050)")
        else:
            print("提示: 未设置TORCH_DISTRIBUTED_PORT_RANGE环境变量，建议设置以限制端口使用")
        
        # 设置NCCL和PyTorch使用受限的端口范围
        # 注意：PyTorch分布式训练可能会使用额外的端口，我们需要确保这些端口在允许范围内
        # 通过设置环境变量来限制（如果系统支持）
        if port_range and port_start and port_end:
            # 确保NCCL socket配置已设置（减少端口使用）
            if "NCCL_SOCKET_NTHREADS" not in os.environ:
                os.environ["NCCL_SOCKET_NTHREADS"] = "2"
            if "NCCL_NSOCKS_PERTHREAD" not in os.environ:
                os.environ["NCCL_NSOCKS_PERTHREAD"] = "4"
            print(f"已设置NCCL socket配置以减少端口使用")
            print(f"注意: 如果仍然遇到端口连接错误（如55995），可能需要使用系统级别的端口限制")
            print(f"     可以使用iptables或firewall规则限制端口范围为 {port_start}-{port_end}")
        
        # torchrun应该已经初始化了进程组，这里只检查状态
        if torch.distributed.is_initialized():
            print("="*60)
            print("多机多卡分布式训练配置:")
            print(f"  总节点数 (NNODES): {nnodes}")
            print(f"  当前节点编号 (NODE_RANK): {node_rank}")
            print(f"  每个节点GPU数 (NPROC_PER_NODE): {nproc_per_node}")
            print(f"  全局进程编号 (RANK): {rank}/{world_size-1}")
            print(f"  本地进程编号 (LOCAL_RANK): {local_rank}/{nproc_per_node-1}")
            print(f"  总进程数 (WORLD_SIZE): {world_size}")
            print(f"  主节点地址: {master_addr}:{master_port}")
            print(f"  当前设备: {device}")
            print(f"  NCCL超时设置: {nccl_timeout}秒")
            if port_range:
                print(f"  端口范围限制: {port_range}")
            print("="*60)
            # 注意：如果进程组已经初始化，无法再修改超时时间
            # 但我们可以确保环境变量已设置，以便后续操作使用
        else:
            print(f"警告: 分布式进程组未初始化，但检测到分布式环境变量")
            print(f"这通常不应该发生，torchrun应该已经初始化了进程组")
            # 如果未初始化，手动初始化（这种情况不应该发生，但作为备用方案）
            try:
                torch.distributed.init_process_group(
                    backend="nccl",
                    timeout=timeout,
                    init_method=f"tcp://{master_addr}:{master_port}",
                    rank=rank,
                    world_size=world_size
                )
                print(f"手动初始化分布式进程组成功，超时时间: {timeout}")
            except Exception as e:
                print(f"手动初始化失败: {e}")
        
        # 确保所有进程同步（barrier），避免某些进程启动过快导致通信问题
        if torch.distributed.is_initialized():
            try:
                torch.distributed.barrier()
                if rank == 0:
                    print(f"所有 {world_size} 个进程已同步，开始训练准备...")
            except Exception as e:
                print(f"警告: 同步操作失败: {e}")
                print(f"这可能是由于某些进程启动较慢，继续尝试...")
        
        print(f"节点 {node_rank} - 进程 {rank}/{world_size-1} (本地 {local_rank}/{nproc_per_node-1}) 在设备 {device} 上运行")
    else:
        rank = 0
        world_size = 1
        local_rank = 0
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        print(f"单GPU训练模式，使用设备: {device}")

    # 优化模型加载以减少显存占用
    # 注意：当使用Trainer的FP16/BF16选项时，不应该在加载时指定torch_dtype
    # Trainer会自动处理混合精度训练，包括模型的数据类型转换
    # 如果在加载时指定了torch_dtype，会导致梯度缩放冲突错误
    # 使用low_cpu_mem_usage可以减少CPU内存占用
    model_kwargs = {
        "trust_remote_code": True,
        "low_cpu_mem_usage": True,  # 减少CPU内存占用
    }

    # 如果指定了显存限制，使用max_memory参数
    # 注意：在DDP模式下不能使用device_map，因为DDP会自己管理设备分配
    if args.max_memory_MB is not None and not ("RANK" in os.environ and "WORLD_SIZE" in os.environ):
        # 只在单GPU训练时使用device_map和max_memory
        max_memory = {0: f"{args.max_memory_MB}MB"}
        model_kwargs["max_memory"] = max_memory
        model_kwargs["device_map"] = "auto"  # 使用device_map自动分配
    elif args.max_memory_MB is not None:
        print(f"警告: 在分布式训练模式下，max_memory参数将被忽略（DDP模式不支持device_map）")

    model = AutoModelForCausalLM.from_pretrained(
        args.model_name,
        **model_kwargs
    )

    # 清理显存缓存
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        import gc
        gc.collect()

    # 将模型移动到对应设备
    # 如果使用了device_map="auto"，模型已经自动分配到设备，不需要再次移动
    if "device_map" not in model_kwargs:
        model = model.to(device)

    if args.gradient_checkpointing:
        model.gradient_checkpointing_enable()

    # 在数据加载前同步所有进程
    if torch.distributed.is_initialized():
        print(f"进程 {rank} 等待所有进程就绪，准备加载数据...")
        try:
            torch.distributed.barrier()
            print(f"进程 {rank} 开始加载数据...")
        except Exception as e:
            print(f"警告: 数据加载前同步失败: {e}")
            print(f"继续尝试加载数据...")

    # 加载和格式化数据集（使用Qwen3 chat template）
    print("加载数据集...")
    train_ds = load_dataset_for_sft(
        dataset_name_or_path=args.dataset,
        subset_name=args.subset_name,
        split="train",
        text_column=args.text_column,
        max_length=args.max_seq_length,
        tokenizer=tokenizer,  # 传递tokenizer以使用chat template
    )
    print(f"训练集大小: {len(train_ds)}")
    
    # 数据加载和格式化完成后，同步所有进程
    # 这确保所有进程都完成数据预处理后再继续，避免tokenization时的等待超时
    if torch.distributed.is_initialized():
        print(f"进程 {rank} 数据加载完成，等待所有进程同步...")
        try:
            torch.distributed.barrier()
            print(f"进程 {rank} 所有进程数据加载完成，继续训练准备...")
        except Exception as e:
            print(f"警告: 数据加载后同步失败: {e}")
            print(f"继续尝试创建trainer...")

    # 配置训练参数
    sft_cfg_kwargs = {
        "output_dir": args.output_dir,
        "learning_rate": args.learning_rate,
        "per_device_train_batch_size": args.per_device_train_batch_size,
        "gradient_accumulation_steps": args.gradient_accumulation_steps,
        "num_train_epochs": args.num_train_epochs,
        "warmup_steps": args.warmup_steps,
        "save_steps": args.save_steps,
        "logging_steps": args.logging_steps,
        "eval_strategy": args.eval_strategy,
        "save_strategy": "steps",
        "save_total_limit": args.save_total_limit,
        "load_best_model_at_end": False,
        "fp16": args.fp16 and not args.bf16,
        "bf16": args.bf16,
        "dataloader_num_workers": args.dataloader_num_workers,
        "dataloader_pin_memory": args.dataloader_pin_memory,
        "report_to": ["none"],
        "push_to_hub": args.push_to_hub,
        "gradient_checkpointing": args.gradient_checkpointing,
        "packing": args.packing,
        "remove_unused_columns": False,
        "dataset_text_field": args.text_column,
    }
    
    # 添加梯度裁剪（防止梯度爆炸，这是导致NaN的主要原因之一）
    if args.max_grad_norm > 0:
        sft_cfg_kwargs["max_grad_norm"] = args.max_grad_norm
        print(f"启用梯度裁剪，最大范数: {args.max_grad_norm}")
    else:
        print("警告: 未启用梯度裁剪，如果遇到NaN问题，建议设置 --max_grad_norm 1.0")

    # 如果使用8-bit优化器，设置优化器类型
    if args.use_8bit_optimizer:
        try:
            import bitsandbytes as bnb
            print("bitsandbytes已安装，可以使用8-bit优化器")
        except ImportError:
            print("警告: 未安装bitsandbytes，8-bit优化器将无法使用")
            print("请运行: pip install bitsandbytes")
            print("将回退到标准优化器")
            args.use_8bit_optimizer = False

        if args.use_8bit_optimizer:
            if args.optim == "adamw_torch":
                # 默认使用paged_adamw_8bit，这是最节省显存的8-bit优化器
                sft_cfg_kwargs["optim"] = "paged_adamw_8bit"
            else:
                sft_cfg_kwargs["optim"] = args.optim
            print("使用8-bit优化器以节省显存（可节省约50-75%优化器状态显存）")

    # 只在 max_steps > 0 时添加该参数
    if args.max_steps > 0:
        sft_cfg_kwargs["max_steps"] = args.max_steps

    # 只在 eval_strategy 为 "steps" 时添加 eval_steps
    if args.eval_strategy == "steps":
        sft_cfg_kwargs["eval_steps"] = args.eval_steps

    sft_cfg = SFTConfig(**sft_cfg_kwargs)

    # 为通用文本全量微调创建 data collator：
    # - 基于 `text` 字段做 tokenize / 截断 / padding
    # - 仅对非 padding token 计算 loss（padding 位置 label=-100）
    data_collator = DataCollatorForCausalLM(
        tokenizer=tokenizer,
        max_length=args.max_seq_length,
    )

    # 在创建trainer前同步所有进程
    if torch.distributed.is_initialized():
        print(f"进程 {rank} 准备创建trainer，等待所有进程同步...")
        try:
            torch.distributed.barrier()
            print(f"进程 {rank} 开始创建trainer...")
        except Exception as e:
            print(f"警告: 创建trainer前同步失败: {e}")
            print(f"继续尝试创建trainer...")

    # 创建NaN检测回调
    callbacks = []
    if args.skip_bad_batches or args.max_nan_count > 0:
        nan_callback = NanDetectionCallback(
            skip_bad_batches=args.skip_bad_batches,
            max_nan_count=args.max_nan_count
        )
        callbacks.append(nan_callback)
        print(f"启用NaN检测: skip_bad_batches={args.skip_bad_batches}, max_nan_count={args.max_nan_count}")
    
    # 打印NaN防护措施摘要
    print("\n" + "="*60)
    print("NaN防护措施配置:")
    print(f"  - 梯度裁剪 (max_grad_norm): {args.max_grad_norm if args.max_grad_norm > 0 else '禁用'}")
    print(f"  - 跳过bad batches: {args.skip_bad_batches}")
    print(f"  - 最大连续NaN次数: {args.max_nan_count}")
    print(f"  - 学习率: {args.learning_rate}")
    if args.learning_rate > 1e-4:
        print(f"  警告: 学习率较高 ({args.learning_rate})，如果遇到NaN问题，建议降低到 1e-5 或更低")
    print("="*60 + "\n")

    # 创建训练器
    # SFTTrainer在初始化时可能会进行tokenization，所以需要确保所有进程同步
    trainer = SFTTrainer(
        model=model,
        args=sft_cfg,
        train_dataset=train_ds,
        processing_class=tokenizer,
        data_collator=data_collator,
        callbacks=callbacks if callbacks else None,
    )
    
    # Trainer创建完成后同步（tokenization可能在这里发生）
    if torch.distributed.is_initialized():
        print(f"进程 {rank} trainer创建完成，等待所有进程同步...")
        try:
            torch.distributed.barrier()
            print(f"进程 {rank} 所有进程trainer创建完成...")
        except Exception as e:
            print(f"警告: trainer创建后同步失败: {e}")
            print(f"继续尝试开始训练...")

    # 开始训练前清理显存
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        import gc
        gc.collect()
        print(
            f"训练前显存状态: {torch.cuda.memory_allocated(device) / 1024 ** 3:.2f} GB / {torch.cuda.memory_reserved(device) / 1024 ** 3:.2f} GB")

    # 在开始训练前最后一次同步
    if torch.distributed.is_initialized():
        print(f"进程 {rank} 准备开始训练，等待所有进程同步...")
        try:
            torch.distributed.barrier()
            print(f"进程 {rank} 所有进程准备就绪，开始训练...")
        except Exception as e:
            print(f"警告: 训练前同步失败: {e}")
            print(f"继续尝试开始训练...")

    # 开始训练
    print("开始训练...")
    trainer.train()

    # 保存模型（只在主进程保存）
    if rank == 0:
        print(f"保存模型到: {args.output_dir}")
        trainer.save_model(args.output_dir)
        tokenizer.save_pretrained(args.output_dir)
    else:
        print(f"进程 {rank} 跳过模型保存（由主进程负责）")

    print("训练完成！")


if __name__ == "__main__":
    main()

```

**Comment by guotong1988** [comment]
Are there any workarounds for this issue?
