### ISSUE TITLE
TorchInductor benchmark accuracy check failing for some models in 2.10

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#172015]
When running H100 TorchInductor benchmark with 2.10 RC in https://github.com/pytorch/pytorch/pull/171857, I'm seeing some failures. So, I'm documenting them here to see if they need to be fixed before the final RC. They can all be reproduced on H100 orH200

* [ ] sam (cc @ezyang @gchanan @kadeng @msaroufim @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @muchulee8 @amjames @aakhundov @coconutruben @jataylo @jeanschmidt) (Failing on 2.10 RC, passing on nightly)
```
pip install torch==2.10.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu128
python benchmarks/dynamo/torchbench.py --accuracy --no-translation-validation --inference --bfloat16 --backend inductor --disable-cudagraphs --device cuda --only sam

loading model: 0it [00:06, ?it/s]
cuda eval  sam
E0108 10:28:37.621000 859 torch/_dynamo/utils.py:3124] Accuracy failed: uint8 tensor did not match
E0108 10:28:37.622000 859 torch/_dynamo/utils.py:3087] Accuracy failed for key name masks
fail_accuracy
```

The latest nightly seems ok though
```
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
python benchmarks/dynamo/torchbench.py --accuracy --no-translation-validation --inference --bfloat16 --backend inductor --disable-cudagraphs --device cuda --only sam

loading model: 0it [00:06, ?it/s]
cuda eval  sam
pass
```

[The dashboard](https://hud.pytorch.org/benchmark/v3/dashboard/compiler_inductor?renderGroupId=main&time.start=2025-12-10T00%3A00%3A00.000Z&time.end=2026-01-08T11%3A00%3A00.000Z&filters.repo=pytorch%2Fpytorch&filters.benchmarkName=compiler&filters.mode=inference&filters.dtype=bfloat16&filters.deviceName=cuda+%28h100%29&filters.device=cuda&filters.arch=h100&filters.suite=all&filters.compiler=&filters.model=sam&lbranch=main&rbranch=main&rcommit.commit=d8f8e6aff8c51e18baacb2b9d61be74ab81abca0&rcommit.workflow_id=20287531338&rcommit.date=2025-12-17T08%3A00%3A00Z&rcommit.branch=main&lcommit.commit=9407f0951682dd6817aa37c8fec9e1532c0dd039&lcommit.workflow_id=20252460513&lcommit.date=2025-12-16T07%3A00%3A00Z&lcommit.branch=main&maxSampling=110) showed that this might be fixed between the nightly run from Dec 16th to Dec 17th

* [ ] torch_multimodal_clip, nanogpt, mobilevit_s (same failure) (Failing on 2.10 RC, passing on nightly)
```
pip install torch==2.10.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu128
python benchmarks/dynamo/torchbench.py --performance --cold-start-latency --training --amp --backend inductor --device cuda --only nanogpt

clip_merges.bpe: 532kB [00:00, 20.4MB/s]
loading model: 0it [00:05, ?it/s]/s]
cuda train torch_multimodal_clip
W0108 11:45:15.890000 15958 torch/_logging/_internal.py:1204] [6/0] Profiler function <class 'torch.autograd.profiler.record_function'> will be ignored
ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/shared-personal/huydo/github/pytorch/benchmarks/dynamo/common.py", line 2711, in warmup
    fn(model, example_inputs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 953, in compile_wrapper
    return fn(*args, **kwargs)
  File "/shared-personal/huydo/github/pytorch/benchmarks/dynamo/torchbench.py", line 468, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)
  File "/shared-personal/huydo/github/pytorch/benchmarks/dynamo/torchbench.py", line 469, in torch_dynamo_resume_in_forward_and_backward_pass_at_468
    self.optimizer_zero_grad(mod)
  File "/shared-personal/huydo/github/pytorch/benchmarks/dynamo/torchbench.py", line 475, in torch_dynamo_resume_in_forward_and_backward_pass_at_469
    loss = self.compute_loss(pred)
  File "/shared-personal/huydo/github/pytorch/benchmarks/dynamo/torchbench.py", line 476, in torch_dynamo_resume_in_forward_and_backward_pass_at_475
    self.grad_scaler.scale(loss).backward()
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_tensor.py", line 630, in backward
    torch.autograd.backward(
  File "/home/dev/.local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 364, in backward
    _engine_run_backward(
  File "/home/dev/.local/lib/python3.10/site-packages/torch/autograd/graph.py", line 865, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/dev/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 317, in apply
    return user_fn(self, *args)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2338, in backward
    return impl_fn()
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2324, in impl_fn
    out = CompiledFunction._backward_impl(ctx, all_args)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2494, in _backward_impl
    out = call_func_at_runtime_with_args(
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 134, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1181, in _fn
    return fn(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/output_code.py", line 638, in __call__
    return self.current_callable(inputs)
  File "/tmp/torchinductor_dev/mj/cmj4cn3oekh6i7qclpuhxtuhhmhpdm4tyh54dt4ygcl5vnr3gm5s.py", line 8492, in call
    (buf576, buf577, buf6, buf573, buf585, buf12, buf14, buf596, buf598, buf592, buf606, buf617, buf621, buf623, buf631, buf605, buf22, buf21, buf642, buf644, buf638, buf652, buf663, buf667, buf669, buf677, buf651, buf688, buf690, buf684, buf698, buf709, buf713, buf715, buf723, buf697, buf734, buf736, buf730, buf744, buf755, buf759, buf761, buf769, buf743, buf780, buf782, buf776, buf790, buf801, buf805, buf807, buf815, buf789, buf826, buf828, buf822, buf836, buf847, buf851, buf853, buf861, buf835, buf872, buf874, buf868, buf882, buf893, buf897, buf899, buf907, buf881, buf918, buf920, buf914, buf928, buf939, buf943, buf945, buf953, buf927, buf964, buf966, buf960, buf974, buf985, buf989, buf991, buf999, buf973, buf1010, buf1012, buf1006, buf1020, buf1031, buf1035, buf1037, buf1045, buf1019, buf1056, buf1058, buf1052, buf1066, buf1077, buf1081, buf1083, buf1091, buf1065, buf1102, buf1104, buf1098, buf1112, buf1123, buf1111, buf616, buf662, buf708, buf754, buf800, buf846, buf892, buf938, buf984, buf1030, buf1076, buf1122, buf584, buf591, buf630, buf637, buf676, buf683, buf722, buf729, buf768, buf775, buf814, buf821, buf860, buf867, buf906, buf913, buf952, buf959, buf998, buf1005, buf1044, buf1051, buf1090, buf1097, buf29, buf33, buf35, buf43, buf54, buf58, buf60, buf68, buf42, buf53, buf28, buf67, buf75, buf79, buf81, buf89, buf100, buf104, buf106, buf114, buf88, buf99, buf74, buf113, buf121, buf125, buf127, buf135, buf146, buf150, buf152, buf160, buf134, buf145, buf120, buf159, buf167, buf171, buf173, buf181, buf192, buf196, buf198, buf206, buf180, buf191, buf166, buf205, buf213, buf217, buf219, buf227, buf238, buf242, buf244, buf252, buf226, buf237, buf212, buf251, buf259, buf263, buf265, buf273, buf284, buf288, buf290, buf298, buf272, buf283, buf258, buf297, buf305, buf309, buf311, buf319, buf330, buf334, buf336, buf344, buf318, buf329, buf304, buf343, buf351, buf355, buf357, buf365, buf376, buf380, buf382, buf390, buf364, buf375, buf350, buf389, buf397, buf401, buf403, buf411, buf422, buf426, buf428, buf436, buf410, buf421, buf396, buf435, buf443, buf447, buf449, buf457, buf468, buf472, buf474, buf482, buf456, buf467, buf442, buf481, buf489, buf493, buf495, buf503, buf514, buf518, buf520, buf528, buf502, buf513, buf488, buf527, buf535, buf539, buf541, buf549, buf560, buf564, buf566, buf548, buf559, buf534, buf1128, buf1130, buf1136, buf1138, buf1140, buf1139, buf1144, buf569, buf568) = self.partitions[0](partition0_args)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1843, in run
    return compiled_fn(new_inputs)  # type: ignore[arg-type]
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 388, in deferred_cudagraphify
    return fn(inputs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/utils.py", line 3220, in run
    out = model(new_inputs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 2033, in run
    out = self._run(new_inputs, function_id)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 2203, in _run
    return self.record_function(new_inputs, function_id)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 2259, in record_function
    torch.cuda.synchronize()
  File "/home/dev/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 1108, in synchronize
    return torch._C._cuda_synchronize()
torch.AcceleratorError: CUDA error: an illegal memory access was encountered
Search for `cudaErrorIllegalAddress' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

warmup_failed
```

Nightly is ok here too:
```
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
python benchmarks/dynamo/torchbench.py --performance --cold-start-latency --training --amp --backend inductor --device cuda --only nanogpt
```

* [ ] torchrec_dlrm (failing on both 2.10 RC and nightly, [the dashboard](https://hud.pytorch.org/benchmark/v3/dashboard/compiler_inductor?renderGroupId=main&time.start=2025-12-10T00%3A00%3A00.000Z&time.end=2026-01-08T11%3A00%3A00.000Z&filters.repo=pytorch%2Fpytorch&filters.benchmarkName=compiler&filters.mode=training&filters.dtype=amp&filters.deviceName=cuda+%28h100%29&filters.device=cuda&filters.arch=h100&filters.suite=all&filters.compiler=&filters.model=torchrec_dlrm&lbranch=main&rbranch=main&rcommit.commit=1daa7257b0d761144bf1fe5c64df900a7eaaba2c&rcommit.workflow_id=20183921790&rcommit.date=2025-12-13T06%3A00%3A00Z&rcommit.branch=main&lcommit.commit=8b21f924c3c24d4cbe239265c87aeb7b271fe974&lcommit.workflow_id=20152216717&lcommit.date=2025-12-12T04%3A00%3A00Z&lcommit.branch=main&maxSampling=110) shows the regression happened between nightly Dec 12th and Dec 13th run)

```
pip install torch==2.10.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu128
pip install git+https://github.com/pytorch/FBGEMM.git@de731af65b4f04696e85c729e3282450b51b95fd#subdirectory=fbgemm_gpu --no-build-isolation
pip install git+https://github.com/pytorch/torchrec.git@6cd9fd362514d14ebb9ed51314c62ac1e1e2bbf2 --no-build-isolation

python benchmarks/dynamo/torchbench.py --accuracy --no-translation-validation --training --amp --backend inductor --disable-cudagraphs --device cuda --only torchrec_dlrm

loading model: 0it [00:00, ?it/s][rank0]:W0108 11:21:01.992000 13642 torch/fx/_symbolic_trace.py:53] is_fx_tracing will return true for both fx.symbolic_trace and torch.export. Please use is_fx_tracing_symbolic_tracing() for specifically fx.symbolic_trace or torch.compiler.is_compiling() for specifically torch.export/compile.
loading model: 0it [00:01, ?it/s]
cuda train torchrec_dlrm
[rank0]:W0108 11:21:10.898000 13642 torch/_logging/_internal.py:1204] [6/0] Profiler function <class 'torch.autograd.profiler.record_function'> will be ignored
[rank0]:E0108 11:21:18.362000 13642 torch/_dynamo/utils.py:3226] RMSE (res-fp64): 0.00093, (ref-fp64): 0.00004 and shape=torch.Size([256]). res.dtype: torch.float32, multiplier: 3.000000, tol: 0.001000, use_larger_multiplier_for_smaller_tensor: 0
[rank0]:E0108 11:21:18.363000 13642 torch/_dynamo/utils.py:3087] Accuracy failed for key name model.over_arch.model.0._mlp.2._linear.bias
fail_accuracy
[rank0]:[W108 11:21:19.281845184 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
```

* [ ] modded_nanogpt (failing on both 2.10 RC and nightly, [the dashboard](https://hud.pytorch.org/benchmark/v3/dashboard/compiler_inductor?renderGroupId=main&time.start=2025-12-10T00%3A00%3A00.000Z&time.end=2026-01-08T11%3A00%3A00.000Z&filters.repo=pytorch%2Fpytorch&filters.benchmarkName=compiler&filters.mode=training&filters.dtype=amp&filters.deviceName=cuda+%28h100%29&filters.device=cuda&filters.arch=h100&filters.suite=all&filters.compiler=&filters.model=modded_nanogpt&lbranch=main&rbranch=main&rcommit.commit=f65bb97673dfa24cc5270f3bb74cca892736de2b&rcommit.workflow_id=20609168520&rcommit.date=2025-12-31T02%3A00%3A00Z&rcommit.branch=main&lcommit.commit=712b350f5b91ee10254289562183eb8a6ec80672&lcommit.workflow_id=20585973619&lcommit.date=2025-12-30T03%3A00%3A00Z&lcommit.branch=main&maxSampling=110) shows a regression between Dec 30th and Dec 31st run)
```
pip install torch==2.10.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu128
python benchmarks/dynamo/torchbench.py --accuracy --no-translation-validation --training --amp --backend inductor --disable-cudagraphs --device cuda --only modded_nanogpt

loading model: 0it [00:06, ?it/s]
cuda train modded_nanogpt
WARNING:common:fp64 golden ref were not generated for modded_nanogpt. Setting accuracy check to cosine
Traceback (most recent call last):
  File "/shared-personal/huydo/github/pytorch/benchmarks/dynamo/common.py", line 2206, in check_accuracy
    fp64_outputs = self.run_n_iterations(
  File "/shared-personal/huydo/github/pytorch/benchmarks/dynamo/common.py", line 2043, in run_n_iterations
    model_iter_fn(mod, inputs, collect_outputs=False)
  File "/shared-personal/huydo/github/pytorch/benchmarks/dynamo/torchbench.py", line 474, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1787, in _call_impl
    return forward_call(*args, **kwargs)
  File "/torchbench/torchbenchmark/models/modded_nanogpt/__init__.py", line 25, in forward
    return self.model(input_seq, self.target_seq, self.sliding_window_num_blocks)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1787, in _call_impl
    return forward_call(*args, **kwargs)
  File "/torchbench/torchbenchmark/models/modded_nanogpt/model.py", line 929, in forward
    logits = self.lm_head(x).float()
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1787, in _call_impl
    return forward_call(*args, **kwargs)
  File "/torchbench/torchbenchmark/models/modded_nanogpt/model.py", line 613, in forward
    out: Tensor = torch.ops.nanogpt.mm(
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_ops.py", line 1209, in __call__
    return self._op(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_library/autograd.py", line 110, in autograd_impl
    result = Generated.apply(*args, Metadata(keyset, keyword_only_args))  # type: ignore[attr-defined]
  File "/home/dev/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 583, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_library/autograd.py", line 51, in forward
    result = op.redispatch(keyset & _C._after_autograd_keyset, *args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_ops.py", line 826, in redispatch
    return self._handle.redispatch_boxed(keyset, *args, **kwargs)  # type: ignore[return-value]
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_library/custom_ops.py", line 347, in backend_impl
    result = self._backend_fns[device_type](*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_compile.py", line 54, in inner
    return disable_fn(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1181, in _fn
    return fn(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_library/custom_ops.py", line 382, in wrapped_fn
    return fn(*args, **kwargs)
  File "/torchbench/torchbenchmark/models/modded_nanogpt/model.py", line 60, in mm_op
    return impl(x, w)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 967, in compile_wrapper
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1019, in _compile_fx_inner
    raise InductorError(e, currentframe()).with_traceback(
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1003, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1766, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1537, in codegen_and_compile
    compiled_module = graph.compile_to_module()
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/graph.py", line 2416, in compile_to_module
    return self._compile_to_module()
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/graph.py", line 2426, in _compile_to_module
    mod = self._compile_to_module_lines(wrapper_code)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/graph.py", line 2501, in _compile_to_module_lines
    mod = PyCodeCache.load_by_key_path(
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 3674, in load_by_key_path
    mod = _reload_python_module(key, path, set_sys_modules=in_toplevel)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/runtime/compile_tasks.py", line 35, in _reload_python_module
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_dev/6v/c6v65m4wxpaba4tzfmwsyz4jersywz7ejvmqgyziv7qqfsbdgwxv.py", line 187, in <module>
    async_compile.wait(globals())
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/async_compile.py", line 649, in wait
    self._wait_futures(scope)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/async_compile.py", line 669, in _wait_futures
    kernel = result.result()
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 4417, in result
    return self.result_fn()
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/async_compile.py", line 438, in get_result
    raise e.with_name(kernel_name) from e
torch._inductor.exc.InductorError: SubprocException: An exception occurred in a subprocess:

Name=triton_poi_fused__to_copy_div_0
Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/compile_worker/subproc_pool.py", line 457, in do_job
    result = job()
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/runtime/compile_tasks.py", line 68, in _worker_compile_triton
    kernel.precompile(warm_cache_only=True)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 432, in precompile
    self._precompile_worker()
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 463, in _precompile_worker
    compile_results.append(self._precompile_config(c))
  File "/home/dev/.local/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 808, in _precompile_config
    binary = triton.compile(*compile_args, **compile_kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/triton/compiler/compiler.py", line 324, in compile
    next_module = compile_ir(module, metadata)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/triton/backends/nvidia/compiler.py", line 544, in <lambda>
    stages["llir"] = lambda src, metadata: self.make_llir(src, metadata, options, capability)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/triton/backends/nvidia/compiler.py", line 378, in make_llir
    pm.run(mod, 'make_llir')
RuntimeError: PassManager::run failed


Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

W0108 11:37:55.947000 15449 torch/_logging/_internal.py:1204] [8/0] Profiler function <class 'torch.autograd.profiler.record_function'> will be ignored
W0108 11:38:04.237000 15449 torch/_dynamo/utils.py:3136] Similarity score=0.9161608219146729
E0108 11:38:04.238000 15449 torch/_dynamo/utils.py:3087] Accuracy failed for key name model.blocks.0.attn.qkvo_w.grad
fail_accuracy
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @kadeng @muchulee8 @amjames @chauhang @aakhundov @coconutruben @jataylo

**Comment by huydhn** [comment]
cc @eellison

**Comment by huydhn** [comment]
@atalman @eqy For the illegal memory access error, this is fixed by building PyTorch from main to include https://github.com/pytorch/pytorch/pull/171627. So, the failure is the same as https://github.com/pytorch/pytorch/issues/169849. Are we sure that we have cherry pick all the change we need there into 2.10?

```
pip install torch==2.10.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu128
python benchmarks/dynamo/torchbench.py --performance --cold-start-latency --training --amp --backend inductor --device cuda --only nanogpt
```

**Comment by huydhn** [comment]
Also, for sam's fail_accuracy, I can confirm now that it's flaky, and also not a real regression. We can cherry pick @jeanschmidt https://github.com/pytorch/pytorch/pull/171927#issuecomment-3728484653 to get release CI to green.  Thank you Jean for the timing fix!

**Comment by jeanschmidt** [comment]
thanks for the headsup, I'll try to reproduce this locally and find a more suitable threshold for sam, 

Maybe, in this case, let me revert the [PR](https://github.com/pytorch/pytorch/pull/171927) as it should return the model accuracy to be disabled and improve on it.

**Comment by atalman** [comment]
Confirm issue 1 is resolved:
```
python benchmarks/dynamo/torchbench.py --performance --cold-start-latency --training --amp --backend inductor --device cuda --only nanogpt
loading model: 0it [00:00, ?it/s]number of parameters: 123.69M
num decayed parameter tensors: 50, with 124,354,560 parameters
num non-decayed parameter tensors: 98, with 121,344 parameters
using fused AdamW: True
loading model: 0it [00:02, ?it/s]
cuda train nanogpt                            
W0109 18:58:41.166000 191 torch/_logging/_internal.py:1204] [6/0] Profiler function <class 'torch.autograd.profiler.record_function'> will be ignored
running benchmark: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 30.57it/s]
6.510x
```
