### ISSUE TITLE
ProcessGroupNCCL.cpp:260, unhandled cuda error

### ISSUE THREAD

**Issue by anotherTK** [pytorch/pytorch#17349]
## 🐛 Bug

two nodes distributed training failed!

## To Reproduce

1. The code using from https://github.com/pytorch/examples/tree/master/imagenet
2. running command with nodes 1: `python main.py -a resnet50 --lr 0.01 --dist-url 'tcp://master_ip:12345' --dist-backend 'nccl' --multiprocessing-distributed --world-size 2 --rank 0 data_path`
3. running command with nodes 2: `python main.py -a resnet50 --lr 0.01 --dist-url 'tcp://master_ip:12345' --dist-backend 'nccl' --multiprocessing-distributed --world-size 2 --rank 1 data_path`

## Expected behavior

```
Use GPU: 2 for training
Use GPU: 3 for training
Use GPU: 7 for training
Use GPU: 4 for training
Use GPU: 1 for training
Use GPU: 5 for training
Use GPU: 0 for training
=> creating model 'resnet50'
Use GPU: 6 for training
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
Traceback (most recent call last):
  File "main.py", line 399, in <module>
    main()
  File "main.py", line 110, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/search/speech/tk/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/search/speech/tk/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/search/speech/tk/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/search/odin/tk/projects/delete/main.py", line 152, in main_worker
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
  File "/search/speech/tk/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 215, in __init__
    self.broadcast_bucket_size)
  File "/search/speech/tk/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 377, in _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:260, unhandled cuda error
```

## Environment

 - PyTorch Version (e.g., 1.0):  1.0.0
 - OS (e.g., Linux):  Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
 - Python version: 3.6.5
 - CUDA/cuDNN version: 10.0

**Comment by tkianai** [comment]
Any ideas? Thanks!

**Comment by qaohv** [comment]
@tkianai , which NCCL version do you use? I have similar problem with NCCL 2.4.2.

**Comment by tkianai** [comment]
@qaohv The same as you, 2.4.2! Besides, pytorch 1.0.0 with cuda9.0 or cuda9.2 has the same error!

**Comment by qaohv** [comment]
@tkianai , How did you add nccl 2.4.2 :  your copied libnccl files to /usr/local/cuda/lib folder or rebuilded pytorch from source with NCCL 2.4.2 ?

**Comment by tkianai** [comment]
Following the installation guides from here: https://developer.nvidia.com/nccl/nccl-download. In addition, distributed training with single node, multi-gpus works fine.

**Comment by ltnghia** [comment]
I also have the same error: two nodes, node 1 has 2 GPU 1080ti, node 1 has 1 GPU 1080ti.
I installed pytorch 1.0.1 - CUDA 9.0 by anaconda. 

`python main.py --dist-url 'tcp://136.187.81.108:1234' --dist-backend 'nccl' --multiprocessing-distributed --world-size 2 --rank 0 ImageNet/tiny-imagenet-200`

`python main.py --dist-url 'tcp://136.187.81.108:1234' --dist-backend 'nccl' --multiprocessing-distributed --world-size 2 --rank 1 ImageNet/tiny-imagenet-200`

**Comment by zhch-sun** [comment]
I met the same problem. waiting for solutions/

**Comment by qaohv** [comment]
I overcame similar problem and ran distributed script on pytorch 1.0.0 and NCCL 2.4.2. I used pytorch script for distributed learning as example from https://pytorch.org/tutorials/beginner/aws_distributed_training_tutorial.html and faced similar problem. For running I used https://pytorch.org/docs/stable/distributed.html#launch-utility.

This steps helped me overcome problem:
1. I installed NCCL 2.4.2 to system using [manual](https://developer.nvidia.com/nccl/nccl-download), but after this Pytorch still used NCCL 2.3.7.  I'm checking which NCCL version used by pytorch using command:
```
import torch
torch._C._nccl_version()
```
I downloaded Pytorch from repository and build package with flags that use installed in system version of NCCL for building. New pytorch package already use NCCL 2.4.2.

2. In base tutorial script I commeted rows:
```
#if name == '__main__':
#    torch.multiprocessing.set_start_method('spawn')
```
and used https://pytorch.org/docs/stable/distributed.html#launch-utility for run distributed learning.

After this step all works fine for me on 1 and N multi-GPU nodes, I tested it on p3.* instances in AWS.
Hope it's helpful.

**Comment by Lausannen** [comment]
@qaohv  Thank you for your suggestion! I use "torch._C._nccl_version()" to check the nccl_version which fit my torch is 2307 . So I installed NCCL 2.3.7 under official guide. But I still met bug info just like @ltnghia . I wonder if you can give me some suggestions. Thank you very much !

**Comment by BobLiu20** [comment]
also hit this error

**Comment by BobLiu20** [comment]
Fixed it after upgrade nccl to 2.4.2! Thanks @qaohv

**Comment by one86951** [comment]
could you give me more details about “upgrade nccl to 2.4.2”？Thanks @qaohv

**Comment by ezyang** [comment]
I'm going to close this issue as "please upgrade your NCCL" version. If you need help doing this, ask in the forums.

**Comment by bearcatt** [comment]
I hit this error in multi-node situation. After setting NCCL_SOCKET_IFNAME as recommended in [](https://pytorch.org/docs/stable/distributed.html#choosing-the-network-interface-to-use) the error got fixed. Also, it seems that we should first launch the program in the master node, wait for a few seconds, and then launch the program in other nodes. If I don't do this way I still meet the error.

**Comment by bearcatt** [comment]
I hit this error in multi-node situation. After setting NCCL_SOCKET_IFNAME as recommended in [here](https://pytorch.org/docs/stable/distributed.html#choosing-the-network-interface-to-use) the error got fixed. Also, it seems that we should first launch the program in the master node, wait for a few seconds, and then launch the program in other nodes. If I don't do this way I still meet the error.

**Comment by raxxerwan** [comment]
I've met a similar issue on my machine with pytorch 1.1, CUDA 10.0 and NCCL 2.4.2. The only difference is that my error message is "RuntimeError: ...... ProcessGroupNCCL.cpp:272, unhandled system error". I finally solved it with setting NCCL_SOCKET_IFNAME=ib0 and NCCL_IB_DISABLE=1. 

Hope it will help!

**Comment by ElegantLin** [comment]
@raxxerwan Thanks for your answer. I also met the problem. Do you know the reason?

Thanks a lot.

**Comment by raxxerwan** [comment]
> I had the same issue. Wonder what causes this issue (do you have to set variable names explicitly somewhere - while installing maybe)? I worked with 2 clusters. The first one worked without throwing any issue. The second one caused issues. @raxxerwan 's solution worked for me.
> 
> Thanks!

Just set NCCL_SOCKET_IFNAME=ib0 and NCCL_IB_DISABLE=1 before your python script is OK.
For example, if yr script is run.py, please use
```
$ export NCCL_SOCKET_IFNAME=ib0
$ export NCCL_IB_DISABLE=1
$ python run.py
```
instead of using 
```
$ python run.py
```
alone.

Plus, in my case, I use NCCL_SOCKET_IFNAME=ib0 because my ip interface is ib0. To find out your own ip interface, you can use
```
$ ifconfig
```
or 
```
$ ip addr
```
In most cases, it would be eth0 or ib0.

**Comment by raxxerwan** [comment]
> @raxxerwan Thanks for your answer. I also met the problem. Do you know the reason?
> 
> Thanks a lot.

I actually don't know the details, but it's probably a bug only with pytorch 1.1 and NCCL 2.4.2. I didn't dig in much because NCCL is written in C, so it's nearly a black box to me. Sorry about that.

**Comment by ElegantLin** [comment]
It's OK. I am sorry that I forgot to give a response. I upgraded to the latest Pytorch and I solved the problem. Thanks a lot.

**Comment by gemfield** [comment]
Below ENVs are always helpful in this situation:
```bash
export NCCL_SOCKET_IFNAME=eth0
export NCCL_IB_DISABLE=1
export NCCL_DEBUG=INFO
export NCCL_DEBUG_SUBSYS=ALL
```
