### ISSUE TITLE
cuDNN error: CUDNN_STATUS_EXECUTION_FAILED when calling .cuda() on RNN layer

### ISSUE THREAD

**Issue by tohinz** [pytorch/pytorch#17543]
## 🐛 Bug

I get "RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED" when trying to move a RNN layer to the GPU by calling ".cuda()".

## To Reproduce

Code:
```
import torch
rnn = torch.nn.LSTM(10,10)  # same error with e.g. torch.nn.GRU(10,10,1)
rnn.cuda()
```

Gives me the error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/data/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in cuda
>     return self._apply(lambda t: t.cuda(device))
>   File "/data/pytorch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
>     self.flatten_parameters()
>   File "/data/pytorch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
>     self.batch_first, bool(self.bidirectional))
> RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

If I call
`rnn.cuda()`
a second time (without restarting the python kernel) it works without any errors:
`LSTM(10, 10)`
But it always fails with the above stack trace when I try it the first time.

The same code works fine with other layers, e.g.
`linear = torch.nn.linear(10,10)`
or
`cnn = torch.nn.Conv1d(10,10,3)`.

The RNNCells also work, but for GRU and LSTM I get the above error.

At the moment I solve the issue by catching the error and calling ".cuda()" a second time:
```
import torch
rnn = torch.nn.LSTM(10,10)
try:
    rnn.cuda()
except:
    rnn.cuda()
```

## Environment
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 410.79
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip3] numpy==1.16.1
[pip3] torch==1.0.1.post2
[pip3] torchvision==0.2.1
[conda] Could not collect

## Additional context
I also tried it with PyTorch 0.4.1 (otherwise same environment), which produced the following stack trace:
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/data/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in cuda
>     return self._apply(lambda t: t.cuda(device))
>   File "/data/pytorch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 112, in _apply
>     self.flatten_parameters()
>   File "/data/pytorch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 105, in flatten_parameters
>     self.batch_first, bool(self.bidirectional))
> RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS

**Comment by soumith** [comment]
CUDA 9 and RTX 2080 Ti simply aren't compatible and dont play well togethere.
An older CuDNN version working is likely a side-effect rather than expectation.
Use CUDA10 and CUDA10 versions of CuDNN etc. for RTX 2080 which is Turing architecture

**Comment by tohinz** [comment]
Thanks, building and using PyTorch with Cuda 10 solved the issue.

**Comment by boru-roylu** [comment]
I have the same problem. My python version: 3.7.2, PyTorch version: 1.0.1.post2, and CUDA is 10.0.130.

**Comment by longxianlei** [comment]
I solved this problem by this method. Thank u!

**Comment by ilyak93** [comment]
@soumith, is there anywhere torch versions 0.3.0 or 0.3.1 for cuda 10 for the RTX 2080 Ti ?
