### ISSUE TITLE
Integers to negative integer powers are handled incorrectly (both CPU and CUDA)

### ISSUE THREAD

**Issue by wranai** [pytorch/pytorch#17751]
```python
    Python 3.6.7 |Anaconda custom (64-bit)| (default, Oct 23 2018, 19:16:44) 
    [GCC 7.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import torch
    >>> torch.__version__
    '1.0.0.dev20190114'
    >>>
```

NumPy handles it nicely:

```python
    >>> 2 ** torch.tensor(-1).numpy()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ValueError: Integers to negative integer powers are not allowed.
    >>>
```

PyTorch on CUDA freaks out irrecoverably:

```python
    >>> 2 ** torch.tensor(-1, device='cuda')
    /opt/conda/conda-bld/pytorch-nightly_1547458468907/work/aten/src/THC/THCNumerics.cuh:27: T powi(T, T) [with T = long]: block: [0,0,0], thread: [0,0,0] Assertion `THCNumerics<T>::ge(b, 0)` failed.
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File ".../anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 66, in __repr__
        return torch._tensor_str._str(self)
      File ".../anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 277, in _str
        tensor_str = _tensor_str(self, indent)
      File ".../anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 195, in _tensor_str
        formatter = _Formatter(get_summarized_data(self) if summarize else self)
      File ".../anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 80, in __init__
        value_str = '{}'.format(value)
      File ".../anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 380, in __format__
        return self.item().__format__(format_spec)
    RuntimeError: CUDA error: device-side assert triggered
    >>>2 ** torch.tensor(2, device='cuda')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    RuntimeError: CUDA error: device-side assert triggered
```

PyTorch on CPU crashes with a C++ runtime error:

```python
    >>> 2 ** torch.tensor(-1)
    terminate called after throwing an instance of 'std::runtime_error'
      what():  invalid argument 1: Integers to negative integer powers are not allowed at /opt/conda/conda-bld/pytorch-nightly_1547458468907/work/aten/src/TH/generic/THTensorApply.hpp:167
    Aborted
    $
```

**Comment by bhushan23** [comment]
We need to catch the exception and raise Runtime error

**Comment by bhushan23** [comment]
this is weird ,`THPVariable_pow` does have try - catch

pasting backtrace for reference

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51                                                   
#1  0x00007ffff7805801 in __GI_abort () at abort.c:79  
#2  0x00007fffe7f3d3df in __gnu_cxx::__verbose_terminate_handler ()
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007fffe7f3bb16 in __cxxabiv1::__terminate (handler=<optimized out>)
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007fffe7f3af91 in __cxa_call_terminate (ue_header=ue_header@entry=0x555555906710)                                                               
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_call.cc:54                                                           #5  0x00007fffe7f3b79d in __cxxabiv1::__gxx_personality_v0 (version=<optimized out>, actions=6, exception_class=5138137972254386944, ue_header=0x555555906710, context=0x7fffffffc740)
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_personality.cc:676
#6  0x00007ffff5604f56 in _Unwind_RaiseException_Phase2 (exc=exc@entry=0x555555906710, context=context@entry=0x7fffffffc740, frames_p=frames_p@entry=0x7fffffffc830)
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libgcc/unwind.inc:64                     
#7  0x00007ffff5605244 in _Unwind_RaiseException (exc=exc@entry=0x555555906710)                                                                          
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libgcc/unwind.inc:136                                                                     
#8  0x00007fffe7f3bd1b in __cxxabiv1::__cxa_throw (obj=0x555555906730, tinfo=0x7fffe88206d8 <typeinfo for c10::Error>, dest=0x7fffe5003f40 <c10::Error::~Error()>)                      
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:90                                                 
#9  0x00007fffe561a6cb in THLongTensor_cpow._omp_fn.382 () from /home/bhushan/miniconda3/envs/pytorch-dev3/lib/python3.7/site-packages/torch/lib/libcaffe2.so                                               #10 0x00007ffff56ae038 in __kmp_api_GOMP_parallel_40_alias () from /home/bhushan/miniconda3/envs/pytorch-dev3/lib/python3.7/site-packages/numpy/../../../libiomp5.so
#11 0x00007fffe5750a91 in THLongTensor_cpow () from /home/bhushan/miniconda3/envs/pytorch-dev3/lib/python3.7/site-packages/torch/lib/libcaffe2.so              
#12 0x00007fffe5407d3b in at::CPULongType::s__th_pow(at::Tensor const&, at::Tensor const&) const () from /home/bhushan/miniconda3/envs/pytorch-dev3/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#13 0x00007fffe552aee0 in at::TypeDefault::_th_pow(at::Tensor const&, at::Tensor const&) const () from /home/bhushan/miniconda3/envs/pytorch-dev3/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#14 0x00007fffe5166e21 in at::native::pow(at::Tensor const&, at::Tensor const&) () from /home/bhushan/miniconda3/envs/pytorch-dev3/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#15 0x00007fffe551a5f9 in at::TypeDefault::pow(at::Tensor const&, at::Tensor const&) const () from /home/bhushan/miniconda3/envs/pytorch-dev3/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#16 0x00007fffe3cd28ac in torch::autograd::VariableType::pow(at::Tensor const&, at::Tensor const&) const ()
   from /home/bhushan/miniconda3/envs/pytorch-dev3/lib/python3.7/site-packages/torch/lib/libtorch.so.1
#17 0x00007fffe828e324 in torch::autograd::THPVariable_pow () from /home/bhushan/miniconda3/envs/pytorch-dev3/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#18 0x000055555568fd27 in _PyMethodDef_RawFastCallDict () at /tmp/build/80754af9/python_1546061345851/work/Objects/call.c:515
#19 0x000055555568fe71 in _PyCFunction_FastCallDict (func=0x7fffe16e6480, args=<optimized out>, nargs=<optimized out>, kwargs=<optimized out>)
    at /tmp/build/80754af9/python_1546061345851/work/Objects/call.c:582
#20 0x00005555556b4442 in call_unbound (nargs=<optimized out>, args=<optimized out>, self=<optimized out>, func=<optimized out>, unbound=<optimized out>)
    at /tmp/build/80754af9/python_1546061345851/work/Objects/typeobject.c:1484
#21 call_maybe.constprop () at /tmp/build/80754af9/python_1546061345851/work/Objects/typeobject.c:1534
#22 0x00005555557597c2 in slot_nb_power_binary (other=0x7ffff7e3f318, self=0x7ffff7e3f360) at /tmp/build/80754af9/python_1546061345851/work/Objects/typeobject.c:6176
#23 slot_nb_power () at /tmp/build/80754af9/python_1546061345851/work/Objects/typeobject.c:6185
#24 0x000055555567b8bd in ternary_op.isra.2 (op_slot=40, z=0x55555589f0f0 <_Py_NoneStruct>, w=0x7ffff7e3f318, v=0x7ffff7e3f360) at /tmp/build/80754af9/python_1546061345851/work/Objects/abstract.c:895
#25 PyNumber_Power () at /tmp/build/80754af9/python_1546061345851/work/Objects/abstract.c:1028
#26 0x0000555555725d5c in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546061345851/work/Python/ceval.c:1195
#27 0x000055555566a0eb in function_code_fastcall (globals=<optimized out>, nargs=2, args=<optimized out>, co=<optimized out>) at /tmp/build/80754af9/python_1546061345851/work/Objects/call.c:283
#28 _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1546061345851/work/Objects/call.c:322
#29 0x00005555556813d4 in _PyObject_FastCall_Prepend () at /tmp/build/80754af9/python_1546061345851/work/Objects/call.c:866
#30 0x00005555556b43fc in call_unbound (nargs=1, args=0x7fffffffd710, self=0x7ffff7e3f318, func=0x7fffe1b5e598, unbound=1) at /tmp/build/80754af9/python_1546061345851/work/Objects/typeobject.c:1481
#31 call_maybe.constprop () at /tmp/build/80754af9/python_1546061345851/work/Objects/typeobject.c:1534
#32 0x00005555555f52c0 in slot_nb_power_binary (other=0x7ffff7e3f318, self=0x7ffff7fd30c0) at /tmp/build/80754af9/python_1546061345851/work/Objects/typeobject.c:6176
#33 slot_nb_power (self=0x7ffff7fd30c0, other=0x7ffff7e3f318, modulus=<optimized out>) at /tmp/build/80754af9/python_1546061345851/work/Objects/typeobject.c:6185
#34 0x000055555567b98a in ternary_op.isra.2 (op_slot=40, z=0x55555589f0f0 <_Py_NoneStruct>, w=0x7ffff7e3f318, v=0x7ffff7fd30c0) at /tmp/build/80754af9/python_1546061345851/work/Objects/abstract.c:901
#35 PyNumber_Power () at /tmp/build/80754af9/python_1546061345851/work/Objects/abstract.c:1028
#36 0x0000555555725d5c in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546061345851/work/Python/ceval.c:1195
#37 0x00005555556690d9 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1546061345851/work/Python/ceval.c:3930
#38 0x0000555555669fa4 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1546061345851/work/Python/ceval.c:3959
#39 0x0000555555669fcc in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at /tmp/build/80754af9/python_1546061345851/work/Python/ceval.c:524
#40 0x0000555555783664 in run_mod () at /tmp/build/80754af9/python_1546061345851/work/Python/pythonrun.c:1035
#41 0x000055555578d881 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1546061345851/work/Python/pythonrun.c:988
#42 0x000055555578da73 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1546061345851/work/Python/pythonrun.c:429
```

**Comment by bhushan23** [comment]
for CPU,
Issue is due to OMP Parallel
https://github.com/pytorch/pytorch/blob/a5e7b1d03268cc2afbce4109206dcf6a57b0f4fd/aten/src/TH/generic/THTensorMath.cpp#L271
Disabling OMP Parallel fixes the unhandleded exception

Haven't looked into cuda issue yet.

**Comment by bhushan23** [comment]
This is a wider issue affecting all the tensor operations with OpenMP

**Comment by ezyang** [comment]
@bhushan23, thank you for your sleuthing. The CPU side version of this problem is easy, and we should fix it using an error flag. There are plenty of existing examples of this in the code.

CUDA side is harder; I'm not sure there is much we can do about it.

**Comment by skrah** [comment]
The CPU issue is fixed in `master` probably by `at::parallel_for()`:

```
>>> 2 ** torch.tensor(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stefan/nomalloc/lib/python3.7/site-packages/torch/tensor.py", line 404, in __rpow__
    return self.new_tensor(other) ** self
RuntimeError: invalid argument 1: Integers to negative integer powers are not allowed at /home/stefan/pytorch/aten/src/TH/generic/THTensorMath.cpp:262
```

**Comment by skrah** [comment]
> CUDA side is harder; I'm not sure there is much we can do about it.

Yes, the underlying problem is similar to the `IndexError` attempt in #16960.  It is hard to report errors from CUDA without affecting performance.

**Comment by ezyang** [comment]
Yeah, let's go ahead and close this in favor of #16960
