### ISSUE TITLE
`torch.nn.LSTM.forward` produces incorrect outputs (or crashes) on ROCm

### ISSUE THREAD

**Issue by mferencevic** [pytorch/pytorch#177834]
### 🐛 Describe the bug

We observed that the the outputs of `torch.nn.LSTM.forward`, when running on a ROCm GPU, differ significantly from their CPU counterpart.
This only happens for larger batch sizes (>100), and the differences become larger as the batch size is further increased.
These differences are extremely large (sometimes up to 1-3 orders of magnitude) and can't be attributed to the usual numerical inaccuracies.
Furthermore, for a large enough batch size (500-1000), the call raises an error:
```
username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0

Traceback (most recent call last):
  File "issue.py", line 73, in <module>
    main()
  File ".venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "issue.py", line 64, in main
    raise e
  File "issue.py", line 61, in main
    ywrong = run(x, dtype, "cuda:0")
             ^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "issue.py", line 40, in run
    y, _ = lstm(x)
           ^^^^^^^
  File ".venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1787, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/torch/nn/modules/rnn.py", line 1141, in forward
    result = _VF.lstm(
             ^^^^^^^^^
RuntimeError: miopenStatusBadParm
```
We also noticed that the numerical differences decrease when the LSTM's hidden size is lower. 
None of these effects are present on CUDA.

Here are some results when running on ROCm:
```
Bidirectional LSTM definition: input_size=60, hidden_size=128, num_layers=4
dtype: torch.float16
    batch_size= 10, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size= 50, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=100, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=110, relative difference vs CPU: mean=0.0140, std=0.1141
    batch_size=120, relative difference vs CPU: mean=0.1747, std=0.4716
    batch_size=130, relative difference vs CPU: mean=0.3114, std=0.6005
    batch_size=200, relative difference vs CPU: mean=0.8847, std=0.7305
    batch_size=250, relative difference vs CPU: mean=0.9642, std=0.7083
    batch_size=300, relative difference vs CPU: mean=0.9611, std=0.7061
    batch_size=400, relative difference vs CPU: mean=0.9616, std=0.7078
    batch_size=500, relative difference vs CPU: mean=0.9576, std=0.7063
MIOpen Error: username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0
    batch_size=1000 FORWARD ON GPU FAILED: miopenStatusBadParm
dtype: torch.float32
    batch_size= 10, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size= 50, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=100, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=110, relative difference vs CPU: mean=0.0134, std=0.1142
    batch_size=120, relative difference vs CPU: mean=0.1742, std=0.4718
    batch_size=130, relative difference vs CPU: mean=0.3110, std=0.6008
    batch_size=200, relative difference vs CPU: mean=0.8847, std=0.7305
    batch_size=250, relative difference vs CPU: mean=1.0828, std=0.8637
    batch_size=300, relative difference vs CPU: mean=1.2134, std=0.9995
    batch_size=400, relative difference vs CPU: mean=1.3588, std=1.2611
    batch_size=500, relative difference vs CPU: mean=1.5400, std=1.4649
MIOpen Error: username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0
    batch_size=1000 FORWARD ON GPU FAILED: miopenStatusBadParm


# Larger `hidden_size` reduces numerical errors.
Bidirectional LSTM definition: input_size=60, hidden_size=256, num_layers=4
dtype: torch.float16
    batch_size= 10, relative difference vs CPU: mean=0.0007, std=0.0007
    batch_size= 50, relative difference vs CPU: mean=0.0007, std=0.0007
    batch_size=100, relative difference vs CPU: mean=0.0007, std=0.0007
    batch_size=110, relative difference vs CPU: mean=0.0007, std=0.0007
    batch_size=120, relative difference vs CPU: mean=0.0007, std=0.0007
    batch_size=130, relative difference vs CPU: mean=0.0007, std=0.0007
    batch_size=200, relative difference vs CPU: mean=0.0007, std=0.0007
    batch_size=250, relative difference vs CPU: mean=0.0007, std=0.0007
MIOpen Error: username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0
    batch_size=300 FORWARD ON GPU FAILED: miopenStatusBadParm
MIOpen Error: username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0
    batch_size=400 FORWARD ON GPU FAILED: miopenStatusBadParm
MIOpen Error: username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0
    batch_size=500 FORWARD ON GPU FAILED: miopenStatusBadParm
MIOpen Error: username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0
    batch_size=1000 FORWARD ON GPU FAILED: miopenStatusBadParm
dtype: torch.float32
    batch_size= 10, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size= 50, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=100, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=110, relative difference vs CPU: mean=0.0136, std=0.1175
    batch_size=120, relative difference vs CPU: mean=0.1762, std=0.4779
    batch_size=130, relative difference vs CPU: mean=0.3145, std=0.6083
    batch_size=200, relative difference vs CPU: mean=0.8945, std=0.7398
    batch_size=250, relative difference vs CPU: mean=0.9774, std=0.7180
MIOpen Error: username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0
    batch_size=300 FORWARD ON GPU FAILED: miopenStatusBadParm
MIOpen Error: username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0
    batch_size=400 FORWARD ON GPU FAILED: miopenStatusBadParm
MIOpen Error: username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0
    batch_size=500 FORWARD ON GPU FAILED: miopenStatusBadParm
MIOpen Error: username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0
    batch_size=1000 FORWARD ON GPU FAILED: miopenStatusBadParm
```

And here are the results of the same script on a CUDA GPU:
```
Bidirectional LSTM definition: input_size=60, hidden_size=128, num_layers=4
dtype: torch.float16
    batch_size= 10, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size= 50, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=100, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=110, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=120, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=130, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=200, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=250, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=300, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=400, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=500, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=1000, relative difference vs CPU: mean=0.0003, std=0.0003
dtype: torch.float32
    batch_size= 10, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size= 50, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=100, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=110, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=120, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=130, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=200, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=250, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=300, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=400, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=500, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=1000, relative difference vs CPU: mean=0.0001, std=0.0001


Bidirectional LSTM definition: input_size=60, hidden_size=256, num_layers=4
dtype: torch.float16
    batch_size= 10, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size= 50, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=100, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=110, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=120, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=130, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=200, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=250, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=300, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=400, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=500, relative difference vs CPU: mean=0.0003, std=0.0003
    batch_size=1000, relative difference vs CPU: mean=0.0003, std=0.0003
dtype: torch.float32
    batch_size= 10, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size= 50, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=100, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=110, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=120, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=130, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=200, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=250, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=300, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=400, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=500, relative difference vs CPU: mean=0.0001, std=0.0001
    batch_size=1000, relative difference vs CPU: mean=0.0001, std=0.0001
```

Here is the script to reproduce the results:
```py
import gc

import torch

torch.manual_seed(42)
torch.use_deterministic_algorithms(True)


INPUT_SIZE = 60
HIDDEN_SIZE = 128
NUM_LAYERS = 4
MAX_BATCH_SIZE = 2000
SEQLEN = 600


def _make_lstm():
    return torch.nn.LSTM(
        input_size=INPUT_SIZE,
        hidden_size=HIDDEN_SIZE,
        num_layers=NUM_LAYERS,
        bidirectional=True,
        batch_first=True,
    )


STATE_DICT = _make_lstm().state_dict()
RANDOM_INPUT = torch.randn((MAX_BATCH_SIZE, SEQLEN, INPUT_SIZE))


@torch.inference_mode()
def run(x, dtype, device):
    lstm = _make_lstm()
    lstm.load_state_dict(STATE_DICT)
    lstm.to(dtype)
    lstm.to(device)
    lstm.eval()

    x = x.to(device).to(dtype)
    y, _ = lstm(x)
    return y.to(torch.float32).cpu()


@torch.inference_mode()
def main():
    print(f"Bidirectional LSTM definition: input_size={INPUT_SIZE}, "
          f"hidden_size={HIDDEN_SIZE}, num_layers={NUM_LAYERS}")

    batch_sizes = [10, 50, 100, 110, 120, 130, 200, 250, 300, 400, 500, 1000]
    for dtype in [torch.float16, torch.float32]:
        print("dtype:", dtype)
        for batch_size in batch_sizes:
            gc.collect()
            torch.cuda.empty_cache()

            assert batch_size <= MAX_BATCH_SIZE
            x = RANDOM_INPUT[:batch_size].contiguous()

            yref = run(x, torch.float32, "cpu")
            try:
                ywrong = run(x, dtype, "cuda:0")
            except RuntimeError as e:
                print(f"    {batch_size=} FORWARD ON GPU FAILED: {e}")
                continue

            ref_center = yref.abs().mean()
            diff = torch.abs(yref - ywrong) / ref_center
            print(f"    {batch_size=:3d}, relative difference vs CPU: mean="
                  f"{diff.mean():.4f}, std={diff.std():.4f}")


main()
```

### Versions

Collecting environment information...
PyTorch version: 2.10.0
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 7.2.26015

OS: Debian GNU/Linux 12 (bookworm) (x86_64)
GCC version: (Debian 12.2.0-14+deb12u1) 12.2.0
Clang version: 14.0.6
CMake version: version 3.31.6
Libc version: glibc-2.36

Python version: 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] (64-bit runtime)
Python platform: Linux-6.1.0-41-amd64-x86_64-with-glibc2.36
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: 
GPU models and configuration: AMD Radeon AI PRO R9700 (gfx1201)
Nvidia driver version: Could not collect
cuDNN version: Could not collect
Is XPU available: False
HIP runtime version: 7.2.26015
MIOpen runtime version: 3.5.1
Is XNNPACK available: True
Caching allocator config: N/A

CPU:
Architecture:                            x86_64
CPU op-mode(s):                          32-bit, 64-bit
Address sizes:                           48 bits physical, 48 bits virtual
Byte Order:                              Little Endian
CPU(s):                                  32
On-line CPU(s) list:                     0-31
Vendor ID:                               AuthenticAMD
Model name:                              AMD Ryzen 9 9950X 16-Core Processor
CPU family:                              26
Model:                                   68
Thread(s) per core:                      2
Core(s) per socket:                      16
Socket(s):                               1
Stepping:                                0
Frequency boost:                         enabled
CPU(s) scaling MHz:                      44%
CPU max MHz:                             8839.3555
CPU min MHz:                             3000.0000
BogoMIPS:                                8600.02
Flags:                                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp ibrs_enhanced vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx_vnni avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid bus_lock_detect movdiri movdir64b overflow_recov succor smca fsrm avx512_vp2intersect flush_l1d amd_lbr_pmc_freeze
Virtualization:                          AMD-V
L1d cache:                               768 KiB (16 instances)
L1i cache:                               512 KiB (16 instances)
L2 cache:                                16 MiB (16 instances)
L3 cache:                                64 MiB (2 instances)
NUMA node(s):                            1
NUMA node0 CPU(s):                       0-31
Vulnerability Gather data sampling:      Not affected
Vulnerability Indirect target selection: Not affected
Vulnerability Itlb multihit:             Not affected
Vulnerability L1tf:                      Not affected
Vulnerability Mds:                       Not affected
Vulnerability Meltdown:                  Not affected
Vulnerability Mmio stale data:           Not affected
Vulnerability Reg file data sampling:    Not affected
Vulnerability Retbleed:                  Not affected
Vulnerability Spec rstack overflow:      Not affected
Vulnerability Spec store bypass:         Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:                Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:                Mitigation; Enhanced / Automatic IBRS; IBPB conditional; STIBP always-on; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                     Not affected
Vulnerability Tsa:                       Not affected
Vulnerability Tsx async abort:           Not affected
Vulnerability Vmscape:                   Not affected

Versions of relevant libraries:
[pip3] numpy==2.4.2
[pip3] torch==2.10.0
[conda] Could not collect

cc @mikaylagawarecki @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @jataylo @hongxiayang @naromero77amd @pragupta @jerrymannil @xinyazhang

**Comment by mferencevic** [comment]
I've also tested on `gfx1100`  (7900 XTX) and only the big batch-size issue seems to be present. There are no numerical correctness issues.

```
Bidirectional LSTM definition: input_size=60, hidden_size=128, num_layers=4
dtype: torch.float16
    batch_size= 10, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size= 50, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=100, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=110, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=120, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=130, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=200, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=250, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=300, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=400, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=500, relative difference vs CPU: mean=0.0007, std=0.0006
MIOpen Error: username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0
    batch_size=1000 FORWARD ON GPU FAILED: miopenStatusBadParm
dtype: torch.float32
    batch_size= 10, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size= 50, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=100, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=110, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=120, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=130, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=200, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=250, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=300, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=400, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=500, relative difference vs CPU: mean=0.0000, std=0.0000
MIOpen Error: username:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/tensor.cpp:120: Lengths must be > 0
    batch_size=1000 FORWARD ON GPU FAILED: miopenStatusBadParm
```

**Comment by naromero77amd** [comment]
cc: @JonathanLichtnerAMD
There are already two internal Jiras for the issues that should cover these issues.

**Comment by JonathanLichtnerAMD** [comment]
This might actually be a different issue than the other two MIOpen issues, but I will take a look.

**Comment by JonathanLichtnerAMD** [comment]
The fix for the second issue 
> (2) the big batch-size issue (1000) happened on both gfx1201 and gfx950, so this is more general.

will be fixed by PR https://github.com/ROCm/rocm-libraries/pull/7300.  The numerical migration issue might have been addressed by the OCL to hip migration of these kernels, since some issues were addressed there, so we can retest once the above PR is merged.

**Comment by JonathanLichtnerAMD** [comment]
Note that https://github.com/ROCm/rocm-libraries/pull/7300 was merged into rocm-libraries today.

**Comment by mferencevic** [comment]
@JonathanLichtnerAMD @naromero77amd I have retested with the official AMD PyTorch 2.12 wheel bundled with ROCm 7.14 on `gfx1201` and the numerical correctness issue is still present:

```
Bidirectional LSTM definition: input_size=60, hidden_size=128, num_layers=4
dtype: torch.float16
    batch_size= 10, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size= 50, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=100, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=110, relative difference vs CPU: mean=0.0140, std=0.1141
    batch_size=120, relative difference vs CPU: mean=0.1747, std=0.4716
    batch_size=130, relative difference vs CPU: mean=0.3114, std=0.6005
    batch_size=200, relative difference vs CPU: mean=0.8847, std=0.7305
    batch_size=250, relative difference vs CPU: mean=0.9642, std=0.7083
    batch_size=300, relative difference vs CPU: mean=0.9611, std=0.7061
    batch_size=400, relative difference vs CPU: mean=0.9616, std=0.7078
    batch_size=500, relative difference vs CPU: mean=0.9576, std=0.7063
    batch_size=1000, relative difference vs CPU: mean=0.9418, std=0.7016
dtype: torch.float32
    batch_size= 10, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size= 50, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=100, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=110, relative difference vs CPU: mean=0.0134, std=0.1142
    batch_size=120, relative difference vs CPU: mean=0.1742, std=0.4718
    batch_size=130, relative difference vs CPU: mean=0.3110, std=0.6008
    batch_size=200, relative difference vs CPU: mean=0.8847, std=0.7305
    batch_size=250, relative difference vs CPU: mean=1.0828, std=0.8637
    batch_size=300, relative difference vs CPU: mean=1.2134, std=0.9995
    batch_size=400, relative difference vs CPU: mean=1.3588, std=1.2611
    batch_size=500, relative difference vs CPU: mean=1.5400, std=1.4649
    batch_size=1000, relative difference vs CPU: mean=1.4999, std=1.4330
```

Do you have any status update on this issue? The issue is causing major performance regressions on the R9700.

As a side-note, I have also tested on `gfx1151` (Strix Halo), and everything seems to be working correctly.

**Comment by naromero77amd** [comment]
@mferencevic Can you confirm that the big-batch issue (The one that generated the MIOpen error) is resolved? I understand that there are still numerical issues.

**Comment by mferencevic** [comment]
@naromero77amd I can confirm that the big-batch issue is now resolved.

**Comment by naromero77amd** [comment]
@fjankovi can someone from your team look at the numerical issues described here? They appear to be very specific to gfx1201. If you determine that is indeed an MIOpen issue, can you get a reproducer to @JonathanLichtnerAMD.

**Comment by k-artem** [comment]
@mferencevic, I've run with lastest ROCm+upstream torch, no issues observed, results&kernel selection are same for gfx1100 and gfx1200:
* gfx1100
```
Bidirectional LSTM definition: input_size=60, hidden_size=128, num_layers=4
dtype: torch.float16
    batch_size= 10, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size= 50, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=100, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=110, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=120, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=130, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=200, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=250, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=300, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=400, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=500, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=1000, relative difference vs CPU: mean=0.0007, std=0.0006
dtype: torch.float32
    batch_size= 10, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size= 50, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=100, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=110, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=120, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=130, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=200, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=250, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=300, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=400, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=500, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=1000, relative difference vs CPU: mean=0.0000, std=0.0000
(.venv) artem@RSB-RORLAB-09:~/remote/gfx1100$ pip list | grep -E 'torch|rocm'
rocm                    10.0.0.dev0
rocm-sdk-core           10.0.0.dev0
rocm-sdk-devel          10.0.0.dev0
rocm-sdk-device-gfx1100 10.0.0.dev0
rocm-sdk-libraries      10.0.0.dev0
torch                   2.14.0a0+devrocm10.0.0.dev0
(.venv) artem@RSB-RORLAB-09:~/remote/gfx1100$ rocminfo | grep gfx
  Name:                    gfx1100
      Name:                    amdgcn-amd-amdhsa--gfx1100
      Name:                    amdgcn-amd-amdhsa--gfx11-generic
```
* gfx1201
```
Bidirectional LSTM definition: input_size=60, hidden_size=128, num_layers=4
dtype: torch.float16
    batch_size= 10, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size= 50, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=100, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=110, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=120, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=130, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=200, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=250, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=300, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=400, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=500, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=1000, relative difference vs CPU: mean=0.0007, std=0.0006
dtype: torch.float32
    batch_size= 10, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size= 50, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=100, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=110, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=120, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=130, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=200, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=250, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=300, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=400, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=500, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=1000, relative difference vs CPU: mean=0.0000, std=0.0000
(.venv) master@RSB-RORLAB-44:~/artem/remote/gfx1201$ pip list | grep -E 'torch|rocm'
rocm                    10.0.0.dev0
rocm-sdk-core           10.0.0.dev0
rocm-sdk-devel          10.0.0.dev0
rocm-sdk-device-gfx1201 10.0.0.dev0
rocm-sdk-libraries      10.0.0.dev0
torch                   2.14.0a0+devrocm10.0.0.dev0
(.venv) master@RSB-RORLAB-44:~/artem/remote/gfx1201$  rocminfo | grep gfx
  Name:                    gfx1201
      Name:                    amdgcn-amd-amdhsa--gfx1201
      Name:                    amdgcn-amd-amdhsa--gfx12-generic
  Name:                    gfx1201
      Name:                    amdgcn-amd-amdhsa--gfx1201
      Name:                    amdgcn-amd-amdhsa--gfx12-generic
```
Could you please run with `MIOPEN_LOG_LEVEL=6 MIOPEN_ENABLE_LOGGING_CMD=1 MIOPEN_ENABLE_LOGGING=1` on your env and share log?

Also make sense to try to force hipblaslt on your env and check results: `export MIOPEN_GEMM_ENFORCE_BACKEND=5`

CC @naromero77amd

**Comment by mferencevic** [comment]
@k-artem I have attached the logs.

The first log is with the following environment variables set: `MIOPEN_LOG_LEVEL=6 MIOPEN_ENABLE_LOGGING_CMD=1 MIOPEN_ENABLE_LOGGING=1`.

The second log is with the environment variables from the first log and with `MIOPEN_GEMM_ENFORCE_BACKEND=5`.

In addition to the correctness issue, we have now also observed a massive performance regression.
MIOpen seems to be compiling the code for a very long time when comparing ROCm 7.14.0 vs ROCm 7.2.1.

The entire script runtime on ROCm 7.2.1. is `0m29.280s` and the entire script runtime on ROCm 7.14.0 is `19m50.491s` with CPU usage pegged to 100% (all cores) the entire time which makes inference practically unusable.
Additionally, setting `MIOPEN_FIND_MODE=FAST` doesn't seem to change anything time-wise and the two runs (with and without `export MIOPEN_GEMM_ENFORCE_BACKEND=5`) have the same runtime.

The environment contains AMD official PyTorch and ROCm packages downloaded using:
```bash
pip install --index-url https://repo.amd.com/rocm/whl-multi-arch/ "rocm[libraries,device-all]==7.14.0" "torch[device-all]==2.12.0+rocm7.14.0"
```

[lstm_second_log.txt.gz](https://github.com/user-attachments/files/30591000/lstm_second_log.txt.gz)
[lstm_first_log.txt.gz](https://github.com/user-attachments/files/30590999/lstm_first_log.txt.gz)

**Comment by k-artem** [comment]
thanks @mferencevic for feedback, I also rechecked torch2.12 with rocm10.0.0
```
rocm                           10.0.0rc4
rocm-bootstrap                 0.1.0
rocm-sdk-core                  10.0.0rc4
rocm-sdk-libraries             10.0.0rc4
torch                          2.12.0+rocm10.0.0rc4
torchaudio                     2.11.0+rocm10.0.0rc4
torchvision                    0.27.0+rocm10.0.0rc4
triton                         3.8.0+git4cff872c.rocm10.0.0rc4

  Name:                    gfx1201
      Name:                    amdgcn-amd-amdhsa--gfx1201
      Name:                    amdgcn-amd-amdhsa--gfx12-generic
```
and results seems ok (both running time and correctness of results)
```
root@ctr-navi4x-aj57-ws07:/workspace# time python test.py
Bidirectional LSTM definition: input_size=60, hidden_size=128, num_layers=4
dtype: torch.float16
    batch_size= 10, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size= 50, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=100, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=110, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=120, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=130, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=200, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=250, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=300, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=400, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=500, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=1000, relative difference vs CPU: mean=0.0007, std=0.0006
dtype: torch.float32
    batch_size= 10, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size= 50, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=100, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=110, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=120, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=130, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=200, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=250, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=300, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=400, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=500, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=1000, relative difference vs CPU: mean=0.0000, std=0.0000

real    0m31.885s
user    4m10.078s
sys     1m17.249s
```

**Comment by k-artem** [comment]
@mferencevic, also I've reproduced correctness issue this rocm7.14 on gfx1201 with the same behavior of bidirectional LSTM (input=60, hidden=128, layers=4, seq=600, bias=True) on PyTorch 2.12. Correctness collapses at the first shape where the bias add after packed GEMM launches `Op2dTensorLite` with grid Y > 65535 (65535  is HIP maxGridSize.y on gfx12), e.g. 

batch | M = batch × 600 (SEQLEN = 600 from repro script) | Op2dTensorLite global_work_dim.y (ROCm 7.14 / MIOpen 3.5.x) | fp16 mean rel. err
-- | -- | -- | --
100 | 60000 | 60032 (OK) | 0.0007
110 | 66000 | 66048 (> 65535) | 0.0140
120 | 72000 | 72000 | 0.1747

At the HIP level, it appears that we have a tensor slice, and this is where the correctness issue becomes visible. 

It passes with ROCm 10 because the issue was fixed in next PR https://github.com/ROCm/rocm-libraries/pull/9049 (https://github.com/ROCm/rocm-libraries/pull/9049/changes#diff-5659b43f978125c87e6b8f262dca56e491deabe0347f41523017557d64c3876dR123).

>  ROCm 7.14.0 is 19m50.491s with CPU usage pegged to 100% (all cores) the entire time which makes inference practically unusable.

I didn't repro timing issue, results from rocm 7.14 below:
```
root@ctr-navi4x-aj57-ws07:/home/user/workspace# rm -rf ~/.cache/miopen/ && time python test.py
Bidirectional LSTM definition: input_size=60, hidden_size=128, num_layers=4
dtype: torch.float16
    batch_size= 10, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size= 50, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=100, relative difference vs CPU: mean=0.0007, std=0.0006
    batch_size=110, relative difference vs CPU: mean=0.0140, std=0.1141
    batch_size=120, relative difference vs CPU: mean=0.1747, std=0.4716
    batch_size=130, relative difference vs CPU: mean=0.3114, std=0.6005
    batch_size=200, relative difference vs CPU: mean=0.8847, std=0.7305
    batch_size=250, relative difference vs CPU: mean=0.9642, std=0.7083
    batch_size=300, relative difference vs CPU: mean=0.9611, std=0.7061
    batch_size=400, relative difference vs CPU: mean=0.9616, std=0.7078
    batch_size=500, relative difference vs CPU: mean=0.9576, std=0.7063
    batch_size=1000, relative difference vs CPU: mean=0.9418, std=0.7016
dtype: torch.float32
    batch_size= 10, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size= 50, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=100, relative difference vs CPU: mean=0.0000, std=0.0000
    batch_size=110, relative difference vs CPU: mean=0.0134, std=0.1142
    batch_size=120, relative difference vs CPU: mean=0.1742, std=0.4718
    batch_size=130, relative difference vs CPU: mean=0.3110, std=0.6008
    batch_size=200, relative difference vs CPU: mean=0.8847, std=0.7305
    batch_size=250, relative difference vs CPU: mean=1.0828, std=0.8637
    batch_size=300, relative difference vs CPU: mean=1.2134, std=0.9995
    batch_size=400, relative difference vs CPU: mean=1.3588, std=1.2611
    batch_size=500, relative difference vs CPU: mean=1.5400, std=1.4649
    batch_size=1000, relative difference vs CPU: mean=1.4999, std=1.4330

real    0m33.069s
user    4m3.057s
sys     1m18.123s
```

So, @mferencevic please use rocm10 if it works for you or adjust params.

CC @JonathanLichtnerAMD @fjankovi

**Comment by k-artem** [comment]
@jeffdaily  @naromero77amd  added  specific test, please have a look -> https://github.com/pytorch/pytorch/pull/195738
