### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by Sierkinhane** [pytorch/pytorch#17834]
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: unknown error (malloc at /home/hane/下载/pytorch/c10/cuda/CUDACachingAllocator.cpp:249)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f59cf75415a in /home/hane/下载/pytorch/torch/lib/libc10.so)
frame #1: <unknown function> + 0x14da9 (0x7f59ce527da9 in /home/hane/下载/pytorch/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x17972 (0x7f59ce52a972 in /home/hane/下载/pytorch/torch/lib/libc10_cuda.so)
frame #3: at::native::empty_cuda(c10::ArrayRef<long>, c10::TensorOptions const&) + 0x3bb (0x7f59d1d13fdb in /home/hane/下载/pytorch/torch/lib/libcaffe2_gpu.so)
frame #4: at::CUDAFloatType::empty(c10::ArrayRef<long>, c10::TensorOptions const&) const + 0x61 (0x7f59d0754dd1 in /home/hane/下载/pytorch/torch/lib/libcaffe2_gpu.so)
frame #5: at::TypeDefault::copy(at::Tensor const&, bool, c10::optional<c10::Device>) const + 0x153 (0x7f59e36a5a73 in /home/hane/下载/pytorch/torch/lib/libcaffe2.so)
frame #6: at::native::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) + 0x12fa (0x7f59e33a699a in /home/hane/下载/pytorch/torch/lib/libcaffe2.so)
frame #7: at::TypeDefault::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) const + 0x2b (0x7f59e367893b in /home/hane/下载/pytorch/torch/lib/libcaffe2.so)
frame #8: void torch::nn::Module::to_impl<c10::Device&, bool&>(c10::Device&, bool&) + 0x1c6 (0x7f59e7b9d7d6 in /home/hane/下载/pytorch/torch/lib/libtorch.so.1)
frame #9: torch::nn::Module::to(c10::Device, bool) + 0x18 (0x7f59e7b9a028 in /home/hane/下载/pytorch/torch/lib/libtorch.so.1)
frame #10: main + 0x18d (0x419e3b in ./simple-nn)
frame #11: __libc_start_main + 0xf0 (0x7f59cede8830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #12: _start + 0x29 (0x418ee9 in ./simple-nn)

**Comment by Sierkinhane** [comment]
and torch::cuda::is_available is True, I

**Comment by Sierkinhane** [comment]
int main() {
  torch::Device device("cpu");
  if (torch::cuda::is_available()){
  	cout << torch::cuda::is_available() << endl;
    device = torch::Device("cuda:0");
  }

  torch::Tensor t = torch::rand({2, 3, 224, 224}).to(device);
  ResNet<BottleNeck> resnet = resnet101();
  resnet.to(device);

  t = resnet.forward(t);
  std::cout << t.sizes() << std::endl;
}

it was ok in cpu, but error in cuda.

**Comment by Sierkinhane** [comment]
Environment

    PyTorch Version (e.g., 1.0): 1.0
    OS (e.g., Linux): ubuntu 16.04
    How you installed PyTorch (conda, pip, source): conda
    Build command you used (if compiling from source): following the guide on official page
    Python version:3.5
    CUDA/cuDNN version: cuda 9.0 + cudnn7.0
    GPU models and configuration:
    Any other relevant information:

**Comment by ezyang** [comment]
Can you report the output of `nvidia-smi` on your machine?

**Comment by martinruenz** [comment]
This might be useful:
https://github.com/pytorch/pytorch/issues/13541

**Comment by Sierkinhane** [comment]
thank you, I reinstalled cuda support then it worked!
