### ISSUE TITLE
torch.distributed.launch receives `RuntimeError: ProcessGroupNCCL does not support barrier`

### ISSUE THREAD

**Issue by michaelyyq** [pytorch/pytorch#17848]
### Environment:
- pytorch 1.0.0.dev20181009
- cuda 9.0
- cudnn 7.1
- python 3.6.5
- TITAN V

### Description:
When I run the following, `RuntimeError: ProcessGroupNCCL does not support barrier` occurs.
`python -m torch.distributed.launch train_net.py`
```
Traceback (most recent call last):
  File "train_net.py", line 187, in <module>
    main()
  File "train_net.py", line 157, in main
    synchronize()
  File "comm.py", line 45, in synchronize
    dist.barrier()
   File “torch/distributed/distributed_c10d.py”, line 1070, in barrier
     work = _default_pg.barrier()
RuntimeError: ProcessGroupNCCL does not support barrier
```

**Comment by soumith** [comment]
we've fixed this on v1.0.1 and later, I believe. Update your pytorch to a newer version, preferably from 2019.
Reopen the issue if you continue seeing the problem
