### ISSUE TITLE
Conv3d fail after curtain batch size

### ISSUE THREAD

**Issue by paland3** [pytorch/pytorch#17930]
## Issue description
The same conv3D does work on batch size = 24 (outputs filled tensor), but not on batch size = 25 (illegal memory access, not filled tensor).

## Code example
Minimal working example:
Copy these lines in a py file, and run it, the second print does not work on 2 computers we have.
```
import torch
import torch.nn as nn

conv1=nn.Conv3d(1, 10, kernel_size=(3, 3, 10), stride=(1, 1, 1), padding=(1, 1, 0)).cuda()

x = torch.randn(24, 1, 100, 375, 128).cuda()
print(conv1(x))

x = torch.randn(25, 1, 100, 375, 128).cuda()
print(conv1(x))
```

## System Info

- PyTorch or Caffe2: Pytorch
- How you installed PyTorch (conda, pip, source): anaconda-navigator
- OS: Ubuntu 18.04
- PyTorch version: 1.0.1
- Python version: 3.7.2/3.6.8
- CUDA/cuDNN version: 10.1
- GPU models and configuration: Titan X Pascal

**Comment by mruberry** [comment]
We are investigating this issue.

**Comment by mruberry** [comment]
We have identified the error and are working on a fix in cuDNN.

**Comment by paland3** [comment]
> We have identified the error and are working on a fix in cuDNN.

What was the problem's source?

**Comment by mruberry** [comment]
I'm sorry I don't know, I'm not on our cuDNN team. I only know they are working on a fix.

**Comment by mruberry** [comment]
Good news, looks like this is fixed in cuDNN 7.6. I was able to reproduce using an older cuDNN and the script ran successfully for me after upgrading to cuDNN 7.6.

Please try it and let me know what you find.

**Comment by gchanan** [comment]
@VitalyFedyunin is going to verify that this is fixed.

**Comment by mruberry** [comment]
I can confirm this is now resolved!
