### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED when calling torch.cudnn_affine_grid_generator

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#18032]
## 🐛 Bug

For the following code block
```python
import torch
import torch.nn.functional as F

x = torch.Tensor(torch.Size([64, 2, 3])).to(torch.device("cuda"))
grid = F.affine_grid(x, torch.Size([64, 1, 28, 28]))
```

With CUDA 8.0.61 and CUDNN 7.2.1 it gives the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 2684, in affine_grid
    return vision.affine_grid_generator(theta, size)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/_functions/vision.py", line 11, in affine_grid_generator
    ret = torch.cudnn_affine_grid_generator(theta, N, C, H, W)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

With CUDA 9.0.176 and CUDNN 7.4.2 it works fine.

## Expected behavior

The same code worked on nightly builds before Jan 27, 2019, but is broken after Feb 8, 2019, which suggests that there is a regression commit in between.

**Comment by hfarazi** [comment]
The same problem here!

**Comment by sailordiary** [comment]
Same here!

**Comment by xinliweiyuan** [comment]
see https://github.com/pytorch/pytorch/issues/14260

but the issue is not solved. The same problem here. Especially when you want to use RNNs.

**Comment by xinliweiyuan** [comment]
I finally found the reason might due to the Cuda and Cudnn configuration issue. You might have several Cuda or Cudnn.  Check it. My problem was solved.

**Comment by ezyang** [comment]
CUDA 8 is no longer supported.
