### ISSUE TITLE
[Dynamo] speech_transformer SIGSEGV on A10G in periodic benchmarks

### ISSUE THREAD

**Issue by NikhilAPatel** [pytorch/pytorch#180741]
### Description

`speech_transformer` causes a SIGSEGV (exit code -11) during dynamo compilation on A10G GPUs in the periodic benchmark CI:

```
Run failed with return code: -11
```

The crash occurs during dynamo tracing, preceded by graph break warnings about `Tensor.item()` in the speech_transformer model:
```
W0418 09:24:29.944000 Graph break from Tensor.item(), consider setting:
    torch._dynamo.config.capture_scalar_outputs = True
  File ".../speech_transformer/utils/utils.py", line 108, in get_non_pad_mask
    non_pad_mask[i, input_lengths[i] :] = 0
```

### Details

- Affects `dynamo_eager_torchbench`, `aot_eager_torchbench`, `dynamic_aot_eager_torchbench` on CUDA (A10G)
- The benchmark runner continues after the crash; subsequent models still run
- Does not directly cause CI failure (the CI fails due to other model graph break regressions)
- Likely OOM-related on A10G (22GB VRAM) or a C++ crash in the dynamo compiler

### CI Impact

Non-blocking. The periodic benchmark framework handles individual model crashes gracefully.

cc @ezyang @gchanan @kadeng @msaroufim @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @amjames @Lucaskabela @jataylo @azahed98

**Comment by NikhilAPatel** [comment]
Note: `speech_transformer` has been baselined as `fail_to_run` in `benchmarks/dynamo/ci_expected_accuracy/dynamic_cpu_max_autotune_inductor_amp_freezing_torchbench_inference.csv` (PR #180738) to unblock CI.

When this issue is fixed, please update the baseline back to `pass,10`.
