### ISSUE TITLE
TypeError:  _queue_reduction() when using DistributedDataParallel to train model with unused parameters

### ISSUE THREAD

**Issue by fyabc** [pytorch/pytorch#18180]
## 🐛 Bug

Hi, I have tried to use `torch.nn.parallel.DistributedDataParallel` to train a model on multi GPUs. My model *shares* weights between several "child networks". In each training step, I want to train only one child network and update its related parameters in the shared model, and other parameters are remain unchanged.
The code can run on single GPU. However, I met "TypeError:  _queue_reduction()" when using `DistributedDataParallel` as the parallel model.
I have found that issue #13273 also report the same error, and I have tried to run the code on PyTorch-nightly build and use `apex.parallel.DistributedDataParallel`, but the error still occurs.
I want to know how to fix this error, and how to train the model with unused parameters on multi-GPUs.
Thanks.

## To Reproduce

1. Copy the code snippet into **reproduce.py**, and run ``python reproduce.py``.

The code snippet to reproduce the error:

```python
#! /usr/bin/python
# -*- coding: utf-8 -*-

import argparse
import gc
import os
import time

import torch
import torch.distributed as dist
import torch.nn.functional as F

from torch.multiprocessing import Process
from torch.utils.data import DataLoader
from torch.nn.parallel import DistributedDataParallel, DataParallel
from torch.utils.data.distributed import DistributedSampler


def show_gpu_memory(device=None):
    if device is None:
        device = torch.cuda.current_device()
    print('## GPU memory usage: rank={}, CurrentMem={:.2f}MiB, MaxMem={:.2f}MiB, CachedMem={:.2f}MiB'.format(
        device,
        torch.cuda.memory_allocated(device) / (1 << 20),
        torch.cuda.max_memory_allocated(device) / (1 << 20),
        torch.cuda.memory_cached(device) / (1 << 20)
    ), flush=True)


class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, data_list):
        self.data_list = data_list

    def __len__(self):
        return len(self.data_list)

    def __getitem__(self, item):
        return self.data_list[item]


class Child(torch.nn.Module):
    def __init__(self, lin_in, linear, lin_out):
        super().__init__()
        self.lin_in = lin_in
        self.linear = linear
        self.lin_out = lin_out

    def forward(self, x):
        return self.lin_out(self.linear(self.lin_in(x)))


class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linears = torch.nn.ModuleList([
            torch.nn.Linear(2000, 5000)     # 38.14MiB
            for _ in range(10)
        ])
        self.lin_in = torch.nn.Linear(3, 2000)
        self.lin_out = torch.nn.Linear(5000, 4)

    @property
    def num_linears(self):
        return len(self.linears)

    def get_child(self, i):
        return Child(self.lin_in, self.linears[i % self.num_linears], self.lin_out)


def get_dataset():
    data_list = [{"x": torch.FloatTensor(3).random_(), "y": torch.FloatTensor(4).random_()} for i in range(10)]
    return CustomDataset(data_list)


def train(args, rank, size, device_name):
    print('| rank={}, size={}, device_name={}'.format(rank, size, device_name))
    dataset = get_dataset()
    distributed_sampler = DistributedSampler(dataset, size, rank)
    train_loader = DataLoader(dataset, pin_memory=True, sampler=distributed_sampler)
    device = torch.device(device_name)
    model = Model()
    model.to(device)

    # optimizer = torch.optim.Adam(model.parameters())
    optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

    children = [None for _ in range(model.num_linears)]

    num_updates = 0
    for epoch in range(100):
        model.train()
        for batch_num, batch in enumerate(train_loader):
            print('epoch={}, rank={}, batch_num={}, x_shape={}'.format(
                epoch, rank, batch_num, batch["x"].shape))
            show_gpu_memory(device)
            optimizer.zero_grad()

            # Create child from model.
            if not args.cache_child:
                child = model.get_child(num_updates)
            else:
                child = children[num_updates % len(children)]
                if child is None:
                    child = model.get_child(num_updates)
                    children[num_updates % len(children)] = child

            # Parallel child
            if args.dp == 'ddp':
                child = DistributedDataParallel(child, device_ids=[device])
            elif args.dp == 'dp':
                child = DataParallel(child, device_ids=[device])
            elif args.dp == 'lddp':
                from legacy_distributed_data_parallel import LegacyDistributedDataParallel
                child = LegacyDistributedDataParallel(module=child, world_size=2)
            elif args.dp == 'none':
                pass
            else:
                raise ValueError('Unknown data-parallel model {!r}'.format(args.dp))

            pred = child(batch['x'].to(device))
            exp = batch['y'].to(device)
            loss = F.binary_cross_entropy_with_logits(exp, pred)
            loss.backward()
            del loss

            optimizer.step()
            num_updates += 1
    gc.collect()
    torch.cuda.empty_cache()
    print('Final GPU memory usage:')
    show_gpu_memory(device)


def init_processes(args, rank, size, fn, ddp_args, device):
    """ Initialize the distributed environment. """
    os.environ['MASTER_ADDR'] = ddp_args['master_addr']
    os.environ['MASTER_PORT'] = ddp_args['master_port']
    os.environ['WORLD_SIZE'] = str(size)
    os.environ['RANK'] = str(rank)
    dist.init_process_group(ddp_args['backend'], rank=rank, world_size=size)
    fn(args, rank, size, device)
    print("done, rank={}".format(rank))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dp', choices=['dp', 'ddp', 'lddp', 'none'], default='ddp',
                        help='data-parallel model, default is %(default)r')
    parser.add_argument('--no-cache-child', action='store_false', dest='cache_child', default=True,
                        help='disable cache child')
    args = parser.parse_args()

    start_time = time.time()
    ddp_args = {"master_addr": "127.0.0.1", "master_port": "29500", "backend": "gloo"}
    devices = ["cuda:0", "cuda:1"]
    size = len(devices)
    processes = []
    for rank, device in enumerate(devices):
        p = Process(target=init_processes, args=(args, rank, size, train, ddp_args, device))
        p.start()
        processes.append(p)

    while not any(p.exitcode is not None for p in processes):  # all worker processes have finished
        time.sleep(0.2)

    for p in processes:
        print("join")
        p.join()
        print("join done")
    print("all done")

    print('Time passed: {:.6f}s'.format(time.time() - start_time))


if __name__ == "__main__":
    main()
```

2. I also tried the `LegacyDistributedDataParallel` from [here](https://github.com/pytorch/fairseq/blob/v0.6.2/fairseq/legacy_distributed_data_parallel.py), but it ran out of memory after several epochs and it seems that a GPU memory leak occurred.
Run steps:
    1. Copy [legacy_distributed_data_parallel.py](https://github.com/pytorch/fairseq/blob/v0.6.2/fairseq/legacy_distributed_data_parallel.py) and [distributed_utils.py](https://github.com/pytorch/fairseq/blob/v0.6.2/fairseq/distributed_utils.py) to the same place of `reproduce.py`
    2. Run `python reproduce.py --dp lddp`.

## Expected behavior

1. Output of `python reproduce.py`:
```
| rank=1, size=2, device_name=cuda:1
| rank=0, size=2, device_name=cuda:0
epoch=0, rank=0, batch_num=0, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:0, CurrentMem=382.80MiB, MaxMem=382.80MiB, CachedMem=383.50MiB
epoch=0, rank=1, batch_num=0, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:1, CurrentMem=382.80MiB, MaxMem=382.80MiB, CachedMem=383.50MiB
epoch=0, rank=1, batch_num=1, x_shape=torch.Size([1, 3])
epoch=0, rank=0, batch_num=1, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:0, CurrentMem=421.31MiB, MaxMem=459.68MiB, CachedMem=462.12MiB
## GPU memory usage: rank=cuda:1, CurrentMem=421.31MiB, MaxMem=459.68MiB, CachedMem=462.12MiB
epoch=0, rank=0, batch_num=2, x_shape=torch.Size([1, 3])
epoch=0, rank=1, batch_num=2, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:0, CurrentMem=459.70MiB, MaxMem=498.09MiB, CachedMem=540.75MiB
## GPU memory usage: rank=cuda:1, CurrentMem=459.70MiB, MaxMem=498.09MiB, CachedMem=540.75MiB
Process Process-1:
Process Process-2:
Traceback (most recent call last):
  File "/home/yangfan/anaconda3/envs/py36-torch10/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/yangfan/anaconda3/envs/py36-torch10/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "reproduce.py", line 141, in init_processes
    fn(args, rank, size, device)
  File "reproduce.py", line 123, in train
    loss.backward()
Traceback (most recent call last):
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 445, in distributed_data_parallel_hook
    self._queue_reduction(bucket_idx)
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 475, in _queue_reduction
    self.device_ids)
  File "/home/yangfan/anaconda3/envs/py36-torch10/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
TypeError: _queue_reduction(): incompatible function arguments. The following argument types are supported:
    1. (process_group: torch.distributed.ProcessGroup, grads_batch: List[List[at::Tensor]], devices: List[int]) -> Tuple[torch.distributed.Work, at::Tensor]

Invoked with: <torch.distributed.ProcessGroupGloo object at 0x7f66f15265a8>, [[None, tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0'), tensor([ -555026.2500, -1591406.2500, -1114738.2500, -1381190.5000],
       device='cuda:0')]], [0]
  File "/home/yangfan/anaconda3/envs/py36-torch10/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "reproduce.py", line 141, in init_processes
    fn(args, rank, size, device)
  File "reproduce.py", line 123, in train
    loss.backward()
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 445, in distributed_data_parallel_hook
    self._queue_reduction(bucket_idx)
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 475, in _queue_reduction
    self.device_ids)
TypeError: _queue_reduction(): incompatible function arguments. The following argument types are supported:
    1. (process_group: torch.distributed.ProcessGroup, grads_batch: List[List[at::Tensor]], devices: List[int]) -> Tuple[torch.distributed.Work, at::Tensor]

Invoked with: <torch.distributed.ProcessGroupGloo object at 0x7f66f15266c0>, [[None, tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:1'), tensor([-6.5016e+05, -2.6875e+02, -1.0882e+06, -4.0550e+06], device='cuda:1')]], [1]
join
join done
join
join done
all done
Time passed: 10.873415s
```

2. Output of `python reproduce.py --dp lddp`:

```
| rank=0, size=2, device_name=cuda:0
epoch=0, rank=0, batch_num=0, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:0, CurrentMem=382.80MiB, MaxMem=382.80MiB, CachedMem=383.50MiB
| rank=1, size=2, device_name=cuda:1
epoch=0, rank=1, batch_num=0, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:1, CurrentMem=382.80MiB, MaxMem=382.80MiB, CachedMem=383.50MiB
epoch=0, rank=0, batch_num=1, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:0, CurrentMem=459.56MiB, MaxMem=459.56MiB, CachedMem=460.12MiB
epoch=0, rank=1, batch_num=1, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:1, CurrentMem=459.56MiB, MaxMem=459.56MiB, CachedMem=460.12MiB
epoch=0, rank=1, batch_num=2, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:1, CurrentMem=536.20MiB, MaxMem=536.20MiB, CachedMem=536.75MiB
epoch=0, rank=0, batch_num=2, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:0, CurrentMem=536.20MiB, MaxMem=536.20MiB, CachedMem=536.75MiB
epoch=0, rank=0, batch_num=3, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:0, CurrentMem=612.85MiB, MaxMem=612.85MiB, CachedMem=613.38MiB
epoch=0, rank=1, batch_num=3, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:1, CurrentMem=612.85MiB, MaxMem=612.85MiB, CachedMem=613.38MiB
epoch=0, rank=0, batch_num=4, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:0, CurrentMem=689.49MiB, MaxMem=689.49MiB, CachedMem=690.00MiB

... after several steps ...

epoch=50, rank=0, batch_num=2, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:0, CurrentMem=10436.11MiB, MaxMem=10436.11MiB, CachedMem=10474.75MiB
epoch=50, rank=1, batch_num=2, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:1, CurrentMem=10436.11MiB, MaxMem=10436.11MiB, CachedMem=10474.75MiB
epoch=50, rank=0, batch_num=3, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:0, CurrentMem=10474.48MiB, MaxMem=10474.48MiB, CachedMem=10513.12MiB
epoch=50, rank=1, batch_num=3, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:1, CurrentMem=10474.48MiB, MaxMem=10474.48MiB, CachedMem=10513.12MiB
epoch=50, rank=1, batch_num=4, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:1, CurrentMem=10512.86MiB, MaxMem=10512.86MiB, CachedMem=10551.50MiB
epoch=50, rank=0, batch_num=4, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:0, CurrentMem=10512.86MiB, MaxMem=10512.86MiB, CachedMem=10551.50MiB
epoch=51, rank=1, batch_num=0, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:1, CurrentMem=10551.23MiB, MaxMem=10551.23MiB, CachedMem=10589.88MiB
epoch=51, rank=0, batch_num=0, x_shape=torch.Size([1, 3])
## GPU memory usage: rank=cuda:0, CurrentMem=10551.23MiB, MaxMem=10551.23MiB, CachedMem=10551.62MiB
Process Process-1:
Traceback (most recent call last):
  File "/home/yangfan/anaconda3/envs/py36-torch10/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/yangfan/anaconda3/envs/py36-torch10/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "reproduce.py", line 141, in init_processes
    fn(args, rank, size, device)
  File "reproduce.py", line 123, in train
    loss.backward()
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 38.25 MiB (GPU 0; 11.90 GiB total capacity; 10.30 GiB already allocated; 16.06 MiB free; 364.50 KiB cached)
Process Process-2:
Traceback (most recent call last):
  File "/home/yangfan/anaconda3/envs/py36-torch10/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/yangfan/anaconda3/envs/py36-torch10/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "reproduce.py", line 141, in init_processes
    fn(args, rank, size, device)
  File "reproduce.py", line 123, in train
    loss.backward()
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/yangfan/Jobs/FairSeqDist/examples/DebugDistPy/legacy_distributed_data_parallel.py", line 163, in reduction_fn
    all_reduce(buffered_params)
  File "/home/yangfan/Jobs/FairSeqDist/examples/DebugDistPy/legacy_distributed_data_parallel.py", line 117, in all_reduce
    distributed_utils.all_reduce(buffer, self.process_group)
  File "/home/yangfan/Jobs/FairSeqDist/examples/DebugDistPy/distributed_utils.py", line 128, in all_reduce
    return dist.all_reduce(tensor, group=group)
  File "/home/yangfan/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 838, in all_reduce
    work.wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [127.0.0.1]:41612
join
join done
join
join done
all done
Time passed: 34.389752s
```

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.44
GPU models and configuration: 
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 384.111
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so.5.0.5
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a

**Comment by githubgsq** [comment]
I also met the same error.

**Comment by apsdehal** [comment]
This error normally happens when you try to use your model with `DistributedDataParallel` and it has unused parameters. In your case, only one of the 10 linear layers from forward will be used, other 9 will be unused in particular forward. To fix this, try to write code in a way that none of the layers in model are unused in forward.

**Comment by ustctf** [comment]
I come upon almost the same problem. 

Furthermore, currently it is quite usual to have such unused params such as in conditional computing and in architecture search. Are there any plans to fix this? @apsdehal

**Comment by apsdehal** [comment]
I am following #13273 for updates.

**Comment by fmassa** [comment]
@mrshenli could you have a look at this?

**Comment by mrshenli** [comment]
sure, self-assigned

**Comment by mrshenli** [comment]
#18251 aims at fixing this issue

**Comment by pietern** [comment]
This will be solved once #18953 is merged.

@fyabc Can you give it a try and see if it fixes the issue for you?

**Comment by fyabc** [comment]
I tried #18953, and the problem has been solved. Thanks!
