### ISSUE TITLE
cuda out of memory while loss.backward() 

### ISSUE THREAD

**Issue by mdasifjalal** [pytorch/pytorch#18313]
Traceback (most recent call last):
  File "info.py", line 409, in <module>
    loss.backward()
  File "/home/xyz/anaconda3/envs/ml_torch/lib/python3.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/xyz/anaconda3/envs/ml_torch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: out of memory

 I am using nvidia gtx 1080 Ti

**Comment by Rhuax** [comment]
It's a quite simple error message: you don't have enough RAM on your gpu in order to allocate memory needed to the backward pass. Can you post some code? Are you watching the memory usage with `nvidia-smi`?

**Comment by mdasifjalal** [comment]
Yes, I was checking with nvidia-smi. The problem was occurring after some epochs. I found that the allocated GPU memory wasn't being allocated again. I manually deleted them after each epoch and now the problem is resolved. Thanks a lot for your response.

**Comment by FruechteBini** [comment]
hey ghost, can you elaborate on how you you deleted the gpu memory after each epoch?
