### ISSUE TITLE
[dynamo][autograd.Function] torch.compile catastrophically changes grad output of in-place autograd matmul

### ISSUE THREAD

**Issue by Birch-san** [pytorch/pytorch#184113]
### 🐛 Describe the bug

This silent correctness bug caused huge divergence when we attempted to enable torch.compile in our training. Compiled model has completely different grads. Might be due to utilising an autograd function, might be due to in-place operations. But doesn't match eager.

We first noticed this on torch 2.11.0 B200 CUDA, but I reproduced it on macOS with CPU and MPS backends (there was no WiFi on the plane okay).

```
# (control): two instances of same model produce same fwd and bwd output. no repro.
python -m repro
fwd outputs matched
model grads matched

# (repro): compile one of the model instances. fwd still matches, grads are completely different.
python -m repro --compile
fwd outputs matched
```

grads are very different. doesn't look like typical numerics fare.  
```
model0.lin.weight.grad
tensor([[ 1.7422,  0.0000],
        [-0.1167,  0.0000]])

model1.lin.weight.grad
tensor([[-0.6289,  0.0000],
        [-0.8594,  0.0000]])
```

`repro.py`  
```python
from __future__ import annotations
from argparse import ArgumentParser, Namespace
from dataclasses import dataclass
import torch
from torch import FloatTensor, IntTensor, Tensor, nn, no_grad
from torch.testing import assert_close
from torch.nn.functional import mse_loss
from os import environ, getenv
import math
from typing import Literal

# based on k-diffusion's _apply_rotary_emb_inplace
# MIT-licensed, by Katherine Crowson
# https://github.com/crowsonkb/k-diffusion/blob/21d12c91ad4550e8fcf3308ff9fe7116b3f19a08/k_diffusion/models/image_transformer_v2.py#L188C5-L188C30
def _halfrope_inplace(t: Tensor, freqs_cis: Tensor, coeff: Literal[1, -1]) -> None:
    cos, sin = freqs_cis.unbind(-1)
    ty, tx = t.unbind(-1)
    # TODO: if this is currently in half-precision, should we do the addition in float32, to reduce accumulation error?
    ty_roped = ty.mul(cos).addcmul_(sin, tx, value=coeff)
    tx_roped = tx.mul(cos).addcmul_(sin, ty, value=-coeff)
    ty.copy_(ty_roped)
    tx.copy_(tx_roped)


# based on k-diffusion's ApplyRotaryEmbeddingInplace,
# MIT-licensed, by Katherine Crowson
# https://github.com/crowsonkb/k-diffusion/blob/21d12c91ad4550e8fcf3308ff9fe7116b3f19a08/k_diffusion/models/image_transformer_v2.py#L202
class HalfRopeInPlace(torch.autograd.Function):
    # we don't currently use vmap, but maybe it will enable compile to fuse QK rope apply into flex attn operations?
    # benchmark suggests that enabling this didn't incur any additional cold-start time, so I guess it's lazy.
    generate_vmap_rule = True

    @staticmethod
    def forward(t: Tensor, freqs_cis: Tensor, coeff: Literal[1, -1] = -1):
        "NOTE: passing the coeff arg -1 explicitly gives better compiled performance than relying on arg defaulting"
        _halfrope_inplace(t, freqs_cis, coeff=coeff)
        return t

    @staticmethod
    def setup_context(ctx, inputs, output):
        t, freqs_cis, coeff = inputs
        # mark t as dirty because we will modify it in-place. this ensures backward() will be called.
        ctx.mark_dirty(t)
        ctx.save_for_backward(freqs_cis)
        # required for jvp, probably
        ctx.save_for_forward(freqs_cis)
        ctx.coeff = coeff

    @staticmethod
    def backward(ctx, grad_output):
        (freqs_cis,) = ctx.saved_tensors
        # clone made because we must "NEVER" modify grad-w.r.t-input in-place.
        # https://pytorch.org/docs/main/notes/extending.html#how-to-use
        # https://discuss.pytorch.org/t/is-it-safe-to-modify-outputs-grad-and-return-as-inputs-grad/201630
        # it seemed to work for simple cases (including ours as far as we can tell), just being cautious really.
        # this copy seems to slow down the train step by 0.4% (non-compiled) / 0.7% (compiled)
        grad_output = HalfRopeInPlace.apply(grad_output.clone(), freqs_cis, -ctx.coeff)
        return grad_output, None, None

    # we are forced to comment this out in order for compilation to succeed, due to
    # https://github.com/pytorch/pytorch/issues/180284
    # @staticmethod
    # def jvp(ctx, grad_input, *_):
    #     """
    #     none of our code currently uses this, but it gives us forward-mode autodiff support,
    #     which could be useful for implementing consistency training.
    #     """
    #     (freqs_cis,) = ctx.saved_tensors
    #     grad_input = HalfRopeInPlace.apply(grad_input, freqs_cis, ctx.coeff)
    #     return grad_input
    

def make_rot_mat(
    pos: IntTensor,
    dim: int,
    log_theta: float | FloatTensor,
    halfrot: bool,
    angular_velocity: float | FloatTensor = 1.0,
    out_dtype=torch.float32,
) -> FloatTensor:
    """
    log_theta can be a [b, 1, 1] tensor to compute multiple theta simultaneously
    scale can be a [b, 1, 1] tensor to compute multiple theta simultaneously

    scale can be provided for changing the speed of the fastest rotation.
    a smaller value of scale, slows down the fastest rotation.
    """
    assert dim % 2 == 0
    device = pos.device
    precise_dtype = torch.float32 if pos.device.type == 'mps' else torch.float64
    neg_scale = torch.linspace(0, 2 / dim - 1, dim // 2, dtype=precise_dtype, device=device)
    if torch.is_tensor(log_theta):
        assert log_theta.ndim >= 3
        assert log_theta.size(-1) == 1
        assert log_theta.size(-2) == 1
    if torch.is_tensor(angular_velocity):
        assert angular_velocity.ndim >= 3
        assert angular_velocity.size(-1) == 1
        assert angular_velocity.size(-2) == 1
    log_omega: FloatTensor = neg_scale * log_theta
    omega = log_omega.exp()
    angle = pos.unsqueeze(-1) * omega * angular_velocity

    cos = angle.cos().type(out_dtype)
    sin = angle.sin().type(out_dtype)
    if halfrot:
        rotmat = torch.stack(
            [
                cos,
                sin,
            ],
            dim=-1,
        )
    else:
        rotmat = torch.stack(
            [
                cos,
                -sin,
                sin,
                cos,
            ],
            dim=-1,
        ).unflatten(-1, (2, 2))
    return rotmat

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = nn.Linear(2, 2, bias=False)

    def forward(self, x: FloatTensor, rotmat: FloatTensor) -> FloatTensor:
        x = self.lin(x)
        HalfRopeInPlace.apply(
            x.unflatten(-1, ((-1, 2))),
            rotmat,
            -1,
        )
        return x


@dataclass
class Args:
    global_rank: int
    world_size: int

    compile: bool
    "compile the peer model to reproduce the very different grad output."

    distributed: bool
    """
    use FSDP2 to shard or replicate model.
    NOTE: reproduces fine on single-GPU without distributing the model.
          I just included this mode because the program in which the bug appeared originally
          used FSDP2, so I wanted a way to reproduce FSDP2's mixed-precision hook in case that
          turned out to be relevant to the compiler's decisions.
    """

    shard: bool
    "[only relevant when using FSDP2] False = shard, True = replicate"

    @staticmethod
    def get_parser() -> ArgumentParser:
        parser = ArgumentParser()
        parser.add_argument("--compile", action="store_true", help="compile the peer model to reproduce the very different grad output.")
        parser.add_argument("--distributed", action="store_true", help="use FSDP2 to shard or replicate model.")
        parser.add_argument("--shard", action="store_true", help="[only relevant when using FSDP2] False = shard, True = replicate")
        return parser
    
    @staticmethod
    def from_namespace(namespace: Namespace) -> Args:
        global_rank=int(getenv("RANK"))
        world_size=int(getenv("WORLD_SIZE"))
        args = Args(
            global_rank=global_rank,
            world_size=world_size,
            **vars(namespace),
        )
        return args


def main(args: Args):
    device=torch.device('cpu')
    hp_dtype=torch.bfloat16
    seq_len = 8
    y = torch.ones((seq_len,), device=device, dtype=torch.float32)
    x = torch.zeros_like(y)
    vec = torch.stack([y, x], dim=-1)
    target_vec = torch.ones_like(vec, dtype=hp_dtype)

    with torch.device('meta'):
        model0 = Model()
        model1 = Model()
    for mod in (model0, model1):
        mod.to_empty(device=device)
        with no_grad():
            torch.eye(2, out=mod.lin.weight.data)
            mod.lin.weight.mul_(2)

    if args.distributed:
        import torch.distributed as dist
        from contextlib import nullcontext
        from datetime import timedelta
        from torch.distributed.fsdp import MixedPrecisionPolicy, fully_shard
        from torch.distributed._composable.replicate_with_fsdp import replicate
        from torch.distributed.device_mesh import DeviceMesh
        
        dist.init_process_group(
            # backend=backends,
            # backend="nccl",
            # backend="gloo",
            init_method=None,
            world_size=args.world_size,
            rank=args.global_rank,
            # device_id=device,  # NOTE: we were once affected by https://github.com/pytorch/pytorch/issues/147568
            timeout=timedelta(seconds=2),  # 70B takes 66 sec to save.
        )
        assert dist.is_initialized(), "Failed to initialize default process group"
        mesh: list[int] = [0]
        device_mesh = DeviceMesh(
            device_type=device.type,
            mesh=mesh,
            mesh_dim_names=["fsdp"],
        )
        mp_policy = MixedPrecisionPolicy(
            param_dtype=hp_dtype,
            reduce_dtype=torch.float32,
            cast_forward_inputs=True,
        )
        for mod in (model0, model1):
            if args.shard:
                fully_shard(mod, mesh=device_mesh, mp_policy=mp_policy)
            else:
                replicate(mod, mesh=device_mesh, mp_policy=mp_policy)
        mp_ctx = nullcontext()
    else:
        from torch.amp.autocast_mode import autocast
        mp_ctx = autocast(device_type=device.type, dtype=hp_dtype)

    if args.compile:
        model1 = torch.compile(model1, dynamic=False, fullgraph=True)

    with no_grad():
        pos = torch.arange(seq_len, device=device, dtype=torch.int32)
        rotmat: FloatTensor = make_rot_mat(
            pos=pos,
            dim=2,
            log_theta = math.log(4000),
            halfrot=True,
        )

    with mp_ctx:
        out0 = model0(vec, rotmat=rotmat)
        out1 = model1(vec, rotmat=rotmat)

    # assert_close(d, d.new_tensor([[2.0, 0.0], [1.078125, 1.6796875], [-0.83203125, 1.8203125], [-1.9765625, 0.283203125], [-1.3046875, -1.515625], [0.56640625, -1.9140625], [1.921875, -0.55859375], [1.5078125, 1.3125]]))
    assert_close(out0, out1)
    print("fwd outputs matched")

    loss0 = mse_loss(out0, target_vec)
    loss1 = mse_loss(out1, target_vec)
    loss0.backward()
    loss1.backward()
    assert_close(model0.lin.weight.grad, model1.lin.weight.grad)
    # assert_close(model.lin.weight.grad, model.lin.weight.grad.new_tensor([[1.7421875, 0.0], [-0.11669921875, 0.0]]))

    print("model grads matched")

if __name__ == "__main__":
    environ.setdefault("RANK", "0")
    environ.setdefault("LOCAL_RANK", "0")
    environ.setdefault("WORLD_SIZE", "1")
    environ.setdefault("MASTER_ADDR", "127.0.0.1")
    environ.setdefault("MASTER_PORT", "2348")

    parser = Args.get_parser()
    args_untyped: Namespace = parser.parse_args()
    args: Args = Args.from_namespace(args_untyped)
    main(args)
```

### Versions

```
PyTorch version: 2.11.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 26.3.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.6)
CMake version: version 3.31.2
Libc version: N/A

Python version: 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)] (64-bit runtime)
Python platform: macOS-26.3.1-arm64-arm-64bit-Mach-O
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
Is XPU available: False
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
Caching allocator config: N/A

CPU:
Apple M3 Pro

Versions of relevant libraries:
[pip3] numpy==2.4.4
[pip3] torch==2.11.0
[pip3] torchvision==0.26.0
[conda] Could not collect
```

cc @ezyang @gchanan @kadeng @msaroufim @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @amjames @jataylo @azahed98

**Comment by Birch-san** [comment]
here's a more realistic, larger-scale repro (applying RoPE to the heads of a Linear projection).  
it also includes an option to replace the custom autograd kernel with a matmul.  
reproduces on CPU (or MPS if you uncomment that). haven't tried on CUDA, but I expect it reproduces there too because that's how we ran the training that exhibited this divergence.

```
python -m repro2 --compile

# fwd gets this:
Tensor-likes are not close!

Mismatched elements: 2 / 8388608 (0.0%)
Greatest absolute difference: 4.57763671875e-05 at index (3, 117, 5, 73) (up to 1e-05 allowed)
Greatest relative difference: 0.0703125 at index (4, 558, 6, 42) (up to 0.016 allowed)

# if we comment out the fwd assertion in order to compare grads, it gets *much* worse:
AssertionError: Tensor-likes are not close!

Mismatched elements: 327119 / 327680 (99.8%)
Greatest absolute difference: 3.3046875 at index (212, 301) (up to 1e-05 allowed)
Greatest relative difference: 372617.96875 at index (771, 110) (up to 1.3e-06 allowed)

these are all over the place, no similarity at all:

model0.lin.weight.grad
tensor([[ 1.1250,  0.8203,  0.5703,  ..., -0.1338,  0.7852, -0.6016],
        [ 0.0457, -0.3691,  0.7539,  ...,  0.9453,  0.0942,  0.5352],
        [-0.5703, -0.0131,  1.0391,  ...,  1.2031, -0.2930, -0.2031],
        ...,
        [-0.2207, -0.2754, -0.0212,  ..., -0.3789,  0.7734, -0.4238],
        [ 1.2188,  0.1689,  0.0525,  ..., -0.1602, -0.0259, -0.3066],
        [ 0.2256,  0.3867, -0.2412,  ...,  0.5195,  1.0547,  0.2949]])
model1.lin.weight.grad
tensor([[ 0.1553, -0.0315,  0.0258,  ...,  0.1895, -0.1689, -0.0923],
        [ 0.1445,  0.2070,  0.1523,  ...,  0.1035, -0.1206,  0.1001],
        [-0.0288, -0.2559,  0.2676,  ..., -0.2334, -0.1826, -0.0228],
        ...,
        [-0.2393, -0.1572, -0.2715,  ..., -0.4629,  0.6719, -0.5234],
        [ 1.1719,  0.1187,  0.0996,  ..., -0.2422, -0.1699, -0.3379],
        [ 0.4062,  0.4180, -0.2314,  ...,  0.4902,  1.0391,  0.2520]])

model0.lin.weight.grad - model1.lin.weight.grad
tensor([[ 0.9697,  0.8518,  0.5446,  ..., -0.3232,  0.9541, -0.5093],
        [-0.0989, -0.5762,  0.6016,  ...,  0.8418,  0.2148,  0.4351],
        [-0.5415,  0.2427,  0.7715,  ...,  1.4365, -0.1104, -0.1803],
        ...,
        [ 0.0186, -0.1182,  0.2502,  ...,  0.0840,  0.1016,  0.0996],
        [ 0.0469,  0.0503, -0.0471,  ...,  0.0820,  0.1440,  0.0312],
        [-0.1807, -0.0312, -0.0098,  ...,  0.0293,  0.0156,  0.0430]])

```

now I'll demonstrate that an equivalent matmul implementation (via matmul instead of half-matmul in-place autograd kernel) compiles far better.

```
# first demonstrate that the custom kernel is basically equivalent to a matmul
python -m repro2 --model1-matmul

# forward inputs are… somewhat similar.
Mismatched elements: 183644 / 8388608 (2.2%)
Greatest absolute difference: 72.0 at index (4, 746, 2, 76) (up to 1e-05 allowed)
Greatest relative difference: inf at index (0, 182, 6, 85) (up to 0.016 allowed)

# if I comment out the fwd assertion we can check bwd, but it's unsurprising for bwd to be cooked when fwd is cooked
Mismatched elements: 76850 / 327680 (23.5%)
Greatest absolute difference: 0.015625 at index (120, 41) (up to 1e-05 allowed)
Greatest relative difference: 490.10205078125 at index (585, 249) (up to 1.3e-06 allowed)
```

```
# next demonstrate that if we turned both models into matmul, they'd match in eager (i.e. we trust the trainer)
python -m repro2 --model0-matmul --model1-matmul

fwd outputs matched
model grads matched
```

```
# if we turned both models into matmul, what happens if we compile one:
python -m repro2 --model0-matmul --model1-matmul --compile

# forward inputs from eager vs compiled matmul are… about as similar as eager matmul vs eager kernel
AssertionError: Tensor-likes are not close!
Mismatched elements: 183663 / 8388608 (2.2%)
Greatest absolute difference: 72.0 at index (4, 746, 2, 76) (up to 1e-05 allowed)
Greatest relative difference: 11392.0 at index (4, 558, 6, 42) (up to 0.016 allowed)

# if I comment out the fwd assertion we can check bwd:
AssertionError: Tensor-likes are not close!

Mismatched elements: 68254 / 327680 (20.8%)
Greatest absolute difference: 0.015625 at index (285, 122) (up to 1e-05 allowed)
Greatest relative difference: 186.98291015625 at index (113, 181) (up to 1.3e-06 allowed)

# so compiling a typical matmul still exhibits *huge* numeric differences; dunno if that's the ballpark we expect, but it's much better than the compilation difference on my compiled autograd kernel.
```

Conclusion:  
a typical matmul can exhibit fairly different numerics under compilation (e.g. 2% fwd, 20% bwd compounding [admittedly disadvantaged by fwd error]).  
but the in-place autograd kernel is exhibiting **much** worse differences under compilation (0.0% fwd diff yet 99.8% bwd diff). I think it's a problem different than numerics.

`repro2.py`  
```python
from __future__ import annotations
from argparse import ArgumentParser, Namespace
from dataclasses import dataclass
from abc import ABC, abstractmethod
from typing_extensions import override
import torch
from torch import FloatTensor, IntTensor, Tensor, nn, no_grad
from torch.testing import assert_close
from torch.nn.functional import mse_loss
from os import environ, getenv
import math
from typing import Literal

# based on k-diffusion's _apply_rotary_emb_inplace
# MIT-licensed, by Katherine Crowson
# https://github.com/crowsonkb/k-diffusion/blob/21d12c91ad4550e8fcf3308ff9fe7116b3f19a08/k_diffusion/models/image_transformer_v2.py#L188C5-L188C30
def _halfrope_inplace(t: Tensor, freqs_cis: Tensor, coeff: Literal[1, -1]) -> None:
    cos, sin = freqs_cis.unbind(-1)
    ty, tx = t.unbind(-1)
    # TODO: if this is currently in half-precision, should we do the addition in float32, to reduce accumulation error?
    ty_roped = ty.mul(cos).addcmul_(sin, tx, value=coeff)
    tx_roped = tx.mul(cos).addcmul_(sin, ty, value=-coeff)
    ty.copy_(ty_roped)
    tx.copy_(tx_roped)


# based on k-diffusion's ApplyRotaryEmbeddingInplace,
# MIT-licensed, by Katherine Crowson
# https://github.com/crowsonkb/k-diffusion/blob/21d12c91ad4550e8fcf3308ff9fe7116b3f19a08/k_diffusion/models/image_transformer_v2.py#L202
class HalfRopeInPlace(torch.autograd.Function):
    # we don't currently use vmap, but maybe it will enable compile to fuse QK rope apply into flex attn operations?
    # benchmark suggests that enabling this didn't incur any additional cold-start time, so I guess it's lazy.
    generate_vmap_rule = True

    @staticmethod
    def forward(t: Tensor, freqs_cis: Tensor, coeff: Literal[1, -1] = -1):
        "NOTE: passing the coeff arg -1 explicitly gives better compiled performance than relying on arg defaulting"
        _halfrope_inplace(t, freqs_cis, coeff=coeff)
        return t

    @staticmethod
    def setup_context(ctx, inputs, output):
        t, freqs_cis, coeff = inputs
        # mark t as dirty because we will modify it in-place. this ensures backward() will be called.
        ctx.mark_dirty(t)
        ctx.save_for_backward(freqs_cis)
        # required for jvp, probably
        ctx.save_for_forward(freqs_cis)
        ctx.coeff = coeff

    @staticmethod
    def backward(ctx, grad_output):
        (freqs_cis,) = ctx.saved_tensors
        # clone made because we must "NEVER" modify grad-w.r.t-input in-place.
        # https://pytorch.org/docs/main/notes/extending.html#how-to-use
        # https://discuss.pytorch.org/t/is-it-safe-to-modify-outputs-grad-and-return-as-inputs-grad/201630
        # it seemed to work for simple cases (including ours as far as we can tell), just being cautious really.
        # this copy seems to slow down the train step by 0.4% (non-compiled) / 0.7% (compiled)
        grad_output = HalfRopeInPlace.apply(grad_output.clone(), freqs_cis, -ctx.coeff)
        return grad_output, None, None

    # we are forced to comment this out in order for compilation to succeed, due to
    # https://github.com/pytorch/pytorch/issues/180284
    # @staticmethod
    # def jvp(ctx, grad_input, *_):
    #     """
    #     none of our code currently uses this, but it gives us forward-mode autodiff support,
    #     which could be useful for implementing consistency training.
    #     """
    #     (freqs_cis,) = ctx.saved_tensors
    #     grad_input = HalfRopeInPlace.apply(grad_input, freqs_cis, ctx.coeff)
    #     return grad_input
    

def make_rot_mat(
    pos: IntTensor,
    dim: int,
    log_theta: float | FloatTensor,
    halfrot: bool,
    angular_velocity: float | FloatTensor = 1.0,
    out_dtype=torch.float32,
) -> FloatTensor:
    """
    log_theta can be a [b, 1, 1] tensor to compute multiple theta simultaneously
    scale can be a [b, 1, 1] tensor to compute multiple theta simultaneously

    scale can be provided for changing the speed of the fastest rotation.
    a smaller value of scale, slows down the fastest rotation.
    """
    assert dim % 2 == 0
    device = pos.device
    precise_dtype = torch.float32 if pos.device.type == 'mps' else torch.float64
    neg_scale = torch.linspace(0, 2 / dim - 1, dim // 2, dtype=precise_dtype, device=device)
    if torch.is_tensor(log_theta):
        assert log_theta.ndim >= 3
        assert log_theta.size(-1) == 1
        assert log_theta.size(-2) == 1
    if torch.is_tensor(angular_velocity):
        assert angular_velocity.ndim >= 3
        assert angular_velocity.size(-1) == 1
        assert angular_velocity.size(-2) == 1
    log_omega: FloatTensor = neg_scale * log_theta
    omega = log_omega.exp()
    angle = pos.unsqueeze(-1) * omega * angular_velocity

    cos = angle.cos().type(out_dtype)
    sin = angle.sin().type(out_dtype)
    if halfrot:
        rotmat = torch.stack(
            [
                cos,
                sin,
            ],
            dim=-1,
        )
    else:
        rotmat = torch.stack(
            [
                cos,
                -sin,
                sin,
                cos,
            ],
            dim=-1,
        ).unflatten(-1, (2, 2))
    return rotmat

class AbstractModel(nn.Module, ABC):
    def __init__(
        self,
        in_dim: int,
        head_dim: int,
        heads: int,
    ):
        self.call_super_init = True
        super().__init__()
        self.heads = heads
        self.lin = nn.Linear(in_dim, head_dim*heads, bias=False)

    @abstractmethod
    def forward(self, x: FloatTensor, rotmat: FloatTensor) -> FloatTensor: ...
    
class HalfRotModel(AbstractModel):
    @override
    def forward(self, x: FloatTensor, rotmat: FloatTensor) -> FloatTensor:
        x = self.lin(x)
        x = x.unflatten(-1, (self.heads, -1))
        HalfRopeInPlace.apply(
            x.unflatten(-1, ((-1, 2))),
            rotmat.unsqueeze(-3), # broadcast over all heads
            -1,
        )
        return x
    
class FullRotModel(AbstractModel):
    @override
    def forward(self, x: FloatTensor, rotmat: FloatTensor) -> FloatTensor:
        x = self.lin(x)
        x = x.unflatten(-1, (self.heads, -1))
        x = x.unflatten(-1, ((-1, 2))).unsqueeze(-2) @ rotmat.unsqueeze(-4).mT
        return x.flatten(start_dim=-3)

@dataclass
class Args:
    global_rank: int
    world_size: int

    compile: bool
    "compile the peer model to reproduce the very different grad output."

    distributed: bool
    """
    use FSDP2 to shard or replicate model.
    NOTE: reproduces fine on single-GPU without distributing the model.
          I just included this mode because the program in which the bug appeared originally
          used FSDP2, so I wanted a way to reproduce FSDP2's mixed-precision hook in case that
          turned out to be relevant to the compiler's decisions.
    """

    shard: bool
    "[only relevant when using FSDP2] False = shard, True = replicate"

    model0_matmul: bool
    "whether model instance 0 should use a typical matmul. if unspecified, uses a custom autograd kernel for reading [cos, sin] rows as [[cos, -sin], [sin, cos]] without materializing the matrix (matmul is implemented in parts)"

    model1_matmul: bool
    "whether model instance 1 should use a typical matmul. if unspecified, uses a custom autograd kernel for reading [cos, sin] rows as [[cos, -sin], [sin, cos]] without materializing the matrix (matmul is implemented in parts)"

    @staticmethod
    def get_parser() -> ArgumentParser:
        parser = ArgumentParser()
        parser.add_argument("--compile", action="store_true", help="compile the peer model to reproduce the very different grad output.")
        parser.add_argument("--distributed", action="store_true", help="use FSDP2 to shard or replicate model.")
        parser.add_argument("--shard", action="store_true", help="[only relevant when using FSDP2] False = shard, True = replicate")
        parser.add_argument("--model0-matmul", action="store_true", help="whether model instance 0 should use a typical matmul. if unspecified, uses a custom autograd kernel for reading [cos, sin] rows as [[cos, -sin], [sin, cos]] without materializing the matrix (matmul is implemented in parts)")
        parser.add_argument("--model1-matmul", action="store_true", help="whether model instance 1 should use a typical matmul. if unspecified, uses a custom autograd kernel for reading [cos, sin] rows as [[cos, -sin], [sin, cos]] without materializing the matrix (matmul is implemented in parts)")
        return parser
    
    @staticmethod
    def from_namespace(namespace: Namespace) -> Args:
        global_rank=int(getenv("RANK"))
        world_size=int(getenv("WORLD_SIZE"))
        args = Args(
            global_rank=global_rank,
            world_size=world_size,
            **vars(namespace),
        )
        return args


def main(args: Args):
    device=torch.device('cpu')
    # device=torch.device('mps')
    hp_dtype=torch.bfloat16
    bs = 8
    seq_len = 1024

    gen = torch.Generator(device=device)

    in_dim=320
    head_dim=128
    heads=8

    with torch.device('meta'):
        model0 = (FullRotModel if args.model0_matmul else HalfRotModel)(in_dim=in_dim, head_dim=head_dim, heads=heads)
        model1 = (FullRotModel if args.model1_matmul else HalfRotModel)(in_dim=in_dim, head_dim=head_dim, heads=heads)
    for mod in (model0, model1):
        mod.to_empty(device=device)
        with no_grad():
            mod.lin.weight.normal_(std=mod.lin.in_features, generator=gen.manual_seed(42))

    if args.distributed:
        import torch.distributed as dist
        from contextlib import nullcontext
        from datetime import timedelta
        from torch.distributed.fsdp import MixedPrecisionPolicy, fully_shard
        from torch.distributed._composable.replicate_with_fsdp import replicate
        from torch.distributed.device_mesh import DeviceMesh

        dist.init_process_group(
            # gloo required for dcp async save, "AssertionError: A CPU backend must be enabled for async save; try initializing process group with 'cpu:gloo,cuda:nccl'"
            # but removed for now because it interferes with dist.gather_object() in generate_samples(),
            # with: "Inplace update to inference tensor outside InferenceMode".
            # if you need gloo back, we could make the inference_mode context more granular to exclude gather_object
            # backend=backends,
            # backend="nccl",
            # backend="gloo",
            init_method=None,
            world_size=args.world_size,
            rank=args.global_rank,
            # device_id=device,  # NOTE: we were once affected by https://github.com/pytorch/pytorch/issues/147568
            timeout=timedelta(seconds=2),  # 70B takes 66 sec to save.
        )
        assert dist.is_initialized(), "Failed to initialize default process group"
        mesh: list[int] = [0]
        device_mesh = DeviceMesh(
            device_type=device.type,
            mesh=mesh,
            mesh_dim_names=["fsdp"],
        )
        mp_policy = MixedPrecisionPolicy(
            param_dtype=hp_dtype,
            reduce_dtype=torch.float32,
            cast_forward_inputs=True,
        )
        for mod in (model0, model1):
            if args.shard:
                fully_shard(mod, mesh=device_mesh, mp_policy=mp_policy)
            else:
                replicate(mod, mesh=device_mesh, mp_policy=mp_policy)
        mp_ctx = nullcontext()
    else:
        from torch.amp.autocast_mode import autocast
        mp_ctx = autocast(device_type=device.type, dtype=hp_dtype)

    if args.compile:
        model1 = torch.compile(model1, dynamic=False, fullgraph=True)

    vec0 = torch.randn((bs, seq_len, in_dim), device=device, dtype=hp_dtype, generator=gen.manual_seed(43))
    target_vec0 = torch.randn((bs, seq_len, heads, head_dim), device=device, dtype=hp_dtype, generator=gen.manual_seed(44))
    vec1 = vec0.clone()
    target_vec1 = target_vec0.clone()

    with no_grad():
        pos = torch.arange(seq_len, device=device, dtype=torch.int32)
        halfrot: FloatTensor = make_rot_mat(
            pos=pos,
            dim=head_dim,
            log_theta = math.log(4000),
            halfrot=True,
        )
        cos, sin = halfrot.unbind(-1)
        fullrot = torch.stack(
            [
                cos,
                -sin,
                sin,
                cos,
            ],
            dim=-1,
        ).unflatten(-1, (2, 2))

    with mp_ctx:
        out0 = model0(vec0, rotmat=fullrot if args.model0_matmul else halfrot)
        out1 = model1(vec1, rotmat=fullrot if args.model1_matmul else halfrot)

    assert_close(out0, out1)
    print("fwd outputs matched")
    loss0 = mse_loss(out0, target_vec0)
    loss1 = mse_loss(out1, target_vec1)
    loss0.backward()
    loss1.backward()
    assert_close(model0.lin.weight.grad, model1.lin.weight.grad)
    print("model grads matched")

if __name__ == "__main__":
    environ.setdefault("RANK", "0")
    environ.setdefault("LOCAL_RANK", "0")
    environ.setdefault("WORLD_SIZE", "1")
    environ.setdefault("MASTER_ADDR", "127.0.0.1")
    environ.setdefault("MASTER_PORT", "2348")

    parser = Args.get_parser()
    args_untyped: Namespace = parser.parse_args()
    args: Args = Args.from_namespace(args_untyped)
    main(args)
```

**Comment by tiakavousi** [comment]
I've been digging into this and have a hypothesis. I'd really appreciate some guidance on whether I'm looking in the right place or not :)

It seems, Dynamo doesn't propagate `ctx.mark_dirty(...)` for custom `autograd.Functions`, and that's what makes the backward silently disappear

**What led me there:**
- I expected to find mark_dirty handling somewhere under `torch/_dynamo/`, but it's not there at all. `AutogradFunctionContextVariable` handles save_for_backward and mark_non_differentiable, but `ctx.mark_dirty(t)` seems to be traced as a plain attribute set and never reaches the HOP.
- The synthesized `ApplyTemplate` in `torch/_functorch/autograd_function.py (AutogradFunctionApply.__call__)` replays `mark_non_differentiable` in `setup_context`, but never calls `ctx.mark_dirty`.
- It only misbehaves when the caller discards `.apply()`'s return value and relies on in-place aliasing `(Fn.apply(view); return x)`. If I instead use the returned tensor, compiled grads match eager exactly.

**Evidence from the captured graphs (`repro.py` 👆, CPU, torch 2.11.0):**
Dynamo graph: the HOP output is dead, and the graph returns the pre-rope tensor:
```python
x = linear(l_x_, weight)
output = x.unflatten(-1, (-1, 2))                       # view of x
autograd_function_apply(fwd_body_0, bwd_body_0, ...);   # = None (discarded)
return (x,)                                             # pre-rope x
```
AOTAutograd backward graph: only the linear's mm, the inverse-RoPE is gone:
```python
def forward(self, convert_element_type, tangents_1):
      mm_1 = mm(permute(tangents_1), convert_element_type)   # linear bwd only
      return (convert_element_type_6, None, None)            # rope-inverse MISSING
```

The forward graph does apply the rope (via select_scatter), so the forward value is correct, only the backward loses it. this is still unfixed on main branch.

To reproduce the graphs above + the control that isolates the trigger:
```python
TORCH_LOGS=graph_code python repro.py --compile   # the Dynamo graph
TORCH_LOGS=aot_graphs  python repro.py --compile   # the AOTAutograd fwd/bwd graphs

# Changing the model from (rely on in-place aliasing):
HalfRopeInPlace.apply(x.unflatten(-1, (-1, 2)), rotmat, -1)
return x

# to use the returned tensor instead:
x2 = HalfRopeInPlace.apply(x.unflatten(-1, (-1, 2)), rotmat, -1)
return x2.flatten(-2)

# makes compiled grads match eager exactly.
```

**A few questions:**
1. Does the missing-mark_dirty-propagation hypothesis sound right?
2. Is "mutate an input in-place + mark_dirty + discard .apply()'s return value" a supported pattern under `torch.compile`, or should it at least error instead of silently producing wrong grads?

Thanks

**Comment by Birch-san** [comment]
I suspect that hypothesis is correct; mark_dirty is obscure enough to have been missed until now, and it would account for why the values are not in the right ballpark at all.

would be good if pytorch team can confirm.

**Comment by anijain2305** [comment]
I can reproduce this on `2.13.0a0+git4b02cd4` with a minimized version of the pattern. This does not look Inductor-specific: `backend="eager"`, `backend="aot_eager"`, and `backend="inductor"` all produce the wrong gradient when the returned tensor from `.apply()` is discarded.

Minimized repro:

```python
import torch


class TimesThreeInplace(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        x.mul_(3)
        ctx.mark_dirty(x)
        return x

    @staticmethod
    def backward(ctx, grad):
        return grad * 3


def fn(w, use_return):
    x = torch.ones(2, 2)
    y = x @ w
    if use_return:
        y = TimesThreeInplace.apply(y)
    else:
        TimesThreeInplace.apply(y)
    return y.sum()


def grad_for(compiled, use_return):
    torch._dynamo.reset()
    w = torch.eye(2, requires_grad=True)
    f = torch.compile(fn, fullgraph=True, dynamic=False) if compiled else fn
    loss = f(w, use_return)
    loss.backward()
    return loss.detach(), w.grad


eager_loss, eager_grad = grad_for(compiled=False, use_return=False)
compiled_loss, compiled_grad = grad_for(compiled=True, use_return=False)
returned_loss, returned_grad = grad_for(compiled=True, use_return=True)

print("discarded return:")
print("eager loss:", eager_loss)
print("compiled loss:", compiled_loss)
print("eager grad:", eager_grad)
print("compiled grad:", compiled_grad)

print("used return:")
print("compiled grad:", returned_grad)

torch.testing.assert_close(eager_loss, compiled_loss)
assert not torch.allclose(eager_grad, compiled_grad)
torch.testing.assert_close(eager_grad, returned_grad)
```

Output:

```text
discarded return:
eager loss: tensor(12.)
compiled loss: tensor(12.)
eager grad: tensor([[6., 6.],
        [6., 6.]])
compiled grad: tensor([[2., 2.],
        [2., 2.]])
used return:
compiled grad: tensor([[6., 6.],
        [6., 6.]])
```

This matches the missing-`mark_dirty` propagation hypothesis. The Dynamo `autograd.Function` HOP tracks/replays `save_for_backward` and `mark_non_differentiable`, but I do not see dirty-input metadata passed to `AutogradFunctionApply`, and the generated `ApplyTemplate.setup_context` only replays `mark_non_differentiable`.

(Analysis done by Codex.)

Human comment - This is definitely related to `mark_dirty`. I am working a fix.

**Comment by anijain2305** [comment]
https://github.com/pytorch/pytorch/pull/184267 should fix this, but I am waiting for CI.

mark_dirty was never supported in Dynamo. So if it was passing earlier in <2.10, it must be because Dynamo was "fortunately" graph breaking on your testcase earlier, causing the autograd.Function object to be compiled in a separate frame. With the autograd.Function refactor last Nov, we have increased the scope of whats supported in autograd.Function, and might have exposed this latent bug.

Thanks for opening this issue, and the narrowing it down for us. This is a critical bug.
