### ISSUE TITLE
training with Multi-GPU hangs

### ISSUE THREAD

**Issue by houweidong** [pytorch/pytorch#18431]
when i train my code with single GPU , it's ok, when i train with 0 and any one of [5,6,7,8,9] display cards, it's ok, but when i train with 0 and one card  in [1,2,3,4], it hangs!!!  and when i train with mxnet with multi GPU, it's ok!

 - PyTorch Version (0.4.1):
 - OS (ubuntu 18.04):
 - How you installed PyTorch (`pip`):
 - Python version: 3.5
 - CUDA/cuDNN version:9.0
 - GPU models and configuration:10 1080Ti
 - Any other relevant information: run the code in docker

the NVIDIA-SMI shows like:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.116                Driver Version: 390.116                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:1A:00.0  On |                  N/A |
| 23%   33C    P8    10W / 250W |    207MiB / 11178MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:1B:00.0 Off |                  N/A |
| 23%   26C    P8     8W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:1C:00.0 Off |                  N/A |
| 23%   29C    P8     9W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:1D:00.0 Off |                  N/A |
| 23%   26C    P8     8W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  Off  | 00000000:1E:00.0 Off |                  N/A |
| 23%   28C    P8     8W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  Off  | 00000000:3D:00.0 Off |                  N/A |
| 31%   54C    P2    79W / 250W |    661MiB / 11178MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  Off  | 00000000:3E:00.0 Off |                  N/A |
| 27%   48C    P2    74W / 250W |    633MiB / 11178MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  Off  | 00000000:3F:00.0 Off |                  N/A |
| 23%   26C    P8     8W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   8  GeForce GTX 108...  Off  | 00000000:40:00.0 Off |                  N/A |
| 23%   28C    P8     8W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   9  GeForce GTX 108...  Off  | 00000000:41:00.0 Off |                  N/A |
| 23%   27C    P8     9W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1567      G   /usr/lib/xorg/Xorg                           110MiB |
|    0      2780      G   /usr/bin/gnome-shell                          72MiB |
|    0      2784      G   /opt/teamviewer/tv_bin/TeamViewer             21MiB |
|    5      6981      C   /usr/bin/python3.5                           649MiB |
|    6      6981      C   /usr/bin/python3.5                           621MiB |
```
the 5,6 are the hanging cards

**Comment by fmassa** [comment]
I believe we used to support only 8 GPUs in a single machine, not sure that this changed since then.

cc @mrshenli

**Comment by mrshenli** [comment]
I am not aware of that limitation. cc @pietern

**Comment by soumith** [comment]
it's likely this is because the gpus dont have p2p access. describe more what your training code looks like -- do you use DataParallel or DistributedDataParallel?

**Comment by houweidong** [comment]
Thanks for you reply. I have solved the problem, it's the opened ACS of the PLX PCI-e switch caused the problem, so after i closed the switch, it's ok. Just like [here](https://www.supermicro.org.cn/support/faqs/faq.cfm?faq=20732)
