### ISSUE TITLE
DataParallel hangs on more than 2 GPUs/Cannot kill process either

### ISSUE THREAD

**Issue by Msabih** [pytorch/pytorch#18439]
I trained UNet model with pytorch dataparallel and with 2 GPUs, it works okay but as soon as I go to 3 or 4, the DataParallel hangs badly. I have to ask admin of the server to restart the machine as nothing else works. 

1. Use https://github.com/jvanvugt/pytorch-unet
2. Get images of 360p and use sufficiently higher batch_size
3.  Use Parallel.

## Environment
PyTorch version: 1.1.0a0+c297f26
Is debug build: No
CUDA used to build PyTorch: 9.2.88

OS: CentOS Linux release 7.6.1810 (Core) 
GCC version: (GCC) 7.1.0
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 410.78
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.14.6
[pip3] numpydoc==0.8.0
[pip3] pytorch-ignite==0.1.2
[pip3] torch==1.1.0a0+c297f26
[pip3] torchfile==0.1.0
[pip3] torchnet==0.0.4
[pip3] torchvision==0.2.2.post3
[conda] _tflow_190_select         0.0.3                       mkl  
[conda] cuda92                    1.0                           0    pytorch
[conda] magma-cuda92              2.4.0                         1    pytorch
[conda] mkl                       2019.3                      199  
[conda] mkl-include               2019.3                      199  
[conda] mkl-service               1.1.2                    py36_3  
[conda] mkl_fft                   1.0.2               np114py36_6    intel
[conda] mkl_random                1.0.1               np114py36_6    intel
[conda] mxnet-cu92mkl             1.3.0.post0              pypi_0    pypi
[conda] pytorch-ignite            0.1.2                    pypi_0    pypi
[conda] torch                     1.1.0a0+c297f26          pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchvision               0.2.2.post3              pypi_0    pypi

**Comment by soumith** [comment]
@Msabih that sounds like a hardware issue, especially wrt " I have to ask admin of the server to restart the machine as nothing else works."

**Comment by Msabih** [comment]
@Soumith
Thanks for the reply

Nothing else works meaning all the ways to kill the process dont work. That has been a fairly common issue with pytorch's parallel data loader when it hangs, the process cannot be killed however, I read that in the most recent version, the interrupt handling was improved so I expected atleast the Ctrl + C or the kill -9 PID to work so I dont have to bother to ask admin to reboot when my process stucks.

Anyways I have updated my cuda tool-kit and drivers to 10.0, I will write back if the problem persists or not.

**Comment by ezyang** [comment]
Closing this for now, please reopen if the issue persists.

**Comment by Msabih** [comment]
@ezyang The issue persists. The problem is not just with DataParallel with gpus more than 2. Looks like the DataParallel itself is buggy. 

The biggest problem that we have is that if torch crashes which happens more with DataParalllel, the python process cant be killed. It either becomes an R process thats stuck or a D process.

The GPUs show in nvidia-smi as being free but the python process that crashes is not being killed. 

As a result, doing cuda.init() hangs indefinitely. The only way to make usable is to reboot it.

We are using pytorch on a university server and its a big problem to restart the server.

Could you please give me some guidelines on isolating the issue and reporting it back ?

**Comment by Tsingularity** [comment]
I also come across the same issue. When this happens, you cannot kill the process except rebooting the whole server. It's really terrible. Hope someone could give some guidelines on how to address this issue.

**Comment by Msabih** [comment]
Hi, I solved this issue by updating the BIOS. To check, if the problem is with your BIOS, could you run cuda multiple devices test.

**Comment by IINemo** [comment]
I ve just hang two servers by using pytorch (version 1.0.0) DataParallel

**Comment by ezyang** [comment]
@IINemo please file a bug with more detailed description of what you were doing. Also, the most recent version of PyTorch is 1.2.0, so please also try with that too.

**Comment by IINemo** [comment]
> @IINemo please file a bug with more detailed description of what you were doing. Also, the most recent version of PyTorch is 1.2.0, so please also try with that too.

Of course, as soon as I manage to reboot these servers that are located in other town =)

**Comment by IINemo** [comment]
> @IINemo please file a bug with more detailed description of what you were doing. Also, the most recent version of PyTorch is 1.2.0, so please also try with that too.

Finally, we managed to do some tests with updated drivers and torch. We did not have any problems with 430 nvidia driver and torch 1.2.
