### ISSUE TITLE
grid_sample cuDNN error

### ISSUE THREAD

**Issue by denkorzh** [pytorch/pytorch#18561]
## 🐛 Bug

cuDNN error `CUDNN_STATUS_EXECUTION_FAILED` when using `grid_sample` method on GPU.

## To Reproduce

```python
import torch
import torch.nn.functional as F
device = torch.device('cuda')
B, C, H, W = 1, 3, 128, 128
x = torch.randn(B, C, H, W, device=device)
flow = torch.tanh(torch.randn(B, H, W, 2, device=device))    
y = F.grid_sample(x, flow)
```
Obtained error message:
```                                      
Traceback (most recent call last):
  File "grid_sample.py", line 7, in <module>
    y = F.grid_sample(x, flow)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2597, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```
## Environment
```
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla P40
Nvidia driver version: 384.145
cuDNN version: /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.0.1.post2
[pip3] torchfile==0.1.0
[pip3] torchvision==0.2.2.post3
[conda] Could not collect
```

**Comment by acheketa** [comment]
Refer to #16935.
Had the same problem and it seems like a version issue.
Roll back to Pytorch 1.0.0.

**Comment by denkorzh** [comment]
@acheketa Thanks, now it works

**Comment by krumo** [comment]
i use pytorch 1.1.0.dev20190414, the same problem.
