### ISSUE TITLE
THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=87 error=30 : unknown error

### ISSUE THREAD

**Issue by MeteoRex11** [pytorch/pytorch#18981]
THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=87 error=30 : unknown error
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    algo.sample(datapath, cfg.STAGE)
  File "C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py", line 238, in sample
    netG, _ = self.load_network_stageII()
  File "C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py", line 110, in load_network_stageII
    netG.cuda()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    param.data = fn(param.data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 162, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at ..\aten\src\THC\THCGeneral.cpp:87

**Comment by MeteoRex11** [comment]
I keep getting the cuda runtime error, even though I ran nvidia-smi , which shows gpu 0 as my GTX 1050

**Comment by peterjc123** [comment]
Could you please try whether it is still a problem for the nightly version?

**Comment by MeteoRex11** [comment]
> Could you please try whether it is still a problem for the nightly version?

I installed the nightly version, now it gives me the following error:

`Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import torch.backends.cudnn as cudnn
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\__init__.py", line 102, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import`

**Comment by peterjc123** [comment]
please downgrade your numpy to 1.13

**Comment by MeteoRex11** [comment]
> please downgrade your numpy to 1.13

Hi. I downgraded to numpy 1.13, and now it is back to the same error as before:

`THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=87 error=30 : unknown error
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    algo.sample(datapath, cfg.STAGE)
  File "C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py", line 238, in sample
    netG, _ = self.load_network_stageII()
  File "C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py", line 110, in load_network_stageII
    netG.cuda()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    param.data = fn(param.data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 162, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at ..\aten\src\THC\THCGeneral.cpp:87`

**Comment by peterjc123** [comment]
Does reducing the batch size help?

**Comment by MeteoRex11** [comment]
> Does reducing the batch size help?

Originally the batch size was 64, but i reduced it to 10, even 2. But still the same error pops up

**Comment by MeteoRex11** [comment]
Also, the nightly build isn't downloading completely. Some sort of HTTP error while downloading the second part of the package (569.8 MB). Could it have something to do with the error?
 
Or could it have something to do with limited GPU memory?

**Comment by MeteoRex11** [comment]
I reinstalled the nightly build, but a new unknown error has popped up:

`Traceback (most recent call last):
  File "main.py", line 77, in <module>
    algo.sample(datapath, cfg.STAGE)
  File "C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py", line 238, in sample
    netG, _ = self.load_network_stageII()
  File "C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py", line 110, in load_network_stageII
    netG.cuda()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 263, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 190, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 190, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 190, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 196, in _apply
    param.data = fn(param.data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 263, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: unknown error`

**Comment by umanwizard** [comment]
Seems like this is resolved (and now you are facing a new issue).

**Comment by Yiyiyimu** [comment]
@umanwizard You can try to downgrade pytorch version to 1.0.0 avoid problems in the title, if you are using 1.0.1 and jupyter.

Referenece: https://forums.fast.ai/t/cuda-runtime-error-30-resnet-not-loading/38556/2

**Comment by HareshMiriyala** [comment]
somehow restarting my machine fixed this issue. using torch v1.1.0

**Comment by PartheshSoni** [comment]
> somehow restarting my machine fixed this issue. using torch v1.1.0

It worked for me too!
