### ISSUE TITLE
RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by MeteoRex11** [pytorch/pytorch#18999]
I had installed CUDA using both conda and the NVIDIA website, and this error vanished at first. But when I restarted my Laptop, it popped up again. 
What can I do?

GPU - NVIDIA GeForce GTX 1050
RAM - 32 GB DDR4
CPU - Core i7 7700HQ

```
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    algo.sample(datapath, cfg.STAGE)
  File "C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py", line 238, in sample
    netG, _ = self.load_network_stageII()
  File "C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py", line 110, in load_network_stageII
    netG.cuda()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 263, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 190, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 190, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 190, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 196, in _apply
    param.data = fn(param.data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 263, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: unknown error
```

**Comment by umanwizard** [comment]
Can you please try asking on the forums: https://discuss.pytorch.org/

**Comment by umanwizard** [comment]
Discussed offline with @soumith and @ezyang , we decided to reopen this.

**Comment by mruberry** [comment]
Is your CUDA still installed properly? Can you, for example, run nvidia-smi? What happens if you try to run some of the CUDA examples (that may have come with your install)?

**Comment by MeteoRex11** [comment]
> Is your CUDA still installed properly? Can you, for example, run nvidia-smi? What happens if you try to run some of the CUDA examples (that may have come with your install)?

I can run nvidia-smi
I haven't run the samples yet, but I have an update for the issue.

If I have Visual Studio Installer open in the background, this error vanishes for some reason

**Comment by mruberry** [comment]
That is bizarre. Please update if you run the samples, that would be helpful to confirm there is a build issue, not a CUDA installation issue.

**Comment by Jonas1312** [comment]
Same issue I think #20635

**Comment by gauravkoradiya** [comment]
same issue

**Comment by elronbandel** [comment]
I had exactly the same issue. i got it fixed  by installing the exact pytorch version for my 10.1 CUDA with:
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
instead of installing it with the installtion snippet generated for me by pytorch website:
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch

**Comment by ezyang** [comment]
@soumith Who can update the website downloader box?  This seems easy
enough to fix.

Excerpts from elronbandel's message of 2019-06-17 13:50:16 -0700:
> I had exactly the same issue. i got it fixed  by installing the exact pytorch version for my 10.1 CUDA with:
> conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
> instead of installing it with the installtion snippet generated for me by pytorch website:
> conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
>

**Comment by it-is-a-username** [comment]
Same issue. What's more puzzling, when I type
`import torch
torch.rand(1).cuda()`
it works. So I guess the versions of cudnn, CUDA and pytorch are compatible but there is something else wrong.

**Comment by LNoving** [comment]
> I had exactly the same issue. i got it fixed by installing the right pytorch version for my 10.1 CUDA with:
> `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch`
> instead of installing it with the installtion snippet generated for me by pytorch website:
> `conda install pytorch torchvision cudatoolkit=10.0 -c pytorch`

Thank you so much for this solution. I know the problem must have something to do with the cuda version and pytorch version, however, I don't know how to fix it. Thank you again.

**Comment by abuelgasimsaadeldin** [comment]
Hi I am facing this issue after running a very big program on my GPU which caused it to crash my laptop and I have to forcefully shut it down, after restarting every time I am using my GPU even on not so computationally expensive tasks which I could run normally before, I receive this error. I am really afraid that it is an internal problem. Any idea how I could go about in troubleshooting this?
