### ISSUE TITLE
Install Issue: torch/_C.so looks for two versions of cuda

### ISSUE THREAD

**Issue by wk910930** [pytorch/pytorch#1941]
Hi,

When I am trying to `import torch`, it said `ImportError: libcudart.so.7.5: cannot open shared object file`. However, when I run the command `ldd /usr/local/lib/python2.7/dist-packages/torch/_C.so`, it shows

```shell
...
linux-vdso.so.1 =>  (0x00007ffcc25f4000)
libshm.so => /usr/local/lib/python2.7/dist-packages/torch/lib/libshm.so (0x00007fa881131000)
libcudart.so.8.0 => /usr/local/cuda/lib64/libcudart.so.8.0 (0x00007fa880eca000)
libnccl.so.1 => /usr/local/lib/libnccl.so.1 (0x00007fa87eead000)
libTH.so.1 => /usr/local/lib/python2.7/dist-packages/torch/lib/libTH.so.1 (0x00007fa87e8e2000)
...
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa86ed3f000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa86eb37000)
libcudart.so.7.5 => not found
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa86e830000)
libopenblas.so.0 => /usr/lib/libopenblas.so.0 (0x00007fa86d01d000)
...
```

Somehow it is looking for the libcudart of two different versions (7.5 & 8.0) at the same time! Currently in my machine, there is only cuda-8.0 installed and `/usr/local/cuda` is linking to cuda-8.0, too. I have been confused by this for 3 days.

Someone encountered the same issue?

Thanks!

**Comment by pavanky** [comment]
How did you install PyTorch?

**Comment by wk910930** [comment]
I tried `sudo python setup.py install` and `CUDA_HOME=/usr/local/cuda-8.0 CUDA_BIN_PATH=/usr/local/cuda-8.0/bin CUDNN_LIB_DIR=/opt/library/NVIDIA/cudnn/v6.0_cuda_8.0/lib64 CUDNN_INCLUDE_DIR=/opt/library/NVIDIA/cudnn/v6.0_cuda_8.0/include sudo python setup.py install`, neither worked.

**Comment by pavanky** [comment]
It is possible that some static library being used linked with `_C.so` was from CUDA 7.5.

**Comment by wk910930** [comment]
Really? Is there any way I can clean/fix it?

**Comment by wk910930** [comment]
Problem Solved: Actually, it is the [nccl](https://github.com/NVIDIA/nccl) (which was build with cuda-7.5) that is looking for `libcudart.so.7.5`. Just clean and rebuild nccl with cuda-8.0, and then `sudo python setup.py install`, now it works like a charm!

Thank you @pavanky !

Closing the issue.
