### ISSUE TITLE
Distributed Communication with openmpi fails

### ISSUE THREAD

**Issue by Usama-Zafar** [pytorch/pytorch#20200]
## 🐛 Bug

When trying to run a multi-process training with mpi backend the program fails at communication. Otherwise runs perfectly fine.

## To Reproduce


1. Install CUDA's latest toolkit 10.1 and equivalent CuDNN 7.5.1
2. Install Openmpi v3.1.2 with CUDA support
3. Build / install pytroch from source.
4. Test any communication for a process group with mpi backend.

## Expected behavior

Carry out communication as it would normally. Send / Receive / Reduce operations.


The following error occurs when trying to use reduce function of the distributed class :
```
[g2-nasp:24252] *** An error occurred in MPI_Reduce
[g2-nasp:24252] *** reported by process [1911816193,0]
[g2-nasp:24252] *** on communicator MPI_COMM_WORLD
[g2-nasp:24252] *** MPI_ERR_ROOT: invalid root
[g2-nasp:24252] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[g2-nasp:24252] ***    and potentially your MPI job)
[g2-nasp:24247] 1 more process has sent help message help-mpi-errors.txt / mpi_errors_are_fatal
```

This only seems to be occur when trying to establish communication between two nodes. A different error occurs for send / receive function calls.

I get following errors when trying to use isend / irecv functions of the distributed module:
```
--------------------------------------------------------------------------
[[18472,1],1]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: g9-nasp

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
I am rank:  1  and my tensor value is:  tensor(0., device='cuda:0')
I am rank:  0  and my tensor value is:  tensor(0., device='cuda:0')
Tensor value before receive:  tensor(0., device='cuda:0')
[g9-nasp:12139:0] Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x13011e0000)
==== backtrace ====
    0  /opt/ucx/lib/libucs.so.0(+0x12d68) [0x7f29c32b3d68]
    1  /opt/ucx/lib/libucs.so.0(+0x12f02) [0x7f29c32b3f02]
    2  /lib/x86_64-linux-gnu/libc.so.6(+0x18eb64) [0x7f2a35a60b64]
    3  /opt/ucx/lib/libuct.so.0(uct_mm_ep_am_short+0x88) [0x7f29c2e74e08]
    4  /opt/ucx/lib/libucp.so.0(ucp_tag_send_nb+0x7e) [0x7f29c34dd1ee]
    5  /home/usama/.openmpi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_isend+0x95) [0x7f29c36efc45]
    6  /home/usama/.openmpi/lib/libmpi.so.40(MPI_Isend+0x105) [0x7f2a0d675355]
    7  /home/usama/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so(_ZN4c10d15ProcessGroupMPI4sendERSt6vectorIN2at6TensorESaIS3_EEii+0xee) [0x7f2a26e1ab3e]
    8  /home/usama/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so(+0x654887) [0x7f2a26d5c887]
    9  /home/usama/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so(+0x11f9f6) [0x7f2a268279f6]
   10  python(_PyCFunction_FastCallDict+0x154) [0x55649c111744]
   11  python(+0x19857e) [0x55649c19857e]
   12  python(_PyEval_EvalFrameDefault+0x30a) [0x55649c1bd38a]
   13  python(+0x1918e4) [0x55649c1918e4]
   14  python(+0x192771) [0x55649c192771]
   15  python(+0x198505) [0x55649c198505]
   16  python(_PyEval_EvalFrameDefault+0x10c7) [0x55649c1be147]
   17  python(+0x19253b) [0x55649c19253b]
   18  python(+0x198505) [0x55649c198505]
   19  python(_PyEval_EvalFrameDefault+0x30a) [0x55649c1bd38a]
   20  python(PyEval_EvalCodeEx+0x329) [0x55649c193289]
   21  python(PyEval_EvalCode+0x1c) [0x55649c19401c]
   22  python(+0x2163c4) [0x55649c2163c4]
   23  python(PyRun_FileExFlags+0xa1) [0x55649c2167c1]
   24  python(PyRun_SimpleFileExFlags+0x1c3) [0x55649c2169c3]
   25  python(Py_Main+0x613) [0x55649c21a4b3]
   26  python(main+0xee) [0x55649c0e302e]
   27  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f2a358f3b97]
   28  python(+0x1c3e0e) [0x55649c1c3e0e]
===================
[g9-nasp:12139:0] Process frozen...
[g9-nasp:12134] 1 more process has sent help message help-mpi-btl-base.txt / btl:no-nics
[g9-nasp:12134] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

## Environment
```
PyTorch version: 1.1.0a0+8cd6d2f                                                                                  
Is debug build: No                                                                                                
CUDA used to build PyTorch: 10.1.105                                                                              
                                                                                                                  
OS: Ubuntu 16.04.6 LTS                                                                                            
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609                                                      
CMake version: version 3.14.0                                                                                     
                                                                                                                  
Python version: 3.6                                                                                               
Is CUDA available: Yes                                                                                            
CUDA runtime version: 10.1.105                                                                                    
GPU models and configuration:                                                                                     
GPU 0: Tesla K40c                                                                                                 
GPU 1: Tesla K40c                                                                                                 
                                                                                                                  
Nvidia driver version: 418.39                                                                                     
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7                                        
                                                                                                                  
Versions of relevant libraries:                                                                                   
[pip3] numpy==1.15.4                                                                                              
[conda] blas                      1.0                         mkl                                                 
[conda] magma-cuda100             2.5.0                         1    pytorch                                      
[conda] mkl                       2019.3                      199  
[conda] mkl-include               2019.3                      199  
[conda] mkl-service               1.1.2            py36he904b0f_5  
[conda] mkl_fft                   1.0.12           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.0.1           cuda100py36he554f03_0  
[conda] torch                     1.1.0a0+8cd6d2f          pypi_0    pypi
[conda] torchvision               0.2.1                    py36_0
```

 - PyTorch Version (e.g., 1.0): 1.1
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): installed from source
 - Build command you used (if compiling from source): python setup.py install
 - Python version: 3.6.8
 - CUDA/cuDNN version: 10.1.105 / 7.5.1
 - GPU models and configuration: Tesla K40c [2 slots]
 - Any other relevant information: Openmpi v3.1.2

## Additional context

This seems to occur for older version of openmpi i.e. 3.1.2... I have the latest version of openmpi v4.0.1 on my local machine where the same code works perfectly fine.

**Comment by Usama-Zafar** [comment]
Some additional information turns out the reduce bug was my problem but the isend and irecv problem still exist. I did some additional poking and found out that this happens when you try to send receive tensors that are on GPU. If you communicate with non cuda tensors the code works fine.

**Comment by pietern** [comment]
@Usama-Zafar Thanks for the report. The output snippet you included shows the tensors you're trying to use are CUDA tensors. Is your MPI build CUDA aware? PyTorch doesn't implicitly copy the CUDA tensors back to the host for you.

**Comment by Usama-Zafar** [comment]
@pietern Yes I the MPI I am using is build CUDA aware. And yes the problem seems to be from moving tensors around in the GPU. When I explicitly copy CUDA tensors back to host and then communicate it works perfectly fine. That's weird even though I built my MPI as CUDA aware.

**Comment by pietern** [comment]
@Usama-Zafar Can you confirm if any MPI operation against CUDA pointers works? If none of them work then the CUDA support in your MPI distribution or UCX may be broken...

**Comment by pietern** [comment]
@Usama-Zafar Did you find a resolution for this issue?

**Comment by Usama-Zafar** [comment]
@pietern sorry for a very late reply, have been traveling. I have closed it because it was part of another bug already reported. I was getting the issue when I was trying to create threads and using them for communication. It was reported here: https://github.com/pytorch/pytorch/issues/16559

**Comment by pietern** [comment]
@Usama-Zafar Thanks for updating, nonetheless! Looks like there is progress on the issue you linked.
