### ISSUE TITLE
MacOSX, CUDA, OS call failed or operation not supported on this OS

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/pytorch#2029]
Hi,

I compiled PyTorch ([master](https://github.com/pytorch/pytorch/tree/ebdec9a837074a303fd5ffb6f319cd593955becc) of 2 days ago) from sources on MacOSX 10.11 using the following command
```
NO_DISTRIBUTED=1 MACOSX_DEPLOYMENT_TARGET=10.11 CC=clang CXX=clang++ python3 setup.py install
```
The build and installation is successfull, however this [tutorial](http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py) ends up with the error : 
```
THCudaCheck FAIL file=/Users/USER/pytorch-master_source/torch/lib/THC/generic/THCStorage.cu line=66 error=63 : OS call failed or operation not supported on this OS
Traceback (most recent call last):
  File "tensor_tutorial.py", line 141, in <module>
    x = x.cuda()
  File "/usr/local/lib/python3.5/site-packages/torch/_utils.py", line 65, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/usr/local/lib/python3.5/site-packages/torch/cuda/__init__.py", line 269, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: cuda runtime error (63) : OS call failed or operation not supported on this OS at /Users/USER/pytorch-master_source/torch/lib/THC/generic/THCStorage.cu:66
``` 
GPU is NVidia GT 750M, 2GB. I have installed CUDA 8.0 with CuDNN 5.1 which works perfectly with Theano, Tensorflow. Clang info : 
```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
```
If anyone know why I would receive such error, hints appreciated. 
Thanks

**Comment by soumith** [comment]
@ngimel any ideas? GT 750M

**Comment by ngimel** [comment]
May be related? https://github.com/facebookresearch/deepmask/issues/85. Someone solved it by updating OSX from 10.11 to 10.12

**Comment by denizs** [comment]
I experienced the same issue on 10.11. Upgrading to 10.12 solved this issue for me @vfdev-5

**Comment by vfdev-5** [comment]
@denizs, @ngimel thanks for info, I fear that such macosx updates can break other packages... Today I have tensorflow and theano perfectly working on 10.11.
Anyway, nice to know that

**Comment by soumith** [comment]
i'm going to close the issue, as it's one of those CUDA issues that is out of pytorch's control.
