### ISSUE TITLE
nccl runtime error: unhandled system error

### ISSUE THREAD

**Issue by un-knight** [pytorch/pytorch#20313]
## 🐛 Bug

Got NCCL RuntimeError when startup a distributed training task with 2 nodes. Error code is:

```
Traceback (most recent call last):
  File "train_recognition.py", line 235, in <module>
    BACKBONE = DistributedDataParallel(BACKBONE, device_ids=[args.local_rank], output_device=args.local_rank)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 286, in __init__
    self.broadcast_bucket_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 410, in _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1556653114079/work/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled system error
```

But when I run the same code inside 1 nodes with multi-processes and each process per gpu, it works well.

## Environment

both node has the same configuration.

```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: TITAN V
GPU 1: TITAN V
GPU 2: TITAN V
GPU 3: TITAN V
GPU 4: TITAN V
GPU 5: TITAN V
GPU 6: TITAN V
GPU 7: TITAN V

Nvidia driver version: 410.78
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[pip] torch==1.1.0
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      199  
[conda] mkl-include               2019.3                      199  
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torchvision               0.2.2                      py_3    pytorch
```

**Comment by ailzhang** [comment]
Hey @un-knight if you could provide a simple repro script for us to test, it would be super helpful. Thanks!

**Comment by un-knight** [comment]
@ailzhang Of course! There is the test code address https://github.com/NVIDIA/apex/tree/master/examples/simple/distributed.

When I run the code on a single node, everything is ok. But when I run the code on multi-nodes, I got the nccl runtime error.

for example:
node1(node1 ip: 192.168.3.8)
```
python -m torch.distributed.launch --nnodes=2 --nproc_per_node=4 --node_rank=0 --master_addr=192.168.3.8 --master_port=9999 distributed_data_parallel.py
```
----------------------------------------------------
node2
```
python -m torch.distributed.launch --nnodes=2 --nproc_per_node=4 --node_rank=1 --master_addr=192.168.3.8 --master_port=9999 distributed_data_parallel.py
```

then node2 got nccl runtime error:

```
Traceback (most recent call last):
  File "distributed_training_example.py", line 50, in <module>
    model = DistributedDataParallel(model, device_ids=[args.local_rank], output_device=args.local_rank)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 286, in __init__
    self.broadcast_bucket_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 410, in _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1556653114079/work/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled system error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'distributed_training_example.py', '--local_rank=0']' returned non-zero exit status 1.
```
and so there are two errors, one is `nccl runtime error`, and the other is `subprocess.CalledProcessError`

and all my operations are done on a docker container.

**Comment by un-knight** [comment]
I think I fixed the issue. It's my fault not to set `NCCL_SOCKET_IFNAME`, `MASTER_ADDR` and `MASTER_PORT` correctly. Debug with `NCCL_DEBUG=INFO` is very useful!

**Comment by raxxerwan** [comment]
Hello, I've met exactly the same problem with you now. Would you plz share your solution? Thx in advance!

**Comment by un-knight** [comment]
> Hello, I've met exactly the same problem with you now. Would you plz share your solution? Thx in advance!

well, in my case, I set NCCL environment to my target ethernet and MASTER address to master node ip, then nccl communication can be start up.

**Comment by obravo7** [comment]
Hello, I get the same error. I am following this guide https://pytorch.org/tutorials/beginner/aws_distributed_training_tutorial.html#running-the-code , but when I run the four terminal windows, the first window for node0 give the error: RuntimeError: Address already in use. While the other three windows give the error message: RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled system error

I tried running the python main file with NCCL_DEBUG=INFO with no luck. I am doing this in on two AWS EC2 Ubuntu instances (Deep learning) and have been following the tutorial listed above. Perhaps it related to the port I am using?

**Comment by un-knight** [comment]
@obravo7 This maybe your MASTER_PORT had being used by other processes,  you can change the MASTER_PORT and try again.

**Comment by obravo7** [comment]
@un-knight When you set the MASTER_ADDR, did you set it to be the same across both nodes? As in both nodes have the same MASTER_ADDR? I tried changing the MASTER_PORT for node one to an available port but I still got the same error messages.

**Comment by un-knight** [comment]
All nodes need to be set with same MASTER_ADDR and MASTER_PORT.

Best Regards,

Junxian Ye

University of Electronic Science and Technology of China (UESTC)


Eric Narciso-Molina <notifications@github.com> 于2019年8月23日周五 下午4:04写道：

**Comment by xxxyyycc** [comment]
> I think I fixed the issue. It's my fault not to set `NCCL_SOCKET_IFNAME`, `MASTER_ADDR` and `MASTER_PORT` correctly. Debug with `NCCL_DEBUG=INFO` is very useful!

set NCCL_SOCKET_IFNAME correctly solved my problems, thanks

**Comment by hongrui16** [comment]
I  found that this error was due to master_port was used more than once at the same time. After modifying number of master_port , I can run training smoothly.

**Comment by emergencyd** [comment]
> I found that this error was due to master_port was used more than once at the same time. After modifying number of master_port , I can run training smoothly.

Could u please tell me how to modify the number of master_port? Since I found that I meet the same error when I want to run two distributed dataparallel programs on the same node (with 8 GPUs total, each occupy 4 GPUs)

**Comment by ganesh3** [comment]
Can someone please share how to set the 3 parameters? NCCL_SOCKET_IFNAME , MASTER_ADDR, MASTER_PORT

**Comment by brando90** [comment]
> @obravo7 This maybe your MASTER_PORT had being used by other processes, you can change the MASTER_PORT and try again.

How does that translate to actual code?

My current set up is this:
```
def setup_process(rank, world_size, backend='gloo'):
    """
    Initialize the distributed environment (for each process).

    gloo: is a collective communications library (https://github.com/facebookincubator/gloo). My understanding is that
    it's a library/API for process to communicate/coordinate with each other/master. It's a backend library.
    """
    if rank != -1:  # -1 rank indicates serial code
        # set up the master's ip address so this child process can coordinate
        # os.environ['MASTER_ADDR'] = '127.0.0.1'
        os.environ['MASTER_ADDR'] = 'localhost'
        # os.environ['MASTER_PORT'] = '12355'
        os.environ['MASTER_PORT'] = '92345'

        # - use NCCL if you are using gpus: https://pytorch.org/tutorials/intermediate/dist_tuto.html#communication-backends
        if torch.cuda.is_available():
            backend = 'nccl'
        # Initializes the default distributed process group, and this will also initialize the distributed package.
        dist.init_process_group(backend, rank=rank, world_size=world_size)
```

**Comment by brando90** [comment]
> > Hello, I've met exactly the same problem with you now. Would you plz share your solution? Thx in advance!
> 
> well, in my case, I set NCCL environment to my target ethernet and MASTER address to master node ip, then nccl communication can be start up.

How does that translate to actual code?

My current set up is this:
```
def setup_process(rank, world_size, backend='gloo'):
    """
    Initialize the distributed environment (for each process).

    gloo: is a collective communications library (https://github.com/facebookincubator/gloo). My understanding is that
    it's a library/API for process to communicate/coordinate with each other/master. It's a backend library.
    """
    if rank != -1:  # -1 rank indicates serial code
        # set up the master's ip address so this child process can coordinate
        # os.environ['MASTER_ADDR'] = '127.0.0.1'
        os.environ['MASTER_ADDR'] = 'localhost'
        # os.environ['MASTER_PORT'] = '12355'
        os.environ['MASTER_PORT'] = '92345'

        # - use NCCL if you are using gpus: https://pytorch.org/tutorials/intermediate/dist_tuto.html#communication-backends
        if torch.cuda.is_available():
            backend = 'nccl'
        # Initializes the default distributed process group, and this will also initialize the distributed package.
        dist.init_process_group(backend, rank=rank, world_size=world_size)
```

**Comment by WenM1222** [comment]
I also met this problem when I ran one training code inside a docker container with pytorch 1.17. I solved it by increasing the number of workers for loading training data.

**Comment by brando90** [comment]
> I also met this problem when I ran one training code inside a docker container with pytorch 1.17. I solved it by increasing the number of workers for loading training data.

Im confused, I thought num_workers had to be zero if we were using DDP (since each process had its own data loader). Was that not the case for you?

Thanks for the response!

**Comment by brando90** [comment]
actually I have related post that is new:


- https://github.com/pytorch/pytorch/issues/53395
- https://stackoverflow.com/questions/66498045/how-to-solve-dist-init-process-group-from-hanging-or-deadlocks

**Comment by WenM1222** [comment]
> > I also met this problem when I ran one training code inside a docker container with PyTorch 1.17. I solved it by increasing the number of workers for loading training data.
> 
> Im confused, I thought num_workers had to be zero if we were using DDP (since each process had its own data loader). Was that not the case for you?
> 
> Thanks for the response!

Sorry, I didn't check the question carefully. I didn't use DDP. I used DataParallel to train my model on 4 RTX 3090 GPU in Ubuntu 18.04. When I set the number of workers of loading data as 0, the NCCL error occurred. After increasing the number of workers, this error disappeared.
