### ISSUE TITLE
Allow parallel sending to device in DataLoader

### ISSUE THREAD

**Issue by veritas9872** [pytorch/pytorch#20619]
## 🚀 Feature
I wish to request a feature that allows DataLoader to send data to devices instead of only pin memory, or create a new DataLoader which can do this.

## Motivation

I am currently working on a dataset with very large image sizes. Also, these images need to be processed with computationally intensive processes which are best done on GPU. 

Due to the large size of my data, the training process is dominated by the time necessary for reading data from disk and sending it to GPU. 

However, DataLoader does not natively support sending data to devices, only to pin memory.

Moreover, when I tried to implement sending to GPU inside the transform for the Dataset, I got "RuntimeError: CUDA error: initialization error".
I found in this [post](https://discuss.pytorch.org/t/pin-memory-vs-sending-direct-to-gpu-from-dataset/33891) that sending to GPU could only be done if only 1 process was being run. 

However, I believe that many training processes which are bottlenecked by data I/O would benefit from being able to prefetch data to GPU in parallel, even at the cost of taking up more GPU memory.

I have found in the [documentation](https://pytorch.org/docs/stable/multiprocessing.html) that sharing tensors between processes is possible, at least in Python 3. I would like to request this feature to maximize GPU utilization.

## Pitch

I would therefore like to propose a new DataLoader that can take in "device" arguments as suggested here https://github.com/pytorch/pytorch/issues/11372, and allow loading to GPUs in parallel.

## Alternatives

An alternative solution would be to create a new DataLoader class specifically designed to allow parallel data loading to GPU devices.

**Comment by SsnL** [comment]
you can already do that in dataset if you use `spawn` starting method

**Comment by veritas9872** [comment]
Thank you. I just figured out how to do it.

**Comment by ihexx** [comment]
@veritas9872 You mind mentioning how you did it? I'm stuck trying to do the same thing.

**Comment by veritas9872** [comment]
Using Python 3, just add torch.multiprocessing.set_start_method(method='spawn') in front of any code that you wish to use. Be careful when using multiple GPUs as this may cause unexpected problems when the default_collate_fn of the DataLoader tries to send a tensor that is already on device to shared memory.

**Comment by ihexx** [comment]
Ah I see. I [had tried that](https://discuss.pytorch.org/t/how-do-i-copy-data-to-gpu-in-parallel/48762), but  I'm still unclear on where exactly you're pushing the tensors to the GPU. Is it in the dataset's __getitem__() method? A dataset transform? A collate_fn passed to a DataLoader?

**Comment by veritas9872** [comment]
No the push occurs inside the transform. It would be possible to design a custom collate_fn but that would be inefficient. The whole point of doing this is because pushing to GPU is so time consuming. Therefore, the best way is to send to GPU in a data transform.

**Comment by ihexx** [comment]
thanks that worked
