### ISSUE TITLE
CUDA error: unknown error on Windows

### ISSUE THREAD

**Issue by Jonas1312** [pytorch/pytorch#20635]
## 🐛 Bug

`CUDA error: unknown error` after trying to convert a `torch.float32` tensor to a `torch.cuda.FloatTensor` using `x.type(torch.cuda.FloatTensor)`

## Call stack: 
![Capture](https://user-images.githubusercontent.com/15847892/57917902-feb13f80-7895-11e9-8f54-bfd07ac3a832.PNG)

Variables:
- item2 tensor: https://user-images.githubusercontent.com/15847892/57917623-631fcf00-7895-11e9-9e66-726352e9baaa.PNG

Code:
![Capture](https://user-images.githubusercontent.com/15847892/57918096-636c9a00-7896-11e9-80e1-f62e13bb7cd8.PNG)

## To Reproduce

Hard to reproduce, error only appears using a specific libray, if I try to reproduce the error in the REPL it works:

```
C:\Users\Jonas>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.1.0.dev20190516'
>>> a = torch.randn(1)
>>> a
tensor([-1.1125])
>>> a.dtype
torch.float32
>>> a.type(torch.cuda.FloatTensor)
tensor([-1.1125], device='cuda:0')
>>>
```

## Environment
 - PyTorch Version (e.g., 1.0): '1.1.0.dev20190516'
 - OS (e.g., Linux): windows 10 17763
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: 940mx

**Comment by Jonas1312** [comment]
Related to #17108

**Comment by colesbury** [comment]
@Jonas1312 what's "using a specific library" refer to?

I don't have easy access to a Windows machine. Can you do some debugging to narrow down the issue? 

First, try using `torch.cuda._lazy_init()` instead of `torch.cuda.current_device()`. If that works try the following at the beginning (instead of `torch.cuda.current_device()`):

```
    torch.cuda._check_driver()
    torch._C._cuda_init()
```

**Comment by Jonas1312** [comment]
@colesbury The bug appears only when I use the library `kymatio` which relies on torch tensors. As shown above, when I try to reproduce the bug in a python interpreter it doesn't crash.

With `torch.cuda._lazy_init()` it works

If I try with `torch.cuda._check_driver()` and `torch._C._cuda_init()` it crashes:
```
Traceback (most recent call last):
  File "c:/Users/Jonas/Documents/GitHub/kymatio/examples/2d/invert_scattering.py", line 50, in <module>
    scattering = scattering.cuda()
  File "c:\users\jonas\documents\github\kymatio\kymatio\scattering2d\scattering2d.py", line 123, in cuda
    return self._type(torch.cuda.FloatTensor)
  File "c:\users\jonas\documents\github\kymatio\kymatio\scattering2d\scattering2d.py", line 114, in _type
    self.Psi[key][key2] = item2.type(_type)
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 176, in _lazy_init
    torch._C._cuda_init()
RuntimeError: generic_type: cannot initialize type "_CudaDeviceProperties": an object with that name is already defined
```

I will try to find the issue with visual c++ debugger but I can't build pytorch myself for now.

**Comment by colesbury** [comment]
@Jonas1312 thanks. I see now why the second two lines wouldn't work in general.

Can you try making a self-contained example that reproduces the issue? It's OK if the example depends on `kymatio`. I'll try it on my Windows machine at home

**Comment by Jonas1312** [comment]
@colesbury ok!
```
pip3 install https://download.pytorch.org/whl/nightly/cu100/torch_nightly-1.1.0.dev20190516-cp36-cp36m-win_amd64.whl
git clone https://github.com/kymatio/kymatio.git
cd kymatio
pip3 install -e .
```
and execute the following file: https://github.com/Jonas1312/kymatio/blob/inverting-scatt-mse/examples/2d/invert_scattering.py

you should be able to comment most lines and imports except:
```
# Compute scattering coefficients
scattering = Scattering2D(J=J, shape=(height, width), max_order=order)
if device == "cuda":
    scattering = scattering.cuda()
```

**Comment by peterjc123** [comment]
@Jonas1312 Hi, I believe this one has the same cause with #17108, which makes it hard to reproduce at our side. Would you provide some logs so that we can have a clear image of the problem? You could use `API Monitor` and set the filters to all the functions of the CUDA DLLs (`cu*.dll` in `[Python Root]\Lib\site-packages\torch\lib`, and `nvfatbinaryloader.dll`, `nvcuda.dll` and `nvapi64.dll` in `C:\Windows\System32` ).

**Comment by Jonas1312** [comment]
Hi @peterjc123 
Again I would be happy to help but I don't really understand what I have to do with `Api monitor` exactly 

Here is what I have now: https://user-images.githubusercontent.com/15847892/57966965-3df49480-7959-11e9-90d5-284f705ac850.png

**Comment by Jonas1312** [comment]
Settings: https://user-images.githubusercontent.com/15847892/57968603-114a7800-796d-11e9-8a3c-6167ddf63815.png
Results: https://user-images.githubusercontent.com/15847892/57968635-62f30280-796d-11e9-97d1-dedc3762b285.png

**Comment by peterjc123** [comment]
Could you please send them in text form?

**Comment by Jonas1312** [comment]
@peterjc123 there is no way to export in text form, only `.apmx64`  [capt.zip](https://github.com/pytorch/pytorch/files/3194884/capt.zip)
BTW I've found many `API monitor` softwares, here I'm using API Monitor (rohitab.com)

**Comment by peterjc123** [comment]
@Jonas1312 Thanks, that's just what I wanted. I've filtered out the unrelated calls and the API log is listed below:

\# | Time of Day | Module | API | Return Value | Duration
-- | -- | -- | -- | -- | --
31934 | 06:11.5 | torch_python.dll | cudaGetDeviceCount ( ... ) | 0 | 0.5731985
31935 | 06:11.6 | cudart64_100.dll | cuDriverGetVersion ( ... ) | 0 | 0.0015398
31936 | 06:11.6 | cudart64_100.dll | cuInit ( ... ) | 0 | 0.5475448
31937 | 06:11.6 | nvcuda.dll | nvapi_QueryInterface ( ... ) | 1.40729E+14 | 0.0000045
31938 | 06:11.6 | nvcuda.dll | nvapi_QueryInterface ( ... ) | 1.40729E+14 | 0
31939 | 06:11.6 | nvcuda.dll | nvapi_QueryInterface ( ... ) | 0 | 0.0000001
31940 | 06:11.6 | nvcuda.dll | nvapi_QueryInterface ( ... ) | 0 | 0.0000001
31941 | 06:12.1 | nvcuda.dll | nvapi_QueryInterface ( ... ) | 1.40729E+14 | 0.000001
31942 | 06:12.1 | nvcuda.dll | nvapi_QueryInterface ( ... ) | 1.40729E+14 | 0.0000048
31943 | 06:12.1 | nvcuda.dll | nvapi_QueryInterface ( ... ) | 1.40729E+14 | 0.0000008
31944 | 06:12.1 | nvcuda.dll | nvapi_QueryInterface ( ... ) | 1.40729E+14 | 0.0000011
31945 | 06:12.1 | cudart64_100.dll | cuGetExportTable ( ... ) | 0 | 0.000456
31946 | 06:12.1 | cudart64_100.dll | cuGetExportTable ( ... ) | 0 | 0.0000008
31947 | 06:12.1 | cudart64_100.dll | cuDeviceGetCount ( ... ) | 0 | 0.0009447
31948 | 06:12.1 | cudart64_100.dll | cuDeviceGet ( ... ) | 0 | 0.0000058
31949 | 06:12.1 | cudart64_100.dll | cuDeviceGetName ( ... ) | 0 | 0.0000011
31950 | 06:12.1 | cudart64_100.dll | cuDeviceTotalMem_v2 ( ... ) | 0 | 0.0000337
32007 | 06:12.1 | nvcuda.dll | nvapi_QueryInterface ( ... ) | 1.40729E+14 | 0.0000043
32045 | 06:12.1 | cudart64_100.dll | cuDeviceGetUuid ( ... ) | 0 | 0.0000005
32046 | 06:12.1 | cudart64_100.dll | cuDeviceGetLuid ( ... ) | 0 | 0.0000007
32047 | 06:12.1 | cudart64_100.dll | cuGetExportTable ( ... ) | 0 | 0.000001
32048 | 06:12.1 | cudart64_100.dll | cuGetExportTable ( ... ) | 0 | 0.0000001
32049 | 06:12.1 | torch_python.dll | cudaGetDeviceCount ( ... ) | 0 | 0.0000002
32050 | 06:14.3 | caffe2_gpu.dll | cudaGetDeviceCount ( ... ) | 0 | 0.0000018
32051 | 06:14.3 | caffe2_gpu.dll | cudaGetDevice ( ... ) | 0 | 0.0022122
32052 | 06:14.3 | cudart64_100.dll | cuCtxGetDevice ( ... ) | 201 | 0.0000048
32053 | 06:14.3 | cudart64_100.dll | cuGetExportTable ( ... ) | 0 | 0.0000017
32054 | 06:14.3 | caffe2_gpu.dll | cudaSetDevice ( ... ) | 0 | 0.0000253
32055 | 06:14.3 | cudart64_100.dll | cuCtxSetCurrent ( ... ) | 0 | 0.0000109
32056 | 06:14.3 | caffe2_gpu.dll | cudaGetDeviceCount ( ... ) | 0 | 0.0000003
32057 | 06:14.3 | caffe2_gpu.dll | cudaGetDeviceProperties ( ... ) | 30 | 0.0002777
32061 | 06:14.3 | caffe2_gpu.dll | cudaGetLastError ( ... ) | 30 | 0.0000008
32062 | 06:14.3 | caffe2_gpu.dll | cudaGetErrorString ( ... ) | 1.40728E+14 | 0.0000005

@colesbury Hopefully, it may help you to locate the issue.

**Comment by peterjc123** [comment]
The error itself was thrown at `nvcuda.dll`:

\# | Time of Day | Module | API | Return Value | Duration
-- | -- | -- | -- | -- | --
32057 | 06:14.3 | caffe2_gpu.dll | cudaGetDeviceProperties ( ... ) | 30 | 0.000278
32058 | 06:14.3 | cudart64_100.dll | cuDeviceGetAttribute ( ... ) | 0 | 5.29E-05
32059 | 06:14.3 | cudart64_100.dll | cuDeviceGetAttribute ( ... ) | 0 | 9E-07
32060 | 06:14.3 | cudart64_100.dll | cuDeviceGetAttribute ( ... ) | 999 | 0.000114

@Jonas1312 It will be great if we could know the argument when those functions get called. You can use `API Monitor` in `Remote Thread (Extended)` mode, right click `cudaGetDeviceProperties` and `cudaGetDeviceProperties`, add pre-call breakpoints to them and use VS as the JIT debugger.
Besides, you may need to add the symbol debugging symbols for CUDA. Here is the reference: https://developer.nvidia.com/nvidia-driver-symbol-server.

**Comment by Jonas1312** [comment]
@peterjc123 Ok, but I'm gonna need some help 😅

So for now I've added breakpoints on the two API calls you suggested and when I launch the monitoring the following window pops up: https://user-images.githubusercontent.com/15847892/57984839-00c6fa00-7a60-11e9-9546-a7d135a923c5.PNG

Then I click `break` and I attach VS debugger to `python.exe`.  https://user-images.githubusercontent.com/15847892/57984872-513e5780-7a60-11e9-9795-bc553a3c5481.PNG

I click `ok` and it shows this:  https://user-images.githubusercontent.com/15847892/57984889-792dbb00-7a60-11e9-9246-c5090ca58f4d.PNG

Symbols settings:  https://user-images.githubusercontent.com/15847892/57984909-b2fec180-7a60-11e9-8d02-3604d2f91aa9.PNG

**Comment by peterjc123** [comment]
@Jonas1312 What about using `continue` or `step over`?

**Comment by Jonas1312** [comment]
@peterjc123 No it's not working sorry

**Comment by peterjc123** [comment]
Looks like it is caused by trying to initialize cuda (a.k.a do `cuInit`) multiple times. 
Because I'm possible to reproduce the same error in https://github.com/pytorch/pytorch/issues/20635#issuecomment-493544995 by doing the following things:
```python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda._initialized
False
>>> torch.cuda.init()
>>> torch.cuda._initialized
True
>>> torch.cuda._initialized = False
>>> torch.cuda.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "torch\cuda\__init__.py", line 145, in init
    _lazy_init()
  File "torch\cuda\__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: generic_type: cannot initialize type "_CudaDeviceProperties": an object with that name is already defined
```
Since the original issue was made when 1.0.1 is released, I checked the commits between v1.0.0 and v1.0.1 and found that https://github.com/pytorch/pytorch/pull/15807 may be related. Could you please revert this change and try again?

**Comment by Jonas1312** [comment]
@peterjc123 Ok, so I've tried what you've suggested and unfortunately it didn't work:
```
C:\Users\Jonas>py36
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda._initialized
False
>>> torch.cuda.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 158, in init
    _lazy_init()
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 176, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: unknown error
>>>
```
```
C:\Users\Jonas\Documents\GitHub\kymatio\examples\2d>python invert_scattering.py
Image shape:  (3, 128, 128)
Traceback (most recent call last):
  File "invert_scattering.py", line 47, in <module>
    scattering = scattering.cuda()
  File "c:\users\jonas\documents\github\kymatio\kymatio\scattering2d\scattering2d.py", line 123, in cuda
    return self._type(torch.cuda.FloatTensor)
  File "c:\users\jonas\documents\github\kymatio\kymatio\scattering2d\scattering2d.py", line 114, in _type
    self.Psi[key][key2] = item2.type(_type)
RuntimeError: CUDA error: unknown error

C:\Users\Jonas\Documents\GitHub\kymatio\examples\2d>


```

**Comment by Jonas1312** [comment]
@peterjc123 any ideas?

**Comment by peterjc123** [comment]
What about using `torch.cuda.is_available()` and then `torch._C._cuda_getDevice()`?

**Comment by peterjc123** [comment]
The call stack of the three functions:
```
is_available:
	torch._C._cuda_isDriverSufficient()
		THCPModule_isDriverSufficient() @ torch/csrc/cuda/Module.cpp
			cudaGetDeviceCount
	torch._C._cuda_getDeviceCount()
		THCPModule_getDeviceCount_wrap @ torch/csrc/cuda/Module.cpp
			at::cuda::device_count() @ ?
				c10::cuda::device_count() @ c10/cuda/CUDAFunctions.h
					cudaGetDeviceCount

device_count:
	is_available
	torch._C._cuda_getDeviceCount()

current_device:
	_lazy_init():
		_check_driver():
			torch._C._cuda_isDriverSufficient()
		torch._C._cuda_init()
			THCPModule_initExtension @ torch/csrc/cuda/Module.cpp
				at::globalContext().lazyInitCUDA() @ aten/src/ATen/Context.h
					detail::getCUDAHooks().initCUDA() @ aten/src/ATen/cuda/detail/CUDAHooks.cpp
						THCudaInit @ aten/src/THC/THCGeneral.cpp
							c10::cuda::CUDACachingAllocator::get() 
							cudaGetDeviceCount
							cudaGetDevice
							cudaSetDevice(i)
							at::cuda::getDeviceProperties(i) @ aten/src/ATen/cuda/CUDAContext.cpp
								initCUDAContextVectors @ aten/src/ATen/cuda/CUDAContext.cpp
									c10::cuda::device_count() @ c10/cuda/CUDAFunctions.h
										cudaGetDeviceCount
								c10::cuda::current_device() @ c10/cuda/CUDAFunctions.h
									cudaGetDevice
								initDeviceProperty @ aten/src/ATen/cuda/CUDAContext.cpp
									cudaGetDeviceProperties
							cudaSetDevice
									
		_load_cudart()
		...
	torch._C._cuda_getDevice()
```

**Comment by peterjc123** [comment]
@ezyang Could it be the CUDA version of this issue https://github.com/pytorch/pytorch/issues/17239?

**Comment by Jonas1312** [comment]
@peterjc123 I just had an error while building pytorch [build.txt](https://github.com/pytorch/pytorch/files/3224178/build.txt)

**Comment by Jonas1312** [comment]
@peterjc123 I fixed the previous build error but don't know how to fix this one: [build2.txt](https://github.com/pytorch/pytorch/files/3224521/build2.txt)

**Comment by peterjc123** [comment]
Please comment out line 277 in `c10\util\ArrayRef.h`.

**Comment by Jonas1312** [comment]
@peterjc123 
```
Microsoft Windows [version 10.0.17763.503]
(c) 2018 Microsoft Corporation. Tous droits réservés.

C:\Users\Jonas>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.2.0a0+f4b434a'
>>> torch.cuda.is_available()
True
>>> torch.cuda._initialized
False
>>> torch.cuda.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 158, in init
    _lazy_init()
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 176, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: unknown error
>>> exit()

C:\Users\Jonas>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch._C._cuda_getDevice()
0
>>>
```

I'm gonna try to build pytorch again but this time with #15807 reverted

**Comment by peterjc123** [comment]
@Jonas1312 What about calling `torch._C._cuda_isDriverSufficient()` and `torch.cuda.init()`?

**Comment by Jonas1312** [comment]
@peterjc123 
```
Microsoft Windows [version 10.0.17763.503]
(c) 2018 Microsoft Corporation. Tous droits réservés.

C:\Users\Jonas>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>>  torch.cuda._initialized
  File "<stdin>", line 1
    torch.cuda._initialized
    ^
IndentationError: unexpected indent
>>> torch.cuda._initialized
False
>>> torch._C._cuda_isDriverSufficient()
True
>>> torch.cuda.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 158, in init
    _lazy_init()
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 176, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: unknown error
>>>
```

**Comment by Jonas1312** [comment]
@peterjc123 
```
Microsoft Windows [version 10.0.17763.503]
(c) 2018 Microsoft Corporation. Tous droits réservés.

C:\Users\Jonas>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch._C._cuda_isDriverSufficient()
True
>>> torch.cuda.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 158, in init
    _lazy_init()
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 176, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: unknown error
>>> exit()

C:\Users\Jonas>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch._C._cuda_getDeviceCount()
1
>>> torch.cuda.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 158, in init
    _lazy_init()
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 176, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: unknown error
>>> exit()

C:\Users\Jonas>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch._C._cuda_getDeviceCount()
1
>>> torch.cuda.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 158, in init
    _lazy_init()
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 176, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: unknown error
>>> exit()

C:\Users\Jonas>
```

**Comment by peterjc123** [comment]
@ezyang May I know where is `at::cuda::device_count()` implemented?

**Comment by Jonas1312** [comment]
> 
> 
> @Jonas1312 No, no, no, I mean don't call `is_available` here.

```
Microsoft Windows [version 10.0.17763.503]
(c) 2018 Microsoft Corporation. Tous droits réservés.

C:\Users\Jonas>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch._C._cuda_isDriverSufficient()
True
>>> torch.cuda.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 158, in init
    _lazy_init()
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 176, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: unknown error
>>> exit()

C:\Users\Jonas>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch._C._cuda_getDeviceCount()
1
>>> torch.cuda.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 158, in init
    _lazy_init()
  File "C:\Python36\lib\site-packages\torch\cuda\__init__.py", line 176, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: unknown error
>>> exit()

C:\Users\Jonas>
```

**Comment by peterjc123** [comment]
@Jonas1312 These two functions are actually doing the same thing but through different code paths. The code is listed below:
```cpp
// torch/csrc/cuda/Module.cpp
PyObject * THCPModule_isDriverSufficient(PyObject *self)
{
  int count;
  cudaError_t err = cudaGetDeviceCount(&count);
  if (err == cudaErrorInsufficientDriver) {
    return PyBool_FromLong(0);
  }
  return PyBool_FromLong(1);
}
PyObject * THCPModule_getDeviceCount_wrap(PyObject *self) 
{
  HANDLE_TH_ERRORS
  return PyLong_FromLong(at::cuda::device_count());
  END_HANDLE_TH_ERRORS
}
```
I guess we can replace `at::cuda::device_count` here with a raw `cudaGetDeviceCount` call, but it will be better to know why it is causing this problem.

**Comment by peterjc123** [comment]
What about replacing `torch.cuda.init()` with `torch._C._cuda_init()`?

**Comment by Jonas1312** [comment]
@peterjc123 
```
Microsoft Windows [version 10.0.17763.503]
(c) 2018 Microsoft Corporation. Tous droits réservés.

C:\Users\Jonas>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch._C._cuda_isDriverSufficient()
True
>>> torch._C._cuda_init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: unknown error
>>> exit()

C:\Users\Jonas>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch._C._cuda_getDeviceCount()
1
>>> torch._C._cuda_init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: unknown error
>>> exit()

C:\Users\Jonas>
```

**Comment by Jonas1312** [comment]
@peterjc123 Reverting #15807 doesn't fix the issue

**Comment by peterjc123** [comment]
So the problem is not on the python side. Actually, I find a similar issue in a different repo https://github.com/xmrig/xmrig-nvidia/pull/255/files#diff-511952111c831a641699c2f24cb59767R550, which tries to do `cudaDeviceReset` before `cudaGetDeviceProperties`. However, I believe this should not be the first thing we should try. I reviewed the code differences between v1.0.0 and v1.0.1 again and saw that we switched off cudart static linking. Would you please try commenting out line 16 in `cmake/public/cuda.cmake` and rebuilding again?

**Comment by Jonas1312** [comment]
@peterjc123 Thank you!
```
C:\Users\Jonas\Desktop>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.2.0a0+3038cf8'
>>> torch._C._cuda_isDriverSufficient()
True
>>> torch.cuda.init()
>>> exit()

C:\Users\Jonas\Desktop>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch._C._cuda_getDeviceCount()
1
>>> torch.cuda.init()
>>> exit()

C:\Users\Jonas\Desktop>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda._initialized
False
>>> torch.cuda.init()
>>> torch.cuda._initialized
True
>>> torch.cuda.init()
>>> torch.cuda.device_count()
1
>>> torch._C._cuda_getDeviceCount()
1
```

**Comment by peterjc123** [comment]
@Jonas1312 Great! I finally did it. But the question is why it is the cause?

**Comment by peterjc123** [comment]
@Jonas1312 Anyway, I made the PR @21062 first.
