### ISSUE TITLE
distributed all_reduce deadlocks in v1.1

### ISSUE THREAD

**Issue by prafullasd** [pytorch/pytorch#20630]
## 🐛 Bug

I'm doing multi-node training (8 nodes, 8 gpu's each, NCCL backend) and am using `DistributedDataParallel` for syncing grads and `distributed.all_reduce()` calls to log losses. I recently upgraded from Pytorch v1.0 to v1.1 and after doing so, my training script hangs at a `distributed.all_reduce()` call. The hang doesn't occur if I downgrade pytorch to v1.0. It also hangs if I use the pytorch-nightly version.
Some observations about the deadlock that might be useful:

1. The script deadlocks exactly after the same number of training iterations (7699). Changing the model architecture changed this number, but it's still the same for different runs of the same architecture.

2. In all the runs, the hang occurs at an all_reduce of a single element gpu tensor created as follows:
```
loss = loss.item()
sum = torch.tensor(loss * batch).float().cuda() //as batch could be different on each rank
distributed.all_reduce(sum)
sum = sum.item()
```
All ranks complete line 3, but only ranks = {0,8,16,...,56} ie ranks with local_rank=0 complete line 4. I checked if different processes are accessing the same GPU, however each process is using it's corresponding gpu (set using `torch.cuda.set_device(local_rank)`, though all GPU's are visible to each process). I tried adding a `dist.barrier()` after the `all_reduce()`, or using the same tensor for sum always (instead of creating a new one), however it still hangs, and always after the same number of iterations (7699). 
3. The reduction within the DDP itself hasn't hung in any of my runs yet. I tried setting `find_unused_parameters=True`, however that didn't help.
4. I looked at NCCL debug logs using `NCCL_DEBUG_SUBSYS=COLL NCCL_DEBUG=INFO`, and no errors were thrown. The last calls corresponded to all reduce calls for a 1 element tensor. It's fewer calls than the previous iteration though. 
## To Reproduce

It takes about 7 hrs for the deadlock to happen, and it's hard for me to share the code. I'll try see if I can come up with a simpler script that reproduces the deadlock.

## Environment
```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130

GPU models and configuration:                                                                                                          GPU 0: Tesla V100-SXM2-16GB                                                                                                            GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 410.79
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4

Versions of relevant libraries:                                                                                                        [pip3] numpy==1.16.3                                                                                                                   [pip3] tcop-pytorch==0.0.0
[pip3] torch==1.1.0
[pip3] torchvision==0.2.2.post3
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.3                      199
[conda] mkl_fft                   1.0.12           py36ha843d7b_0
[conda] mkl_random                1.0.2            py36hd81dba3_0
[conda] pytorch                   1.1.0           py3.6_cuda10.0.130_cudnn7.5.1_0    pytorch                                           [conda] tcop-pytorch              0.0.0                    pypi_0    pypi
[conda] torchvision               0.2.2.post3              pypi_0    pypi
```

**Comment by GolovanovSrg** [comment]
I have the same problem

**Comment by XuezheMax** [comment]
I have the same problem, but not sure if it happened only to reduce_all

**Comment by kefirski** [comment]
actually, I'm too not sure whether the problem in `reduce_all`. I had removed everything including all reducing ops from my code, except `backward`, but I still get this weird deadlock that happens in ~35 hours of training

**Comment by prafullasd** [comment]
In my case I don't get a deadlock if I run the same code on a single node with 8 gpus. I also don't get a deadlock if I remove the `all_reduce()` call (while keeping DistributedDataParallel for grads). It probably is related to a multi-node `all_reduce()` call then.

**Comment by ngimel** [comment]
Pytorch 1.1 uses nccl 2.4.2 which has a known issue of hanging with long running jobs that was fixed for 2.4.6. https://github.com/NVIDIA/nccl/commit/f40ce73e8987d2990e4b9ef6c75f4b3423acce78
Workaround is to export NCCL_LL_THRESHOLD=0. 
cc @pietern, @mrshenli  to bump nccl submodule.

**Comment by prafullasd** [comment]
@ngimel Thanks a lot for the workaround, I can confirm that jobs have been running for longer than 50 hrs without deadlock.
@mrshenli Thanks for updating the module so fast :) I'll run my jobs again with the latest pytorch-nightly to make sure there's no deadlocks.

**Comment by bezero** [comment]
I am having same bug with `NCCL version 2.5.6` and `torch 1.4`

**Comment by gemfield** [comment]
Env:
- Ubuntu 18.04
- Pytorch 1.6.0
- CUDA 10.1

Actually, I am using Docker image gemfield/pytorch:1.6.0-devel which stated in https://github.com/DeepVAC/deepvac (same with above env), and use PyTorch DDP (by use the class DeepvacDDP in https://github.com/DeepVAC/deepvac/blob/master/deepvac/syszux_deepvac.py) to train my model, which the code worked perfect yesterday. But today when I launch the train program again, the DDP is stucked in loss.backward()， with cpu 100% and GPU 100%。
There has no code change and docker container change since yesterday, except the Ubuntu host got a system update today:
```bash
gemfield@ai03:~$ cat /var/log/apt/history.log | grep -C 3 nvidia

Start-Date: 2020-09-03  06:44:01
Commandline: /usr/bin/unattended-upgrade
Install: linux-modules-nvidia-440-5.4.0-45-generic:amd64 (5.4.0-45.49, automatic)
Upgrade: linux-modules-nvidia-440-generic-hwe-20.04:amd64 (5.4.0-42.46, 5.4.0-45.49)
End-Date: 2020-09-03  06:44:33
```
Obviously, the nvidia driver got update from 440.64 to 440.100, and I think these info may be useful for somebody.

**Comment by dongdongbh** [comment]
I enconter the same error, the program stuck with 100% GPU usage, no warnings or errors. I update nccl to `2.7.08` with `pytroch 1.7`, and my nvidia driver is `440.100`, but the problem still there. The program stuck when I use the function `torch.distributed.reduce`.

Finally, I figure out why this happens. I call the `torch.distributed.reduce` inside a conditional code block where there is only rank-0 process executing. This leads to nccl **deadlock**. So if you call distributed related function, **make sure all processes get the chance to run it.** I just move the outside the conditional code block, the problem disappeared.

**Comment by Hzzone** [comment]
@do

> I encountered the same error, the program stuck with 100% GPU usage, no warnings or errors. I update nccl to `2.7.08` with `pytroch 1.7`, and my nvidia driver is `440.100`, but the problem still there. The program stuck when I use the function `torch.distributed.reduce`.
> 
> Finally, I figure out why this happens. I call the `torch.distributed.reduce` inside a conditional code block where there is only rank-0 process executing. This leads to nccl **deadlock**. So if you call distributed related function, **make sure all processes get the chance to run it.** I just move the outside the conditional code block, the problem disappeared.

It happens when starting to run the code, but not in the case of this issue.

**Comment by morgankohler** [comment]
I seem to be having the same issue. The code works on 1 node but fails on 2. Training loop works fine but then I do distributed validation with an all_reduce at the end. 1 process hangs on all_reduce and breaks the code (I have only tried this on 2 nodes but the one that breaks is always gpu 0 on node 0) . Without all_reduce I have no problem. Checking the debug logs I get this warning after the all_reduce: "NCCL WARN Net : Connection closed by remote peer". This is the only warning or error I get. I have tried to see which NCCL version I have using "torch.cuda.nccl.version()" and get "2408" guessing this is 2.4.8 so the workaround posted above by @ngimel is outdated. Interestingly enough this workaround works for the situation where there are 2 nodes but only one gpu on each node. But if there are >1 gpu per node then it doesn't. 

Also I am not calling this inside a conditional block as @dongdongbh was.

Anyone have any ideas?

**Comment by eslambakr** [comment]
For me it was solved after removing tqdm.

**Comment by doubleZ0108** [comment]
First of all, I describe my personal task basically and point out my error.
- 🎯**Task**: I am doing an image generation task based on diffusion, the packages most related to me are `accelerate`, `diffusers`, `torch`.
- 🐛**BUG**: When I run my code on a single machine + single GPU, everything works pretty fine. But when I use a single machine + multiple GPUs for DDP training, the _NCCL timeout_ related bugs occur.
- 🌪️**Phenomena**: When running the project on 1 machine + 4 GPUs (for example), I got the error message randomly after several steps. The error message points out the NCCL timeout as something like `[Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4084, OpType=BROADCAST, NumelIn=56623104, NumelOut=56623104, Timeout(ms)=600000) ran for 600059 milliseconds before timing out`. And I do not get any error message from my personal code.
    > I use a distributed implementation encapsulated by accelerate, rather than the raw torch. distributed, but I think the core issues are consistent.

<details><summary>The complete error traces.</summary>
<p>

```shell
[rank2]:[E ProcessGroupNCCL.cpp:563] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4084, OpType=ALLREDUCE, NumelIn=4821568, NumelOut=4821568, Timeout(ms)=600000) ran for 600077 milliseconds before timing out.
[rank1]:[E ProcessGroupNCCL.cpp:563] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4084, OpType=ALLREDUCE, NumelIn=4821568, NumelOut=4821568, Timeout(ms)=600000) ran for 600095 milliseconds before timing out.
[rank3]:[E ProcessGroupNCCL.cpp:563] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4084, OpType=BROADCAST, NumelIn=56623104, NumelOut=56623104, Timeout(ms)=600000) ran for 600059 milliseconds before timing out.
dlciwpwqw7kd1h3y-master-0:301:382 [3] NCCL INFO [Service thread] Connection closed by localRank 3
dlciwpwqw7kd1h3y-master-0:301:315 [3] NCCL INFO comm 0x12fd4c240 rank 3 nranks 4 cudaDev 3 busId 70 - Abort COMPLETE
[rank3]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 3] Timeout at NCCL work: 4084, last enqueued NCCL work: 4084, last completed NCCL work: 4083.
[rank3]:[E ProcessGroupNCCL.cpp:577] [Rank 3] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank3]:[E ProcessGroupNCCL.cpp:583] [Rank 3] To avoid data inconsistency, we are taking the entire process down.
[rank3]:[E ProcessGroupNCCL.cpp:1414] [PG 0 Rank 3] Process group watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4084, OpType=BROADCAST, NumelIn=56623104, NumelOut=56623104, Timeout(ms)=600000) ran for 600059 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:565 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f4e9d77a897 in /path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7f4e513aa1b2 in /path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1a0 (0x7f4e513aefd0 in /path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7f4e513b031c in /path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdbbf4 (0x7f4e9ecc7bf4 in /path/to/conda/envs/fitdit/bin/../lib/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x7f4ead294ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126660 (0x7f4ead326660 in /usr/lib/x86_64-linux-gnu/libc.so.6)

W0325 15:10:13.736000 140515496433472 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 298 closing signal SIGTERM
W0325 15:10:13.737000 140515496433472 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 299 closing signal SIGTERM
W0325 15:10:13.738000 140515496433472 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 300 closing signal SIGTERM
E0325 15:10:14.906000 140515496433472 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: -6) local_rank: 3 (pid: 301) of binary: /path/to/conda/envs/fitdit/bin/python
Traceback (most recent call last):
  File "/path/to/conda/envs/fitdit/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
train_logo_refiner.py FAILED
----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-25_15:10:13
  host      : dlciwpwqw7kd1h3y-master-0
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 301)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 301
====================================================

```

</p>
</details> 

<br />

Then I list all attempts I have tried to face the core problem, and you can have a try : ), maybe something can work in your situation.
1. Check your GPU memory. Be sure that the forward and backward of your model do not trap into `CUDA out of memory. Tried to allocate xxx MiB`. You can verify this on a single GPU configuration, and please take some time for a long training test.
2. Check your Dataloader. You should catch exceptions like file paths do not exist, image cannot open... And you can use an `is_valid` flag and `for` loop in `__getitem__()` to make sure that the data you construct is correct. And I have also checked that the processing time of the adjacent two batches is less than a really small seconds.
  a. If your data is stored on a network location (like NAS), pay attention to the fetching time! Be wary of network fluctuations and possible file path corruption.
3. You can try adding these environment parameters.

    ````bash
    export TORCH_DISTRIBUTED_DEBUG=INFO
    export NCCL_DEBUG=INFO
    export NCCL_P2P_DISABLE=0
    export NCCL_P2P_LEVEL=NVL
    ````
4. Allow longer timeout waiting time and set `find_unused_parameters=True`
    
    ```python
    kwargs = DistributedDataParallelKwargs(find_unused_parameters=True)
    timeout = InitProcessGroupKwargs(timeout=timedelta(minutes=15))
    accelerator = Accelerator(
        ...
        kwargs_handlers=[kwargs, timeout],
    )
    ```
5. Build a new python env and upgrade key packages to the latest version, `torch`, `accelerate`, `transformer`, `diffusers`, `nvidia-nccl-cu12`.
6. Delete code related to `tqdm`, `time.time()` or something similar to time record.

<br />

Finally, I will try to understand the problem as deeply as possible based on my current understanding and provide a solution that is applicable to me.
Look at the GPU usage (calculating usage, not GPU memory usage) below. From a certain point in time, the GPU usage reached 100%, and this time coincided with the onset of program pauses / hangs. This extreme usage persisted until the timeout ended, after which the entire program was terminated.

<img src="https://github.com/user-attachments/assets/ef78b6a2-924b-46cc-9c45-7f4531cefd28" width="40%" height="40%" />

Let's conduct a detailed observation. As your task is hung and befor killed by timeout, enter your program's runtime container and execute `ps -ef | grep python` or `htop` to find your Python training processes (typically, the one with the smallest PID is the main process, and the number corresponds to the number of GPUs you are using). Install [pystack](https://github.com/bloomberg/pystack) and use `pystack [PID]` to monitor your main python processes one by one. Compare the output stack message and find the differences.

<details><summary>I got something like</summary>
<p>

```bash
  File "/path/to/train_logo_refiner.py", line 1273, in <module>
    logs['Loss/logo_ssim_loss'] = (loss_logo_ssim / loss_factor).detach().item()
  File "/path/to/train_logo_refiner.py", line 1099, in main
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1593, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1411, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/accelerate/utils/operations.py", line 823, in forward
    return model_forward(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/accelerate/utils/operations.py", line 811, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/path/to/src/transformer_sd3_xxx.py", line 325, in forward
    encoder_hidden_states, hidden_states = torch.utils.checkpoint.checkpoint(
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 494, in checkpoint
    ret = function(*args, **kwargs)
  File "/path/to/src/transformer_sd3_xxx.py", line 320, in custom_forward
    return module(*inputs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/src/attention_xxx.py", line 168, in forward
    norm_hidden_states, gate_msa, shift_mlp, scale_mlp, gate_mlp = self.norm1(hidden_states, emb=temb)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/imggen/diffusers_v32/src/diffusers/models/normalization.py", line 170, in forward
    x = self.norm(x) * (1 + scale_msa[:, None]) + shift_msa[:, None]
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
```

</p>
</details> 


Combining other information output by `pystack`, the issue becomes quite clear: a deadlock caused by a lack of synchronization between processes resulted in GPU usage reaching 100%, but your training did not progress further until it was interrupted by the protection mechanism after a timeout.
- Why are there no errors when using a single GPU? Because, in this case, there are no thread synchronization problems.
- Where do thread synchronization conflicts occur? I'll provide some of my practices and examples.
Look the point #6 on the ordered list ahead. If you use `tqdm` to show your training process, it will cause thread synchronization conflicts. And statistic `time.time()` in training step is also the case.
Another interesting case, if you check the `NaN` value in loss and skip the polluted steps. You may write the code like:

```python
if torch.any(torch.isnan(loss)):
    continue

accelerator.backward(loss)
# ....

# ------------------------------------

if not torch.any(torch.isnan(loss)):
    accelerator.backward(loss)
    # ...
else:
    print("Loss has NaN skip...")
```

This will cause thread synchronization conflicts easily because `rank-i` end a step with no backward and other ranks still calculating the loss backward. You should change your code to:

```python
def check_nan(tensor):
    return torch.isnan(tensor).any().item()

loss_is_nan = torch.tensor(check_nan(loss), device=accelerator.device, dtype=torch.int)

# reduce to check if any process has NaN loss
loss_is_nan = accelerator.reduce(loss_is_nan, reduction="sum")

if loss_is_nan.item() == 0:
    accelerator.backward(loss)
    # ...
else:
    if accelerator.is_main_process:
        print("Loss has NaN, skip...")
```

There are several common cases. Logging to tensorboard, decoding latent image to pixel space for visualization...The principle is that you should not execute special code only for certain threads. Use `accelerator.is_main_process` and `accelerator.wait_for_everyone()` properly.

<br />

<details><summary>Some related issues</summary>
<p>

- https://github.com/huggingface/accelerate/issues/314
- https://blog.csdn.net/weixin_42001089/article/details/122733667 (in Chinese)
- https://github.com/pytorch/pytorch/issues/22834
- https://github.com/pytorch/pytorch/issues/20630
- https://discuss.pytorch.org/t/multi-gpu-training-hangs-watchdog-caught-collective-operation-timeout/188702
- https://github.com/pytorch/pytorch/issues/135352

</p>
</details>
