### ISSUE TITLE
cuda runtime error (9) invalid configuration argument on softmax when sending .view() variables

### ISSUE THREAD

**Issue by bishesh** [pytorch/pytorch#2080]
I need to use `softmax()` function on variables containing 5D tensors (batch_size X nChannels X W X D X H ). 
Since `softmax()` doesn't support 5D, I was changing the variable view as below:
`var = var.view(batch_size, nChannels, -1)`
However running `softmax(var)` throws runtime error when W X D X H is bigger than a certain size. E.g. it works for sizes less than or equal to 40 X 40 X 40 but not greater than this.
 The error I get is the following:
RuntimeError: cuda runtime error (9) : invalid configuration argument at /py/conda-bld/pytorch_1493681908901/work/torch/lib/THCUNN/generic/SoftMax.cu:72

An example to reproduce the error:

```python
import torch
from torch.autograd import Variable
import torch.nn.functional as F
t1 = Variable(torch.FloatTensor(2,1,40,40,40)).cuda()
#Uncommenting the line below breaks softmax
#t1 = Variable(torch.FloatTensor(2,1,41,41,41)).cuda()
t1 = t1.contiguous().view(2,1,-1)
t1=F.softmax(t1)
print(t1.data.size())
t2 = Variable(torch.FloatTensor(2,1,41*41,41*41)).cuda()
# Uncommenting the line below results in error which means total size is not an issue!
#t2 = t2.contiguous().view(2,1,-1)
t2=F.softmax(t2)
print(t2.data.size())
```

**Comment by jjmetzger** [comment]
I get the same problem. As a workaround, viewing this as a 4D tensor works for me.
```
t1 = Variable(torch.FloatTensor(2,1,41,41,41)).cuda()
t1 = t1.contiguous().view(2,1,41,-1)
t1=F.softmax(t1)

```

**Comment by bishesh** [comment]
That will work ONLY for up to a certain size. In general I've found that viewing the tensor by reducing the dimensions from the last ones creates this issue.
So a workaround would be to permute the tensor before doing the viewing so that batch size or nChannels are the last dimensions assuming they won't be as big as the other image dimensions. But then we also need to add some logic to compute softmax in a right way because of the inconsistent (annoying!) way the softmax works for [different dimensions](https://github.com/pytorch/pytorch/issues/1020).  
Here is an example showing these problems: 
```
cs, bs, nc, w, h, d = 1, 1, 1, 1, 256, 256
cs, bs, nc, w, h, d = 2, 1, 1, 39, 41, 41
#cs, bs, nc, w, h, d = 3, 2, 1, 400, 450, 450 
t1 = Variable(torch.FloatTensor(bs,nc,w,h,d)).cuda()
if cs == 1:
    #Breaks from bs, nc, w, h, d = 1, 1, 39, 41, 41
    t1 = t1.contiguous().view(bs,nc,-1)
if cs == 2:
    # Breaks from bs, nc, w, h, d = 1, 1, 1, 256, 256
    t1 = t1.contiguous().view(bs,nc,w,-1)
if cs == 3:
    # Seems to works until out of memory
    t1 = t1.permute(4,3,2,1,0) # d X h X w X nc X bs
    t1 = t1.contiguous().view(-1, nc, bs)
t1=F.softmax(t1)
print(t1.data.size())
# The pattern is similar with 4D tensors also where we do view by
# reducing the last few dimensions.
#t2 = Variable(torch.FloatTensor(2,1,41*41,41*41)).cuda()
# Uncommenting the line below results in error which means total size is not an issue!
#t2 = t2.contiguous().view(2,1,-1)
#t2=F.softmax(t2)
#print(t2.data.size())
```

**Comment by zou3519** [comment]
@bishesh this appears to be fixed on master now (I tried running your examples on master and they didn't error out)

**Comment by soumith** [comment]
will be part of next release.
