### ISSUE TITLE
cuda-runtime error(4) on PyTorch 0.4.1

### ISSUE THREAD

**Issue by encichou** [pytorch/pytorch#21270]
hello every one ,recently i have a bug ,when i train a resnet18 ,after 9000 iterator times ,some problem occured.could you help me ?

```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=271 error=4 : unspecified launch failure 
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=271 error=4 : unspecified launch failure 
Traceback (most recent call last): 
File "model_run.py", line 464, in 
train(train_loader, model, criterion, optimizer, scheduler, epoch,log_file) 
File "model_run.py", line 163, in train 
loss.backward() 
File "/data/anaconda2/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward 
torch.autograd.backward(self, gradient, retain_graph, create_graph) 
File "/data/anaconda2/lib/python2.7/site-packages/torch/autograd/init.py", line 90, in backward 
allow_unreachable=True) # allow_unreachable flag 
File "/data/anaconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 76, in apply 
return self._forward_cls.backward(self, *args) 
File "/data/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 30, in backward 
return (None,) + ReduceAddCoalesced.apply(ctx.input_device, ctx.num_inputs, *grad_outputs) 
File "/data/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 41, in forward x
return comm.reduce_add_coalesced(grads, destination) 
File "/data/anaconda2/lib/python2.7/site-packages/torch/cuda/comm.py", line 119, in reduce_add_coalesced 
flat_tensors = [_flatten_dense_tensors(chunk) for chunk in chunks] 
File "/data/anaconda2/lib/python2.7/site-packages/torch/_utils.py", line 144, in _flatten_dense_tensors x
flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0) 
RuntimeError: cuda runtime error (4) : unspecified launch failure at /pytorch/aten/src/THC/THCCachingHostAllocator.cpp:271 
```

[ Expected behavior ]:
my network is a multi-classification work. after this bug occured，i try to run my code again。now，my code is running correctly，but this prollem not be dealed。

[ environment ] 
pytorch 0.4.1
torchvision 0.2.2.post3
python 2.7
cuda 8.0
Ubuntu 16.04
GPU Tesla k80

**Comment by vishwakftw** [comment]
Please provide more details.

**Comment by encichou** [comment]
> Please provide more details.

thank you for you response， i have provided my bug detials

**Comment by vishwakftw** [comment]
Can you provide information as asked in the issue template? A reproduction script would also help reproduce the error.

**Comment by ezyang** [comment]
This bug report is for a pretty old version of PyTorch. Could you try upgrading at least to 1.1 and see if the problem persists?

**Comment by encichou** [comment]
> This bug report is for a pretty old version of PyTorch. Could you try upgrading at least to 1.1 and see if the problem persists?

thanks for your  advice , i haved not upgraded  my pytorch,  I will try your idea,

**Comment by encichou** [comment]
> This bug report is for a pretty old version of PyTorch. Could you try upgrading at least to 1.1 and see if the problem persists?

thanks ，I update my pytorch 1.0，now my error is finished

**Comment by Mulan337287** [comment]
Is there some solution can solve it without upgrade?

**Comment by smitheric95** [comment]
> Is there some solution can solve it without upgrade?

I was able to solve this problem on 0.4.1 by reinstalling NVIDIA drivers.

**Comment by JeremySun1224** [comment]
> > Is there some solution can solve it without upgrade?
> 
> I was able to solve this problem on 0.4.1 by reinstalling NVIDIA drivers.

Hello, may I ask you about your NVIDIA driver version?

**Comment by smitheric95** [comment]
> Hello, may I ask you about your NVIDIA driver version?

Of course!

Here are the versions reported by `nvidia-smi`:
```
NVIDIA-SMI 440.100
Driver Version: 440.100
CUDA Version: 10.2 
```

When using an older version of PyTorch, I use an anaconda environment that reports the following: 

```
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'0.4.1'
>>> torch.version.cuda
'9.2.148'
>>>
```

This works fine on my RTX series cards.

**Comment by JeremySun1224** [comment]
> > Hello, may I ask you about your NVIDIA driver version?
> 
> Of course!
> 
> Here are the versions reported by `nvidia-smi`:
> 
> ```
> NVIDIA-SMI 440.100
> Driver Version: 440.100
> CUDA Version: 10.2 
> ```
> 
> When using an older version of PyTorch, I use an anaconda environment that reports the following:
> 
> ```
> Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> >>> torch.__version__
> '0.4.1'
> >>> torch.version.cuda
> '9.2.148'
> >>>
> ```
> 
> This works fine on my RTX series cards.

WoW, thank you so much.👍
