### ISSUE TITLE
python setup.py install get error.subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBUILDING_WITH_TORCH_LIBS=ON', '-DBUILD_BINARY=False', '-DBUILD_CAFFE2_OPS=True', '-DBUILD_PYTHON=True', '-DBUILD_SHARED_LIBS=ON', '-DBUILD_TEST=True', '-DCAFFE2_STATIC_LINK_CUDA=False', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CXX_FLAGS= ', '-DCMAKE_C_FLAGS= ', '-DCMAKE_EXE_LINKER_FLAGS=', '-DCMAKE_INSTALL_PREFIX=/home/nudt302/pytorch/torch', '-DCMAKE_PREFIX_PATH=/home/nudt302/anaconda3/lib/python3.6/site-packages', '-DCMAKE_SHARED_LINKER_FLAGS=', '-DINSTALL_TEST=True', '-DNAMEDTENSOR_ENABLED=False', '-DNCCL_EXTERNAL=True',

### ISSUE THREAD

**Issue by yongqianxiao** [pytorch/pytorch#21901]
## 🐛 Bug

 - PyTorch Version (e.g., 1.0): the latest version
 - OS (e.g., Linux): 16.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: 1080ti
 - Any other relevant information: **mkl: 2018**
cmake: 3.14 was built through the source, and I can't find cmake with `conda list`, but I know the cmake version of anaconda is 3.11

## Additional context
When I installed pytorch through the source, I got errors.
my ops:
1. First, I uninstall the pytorch of anaconda3
```conda uninstall pytorch```
2. Then I install dependencies with conda
```conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing```
and `magma-cuda100`:
```conda install -c pytorch magma-cuda100```
3. I got the PyTorch Source:
```
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
# if you are updating an existing checkout
git submodule sync
git submodule update --init --recursive
```
4. Then I did the op:
```export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}```
And the fellow line raised a error:
```python setup.py install```
the details of the error:
```
(base) nudt302@nudt302robot:~/pytorch$ python setup.py install
Building wheel torch-1.2.0a0+d8314a6
-- Building version 1.2.0a0+d8314a6
cmake -GNinja -DBUILDING_WITH_TORCH_LIBS=ON -DBUILD_BINARY=False -DBUILD_CAFFE2_OPS=True -DBUILD_PYTHON=True -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=True -DCAFFE2_STATIC_LINK_CUDA=False -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=  -DCMAKE_C_FLAGS=  -DCMAKE_EXE_LINKER_FLAGS= -DCMAKE_INSTALL_PREFIX=/home/nudt302/pytorch/torch -DCMAKE_PREFIX_PATH=/home/nudt302/anaconda3/lib/python3.6/site-packages -DCMAKE_SHARED_LINKER_FLAGS= -DINSTALL_TEST=True -DNAMEDTENSOR_ENABLED=False -DNCCL_EXTERNAL=True -DNUMPY_INCLUDE_DIR=/usr/local/lib/python3.6/dist-packages/numpy/core/include -DONNX_ML=True -DONNX_NAMESPACE=onnx_torch -DPYTHON_EXECUTABLE=/home/nudt302/anaconda3/bin/python -DPYTHON_INCLUDE_DIR=/home/nudt302/anaconda3/include/python3.6m -DPYTHON_LIBRARY=/home/nudt302/anaconda3/lib/libpython3.6m.so.1.0 -DTHD_SO_VERSION=1 -DTORCH_BUILD_VERSION=1.2.0a0+d8314a6 -DUSE_ASAN=False -DUSE_CUDA=True -DUSE_DISTRIBUTED=True -DUSE_FBGEMM=True -DUSE_FFMPEG=False -DUSE_LEVELDB=False -DUSE_LMDB=False -DUSE_MKLDNN=True -DUSE_NCCL=True -DUSE_NNPACK=True -DUSE_NUMPY=True -DUSE_OPENCV=False -DUSE_QNNPACK=True -DUSE_ROCM=False -DUSE_SYSTEM_EIGEN_INSTALL=OFF -DUSE_SYSTEM_NCCL=False -DUSE_TENSORRT=False -DMKLDNN_ENABLE_CONCURRENT_EXEC=ON /home/nudt302/pytorch
-- The CXX compiler identification is Clang 6.0.0
-- The C compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Not forcing any particular BLAS to be found
-- Performing Test COMPILER_WORKS
-- Performing Test COMPILER_WORKS - Success
-- Performing Test SUPPORT_GLIBCXX_USE_C99
-- Performing Test SUPPORT_GLIBCXX_USE_C99 - Success
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED - Success
-- std::exception_ptr is supported.
-- Performing Test CAFFE2_IS_NUMA_AVAILABLE
-- Performing Test CAFFE2_IS_NUMA_AVAILABLE - Success
-- NUMA is available
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING - Failed
-- Turning off deprecation warning due to glog.
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS - Success
-- Current compiler supports avx2 extension. Will build perfkernels.
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512_EXTENSIONS - Success
-- Current compiler supports avx512f extension. Will build fbgemm.
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/home/nudt302/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- Trying to find preferred BLAS backend of choice: MKL
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
Traceback (most recent call last):
  File "setup.py", line 754, in <module>
    build_deps()
  File "setup.py", line 327, in build_deps
    cmake=cmake)
  File "/home/nudt302/pytorch/tools/build_pytorch_libs.py", line 61, in build_caffe2
    rerun_cmake)
  File "/home/nudt302/pytorch/tools/setup_helpers/cmake.py", line 342, in generate
    self.run(args, env=my_env)
  File "/home/nudt302/pytorch/tools/setup_helpers/cmake.py", line 110, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/nudt302/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBUILDING_WITH_TORCH_LIBS=ON', '-DBUILD_BINARY=False', '-DBUILD_CAFFE2_OPS=True', '-DBUILD_PYTHON=True', '-DBUILD_SHARED_LIBS=ON', '-DBUILD_TEST=True', '-DCAFFE2_STATIC_LINK_CUDA=False', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CXX_FLAGS= ', '-DCMAKE_C_FLAGS= ', '-DCMAKE_EXE_LINKER_FLAGS=', '-DCMAKE_INSTALL_PREFIX=/home/nudt302/pytorch/torch', '-DCMAKE_PREFIX_PATH=/home/nudt302/anaconda3/lib/python3.6/site-packages', '-DCMAKE_SHARED_LINKER_FLAGS=', '-DINSTALL_TEST=True', '-DNAMEDTENSOR_ENABLED=False', '-DNCCL_EXTERNAL=True', '-DNUMPY_INCLUDE_DIR=/usr/local/lib/python3.6/dist-packages/numpy/core/include', '-DONNX_ML=True', '-DONNX_NAMESPACE=onnx_torch', '-DPYTHON_EXECUTABLE=/home/nudt302/anaconda3/bin/python', '-DPYTHON_INCLUDE_DIR=/home/nudt302/anaconda3/include/python3.6m', '-DPYTHON_LIBRARY=/home/nudt302/anaconda3/lib/libpython3.6m.so.1.0', '-DTHD_SO_VERSION=1', '-DTORCH_BUILD_VERSION=1.2.0a0+d8314a6', '-DUSE_ASAN=False', '-DUSE_CUDA=True', '-DUSE_DISTRIBUTED=True', '-DUSE_FBGEMM=True', '-DUSE_FFMPEG=False', '-DUSE_LEVELDB=False', '-DUSE_LMDB=False', '-DUSE_MKLDNN=True', '-DUSE_NCCL=True', '-DUSE_NNPACK=True', '-DUSE_NUMPY=True', '-DUSE_OPENCV=False', '-DUSE_QNNPACK=True', '-DUSE_ROCM=False', '-DUSE_SYSTEM_EIGEN_INSTALL=OFF', '-DUSE_SYSTEM_NCCL=False', '-DUSE_TENSORRT=False', '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON', '/home/nudt302/pytorch']' died with <Signals.SIGSEGV: 11>.
```

This error have spent me 2 days, can someone help me to solve it? Thanks a lot. Thanks

**Comment by yongqianxiao** [comment]
@ezyang hello, could you have a look at this issue? Thank you.

**Comment by Rogerspy** [comment]
I have the same issue:

- OS (e.g., Linux): 18.04
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): python setup.py install
- Python version: 3.5

**Comment by yongqianxiao** [comment]
I solved the problem. If you have the same problem, have a look at the answer of @ezyang  [#16602](https://github.com/pytorch/pytorch/issues/16602).  

ezyang:  It's failing on a Werror, so if you can somehow force the gtest build to not build with `-Werror` that should also unblock you. So maybe try just deleting` -Werror` from` third_party/googletest/googletest/cmake/internal_utils.cmake` and see if that unblocks you.

```
gedit pytorch/third_party/googletest/googletest/cmake/internal_utils.cmake
# change this line:
set(cxx_base_flags "-Wall -Wshadow -Werror")
# to this line:
set(cxx_base_flags "-Wall -Wshadow")
```

** if the above solution didn't solve your problem, please check out if your g++ path is ok. `g++ -v`, if it says you didn't install g++, then you should reinstall g++**
