### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR in 1.1.0 

### ISSUE THREAD

**Issue by Moondra** [pytorch/pytorch#22050]
I am currently using Windows 7, Pytorch version 1.1.0, 
It seems from what I have read this error should have been fixed
in 1.1.0?

Here is the environment:

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 7 Professional
GCC version: (tdm64-1) 5.1.0

CMake version: version 3.7.0-rc1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 411.31
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip3] numpy==1.16.4

[pip3] torch==1.1.0

[pip3] torchsummary==1.5.1

[pip3] torchvision==0.3.0
[conda] Could not collect

Here is the traceback:

`Traceback (most recent call last):
  File "C:\Users\Moondra\Desktop\PYTORCH\PYTORCH BASICS\PYTORCH ENVIRONMENTS\PYTORCH STUFF\pytorch_test.py", line 191, in <module>
    num_epochs=3)
  File "C:\Users\Moondra\Desktop\PYTORCH\PYTORCH BASICS\PYTORCH ENVIRONMENTS\PYTORCH STUFF\pytorch_test.py", line 52, in train_model
    outputs = model(inputs)
  File "C:\Users\Moondra\Desktop\PYTORCH\PYTORC~1\PYTORC~2\test1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Moondra\Desktop\PYTORCH\PYTORC~1\PYTORC~2\test1\lib\site-packages\torchvision\models\densenet.py", line 119, in forward
    features = self.features(x)
  File "C:\Users\Moondra\Desktop\PYTORCH\PYTORC~1\PYTORC~2\test1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Moondra\Desktop\PYTORCH\PYTORC~1\PYTORC~2\test1\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\Moondra\Desktop\PYTORCH\PYTORC~1\PYTORC~2\test1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Moondra\Desktop\PYTORCH\PYTORC~1\PYTORC~2\test1\lib\site-packages\torch\nn\modules\conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR`

I have multiple versions of CUDA installed for compatibility
with Tensorflow, Keras and Pytorch.

Thank you. 

The script I am running is the `transfer learning` script using `Densenet`

https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html

**Comment by mrshenli** [comment]
@Moondra  Based on discussions in #16831 and 21819, this seems to be fixed in cudnn 7.6. Can you try upgrade your cudnn?

**Comment by Moondra** [comment]
Okay, will do and report back.

**Comment by Moondra** [comment]
I have multiple versions of CUDA so will need to do it on all of them. I did so on CUDA 9 (update cudnn), but so far no luck. I am assuming I need to do it on CUDA 10 as that's what's being used at runtime.

**Comment by Moondra** [comment]
I've updated it to 7.6 but I am still running into the same problem.
https://developer.nvidia.com/rdp/cudnn-download
For Cuda 10.
Extracted it and placed it in the CUDA 10 folder.

Any thing else I can try?

**Comment by mrshenli** [comment]
Hi @ngimel @mruberry, it seems the error fixed in #16831 occurs again. This is also reported in #21819. Do you have any thoughts on what might be the cause here?

**Comment by mruberry** [comment]
@ngimel @csarofeen since I’m no longer at Nvidia.

**Comment by ptrblck** [comment]
Hi @Moondra,

thanks for reporting this issue.
It seems you are using PyTorch binaries with CUDA 9 and also installed CUDA 10.0.130 locally.

If that's correct, placing the cudnn files in the local CUDA10 folder won't change the used cudnn version in the PyTorch binaries. You would need to build PyTorch from source to use your local CUDA and cudnn.

You could check the currently used cudnn version via `torch.backends.cudnn.version()`.

**Comment by Moondra** [comment]
Hi ptrblck,

I tried placing the cudnn file in CUDA9 directory as well (as far I can remember!) as I have multiple CUDA folders for compatibility with Keras (tf backend).   

At this path:
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA"

I have:

v8.0
v9.0
v10.0

I will try running the command you provided. Thank you so much for your help.

**Comment by Moondra** [comment]
Creating a new comment just incase edits don't notify:

I ran the command:

7005

**Comment by ptrblck** [comment]
@Moondra If you are using the PyTorch binaries, CUDA and cudnn will be shipped with these bins, so that you cannot simply copy the cudnn files to switch the version.
E.g. if you are running
```
conda install pytorch-nightly cudatoolkit=10.0 -c pytorch
```
you'll see something like
```
The following NEW packages will be INSTALLED:

  cudatoolkit        pkgs/main/linux-64::cudatoolkit-10.0.130-0
  ninja              pkgs/main/linux-64::ninja-1.9.0-py37hfd86e86_0
  pytorch-nightly    pytorch/linux-64::pytorch-nightly-1.2.0.dev20190805-py3.7_cuda10.0.130_cudnn7.6.2_0
```
which shows you that cudnn7.6.2_0 will be installed.
Could you try to run this command and check, if the error is still thrown?

**Comment by Moondra** [comment]
So sorry for the late reply. I am not using Conda, so I am assuming pip will suffice. 
Thank you.

**Comment by ptrblck** [comment]
Try to use this command from the [website](https://pytorch.org/get-started/locally/):
```
pip3 install torch torchvision
```

This should install PyTorch 1.2, CUDA10.0 for Python3.6 on a Linux OS.
Just select whatever config matches your current setup and use the shown install command.

**Comment by Moondra** [comment]
Everything is working perfectly now. Thank you so much for your help and patience.

**Comment by zhixuanli** [comment]
> Try to use this command from the [website](https://pytorch.org/get-started/locally/):
> 
> ```
> pip3 install torch torchvision
> ```
> 
> This should install PyTorch 1.2, CUDA10.0 for Python3.6 on a Linux OS.
> Just select whatever config matches your current setup and use the shown install command.

Hi, I have tried with this command, but still having this issue.

My environment:
+ CUDA: 10.0.130
+ cudnn : 7602
+ pytorch: 1.2.0, installed via pip
+ torchvision: 0.4.0 
+ python: 3.6.6
+ ubuntu 16.04
+ RTX 2080ti

@ptrblck 
Do you have any suggestions?
It has bothered me for many days.

Thanks!!
