### ISSUE TITLE
CUDA error: invalid configuration argument on MultivariateNormal

### ISSUE THREAD

**Issue by xymeng16** [pytorch/pytorch#22313]
## 🐛 Bug

I am trying to use `torch.distributions.MultivariateNormal` to sample some normal distributed noise. But when constructing the `MultivariateNormal` object I faced a strange problem, that is, when the dimension of the loc is larger than a certain value (like 170), the code will crash with CUDA error: invalid configuration argument.

## To Reproduce

My code is as follow:
```python
import torch 
from torch import distributions as tdist
```
and then
```python
m = tdist.MultivariateNormal(torch.zeros([170,128,3,3]).cuda(), (torch.eye(3)*3).cuda())
```
This line works well.
However, for the following two lines, the bug appears!
```python
m = tdist.MultivariateNormal(torch.zeros([170,128,4,3]).cuda(), (torch.eye(3)*3).cuda())
m = tdist.MultivariateNormal(torch.zeros([171,128,3,3]).cuda(), (torch.eye(3)*3).cuda())
```
The error infomation is like:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-53-71ee342b6686> in <module>
----> 1 m = tdist.MultivariateNormal(torch.zeros([170,127,4,3]).cuda(), (torch.eye(3)*3).cuda())

~/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/distributions/multivariate_normal.py in __init__(self, loc, covariance_matrix, precision_matrix, scale_tril, validate_args)
    140             if precision_matrix is not None:
    141                 self.covariance_matrix = torch.inverse(precision_matrix).expand_as(loc_)
--> 142             self._unbroadcasted_scale_tril = torch.cholesky(self.covariance_matrix)
    143 
    144     def expand(self, batch_shape, _instance=None):

RuntimeError: CUDA error: invalid configuration argument
```

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 418.56
cuDNN version: /usr/local/cuda-10.0/lib64/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.16.4
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl_fft                   1.0.12           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torchvision               0.3.0           py37_cu10.0.130_1    pytorch

**Comment by vishwakftw** [comment]
Thank you for the bug report.

I think this is because of broadcasting the mean and covariances. The number of covariance matrices becomes 170*127*4 which is greater than 65535, and v1.1.0 couldn’t handle triu / tril ops for these many matrices.

Installing a nightly build should solve this problem for you. Please let me know if that works out.

**Comment by xymeng16** [comment]
@vishwakftw What you state is where the problem exactly is! I upgraded to the nightly build and my problem was solved, thanks! But installing the corresponding version of torchvision for pytorch-nightly seems a little bit hard and I try several approaches before success... I hope the official guide would add the instruction for installing pytorch-nightly with torchvision!
Thanks!
