### ISSUE TITLE
Memory leak in Jupyter Nb when re-executing the same cell

### ISSUE THREAD

**Issue by sebastienwood** [pytorch/pytorch#22684]
## 🐛 Bug
When using a Jupyter Notebook, executing the same cell multiple times eventually leads to CUDA Out of memory. 

## To Reproduce

1. In a Jupyter notebook, define a cell which declares a network and executes the train/test cycle
2. Execute the cell multiple times
3. A CUDA Out of memory error is thrown at some point

## Expected behavior

Executing the same cell twice shouldn't increase the memory required

## Environment

PyTorch version: 1.0.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux release 7.6.1810 (Core) 
GCC version: (Homebrew gcc 5.5.0_4) 5.5.0
CMake version: version 3.13.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla P100-SXM2-16GB
GPU 1: Tesla P100-SXM2-16GB
GPU 2: Tesla P100-SXM2-16GB
GPU 3: Tesla P100-SXM2-16GB

Nvidia driver version: 396.37
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                intel_243    intel
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.12           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.0.1           cuda90py37h8b0c50b_0  
[conda] torchvision               0.2.2                      py_3    pytorch
[conda] torchviz                  0.0.1                    pypi_0    pypi

## Additional context

This happened across a few differents experiments that required me to re-run a particular cell in a Jupyter Notebook.

**Comment by ezyang** [comment]
I think this is an ipython problem, and not something we can fix. Take a look at https://ipython.org/ipython-doc/3/interactive/reference.html#output-caching-system for more details.

**Comment by scientist1642** [comment]
If you are using `conda` and you installed `jupyter` with pip, try to uninstall it and install it with `conda`.
Worked for me.
