### ISSUE TITLE
Script freezes with no output when using DistributedDataParallel

### ISSUE THREAD

**Issue by shoaibahmed** [pytorch/pytorch#22834]
## 🐛 Bug

I was trying to evaluate the performance of the system with static data but different models, batch sizes and AMP optimization levels. However, when using DDP, the script gets frozen at a random point. The GPU usage is stuck at 100% and the process is also using 100% CPU. I tried this on three different system configs but the error persists. I even tried the nightly version of PyTorch but it wasn't useful.

If I switch from NCCL backend to gloo backend, the code works, but very slow. I suspect that the problem might be with NCCL somehow.

Here is the NCCL log that I retrieved.

```
sas-desktop:26887:26887 [1] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
sas-desktop:26887:26910 [1] NCCL INFO Setting affinity for GPU 1 to 0fff
sas-desktop:26887:26910 [1] NCCL INFO comm 0x7fa4080022b0 rank 1 nranks 2 cudaDev 1 nvmlDev 1
sas-desktop:26886:26902 [0] NCCL INFO Channel 00 :    0   1
sas-desktop:26887:26910 [1] NCCL INFO Ring 00 : 1[1] -> 0[0] via direct shared memory
sas-desktop:26886:26902 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via direct shared memory
sas-desktop:26886:26902 [0] NCCL INFO Using 256 threads, Min Comp Cap 6, Trees disabled
sas-desktop:26886:26902 [0] NCCL INFO comm 0x7fbb380022b0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 - Init COMPLETE
sas-desktop:26886:26886 [0] NCCL INFO Launch mode Parallel
sas-desktop:26887:26910 [1] NCCL INFO comm 0x7fa4080022b0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 - Init COMPLETE
Time taken: 5.01 secs
sas-desktop:26886:26886 [0] NCCL INFO Destroyed comm 0x7fbb380022b0 rank 0
sas-desktop:26887:26887 [1] NCCL INFO Destroyed comm 0x7fa4080022b0 rank 1
Using batch size: 3
sas-desktop:26921:26921 [0] NCCL INFO NET/Socket : Using [0]eno1:10.110.39.89<0>
sas-desktop:26921:26921 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

sas-desktop:26921:26921 [0] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
NCCL version 2.4.2+cuda10.0
sas-desktop:26921:26949 [0] NCCL INFO Setting affinity for GPU 0 to 0fff
sas-desktop:26921:26949 [0] NCCL INFO comm 0x7f23100022b0 rank 0 nranks 2 cudaDev 0 nvmlDev 0
sas-desktop:26922:26922 [1] NCCL INFO NET/Socket : Using [0]eno1:10.110.39.89<0>
sas-desktop:26922:26922 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

sas-desktop:26922:26922 [1] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
sas-desktop:26922:26952 [1] NCCL INFO Setting affinity for GPU 1 to 0fff
sas-desktop:26922:26952 [1] NCCL INFO comm 0x7fc3940022b0 rank 1 nranks 2 cudaDev 1 nvmlDev 1
sas-desktop:26921:26949 [0] NCCL INFO Channel 00 :    0   1
sas-desktop:26922:26952 [1] NCCL INFO Ring 00 : 1[1] -> 0[0] via direct shared memory
sas-desktop:26921:26949 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via direct shared memory
sas-desktop:26921:26949 [0] NCCL INFO Using 256 threads, Min Comp Cap 6, Trees disabled
sas-desktop:26921:26949 [0] NCCL INFO comm 0x7f23100022b0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 - Init COMPLETE
sas-desktop:26921:26921 [0] NCCL INFO Launch mode Parallel
sas-desktop:26922:26952 [1] NCCL INFO comm 0x7fc3940022b0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 - Init COMPLETE
Time taken: 5.01 secs
sas-desktop:26921:26921 [0] NCCL INFO Destroyed comm 0x7f23100022b0 rank 0
sas-desktop:26922:26922 [1] NCCL INFO Destroyed comm 0x7fc3940022b0 rank 1
Using batch size: 4
sas-desktop:26967:26967 [0] NCCL INFO NET/Socket : Using [0]eno1:10.110.39.89<0>
sas-desktop:26967:26967 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

sas-desktop:26967:26967 [0] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
NCCL version 2.4.2+cuda10.0
sas-desktop:26967:26984 [0] NCCL INFO Setting affinity for GPU 0 to 0fff
sas-desktop:26967:26984 [0] NCCL INFO comm 0x7f3e4c0022b0 rank 0 nranks 2 cudaDev 0 nvmlDev 0
sas-desktop:26968:26968 [1] NCCL INFO NET/Socket : Using [0]eno1:10.110.39.89<0>
sas-desktop:26968:26968 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

sas-desktop:26968:26968 [1] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
sas-desktop:26968:26985 [1] NCCL INFO Setting affinity for GPU 1 to 0fff
sas-desktop:26968:26985 [1] NCCL INFO comm 0x7f28dc0022b0 rank 1 nranks 2 cudaDev 1 nvmlDev 1
sas-desktop:26967:26984 [0] NCCL INFO Channel 00 :    0   1
sas-desktop:26967:26984 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via direct shared memory
sas-desktop:26968:26985 [1] NCCL INFO Ring 00 : 1[1] -> 0[0] via direct shared memory
sas-desktop:26967:26984 [0] NCCL INFO Using 256 threads, Min Comp Cap 6, Trees disabled
sas-desktop:26967:26984 [0] NCCL INFO comm 0x7f3e4c0022b0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 - Init COMPLETE
sas-desktop:26967:26967 [0] NCCL INFO Launch mode Parallel
sas-desktop:26968:26985 [1] NCCL INFO comm 0x7f28dc0022b0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 - Init COMPLETE
Time taken: 5.01 secs
sas-desktop:26967:26967 [0] NCCL INFO Destroyed comm 0x7f3e4c0022b0 rank 0
```

I closed the script by Ctrl+C after an hour as it was stuck at this point. I also did a backtrace using GDB:

```
#0  0x00007ffd20ec5b62 in clock_gettime ()
#1  0x00007f243f141ea6 in __GI___clock_gettime (clock_id=4, tp=0x7ffd20e9f1e0) at ../sysdeps/unix/clock_gettime.c:115
#2  0x00007f23e1d2aa2e in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007f23e1dce807 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007f23e1d130ec in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007f23e1d13249 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007f23e1c1f051 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#7  0x00007f23e1d7dbc2 in cuStreamSynchronize () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#8  0x00007f23e465eb60 in ?? () from /home/ssiddiqui/anaconda3/lib/python3.7/site-packages/torch/lib/libcudart-1581fefa.so.10.0
#9  0x00007f23e469d61d in cudaStreamSynchronize () from /home/ssiddiqui/anaconda3/lib/python3.7/site-packages/torch/lib/libcudart-1581fefa.so.10.0
#10 0x00007f23f7625e6b in commDestroy (comm=0x7f23940022b0) at init.cu:1141
#11 ncclCommDestroy (comm=0x7f23940022b0) at init.cu:1158
#12 0x00007f242f0bcadb in std::_Sp_counted_ptr_inplace<c10d::NCCLComm, std::allocator<c10d::NCCLComm>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() ()
   from /home/ssiddiqui/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#13 0x00007f242f0bd11e in std::_Hashtable<std::string, std::pair<std::string const, std::vector<std::shared_ptr<c10d::NCCLComm>, std::allocator<std::shared_ptr<c10d::NCCLComm> > > >, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<c10d::NCCLComm>, std::allocator<std::shared_ptr<c10d::NCCLComm> > > > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::~_Hashtable() ()
   from /home/ssiddiqui/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#14 0x00007f242f0b5955 in c10d::ProcessGroupNCCL::~ProcessGroupNCCL() () from /home/ssiddiqui/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#15 0x00007f242f0b5a79 in c10d::ProcessGroupNCCL::~ProcessGroupNCCL() () from /home/ssiddiqui/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#16 0x00007f242ea94d82 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() () from /home/ssiddiqui/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#17 0x00007f242f02b50b in pybind11::class_<c10d::ProcessGroupNCCL, std::shared_ptr<c10d::ProcessGroupNCCL> >::dealloc(pybind11::detail::value_and_holder&) ()
   from /home/ssiddiqui/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#18 0x00007f242eaa5e67 in pybind11::detail::clear_instance(_object*) () from /home/ssiddiqui/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#19 0x00007f242eaa60be in pybind11_object_dealloc () from /home/ssiddiqui/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#20 0x000056111beb50ab in free_keys_object (keys=<optimized out>) at /tmp/build/80754af9/python_1553721932202/work/Objects/dictobject.c:559
#21 PyDict_Clear () at /tmp/build/80754af9/python_1553721932202/work/Objects/dictobject.c:1644
#22 0x000056111beb517a in dict_tp_clear (op=<optimized out>) at /tmp/build/80754af9/python_1553721932202/work/Objects/dictobject.c:2997
#23 0x000056111bed44a8 in delete_garbage (old=<optimized out>, collectable=<optimized out>) at /tmp/build/80754af9/python_1553721932202/work/Modules/gcmodule.c:761
#24 collect () at /tmp/build/80754af9/python_1553721932202/work/Modules/gcmodule.c:916
#25 0x000056111bfa21da in _PyGC_CollectNoFail () at /tmp/build/80754af9/python_1553721932202/work/Modules/gcmodule.c:1605
#26 0x000056111bf65650 in PyImport_Cleanup () at /tmp/build/80754af9/python_1553721932202/work/Python/import.c:579
#27 0x000056111bfd88a7 in Py_FinalizeEx () at /tmp/build/80754af9/python_1553721932202/work/Python/pylifecycle.c:1195
#28 0x000056111bff0c63 in pymain_main () at /tmp/build/80754af9/python_1553721932202/work/Modules/main.c:3040
#29 0x000056111bff0f7c in _Py_UnixMain () at /tmp/build/80754af9/python_1553721932202/work/Modules/main.c:3073
#30 0x00007f243f032b97 in __libc_start_main (main=0x56111beaced0 <main>, argc=9, argv=0x7ffd20e9fcf8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd20e9fce8)
    at ../csu/libc-start.c:310
#31 0x000056111bf96122 in _start () at ../sysdeps/x86_64/elf/start.S:103
```

## To Reproduce

1. Download the script: https://gist.github.com/shoaibahmed/1b4bdaf5fdadfc80427b90a32eaa3053
2. Evaluate using a simple script as follows:

```bash
for bs in {1..30}; do
    echo "Using batch size: $bs"
    NCCL_DEBUG=INFO python3 -m torch.distributed.launch --nproc_per_node=2 python ./benchmark.py --mname=resnet18 --numgpus=2 --batchsize=$bs --amp=O4 --distributed
done
```

The error is non-deterministic, so might not be reproduced on the first run. Please run it again and again if you are unable to reproduce it.

## Expected behavior

The script should have been executed until the end. However, the script gets stuck at some random position where one of the processes is closed by the system, but the other one is still running waiting for the others. I tried with both APEX DDP and PyTorch DDP and the error persists.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: TITAN Xp

Nvidia driver version: 418.56
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.1

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[pip] torch==1.1.0
[pip] torch-encoding==1.0.1
[pip] torchgpipe==0.0.2
[pip] torchsummary==1.5.1
[pip] torchtrainers==0.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      199  
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] torch                     1.1.0                    pypi_0    pypi
[conda] torch-encoding            1.0.1                    pypi_0    pypi
[conda] torchgpipe                0.0.2                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchtrainers             0.0                      pypi_0    pypi
[conda] torchvision               0.3.0                    pypi_0    pypi

**Comment by JoeriHermans** [comment]
Are you using .item() somewhere in your training-loop? I have the exact same symptoms when using DataParallel. My code always hangs at epoch 95. I have no idea why. This is my `gdb` stacktrace:

```
gdb -p [pid]

(gdb) bt
#0  0x00007ffecf4eb6c2 in clock_gettime ()
#1  0x00007fa7455edc6d in __GI___clock_gettime (clock_id=<optimized out>, tp=<optimized out>) at ../sysdeps/unix/clock_gettime.c:115
#2  0x00007fa6e8ae3f4e in ?? () from /lib64/libcuda.so.1
#3  0x00007fa6e8b99807 in ?? () from /lib64/libcuda.so.1
#4  0x00007fa6e8bbb474 in ?? () from /lib64/libcuda.so.1
#5  0x00007fa6e8abd5cd in ?? () from /lib64/libcuda.so.1
#6  0x00007fa6e89ca88e in ?? () from /lib64/libcuda.so.1
#7  0x00007fa6e89cd9b3 in ?? () from /lib64/libcuda.so.1
#8  **0x00007fa6e8b454f2 in cuMemcpyDtoHAsync_v2 () from /lib64/libcuda.so.1**
#9  0x00007fa70012b34f in ?? () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/../../../../libcudart.so.10.0
#10 0x00007fa700108643 in ?? () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/../../../../libcudart.so.10.0
#11 **0x00007fa700146af8 in cudaMemcpyAsync () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/../../../../libcudart.so.10.0**
#12 0x00007fa70dc7ae40 in at::native::_local_scalar_dense_cuda(at::Tensor const&)::{lambda()#1}::operator()() const ()
   from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so
#13 0x00007fa70dc7d447 in at::native::_local_scalar_dense_cuda(at::Tensor const&) () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so
#14 0x00007fa70c84dac2 in at::CUDAType::_local_scalar_dense(at::Tensor const&) const () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so
#15 0x00007fa700b9da61 in torch::autograd::VariableType::_local_scalar_dense(at::Tensor const&) const ()
   from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libtorch.so.1
#16 0x00007fa708bbc89a in at::native::item(at::Tensor const&) () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#17 0x00007fa708ec6d85 in at::TypeDefault::item(at::Tensor const&) const () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libcaffe2.so
#18 **0x00007fa700d9161c in torch::autograd::VariableType::item(at::Tensor const&) const () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libtorch.so.1** <- .item()
#19 0x00007fa737426b06 in torch::autograd::dispatch_to_CDouble(at::Tensor const&) () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#20 0x00007fa737426f56 in torch::autograd::THPVariable_item(_object*, _object*) () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#21 0x000055bf518005c1 in _PyMethodDef_RawFastCallKeywords () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:629
#22 0x000055bf5180086f in _PyMethodDescr_FastCallKeywords () at /tmp/build/80754af9/python_1553721932202/work/Objects/descrobject.c:288
#23 0x000055bf5185c07c in call_function (kwnames=0x0, oparg=1, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4593
#24 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3110
#25 0x000055bf517ff79b in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>)
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:283
#26 _PyFunction_FastCallKeywords () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:408
#27 0x000055bf51857846 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#28 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#29 0x000055bf517ff79b in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>)
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:283
#30 _PyFunction_FastCallKeywords () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:408
#31 0x000055bf51857846 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#32 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#33 0x000055bf5179d4f9 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#34 0x000055bf5179e3c4 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3959
#35 0x000055bf5179e3ec in PyEval_EvalCode (co=co@entry=0x7fa745b634b0, globals=globals@entry=0x7fa745bd3678, locals=locals@entry=0x7fa745bd3678)```

**Comment by shoaibahmed** [comment]
@JoeriHermans I have already tried this fix, but no luck for me. My problem is related to comm release in NCCL. You can refer to my code and give it a try. You should be able to reproduce it. I have also updated my issue with the backtrace information.

**Comment by pietern** [comment]
@shoaibahmed The communicator is not released because some kernel is still running / is stuck. This is likely caused by a desynchronization between your processes, such that one of them has executed N kernels and exits, and the other tries to execute N+1 kernels and hangs infinitely. Please double check the number of calls to forward and backward in each process, and correspondingly the number of broadcast and allreduce calls.

**Comment by shoaibahmed** [comment]
@pietern I double-checked. There is no desynchronization between the threads. If there had been any desynchronization, gloo backend would also have failed. However, it executes without any issues. Here is the main training loop from the code. I don't see any desynchronization. If you are sure that this is the case, can you please look at the code and point it out.

for trial in range(maxtrials):
    if inference:
        with torch.no_grad():
            ys = model(xs)
    else:
        optimizer.zero_grad()
        ys = model(xs)
        loss = criterion(ys, targets)
        if amp_level is not None:
            with amp.scale_loss(loss, optimizer) as scaled_loss:
                scaled_loss.backward()
        else:
            loss.backward()
        optimizer.step()

    finish = time.time()

    if finish-start >= mintime and trial >= mintrials:
        break

**Comment by shoaibahmed** [comment]
I am running multiple training sessions, one after the other. Can that lead to any kind of issues?
The complete code along with the execution script is available in the main issue section.

**Comment by pietern** [comment]
You have timing code in there. It is possible that one process exits before the other one, causing the hang.

If you do want to rely on timing, make sure to use timing information from a single process by broadcasting it, instead of having each process take its own measurements. With the snippet you posted it is possible for one process to break out of the loop before others do.

**Comment by shoaibahmed** [comment]
Thanks @pietern. Let me confirm if the timing code is indeed the one causing this desynchronization between the processes.

**Comment by shoaibahmed** [comment]
@pietern It was indeed the timing that was causing process desynchronization. Thanks for your help in this regard. I am closing the issue now.

**Comment by pietern** [comment]
Glad to hear this is resolved.

**Comment by hitvoice** [comment]
@shoaibahmed will adding `torch.distributed.barrier()` after time.time() help in this case?

**Comment by pldelisle** [comment]
I have kind of the same problem.

After every epoch, I have to reconstruct three 3D volume by making a forward pass on two consecutive models. These reconstructions can take over 30 minutes to do (thousands of patches to infer). Only process `rank==0` is doing it, other with `rank>0` should theoretically  be waiting. Except that the processes just seem to hang forever, which result in a `Runtime Error: Socket timeout`.

I have already tried to increase the timeout of `torch.distributed.init_process_group`, but without luck.

Do you guys think of any way the processes with `rank>0` could just be waiting and everything restart when reconstruction is done on `rank=0`? Already tried a `torch.distributed.barrier()` too but seems to halt the process forever too.

Thanks.

**Comment by shoaibahmed** [comment]
> @shoaibahmed will adding `torch.distributed.barrier()` after time.time() help in this case?

Yes, but that will slow down the process. Since I was doing some benchmarking, I instead decided to fix the number of iterations.

**Comment by shoaibahmed** [comment]
> I have kind of the same problem.
> 
> After every epoch, I have to reconstruct three 3D volume by making a forward pass on two consecutive models. These reconstructions can take over 30 minutes to do (thousands of patches to infer). Only process `rank==0` is doing it, other with `rank>0` should theoretically be waiting. Except that the processes just seem to hang forever, which result in a `Runtime Error: Socket timeout`.
> 
> I have already tried to increase the timeout of `torch.distributed.init_process_group`, but without luck.
> 
> Do you guys think of any way the processes with `rank>0` could just be waiting and everything restart when reconstruction is done on `rank=0`? Already tried a `torch.distributed.barrier()` too but seems to halt the process forever too.
> 
> Thanks.

Can you please share a code snippet that will help in the identification of the error?

**Comment by nkatebi** [comment]
I have a same problem. I've tried the script benchmark.py. Here is the error:
![Screenshot from 2020-08-13 11-34-39](https://user-images.githubusercontent.com/25439624/90155550-78660080-dd59-11ea-94aa-4e1908cf2aa7.png)

**Comment by shoaibahmed** [comment]
> I have the same problem. I've tried the script benchmark.py. Here is the error:
> Does anyone have a suggestion to solve the problem?
> ![Screenshot from 2020-08-13 11-34-39](https://user-images.githubusercontent.com/25439624/90155550-78660080-dd59-11ea-94aa-4e1908cf2aa7.png)

Can you please provide more details e.g. how you are running the script etc.? This seems to be an issue with the command you are using.

**Comment by nkatebi** [comment]
I'm using 2 GPUs and  I've used the code in "To Reproduce" part which is for evaluation. I had the same error in runpy.py when I used the distributed PyTorch in another script.

**Comment by gemfield** [comment]
Env:
- Ubuntu 18.04
- Pytorch 1.6.0
- CUDA 10.1

Actually, I am using Docker image gemfield/pytorch:1.6.0-devel which stated in https://github.com/DeepVAC/deepvac (same with above env), and use PyTorch DDP (by use the class DeepvacDDP in https://github.com/DeepVAC/deepvac/blob/master/deepvac/syszux_deepvac.py) to train my model, which the code worked perfect yesterday. But today when I launch the train program again, the DDP is stucked in loss.backward()， with cpu 100% and GPU 100%。
There has no code change and docker container change since yesterday, except the Ubuntu host got a system update today:
```bash
gemfield@ai03:~$ cat /var/log/apt/history.log | grep -C 3 nvidia

Start-Date: 2020-09-03  06:44:01
Commandline: /usr/bin/unattended-upgrade
Install: linux-modules-nvidia-440-5.4.0-45-generic:amd64 (5.4.0-45.49, automatic)
Upgrade: linux-modules-nvidia-440-generic-hwe-20.04:amd64 (5.4.0-42.46, 5.4.0-45.49)
End-Date: 2020-09-03  06:44:33
```
Obviously, the nvidia driver got update from 440.64 to 440.100, and I think these info may be useful for somebody.

**Comment by nomadlx** [comment]
> 您是否在训练循环中的某处使用.item（）？使用DataParallel时，我有完全相同的症状。我的代码总是挂在纪元95。我不知道为什么。这是我的`gdb`堆栈跟踪：
> 
> ```
> gdb -p [pid]
> 
> (gdb) bt
> #0  0x00007ffecf4eb6c2 in clock_gettime ()
> #1  0x00007fa7455edc6d in __GI___clock_gettime (clock_id=<optimized out>, tp=<optimized out>) at ../sysdeps/unix/clock_gettime.c:115
> #2  0x00007fa6e8ae3f4e in ?? () from /lib64/libcuda.so.1
> #3  0x00007fa6e8b99807 in ?? () from /lib64/libcuda.so.1
> #4  0x00007fa6e8bbb474 in ?? () from /lib64/libcuda.so.1
> #5  0x00007fa6e8abd5cd in ?? () from /lib64/libcuda.so.1
> #6  0x00007fa6e89ca88e in ?? () from /lib64/libcuda.so.1
> #7  0x00007fa6e89cd9b3 in ?? () from /lib64/libcuda.so.1
> #8  **0x00007fa6e8b454f2 in cuMemcpyDtoHAsync_v2 () from /lib64/libcuda.so.1**
> #9  0x00007fa70012b34f in ?? () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/../../../../libcudart.so.10.0
> #10 0x00007fa700108643 in ?? () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/../../../../libcudart.so.10.0
> #11 **0x00007fa700146af8 in cudaMemcpyAsync () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/../../../../libcudart.so.10.0**
> #12 0x00007fa70dc7ae40 in at::native::_local_scalar_dense_cuda(at::Tensor const&)::{lambda()#1}::operator()() const ()
>    from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so
> #13 0x00007fa70dc7d447 in at::native::_local_scalar_dense_cuda(at::Tensor const&) () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so
> #14 0x00007fa70c84dac2 in at::CUDAType::_local_scalar_dense(at::Tensor const&) const () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so
> #15 0x00007fa700b9da61 in torch::autograd::VariableType::_local_scalar_dense(at::Tensor const&) const ()
>    from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libtorch.so.1
> #16 0x00007fa708bbc89a in at::native::item(at::Tensor const&) () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libcaffe2.so
> #17 0x00007fa708ec6d85 in at::TypeDefault::item(at::Tensor const&) const () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libcaffe2.so
> #18 **0x00007fa700d9161c in torch::autograd::VariableType::item(at::Tensor const&) const () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libtorch.so.1** <- .item()
> #19 0x00007fa737426b06 in torch::autograd::dispatch_to_CDouble(at::Tensor const&) () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
> #20 0x00007fa737426f56 in torch::autograd::THPVariable_item(_object*, _object*) () from /home/jhermans/Anaconda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
> #21 0x000055bf518005c1 in _PyMethodDef_RawFastCallKeywords () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:629
> #22 0x000055bf5180086f in _PyMethodDescr_FastCallKeywords () at /tmp/build/80754af9/python_1553721932202/work/Objects/descrobject.c:288
> #23 0x000055bf5185c07c in call_function (kwnames=0x0, oparg=1, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4593
> #24 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3110
> #25 0x000055bf517ff79b in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>)
>     at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:283
> #26 _PyFunction_FastCallKeywords () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:408
> #27 0x000055bf51857846 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
> #28 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
> #29 0x000055bf517ff79b in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>)
>     at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:283
> #30 _PyFunction_FastCallKeywords () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:408
> #31 0x000055bf51857846 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
> #32 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
> #33 0x000055bf5179d4f9 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
> #34 0x000055bf5179e3c4 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3959
> #35 0x000055bf5179e3ec in PyEval_EvalCode (co=co@entry=0x7fa745b634b0, globals=globals@entry=0x7fa745bd3678, locals=locals@entry=0x7fa745bd3678)
> ```
> 
> 调试此问题非常烦人，因为要花一天的时间才能达到目的。
> 
> 这可能是相关的，将尝试此“修复”。[＃20630](https://github.com/pytorch/pytorch/issues/20630)

I ran into exactly the same bug, and has the same GDB stack, but I didn't use `.item` in my code

The link you provided doesn't seem very relevant to our error because original code seems to work well (the code that caused this bug was the one I changed)

I feel the bug is caused by `if` statement, but it will take long time to confirm (this problem is really hard to repeat), is there a similar statement in your code?

I don't know why is that the GDB stack shows an asynchronous copy operation (`cuMemcpyDtoHAsync`), but other processes are hanging around waiting for it.

**Comment by eslambakr** [comment]
For me it was solved after removing tqdm.

**Comment by TAOSHss** [comment]
> 环境：
> 
> * Ubuntu 18.04
> * 火炬 1.6.0
> * 杂项 10.1
> 
> 实际上，我使用的是https://github.com/DeepVAC/deepvac中所述的 Docker 映像 gemfield/pytorch:1.6.0-devel （与上述环境相同），并使用 PyTorch DDP（通过使用[https 中的 DeepvacDDP 类： //github.com/DeepVAC/deepvac/blob/master/deepvac/syszux_deepvac.py](https://github.com/DeepVAC/deepvac/blob/master/deepvac/syszux_deepvac.py)）来训练我的模型，该代码昨天运行良好。但是今天再次启动train程序时，DDP卡在loss.backward()中，cpu 100%，GPU 100%。 从昨天开始没有代码变化和docker容器变化，除了Ubuntu主机得到了系统更新今天：
> 
> ```shell
> gemfield@ai03:~$ cat /var/log/apt/history.log | grep -C 3 nvidia
> 
> Start-Date: 2020-09-03  06:44:01
> Commandline: /usr/bin/unattended-upgrade
> Install: linux-modules-nvidia-440-5.4.0-45-generic:amd64 (5.4.0-45.49, automatic)
> Upgrade: linux-modules-nvidia-440-generic-hwe-20.04:amd64 (5.4.0-42.46, 5.4.0-45.49)
> End-Date: 2020-09-03  06:44:33
> ```
> 
> 显然，nvidia 驱动程序从 440.64 更新到 440.100，我认为这些信息可能对某些人有用。



> Env:
> 
> * Ubuntu 18.04
> * Pytorch 1.6.0
> * CUDA 10.1
> 
> Actually, I am using Docker image gemfield/pytorch:1.6.0-devel which stated in https://github.com/DeepVAC/deepvac (same with above env), and use PyTorch DDP (by use the class DeepvacDDP in https://github.com/DeepVAC/deepvac/blob/master/deepvac/syszux_deepvac.py) to train my model, which the code worked perfect yesterday. But today when I launch the train program again, the DDP is stucked in loss.backward()， with cpu 100% and GPU 100%。 There has no code change and docker container change since yesterday, except the Ubuntu host got a system update today:
> 
> ```shell
> gemfield@ai03:~$ cat /var/log/apt/history.log | grep -C 3 nvidia
> 
> Start-Date: 2020-09-03  06:44:01
> Commandline: /usr/bin/unattended-upgrade
> Install: linux-modules-nvidia-440-5.4.0-45-generic:amd64 (5.4.0-45.49, automatic)
> Upgrade: linux-modules-nvidia-440-generic-hwe-20.04:amd64 (5.4.0-42.46, 5.4.0-45.49)
> End-Date: 2020-09-03  06:44:33
> ```
> 
> Obviously, the nvidia driver got update from 440.64 to 440.100, and I think these info may be useful for somebody.

I had the same problem, 
> * Ubuntu 18.04
> * Pytorch 1.5.0
> * CUDA 10.1
the DDP is stucked in loss.backward()， with cpu 100% and GPU 100%。 There has no code change and docker container change

**Comment by dlfld** [comment]
多机多卡训练卡住，超时 然后报错
一直卡在这一行代码
`model = torch.nn.parallel.DistributedDataParallel(model,find_unused_parameters=True)  `
希望有能够解决这个问题的大佬帮助一下，跪谢

**Comment by TAOSHss** [comment]
> 

这一行代码可能不是最关键的；或者你加入参数device_ids，output_device并把find_unused_parameters改为False

**Comment by TAOSHss** [comment]
哦多多服务器我不太懂，我都说单机多卡



---Original---
From: ***@***.***&gt;
Date: Tue, Oct 11, 2022 21:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pytorch/pytorch] Script freezes with no output when usingDistributedDataParallel (#22834)




 
非常感谢🙏，可是我设置之后还是卡住了，我用的是两台服务器一台服务器GPU是3070，CUDA Version: 11.7 另一台服务器GPU是2080ti，    CUDA Version: 11.7 还是卡在这一行代码。
    model = torch.nn.parallel.DistributedDataParallel(model,find_unused_parameters=False,output_device=None,device_ids=None)

**Comment by dlfld** [comment]
好的 还是谢谢你

**Comment by nomadlx** [comment]
> 多机多卡训练卡住，超时 然后报错 一直卡在这一行代码 `model = torch.nn.parallel.DistributedDataParallel(model,find_unused_parameters=True) ` 希望有能够解决这个问题的大佬帮助一下，跪谢

试一下减少`--max-tokens`，我在之前的实践中发现这个过大会导致卡住。

**Comment by dlfld** [comment]
现在我的代码是这样的
在两台服务器上运行的命令是`python mnsit.py  --rank=0 --world-size=2`
`python mnsit.py  --rank=1 --world-size=2`
还是卡在 `model = torch.nn.parallel.DistributedDataParallel(model,find_unused_parameters=False,output_device=None,device_ids=None)  `

这一行代码，恳请各位大佬帮我看一下，已经在这里卡了好几天了，一直改不好。
`
from __future__ import print_function
import argparse
import time
 
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
 
import torch.distributed as dist
import torch.utils.data
import torch.utils.data.distributed
 
 
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5, 1)
        self.conv2 = nn.Conv2d(20, 50, 5, 1)
        self.fc1 = nn.Linear(4 * 4 * 50, 500)
        self.fc2 = nn.Linear(500, 10)
 
    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2, 2)
        x = x.view(-1, 4 * 4 * 50)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x)
 
 
def train(args, model, device, train_loader, optimizer, epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % args.log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                       100. * batch_idx / len(train_loader), loss.item()))
 
 
def test(args, model, device, test_loader):
    model.eval()
    test_loss = 0
    correct = 0
    for data, target in test_loader:
        data, target = data.to(device), target.to(device)
        output = model(data)
        test_loss += F.nll_loss(output, target, size_average=False).item()  # sum up batch loss
        pred = output.data.max(1, keepdim=True)[1]  # get the index of the max log-probability
        correct += pred.eq(target.data.view_as(pred)).cpu().sum()
 
    test_loss /= len(test_loader.dataset)
 
    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))
 
 
def main():
    # Training settings
    parser = argparse.ArgumentParser(description='PyTorch MNIST Example')
    parser.add_argument('--batch-size', type=int, default=64, metavar='N',
                        help='input batch size for training (default: 64)')
    parser.add_argument('--test-batch-size', type=int, default=1000, metavar='N',
                        help='input batch size for testing (default: 1000)')
    parser.add_argument('--epochs', type=int, default=10, metavar='N',
                        help='number of epochs to train (default: 10)')
    parser.add_argument('--lr', type=float, default=0.01, metavar='LR',
                        help='learning rate (default: 0.01)')
    parser.add_argument('--momentum', type=float, default=0.5, metavar='M',
                        help='SGD momentum (default: 0.5)')
    parser.add_argument('--no-cuda', action='store_true',
                        help='disables CUDA training')
    parser.add_argument('--seed', type=int, default=1, metavar='S',
                        help='random seed (default: 1)')
    parser.add_argument('--log-interval', type=int, default=500, metavar='N',
                        help='how many batches to wait before logging training status')
 
    parser.add_argument('--init-method', type=str, default='tcp://10.23.65.200:8888')
    parser.add_argument('--rank', type=int)
    parser.add_argument('--world-size', type=int)
 
    args = parser.parse_args()

 
    # 初始化
    dist.init_process_group(init_method=args.init_method, backend="nccl", world_size=args.world_size, rank=args.rank,
                            group_name="pytorch_test")
    use_cuda = not args.no_cuda and torch.cuda.is_available()
    print(args)
    torch.manual_seed(args.seed)
    if use_cuda:
        torch.cuda.manual_seed(args.seed)
 
    train_dataset = datasets.MNIST('./data', train=True, download=False,
                                   transform=transforms.Compose([
                                       transforms.ToTensor(),
                                       transforms.Normalize((0.1307,), (0.3081,))
                                   ]))
    # 分发数据
    train_sampler = torch.utils.data.distributed.DistributedSampler(train_dataset)
 
    kwargs = {'num_workers': 5, 'pin_memory': True} if use_cuda else {}
 
    train_loader = torch.utils.data.DataLoader(train_dataset,
                                               batch_size=args.batch_size, shuffle=False, **kwargs)
 
    test_loader = torch.utils.data.DataLoader(
        datasets.MNIST('data', train=False, transform=transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307,), (0.3081,))
        ])),
        batch_size=args.test_batch_size, shuffle=True, **kwargs)
 
    device = torch.device("cuda" if use_cuda else "cpu")
    print(device)
    model = Net().to(device)

    if use_cuda:
        
        if use_cuda:
            print(" model = torch.nn.parallel.DistributedDataParallel(model,find_unused_parameters=True) start ")
            # output_device(int或者torch.device) -单设备 CUDA 模块的输出设备位置。对于多设备模块和 CPU 模块，它必须是 None ，并且模块本身决定了输出位置。 (默认：device_ids[0] 用于单设备模块)
            # CUDA 设备。 1)对于单设备模块，device_ids可以只包含一个设备id，代表该进程对应的输入模块所在的唯一CUDA设备。或者，device_ids 也可以是 None 。 2) 对于多设备模块和 CPU 模块，device_ids 必须为 None 。
            model = torch.nn.parallel.DistributedDataParallel(model,find_unused_parameters=False,output_device=None,device_ids=None)  
            print(" model = torch.nn.parallel.DistributedDataParallel(model,find_unused_parameters=True) end ")
        else:
            model = torch.nn.parallel.DistributedDataParallelCPU(model)
        # torch.nn.parallel.DistributedDataParallelCPU(model)
        print("model = torch.nn.parallel.DistributedDataParallel(model) if use_cuda else torch.nn.parallel.DistributedDataParallelCPU(model) end")
 
    optimizer = optim.SGD(model.parameters(), lr=args.lr, momentum=args.momentum)
 
    total_time = 0
    for epoch in range(1, args.epochs + 1):
        # 设置epoch位置，这应该是个为了同步所做的工作
        train_sampler.set_epoch(epoch)
 
        start_cpu_secs = time.time()
        train(args, model, device, train_loader, optimizer, epoch)
        end_cpu_secs = time.time()
 
        print("Epoch {} of {} took {:.3f}s".format(
            epoch, args.epochs, end_cpu_secs - start_cpu_secs))
        total_time += end_cpu_secs - start_cpu_secs
 
        test(args, model, device, test_loader)
 
    print("Total time= {:.3f}s".format(total_time))
 
 
if __name__ == '__main__':
    main()
`

**Comment by dlfld** [comment]
`from __future__ import print_function
import argparse
import time
 
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
 
import torch.distributed as dist
import torch.utils.data
import torch.utils.data.distributed
 
 
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5, 1)
        self.conv2 = nn.Conv2d(20, 50, 5, 1)
        self.fc1 = nn.Linear(4 * 4 * 50, 500)
        self.fc2 = nn.Linear(500, 10)
 
    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2, 2)
        x = x.view(-1, 4 * 4 * 50)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x)
 
 
def train(args, model, device, train_loader, optimizer, epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % args.log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                       100. * batch_idx / len(train_loader), loss.item()))
 
 
def test(args, model, device, test_loader):
    model.eval()
    test_loss = 0
    correct = 0
    for data, target in test_loader:
        data, target = data.to(device), target.to(device)
        output = model(data)
        test_loss += F.nll_loss(output, target, size_average=False).item()  # sum up batch loss
        pred = output.data.max(1, keepdim=True)[1]  # get the index of the max log-probability
        correct += pred.eq(target.data.view_as(pred)).cpu().sum()
 
    test_loss /= len(test_loader.dataset)
 
    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))
 
 
def main():
    # Training settings
    parser = argparse.ArgumentParser(description='PyTorch MNIST Example')
    parser.add_argument('--batch-size', type=int, default=64, metavar='N',
                        help='input batch size for training (default: 64)')
    parser.add_argument('--test-batch-size', type=int, default=1000, metavar='N',
                        help='input batch size for testing (default: 1000)')
    parser.add_argument('--epochs', type=int, default=10, metavar='N',
                        help='number of epochs to train (default: 10)')
    parser.add_argument('--lr', type=float, default=0.01, metavar='LR',
                        help='learning rate (default: 0.01)')
    parser.add_argument('--momentum', type=float, default=0.5, metavar='M',
                        help='SGD momentum (default: 0.5)')
    parser.add_argument('--no-cuda', action='store_true',
                        help='disables CUDA training')
    parser.add_argument('--seed', type=int, default=1, metavar='S',
                        help='random seed (default: 1)')
    parser.add_argument('--log-interval', type=int, default=500, metavar='N',
                        help='how many batches to wait before logging training status')
 
    parser.add_argument('--init-method', type=str, default='tcp://10.23.65.200:8888')
    parser.add_argument('--rank', type=int)
    parser.add_argument('--world-size', type=int)
 
    args = parser.parse_args()

 
    # 初始化
    dist.init_process_group(init_method=args.init_method, backend="nccl", world_size=args.world_size, rank=args.rank,
                            group_name="pytorch_test")
    use_cuda = not args.no_cuda and torch.cuda.is_available()
    print(args)
    torch.manual_seed(args.seed)
    if use_cuda:
        torch.cuda.manual_seed(args.seed)
 
    train_dataset = datasets.MNIST('./data', train=True, download=False,
                                   transform=transforms.Compose([
                                       transforms.ToTensor(),
                                       transforms.Normalize((0.1307,), (0.3081,))
                                   ]))
    # 分发数据
    train_sampler = torch.utils.data.distributed.DistributedSampler(train_dataset)
 
    kwargs = {'num_workers': 5, 'pin_memory': True} if use_cuda else {}
 
    train_loader = torch.utils.data.DataLoader(train_dataset,
                                               batch_size=args.batch_size, shuffle=False, **kwargs)
 
    test_loader = torch.utils.data.DataLoader(
        datasets.MNIST('data', train=False, transform=transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307,), (0.3081,))
        ])),
        batch_size=args.test_batch_size, shuffle=True, **kwargs)
 
    device = torch.device("cuda" if use_cuda else "cpu")
    print(device)
    model = Net().to(device)

    if use_cuda:
        
        if use_cuda:
            print(" model = torch.nn.parallel.DistributedDataParallel(model,find_unused_parameters=True) start ")
            # output_device(int或者torch.device) -单设备 CUDA 模块的输出设备位置。对于多设备模块和 CPU 模块，它必须是 None ，并且模块本身决定了输出位置。 (默认：device_ids[0] 用于单设备模块)
            # CUDA 设备。 1)对于单设备模块，device_ids可以只包含一个设备id，代表该进程对应的输入模块所在的唯一CUDA设备。或者，device_ids 也可以是 None 。 2) 对于多设备模块和 CPU 模块，device_ids 必须为 None 。
            model = torch.nn.parallel.DistributedDataParallel(model,find_unused_parameters=False,output_device=None,device_ids=None)  
            print(" model = torch.nn.parallel.DistributedDataParallel(model,find_unused_parameters=True) end ")
        else:
            model = torch.nn.parallel.DistributedDataParallelCPU(model)
        # torch.nn.parallel.DistributedDataParallelCPU(model)
        print("model = torch.nn.parallel.DistributedDataParallel(model) if use_cuda else torch.nn.parallel.DistributedDataParallelCPU(model) end")
 
    optimizer = optim.SGD(model.parameters(), lr=args.lr, momentum=args.momentum)
 
    total_time = 0
    for epoch in range(1, args.epochs + 1):
        # 设置epoch位置，这应该是个为了同步所做的工作
        train_sampler.set_epoch(epoch)
 
        start_cpu_secs = time.time()
        train(args, model, device, train_loader, optimizer, epoch)
        end_cpu_secs = time.time()
 
        print("Epoch {} of {} took {:.3f}s".format(
            epoch, args.epochs, end_cpu_secs - start_cpu_secs))
        total_time += end_cpu_secs - start_cpu_secs
 
        test(args, model, device, test_loader)
 
    print("Total time= {:.3f}s".format(total_time))
 
 
if __name__ == '__main__':
    main()`

**Comment by dlfld** [comment]
> 

非常感谢🙏 我想问一下这个参数是在哪儿设置的呢？
`--max-tokens`

**Comment by orangewcz2000** [comment]
> > 
> 
> 非常感谢🙏 我想问一下这个参数是在哪儿设置的呢？ `--max-tokens`



> 现在我的代码是这样的. [代码链接](https://github.com/dlfld/ddp_code/blob/main/monist.py) 在两台服务器上运行的命令是`python mnsit.py --rank=0 --world-size=2` `python mnsit.py --rank=1 --world-size=2` 还是卡在 `model = torch.nn.parallel.DistributedDataParallel(model,find_unused_parameters=False,output_device=None,device_ids=None) ` 这一行代码，恳请各位大佬帮我看一下，已经在这里卡了好几天了，一直改不好。

dist.init_process_group 一直卡住   请问您是怎么解决的

**Comment by braunagn** [comment]
> Thanks @pietern. Let me confirm if the timing code is indeed the one causing this desynchronization between the processes.

@shoaibahmed - this solution also worked for me; thanks for setting up this issue thread.

For the general audience: does anyone have links to resources to better understand desynchronization between processes and how to avoid it?  It's not immediately clear to me how commenting out `time` functions fixed the `DDP` hang issue.

**Comment by doubleZ0108** [comment]
First of all, I describe my personal task basically and point out my error.
- 🎯**Task**: I am doing an image generation task based on diffusion, the packages most related to me are `accelerate`, `diffusers`, `torch`.
- 🐛**BUG**: When I run my code on a single machine + single GPU, everything works pretty fine. But when I use a single machine + multiple GPUs for DDP training, the _NCCL timeout_ related bugs occur.
- 🌪️**Phenomena**: When running the project on 1 machine + 4 GPUs (for example), I got the error message randomly after several steps. The error message points out the NCCL timeout as something like `[Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4084, OpType=BROADCAST, NumelIn=56623104, NumelOut=56623104, Timeout(ms)=600000) ran for 600059 milliseconds before timing out`. And I do not get any error message from my personal code.
    > I use a distributed implementation encapsulated by accelerate, rather than the raw torch. distributed, but I think the core issues are consistent.

<details><summary>The complete error traces.</summary>
<p>

```shell
[rank2]:[E ProcessGroupNCCL.cpp:563] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4084, OpType=ALLREDUCE, NumelIn=4821568, NumelOut=4821568, Timeout(ms)=600000) ran for 600077 milliseconds before timing out.
[rank1]:[E ProcessGroupNCCL.cpp:563] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4084, OpType=ALLREDUCE, NumelIn=4821568, NumelOut=4821568, Timeout(ms)=600000) ran for 600095 milliseconds before timing out.
[rank3]:[E ProcessGroupNCCL.cpp:563] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4084, OpType=BROADCAST, NumelIn=56623104, NumelOut=56623104, Timeout(ms)=600000) ran for 600059 milliseconds before timing out.
dlciwpwqw7kd1h3y-master-0:301:382 [3] NCCL INFO [Service thread] Connection closed by localRank 3
dlciwpwqw7kd1h3y-master-0:301:315 [3] NCCL INFO comm 0x12fd4c240 rank 3 nranks 4 cudaDev 3 busId 70 - Abort COMPLETE
[rank3]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 3] Timeout at NCCL work: 4084, last enqueued NCCL work: 4084, last completed NCCL work: 4083.
[rank3]:[E ProcessGroupNCCL.cpp:577] [Rank 3] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank3]:[E ProcessGroupNCCL.cpp:583] [Rank 3] To avoid data inconsistency, we are taking the entire process down.
[rank3]:[E ProcessGroupNCCL.cpp:1414] [PG 0 Rank 3] Process group watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4084, OpType=BROADCAST, NumelIn=56623104, NumelOut=56623104, Timeout(ms)=600000) ran for 600059 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:565 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f4e9d77a897 in /path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7f4e513aa1b2 in /path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1a0 (0x7f4e513aefd0 in /path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7f4e513b031c in /path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdbbf4 (0x7f4e9ecc7bf4 in /path/to/conda/envs/fitdit/bin/../lib/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x7f4ead294ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126660 (0x7f4ead326660 in /usr/lib/x86_64-linux-gnu/libc.so.6)

W0325 15:10:13.736000 140515496433472 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 298 closing signal SIGTERM
W0325 15:10:13.737000 140515496433472 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 299 closing signal SIGTERM
W0325 15:10:13.738000 140515496433472 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 300 closing signal SIGTERM
E0325 15:10:14.906000 140515496433472 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: -6) local_rank: 3 (pid: 301) of binary: /path/to/conda/envs/fitdit/bin/python
Traceback (most recent call last):
  File "/path/to/conda/envs/fitdit/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
train_logo_refiner.py FAILED
----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-25_15:10:13
  host      : dlciwpwqw7kd1h3y-master-0
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 301)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 301
====================================================

```

</p>
</details> 

<br />

Then I list all attempts I have tried to face the core problem, and you can have a try : ), maybe something can work in your situation.
1. Check your GPU memory. Be sure that the forward and backward of your model do not trap into `CUDA out of memory. Tried to allocate xxx MiB`. You can verify this on a single GPU configuration, and please take some time for a long training test.
2. Check your Dataloader. You should catch exceptions like file paths do not exist, image cannot open... And you can use an `is_valid` flag and `for` loop in `__getitem__()` to make sure that the data you construct is correct. And I have also checked that the processing time of the adjacent two batches is less than a really small seconds.
  a. If your data is stored on a network location (like NAS), pay attention to the fetching time! Be wary of network fluctuations and possible file path corruption.
3. You can try adding these environment parameters.

    ````bash
    export TORCH_DISTRIBUTED_DEBUG=INFO
    export NCCL_DEBUG=INFO
    export NCCL_P2P_DISABLE=0
    export NCCL_P2P_LEVEL=NVL
    ````
4. Allow longer timeout waiting time and set `find_unused_parameters=True`
    
    ```python
    kwargs = DistributedDataParallelKwargs(find_unused_parameters=True)
    timeout = InitProcessGroupKwargs(timeout=timedelta(minutes=15))
    accelerator = Accelerator(
        ...
        kwargs_handlers=[kwargs, timeout],
    )
    ```
5. Build a new python env and upgrade key packages to the latest version, `torch`, `accelerate`, `transformer`, `diffusers`, `nvidia-nccl-cu12`.
6. Delete code related to `tqdm`, `time.time()` or something similar to time record.

<br />

Finally, I will try to understand the problem as deeply as possible based on my current understanding and provide a solution that is applicable to me.
Look at the GPU usage (calculating usage, not GPU memory usage) below. From a certain point in time, the GPU usage reached 100%, and this time coincided with the onset of program pauses / hangs. This extreme usage persisted until the timeout ended, after which the entire program was terminated.

<img src="https://github.com/user-attachments/assets/ef78b6a2-924b-46cc-9c45-7f4531cefd28" width="40%" height="40%" />

Let's conduct a detailed observation. As your task is hung and befor killed by timeout, enter your program's runtime container and execute `ps -ef | grep python` or `htop` to find your Python training processes (typically, the one with the smallest PID is the main process, and the number corresponds to the number of GPUs you are using). Install [pystack](https://github.com/bloomberg/pystack) and use `pystack [PID]` to monitor your main python processes one by one. Compare the output stack message and find the differences.

<details><summary>I got something like</summary>
<p>

```bash
  File "/path/to/train_logo_refiner.py", line 1273, in <module>
    logs['Loss/logo_ssim_loss'] = (loss_logo_ssim / loss_factor).detach().item()
  File "/path/to/train_logo_refiner.py", line 1099, in main
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1593, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1411, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/accelerate/utils/operations.py", line 823, in forward
    return model_forward(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/accelerate/utils/operations.py", line 811, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/path/to/src/transformer_sd3_xxx.py", line 325, in forward
    encoder_hidden_states, hidden_states = torch.utils.checkpoint.checkpoint(
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 494, in checkpoint
    ret = function(*args, **kwargs)
  File "/path/to/src/transformer_sd3_xxx.py", line 320, in custom_forward
    return module(*inputs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/src/attention_xxx.py", line 168, in forward
    norm_hidden_states, gate_msa, shift_mlp, scale_mlp, gate_mlp = self.norm1(hidden_states, emb=temb)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path/to/conda/envs/fitdit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/imggen/diffusers_v32/src/diffusers/models/normalization.py", line 170, in forward
    x = self.norm(x) * (1 + scale_msa[:, None]) + shift_msa[:, None]
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
```

</p>
</details> 


Combining other information output by `pystack`, the issue becomes quite clear: a deadlock caused by a lack of synchronization between processes resulted in GPU usage reaching 100%, but your training did not progress further until it was interrupted by the protection mechanism after a timeout.
- Why are there no errors when using a single GPU? Because, in this case, there are no thread synchronization problems.
- Where do thread synchronization conflicts occur? I'll provide some of my practices and examples.
Look the point #6 on the ordered list ahead. If you use `tqdm` to show your training process, it will cause thread synchronization conflicts. And statistic `time.time()` in training step is also the case.
Another interesting case, if you check the `NaN` value in loss and skip the polluted steps. You may write the code like:

```python
if torch.any(torch.isnan(loss)):
    continue

accelerator.backward(loss)
# ....

# ------------------------------------

if not torch.any(torch.isnan(loss)):
    accelerator.backward(loss)
    # ...
else:
    print("Loss has NaN skip...")
```

This will cause thread synchronization conflicts easily because `rank-i` end a step with no backward and other ranks still calculating the loss backward. You should change your code to:

```python
def check_nan(tensor):
    return torch.isnan(tensor).any().item()

loss_is_nan = torch.tensor(check_nan(loss), device=accelerator.device, dtype=torch.int)

# reduce to check if any process has NaN loss
loss_is_nan = accelerator.reduce(loss_is_nan, reduction="sum")

if loss_is_nan.item() == 0:
    accelerator.backward(loss)
    # ...
else:
    if accelerator.is_main_process:
        print("Loss has NaN, skip...")
```

There are several common cases. Logging to tensorboard, decoding latent image to pixel space for visualization...The principle is that you should not execute special code only for certain threads. Use `accelerator.is_main_process` and `accelerator.wait_for_everyone()` properly.

<br />

<details><summary>Some related issues</summary>
<p>

- https://github.com/huggingface/accelerate/issues/314
- https://blog.csdn.net/weixin_42001089/article/details/122733667 (in Chinese)
- https://github.com/pytorch/pytorch/issues/22834
- https://github.com/pytorch/pytorch/issues/20630
- https://discuss.pytorch.org/t/multi-gpu-training-hangs-watchdog-caught-collective-operation-timeout/188702
- https://github.com/pytorch/pytorch/issues/135352

</p>
</details>
