### ISSUE TITLE
Unhandled CUDA Error (1)

### ISSUE THREAD

**Issue by ritchieng** [pytorch/pytorch#2332]
**Error**
```
    Traceback (most recent call last):
      File "main.py", line 201, in <module>
        loss_list, lr_epoch, mu_epoch = train(epoch)
      File "main.py", line 132, in train
        outputs = net(inputs)
      File "/home/lala/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/lala/miniconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 59, in forward
        replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
      File "/home/lala/miniconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 64, in replicate
        return replicate(module, device_ids)
      File "/home/lala/miniconda2/lib/python2.7/site-packages/torch/nn/parallel/replicate.py", line 12, in replicate
        param_copies = Broadcast(devices)(*params)
      File "/home/lala/miniconda2/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 19, in forward
        outputs = comm.broadcast_coalesced(inputs, self.target_gpus)
      File "/home/lala/miniconda2/lib/python2.7/site-packages/torch/cuda/comm.py", line 54, in broadcast_coalesced
        results = broadcast(_flatten_tensors(chunk), devices)
      File "/home/lala/miniconda2/lib/python2.7/site-packages/torch/cuda/comm.py", line 24, in broadcast
        nccl.broadcast(tensors)
      File "/home/lala/miniconda2/lib/python2.7/site-packages/torch/cuda/nccl.py", line 190, in broadcast
        data_type, root, comm[i], cudaStream()))
      File "/home/lala/miniconda2/lib/python2.7/site-packages/torch/cuda/nccl.py", line 118, in check_error
        raise NcclError(status)
    torch.cuda.nccl.NcclError: Unhandled Cuda Error (1)
```

When I run without GPU, the code is fine. On v0.1.12 it is fine on GPU and CPU.

**Lines with issues I believe**

```
    if use_cuda:
        net.cuda()
        net = torch.nn.DataParallel(net, device_ids=range(torch.cuda.device_count()))
        cudnn.benchmark = True
```

**Comment by soumith** [comment]
Ritchie, can this be reproduced in a Docker image so that we can investigate on our side?

**Comment by garyzhalo** [comment]
I had the same issue when I upgrade PyTorch 0.2.0 through conda. Spent one day to debug. Finally, I found it can be fixed by pip install... There has to be some issue in the conda build.

**Comment by soumith** [comment]
@garyzhalo can you give me your output of `conda list`

**Comment by garyzhalo** [comment]
#
backports.weakref         1.0rc1                    <pip>
bleach                    1.5.0                    py35_0  
bleach                    1.5.0                     <pip>
cffi                      1.10.0                   py35_0  
cudatoolkit               7.5                           2  
cudnn                     6.0.21                cuda7.5_0  
cycler                    0.10.0                   py35_0  
dbus                      1.10.20                       0  
decorator                 4.1.2                    py35_0  
entrypoints               0.2.3                    py35_0  
expat                     2.1.0                         0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
glib                      2.50.2                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.7.0               np113py35_0  
hdf5                      1.8.17                        2  
html5lib                  0.9999999                 <pip>
html5lib                  0.9999999                py35_0  
icu                       54.1                          0  
ipykernel                 4.6.1                    py35_0  
ipython                   6.1.0                    py35_0  
ipython_genutils          0.2.0                    py35_0  
ipywidgets                6.0.0                    py35_0  
jbig                      2.1                           0  
jedi                      0.10.2                   py35_2  
jinja2                    2.9.6                    py35_0  
jpeg                      9b                            0  
jsonschema                2.6.0                    py35_0  
jupyter                   1.0.0                    py35_3  
jupyter_client            5.1.0                    py35_0  
jupyter_console           5.1.0                    py35_0  
jupyter_core              4.3.0                    py35_0  
Keras                     2.0.6                     <pip>
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         3  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
Markdown                  2.6.8                     <pip>
markupsafe                0.23                     py35_2  
matplotlib                2.0.2               np113py35_0  
mistune                   0.7.4                    py35_0  
mkl                       2017.0.3                      0  
nbconvert                 5.2.1                    py35_0  
nbformat                  4.3.0                    py35_0  
nccl                      1.3.4                         0  
notebook                  5.0.0                    py35_0  
numpy                     1.13.1                    <pip>
numpy                     1.13.1                   py35_0  
olefile                   0.44                     py35_0  
openssl                   1.0.2l                        0  
pandas                    0.20.3                   py35_0  
pandocfilters             1.4.1                    py35_0  
path.py                   10.3.1                   py35_0  
pcre                      8.39                          1  
pexpect                   4.2.1                    py35_0  
pickleshare               0.7.4                    py35_0  
pillow                    4.2.1                    py35_0  
pip                       9.0.1                    py35_1  
prompt_toolkit            1.0.14                   py35_0  
protobuf                  3.3.0                     <pip>
ptyprocess                0.5.2                    py35_0  
pycparser                 2.18                     py35_0  
pygments                  2.2.0                    py35_0  
pyparsing                 2.2.0                    py35_0  
pyqt                      5.6.0                    py35_2  
python                    3.5.3                         1  
python-dateutil           2.6.1                    py35_0  
pytorch                   0.1.12          py35cuda7.5cudnn6.0_1  
pytz                      2017.2                   py35_0  
PyYAML                    3.12                      <pip>
pyzmq                     16.0.2                   py35_0  
qt                        5.6.2                         5  
qtconsole                 4.3.0                    py35_0  
readline                  6.2                           2  
scipy                     0.19.1              np113py35_0  
setuptools                27.2.0                   py35_0  
setuptools                36.0.1                    <pip>
simplegeneric             0.8.1                    py35_1  
sip                       4.18                     py35_0  
six                       1.10.0                    <pip>
six                       1.10.0                   py35_0  
sqlite                    3.13.0                        0  
tensorflow-gpu            1.2.1                     <pip>
terminado                 0.6                      py35_0  
testpath                  0.3.1                    py35_0  
Theano                    0.9.0                     <pip>
tk                        8.5.18                        0  
torch-0.2.0               1                         <pip>
torchvision               0.1.9                     <pip>
tornado                   4.5.1                    py35_0  
tqdm                      4.15.0                   py35_0  
traitlets                 4.3.2                    py35_0  
wcwidth                   0.1.7                    py35_0  
Werkzeug                  0.12.2                    <pip>
wheel                     0.29.0                    <pip>
wheel                     0.29.0                   py35_0  
widgetsnbextension        2.0.0                    py35_0  
xz                        5.2.2                         1  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3

**Comment by patrickpoirson** [comment]
Also, ran into the same issue. Works when using pip wheel instead of conda.

**Comment by alexander-beer-weiss** [comment]
Has there been any progress on this issue?  I have two GTX 1080 Ti cards and I've been getting this error since I upgraded to v0.2 (using conda).  I tried "pip install" as suggested above, and it works, but it causes other problems.

**Comment by MohsenFayyaz89** [comment]
I have the same problem with +8 GPUs. I have installed Pytorch 0.2 using "pip install". However, with 8 GPUs everything is ok.

**Comment by soumith** [comment]
i've tried to reproduce this issue on multiple machines, and so far I have nothing :(
If anyone could help reproduce this in a Docker image, I can quickly issue fixes.
Also, can either of you give me the output of 
`echo $PATH`
`echo $LD_LIBRARY_PATH`
`ldd $(dirname $(which conda))/../lib/python2.7/site-packages/torch/_C.so*`

**Comment by aymenx17** [comment]
Hi guys, i had the same error, here some logs:
PATH: home/cf/anaconda3/envs/pytorch/bin:/home/cf/anaconda3/bin:/usr/local/cuda-8.0/bin:/home/cf/bin:/home/cf/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:
LD_LYBRARY_PATH: /usr/local/cuda-8.0/lib64:  
ldd: /home/cf/anaconda3/envs/pytorch/bin/../lib/python3.6/site-packages/torch/_C.so*: No such file or directory
I'm using pytorch   0.2.0 py36h53baedd_4cu80  [cuda80]  soumith on two GPU Nvidia 1080TI 
I was using another version that was working but i don't remember which
Thanks

**Comment by D-X-Y** [comment]
Hi, I reinstall the anaconda for PyThon 3.6 as well as the PyTorch 2.0. The problem was solved.
I use 'conda install pytorch torchvision cuda80 -c soumith' and 4 GPUs parallel is ok.

**Comment by VladislavZavadskyy** [comment]
Same on master 1d57a2d54c257f31f94c562feca43a687577d733.
Built with cuda 9 and cuddn 7.0.3.

**Comment by foolwood** [comment]
I have the same problem with 8 K80 GPUs. I  installed Pytorch 0.2 using "conda". 

@soumith 


ldd $(dirname $(which conda))/../lib/python2.7/site-packages/torch/_C.so*
        linux-vdso.so.1 =>  (0x00002aaaaaaab000)
        libshm.so => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libshm.so (0x00002aaaac0ec000)
        libcudart.so.8.0 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libcudart.so.8.0 (0x00002aaaac394000)
        libnvToolsExt.so.1 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libnvToolsExt.so.1 (0x00002aaaac5fc000)
        libcudnn.so.6 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libcudnn.so.6 (0x00002aaaac807000)
        libpython2.7.so.1.0 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/../../../libpython2.7.so.1.0 (0x00002aaab5d6b000)
        libTH.so.1 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libTH.so.1 (0x00002aaab6148000)
        libTHS.so.1 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libTHS.so.1 (0x00002aaab6736000)
        libTHPP.so.1 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libTHPP.so.1 (0x00002aaab696a000)
        libTHNN.so.1 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libTHNN.so.1 (0x00002aaab6e5e000)
        libATen.so.1 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libATen.so.1 (0x00002aaab7185000)
        libTHC.so.1 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libTHC.so.1 (0x00002aaab7a93000)
        libTHCS.so.1 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libTHCS.so.1 (0x00002aaac77cf000)
        libTHCUNN.so.1 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libTHCUNN.so.1 (0x00002aaac7bf1000)
        libnccl.so.1 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/libnccl.so.1 (0x00002aaacbe8c000)
        libgcc_s.so.1 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/../../../libgcc_s.so.1 (0x00002aaaceb6a000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00002aaaced7c000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00002aaacef98000)
        /lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00002aaacf35a000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00002aaacf562000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00002aaacf865000)
        libstdc++.so.6 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/../../../../libstdc++.so.6 (0x00002aaacfa69000)
        libutil.so.1 => /usr/lib64/libutil.so.1 (0x00002aaacfda4000)
        libmkl_intel_lp64.so => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/../../../../libmkl_intel_lp64.so (0x00002aaacffa7000)
        libmkl_intel_thread.so => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/../../../../libmkl_intel_thread.so (0x00002aaad0a98000)
        libmkl_core.so => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/../../../../libmkl_core.so (0x00002aaad2791000)
        libiomp5.so => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/../../../../libiomp5.so (0x00002aaad44d6000)
        libgomp.so.1 => /home/qwang/anaconda2/bin/../lib/python2.7/site-packages/torch/lib/../../../../libgomp.so.1 (0x00002aaad487a000)
        libcublas.so.8.0 => /home/qwang/anaconda2/lib/python2.7/site-packages/torch/lib/libcublas.so.8.0 (0x00002aaad4a9d000)
        libcurand.so.8.0 => /home/qwang/anaconda2/lib/python2.7/site-packages/torch/lib/libcurand.so.8.0 (0x00002aaad7ae6000)
        libcusparse.so.8.0 => /home/qwang/anaconda2/lib/python2.7/site-packages/torch/lib/libcusparse.so.8.0 (0x00002aaadba5d000)

**Comment by VladislavZavadskyy** [comment]
If you've ran into the same issue, you may want to follow steps described [here](https://github.com/pytorch/pytorch/issues/5553).

**Comment by gchanan** [comment]
Closing this as it's sufficiently out of date.
