### ISSUE TITLE
error in multi node

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#23363]
When I training in distirbuted mode, the program report error.
Error info:
```
fail to new train...e= NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhanled system error
```

The Environment:
I run in two docker container, the program report error.
```
# node 0: 10.30.112.212
init_method="tcp://10.30.112.212:10087"
rank=0
world_size=2
backend="nccl"

# node 1: 10.30.112.224
init_method="tcp://10.30.112.212:10087"
rank=1
world_size=2
backend="nccl"
```

I run in one docker container, but run twice with different rank, the program can run.
```
# node 0: 10.30.112.212
init_method="tcp://10.30.112.212:10087"
rank=0
world_size=2
backend="nccl"

# node 1: 10.30.112.212
init_method="tcp://10.30.112.212:10087"
rank=1
world_size=2
backend="nccl"
```

**Comment by pietern** [comment]
This is likely caused by the processes assuming they can connect to one another and that not being the case because of Docker's network isolation. You can try running without network isolation. I think the argument for that is `--network=host`, but I might be mistaken. The Docker docs will have the definitive answes.

**Comment by un-knight** [comment]
I meet the same problem:
```
Traceback (most recent call last):
  File "synthetic_benchmark.py", line 129, in <module>
    main()
  File "synthetic_benchmark.py", line 105, in main
    number=args.num_warmup_batches, globals=globals())
  File "/opt/anaconda/lib/python3.7/timeit.py", line 232, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/opt/anaconda/lib/python3.7/timeit.py", line 176, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 3, in inner
  File "/workspace/image-classification/libs/clf_train.py", line 255, in create_training_components
    output_device=args.local_rank)
  File "/opt/anaconda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 286, in __init__
    self.broadcast_bucket_size)
  File "/opt/anaconda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 410, in _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1556653114079/work/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled cuda error
```

And it's strange that I can run the same script correctly with Pytorch1.0 but get an nccl error with pytorch1.1

**Comment by as754770178** [comment]
I follow the pytorch document, set `export NCCL_SOCKET_IFNAME=IBNet` `export NCCL_DEBUG=INFO` `export NCCL_DEBUG_SUBSYS=ALL`.
The program not report error, but stuck. The last of log:
```
[0] NCCL INFO NET/Socket : Using [0]IBNet:10.30.112.224<0>
[0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so)
[0] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
... ... 
[7] NCCL INFO AllReduce: opCount 1 sendbuff 0x7faf4c000000 recvbuff 0x7faf4c000000 count 8436224 datatype 7 op 0 root 0 comm 0x7fae40000d50 [nranks=16] stream 0x7fae8811d320
```

**Comment by as754770178** [comment]
I run docker in `--net=host`, and  `set export NCCL_SOCKET_IFNAME=IBNet`  `export NCCL_DEBUG=INFO`  `export NCCL_DEBUG_SUBSYS=ALL`.
The node `rank=0` report error:
```
# rank=0: 10.30.112.72    rank=1:10.30.112.66
include/socket.h NCCL WARN Connect to 10.30.112.66<48115> failed : No route to host
```

**Comment by un-knight** [comment]
> I meet the same problem:
> 
> ```
> Traceback (most recent call last):
>   File "synthetic_benchmark.py", line 129, in <module>
>     main()
>   File "synthetic_benchmark.py", line 105, in main
>     number=args.num_warmup_batches, globals=globals())
>   File "/opt/anaconda/lib/python3.7/timeit.py", line 232, in timeit
>     return Timer(stmt, setup, timer, globals).timeit(number)
>   File "/opt/anaconda/lib/python3.7/timeit.py", line 176, in timeit
>     timing = self.inner(it, self.timer)
>   File "<timeit-src>", line 3, in inner
>   File "/workspace/image-classification/libs/clf_train.py", line 255, in create_training_components
>     output_device=args.local_rank)
>   File "/opt/anaconda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 286, in __init__
>     self.broadcast_bucket_size)
>   File "/opt/anaconda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 410, in _dist_broadcast_coalesced
>     dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
> RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1556653114079/work/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled cuda error
> ```
> 
> And it's strange that I can run the same script correctly with Pytorch1.0 under 2 nodes but get an nccl error with pytorch1.1, I am sure that all configurations are same except PyTorch version.
> 
> Besides, it's both fine to run with single-node multi-gpus with pytorch1.0 and pytorch1.1. So the nccl runtime error seems only occurs with multi-nodes.

@pietern I think this problem maybe related with nccl library according to https://github.com/horovod/horovod/issues/893, there are some bugs with nccl 2.4.2 https://github.com/NVIDIA/nccl/pull/185.

pytorch1.1 may downgrade nccl 2.4.2 to 2.3.7 to fix this problem.

**Comment by mrshenli** [comment]
Hi @un-knight, the master branch has been updated to 2.4.8 in #23186 four days ago. Can you try the nightly or build from source?

**Comment by un-knight** [comment]
> Hi @un-knight, the master branch has been updated to 2.4.8 in #23186 four days ago. Can you try the nightly or build from source?

@mrshenli ok, I will have a try and feedback the result.

**Comment by as754770178** [comment]
Install fro source, what version needed for gcc, nccl ...?  If I use pip install, also need update nccl to 2.4.8?

**Comment by un-knight** [comment]
@mrshenli After updating pytorch from 1.1 to 1.2(nightly), the default nccl is updated from 2.4.2 to 2.4.8, then the nccl runtime error is fixed under multi-nodes communication. By the way, when will pytorch 1.2 be released?

**Comment by mrshenli** [comment]
Hi @un-knight, the branch [v1.2.0](https://github.com/pytorch/pytorch/tree/v1.2.0) has been cut, and #23555 is tracking the discussion. Official announcement should come soon.

**Comment by mrshenli** [comment]
Hi @as754770178, to install from source, checkout [this section](https://github.com/pytorch/pytorch#from-source). NCCL is included as a git submodule in PyTorch repo, so no need to install that manually or separately.

> If I use pip install, also need update nccl to 2.4.8?

[pytorch-nightly](https://anaconda.org/pytorch/pytorch-nightly) should work for you, it uses NCCL 2.4.8.

**Comment by as754770178** [comment]
Now I success run distribute program in two node, but when I use IB, the program stuck. even I run distribute program in one node, the program still stuck.

The last log info such as:
```
[3] NCCL INFO AllReduce: opCount 1 sendbuff 0x7faf4c000000 recvbuff 0x7faf4c000000 count 8436224 datatype 7 op 0 root 0 comm 0x7fae40000d50 [nranks=16] stream 0x7fae8811d320
```

**Comment by as754770178** [comment]
I use `tcp://` for all backend, whether use different prefix for different backend, such as: nccl, gloo.

**Comment by pietern** [comment]
You probably mean "tcp://" for the init method, regardless of the backend.

Which version of PyTorch are you running now?

**Comment by as754770178** [comment]
pytorch 1.1.0 

I mean what is different run program on common network card and on the IB network card. 

on common network card:
```
export NCCL_SOCKET_IFNAME=team0
export NCCL_DEBUG=INFO 
export NCCL_DEBUG_SUBSYS=ALL
export NCCL_IB_DISABLE=1

# ip
init_method="tcp://10.30.112.212:10087"
```

on IB network card:
```
export NCCL_SOCKET_IFNAME=team0
export NCCL_DEBUG=INFO 
export NCCL_DEBUG_SUBSYS=ALL
unset NCCL_IB_DISABLE

# ip
init_method="tcp://66.66.66.75:10087"
```
other is same， but when on ib network card, the program stuck.

**Comment by pietern** [comment]
Can you try with a PyTorch nightly build? It includes a newer version of NCCL which might fix the issue.

**Comment by as754770178** [comment]
I install nccl memory that solved the problem about IB.
I have two IB network card at every node, but only one be used. When I run by mpi, the two IB network card are used. One for the communication between node, the other for the communication between GPU.

**Comment by pietern** [comment]
It sounds like the original issue was resolved then?

If you have a performance problem, let's open a new issue for that. If you do, please include all relevant details about your environment, and if possible, any scripts or commands you run to reproduce the issue. Thanks.
