### ISSUE TITLE
RuntimeError: cuda runtime error (3) : initialization error AFTER daemonization

### ISSUE THREAD

**Issue by farleylai** [pytorch/pytorch#23401]
## 🐛 Bug

Calling `torch.cuda.is_available()` or `torch.cuda.device_count()` BEFORE `with daemon.DaemonContext(...):` and then call any torch API that internally calls ` th._C._cuda_getDevice()` AFTER daemonization throws the following runtime error:

> RuntimeError: cuda runtime error (3) : initialization error at /opt/conda/conda-bld/pytorch_1556653099582/work/torch/csrc/cuda/Module.cpp:52

However, the use case is to set all the seeds and visible GPUs according to the availability of GPUs and user config as early as possible as part of the application framework without explicit initialization code by user  and let the user decide whether to daemonize or not later.

## To Reproduce

- Install `python-daemon` which is the implementation of PEP 3143.
- Run the following script to reproduce error

```python
import sys, daemon, torch as th
print('BEFORE:', th.cuda.device_count())
with daemon.DaemonContext(stdout=sys.stdout, stderr=sys.stderr, chroot_directory=None, working_directory='.'):
    print('prev_idx:', th._C._cuda_getDevice())
```

Ouput:
```sh
$ python test-daemon.py 
BEFORE: 2
$ 
$ THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653099582/work/torch/csrc/cuda/Module.cpp line=52 error=3 : initialization error
Traceback (most recent call last):
  File "test-daemon.py", line 28, in <module>
    print('prev_idx:', th._C._cuda_getDevice())
RuntimeError: cuda runtime error (3) : initialization error at /opt/conda/conda-bld/pytorch_1556653099582/work/torch/csrc/cuda/Module.cpp:52
```

## Expected behavior

Should produce no error as called in the following order:

```python
import sys, daemon, torch as th
with daemon.DaemonContext(stdout=sys.stdout, stderr=sys.stderr, chroot_directory=None, working_directory='.'):
    print('AFTER:', th.cuda.device_count())
    print('prev_idx:', th._C._cuda_getDevice())
```

Output:
```
AFTER: 2
prev_idx: 0
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): Ubuntu 16.04.3 LTS
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): N/A
 - Python version: 3.6.8 from conda
 - CUDA/cuDNN version: 10.0.130/7.1.4
 - GPU models and configuration: 2 x TITAN RTX
 - Any other relevant information: driver 418.59

**Comment by ezyang** [comment]
We think this was fixed by a recent patch from @zhangguanheng66; he'll check if that's the case and close this issue out if it is.

**Comment by zhangguanheng66** [comment]
Check with the master branch and it works as expected. Feel free to re-open the issue if you still have questions. @farleylai

**Comment by farleylai** [comment]
@zafartahirov 

Can you elaborate more about the patch?
The same issue remains even after upgrading to PyTorch 1.3 as follows:

```py
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, daemon, torch as th
>>> print('BEFORE:', th.cuda.device_count())
BEFORE: 2
>>> with daemon.DaemonContext(stdout=sys.stdout, stderr=sys.stderr, chroot_directory=None, working_directory='.'):
...     print('prev_idx:', th._C._cuda_getDevice())
... 
(sinet37) farleylai@ml17-pc02:~/local/projects/sinet/SINet$ THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1570711556059/work/aten/src/THC/THCGeneral.cpp line=54 error=3 : initialization error
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/ml/farleylai/miniconda3/envs/sinet37/lib/python3.7/site-packages/torch/cuda/__init__.py", line 193, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (3) : initialization error at /opt/conda/conda-bld/pytorch_1570711556059/work/aten/src/THC/THCGeneral.cpp:54
>>> 
```

The environment is shown below FYI:
```
Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: TITAN RTX
GPU 1: TITAN RTX

Nvidia driver version: 418.87.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] pytorch-ignite==0.2.1
[pip] pytorch-pretrained-bert==0.6.2
[pip] torch==1.3.0
[pip] torchfile==0.1.0
[pip] torchnet==0.0.4
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl  
[conda] ignite                    0.2.1                    py37_0    pytorch
[conda] magma-cuda101             2.5.1                         1    pytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] mxnet-cu101mkl            1.5.1.post0              pypi_0    pypi
[conda] pytorch                   1.3.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] pytorch-pretrained-bert   0.6.2                    py37_0    conda-forge
[conda] torchfile                 0.1.0                      py_0    conda-forge
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchvision               0.4.1                py37_cu101    pytorch
```

**Comment by gchanan** [comment]
@zhangguanheng66 can you post the patch you expected to fix this?

**Comment by zhangguanheng66** [comment]
@gchanan I just checked that `set_device` func does report the proper error message. I fixed it for the issue https://github.com/pytorch/pytorch/issues/17357.

**Comment by peterbell10** [comment]
There are two issues here:
1. `torch.cuda` is not initialized when `device_count` is called:
https://github.com/pytorch/pytorch/blob/d690521cf661c5f080e9d330b9f88e5055bb2e67/torch/csrc/cuda/Module.cpp#L64-L65
@zhangguanheng66 can hopefully comment on why it was left commented out in #23030. Did it break something?

2. `atfork` handlers registered with `multiprocessing.util.register_after_fork` are only called on processes created with `multiprocessing`; not after `os.fork()` which is what `python-daemonize` uses. One way to fix this would be to create our own version that uses `pthread_atfork` under the hood. Thoughts?

You can see 
<details>
<summary>Script confirming 2 is under the fold</summary>

```python
import multiprocessing.util
import multiprocessing as mp

def _hello(n):
    print("Hello from {}".format(n))
    sys.exit(0)

def _after_fork(arg):
    print("After fork called successfully")
mp.util.register_after_fork(_after_fork, _after_fork)

import os, sys
if os.fork() != 0:
    _hello("fork")

p = mp.Process(target=_hello, args=("mp.Process",))
p.start(); p.join()

```

The output is:
```
Hello from fork
After fork called successfully
Hello from mp.Process
```

</details>

**Comment by SsnL** [comment]
@peterbell10 Yeah, really `os.register_at_fork` should be the preferred atfork handler registration method but it is only available >= 3.7. I think `pthread_atfork` is fine here because the same problem can happen even if the fork child does not return to python interpreter. A comment would be nice.

**Comment by ezyang** [comment]
> @zhangguanheng66 can hopefully comment on why it was left commented out in #23030. Did it break something?

For the full history, read #15782, #15734, #17357.

But I believe the true constraint is that it is not permissible to initialize CUDA context when device count is called. This is because internally, we have a hack called "lazy cuda library stubs", where you can run programs that are dynamically linked against CUDA even on systems that don't have CUDA. In this situation, calls to `cudaGetDeviceCount` will (properly) return zero, but all other calls will raise an exception. Various CPU-only code relies on this to call `device_count()` even when CUDA is not available. If you initialize CUDA when device count is invoked, you break these stubs.

**Comment by jhagege** [comment]
I have this issue when having tensorboard installed, but not with tensorboardX. 
Very weird.. 
Hope it can help to troubleshoot..
