### ISSUE TITLE
Batched torch.solve on GPU fails with: invalid device function

### ISSUE THREAD

**Issue by jungomi** [pytorch/pytorch#24328]
## 🐛 Bug

Using the batched version of `torch.solve` on a multi-GPU machine crashes with the error:

```
RuntimeError: CUDA error: invalid device function
```

The computation seems to work, but when the solution is used, it crashes due to not being on the correct device.

The same batch works on the CPU and on another machine with a single GPU it worked as expected, even on the GPU.

It does not crash when using PyTorch 1.1, only on PyTorch 1.2.0.

## To Reproduce

Install PyTorch 1.2.0 and run it on a multi-GPU machine:

```python
import torch

torch.manual_seed(1234)

device = torch.device("cuda")

A = torch.randn(2, 3, 3, device=device)
B = torch.randn(2, 3, 5, device=device)

# CPU version works fine
solution_cpu, _ = torch.solve(B.cpu(), A.cpu())
print("CPU: ", solution_cpu)

solution_gpu, _ = torch.solve(B, A)
# The GPU solution seems to exist on the device
print("Solution Device = ", solution_gpu.device)
# Using the solution crashes
solution_gpu * 1
print("GPU: ", solution_gpu)
```

Doing anything with the solution will crash.

Resulting in the following error:

```
Traceback (most recent call last):
  File "solve-gpu.py", line 18, in <module>
    solution_gpu * 1
RuntimeError: CUDA error: invalid device function
```

Additionally, it seems that the devices of the inputs have also been corrupted and using them crashes as well.

## Expected behavior

Both the CPU and GPU versions should work and return the same result:

```
CPU:  tensor([[[ 0.0290, -4.0359,  0.5566, -0.7381,  1.7561],
         [-0.8191,  0.3854,  0.9550,  0.0858, -1.8166],
         [-2.2452, 10.0097, -0.0216,  0.4357, -6.7798]],

        [[-0.6199, -0.2213, -0.9044,  2.2596, -0.8462],
         [-2.8596,  2.5067, -0.8933,  2.1357, -0.2028],
         [ 1.9015, -0.1691,  0.2684, -0.6873, -0.2327]]])
Solution Device =  cuda:0
GPU:  tensor([[[ 0.0290, -4.0359,  0.5566, -0.7381,  1.7561],
         [-0.8191,  0.3854,  0.9550,  0.0858, -1.8166],
         [-2.2452, 10.0097, -0.0216,  0.4357, -6.7798]],

        [[-0.6199, -0.2213, -0.9044,  2.2596, -0.8462],
         [-2.8596,  2.5067, -0.8933,  2.1357, -0.2028],
         [ 1.9015, -0.1691,  0.2684, -0.6873, -0.2327]]], device='cuda:0')
```

## Environment

```
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80

Nvidia driver version: 430.26
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.2

Versions of relevant libraries:
[pip] numpy==1.17.0
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect
```

**Comment by vishwakftw** [comment]
What CUDA version are you using?

**Comment by jungomi** [comment]
The CUDA version is `10.1.168`

**Comment by SsnL** [comment]
Sounds like related to MAGMA & CUDA 10.1 (https://github.com/pytorch/pytorch/issues/20103)

**Comment by SsnL** [comment]
Oh actually we have magma 10.1 now!

**Comment by vishwakftw** [comment]
Have you installed the correct version of MAGMA? We have binaries available for 10.1.

**Comment by vishwakftw** [comment]
The environment summary says that 10.0.30 was used to build PyTorch, but you said that you use 10.1.68. Could you install the current PyTorch binary?

**Comment by jungomi** [comment]
I'm using the PyTorch from pip and I didn't install MAGMA because I was under the impression that it was only required to build PyTorch from source.

I never had to install anything else but the pip package and on that same machine replacing PyTorch with version 1.1.0 (also from pip), works just fine.

**Comment by vishwakftw** [comment]
@SsnL was partly right about the version mismatch- because I don’t think we have MAGMA for CUDA 10.1 on pip.

This mismatch would be the most likely cause for the issue.

**Comment by jungomi** [comment]
Using the conda version instead of the pip version fixes the problem.

I though it could have been the `cudatoolkit` that is being installed with the command from the installation instructions:

```
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
```

Then I tried to install the pip version on top of that:

```
pip install --user --force torch
```

With that it failed again.

After removing that again, and going back to the conda version:

```
pip uninstall torch
```

It worked again.

**Comment by vishwakftw** [comment]
Glad that it worked out. Feel free to close it if you think the issue is resolved.

**Comment by jungomi** [comment]
Yes, thanks for the help.

**Comment by benelot** [comment]
Should this not be notified to the pip maintainers of the torch package or something? I have the same problem with code I run in google colab since they probably just installed their package right away from pip. Currently, I have to downgrade torch to 1.1.0 every time I run it.
