### ISSUE TITLE
cuda runtime error (60)

### ISSUE THREAD

**Issue by Penn000** [pytorch/pytorch#25019]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

hi, when I change gpu ids from [0, 1] to [0, 1, 2, 3] to run my program, it arises `RuntimeError: cuda runtime error (60) : peer mapping resources exhausted at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCGeneral.cpp:164`, what is it? I can't find solution on google or stackoverflow. does somebody know it? thx!

**Comment by andreaskoepf** [comment]
How many GPUs are you using? You might want to google for "CUDA_ERROR_TOO_MANY_PEERS".

From the [nvidia forum](https://devtalk.nvidia.com/default/topic/970010/cuda-programming-and-performance/cuda-peer-resources-error-when-running-on-more-than-8-k80s-aws-p2-16xlarge-/post/4994583/#4994583):

"The CUDA peer-to-peer system can use a maximum of 8 GPUs in a peer-to-peer (P2P) ensemble.

Since K80 consists of 2 GPU devices, a maximum of 4 K80's could participate (i.e. all of their GPU devices could participate) in a single P2P ensemble.

16 GPUs could still be used in 2 separate ensembles, I believe. If I were doing this, I would run two separate applications/processes, and for each I would specify an appropriate 8-gpu-device-ensemble using a mechanism such as CUDA_VISIBLE_DEVICES environment variable."

**Comment by ifedan** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.

**Comment by SiyuWang15** [comment]
I came into the same problem, and I really set CUDA_VISIBLE_DEVICES=0,1 and I still got the error. Do you solve the problem?

**Comment by Penn000** [comment]
@SiyuWang15 I met this problem for the sake of CUDA installed on server is V7.5, which is not match with cudatoolkit and pytorch. The problem is solved after reinstalling the CUDA.

**Comment by SiyuWang15** [comment]
@Penn000  I solved this problem this afternoon by running my codes on another gpu server. I don't exactly know why but I guess not enough cpu memory caused that.

**Comment by gdxie1** [comment]
I met the same problem. When I simply use CUDA_VISIBLE_DEVICES=0,1, the problem arose. 
I solved it by use "export CUDA_VISIBLE_DEVICES=0,1" in my script.

**Comment by rashad101** [comment]
> I met the same problem. When I simply use CUDA_VISIBLE_DEVICES=0,1, the problem arose.
> I solved it by use "export CUDA_VISIBLE_DEVICES=0,1" in my script.

This also solved my problem. Thanks

**Comment by abcliguanxi** [comment]
> export CUDA_VISIBLE_DEVICES=0,1

this also solved my problem,Thanks

**Comment by jasperhyp** [comment]
gosh this also solved my problem!
