### ISSUE TITLE
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by luanyunteng** [pytorch/pytorch#25173]
##  import torchvision error

I install by `pip3 install torch torchvision` in a virtualenv,
and the system is ubuntu 16.04
CUDA version is 10.0
GPU is 2080Ti

I could import torch successfully, however, when I run `import torchvision`:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lyt/venv_pytorch/lib/python3.5/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/lyt/venv_pytorch/lib/python3.5/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/home/lyt/venv_pytorch/lib/python3.5/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/lyt/venv_pytorch/lib/python3.5/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/lyt/venv_pytorch/lib/python3.5/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/lyt/venv_pytorch/lib/python3.5/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

How could I fix it?

cc @ezyang

**Comment by peterjc123** [comment]
Please use the install commands on https://pytorch.org.

**Comment by peterjc123** [comment]
Sorry, I didn't see the post carefully. Would you please try whether the following command solves your problem? `pip3 install torch===1.2.0 torchvision===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by 1224wxwx** [comment]
> Sorry, I didn't see the post carefully. Would you please try whether the following command solves your problem? `pip3 install torch===1.2.0 torchvision===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html`

I got the same error and the command didn't solve my problem.

**Comment by peterjc123** [comment]
cc @soumith

**Comment by ezyang** [comment]
So, I thought we don't build CUDA 9.0 binaries anymore. Do we still do so for Windows?

**Comment by peterjc123** [comment]
No, we don't do that. But this issue about users get cuda 9.0 binaries when specifying CUDA 10.0.

**Comment by ezyang** [comment]
So, I made a bunch of packaging changes for Linux/OS X to make it more difficult to get the wrong binary when you installed torch (specifically, I hard-code a specific dependency on +cu100, etc. version in the setup.py). But I didn't apply those changes to the Windows packaging. Maybe that is what is at fault.

**Comment by peterjc123** [comment]
I apply the same changes to the Windows packages and from their description, they are having Ubuntu as the operating system.

**Comment by ezyang** [comment]
oh oops, I assumed it was Windows because you were commenting XD

**Comment by luanyunteng** [comment]
I just reinstall it again, and the error is fixed. However, I do not know why.

**Comment by peterjc123** [comment]
Maybe it's just something wrong about the cache. Closing it.

**Comment by yicai** [comment]
torchvision and cuda  version dis-match.

pls try:  pip install torchvision==0.2.2 ,  and my problem is sloved.

**Comment by pl4yer57** [comment]
@yicai thank you solved my problem!
