### ISSUE TITLE
torch.bmm produces incorrect results for GPU fp16 tensors with batch size > 65535

### ISSUE THREAD

**Issue by felix-schneider** [pytorch/pytorch#25241]
## 🐛 Bug

When using `torch.bmm` to multiply GPU matrices in FP16 with a batch size > 65535, the results are only correct for the first 65535 batch entries, after that is garbage.

## To Reproduce

Minimal example:

```python
import torch

torch.manual_seed(1234)

mat_a = torch.rand(65536, 8, 64).cuda()
mat_b = torch.rand(65536, 64, 8).cuda()

mat_a_half = mat_a.half()
mat_b_half = mat_b.half()

res = torch.bmm(mat_a, mat_b)
res_half = torch.bmm(mat_a_half, mat_b_half)

print(res[65534, 0])
print(res_half[65534, 0])
print("-" * 80)
print(res[65535, 0])
print(res_half[65535, 0])

assert torch.allclose(res, res_half.float(), atol=1e-1)
```

In my case, the output is:
```
tensor([13.3080, 16.3155, 15.8803, 14.1044, 14.4463, 14.3881, 12.6462, 15.0877],
       device='cuda:0')
tensor([13.3047, 16.3125, 15.8828, 14.1016, 14.4453, 14.3906, 12.6484, 15.0859],
       device='cuda:0', dtype=torch.float16)
--------------------------------------------------------------------------------
tensor([16.6753, 16.2456, 15.2091, 16.5250, 15.8137, 14.3729, 15.5661, 16.0661],
       device='cuda:0')
tensor([0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0', dtype=torch.float16)
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    assert torch.allclose(res, res_half.float(), atol=1e-1)
AssertionError
```

Note that the incorrect entries were not always zero in all my tests.

## Expected behavior

The output tensors should be the same (to within floating point accuracy) after the index 65535.

## Environment

```
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.2.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: TITAN V
GPU 5: TITAN V
GPU 6: TITAN V
GPU 7: TITAN V

Nvidia driver version: 418.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchtext==0.4.0
[pip] torchvision==0.3.0
[pip] xnmtorch==0.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.0.2            py37h7b6447c_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchtext                 0.4.0                     dev_0    <develop>
[conda] torchvision               0.3.0           py37_cu10.0.130_1    pytorch
[conda] xnmtorch                  0.1                       dev_0    <develop>
```

The test was run while restricting to one GPU (using `CUDA_VISIBLE_DEVICES`) and was tested on both the 2080 Ti and the Titan V GPUs

cc @ezyang @gchanan

**Comment by ptrblck** [comment]
@felix-schneider Thanks for the code snippet to reproduce this issue.
I cannot reproduce it in CUBLAS 10.2.1.243 and this issue might be related to [this one](https://github.com/pytorch/pytorch/issues/24018#issuecomment-528004576). I try to narrow down the potential version, which fixed it.

**Comment by pbelevich** [comment]
I tried to reproduce it with master on devgpu with Tesla M40:
```
     12
     13 res = torch.bmm(mat_a, mat_b)
---> 14 res_half = torch.bmm(mat_a_half, mat_b_half)
     15

RuntimeError: cublas runtime error : unknown error at /data/users/pbelevich/pytorch/aten/src/THC/THCBlas.cu:271
```
```
PyTorch version: 1.3.0a0+ef98e45
Is debug build: No
CUDA used to build PyTorch: 9.2.88

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.88
GPU models and configuration:
GPU 0: Tesla M40
GPU 1: Tesla M40
GPU 2: Tesla M40
GPU 3: Tesla M40
GPU 4: Tesla M40
GPU 5: Tesla M40
GPU 6: Tesla M40
GPU 7: Tesla M40

Nvidia driver version: 396.69
cuDNN version: /usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.3.0a0+ef98e45
[conda] blas                      1.0                         mkl
[conda] magma-cuda92              2.5.1                         1    pytorch
[conda] mkl                       2019.4                      243
[conda] mkl-include               2019.4                      243
[conda] mkl-service               2.0.2            py37h7b6447c_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] torch                     1.3.0a0+ef98e45           dev_0    <develop>
```

devfair with Quadro GP100: works perfectly even with size = 1048576
```
PyTorch version: 1.3.0a0+b0bb5e3
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 410.79
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.3.0a0+b0bb5e3
[pip] torchvision==0.4.0
[conda] blas                      1.0                         mkl
[conda] magma-cuda100             2.5.1                         1    pytorch
[conda] mkl                       2019.4                      243
[conda] mkl-include               2019.4                      243
[conda] mkl-service               2.0.2            py37h7b6447c_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] torch                     1.3.0a0+b0bb5e3           dev_0    <develop>
[conda] torchvision               0.4.0                    pypi_0    pypi
```

**Comment by pbelevich** [comment]
@felix-schneider what version of cublas did you use?

**Comment by ngimel** [comment]
It looks like it depends on both cublas version and GPU architecture, so e.g. P100 and cuda 10 is ok, but V100/Turing and cuda 10 is not.

**Comment by ptrblck** [comment]
@felix-schneider Could you run the code again with the PyTorch 1.3.0 binaries + CUDA10.1.243, as it should be fixed?

**Comment by felix-schneider** [comment]
The output is now:
```
tensor([13.3080, 16.3155, 15.8803, 14.1044, 14.4463, 14.3881, 12.6462, 15.0877],
       device='cuda:0')
tensor([13.3047, 16.3125, 15.8828, 14.1016, 14.4453, 14.3906, 12.6484, 15.0859],
       device='cuda:0', dtype=torch.float16)
--------------------------------------------------------------------------------
tensor([16.6753, 16.2456, 15.2091, 16.5250, 15.8137, 14.3729, 15.5661, 16.0661],
       device='cuda:0')
tensor([16.6719, 16.2500, 15.2109, 16.5312, 15.8125, 14.3750, 15.5625, 16.0625],
       device='cuda:0', dtype=torch.float16)
```
which is expected. It seems that the problem is fixed.
