### ISSUE TITLE
external nccl breaks gloo compilation

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#2553]
Currently, you can have a libnccl on your system, and pytorch setup favors that instead of compiling one itself from source. The code that takes care of this is:
https://github.com/pytorch/pytorch/blob/master/setup.py#L316-L318

However, this breaks gloo build because gloo gets a path to NCCL via: https://github.com/pytorch/pytorch/blob/master/torch/lib/build_libs.sh#L40

**Comment by zhanghang1989** [comment]
I got the error during the installation:
```
CMake Error: The source directory "/home/username/pytorch/torch/lib/gloo" does not appear to contain CMakeLists.txt.
```
Is it related to this problem?

**Comment by ngimel** [comment]
@soumith, that's a dupe of #2375

**Comment by ngimel** [comment]
@zhanghang1989, no, that's a consequence of #2574, now you have to do ```git submodule update --init``` before compiling. I think you don't want to do recursive submodule update, because that will pull in gtest and another copy of nccl.

**Comment by apaszke** [comment]
Alternatively we can pass new flags to gloo to prevent it from using its own NCCL

**Comment by zhanghang1989** [comment]
Thanks @ngimel! `git submodule update --init` works for me.

**Comment by ngimel** [comment]
You can prevent it from using its own nccl, but its cmake still has to be able to find some nccl.

**Comment by ezyang** [comment]
I think `-DNCCL_EXTERNAL=1` should be sufficient. I'm testing.

**Comment by soumith** [comment]
`-DNCCL_EXTERNAL=1` fixes it when we dont have an external NCCL and pytorch compiles it's own NCCL?

**Comment by ngimel** [comment]
I don't see how NCCL_EXTERNAL fixes anything, looks like in gloo NCCL_EXTERNAL is used just to set dependency if gloo is compiling its own nccl (which we don't want in any case).
https://github.com/facebookincubator/gloo/search?utf8=%E2%9C%93&q=NCCL_EXTERNAL&type=

**Comment by ezyang** [comment]
The only thing I tested when I added `NCCL_EXTERNAL` was that the vendored nccl was not being built (even if its submodule was checked out); I tested this by adding an `#error` to one of the headers. I'll test with the other configurations.

**Comment by ezyang** [comment]
Actually, there are a few bugs here.

First, even though GLOO_FLAGS looks like it's setting NCCL_ROOT_DIR:

```
GLOO_FLAGS=""
if [[ $WITH_CUDA -eq 1 ]]; then
    GLOO_FLAGS="-DUSE_CUDA=1 -DNCCL_ROOT_DIR=$INSTALL_DIR"
fi
```

it actually isn't because the gloo invocation is

```
        build gloo $GLOO_FLAGS
```

which expands to `build gloo -DUSE_CUDA=1 -DNCCL_ROOT_DIR=$INSTALL_DIR` but only `$2` is passed to cmake.

Suppose you fix this. nccl is still not going to be picked up, because INSTALL_DIR is PyTorch's local install dir, but if you disabled nccl builds, there will never actually be a nccl here. So cmake is just going to do it's standard search to find a nccl somewhere. Inversely, if you ever built nccl, and then turn it off, we will keep picking up that locally built version until you delete it. So we shouldn't do that.

Suppose you fix this. Then I think gloo will (continue to) correctly pick up system nccl and be built with it, and the final thing to fix is that build of PyTorch csrc doesn't know how to search for nccl headers somewhere. This is probably related to #2375.

I wonder, maybe we shouldn't do any autodetection at all, and force the user to pass us the include and library paths of nccl if they want to build with system.

**Comment by pietern** [comment]
FYI, I committed a change to gloo to stop bundling NCCL itself. It will now happily pick up whatever NCCL you give it through NCCL_ROOT_DIR or by trying to find it in the standard systems paths. See facebookincubator/gloo@84c1c69f919ff7230fde57e3a14831f16f61f0c9. You do have to set `-DUSE_NCCL=1` to make Gloo try and find it and compile in support.

**Comment by pietern** [comment]
So to fix this, you should be able to not specify anything aside from `-DUSE_NCCL=1` if you want to use system NCCL, and add `-DNCCL_ROOT_DIR` if you have some custom location (either a PyTorch bundled version or a custom install altogether).

**Comment by ghltshubh** [comment]
Is there no cudnn.h in CUDA 8? I am getting 
1. In file included from /autofs/nccs-svm1_home1/shubhankar/pytorch/caffe2/python/pybind_state_gpu.cc:13:0:
/autofs/nccs-svm1_home1/shubhankar/pytorch/caffe2/core/common_cudnn.h:7:19: fatal error: cudnn.h: No such file or directory
 #include <cudnn.h>


2. make[2]: *** [caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state_gpu.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....

3. CMakeFiles/proto_utils_test.dir/utils/proto_utils_test.cc.o: In function `caffe2::ProtoUtilsTest_SimpleReadWrite_Test::TestBody()':
proto_utils_test.cc:(.text+0x4c): warning: the use of `tmpnam' is dangerous, better use `mkstemp'

4. make[2]: *** [caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state.cc.o] Error 1
make[2]: *** [caffe2/CMakeFiles/blob_test.dir/core/blob_test.cc.o] Error 1
make[1]: *** [caffe2/CMakeFiles/blob_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [caffe2/CMakeFiles/basic.dir/__/aten/src/ATen/test/basic.cpp.o] Error 1
make[1]: *** [caffe2/CMakeFiles/basic.dir/all] Error 2

5. ?/{usr?/:bin /finalld :close  finalfailed :link  Inputfailed/:output  Inputerror/
output/ usrerror/
bin//usrsha1sum/:bin /.sha1sum.:/ bin././operator_fallback_gpu_testbin:/ Nodepthwise3x3_conv_op_test :such  Nofile  suchor  file directoryor
 directory
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make[2]: make[2]: *** [bin/depthwise3x3_conv_op_test] Error 1*** [bin/operator_fallback_gpu_test] Error 1

make[1]: *** [caffe2/CMakeFiles/depthwise3x3_conv_op_test.dir/all] Error 2
make[1]: *** [caffe2/CMakeFiles/operator_fallback_gpu_test.dir/all] Error 2


6. make[1]: *** [caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/all] Error 2

7.  make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 libshm gloo c10d T
