### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered - yesterday it worked

### ISSUE THREAD

**Issue by lr91-089** [pytorch/pytorch#25537]
I have problems running this file on my machine: https://colab.research.google.com/github/Curt-Park/rainbow-is-all-you-need/blob/master/08.rainbow.ipynb

Yesterday everything worked fine, now I am alway getting this CUDA error. Appears also on my other code, which was working fine before.

cuda
Traceback (most recent call last):

  File "<ipython-input-14-f1898308ae81>", line 1, in <module>
    runfile('D:/Dokumente/TUM/Masterthesis/PythonModel/BestModels/rainbow/08_rainbow.py', wdir='D:/Dokumente/TUM/Masterthesis/PythonModel/BestModels/rainbow')

  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Dokumente/TUM/Masterthesis/PythonModel/BestModels/rainbow/08_rainbow.py", line 858, in <module>
    agent = DQNAgent(env, memory_size, batch_size, target_update)

  File "D:/Dokumente/TUM/Masterthesis/PythonModel/BestModels/rainbow/08_rainbow.py", line 593, in __init__
    ).to(self.device)

RuntimeError: CUDA error: device-side assert triggered

Any ideas how to solve it?

**Comment by peterjc123** [comment]
Could you find something useful here?
https://github.com/pytorch/pytorch/issues/1204

**Comment by lr91-089** [comment]
Thanks @peterjc123 
Partly. I did a pytorch and cuda downgrade to conda install pytorch=0.4.1 cuda90 -c pytorch, now it works.

Any idea why the new versions are not working?

Full error message:

cuda
5C:/w/1/s/tmp_conda_3.6_114131/conda/conda-bld/pytorch_1567251986110/work/aten/src/THC/THCTensorIndex.cu:189: block: [25,0,0], thread: [63,0,0] Assertion `dstIndex < dstAddDimSize` failed.
Traceback (most recent call last):
  File "rainbow.py", line 763, in <module>
    agent.train(epochs)
  File "rainbow.py", line 629, in train
    loss = self.update_model()
  File "rainbow.py", line 578, in update_model
    elementwise_loss_n_loss = self._compute_dqn_loss(samples, gamma)
  File "rainbow.py", line 710, in _compute_dqn_loss
    dist = self.dqn.dist(state)
  File "rainbow.py", line 387, in dist
    feature = self.feature_layer(x)
  File "C:\Users\un_po\Anaconda3\envs\rl-env\lib\site-packages\torch\nn\modules\module.py", line 545, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\un_po\Anaconda3\envs\rl-env\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\un_po\Anaconda3\envs\rl-env\lib\site-packages\torch\nn\modules\module.py", line 545, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\un_po\Anaconda3\envs\rl-env\lib\site-packages\torch\nn\modules\linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\un_po\Anaconda3\envs\rl-env\lib\site-packages\torch\nn\functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: device-side assert triggered

Nvidia specs:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 436.15       Driver Version: 436.15       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060   WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8     6W /  N/A |     92MiB /  6144MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by peterjc123** [comment]
What about setting the environmental variable `CUDA_LAUNCH_BLOCKING=1` and then rerun that example?

**Comment by lr91-089** [comment]
Then I got the error message in my second post.
But downgrading seems  to work. I also installed a new nvidia driver today, maybe this is causing the issue? But I also un- and reinstalled the driver.

**Comment by peterjc123** [comment]
Could you please insert some code before this line and print out these values and their shapes?
```pytb
  File "C:\Users\un_po\Anaconda3\envs\rl-env\lib\site-packages\torch\nn\functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
```

**Comment by lr91-089** [comment]
Would the input be the x in this line?
```
 File "rainbow.py", line 387, in dist
    feature = self.feature_layer(x)
```

**Comment by peterjc123** [comment]
Yes, it should be `x`. But I  want to know the other two values `bias` and `weight` too.

**Comment by lr91-089** [comment]
```
X-tensor: tensor([[0.0966, 0.4998, 1.0000, 0.2143, 0.0164],
        [0.1607, 0.5231, 1.0000, 0.2857, 0.0219],
        [0.2535, 0.4962, 1.0000, 0.3571, 0.0273],
        [0.3150, 0.5427, 1.0000, 0.4286, 0.0328],
        [0.4314, 0.5616, 1.0000, 0.5000, 0.0383],
        [0.5555, 0.5357, 1.0000, 0.5714, 0.0437],
        [0.8409, 0.5187, 1.0000, 0.7143, 0.0546],
        [0.8409, 0.5187, 1.0000, 0.7143, 0.0546],
        [0.9362, 0.4129, 1.0000, 0.7857, 0.0601],
        [0.9389, 0.4930, 1.0000, 0.8571, 0.0656],
        [0.9287, 0.5291, 1.0000, 0.9286, 0.0710],
        [0.9148, 0.5880, 1.0000, 1.0000, 0.0765],
        [0.9148, 0.5880, 1.0000, 1.0000, 0.0765],
        [0.9148, 0.5880, 1.0000, 1.0000, 0.0765],
        [0.1223, 0.4955, 1.0000, 0.2857, 0.0219],
        [0.1223, 0.4955, 1.0000, 0.2857, 0.0219],
        [0.2180, 0.4886, 1.0000, 0.3571, 0.0273],
        [0.3848, 0.4203, 1.0000, 0.5000, 0.0383],
        [0.3848, 0.4203, 1.0000, 0.5000, 0.0383],
        [0.6486, 0.3935, 1.0000, 0.6429, 0.0492],
        [0.8023, 0.4568, 1.0000, 0.7143, 0.0546],
        [0.8023, 0.4568, 1.0000, 0.7143, 0.0546],
        [0.9055, 0.4803, 1.0000, 0.8571, 0.0656],
        [0.8938, 0.5155, 1.0000, 0.9286, 0.0710],
        [0.8858, 0.5976, 1.0000, 1.0000, 0.0765],
        [0.8858, 0.5976, 1.0000, 1.0000, 0.0765],
        [0.8858, 0.5976, 1.0000, 1.0000, 0.0765],
        [0.1044, 0.4968, 1.0000, 0.2143, 0.0164],
        [0.1651, 0.5090, 1.0000, 0.2857, 0.0219],
        [0.2575, 0.4929, 1.0000, 0.3571, 0.0273],
        [0.3177, 0.5142, 1.0000, 0.4286, 0.0328],
        [0.4365, 0.5715, 1.0000, 0.5000, 0.0383],
        [0.5661, 0.5371, 1.0000, 0.5714, 0.0437],
        [0.6990, 0.3731, 1.0000, 0.6429, 0.0492],
        [0.8536, 0.4542, 1.0000, 0.7143, 0.0546],
        [0.9491, 0.5377, 1.0000, 0.7857, 0.0601],
        [0.9560, 0.4722, 1.0000, 0.8571, 0.0656],
        [0.9471, 0.5078, 1.0000, 0.9286, 0.0710],
        [0.9313, 0.5556, 1.0000, 1.0000, 0.0765],
        [0.9313, 0.5556, 1.0000, 1.0000, 0.0765],
        [0.9313, 0.5556, 1.0000, 1.0000, 0.0765],
        [0.0804, 0.5133, 1.0000, 0.2143, 0.0164],
        [0.1423, 0.5190, 1.0000, 0.2857, 0.0219],
        [0.2394, 0.4825, 1.0000, 0.3571, 0.0273],
        [0.4074, 0.5533, 1.0000, 0.5000, 0.0383],
        [0.5376, 0.5345, 1.0000, 0.5714, 0.0437],
        [0.5376, 0.5345, 1.0000, 0.5714, 0.0437],
        [0.6711, 0.4358, 1.0000, 0.6429, 0.0492],
        [0.9216, 0.4641, 1.0000, 0.7857, 0.0601],
        [0.9216, 0.4641, 1.0000, 0.7857, 0.0601],
        [0.9303, 0.4757, 1.0000, 0.8571, 0.0656],
        [0.9196, 0.5143, 1.0000, 0.9286, 0.0710],
        [0.9075, 0.5852, 1.0000, 1.0000, 0.0765],
        [0.9075, 0.5852, 1.0000, 1.0000, 0.0765],
        [0.9075, 0.5852, 1.0000, 1.0000, 0.0765],
        [0.0825, 0.5112, 1.0000, 0.2143, 0.0164],
        [0.1420, 0.5097, 1.0000, 0.2857, 0.0219],
        [0.2364, 0.4865, 1.0000, 0.3571, 0.0273],
        [0.4102, 0.4430, 1.0000, 0.5000, 0.0383],
        [0.5375, 0.6238, 1.0000, 0.5714, 0.0437],
        [0.6707, 0.4532, 1.0000, 0.6429, 0.0492],
        [0.8255, 0.2652, 1.0000, 0.7143, 0.0546],
        [0.9208, 0.4288, 1.0000, 0.7857, 0.0601],
        [0.0000, 0.4878, 0.9636, 0.0000, 0.0656]], device='cuda:0') weight-tensor: Parameter containing:
tensor([[-0.3734,  0.3161,  0.0996,  0.2442, -0.1595],
        [-0.2662,  0.0612,  0.3732, -0.0944,  0.0957],
        [-0.1173, -0.1154,  0.2352, -0.2978,  0.3999],
        [ 0.2761,  0.2907, -0.1543,  0.1034, -0.0534],
        [-0.2571, -0.2808, -0.0150,  0.3931, -0.3421],
        [-0.1852, -0.3157,  0.1033,  0.1615, -0.1933],
        [-0.1524,  0.3934, -0.3712, -0.4113,  0.0271],
        [ 0.1970,  0.2263, -0.1470,  0.4033,  0.3916],
        [ 0.3935, -0.0994,  0.4162,  0.0541, -0.0186],
        [-0.2060,  0.4312, -0.3696,  0.2850,  0.2905],
        [-0.0022,  0.1726, -0.1714, -0.4120,  0.3267],
        [ 0.0416,  0.0353, -0.4196,  0.3645,  0.3494],
        [ 0.2480, -0.3457,  0.0450, -0.0888,  0.0921],
        [ 0.2898, -0.1654, -0.2198, -0.1305,  0.1143],
        [-0.1438,  0.0527,  0.4029,  0.4296,  0.2450],
        [ 0.0621, -0.1332, -0.3792, -0.1452, -0.2068],
        [ 0.2395,  0.2141, -0.4331, -0.0892,  0.1816],
        [-0.1270,  0.1724, -0.2525,  0.4327, -0.3766],
        [ 0.3978,  0.3829,  0.3145,  0.0266,  0.3325],
        [-0.4396,  0.0928, -0.2067, -0.3383,  0.2727],
        [ 0.2536, -0.1647,  0.2435, -0.1929,  0.4073],
        [-0.2202, -0.2205, -0.1504, -0.0211,  0.0181],
        [-0.3921,  0.0225,  0.0606,  0.2245, -0.4002],
        [ 0.2944,  0.1924,  0.1344, -0.0895,  0.3855],
        [ 0.1352, -0.2332,  0.1783, -0.2048,  0.2991],
        [ 0.3728, -0.0934,  0.3848,  0.2411, -0.3239],
        [ 0.1624,  0.3680, -0.0278, -0.4151,  0.1564],
        [-0.2820,  0.1316,  0.4393, -0.3855, -0.3037],
        [-0.0118,  0.0697,  0.1839, -0.1895,  0.3729],
        [ 0.0602,  0.1946, -0.2394,  0.0987,  0.4307],
        [ 0.1882, -0.4151, -0.1522,  0.1199,  0.3760],
        [-0.2405,  0.4344,  0.2478,  0.2685,  0.0587],
        [-0.0706,  0.3291,  0.0259, -0.3197, -0.3109],
        [-0.1179, -0.3429, -0.1125, -0.0772, -0.1782],
        [ 0.1513,  0.2418,  0.4385,  0.2863, -0.3633],
        [ 0.2388,  0.1648,  0.0999, -0.3769, -0.3784],
        [-0.2290,  0.0247, -0.3213,  0.1120,  0.3148],
        [ 0.0503,  0.1597, -0.4257, -0.4142,  0.0976],
        [ 0.3146,  0.3519,  0.4088, -0.2033, -0.3151],
        [-0.4109, -0.3416,  0.0643,  0.3063,  0.4181],
        [-0.0478, -0.2036,  0.4446, -0.2136, -0.1947],
        [ 0.3950, -0.2729,  0.0791,  0.1141, -0.0281],
        [ 0.1592, -0.0718,  0.2512, -0.0523, -0.4444],
        [ 0.1715, -0.4154,  0.2372, -0.3296, -0.1424],
        [-0.0611,  0.4362, -0.3599,  0.1851,  0.3870],
        [ 0.1186,  0.2285, -0.0442, -0.0823,  0.4102],
        [ 0.2100, -0.1096,  0.0391, -0.3782,  0.0080],
        [ 0.4471,  0.3709,  0.2498,  0.1845, -0.3295],
        [ 0.1825,  0.3164, -0.1553, -0.0628,  0.2055],
        [ 0.2520, -0.0208,  0.0879,  0.3667, -0.0854],
        [-0.3825, -0.1077, -0.0011, -0.4290,  0.2207],
        [ 0.3010,  0.3401,  0.3079,  0.1596, -0.1537],
        [ 0.2391, -0.2995, -0.0890, -0.2818, -0.0710],
        [ 0.3503, -0.2023, -0.3616, -0.1167, -0.0967],
        [-0.1894, -0.2739, -0.3284, -0.3793, -0.2694],
        [-0.1840,  0.0243,  0.2967, -0.0857, -0.4192],
        [ 0.2077,  0.0300,  0.0740,  0.1109, -0.3731],
        [ 0.3524, -0.3960, -0.2170, -0.4430,  0.3666],
        [-0.4469, -0.0623,  0.2683, -0.4264,  0.3847],
        [-0.2539,  0.3993,  0.2296,  0.4165,  0.0360],
        [ 0.3815, -0.2168, -0.1215, -0.2887, -0.1709],
        [ 0.4438, -0.1404,  0.3542, -0.1282,  0.1013],
        [-0.1826,  0.2179, -0.2127, -0.0541, -0.3070],
        [-0.4167,  0.1256, -0.4459, -0.0291,  0.2769],
        [ 0.4117,  0.3886,  0.0033,  0.0336, -0.2435],
        [ 0.1371, -0.2124,  0.4413, -0.0811, -0.0205],
        [ 0.2711,  0.2374,  0.2743, -0.1104, -0.2828],
        [ 0.1762, -0.1136, -0.3584, -0.1727, -0.0672],
        [-0.0482,  0.1174, -0.1587, -0.2705, -0.2734],
        [-0.2146, -0.3401, -0.3800, -0.3924, -0.4107],
        [-0.3063,  0.0101,  0.3600, -0.3988, -0.1448],
        [-0.1099,  0.2110, -0.3372,  0.2355, -0.0438],
        [-0.1697,  0.4072,  0.3402, -0.2105,  0.2099],
        [-0.2003, -0.3394, -0.1139, -0.2225,  0.3828],
        [-0.0987,  0.1328,  0.1459,  0.1367,  0.2731],
        [ 0.3758, -0.0134,  0.1923, -0.0204,  0.0859],
        [ 0.3907, -0.1017,  0.2068,  0.1853,  0.3852],
        [ 0.3719,  0.2997,  0.3033, -0.4468,  0.0085],
        [ 0.2854,  0.1571,  0.1212,  0.0050,  0.1446],
        [-0.3038, -0.1560, -0.0870,  0.2865, -0.3420],
        [ 0.3414, -0.1086,  0.0106, -0.3617, -0.2502],
        [ 0.4160, -0.1724,  0.3352, -0.4437,  0.3014],
        [-0.2102,  0.2256,  0.2382,  0.3484,  0.0767],
        [-0.0398,  0.3586,  0.3979,  0.0803,  0.3840],
        [-0.0316,  0.2225, -0.1941,  0.1116, -0.0645],
        [-0.1004, -0.0962,  0.3964,  0.1549, -0.2622],
        [ 0.0411,  0.2712,  0.0116,  0.3561, -0.2491],
        [ 0.2155,  0.2110,  0.3669,  0.2620, -0.2209],
        [-0.4286, -0.3548,  0.2004,  0.3278, -0.2792],
        [ 0.4462, -0.0828, -0.0527, -0.3143,  0.3964],
        [-0.1797,  0.2302, -0.2067,  0.4361,  0.2438],
        [ 0.3527, -0.1347,  0.3873,  0.2871, -0.2746],
        [ 0.1693,  0.3117, -0.2229, -0.3353,  0.3192],
        [-0.3096, -0.2497,  0.3368, -0.1047, -0.2475],
        [ 0.0510, -0.2777,  0.3701, -0.3160, -0.4467],
        [ 0.1633,  0.4311,  0.3066,  0.3084, -0.1997],
        [ 0.1077, -0.2649, -0.4200, -0.3931, -0.1456],
        [ 0.1439,  0.1507,  0.2141, -0.2448, -0.2178],
        [-0.1369,  0.1000,  0.1308,  0.0868,  0.1557],
        [-0.0858, -0.1970, -0.1048,  0.0907,  0.1546],
        [ 0.3685,  0.3852,  0.2270,  0.3794, -0.2886],
        [-0.2368, -0.2260,  0.3286, -0.3553,  0.0514],
        [-0.3147, -0.3640, -0.3823,  0.3316,  0.0699],
        [ 0.3766, -0.2374, -0.1822,  0.0034, -0.3551],
        [ 0.3784, -0.1908,  0.0627, -0.2977, -0.1419],
        [-0.2994, -0.0684,  0.3376, -0.0884, -0.1821],
        [-0.3722, -0.1578,  0.3703, -0.2728, -0.2601],
        [ 0.0885,  0.1443,  0.3801, -0.4137, -0.3413],
        [ 0.0131, -0.2688,  0.3376,  0.1889,  0.4302],
        [ 0.0183, -0.1062, -0.0910,  0.2889, -0.0376],
        [ 0.3484,  0.0247,  0.3001,  0.2557, -0.4226],
        [-0.1666, -0.0090, -0.3396, -0.1254, -0.1651],
        [-0.1958, -0.0380, -0.3314,  0.2669,  0.4173],
        [ 0.0339,  0.4060,  0.3535,  0.1454, -0.2106],
        [-0.3047, -0.0237,  0.2301,  0.4397,  0.4357],
        [ 0.2233, -0.1683, -0.0899, -0.4248, -0.0035],
        [-0.3961, -0.3028,  0.2416,  0.1443, -0.0020],
        [ 0.2982,  0.1459,  0.2461,  0.2480, -0.1866],
        [ 0.1570, -0.2091, -0.3804,  0.3258, -0.0059],
        [-0.0838, -0.3534,  0.3834, -0.4384, -0.2606],
        [ 0.4399,  0.3886,  0.3049, -0.0844, -0.3339],
        [-0.2412, -0.1984,  0.2985, -0.1648,  0.2834],
        [ 0.0840,  0.2567, -0.1519, -0.0342,  0.4089],
        [-0.0658, -0.3230, -0.1302, -0.0511, -0.4060],
        [ 0.1153, -0.2072, -0.1827,  0.2645, -0.0908],
        [-0.1048,  0.1989,  0.1617,  0.2114,  0.0545],
        [-0.0856,  0.1638, -0.2672,  0.0729,  0.4414],
        [-0.2597,  0.0684, -0.1172,  0.0709,  0.1739]], device='cuda:0',
       requires_grad=True) bias-tensor: Parameter containing:
tensor([-0.4121, -0.2680,  0.3437,  0.3309, -0.1466, -0.2350, -0.3797, -0.2821,
        -0.1278,  0.3840, -0.2520, -0.0384,  0.3870, -0.2426,  0.3764,  0.3631,
         0.0580, -0.0817,  0.2886, -0.4239, -0.1227,  0.1342, -0.2911,  0.2356,
         0.1254,  0.3094,  0.3222,  0.3492, -0.0563,  0.0787,  0.0790,  0.0475,
        -0.0620, -0.2466,  0.0153,  0.2684,  0.4160,  0.0192, -0.3554,  0.3896,
        -0.1807, -0.1653,  0.3222,  0.2462, -0.3811, -0.0232, -0.1342, -0.3190,
        -0.0692, -0.1073,  0.1412,  0.2858,  0.4416,  0.3799, -0.0304,  0.0942,
        -0.3162, -0.0970, -0.2893,  0.3930, -0.2779,  0.4123, -0.4099, -0.1262,
         0.3631,  0.1191, -0.1953, -0.0528,  0.2297, -0.1849, -0.2701,  0.2762,
        -0.2263, -0.0765, -0.1990,  0.2963,  0.2974,  0.1819, -0.0951,  0.0901,
        -0.1446, -0.2855, -0.1965,  0.0583, -0.3327, -0.1822, -0.0286, -0.0959,
         0.2003, -0.1924,  0.3466, -0.0152, -0.3146, -0.2195, -0.2716,  0.4184,
        -0.3303, -0.2658, -0.3078,  0.0147,  0.1638, -0.1246,  0.0576,  0.4332,
         0.1825, -0.3162,  0.1732, -0.2859, -0.1827,  0.3686, -0.1244,  0.2515,
        -0.3614, -0.2369,  0.0778, -0.3364, -0.2306,  0.2620,  0.1740, -0.0486,
        -0.2809,  0.0748,  0.0133, -0.1514, -0.0919, -0.4121,  0.0982, -0.4283],
       device='cuda:0', requires_grad=True)
C:/w/1/s/tmp_conda_3.6_045031/conda/conda-bld/pytorch_1565412750030/work/aten/src/THC/THCTensorIndex.cu:189: block: [25,0,0], thread: [62,0,0] Assertion `dstIndex < dstAddDimSize` failed.
C:/w/1/s/tmp_conda_3.6_045031/conda/conda-bld/pytorch_1565412750030/work/aten/src/THC/THCTensorIndex.cu:189: block: [25,0,0], thread: [63,0,0] Assertion `dstIndex < dstAddDimSize` failed.
Traceback (most recent call last):
  File "rainbow.py", line 773, in <module>
    agent.train(epochs)
  File "rainbow.py", line 645, in train
    loss = self.update_model()
  File "rainbow.py", line 579, in update_model
    elementwise_loss_n_loss = self._compute_dqn_loss(samples, gamma)
  File "rainbow.py", line 720, in _compute_dqn_loss
    dist = self.dqn.dist(state)
  File "rainbow.py", line 388, in dist
    feature = self.feature_layer(x)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\nn\modules\linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\nn\functional.py", line 1369, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: device-side assert triggered
```

Mhm... is this a batch-size - layer missmatch? I am quite new in this tensor and neural network operations, so I don't really understand this so good...

**Comment by peterjc123** [comment]
No, the inputs are correct. I checked the result locally, but could not reproduce that.
@soumith @ezyang  Any ideas?

**Comment by peterjc123** [comment]
@lr91-089 Does it error out if you call this line directly? 
```python
torch.addmm(bias, input, weight.t())
```

**Comment by lr91-089** [comment]
No. When I just put in the tensors above, the code executes correctly.

```
>>> torch.addmm(bias, input, weight.t())
tensor([[-0.1409,  0.0914,  0.4526,  ..., -0.1149, -0.0725, -0.5184],
        [-0.1409,  0.0696,  0.4234,  ..., -0.1016, -0.0666, -0.5274],
        [-0.1675,  0.0370,  0.3965,  ..., -0.1013, -0.0713, -0.5473],
        ...,
        [-0.3712, -0.1605,  0.2606,  ..., -0.1302, -0.1201, -0.6816],
        [-0.3385, -0.1821,  0.2115,  ..., -0.0922, -0.0938, -0.6891],
        [-0.1724,  0.1277,  0.5403,  ..., -0.1557, -0.0504, -0.4965]])
```
This old build is working on another conda environment through: conda install pytorch=0.4.1 cuda90 -c pytorch

**Comment by ezyang** [comment]
I ran your script on PyTorch 1.2.0 on Linux with Tesla M40 Driver Version: 396.69 and was not able to repro. In your original test were you running 1.2.0 on CUDA 10? Can you try running it with 1.2.0 with CUDA 9.2?

**Comment by lr91-089** [comment]
Mhm after downgrading some scripts are working again, but the main file not. Is it maybe an error because of the input of my tensors? But it is basically a 5 d numpy array with each input values ranging from 0-1.

```
C:/w/1/s/tmp_conda_3.6_155139/conda/conda-bld/pytorch_1565366019852/work/aten/src/THC/THCTensorIndex.cu:189: block: [50,0,0], thread: [127,0,0] Assertion `dstIndex < dstAddDimSize` failed.
 steps: 125  episodes: 8  running reward: -0.4091374322Traceback (most recent call last):
  File "rainbow.py", line 773, in <module>
    agent.train(epochs)
  File "rainbow.py", line 645, in train
    loss = self.update_model()
  File "rainbow.py", line 568, in update_model
    elementwise_loss = self._compute_dqn_loss(samples, self.gamma)
  File "rainbow.py", line 720, in _compute_dqn_loss
    dist = self.dqn.dist(state)
  File "rainbow.py", line 396, in dist
    q_atoms = value + advantage - advantage.mean(dim=1, keepdim=True)
RuntimeError: CUDA error: device-side assert triggered

(rainbowPy) D:\Dokumente\TUM\Masterthesis\PythonModel\BestModels\rainbow>python rainbow.py
cuda
C:/w/1/s/tmp_conda_3.6_155139/conda/conda-bld/pytorch_1565366019852/work/aten/src/THC/THCTensorIndex.cu:189: block: [50,0,0], thread: [127,0,0] Assertion `dstIndex < dstAddDimSize` failed.
 steps: 125  episodes: 8  running reward: -0.4091374322Traceback (most recent call last):
  File "rainbow.py", line 773, in <module>
    agent.train(epochs)
  File "rainbow.py", line 645, in train
    loss = self.update_model()
  File "rainbow.py", line 568, in update_model
    elementwise_loss = self._compute_dqn_loss(samples, self.gamma)
  File "rainbow.py", line 720, in _compute_dqn_loss
    dist = self.dqn.dist(state)
  File "rainbow.py", line 388, in dist
    feature = self.feature_layer(x)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\nn\modules\linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\nn\functional.py", line 1369, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by ezyang** [comment]
`THCTensorIndex.cu:189: block: [50,0,0], thread: [127,0,0] Assertion `dstIndex < dstAddDimSize` failed.` looks relevant.

Are you doing an indexing operation somewhere in your program? (You didn't run this example with `CUDA_LAUNCH_BLOCKING=1` so the backtraces are too late--if you rerun with this envvar you'll get better back traces). If so, can you check that your indices are all in bounds?

**Comment by Wuziyi616** [comment]
Yeah, I also came across this error yesterday and it turned out to be "index out of range" error. Maybe you should check your index via pdb and make sure they're not out of range. Hope it will help you!

**Comment by lr91-089** [comment]
@ezyang I did run this example with CUDA_LAUNCH_BLOCKING=1. Its the second output above. I have put os.environ['CUDA_LAUNCH_BLOCKING'] = "1" in the code, that is correct right?

@Wuziyi616 could you please provide me more information about pdb debugging?
I basically pass values to the network, I want to investigate, right? And could you give me more information about what kind of index error? Maybe in the batch?

**Comment by ezyang** [comment]
@lr91-089 I actually think this does not actually work. Can you set the environment variable outside of the script?

**Comment by lr91-089** [comment]
Any ways to set it up in anaconda on windwos?
 
CUDA_LAUNCH_BLOCKING=1 python myscript.py does not work and did not find any other method than the os method.

**Comment by ezyang** [comment]
Yes, the last trace looks better. What's the full contents of the line at line 338?

**Comment by lr91-089** [comment]
Do you mean the tensors? This is the last output.

```
"Parameter containing:
tensor([[-0.0849,  0.0285,  0.0204,  ...,  0.0880,  0.0489,  0.0734],
        [ 0.0088, -0.0316,  0.0773,  ...,  0.0854,  0.0805, -0.0868],
        [-0.0383,  0.0710,  0.0835,  ...,  0.0758,  0.0208,  0.0019],
        ...,
        [-0.0037, -0.0028, -0.0285,  ...,  0.0766,  0.0176, -0.0440],
        [-0.0077, -0.0180,  0.0842,  ..., -0.0302,  0.0204,  0.0343],
        [-0.0404, -0.0514, -0.0560,  ...,  0.0157,  0.0820,  0.0326]],
       device='cuda:0', requires_grad=True)","Parameter containing:
tensor([[0.0442, 0.0442, 0.0442,  ..., 0.0442, 0.0442, 0.0442],
        [0.0442, 0.0442, 0.0442,  ..., 0.0442, 0.0442, 0.0442],
        [0.0442, 0.0442, 0.0442,  ..., 0.0442, 0.0442, 0.0442],
        ...,
        [0.0442, 0.0442, 0.0442,  ..., 0.0442, 0.0442, 0.0442],
        [0.0442, 0.0442, 0.0442,  ..., 0.0442, 0.0442, 0.0442],
        [0.0442, 0.0442, 0.0442,  ..., 0.0442, 0.0442, 0.0442]],
       device='cuda:0', requires_grad=True)","tensor([[-0.3787, -0.5588, -0.9302,  ...,  0.4656,  0.5676, -1.1919],
        [-0.4000, -0.5903, -0.9827,  ...,  0.4918,  0.5996, -1.2591],
        [-0.1744, -0.2574, -0.4285,  ...,  0.2145,  0.2615, -0.5491],
        ...,
        [ 0.1534,  0.2263,  0.3768,  ..., -0.1886, -0.2299,  0.4828],
        [-0.5306, -0.7830, -1.3035,  ...,  0.6524,  0.7954, -1.6703],
        [ 0.2233,  0.3295,  0.5485,  ..., -0.2745, -0.3347,  0.7029]],
       device='cuda:0')"
```
Got a new error message this time: 
```
cuda
C:/w/1/s/tmp_conda_3.6_155139/conda/conda-bld/pytorch_1565366019852/work/aten/src/THC/THCTensorIndex.cu:189: block: [50,0,0], thread: [127,0,0] Assertion `dstIndex < dstAddDimSize` failed.
THCudaCheck FAIL file=..\aten\src\THC\THCCachingHostAllocator.cpp line=296 error=59 : device-side assert triggered
 steps: 125  episodes: 8  running reward: -0.4091374322Traceback (most recent call last):
  File "rainbow_256.py", line 779, in <module>
    agent.train(epochs)
  File "rainbow_256.py", line 650, in train
    loss = self.update_model()
  File "rainbow_256.py", line 573, in update_model
    elementwise_loss = self._compute_dqn_loss(samples, self.gamma)
  File "rainbow_256.py", line 726, in _compute_dqn_loss
    dist = self.dqn.dist(state)
  File "rainbow_256.py", line 391, in dist
    adv_hid = F.relu(self.advantage_hidden_layer(feature))
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "rainbow_256.py", line 336, in forward
    writecsv((self.weight_mu,self.weight_sigma,self.weight_epsilon),1111),
  File "rainbow_256.py", line 45, in writecsv
    newFileWriter.writerow(line)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\nn\parameter.py", line 37, in __repr__
    return 'Parameter containing:\n' + super(Parameter, self).__repr__()
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\tensor.py", line 82, in __repr__
    return torch._tensor_str._str(self)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\_tensor_str.py", line 300, in _str
    tensor_str = _tensor_str(self, indent)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\_tensor_str.py", line 201, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\_tensor_str.py", line 234, in get_summarized_data
    return torch.stack([get_summarized_data(x) for x in (start + end)])
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\_tensor_str.py", line 234, in <listcomp>
    return torch.stack([get_summarized_data(x) for x in (start + end)])
  File "C:\Users\un_po\Anaconda3\envs\rainbowPy\lib\site-packages\torch\_tensor_str.py", line 227, in get_summarized_data
    return torch.cat((self[:PRINT_OPTS.edgeitems], self[-PRINT_OPTS.edgeitems:]))
RuntimeError: cuda runtime error (59) : device-side assert triggered at ..\aten\src\THC\THCCachingHostAllocator.cpp:296
```

**Comment by ezyang** [comment]
Sorry, not the tensor, I mean the code.

```
return torch.cat((self[:PRINT_OPTS.edgeitems], self[-PRINT_OPTS.edgeitems:]))
```

looks like an indexing operation. Though maybe `PRINT_OPTS` is just a plain old number?

**Comment by lr91-089** [comment]
Yes sorry, the second or new error message was just because I wrote the tensors to the csv files for tracing the error/result.
```

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Forward method implementation.
        
        We don't use separate statements on train / eval mode.
        It doesn't show remarkable difference of performance.
        """
        return F.linear(
            x,
            self.weight_mu + self.weight_sigma * self.weight_epsilon,
            self.bias_mu + self.bias_sigma * self.bias_epsilon,
        )
```

**Comment by ezyang** [comment]
Yeah, I don't know why the trace isn't showing up. You should manually audit your code looking for indexing operations.

**Comment by lr91-089** [comment]
Thanks a lot for  the help. I will try to trace the error in october, when I have more time.
Hopefully I can resolve it then :)

**Comment by YuhengLi9621** [comment]
I had this problem and it turns out I had a inf loss in my previous calculation.
In my case I have a mask for loss and I need to do something like 1/mask.mean() to scale loss value, and if mask is all zero, it would trigger this bug.

**Comment by brando90** [comment]
I had a similar error and for me it was resolved with this link:
```
Traceback (most recent call last):
  File "automl-proj/experiments/meta_learning/supervised_experiments_submission.py", line 465, in <module>
    main(args)
  File "automl-proj/experiments/meta_learning/supervised_experiments_submission.py", line 451, in main
    meta_valloader)
  File "/home/miranda9/automl-meta-learning/automl-proj/meta_learning/training/supervised_training.py", line 43, in supervised_train
    train_acc, acc5, train_loss = train(args, base_model, opt, train_sl_loader)
  File "/home/miranda9/automl-meta-learning/automl-proj/meta_learning/training/supervised_training.py", line 114, in train
    acc1, acc5 = accuracy(output, target, topk=(1, 5))
  File "/home/miranda9/ultimate-utils/ultimate-utils-project/torch_uutils/__init__.py", line 467, in accuracy
    correct = pred.eq(target.view(1, -1).expand_as(pred))
RuntimeError: CUDA error: device-side assert triggered

/opt/conda/conda-bld/pytorch_1595629427478/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.
  0%|                                                                                                                                                                                                                                                                                                                                                                                                 | 0/200 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "automl-proj/experiments/meta_learning/supervised_experiments_submission.py", line 465, in <module>
    main(args)
  File "automl-proj/experiments/meta_learning/supervised_experiments_submission.py", line 451, in main
    meta_valloader)
  File "/home/miranda9/automl-meta-learning/automl-proj/meta_learning/training/supervised_training.py", line 43, in supervised_train
    train_acc, acc5, train_loss = train(args, base_model, opt, train_sl_loader)
  File "/home/miranda9/automl-meta-learning/automl-proj/meta_learning/training/supervised_training.py", line 114, in train
    acc1, acc5 = accuracy(output, target, topk=(1, 5))
  File "/home/miranda9/ultimate-utils/ultimate-utils-project/torch_uutils/__init__.py", line 466, in accuracy
    _, pred = output.topk(maxk, 1, True, True)
RuntimeError: cuda runtime error (710) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1595629427478/work/aten/src/THC/generic/THCTensorSort.cu:151
```

does this not solve it for you?

**Comment by limberc** [comment]
Great! It works for me!!!

**Comment by RodeWayne** [comment]
I met the same error, then I set 'device = torch.device("cpu")' to run codes on cpu, the error statements were much more clear.
Anyone has a similar error can have a try.

**Comment by N1h1l1sT** [comment]
For me, what caused this particular problem was that my labels were from 1 to k instead of from 0 to k-1,
i.e. set(Y_Train) and set(Y_Test ) gave [1, 2, ..., k] instead of [0, 1, ..., k-1].

Hope someone finds this helpful
