### ISSUE TITLE
Cuda out of Memory

### ISSUE THREAD

**Issue by mnauf** [pytorch/pytorch#25659]
```

RuntimeError                              Traceback (most recent call last)
<ipython-input-22-33821ccddf5f> in <module>
     21         optimizer.zero_grad()
     22         # forward pass: compute predicted outputs by passing inputs to the model
---> 23         output = model(data)
     24         # calculate the batch loss
     25         loss = criterion(output, target)

C:\Users\mnauf\Anaconda3\envs\federated_learning\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

<ipython-input-20-03753f357697> in forward(self, x)
     27     def forward(self, x):
     28         # add sequence of convolutional and max pooling layers
---> 29         x = self.pool(F.relu(self.conv1(x)))
     30         x = self.pool(F.relu(self.conv2(x)))
     31         x = self.pool(F.relu(self.conv3(x)))

C:\Users\mnauf\Anaconda3\envs\federated_learning\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

C:\Users\mnauf\Anaconda3\envs\federated_learning\lib\site-packages\torch\nn\modules\conv.py in forward(self, input)
    318     def forward(self, input):
    319         return F.conv2d(input, self.weight, self.bias, self.stride,
--> 320                         self.padding, self.dilation, self.groups)
    321 
    322 

RuntimeError: CUDA out of memory. Tried to allocate 173.50 MiB (GPU 0; 4.00 GiB total capacity
```
I am working on the Horses vs humans dataset. [This is my code](https://github.com/mnauf/horses_humans/blob/master/Untitled.ipynb). I am using `criterion = nn.BCEWithLogitsLoss()` and `optimizer = optim.RMSprop(model.parameters(), lr=0.01)`. My final layer is `self.fc2 = nn.Linear(512, 1)`, because i read that if its horse, our last neuron should display 0 and in other case 1, so instead of choosing 2 neurons for output, I chose 1.

**Comment by mnauf** [comment]
I reduced the batch size to 16 and this error was solved.

**Comment by ailzhang** [comment]
@mnauf I'd suggest using `torch.cuda.memory_allocated(device=None)` to check which part takes more memory that expected.
I'll close this issue for now, please feel free to reopen if you think OOM is a bug on Pytorch side.
