### ISSUE TITLE
Pytorch 1.2.0 produce `unspecified launch failure` on Mac OS using CUDA.

### ISSUE THREAD

**Issue by TomHeaven** [pytorch/pytorch#25693]
## 🐛 Bug

The same OS and hardware run Pytorch 1.1.0 fairly well, but encounter this bug using Pytorch 1.2.0. Binary pytorch packages for Mac OS with CUDA support are available at: https://github.com/TomHeaven/pytorch-osx-build/releases.

## To Reproduce

Simply run the following demo code in console:
```
iMac18:~ tomheaven$ python3
Python 3.7.0 (default, Oct  2 2018, 09:20:07) 
[Clang 10.0.0 (clang-1000.11.45.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> a = torch.rand(4,4)
>>> ca = a.cuda()
>>> ca
```

The stack trace looks like this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/torch/tensor.py", line 82, in __repr__
    return torch._tensor_str._str(self)
  File "/usr/local/lib/python3.7/site-packages/torch/_tensor_str.py", line 300, in _str
    tensor_str = _tensor_str(self, indent)
  File "/usr/local/lib/python3.7/site-packages/torch/_tensor_str.py", line 201, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/usr/local/lib/python3.7/site-packages/torch/_tensor_str.py", line 87, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: scan failed to synchronize: unspecified launch failure
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
iMac18:~ tomheaven$ python3 collect.py 
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Mac OSX 10.13.6
GCC version: (GCC) 6.2.0
CMake version: version 3.13.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GeForce GTX 1080 Ti
Nvidia driver version: 1.1.0
cuDNN version: Probably one of the following:
/usr/local/cuda/lib/libcudnn.6.dylib
/usr/local/cuda/lib/libcudnn.7.dylib
/usr/local/cuda/lib/libcudnn.dylib
/usr/local/cuda/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy==1.17.1
[pip3] torch==1.2.0
[pip3] torchvision==0.2.1
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519

**Comment by colesbury** [comment]
Is this related to the issue described in https://github.com/pytorch/pytorch/pull/25553?

**Comment by TomHeaven** [comment]
I've re-built pytorch 1.2.0 with pull quest https://github.com/pytorch/pytorch/pull/25553, it solved the issue. We should consider merge that pull.

**Comment by gchanan** [comment]
closing because the referenced PR has merged.
