### ISSUE TITLE
specified alignment (8) is different from alignment (2) specified on a previous declaration

### ISSUE THREAD

**Issue by zaferarican** [pytorch/pytorch#2692]
macOS 10.12.6
CUDA 9.0rc
CUDNN 7.0 for CUDA 9.0rc
Python 3.6 (anaconda)
Xcode 8.3.3
Apple LLVM version 8.1.0 (clang-802.0.42)

MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install failed

CMake Warning:
  Manually-specified variables were not used by the project:

    ATEN_LIBRARIES
    CMAKE_DEBUG_POSTFIX
    CMAKE_INSTALL_LIBDIR
    CWRAP_FILES_BASE
    NCCL_EXTERNAL
    NO_CUDA
    THCS_LIBRARIES
    THCUNN_LIBRARIES
    THCUNN_SO_VERSION
    THC_LIBRARIES
    THD_SO_VERSION
    THNN_LIBRARIES
    THNN_SO_VERSION
    THPP_LIBRARIES
    THS_LIBRARIES
    TH_SO_VERSION
    nanopb_BUILD_GENERATOR

-- Build files have been written to: /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/THC
[  7%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o
[  7%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
[  7%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
[  8%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
[  8%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
[  9%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
[  9%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o
[  9%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
[ 10%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
[ 12%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMath2.cu.o
[ 13%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathBlas.cu.o
[ 14%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathMagma.cu.o
[ 15%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathPairwise.cu.o
[ 17%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathReduce.cu.o
[ 18%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathScan.cu.o
[ 19%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorIndex.cu.o
[ 20%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorConv.cu.o
[ 21%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorRandom.cu.o
[ 23%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorScatterGather.cu.o
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/THC/THCTensorRandom.cuh(156): error: specified alignment (4) is different from alignment (2) specified on a previous declaration
          detected during instantiation of "void sampleMultinomialOnce<T,AccT>(long *, long, int, T *, T *) [with T=half, AccT=float]" 
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/THC/generic/THCTensorRandom.cu(191): here

/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/THC/THCTensorRandom.cuh(95): error: specified alignment (4) is different from alignment (2) specified on a previous declaration
          detected during instantiation of "void renormRowsL1(T *, long, long) [with T=float]" 
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/THC/generic/THCTensorRandom.cu(120): here

/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/THC/THCTensorRandom.cuh(156): error: specified alignment (4) is different from alignment (2) specified on a previous declaration
          detected during instantiation of "void sampleMultinomialOnce<T,AccT>(long *, long, int, T *, T *) [with T=float, AccT=float]" 
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/THC/generic/THCTensorRandom.cu(191): here

/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/THC/THCTensorRandom.cuh(95): error: specified alignment (8) is different from alignment (2) specified on a previous declaration
          detected during instantiation of "void renormRowsL1(T *, long, long) [with T=double]" 
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/THC/generic/THCTensorRandom.cu(120): here

/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/THC/THCTensorRandom.cuh(156): error: specified alignment (8) is different from alignment (2) specified on a previous declaration
          detected during instantiation of "void sampleMultinomialOnce<T,AccT>(long *, long, int, T *, T *) [with T=double, AccT=double]" 
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/THC/generic/THCTensorRandom.cu(191): here

5 errors detected in the compilation of "/var/folders/67/xg4tb7ps26jgsnv19_cjdnq80000gn/T//tmpxft_00001041_00000000-11_THCTensorRandom.compute_61.cpp1.ii".
CMake Error at THC_generated_THCTensorRandom.cu.o.cmake:267 (message):
  Error generating file
  /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorRandom.cu.o

make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensorRandom.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/THC.dir/all] Error 2
make: *** [all] Error 2

**Comment by ngimel** [comment]
CUDA 8.0 and 9.0 are based on different EDG frontend sources. The 9.0 frontend code has newer paths that check for this alignment incompatibility. 
In any case, the compiler does not use the alignment information specified here; instead the runtime will always align the dynamically allocated shared memory at a fixed alignment(16). Usually it is just a warning, if you turned on -Werror,  just remove __align__ from the lines giving you trouble (/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/THC/THCTensorRandom.cuh(156) and (95)

**Comment by zaferarican** [comment]
Thanks, removing align solved that problem. Afterwards however, I got the the following error. 

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ATEN_LIBRARIES
    CMAKE_DEBUG_POSTFIX
    CMAKE_INSTALL_LIBDIR
    NCCL_EXTERNAL
    THCUNN_SO_VERSION
    THC_SO_VERSION
    THD_SO_VERSION
    THNN_SO_VERSION
    THPP_LIBRARIES
    TH_INCLUDE_PATH
    TH_LIB_PATH
    TH_SO_VERSION
    nanopb_BUILD_GENERATOR


-- Build files have been written to: /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen
[  1%] Generating ATen/CPUGenerator.h, ATen/CUDAGenerator.h, ATen/Declarations.yaml, ATen/CPUByteStorage.cpp, ATen/CPUByteStorage.h, ATen/CPUByteType.cpp, ATen/CPUByteType.h, ATen/CPUByteTensor.cpp, ATen/CPUByteTensor.h, ATen/CPUCharStorage.cpp, ATen/CPUCharStorage.h, ATen/CPUCharType.cpp, ATen/CPUCharType.h, ATen/CPUCharTensor.cpp, ATen/CPUCharTensor.h, ATen/CPUDoubleStorage.cpp, ATen/CPUDoubleStorage.h, ATen/CPUDoubleType.cpp, ATen/CPUDoubleType.h, ATen/CPUDoubleTensor.cpp, ATen/CPUDoubleTensor.h, ATen/CPUFloatStorage.cpp, ATen/CPUFloatStorage.h, ATen/CPUFloatType.cpp, ATen/CPUFloatType.h, ATen/CPUFloatTensor.cpp, ATen/CPUFloatTensor.h, ATen/CPUIntStorage.cpp, ATen/CPUIntStorage.h, ATen/CPUIntType.cpp, ATen/CPUIntType.h, ATen/CPUIntTensor.cpp, ATen/CPUIntTensor.h, ATen/CPULongStorage.cpp, ATen/CPULongStorage.h, ATen/CPULongType.cpp, ATen/CPULongType.h, ATen/CPULongTensor.cpp, ATen/CPULongTensor.h, ATen/CPUShortStorage.cpp, ATen/CPUShortStorage.h, ATen/CPUShortType.cpp, ATen/CPUShortType.h, ATen/CPUShortTensor.cpp, ATen/CPUShortTensor.h, ATen/CPUHalfStorage.cpp, ATen/CPUHalfStorage.h, ATen/CPUHalfType.cpp, ATen/CPUHalfType.h, ATen/CPUHalfTensor.cpp, ATen/CPUHalfTensor.h, ATen/SparseCPUByteType.cpp, ATen/SparseCPUByteType.h, ATen/SparseCPUByteTensor.cpp, ATen/SparseCPUByteTensor.h, ATen/SparseCPUCharType.cpp, ATen/SparseCPUCharType.h, ATen/SparseCPUCharTensor.cpp, ATen/SparseCPUCharTensor.h, ATen/SparseCPUDoubleType.cpp, ATen/SparseCPUDoubleType.h, ATen/SparseCPUDoubleTensor.cpp, ATen/SparseCPUDoubleTensor.h, ATen/SparseCPUFloatType.cpp, ATen/SparseCPUFloatType.h, ATen/SparseCPUFloatTensor.cpp, ATen/SparseCPUFloatTensor.h, ATen/SparseCPUIntType.cpp, ATen/SparseCPUIntType.h, ATen/SparseCPUIntTensor.cpp, ATen/SparseCPUIntTensor.h, ATen/SparseCPULongType.cpp, ATen/SparseCPULongType.h, ATen/SparseCPULongTensor.cpp, ATen/SparseCPULongTensor.h, ATen/SparseCPUShortType.cpp, ATen/SparseCPUShortType.h, ATen/SparseCPUShortTensor.cpp, ATen/SparseCPUShortTensor.h, ATen/CUDAByteStorage.cpp, ATen/CUDAByteStorage.h, ATen/CUDAByteType.cpp, ATen/CUDAByteType.h, ATen/CUDAByteTensor.cpp, ATen/CUDAByteTensor.h, ATen/CUDACharStorage.cpp, ATen/CUDACharStorage.h, ATen/CUDACharType.cpp, ATen/CUDACharType.h, ATen/CUDACharTensor.cpp, ATen/CUDACharTensor.h, ATen/CUDADoubleStorage.cpp, ATen/CUDADoubleStorage.h, ATen/CUDADoubleType.cpp, ATen/CUDADoubleType.h, ATen/CUDADoubleTensor.cpp, ATen/CUDADoubleTensor.h, ATen/CUDAFloatStorage.cpp, ATen/CUDAFloatStorage.h, ATen/CUDAFloatType.cpp, ATen/CUDAFloatType.h, ATen/CUDAFloatTensor.cpp, ATen/CUDAFloatTensor.h, ATen/CUDAIntStorage.cpp, ATen/CUDAIntStorage.h, ATen/CUDAIntType.cpp, ATen/CUDAIntType.h, ATen/CUDAIntTensor.cpp, ATen/CUDAIntTensor.h, ATen/CUDALongStorage.cpp, ATen/CUDALongStorage.h, ATen/CUDALongType.cpp, ATen/CUDALongType.h, ATen/CUDALongTensor.cpp, ATen/CUDALongTensor.h, ATen/CUDAShortStorage.cpp, ATen/CUDAShortStorage.h, ATen/CUDAShortType.cpp, ATen/CUDAShortType.h, ATen/CUDAShortTensor.cpp, ATen/CUDAShortTensor.h, ATen/CUDAHalfStorage.cpp, ATen/CUDAHalfStorage.h, ATen/CUDAHalfType.cpp, ATen/CUDAHalfType.h, ATen/CUDAHalfTensor.cpp, ATen/CUDAHalfTensor.h, ATen/SparseCUDAByteType.cpp, ATen/SparseCUDAByteType.h, ATen/SparseCUDAByteTensor.cpp, ATen/SparseCUDAByteTensor.h, ATen/SparseCUDACharType.cpp, ATen/SparseCUDACharType.h, ATen/SparseCUDACharTensor.cpp, ATen/SparseCUDACharTensor.h, ATen/SparseCUDADoubleType.cpp, ATen/SparseCUDADoubleType.h, ATen/SparseCUDADoubleTensor.cpp, ATen/SparseCUDADoubleTensor.h, ATen/SparseCUDAFloatType.cpp, ATen/SparseCUDAFloatType.h, ATen/SparseCUDAFloatTensor.cpp, ATen/SparseCUDAFloatTensor.h, ATen/SparseCUDAIntType.cpp, ATen/SparseCUDAIntType.h, ATen/SparseCUDAIntTensor.cpp, ATen/SparseCUDAIntTensor.h, ATen/SparseCUDALongType.cpp, ATen/SparseCUDALongType.h, ATen/SparseCUDALongTensor.cpp, ATen/SparseCUDALongTensor.h, ATen/SparseCUDAShortType.cpp, ATen/SparseCUDAShortType.h, ATen/SparseCUDAShortTensor.cpp, ATen/SparseCUDAShortTensor.h, ATen/Type.h, ATen/TypeMethods.h, ATen/Type.cpp, ATen/Tensor.h, ATen/TensorMethods.h, ATen/Functions.h, ATen/Dispatch.h, ATen/Copy.cpp
Excluding arange
Excluding arange
Excluding arange
Excluding arange
Excluding random_
Excluding random_
Excluding random_
Excluding random_
Excluding random_
Excluding random_
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal
Excluding normal_
Excluding normal_
Excluding normal_
Excluding normal_
Excluding normal_
Excluding normal_
Excluding exponential_
Excluding exponential_
Excluding exponential_
Excluding exponential_
Excluding bernoulli
Excluding bernoulli
Excluding bernoulli
Excluding bernoulli
Excluding bernoulli_
Excluding bernoulli_
Excluding bernoulli_
Excluding bernoulli_
Excluding bernoulli_
Excluding bernoulli_
Excluding bernoulli_
Excluding bernoulli_
Scanning dependencies of target ATen
[  2%] Building CXX object CMakeFiles/ATen.dir/CPUGenerator.cpp.o
[  6%] Building CXX object CMakeFiles/ATen.dir/Scalar.cpp.o
[  6%] Building CXX object CMakeFiles/ATen.dir/Context.cpp.o
[  6%] Building CXX object CMakeFiles/ATen.dir/Formatting.cpp.o
[  9%] Building CXX object CMakeFiles/ATen.dir/Utils.cpp.o
[  9%] Building CXX object CMakeFiles/ATen.dir/CUDAGenerator.cpp.o
[  9%] Building CXX object CMakeFiles/ATen.dir/ATen/CPUByteStorage.cpp.o
[ 10%] Building CXX object CMakeFiles/ATen.dir/ATen/CPUByteType.cpp.o
[ 11%] Building CXX object CMakeFiles/ATen.dir/ATen/CPUByteTensor.cpp.o
[ 12%] Building CXX object CMakeFiles/ATen.dir/ATen/CPUCharStorage.cpp.o
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/Formatting.cpp:1:
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Formatting.h:5:
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:16:14: error: 
      call to constructor of 'at::Scalar' is ambiguous
  Scalar() : Scalar(0L) {}
             ^      ~~
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
  AT_FORALL_SCALAR_TYPES(DEFINE_IMPLICIT_CTOR)
                         ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit move constructor
class Scalar {
      ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit copy constructor
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/CPUByteType.cpp:1:
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/CPUByteType.h:4:
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/TensorMethods.h:4:
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:16:14: error: 
      call to constructor of 'at::Scalar' is ambiguous
  Scalar() : Scalar(0L) {}
             ^      ~~
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
  AT_FORALL_SCALAR_TYPES(DEFINE_IMPLICIT_CTOR)
                         ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit move constructor
class Scalar {
      ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit copy constructor
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/Scalar.cpp:1:
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:16:14: error: 
      call to constructor of 'at::Scalar' is ambiguous
  Scalar() : Scalar(0L) {}
             ^      ~~
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
  AT_FORALL_SCALAR_TYPES(DEFINE_IMPLICIT_CTOR)
                         ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit move constructor
class Scalar {
      ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit copy constructor
[ 13%] Building CXX object CMakeFiles/ATen.dir/ATen/CPUCharType.cpp.o
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/CPUByteStorage.cpp:1:
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/CPUByteStorage.h:8:
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Storage.h:3:
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:16:14: error: 
      call to constructor of 'at::Scalar' is ambiguous
  Scalar() : Scalar(0L) {}
             ^      ~~
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
  AT_FORALL_SCALAR_TYPES(DEFINE_IMPLICIT_CTOR)
                         ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit move constructor
class Scalar {
      ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit copy constructor
1 error generated.
make[2]: *** [CMakeFiles/ATen.dir/Scalar.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [CMakeFiles/ATen.dir/ATen/CPUByteStorage.cpp.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/ATen.dir/Formatting.cpp.o] Error 1
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/CPUByteTensor.cpp:1:
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/CPUByteTensor.h:11:
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/TensorMethods.h:4:
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:16:14: error: 
      call to constructor of 'at::Scalar' is ambiguous
  Scalar() : Scalar(0L) {}
             ^      ~~
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
  AT_FORALL_SCALAR_TYPES(DEFINE_IMPLICIT_CTOR)
                         ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit move constructor
class Scalar {
      ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit copy constructor
1 error generated.
make[2]: *** [CMakeFiles/ATen.dir/ATen/CPUByteType.cpp.o] Error 1
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/CPUCharStorage.cpp:1:
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/CPUCharStorage.h:8:
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Storage.h:3:
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:16:14: error: 
      call to constructor of 'at::Scalar' is ambiguous
  Scalar() : Scalar(0L) {}
             ^      ~~
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
  AT_FORALL_SCALAR_TYPES(DEFINE_IMPLICIT_CTOR)
                         ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit move constructor
class Scalar {
      ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit copy constructor
1 error generated.
make[2]: *** [CMakeFiles/ATen.dir/ATen/CPUByteTensor.cpp.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/ATen.dir/ATen/CPUCharStorage.cpp.o] Error 1
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/CPUCharType.cpp:1:
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/CPUCharType.h:4:
In file included from /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/build/ATen/ATen/TensorMethods.h:4:
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:16:14: error: 
      call to constructor of 'at::Scalar' is ambiguous
  Scalar() : Scalar(0L) {}
             ^      ~~
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
  AT_FORALL_SCALAR_TYPES(DEFINE_IMPLICIT_CTOR)
                         ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:28:26: note: 
      candidate constructor
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit move constructor
class Scalar {
      ^
/Users/zafer/deeplearning/buildenv/pytorch/torch/lib/ATen/../ATen/Scalar.h:14:7: note: 
      candidate is the implicit copy constructor
1 error generated.
make[2]: *** [CMakeFiles/ATen.dir/ATen/CPUCharType.cpp.o] Error 1
make[1]: *** [CMakeFiles/ATen.dir/all] Error 2
make: *** [all] Error 2

**Comment by ngimel** [comment]
Same problem was reported in #2682, I don't think it is solved yet.

**Comment by soumith** [comment]
the alignment error is fixed now. we'll fix this scalar error soon as well, we;re tracking it in #2682

**Comment by soumith** [comment]
the second error should be fixed now as well

**Comment by zaferarican** [comment]
Thanks, it compiled fine without any errors after the update.

**Comment by Lareinahe** [comment]
killed Cmake Error at ATen_generated_THCTensorMode.cu.o
what can I do?
