### ISSUE TITLE
topk cudaerror traceback...

### ISSUE THREAD

**Issue by jmlago** [pytorch/pytorch#2753]
Recently I've been trying to use the topk function on a NN. But when I execute the following code ...

```
import torch
from torch.autograd import Variable


b_x = Variable(torch.rand(16*2775*300).view(1,16,2775,300).cuda())    
b_x=b_x.topk(20,2)[1]

print(b_x)
Traceback (most recent call last):

  File "<ipython-input-4-bc9526cb72e9>", line 1, in <module>
    print(b_x)

  File "/home/user/anaconda3/lib/python3.5/site-packages/torch/autograd/variable.py", line 117, in __repr__
    return 'Variable containing:' + self.data.__repr__()

  File "/home/user/anaconda3/lib/python3.5/site-packages/torch/tensor.py", line 133, in __repr__
    return str(self)

  File "/home/user/anaconda3/lib/python3.5/site-packages/torch/tensor.py", line 140, in __str__
    return _tensor_str._str(self)

  File "/home/user/anaconda3/lib/python3.5/site-packages/torch/_tensor_str.py", line 290, in _str
    strt = _tensor_str(self)

  File "/home/user/anaconda3/lib/python3.5/site-packages/torch/_tensor_str.py", line 138, in _tensor_str
    formatter = _number_format(self, min_sz=3 if not print_full_mat else 0)

  File "/home/user/anaconda3/lib/python3.5/site-packages/torch/_tensor_str.py", line 70, in _number_format
    tensor = torch.DoubleTensor(tensor.size()).copy_(tensor).abs_().view(tensor.nelement())

RuntimeError: cuda runtime error (6) : the launch timed out and was terminated at /opt/conda/conda-bld/pytorch_1502008109146/work/torch/lib/THC/generic/THCTensorCopy.c:65
```

The error says "the launch timed out and was terminated" so its not a OOM in theory...

If I execute the code with lower sizes in the b_x, it works (so to reproduce the error, probably you need to change the sizes of b_x).

But reproducing this with lower sizes of b_x but in a for loop, it also crashes with the same error cuda runtime error (6)...
```
for j in range(10):     
    b_x = Variable(torch.rand(16*675*300).view(1,16,675,300).cuda())    
    b_x=b_x.topk(20,2)[1]

```
Maybe the traceback is not well traced in the topk function ...
Maybe some variables were not freed...

**Comment by soumith** [comment]
This is not related to topk itself, but because the operation is pretty intense / taking too long on your GPU.
The NVIDIA driver realizes that the operation is taking too long, and **because an active display is also attached to this GPU**, it kicks out the CUDA kernel.

This thread gives more context: https://devtalk.nvidia.com/default/topic/483643/cuda-the-launch-timed-out-and-was-terminated/

There's not a whole lot we can do from the pytorch end.

What GPU do you have? Is it an option to not turn on the display on the GPU (maybe use this GPU purely over SSH). Is it an option to run your code on a second gpu (if you have two GPUs)

**Comment by soumith** [comment]
since we cant take any action from the pytorch side, i'm closing the issue, but i'd love to know more and see if we can find a solution for you.

**Comment by soumith** [comment]
I couldn't find an immediate way to increase the timeouts on Linux via stalking the devtalk forums. @ngimel do you know if there's a linux way to increase timeouts?

**Comment by ngimel** [comment]
No, your diagnosis and proposed solutions are correct, for cards that are also display cards watchdog will enforce the timeout.

**Comment by ngimel** [comment]
On the pytorch side, if we find a way to use @wickedfoo's topk, may be timeouts won't be triggered. Last time I checked, for small k THC implementation is pretty slow.

**Comment by jmlago** [comment]
I was trying to execute that in a gtx 660 and it does not work. Now in a gtx 1060 and it works. 
If you can tell me where is the cuda kernel that performs the topk operation, maybe I can modify it locally to make it work faster.
Thanks for your attention.

**Comment by wickedfoo** [comment]
This one is pretty slow too since the dimension for the top-k is not innermost, so all the reads are strided / non-coalesced (and it has to do N of them). I don't have an implementation that works well where the dimension is not innermost. If you could transpose your data such that the dimension along which you are gathering is innermost, this example would work faster. Or, as a fix (assuming that the temporary memory allocator is good enough), one could allocate temporary memory for the transposition, transpose it, operate on the transposed form, then produce results back out in cases where the top-k dimension is not innermost.

The version I have in Faiss is fastest for k <= 1024 (for k <= 128, it does it in a single pass at up to 70-80% peak mem b/w):
https://github.com/facebookresearch/faiss/blob/master/gpu/utils/Select.cuh

I checked in a version for small top-k that is less fast in Caffe2, but still single-pass:
https://github.com/caffe2/caffe2/blob/master/caffe2/operators/top_k_heap_selection.cuh
