### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by isalirezag** [pytorch/pytorch#27588]
I am using pytorch 1.2.0 via CUDA 10 on ubuntu 16.04 and titan XP GPU.

When my batch size is 20 i get the mentioned error:
```

  File "/home/alireza/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)

  File "/home/alireza/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag

RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
```
interestingly, if I use:
```torch.backends.cudnn.enabled = False```

the error will disappears and the code run okay, BUT it will be 4 times slower...

also if i dont have 
```torch.backends.cudnn.enabled = False```
in my code i notice that if i reduce the batch size to 10 the code will run.

Can you please help what is going on?

**Comment by zou3519** [comment]
Do you have a minimal example that repros this?

**Comment by isalirezag** [comment]
it is not `minimal` but I simplify my files to these, so you can generate the error:
runcode:
```


import os

import time
import torch

import numpy as np
import torch.nn as nn

import torch.optim as optim



NumberOfEpochs = 50
BatchSize = 20


TotalEpoch = list(range(0,NumberOfEpochs))
Change = 20

os.environ["CUDA_VISIBLE_DEVICES"] = "0"

print("PyTorch Version {}" .format(torch.__version__))
print("Cuda Version {}" .format(torch.version.cuda))
print("CUDNN Version {}" .format(torch.backends.cudnn.version()))



# Initialization for training
Tensors_Input = torch.FloatTensor(1)
Lables_GT = torch.tensor(1, dtype=torch.long)


### ship to cuda ###
if torch.cuda.is_available():
	Tensors_Input = Tensors_Input.cuda()
	Lables_GT = Lables_GT.cuda()
	
# model
from C3D_Modified import C3D
Model = C3D(num_classes=101, pretrained=False)    

        
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(Model.parameters(), lr= 0.001, momentum=0.9, weight_decay=5e-4)
	
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

if  torch.cuda.device_count()>1 :
	Model.cuda()
	criterion.cuda()
	
	Model = torch.nn.DataParallel(Model)
	
if torch.cuda.device_count() == 1:
	Model.cuda()
	criterion.cuda()
	
    

# =============================================================================
# Training 
# =============================================================================


for epoch in TotalEpoch:
	
	Model.train()
	
    
	# Training Iteration
	for IterationNum in range(0, 100):
		start_time = time.time()

        # getting the data
		Tensors, Labels  = torch.rand(BatchSize,3,16,112,112), [1.]*BatchSize


		# zero the parameter gradients
		optimizer.zero_grad()
		Model.zero_grad()
        
		Tensors = Tensors.to(device, torch.float32)
        
		Tensors.requires_grad = True
		
		
		VideoActivityLable = [float(k) for k in Labels]
		VideoActivityLable = torch.from_numpy(np.stack(VideoActivityLable)).float()
		Lables_GT.resize_(VideoActivityLable.size()).copy_(VideoActivityLable)
	  
		
		Lables_GT.requires_grad_(False)
		
        
        
		ClassPrediction = Model(Tensors)
		
		# loss
		loss = criterion(ClassPrediction, Lables_GT)
        
        
		loss.backward()
		optimizer.step()

		print ("\r{}/{} epoch {}/{} Training... {}... time {:.4f}".format(epoch, NumberOfEpochs, IterationNum, 100, loss.data.item(),(time.time() - start_time)), end="")

```

and 
C3D_Modified:

```

import torch
import torch.nn as nn


class C3D(nn.Module):
    """
    The C3D network.
    """

    def __init__(self, num_classes, pretrained=False):
        super(C3D, self).__init__()

        self.conv1 = nn.Conv3d(3, 64, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.pool1 = nn.MaxPool3d(kernel_size=(1, 2, 2), stride=(1, 2, 2))

        self.conv2 = nn.Conv3d(64, 128, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.pool2 = nn.MaxPool3d(kernel_size=(2, 2, 2), stride=(2, 2, 2))

        self.conv3a = nn.Conv3d(128, 256, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.conv3b = nn.Conv3d(256, 256, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.pool3 = nn.MaxPool3d(kernel_size=(2, 2, 2), stride=(2, 2, 2))

        self.conv4a = nn.Conv3d(256, 512, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.conv4b = nn.Conv3d(512, 512, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.pool4 = nn.MaxPool3d(kernel_size=(2, 2, 2), stride=(2, 2, 2))

        self.conv5a = nn.Conv3d(512, 512, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.conv5b = nn.Conv3d(512, 512, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.pool5 = nn.MaxPool3d(kernel_size=(2, 2, 2), stride=(2, 2, 2), padding=(0, 1, 1))

        self.fc6 = nn.Linear(8192, 4096)
        self.fc7 = nn.Linear(4096, 4096)
        self.fc8 = nn.Linear(4096, num_classes)

        self.dropout = nn.Dropout(p=0.5)

        self.relu = nn.ReLU()

        self.__init_weight()

        if pretrained:
            self.__load_pretrained_weights()

    def forward(self, x):

        x = self.relu(self.conv1(x))
        x = self.pool1(x)

        x = self.relu(self.conv2(x))
        x = self.pool2(x)

        x = self.relu(self.conv3a(x))
        x = self.relu(self.conv3b(x))
        x = self.pool3(x)

        x = self.relu(self.conv4a(x))
        x = self.relu(self.conv4b(x))
        x = self.pool4(x)

        x = self.relu(self.conv5a(x))
        x = self.relu(self.conv5b(x))
        x = self.pool5(x)

        x = x.view(-1, 8192)
        x = self.relu(self.fc6(x))
        x = self.dropout(x)
        x = self.relu(self.fc7(x))
        x = self.dropout(x)

        logits = self.fc8(x)

        return logits

    def __load_pretrained_weights(self):
        """Initialiaze network."""
        corresp_name = {
                        # Conv1
                        "features.0.weight": "conv1.weight",
                        "features.0.bias": "conv1.bias",
                        # Conv2
                        "features.3.weight": "conv2.weight",
                        "features.3.bias": "conv2.bias",
                        # Conv3a
                        "features.6.weight": "conv3a.weight",
                        "features.6.bias": "conv3a.bias",
                        # Conv3b
                        "features.8.weight": "conv3b.weight",
                        "features.8.bias": "conv3b.bias",
                        # Conv4a
                        "features.11.weight": "conv4a.weight",
                        "features.11.bias": "conv4a.bias",
                        # Conv4b
                        "features.13.weight": "conv4b.weight",
                        "features.13.bias": "conv4b.bias",
                        # Conv5a
                        "features.16.weight": "conv5a.weight",
                        "features.16.bias": "conv5a.bias",
                         # Conv5b
                        "features.18.weight": "conv5b.weight",
                        "features.18.bias": "conv5b.bias",
                        # fc6
                        "classifier.0.weight": "fc6.weight",
                        "classifier.0.bias": "fc6.bias",
                        # fc7
                        "classifier.3.weight": "fc7.weight",
                        "classifier.3.bias": "fc7.bias",
                        }

        p_dict = torch.load('pretrained_model/c3d-pretrained.pth')
        s_dict = self.state_dict()
        for name in p_dict:
            if name not in corresp_name:
                continue
            s_dict[corresp_name[name]] = p_dict[name]
        self.load_state_dict(s_dict)

    def __init_weight(self):
        for m in self.modules():
            if isinstance(m, nn.Conv3d):
                # n = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
                # m.weight.data.normal_(0, math.sqrt(2. / n))
                torch.nn.init.kaiming_normal_(m.weight)
            elif isinstance(m, nn.BatchNorm3d):
                m.weight.data.fill_(1)
                m.bias.data.zero_()



if __name__ == "__main__":
    inputs = torch.rand(1, 3, 16, 112, 112)
    net = C3D(num_classes=101, pretrained=True)

    outputs = net.forward(inputs)
    print(outputs.size())
```

**Comment by ruiyan1995** [comment]
@isalirezag Hi, how did you solve this issue?

**Comment by isalirezag** [comment]
@ruiyan1995 nope :/

**Comment by gchanan** [comment]
have you tried with a later version of PyTorch?

**Comment by isalirezag** [comment]
my pytorch was the newest version at that time (v1.3). 
i have not had the chance to reinstall it from source since then.

**Comment by wenqihuang** [comment]
I have the same problem, and I tried to run code with `autograd.detect_anomaly()`, I find the problem happens in a Conv3d layer. 
Reducing the batch_size will be a temperial solution as @isalirezag said. The problem disappeared when I reduce my batch size to 12.
I think it is a cudnn bug.

**Comment by liaohaofu** [comment]
Does anyone have a solution to this issue? I had exactly the same problem and the only way to temporarily solve this issue is to reduce the batch size. This is also caused by the Conv3d layer.

**Comment by fraserprice** [comment]
Bump. Any solutions?

**Comment by zou3519** [comment]
@fraserprice the workaround is setting `torch.backends.cudnn.enabled = False`. From the thread above it looks like we're having trouble reproducing a bug. If you could send some information about what cudnn / cuda version you have installed, which version of pytorch you're using, and a minimal repro we can help look at the problem

**Comment by hktxt** [comment]
solved, thx

**Comment by kpprasa** [comment]
I too have this bug. My code is rather complex, but I checked it without GPU and it does run. 
<img width="680" alt="Screen Shot 2020-04-19 at 9 29 01 PM" src="https://user-images.githubusercontent.com/36089289/79705754-d2135e00-8284-11ea-902d-a7ff2ca67d36.png">
 
I was able to temporarily get rid of this error by reducing the batch size from 32 to 16

**Comment by Cassieyy** [comment]
I have the same issue, so... the only method now is to reduce the batch size, right?

**Comment by loveisacat** [comment]
I have that error. Reducing the batch size is not work.  The cause of my error is my GPU is GeForce RTX 3090. The version of PyTorch and cudatoolkit should be updated to use the capacities  of RTX 3090.
Finally, I use PyTorch 1.6 and cudatoolkit 11.0 to solve it.

**Comment by ZinoTAT** [comment]
> I have that error. Reducing the batch size is not work. The cause of my error is my GPU is GeForce RTX 3090. The version of PyTorch and cudatoolkit should be updated to use the capacities of RTX 3090.
> Finally, I use PyTorch 1.6 and cudatoolkit 11.0 to solve it.

I have that error with 4 RTX 3090, cuda11.0 and PyTorch 1.7

**Comment by sunjc0306** [comment]
I meet the same problem using Conv3d layers for my network. Reducing the batch size is  work, but it does not take full usage of the GPU's memory. I would like to know if there is any other way to do both?

**Comment by dketterer** [comment]
I have this issue with Cudnn 8.1.1, CUDA 11.2, Pytorch 1.8.1 on a RTX 3090. I compiled PyTorch myself.
It happens during a forward pass and I do not use Conv3d.
GPU memory is not even close to be filled.

**Comment by AndreiRoibu** [comment]
Hi all - I started experiencing this issue recently on a new set of A100 GPUs. I am using the following configuration:

NVIDIA A100 GPU
torch == 1.4.0
Python == 3.7.4-GCCcore-8.3.0
CUDA == 10.1.243-GCC-8.3.0
cudnn == 7.6.5.32-10.1

I have used the same configuration on other GPUs, such as K80, P100, V100 and RTX8000, and never had the error. Anybody found a solution to this issue?

**Comment by AndreiRoibu** [comment]
> Hi all - I started experiencing this issue recently on a new set of A100 GPUs. I am using the following configuration:
> 
> NVIDIA A100 GPU
> torch == 1.4.0
> Python == 3.7.4-GCCcore-8.3.0
> CUDA == 10.1.243-GCC-8.3.0
> cudnn == 7.6.5.32-10.1
> 
> I have used the same configuration on other GPUs, such as K80, P100, V100 and RTX8000, and never had the error. Anybody found a solution to this issue?

I think I actually fixed my own issue. I posted the answer here- https://discuss.pytorch.org/t/nvidia-a100-gpu-runtimeerror-cudnn-error-cudnn-status-mapping-error/121648

**Comment by wangxueping78** [comment]
I adjust batch_size to 1, but still get this error!!!!what should I do?

**Comment by CAuYi15** [comment]
> 我将batch_size调整为1，但仍然出现此错误！！！！我该怎么办？

Do you fix it? I have met the same problem while I set the batch_size ==1 recently.

**Comment by Cassieyy** [comment]
您的邮件已收到哦我会及时处理哒~

**Comment by wangxueping78** [comment]
> RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

 It's been so long, I forgot. You can try adding the following code: torch.backends.cudnn.enabled = False

**Comment by lubin2022** [comment]
> > RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
> 
> It's been so long, I forgot. You can try adding the following code: torch.backends.cudnn.enabled = False

could you please tell me that where should I add the code'torch.backends.cudnn.enabled = False'?

**Comment by lubin2022** [comment]
> I have the same issue, so... the two methods now are to reduce the batch size or setting `torch.backends.cudnn.enabled =False,` right?

Could you please tell me wherer should I add the code 'torch.backends.cudnn.enabled = False' ?

**Comment by Mattwmaster58** [comment]
In case this helps anyone else, I experienced this issue and it was nondeterministic, but it seemed to be related to system cuda libs and pytorch expected cuda version. In my case, I had CUDA 11.8 installed, with a pytorch version expecting 11.6. I upgraded pytorch to a version that "expected" 11.7 and all seems to be well.

**Comment by david-waterworth** [comment]
@Mattwmaster58 I've been experiencing something very similar. What I did notice is that I have multiple versions of cuda (11.3, 11.7, 11.8 and 12.0) with update-alternatives set to 11.7

But I only have a single version of cudnn - 8.8.0.121-1+cuda12.0 

I removed all cuda packages other than 11.7 (as that's the version of torch I'm using and I downgraded cudnn to 8.5.0.96-1+cuda11.7

So far things seem stable.

**Comment by Cassieyy** [comment]
您的邮件已收到哦我会及时处理哒~
