### ISSUE TITLE
torch.device reporting an error as it should when using msnpu

### ISSUE THREAD

**Issue by jeffswt** [pytorch/pytorch#27875]
## 🐛 Bug

When specifying MSNPU for `torch.device` it throws a RuntimeError inside the C library instead of catching it and raising it as a Python error.

## To Reproduce

1. Create a `msnpu` device with `device = torch.device('msnpu')
2. Boom

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-32-b5acb62a1678> in <module>
      3     a = torch.zeros(1, device=device)
      4     print(a)
----> 5 get_device()

<ipython-input-32-b5acb62a1678> in get_device()
      1 def get_device():
      2     device = torch.device('msnpu')
----> 3     a = torch.zeros(1, device=device)
      4     print(a)
      5 get_device()

RuntimeError: p INTERNAL ASSERT FAILED at C:\w\1\s\windows\pytorch\c10/core/impl/DeviceGuardImplInterface.h:213, please report a bug to PyTorch. DeviceGuardImpl for msnpu is not available
```

## Expected behavior

It ought have thrown something like this:

```
RuntimeError: CUDA error: invalid device ordinal
```

## Environment

```
Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Microsoft Windows 10 Pro
GCC version: (tdm64-1) 4.9.2
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 950M
Nvidia driver version: 431.60
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.5
[pip3] torch==1.3.0
[conda] Could not collect
```

## Additional context

N/A

cc @ezyang @gchanan @zou3519

**Comment by zou3519** [comment]
We should definitely change the error message. This is easy to do so I am marking it as high pri

**Comment by jeffswt** [comment]
Oh, and by the way other devices are throwing similar errors as well (Facepalm)

**Comment by gchanan** [comment]
High priority if this turns out to be a 1-liner or so, otherwise this probably doesn't come up very often, so maybe not worth high priority.
