### ISSUE TITLE
magma functionality isn't working on K80 GPU with official binaries

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#29096]
## 🐛 Bug

The bug started with me investigating that WaveGlow models, and torch.inverse are not working on K80 GPUs in Colab: https://github.com/pytorch/hub/issues/62

The summary of the bug is that one sees `RuntimeError: CUDA error: invalid device function` when running any CUDA linear algebra functions on a K80 GPU, which end up hitting magma.

Here's a minimal repro:

```python
import torch
x = torch.randn(10, 10, device='cuda')
y = x.inverse()
print(y)
```
The print is needed to trigger the error message, because of https://github.com/pytorch/pytorch/pull/29003

### How is magma built and linked into PyTorch binaries?

We build magma statically using the process described [here](https://github.com/pytorch/builder/tree/master/conda#building-magma-cuda91) and the build files [here](https://github.com/pytorch/builder/tree/master/conda/magma-cuda101-2.5.1), which is roughly that we build it with CUDA sass 3.5, 5.0, 6.0, 7.0 and no PTX at all.

We build the entire PyTorch stack with devtoolset7 starting pytorch 1.2.0, which upgraded Magma from 2.5.0 to 2.5.1 and upgraded the tool stack from devtoolset3 to devtoolset7. 
When transitioning Magma from 2.5.0 to 2.5.1, we started noticing super weird and unreasonable binary size increase. The context of it is here: https://github.com/pytorch/builder/issues/346 , aptly titled: "magma + devtoolset7 bumps binary sizes by unreasonable amounts".
So, for unknown reasons detailed in that issue, we build our magma binaries with devtoolset3, though we build PyTorch with devtoolset7.

### Theories about the bug

I had three theories I needed to investigate:

1. somehow magma 2.5.1 is a special snowflake and wants sm37 sass for K80 instead of sm35 sass, even though they are binary-compatible.
2. pytorch+devtoolset7 linking to the magma+devtoolset3 is dropping a bunch of magma sass into the final binary because of some unknown linker issues
3. adding PTX into the magma binaries is a sureshot way of fixing the problem even if (1) and (2) are not the relevant theories.

### Invalidating (1): building magma with sm37 sass

With commits https://github.com/pytorch/builder/commit/2aac90bd723dfbb3dc7728152bf0e6877ec4da16 and https://github.com/pytorch/builder/commit/43c06e172dfc214ac0a71449c1e49ddcdda7ef22 I moved magma from 3.5 to 3.7.

I rebuilt magma binaries, uploaded them, refreshed the binary dockers.
I waited for the nightly to be built.
I checked with cuobjdump that the nightlies do really have 3.7 sass for magma kernels.

But even with these cool new binaries, the error persisted. So, this was clearly not it.

### Invalidating (2) and (3): building a matrix of binaries that have {3.7+PTX, devtoolset7} cross-product

So, I did that last night, with https://github.com/pytorch/builder/commit/d5e3f7f9b6010313b9acd3c335fd2ba392a574a3 with the following matrix:

|CUDA build | With 3.7 PTX | magma's devtoolset |
|------------|--------------|-----------------|
|  10.1            |    Yes              |          7                |
|  10.0            |    No              |          7                |
|  10.0            |    Yes              |          3                |

It turns out, my cleverness didn't work out. None of the three binaries worked, and produce the same error.

Now I'm out of ideas, so I wanted to open a detailed issue to open up the discussion.

**Comment by soumith** [comment]
cc: @ngimel @csarofeen @ptrblck for any ideas

**Comment by soumith** [comment]
cc: @vishwakftw fyi

**Comment by vishwakftw** [comment]
Does `torch.solve(torch.eye(10), torch.randn(10, 10, requires_grad=True))` work?

If it does, this could be a hotpatch for the upstream pytorch/hub issue.

**Comment by soumith** [comment]
the torch.solve thing does work!

**Comment by vishwakftw** [comment]
This probably means that there is some issue with MAGMA's `getri`.

**Comment by ngimel** [comment]
It's an issue with magma helper functions that `getri` uses - magmablas_slacpy, magmablas_slaset, magmablas_strtri_diag etc.

**Comment by soumith** [comment]
as an update, Natalia came up with the following repro: https://gist.github.com/soumith/7db66e7f6c87bb4718856c03137685d3

We've also eliminated any of the cuda pruning business as the issue, because the issue is also with conda binaries.

Additionally, Natalia verified that the appropriate sass is actually in the binary.

I've additionally started bisecting things towards how we build magma.a via https://github.com/pytorch/builder/tree/master/conda/magma-cuda101-2.5.1

So far,
- I've built a fresh magma 2.5.1 on the K80 machine, and linked the repro to it. It passes the run.
- I've built magma 2.5.1 + the patches in https://github.com/pytorch/builder/tree/master/conda/magma-cuda101-2.5.1. It passes the run.

So, it has to do with some cross-env thing, i.e. building in the soumith/conda-cuda docker and running on the K80 machine.
I'll start bisecting further by removing the patch line by line, rebuilding in conda-cuda docker, and if things start working.

**Comment by soumith** [comment]
Finally resolved the issue today.

It turns out that the CMake for magma 2.5.1 added the line `set(CUDA_SEPARABLE_COMPILATION ON)`, and doing separable compilation somehow triggers some deep nvcc interaction with CentOS7 / RHEL7 linkers and all of that doesn't go down very well.

After setting `CUDA_SEPARABLE_COMPILATION` to `OFF`, we can successfully build static binaries that work correctly on a K80.

We **did not root cause this bug**, which needs significant more time and effort, because of it's subtle nature. We do not intend to root-cause it for now, as the cost-benefit isn't very high.

The commit that fixes the issue is https://github.com/pytorch/builder/commit/dd7edfdf40e7eb75f0d561512e31b31c8319d9c9

The nightlies from tomorrow morning will carry the fix.

The fix will also naturally be part of v1.3.1, after which we will request an update Google Colab, which will fix the originally flagged bug report.

**Comment by vishwakftw** [comment]
Thanks ever so much @soumith @ngimel for helping find the bug.
