### ISSUE TITLE
CUDA error (cublasSgemm / cuda runtime error (719) / etc)

### ISSUE THREAD

**Issue by JoonBumLeem** [pytorch/pytorch#29795]
## To Reproduce

I reproduce code for error. When I run this code on 1 console, its okay. But run over 2 and 3 console, then it show error message. Sometimes running only 1 console makes error message too.

    
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
    from torch.utils.data import DataLoader, Dataset
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    class Rnn(nn.Module):
    
        def __init__(self):
            super(Rnn, self).__init__()
            self.seq_len = 30
            self.rnn = nn.LSTM(29, 128, batch_first=True,
                              num_layers=1, dropout=0, bidirectional=False)
    
            self.fc = nn.Sequential(
                nn.ELU(),
                nn.Dropout(0.2),
    
                nn.Linear(128, 32),
                nn.ELU(),
                nn.BatchNorm1d(32),
                nn.Dropout(0.2),
    
                nn.Linear(32, 6),
            )
    
        def forward(self, x):
            x = x.view(x.size(0), 30, 29)
            h0 = torch.zeros(1, x.size(0), 128).to(device)
            c0 = torch.zeros(1, x.size(0), 128).to(device)
            rnn_out, _ = self.rnn(x, (h0, c0))
            rnn_out = rnn_out[:, -1, :]
            out = self.fc(rnn_out)
    
            return out
    
    
    class TestDataset(Dataset):
        def __init__(self, sample_x, sample_y):
            self.sample_x = sample_x
            self.sample_y = sample_y
    
        def __len__(self):
            return len(self.sample_x)
    
        def __getitem__(self, idx):
            return self.sample_x[idx], self.sample_y[idx]
    
    
    sample_x = torch.randn(1000, 30, 29).float().to(device)
    sample_y = torch.randint(low=0, high=4, size=(1000, 1)).long().to(device)
    test_dataset = TestDataset(sample_x, sample_y)
    dataloader = DataLoader(test_dataset, batch_size=64, shuffle=True)
    
    model = Rnn().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)
    criterion = nn.CrossEntropyLoss()
    
    for epoch in range(1000):
        for x_batch, y_batch in dataloader:
            # Forward pass
            model = model.train()
            output = model(x_batch)
            loss = criterion(output, y_batch.reshape(-1))
    
            # Backward and optimize
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
    
        print("Epoch: %d, Loss: %.3f" % (epoch+1, loss.item()))
    
        with torch.no_grad():
            model = model.eval()
            output = model(sample_x)
            acc = (output.argmax(axis=1) == sample_y.squeeze()).sum().item() / len(test_dataset)
    
            print("Epoch: %d, Accuracy: %.3f" % (epoch + 1, acc))

###### 1st error message

    Epoch: 8, Loss: 1.802
    Epoch: 8, Accuracy: 0.272
    Traceback (most recent call last):
    
      File "<ipython-input-1-5c9923c95969>", line 1, in <module>
        runfile('C:/Users/User/Desktop/test.py', wdir='C:/Users/User/Desktop')
    
      File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
        execfile(filename, namespace)
    
      File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
        exec(compile(f.read(), filename, 'exec'), namespace)
    
      File "C:/Users/User/Desktop/test.py", line 74, in <module>
        optimizer.step()
    
      File "C:\Users\User\Anaconda3\lib\site-packages\torch\optim\adam.py", line 107, in step
        p.data.addcdiv_(-step_size, exp_avg, denom)
    
    RuntimeError: CUDA error: unspecified launch failure

###### 2nd error message

    Epoch: 35, Loss: 1.621
    Epoch: 35, Accuracy: 0.458
    Traceback (most recent call last):
    
      File "<ipython-input-1-5c9923c95969>", line 1, in <module>
        runfile('C:/Users/User/Desktop/test.py', wdir='C:/Users/User/Desktop')
    
      File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
        execfile(filename, namespace)
    
      File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
        exec(compile(f.read(), filename, 'exec'), namespace)
    
      File "C:/Users/User/Desktop/test.py", line 68, in <module>
        output = model(x_batch)
    
      File "C:\Users\User\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
        result = self.forward(*input, **kwargs)
    
      File "C:/Users/User/Desktop/test.py", line 34, in forward
        h0 = torch.zeros(1, x.size(0), 128).to(device)
    
    RuntimeError: CUDA error: unspecified launch failure

###### 3rd error message

    Epoch: 236, Loss: 0.066
    Epoch: 236, Accuracy: 1.000
    Traceback (most recent call last):
    
      File "<ipython-input-1-5c9923c95969>", line 1, in <module>
        runfile('C:/Users/User/Desktop/test.py', wdir='C:/Users/User/Desktop')
    
      File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
        execfile(filename, namespace)
    
      File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
        exec(compile(f.read(), filename, 'exec'), namespace)
    
      File "C:/Users/User/Desktop/test.py", line 73, in <module>
        loss.backward()
    
      File "C:\Users\User\Anaconda3\lib\site-packages\torch\tensor.py", line 166, in backward
        torch.autograd.backward(self, gradient, retain_graph, create_graph)
    
      File "C:\Users\User\Anaconda3\lib\site-packages\torch\autograd\__init__.py", line 99, in backward
        allow_unreachable=True)  # allow_unreachable flag
    
    RuntimeError: cuda runtime error (719) : unspecified launch failure at C:/w/1/s/tmp_conda_3.7_104508/conda/conda-bld/pytorch_1572950778684/work/aten/src/ATen/native/cuda/SoftMax.cu:647

###### 4th error message

    RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): windows10
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): run above code directly
 - Python version: 3.7.5
 - CUDA/cuDNN version: py3.7_cuda101_cudnn7_0 (conda list - pytorch) / Cuda V10.1.243 / cuDNN 7.6.5
 - GPU models and configuration: 2060 super / 1-way
 - Any other relevant information: cpu - i7 9700 / ram - 16gb / power - 500w

## Additional context

cc @ngimel @peterjc123

**Comment by peterjc123** [comment]
First, please rewrite your code into the following style:
```python
import xxx
def main():
    do xxx

if __name__ == '__main__':
    main()
```
Second, for your problem, there are two major causes:
1. You are out of GPU memory.
2. You'll need to switch off the TDR settings.

**Comment by vincentqb** [comment]
As mentioned [here](https://github.com/pytorch/pytorch/issues/27837#issuecomment-541927318), to help diagnose, could you also run your code with anomaly mode enabled?

**Comment by JoonBumLeem** [comment]
Thank you for  answers @peterjc123 @vincentqb 
And sorry for the code style. I don't know how to change it with colors.

I tried all above but it's still error.
For GPU memory, it's usually running long time  and then suddenly make error message.
TDR settings also I did but not work.

t.autograd.set_detect_anomaly = True 
This option not work too.

self.rnn = nn.LSTM(29, 128, batch_first=True,
                          num_layers=1, dropout=0, bidirectional=False)
I think I found some clue. 
Here batch_first=True option make error and batch_first=False option no error.

**Comment by vincentqb** [comment]
Given the size of `sample_x` and `sample_y` ((1000, 30, 29) and (1000, 1)), I assume the dimensions of the first are `(seq_len, batch_size, features)`?

If that is so, then you should use `batch_first=False`. Please see [here](https://discuss.pytorch.org/t/could-someone-explain-batch-first-true-in-lstm/15402) for a discussion.

**Comment by SteveJunGao** [comment]
Are there any updates on this? I also encountered the problem 
```
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

**Comment by Jmennius** [comment]
CUDA Toolkit 11.1 release notes mention an issue fixed in cuBLAS:
> Fixed an issue that caused an Address out of bounds error when calling `cublasSgemm()`.

We had `cublasSgemm()` failing with `CUBLAS_STATUS_EXECUTION_FAILED` for us when built with 10.0 and running on Ampere GPU (3060 Ti). It ran fine on older GPUs (Pascal, Turing).
We had it run successfully on Ampere when we build it with CUDA 11.2.

P.S. This was with another framework/project.

**Comment by pauli31** [comment]
> Are there any updates on this? I also encountered the problem
> 
> ```
> RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
> ```

I have the same issue, Nvidia A100 Cuda 10.1,  torch==1.5.1+cu101
torchvision==0.6.1+cu101, with XLM-R and XLM models from transformer library... I cannot change the cuda version, since I'm using computational center where I can not install anything.

**Comment by Jmennius** [comment]
@pauli31 Regarding not being able to install CUDA toolkit without root.
Assuming you are on Linux and the NVIDIA kernel driver is recent enough (>=455 for 11.1 CUDA toolkit and >=460 for 11.2) - you can actually install CUDa toolkit somewhere into your user directory, like so: `sh cuda_11.2.0_460.27.04_linux.run --silent --toolkit --toolkitpath=~/cuda-11.2`.
Download [here](https://developer.nvidia.com/cuda-toolkit-archive) choose our OS and runfile. You can check your kernel driver version with `cat /proc/driver/nvidia/version`

When this is done - you tell the CUDA path to your framework etc and `export LD_LIBRARY_PATH=~/cuda-11.2/targets/x86_64-linux/lib/`.

**Comment by pauli31** [comment]
> @pauli31 Regarding not being able to install CUDA toolkit without root.
> Assuming you are on Linux and the NVIDIA kernel driver is recent enough (>=455 for 11.1 CUDA toolkit and >=460 for 11.2) - you can actually install CUDA toolkit somewhere into your user directory, like so: `sh cuda_11.2.0_460.27.04_linux.run --silent --toolkit --toolkitpath=~/cuda-11.2`.
> Download [here](https://developer.nvidia.com/cuda-toolkit-archive) choose your OS and `runfile`. You can check your kernel driver version with `cat /proc/driver/nvidia/version` to deduce the latest toolkit you can run with.
> 
> When this is done - you tell the CUDA path to your framework etc and `export LD_LIBRARY_PATH=~/cuda-11.2/targets/x86_64-linux/lib/`.

Thank you I'll try :)

**Comment by pedromingues** [comment]
> > @pauli31 Regarding not being able to install CUDA toolkit without root.
> > Assuming you are on Linux and the NVIDIA kernel driver is recent enough (>=455 for 11.1 CUDA toolkit and >=460 for 11.2) - you can actually install CUDA toolkit somewhere into your user directory, like so: `sh cuda_11.2.0_460.27.04_linux.run --silent --toolkit --toolkitpath=~/cuda-11.2`.
> > Download [here](https://developer.nvidia.com/cuda-toolkit-archive) choose your OS and `runfile`. You can check your kernel driver version with `cat /proc/driver/nvidia/version` to deduce the latest toolkit you can run with.
> > When this is done - you tell the CUDA path to your framework etc and `export LD_LIBRARY_PATH=~/cuda-11.2/targets/x86_64-linux/lib/`.
> 
> Thank you I'll try :)

I have the same problem, did it work for you?

**Comment by danielqingz** [comment]
> > > @pauli31 Regarding not being able to install CUDA toolkit without root.
> > > Assuming you are on Linux and the NVIDIA kernel driver is recent enough (>=455 for 11.1 CUDA toolkit and >=460 for 11.2) - you can actually install CUDA toolkit somewhere into your user directory, like so: `sh cuda_11.2.0_460.27.04_linux.run --silent --toolkit --toolkitpath=~/cuda-11.2`.
> > > Download [here](https://developer.nvidia.com/cuda-toolkit-archive) choose your OS and `runfile`. You can check your kernel driver version with `cat /proc/driver/nvidia/version` to deduce the latest toolkit you can run with.
> > > When this is done - you tell the CUDA path to your framework etc and `export LD_LIBRARY_PATH=~/cuda-11.2/targets/x86_64-linux/lib/`.
> > 
> > 
> > Thank you I'll try :)
> 
> I have the same problem, did it work for you?

I have the same problem, too, did it work for you?

**Comment by alik604** [comment]
note to other: when I got this it was because I didnt have the right torch. install as it says on the website, NOT `pip install torch`, you need the `cu` version/build

**Comment by pauli31** [comment]
> > > > @pauli31 Regarding not being able to install CUDA toolkit without root.
> > > > Assuming you are on Linux and the NVIDIA kernel driver is recent enough (>=455 for 11.1 CUDA toolkit and >=460 for 11.2) - you can actually install CUDA toolkit somewhere into your user directory, like so: `sh cuda_11.2.0_460.27.04_linux.run --silent --toolkit --toolkitpath=~/cuda-11.2`.
> > > > Download [here](https://developer.nvidia.com/cuda-toolkit-archive) choose your OS and `runfile`. You can check your kernel driver version with `cat /proc/driver/nvidia/version` to deduce the latest toolkit you can run with.
> > > > When this is done - you tell the CUDA path to your framework etc and `export LD_LIBRARY_PATH=~/cuda-11.2/targets/x86_64-linux/lib/`.
> > > 
> > > 
> > > Thank you I'll try :)
> > 
> > 
> > I have the same problem, did it work for you?
> 
> I have the same problem, too, did it work for you?

Finally I managed to run it, I tried many things, I tried even to install the cuda 11.2
`sh cuda_11.2.0_460.27.04_linux.run --silent --toolkit --toolkitpath=~/cuda-11.2` and then `export LD_LIBRARY_PATH=~/cuda-11.2/targets/x86_64-linux/lib/`, then I tried this:
`pip uninstall torch`
`pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html` 

from [https://github.com/pytorch/pytorch/issues/45021](https://github.com/pytorch/pytorch/issues/45021)

**Comment by SaoYear** [comment]
Think this bug may be raised by unused but defined modules. I defined two CNNs in my network. When I used both of them, everything worked well but if I muted one (did not mentioned it in `forward`), this error happened.

**Comment by eliphatfs** [comment]
I also have this error, and I have a smaller reproduction code. Changing the batch dimension from 2 to 16 or removing the first layer in the MLP and it will not reproduce. torch 1.8.1 with CUDA driver 11.2 and toolkit 11.1
```python
import torch
import tqdm


def net():
    return torch.nn.Sequential(
        torch.nn.Linear(1024, 1024),
        torch.nn.ReLU(),
        torch.nn.Linear(1024, 256)
    )


if __name__ == "__main__":
    pred = net().to('cuda:0')
    opt = torch.optim.Adam(pred.parameters())
    for i in tqdm.trange(100):
        opt.zero_grad()
        pred(torch.randn(2, 1024).to('cuda:0')).sum().backward()
        opt.step()
```

**Comment by dros1986** [comment]
> I also have this error, and I have a smaller reproduction code. Changing the batch dimension from 2 to 16 or removing the first layer in the MLP and it will not reproduce. torch 1.8.1 with CUDA driver 11.2 and toolkit 11.1
> 
> ```python
> import torch
> import tqdm
> 
> 
> def net():
>     return torch.nn.Sequential(
>         torch.nn.Linear(1024, 1024),
>         torch.nn.ReLU(),
>         torch.nn.Linear(1024, 256)
>     )
> 
> 
> if __name__ == "__main__":
>     pred = net().to('cuda:0')
>     opt = torch.optim.Adam(pred.parameters())
>     for i in tqdm.trange(100):
>         opt.zero_grad()
>         pred(torch.randn(2, 1024).to('cuda:0')).sum().backward()
>         opt.step()
> ```

Tried your code. Same behaviour on my computer.  I also have pytorch 1.8.1+cu111. I have CUDA 11.3 and NVIDIA driver 465.19.01.

**Comment by lilohuang** [comment]
> I have the same issue, Nvidia A100 Cuda 10.1, cudnn-7.6.4, torch==1.5.1+cu101

Hi @pauli31 ,

I couldn't find CUDA driver 10.1 for NVIDIA A100 GPU card from [NVIDIA web-site](https://www.nvidia.com.tw/Download/index.aspx?lang=en). 
![image](https://user-images.githubusercontent.com/8341304/171791382-4fb05f63-c4ab-4616-bad8-8df64f7b3279.png)

Could you share how to make CUDA 10.1 driver work with NVIDIA A100 GPU card. 

Thanks,
Lilo

**Comment by vladimir-aubrecht** [comment]
We couldn't reproduce with latest versions of CUDA, PyTorch, Python and based on the discussion it seems bug was fixed by CUDA 11. Closing this ticket, please create new one if issues persists on latest versions of stack.

**Comment by yiyualt** [comment]
One possible reason could be that PyTorch version does not coincide with your CUDA version.  In my case, when I have: CUDA 11.5 + PyTorch 1.14, I encountered the same errors.     Then I changed PyTorch to **"torch==1.11.0+cu113"**. It works fine. 

Hope it helps!
