### ISSUE TITLE
A problem of nn.ConvTranspose2d in PyTorch

### ISSUE THREAD

**Issue by XiaoqiangZhou** [pytorch/pytorch#30211]
I met a strange `cuDNN error: CUDNN_STATUS_INTERNAL_ERROR` when I run the `nn.ConvTranspose2d` function in gpu-cluster.
Codes like:(in the ipdb debug mode)
```python
my_func = nn.Sequential(nn.ConvTranspose2d(128, 64, kernel_size=(2, 2), stride=(2, 2))).cuda()
my_input = torch.randn(8, 128, 128, 80).cuda()
print(my_func(my_input).shape)
```
I'm not sure whether it is because `nn.ConvTranspose2d` cannot handle the strange spatial size (128, 80).  
After I change the spatial size to (64,64), no error.
I think there is no problem with pytorch environment, with `pytorch=1.0.1` and `cuda=9.0`.  

Solutions for `cuDNN error: CUDNN_STATUS_INTERNAL_ERROR` also didn't work, e.g., `rm -rf ~/.nv`  

**It seems the problem is most likely from inappropriate input spatial size. Is there any constrain about `nn.ConvTranspose2d`?**  

Besides, when I try to run the aforementioned codes in the command line after run `python`, also no error reported. When I use the same (128, 80) spatial size but `kernel_size=(3,3)`, no problem. 

Is there any suggestion? Thanks

**Comment by cpuhrsch** [comment]
Hello @XiaoqiangZhou - I tried reproducing this on my end using the latest nightly but wasn't able to.

PyTorch 1.0.1 is quite old (we have 1.3 now) - is there a reason you don't want to update?  I'm flagging this in any case, but you're using old software effectively.

**Comment by XiaoqiangZhou** [comment]
@cpuhrsch Thanks for your suggestion.   

In fact, it seems to be the problem of "out of memory" in GPU. When I tried to reduce the input image size, the problem disappeared.  

By the way, I came to the the above conclusion based on the observation of GPU util information. When the memory usage is large than the maximum capacity, my program got the `cuDNN error: CUDNN_STATUS_INTERNAL_ERROR` 

I have another question, in the model initialization stage, the GPU memory usage often change dramatically, and it may exceed the maximum capacity. Is there any solution to solve such problem?

Thanks

**Comment by cpuhrsch** [comment]
@XiaoqiangZhou - happy to hear you were to resolve this error!

If you have a separate question, please open another issue so we can help other users who have a similar issue.

I'm closing this now, but please fill encouraged to reopen the issue if it reoccurs or you don't consider this resolved.
