### ISSUE TITLE
Version 1.3 no longer supporting Tesla K40m?

### ISSUE THREAD

**Issue by JamesOwers** [pytorch/pytorch#30532]
## 🐛 Bug

I am using a Tesla K40m, installed pytorch 1.3 with conda, using CUDA 10.1

## To Reproduce

1. Have a box with a Tesla K40m
1. conda install pytorch cudatoolkit -c pytorch
1. ```
python -c 'import torch; print(torch.cuda.isavailable());'
>>> True
```
1. Run any job using the GPU
```
Traceback (most recent call last):
  File "./baselines/get_results.py", line 395, in <module>
    main(args)
  File "./baselines/get_results.py", line 325, in main
    log_info = eval_main(eval_args)
  File "/mnt/cdtds_cluster_home/s0816700/git/midi_degradation_toolkit/baselines/eval_task.py", line 165, in main
    log_info = trainer.test(0, evaluate=True)
  File "/mnt/cdtds_cluster_home/s0816700/git/midi_degradation_toolkit/mdtk/pytorch_trainers.py", line 110, in test
    evaluate=evaluate)
  File "/mnt/cdtds_cluster_home/s0816700/git/midi_degradation_toolkit/mdtk/pytorch_trainers.py", line 220, in iteration
    model_output = self.model.forward(input_data, input_lengths)
  File "/mnt/cdtds_cluster_home/s0816700/git/midi_degradation_toolkit/mdtk/pytorch_models.py", line 49, in forward
    self.hidden = self.init_hidden(batch_size, device=device)
  File "/mnt/cdtds_cluster_home/s0816700/git/midi_degradation_toolkit/mdtk/pytorch_models.py", line 40, in init_hidden
    return (torch.randn(1, batch_size, self.hidden_dim, device=device),
RuntimeError: CUDA error: no kernel image is available for execution on the device
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

First tried downgrading to cudatoolkit=10.0, that exhibited same issue.

The code will run fine if you repeat steps above but instead `conda install pytorch=1.2 cudatoolkit=10.0 -c pytorch.


## Expected behavior
If no longer supporting a specific GPU, please bomb out upon load with useful error message.


## Environment

Unfort ran your script after I 'fixed' so pytorch version will be 1.2 here - issue encountered with version 1.3.

```
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Scientific Linux release 7.6 (Nitrogen)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla K40m
Nvidia driver version: 430.50
cuDNN version: /usr/lib64/libcudnn.so.6.5.18

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] numpydoc==0.8.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchvision               0.4.0                py37_cu100    pytorch
```

**Comment by albanD** [comment]
Just to be sure, were you using `1.3.0` or `1.3.1`?

**Comment by JamesOwers** [comment]
```
conda list 'pytorch|cuda'
# packages in environment at /home/s0816700/miniconda3/envs/mdtk:
#
# Name                    Version                   Build  Channel
cudatoolkit               10.1.243             h6bb024c_0  
pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
```
Was the env at point of failure.

**Comment by albanD** [comment]
cc @ngimel

**Comment by SsnL** [comment]
K40m has a compute capability of 3.5, which I believe we have dropped support of.

**Comment by JamesOwers** [comment]
Ok. Please may you implement a useful "oldgpu" warning? Like here: https://github.com/pytorch/pytorch/issues/6529

Error at the moment very unclear to casual user like me.

**Comment by ptrblck** [comment]
@JamesOwers If I'm not mistaken, [this commit](https://github.com/pytorch/builder/commit/2aac90bd723dfbb3dc7728152bf0e6877ec4da16#diff-65bdb50b3eee4c380f3b65973141e454) bumped the minimal compute capability to 3.7.

**Comment by xsacha** [comment]
There's no technical reason for it to be changed to 3.7 right?
The code still supports 3.5 (and even 3.0 again).

**Comment by ptrblck** [comment]
@soumith might correct me, but I think the main reason is the growing size of the binaries.

**Comment by xsacha** [comment]
@ptrblck that is the reason but it is strange it went from supporting K40 (+ several consumer cards) and not K80 to supporting K80 and not K40 (+ several consumer cards).

> on an NVIDIA GPU with compute capability >= 3.0. 
I also wish there was a way for the message to reflect the minimum cuda arch from the cuda arch list for when it was compiled. This would make it easier when it gets changed to 3.7, for example. Or when a user supports 3.0 by compiling it themselves.

**Comment by ezyang** [comment]
This is also being discussed at https://github.com/pytorch/pytorch/issues/24205#issuecomment-560185215

**Comment by jeherr** [comment]
I'd just like to suggest that the compatible compute capabilities for the precompiled binaries be added somewhere to the documentation, especially when providing installation instructions for the binaries. That information does not appear to be readily available anywhere.

**Comment by shiyongde** [comment]
k40m with cuda10.0 get the same error!!!
build from source get more Error!!!

**Comment by jayenashar** [comment]
hi guys, i have made a python 3.6 pytorch 1.3.1 linux_x86_64 wheel without restriction on compute capability, and it's working on my 3.5 GPU.  i would be more than happy to build wheels for different python and pytorch versions if someone can tell me a proper distribution channel (i.e. not [google drive](https://drive.google.com/drive/folders/0B-X0-FlSGfCYdTNldW02UGl4MXM)).

**Comment by anowlan123** [comment]
@jayenashar Are you able to provide instruction to build Pytorch version 1.3.1 for a specific GPU (NVIDIA Tesla K20 GPU) & Python 3.6.8? I've attempted to build a compatible version but am still having hardware compatibility issues: 
[W NNPACK.cpp:77] Could not initialize NNPACK! Reason: Unsupported hardware.

**Comment by jayenashar** [comment]
I don't see a reason to build for a specific GPU, but I believe you can export the environment variable `TORCH_CUDA_ARCH_LIST` for your specific compute capability (`3.5`), then use the [build-from-source instructions for pytorch](https://github.com/pytorch/pytorch#from-source).

The pytorch 1.3.1 wheel I made should work for you (python 3.6.8, NVIDIA Tesla K20 GPU).  I setup a pypi account to try and distribute it, but it seems there is a 60MB limit, and my wheel is 139MB.  So I have uploaded it here: https://github.com/UNSWComputing/pytorch/releases/download/v1.3.1/torch-1.3.1-cp36-cp36m-linux_x86_64.whl

**Comment by PeteKey** [comment]
Dear @anowlan123,

I would be very interested in a wheel of pytorch1.4 that work with Keppler K40 and cuda9.2. Would you be able to help out? I am thinking about installing that via miniconda.

**Comment by jayenashar** [comment]
@PeteKey you didn't specify a python version, but i made a wheel with python 3.6, pytorch 1.4.1, and magma-cuda92.  please try it here: https://github.com/UNSWComputing/pytorch/releases/download/v1.4.1/torch-1.4.1-cp36-cp36m-linux_x86_64.whl  if you have any issues, please upgrade to cuda10.2.

**Comment by PeteKey** [comment]
@anowlan123, python 3.6 is fine but I guess something is not quite working yet. Any idea how to fix this? I am running this on ubuntu 14.04 if that matters.

  File "/home/pk/miniconda3/envs/pytorch1.4py36_unsw_anowlan123/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory

**Comment by anowlan123** [comment]
@jayenashar Thanks, still having the same compatibility issues though.  @PeteKey  once i create an conda enviroment, i used this script to build from source. 

#!/bin/bash
#Make sure conda enviroment is activated
cd /home/user
conda activate env

conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi
conda install -c pytorch magma-cuda101

cd ~/anaconda3/envs/env/compiler_compat
mv ld ld-old

# Prep Pyorch Repo
cd /home/user/Downloads
git clone --recursive https://github.com/pytorch/pytorch
cd /home/user/Downloads/pytorch
git submodule sync
git submodule update --init --recursive

# Specify environment variables for specific pytorch build
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
export PYTORCH_BUILD_VERSION=1.3.1
export PYTORCH_BUILD_NUMBER=1
export TORCH_CUDA_ARCH_LIST=3.5




# Build and install
python setup.py install

# Clean the build
setup.py clean --all


cd ~/anaconda3/envs/env/compiler_compat
mv ld-old ld

**Comment by jayenashar** [comment]
> python 3.6 is fine but I guess something is not quite working yet. Any idea how to fix this? I am running this on ubuntu 14.04 if that matters.
> 
> File "/home/pk/miniconda3/envs/pytorch1.4py36_unsw_anowlan123/lib/python3.6/site-packages/torch/**init**.py", line 81, in
> from torch._C import *
> ImportError: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory

@PeteKey i think it's because you are using the wheel in conda.  try installing mkl in your conda env.

also, upgrade your ubuntu

**Comment by jayenashar** [comment]
@anowlan123 i don't see where you checkout v1.3.1 in the git repo.  also i'm not sure where your install installs to.  here is the script i used, it only makes the wheel, then i used pip to install it.

```
#!/bin/bash
CONDA_ENV=py369
PYTHON_VERSION=3.6.9
CUDA_VERSION=102
PYTORCH_BUILD_VERSION=1.3.1

set -e
set -u

conda create --yes --name $CONDA_ENV python=$PYTHON_VERSION
conda activate $CONDA_ENV
conda install --yes numpy ninja pyyaml mkl mkl-include setuptools cmake cffi
conda install --yes --channel pytorch magma-cuda$CUDA_VERSION

cd ~/pytorch
git checkout v$PYTORCH_BUILD_VERSION
git submodule sync
git submodule update --init --recursive
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
export PYTORCH_BUILD_VERSION
PYTORCH_BUILD_NUMBER=0 python setup.py bdist_wheel
```

**Comment by jayenashar** [comment]
@PeteKey i just uploaded files for conda (py3.5 and py3.6) to https://github.com/UNSWComputing/pytorch/releases/tag/v1.4.1 .  i think you can download the files and install them with `conda install $filename` but i'm not sure how to tell conda to install the dependencies.  maybe with `--only-deps`?  here are the dependencies of the py3.6 tarball if you need them:

```
    "blas * mkl", 
    "cudatoolkit >=9.2,<9.3", 
    "mkl >=2018", 
    "ninja", 
    "numpy >=1.11", 
    "python >=3.6,<3.7.0a0"
```

**Comment by PeteKey** [comment]
I just got it compiled once and it worked with K40 (so that's the proof of concept done), but then I did something and it did get messed up so I am starting from scratch.

What would be best steps to install torchvision for cuda 10.0 and cudatoolkit 10.0, and then compile the pytorch 1.4? I suppose the question is in which order I should do things in order not to end up with mess as miniconda install likes to 'resolve' lots of things and my feeling is that causes mess later on as it wants to download pytorch 1.4 from the channel etc.

**Comment by jayenashar** [comment]
maybe the best thing is to install the upstream pytorch 1.4.1 for cuda 10.0 and then install the package i can make for you.  this is how i am making the conda tarballs with [pytorch/builder](https://github.com/pytorch/builder):

```
export PYTORCH_REPO=pytorch
export PYTORCH_BRANCH=v1.4.1
export PYTORCH_BUILD_VERSION=1.4.1
export PYTORCH_BUILD_NUMBER=0
export TORCH_CONDA_BUILD_FOLDER=pytorch-nightly
export TORCH_PACKAGE_NAME=torch
export PIP_UPLOAD_FOLDER=""
export NIGHTLIES_ROOT_FOLDER="$HOME/local/builder/binaries_v1.4.1"
cd pytorch-builder/cron
./build_multiple.sh conda 3.6 cu92
```

**Comment by PeteKey** [comment]
@jayenashar, I am very close but one thing that is still weird is that even when I export CUDA_VERSION=100, the torch.version.cuda still shows cuda 10.2 ... which is a bit too new for some codes I am trying to run.

If you tell me how to force compilation to use and then have pytorch with cuda 10, this will solve my aches. Below I list my packages (I can see cuda100 and cudatulkit 10.0 there) so am confused.

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.1.1                      0  
certifi                   2020.4.5.1               py38_0  
cffi                      1.14.0           py38he30daa8_1  
cloudpickle               1.4.1                      py_0    conda-forge
cmake                     3.14.0               h52cb24c_0  
cuda100                   1.0                           0    pytorch
cudatoolkit               10.0.130                      0  
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py38h516909a_0    conda-forge
dask-core                 2.16.0                     py_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
expat                     2.2.6                he6710b0_0  
freetype                  2.9.1                h8a8886c_1  
icu                       58.2              hf484d3e_1000    conda-forge
imagecodecs-lite          2019.12.3        py38h1e0a361_0    conda-forge
imageio                   2.8.0                      py_0    conda-forge
intel-openmp              2020.1                      217  
joblib                    0.15.1                     py_0    conda-forge
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.2.0            py38hbf85e49_0    conda-forge
krb5                      1.17.1               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
libcurl                   7.69.1               h20c2e04_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.3                  he6710b0_1  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0                    15_mkl    conda-forge
libpng                    1.6.37               hbc83047_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
magma-cuda100             2.5.2                         1    pytorch
matplotlib-base           3.1.3            py38hef1b27d_0  
mkl                       2020.1                      217  
mkl-include               2020.1                      217  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.0.15           py38ha843d7b_0  
mkl_random                1.1.0            py38h962f231_0  
ncurses                   6.2                  he6710b0_1  
networkx                  2.4                        py_1    conda-forge
ninja                     1.9.0            py38hfd86e86_0  
numpy                     1.18.1           py38h4f9e942_0  
numpy-base                1.18.1           py38hde5b4d6_1  
olefile                   0.46                       py_0  
openssl                   1.1.1g               h7b6447c_0  
pillow                    7.1.2            py38hb39fc2d_0  
pip                       20.0.2                   py38_3  
pycparser                 2.20                       py_0  
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.8.2               hcff3b4d_14  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.4.0           py3.8_cuda10.0.130_cudnn7.6.3_0    pytorch
pywavelets                1.1.1            py38h8790de6_1    conda-forge
pyyaml                    5.3.1            py38h7b6447c_0  
readline                  8.0                  h7b6447c_0  
rhash                     1.3.8                h1ba5d50_0  
scikit-image              0.17.2           py38hcb8c335_0    conda-forge
scikit-learn              0.23.0           py38h3a94b23_0    conda-forge
scipy                     1.4.1            py38h18bccfc_3    conda-forge
setuptools                46.4.0                   py38_0  
six                       1.14.0                   py38_0  
sqlite                    3.31.1               h62c20be_1  
threadpoolctl             2.0.0              pyh5ca1d4c_0    conda-forge
tifffile                  2020.5.11                  py_0    conda-forge
tk                        8.6.8                hbc83047_0  
toolz                     0.10.0                     py_0    conda-forge
torch                     1.4.1                    pypi_0    pypi
torchvision               0.5.0                py38_cu100    pytorch
tornado                   6.0.4            py38h1e0a361_1    conda-forge
wheel                     0.34.2                   py38_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0

**Comment by jayenashar** [comment]
> @jayenashar, I am very close but one thing that is still weird is that even when I export CUDA_VERSION=100, the torch.version.cuda still shows cuda 10.2 ... which is a bit too new for some codes I am trying to run.

I'm not 100% sure the CUDA_VERSION in my script actually works.  It may only set the package version numbers and not set what version of CUDA it builds with.  if you run `nvcc --version` on the machine that you are using to build from source, that probably needs to be 10.0.

**Comment by PeteKey** [comment]
@jayenashar, @anowlan123, thanks for help. In the end I have compiled pytorch 1.5 for cuda10.2 and installed other packages via pip install, and finally the codes I wanted to run kicked off. So, my old K40 gets a bit more life.

**Comment by PeteKey** [comment]
@jayenashar, @anowlan123, last more question... bl...y pytorch somehow has got compiled without magma ... Do you know if I need to setup any flags for that. I had magma installed yet ...

**Comment by PeteKey** [comment]
@jayenashar, @anowlan123,  solved, export MAGMA_HOME=/home/pk/miniconda3/pkgs/magma-cuda102-2.5.2-1/

**Comment by breznak** [comment]
Guys, thank you for providing the solutions to get torch running with K40! 👍🏻

I seem to have built torch from source fine, but it fails to import extension `from torch.utils.cpp_extension import xxx` 

My env: 
K40, export *ARCH=3.5 
Torch v1.5.0, build finished ok and I can `import torch` 

Note, the source built torch==1.5.0 did not replace conda-installed pytorch==1.3.1, which I uninstalled along with its dependencies. 

Do I need to specify in the torch source build to use CUDA and cpp_extension ? 

Thank you

**Comment by jayenashar** [comment]
@breznak 

There's some differences between conda and pip such that the names are different (pytorch vs torch) hence the old version was not replaced.

`from torch.utils import cpp_extension` works for me with my 1.3.1 pip package, so i'm not sure what is the issue with yours.

**Comment by breznak** [comment]
> from torch.utils import cpp_extension works for me with my 1.3.1 pip package, so i'm not sure what is the issue with yours. 

works for me too, but I need torch >= 1.4, and I need to build from source (K40) ..these are the diffs.

**Comment by jayenashar** [comment]
do any of the files i uploaded to https://github.com/UNSWComputing/pytorch/releases/tag/v1.4.1 work for you?

**Comment by breznak** [comment]
> do any of the files i uploaded to https://github.com/UNSWComputing/pytorch/releases/tag/v1.4.1 work for you? 

thanks! I'll test but guessing from the names I don't think so, unfortunately. 
My constraints are:
``` 
K40
py>= 3.6
cuda >=10.1
torch>=1.4.1
```

**Comment by jayenashar** [comment]
I assume since you tried pytorch 1.5.0 first, that is your preferred one, so try this one: https://github.com/UNSWComputing/pytorch/releases/tag/v1.5.0  Also assumed the minimums py & cuda are what you already have installed, so built based on those assumptions.

**Comment by breznak** [comment]
@jayenashar thank you very much for supporting this! 
I've tried your repo, but `import torch` is failing for me after install with 
```
from torch._C import *
ImportError: /home/xxx/miniconda3/envs/detectron2-env/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack
```

**Comment by jayenashar** [comment]
Are you on Python 3.6.0?  I believe there's an issue with that and you need any other 3.6 (i.e., 3.6.1- 3.6.10

**Comment by jayenashar** [comment]
If you run python3.7, it shouldn't try to use this version of torch, so i would guess you have python 3.6.0

**Comment by breznak** [comment]
> Are you on Python 3.6.0? I believe there's an issue with that 

you're correct. (I had default python 3.7 installed in conda env, since I mistakenly told you I have 3.6, I installed python 3.6.0 available at conda-forge.) I'll see if there's later version of 3.6.x available at conda.

**Comment by wydwww** [comment]
Dear @jayenashar Can you please build PyTorch 1.5.0 for Python 3.7? Really appreciate your effort!
My settings are:
```
K40m
Python 3.7
CUDA 10.1
```

**Comment by jayenashar** [comment]
No problem.  For anyone making future requests, I would like the following info in your request:

- pytorch version - patch level (1.3.0 should work with most gpus.  1.3.1 dropped support for a lot of our gpus.)
- conda or pip
- cuda version - minor level (9.2, 10.1, 10.2 - note that 10.2 supports old gpus.  see https://developer.nvidia.com/cuda-gpus to find your GPU's compute capability and https://en.wikipedia.org/wiki/CUDA#GPUs_supported to find supported cuda versions)
- python version - minor level (note that python 3.6.0 does not work, but other 3.6.x should work)

I do not need the exact GPU or compute capability.  If your chosen version of pytorch supports it, it will be included.

I do not need the OS.  I am only building linux packages.

@wydwww check https://github.com/UNSWComputing/pytorch/releases/tag/v1.5.0 for the latest upload.  :)

**Comment by breznak** [comment]
Thank you @jayenashar , I really appreciate your work! Thanks to your prebuilt packages, I'm able to run pytorch (torchvision) on our cluster :+1: 

>  believe there's an issue with that and you need any other 3.6 (i.e., 3.6.1- 3.6.10) 

everything works fine with py 3.7. 

> so try this one: https://github.com/UNSWComputing/pytorch/releases/tag/v1.5.0  

for the reference for people installing from these binaries, you should use conda (not python, pip) to install these packages. 
`conda install pytorch-....tar.gz`

**Comment by KevinMusgrave** [comment]
@jayenashar Any luck building pytorch 1.6? I'm running into compilation errors at the moment, and am trying to debug it.

**Comment by jayenashar** [comment]
sadly my [remote] machine for building is down, and no ETA on when i can get to it to bring it back up, sorry.  haven't tried 1.6.

**Comment by KevinMusgrave** [comment]
So the "bug" was pretty silly. I forgot to clean the build folder before trying to build 1.6.0. After I cleaned it, the build was successful. 

Here's a whl file in case anyone needs it. It was built without tests or caffe2 operators: https://github.com/KevinMusgrave/pytorch/releases/tag/v1.6.0-compute-capability-3.5

**Comment by darolt** [comment]
@jayenashar Just commenting here to thank you. Managed to make 1.5 work in a K40 :)

**Comment by Vichoko** [comment]
@jayenashar could be possible for you to compile a version for a tesla k40c with NVCC 10.0?

    pytorch version - 1.6.0
    conda or pip - any
    cuda version - 10
    python version - 3.8.5 or other

**Comment by jayenashar** [comment]
@Vichoko https://github.com/UNSWComputing/pytorch/releases/tag/v1.6.0

you may have installed cuda-nvcc-9-2 and a precompiled driver.  probably easier to upgrade nvcc.

**Comment by sophiaas** [comment]
@jayenashar Can you comple a version for Tesla K40c with the following:

- PyTorch: latest possible
- Python: 3.7.7
- CUDA: 10.2
- conda

Many thanks!

**Comment by jayenashar** [comment]
sorry @sophiaas it looks like i can't do CUDA 10.2 so easily.  @KevinMusgrave has 10.1 at https://github.com/KevinMusgrave/pytorch/releases/tag/v1.6.0-compute-capability-3.5 in a wheel and i'm trying to build a conda version now.

**Comment by jayenashar** [comment]
@sophiaas i uploaded a 10.1 conda package to https://github.com/UNSWComputing/pytorch/releases/tag/v1.6.0

i'll keep trying to make a 10.2 but it keeps giving me a CPU-only build.

**Comment by sophiaas** [comment]
@jayenashar Thank you! Really appreciate it.

**Comment by nelson-liu** [comment]
If it helps, I put up some K40-compatible pip binaries at https://nelsonliu.me/files/pytorch/whl/torch_stable.html . Versions 1.3.1 to 1.6.0, hoping to keep them updated for new releases.

You can pip-install them with (change desired versions as necessary):

```
pip install torch==1.3.1+cu92 -f https://nelsonliu.me/files/pytorch/whl/torch_stable.html
```

I tested all of these binaries (except the CUDA 10.2 ones, hoping to get to those soon) by running the word-level language modeling example on a K40 and manually verifying that the perplexity was the same within versions and generally reasonable.

**Comment by jayenashar** [comment]
@nelson-liu that's great.  then i only need to worry about conda packages.

this is how i test for cuda: `python -c 'import torch; torch.randn([3,5]).cuda()'`

**Comment by Guptajakala** [comment]
@jayenashar 
That's so great to see your releases! 
I'm planning to subscribe to your future releases as well if you still plan to keep update with later pytorch releases. Would you plan to always release to that forked repo? Where should I request specific build, here or elsewhere?

**Comment by jayenashar** [comment]
@Guptajakala yes i will release to that forked repo, unless someone knows a better place.  i tried pypi but it seems they have a file size limit and that is the reason the official builds don't support old GPUs.  i can try an anaconda channel.

right now i'm taking requests here as it seems to be the discoverable place.

**Comment by Guptajakala** [comment]
@jayenashar 
Hi, does this work with python 3.6.9?
![image](https://user-images.githubusercontent.com/40518028/97660709-c29d7a80-1a48-11eb-858a-41ddd37e4f13.png)
I downloaded this one and run command
`conda install ./pytorch-1.6.0-py3.7_cuda10.1.243_cudnn7.6.3_0.tar.bz2`
It says
`No module named 'torch'`

**Comment by jayenashar** [comment]
no you can't use a py3.7 pytorch with python 3.6.

do you want me to build you one for python 3.6?

**Comment by Guptajakala** [comment]
@jayenashar 
that would be great, thank you!

**Comment by jayenashar** [comment]
@Guptajakala https://github.com/UNSWComputing/pytorch/releases/tag/v1.7.0

**Comment by Guptajakala** [comment]
@jayenashar aweseome!

**Comment by igor-krawczuk** [comment]
@nelson-liu  thank you very much for the wheels, the 1.6 wheel helped me a lot to get a project running just now

@jayenashar also thanks to you for being so incredible considerate! if you are still taking requests, could I ask you to please create a build for the following?

- pytorch: the latest possible (1.7,1.8,1.9?)
- k40c Driver Version: 435.21
- conda python 3.8
- cuda 10.1 according to nvidia-smi

**Comment by jayenashar** [comment]
@igor-krawczuk https://github.com/UNSWComputing/pytorch/releases/tag/v1.7.0

**Comment by AlbertoZandara** [comment]
@jayenashar I have a Nvidia 920m with cuda capabilities 3.5, can I use your prebuilt packages?

- pytorch: the latest possible (1.7,1.8,1.9?)
- 920m Driver Version: 419.67
- conda python 3.8.5
- cuda 10.1 according to nvidia-smi

**Comment by jayenashar** [comment]
hi @AlbertoZandara any CUDA GPU will work with my packages.  pytorch remove the old compute capabilities to save space and that's why my packages are much larger.

unfortunately i don't have windows, so i am only building linux packages: https://github.com/pytorch/pytorch/issues/30532#issuecomment-638836247

**Comment by sophiaas** [comment]
Hi @jayenashar, any chance I can get a 1.8.0 wheel for the following?

PyTorch: 1.8.0
Python: 3.8
CUDA: 10.2
conda

Thanks so much for your help!

**Comment by jayenashar** [comment]
hi @sophiaas unfortunately the way i used to build isn't working anymore.  i'll try and get them for you another way, hopefully in the next week, but no promises.

**Comment by sophiaas** [comment]
@jayenashar appreciate you!

**Comment by jayenashar** [comment]
@sophiaas i regret to inform you that i can't figure it out.  i can help you to build from source, maybe?

**Comment by geemk** [comment]
Hi @jayenashar, any chance I can get a wheel for the most advanced version of PyTorch (>= 1.5) for the following configurations

PyTorch: >= 1.5
Python: 3.6.13
CUDA: 9.2
conda

Thank you so much i'm becoming desperate to make this work

**Comment by jayenashar** [comment]
@geemk i built some but they aren't working.  you can try them if they magically work for you:
https://github.com/UNSWComputing/pytorch/releases/tag/v1.6.0
https://github.com/UNSWComputing/pytorch/releases/tag/v1.7.1
https://github.com/UNSWComputing/pytorch/releases/tag/v1.8.0

**Comment by beifengli** [comment]
@jayenashar Thank you very much for your availability, I have a Nvidia 820m which **compute capability is only 2.1**, can I get a possible  wheel for the following

* PyTorch: latest possible
* Python: >=3.6
* CUDA: 9.1 or 9.0
* conda

Thanks so much for your help!

**Comment by jayenashar** [comment]
@beifengli looks like CUDA 9.1 was never supported and 9.0 was last supported in pytorch 1.1.  Have you tried https://pytorch.org/get-started/previous-versions/#v110 ?

**Comment by beifengli** [comment]
I try to use pytorch 1.0 and 1.1, but it always show me the following information:
![image](https://user-images.githubusercontent.com/19248667/120055384-4a437a00-c068-11eb-87db-3f030e609028.png)

I found that pytorch from version 0.2 recommand GPU  compute capability >= 3.0. But my GPU is too old and it's compute capability is only 2.1. 

![image](https://user-images.githubusercontent.com/19248667/120055491-12890200-c069-11eb-8285-35b67e740370.png)

### my test code:
```
import torch
from torch import nn, tensor
from torch.cuda import device_count

x=torch.rand(5,3)
print(x)
print("available:",torch.cuda.is_available()," device_count:",
torch.cuda.device_count()," current_device:",
torch.cuda.current_device())

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
#x = torch.tensor([1, 2, 3]).to(device)
y = torch.tensor([1,4,9]).to(device)

print(x,y)
print(x+y)
```

**I really want to use my GPU, I hope you can help, thank you very much.**

**Comment by jayenashar** [comment]
sorry i don't think i can help you.  0.1.12 seems like your best chance

**Comment by beifengli** [comment]
thank you very much. I will try it right away

**Comment by weiaicunzai** [comment]
> Looks like your error message for this is buggy:
> 
> ```
> /home/USERNAME/.conda/envs/py38/lib/python3.8/site-packages/torch/cuda/__init__.py:120: UserWarning: 
>     Found GPU%d %s which is of cuda capability %d.%d.
>     PyTorch no longer supports this GPU because it is too old.
>     The minimum cuda capability supported by this library is %d.%d.
> ```
> 
> It would be helpful if you actually filled in the `%d` values here. Tested on a Tesla K40m on my University's HPC with Python 3.8.8 & PyTorch 1.10.2+cu102. I came through [this StackOverflow answer](https://stackoverflow.com/q/61104083) which has over 2K views.
> 
> I **strongly** suggest updating your main website page (https://pytorch.org/get-started/locally/) to clearly state the minimum CUDA capability index supported. You link to https://developer.nvidia.com/cuda-zone, which gives people the false impression that any CUDA-capable Nvidia GPU will work, which is **not the case**.

Agreed,  a CUDA capability matrix of Pytorch on the official website would be very helpful.
