### ISSUE TITLE
Windows v141 (14.16) compile regression

### ISSUE THREAD

**Issue by EscapeZero** [pytorch/pytorch#30886]
## 🐛 Bug

When trying to compile with VS2019 but targeting v141 toolchain and cuda 10.0 there seems to be some issues with rewrite of dispatching that was done in recent weeks.

This snippet was from building using facebook internal Buck, but I was able to reproduce same thing using cmake.

Compiling with /permissive- fixed the "no matching overload" error, but raises some other cuda errors related to `__nv_hdl_create_wrapper_t`

## To Reproduce

1. checkout pytorch master
1. pass v141 as toolchain to cmake when generating
1. set cuda sdk root to 10.0
1. try and build torch_cuda

Error without /permissive-
```
caffe2\aten\src\aten\core\boxing\KernelFunction_impl.h(67): error C2672: 'c10::impl::boxAndCallBoxedFunc': no matching overloaded function found
caffe2/aten/src\ATen/core/dispatch/Dispatcher.h(180): note: see reference to function template instantiation 'Return c10::KernelFunction::callUnboxed<Return,const at::Tensor&,const at::Tensor&,bool,bool>(const c10::OperatorHandle &,const at::Tensor &,const at::Tensor &,bool,bool) const' being compiled
        with
        [
            Return=void
        ]
caffe2/aten/src\ATen/core/dispatch/Dispatcher.h(155): note: see reference to function template instantiation 'Return c10::Dispatcher::callUnboxed<Return,const at::Tensor&,const at::Tensor&,bool,bool>(const c10::OperatorHandle &,const at::Tensor &,const at::Tensor &,bool,bool) const' being compiled
        with
        [
            Return=void
        ]
caffe2\ATen/core/TensorMethods.h(66): note: see reference to function template instantiation 'Return c10::OperatorHandle::callUnboxed<void,const at::Tensor&,const at::Tensor&,bool,bool>(const at::Tensor &,const at::Tensor &,bool,bool) const' being compiled
        with
        [
            Return=void
        ]
caffe2\aten\src\aten\core\boxing\KernelFunction_impl.h(67): error C2770: invalid explicit template argument(s) for 'Result c10::impl::boxAndCallBoxedFunc(c10::KernelFunction::InternalBoxedKernelFunction (__cdecl *),c10::OperatorKernel *,const c10::OperatorHandle &,Args...,enable_if<_Test,_Ty>::type)'
        with
        [
            _Ty=int
        ]
caffe2/aten/src\ATen/core/boxing/boxing.h(53): note: see declaration of 'c10::impl::boxAndCallBoxedFunc'
caffe2\aten\src\aten\core\boxing\KernelFunction_impl.h(67): error C2893: Failed to specialize function template 'Result c10::impl::boxAndCallBoxedFunc(c10::KernelFunction::InternalBoxedKernelFunction (__cdecl *),c10::OperatorKernel *,const c10::OperatorHandle &,Args...,enable_if<_Test,_Ty>::type)'
        with
        [
            _Ty=int
        ]
caffe2\aten\src\aten\core\boxing\KernelFunction_impl.h(67): note: With the following template arguments:
caffe2\aten\src\aten\core\boxing\KernelFunction_impl.h(67): note: 'Result=Return'
caffe2\aten\src\aten\core\boxing\KernelFunction_impl.h(67): note: 'Args={}'
```
Error with /permissive-
```
nvcc_internal_extended_lambda_implementation(542): error C3861: 'args': identifier not found
caffe2/aten/src/ATen/native/cuda/Copy.cu(62): note: see reference to class template instantiation '__nv_hdl_create_wrapper_t<false,true,__nv_dl_tag<void (__cdecl *)(at::TensorIterator &,bool),at::native::copy_device_to_device,1>>' being compiled
```

## Expected behavior

files compile

cc @ezyang @gchanan @zou3519 @yf225 @peterjc123

**Comment by peterjc123** [comment]
The first one seems to be a VS bug, because it cannot be reproduced either in VS 2019 and VS 2017 14.11. About the second one, I never tried that so I actually have no idea on this.

**Comment by EscapeZero** [comment]
@peterjc123 I was able to reproduce it with MSVC 14.16.27023, what exact 2017 version did you check? I agree it is fixed in 2019, but not sure about the ability to switch monorepo to 2019.

**Comment by peterjc123** [comment]
@EscapeZero We test with VS2017 Update 4 in nightly CI, which should be 14.11.25503.

**Comment by EscapeZero** [comment]
@peterjc123 I just did a fresh install of visual studio 2017 which is 14.16.27023 and the templates fail to compile. You don't think that is a valuable version to support?

**Comment by peterjc123** [comment]
We are aware of this issue but it is not a high priority because it doesn't block our builds, either CI builds or nightly builds. What's more, this issue doesn't have any easy workaround, maybe we'll have to revert all the related changes. cc @ezyang

**Comment by gchanan** [comment]
@peterjc123: could you talk a bit about a potential workaround?  Did you try something?

**Comment by ezyang** [comment]
cc @smessmer as the compilation failure is related to c10 code.

I'm bumping priority since this is an FB internal case that I think we do want to support. However, testing against v141 will be hard as CircleCI has very limited options for Windows build environments

**Comment by peterjc123** [comment]
> @peterjc123: could you talk a bit about a potential workaround? Did you try something?

As I said, I tried to update to VS 2019 and this issue disappeared. I also tried to make a minimal reproducible example from the code in `caffe2\aten\src\aten\core\boxing\KernelFunction_impl.h`, but failed. So actually I don't what the compiler is complaining about.

> However, testing against v141 will be hard as CircleCI has very limited options for Windows build environments

That's not a problem for CircleCI, which has v141 toolchain installed.

**Comment by EscapeZero** [comment]
@peterjc123 You are correct it does not appear on VS2019, but unfortunately internally we are locked to VS2017 (15.9), it looks like your CI is testing on VS2017(15.4). v141 toolset descriptor is a bit ambiguous as it is refers to multiple _MSC_VER (1910 through 1916 currently)

**Comment by aaost** [comment]
In case this is valuable, I am running into this issue building from source with VS2017 v15.9.18, Windows SDK 10.0.17763.0, build toolset v141 (v14.16). I attempted to install v15.4 toolset v14.11 but it doesn't show up in my IDE. I tried going back to Dec 2nd and still get the same errors.
I see the same problem when I build a project that links with the latest nightly binaries, but my build succeeds if I use the official 1.3.1 release. Using `/permissive-` with my project and linking with the latest nightly binary still doesn't work. Compiling latest (and even as far as Dec 2) torch source with `/permissive-` introduces a ton of other errors like `'std': ambiguous symbol`

**Comment by peterjc123** [comment]
Would you please try whether https://github.com/pytorch/pytorch/pull/31092 solves the problem?

**Comment by aaost** [comment]
Apologies ahead of time if I'm doing something wrong, as I'm, but here's what I tried

```
git fetch origin pull/31092/head:fix-31092
git checkout fix-31092

cmake -G"Visual Studio 15 2017 Win64" -DBUILD_PYTHON=False -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release;Debug -DCMAKE_INSTALL_PREFIX=C:\dev\opensource\pytorch\install-master -DCMAKE_PREFIX_PATH=C:\Qt\5.11.1-x64\lib\cmake -DPYTHON_EXECUTABLE=C:\Users\user\AppData\Local\Programs\Python\Python37-32\python.exe -DPYTHON_INCLUDE_DIR=C:\Users\user\AppData\Local\Programs\Python\Python37-32\include -DUSE_NUMPY=True C:\dev\opensource\pytorch -DUSE_CUDA=False ..
cmake --build . --config Release
```

What I get is many errors like

```
c:\dev\opensource\pytorch\aten\src\aten\core\boxing\kernelfunction_impl.h(66): error C2440: 'return': cannot conve
rt from 'void' to 'Return' [C:\dev\opensource\pytorch\build-master\caffe2\torch_cpu.vcxproj]

c:\dev\opensource\pytorch\aten\src\aten\core\boxing\kernelfunction_impl.h(66): error C2440: 'return': cannot convert
 from 'void' to 'std::tuple<at::Tensor,at::Tensor>' (compiling source file C:\dev\opensource\pytorch\aten\src\ATen\T
ensorNames.cpp) [C:\dev\opensource\pytorch\build-master\caffe2\torch_cpu.vcxproj]
```

I also tried toolset 14.11 via `-T "v141,version=14.11"` and it also fails

```
c:\dev\opensource\pytorch\aten\src\aten\core\boxing\boxing.h(72): error C3520: 'Args': parameter pack must be expand
ed in this context (compiling source file C:\dev\opensource\pytorch\aten\src\ATen\native\UpSampleNearest2d.cpp) [C:\
dev\opensource\pytorch\build-master\caffe2\torch_cpu.vcxproj]
```

I don't actually want to build libtorch from source. My problem is I'm getting a crash when simply including the torch/script.h header from the latest nightly binary libtorch build. #31455 is supposed to fix it, but that fix is from Dec 20th while the files in the latest 'nightly' binary build are actually dated Dec 17th. Strangely, the build server for the Windows version says the last [successful build](https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-trigger/) was Dec 6th.

**Comment by ezyang** [comment]
@EscapeZero Do you think you could also post the Buck commands, in case an FB employee wants to reproduce this from inside FB?

**Comment by ezyang** [comment]
@peterjc123 If we wanted to run this version of MSVC in CI, do you have an idea of how we'd go about doing it? I guess we can add another version of `.circleci/scripts/vs_install.ps1` with the appropriate version?

**Comment by EscapeZero** [comment]
@ezyang have not landed the new targets that fail. Will hopefully get to that early next week.

**Comment by smessmer** [comment]
I haven't tried to reproduce this, but there's a PR https://github.com/pytorch/pytorch/pull/31092 that rewrites part of this logic. It's possible that the compiler bug isn't triggered anymore after that.

**Comment by EscapeZero** [comment]
I will try to reproduce with the PR next chance I get.

**Comment by smessmer** [comment]
@EscapeZero I'm not sure what the state of the PR is, it might not work yet.

**Comment by peterjc123** [comment]
@smessmer The PR doesn't seem to work. See https://github.com/pytorch/pytorch/issues/30886#issuecomment-568595921.
@ezyang No need to install vs2017 because it is already installed in the circleci images. Just replace https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/win-test-helpers/build_pytorch.bat#L48 and https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/win-test-helpers/setup_pytorch_env.bat#L50 with `call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.16`.

**Comment by ezyang** [comment]
Nikita thinks that this is related to `C10_HOST_CONSTEXPR` and `C10_DEVICE_CONSTEXPR` and an inconsistency between the two

**Comment by EscapeZero** [comment]
Thanks for the work on this everyone!

**Comment by peterjc123** [comment]
@ezyang Could you please put up a fix for this? Or, could you please tell me what to do?

**Comment by ezyang** [comment]
@peterjc123 It looks like Nikita got busy and never put out the patch lol. If his hypothesis is right, maybe if we just turn off constexpr anywhere we don't actually need it, that might help.

**Comment by peterjc123** [comment]
I tried with https://github.com/pytorch/pytorch/pull/32688 and the result shows that the error is thrown during the compilation of the source files at the CPU side. So this hypothesis is likely not correct. The new error message is listed below.
```
C:\Users\circleci\project\build\win_tmp\bin\sccache.exe  cl   /TP -DAT_PARALLEL_OPENMP=1 -DCPUINFO_SUPPORTED_PLATFORM=1 -DIDEEP_USE_MKL -DMAGMA_V2 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE=1 -D_OPENMP_NOFORCE_MANIFEST -Dtorch_cpu_EXPORTS -Iaten\src -I..\aten\src -I. -I..\ -I..\cmake\..\third_party\benchmark\include -Icaffe2\contrib\aten -I..\third_party\onnx -Ithird_party\onnx -I..\third_party\foxi -Ithird_party\foxi -I..\caffe2\..\torch\csrc\api -I..\caffe2\..\torch\csrc\api\include -I..\caffe2\aten\src\TH -Icaffe2\aten\src\TH -I..\caffe2\..\torch\..\aten\src -Icaffe2\aten\src -Icaffe2\..\aten\src -Icaffe2\..\aten\src\ATen -I..\caffe2\..\torch\csrc -I..\caffe2\..\torch\..\third_party\miniz-2.0.8 -I..\aten\src\TH -I..\aten\..\third_party\catch\single_include -I..\aten\src\ATen\.. -Icaffe2\aten\src\ATen -I..\third_party\miniz-2.0.8 -I..\caffe2\core\nomnigraph\include -I..\c10\.. -Ithird_party\ideep\mkl-dnn\include -I..\third_party\ideep\mkl-dnn\src\..\include -I..\third_party\cpuinfo\include -I..\third_party\FP16\include -I..\cmake\..\third_party\googletest\googlemock\include -I..\cmake\..\third_party\googletest\googletest\include -I..\third_party\protobuf\src -Iwin_tmp\mkl\include -I..\cmake\..\third_party\eigen -IC:\Jenkins\Miniconda3\include -IC:\Jenkins\Miniconda3\lib\site-packages\numpy\core\include -I..\cmake\..\third_party\pybind11\include -I\opt\rocm\hip\include -I\include -I..\cmake\..\third_party\cub -Iwin_tmp\magma\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I..\third_party\ideep\mkl-dnn\include -I..\third_party\ideep\include -I..\caffe2 /DWIN32 /D_WINDOWS /GR  /w /EHa /MP /bigobj -openmp -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION /MD /O2 /Ob2  /w /EHa /MP /bigobj   -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD /Z7 /EHa /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -O2 -DCAFFE2_BUILD_MAIN_LIB -DONNX_BUILD_MAIN_LIB -std:c++14 /showIncludes /Focaffe2\CMakeFiles\torch_cpu.dir\__\aten\src\ATen\ParallelThreadPoolNative.cpp.obj /Fdcaffe2\CMakeFiles\torch_cpu.dir\ /FS -c ..\aten\src\ATen\ParallelThreadPoolNative.cpp
c:\users\circleci\project\aten\src\aten\core\boxing\KernelFunction_impl.h(70): error C2672: 'c10::impl::boxAndCallBoxedFunc': no matching overloaded function found
C:\Users\circleci\project\aten\src\ATen/core/dispatch/Dispatcher.h(204): note: see reference to function template instantiation 'Return c10::KernelFunction::callUnboxed<Return,const at::Tensor&,const at::Tensor&,bool,bool>(const c10::OperatorHandle &,const at::Tensor &,const at::Tensor &,bool,bool) const' being compiled
        with
        [
            Return=void
        ]
C:\Users\circleci\project\aten\src\ATen/core/dispatch/Dispatcher.h(212): note: see reference to function template instantiation 'Return c10::Dispatcher::callUnboxedWithDispatchKey<Return,const at::Tensor&,const at::Tensor&,bool,bool>(const c10::OperatorHandle &,c10::optional<c10::DispatchKey>,const at::Tensor &,const at::Tensor &,bool,bool) const' being compiled
        with
        [
            Return=void
        ]
C:\Users\circleci\project\aten\src\ATen/core/dispatch/Dispatcher.h(175): note: see reference to function template instantiation 'Return c10::Dispatcher::callUnboxed<Return,const at::Tensor&,const at::Tensor&,bool,bool>(const c10::OperatorHandle &,const at::Tensor &,const at::Tensor &,bool,bool) const' being compiled
        with
        [
            Return=void
        ]
C:\Users\circleci\project\build\aten\src\ATen/core/TensorMethods.h(64): note: see reference to function template instantiation 'Return c10::OperatorHandle::callUnboxed<void,const at::Tensor&,const at::Tensor&,bool,bool>(const at::Tensor &,const at::Tensor &,bool,bool) const' being compiled
        with
        [
            Return=void
        ]
c:\users\circleci\project\aten\src\aten\core\boxing\KernelFunction_impl.h(70): error C2770: invalid explicit template argument(s) for 'Result c10::impl::boxAndCallBoxedFunc(c10::KernelFunction::InternalBoxedKernelFunction (__cdecl *),c10::OperatorKernel *,const c10::OperatorHandle &,Args...,enable_if<_Test,_Ty>::type)'
        with
        [
            _Ty=int
        ]
C:\Users\circleci\project\aten\src\ATen/core/boxing/boxing.h(52): note: see declaration of 'c10::impl::boxAndCallBoxedFunc'
c:\users\circleci\project\aten\src\aten\core\boxing\KernelFunction_impl.h(70): error C2893: Failed to specialize function template 'Result c10::impl::boxAndCallBoxedFunc(c10::KernelFunction::InternalBoxedKernelFunction (__cdecl *),c10::OperatorKernel *,const c10::OperatorHandle &,Args...,enable_if<_Test,_Ty>::type)'
        with
        [
            _Ty=int
        ]
c:\users\circleci\project\aten\src\aten\core\boxing\KernelFunction_impl.h(70): note: With the following template arguments:
c:\users\circleci\project\aten\src\aten\core\boxing\KernelFunction_impl.h(70): note: 'Result=Return'
c:\users\circleci\project\aten\src\aten\core\boxing\KernelFunction_impl.h(70): note: 'Args={at::Tensor &, bool}'
```

**Comment by EscapeZero** [comment]
I think I have fix for this. While extensively digging around, I finally found out that `guts::disjunction` (aliased to `std::disjunction`) was not happy about eating expanded `Args...` So I figured maybe MSVC implementation is wonky and tried switching it to the cppreference implementation, and things seemed to start working again.

**Comment by EscapeZero** [comment]
Can anyone try this patch with changes to circleci targeted to problematic msvc version? (I have 0 circleci knowledge haha)

**Comment by peterjc123** [comment]
@EscapeZero No problem. I'll do this.

**Comment by peterjc123** [comment]
Fixed by #33076.

**Comment by EscapeZero** [comment]
@peterjc123 Can we go ahead and switch circleci to the previously broken version of msvc, so that we catch this much sooner in the future?

**Comment by ezyang** [comment]
SGTM. Should be an easy enough patch, now that it's made generic.

**Comment by peterjc123** [comment]
I'll add the test configuration to https://github.com/pytorch/pytorch/issues/18319#issuecomment-562025577.
