### ISSUE TITLE
NCCL Error 4: invalid argument

### ISSUE THREAD

**Issue by chi0tzp** [pytorch/pytorch#31045]
## 🐛 Bug
After upgrading to CUDA 10.2 (10.2, V10.2.89), and nccl-2.5.6-1 (PyTorch 1.3.1), I have the following error when using `DataParallel`:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL Error 4: invalid argument
Aborted (core dumped)
```
I'm on Arch Linux (maybe this explains a lot). I'll be waiting for Arch upgrades (cuda and/or nccl), but I'm also posting this here in case it's useful.

cc @ngimel

**Comment by izdeby** [comment]
@chi0tzp, thank you for reporting the issue. Do you have a reproducible example?

**Comment by ngimel** [comment]
cc @csarofeen @ptrblck

**Comment by ptrblck** [comment]
@chi0tzp Do you see any other error before NCCL raised this exception?
We often see another assertion (e.g. indexing error) before NCCL catches this error.

**Comment by chi0tzp** [comment]
Hi @izdeby, a reproducible example is the following:

```
import torch
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable
from torch.utils.data import Dataset, DataLoader


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class Model(nn.Module):
    def __init__(self, input_size, output_size):
        super(Model, self).__init__()
        self.fc = nn.Linear(input_size, output_size)
        self.sigmoid = nn.Sigmoid()

    def forward(self, input):
        return self.sigmoid(self.fc(input))


# Parameters and DataLoaders
input_size = 5
output_size = 1
batch_size = 30
data_size = 100

rand_loader = DataLoader(dataset=RandomDataset(input_size, data_size),
                         batch_size=batch_size, shuffle=True)

model = Model(input_size, output_size)
if torch.cuda.device_count() > 1:
    print("Let's use", torch.cuda.device_count(), "GPUs!")
    model = nn.DataParallel(model).cuda()

optimizer = optim.SGD(params=model.parameters(), lr=1e-3)
cls_criterion = nn.BCELoss()

for data in rand_loader:
    targets = torch.empty(batch_size).random_(2).view(-1, 1)

    if torch.cuda.is_available():
        input = Variable(data.cuda())
        with torch.no_grad():
            targets = Variable(targets.cuda())
    else:
        input = Variable(data)
        with torch.no_grad():
            targets = Variable(targets)

    output = model(input)

    optimizer.zero_grad()
    loss = cls_criterion(output, targets)
    loss.backward()
    optimizer.step()
```

@ptrblck I can't see I remember such an error. In any case, I don't get it using the simple example above.

Thanks.

**Comment by ptrblck** [comment]
@chi0tzp Thanks for the code snippet!
I removed the deprecated `Variable` calls and got the following error:
```python
ValueError: Target and input must have the same number of elements. target nelement (30) != input nelement (10)
```
This is due to the last batch, which will have 10 samples (using `batch_size = 30` and `data_size = 100`), while you create the target with the fixed `batch_size`.

Could you initialize it as:
```python
targets = torch.empty(data.size(0)).random_(2).view(-1, 1)
```
and rerun the code again?

**Comment by chi0tzp** [comment]
@ptrblck Many thanks for your feedback. I changed `targets` initialization as you suggested and now I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    loss.backward()
  File "/usr/lib/python3.8/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/lib/python3.8/site-packages/torch/autograd/__init__.py", line 97, in backward
    Variable._execution_engine.run_backward(
  File "/usr/lib/python3.8/site-packages/torch/autograd/function.py", line 77, in apply
    return self._forward_cls.backward(self, *args)
  File "/usr/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 32, in backward
    return (None,) + ReduceAddCoalesced.apply(ctx.input_device, ctx.num_inputs, *grad_outputs)
  File "/usr/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 43, in forward
    return comm.reduce_add_coalesced(grads, destination)
  File "/usr/lib/python3.8/site-packages/torch/cuda/comm.py", line 121, in reduce_add_coalesced
    flat_result = reduce_add(flat_tensors, destination)
  File "/usr/lib/python3.8/site-packages/torch/cuda/comm.py", line 77, in reduce_add
    nccl.reduce(inputs, outputs, root=nccl_root)
  File "/usr/lib/python3.8/site-packages/torch/cuda/nccl.py", line 51, in reduce
    torch._C._nccl_reduce(inputs, outputs, root, op, streams, comms)
RuntimeError: NCCL Error 4: invalid argument
```

Running with ``, I get:

```
Let's use 2 GPUs!
yyy:845:867 [0] NCCL INFO Bootstrap : Using [0]eno1:x.x.x.x<0>
yyy:845:867 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

yyy:845:867 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
yyy:845:867 [0] NCCL INFO NET/Socket : Using [0]eno1:x.x.x.x<0>
NCCL version 2.5.6+cuda10.2

yyy:845:867 [0] misc/argcheck.cc:40 NCCL WARN Reduce : invalid root 0 (root should be in the 0..0 range)
yyy:845:867 [0] NCCL INFO enqueue.cc:447 -> 4

yyy:845:867 [0] init.cc:840 NCCL WARN comm 0x7f9df00000c0 has already been destroyed
yyy:845:867 [0] NCCL INFO group.cc:184 -> 4
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL Error 4: invalid argument
Aborted (core dumped)

```

**Comment by sclarkson** [comment]
This was fixed in #29014

Should probably request a cherry pick for 1.4.0

**Comment by ngimel** [comment]
I will request a cherry pick

**Comment by chi0tzp** [comment]
@ptrblck @izdeby @sclarkson thank you!

**Comment by ngimel** [comment]
@chi0tzp can this issue be closed, or are you still seeing an error?

**Comment by sclarkson** [comment]
@ngimel Ah, thanks. Guess I didn't look closely enough.

That patch solved the issue for me. I tested NCCL 2.4.8 and 2.5.6, and both work with the patch.

**Comment by valexsyu** [comment]
> @ngimel Ah, thanks. Guess I didn't look closely enough.
> 
> That patch solved the issue for me. I tested NCCL 2.4.8 and 2.5.6, and both work with the patch.

@sclarkson hi, I am a rookie and trying to fix the same problem, but I don't how to use patch form #29014.
Could you help to provide more detail description? 
Thanks

**Comment by ptrblck** [comment]
@valexsyu The patch should be already in PyTorch `1.4.0`. Are you seeing this error using this version?

**Comment by chi0tzp** [comment]
@valexsyu @ptrblck I can confirm that the patch works in PyTorch 1.4.0-4 (in Arch Linux: `python-pytorch-cuda-1.4.0-4` -- version `1.4.0-3` was still buggy, at least in Arch).

**Comment by valexsyu** [comment]
> @valexsyu The patch should be already in PyTorch `1.4.0`. Are you seeing this error using this version?

hi ptrblck,

It is work now!! I update PyTorch to 1.4.0 , thanks for your reply !!
