### ISSUE TITLE
Cuda error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by legoritma** [pytorch/pytorch#31285]
## 🐛 Bug

Hi, torch.cuda.is_available() returns True, however I cannot use cuda tensor. I tried to uninstall and install anaconda, nvidia drivers and cudatoolkit. Still the error is same

## To Reproduce
 I did nothiing special, just installed pytorch on anaconda and execute following commanda

```
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.tensor([1.0, 2.0])
tensor([1., 2.])
>>> torch.tensor([1.0, 2.0]).cuda()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\balci\Anaconda3\envs\pytorch\lib\site-packages\torch\tensor.py", line 130, in __repr__
    return torch._tensor_str._str(self)
  File "C:\Users\balci\Anaconda3\envs\pytorch\lib\site-packages\torch\_tensor_str.py", line 311, in _str
    tensor_str = _tensor_str(self, indent)
  File "C:\Users\balci\Anaconda3\envs\pytorch\lib\site-packages\torch\_tensor_str.py", line 209, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "C:\Users\balci\Anaconda3\envs\pytorch\lib\site-packages\torch\_tensor_str.py", line 87, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
  File "C:\Users\balci\Anaconda3\envs\pytorch\lib\site-packages\torch\functional.py", line 227, in isfinite
    return (tensor == tensor) & (tensor.abs() != inf)
RuntimeError: CUDA error: no kernel image is available for execution on the device
>>>   
```

## Expected behavior

Run pytorch on gpu

## Environment
```
Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 780
Nvidia driver version: 441.22
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] torch==1.3.1
[pip] torchvision==0.4.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      245  
[conda] mkl-service               2.3.0            py37hb782905_0  
[conda] mkl_fft                   1.0.15           py37h14836fe_0  
[conda] mkl_random                1.1.0            py37h675688f_0  
[conda] pytorch                   1.3.1           py3.7_cuda101_cudnn7_0    pytorch
[conda] torchvision               0.4.2                py37_cu101    pytorch

Process finished with exit code 0
```

 - PyTorch Version (e.g., 1.0): 1.3
 - OS (e.g., Linux): Windows 10 x64
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): -
 - Python version: 3.7.5 (conda)
 - CUDA/cuDNN version: cudatoolkit=10.1 (conda),  I also tried with cudatoolkit 10.1 and 10.2 (https://developer.nvidia.com/cuda-toolkit-archive)
 - GPU models and configuration: GTX 780
 - Any other relevant information: -

**Comment by peterjc123** [comment]
GTX 780 has the cuda cc of 3.5, which is not supported anymore in 1.3.1. You'll have to build PyTorch from source.

**Comment by ParikshitS** [comment]
I am getting the same error. I am using Tesla K40c. Cuda version 10.2. Pytorch 1.4.0

**Comment by peterjc123** [comment]
@ParikshitS Yes, your card is not supported anymore, too. Please build from source.

**Comment by andmax** [comment]
Hi @peterjc123 I am also getting the same error with pytorch 1.4.0 using cuda 10.1 and a gtx titan.

**Comment by peterjc123** [comment]
If you refer to the following cards for Titan, then maybe you should build from source too.
```
GeForce GTX TITAN Z
GeForce GTX TITAN Black
GeForce GTX TITAN
```

**Comment by andmax** [comment]
Hi @peterjc123 thanks for your prompt response.  I am referring to the last GPU you listed.  I am trying to understand why I should build from source if this GPU is within the range of supported GPUs by CUDA compute capability (3.5 is ok with CUDA 10.1 toolkit) and PyTorch says CUDA is available.  I created a specific issue for this:

[36062](https://github.com/pytorch/pytorch/issues/36062)

**Comment by peterjc123** [comment]
Yes, arch 3.5 is supported by CUDA 10.1. But starting from 1.3.1, we start to compile binaries only for arch 3.7 and up. That caused the issue you mentioned.

**Comment by andmax** [comment]
Oh, that is unfortunate, @peterjc123.  Why then torch.cuda.is_available() function is returning True?  Should its semantics be CUDA is available /to be used by PyTorch/?

**Comment by peterjc123** [comment]
I guess `torch.cuda.is_available` only checks whether your driver is compatible with the version of cuda we used in the binary. So it means that CUDA 10.1 is compatible with your driver. But when you do computation with CUDA, it couldn't find the code for your arch.

**Comment by andmax** [comment]
Ok @peterjc123, but it is strange.  I tried tensorflow 2.1 in the same machine, with the same configuration, and it worked from the conda package, without need to compile it from source.  My suggestion is for PyTorch be compiled with CUDA archs matching the CUDA toolkit support.  For CUDA 10.1 is 3.0 forward.  I don't understand this decision to have it for arch 3.7 and up.

**Comment by peterjc123** [comment]
@soumith knows the answer.

**Comment by legoritma** [comment]
@peterjc123 Is it possible to add specific errors/warnings for these cases? I believe these are very common pitfalls for beginners who has old GPU or systems

BTW my original problem is solved by compiling source code.

**Comment by peterjc123** [comment]
> @peterjc123 Is it possible to add specific errors/warnings for these cases? I believe these are very common pitfalls for beginners who has old GPU or systems
> 
> BTW my original problem is solved by compiling source code.

Yeah, it is already done but sometimes doesn't work. Would you please open a new issue?

**Comment by renesax14** [comment]
What does the error even mean? what is actually going wrong?
```
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

**Comment by peterjc123** [comment]
It means that there is no binary for your GPU card. We only compile binaries for NV cards with CC 3.7 and up.

**Comment by brando90** [comment]
@peterjc123  Where is a complete list of GPUs that are supported and not?

Btw, these are the GPUs I believe I have access to. Which are and which are not supported?

```
Specific kind of GPU: `requirements = (CUDADeviceName == "GeForce GTX TITAN X")`

* K40: `"Tesla K40m"`
* Titan X Maxwell: `"GeForce GTX TITAN X"`
* Titan X Pascal (2016): `"TITAN X (Pascal)"`
* Titan Xp (2017): `"TITAN Xp"`
```

**Comment by peterjc123** [comment]
You can get the cuda compute capability level of your cards [here](https://developer.nvidia.com/cuda-gpus). If you have CC >= 3.7, then it is supported.

**Comment by brando90** [comment]
> You can get the cuda compute capability level of your cards [here](https://developer.nvidia.com/cuda-gpus). If you have CC >= 3.7, then it is supported.

I have no idea how to read that but thanks.

**Comment by peterjc123** [comment]
GPU | Compute Capability
-- | --
NVIDIA TITAN RTX | 7.5
Geforce RTX 2080 Ti | 7.5
Geforce RTX 2080 | 7.5
Geforce RTX 2070 | 7.5
Geforce RTX 2060 | 7.5
NVIDIA TITAN V | 7.0
NVIDIA TITAN Xp | 6.1
NVIDIA TITAN X | 6.1
GeForce GTX 1080 Ti | 6.1
GeForce GTX 1080 | 6.1
GeForce GTX 1070 | 6.1
GeForce GTX 1060 | 6.1
GeForce GTX 1050 | 6.1
GeForce GTX TITAN X | 5.2
GeForce GTX TITAN Z | 3.5
GeForce GTX TITAN Black | 3.5
GeForce GTX TITAN | 3.5
GeForce GTX 980 Ti | 5.2
GeForce GTX 980 | 5.2
GeForce GTX 970 | 5.2
GeForce GTX 960 | 5.2
GeForce GTX 950 | 5.2
GeForce GTX 780 Ti | 3.5
GeForce GTX 780 | 3.5
GeForce GTX 770 | 3.0
GeForce GTX 760 | 3.0
GeForce GTX 750 Ti | 5.0
GeForce GTX 750 | 5.0
GeForce GTX 690 | 3.0
GeForce GTX 680 | 3.0
GeForce GTX 670 | 3.0
GeForce GTX 660 Ti | 3.0
GeForce GTX 660 | 3.0
GeForce GTX 650 Ti BOOST | 3.0
GeForce GTX 650 Ti | 3.0
GeForce GTX 650 | 3.0
GeForce GTX 560 Ti | 2.1
GeForce GTX 550 Ti | 2.1
GeForce GTX 460 | 2.1
GeForce GTS 450 | 2.1
GeForce GTS 450* | 2.1
GeForce GTX 590 | 2.0
GeForce GTX 580 | 2.0
GeForce GTX 570 | 2.0
GeForce GTX 480 | 2.0
GeForce GTX 470 | 2.0
GeForce GTX 465 | 2.0
GeForce GT 740 | 3.0
GeForce GT 730 | 3.5
GeForce GT 730 DDR3,128bit | 2.1
GeForce GT 720 | 3.5
GeForce GT 705* | 3.5
GeForce GT 640 (GDDR5) | 3.5
GeForce GT 640 (GDDR3) | 2.1
GeForce GT 630 | 2.1
GeForce GT 620 | 2.1
GeForce GT 610 | 2.1
GeForce GT 520 | 2.1
GeForce GT 440 | 2.1
GeForce GT 440* | 2.1
GeForce GT 430 | 2.1
GeForce GT 430* | 2.1


GPU | Compute Capability
-- | --
Tesla K80 | 3.7
Tesla K40 | 3.5
Tesla K20 | 3.5
Tesla C2075 | 2.0
Tesla C2050/C2070 | 2.0

**Comment by GabrielBena** [comment]
Hello, I'm trying to use some torch functions with CUDA on a Nvidia 940MX (cc = 5.0). I've built pytorch 1.2 from source and am using CUDA 9.2. I am still getting the error when trying : 
tensor.data.fill, or to do a torch.sum for example.

**Comment by mkorycinski** [comment]
I am getting the same error trying to compute on Tesla V100, with compute capability of 7.0. Is there something else I should check for?

**Comment by xwang233** [comment]
@mkorycinski 
- Do you have multiple GPUs? If so, you may need to set CUDA_VISIBLE_DEVICES to make sure your code runs on V100 GPU instead of an old GPU.
- Where do you get the pytorch package (pip, build from source, or...), and what's the pytorch version you have?

**Comment by Ceceu** [comment]
It is frustrating that in a deep learning framework you have to waste so much time to run a project on GPU. And I hadn't even started trying to run on multi GPUs.

**Comment by ashwinvaswani** [comment]
@mkorycinski Even I am facing the same issue on Tesla V100. How did you manage to fix this?

**Comment by trevorgribble** [comment]
> It means that there is no binary for your GPU card. We only compile binaries for NV cards with CC 3.7 and up.

hi @peterjc123 & @soumith 

I have an old GeForce GT 740 with Cuda Capability 3.0 and I spent last 2 days getting CUDA set up, installing pytorch from source, only to run into this same kernal image issue as others in this thread.

Given that I've followed and verified all cuda installation, succesfully built pytorch from source, and it's still not working...should I just give up on trying to make this work on my older setup?  It's obviously quite frustrating to not even reach the point of being able to code.

Thanks in advance for your help

```
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.backends.cudnn.enabled)
device = torch.device('cuda')
print(torch.cuda.get_device_properties(device))
print(torch.tensor([1.0, 2.0]).cuda())
```
outputs

```
1.3.1
True
True
_CudaDeviceProperties(name='GeForce GT 740', major=3, minor=0, total_memory=1991MB, multi_processor_count=2)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-668ac820ff90> in <module>
      5 device = torch.device('cuda')
      6 print(torch.cuda.get_device_properties(device))
----> 7 print(torch.tensor([1.0, 2.0]).cuda())
      8 

~/anaconda3/envs/pytorch_test/lib/python3.7/site-packages/torch/tensor.py in __repr__(self)
    128         # characters to replace unicode characters with.
    129         if sys.version_info > (3,):
--> 130             return torch._tensor_str._str(self)
    131         else:
    132             if hasattr(sys.stdout, 'encoding'):

~/anaconda3/envs/pytorch_test/lib/python3.7/site-packages/torch/_tensor_str.py in _str(self)
    309                 tensor_str = _tensor_str(self.to_dense(), indent)
    310             else:
--> 311                 tensor_str = _tensor_str(self, indent)
    312 
    313     if self.layout != torch.strided:

~/anaconda3/envs/pytorch_test/lib/python3.7/site-packages/torch/_tensor_str.py in _tensor_str(self, indent)
    207     if self.dtype is torch.float16 or self.dtype is torch.bfloat16:
    208         self = self.float()
--> 209     formatter = _Formatter(get_summarized_data(self) if summarize else self)
    210     return _tensor_str_with_formatter(self, indent, formatter, summarize)
    211 

~/anaconda3/envs/pytorch_test/lib/python3.7/site-packages/torch/_tensor_str.py in __init__(self, tensor)
     85 
     86         else:
---> 87             nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
     88 
     89             if nonzero_finite_vals.numel() == 0:

~/anaconda3/envs/pytorch_test/lib/python3.7/site-packages/torch/functional.py in isfinite(tensor)
    225     if not tensor.is_floating_point():
    226         return torch.ones_like(tensor, dtype=torch.bool)
--> 227     return (tensor == tensor) & (tensor.abs() != inf)
    228 
    229 

RuntimeError: CUDA error: no kernel image is available for execution on the device
```


Further: nvidia-smi output:

```
$ nvidia-smi
Wed Aug 12 09:33:37 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 740      On   | 00000000:01:00.0 N/A |                  N/A |
| 30%   37C    P0    N/A /  N/A |   1132MiB /  1991MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+

```

**Comment by soumith** [comment]
@trevorgribble CUDA Capability 3.0 is not actually supported by PyTorch, as we use __shfl instructions at places, which only came out starting CUDA capability 3.5.

**Comment by jbohnslav** [comment]
This might be the source of the issue for some of you. I have a machine with a Titan RTX and a 1080-Ti. When compiling from source, pytorch only automatically detected the Titan, it appears. I got this error: 

```
UserWarning: 
GeForce GTX 1080 Ti with CUDA capability sm_61 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_75.
If you want to use the GeForce GTX 1080 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```

I uninstalled, and re-installed with this command: `TORCH_CUDA_ARCH_LIST="6.1;7.5" python setup.py install`. Works fine now.

**Comment by nguyenbh1507** [comment]
Creating new environment with python 3.7, install pytorch by `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch`, using `openCV 4.2.0.34` help me solve the same problem on RTX 2060.

**Comment by Abbyyan** [comment]
> @trevorgribble CUDA Capability 3.0 is not actually supported by PyTorch, as we use __shfl instructions at places, which only came out starting CUDA capability 3.5.

![image](https://user-images.githubusercontent.com/12140508/92571321-8e61d500-f2b5-11ea-8369-a0ad20440345.png)

I used `Tesla K40` with CC=3.5, get the same error. `RuntimeError: CUDA error: no kernel image is available for execution on the device`. How to build pytorch from source please?

**Comment by Abbyyan** [comment]
> > @trevorgribble CUDA Capability 3.0 is not actually supported by PyTorch, as we use __shfl instructions at places, which only came out starting CUDA capability 3.5.
> 
> ![image](https://user-images.githubusercontent.com/12140508/92571321-8e61d500-f2b5-11ea-8369-a0ad20440345.png)
> 
> I used `Tesla K40` with CC=3.5, get the same error. `RuntimeError: CUDA error: no kernel image is available for execution on the device`. How to build pytorch from source please?

Meanwhile, It's wired that all the test about pytorch is available, but it just can't use can will raise `RuntimeError: CUDA error: no kernel image is available for execution on the device`. How can i judge whether the `pytorch cuda` can use or not please? Thanks a lot.

**Comment by HeyangQin** [comment]
I came across this error message on GeForce 1080 card and cuda 10.2 which should have compute capability of 6.1. No idea why this still happens.

**Comment by dataplayer12** [comment]
I am facing this issue with an RTX 3090, cuda 11.1 and torch 1.7.0 installed via pip on ubuntu 18.04. While others have faced this issue because of their card being too old, I am apparently facing it because the card is too new. Really weird.

**Comment by GuanhuaWang** [comment]
same error on V100 when using apex, I don't believe you do not support this one?

```
File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 30, in __call__
    *args)
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

**Comment by stas00** [comment]
> I am facing this issue with an RTX 3090, cuda 11.1 and torch 1.7.0 installed via pip on ubuntu 18.04. While others have faced this issue because of their card being too old, I am apparently facing it because the card is too new. Really weird.

I'm on RTX 3090, cuda 11.1 and torch-nightly from:

```
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html -U
```

It's limited until cuda-11.2 is released, but it works just fine.

**Comment by gemfield** [comment]
If you build pytorch from source, please be noted that the compute-capability number passed to nvcc comes in three ways:
1, auto detected from host;
2, user specified with TORCH_CUDA_ARCH_LIST environment variable;
3, if not above and cannot auto detected from host, use default, e.g. "3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX".

For Chinese reader, there has a blog with more detail: https://zhuanlan.zhihu.com/p/313481517

**Comment by kevinbird15** [comment]
I had this issue when trying to run yolov3 with a 3090 and it turned out my problem was that I needed to add the gencode to the makefile.  When I added these lines to the ARCH, it worked: 
```
-gencode arch=compute_80,code=[sm_80,compute_80] \
-gencode arch=compute_86,code=[sm_86,compute_86] \
```
I used this site to help me find the correct codes: https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

**Comment by embray** [comment]
Anyone else finding this issue might also be interested in this [code snippet](https://github.com/pytorch/pytorch/issues/36066#issuecomment-746092519) I wrote which should detect for you which CUDA compute architectures your PyTorch was compiled for.  For these purposes I'm not sure whether or not it's better to use the virtual `compute_` architectures or the `sm_` architectures; someone with more expertise could clarify that point.  For the purposes of the PyTorch 1.5.1 from conda that I'm testing it on it doesn't matter because the always match:

```
#define NVCC_FLAGS_EXTRA "arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37"
```

**Comment by LiUzHiAn** [comment]
> I am facing this issue with an RTX 3090, cuda 11.1 and torch 1.7.0 installed via pip on ubuntu 18.04. While others have faced this issue because of their card being too old, I am apparently facing it because the card is too new. Really weird.

I met the same issue with RTX 3090, cuda 11.0, PtTorch1.7.0, mmcv-full 1.2.2 and mmdet 2.7.0.

**Comment by lgmventura** [comment]
I ran into the same issue with GTX 760M, cuda 11.0, PyTorch 1.7.1, Ubuntu 20.04 Focal Fossa, using Anaconda.

**Comment by jiaxiangshang** [comment]
@GuanhuaWang Hi guanhua,
I have the same env with V100, do you have any suggestions except building from source?
Really thanks for your help.

**Comment by dataplayer12** [comment]
I got around this issue by using NVIDIA's pytorch docker container.

**Comment by GuanhuaWang** [comment]
> @GuanhuaWang Hi guanhua,
> I have the same env with V100, do you have any suggestions except building from source?
> Really thanks for your help.

@jiaxiangshang not really. I just abandon using AWS pre-built pytorch and building from source.

**Comment by pinouchon** [comment]
Same issue with
`NVIDIA-SMI 455.38       Driver Version: 455.38       CUDA Version: 11.1`, python 3.7

```
import torch
import sys
print('A', sys.version)
print('B', torch.__version__)
print('C', torch.cuda.is_available())
print('D', torch.backends.cudnn.enabled)
device = torch.device('cuda')
print('E', torch.cuda.get_device_properties(device))
print('F', torch.tensor([1.0, 2.0]).cuda())
```

Gave me

```
A 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
B 1.8.0.dev20210115+cu110
C True
D True
E _CudaDeviceProperties(name='GeForce RTX 3090', major=8, minor=6, total_memory=24267MB, multi_processor_count=82)
F 
<stacktrace>
CUDA error: no kernel image is available for execution on the device
```

It was fixed with the following:
`pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html -U`

**Comment by johndpope** [comment]
same problem too.

I am on 1.8.0
//  Downloading https://download.pytorch.org/whl/nightly/cu110/torch-1.8.0.dev20210119%2Bcu110-cp37-cp37m-linux_x86_64.whl (1202.3 MB)


fyi @pinouchon - there's a later driver 460 bundle with cuda toolkit 11.2 that fixes other things related to tensorflow 2 (though it doesn't fix this issue) https://developer.nvidia.com/cuda-downloads

**Comment by 0tist** [comment]
Had the same problem, currently using Ubuntu 20.04 with RTX 3090
`pip uninstall torch`
`pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html`
solved the problem for me

**Comment by corticalstack** [comment]
> I am facing this issue with an RTX 3090, cuda 11.1 and torch 1.7.0 installed via pip on ubuntu 18.04. While others have faced this issue because of their card being too old, I am apparently facing it because the card is too new. Really weird.



> pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html -U

The nightly fixed it for me with Ubuntu 20.04, RTX 3090FE, Linux kernal 5.10, thx!

**Comment by mrgransky** [comment]
Is there any script in python and torch I could print cuda compute compatibility CC ?
I tried `$ python -c "import torch; print(torch.cuda.get_arch_list())"` and it returns the error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'torch.cuda' has no attribute 'get_arch_list'
```
Environment:
```
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux

torch: 1.4.0     torchvision: 0.5.0

Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
```

**Comment by sk-g** [comment]
For people facing this on 3090 FE  (or any 30xx cards) here is what helped

Fairseq training wrapper failed with this error with CUDA 11.0 + pytorch 0.7.1. 

After a series of painstaking efforts, I realized that I had two versions of torch living in `dist-packages` and `site-packages` and fairseq was using an ancient install of pytorch during build.


The comment from @stas00 has eventually helped figure out the correct way to do things.

https://github.com/pytorch/pytorch/issues/31285#issuecomment-739139454

## Solution

First, purge all torch installs and reinstall it from the correct source. 

Since I have CUDA11.1 (and corresponding CUDNN `cudnn-11.1-linux-x64-v8.0.5.39` ) installed I used 
`pip3 install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html -U`

Ideally one should not use nightly versions unless you are looking for specific things currently under development especially when the latest version of CUDA is not yet supported by  torch.

`pip3 install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/<cuda_ver>/torch_nightly.html -U`

In my opinion, the best way to install torch is to clone the repo and build it from source with the correct flags.

**Comment by pederismo** [comment]
Experiencing the same issue when running with torch.distributed.launch on some A100 GPUs with CUDA 11.0, unfortunately installing the nightly Pytorch version didn't help, anybody has a suggestion?

**Comment by stas00** [comment]
I gave up on the nightlies and have been building my own, using nvidia docker image. I then take the wheels out of the image and install them on my system.

You will have to:
1. adjust `TORCH_CUDA_ARCH_LIST` to match the desired archs
2. choose the docker image that matches your nvidia-drivers, e.g. the one listed in the script below uses the latest of this writing docker image, and I had to update my nvidia kernel to 465 and cuda to 11.3. If your drivers are less than that use an earlier image. See comment notes for details.
3. I map this folder on my fs `~/github/00pytorch/pytorch/docker` to docker's `/tmp/out` where I copy the wheels. So make sure to edit it to the real folder on your system 

It will take a few hours to build if you have a relatively strong machine, but otherwise it's very painless to do.

```
####################
### source build ###
####################

# one time prep

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker

# then
docker run --runtime=nvidia --rm nvidia/cuda:11.0-base nvidia-smi

# find the latest container at https://ngc.nvidia.com/catalog/containers/nvidia:pytorch (use Tags tab),
# but also check that the driver version isn't too high in release notes here:
# https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/index.html
# then pull it:
docker pull nvcr.io/nvidia/pytorch:21.04-py3

#docker run --gpus all --ipc=host --rm -it nvcr.io/nvidia/pytorch:21.04-py3
# to mount some host system dir inside the docker -v src:tgt
docker run --gpus all --ipc=host --rm -it -v ~/github/00pytorch/pytorch/docker:/tmp/output nvcr.io/nvidia/pytorch:21.04-py3

# once docker is running:
conda create -n pytorch-dev python=3.8 -y
bash
conda init bash
conda activate pytorch-dev
conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses -y
conda install -c pytorch magma-cuda113 -y

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
# if you are updating an existing checkout
#git submodule sync
#git submodule update --init --recursive
#git pull

# to build a wheel
unset PYTORCH_BUILD_VERSION
unset PYTORCH_VERSION
TORCH_CUDA_ARCH_LIST="6.1 8.6" \
CUDA_HOME="/usr/local/cuda" \
CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
USE_SYSTEM_NCCL=1 \
NCCL_INCLUDE_DIR="/usr/include/" \
NCCL_LIB_DIR="/usr/lib/" \
python setup.py bdist_wheel 2>&1 | tee build.log
pip install dist/*whl
# make a copy of the wheel outside the docker
cp dist/*whl /tmp/output

# adjust TORCH_CUDA_ARCH_LIST if needed, the full list is:
# TORCH_CUDA_ARCH_LIST="5.2 6.0 6.1 7.0 7.5 8.0 8.6+PTX"

# had to install nccl .so objects on the target system

# could also add:
# USE_OPENCV=1 \
# but need to have matching .so objects on the target system

# NEXT: build torchvision - since many packages depend on it

cd ..
git clone https://github.com/pytorch/vision
cd vision
# if you are updating an existing checkout
#git pull

# to build a wheel
TORCH_CUDA_ARCH_LIST="6.1 8.6" \
python setup.py bdist_wheel
pip install dist/*whl
# make a copy of the wheel outside the docker
cp dist/*whl /tmp/output


cd ..
git clone --recursive https://github.com/pytorch/audio
cd audio
# if you are updating an existing checkout
#git submodule sync
#git submodule update --init --recursive
#git pull

# to build a wheel
TORCH_CUDA_ARCH_LIST="6.1 8.6" \
BUILD_SOX=1 python setup.py bdist_wheel
pip install dist/*whl
# make a copy of the wheel outside the docker
cp dist/*whl /tmp/output


```

**Comment by Amit-GH** [comment]
This troubled me for a couple of days. I got it working by following these steps. I am using AWS EC2 instance with AMI image. Some details about my system:
```
Operating System: Ubuntu 18.04.5 LTS
Kernel: Linux 5.4.0-1051-aws
Architecture: x86-64
```
I changed cuda to 11.1 using [this](https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-base.html) guide. Then installed PyTorch again using the below command:
```
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge
``` 
which is for Cuda-11.1 and pyTorch 1.8.0. I got the command from [here](https://pytorch.org/get-started/previous-versions/).

**Comment by MausamGaurav** [comment]
Unfortunately none of the methods discussed here worked for me. I tried nightly builds, docker and building from source. The latter two options result in errors and the build process never succeeds because of these errors. Just hope there was a robust work around this problem.

**Comment by lvZic** [comment]
> > I am facing this issue with an RTX 3090, cuda 11.1 and torch 1.7.0 installed via pip on ubuntu 18.04. While others have faced this issue because of their card being too old, I am apparently facing it because the card is too new. Really weird.
> 
> > pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html -U
> 
> The nightly fixed it for me with Ubuntu 20.04, RTX 3090FE, Linux kernal 5.10, thx!

 following fixed it for me with RTX 3070, docker.
 pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html -U

**Comment by lvZic** [comment]
> Getting this issue using RTX 3090 with `torch==1.10.0` and CUDA 11.3 on Ubuntu 20.04.
> 
> @lvZic running `pip install --pre torch` does not help in my case as it will only try to install `1.10.0` again.

torch-1.8.1+cu111-cp38-cp38-linux_x86_64, and cuda 11.1 worked for me on ubuntn 1804 using 3070,  but won't work without "pip install --pre torch" command under docker environment. 
Because the card is too new, u may try an adapted version from https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html

**Comment by MaxGCM** [comment]
As below is my environment:

PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.14.4

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 470.86
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.1+cu111
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.9.1+cu111
[conda] Could not collect

When i trained,  i got the error message RuntimeError: CUDA error: no kernel image is available for execution on the device.
First of all, i tried 

>>> import torch
>>> import sys
>>> print('A', sys.version)
A 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
>>> print('B', torch.__version__)
B 1.8.1+cu111
>>> print('C', torch.cuda.is_available())
C True
>>> print('D', torch.backends.cudnn.enabled)
D True
>>> device = torch.device('cuda')
>>> print('E', torch.cuda.get_device_properties(device))
E _CudaDeviceProperties(name='NVIDIA GeForce RTX 3060 Laptop GPU', major=8, minor=6, total_memory=5938MB, multi_processor_count=30)
>>> print('F', torch.tensor([1.0, 2.0]).cuda())
F tensor([1., 2.], device='cuda:0')
it was working well.
 Secondly, when i compiled the project and trained that used that TORCH_CUDA_ARCH_LIST=8.6 , still not working.
 By thhe way, I got the mmdetection3d project from my colleague(use same docker environment rom them), they have built and trained sucessfully on their own computer, any suggestion??

**Comment by 2blackbar** [comment]
Hey, can someone upload compiled torch with old compute 3.5 support  somewhere? So many answers and its stil not solved, my gtx has a lot of cuda cores and yet its not supported anymore, weird, at least one version per half year would be great, suddenly cutting off users with older cards is a strange decision.At least one , one release with latest pytorch would be appreciated a lot.

**Comment by celsofranssa** [comment]
> Hey, can someone upload compiled torch with old compute 3.5 support somewhere? So many answers and its stil not solved, my gtx 780 has a lot of cuda cores and yet its not supported anymore, weird, at least one version per half year would be great, suddenly cutting off users with older cards is a strange decision.At least one , one release with latest pytorch would be appreciated a lot. Hey if you lack space to keep it, i can create googledrive account for you, 25gb to keep it for us all on win10

Hey @2blackbar,
I guess the quick solution is to install from the source following instructions at this URL: https://github.com/pytorch/pytorch#from-source

**Comment by jolestar** [comment]
```
pip uninstall torch
Found existing installation: torch 1.11.0

pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu115

Successfully installed torch-1.11.0+cu115 torchaudio-0.11.0+cu115
```

Resolve this problem.

* ubuntu 22.04
* GeForce RTX 3090

**Comment by ilisparrow** [comment]
> ```
> pip uninstall torch
> Found existing installation: torch 1.11.0
> 
> pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu115
> 
> Successfully installed torch-1.11.0+cu115 torchaudio-0.11.0+cu115
> ```
> 
> Resolve this problem.
> 
>     * ubuntu 22.04
> 
>     * GeForce RTX 3090

This worked for me, thanks.

**Comment by dennisushi** [comment]
> > pip3 install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/<cuda version>/torch_nightly.html -U
> 
> This is the comment that saved me for RTX 3080, Ubuntu 18. The previous solutions did not work.

The problem appeared again and this time this wasn't enough to solve it. What solved it was: Updating CUDA to 11.6 (was 9.1 before), installing as usual with UI command - https://pytorch.org/get-started/locally/ , selecting CUDA 11.3, Linux, Torch 1.11.0 (Stable)

**Comment by danielajisafe** [comment]
Running the command below fixed it for me. I am using a laptop GPU RTX 3080

``` conda install pytorch torchvision torchaudio cuda=11.6 -c pytorch-nightly -c nvidia
```

**Comment by wasdee** [comment]
Just install the cuda from <https://pytorch.org/get-started/locally/>
 for example, as of today
```
pip3 install torch torchvision torchaudio --force-reinstall  --extra-index-url https://download.pytorch.org/whl/cu116
```

**Comment by eyildiz-ugoe** [comment]
> Just install the cuda from https://pytorch.org/get-started/locally/ for example, as of today
> 
> ```
> pip3 install torch torchvision torchaudio --force-reinstall  --extra-index-url https://download.pytorch.org/whl/cu116
> ```

Fixed it for me. Ubuntu 22.04.  RTX 3090

**Comment by a-v-ebrahimi** [comment]
> > Just install the cuda from https://pytorch.org/get-started/locally/ for example, as of today
> > ```
> > pip3 install torch torchvision torchaudio --force-reinstall  --extra-index-url https://download.pytorch.org/whl/cu116
> > ```
> 
> Fixed it for me. Ubuntu 22.04. RTX 3090

This worked for me on RTX 3060 and Nvidia PyTorch container 👌

**Comment by scottfleming** [comment]
Hit the same error. Running `nvidia-smi` I noticed that it had `CUDA Version 11.4` listed in the first row, but when I ran `torch.__version__` from the Python interpreter, it listed my current PyTorch version as `1.12.0+cu102` (i.e., the Torch version was specified for "CUDA Version 10.2". So I uninstalled `torch` and then reinstalled using the proper specs on the "[Install](https://pytorch.org/)" page on the PyTorch website: `pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113`. That did it, everything is working fine now.

**Comment by maheshmechengg** [comment]
Upgrading torch + cuda for available will solve the issue.
pip install torch==1.12.0+cu116 torchvision==0.13.0+cu116 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu116

**Comment by tuannvhust** [comment]
@maheshmechengg  omg , it works for me, thank you so much

**Comment by germanjke** [comment]
> Just install the cuda from https://pytorch.org/get-started/locally/ for example, as of today
> 
> ```
> pip3 install torch torchvision torchaudio --force-reinstall  --extra-index-url https://download.pytorch.org/whl/cu116
> ```

amazing, this helped me, thanks!

**Comment by CrackerHax** [comment]
> > Just install the cuda from https://pytorch.org/get-started/locally/ for example, as of today
> > ```
> > pip3 install torch torchvision torchaudio --force-reinstall  --extra-index-url https://download.pytorch.org/whl/cu116
> > ```
> 
> amazing, this helped me, thanks!

Worked for me too thanks

**Comment by bamboosdu** [comment]
> > Just install the cuda from https://pytorch.org/get-started/locally/ for example, as of today
> > ```
> > pip3 install torch torchvision torchaudio --force-reinstall  --extra-index-url https://download.pytorch.org/whl/cu116
> > ```
> 
> Fixed it for me. Ubuntu 22.04. RTX 3090

It works for me

**Comment by MohammadTabbaby** [comment]
> GTX 780 has the cuda cc of 3.5, which is not supported anymore in 1.3.1. You'll have to build PyTorch from source.

![Screenshot (11)](https://github.com/pytorch/pytorch/assets/96926242/e7b59d0d-37a3-44c1-96bd-dddc24e2d890)
Hi! i'm building PyTorch from source as mentioned earlier  ..  should i replace the original files ?

**Comment by mha142** [comment]
> Just install the cuda from https://pytorch.org/get-started/locally/ for example, as of today
> 
> ```
> pip3 install torch torchvision torchaudio --force-reinstall  --extra-index-url https://download.pytorch.org/whl/cu116
> ```

First I needed to check the CUDA version on my machine, so I  used the command:
`nvidia-smi`
I found it to be 12.4 
so I used the same command just changed the end from cu116 to cu124 and it worked like a charm! 

`pip3 install torch torchvision torchaudio --force-reinstall  --extra-index-url https://download.pytorch.org/whl/cu124`

Thank you

**Comment by AriGarcia22** [comment]
> @ParikshitSSí, tu tarjeta ya no es compatible. Crea la versión desde el código fuente.
@ParikshitS @legoritma Plss, could you please explain this solution? How to compile from source code in detail plsss

**Comment by AriGarcia22** [comment]
> > Simplemente instale el cuda desde https://pytorch.org/get-started/locally/ por ejemplo, a partir de hoy
> > ```
> > pip3 install torch torchvision torchaudio --force-reinstall  --extra-index-url https://download.pytorch.org/whl/cu116
> > ```
> 
> Primero necesitaba verificar la versión de CUDA en mi máquina, así que usé el comando: `nvidia-smi` Encontré que era 12.4, así que usé el mismo comando, simplemente cambié el final de cu116 a cu124 y funcionó de maravillas.
> 
> `pip3 install torch torchvision torchaudio --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu124`
> 
> Gracias

Hello, this helped you to solve the problem of “RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1”. I have a Tesla K40c board with CUDA11.4, I have the same problem and what I have seen is only compiling in the PyTorch source. could you please help me? Pleaseee 
 @mha142

**Comment by AriGarcia22** [comment]
> > Just install the cuda from https://pytorch.org/get-started/locally/ for example, as of today
> > ```
> > pip3 install torch torchvision torchaudio --force-reinstall  --extra-index-url https://download.pytorch.org/whl/cu116
> > ```
> 
> First I needed to check the CUDA version on my machine, so I used the command: `nvidia-smi` I found it to be 12.4 so I used the same command just changed the end from cu116 to cu124 and it worked like a charm!
> 
> `pip3 install torch torchvision torchaudio --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu124`
> 
> Thank you

@mha142 Hello, this helped you to solve the problem of “RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1”. I have a Tesla K40c board with CUDA11.4, I have the same problem and what I have seen is only compiling in the PyTorch source. could you please help me?

**Comment by miroi** [comment]
Hello,

with torch==1.11.* I got the same problem with my NB gfx card:
~~~
miroi@MIRO:~/work/projects/open-collection/computer_science/pytorch/buildup_on_servers/wsl_notebookVictus/.python3 test.py
/home/miroi/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:145: UserWarning:
NVIDIA GeForce RTX 3050 Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3050 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
~~~
