### ISSUE TITLE
cudnn heuristics (cudnnGet*) returns algorithms that cannot be used

### ISSUE THREAD

**Issue by richard-vogl** [pytorch/pytorch#31336]
## 🐛 Bug

For certain input shapes (it seems not to be related to absolute size in bytes, see examples) Conv2D failes with CUDNN_STATUS_NOT_SUPPORTED

## To Reproduce

1. Code snipped:

Problem can be reproduced with:
```
import torch
x = torch.rand(1, 16, 70000, 100).to('cuda:0')
print('size of tensor: {:,} bytes'.format(x.element_size()*x.nelement()))
conv = torch.nn.Conv2d(in_channels=16, out_channels=32, kernel_size=(3,3), bias=False).to('cuda:0')
out = conv(x)
print(out.shape)
```
Note that the issue does not occur with slightly different shape and similar (slightly larger) sized tensor:

```
x2 = torch.rand(1, 16, 3000, 3000).to('cuda:0')
print('size of tensor: {:,} bytes'.format(x2.element_size()*x2.nelement()))
out2 = conv(x2)
print(out2.shape)
```

2. Google Colab Notebook:

https://colab.research.google.com/drive/1szd95jnY0rkcblIq8n9Zo0BpsWdFhrf3

Output of snipped (also compare Google Colab Notebook:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-872c4a39a547> in <module>()
      3 print('size of tensor: {:,} bytes'.format(x.element_size()*x.nelement()))
      4 conv = torch.nn.Conv2d(in_channels=16, out_channels=32, kernel_size=(3,3), bias=False).to('cuda:0')
----> 5 out = conv(x)
      6 print(out.shape)

2 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py in conv2d_forward(self, input, weight)
    340                             _pair(0), self.dilation, self.groups)
    341         return F.conv2d(input, weight, self.bias, self.stride,
--> 342                         self.padding, self.dilation, self.groups)
    343 
    344     def forward(self, input):

RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```

## Environment

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: TITAN RTX
GPU 5: TITAN RTX

Nvidia driver version: 430.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

GPU:
GeForce GTX 1080 Ti (rev a1)

CUDA:
NVIDIA-SMI 430.26 Driver Version: 430.26 CUDA Version: 10.2

cudnn:

torch.backends.cudnn.version()
7501

 - OS: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-58-generic x86_64)
 - How you installed PyTorch: pip
 - Python version: Python 3.6.8

## Additional context

Problem may be related to:
https://github.com/pytorch/pytorch/issues/4107
https://github.com/pytorch/pytorch/issues/11065

I tried to find out which cuDNN bug is referenced in 11065 but without success.

**Comment by richard-vogl** [comment]
as requested by @ngimel I created this new issue and tagged @ptrblck

**Comment by Enealor** [comment]
After some exploring, I can confirm that it is not inherently tied to memory size. The notebook you posted worked for me. In order to get it to break, I used `x = torch.rand(1, 16, 2*70000, 10).to('cuda:0')` and the convolution would fail. From here, I could change the shape using `x2 = x.view((1, 16, -1, 20))` and have the convolution work.

As an extra note, the shape of the convolution weight changed whether or not the convolution operation failed. I found in the same experiment that using kernel shapes `(3, 4)` or `(3, 2)` works while `(3, 3)` fails.

**Comment by ngimel** [comment]
Thank you @Enealor, the original notebook ran for me too, but your example failed. 
As is often the case, the workaround for this is to add
```
torch.backends.cudnn.benchmark = True
```
or 
```
torch.backends.cudnn.deterministic = True
```
This is yet another cudnn heuristics bug, and I can't really blame them - 140000 x 20 is not a common size, and heuristics is not trained for that. It still should not be picking an algo that won't even run. @ptrblck please work with cudnn on this.

**Comment by ptrblck** [comment]
Thanks for the code snippet @Enealor!

I cannot reproduce the error using the following code on Volta GPUs:
```python
import torch
x = torch.rand(1, 16, 2*70000, 10).to('cuda:0')
print('size of tensor: {:,} bytes'.format(x.element_size()*x.nelement()))
print('nelement: {}'.format(x.nelement()))
conv = torch.nn.Conv2d(in_channels=16, out_channels=32, kernel_size=(3,3), bias=False).to('cuda:0')
out = conv(x)
print(out.shape)
```

All runs succeed with the output:
```python
size of tensor: 89,600,000 bytes
nelement: 22400000
torch.Size([1, 32, 139998, 8])
```

Tested using cudnn `7.6.5.32`, `7.5.1.15`, and `7.5.1.2`, with CUDA10.2 on V100-SXM2 16GB GPUs.

However, it fails with cudnn `7.6.5.32` + CUDA10.2 on a P100 system, so it seems to be some issue for cudnn + specific GPUs.

I've created logs and will work with cudnn team on it.

**Comment by pbelevich** [comment]
Maybe related to #1664

**Comment by ngimel** [comment]
So this (or similar) issue has been reported at least twice recently, and many times over the years. @csarofeen @ptrblck does cudnn have a timeline for the fix? If not, it may make sense to do a workaround inside pytorch for a case when algo is selected via cudnnGet - if CUDNN_STATUS_NOT_SUPPORTED is returned by actual call, retry with default algo (the one that is selected with benchmark=False deterministic=True). It will make code exceedingly ugly though, so I'm conflicted about this.
