### ISSUE TITLE
torch.no_grad() context manager seems to leak memory

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#31497]
I have a lazy loop that is used to evaluate the model. This version doesn't use any noticeable memory (memory_allocated < 1Gb):
```python
def apply_model(data_loader, model):
    for dataset_name_, audio_path_, reference_, x, xlen, y, ylen in data_loader:
        x, xlen, y, ylen = x.to(args.device), xlen.to(args.device), y.to(args.device), ylen.to(args.device)
        with torch.no_grad():
            log_probs, output_lengths, loss = map(model(x, xlen, y = y, ylen = ylen).get, ['log_probs', 'output_lengths', 'loss'])
        yield log_probs
```

The context manager version:
```python
@torch.no_grad()
def apply_model(data_loader, model):
    print('memory_allocated', torch.cuda.memory_allocated() / 1e9, 'memory_cached', torch.cuda.memory_cached() / 1e9)
    for dataset_name_, audio_path_, reference_, x, xlen, y, ylen in data_loader:
        x, xlen, y, ylen = x.to(args.device), xlen.to(args.device), y.to(args.device), ylen.to(args.device)
        log_probs, output_lengths, loss = map(model(x, xlen, y = y, ylen = ylen).get, ['log_probs', 'output_lengths', 'loss'])
        yield log_probs
```

leads to OOM even on a 32Gb gpu:
```
...
memory_allocated 7.163547136 memory_cached 19.10505472
memory_allocated 7.164415488 memory_cached 19.10505472
memory_allocated 8.457690624 memory_cached 17.953718272
memory_allocated 8.454446592 memory_cached 22.206742528
memory_allocated 8.457297408 memory_cached 22.206742528
memory_allocated 9.7478528 memory_cached 22.013804544
memory_allocated 11.03991552 memory_cached 24.29550592

RuntimeError: CUDA out of memory. Tried to allocate 152.00 MiB (GPU 0; 31.72 GiB total capacity; 24.89 GiB already allocated; 6.12 MiB free; 30.70 GiB reserved in total by PyTorch)
```

A few things about this:
1) context manager seems to be broken
2) huge memory fragmentation: 11Gb of allocated memory, 24 Gb cached, 32Gb total, still OOM? it tried to allocate just 152Mb with 12Gb of free memory, fragmentation must be super-huge...
3) memory_allocated of 11Gb is not reported in OOM message
4) terminology discrepancy: torch.cuda.memory_cached seems to be equivalent to "already allocated" from OOM message. In presence of also existing torch.cuda.memory_allocated this is confusing. Probably the OOM message should also say cached. Otherwise, it's pretty easy to mix up allocated, cached, reserved.

this is on PyTorch nightly from a few days ago

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen @ngimel

**Comment by ngimel** [comment]
Thank you for reporting, we'll look into this.

**Comment by cpuhrsch** [comment]
Could you also share the model if you can? That'll make it easier for us to reproduce

**Comment by vadimkantorov** [comment]
I will try: I’ll save the model and all data inputs

**Comment by OhadRubin** [comment]
I am also experiencing memory leaking on this recent nightly, but my code doesn't use torch.no_grad, @vadimkantorov, did you try without torch.no_grad and it still leaked?

**Comment by ezyang** [comment]
What happens if you move the context manager "inside", e.g., so that you only `no_grad` the model as opposed to the data loader?

**Comment by albanD** [comment]
Also does adding a `gc.collect()` help? We might be creating a ref cycle?

**Comment by vadimkantorov** [comment]
> What happens if you move the context manager "inside", e.g., so that you only `no_grad` the model as opposed to the data loader?

I'm not understanding your proposal (because the "good" example above does just that: no_grad just the model inside the loop works well). Could you please rephrase it?

**Comment by albanD** [comment]
His point I think is that between the good and bad above. There are two differences. One uses the decorator and not the other. And one applies the no_grad to the dataloader and not the other.
So you should apply the no grad to the same thing. So that the only difference is the decorator. Either change the one with the context manager to wrap the whole function. Or use the decorator on a different function that only contains the inside of the loop.

**Comment by vadimkantorov** [comment]
@albanD got it now! about your original question: I'll try it as well when I get back to this investigation

**Comment by peterbell10** [comment]
The decorator `torch.no_grad` effectively creates a new function:
```python
def decorate_no_grad(*args, **kwargs):
    with torch.no_grad():
        return apply_model(*args, **kwargs)
``` 

Now since `apply_model` is a coroutine, it doesn't actually perform any computation when called. Instead it immediately returns a python generator object. i.e. the `torch.no_grad` context ends before any computation is done.

It may be possible to detect that `apply_model` is a coroutine and instead produce something like:
```python
def generator_no_grad(*args, **kwargs):
	gen = apply_model(*args, **kwargs)
	while True:
        with torch.no_grad():
            try:
                yield next(gen)
            except StopIteration:
                break
```

**Comment by ezyang** [comment]
Nice catch @peterbell10

**Comment by vadimkantorov** [comment]
That is indeed a great catch!

I would say the following things left: 
3. memory_allocated of 11Gb is not reported in OOM message
4. terminology discrepancy: torch.cuda.memory_cached seems to be equivalent to "already allocated" from OOM message. In presence of also existing torch.cuda.memory_allocated this is confusing. Probably the OOM message should also say cached. Otherwise, it's pretty easy to mix up allocated, cached, reserved.

**Comment by vadimkantorov** [comment]
@ezyang should I open separate issues about the points in my last comment? This issue was closed automatically

**Comment by albanD** [comment]
We had a PR recently that tried to improve this message: https://github.com/pytorch/pytorch/pull/13751  But if you think of a different way to reformulate it better, I'm sure you can open an issue and we can discuss it.

**Comment by ezyang** [comment]
Yeah, new issue would be great!

**Comment by ai21mtech13002** [comment]
@vadimkantorov how do we resolve this OOM issue?

**Comment by vadimkantorov** [comment]
in this issue the problem was in combination of no_grad decorator and generator. They don't go together very well
