### ISSUE TITLE
Computing dot product of columns sliced from large matrix causes illegal memory access in CUDA

### ISSUE THREAD

**Issue by HapeMask** [pytorch/pytorch#31708]
## 🐛 Bug

If you compute the dot product of a column sliced from a larger CUDA matrix with itself using `th.mm()`, it will produce an illegal memory access. If you instead compute `(v**2).sum()` (doesn't use CUBLAS), it will not produce the illegal memory access. Additionally, if `v` is allocated separately rather than being sliced, it will not produce the error.

This may be a duplicate of #17897 or just a similar underlying CUBLAS issue. This script can succeed if N*K > 2^31 - 1 (the commented `N = ...` line is bigger but still works) so I'm not sure.

## To Reproduce

```python
import torch as th                                                                                                                    
                                                                                                                                      
N = 16909322                                                                                                                          
#N = 16909321 # << this one won't fail                                                                                                
                                                                                                                                      
K = 127                                                                                                                               
                                                                                                                                      
print(f"Allocating {4*N*K / (1024**3)} GB ...")                                                                                       
U = th.zeros((N, K), device="cuda:0")                                                                                                 
print("Done.")                                                                                                                        
                                                                                                                                      
u = U[:, 0:1]                                                                                                                         
#u = th.zeros_like(u) # << adding this makes the following line succeed for either value of N                                         
                                                                                                                                      
v = th.mm(u.permute(1, 0), u)                                                                                                         
#v = (u**2).sum() # << this succeeds for either value of N                                                                            
                                                                                                                                      
# Just to force the error to propagate up to Python, otherwise it will silently                                                       
# fail and exit.                                                                                                                      
th.cuda.synchronize()
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.3 (also verified still present in latest master)
 - OS (e.g., Linux): Linux
 - Python version: 3.7
 - CUDA/cuDNN version: 9.0.176
 - GPU models and configuration: V100

**Comment by ngimel** [comment]
Once again, ltrace produces reasonably looking arguments to cublas call, so error is most likely in cublas. .ltrace.conf is in my gist is you need it. cc @csarofeen, @ptrblck 
```
(pytorch) ngimel@xxxxxxx:~/playground$ ltrace -f -e  'cublasSgemm_v2' python mm_transpose.py 
[pid 8269] --- Called exec() ---
[pid 8270] --- Called exec() ---
[pid 8270] +++ exited (status 0) +++
[pid 8269] --- SIGCHLD (Child exited) ---
[pid 8269] +++ exited (status 0) +++
[pid 8265] --- SIGCHLD (Child exited) ---
Allocating 8.000000916421413 GB ...
Done.
[pid 8265] libtorch_cuda.so->cublasSgemm_v2(0x55cc6926f560, 0, 1, 1, 1, 16909322, 1.000000, 0x7fb4c0000000, 127, 0x7fb4c0000000, 127, 0.000000, 0x7fb6c0200000, 1) = 0
THCudaCheck FAIL file=../torch/csrc/cuda/Module.cpp line=179 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "mm_transpose.py", line 20, in <module>
    th.cuda.synchronize()
  File "/private/home/ngimel/pytorch/torch/cuda/__init__.py", line 391, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at ../torch/csrc/cuda/Module.cpp:179
```

**Comment by ngimel** [comment]
Setting high priority label because it is a crash.

**Comment by ezyang** [comment]
@gchanan points out that in a similar case we warned when this case. @ngimel says we should get some input from NVIDIA about the surface area of this bug.

We should probably file an nvbug about this.

**Comment by ptrblck** [comment]
I can reproduce it with `1.5.0.dev20200113` and `cudatoolkit=10.1`, but cannot reproduce it in our PyTorch container build 19.12. 
I'll open a cublas bug with the code and cublas call and try to narrow down the issue.

**Comment by ptrblck** [comment]
This issue was fixed in the latest cublas release, which ships with CUDA10.2.
I'll narrow down the commit to get the scope of this issue for CUDA10.1.

**Comment by ptrblck** [comment]
As assumed the stride overflows using int32 inside cublas.
Cublas10.2 doesn't run into this error, as another internal path is used. 
However, the stride calculation was fixed recently by using int64 indexing to avoid this issue in the future.

@zasdfgbnm Could you please take a look at this issue and limit the input strides to <int32_max for cublas<10.2.2.89?

**Comment by zasdfgbnm** [comment]
@ptrblck Should we just providing a better error message ("strides larger than int32_max is not supported in CUDA<10.2.2.89")? Or should we dispatch to the fallback kernel in such case?

**Comment by ptrblck** [comment]
I'm OK with the former, as newer cublas versions fixed this issue.
CC @ezyang, @ngimel

**Comment by ezyang** [comment]
Either seems OK, just better than silently failing.

**Comment by zasdfgbnm** [comment]
Sure, I will add that check.

Besides, does it make sense to ship our release/nightly build using CUDA 10.2 instead of 10.1? This sounds like a "real fix".

**Comment by zasdfgbnm** [comment]
Initially, I thought it would be as simple as

```C++
if (condition) {
  AT_ERROR("The input tensor must blablabla");
}
cublasSgemm(...);
```

But when I try to implement the condition, I feel it is practically not possible to add a check before the cuBlas call to provide a better error message. As mentioned in https://github.com/pytorch/pytorch/issues/31708#issue-543955996:
> This script can succeed if N*K > 2^31 - 1 

The condition of the check really depends on how cuBlas heuristics internally selects kernels, and how does the problematic kernel internally use `int`. I don't see any easy and robust way to write the condition

**Comment by ngimel** [comment]
> , just better than silently failing.

It's not silently failing, it's quite loudly failing, and killing cuda context with it. So, based on the previous comment, alternatives here are
1) do an overly strict check, and throw a runtime error in cases where cublas might have succeeded. User can then attempt to somehow recover from runtime error
2) leave things as is, if the error is encountered, context is killed, there's no way to recover.

**Comment by zasdfgbnm** [comment]
Even for option 1, I am not sure how to do it. One thing in mind could be
```C++
if (stride[0] * shape[0] > 2^31 - 1) {
  error
}
```
but I am not sure if this would make users annoyed and if this filter out all failing cases(need to look deep into it). But this sounds somewhat reasonable because the largest address offset for this case would be <= 2**31 - 1.

**Comment by ezyang** [comment]
> It's not silently failing, it's quite loudly failing, and killing cuda context with it

Sorry, my bad, I got this bug mixed up with another one. Maybe we should just not do anything about it, in that case.
