### ISSUE TITLE
GPU is not recognized, GCP image: c1-deeplearning-common-cu100-20191226

### ISSUE THREAD

**Issue by Bill-Fujimoto** [pytorch/pytorch#31766]
## 🐛 Bug

Described on Stackoverflow:
https://stackoverflow.com/q/59557542/9447938

## To Reproduce

1.  Create Google GCP VM instance with this image: c1-deeplearning-common-cu100-20191226
2.  Install Anaconda, create new conda env for Torch, python 3.7.5
3.  Install Pytorch using  $ conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

```
import torch
torch.cuda.is_available()
False
```

## Expected behavior

 Expected GPU to be active
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Debian GNU/Linux 9.11 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: 10.0.130
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] intel-numpy==1.15.1
[pip3] numpy==1.15.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.2                py37_cu101    pytorch
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

The same image noted above works fine with Tensorflow-gpu, it recognizes the GPU and driver.

cc @ezyang @ngimel

**Comment by ezyang** [comment]
What happens if you

```
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
```

instead

**Comment by Bill-Fujimoto** [comment]
I was able to resolve the issue.  Not being a computer science guy, I figured that it could be an nvidia driver compatibility issue.  Since Pytorch was built using CUDA 10.1 driver, and the deep learning image had CUDA 10.0 installed, I created another VM instance but this time instead of using the public image noted earlier, I used the gcloud command line to specify deep learning with cu10.1 driver.  This made it all work as expected.  This is noted in the Stackoverflow post as well.
