### ISSUE TITLE
pytorch 1.4 bug in conv2D kernel size 1x1 RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input

### ISSUE THREAD

**Issue by One-sixth** [pytorch/pytorch#32395]
## 🐛 Bug

The bug only appeared in pytorch 1.4 cuda and conv2d with kernel size 1x1. 
pytorch 1.3 does not have this bug.

## To Reproduce

Will be raise CUDNN_STATUS_NOT_SUPPORTED
```
import torch
import torch.nn as nn

a = torch.zeros(2, 512, 512, 3).cuda().permute(0, 3, 1, 2)
conv1 = nn.Conv2d(3, 3, 1, 1, 0).cuda()
y = conv1(a)
y.sum().backward()
print(y.shape)

```

Use input with contiguous. No raise error.
```
import torch
import torch.nn as nn

a = torch.zeros(2, 512, 512, 3).cuda().permute(0, 3, 1, 2).contiguous()
conv1 = nn.Conv2d(3, 3, 1, 1, 0).cuda()
y = conv1(a)
y.sum().backward()
print(y.shape)

```

Use kernel size 3x3. No raise error.
```
import torch
import torch.nn as nn

a = torch.zeros(2, 512, 512, 3).cuda().permute(0, 3, 1, 2)
conv1 = nn.Conv2d(3, 3, 3, 1, 0).cuda()
y = conv1(a)
y.sum().backward()
print(y.shape)

```

## Environment

 - PyTorch Version (e.g., 1.0): 1.4
 - OS (e.g., Linux): windows10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): 
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1/7.6.5
 - GPU models and configuration: gtx1070
 - Any other relevant information:

## Additional context

cc @ngimel

**Comment by peterjc123** [comment]
cc @ngimel 
Anyway, you can try out adding
`torch.backends.cudnn.benchmark = True`
or
`torch.backends.cudnn.deterministic = True`
first.

**Comment by ngimel** [comment]
cc @jjsjann123, looks like nhwc-related. Likely fixed on master.

**Comment by jjsjann123** [comment]
I tried with cudnn 7.6.5 and doesn't repro on master. This is fixed :smile:

**Comment by yf225** [comment]
@jjsjann123 Do you mind checking if this is fixed on our nightly builds?

**Comment by yf225** [comment]
@One-sixth Do you mind checking whether this repros with our nightly builds?

**Comment by One-sixth** [comment]
@yf225 I just tested the night version and this problem has been fixed.

**Comment by peterjc123** [comment]
Maybe we need to backport the changes to v1.4.0.

**Comment by yf225** [comment]
@soumith Should we backport the fix to v1.4.0?

**Comment by soumith** [comment]
1.4.0 is frozen, if we plan for a 1.4.1, we should mark this as 1.4.1 backport-target. Right now, we have no plans for 1.4.1

**Comment by ngimel** [comment]
Closing, this issue is fixed.
