### ISSUE TITLE
CMake find_package returns corrupted library list 

### ISSUE THREAD

**Issue by thomashrabeBC** [pytorch/pytorch#32500]
## 🐛 Bug
Use PyTorch model in C++, compilation breaks when using the default route.
CMake `find_package(Torch REQUIRED)` 

returns corrupted `TORCH_LIBRARIES` list

```
torch
torch_library
/usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so
/usr/local/cuda/lib64/stubs/libcuda.so
/usr/local/cuda/lib64/libnvrtc.so
/usr/local/cuda/lib64/libnvToolsExt.so
/usr/local/cuda/lib64/libcudart.so
/usr/local/lib/python3.6/dist-packages/torch/lib/libc10_cuda.so
```

It should not contain absolute paths to the other libraries but rather the lib names.
The library paths should be added to the environment if necessary

## Solution

Instead of 

`target_link_libraries(MyTARGET PUBLIC ${TORCH_LIBRARIES})`

do

```
link_directories(/usr/local/lib/python3.6/dist-packages/torch/lib/)
link_directories(/usr/local/cuda/lib64/)
link_directories(/usr/local/cuda/lib64/stubs)

target_link_libraries(MyTARGET PUBLIC torch torch_library libc10.so libcuda.so libnvrtc.so libnvToolsExt.so libcudart.so libc10_cuda.so)
```

## To Reproduce

1. Create `CMakeLists.txt`
2.`find_package(Torch REQUIRED)`
3. `message("TORCH LIBS ${TORCH_LIBRARIES}")`

## Expected behavior

Returns linker errors as `c10` can not be found

```
/usr/local/lib/python3.6/dist-packages/torch/include/c10/core/Backend.h:107: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
SunlightNoiseClassifier/libSunlightNoiseClassifier.a(SunlightNoiseClassifier.cpp.o): In function `c10::backendToDeviceType(c10::Backend)':
```

## Environment

```
cmake version 3.5.1

python collect_env.py 
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: N/A
CUDA runtime version: 9.2.148
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.4.2
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @yf225

**Comment by ezyang** [comment]
Tentatively marking this as high priority as it seems to imply that the binary distribution of libtorch is unusable

**Comment by ezyang** [comment]
Did you get libtorch from the binary distribution or build it yourself?

**Comment by thomashrabeBC** [comment]
It's a binary that was installed with `pip` into `/usr/local/lib/python3.6/dist-packages/torch`

**Comment by thomashrabeBC** [comment]
It may very well be I was doing something wrong too. But, with the above adjustments I got it to work :)

**Comment by ezyang** [comment]
Thanks. Would you mind checking to see what happens if you use the libtorch packaging instead of the pip wheel?

**Comment by Baranowski** [comment]
Reproduced with `conda`. My `TORCH_LIBRARIES` also contains an absolute path:

```
MESSAGE("TORCH LIBS ${TORCH_LIBRARIES}")
```

```
TORCH LIBS torch;/home/wbaranowski/miniconda3/envs/pytorch-bin/lib/python3.8/site-packages/torch/lib/libc10.so;CPUINFO_LIBRARY-NOTFOUND;CLOG_LIBRARY-NOTFOUND
```

**Comment by Baranowski** [comment]
Reproduced also for build from the sources:

```
TORCH LIBS torch;/home/wbaranowski/miniconda3/envs/pytorch-cuda-dev/lib/python3.6/site-packages/torch/lib/libc10.so;/home/wbaranowski/miniconda3/envs/pytorch-cuda-dev/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so;CPUINFO_LIBRARY-NOTFOUND;CLOG_LIBRARY-NOTFOUND
```

**Comment by Baranowski** [comment]
@thomashrabeBC Could you please paste the entire verbose cmake and make log? I cannot reproduce your exact errors and the CMake documentation states that absolute paths to libraries are allowed in `target_link_libraries`: https://cmake.org/cmake/help/latest/command/target_link_libraries.html

However, I can see an issue that might be related to what you are experiencing.

To generate the logs you can:

1. remove all the build artefacts (for example with `git clean -xdf`)
2. `export VERBOSE=1`
3. build as you normally do, optionally redirecting the output to a file

**Comment by Baranowski** [comment]
I cannot reproduce this issue (i.e., cmake failing to link against c10 for projects depending on libtorch). @thomashrabeBC it would be very helpful if you could link to your project that depends on libtorch and doesn't build.

**Comment by thomashrabe** [comment]
Can't provide a link, IP protected. But seems Baranowski could reproduce this ^ .

**Comment by Baranowski** [comment]
@thomashrabe, I could reproduce TORCH_LIBRARIES containing absolute paths. I could not reproduce failure to link against c10. (I.e., I have built a project depending on PyTorch despite TORCH_LIBRARIES containing absolute paths.) I have also looked at the CMake docs, and it appears that absolute paths in TORCH_LIBRARIES are allowed.

Maybe you can provide a minimal reproducible example?

**Comment by rgommers** [comment]
@Baranowski I think absolute paths are a bug by definition for anything that ends up in a binary distribution, and you can reproduce it by building on one machine, and using that build on another machine with a different directory layout.

You said above you can reproduce `TORCH_LIBRARIES` having `/home/wbaranowski/...` in them - this is a clear bug, and it will fail _except_ if you do an in-place build and then test that same exact build.

I would just go ahead and replace it with relative paths.

**Comment by Baranowski** [comment]
@rgommers, those paths are not hardcoded in any files in the binary distribution. They are generated by CMake on the user's machine.

1. User runs cmake to build their own project depending on PyTorch
2. cmake processes `TorchConfig.cmake` (from PyTorch binary distribution) as one of the dependencies
3. while processing that file, cmake identifies absolute paths on the user's machine where PyTorch lives, puts them in the `TORCH_LIBRARIES` variable and communicates back to the upstream cmake (conceptually)

The absolute paths have to be somewhere in this cmake-to-cmake communication protocol (conceptually). The disagreement here is whether they might be put in `TORCH_LIBRARIES`, or whether they belong exclusively to other variables/properties.

**Comment by rgommers** [comment]
Thanks @Baranowski, you are correct. The two places that have absolute paths seem to be `TORCH_INSTALL_PREFIX` and `TORCH_LIBRARIES`, that does indeed look okay.

Maybe still worth to double check that you can't see the `c10` linking issue when installing with `pip` instead of `conda` - wouldn't be the first time those are different. If that works fine too, then may consider closing this issue (lack of reproducer, seems to all work).

**Comment by Baranowski** [comment]
Thanks for the suggestions, Ralf.

I have successfully built a project depending on libtorch with a `pip` installation of `torch`. I will close this issue in a week if I don't hear from @thomashrabe or other users.

**Comment by zhangwenhao666** [comment]
> ## 🐛 Bug
> Use PyTorch model in C++, compilation breaks when using the default route. CMake `find_package(Torch REQUIRED)`
> 
> returns corrupted `TORCH_LIBRARIES` list
> 
> ```
> torch
> torch_library
> /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so
> /usr/local/cuda/lib64/stubs/libcuda.so
> /usr/local/cuda/lib64/libnvrtc.so
> /usr/local/cuda/lib64/libnvToolsExt.so
> /usr/local/cuda/lib64/libcudart.so
> /usr/local/lib/python3.6/dist-packages/torch/lib/libc10_cuda.so
> ```
> 
> It should not contain absolute paths to the other libraries but rather the lib names. The library paths should be added to the environment if necessary
> 
> ## Solution
> Instead of
> 
> `target_link_libraries(MyTARGET PUBLIC ${TORCH_LIBRARIES})`
> 
> do
> 
> ```
> link_directories(/usr/local/lib/python3.6/dist-packages/torch/lib/)
> link_directories(/usr/local/cuda/lib64/)
> link_directories(/usr/local/cuda/lib64/stubs)
> 
> target_link_libraries(MyTARGET PUBLIC torch torch_library libc10.so libcuda.so libnvrtc.so libnvToolsExt.so libcudart.so libc10_cuda.so)
> ```
> 
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Create `CMakeLists.txt`
>    2.`find_package(Torch REQUIRED)`
> 2. `message("TORCH LIBS ${TORCH_LIBRARIES}")`
> 
> ## Expected behavior
> Returns linker errors as `c10` can not be found
> 
> ```
> /usr/local/lib/python3.6/dist-packages/torch/include/c10/core/Backend.h:107: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> SunlightNoiseClassifier/libSunlightNoiseClassifier.a(SunlightNoiseClassifier.cpp.o): In function `c10::backendToDeviceType(c10::Backend)':
> ```
> 
> ## Environment
> ```
> cmake version 3.5.1
> 
> python collect_env.py 
> Collecting environment information...
> PyTorch version: N/A
> Is debug build: N/A
> CUDA used to build PyTorch: N/A
> 
> OS: Ubuntu 16.04.3 LTS
> GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
> CMake version: version 3.5.1
> 
> Python version: 2.7
> Is CUDA available: N/A
> CUDA runtime version: 9.2.148
> GPU models and configuration: Could not collect
> Nvidia driver version: Could not collect
> cuDNN version: Could not collect
> 
> Versions of relevant libraries:
> [pip] msgpack-numpy==0.4.4.2
> [pip] numpy==1.16.4
> [pip] torch==1.2.0
> [pip] torchvision==0.4.0
> [conda] Could not collect
> ```
> 
> cc @ezyang @gchanan @zou3519 @yf225

thank you very much. IT help me sovle my problem
