### ISSUE TITLE
pytorch distributed timeout when running with number processes > 16

### ISSUE THREAD

**Issue by joe-redstone** [pytorch/pytorch#3615]
I am experimenting distributed package using a cluster with 10 computing nodes, each node has 64 cores and 256 GB RAM, no GPUs. Pytorch version is 0.2.0_3. The code runs fine when using only 16 processes or less on a single machine. But if I use 32 processes on a single machine or multiple machines (say, 4 or 6) with 16 or more processes on each machine,  it often errors out with messages like "Read timeout" with gloo backend or "Connection reset by peer" with TCP backend. After some digging into the Pytorch source code, I suspect it is likely because of the communications between processes taking too long when there are too many processes. Currently both DataChannelTCP and DataChannelGloo have a constructor that takes a "timeout" parameter. However the python interface does not expose this interface currently, instead it uses the constructor with default timeout set to 30s. I wonder if you can give user the option to set this. Sorry I can't post my code here but some simple code with resnet should be able to reproduce the problem.

**Comment by gmyofustc** [comment]
Hi, @joe-redstone  I have the same question when I tried to train models on 4 nodes with 16 gpus. This error happens when i calll
`dist.all_reduce(tensor, OP)`
most of the time, the disributed program will goes well. However, when the communication between nodes is not fast enough, say, the all_reduce cost time long than 30seconds, it will give me a "Read Timeout Error"

Do you have any solutions for this?

**Comment by apaszke** [comment]
@gmyofustc did you try using MPI? We can try to expose the timeout argument to Python

**Comment by alsrgv** [comment]
@apaszke, I have a similar problem, too. I'm running the code from the master branch that I built 2 days ago.

I got Gloo working with 4 nodes with 4 GPUs each, but it fails on 32 nodes.  I tried MPI backend with `DistributedDataParallel` and found that it doesn't converge very well.

I scaled back experiment to 4 nodes with 4 GPUs each and observed that MPI backend with `DistributedDataParallel` indeed converges much worse with the same batch size & lr.  On the chart below, gray line is Gloo and green line is MPI. 

<img width="714" alt="screen shot 2017-12-27 at 4 03 34 pm" src="https://user-images.githubusercontent.com/16640218/34396423-934bfc4e-eb1f-11e7-8fca-8bd3a9ed8b33.png">

I was finally able to run large-scale experiment with doing a simple gradient averaging instead of using `DistributedDataParallel` functionality:

```
def average_gradients(model):
    size = float(dist.get_world_size())
    for param in model.parameters():
        dist.all_reduce(param.grad.data, op=dist.reduce_op.SUM)
        param.grad.data /= size
```

I did two more runs - one with `DataParallel` and one worker per machine (blue line), and another is with one worker per GPU (orange line).

<img width="707" alt="screen shot 2017-12-27 at 4 21 27 pm" src="https://user-images.githubusercontent.com/16640218/34396602-059783b6-eb22-11e7-9ba1-079bcbbe5a04.png">

Unfortunately, it's slow.  Any idea how to make `DistributedDataParallel` work correctly with MPI?

**Comment by apaszke** [comment]
@alsrgv Thanks a lot for the detailed writeup. That's very surprising for me, we'll need to look into the discrepancy. Changing the way you do communication shouldn't have such a dramatic effect on the training. BTW what kind of errors do you get form gloo (is it still the timeout?) and when does that happen (perhaps right before/after validation?)?

**Comment by apaszke** [comment]
I've created an issue to track the MPI problems: #4406

**Comment by alsrgv** [comment]
@apaszke, I was getting "Read timeout" errors.  I think they were caused by longer GPU initialization on certain workers.  I was able to partially mitigate this by doing a bit of warmup with Keras + Horovod training, and then switching to PyTorch.  Having a larger default timeout (and/or having it configurable) would be helpful.

**Comment by apaszke** [comment]
It is configurable, it's just not exposed in Python 😕

**Comment by apaszke** [comment]
@alsrgv If you want to give a larger timeout a try you can add [`context->setTimeout(...)`](https://github.com/facebookincubator/gloo/blob/8b630a7d4d31948b999edaf773aff4135d758451/gloo/context.h#L37) right before [this line](https://github.com/pytorch/pytorch/blob/master/torch/lib/THD/base/data_channels/GlooCache.hpp#L119).

**Comment by gmyofustc** [comment]
@apaszke  I am using gloo backend. 
@alsrgv Recently, I found when I change the init_process_group from tcp to shared file system, the distributed training will be much stable
```python 
dist.init_process_group(init_method='file:///mnt/nfs/sharedfile', world_size=4,
                        group_name='mygroup')
```
But when using the shared file system, the distributed engine does not always launch sucessfully. I have to submit the job lots of times.

And for distributed training, you can try [bmuf algorithm](https://docs.microsoft.com/en-us/cognitive-toolkit/multiple-gpus-and-machines#6-block-momentum-sgd). I tried this, and found 16 gpus coverages as well as 1gpu's result.

**Comment by alsrgv** [comment]
@apaszke, sorry for delayed response.  I've added `setTimeout()`, like follows:
```c++
  // NOTE: this function needs to be thread safe
  std::shared_ptr<context_type> createContext(
    const DataChannelGloo::Group& group,
    const std::string& prefix
  ) {
    auto context = std::make_shared<context_type>(
        group.mustGetGroupRank(_rank), group.size());
    prefix_store_type prefix_store(prefix, *group._store);
    context->setTimeout(std::chrono::minutes(15));
    context->connectFullMesh(prefix_store, _device);
    return context;
  }
```

Seems that it helped a bit, but I will hold conclusions for a little while since there is another failure mode described below.

I have added distributed validation to [ImageNet training example], like this:
```python
    metrics = torch.FloatTensor([losses.avg, top1.avg, top5.avg])
    if args.distributed:
        dist.all_reduce(metrics)
        metrics /= dist.get_world_size()
```

Unfortunately, I get errors running that operation:
```
[1,4]<stderr>:Traceback (most recent call last):
[1,4]<stderr>:  File "torch_imagenet_gloo_dv_smooth_warmup.py", line 376, in <module>
[1,4]<stderr>:    main()
[1,4]<stderr>:  File "torch_imagenet_gloo_dv_smooth_warmup.py", line 180, in main
[1,4]<stderr>:    prec1 = validate(val_loader, model, criterion, epoch)
[1,4]<stderr>:  File "torch_imagenet_gloo_dv_smooth_warmup.py", line 298, in validate
[1,4]<stderr>:    dist.all_reduce(metrics)
[1,4]<stderr>:  File "/usr/local/lib/python2.7/dist-packages/torch/distributed/__init__.py", line 344, in all_reduce
[1,4]<stderr>:    return torch._C._dist_all_reduce(tensor, op, group)
[1,4]<stderr>:RuntimeError: [/mnt/share/asergeev/torch_imagenet/pytorch/torch/lib/gloo/gloo/transport/tcp/pair.cc:696] Socket closed [xx.xx.xx.xx]:1157
```

I tried to add MPI barrier before that operation, but it did not help.

I have tried the same code with NCCL2 transport and it works flawlessly and initializes much faster.

**Comment by apaszke** [comment]
That's weird, I've never seen this one. Did any of your processes crash?

**Comment by ejoebstl** [comment]
@apaszke I'm currently running into the same issue. Would you mind to share how you properly initialized the  distributed module with the NCCL backend, as a temporary workaround?

**Comment by pengjiang030** [comment]
I have met the same problem. It seems distributed training with gradient averaging is exactly the same as minibatch on a single node; however, the algorithm converges slower than single node training. I looked at the code in DistributedDataParallel, it actually synchronizes the parameters at the beginning of forward propagation. 

In Source code for torch.nn.parallel.distributed:
` def forward(self, *inputs, **kwargs):
        self.need_reduction = True
        inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
        self._sync_params()
        if len(self.device_ids) == 1:
            return self.module(*inputs[0], **kwargs[0])
        outputs = self.parallel_apply(self._module_copies[:len(inputs)], inputs, kwargs)
        return self.gather(outputs, self.output_device)`

The gradient averaging is registered: 
`for p in self.module.parameters():
            if not p.requires_grad:
                continue

            def allreduce_hook(*unused):
                Variable._execution_engine.queue_callback(reduction_fn_nccl)

            p.register_hook(allreduce_hook)`

and executed later at the end of backward propagation. 

I wonder if it is some internal state on different nodes that is not communicated with gradient averaging causes the slow down of convergence. Is the parameter averaging at the beginning of each iteration really necessary?
