### ISSUE TITLE
NCCL Connection Failed Using PyTorch Distributed with Error ProcessGroupNCCL.cpp:290, unhandled system error

### ISSUE THREAD

**Issue by MonicaGu** [pytorch/pytorch#36294]
## ❓ Questions and Help
I am trying to send a PyTorch tensor from one machine to another with torch.distributed. The dist.init_process_group function works properly. However, there is a connection failure in the dist.broadcast function. Here is my code on node 0:
```
import torch
from torch import distributed as dist
import numpy as np
import os

master_addr = '47.xxx.xxx.xx'
master_port = 10000
world_size = 2
rank = 0
backend = 'nccl'

os.environ['MASTER_ADDR'] = master_addr
os.environ['MASTER_PORT'] = str(master_port)
os.environ['WORLD_SIZE'] = str(world_size)
os.environ['RANK'] = str(rank)
dist.init_process_group(backend, init_method='tcp://47.xxx.xxx.xx:10000', timeout=datetime.timedelta(0, 10), rank=rank, world_size=world_size)
print("Finished initializing process group; backend: %s, rank: %d, "
"world_size: %d" % (backend, rank, world_size))

a = torch.from_numpy(np.random.rand(3, 3)).cuda()
dist.broadcast(tensor=a, src=0)
```
Here is my code on node 1:
```
import torch
from torch import distributed as dist
import numpy as np
import os

master_addr = '47.xxx.xxx.xx'
master_port = 10000
world_size = 2
rank = 1
backend = 'nccl'

os.environ['MASTER_ADDR'] = master_addr
os.environ['MASTER_PORT'] = str(master_port)
os.environ['WORLD_SIZE'] = str(world_size)
os.environ['RANK'] = str(rank)
dist.init_process_group(backend, init_method='tcp://47.xxx.xxx.xx:10000', timeout=datetime.timedelta(0, 10), rank=rank, world_size=world_size)
print("Finished initializing process group; backend: %s, rank: %d, "
"world_size: %d" % (backend, rank, world_size))

a = torch.zeros((3,3)).cuda()
dist.broadcast(tensor=a, src=0)
```
I set NCCL_DEBUG=INFO before running the code. Here is the information I got on Node 1:
```
iZbp11ufz31riqnssil53cZ:13530:13530 [0] NCCL INFO Bootstrap : Using [0]eth0:192.168.0.181<0>
iZbp11ufz31riqnssil53cZ:13530:13530 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
iZbp11ufz31riqnssil53cZ:13530:13530 [0] NCCL INFO NET/IB : No device found.
iZbp11ufz31riqnssil53cZ:13530:13530 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.0.181<0>
iZbp11ufz31riqnssil53cZ:13530:13553 [0] NCCL INFO Setting affinity for GPU 0 to ffff
iZbp11ufz31riqnssil53cZ:13530:13553 [0] NCCL INFO Call to connect returned Connection timed out, retrying
iZbp11ufz31riqnssil53cZ:13530:13553 [0] NCCL INFO Call to connect returned Connection timed out, retrying

iZbp11ufz31riqnssil53cZ:13530:13553 [0] include/socket.h:395 NCCL WARN Connect to 192.168.0.143<59811> failed : Connection timed out
iZbp11ufz31riqnssil53cZ:13530:13553 [0] NCCL INFO bootstrap.cc:100 -> 2
iZbp11ufz31riqnssil53cZ:13530:13553 [0] NCCL INFO bootstrap.cc:326 -> 2
iZbp11ufz31riqnssil53cZ:13530:13553 [0] NCCL INFO init.cc:695 -> 2
iZbp11ufz31riqnssil53cZ:13530:13553 [0] NCCL INFO init.cc:951 -> 2
iZbp11ufz31riqnssil53cZ:13530:13553 [0] NCCL INFO misc/group.cc:69 -> 2 [Async thread]
Traceback (most recent call last):
  File "test_dist_1.py", line 25, in <module>
    dist.broadcast(tensor=a, src=0)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 806, in broadcast
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: NCCL error in: /tmp/pip-req-build-58y_cjjl/torch/lib/c10d/ProcessGroupNCCL.cpp:290, unhandled system error
```
And Node 0 seems to stuck in function dist.broadcast and stops outputting more information. And the cpu utilization of this process is 99.9%:
```
iZuf6cu11ru7evq9ybagdjZ:13530:13530 [0] NCCL INFO Bootstrap : Using [0]eth0:192.168.0.143<0>
iZuf6cu11ru7evq9ybagdjZ:13530:13530 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
iZuf6cu11ru7evq9ybagdjZ:13530:13530 [0] NCCL INFO NET/IB : No device found.
iZuf6cu11ru7evq9ybagdjZ:13530:13530 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.0.143<0>
iZuf6cu11ru7evq9ybagdjZ:13530:13553 [0] NCCL INFO Setting affinity for GPU 0 to ffff
```
Can anyone help me with this? How can I send the tensor `a` from node 0 to node 1? I would really appreciate any help!

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by osalpekar** [comment]
Are you trying to send the tensor between 2 CPUs or GPUs? If they are CPUs, you should use the Gloo backend, not NCCL - more information here: https://pytorch.org/docs/stable/distributed.html#which-backend-to-use.

**Comment by MonicaGu** [comment]
> Are you trying to send the tensor between 2 CPUs or 2 GPUs? If they are CPUs, you should use the Gloo backend, not NCCL - more information here: https://pytorch.org/docs/stable/distributed.html#which-backend-to-use.

I am trying to send them between 2 GPUs. So I used NCCL backend.
 Besides, I also have a problem sending them between CPUs with Gloo backend. When I use Gloo backend, the rank 1 tries to connect with a strange address `192.168.0.143:51078`, which seems to be a LAN address with a random port.

**Comment by pritamdamania87** [comment]
@MonicaGu Is eth0 the right interface to reach the `47.xxx.xxx.xx` address? If not, you might have to configure NCCL/GLOO to use the right interface: https://pytorch.org/docs/stable/distributed.html#choosing-the-network-interface-to-use.

**Comment by MonicaGu** [comment]
Thanks for your help! I found that this problem is caused by the network connection problem. I will close this issue.

**Comment by Teoge** [comment]
> Thanks for your help! I found that this problem is caused by the network connection problem. I will close this issue.

I have exactly the same problem with that random port number. Can you tell me how you solved it? Thanks!

**Comment by gudiandian** [comment]
> > Thanks for your help! I found that this problem is caused by the network connection problem. I will close this issue.
> 
> I have exactly the same problem with that random port number. Can you tell me how you solved it? Thanks!

I found that the two servers that I used were not under the same VPC. So I used other servers and it worked. Maybe you can consider using other servers.
