### ISSUE TITLE
Pytorch AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by sharmalakshay93** [pytorch/pytorch#3717]
I am trying to run code from [this repo](https://github.com/eladhoffer/captionGen). I have disabled cuda by changing lines 39/40 in [main.py](https://github.com/eladhoffer/captionGen/blob/master/main.py) from

```Python
parser.add_argument('--type', default='torch.cuda.FloatTensor', help='type of tensor - e.g torch.cuda.HalfTensor')
```

to

```Python
parser.add_argument('--type', default='torch.FloatTensor', help='type of tensor - e.g torch.HalfTensor')
```

However, I keep receiving the aforementioned AssertionError. Below is the trace:

```Python
Traceback (most recent call last):
  File "main.py", line 190, in <module>
    main()
  File "main.py", line 178, in main
    model, train_data, training=True, optimizer=optimizer)
  File "main.py", line 135, in forward
    for i, (imgs, (captions, lengths)) in enumerate(data):
  File "/Users/lakshay/anaconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/Users/lakshay/anaconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/Users/lakshay/anaconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 62, in _pin_memory_loop
    batch = pin_memory_batch(batch)
  File "/Users/lakshay/anaconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 123, in pin_memory_batch
    return [pin_memory_batch(sample) for sample in batch]
  File "/Users/lakshay/anaconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 123, in <listcomp>
    return [pin_memory_batch(sample) for sample in batch]
  File "/Users/lakshay/anaconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 117, in pin_memory_batch
    return batch.pin_memory()
  File "/Users/lakshay/anaconda/lib/python3.6/site-packages/torch/tensor.py", line 82, in pin_memory
    return type(self)().set_(storage.pin_memory()).view_as(self)
  File "/Users/lakshay/anaconda/lib/python3.6/site-packages/torch/storage.py", line 83, in pin_memory
    allocator = torch.cuda._host_allocator()
  File "/Users/lakshay/anaconda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 220, in _host_allocator
    _lazy_init()
  File "/Users/lakshay/anaconda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 84, in _lazy_init
    _check_driver()
  File "/Users/lakshay/anaconda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 51, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

Unable to figure this out. Please help? Thanks!

**Comment by soumith** [comment]
you are running this on OSX. The OSX binary of PyTorch does not come with GPU support.

The code you linked to still has some GPU stuff remaining (as you see from the stack-trace.

Change these two lines to get_iterator:
https://github.com/eladhoffer/captionGen/blob/48552694775ef11f5fa68c100584f40d98e4b690/main.py#L96

`get_iterator(..., pin_memory=False)`

**Comment by sharmalakshay93** [comment]
Thank you, @soumith!

**Comment by Kdc23** [comment]
i'm trying to run python prepro_feats.py from this repo [https://github.com/xiadingZ/video-caption.pytorch] 
The error I'm getting: 
/home/k23/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Traceback (most recent call last):
  File "prepro_feats.py", line 126, in <module>
    model = model.cuda()
  File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 152, in _apply
    param.data = fn(param.data)
  File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/koeldc23/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 453, in _lazy_new
    _lazy_init()
  File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 152, in _lazy_init
    _check_driver()
  File "/home/k23/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 74, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

How do I compile Torch with CUDA? I've followed the following steps to install PyTorch
$ git clone https://github.com/pytorch/pytorch
$ export CMAKE_PREFIX_PATH=/home/alexis/anaconda2
$ conda install numpy mkl setuptools cmake gcc cffi
$ conda install -c soumith magma-cuda80
$ pip install -r requirements.txt
$ python setup.py install

Unable to figure this out. Kindly help. Thanks!

**Comment by Kdc23** [comment]
i'm trying to run python prepro_feats.py from this repo [https://github.com/xiadingZ/video-caption.pytorch]
The error I'm getting:
/home/k/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
"please use transforms.Resize instead.")
Traceback (most recent call last):
File "prepro_feats.py", line 126, in
model = model.cuda()
File "/home/k/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
return self._apply(lambda t: t.cuda(device))
File "/home/k/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
module._apply(fn)
File "/home/k/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
module._apply(fn)
File "/home/k/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
module._apply(fn)
File "/home/k/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 152, in _apply
param.data = fn(param.data)
File "/home/k/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in
return self._apply(lambda t: t.cuda(device))
File "/home/k/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 69, in cuda
return new_type(self.size()).copy(self, async)
File "/home/k/anaconda3/lib/python3.6/site-packages/torch/cuda/init.py", line 453, in _lazy_new
_lazy_init()
File "/home/k/anaconda3/lib/python3.6/site-packages/torch/cuda/init.py", line 152, in _lazy_init
_check_driver()
File "/home/k/anaconda3/lib/python3.6/site-packages/torch/cuda/init.py", line 74, in _check_driver
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

How do I compile Torch with CUDA? I've followed the following steps to install PyTorch
$ git clone https://github.com/pytorch/pytorch
$ export CMAKE_PREFIX_PATH=/home/alexis/anaconda2
$ conda install numpy mkl setuptools cmake gcc cffi
$ conda install -c soumith magma-cuda80
$ pip install -r requirements.txt
$ python setup.py install

Unable to figure this out. Kindly help. Thanks!

**Comment by apaszke** [comment]
Try setting `CUDA_HOME` to where your CUDA toolkit is installed (usually it's `/usr/local/cuda`, but apparently not in your case). Then, make sure the logs show `-- Building with CUDA` or something similar

**Comment by Kdc23** [comment]
Is there any instructions on how to build from source for CUDA 8.0? If not can you tell how to do in a few steps when one doesn't have root access? That would be useful.

This is my bashrc profile:

# export SYSTEMD_PAGER=

export PATH=/home/k/anaconda3/bin:$PATH
export CMAKE_PREFIX_PATH=/home/koeldc23/anaconda3
# User specific aliases and functions

# CUDA cuda and CuDNN
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-8.0/lib64"
export PATH="/usr/local/cuda-8.0/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
export PATH="/usr/local/cuda/bin:$PATH"

**Comment by Kdc23** [comment]
Thanks. Is there any instructions on how to build from source for CUDA 8.0? If not can you tell how to do in a few steps when one doesn't have root access? That would be useful.
This is my bashrc profile.
# export SYSTEMD_PAGER=

export PATH=/home/k/anaconda3/bin:$PATH
export CMAKE_PREFIX_PATH=/home/k/anaconda3
# User specific aliases and functions

# CUDA cuda and CuDNN
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-8.0/lib64"
export PATH="/usr/local/cuda-8.0/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
export PATH="/usr/local/cuda/bin:$PATH"

**Comment by apaszke** [comment]
Can you post a full build log somewhere (e.g. to a GitHub gist)?

**Comment by Kdc23** [comment]
Can you kindly have a look at this-

https://gist.github.com/Kdc23/3080218ab97a99da8f93c02b35ced6c9/revisions

**Comment by madieraRRC** [comment]
Accept:appliction/vnd.machine-man-preview+jsn
Accept:application/vnd.github.valkyrie-preview+jsn
![Uploading 2016-03-05_01-42-33.jpg…]()

**Comment by apaszke** [comment]
I meant a build log (from `python setup.py install`)

**Comment by Blues5** [comment]
Kindly refer to this- https://gist.github.com/Blues5/44bf19b02b6d0ec01454bb4b7b53fd4a/f5f413807a3196a735e5a11d92470d38e4dcee44

Many thanks!

**Comment by soumith** [comment]
@Blues5 it looks like CUDA is not installed maybe?

what is output of:

```
ls /usr/local/cuda-8.0/lib64
```

and try install via:

```
CUDA_HOME="/usr/local/cuda-8.0" python setup.py install
```

**Comment by Blues5** [comment]
I guess I ignored the most important step, i.e, to be on the node while doing all these steps.

It's working fine now. Thanks a bunch! :)

**Comment by ayockishaya** [comment]
i am trying to execute the code in the link below
https://github.com/ayockishaya/np-hard-deep-reinforcement-learning/blob/master/Neural%20Combinatorial%20Optimization.ipynb

 but i am experiencing an error " Torch not compiled with CUDA enabled ".
i am using windows 10.
please kindly assist.
Thanks

**Comment by Shijihao** [comment]
I met the same problem because I chose pytorch package with no cuda when I install. I fix it to choose cuda 9.0

**Comment by abdallahserag** [comment]
hello guys  I try to run this code from GitHub 
https://github.com/zllrunning/Deep-Steganography
on my Mac  but I have error 
main.py:17: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(m.weight.data, a=0, mode='fan_in')
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    hide_net.cuda()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 305, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 202, in _apply
    module._apply(fn)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 202, in _apply
    module._apply(fn)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in _apply
    param_applied = fn(param)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 305, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/cuda/__init__.py", line 192, in _lazy_init
    _check_driver()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/cuda/__init__.py", line 95, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
.
please any one help

**Comment by JonasZerbib** [comment]
hi,
i try to run my code on macOS 10.15.1  , and it displays the follow error:
AssertionError: Torch not compiled with CUDA enabled.
someone can help me please

`Traceback (most recent call last):
  File "/Users/Jonas/Documents/ML_ex_3_neural_network/Lior/ex4.py", line 160, in <module>
    main()
  File "/Users/Jonas/Documents/ML_ex_3_neural_network/Lior/ex4.py", line 153, in main
    model.validation_model(valid_loader)
  File "/Users/Jonas/Documents/ML_ex_3_neural_network/Lior/ex4.py", line 54, in validation_model
    examples, labels = examples.to("cuda"), labels.to("cuda")
  File "/Users/Jonas/.conda/envs/hw5/lib/python3.7/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/Users/Jonas/.conda/envs/hw5/lib/python3.7/site-packages/torch/cuda/__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled`

**Comment by XinyingZheng** [comment]
> you are running this on OSX. The OSX binary of PyTorch does not come with GPU support.
> 
> The code you linked to still has some GPU stuff remaining (as you see from the stack-trace.
> 
> Change these two lines to get_iterator:
> https://github.com/eladhoffer/captionGen/blob/48552694775ef11f5fa68c100584f40d98e4b690/main.py#L96
> 
> `get_iterator(..., pin_memory=False)`

in my code, I have changed pin_memory=True to pin_memory=False,but it still have this error,Torch not compiled with CUDA enabled.

**Comment by morawi** [comment]
I am facing the same problem. Strangely, if I python at the terminal there is no problem. However, I get the error when I use Spyder.
