### ISSUE TITLE
Google Colab error

### ISSUE THREAD

**Issue by charlyromero** [pytorch/pytorch#37287]
I am running Demucs in Google Colab, and when I execute a command I get the following error

AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

the version of the card is as follows:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

How can i fix this?

**Comment by margiki** [comment]
I get the same error... My current solution involves downgrading to PyTorch 1.4

**Comment by charlyromero** [comment]
Thank you very much, thanks to what you told me I was able to solve it

**Comment by izdeby** [comment]
Please, use the [forum](https://discuss.pytorch.org/) for the questions.
