### ISSUE TITLE
torch.remainder gives a remainder larger than the divisor

### ISSUE THREAD

**Issue by KeAWang** [pytorch/pytorch#37743]
## 🐛 Bug

`torch.remainder` is wrong on some inputs. It's accurate when computing in float64, but the remainder can be larger than the divisor in float32. What's worse is that the wrong result is **different** on CPU vs GPU

## To Reproduce

```python
import torch
import math
import numpy as np

n = 1e9

torch.remainder(torch.tensor([n], device="cpu", dtype=torch.float32), math.pi)  # will return tensor([-64.]) which is larger than the divisor math.pi

torch.remainder(torch.tensor([n], device="cuda", dtype=torch.float32), math.pi)  # will return tensor([-33.5333], device='cuda:0') which is also larger than the divisor math.pi
```

## Expected behavior
```python
np.remainder(np.array([n], dtype=np.float32), math.pi)  # will return array([1.024195], dtype=float32)
```

Some other observations:
- The results of `torch.fmod` matches the results of `np.fmod` in both GPU and CPU in fp32 and fp64
- Since by default `x % y` will call `torch.remainder(x, y)` if `x` and `y` are PyTorch Tensors, wrong behavior in `torch.remainder` also results in wrong behavior of `%`.

## Environment

```
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: EndeavourOS Linux
GCC version: (GCC) 8.4.0
CMake version: version 3.17.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 440.82
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] pytorch-lightning==0.7.5
[pip] torch==1.5.0
[pip] torchcontrib==0.0.2
[pip] torchdiffeq==0.0.1
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas                      2.15                        mkl    conda-forge
[conda] cudatoolkit               10.2.89              hfd86e86_0  
[conda] libblas                   3.8.0                    15_mkl    conda-forge
[conda] libcblas                  3.8.0                    15_mkl    conda-forge
[conda] liblapack                 3.8.0                    15_mkl    conda-forge
[conda] liblapacke                3.8.0                    15_mkl    conda-forge
[conda] mkl                       2020.0                      166    conda-forge
[conda] numpy                     1.18.1           py37h8960a57_1    conda-forge
[conda] pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] pytorch-lightning         0.7.5                     dev_0    <develop>
[conda] torchcontrib              0.0.2                    pypi_0    pypi
[conda] torchdiffeq               0.0.1                    pypi_0    pypi
[conda] torchvision               0.6.0                py37_cu102    pytorch
```

cc @ezyang @gchanan @zou3519

**Comment by xwang233** [comment]
Thanks for the report!

It turns out that this problem is due to numerical precision issue when you subtract two larger numbers with only small difference, such as 100000000002 - 100000000001. Even the numpy single precision result of 1.024195 is incorrect (from c function `fmodf`). The accurate double precision result is 0.577396.

The current `torch.remainder` impl for both cpu and gpu have this problem, e.g. https://github.com/pytorch/pytorch/blob/253943d5a7bb90a420e4d94366101915823c7929/aten/src/ATen/native/cuda/BinaryArithmeticKernel.cu#L80-L85

I also checked the `torch.fmod` impl which are correct for both cpu and gpu. You can temporarily use `torch.fmod` as a substitute for `torch.remainder`. I will provide a fix to `torch.remainder` soon, and let it use the native c/cuda function of `fmod`.

**Comment by xwang233** [comment]
Also see #24861

**Comment by ngimel** [comment]
Setting high priority as it is silent wrong answer.

**Comment by xwang233** [comment]
The GPU part of this should be fixed. You can test that using the nightly build. Waiting for someone to also fix the CPU part.
