### ISSUE TITLE
torch.cdist [Cuda out of memory Tried to allocate 108GB of memory]

### ISSUE THREAD

**Issue by dvirginz** [pytorch/pytorch#37754]
I'm trying to evaluate `torch.cdist` on `A.shape=[4,6890,1000],B.shape=[4,8690,1000]`.
While the tensors **are** big, scikit learn cdist evaluates the above, and I also don't have 100GB of ram:).
One important thing to mention is that `torch.cdist(A,B)` crashes only at **backprop** phase, and still, 100GB sounds quite extensive. 
Can someone share relatively reasonable tensor sizes for the operation?

**Comment by ngimel** [comment]
Please provide full reproducer for your issue, as well as your environment collected by the script below: https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
The following script
```
a=torch.randn(4,6890,1000, device="cuda", requires_grad=True)
b=torch.randn(4,8690,1000, device="cuda", requires_grad=True)
c=torch.cdist(a,b)
c.sum().backward()
```
passes on the GPU with 16 GB of memory on pytorch 1.5, so you are on an old pytorch version probably.

**Comment by dvirginz** [comment]
I'm closing it as after building my env from scratch it now works. (I was already on torch 1.5, so I can't directly point on the problem but ...)
