### ISSUE TITLE
libtorch1.5 CUDA10.1 Windows10_x64  GPU failed

### ISSUE THREAD

**Issue by jjqcat** [pytorch/pytorch#38194]
my env is windows10 x64 platform, GTX 1660ti and NVIDIA driver is 445.87 , and download libtorch 1.5 for c++, call torch::cuda::is_available() return  false, but the same version of pytorch works well and it return true

**Comment by peterjc123** [comment]
Please copy all the DLLs to the directory of your executable.

**Comment by jjqcat** [comment]
I have solved this configure problem, and done following cmake, because my old project links libtorch1.4, much different from new version. please close this issue. thanks
