### ISSUE TITLE
Failed to link torch_library using cmake

### ISSUE THREAD

**Issue by vsuryamurthy** [pytorch/pytorch#38239]
## 🐛 Bug

When I compile a simple package (**a** for instance) using cmake, the exported ${TORCH_LIBRARIES}$ is as follows,
```
torch;torch_library;/usr/lib/libc10.so;/opt/cuda/lib/stubs/libcuda.so;/opt/cuda/lib/libnvrtc.so;/opt/cuda/lib/libnvToolsExt.so;/opt/cuda/lib64/libcudart.so;/usr/lib/libc10_cuda.so
```
Package **a** compiles successfully even if the linker fails to link **torch_library**. 

The actual problem arises when I have another package (**b**), dependent on the already created package **a**. When I build, it fails with error

```
CMake Error at /home/vsury/dev/ros/pytorch-example/devel_isolated/a/share/a/cmake/aConfig.cmake:150 (message):
  Project 'b' tried to find library '-Wl,--no-as-needed,$<TARGET_FILE:torch>
  -Wl,--as-needed'.  The library is neither a target nor built/installed
  properly.  Did you compile project 'a'? Did you find_package() it before
  the subdirectory containing its code is included?
```

The reason has to do with **torch_library** because there is no library such as **libtorch_library.so**.

Looking further, it seems like that ${TORCH_LIBRARIES} is linked to ${Caffe2_MAIN_LIBS},

https://github.com/pytorch/pytorch/blob/master/cmake/TorchConfig.cmake.in#L41

and  ${Caffe2_MAIN_LIBS} is linked to **torch_library**,

https://github.com/pytorch/pytorch/blob/master/cmake/Caffe2Config.cmake.in#L121

I do not understand the need for **torch_library** and removing it from $TORCH_LIBRARIES$ fixes the entire problem.

## To Reproduce

1. Create a package **a** with any script with torch functionalities (basically CMakeLists should contain find_package(Torch REQUIRED) and build target with torch libraries.
2. Create another package **b** and make it depend on **a**.
3. Compile package b to get the error.

## Expected behavior

Successful build

## Environment

Please copy and paste the output from our

 - PyTorch Version (e.g., 1.0): 1.5.0
 - OS (e.g., Linux): Archlinux
 - How you installed PyTorch (`conda`, `pip`, source): pacman -S
 - Build command you used (if compiling from source): cmake ..
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by glaringlee** [comment]
@vsuryamurthy 
Can you take a look at our installing instruction here?
https://pytorch.org/cppdocs/installing.html
There is a section which has the guide on what need to be added into CMakeLists and how to compile, and let me know if this works for you. thx

**Comment by vsuryamurthy** [comment]
@glaringlee Following the link, I get

```
torch;torch_library;/home/vsury/pytorch/libtorch/lib/libc10.so
``` 
when I print ${TORCH_LIBRARIES}. 

I have the same problem of failing to link torch_library as there is no **libtorch_library.so** in libtorch/lib.

**Comment by glaringlee** [comment]
@malfet Can you pls advise on this? Thanks.

**Comment by malfet** [comment]
@vsuryamurthy `torch_library` is interface defined in `Caffe2Targets.cmake`
But it looks like there are no reason why TORCH_LIBRARIES need to depend on Caffe2_MAIN_LIBS.
Let me figure out the best way to patch it.

**Comment by vsuryamurthy** [comment]
@malfet Precisely my point. 

I have fixed it by removing ${Caffe2_MAIN_LIBS} in https://github.com/pytorch/pytorch/blob/master/cmake/TorchConfig.cmake.in#L41 (which means removing if-else too). This works for me but I am not sure if this is the way to go about it.

**Comment by vsuryamurthy** [comment]
@malfet any update?
