### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by GlassyWing** [pytorch/pytorch#38618]
## 🐛 Bug

Recently, I plan to implement Kalman filter with pytorch. I tried to obtain the batch processing capability through torch. However, when I call "torch.cholesky (covariance)" and run it on the GPU, I randomly encounter an incomprehensible error. " CUDA error: an illegal memory access was encountered ", but it does not happen when it is processed through the loop. At the same time, what is even more surprising is that this will not have any problems on window10.

## To Reproduce

If i combine the covariances like this, the error will happen randomly.
```
    means = []
    covariances = []
    for row, track_idx in enumerate(track_indices):
        track = tracks[track_idx]
        means.append(track.mean)
        covariances.append(track.covariance)
    means = torch.cat(means, dim=0)
    covariances = torch.cat(covariances, dim=0)
    gating_distance = kf.gating_distance(means, covariances, measurements, only_position)
```

What ` kf.gating_distance` does is call `torch.cholesky(covariance)`:

```
    def gating_distance(self, mean, covariance, measurements, only_position=False):
        mean, covariance = self.project(mean, covariance)
        # (n, 4, 4)
        cholesky_factor = torch.cholesky(covariance)
        d = - mean + measurements  # (n, m, 4)
        z = torch.triangular_solve(d.permute(0, 2, 1), cholesky_factor, upper=False)[0]
        squared_maha = torch.sum(z ** 2, dim=1)  # (n, m)
        return squared_maha

     def project(self, mean, covariance):
        """Project state distribution to measurement space.
        std = torch.tensor([[
            self._std_weight_position,
            self._std_weight_position,
            1e-1,
            self._std_weight_position]], device=mean.device)

        std = mean[:, 3:4] * std  # (*, 4)
        std[:, 2] = 1e-1  # (*, 4)

        # (*, 4, 4)
        innovation_cov = torch.diag_embed(torch.pow(std, 2))

        update_mat_t = self._update_mat.t()

        # (4, 8) dot (*, 8)
        mean = torch.mm(mean, update_mat_t)  # (*, 4)

        # (*, 4, 4)
        covariance = torch.matmul(torch.matmul(covariance.permute(0, 2, 1), update_mat_t).permute(0, 2, 1),
                                  update_mat_t)
        return mean, covariance + innovation_cov
```

The complete code is here [kalman_filter.py](https://github.com/GlassyWing/sort_torch/blob/master/deep_sort/sort/kalman_filter.py)

## Expected behavior

There should be no problem。

## Environment

The runtime is from docker image: pytorch/pytorch:1.5-cuda10.1-cudnn7-runtime

Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: TITAN Xp
Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.1           py37h4f9e942_0
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] pytorch                   1.5.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.6.0                py37_cu101    pytorch

cc @ezyang @gchanan @zou3519 @ngimel @vincentqb @vishwakftw @SsnL @jianyuh

**Comment by GlassyWing** [comment]
Before things are resolved, this is an alternative solution: first combine on the CPU, and then calculate on the GPU. In this way, instead of looping, you can maximize parallelization:

```
# Combine tensors on cpu
    means = []
    covariances = []
    for row, track_idx in enumerate(track_indices):
        track = tracks[track_idx]
        means.append(track.mean.cpu())
        covariances.append(track.covariance.cpu())

    # Then copy to gpu
    means = torch.cat(means, dim=0).to(measurements.device)
    covariances = torch.cat(covariances, dim=0).to(measurements.device)

    # The calculation takes place on the GPU 
    gating_distance = kf.gating_distance(means, covariances, measurements, only_position)
    cost_matrix[gating_distance > gating_threshold] = gated_cost
    return cost_matrix
```
At the same time, it also indirectly shows that when using the GPU, strange things happen to the combination operation

**Comment by agolynski** [comment]
@GlassyWing is it a crash?

**Comment by GlassyWing** [comment]
> @GlassyWing is it a crash?

Yes, it is. I have been stuck on this issue for a long time, now I have to run it on cpu (no problem with cpu) although CPU usage is high

**Comment by xwang233** [comment]
I tried your "kalman_filter.py" script on today's master commit 1.6.0a0+21ba3b4, with small changes like this 
```python
if __name__ == '__main__':
    device = 'cuda'

    kf = KalmanFilter(device)
    mean, covariance = kf.initiate(torch.tensor([10, 15, 0.5, 10], device=device))
    mean, covariance = kf.predict(mean, covariance)
    mean, covariance = kf.update(mean, covariance, torch.tensor([12, 20, 0.6, 11], device=device))

    mean_2, covariance_2 = kf.initiate(torch.tensor([12, 13, 0.7, 5], device=device))
    mean_2, covariance_2 = kf.predict(mean_2, covariance_2)
    mean_2, covariance_2 = kf.update(mean_2, covariance_2, torch.tensor([13, 14, 0.7, 8], device=device))

    squared_maha = kf.gating_distance(torch.cat((mean, mean_2), dim=0),
                                      torch.cat((covariance, covariance_2), dim=0),
                                      torch.tensor([[12, 20, 0.6, 11],
                                                    [20, 16, 0.4, 18]], device=device))
    print(squared_maha)
```
The script finished well with no exception and gave same output as CPU. Can you try with nightly build (and maybe latest driver, cuda, cudnn, etc) to verify that?

My environment (MAGMA 2.5.3)
```
PyTorch version: 1.6.0a0+21ba3b4
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Fedora 31 (Workstation Edition)
GCC version: (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
CMake version: version 3.15.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2070 SUPER
Nvidia driver version: 440.31
cuDNN version: /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.6.0a0+21ba3b4
[pip3] torchvision==0.7.0a0+f9ef235
[conda] Could not collect
```

**Comment by GlassyWing** [comment]
> I tried your "kalman_filter.py" script on today's master commit 1.6.0a0+21ba3b4, with small changes like this
> 
> ```python
> if __name__ == '__main__':
>     device = 'cuda'
> 
>     kf = KalmanFilter(device)
>     mean, covariance = kf.initiate(torch.tensor([10, 15, 0.5, 10], device=device))
>     mean, covariance = kf.predict(mean, covariance)
>     mean, covariance = kf.update(mean, covariance, torch.tensor([12, 20, 0.6, 11], device=device))
> 
>     mean_2, covariance_2 = kf.initiate(torch.tensor([12, 13, 0.7, 5], device=device))
>     mean_2, covariance_2 = kf.predict(mean_2, covariance_2)
>     mean_2, covariance_2 = kf.update(mean_2, covariance_2, torch.tensor([13, 14, 0.7, 8], device=device))
> 
>     squared_maha = kf.gating_distance(torch.cat((mean, mean_2), dim=0),
>                                       torch.cat((covariance, covariance_2), dim=0),
>                                       torch.tensor([[12, 20, 0.6, 11],
>                                                     [20, 16, 0.4, 18]], device=device))
>     print(squared_maha)
> ```
> 
> The script finished well with no exception and gave same output as CPU. Can you try with nightly build (and maybe latest driver, cuda, cudnn, etc) to verify that?
> 
> My environment (MAGMA 2.5.3)
> 
> ```
> PyTorch version: 1.6.0a0+21ba3b4
> Is debug build: No
> CUDA used to build PyTorch: 10.2
> 
> OS: Fedora 31 (Workstation Edition)
> GCC version: (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
> CMake version: version 3.15.3
> 
> Python version: 3.7
> Is CUDA available: Yes
> CUDA runtime version: 10.2.89
> GPU models and configuration: GPU 0: GeForce RTX 2070 SUPER
> Nvidia driver version: 440.31
> cuDNN version: /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7
> 
> Versions of relevant libraries:
> [pip3] numpy==1.17.3
> [pip3] torch==1.6.0a0+21ba3b4
> [pip3] torchvision==0.7.0a0+f9ef235
> [conda] Could not collect
> ```

In fact I have bypassed cholesky in some alternative way:
https://github.com/GlassyWing/sort_torch/blob/3d4c809dee6ad35b2f7d5a4b75f9e30b07722441/deep_sort/sort/kalman_filter.py#L245

If you need to test, you need to cancel cholesky's comment and comment out the replacement method. 

In previous attempts, I found that there will be no errors if run alone, but if run in multiple threads or used with other models, it may throw an exception. I have not found a reproducible pattern, but under multi-threading, each thread has a Kalman filter, and it is more likely to cause errors.

**Comment by kurtamohler** [comment]
Hey @GlassyWing , how many times on average would someone need to run your `kalman_filter.py` script to see the error? I tried uncommenting/commenting the spots you pointed out, and I changed everything to use `device='cuda'`, but I didn't see the error after running the script about 200 times in a loop.

I'm using one of today's commits (79450edad32bde56b8fb6f5ce95b8cebc8254fe7). My CUDA version is 10.1.243. I'm using nvidia driver 440.33.01 with a Titan RTX TU102.

**Comment by GlassyWing** [comment]
> Hey @GlassyWing , how many times on average would someone need to run your `kalman_filter.py` script to see the error? I tried uncommenting/commenting the spots you pointed out, and I changed everything to use `device='cuda'`, but I didn't see the error after running the script about 200 times in a loop.
> 
> I'm using one of today's commits ([79450ed](https://github.com/pytorch/pytorch/commit/79450edad32bde56b8fb6f5ce95b8cebc8254fe7)). My CUDA version is 10.1.243. I'm using nvidia driver 440.33.01 with a Titan RTX TU102.

I retested it and updated the driver, then the error disappeared magically. It seems that this is a driver problem, I replaced the previous version 418.56 with 418.113, the graphics card is TiTan XP

**Comment by ezyang** [comment]
OK, feel free to reopen if it happens again!

**Comment by KhoomeiK** [comment]
I believe I'm experiencing the same issue on Colab, and have opened a [bug report with Google Colab as well](https://github.com/googlecolab/colabtools/issues/1493). Below is the minimal script that triggers the issue. CUDA crashes without throwing an error, and then becomes unusable until runtime is restarted.

https://colab.research.google.com/drive/1TxAkgCUaFSfy7Cja7aJCie6ziAhmO1RG#scrollTo=IaDqVUmdcpIK

**Comment by ngimel** [comment]
@KhoomeiK this is a different issue, it's a duplicate of #42282. It's a bug that it results in invalid memory access and context invalidation, but since in your example you are trying to operat on cuda  and cpu tensors, we should be throwing RuntimeError error with a better error message.
