### ISSUE TITLE
cuda out of memory , but there is enough memory 

### ISSUE THREAD

**Issue by gogoIsComing** [pytorch/pytorch#40002]
i am training binary classification model on gpu using pytorch, and i get cuda memory error , but i have enough free memory as the message say: 

error : 
`RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 6.00 GiB total capacity; 693.78 MiB already allocated; 3.91 GiB free; 18.22 MiB cached)`

it is trying to allocate 50 MB but i have 3.91 GB free, so what is the problem ???

note:
gpu: gtx 1060 6 GB 
torch: 1.2.0

cc @ngimel

**Comment by Marceliny** [comment]
It might be because of mini-batch of data does not fit on to GPU memory. Just decrease the batch size

**Comment by Aceticia** [comment]
@Marceliny Hi, what does free memory mean in this case? Just from the error message, it looks like there are enough space to fit the current allocation, unless it means something else? 
I'm having the same issue, but just want to be really sure it's not a problem in pytorch or CUDA before I decrease the batch size.

**Comment by gogoIsComing** [comment]
@Aceticia  in my case it turns out that the main memory (RAM) is full.
