### ISSUE TITLE
(Cuda 11.0) RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by NavpreetDevpuri** [pytorch/pytorch#40430]
## 🐛 Bug

I installed pytorch by `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch` On windows 10 64-bit
I have CUDA 11.0 
`nvidia-smi`
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 446.14       Driver Version: 446.14       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 710     WDDM  | 00000000:01:00.0 N/A |                  N/A |
| 40%   47C    P8    N/A /  N/A |    337MiB /  2048MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU                  PID   Type   Process name                  GPU Memory |
|                                                                  Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

## To Reproduce

```python
import torch
device = torch.device("cuda")
torch.rand(10).to(device)
```
I am getting 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\torch\tensor.py", line 162, in __repr__
    return torch._tensor_str._str(self)
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\torch\_tensor_str.py", line 315, in _str
    tensor_str = _tensor_str(self, indent)
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\torch\_tensor_str.py", line 213, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\torch\_tensor_str.py", line 88, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

## Expected behavior
Resolve this error.

## Environment

`python collect_env.py`
```
[pip] numpy==1.18.1
[pip] numpydoc==0.9.2
[pip] torch==1.5.1
[pip] torchvision==0.6.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              h74a9793_1
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.0.15           py37h14836fe_0
[conda] mkl_random                1.1.0            py37h675688f_0
[conda] numpy                     1.18.1           py37h93ca92e_0
[conda] numpy-base                1.18.1           py37hc3f5095_1
[conda] numpydoc                  0.9.2                      py_0
[conda] pytorch                   1.5.1           py3.7_cuda102_cudnn7_0    pytorch
[conda] torchvision               0.6.1                py37_cu102    pytorch
## Additional context

<!-- Add any other context about the problem here. -->

**Comment by peterjc123** [comment]
Your card is too old and is not supported anymore. Please build from source.

**Comment by NavpreetDevpuri** [comment]
is there any easier way to correct this ? i am new with pytorch and `build from source` seems difficult and i think i may unable to install it currectly.

**Comment by peterjc123** [comment]
You can use PyTorch <= 1.3.0 I guess.

**Comment by NavpreetDevpuri** [comment]
What wrong ?
```
C:\Users\Devpuri>conda install pytorch=1.3.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch=1.3.0
```

**Comment by NavpreetDevpuri** [comment]
And when i try `pip install -Iv pytorch==1.3.0`
```
Traceback (most recent call last):
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\pip\_internal\legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\pip\_internal\legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\pip\_internal\legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\pip\_internal\req\req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\pip\_internal\index\package_finder.py", line 927, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for pytorch==1.3.0
```

**Comment by NavpreetDevpuri** [comment]
after trying as mesntioned [here](https://pytorch.org/get-started/previous-versions/)
```
conda remove --force pytorch
conda install pytorch==1.2.0 torchvision==0.4.0 -c pytorch
```
Now its installing

**Comment by NavpreetDevpuri** [comment]
@peterjc123 thanku.
Now its working.

**Comment by NavpreetDevpuri** [comment]
Now this error
```
File "C:\Users\Devpuri\anaconda3\lib\site-packages\torchvision\transforms\functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (C:\Users\Devpuri\anaconda3\lib\site-packages\PIL\__init__.py)
```

**Comment by NavpreetDevpuri** [comment]
after trying as menstioned [here](https://discuss.pytorch.org/t/cannot-import-name-pillow-version-from-pil/66096)
Pillow's error is fixed 
```
conda remove --force pillow
conda install pillow=6.2.1
```

But

Now an other error 
```
  File "C:\Users\Devpuri\Downloads\pix2pixHD-master\pix2pixHD-master\models\base_model.py", line 58, in load_network
    raise('Generator must exist!')
TypeError: exceptions must derive from BaseException
```

**Comment by NavpreetDevpuri** [comment]
Fixed this But now another error 

```
    raise ValueError('Generator must exist!')
ValueError: Generator must exist!
```
