### ISSUE TITLE
build error: use of enum ‘cudaGraphExecUpdateResult’ without previous declaration

### ISSUE THREAD

**Issue by lawpdas** [pytorch/pytorch#40909]
I try to build pytorch from source with cuda10.2 . 
But there are some error about cuda:

```
[4213/4940] Building CXX object caffe2...e_gpu.dir/python/pybind_state_gpu.cc.o
FAILED: caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state_gpu.cc.o 
/usr/bin/c++  -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DIDEEP_USE_MKL -DMAGMA_V2 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -DUSE_EXTERNAL_MZCRC -D_FILE_OFFSET_BITS=64 -Dcaffe2_pybind11_state_gpu_EXPORTS -Iaten/src -I../aten/src -I. -I../ -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -I../third_party/foxi -Ithird_party/foxi -Icaffe2/aten/src/TH -I../aten/src/TH -Icaffe2/aten/src -I../aten/../third_party/catch/single_include -I../aten/src/ATen/.. -Icaffe2/aten/src/ATen -I../third_party/miniz-2.0.8 -I../caffe2/core/nomnigraph/include -I../caffe2/../torch/csrc/api -I../caffe2/../torch/csrc/api/include -I../c10/.. -Ithird_party/ideep/mkl-dnn/include -I../third_party/ideep/mkl-dnn/src/../include -I../c10/cuda/../.. -isystem third_party/gloo -isystem ../cmake/../third_party/gloo -isystem ../cmake/../third_party/googletest/googlemock/include -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party/protobuf/src -isystem /home/space/Public/anaconda3/envs/pynightly/include -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../third_party/XNNPACK/include -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /home/space/Public/anaconda3/envs/pynightly/include/python3.7m -isystem /home/space/Public/anaconda3/envs/pynightly/lib/python3.7/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem ../cmake/../third_party/cub -isystem /usr/local/cuda/include -isystem ../third_party/ideep/mkl-dnn/include -isystem ../third_party/ideep/include -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -fPIC   -fvisibility=hidden -DCAFFE2_USE_GLOO -DCUDA_HAS_FP16=1 -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -pthread -std=gnu++14 -MD -MT caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state_gpu.cc.o -MF caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state_gpu.cc.o.d -o caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state_gpu.cc.o -c ../caffe2/python/pybind_state_gpu.cc
In file included from /usr/local/cuda-10.2/include/channel_descriptor.h:61:0,
                 from /usr/local/cuda-10.2/include/cuda_runtime.h:95,
                 from /usr/local/cuda/include/cudnn.h:64,
                 from ../caffe2/core/common_cudnn.h:16,
                 from ../caffe2/python/pybind_state_gpu.cc:14:
/usr/local/cuda-10.2/include/cuda_runtime_api.h:9534:145: error: use of enum ‘cudaGraphExecUpdateResult’ without previous declaration
 extern __host__ cudaError_t CUDARTAPI cudaGraphExecUpdate(cudaGraphExec_t hGraphExec, cudaGraph_t hGraph, cudaGraphNode_t *hErrorNode_out, enum cudaGraphExecUpdateResult *updateResult_out);
                                                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
[4218/4940] Building CXX object caffe2...et_gpu_test.dir/core/net_gpu_test.cc.o
../caffe2/core/net_gpu_test.cc: In function ‘void caffe2::checkChainingAndRun(const char*, const ExecutionChains&)’:
../caffe2/core/net_gpu_test.cc:79:30: warning: ‘void caffe2::NetDef::set_num_workers(google::protobuf::int32)’ is deprecated [-Wdeprecated-declarations]
     net_def.set_num_workers(4);
                              ^
In file included from ../caffe2/proto/caffe2_pb.h:4:0,
                 from ../caffe2/core/context_base.h:18,
                 from ../caffe2/core/context.h:11,
                 from ../caffe2/core/storage.h:14,
                 from ../caffe2/core/tensor.h:5,
                 from ../caffe2/core/blob.h:14,
                 from ../caffe2/core/net.h:14,
                 from ../caffe2/core/net_gpu_test.cc:3:
./caffe2/proto/caffe2.pb.h:9726:13: note: declared here
 inline void NetDef::set_num_workers(::PROTOBUF_NAMESPACE_ID::int32 value) {
             ^~~~~~
[4228/4940] Building CXX object caffe2...state_gpu.dir/python/pybind_state.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 734, in <module>
    build_deps()
  File "setup.py", line 318, in build_deps
    cmake=cmake)
  File "/home/space/Public/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/space/Public/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/home/space/Public/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/space/Public/anaconda3/envs/pynightly/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '16']' returned non-zero exit status 1.

```

cc @malfet

**Comment by pbelevich** [comment]
Obviously we need more information like: what environment/tools do you use, how did you get pytorch source code, what commands did you run, etc.

**Comment by lawpdas** [comment]
Thanks for your reply. I got pytorch source by `git clone` and ran these commands within a conda environment.
```
conda install -c pytorch magma-cuda102
git submodule sync
git submodule update --init --recursive
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
python setup.py install
```
ubuntu18.04
cuda10.2.89
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
python3.7

packages in environment
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2020.6.24                     0    defaults
certifi                   2020.6.20                py37_0    defaults
cffi                      1.14.0           py37he30daa8_1    defaults
cmake                     3.14.0               h52cb24c_0    defaults
cudatoolkit               10.2.89              hfd86e86_1    defaults
expat                     2.2.9                he6710b0_2    defaults
intel-openmp              2020.1                      217    defaults
krb5                      1.18.2               h173b8e3_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libcurl                   7.71.0               h20c2e04_0    defaults
libedit                   3.1.20191231         h7b6447c_0    defaults
libffi                    3.3                  he6710b0_1    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libssh2                   1.9.0                h1ba5d50_1    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
magma-cuda102             2.5.2                         1    pytorch
mkl                       2020.1                      217    defaults
mkl-include               2020.1                      217    defaults
mkl-service               2.3.0            py37he904b0f_0    defaults
mkl_fft                   1.1.0            py37h23d657b_0    defaults
mkl_random                1.1.1            py37h0573a6f_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
ninja                     1.9.0            py37hfd86e86_0    defaults
numpy                     1.18.5           py37ha1c710e_0    defaults
numpy-base                1.18.5           py37hde5b4d6_0    defaults
openssl                   1.1.1g               h7b6447c_0    defaults
pip                       20.1.1                   py37_1    defaults
pycparser                 2.20                       py_0    defaults
python                    3.7.7                hcff3b4d_5    defaults
pyyaml                    5.3.1            py37h7b6447c_1    defaults
readline                  8.0                  h7b6447c_0    defaults
rhash                     1.3.8                h1ba5d50_0    defaults
setuptools                47.3.1                   py37_0    defaults
six                       1.15.0                     py_0    defaults
sqlite                    3.32.3               h62c20be_0    defaults
tk                        8.6.10               hbc83047_0    defaults
wheel                     0.34.2                   py37_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```

**Comment by malfet** [comment]
@lawpdas this sounds like a broken CUDA installation. That `enum` should be declared in `/usr/loca/cuda-10.2/include/driver_types.h` Can you please check, that it is there and also that you don't have `driver_types.h` header in your `/usr/include/` folder (which would indicate, that you have previous version of cuda installed via DEB packages)
Also, please check that `/usr/local/cuda` is a symlink to `/usr/local/cuda-10.2`

**Comment by lawpdas** [comment]
I can find `driver_types.h` in `cuda-10.2/include`, and `enum cudaGraphExecUpdateResult` is declared in this file.  Because there are three version of cuda in my computer, and all of them are installed via runfile, I do not create any symlink in `/usr/local/` and never have the header in `/usr/include/`.  I just select a specific version in the conda environment by using `anaconda3/envs/pynightly/etc/conda/activate.d/env_vars.sh`:
```
# cuda
ORIGINAL_PATH=$PATH
ORIGINAL_LD_LIBRARY_PATH=$LD_LIBRARY_PATH

export CUDA_HOME=/usr/local/cuda-10.2
export PATH=/usr/local/cuda-10.2/bin:/usr/local/cuda-10.2:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.2/lib64
export CPATH=/usr/local/cuda-10.2/include:$CPATH

```

...
Now, I select cuda10.0 and can build pytorch successfully.
p.s. GPU: 2080ti, driver version: 440.100

**Comment by malfet** [comment]
@lawpdas as you can see from the log you've provided, it tries to include cudnn.h from `/usr/local/cuda/include/cudnn.h`
> ```
>                  from /usr/local/cuda/include/cudnn.h:64,
> ```
Does `/usr/local/cuda/` symlink points to `cuda-10.2` or some other version of cuda? If later, that that would probably is causing the build failure.

**Comment by lawpdas** [comment]
Yes! You are right! I have solved this problem by setting `USE_CUDNN=0`. Because I did not install cudnn in cuda10.2, it uses the cudnn installed in another version of cuda.
