### ISSUE TITLE
Need help to solve this error CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by narpat22** [pytorch/pytorch#41010]
**I am implement simple feedforward network using MNIST data (digit recognotion)**
- [Discussion Forum](https://discuss.pytorch.org/)

```input_size = 784 # 28 * 28
hidden_size = 500
num_classes = 10

class NeuralNet(nn.Module):
    def __init__(self , input_size , hidden_size , num_classes):
        super(NeuralNet , self).__init__()
        self.l1 = nn.Linear(input_size , hidden_size)
        self.relu = nn.ReLU()
        self.l2 = nn.Linear(hidden_size , num_classes )
        self.softmax  = nn.Softmax()
    def forward(self , x):
        out = self.l1(x)
        out = self.relu(out)
        out = self.l2(out)
        out = self.softmax(out)
        return out

model = NeuralNet(input_size , hidden_size , num_classes).to(device)  # --> error generates here
```

**here is the full error** 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
 in 
----> 1 model = NeuralNet(input_size , hidden_size , num_classes).to(device)

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in to(self, *args, **kwargs)
    441             return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
    442 
--> 443         return self._apply(convert)
    444 
    445     def register_backward_hook(self, hook):

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in _apply(self, fn)
    201     def _apply(self, fn):
    202         for module in self.children():
--> 203             module._apply(fn)
    204 
    205         def compute_should_use_set_data(tensor, tensor_applied):

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in _apply(self, fn)
    223                 # `with torch.no_grad():`
    224                 with torch.no_grad():
--> 225                     param_applied = fn(param)
    226                 should_use_set_data = compute_should_use_set_data(param, param_applied)
    227                 if should_use_set_data:

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in convert(t)
    439             if convert_to_format is not None and t.dim() == 4:
    440                 return t.to(device, dtype if t.is_floating_point() else None, non_blocking, memory_format=convert_to_format)
--> 441             return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
    442 
    443         return self._apply(convert)

RuntimeError: CUDA error: device-side assert triggered
```
**I have tried using this **
```
CUDA_LAUNCH_BLOCKING = 1 
```

**Comment by peterjc123** [comment]
What is the error if you remove the `.to(device)` call in that line?

**Comment by narpat22** [comment]
It will work fine. 
As it will work on Cpu and am trying to work on GPU

**Comment by narpat22** [comment]
i found the solution

**Comment by kooruhana** [comment]
I am having the same issue. How did you solve it? Thank you.

**Comment by narpat22** [comment]
> I am having the same issue. How did you solve it? Thank you.

If you want to run on gpu you can simple use .cuda() instead of .to(device)

```  model = ClassName(params =  . . . ).cuda() ```
