### ISSUE TITLE
RuntimeError: ProcessGroupNCCL does not support recv (torch-nightly)

### ISSUE THREAD

**Issue by jeffreysijuntan** [pytorch/pytorch#42332]
## 🐛 Bug

pytorch recently upgraded the nccl version to 2.7.3 https://github.com/pytorch/pytorch/pull/40622, which has support for point-to-point communication such as send and recv. However, I encounter `RuntimeError: ProcessGroupNCCL does not support recv` when using a nccl backend for send and recv. `torch.cuda.nccl.version()` returns `273`.

## Stack trace

```
  File "/private/home/sijun/projects/CrypTen/crypten/mpc/provider/ttp_provider.py", line 75, in generate_binary_triple
    c = TTPClient.get().ttp_request("binary", device, size0, size1)
  File "/private/home/sijun/projects/CrypTen/crypten/mpc/provider/ttp_provider.py", line 203, in ttp_request
    comm.get().recv(result, ttp_rank, self.comm_group)
  File "/private/home/sijun/projects/CrypTen/crypten/communicator/communicator.py", line 223, in logging_wrapper
    return func(self, *args, **kwargs)
  File "/private/home/sijun/projects/CrypTen/crypten/communicator/distributed_communicator.py", line 123, in recv
    dist.recv(result.data, src=src, group=group)
  File "/private/home/sijun/.conda/envs/torch_preview/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 751, in recv
    pg.recv([tensor], group_src_rank, tag).wait()
RuntimeError: ProcessGroupNCCL does not support recv
```

## Environment

 - PyTorch Version (e.g., 1.0): torch-nightly (1.7.0)
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): 
 - Python version: 3.8.3
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ngimel** [comment]
While nccl itself supports point to point communications, this functionality has not been added to pytorch yet. @mrshenli, @pritamdamania87 what are the plans here?
There are PRs to implement all2all functionality using nccl's p2p https://github.com/pytorch/pytorch/pulls?q=is%3Aopen+is%3Apr+author%3Asrinivas212+nccl, but as far as I can see they don't expose p2p directly.

**Comment by mrshenli** [comment]
Yep, we don't support send/recv in `ProcessGroupNCCL` yet, but this is on our roadmap. cc @mingzhe09088

**Comment by awan-10** [comment]
@mrshenli, @mingzhe09088 -- I have a similar question about alltoall itself. Is exposing all_to_all with NCCL backend also on the roadmap? Can I try this out with a nightly version? I tried send/recv with nightly and they worked for me but when I try alltoall with that same build of PyTorch, it says `RuntimeError: ProcessGroupNCCL does not support alltoall`

**Comment by JonathanCMitchell** [comment]
Has this been fixed for a latest torch version? Trying to do send/recv for NCCL backend in PyTorch

**Comment by LukeLIN-web** [comment]
still don't support send/recv in.   torch 1.7.1+cu102
