### ISSUE TITLE
ModuleNotFoundError 

### ISSUE THREAD

**Issue by Srikanth421** [pytorch/pytorch#43753]
I installed PyTorch for GPU from conda. But when I try to check if it worked by import torch, it doesn't recognize the module. Earlier when I tried PyTorch for CPU, I didn't face issue. Let me know what details or commands you need me to run?

**Comment by Srikanth421** [comment]
I uninstalled pytorch-cpu and error went away! But now torch.cuda.is_available() is False?

**Comment by peterjc123** [comment]
@Srikanth421 What is the output of `torch -m torch.utils.collect_env`?

**Comment by Srikanth421** [comment]
I solved the issue by re-installing pytorch gpu. Now gpu is available but another error of loading mnist dataset. I guess I can close and post the new error as separate issue.
