### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

### ISSUE THREAD

**Issue by MSKazemi** [pytorch/pytorch#44473]
I have a model with 3dConv layer when start training I got the following error:

RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input. (getWorkspaceSize at /pytorch/aten/src/ATen/native/cudnn/Conv.cpp:572)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7ff7f4824536 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xf0b613 (0x7ff7f595c613 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xf0167c (0x7ff7f595267c in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xf02541 (0x7ff7f5953541 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xf0657b (0x7ff7f595757b in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: at::native::cudnn_convolution_backward_input(c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool) + 0xb2 (0x7ff7f5957ad2 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0xf6d5f0 (0x7ff7f59be5f0 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xfb1e88 (0x7ff7f5a02e88 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #8: at::native::cudnn_convolution_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x4fa (0x7ff7f595916a in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #9: <unknown function> + 0xf6d91b (0x7ff7f59be91b in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #10: <unknown function> + 0xfb1ee4 (0x7ff7f5a02ee4 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #11: <unknown function> + 0x2c80736 (0x7ff833ee4736 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x2ccff44 (0x7ff833f33f44 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #13: torch::autograd::generated::CudnnConvolutionBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x378 (0x7ff833afc908 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x2d89705 (0x7ff833fed705 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #15: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x16f3 (0x7ff833feaa03 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #16: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7ff833feb7e2 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #17: torch::autograd::Engine::thread_init(int) + 0x39 (0x7ff833fe3e59 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #18: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7ff84cb685f8 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #19: <unknown function> + 0xbd6df (0x7ff8609656df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #20: <unknown function> + 0x76db (0x7ff8661e16db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #21: clone + 0x3f (0x7ff86651aa3f in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by xwang233** [comment]
Thanks for the report. Can you run
```bash
 python -m torch.utils.collect_env
```
to provide your system environment?

Also, please provide a minimal script that can repro this error, at least with the tensor shapes and convolution parameters (kernel size, strides, etc).

**Comment by colesbury** [comment]
@xwang233 maybe we can add the shape (and other relevant info) to the error message when we encounter CUDNN_STATUS_NOT_SUPPORTED.

**Comment by xwang233** [comment]
@colesbury that's a good point! I'll check the code and see what we can do.

**Comment by MSKazemi** [comment]
> Thanks for the report. Can you run
> 
> ```shell
>  python -m torch.utils.collect_env
> ```
> 
> to provide your system environment?
> 
> Also, please provide a minimal script that can repro this error, at least with the tensor shapes and convolution parameters (kernel size, strides, etc).
please find in the following the results:

PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 450.36.06
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] torch==1.5.1
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.6.1
[conda] Could not collect

**Comment by MSKazemi** [comment]
> @xwang233 maybe we can add the shape (and other relevant info) to the error message when we encounter CUDNN_STATUS_NOT_SUPPORTED.

I have this error just in the model with 3dConv.

**Comment by MSKazemi** [comment]
with the following line of codes, it starts to work.
torch.backends.cudnn.enabled = False

**Comment by ngimel** [comment]
@MSKazemi can you please collect cudnn logs for your model? https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#api-logging

**Comment by MSKazemi** [comment]
> @MSKazemi can you please collect cudnn logs for your model? https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#api-logging
please find the attached file.
[cudnn_debug.log](https://github.com/pytorch/pytorch/files/5294842/cudnn_debug.log)

**Comment by MSKazemi** [comment]
> @MSKazemi can you please collect cudnn logs for your model? https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#api-logging

please find in the attached file.
[cudnn_debug.log](https://github.com/pytorch/pytorch/files/5294853/cudnn_debug.log)

**Comment by zcong17huang** [comment]
> with the following line of codes, it starts to work.
> torch.backends.cudnn.enabled = False

Hello，I meet the same problem. But when i add `torch.backends.cudnn.enabled = False`，the 'non-contiguous input'  problem is solved，but it comes with a new one: **RuntimeError: CUDA out of memory**. My GPU has enough memory. So do you know why?

**Comment by phcerdan** [comment]
I faced this error message in a **valid** out of memory situation when using `torch.cuda.amp.autocast()`
```py
with torch.cuda.amp.autocast():
  outputs = model(inputs)
  loss = loss_function(outputs, labels)
```
When I run the `forward` function outside the `amp.autocast` environment I get an out of memory RuntimeError:
```py
RuntimeError: CUDA out of memory. Tried to allocate ...
```

So I guess, the error message could be improved when running `amp.autocast`.
