### ISSUE TITLE
JIT cuda error with non default GPU ID

### ISSUE THREAD

**Issue by deepbrain** [pytorch/pytorch#4468]
I found an issue when using a GPU with ID != 0. If I run all of the .cuda calls with the GPU argument of 1 
 -- .cuda(1), I get an error:

RuntimeError: arguments are located on different GPUs at 
 ../pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu:259

It happens only with the JIT class decorations on. Also, it does not happen when the GPU id == 0.

Let me know if you can reproduce this, if not, I will create a simplified test case for you.

**Comment by zdevito** [comment]
I couldn't reproduce this exact problem, but I did submit #4504 which fixes a related issue. If this doesn't fix your issue, then a test case would be helpful.

**Comment by deepbrain** [comment]
I am still getting the same error with the new code. Here is a simple test case, if you set the GPU=0 all works fine, when GPU=1 I get the error:

RuntimeError: arguments are located on different GPUs at ../pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:236

if I comment out @torch.jit.compile(nderivs=1), no error is thrown.

```python
import torch
from torch import jit
import torch.nn as nn
from torch.autograd import Variable


@torch.jit.compile(nderivs=1)
class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()
        self.net1 = nn.Linear(100, 200)
        self.net2 = nn.Linear(200, 1)
        self.sigmoid = nn.Sigmoid()
        self.ReLU = nn.ReLU(inplace=False)
        self.drop = nn.Dropout(0.5)
...............
    def forward(self, V):
        return self.sigmoid(self.net2(self.drop(self.ReLU(self.net1(V))))).squeeze().


use_cuda = True
GPU = 1
net = TestNet()
criterion = nn.BCELoss()
if use_cuda:
    net.cuda(GPU)
    criterion.cuda(GPU)
    V = Variable(torch.randn(100, 100)).cuda(GPU)
    label = Variable(torch.randn(100)).cuda(GPU)
else:
    V = Variable(torch.randn(100, 100))
    label = Variable(torch.randn(100))

net.train()
for i in range(0,1000000):
    r = net(V)
    err = criterion(r, label)
    err.backward()...

```

**Comment by soumith** [comment]
fixed via #4545

**Comment by deepbrain** [comment]
this issue is still present in the current code, I was wondering if the test code above could be added to the regression tests?

**Comment by apaszke** [comment]
Yes, we should definitely have a test like this.

**Comment by Choco31415** [comment]
I can confirm that I am having the same issue with the latest PyTorch. I currently have a 1060 and 1080 Ti on Ubuntu 17.10. If any other details are needed, just ask.

**Comment by linxiaoby** [comment]
I am having the same issue with the PyTorch 0.4.0， call for help!

**Comment by eellison** [comment]
Just tried the repro and it worked so I'm closing. please re-open if this an issue for you on master.
