### ISSUE TITLE
AMP with Linear layer then GRU raises CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by johnmccain** [pytorch/pytorch#46016]
## 🐛 Bug

Running a linear layer followed by a GRU with AMP raises a CUDNN_STATUS_BAD_PARAM error. This does not happen if not using AMP.

## To Reproduce

Minimal example:
```
import torch
from torch import nn
import sys

print("Python version")
print (sys.version)
print('CuDNN Version')
print(torch.backends.cudnn.version())
print('CuDNN Enabled')
print(torch.backends.cudnn.enabled)

class GRU_Amp_Bug(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.linear = nn.Linear(128, 128)
        
        self.gru = nn.GRU(
            input_size=128,
            hidden_size=128
        )
        
    def forward(self, X, h):
        X = self.linear(X)
        X, h_n = self.gru(X, h)
        return X


model = GRU_Amp_Bug().to(torch.cuda.current_device())

input_X = torch.rand((1, 1, 128)).to(torch.cuda.current_device())

input_h = torch.rand((1, 1, 128)).to(torch.cuda.current_device())

scaler = torch.cuda.amp.GradScaler()

with torch.cuda.amp.autocast():
    out = model(input_X, input_h)
```

Output:

```
Python version
3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
CuDNN Version
7605
CuDNN Enabled
True
Traceback (most recent call last):
  File "pytorch_gru_amp_bug_minimal_example.py", line 38, in <module>
    out = model(input_X, input_h)
  File "C:\Users\name\Documents\projects\gru-amp-bug\venv\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "pytorch_gru_amp_bug_minimal_example.py", line 25, in forward
    X, h_n = self.gru(X, h)
  File "C:\Users\name\Documents\projects\gru-amp-bug\venv\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\name\Documents\projects\gru-amp-bug\venv\lib\site-packages\torch\nn\modules\rnn.py", line 735, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
```

## Expected behavior

The expected behavior is to encounter no exceptions when using AMP in this scenario.

## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] Could not collect

## Additional context

GPU is an RTX Titan running GeForce Game Ready Driver 456.55.

It looks like `input` for [this function call](https://github.com/pytorch/pytorch/blob/b31f58de6fa8bbda5353b3c77d9be4914399724d/torch/nn/modules/rnn.py#L734) is dtype `torch.float16` which seems to cause the issue. 

cc @mcarilli

**Comment by ngimel** [comment]
Have you tried nightly builds? There were GRU fixes submitted after 1.6

**Comment by johnmccain** [comment]
I just tested with the latest nightly build and it looks like this has been fixed--thanks!

Specifically I can confirm that this works with Pytorch version `torch==1.8.0.dev20201008`, `torchvision==0.8.0.dev20201008`.
