### ISSUE TITLE
In PyTorch Tutorials: DEEP LEARNING WITH PYTORCH: A 60 MINUTE BLITZ, RuntimeError: CUDA error: out of memory happen

### ISSUE THREAD

**Issue by 2015211289** [pytorch/pytorch#46084]
## 🐛 Bug

when I learned how to use CUDA Tensors in Toturials "WHAT IS PYTORCH?" of "DEEP LEARNING WITH PYTORCH: A 60 MINUTE BLITZ", I executed 
    if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
when I executed 'y = torch.ones_like(x, device=device)' , python showed that RuntimeError: CUDA error: out of memory. But I checked out my GPU usage, it seemed have about 100MB to use. 
What' more,  I found that if my executed 'x = x.to(device)' before ' y = torch.ones_like(x, device=device)' , it would work without error.

## To Reproduce

1. open a python terminal 
2. run the code above with a GPU with about 500MB left to use

In my computer:
(RL) seth@seth-Precision-3630-Tower:~$ python
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> x=torch.tensor(1)
>>> x
tensor(1)
>>> device = torch.device("cuda") 
>>> y = torch.ones_like(x, device=device)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: out of memory

## Expected behavior
it should work
## Environment
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Quadro P620
Nvidia driver version: 450.51.06
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] numpy                     1.19.2                   pypi_0    pypi
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi

## Additional context
I know my GPU capacity is small, but I used a tensor(1) which should not obtain much more than 500 MB to use.
Importantly, I changed the execution order and it worked. I don't know why and if it really means something, I think the tutorials can remind us.

**Comment by agolynski** [comment]
@2015211289 I presume you are doing this tutorial https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

I've tried to repro on my machine (although I think it has more than 500M) and no luck
![Screen Shot 2020-10-12 at 10 51 57 AM](https://user-images.githubusercontent.com/5865598/95760476-13eff080-0c79-11eb-8590-f0d4552e6495.png)

What did you change in order of execution for it to work?

**Comment by 2015211289** [comment]
> @2015211289 I presume you are doing this tutorial https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html
> 
> I've tried to repro on my machine (although I think it has more than 500M) and no luck
> ![Screen Shot 2020-10-12 at 10 51 57 AM](https://user-images.githubusercontent.com/5865598/95760476-13eff080-0c79-11eb-8590-f0d4552e6495.png)
> 
> What did you change in order of execution for it to work?

if torch.cuda.is_available():
    device = torch.device("cuda")     
    x = x.to(device)                                      #  I sent x to GPU first,
    y = torch.ones_like(x, device=device)   #  and then created y in GPU , and it worked              
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
