### ISSUE TITLE
Nightly build not working with GeForce 3090

### ISSUE THREAD

**Issue by 3DTOPO** [pytorch/pytorch#46794]
## 🐛 Bug

I just installed a 3090, NVIDIA 455.23.04 and installed PyTorch nightly with:

`conda install pytorch torchvision cudatoolkit=10.2 -c pytorch-nightly`

When I try to run I get this message:

>GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

The instructions mentioned above are where I started and used the install command listed there to install nightly.

Here is my relevant env:

>torch==1.8.0.dev20201023
torchvision==0.8.0.dev20201023

**Comment by 3DTOPO** [comment]
Looks like the solution is in issue #45028:

'conda install pytorch torchvision cudatoolkit=11 -c pytorch-nightly'

I'm trying that now (I have to install cuda 11 first) and will report back.

**Comment by 3DTOPO** [comment]
I'm up and running now, might be nice to add the above line to the configurator.

**Comment by anthonyfuller7** [comment]
> I'm up and running now, might be nice to add the above line to the configurator.

How did you install CUDA 11.0 on the 3090? I tried installing it via the local runfile:

`wget https://developer.download.nvidia.com/compute/cuda/11.0.3/local_installers/cuda_11.0.3_450.51.06_linux.run`

But that driver version 450.51.06 is not supported by the 3090. I tried to swap out driver versions that would be supported by the 3090, but couldn't find the files. I then tried via the deb (network) option, but this installed CUDA 11.1, even though it is on the 11.0 page. 

Any help would be much appreciated :)

**Comment by 3DTOPO** [comment]
I installed the 455.23.04 driver then installed Cuda 11 without incident. Although, I'm confused now myself because it shows Cuda 11.1:
<img width="562" alt="Screen Shot 2020-10-28 at 2 27 03 PM" src="https://user-images.githubusercontent.com/352383/97492916-d0101300-1929-11eb-8b94-ab2d64d98989.png">

But if I look at /usr/local I have 'cuda-11.0' not 'cuda-11.1' shown there.

Anyhow, I think you just need to install  455.23.04 and since 1.7 was just released, all you need to do is run the Start Locally command and choose CUDA 11.0:

**Comment by anthonyfuller7** [comment]
> I installed the 455.23.04 driver then installed Cuda 11 without incident. Although, I'm confused now myself because it shows Cuda 11.1:
> <img alt="Screen Shot 2020-10-28 at 2 27 03 PM" width="562" src="https://user-images.githubusercontent.com/352383/97492916-d0101300-1929-11eb-8b94-ab2d64d98989.png">
> 
> But if I look at /usr/local I have 'cuda-11.0' not 'cuda-11.1' shown there.
> 
> Anyhow, I think you just need to install 455.23.04 and since 1.7 was just released, all you need to do is run the Start Locally command and choose CUDA 11.0:
> [https://pytorch.org/get-started/locally/](url)
> 
> I can confirm that with that install command PyTorch is running on the 3090 here.
> 
> `conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch`

Interesting... Looking at /usr/local I have 'cuda-11.1'. And nvcc --version also says it is CUDA 11.1

But I successfully installed stable PyTorch (that specifies 11.0), and ran a quick test putting a random tensor on the GPU, and it worked...

**Comment by 3DTOPO** [comment]
Cool, glad you're up and running!!

**Comment by KyuanCortex** [comment]
> conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch

Hello, which gcc/g++ version is adopted, thanks.
