### ISSUE TITLE
torch.distributed.reduce hangs with nccl backend

### ISSUE THREAD

**Issue by shuuchen** [pytorch/pytorch#47498]
Hi,

I am using multi-gpu training, following the tutorial:
https://pytorch.org/docs/stable/notes/ddp.html

I am trying with 
```
import torch.distributed as dist
...
dist.reduce(loss, 0, dist.ReduceOp.SUM)
```

However, it hangs after reduce function is called. If I don't use reduce function, it is OK.

I searched and found similar issues, but no solutions at all. Anyone can help ?

Thank you !

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by jeffdaily** [comment]
Related to https://github.com/pytorch/pytorch/issues/47629 ?

**Comment by rohan-varma** [comment]
Might possibly be related. @shuuchen, could you provide a full script that reproduces the issue and information about your environment, such as PyTorch version? Thank you!

**Comment by shuuchen** [comment]
Sorry, my fault. 
I wrote a test script and now it works OK.

https://gist.github.com/shuuchen/7463009370e9ddf77e649f3fec259024
