### ISSUE TITLE
NaN errors in test_torch

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#47661]
## 🐛 Bug

Running the tests I get 2 failing tests in test_torch where NaNs are produced

## To Reproduce

1. Build with `PYTORCH_BUILD_VERSION=1.7.0 PYTORCH_BUILD_NUMBER=1 MAX_JOBS=12 BLAS=Eigen USE_FFMPEG=1 BUILD_CUSTOM_PROTOBUF=0 USE_IBVERBS=1 USE_CUDA=1 CUDNN_LIB_DIR=/sw/installed/cuDNN/7.6.4.38-gcccuda-2019b/lib64 CUDNN_INCLUDE_DIR=/sw/installed/cuDNN/7.6.4.38-gcccuda-2019b/include USE_SYSTEM_NCCL=1 NCCL_INCLUDE_DIR=/sw/installed/NCCL/2.4.8-gcccuda-2019b/include TORCH_CUDA_ARCH_LIST="3.7;6.1;7.0" USE_METAL=0   /sw/installed/Python/3.7.4-GCCcore-8.3.0/bin/python setup.py install`
1. Run tests with `cd tes && python run_test.py --verbose`

Error message:
```
======================================================================
FAIL: test_det_logdet_slogdet_batched_cuda_float64 (__main__.TestTorchDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/easybuild-tmp/eb-T5lOcH/tmpRzOnNw/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 827, in wrapper
    method(*args, **kwargs)
  File "/tmp/easybuild-tmp/eb-T5lOcH/tmpRzOnNw/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 273, in instantiated_test
    result = test_fn(self, *args)
  File "/tmp/easybuild-tmp/eb-T5lOcH/tmpRzOnNw/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 508, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/tmp/easybuild-tmp/eb-T5lOcH/tmpRzOnNw/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 508, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_torch.py", line 7519, in test_det_logdet_slogdet_batched
    run_test(matsize, batchdims, mat_chars=['sing'])
  File "test_torch.py", line 7515, in run_test
    self.assertEqual(actual_value, expected_value)
  File "/tmp/easybuild-tmp/eb-T5lOcH/tmpRzOnNw/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1136, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1e-07 and atol=1e-07, found 3 element(s) (out of 3) whose difference(s) exceeded the margin of error (including 3 nan comparisons). The greatest difference was nan (nan vs. 0.0), which occurred at index 0.

======================================================================
FAIL: test_lu_cuda (__main__.TestTorchDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/easybuild-tmp/eb-T5lOcH/tmpRzOnNw/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 827, in wrapper
    method(*args, **kwargs)
  File "/tmp/easybuild-tmp/eb-T5lOcH/tmpRzOnNw/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 273, in instantiated_test
    result = test_fn(self, *args)
  File "/tmp/easybuild-tmp/eb-T5lOcH/tmpRzOnNw/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 508, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/tmp/easybuild-tmp/eb-T5lOcH/tmpRzOnNw/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 508, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_torch.py", line 15476, in test_lu
    run_test(device, True)
  File "test_torch.py", line 15470, in run_test
    run_subtest(ms, batch, device, pivot, singular=True, a=a)
  File "test_torch.py", line 15446, in run_subtest
    self.assertEqual(P.matmul(L.matmul(U)), a)
  File "/tmp/easybuild-tmp/eb-T5lOcH/tmpRzOnNw/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1136, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1e-07 and atol=1e-07, found 18 element(s) (out of 18) whose difference(s) exceeded the margin of error (including 18 nan comparisons). The greatest difference was nan (nan vs. 1.0), which occurred at index (0, 0, 0).
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

```
PyTorch version: 1.7.0
Is debug build: no
CUDA used to build PyTorch: 10.1.243 
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.7.1908 (Core) (x86_64)
GCC version: (GCC) 8.3.0
CMake version: version 3.15.3

Python version: 3.7 (64-bit runtime)
Is CUDA available: yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti

Nvidia driver version: 450.36.06
cuDNN version: 7.6.4.38

Versions of relevant libraries:
[pip3] numpy==1.17.3
[conda] Could not collect
```

I checked against 1.6.0 and the issue has been there too.

**Comment by Flamefire** [comment]
Reduced reproducer for the first failure:

```
import torch

values = [
    [0.8909, 0.8909, 0.8909],
    [0.8909, 0.8909, 0.8909],
    [0.8909, 0.8909, 0.8909]
]
singleTensor = torch.tensor(values, dtype=torch.float64)
multiTensor = torch.tensor([values, values, values], dtype=torch.float64)

print("CPU single: %s, multi: %s" % (torch.det(singleTensor), torch.det(multiTensor)))
print("GPU single: %s, multi: %s" % (torch.det(singleTensor.cuda()), torch.det(multiTensor.cuda())))
```
-->
```
CPU single: tensor(0., dtype=torch.float64), multi: tensor([0., 0., 0.], dtype=torch.float64)
GPU single: tensor(0., device='cuda:0', dtype=torch.float64), multi: tensor([nan, nan, nan], device='cuda:0', dtype=torch.float64)
```

**Comment by Flamefire** [comment]
I was able to reduce this further to `print("GPU single: %s, multi: %s" % (singleTensor.cuda().lu(), multiTensor.cuda().lu()))` for the above example.
Turns out it is a bug in Magma 2.5.1 which is fixed in 2.5.2:
> Fix a bug in batched LU factorization to avoind NaNs when singularity is ancountered

https://icl.utk.edu/magma/software/browse.html?start=5&per=5
