### ISSUE TITLE
NCCL 2.7.8 errors on PyTorch distributed process group creation

### ISSUE THREAD

**Issue by ruipeterpan** [pytorch/pytorch#47885]
## 🐛 Bug

NCCL 2.7.8 errors on PyTorch distributed process group creation

## To Reproduce

1. On two machines, execute this command with ranks 0 and 1 after setting the environment variables (`MASTER_ADDR`, `MASTER_PORT`, `CUDA_VISIBLE_DEVICES`):
```
>>> dist.init_process_group(backend='nccl', rank=0, world_size=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 442, in init_process_group
    barrier()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1947, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
```

## Expected behavior

A clean initialization w/o error

## Environment

- PyTorch version: 1.7.0+cu110
- Is debug build: True
- CUDA used to build PyTorch: 11.0
- ROCM used to build PyTorch: N/A
- 
- OS: Ubuntu 18.04.5 LTS (x86_64)
- GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- Clang version: Could not collect
- CMake version: version 3.10.2
- 
- Python version: 3.8 (64-bit runtime)
- Is CUDA available: True
- CUDA runtime version: Could not collect
- GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
- Nvidia driver version: 450.51.05
- cuDNN version: Probably one of the following:
- /usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
- /usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
- /usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
- /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
- /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
- /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
- /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
- HIP runtime version: N/A
- MIOpen runtime version: N/A
- 
- Versions of relevant libraries:
- [pip] Could not collect
- [conda] Could not collect

## Additional context
NCCL version is as follows:
- libnccl2=2.7.8-1+cuda11.0

**Comment by rohan-varma** [comment]
Hi, is there a script that reproduces the issue on your end? 

I tried with a clean build of PT master and NCCL 2.7.8, and was not able to repro the issue:
```
import sys
import torch
import os
import torch.distributed as dist

if __name__ == '__main__':
    rank = int(sys.argv[1])
    print(torch.cuda.nccl.version())
    print(rank)
    assert rank in [0,1]
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "29500"
    os.environ["CUDA_VISIBLE_DEVICES"] = str(rank)
    dist.init_process_group(backend='nccl', rank=rank,world_size=2)
    print("Finished init")
```

**Comment by frederikschubert** [comment]
This is is caused by the topology of your CUDA devices. You can see it via the following command:
```
 nvidia-smi topo -m                                                                                                                                                                                                     erebos.tnt.uni-hannover.de
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    CPU Affinity    NUMA Affinity
GPU0     X      PIX     NODE    SYS     SYS     SYS     0-17,36-53      0
GPU1    PIX      X      NODE    SYS     SYS     SYS     0-17,36-53      0
GPU2    NODE    NODE     X      SYS     SYS     SYS     0-17,36-53      0
GPU3    SYS     SYS     SYS      X      PIX     NODE    18-35,54-71     1
GPU4    SYS     SYS     SYS     PIX      X      NODE    18-35,54-71     1
GPU5    SYS     SYS     SYS     NODE    NODE     X      18-35,54-71     1

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```
If the CUDA devices are not connected via a `SYS` connection, NCCL will throw your error.

**Comment by kiddyboots216** [comment]
For anyone who finds this issue in the future -I had the same issue and downgrading to pytorch 1.6 fixed things.

**Comment by ruiyuanlu** [comment]
I met the same issue using Pytorch-1.7.1 CUDA 10.2 and NCCL-2.7.8 on Ubuntu16.04. Any updates?

**Comment by ruipeterpan** [comment]
@ruiyuanlu sorry for the inactivity :( For now, I'm not able to replicate my previous issue, but process group creation works fine in my current environment:

- PyTorch version: 1.7.0+cu110
- CUDA used to build PyTorch: 11.0-devel-ubuntu18.04
- OS: Linux 4.15.0-1100-azure x86_64
- GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- CMake version: version 3.10.2
- Python version: 3.6.9
- Is CUDA available: True
- GPU models and configuration: Tesla K80
- Nvidia driver version: 440.33.01
- cuDNN version: 8.0.5.39-1+cuda11.0
- NCCL version: 2.7.8-1+cuda11.0

**Comment by ruipeterpan** [comment]
FYI, this is a previous comment by @frederikschubert. Not sure if this was the reason behind this, but hope this helps!

```
This is is caused by the topology of your CUDA devices. You can see it via the following command:

 nvidia-smi topo -m                                                                                                                                                                                                     erebos.tnt.uni-hannover.de
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    CPU Affinity    NUMA Affinity
GPU0     X      PIX     NODE    SYS     SYS     SYS     0-17,36-53      0
GPU1    PIX      X      NODE    SYS     SYS     SYS     0-17,36-53      0
GPU2    NODE    NODE     X      SYS     SYS     SYS     0-17,36-53      0
GPU3    SYS     SYS     SYS      X      PIX     NODE    18-35,54-71     1
GPU4    SYS     SYS     SYS     PIX      X      NODE    18-35,54-71     1
GPU5    SYS     SYS     SYS     NODE    NODE     X      18-35,54-71     1

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
If the CUDA devices are not connected via a SYS connection, NCCL will throw your error.
```

**Comment by ruiyuanlu** [comment]
> FYI, this is a previous comment by @frederikschubert. Not sure if this was the reason behind this, but hope this helps!
> 
> ```
> This is is caused by the topology of your CUDA devices. You can see it via the following command:
> 
>  nvidia-smi topo -m                                                                                                                                                                                                     erebos.tnt.uni-hannover.de
>         GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    CPU Affinity    NUMA Affinity
> GPU0     X      PIX     NODE    SYS     SYS     SYS     0-17,36-53      0
> GPU1    PIX      X      NODE    SYS     SYS     SYS     0-17,36-53      0
> GPU2    NODE    NODE     X      SYS     SYS     SYS     0-17,36-53      0
> GPU3    SYS     SYS     SYS      X      PIX     NODE    18-35,54-71     1
> GPU4    SYS     SYS     SYS     PIX      X      NODE    18-35,54-71     1
> GPU5    SYS     SYS     SYS     NODE    NODE     X      18-35,54-71     1
> 
> Legend:
> 
>   X    = Self
>   SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
>   NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
>   PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
>   PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
>   PIX  = Connection traversing at most a single PCIe bridge
>   NV#  = Connection traversing a bonded set of # NVLinks
> If the CUDA devices are not connected via a SYS connection, NCCL will throw your error.
> ```

Thanks for the sharing. I don't see any problem here in my `nvidia-smi topo -m`:
In my case, the GPU 0-3 and GPU 4-7 are on 2 PCIe bridges, I think PIX is reasonable here, right?

```shell
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	CPU Affinity
GPU0	 X 	PIX	PIX	PIX	SYS	SYS	SYS	SYS	0-15,32-47
GPU1	PIX	 X 	PIX	PIX	SYS	SYS	SYS	SYS	0-15,32-47
GPU2	PIX	PIX	 X 	PIX	SYS	SYS	SYS	SYS	0-15,32-47
GPU3	PIX	PIX	PIX	 X 	SYS	SYS	SYS	SYS	0-15,32-47
GPU4	SYS	SYS	SYS	SYS	 X 	PIX	PIX	PIX	16-31,48-63
GPU5	SYS	SYS	SYS	SYS	PIX	 X 	PIX	PIX	16-31,48-63
GPU6	SYS	SYS	SYS	SYS	PIX	PIX	 X 	PIX	16-31,48-63
GPU7	SYS	SYS	SYS	SYS	PIX	PIX	PIX	 X 	16-31,48-63

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by ruipeterpan** [comment]
So I circled back to the issue I myself created a few months back. This time I used `export NCCL_DEBUG=INFO` and here's what I got (probably because I was trying to have two processes on the same GPU form a process group?):

```
root@node2:# python3.8 repro.py 0
2708
0
node2:458:458 [0] NCCL INFO Bootstrap : Using [0]eno4:10.0.1.240<0> [1]enps0f1:192.168.100.12<0>
node2:458:458 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

node2:458:458 [0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed

node2:458:458 [0] transport/net_ib.cc:148 NCCL WARN NET/IB : Unable to open device mlx5_0

node2:458:458 [0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed

node2:458:458 [0] transport/net_ib.cc:148 NCCL WARN NET/IB : Unable to open device mlx5_1
node2:458:458 [0] NCCL INFO NET/IB : No device found.
node2:458:458 [0] NCCL INFO NET/Socket : Using [0]eno4:10.0.1.240<0> [1]enps0f1:192.168.100.12<0>
node2:458:458 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda11.0

node2:458:528 [0] init.cc:573 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 3b000
node2:458:528 [0] NCCL INFO init.cc:840 -> 5
node2:458:528 [0] NCCL INFO group.cc:73 -> 5 [Async thread]
Traceback (most recent call last):
  File "repro.py", line 13, in <module>
    dist.init_process_group(backend='nccl', rank=rank,world_size=2)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 442, in init_process_group
    barrier()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1947, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
```

**Comment by miccio-dk** [comment]
sorry for the intromission, I'm experiencing the same issue with Pytorch 1.7/ NCCL 2.7.8 running on a single node with two TITAN X gpus. This is the debugging output before inevitably quitting at `ProcessGroupNCCL.cpp:784`:
```
hostmachine:5893:5893 [0] NCCL INFO Bootstrap : Using [0]eno1:172.30.215.224<0>
hostmachine:5893:5893 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

hostmachine:5893:5893 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
hostmachine:5893:5893 [0] NCCL INFO NET/Socket : Using [0]eno1:172.30.215.224<0>
hostmachine:5893:5893 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda10.2
hostmachine:5924:5924 [1] NCCL INFO Bootstrap : Using [0]eno1:172.30.215.224<0>
hostmachine:5924:5924 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

hostmachine:5924:5924 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
hostmachine:5924:5924 [1] NCCL INFO NET/Socket : Using [0]eno1:172.30.215.224<0>
hostmachine:5924:5924 [1] NCCL INFO Using network Socket


hostmachine:5924:5948 [1] init.cc:573 NCCL WARN Duplicate GPU detected : rank 1 and rank 0 both on CUDA device 3000
hostmachine:5893:5947 [0] init.cc:573 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 3000
hostmachine:5924:5948 [1] NCCL INFO init.cc:840 -> 5
hostmachine:5893:5947 [0] NCCL INFO init.cc:840 -> 5
hostmachine:5924:5948 [1] NCCL INFO group.cc:73 -> 5 [Async thread]
hostmachine:5893:5947 [0] NCCL INFO group.cc:73 -> 5 [Async thread]
```

Conversely, downgrading to Pytorch 1.6 shows this (however this is not viable because I'm using certain complex functions which were not available in v1.6):
```
hostmachine:11053:11053 [0] NCCL INFO Bootstrap : Using [0]eno1:172.30.215.224<0>
hostmachine:11053:11053 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

hostmachine:11053:11053 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
hostmachine:11053:11053 [0] NCCL INFO NET/Socket : Using [0]eno1:172.30.215.224<0>
NCCL version 2.4.8+cuda10.2
hostmachine:11053:11091 [0] NCCL INFO Setting affinity for GPU 0 to 03f03f
hostmachine:11068:11068 [1] NCCL INFO Bootstrap : Using [0]eno1:172.30.215.224<0>
hostmachine:11068:11068 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

hostmachine:11068:11068 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
hostmachine:11068:11068 [1] NCCL INFO NET/Socket : Using [0]eno1:172.30.215.224<0>
hostmachine:11068:11092 [1] NCCL INFO Setting affinity for GPU 1 to 03f03f
hostmachine:11053:11091 [0] NCCL INFO Channel 00 :    0   1
hostmachine:11068:11092 [1] NCCL INFO Ring 00 : 1[1] -> 0[1] via P2P/IPC
hostmachine:11053:11091 [0] NCCL INFO Ring 00 : 0[1] -> 1[1] via P2P/IPC
hostmachine:11053:11091 [0] NCCL INFO Using 256 threads, Min Comp Cap 6, Trees disabled
hostmachine:11053:11091 [0] NCCL INFO comm 0x7efd64002620 rank 0 nranks 2 cudaDev 0 nvmlDev 1 - Init COMPLETE
hostmachine:11068:11092 [1] NCCL INFO comm 0x7faba8002620 rank 1 nranks 2 cudaDev 1 nvmlDev 1 - Init COMPLETE
hostmachine:11053:11053 [0] NCCL INFO Launch mode Parallel
```

**Comment by rubencart** [comment]
Getting the same error. Running my script like `CUDA_VISIBLE_DEVICES=1,2 python -u src/main.py --cfg config/train_debug.yaml` on two TITAN Xp GPU's. Same error with `CUDA_VISIBLE_DEVICES=2,3`.

`nvidia-smi -l` briefly shows memory allocated to 2 processes on the same GPU, instead of 2 different GPUs, before it crashes.
```
26-02-2021 10:23:04 - 33793 - INFO - initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
frodo:33631:33631 [0] NCCL INFO Bootstrap : Using [0]eno1:134.58.47.35<0>
frodo:33631:33631 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
frodo:33631:33631 [0] NCCL INFO NET/IB : No device found.
frodo:33631:33631 [0] NCCL INFO NET/Socket : Using [0]eno1:134.58.47.35<0>
frodo:33631:33631 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda11.0
frodo:33793:33793 [1] NCCL INFO Bootstrap : Using [0]eno1:134.58.47.35<0>
frodo:33793:33793 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
frodo:33793:33793 [1] NCCL INFO NET/IB : No device found.
frodo:33793:33793 [1] NCCL INFO NET/Socket : Using [0]eno1:134.58.47.35<0>
frodo:33793:33793 [1] NCCL INFO Using network Socket

frodo:33793:33885 [1] init.cc:573 NCCL WARN Duplicate GPU detected : rank 1 and rank 0 both on CUDA device 83000

frodo:33631:33884 [0] init.cc:573 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 83000
frodo:33793:33885 [1] NCCL INFO init.cc:840 -> 5
frodo:33631:33884 [0] NCCL INFO init.cc:840 -> 5
frodo:33793:33885 [1] NCCL INFO group.cc:73 -> 5 [Async thread]
frodo:33631:33884 [0] NCCL INFO group.cc:73 -> 5 [Async thread]
Traceback (most recent call last):
Traceback (most recent call last):
  File "src/main.py", line 173, in <module>
  File "/cw/liir/NoCsBack/testliir/rubenc/reteco/src/main.py", line 173, in <module>
    main(cfg, namespace_cfg)
  File "src/main.py", line 140, in main
    main(cfg, namespace_cfg)
  File "/cw/liir/NoCsBack/testliir/rubenc/reteco/src/main.py", line 140, in main
    trainer.fit(model, datamodule=data_module)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    trainer.fit(model, datamodule=data_module)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 158, in train
    results = self.accelerator_backend.train()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 158, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 258, in ddp_train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 258, in ddp_train
    self.init_ddp_connection(
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 158, in init_ddp_connection
    self.init_ddp_connection(
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 158, in init_ddp_connection
    self.ddp_plugin.init_ddp_connection(
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/pytorch_lightning/plugins/ddp_plugin.py", line 93, in init_ddp_connection
    self.ddp_plugin.init_ddp_connection(
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/pytorch_lightning/plugins/ddp_plugin.py", line 93, in init_ddp_connection
    torch_distrib.init_process_group(
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    torch_distrib.init_process_group(
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    barrier()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/tsenv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1607370172916/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1607370172916/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
```
Output of `nvidia-smi topo -m`:
```
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity
GPU0     X      PHB     SYS     SYS     0,2,4,6,8,10    0
GPU1    PHB      X      SYS     SYS     0,2,4,6,8,10    0
GPU2    SYS     SYS      X      PHB     1,3,5,7,9,11    1
GPU3    SYS     SYS     PHB      X      1,3,5,7,9,11    1

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```
Environment:
```
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN Xp
GPU 1: TITAN X (Pascal)
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-fid==0.2.0
[pip3] pytorch-lightning==1.1.8
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.221             h6bb024c_0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.1            py38h54f3939_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.7.1           py3.8_cuda11.0.221_cudnn8.0.5_0    pytorch
[conda] pytorch-fid               0.2.0                    pypi_0    pypi
[conda] pytorch-lightning         1.1.8              pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.8.2                py38_cu110    pytorch
```

**Comment by rohan-varma** [comment]
It looks like the common theme here is that some configuration results in different processes being assigned to the same GPU, resulting in invalid NCCL usage errors. Generally when calling into NCCL collectives, you'd want to ensure that each process calls into collectives with tensors on distinct GPUs, as this is what NCCL expects.

There were a few issues opened up similar to this one, for example https://github.com/pytorch/pytorch/issues/50921, which ended up being mitigated by appropriately setting the CUDA device with `torch.cuda.set_device()`. 

If that doesn't mitigate the issue it would be great if folks could provide a reproducer script that we can use to debug.

**Comment by brando90** [comment]
> It looks like the common theme here is that some configuration results in different processes being assigned to the same GPU, resulting in invalid NCCL usage errors. Generally when calling into NCCL collectives, you'd want to ensure that each process calls into collectives with tensors on distinct GPUs, as this is what NCCL expects.
> 
> There were a few issues opened up similar to this one, for example #50921, which ended up being mitigated by appropriately setting the CUDA device with `torch.cuda.set_device()`.
> 
> If that doesn't mitigate the issue it would be great if folks could provide a reproducer script that we can use to debug.

This is a very hard but to reproduce without just copy pasting the entire code infrastructure we have. I've tried to isolate it and I can never reproduce it (but I do get new errors). Did anyone at facebook manage to get this bug to be reproducible in a small example somehow?

**Comment by brando90** [comment]
related: https://stackoverflow.com/questions/66807131/how-does-solve-the-famous-unhandled-cuda-error-nccl-version-2-7-8-error

**Comment by Actstone** [comment]
I meet the same problem! Maybe the reason is that "num-gpus" is too big! You can try to set a smaller num.

**Comment by AAnoosheh** [comment]
I get this issue if I pass in the GPU ids in non-ascending order, i.e. gpus=[3,2,1,0] gives error, while gpus=[0,1,2,3] is okay.

But only since Pytorch 1.7

**Comment by ljz756245026** [comment]
> Hi, is there a script that reproduces the issue on your end?
> 
> I tried with a clean build of PT master and NCCL 2.7.8, and was not able to repro the issue:
> 
> ```
> import sys
> import torch
> import os
> import torch.distributed as dist
> 
> if __name__ == '__main__':
>     rank = int(sys.argv[1])
>     print(torch.cuda.nccl.version())
>     print(rank)
>     assert rank in [0,1]
>     os.environ["MASTER_ADDR"] = "localhost"
>     os.environ["MASTER_PORT"] = "29500"
>     os.environ["CUDA_VISIBLE_DEVICES"] = str(rank)
>     dist.init_process_group(backend='nccl', rank=rank,world_size=2)
>     print("Finished init")
> ```
> 
> `python repro.py 0`
> `python repro.py 1`

I have some code may reproduce this problem.

my python code is as follows:
```
import torch.distributed as dist
import torch.utils.data.distributed
import os
from datetime import datetime
import argparse
import torch.multiprocessing as mp
import torchvision
import torchvision.transforms as transforms
import torch
import torch.nn as nn
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP

parser = argparse.ArgumentParser(description='PyTorch distributed training on cifar-10')
parser.add_argument('--rank', default=0,type=int,
                    help='rank of current process')
parser.add_argument('--word_size', default=2,type=int,
                    help="word size")
parser.add_argument('--init_method', default='tcp://127.0.0.1:23456',
                    help="init-method")
args = parser.parse_args()

print('starting init_process_group')
dist.init_process_group(backend='nccl', init_method=args.init_method, rank=args.rank, world_size=args.word_size)
print('end init_process_group')
```


I run this code on 2 machines.
machine 0: 2 * NVIDIA Quadro (each GPU is around 8200MiB)
machine 1: 2 * TITAN RTX (each GPU is around 24200MiB)

my command are as follows:
on machine 0: 2 * NVIDIA Quadro:
NVIDIA_VISIBLE_DEVICES=0,1 python new.py --init_method tcp://IP address:12345 --rank 0 --word_size 2
on machine 1: 2 * TITAN RTX
NVIDIA_VISIBLE_DEVICES=0,1 python new.py --init_method tcp://IP address:12345 --rank 1 --word_size 2

problem happened on machine 1
`python new.py --init_method tcp://192.168.64.97:12345 --rank 1 --word_size 2
starting init_process_group
Traceback (most recent call last):
  File "new.py", line 26, in <module>
    dist.init_process_group(backend='nccl', init_method=args.init_method, rank=args.rank, world_size=args.word_size)
  File "/home/liujz/anaconda3/envs/myenvs2/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/liujz/anaconda3/envs/myenvs2/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1607370141920/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8`

**Comment by ljz756245026** [comment]
I have solved this problem by install a new environment. You can see the following list to find the software version you need.
```

Package            Version
------------------ -------------------
certifi            2021.5.30
charset-normalizer 2.0.3
click              8.0.1
datasets           1.10.2
dill               0.3.4
fairscale          0.3.8
filelock           3.0.12
fsspec             2021.7.0
huggingface-hub    0.0.12
idna               3.2
importlib-metadata 4.6.1
joblib             1.0.1
mkl-fft            1.3.0
mkl-random         1.2.2
mkl-service        2.4.0
multiprocess       0.70.12.2
numpy              1.20.3
olefile            0.46
packaging          21.0
pandas             1.3.0
Pillow             8.3.1
pip                21.1.3
portalocker        2.0.0
pyarrow            4.0.1
pyparsing          2.4.7
python-dateutil    2.8.2
pytz               2021.1
PyYAML             5.4.1
regex              2021.7.6
requests           2.26.0
sacrebleu          1.5.1
sacremoses         0.0.45
setuptools         52.0.0.post20210125
six                1.16.0
tokenizers         0.10.3
torch              1.9.0
torchaudio         0.9.0a0+33b2469
torchvision        0.10.0
tqdm               4.61.2
transformers       4.10.0.dev0
typing-extensions  3.10.0.0
urllib3            1.26.6
wheel              0.36.2
xxhash             2.0.2
zipp               3.5.0
```


Also, please make sure that you have opened the port. You can open the port by the following commands.

1. install firewalld
```
sudo apt-get install firewalld
```
2.open the ip port you want and restart the firewalld
```
sudo firewall-cmd --permanent --add-port=12345/tcp
sudo firewall-cmd --reload
```

**Comment by leo870823** [comment]
I met the same issue ,and my torch=1.7.1,NCCL version 2.7.8+cuda10.2

>   File "/home/r09021/miniconda2/envs/DeblurNet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
>     work = _default_pg.barrier()
> RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1607370128159/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
>     work = _default_pg.barrier()
> RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1607370128159/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
> Traceback (most recent call last):

**Comment by ruipeterpan** [comment]
I ran into this issue again and this time it's because I had exported the wrong `NCCL_SOCKET_IFNAME` environment variable. Just leaving a note here in case someone else might find it helpful...

**Comment by tanmodong** [comment]
Upgrade to NCCL 2.11.4 resoleved my problem in pytorch 1.7.1

 1) cuda/11.0/11.0.3     2) cudnn/8.0/8.0.5      3) nccl/2.11/2.11.4-1


below list is my torch environment
Package                       Version
----------------------------- -----------
accelerate                    0.5.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
certifi                       2021.10.8
cycler                        0.11.0
debugpy                       1.5.1
decorator                     5.1.1
entrypoints                   0.4
fonttools                     4.29.1
ipykernel                     6.9.0
ipython                       7.31.1
jedi                          0.18.1
jupyter-client                7.1.2
jupyter-core                  4.9.1
kiwisolver                    1.3.2
matplotlib                    3.5.1
matplotlib-inline             0.1.3
nest-asyncio                  1.5.4
numpy                         1.22.2
opencv-python                 4.5.5.62
packaging                     21.3
parso                         0.8.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.0.1
pip                           21.2.4
prompt-toolkit                3.0.26
ptyprocess                    0.7.0
Pygments                      2.11.2
pynvml                        11.4.1
pyparsing                     3.0.7
python-dateutil               2.8.2
pytorch-ranger                0.1.1
PyYAML                        6.0
pyzmq                         19.0.2
setuptools                    58.0.4
six                           1.16.0
timm                          0.5.4
torch                         1.7.1+cu110
torch-optimizer               0.3.0
torchaudio                    0.7.2
torchvision                   0.8.2+cu110
tornado                       6.1
tqdm                          4.63.0
traitlets                     5.1.1
typing_extensions             4.0.1
wcwidth                       0.2.5
wheel                         0.37.1

**Comment by Howe-Young** [comment]
upgrade your GPU Driver version >= 455.23

**Comment by yarkable** [comment]
In my case, I type `CUDA_VISIBLE_DEVICES=0,1,2,34,5,6,7 python xx.py`. Using `CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python xx.py` solved this.

**Comment by unreal91** [comment]
> Upgrade to NCCL 2.11.4 resoleved my problem in pytorch 1.7.1
> 
> 1. cuda/11.0/11.0.3     2) cudnn/8.0/8.0.5      3) nccl/2.11/2.11.4-1
> 
> below list is my torch environment Package Version
> 
> accelerate 0.5.1 backcall 0.2.0 backports.functools-lru-cache 1.6.4 certifi 2021.10.8 cycler 0.11.0 debugpy 1.5.1 decorator 5.1.1 entrypoints 0.4 fonttools 4.29.1 ipykernel 6.9.0 ipython 7.31.1 jedi 0.18.1 jupyter-client 7.1.2 jupyter-core 4.9.1 kiwisolver 1.3.2 matplotlib 3.5.1 matplotlib-inline 0.1.3 nest-asyncio 1.5.4 numpy 1.22.2 opencv-python 4.5.5.62 packaging 21.3 parso 0.8.3 pexpect 4.8.0 pickleshare 0.7.5 Pillow 9.0.1 pip 21.2.4 prompt-toolkit 3.0.26 ptyprocess 0.7.0 Pygments 2.11.2 pynvml 11.4.1 pyparsing 3.0.7 python-dateutil 2.8.2 pytorch-ranger 0.1.1 PyYAML 6.0 pyzmq 19.0.2 setuptools 58.0.4 six 1.16.0 timm 0.5.4 torch 1.7.1+cu110 torch-optimizer 0.3.0 torchaudio 0.7.2 torchvision 0.8.2+cu110 tornado 6.1 tqdm 4.63.0 traitlets 5.1.1 typing_extensions 4.0.1 wcwidth 0.2.5 wheel 0.37.1

@tanmodong how did you upgrade the NCCL version in same pytorch. Can you pass me the command list please.

**Comment by tanmodong** [comment]
@unreal91 
I don't know how to install nccl from scratch...
my environment is here (https://docs.abci.ai/ja/environment-modules/) and I used module load command specific in this environment...

**Comment by JerryDaHeLian** [comment]
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1347, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.5
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'invalid argument'
I have encountered the same problem, has anyone solved it?
