### ISSUE TITLE
Cuda.is_available() return False on Docker image pytorch/pytorch:1.7.0-cuda11.0-cudnn8-devel

### ISSUE THREAD

**Issue by Khoa-NT** [pytorch/pytorch#48361]
Hi,

I've already asked this question [here  ](https://discuss.pytorch.org/t/cuda-is-available-return-false-on-docker-image-pytorch-pytorch-1-7-0-cuda11-0-cudnn8-devel/103494?u=shaolinkhoa). 
But no answer, so I would like to post it here.

**Comment by Meehai** [comment]
Related: https://github.com/pytorch/pytorch/issues/47109

Apparently cuda 11.1 is not supported yet.

**Comment by Khoa-NT** [comment]
So weird, my other server (server B) has the same configuration that can run my image.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.04    Driver Version: 455.23.04    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:3B:00.0 Off |                  N/A |
|  0%   38C    P8    34W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 3090    Off  | 00000000:AF:00.0 Off |                  N/A |
|  0%   32C    P8    34W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
Meanwhile, server A has this problem after I rebooted it.

**Comment by Khoa-NT** [comment]
I reinstall the Nvidia driver and it works.
