### ISSUE TITLE
NCCL Error when training with 2x 3090s.

### ISSUE THREAD

**Issue by George3d6** [pytorch/pytorch#49095]
Cross post from here: https://discuss.pytorch.org/t/nccl-error-2-when-training-with-2-gpus/105465 -- because I'm getting a bit desperate in terms of getting to the bottom of this.

I am training a model with 2 GTX 3090 GPUs. Driver is 455.32.00, CUDA version is 11.1, and torch.cuda.nccl.version() yields 2708.

To enable multi-GPU, I have something like this:

```
 def to(self, device, available_devices):
        if available_devices > 1:
            self.net = torch.nn.DataParallel(self.net).to(device)
```

However, when training I get the following stack trace:

```
File "nn.py", line 641, in _iter_fit                                                                                                                                                                              
    outputs = self.net(inputs)                                                                                                                                                                                                                                                     
  File "torch/nn/modules/module.py", line 727, in _call_impl                                                                                                                                                                         
    result = self.forward(*input, **kwargs)                                                                                                                                                                                                                                        
  File "helpers/default_net.py", line 124, in forward                                                                                                                                                               
    output = self._forward_net(input)                                                                                                                                                                                                                                               
  File "torch/nn/modules/module.py", line 727, in _call_impl                                                                                                                                                                         
    result = self.forward(*input, **kwargs)                                                                                                                                                                                                                                        
  File "torch/nn/parallel/data_parallel.py", line 160, in forward                                                                                                                                                                    
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])                                                                                                                                                                                                          
  File "torch/nn/parallel/data_parallel.py", line 165, in replicate                                                                                                                                                                  
    return replicate(module, device_ids, not torch.is_grad_enabled())                                                                                                                                                                                                              
  File "torch/nn/parallel/replicate.py", line 88, in replicate                                                                                                                                                                       
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)                                                                                                                                                                                                           
  File "torch/nn/parallel/replicate.py", line 71, in _broadcast_coalesced_reshape                                                                                                                                                    
    tensor_copies = Broadcast.apply(devices, *tensors)                                                                                                                                                                                                                             
  File "torch/nn/parallel/_functions.py", line 22, in forward                                                                                                                                                                        
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)                                                                                                                                                                                                                    
  File "torch/nn/parallel/comm.py", line 56, in broadcast_coalesced                        
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)                                                                                                                                                                                                            
RuntimeError: NCCL Error 2: unhandled system error 
```

With this additional info dump from NCCL:

```
78244:78244 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation                                                                                                                                                                                                                                                                                                                                                                                                                                             
78244:78244 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]                                                                                                                                                                                                   
78244:78244 [0] NCCL INFO Using network Socket                                                                                                                                                                                                                               
NCCL version 2.7.8+cuda11.0                                                                                                                                                                                                                                                        
78244:78465 [0] NCCL INFO Call to connect returned Connection timed out, retrying                                                                                                                                                                                            
78244:78466 [1] NCCL INFO Call to connect returned Connection timed out, retrying                                                                                                                                                                                            
78244:78465 [0] NCCL INFO Call to connect returned Connection timed out, retrying                                                                                                                                                                                            
78244:78466 [1] NCCL INFO Call to connect returned Connection timed out, retrying                                                                                                                                                                                                                                                                                                                                                                                                                           
78244:78465 [0] include/socket.h:403 NCCL WARN Connect failed : Connection timed out                                                                                                                                                                                                                                                                                                                                                                                               
78244:78466 [1] include/socket.h:403 NCCL WARN Connect failed : Connection timed out                                                                                                                                                                   
78244:78466 [1] NCCL INFO bootstrap.cc:95 -> 2                                                                                                                                                                                                                               
78244:78466 [1] NCCL INFO bootstrap.cc:309 -> 2                                                                                                                                                                                                                              
78244:78466 [1] NCCL INFO init.cc:555 -> 2                                                                                                                                                                                                                                   
78244:78466 [1] NCCL INFO init.cc:840 -> 2                                                                                                                                                                                                                                   
78244:78465 [0] NCCL INFO bootstrap.cc:95 -> 2                                                                                                                                                                                                                               
78244:78466 [1] NCCL INFO group.cc:73 -> 2 [Async thread]                                                                                                                                                                                                                    
78244:78465 [0] NCCL INFO bootstrap.cc:309 -> 2                                                                                                                                                                                                                              
78244:78465 [0] NCCL INFO init.cc:555 -> 2                                                                                                                                                                                                                                   
78244:78465 [0] NCCL INFO init.cc:840 -> 2                                                                                                                                                                                                                                   
78244:78465 [0] NCCL INFO group.cc:73 -> 2 [Async thread]                                                                                                                                                                                                                    
78244:78244 [0] NCCL INFO init.cc:906 -> 2    
````

Any ideas on what might be happening? Feedback will be deeply appreciated.

**Comment by ptrblck** [comment]
Based on the NCCL output:
```
NCCL INFO Call to connect returned Connection timed out, retrying      
```
it seems your setup has trouble to create a connection.
Could you take a look at [the network interface docs](https://pytorch.org/docs/stable/distributed.html#choosing-the-network-interface-to-use) and check if specifying the right interfaces would solve this issue?

**Comment by George3d6** [comment]
As far as I'm aware though, both GPUs are connected to the motherboard via PCIE (no nvlink), how could that result in a network error ?

I will take a look at the docs though.

**Comment by blair2020** [comment]
Hello, I've met exactly the same problem with you now. Would you plz share your solution? Thx in advance!

**Comment by George3d6** [comment]
As of yet we were unable to find a cause.

**Comment by maqy1995** [comment]
> As of yet we were unable to find a cause.

Hi, I met the same problem. 
What's your version of pytorch? In my environment, the problem occurs when I use pytorch 1.7.x. But I can run my code successfully used pytorch 1.6.

**Comment by conansherry** [comment]
I, got the same problem.
my platform AMD 5800-X570
![image](https://user-images.githubusercontent.com/2148224/105567259-c4d35480-5d6b-11eb-9b35-364e2d1dc4b4.png)

code:
`
import torch
import numpy as np
import cv2
import os
import torchvision.models as models

if __name__ == '__main__':
    resnet18 = models.resnet18()
    resnet18.cuda(0)
    resnet18 = torch.nn.DataParallel(resnet18, device_ids=[0, 1])
    while True:
        t0 = cv2.getTickCount()
        example_input = torch.zeros((64, 3, 224, 224), dtype=torch.float32)
        output = resnet18(example_input)
        print('cost', (cv2.getTickCount() - t0) / cv2.getTickFrequency() * 1000)
`

error:
![image](https://user-images.githubusercontent.com/2148224/105567281-019f4b80-5d6c-11eb-832a-8c9b14e54170.png)

**Comment by blair2020** [comment]
> As of yet we were unable to find a cause.

I can run my code successfully used pytorch 1.6,too.

**Comment by blair2020** [comment]
> I, got the same problem.
> my platform AMD 5800-X570
> ![image](https://user-images.githubusercontent.com/2148224/105567259-c4d35480-5d6b-11eb-9b35-364e2d1dc4b4.png)
> ![image](https://user-images.githubusercontent.com/2148224/105567373-622e8880-5d6c-11eb-993b-fe5ffb133b6a.png)
> 
> code:
> 
> ```
> import torch
> import numpy as np
> import cv2
> import os
> import torchvision.models as models
> 
> if __name__ == '__main__':
>     resnet18 = models.resnet18()
>     resnet18.cuda(0)
>     resnet18 = torch.nn.DataParallel(resnet18, device_ids=[0, 1])
>     while True:
>         t0 = cv2.getTickCount()
>         example_input = torch.zeros((64, 3, 224, 224), dtype=torch.float32)
>         output = resnet18(example_input)
>         print('cost', (cv2.getTickCount() - t0) / cv2.getTickFrequency() * 1000)
> ```
> 
> error:
> ![image](https://user-images.githubusercontent.com/2148224/105567281-019f4b80-5d6c-11eb-832a-8c9b14e54170.png)

i don't know why but pytorch 1.6 is ok

**Comment by brightbsit** [comment]
How can you run pytorch version 1.6 with rtx3090??
doesn't it support below 1.6?

I'm also using 2 rtx3090 and i got warning
` " UserWarning: GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation."`

after the warning message, it doesn't show up any logs.

**Comment by ptrblck** [comment]
Since NCCL raises a system error, you could check the [NCCL tests](https://github.com/nvidia/nccl-tests) and see, if these are working.
To get more information about the issue, you can use the env var `NCCL_DEBUG=INFO`, which should show where NCCL is failing on your system.

**Comment by brightbsit** [comment]
@ptrblck i found this. https://github.com/NVIDIA/nccl/issues/442. I'm using wsl2. That's why i can't run it..

**Comment by kapsner** [comment]
I get the same error when trying to train on >1 GPUs using pytorch 1.7.1 inside docker (official nvidia/cuda base image) on a ubuntu 20.04 host with cuda 11.0

(Training on 1 GPU is working as expected with this setup)

Is there already a solution?

**Comment by WenM1222** [comment]
Is there any progress on this issue? I have met same problem when I run with >2 rtx 3090 GPUs, but no problem when i ran with 2 rtx 3090 GPUs.

**Comment by brando90** [comment]
I'd also like to know since it might be related to:

https://github.com/pytorch/pytorch/issues/54550

**Comment by del2z** [comment]
It seems like a bug related to ports. I got NCCL info `include/socket.h:403 NCCL WARN Connect to 42.186.72.186<54716> failed : Connection timed out`. However, the port 54716 is not one of connected ports between two nodes, according to output of `netstat | grep <MASTER_PORT>` in machine 42.186.72.186. I have no idea how this happened.

**Comment by Wzw666888** [comment]
I met this problem...
![image](https://user-images.githubusercontent.com/82068553/114165314-e4d3e680-995e-11eb-8e62-a2c9849567c7.png)
my pytorch version is 1.8. cuda is 10.1...

**Comment by del2z** [comment]
I've used DDP in multi-node training, NCCL timeout error seemed like a failure in setuping sockets through network interface. If used in docker, `--ipc=host` and `--network=host` should be set in order to avoid port mapping and allow communication among processes.

When I launched DDP training using network interfaces like 'eth*' by exporting 'NCCL_SOCKET_IFNAME=eth*', training was successfully started. Note that 'eth*' in both nodes are not virtual interfaces. However, adding another node that only virtual interface is available, DDP training failed. Command `ls -lt /sys/class/net/` could check whether an interface is virtual or not. To sum up, I suspect the failure may be a problem related to (virtual) network interface.

Funtunately, GLOO backend works in such seneraio, and becomes my only option.

**Comment by sumethy** [comment]
> I get the same error when trying to train on >1 GPUs using pytorch 1.7.1 inside docker (official nvidia/cuda base image) on a ubuntu 20.04 host with cuda 11.0
> 
> (Training on 1 GPU is working as expected with this setup)
> 
> Is there already a solution?

I had the same problem using image nvcr.io/nvidia/pytorch:20.09-py3. For me passing `--ipc=host` (from fairseq's README) option to `docker run` fixed the problem.

**Comment by charlevr** [comment]
> As of yet we were unable to find a cause.

Any progress on this? I ran into the same error and switching to PyTorch version from 1.8.1 to 1.6 worked for my code. I was trying to run the Trainer() function from the transformers library using four 2080ti's.

**Comment by curiosity2** [comment]
> Based on the NCCL output:
> 
> ```
> NCCL INFO Call to connect returned Connection timed out, retrying      
> ```
> 
> it seems your setup has trouble to create a connection.
> Could you take a look at [the network interface docs](https://pytorch.org/docs/stable/distributed.html#choosing-the-network-interface-to-use) and check if specifying the right interfaces would solve this issue?

Thank you, it worked for me.

**Comment by embray** [comment]
I've run into a similar problem after upgrading some code using `DataParallel` from an older version of PyTorch.  I'm still searching the documentation, but I wonder how `DataParallel` (as opposed to `DistributedDataParallel`) uses the new (to me) `torch.distributed` stuff in the implementation when it wasn't before.

What's interesting is that I only run into this problem when running the tests for my package in parallel (on multiple processes) using pytest-xdist.  So it seems that NCCL is getting confused, possibly, because because the process in which the model is being trained is not the parent process of the process group in this case.  Otherwise it works fine.

**Comment by hamid-ramezani** [comment]
I have the same problem.

**Comment by erzaliator** [comment]
Ran into the same issue while running on my docker on multiple Titan X's. Generally I reducing the number of GPUs works for me. But sometimes, I get it while running on 2 GPUs as well. Any solution for that?

**Comment by vietvo89** [comment]
> I've run into a similar problem after upgrading some code using `DataParallel` from an older version of PyTorch. I'm still searching the documentation, but I wonder how `DataParallel` (as opposed to `DistributedDataParallel`) uses the new (to me) `torch.distributed` stuff in the implementation when it wasn't before.
> 
> What's interesting is that I only run into this problem when running the tests for my package in parallel (on multiple processes) using pytest-xdist. So it seems that NCCL is getting confused, possibly, because because the process in which the model is being trained is not the parent process of the process group in this case. Otherwise it works fine.
> 
> **Update:** In case it helps anyone else. I found (thanks to setting `NCCL_DEBUG=INFO`) that it was this problem: [NVIDIA/nccl#290](https://github.com/NVIDIA/nccl/issues/290) since I was running in a Docker container. I suspect in this case the only difference between using pytest-xdist and not is that with multiple processes I more quickly ran into Docker's default (low) `/dev/shm` size limit of 64MB.
> 
> I wish I still could find more technical information on how `DataParallel` uses NCCL but I'll poke around the source I guess.
> 
> **Update 2:** I see now that this has less to do with DDP and more to do with the fact that `DataParallel` is using some more generic functions like `broadcast_coalesced` to send the model to multiple GPUs, and that that function uses NCCL (even for multiple GPUs on the same host) if PyTorch is compiled to support it.

I ran into the same problem when using Dataparallel. I found some solutions but have not tested yet. However, what I did is initialize environment parameters like below, particularly cuda visible devices can be 0 or 1 if you have more than one GPU and which one has free memory. I hope that helps.

- os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
- os.environ["CUDA_VISIBLE_DEVICES"]="1"

**Comment by zhLawliet** [comment]
+1  pytorch 1.9.1 cuda10.2
![image](https://user-images.githubusercontent.com/17424385/135010951-6af2cedf-c159-4178-b62f-b71efe119e98.png)

**Comment by XDUWQ** [comment]
I change the verision of pytorch and solve this same problem.

**Comment by Urheen** [comment]
@XDUWQ  hey bro which version of PyTorch you are using?

**Comment by lmz123321** [comment]
I met the same problem with PyTorch 1.7.0 and CUDA 10.1.
 I degrade PyTorch into 1.6.0 and solve the problem.
