### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the driver, when use pytorch 1.7 on linux with RTX 3090

### ISSUE THREAD

**Issue by Dingseewhole** [pytorch/pytorch#49161]
## 🐛 Bug

**RuntimeError: CUDA error: no kernel image is available for execution on the driver when use Pytorch 1.7 on Linux with RTX 3090 + ubuntun 20 + GPU driver 455.45 + CUDA 11.0**
I am a skilled user of pytorch-gpu, recently I purchased an RTX 3090 server, but the bug with pytorch 1.7 and RT 3090 makes me mad. I try a lot of experiments to figure it out, but I failed. You can reproduce the bug when you do as follow
## To Reproduce

1. First I install the RTX 3090 + ubuntu 20 + GPU driver 455 + CUDA 11.1 (both are suggested by Nvidia official for the RTX 3090) on my host machine which has RTX 3090 GPU. When I use `nvidia-smi` the GPU information can be shown correctly.
2. Second, I build a docker container by an nvidia-docker official image on the docker hub (You can pull it by `docker pull nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04`). And install the pytorch 1.7.  **In this container** I can use `nvidia-smi` to check the GPU's information, and the `torch.cuda.is_available()=True`. I can also build a tensor on GPU by `torch.zeore(1).cuda`, and concate two torch.cuda.tensor by `torch.cat(a.cuda(),b.cuda())`.
3. But when I run my deep learning python script which can run correctly on **RTX 2080 + ubuntu 20 + GPU driver 455 + CUDA 10.2 + cuDnn8 + pytorch1.7**, the bug occurs. The information of the bug is **RuntimeError: CUDA error: no kernel image is available for execution on the driver**.
4. I am pretty sure that my python script has no bugs, because I have run the same one on many different servers and environments (pytorch + RTX 2080/GTX 1080/Titan X/K80/Tesla V100). And it never occurs bugs.
5. I have also tried different nvidia-docker offical images with CUDA 11.1 +pytorch 1.7 or CUDA 10.1 +pytorch 1.7. But it doesn't help.

1. Use **RTX 3090 + ubuntu 20 + GPU driver 455 + CUDA 11.0 + cuDnn8 + pytorch1.7 + python 3.7** the bug is **RuntimeError: CUDA error: no kernel image is available for execution on the driver**
2. . Use **RTX 3090 + ubuntu 20 + GPU driver 455 + CUDA 11.1 + cuDnn8 + pytorch1.7 + python 3.7** the bug is **RuntimeError: CUDA error: no kernel image is available for execution on the driver**
3. Use **RTX 3090 + ubuntu 20 + GPU driver 455 + CUDA 10.2 + cuDnn8 + pytorch1.7 + python 3.7** the bug is **RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:116**
4.Use **RTX 3090 + ubuntu 20 + GPU driver 455 + CUDA 11.0 + cuDnn8 + pytorch1.7 + python 3.7** ,it also shows RTX 2090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
5. 
![image](https://user-images.githubusercontent.com/44332832/101777637-b0eccf80-3aea-11eb-9b85-6018a14f8665.png)

## Expected behavior

I want to run a PyTorch script on RTX 3090 with ubuntu.
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.7
 - OS (e.g., Linux): Linux ubuntun 20
 - How you installed PyTorch (`conda`, `pip`, source):I have tried:
1. pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
2. pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html
 - Build command you used (if compiling from source):
 - Python version:3.7
 - CUDA/cuDNN version:CUDA 11.0 +cuDNN 8
 - GPU models and configuration:RTX 3090
 - Any other relevant information:

## Additional context

cc @ngimel

**Comment by Dingseewhole** [comment]
![image](https://user-images.githubusercontent.com/44332832/101777690-c235dc00-3aea-11eb-899b-bdf9ca195213.png)
The bug picture is here

**Comment by ngimel** [comment]
The error message on your screen is quite clear, your pytorch installation does not support sm_86 compute capability. That said,  torch==1.7.0+cu110 supports 30xx gpus, so perhaps when you are installing torchvision or torchaudio, your pytorch version gets downgraded? When you are installing binary build of pytorch, your cuda or cudnn version don't matter, because pytorch uses its own.  
cc @malfet.

**Comment by malfet** [comment]
@Dingseewhole can you please see if the problem persists if you upgrade to PyTorch-1.7.1 that was released today?
Can you please re-run your training script with `CUDA_LAUNCH_BLOCKING=1` environment variable set to see what operation actually caused the exception.
And can you let me know if `python -c "import torch;print(torch.max(torch.rand((30,30),device='cuda')))"` command works on your RTX-3090 system?

**Comment by Dingseewhole** [comment]
> The error message on your screen is quite clear, your pytorch installation does not support sm_86 compute capability. That said, torch==1.7.0+cu110 supports 30xx gpus, so perhaps when you are installing torchvision or torchaudio, your pytorch version gets downgraded? When you are installing binary build of pytorch, your cuda or cudnn version don't matter, because pytorch uses its own.
> cc @malfet.

Thank you for your help!
I use the official PyTorch pip install method `install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html` to build my pytorch environment. And after that, I didn't change my torch version or torchvision version or torchaudio version. So I guess my pytorch version was not get downgraded?
Here is my `pip list` result , you can see the all packages version my python script using,
![image](https://user-images.githubusercontent.com/44332832/101856124-a8a29c00-3b9f-11eb-90b5-c19ca88cf31f.png)

**Comment by malfet** [comment]
@Dingseewhole , try upgrading to 1.7.1 by using 
`pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by Dingseewhole** [comment]
> @Dingseewhole , try upgrading to 1.7.1 by using
> `pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`

Thank you for your help. When I upgrade my pytorch 1.70 to 1.71, the bug disappeared.
Thanks!

**Comment by gohguodong** [comment]
Hi, i am experiencing similar issue with the rtx3080. i use the command below to install the pytorch
`pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 -f https://download.pytorch.org/whl/torch_stable.html`

below are the details of my environment:
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.1+cu110
[pip3] torchvision==0.8.2+cu110
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] torch                     1.7.1+cu110              pypi_0    pypi
[conda] torchvision               0.8.2+cu110              pypi_0    pypi

the no kernel image error still persists in pytorch 1.7.1. FYI, i am using WSL2. any idea what went wrong?

**Comment by YUyttendaele** [comment]
@gohguodong I'm not sure, but your nvidia driver may be incompatible with CUDA 11.0. Check https://docs.nvidia.com/deploy/cuda-compatibility/index.html for more info.

**Comment by maltevb** [comment]
Hey guys,
i am also facing the same problem with my RTX 3090.
The specs are:

torch = 1.7.1
cuda = 11.2
nvidia driver = 460.32.03
torchvision = 0.8.2

Anybody has an idea how to fix it? Tried also torch = 1.7.0, but the error still occurs.
Would appreciate if you share your experience.

See the full error message below:
_Traceback (most recent call last):
   File "/home/user/20210129_instance_nn_tuned/years/code/solver.py", line 101, in train
    y_predicted = model(x_train).flatten() # flatten to (N,) otherwise it has shape (N,1) and loss function throws a warning
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/20210129_instance_nn_tuned/years/code/nn_architecture.py", line 53, in forward
    out = self.model(x)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
**RuntimeError: CUDA error: no kernel image is available for execution on the device_**

**Comment by hszhoushen** [comment]
> Hey guys,
> i am also facing the same problem with my RTX 3090.
> The specs are:
> 
> torch = 1.7.1
> cuda = 11.2
> nvidia driver = 460.32.03
> torchvision = 0.8.2
> 
> Anybody has an idea how to fix it? Tried also torch = 1.7.0, but the error still occurs.
> Would appreciate if you share your experience.
> 
> See the full error message below:
> Traceback (most recent call last):
> File "/home/user/20210129_instance_nn_tuned/years/code/solver.py", line 101, in train
> y_predicted = model(x_train).flatten() # flatten to (N,) otherwise it has shape (N,1) and loss function throws a warning
> File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/user/20210129_instance_nn_tuned/years/code/nn_architecture.py", line 53, in forward
> out = self.model(x)
> File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
> input = module(input)
> File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 93, in forward
> return F.linear(input, self.weight, self.bias)
> File "/home/user/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1690, in linear
> ret = torch.addmm(bias, input, weight.t())
> 
> **RuntimeError: CUDA error: no kernel image is available for execution on the device**

Hi, did you solve the problem? I have a similar configuration and with the same problem.
RTX3090
torch = 1.7.1
cuda = 11.1
nvidia driver = 460.32.03
torchvision = 0.8.2

**Comment by linhduongtuan** [comment]
I am struggling with the same issue when my machine with RTX 3090 is running on Ubuntu 20.04, CUDA = 11.2, Nvidia-driver = 460.39, Pytorch from "pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html" (also try to using Nightly version) ==> Error messenger:
"RuntimeError: CUDA error: no kernel image is available for execution on the device"

One important thing, before my machine was updated automatically, everything was fine. Later, it is collapsed.
Furthermore, when I call nvidia-smi the message also indicates an error at "Volatile Uncorr. ECC ...."  you can see my attach image.
![Screenshot from 2021-02-28 16-37-30](https://user-images.githubusercontent.com/22388092/109414071-802e7f00-79e3-11eb-84b9-945e3fea7232.png)

**Comment by maltevb** [comment]
Hey @linhduongtuan,
i had similar issues after an ubuntu update.
I had to reinstall the nvidia drivers, cuda (v. 11.2) and also reinstalled torch as mentioned by @malfet using `pip3 install torch==1.7.1+cu110 torchvision==0.8.2+cu110 -f https://download.pytorch.org/whl/torch_stable.html`.
I know that is was the combination of this three as just updating torch did not solve the problem.
Hope i could help.

**Comment by linhduongtuan** [comment]
Dear @MaltevB, Many thank for your suggestion. I will try and hope it fixed


Linh

**Comment by linhduongtuan** [comment]
Dear @maltevb I tried as you suggested, but it doesn’t work. The machine cannot install CUDA 11.2.32 which I downloaded from Nvidia homepage. If I install directly from “additional drivers” tool, it is recieved CUDA 11.2.39. The most recent version leads to an error like my description above. 


Linh

**Comment by sk-g** [comment]
@linhduongtuan if you are still facing the problem, please read my comment 

https://github.com/pytorch/pytorch/issues/31285#issuecomment-787582949

**Comment by linhduongtuan** [comment]
@Sanjay Krishna Gouda, many thank for your suggestion. I will try to fix the issue.
Linh

**Comment by linhduongtuan** [comment]
@sk-g it doesn't work. I am really upset, and don't know why? It is the first time I face with problems using PyTorch ~ CUDA

**Comment by rushirajsherlocked** [comment]
> Hey @linhduongtuan,
> i had similar issues after an ubuntu update.
> I had to reinstall the nvidia drivers, cuda (v. 11.2) and also reinstalled torch as mentioned by @malfet using `pip3 install torch==1.7.1+cu110 torchvision==0.8.2+cu110 -f https://download.pytorch.org/whl/torch_stable.html`.
> I know that is was the combination of this three as just updating torch did not solve the problem.
> Hope i could help.

This worked for me! :)

**Comment by iamsaurabh007** [comment]
I am getting same error, Here is logs upon running above python script

Collecting environment information...
PyTorch version: 1.8.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce 920M
Nvidia driver version: 460.39
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.0+cu111
[pip3] torchaudio==0.8.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.9.0+cu111
[conda] Could not collect

**Comment by malfet** [comment]
@iamsaurabh007 , this was fixed in torch-1.8.1, please update your pip install

**Comment by tensorfoo** [comment]
> @iamsaurabh007 , this was fixed in torch-1.8.1, please update your pip install

Sorry but i'm still getting the same error even on torch-1.8.1.

**Comment by hero-y** [comment]
I also get the same error on torch-1.8.1

**Comment by jamfly** [comment]
I also got the same error on torch 1.8.1, coda 11.1, A5000

**Comment by DPS0340** [comment]
> import torch print(torch.version.cuda) # check cuda version
> 
> # Install only latest version torch with cuda
> pip3 install torch==1.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

+1

also if you're using torchvision, you have to install from cuda 11.3 repo.

```bash
pip install torch==1.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
pip install torchvision==0.11.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

**Comment by GuShizhang** [comment]
> I also get the same error on torch-1.8.1, cuda11.1, 3060

have you resolved this issue??i also have met the same issue, thanks

**Comment by MiuGod0126** [comment]
> @Dingseewhole , try upgrading to 1.7.1 by using `pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`

thank you, this method worked.

**Comment by kvnptl** [comment]
> import torch print(torch.version.cuda) # check cuda version
> # Install only latest version torch with cuda
> 
> pip3 install torch==1.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

Thanks, it worked for me. I checked the latest torch and torchvision version with cuda from the given link. Stable versions list: https://download.pytorch.org/whl/cu113/torch_stable.html

Below versions solved the error,
`pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by lrs01** [comment]
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
如果你发现因为使用torch版本对应的torchaudio不能胜任一些任务，你可以尝试如下：
pip install torch==1.11.0+cu115  torchaudio===0.11.0 -f https://download.pytorch.org/whl/torch_stable.html
就是torch的版本要和torchaudio的版本尽量一致

**Comment by lrs01** [comment]
pip install torch==1.11.0+cu115 torchvision==0.8.2+cu110 torchaudio===0.11.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by ANTZ314** [comment]
I have uninstalled all versions of torch from the environment, but when running the above suggested:
```
pip install torch==1.7.1+cu110 -f https://download.pytorch.org/whl/torch_stable.html
```
I am getting this:
```
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.7.1+cu110 (from versions: 1.11.0, 1.11.0+cpu, 1.11.0+cu102, 1.11.0+cu113, 1.11.0+cu115, 1.11.0+rocm4.3.1, 1.11.0+rocm4.5.2, 1.12.0, 1.12.0+cpu, 1.12.0+cu102, 1.12.0+cu113, 1.12.0+cu116, 1.12.0+rocm5.0, 1.12.0+rocm5.1.1, 1.12.1, 1.12.1+cpu, 1.12.1+cu102, 1.12.1+cu113, 1.12.1+cu116, 1.12.1+rocm5.0, 1.12.1+rocm5.1.1, 1.13.0, 1.13.0+cpu, 1.13.0+cu116, 1.13.0+cu117, 1.13.0+cu117.with.pypi.cudnn, 1.13.0+rocm5.1.1, 1.13.0+rocm5.2)
ERROR: No matching distribution found for torch==1.7.1+cu110
```
Even though I can see the package in the archive: [1.7.1+cu110](https://download.pytorch.org/whl/torch/)

I previously had torch=1.12.0 with CUDA=11.7

Outside of the env I still have "nvidia-smi":
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   34C    P0    22W /  N/A |      5MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2662      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

```

**Comment by lrs01** [comment]
I think you should get the matched torch and coda,you can visit it in https://pytorch.org
