### ISSUE TITLE
Error with NVIDIA graphic driver 465.21 

### ISSUE THREAD

**Issue by jeonghwaYoo** [pytorch/pytorch#49592]
## 🐛 Bug

I did not install cuda and cudnn directly, but installed and running in anaconda.
I downloaded the nvidia driver to use cuda in wsl2.
Windows builds were also updated to 20241.
After installing the nvidia driver, the following error appears in the original anaconda.

>  File "C:\Users\2020498\Anaconda3\envs\torch-gpu\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\2020498\Anaconda3\envs\torch-gpu\lib\site-packages\torch\nn\parallel\data_parallel.py", line 157, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "C:\Users\2020498\Anaconda3\envs\torch-gpu\lib\site-packages\torch\nn\parallel\data_parallel.py", line 168, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "C:\Users\2020498\Anaconda3\envs\torch-gpu\lib\site-packages\torch\nn\parallel\scatter_gather.py", line 36, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "C:\Users\2020498\Anaconda3\envs\torch-gpu\lib\site-packages\torch\nn\parallel\scatter_gather.py", line 28, in scatter
    res = scatter_map(inputs)
  File "C:\Users\2020498\Anaconda3\envs\torch-gpu\lib\site-packages\torch\nn\parallel\scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "C:\Users\2020498\Anaconda3\envs\torch-gpu\lib\site-packages\torch\nn\parallel\scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "C:\Users\2020498\Anaconda3\envs\torch-gpu\lib\site-packages\torch\nn\parallel\_functions.py", line 92, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "C:\Users\2020498\Anaconda3\envs\torch-gpu\lib\site-packages\torch\nn\parallel\comm.py", line 186, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: CUDA error: an illegal memory access was encountered

When I delete the nvidia driver it works again well. 

## Expected behavior

I want to use the 465.12 graphics driver (https://developer.nvidia.com/cuda/wsl/download) for using cuda in wsl2 with pytorch of the original environment.

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): windows10 
 - How you installed PyTorch (`conda`, `pip`, source): pip 
 - Build command you used (if compiling from source): 
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1.24
 - GPU models and configuration: Titan XP 
 - Any other relevant information: Windows 10 BUILD 20241, Anaconda 3

cc @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by peterjc123** [comment]
You are using both a preview version of Windows 10 and Nvidia driver. So, it's hard to say whether it's our problem or not. Would you please try whether the CUDA 11 variant of PyTorch works?

**Comment by xsacha** [comment]
I have encountered this same error on the same driver version and can explain what is happening.
I didn't report this to Nvidia (but they probably already know).

This driver (465.12) has a bug in NVDEC when assigning the CUDA memory after decoding a frame.

**Comment by jeonghwaYoo** [comment]
@peterjc123 I think it is not pytorch problem, because similar error occurred in tensorflow. Thank you 
@xsacha Thank you for your reply. How did you solve this problem? How could I use cuda in wsl without 465.12 driver?

**Comment by xsacha** [comment]
@jeonghwaYoo I downgraded the driver to 460 WSL2 driver and it works.

**Comment by jeonghwaYoo** [comment]
@xsacha I couldn't find other preview versions on the nvidia official website, but I found the 460.15 installation file on the internet. I'll try with it. Thank you!

**Comment by jeonghwaYoo** [comment]
Tha
