### ISSUE TITLE
torch.backends.cudnn.CuDNNError: 8: b'CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by Rhuax** [pytorch/pytorch#4996]
- OS: Ubuntu 17
- PyTorch version: 0.3.0.post4
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.6.3
- CUDA/cuDNN version: CUDA 9.0 cuDNN 7
- GPU models and configuration: gtx950m 2 GB

```
Traceback (most recent call last):
  File "/opt/pycharm-community-2017.3.1/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/opt/pycharm-community-2017.3.1/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-community-2017.3.1/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-community-2017.3.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/crow/PycharmProjects/text-summarization/train.py", line 200, in <module>
    trainIters(encoder1, attn_decoder1, 7, print_every=100)
  File "/home/crow/PycharmProjects/text-summarization/train.py", line 169, in trainIters
    loss = train(input_variable, target_variable, encoder,decoder, encoder_optimizer, decoder_optimizer, criterion)
  File "/home/crow/PycharmProjects/text-summarization/train.py", line 54, in train
    encoder_output, encoder_hidden = encoder(e_i, encoder_hidden)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/crow/PycharmProjects/text-summarization/encoder.py", line 18, in forward
    output,hidden=self.gru(output,hidden)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 169, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/_functions/rnn.py", line 385, in forward
    return func(input, *fargs, **fkwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/function.py", line 328, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/function.py", line 350, in forward
    result = self.forward_extended(*nested_tensors)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/_functions/rnn.py", line 294, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/usr/local/lib/python3.6/dist-packages/torch/backends/cudnn/rnn.py", line 305, in forward
    ctypes.c_void_p(fn.reserve.data_ptr()), fn.reserve.size(0)
  File "/usr/local/lib/python3.6/dist-packages/torch/backends/cudnn/__init__.py", line 283, in check_error
    raise CuDNNError(status)
torch.backends.cudnn.CuDNNError: 8: b'CUDNN_STATUS_EXECUTION_FAILED'
```

I think this error is not related to my code since not modifying my source code and running again sometimes doesn't cause this error to appear. So every time I see it I just try to run again.
Can someone help me?

**Comment by SsnL** [comment]
This is a cudnn error status. Could you provide more information such as your script so we can have a rough idea what's going on?

**Comment by Rhuax** [comment]
https://github.com/Rhuax/text-summarization

I run `train.py` .

**Comment by ezyang** [comment]
This is really old, and I'm going to guess that we've fixed it in the last two years. If there are still problems, please open a new issue.
