### ISSUE TITLE
Conflict with cudatoolkit 11.0.221

### ISSUE THREAD

**Issue by kcarnold** [pytorch/pytorch#51080]
## 🐛 Bug

If `cudatoolkit` 11.0.221 is installed, `python -c 'import torch'` fails with

```
OSError: /home/ka37/anaconda3/envs/fail/lib/python3.8/site-packages/torch/lib/../../../../libcublas.so.11: symbol free_gemm_select version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
```

This situation does not arise when installing `pytorch` using the exact command on the website, but it can arise if other packages bring it in.

This is probably actually a bug in Anaconda (and I think it's `main`, not `conda-forge`), but `pytorch` shows the problem clearly so I'm reporting here first.

## To Reproduce

There are two paths to get this behavior:

* *explicit*: `conda create -n fail -c pytorch -c conda-forge pytorch cudatoolkit=11.0.221`
* *implicit*: `mamba create -n fail -c pytorch -c conda-forge pytorch cudatoolkit=11.0`

(it seems that `mamba` prefers the latest version of a package.)

Both ways succeed if `cudatoolkit=11.0.3` is specified instead.

## Environment

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1660 SUPER
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.0.221             h6bb024c_0
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py38h1e0a361_2    conda-forge
[conda] mkl_fft                   1.2.0            py38hab2c0dc_1    conda-forge
[conda] mkl_random                1.2.0            py38hc5bc63f_1    conda-forge
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.7.1           py3.8_cuda11.0.221_cudnn8.0.5_0    pytorch
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @seemethere @malfet @walterddr @csarofeen @ptrblck @xwang233 @ngimel

**Comment by johndpope** [comment]
I'm seeing this without a conda install / just using a vanilla cudatoolkit install / but then pytorch + miniconda
is there a command I can run to fix installation? this didn't work.

`conda install cudatoolkit=11.0.3
`

**Comment by seemethere** [comment]
I've created https://github.com/pytorch/builder/pull/632 to solve for the correct minimum version of cudatoolkit to get installed.

Will leave this open until we have nightly binaries with this change insert. Will follow up with an update after that happens.

**Comment by kcarnold** [comment]
Unfortunately I think it's the *newer* version that's broken.

**Comment by seemethere** [comment]
> Unfortunately I think it's the _newer_ version that's broken.

In that case I've submitted another patch where `11.0.221` cannot be the version installed with our binaries: https://github.com/pytorch/builder/pull/635

**Comment by seemethere** [comment]
Looks like my initial patch of setting the `cudatoolkit>=11.0,<11.1,!=11.0.221` didn't work correctly and resulted in https://github.com/pytorch/vision/issues/3342

I've submitted https://github.com/pytorch/builder/pull/642 as another patch to try out for this which turns the dependency into `cudatoolkit>=11.0,<11.0.221`

**Comment by YukeWang96** [comment]
Using `pip` works fine for me.

```
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by dinever** [comment]
> Using `pip` works fine for me.
> 
> ```
> pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
> ```

This worked for me. Thanks!

**Comment by seemethere** [comment]
This should be resolved now that we’re no longer producing CUDA 11.0 binaries and now only produce CUDA 11.1 binaries.

For nightlies use:
```
conda install -y -c conda-forge -c pytorch-nightly pytorch cudatoolkit=11.1
```

For stable binaries you’ll have to wait until our release of `v1.8.0` but after that you’ll be able to use:
```
conda install -y -c conda-forge -c pytorch pytorch cudatoolkit=11.1
```

If you’d like to test that experience right now you can use:

```
conda install -y -c conda-forge -c pytorch-test pytorch cudatoolkit=11.1
```

**Comment by mrgransky** [comment]
Installed pytorch with: `$ conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch`
Using miniconda3:
```
$ (py3_gpu) [alijanif@r14g07 OxfordRobotCar]$ conda info

     active environment : py3_gpu
    active env location : /projappl/project_2004072/miniconda3/envs/py3_gpu
            shell level : 1
       user config file : /users/alijanif/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.2=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /projappl/project_2004072/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /projappl/project_2004072/miniconda3/pkgs
                          /users/alijanif/.conda/pkgs
       envs directories : /projappl/project_2004072/miniconda3/envs
                          /users/alijanif/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/3.10.0-1062.33.1.el7.x86_64 rhel/7.7 glibc/2.17
                UID:GID : 10010334:10010334
             netrc file : None
           offline mode : False
```
```
$ (py3_gpu) [alijanif@r14g07 OxfordRobotCar]$ python -c "import torch; print(torch.__version__); print(torch.cuda.is_available())"
1.7.1
True
```

Using anaconda3:
```
$ (py37_gpu) [alijani@nag09 OxfordRobotCar]$ conda info

     active environment : py37_gpu
    active env location : /home/alijani/.conda/envs/py37_gpu
            shell level : 1
       user config file : /home/alijani/.condarc
 populated config files : /home/alijani/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.6.2.final.0
       virtual packages : __cuda=11.2
       base environment : /home/opt/anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/opt/anaconda3/pkgs
                          /home/alijani/.conda/pkgs
       envs directories : /home/alijani/.conda/envs
                          /home/opt/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.6.2 Linux/3.10.0-1160.2.2.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 21111:21111
             netrc file : /home/alijani/.netrc
           offline mode : False
```

```
$ (py37_gpu) [alijani@nag09 OxfordRobotCar]$ python -c "import torch; print(torch.__version__); print(torch.cuda.is_available())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/alijani/.conda/envs/py37_gpu/lib/python3.7/site-packages/torch/__init__.py", line 189, in <module>
    _load_global_deps()
  File "/home/alijani/.conda/envs/py37_gpu/lib/python3.7/site-packages/torch/__init__.py", line 142, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/alijani/.conda/envs/py37_gpu/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/alijani/.conda/envs/py37_gpu/lib/python3.7/site-packages/torch/lib/../../../../libcublas.so.11: symbol free_gemm_select, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
```
Does anyone know how to fix this with `anaconda3`?
Cheers,

**Comment by seemethere** [comment]
We will no longer be producing CUDA 11.0 binaries, please use the CUDA 11.1 binaries with:

```
conda install -y -c pytorch -c conda-forge cudatoolkit=11.1 pytorch torchvision torchaudio
```

**Comment by GMetola** [comment]
Following these steps:
> conda create --name my_name
> conda activate my_name
> conda install python=3.7.10
> conda install cudatoolkit=11.0.3
> pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html

I got:
> Successfully installed numpy-1.20.1 pillow-8.1.2 torch-1.8.0 torchaudio-0.8.0 torchvision-0.9.0 typing-extensions-3.7.4.3

But it automatically installed normal torch, **not** torch-x.x.x.dev...-**cu110**, so I also got an **error**:
> AssertionError: Torch not compiled with CUDA enabled

After many tries I **solved the error** with:
> conda create --name my_name2
> conda activate my_name2
> conda install python=3.7.10
> conda install cudatoolkit=11.0.3

I **downloaded** from https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html the packages I needed, the last ones with python37 and with cu110 in the name. And then installed them with pip:
> pip install torch-1.8.0.dev20210208+cu110-cp37-cp37m-win_amd64.whl
Successfully installed numpy-1.20.1 torch-1.8.0.dev20210208+cu110 typing-extensions-3.7.4.3
pip install torchvision-0.9.0.dev20210211+cu110-cp37-cp37m-win_amd64.whl
Successfully installed pillow-8.1.2 torchvision-0.9.0.dev20210211+cu110

Correct output for me:
>>> import torch
>>> import torchvision
>>> torch.cuda.get_device_name()
'GeForce RTX 3060'

In case it can help you:
```
# packages in environment at C:\Users\metol\.conda\envs\swecomic:
#
# Name                    Version                   Build  Channel
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py37h03978a9_1    conda-forge
cudatoolkit               11.0.3               h3f58a73_8    conda-forge
numpy                     1.20.1                   pypi_0    pypi
openssl                   1.1.1j               h8ffe710_0    conda-forge
pillow                    8.1.2                    pypi_0    pypi
pip                       21.0.1           py37haa95532_0
python                    3.7.10               h6244533_0
python_abi                3.7                     1_cp37m    conda-forge
setuptools                52.0.0           py37haa95532_0
sqlite                    3.33.0               h2a8f88b_0
torch                     1.8.0.dev20210208+cu110          pypi_0    pypi
torchvision               0.9.0.dev20210211+cu110          pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py37_0
zlib                      1.2.11               h62dcd97_4
```

**Comment by rgommers** [comment]
@seemethere I think this can be closed, right?

**Comment by karliell** [comment]
> Using `pip` works fine for me.
> 
> ```
> pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
> ```

This one works for me! Even on cuda 11.3

**Comment by seemethere** [comment]
> @seemethere I think this can be closed, right?

Yup I believe this can be closed

**Comment by austindimmer** [comment]
I ran into this issue today 

I resolved it with the following commands:

```bash
conda deactivate
conda env remove -n torchaudio
conda clean --all
conda create --name torchaudio -y python=3.8.13
conda install pytorch torchvision torchaudio cudatoolkit=11.7 -c pytorch -c conda-forge
```

**Comment by bsac0** [comment]
I wasn't using CONDA and had an VENV setup in project directory. I think there's some problem with installation, as I got the same error. Resolved through pip reinstall:

`pip install torch==1.12.1+cu102 torchvision==0.13.1+cu102 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu102`

**Comment by brando90** [comment]
@seemethere what is pip comand for this?

**Comment by brando90** [comment]
ANSWER: this should help find the answer: https://stackoverflow.com/questions/74394695/how-does-one-fix-when-torch-cant-find-cuda-error-version-libcublaslt-so-11-no/74394696#74394696

**Comment by realliyifei** [comment]
```
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
```

This also works for me. However, in my code I have to install `functorch` as well, which would then upgrade the torch from `1.7.1+cu110` to `1.13.0` and this same error occurs again :(

**Comment by RainEggplant** [comment]
Just run:

```shell
conda install cudatoolkit=11.0.3 -c conda-forge
```
