### ISSUE TITLE
torch.cuda.is_available() returns False

### ISSUE THREAD

**Issue by SimplyLucKey** [pytorch/pytorch#51858]
I have GTX 1050ti on laptop and when I run `torch.cuda.is_available()` it returns `False`.

`nvcc --version`
```
C:\WINDOWS\system32>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:48_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.relgpu_drvr445TC445_37.28540450_0
```

My `nvidia-smi`

```
Sun Feb  7 04:16:50 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 461.40       Driver Version: 461.40       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 105... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8    N/A /  N/A |     78MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I have installed pytorch using both anaconda virtual env and going to the pytorch website and selecting CUDA version 11.0. 

cc @ezyang @seemethere @malfet @walterddr @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by malfet** [comment]
@SimplyLucKey Please run `python -m torch.utils.collect_env` and post its output here.

**Comment by mszhanyi** [comment]
@SimplyLucckey
I've verifed that pytorch wih cuda 11.0 works on cuda 11.2
could you please run pip show torch? 
and open  ....\envs\xxx\lib\site-packages\torch\lib to see if there's torch_cuda.dll

**Comment by SimplyLucKey** [comment]
> @SimplyLucKey Please run `python -m torch.utils.collect_env` and post its output here.

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Home
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] numpydoc==1.1.0
[pip3] torch==1.4.0
[conda] _pytorch_select           0.1                       cpu_0
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      216
[conda] mkl-service               2.3.0            py38hb782905_0
[conda] mkl_fft                   1.1.0            py38h45dec08_0
[conda] mkl_random                1.1.1            py38h47e9c7a_0
[conda] pytorch                   1.4.0           cpu_py38ha775e86_0




> @SimplyLucckey
> I've verifed that pytorch wih cuda 11.0 works on cuda 11.2
> could you please run pip show torch?
> and open ....\envs\xxx\lib\site-packages\torch\lib to see if there's torch_cuda.dll

From C:\Users\user\anaconda3\Lib\site-packages\torch\lib. I do not see `torch_cuda.dll`

**Comment by SimplyLucKey** [comment]
> @SimplyLucKey Please run `python -m torch.utils.collect_env` and post its output here.

Oops sorry I think I uninstalled pytorch so I reinstalled it again and here's the result 

Traceback (most recent call last):
  File "C:\Users\ruine\anaconda3\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\ruine\anaconda3\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\ruine\anaconda3\lib\site-packages\torch\__init__.py", line 117, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\ruine\anaconda3\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.

**Comment by peterjc123** [comment]
@SimplyLucKey  Hey, I think it's impractical that you want to train a bert model with 1050Ti, which has only 4GB of GPU memory. In my experience, even with 1080Ti (GPU memory: 12 GB), we use apex (mixed precision) for training.

**Comment by skyline75489** [comment]
@SimplyLucKey It's really not "they're only a few MB big". It will try to acquire more memory after the 30MB is granted. Try to reduce the batch size or just use a better card. @peterjc123 is right about this.

**Comment by SimplyLucKey** [comment]
> @SimplyLucKey Hey, I think it's impractical that you want to train a bert model with 1050Ti, which has only 4GB of GPU memory. In my experience, even with 1080Ti (GPU memory: 12 GB), we use apex (mixed precision) for training.



> @SimplyLucKey It's really not "they're only a few MB big". It will try to acquire more memory after the 30MB is granted. Try to reduce the batch size or just use a better card. @peterjc123 is right about this.

If the device is using cpu instead, is it then using the RAM as memory? I ran it on my PC with an AMD card (so the device was CPU) and it runs without a problem but takes a long time to train.

**Comment by peterjc123** [comment]
> If the device is using cpu instead, is it then using the RAM as memory?

Yes.



> I ran it on my PC with an AMD card (so the device was CPU) and it runs without a problem but takes a long time to train.

Well, it may take much longer. I hope you are not trying to train from scratch.

**Comment by mszhanyi** [comment]
close this issue because the discussion is off the topic.
@SimplyLucKey , Thank your feedback. 
https://discuss.pytorch.org/ is a better place to discussion how to make the best of PyTorch.

**Comment by gohjiayi** [comment]
Here to leave a comment for anyone encountering the same issue, I have faced the same issue for a very long period where `torch.cuda.is_available()` returns `False`. Turns out it was the PyTorch installation that made a difference, I have reinstalled multiple times, but only this one instance worked for me.

As mentioned in many other places, check your CUDA version via `nvcc -V`. Mine could be seen below - showing I have CUDA 10.1. Install PyTorch and other relevant packages according to this CUDA version.
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

Do note that your `nvidia-smi` might show a different CUDA version based on your driver, but it should not affect your installation. 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   32C    P0    30W / 250W |    512MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  On   | 00000000:5E:00.0 Off |                    0 |
| N/A   45C    P0   115W / 250W |   5561MiB / 16280MiB |    100%      Default |
|                               |                      |                  N/A |
+-----------------------------------------------------------------------------+
```

Head on to [PyTorch's website ](https://pytorch.org/get-started/locally/) to find the installation command for your environment. For me, as CUDA 10.1 is one of the older options, I've searched the commands through the [previous versions](https://pytorch.org/get-started/previous-versions/). Although I was using a conda environment, using the conda installation commands did not work for me but pip install did. This could be a case-by-case situation.

What worked:
`pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`

What did not work:
`conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.1 -c pytorch`

Alternatively, I have tried setting `CUDA_VISIBLE_DEVICES` and `LD_LIBRARY_PATH` variables previously which did not help. Hope my experience will be useful to someone else.

**Comment by Vikram12301** [comment]
> @SimplyLucKey Please run `python -m torch.utils.collect_env` and post its output here.

This is my output

Collecting environment information...
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi

**Comment by Jdragno** [comment]
> Here to leave a comment for anyone encountering the same issue, I have faced the same issue for a very long period where `torch.cuda.is_available()` returns `False`. Turns out it was the PyTorch installation that made a difference, I have reinstalled multiple times, but only this one instance worked for me.
> 
> As mentioned in many other places, check your CUDA version via `nvcc -V`. Mine could be seen below - showing I have CUDA 10.1. Install PyTorch and other relevant packages according to this CUDA version.
> 
> ```
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Sun_Jul_28_19:07:16_PDT_2019
> Cuda compilation tools, release 10.1, V10.1.243
> ```
> 
> Do note that your `nvidia-smi` might show a different CUDA version based on your driver, but it should not affect your installation.
> 
> ```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  Tesla P100-PCIE...  On   | 00000000:3B:00.0 Off |                    0 |
> | N/A   32C    P0    30W / 250W |    512MiB / 16280MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   1  Tesla P100-PCIE...  On   | 00000000:5E:00.0 Off |                    0 |
> | N/A   45C    P0   115W / 250W |   5561MiB / 16280MiB |    100%      Default |
> |                               |                      |                  N/A |
> +-----------------------------------------------------------------------------+
> ```
> 
> Head on to [PyTorch's website ](https://pytorch.org/get-started/locally/) to find the installation command for your environment. For me, as CUDA 10.1 is one of the older options, I've searched the commands through the [previous versions](https://pytorch.org/get-started/previous-versions/). Although I was using a conda environment, using the conda installation commands did not work for me but pip install did. This could be a case-by-case situation.
> 
> What worked: `pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> What did not work: `conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.1 -c pytorch`
> 
> Alternatively, I have tried setting `CUDA_VISIBLE_DEVICES` and `LD_LIBRARY_PATH` variables previously which did not help. Hope my experience will be useful to someone else.

This worked.... Very odd. Are the newer versions of Pytorch builds broken for pip?

**Comment by Alamnoor** [comment]
> I just tried what worked for you, installing using pip instead of conda. However, your solution didn't work for me. I got the following error message: " Could not find a version that satisfies the requirement torch==1.8.1+cu101 (from versions: 0.1.6.post17, 0.1.6.post20, 0.1.6.post22, 0.1.7.post2, 0.1.8.post1, 0.1.9.post1, 0.1.9.post2, 0.1.10.post1, 0.1.10.post2, 0.1.11.post4, 0.1.11.post5, 0.1.12.post1, 0.1.12.post2, 0.2.0.post1, 0.2.0.post2, 0.2.0.post3, 0.3.0, 0.3.0.post2, 0.3.0.post3, 0.3.0.post4, 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.2.0+cpu, 1.2.0+cu92, 1.3.0, 1.3.0+cpu, 1.3.0+cu100, 1.3.0+cu92, 1.3.1, 1.3.1+cpu, 1.3.1+cu100, 1.3.1+cu92, 1.4.0, 1.4.0+cpu, 1.4.0+cu100, 1.4.0+cu92, 1.5.0+cpu, 1.5.0+cu92) No matching distribution found for torch==1.8.1+cu101 " Any ideas?

USE> pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

It worked for me

**Comment by selezenart** [comment]
Sorry for reopening it.
![telegram-cloud-photo-size-2-5289949869903036446-x](https://user-images.githubusercontent.com/47925608/174416495-eda4e7fe-3563-420c-af51-142c65bbc714.jpg)
that's my nvidia-smi.
and pip list
ertifi            2022.6.15
charset-normalizer 2.0.12
idna               3.3
numpy              1.22.4
opencv-python      4.6.0.66
Pillow             9.1.1
pip                22.0.4
requests           2.28.0
setuptools         58.1.0
torch              1.11.0
torchaudio         0.11.0+cu113
torchvision        0.12.0
typing_extensions  4.2.0
urllib3            1.26.9
so I downloaded torch from official website and coda toolkit. 
After calling torch.cuda.is_available I get false and after calling torch.version.cuda I get None

**Comment by selcukyazar** [comment]
Hi, after fresh install anaconda, i set up the base environment for pytorch. but I also have cuda available false!

Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Enterprise
GCC version: (tdm64-1) 10.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: False
CUDA runtime version: 11.6.55
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 512.78
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.4.0
[pip3] torch==1.12.1
[pip3] torchvision==0.13.1a0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h59b6b97_2
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py39h2bbff1b_0
[conda] mkl_fft                   1.3.1            py39h277e83a_0
[conda] mkl_random                1.2.2            py39hf11a4ad_0
[conda] numpy                     1.21.5           py39h7a0a035_3
[conda] numpy-base                1.21.5           py39hca35cd5_3
[conda] numpydoc                  1.4.0            py39haa95532_0
[conda] pytorch                   1.12.1          cpu_py39h5e1f01c_0
[conda] torchvision               0.13.1          cpu_py39h378ed51_0

**Comment by nothingness6** [comment]
My apologies opening this thread again, but I've been struggling for 5 days with this issue with no luck. I installed the below ones:
cuda_11.7.0_windows_network
cudnn-windows-x86_64-8.8.1.3_cuda11-archive

Here is the info of mine:

'nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:59:34_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0'

'+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.41                 Driver Version: 531.41       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060 L...  WDDM | 00000000:01:00.0  On |                  N/A |
| N/A   32C    P8               11W /  N/A|    148MiB /  6144MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+'

'(base) C:\Users\Mono>python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 531.41
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3201
DeviceID=CPU0
Family=107
L2CacheSize=4096
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3201
Name=AMD Ryzen 7 5800H with Radeon Graphics
ProcessorType=3
Revision=20480

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[conda] blas                      1.0                         mkl
[conda] cpuonly                   2.0                           0    pytorch
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py39h2bbff1b_0
[conda] mkl_fft                   1.3.1            py39h277e83a_0
[conda] mkl_random                1.2.2            py39hf11a4ad_0
[conda] numpy                     1.21.5           py39h7a0a035_1
[conda] numpy-base                1.21.5           py39hca35cd5_1
[conda] numpydoc                  1.2                pyhd3eb1b0_0
[conda] pytorch                   2.0.0               py3.9_cpu_0    pytorch
[conda] pytorch-cuda              11.7                 h67b0de4_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                2.0.0                  py39_cpu    pytorch
[conda] torchvision               0.15.0                 py39_cpu    pytorch
'

**Comment by malfet** [comment]
@nothingness6 looks like you've install CPU-only build of PyTorch, which does not have CUDA support. Please use the different installation command to install PyTorch with GPU support, and if it does not work, ask question on https://discuss.pytorch.org or open a new issue

**Comment by nothingness6** [comment]
@malfet Thanks for the quick response. I installed Pytorch following the instruction on the official website. I just tried it again and got this message:

'
(base) C:\Users\Mono>pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
Looking in indexes: https://download.pytorch.org/whl/cu117
Requirement already satisfied: torch in d:\coding\anaconda\lib\site-packages (2.0.0)
Requirement already satisfied: torchvision in d:\coding\anaconda\lib\site-packages (0.15.0)
Requirement already satisfied: torchaudio in d:\coding\anaconda\lib\site-packages (2.0.0)
Requirement already satisfied: filelock in d:\coding\anaconda\lib\site-packages (from torch) (3.6.0)
Requirement already satisfied: typing-extensions in d:\coding\anaconda\lib\site-packages (from torch) (4.1.1)
Requirement already satisfied: sympy in d:\coding\anaconda\lib\site-packages (from torch) (1.10.1)
Requirement already satisfied: networkx in d:\coding\anaconda\lib\site-packages (from torch) (2.7.1)
Requirement already satisfied: jinja2 in d:\coding\anaconda\lib\site-packages (from torch) (2.11.3)
Requirement already satisfied: numpy in d:\coding\anaconda\lib\site-packages (from torchvision) (1.21.5)
Requirement already satisfied: requests in d:\coding\anaconda\lib\site-packages (from torchvision) (2.27.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\coding\anaconda\lib\site-packages (from torchvision) (9.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in d:\coding\anaconda\lib\site-packages (from jinja2->torch) (2.0.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\coding\anaconda\lib\site-packages (from requests->torchvision) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in d:\coding\anaconda\lib\site-packages (from requests->torchvision) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\coding\anaconda\lib\site-packages (from requests->torchvision) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\coding\anaconda\lib\site-packages (from requests->torchvision) (2021.10.8)
Requirement already satisfied: mpmath>=0.19 in d:\coding\anaconda\lib\site-packages (from sympy->torch) (1.2.1)
'

It looks like the requirements are already satisfied even though I installed it with the right method.

**Comment by vecorro** [comment]
I have a similar issue as @nothingness6 is reporting. It looks like something is broken between PyTorch 1.13 and CUDA 11.7. I hope the PyTorch dev team can take a look. Thanks in advance.

Here are my outputs:
```

>>> import torch
>>> torch.cuda.device_count()
1
>>> torch.cuda.is_available()
/root/miniconda3/lib/python3.9/site-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
False
```


Installation 
`pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117`

```
> nvidia-smi
Tue Apr 11 21:25:48 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  Off  | 00000000:03:00.0 Off |                   On |
| N/A   31C    P0    33W / 250W |      0MiB / 40960MiB |     N/A      Default |
|                               |                      |              Enabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| MIG devices:                                                                |
+------------------+----------------------+-----------+-----------------------+
| GPU  GI  CI  MIG |         Memory-Usage |        Vol|         Shared        |
|      ID  ID  Dev |           BAR1-Usage | SM     Unc| CE  ENC  DEC  OFA  JPG|
|                  |                      |        ECC|                       |
|==================+======================+===========+=======================|
|  No MIG devices found                                                       |
+-----------------------------------------------------------------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```


```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

```


```
python -m torch.utils.collect_env
Collecting environment information...
/root/miniconda3/lib/python3.9/site-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.16 (main, Jan 11 2023, 16:05:54)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA A100-PCIE-40GB
Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==1.13.1+cu117
[pip3] torchaudio==0.13.1+cu117
[pip3] torchvision==0.14.1+cu117
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     1.13.1+cu117             pypi_0    pypi
[conda] torchaudio                0.13.1+cu117             pypi_0    pypi
[conda] torchvision               0.14.1+cu117             pypi_0    pypi
```

**Comment by nothingness6** [comment]
Hi, Hudaka.
It works!! Finally!!!
I'd like to give you kiss twice!! My pain in the ass has gone now!!
Thanks so much!!


> > Here to leave a comment for anyone encountering the same issue, I have faced the same issue for a very long period where `torch.cuda.is_available()` returns `False`. Turns out it was the PyTorch installation that made a difference, I have reinstalled multiple times, but only this one instance worked for me.
> > As mentioned in many other places, check your CUDA version via `nvcc -V`. Mine could be seen below - showing I have CUDA 10.1. Install PyTorch and other relevant packages according to this CUDA version.
> > ```
> > nvcc: NVIDIA (R) Cuda compiler driver
> > Copyright (c) 2005-2019 NVIDIA Corporation
> > Built on Sun_Jul_28_19:07:16_PDT_2019
> > Cuda compilation tools, release 10.1, V10.1.243
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do note that your `nvidia-smi` might show a different CUDA version based on your driver, but it should not affect your installation.
> > ```
> > +-----------------------------------------------------------------------------+
> > | NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
> > |-------------------------------+----------------------+----------------------+
> > | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> > | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> > |                               |                      |               MIG M. |
> > |===============================+======================+======================|
> > |   0  Tesla P100-PCIE...  On   | 00000000:3B:00.0 Off |                    0 |
> > | N/A   32C    P0    30W / 250W |    512MiB / 16280MiB |      0%      Default |
> > |                               |                      |                  N/A |
> > +-------------------------------+----------------------+----------------------+
> > |   1  Tesla P100-PCIE...  On   | 00000000:5E:00.0 Off |                    0 |
> > | N/A   45C    P0   115W / 250W |   5561MiB / 16280MiB |    100%      Default |
> > |                               |                      |                  N/A |
> > +-----------------------------------------------------------------------------+
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Head on to [PyTorch's website ](https://pytorch.org/get-started/locally/) to find the installation command for your environment. For me, as CUDA 10.1 is one of the older options, I've searched the commands through the [previous versions](https://pytorch.org/get-started/previous-versions/). Although I was using a conda environment, using the conda installation commands did not work for me but pip install did. This could be a case-by-case situation.
> > What worked: `pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`
> > What did not work: `conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.1 -c pytorch`
> > Alternatively, I have tried setting `CUDA_VISIBLE_DEVICES` and `LD_LIBRARY_PATH` variables previously which did not help. Hope my experience will be useful to someone else.
> 
> This did solve my problem. Thanks a million!

**Comment by ReneFrlan** [comment]
> Here to leave a comment for anyone encountering the same issue, I have faced the same issue for a very long period where `torch.cuda.is_available()` returns `False`. Turns out it was the PyTorch installation that made a difference, I have reinstalled multiple times, but only this one instance worked for me.
> 
> As mentioned in many other places, check your CUDA version via `nvcc -V`. Mine could be seen below - showing I have CUDA 10.1. Install PyTorch and other relevant packages according to this CUDA version.
> 
> ```
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Sun_Jul_28_19:07:16_PDT_2019
> Cuda compilation tools, release 10.1, V10.1.243
> ```
> 
> Do note that your `nvidia-smi` might show a different CUDA version based on your driver, but it should not affect your installation.
> 
> ```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  Tesla P100-PCIE...  On   | 00000000:3B:00.0 Off |                    0 |
> | N/A   32C    P0    30W / 250W |    512MiB / 16280MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   1  Tesla P100-PCIE...  On   | 00000000:5E:00.0 Off |                    0 |
> | N/A   45C    P0   115W / 250W |   5561MiB / 16280MiB |    100%      Default |
> |                               |                      |                  N/A |
> +-----------------------------------------------------------------------------+
> ```
> 
> Head on to [PyTorch's website ](https://pytorch.org/get-started/locally/) to find the installation command for your environment. For me, as CUDA 10.1 is one of the older options, I've searched the commands through the [previous versions](https://pytorch.org/get-started/previous-versions/). Although I was using a conda environment, using the conda installation commands did not work for me but pip install did. This could be a case-by-case situation.
> 
> What worked: `pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> What did not work: `conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.1 -c pytorch`
> 
> Alternatively, I have tried setting `CUDA_VISIBLE_DEVICES` and `LD_LIBRARY_PATH` variables previously which did not help. Hope my experience will be useful to someone else.

This worked for me too, thanks so much ! the issue for me was that Pycuda wasn't working when I was using the CUDA version displayed by the `nvidia-smi`(12.1), but when I downgraded to CUDA 11.7 everything worked fine.

**Comment by mishal-harbi** [comment]
> Here to leave a comment for anyone encountering the same issue, I have faced the same issue for a very long period where `torch.cuda.is_available()` returns `False`. Turns out it was the PyTorch installation that made a difference, I have reinstalled multiple times, but only this one instance worked for me.
> 
> As mentioned in many other places, check your CUDA version via `nvcc -V`. Mine could be seen below - showing I have CUDA 10.1. Install PyTorch and other relevant packages according to this CUDA version.
> 
> ```
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Sun_Jul_28_19:07:16_PDT_2019
> Cuda compilation tools, release 10.1, V10.1.243
> ```
> 
> Do note that your `nvidia-smi` might show a different CUDA version based on your driver, but it should not affect your installation.
> 
> ```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  Tesla P100-PCIE...  On   | 00000000:3B:00.0 Off |                    0 |
> | N/A   32C    P0    30W / 250W |    512MiB / 16280MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   1  Tesla P100-PCIE...  On   | 00000000:5E:00.0 Off |                    0 |
> | N/A   45C    P0   115W / 250W |   5561MiB / 16280MiB |    100%      Default |
> |                               |                      |                  N/A |
> +-----------------------------------------------------------------------------+
> ```
> 
> Head on to [PyTorch's website ](https://pytorch.org/get-started/locally/) to find the installation command for your environment. For me, as CUDA 10.1 is one of the older options, I've searched the commands through the [previous versions](https://pytorch.org/get-started/previous-versions/). Although I was using a conda environment, using the conda installation commands did not work for me but pip install did. This could be a case-by-case situation.
> 
> What worked: `pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> What did not work: `conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.1 -c pytorch`
> 
> Alternatively, I have tried setting `CUDA_VISIBLE_DEVICES` and `LD_LIBRARY_PATH` variables previously which did not help. Hope my experience will be useful to someone else.

Finally, it worked ! Thanks a million, I have been googling for days to solve this!

**Comment by HAMZA12337** [comment]
import torch

print(torch.cuda.is_available()) return false

python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.16 (main, May 17 2023, 17:49:16) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1050 Ti
Nvidia driver version: 535.98
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2904
DeviceID=CPU0
Family=198
L2CacheSize=2048
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2904
Name=Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.1+cu117
[pip3] torchaudio==2.0.2+cu117
[pip3] torchvision==0.15.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h8bd8f75_46356
[conda] mkl-service               2.4.0            py39h2bbff1b_1
[conda] mkl_fft                   1.3.6            py39hf11a4ad_1
[conda] mkl_random                1.2.2            py39hf11a4ad_1
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] numpy-base                1.24.3           py39h8a87ada_1
[conda] torch                     2.0.1+cu117              pypi_0    pypi
[conda] torchaudio                2.0.2+cu117              pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
