### ISSUE TITLE
CUDA error: misaligned address on CUDA 11.2 on Windows on torch.where complex128

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#51980]
## 🐛 Bug

Discovered in https://github.com/pytorch/pytorch/pull/51598, the failing test is `test_where_scalar_valid_combination_cuda_complex128 `

Minumum repro is:

```python
import torch

x = torch.randn(5, 5, 5, dtype=torch.cdouble, device='cuda')
cond = torch.zeros_like(x, dtype=torch.bool)
torch.where(cond, x, complex(0.0))
```

Fails with

```python
Traceback (most recent call last):
  File "test/where.py", line 5, in <module>
    torch.where(cond, x, complex(0.0))
RuntimeError: CUDA error: misaligned address
```

## Environment

```
Collecting environment information...
PyTorch version: 1.8.0a0+dac730a
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.17.0-rc1

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 461.40
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.8.0a0+dac730a
[conda] Could not collect
```

cc @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489 @janeyx99 @ptrblck @xwang233

**Comment by zasdfgbnm** [comment]
self assign to look deeper at it

**Comment by janeyx99** [comment]
Do you think this other CUDA misaligned error on Windows 11.2 is due to the same cause? https://app.circleci.com/pipelines/github/pytorch/pytorch/271054/workflows/95e4fc48-4caa-42bc-8dd7-a16d1104b184/jobs/10761908

**Comment by zasdfgbnm** [comment]
Seems yes to me!

**Comment by zasdfgbnm** [comment]
Reproduced with standalone C++ at https://github.com/zasdfgbnm/tensoriterator/blob/where/where.cu

**Comment by mszhanyi** [comment]
@zasdfgbnm , build with update2 of cuda11.2. it works now.

**Comment by kshitij12345** [comment]
@mszhanyi Not sure if the update that you mention has been pushed to CI or not but failure related to masked_fill still exists.

Reference : https://github.com/pytorch/pytorch/pull/54244#issuecomment-801789157

**Comment by mszhanyi** [comment]
> @mszhanyi Not sure if the update that you mention has been pushed to CI or not but failure related to masked_fill still exists.
> 
> Reference : [#54244 (comment)](https://github.com/pytorch/pytorch/pull/54244#issuecomment-801789157)

No, it hasn't been in CI. I verified it in my local build and I submitted a PR last night
