### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory when using loss function

### ISSUE THREAD

**Issue by ahmed-shariff** [pytorch/pytorch#5210]
When I am trying to run my model, during the evaluation loop, when I call the loss function, it results in a `out of memory error`. If I comment out the loss in the evaluation loop, I don't get this problem. Note that the loss function in the training loop does not cause this problem.

The code of the model I am running:
```
class TestingModel(Model):
    def __init__(self, versions, **args):
        super().__init__(versions, **args)
        self.model = ResNet(Bottleneck, [2,3,4,4], 4)
        self.topk_k = 3
        self.logging_iteration = 10
        self.criterion = torch.nn.CrossEntropyLoss()
        if torch.cuda.is_available() and use_cuda:
            self.criterion.cuda()
            self.model.cuda()
            
    def train_model(self, input_fn, steps):
        #criterion = torch.nn.CrossEntropyLoss()
        top1 = matricContainer()
        topk = matricContainer()
        loss_average = matricContainer()
        #if use_cuda:
        #    criterion.cuda()
        optimizer = torch.optim.Adam(self.model.parameters())
        epocs = math.ceil(steps/self.current_version[version_parameters.EPOC_COUNT])
        datasize = self.current_version[version_parameters.DATALOADER].get_train_sample_count()
        epocs = 1
        for epoc in range(epocs):
            for idx, i in enumerate(input_fn):
                #print(idx)
                if idx > 1:
                    break
                if use_cuda:
                    input_var = torch.autograd.Variable(i[0].cuda())
                    label_var = torch.autograd.Variable(i[1].cuda())
                else:
                    input_var = torch.autograd.Variable(i[0])
                    label_var = torch.autograd.Variable(i[1])
                    pass
                out = self.model(input_var)
                loss = self.criterion(out, label_var)
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
                t1, tk, total = accuracy(out, label_var, self.topk_k)
                top1.update(t1, total)
                topk.update(tk, total)
                loss_average.update(loss, 1)
            
                if idx % self.logging_iteration == 0:
                    self.log("Step: {}   Epoc: {}".format(epoc*datasize + idx, epoc + 1))
                    self.log("Top1: {:.4f}  Top{}: {:.4f}  Loss: {:.4f}".format(
                        top1.avg(),
                        self.topk_k,
                        topk.avg(),
                        loss_average.avg().data[0]))

    def log(self, message,log_to_file=False, **kargs):
        log("{}Model- {}{}".format(console_colors.CYAN_FG,
                                   console_colors.RESET,
                                   message),
            log=log_to_file, **kargs)

      
    def evaluate_model(self, input_fn, steps):
        top1 = matricContainer()
        topk = matricContainer()
        loss_average = matricContainer()
        #print(self.model.state_dict())
        for idx, i in enumerate(input_fn):
            #print(idx)
            if idx > 50:
                break
            if use_cuda:
                input_var = torch.autograd.Variable(i[0].cuda())
                label_var = torch.autograd.Variable(i[1].cuda())
            else:
                input_var = torch.autograd.Variable(i[0])
                label_var = torch.autograd.Variable(i[1])
                pass
            out = self.model(input_var)
            print("*"*20)
            
            #LINE CAUSING THE PROBLEM
            #The error does not happen when I comment out this line
            loss = self.criterion(out, label_var)
            
            t1, tk, total = accuracy(out, label_var, self.topk_k)
            top1.update(t1, total)
            self.model.zero_grad()
            topk.update(tk, total)
            loss_average.update(loss, 1)
            #print()rint(idx % self.logging_iteration)
        self.log("Step: {}".format(idx))
        self.log("Top1: {:.4f}  Top{}: {:.4f}  Loss: {:.4f}".format(
            top1.avg(),
            self.topk_k,
            topk.avg(),
            loss_average.avg().data[0]))
```
The `input_fn` pass above (in both places) is the return value of the following:
```
 def get_train_input_fn(self, mode= ModeKeys.TRAIN, **kargs):
        _size = 440
        self.log("batch size: {}".format(self.batch_size))
        if self.train_files is None or self.train_labels is None:
            self.set_classes(self.use_all_classes, self.classes_count)
        pre = [RandomCrop(450), transforms.ToPILImage(), transforms.Resize((256,256))]
        post = [transforms.ToTensor()]

        dataset = parent_dataset(self.train_files,
                                 self.train_labels,
                                 transforms.Compose(pre + post))
        dl = torch.utils.data.DataLoader(dataset, self.batch_size, True)
        
        return dl
```

The model:
```
class Bottleneck(nn.Module):
    expansion = 4

    def __init__(self, inplanes, planes, stride=1, downsample=None):
        super(Bottleneck, self).__init__()
        self.conv1 = nn.Conv2d(inplanes, planes, kernel_size=1, bias=False)
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=stride,
                               padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(planes)
        self.conv3 = nn.Conv2d(planes, planes * 4, kernel_size=1, bias=False)
        self.bn3 = nn.BatchNorm2d(planes * 4)
        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample
        self.stride = stride

    def forward(self, x):
        residual = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)
        out = self.relu(out)

        out = self.conv3(out)
        out = self.bn3(out)

        if self.downsample is not None:
            residual = self.downsample(x)

        out += residual
        out = self.relu(out)

        return out


class ResNet(nn.Module):

    def __init__(self, block, layers, num_classes=1000):
        self.inplanes = 64
        super(ResNet, self).__init__()
        self.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3,
                               bias=False)
        self.bn1 = nn.BatchNorm2d(64)
        self.relu = nn.ReLU(inplace=True)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
        self.layer1 = self._make_layer(block, 64, layers[0])
        self.layer2 = self._make_layer(block, 128, layers[1], stride=2)
        self.layer3 = self._make_layer(block, 256, layers[2], stride=2)
        self.layer4 = self._make_layer(block, 512, layers[3], stride=2)
        self.avgpool = nn.AvgPool2d(8, stride=8)
        self.fc = nn.Linear(512 * block.expansion, num_classes)
        self.sigmoid = nn.Sigmoid()

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                n = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
                m.weight.data.normal_(0, math.sqrt(2. / n))
            elif isinstance(m, nn.BatchNorm2d):
                m.weight.data.fill_(1)
                m.bias.data.zero_()

    def _make_layer(self, block, planes, blocks, stride=1):
        downsample = None
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = nn.Sequential(
                nn.Conv2d(self.inplanes, planes * block.expansion,
                          kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(planes * block.expansion),
            )

        layers = []
        layers.append(block(self.inplanes, planes, stride, downsample))
        self.inplanes = planes * block.expansion
        for i in range(1, blocks):
            layers.append(block(self.inplanes, planes))

        return nn.Sequential(*layers)

    def forward(self, x):
        
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)
        
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        
        x = self.avgpool(x)
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        x = self.sigmoid(x)

        return x
```

Error output:
```
2018-02-13 14:28:06:INFO:mlp- Model- Step: 0   Epoc: 1
2018-02-13 14:28:06:INFO:mlp- Model- Top1: 0.2000  Top3: 0.4000  Loss: 1.7698
2018-02-13 14:28:06:INFO:mlp- Model traning output: None
2018-02-13 14:28:06:INFO:mlp- Model trained
2018-02-13 14:28:06:INFO:mlp- Training evaluation started: 1 steps
2018-02-13 14:28:06:INFO:mlp- DataLoader- batch size: 5
********************
********************
********************
********************
********************
THCudaCheck FAIL file=/home/amsha/builds/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "pipeline.py", line 598, in <module>
    main(parser.parse_args())
  File "pipeline.py", line 591, in main
    _main()
  File "pipeline.py", line 170, in _main
    steps = train_eval_steps)
  File "/home/amsha/Research/FoodClassification/models/test_torch.py", line 244, in evaluate_model
    out = self.model(input_var)
  File "/home/amsha/virtualenv/torch-master-12022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amsha/Research/FoodClassification/models/test_torch.py", line 137, in forward
    x = self.layer1(x)
  File "/home/amsha/virtualenv/torch-master-12022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amsha/virtualenv/torch-master-12022018/lib/python3.6/site-packages/torch/nn/modules/container.py", line 81, in forward
    input = module(input)
  File "/home/amsha/virtualenv/torch-master-12022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amsha/Research/FoodClassification/models/test_torch.py", line 75, in forward
    out = self.conv3(out)
  File "/home/amsha/virtualenv/torch-master-12022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amsha/virtualenv/torch-master-12022018/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 292, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (2) : out of memory at /home/amsha/builds/pytorch/aten/src/THC/generic/THCStorage.cu:58
```

OS: Arch Linux
GPU: GTX 1050
CUDA: 8.0.61-3 & 9.1.85-1
cudnn: 7.0.5-2
(cudnn and cuda installed from arch packages)
pytorch: built from source ( b608ea9178eeb32b66a3480aad16d439ba039bdc ) 
              without conda using gcc 4.8

**Comment by ezyang** [comment]
I don't see any occurrences of volatile in your evaluation code, which means that you are likely attempting to backprop through the *entirety* of your validation data set, leading to an OOM. Try repackaging the input in:

```

            if use_cuda:
                input_var = torch.autograd.Variable(i[0].cuda())
                label_var = torch.autograd.Variable(i[1].cuda())
            else:
                input_var = torch.autograd.Variable(i[0])
                label_var = torch.autograd.Variable(i[1])
                pass
```

as

```

            if use_cuda:
                input_var = torch.autograd.Variable(i[0].cuda(), volatile=True)
                label_var = torch.autograd.Variable(i[1].cuda(), volatile=True)
            else:
                input_var = torch.autograd.Variable(i[0], volatile=True)
                label_var = torch.autograd.Variable(i[1], volatile=True)
                pass
```

**Comment by ahmed-shariff** [comment]
using volatile gives the following warning: 
```
/home/amsha/Research/FoodClassification/models/test_torch.py:262: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
```

Anyhow, the problem doesn't exist anymore, even without `volatile`. Will update here if things change.

**Comment by ahmed-shariff** [comment]
I accidentally found that the problem was not with the loss function. But with the `matricContainer` I am using. When I am adding the values returned by the `self.criterion`, I am actually adding `torch.autograd.variable.Variable`'s instead of just `float`'s. So when i replace `loss_average.update(loss, 1)` with `loss_average.update(loss.data[0], 1)`, the problem gets solved. 

While it fixes the problem, I don't understand **why adding `Variable`s would cause a memory overflow?**

**Comment by apaszke** [comment]
Because as long as output Variables are in scope, the underlying graphs can't be freed. You're meant to let go the loss at the end of iteration.

**Comment by ahmed-shariff** [comment]
I see. Thank you for the response mate.
