### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED with RNN on GPU

### ISSUE THREAD

**Issue by Diego999** [pytorch/pytorch#5213]
Hi everyone,

I'm using the new torch.split function given a list of chunks as well as a LSTM/GRU network (both lead to the bug).

On CPU, the code works perfectly.
On GPU, If I do something else that a RNN forward during the iteration over torch.split, it's fine. otherwise it crashes.

**StackTrace**
 ...
  File "/home/diego/Github/DocAgg/pygcn_modified/models.py", line 80, in forward
    output, hidden = self.document_rnn(sentence_embeddings_per_doc, self.document_rnn_hidden)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 181, in forward
    output, hidden = func(input, self.all_weights, hx, batch_sizes)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/_functions/rnn.py", line 315, in forward
    return func(input, *fargs, **fkwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/_functions/rnn.py", line 284, in forward
    Variable(dropout_desc.state) if dropout_desc.state is not None else None)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

**Code**
sentence_hidden_embeddings is a FloatTensor [657, 700]
nb_sentences_per_doc is a python list :[26, 13, 12, 20, 25, 26, 535]

`

        all_sentence_embeddings_per_doc = torch.split(sentence_hidden_embeddings.unsqueeze(0), nb_sentences_per_doc, dim=1)[:-1]

        document_embeddings = []
        for sentence_embeddings_per_doc in all_sentence_embeddings_per_doc:
            self.document_rnn_hidden = self.init_hidden()
            output, hidden = self.document_rnn(sentence_embeddings_per_doc, self.document_rnn_hidden)

            # output[-1][-1] == hidden[-1][-1] (GRU) and output[-1][-1] == hidden[0][-1][-1] (LSTM)
            doc_emb = hidden[-1] if self.mode == 'GRU' else (hidden[0][-1] if self.mode == 'LSTM' else None)
            document_embeddings.append(doc_emb)

            # TODO Remove. Doing only this perfectly works on GPU
            #doc_emb = torch.mean(sentence_embeddings_per_doc, dim=1)
            #document_embeddings.append(doc_emb)
        cluster_embedding = torch.mean(torch.cat(document_embeddings), dim=0)`

__RNN__
`

        if self.mode == 'GRU':
            self.document_rnn = nn.GRU(embedding_size, embedding_size, num_layers=self.nb_layers, bias=True, dropout=self.dropout, bidirectional=False, batch_first=True)
        elif self.mode == 'LSTM':
            self.document_rnn = nn.LSTM(embedding_size, embedding_size, num_layers=self.nb_layers, bias=True, dropout=self.dropout, bidirectional=False, batch_first=True)
        self.document_rnn_hidden = self.init_hidden()

`

__Hidden_init__
`

    def init_hidden(self):
        document_rnn_init_h = nn.Parameter(nn.init.xavier_uniform(torch.Tensor(self.nb_layers, self.batch_size, self.embedding_size).type(torch.FloatTensor)), requires_grad=True)
        if self.mode == 'GRU':
            return document_rnn_init_h
        elif self.mode == 'LSTM':
            document_rnn_init_c = nn.Parameter(nn.init.xavier_uniform(torch.Tensor(self.nb_layers, self.batch_size, self.embedding_size).type(torch.FloatTensor)), requires_grad=True)
            return (document_rnn_init_h, document_rnn_init_c)

`

- OS: Linux Mint 18.2 Sonya
- PyTorch version: From source (https://github.com/pytorch/pytorch/commit/2b2d56d8460d335daf5aa79774442a111d424f90)
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.5
- CUDA/cuDNN version: 9.1/7.0.5 (latest versions)
- GPU models and configuration: Titan Xp 12Go (Driver 390.12)
- GCC version (if compiling from source): (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609

**Comment by Diego999** [comment]
I realized the problem is not from torch.split, but rather from the CUDA code for RNN. I’m saying this because I did the operation on CPU using numpy and converted to a tensor of Xx2 I give during the forward pass and it still doesn’t work.

I downgraded to cuda 9.0, cudnn 7.0 and last release of pytorch (0.3.1) and it works (with the workeraround as torch.split is still the old version.

**Comment by soumith** [comment]
thanks for narrowing this down.
@ezyang it looks like it might be an issue in the CuDNN RNN bindings you wrote in C++

**Comment by ezyang** [comment]
Hi @Diego999, I'll try to reproduce from the description you gave, but it would be a lot easier if there were a complete script I could run to repro :)

**Comment by ezyang** [comment]
Well, I managed to reproduce it.

```
import torch
from torch.autograd import Variable
import torch.nn as nn


class Model(nn.Module):
    def __init__(self, mode, embedding_size):
        super(Model, self).__init__()
        self.mode = mode
        self.embedding_size = embedding_size
        self.nb_layers = 1
        self.dropout = 0
        self.batch_size = 1

        if self.mode == 'GRU':
            self.document_rnn = nn.GRU(embedding_size, embedding_size, num_layers=self.nb_layers, bias=True, dropout=self.dropout, bidirectional=False, batch_first=True)
        elif self.mode == 'LSTM':
            self.document_rnn = nn.LSTM(embedding_size, embedding_size, num_layers=self.nb_layers, bias=True, dropout=self.dropout, bidirectional=False, batch_first=True)
        self.document_rnn_hidden = self.init_hidden()

        self.init_hidden()

    def init_hidden(self):
        document_rnn_init_h = nn.Parameter(nn.init.xavier_uniform(torch.Tensor(self.nb_layers, self.batch_size, self.embedding_size).type(torch.FloatTensor)), requires_grad=True)
        if self.mode == 'GRU':
            return document_rnn_init_h
        elif self.mode == 'LSTM':
            document_rnn_init_c = nn.Parameter(nn.init.xavier_uniform(torch.Tensor(self.nb_layers, self.batch_size, self.embedding_size).type(torch.FloatTensor)), requires_grad=True)
            return (document_rnn_init_h, document_rnn_init_c)

    def forward(self, sentence_hidden_embeddings, nb_sentences_per_doc):
        all_sentence_embeddings_per_doc = torch.split(sentence_hidden_embeddings.unsqueeze(0), nb_sentences_per_doc, dim=1)[:-1]

        document_embeddings = []
        for sentence_embeddings_per_doc in all_sentence_embeddings_per_doc:
            self.document_rnn_hidden = self.init_hidden()
            output, hidden = self.document_rnn(sentence_embeddings_per_doc, self.document_rnn_hidden)

            # output[-1][-1] == hidden[-1][-1] (GRU) and output[-1][-1] == hidden[0][-1][-1] (LSTM)
            doc_emb = hidden[-1] if self.mode == 'GRU' else (hidden[0][-1] if self.mode == 'LSTM' else None)
            document_embeddings.append(doc_emb)

            # TODO Remove. Doing only this perfectly works on GPU
            #doc_emb = torch.mean(sentence_embeddings_per_doc, dim=1)
            #document_embeddings.append(doc_emb)
        cluster_embedding = torch.mean(torch.cat(document_embeddings), dim=0)

        return document_embeddings, cluster_embedding



sentence_hidden_embeddings = Variable(torch.randn(657, 700).cuda())
nb_sentences_per_doc = [26, 13, 12, 20, 25, 26, 535]

model = Model('LSTM', 700)
model = model.cuda()
model(sentence_hidden_embeddings, nb_sentences_per_doc)
```

**Comment by ezyang** [comment]
When I replace:

```

    def init_hidden(self):
        document_rnn_init_h = nn.Parameter(nn.init.xavier_uniform(torch.Tensor(self.nb_layers, self.batch_size, self.embedding_size).type(torch.FloatTensor)), requires_grad=True)
        if self.mode == 'GRU':
            return document_rnn_init_h
        elif self.mode == 'LSTM':
            document_rnn_init_c = nn.Parameter(nn.init.xavier_uniform(torch.Tensor(self.nb_layers, self.batch_size, self.embedding_size).type(torch.FloatTensor)), requires_grad=True)
            return (document_rnn_init_h, document_rnn_init_c)
```

with

```
    def init_hidden(self):
        document_rnn_init_h = nn.Parameter(nn.init.xavier_uniform(torch.Tensor(self.nb_layers, self.batch_size, self.embedding_size).type(torch.FloatTensor).cuda()), requires_grad=True)
        if self.mode == 'GRU':
            return document_rnn_init_h
        elif self.mode == 'LSTM':
            document_rnn_init_c = nn.Parameter(nn.init.xavier_uniform(torch.Tensor(self.nb_layers, self.batch_size, self.embedding_size).type(torch.FloatTensor).cuda()), requires_grad=True)
            return (document_rnn_init_h, document_rnn_init_c)
```

(that is, ensuring that the hidden parameters are put onto CUDA appropriately), it works. So it sounds like we're missing (1) some checks that the tensors we're running are indeed CUDA tensors, and maybe (2) some implicit conversions which no longer exist.

**Comment by Diego999** [comment]
@ezyang thank you for all these details !

It’s true that yesterday I remarked the missing cuda tensor for the hidden and cell states but it worked on the stable version.

I’ll try later today to see if this works on my code.

I’m sorry to not have put the whole code. Tell me if you need the whole model :)

**Comment by Diego999** [comment]
@ezyang I confirm that it works with the last version of master.

**Comment by ezyang** [comment]
Thanks @Diego999, I'll look into adding error-checking / restoring the auto-cast behavior.

**Comment by ezyang** [comment]
I don't think we're going do auto-cast, it probably shouldn't have been doing that in the first place. But there will be an error.

**Comment by Diego999** [comment]
Seems good to me because IMHO it makes more sense to have the error saying that we should have cuda tensor rather having auto-cast without any warning

**Comment by peterbell10** [comment]
Device type checks were added in #10185
