### ISSUE TITLE
Deadlock in a single machine multi-gpu using dataparlel when cpu is AMD

### ISSUE THREAD

**Issue by ROBOTICSENGINEER** [pytorch/pytorch#52142]
## 🐛 Bug

Training CNN (include torchvision resnet18 and timm efficientnet) with a single machine and multi-gpu using dataparallel cause deadlock in machines with AMD cpu, while the same code works well in the machines with Intel cpu.

The code run until forward pass, i.e., `output = model(images)` , inside the for loop in the training. It remains in the `model(images)` forever with gpu utilization go to 0% (memory is occupied, not 0),  three cpu cores go to 100%, and other cpu cores go to 0%. The processes PID and GPU mempry usage remains after stopping with `ctrl+c` and `ctrll+z`. The `kill` , `pkill`  , and `fuser -k /dev/nvidia*` commands cause zombie processes, also known as defunct and z state. The zombie processes have the parent pid of 1, so it cannot be killed. The only solution is to reboot the system. 

The code works well in 3 machines with Intel cpu and has this issue in 4 machines with AMD cpu.
We tested on GTX 1080, Titan V, Titan RTX,  Quadro RTX 8000, and RTX 3090. So, it is independent of gpu model.

**Note**: There is similar issue with Distributed Data Parallel (DDP).

## To Reproduce

1. use a machine with AMD cpu and multiple NVIDIA gpu
2. Linux, Python3.8, cuda 11.0, pytorch 1.7.1, torchvision 0.8.2
3. write a code to train a resnet18 model in torchvisaion
4. please test both Data Parallel (DP) and Distributed Data Parallel (DP)

## Expected behavior

1. code go to deadlock at forward pass of in the first epoch and the first iteration of training when using AMD cpu.
2. same code work well when using intel cpu

#### Intel cpu environment (system 1)

Intel(R) Xeon(R) CPU E5-2699C v4 @ 2.20GHz

```
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.1.85
GPU models and configuration:
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 3090
GPU 2: GeForce RTX 3090
GPU 3: GeForce RTX 3090

Nvidia driver version: 455.45.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

#### Intel cpu environment (system 2)

Intel(R) Xeon(R) CPU E5-2699A v4 @ 2.40GHz

```
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX
GPU 2: TITAN RTX
GPU 3: Quadro RTX 8000

Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

#### Intel cpu environment (system 3)

Intel(R) Xeon(R) CPU E5-2699A v4 @ 2.40GHz

```
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80
GPU 4: Tesla K80
GPU 5: Tesla K80
GPU 6: Tesla K80
GPU 7: Tesla K80
GPU 8: Tesla K80
GPU 9: Tesla K80
GPU 10: Tesla K80
GPU 11: Tesla K80
GPU 12: Tesla K80
GPU 13: Tesla K80
GPU 14: Tesla K80
GPU 15: Tesla K80

Nvidia driver version: 450.102.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.14.3
[conda] Could not collect
```

#### AMD cpu environment (system 4)

AMD Eng Sample: 100-000000053-04_32/20_N

```
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti

Nvidia driver version: 450.102.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

#### AMD cpu environment (system 5)

AMD Eng Sample: 100-000000053-04_32/20_N

```
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN V
GPU 1: TITAN V

Nvidia driver version: 455.45.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

#### AMD cpu environment (system 6)

AMD Opteron(tm) Processor 6380

```
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN V
GPU 1: TITAN V

Nvidia driver version: 450.102.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

#### AMD cpu environment (system 7)

AMD Opteron(tm) Processor 6380

```
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti

Nvidia driver version: 450.102.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.1.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

cc @ngimel @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by SciPioneer** [comment]
@ROBOTICSENGINEER
Thanks for reporting this bug! 

> The zombie processes have the parent pid of 1, so it cannot be killed. The only solution is to reboot the system.
The consequence sounds really bad.

> The code run until forward pass, i.e., `output = model(images)` , inside the for loop in the training. 
To clarify, is the training stuck at the first step?

> 3. write a code to train a resnet18 model in torchvisaion
To simplify the debug process, wonder if this issue can also be reproduced by running a toy model probably w/ random data?

@mrshenli 
Do we have any CI test that uses AMD CPU?

**Comment by ROBOTICSENGINEER** [comment]
It happen at the first forward pass. After data loadar and sending data to cuda.

I tried ImagNet, mini ImageNet, CIFAR 10, and other datasets.

Because CIFAR 10 is light weight, it is best to debugging.  

In the following I prove cifar10 example and toy_example

## CIFAR 10 example

```
import numpy as np
import os
import time
import PIL
import torch
from torch import Tensor
from torch.utils.data import Dataset, DataLoader
import torchvision
from torchvision import transforms
from torchvision.models.resnet   import  ResNet, BasicBlock

batch_size = 128
max_number_of_epoch = 100
LR = 0.1
image_size = 224
number_of_classes = 10
clipping_value = 512

np.random.seed(2)
torch.manual_seed(2)

n_cpu = n_cpu = int(os.cpu_count()*0.8)

class Average_Meter(object):
  """Computes and stores the average and current value"""
  def __init__(self):
    self.reset()

  def reset(self):
    self.val = 0.0
    self.avg = 0.0
    self.sum = 0.0
    self.count = 0

  def update(self, val, n):
    if n > 0:
      self.val = val
      self.sum += val * n
      self.count += n
      self.avg = self.sum / self.count

class Sum_Meter(object):
  """Computes and stores the sum and current value"""
  def __init__(self):
    self.reset()

  def reset(self):
    self.val = 0.0
    self.avg = 0.0
    self.sum = 0.0
    self.count = 0

  def update(self, val, n):
    if n > 0:
      self.val = val
      self.sum += val
      self.count += n
      self.avg = self.sum / self.count

def accuracy(output, target, topk=(1,)):
    """Computes the accuracy over the k top predictions for the specified values of k"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))

        res = []
        for k in topk:
            correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
            res.append(correct_k.mul_(1.0 / batch_size))
        return res


transform = transforms.Compose([
            transforms.Resize(size=(image_size,image_size), interpolation=PIL.Image.BICUBIC),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]) ])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,  download=True, transform=transform)
train_loader = torch.utils.data.DataLoader(trainset, batch_size=batch_size, shuffle=True, num_workers=n_cpu)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
val_loader = torch.utils.data.DataLoader(testset, batch_size=batch_size, shuffle=False, num_workers=n_cpu)

class MyResNet18(ResNet):
  def __init__(self, num_classes):
    super(MyResNet18, self).__init__(BasicBlock, [2, 2, 2, 2], num_classes = num_classes)
      
  def _forward_impl(self, x: Tensor) -> Tensor:
    x = self.conv1(x)
    x = self.bn1(x)
    x = self.relu(x)
    x = self.maxpool(x)
    x = self.layer1(x)
    x = self.layer2(x)
    x = self.layer3(x)
    x = self.layer4(x)
    x = self.avgpool(x)
    FV = torch.flatten(x, 1)
    Logit = self.fc(FV)
    return FV, Logit


model = MyResNet18(num_classes=number_of_classes) 

best_val = 0.0

optimizer = torch.optim.Adam(model.parameters(), lr=LR)

device = torch.device('cuda')
if torch.cuda.device_count() > 1:
  print("Let's use", torch.cuda.device_count(), "GPUs!")
  model = torch.nn.DataParallel(model)
model.to(device)

loss_CE = torch.nn.CrossEntropyLoss(reduction='sum').cuda()

torch.backends.cudnn.benchmark=True

losses_train_total = Sum_Meter()
top1_train = Average_Meter()
top5_train = Average_Meter()
losses_val_total = Sum_Meter()
top1_val = Average_Meter()
top5_val = Average_Meter()

for epoch in range(max_number_of_epoch):
  print("\nepoch = ", epoch +1)
  losses_train_total.reset()
  top1_train.reset()
  top5_train.reset()
  losses_val_total.reset()
  top1_val.reset()
  top5_val.reset()
  t1 = time.time()
  model.train()
  for i, (x,y) in enumerate(train_loader, 0):
    optimizer.zero_grad()
    x = x.cuda()
    y = y.detach().clone().long().cuda()
    FV, Logit  = model(x)
    prec1, prec5 = accuracy(Logit.data, y, topk=(1, 5))
    loss = loss_CE(Logit,y)
    losses_train_total.update(loss.item(), y.size(0))
    top1_train.update(prec1.item(), y.size(0))
    top5_train.update(prec5.item(), y.size(0))
    assert not torch.isnan(loss)
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), clipping_value)
    optimizer.step()
  model.eval()
  with torch.no_grad():
    for i, (x,y) in enumerate(val_loader, 0):
      x = x.cuda()
      y = y.detach().clone().long().cuda()
      FV, Logit  = model(x)
      prec1, prec5 = accuracy(Logit.data, y, topk=(1, 5))
      loss = loss_CE(Logit,y)
      losses_val_total.update(loss.item(), y.size(0))
      top1_val.update(prec1.item(), y.size(0))
      top5_val.update(prec5.item(), y.size(0))
  t2 = time.time()
  print('train average_loss_total', losses_train_total.avg)
  print('train top1 accuracy', top1_train.avg)
  print('train top5 accuracy ', top5_train.avg)
  print('validation average_loss_total', losses_val_total.avg)
  print('validation top1 accuracy', top1_val.avg)
  print('validation top5 accuracy ', top5_val.avg)
  print("epoch time = ", t2-t1)
  if top1_val.avg > best_val:
    best_val = top1_val.avg
    print("model saved with vallidation top-1 accuracy  =  " , best_val)
    torch.save(model.state_dict(), f"resnet_18_cifar_10_vall_acc_{best_val}.pth.tar")

print('Finished Training')
```

## Toy example

```
import numpy as np
import os
import time
import PIL
import torch
from torch import Tensor
from torch.utils.data import Dataset, DataLoader
import torchvision
from torchvision import transforms
from torchvision.models.resnet   import  ResNet, BasicBlock

batch_size = 32
max_number_of_epoch = 100
LR = 0.1
number_of_classes = 10
clipping_value = 512

np.random.seed(2)
torch.manual_seed(2)


class MyResNet18(ResNet):
  def __init__(self, num_classes):
    super(MyResNet18, self).__init__(BasicBlock, [2, 2, 2, 2], num_classes = num_classes)
      
  def _forward_impl(self, x: Tensor) -> Tensor:
    x = self.conv1(x)
    x = self.bn1(x)
    x = self.relu(x)
    x = self.maxpool(x)
    x = self.layer1(x)
    x = self.layer2(x)
    x = self.layer3(x)
    x = self.layer4(x)
    x = self.avgpool(x)
    FV = torch.flatten(x, 1)
    Logit = self.fc(FV)
    return FV, Logit

model = MyResNet18(num_classes=number_of_classes) 

best_val = 0.0

optimizer = torch.optim.Adam(model.parameters(), lr=LR)

device = torch.device('cuda')
if torch.cuda.device_count() > 1:
  print("Let's use", torch.cuda.device_count(), "GPUs!")
  model = torch.nn.DataParallel(model)
model.to(device)

loss_CE = torch.nn.CrossEntropyLoss(reduction='sum').cuda()

torch.backends.cudnn.benchmark=True

model.train()
for epoch in range(max_number_of_epoch):
  print("\nepoch = ", epoch +1)
  t1 = time.time()
  for i in range(100):
    print("\niteration = ", i)
    optimizer.zero_grad()
    x = torch.randn(batch_size, 3, 224, 224).cuda()
    y = torch.randint(low = 0, high = number_of_classes, size = (batch_size,)).long().cuda()
    print("before model(x)")
    FV, Logit  = model(x)
    print("after model(x)")
    loss = loss_CE(Logit,y)
    assert not torch.isnan(loss)
    print("after loss_CE")
    loss.backward()
    print("after loss.backward()")
    torch.nn.utils.clip_grad_norm_(model.parameters(), clipping_value)
    print("after clip_grad_norm_")
    optimizer.step()
    print("after optimizer.step()")
  t2 = time.time()
  print("epoch time = ", t2-t1)

print('Finished Training')
```

**Comment by SciPioneer** [comment]
After discussing with other teammates, I realize that our tests don't cover any use case that involves AMD CPU, and currently we don't have a way to reproduce this issue on our end.

Once we improve our test environments by supporting more hardware types later this year, we will revisit this issue.

**Comment by yueruchen** [comment]
Hi @SciPioneer , I met the similar issue on AMD and can you provide some suggestions on solving this issue?

**Comment by DachuanZhao** [comment]
I see the news from jiqichixin.com . I've had similar problems with ```tf.distribute.MirroredStrategy``` ([https://github.com/tensorflow/tensorflow/issues/44976](https://github.com/tensorflow/tensorflow/issues/44976)) . The problem is caused by incompatibility between nvidia ncll and amd IOMMU . Turning off IOMMU in the motherboard may solve it .

**Comment by ROBOTICSENGINEER** [comment]
> 
> 
> I see the news from jiqizhixin.com . I've had similar problems with `tf.distribute.MirroredStrategy` ([tensorflow/tensorflow#44976](https://github.com/tensorflow/tensorflow/issues/44976)) . The problem is caused by incompatibility between nvidia nccl and amd IOMMU . Turning off IOMMU in the motherboard may solve it .

We have tried it, but it did not solve the issue.

**Comment by Dreamurrrr** [comment]
What is `AMD Eng Sample: 100-000000053-04_32/20_N`? I have never heard of a CPU like this.

**Comment by DachuanZhao** [comment]
> > I see the news from jiqizhixin.com . I've had similar problems with `tf.distribute.MirroredStrategy` ([tensorflow/tensorflow#44976](https://github.com/tensorflow/tensorflow/issues/44976)) . The problem is caused by incompatibility between nvidia nccl and amd IOMMU . Turning off IOMMU in the motherboard may solve it .
> 
> We have tried it, but it did not solve the issue.

Have you run the nccl test in [https://github.com/NVIDIA/nccl-tests](https://github.com/NVIDIA/nccl-tests) ? I think you can run it to check whether there is something incompatible .

**Comment by ROBOTICSENGINEER** [comment]
NCCL works without error

```
# nThread 1 nGpus 3 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 1
#
# Using devices
#   Rank  0 Pid  46570 on       nova device  0 [0x05] GeForce GTX 1080 Ti
#   Rank  1 Pid  46570 on       nova device  1 [0x47] GeForce GTX 1080 Ti
#   Rank  2 Pid  46570 on       nova device  2 [0x87] GeForce GTX 1080 Ti
#
#                                                     out-of-place                       in-place
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2   float     sum    49362    0.00    0.00  6e-08    49361    0.00    0.00  6e-08
          16             4   float     sum    49362    0.00    0.00  0e+00    49361    0.00    0.00  3e-08
          32             8   float     sum    49362    0.00    0.00  3e-08    49361    0.00    0.00  3e-08
          64            16   float     sum    49362    0.00    0.00  3e-08    49362    0.00    0.00  1e-08
         128            32   float     sum    49362    0.00    0.00  1e-08    49362    0.00    0.00  1e-08
         256            64   float     sum    49363    0.00    0.00  1e-08    49363    0.00    0.00  1e-08
         512           128   float     sum    49363    0.00    0.00  1e-08    49363    0.00    0.00  1e-08
        1024           256   float     sum    49366    0.00    0.00  1e-07    49364    0.00    0.00  1e-07
        2048           512   float     sum    49366    0.00    0.00  1e-07    49366    0.00    0.00  1e-07
        4096          1024   float     sum    49371    0.00    0.00  1e-07    49370    0.00    0.00  1e-07
        8192          2048   float     sum    49380    0.00    0.00  1e-07    49380    0.00    0.00  1e-07
       16384          4096   float     sum    49407    0.00    0.00  1e-07    49407    0.00    0.00  1e-07
       32768          8192   float     sum   493540    0.00    0.00  1e-07   493539    0.00    0.00  1e-07
       65536         16384   float     sum   493546    0.00    0.00  1e-07   493546    0.00    0.00  1e-07
      131072         32768   float     sum   493571    0.00    0.00  1e-07   493571    0.00    0.00  1e-07
      262144         65536   float     sum   888418    0.00    0.00  1e-07   888417    0.00    0.00  1e-07

```

```
# nThread 1 nGpus 3 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 1
#
# Using devices
#   Rank  0 Pid  46570 on       nova device  0 [0x05] GeForce GTX 1080 Ti
#   Rank  1 Pid  46570 on       nova device  1 [0x47] GeForce GTX 1080 Ti
#   Rank  2 Pid  46570 on       nova device  2 [0x87] GeForce GTX 1080 Ti
#
#                                                     out-of-place                       in-place
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2   float     sum    49362    0.00    0.00  6e-08    49361    0.00    0.00  6e-08
          16             4   float     sum    49362    0.00    0.00  0e+00    49361    0.00    0.00  3e-08
          32             8   float     sum    49362    0.00    0.00  3e-08    49361    0.00    0.00  3e-08
          64            16   float     sum    49362    0.00    0.00  3e-08    49362    0.00    0.00  1e-08
         128            32   float     sum    49362    0.00    0.00  1e-08    49362    0.00    0.00  1e-08
         256            64   float     sum    49363    0.00    0.00  1e-08    49363    0.00    0.00  1e-08
         512           128   float     sum    49363    0.00    0.00  1e-08    49363    0.00    0.00  1e-08
        1024           256   float     sum    49366    0.00    0.00  1e-07    49364    0.00    0.00  1e-07
        2048           512   float     sum    49366    0.00    0.00  1e-07    49366    0.00    0.00  1e-07
        4096          1024   float     sum    49371    0.00    0.00  1e-07    49370    0.00    0.00  1e-07
        8192          2048   float     sum    49380    0.00    0.00  1e-07    49380    0.00    0.00  1e-07
       16384          4096   float     sum    49407    0.00    0.00  1e-07    49407    0.00    0.00  1e-07
       32768          8192   float     sum   493540    0.00    0.00  1e-07   493539    0.00    0.00  1e-07
       65536         16384   float     sum   493546    0.00    0.00  1e-07   493546    0.00    0.00  1e-07
      131072         32768   float     sum   493571    0.00    0.00  1e-07   493571    0.00    0.00  1e-07
      262144         65536   float     sum   888418    0.00    0.00  1e-07   888417    0.00    0.00  1e-07
      524288        131072   float     sum   888438    0.00    0.00  1e-07   888438    0.00    0.00  1e-07
     1048576        262144   float     sum   888529    0.00    0.00  1e-07   888523    0.00    0.00  1e-07
     2097152        524288   float     sum   888726    0.00    0.00  1e-07   888743    0.00    0.00  1e-07
     4194304       1048576   float     sum   889144    0.00    0.01  1e-07   889108    0.00    0.01  1e-07
     8388608       2097152   float     sum   889892    0.01    0.01  1e-07   889872    0.01    0.01  1e-07
    16777216       4194304   float     sum  1680396    0.01    0.01  1e-07  1680325    0.01    0.01  1e-07
    33554432       8388608   float     sum  2470016    0.01    0.02  1e-07  2462953    0.01    0.02  1e-07
    67108864      16777216   float     sum  4836651    0.01    0.02  1e-07  4838822    0.01    0.02  1e-07
   134217728      33554432   float     sum  8784843    0.02    0.02  1e-07  8780533    0.02    0.02  1e-07
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 0.00386344
#
```

**Comment by rohan-varma** [comment]
It seems like we need a POC from AMD to help with this issue. @jithunnair-amd would you be the right person to take a look at this AMD CPU issue or loop in someone who would be? Thanks!

**Comment by mschnepf** [comment]
I have observed a similar issue #50363. I thought it is a problem with non-existing NVLink or the V100 GPUs.
However, also in my example, Pytorch running on multiple-GPU causes a deadlock. Furthermore, I saw in `dmesg`  AMD-VI errors
```
[ 4703.568967] AMD-Vi: Event logged [IO_PAGE_FAULT device=41:00.0 domain=0x000e address=0x000003f80001b100 flags=0x0030]
[ 4703.569037] AMD-Vi: Event logged [IO_PAGE_FAULT device=41:00.0 domain=0x000e address=0x00000000f61390a8 flags=0x0020]
[ 4703.569089] AMD-Vi: Event logged [IO_PAGE_FAULT device=41:00.0 domain=0x000e address=0x00000000f61390b0 flags=0x0020]
[ 4703.981230] AMD-Vi: Event logged [IO_PAGE_FAULT device=41:00.0 domain=0x000e address=0x000002f800010000 flags=0x0030]
[ 4703.981262] AMD-Vi: Event logged [IO_PAGE_FAULT device=41:00.0 domain=0x000e address=0x00000000c41390a8 flags=0x0020]
[ 4703.981290] AMD-Vi: Event logged [IO_PAGE_FAULT device=41:00.0 domain=0x000e address=0x000002f800010000 flags=0x0030]
[ 4703.981319] AMD-Vi: Event logged [IO_PAGE_FAULT device=41:00.0 domain=0x000e address=0x00000000c41390a8 flags=0x0020]
[ 4704.077873] AMD-Vi: Event logged [IO_PAGE_FAULT device=41:00.0 domain=0x000e address=0x00000000c41390b0 flags=0x0020]
```

As recommended, I disabled IUMMO in EFI and now it runs fine.

**Comment by Mirsadeghi** [comment]
I faced the same issue with 2 1080ti GPUs and AMD CPU when using "DistributedDataParallel" by torch 1.81 and Cuda 11. But when change the PyTorch version to 1.6.0, I got this error:

_RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable)._

Then, by applying the above-recommended solution **(passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`)** I resolved the issue.

**Comment by Heermosi** [comment]
I also face with the same problem with 4xA40 GPU and 2x Intel Xeon Gold 6330 on Dell R750xa
I've tested with a pytorch 1.9.0 with cuda 11.2, the module forwarding was blocked and cannot print anything

**Comment by Heermosi** [comment]
I've tried to disable the iommu of Linux, but it cannot help.
I still cannot use all the GPUs.
Before all, let me declare the environment:
Server Hardware:
       Hulk:  Dell R750xa
       CPU:  2xIntel Xeon Gold 6326
       Persistent storage:  8xKoxia 1.92TB
       RAM:  8x 32GB DDR4
       GPU: 4xA40 48GB
Server Software:
       OS: Ubuntu 20.04 Server LTS
       Installed Software: docker-ce, nvidia-docker2, cuda11.2
       Test Container Environment: pytorch1.9.0, python 3.9, cuda 11.2

Scene:
I tried to make pytorch to run DataParallel on GPU 0 and GPU 1, but it cannot work, even if I set the iommu to 'soft'
The synptem looks like every thread ran into forwarding then got stuck, I've printed the __call_impl in module.py, so I knew it blocked there. If you tried to print the gpu status ,it would tell you the GPU 0 and GPU 1 are at full usage ---- however it actually stopped at the entrance and never returns.

When I'm still headaching with the problem to solve, my IT assistant told me it might be a problem with power or pcie.
I thought it was nonsense, but ..... it could be possible,  I finally rewrote the config and ran it on GPU 0 and GPU 3
Then .....
It worked!!! It worked!!!!
The really fucking things happened. Then we tried to find how this mechanic works:
It was able to run on:
   GPU 0, 2
   GPU 0, 3
It was unable to run on all else.
We suspect, it might be a problem with pcie or something else, might be a problem with kernel, pcie, driver or etc.
Since we cannot look into the problem further we stopped here.
We'll contact dell to determine if there is a problem with power, if not, then ...... May you investigate into this further.
This is the sole information I could get.
@wayi1

**Comment by PythaGorilla** [comment]
I had similar issues with pytorch on AMD CPU and 4 A100 in distributed mode

**Comment by hongyuanmei** [comment]
> 

have you fixed this issue? 
I encountered the same problem.

**Comment by hongyuanmei** [comment]
have anyone made any progress in this direction? 
i encountered this problem on a new machine with AMD + 8 x A6000 GPUs

**Comment by mhillebrand** [comment]
@mschnepf You're a life saver! I [disabled IOMMU](https://community.amd.com/t5/knowledge-base/iommu-advisory-for-multi-gpu-environments/ta-p/477468), and now my AMD Threadripper and 4xA6000 GPUs work quite nicely together.

**Comment by Minhyeok01** [comment]
I also encountered this problem on my machine with AMD threadripper 3990x + 4 x A6000 GPUs. I disabled iommu and it works well.

**Comment by AngLi666** [comment]
> I also face with the same problem with 4xA40 GPU and 2x Intel Xeon Gold 6330 on Dell R750xa I've tested with a pytorch 1.9.0 with cuda 11.2, the module forwarding was blocked and cannot print anything

Did you solve this problem? We are building a training server using 2x intel6330 as well. I thought it was AMD related issue until your comments. Could you please share your solutions or current ststaus?

**Comment by Heermosi** [comment]
not a way we can find a solution to this
the only cure may be doing a distributed training, instead of running model simply on 2 gpus with dataparallel.
you may find the program running. but it did not output the correct result.



***@***.***
 
From: AngLi666
Date: 2022-12-26 15:12
To: pytorch/pytorch
CC: Heermosi; Comment
Subject: Re: [pytorch/pytorch] Deadlock in a single machine multi-gpu using dataparlel when cpu is AMD (#52142)
I also face with the same problem with 4xA40 GPU and 2x Intel Xeon Gold 6330 on Dell R750xa I've tested with a pytorch 1.9.0 with cuda 11.2, the module forwarding was blocked and cannot print anything
Did you solve this problem? We are building a training server using 2x intel6330 as well. I thought it was AMD related issue until your comments. Could you please share your solutions or current ststaus?

**Comment by rickywrq** [comment]
A similar issue occurred to me after upgrading the Nvidia driver and CUDA for pytorch 2.
Adding `NCCL_P2P_DISABLE=1` before the python command as mentioned in https://github.com/pytorch/pytorch/issues/23074#issuecomment-975950354 is helpful in my case (for both DataParallel and DistributedDataParallel) at least.

**Comment by samsja** [comment]
> A similar issue occurred to me after upgrading the Nvidia driver and CUDA for pytorch 2. Adding `NCCL_P2P_DISABLE=1` before the python command as mentioned in [#23074 (comment)](https://github.com/pytorch/pytorch/issues/23074#issuecomment-975950354) is helpful in my case (for both DataParallel and DistributedDataParallel) at least.

NCCL_P2P_DISABLE=1 is punitivly slow, I had the same problem with 545 driver, I had to downgrade to 535 to make it work

**Comment by rickywrq** [comment]
> > A similar issue occurred to me after upgrading the Nvidia driver and CUDA for pytorch 2. Adding `NCCL_P2P_DISABLE=1` before the python command as mentioned in [#23074 (comment)](https://github.com/pytorch/pytorch/issues/23074#issuecomment-975950354) is helpful in my case (for both DataParallel and DistributedDataParallel) at least.
> 
> NCCL_P2P_DISABLE=1 is punitivly slow, I had the same problem with 545 driver, I had to downgrade to 535 to make it work

Indeed, we eventually downgraded the driver.

**Comment by KatynaSada** [comment]
# Set the environment variable
os.environ['NCCL_P2P_DISABLE'] = '1'

this solved it for me!
