### ISSUE TITLE
cuda runtime error (8) : invalid device function during ops between cuda tensors

### ISSUE THREAD

**Issue by GPistre** [pytorch/pytorch#524]
Pytorch installed via conda, as well as all the optional dependencies, including magma-cuda80.
`torch.cuda.is_available()` prints True, but operations between tensors raise an error: 

```
import torch

print(torch.cuda.is_available())

x = torch.ones(4, 4).cuda()
y = torch.ones(4, 4).cuda()

x + y

```

```
True
THCudaCheck FAIL file=/data/users/soumith/miniconda2/conda-bld/pytorch-0.1.6_1484802121799/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu line=246 error=8 : invalid device function
Traceback (most recent call last):
  File "/home/gpistre/PycharmProjects/hellopytorch/cuda_test.py", line 8, in <module>
    x + y
  File "/home/gpistre/anaconda2/envs/py35/lib/python3.5/site-packages/torch/tensor.py", line 396, in __add__
    return self.add(other)
RuntimeError: cuda runtime error (8) : invalid device function at /data/users/soumith/miniconda2/conda-bld/pytorch-0.1.6_1484802121799/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:246
```

**Comment by karandwivedi42** [comment]
+1 
Same problem on 2 configs

- CUDA 8; CuDNN v5.1; Ubuntu 16.04
- CUDA 7.5; CuDNN v5; Ubuntu 16.04

**Comment by soumith** [comment]
i'm working on fixing this as we speak.

**Comment by soumith** [comment]
i need to rebuild new Conda binaries.
To confirm, what graphics cards are you running these on?

**Comment by karandwivedi42** [comment]
[NVIDIA 940M](http://www.geforce.com/hardware/notebook-gpus/geforce-940m)

Torch CUDA and CuDNN work perfectly.

**Comment by soumith** [comment]
ok yea that's one of the cards that has the issue. I didn't build binaries with Cuda-capability 5.0 support, adding it now.

**Comment by apaszke** [comment]
As an alternative you can try building it from source (like Lua torch does). This should build it for your arch.

**Comment by GPistre** [comment]
Mine is a GTX 960M

**Comment by soumith** [comment]
if you reinstall pytorch from conda, this should now be fixed.
I am also going to commit refreshed pip wheels in ~2 hours

**Comment by karandwivedi42** [comment]
Works for me! Thanks :)

**Comment by soumith** [comment]
fixed both conda and pip binaries now

**Comment by shakti365** [comment]
I am having the same issue with my Nvidia 820M

**Comment by delijati** [comment]
Had the same error the default is not compiling with `Cuda 2.0`. I had to compile it by my own:

```
CC=/usr/bin/gcc-4.9 TORCH_CUDA_ARCH_LIST="2.0 3.0 3.5 5.2 6.0 6.1+PTX" env3/bin/python setup.py bdist_wheel
```

**Comment by delijati** [comment]
Had the same error the default is not compiling with `Cuda 2.0`. I compile  with `2.0`
```
CC=/usr/bin/gcc-4.9 TORCH_CUDA_ARCH_LIST="2.0 3.0 3.5 5.2 6.0 6.1+PTX" env3/bin/python setup.py bdist_wheel
```

**Comment by fjaragones** [comment]
Had the same error when running the code in fresh built Docker image (compiling from source).
GeForce GTX 950M
gpu is detected inside container, but pytorch example code produces error when working with cuda
'''
$ nvidia-docker run --rm -ti --ipc=host ptbare

root@9f82cba71dad:/workspace# source activate pytorch-py35
(pytorch-py35) root@9f82cba71dad:/workspace# python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import print_function
>>> import torch
>>> if torch.cuda.is_available():
...   print("OK")
... 
OK
>>> 
>>> x = torch.rand(5, 3)
>>> y = torch.rand(5, 3)
>>> x+y

 0.7594  0.4101  0.0759
 1.0612  0.4475  0.1293
 1.1452  1.2344  0.8142
 1.7445  1.1804  1.2515
 1.5162  1.5922  1.3437
[torch.FloatTensor of size 5x3]

>>> x = x.cuda()
>>> y = y.cuda()
>>> x+y
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/tensor.py", line 293, in __add__
    return self.add(other)
RuntimeError: cuda runtime error (8) : invalid device function at /tmp/pip-on0rh4dz-build/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:247
>>> x

 0.5495  0.0533  0.0517
 0.9988  0.1758  0.0185
 0.5467  0.3758  0.3547
 0.8154  0.2422  0.4138
 0.8291  0.7782  0.4513
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]

>>> y

 0.2099  0.3569  0.0242
 0.0624  0.2717  0.1108
 0.5985  0.8586  0.4595
 0.9291  0.9382  0.8377
 0.6871  0.8140  0.8924
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]
'''

**Comment by ngimel** [comment]
Dockerfile does not compile for 5.0 architecture. Modify this line https://github.com/pytorch/pytorch/blob/master/Dockerfile#L29 to include 5.0 architecture.

**Comment by fjaragones** [comment]
Thanks, works changing the line to 
```
RUN TORCH_CUDA_ARCH_LIST="3.5 5.0 5.2 6.0 6.1+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
```

**Comment by fjaragones** [comment]
After restarting host machine, cuda is available inside docker image and example works as expected. Thanks!

**Comment by nguyenv7** [comment]
Hello, this problem still appear in my system:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro 2000         Off  | 0000:01:00.0      On |                  N/A |
| 30%   52C    P8    N/A /  N/A |    463MiB /   956MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

with Ubuntu 16.04, Cuda 7.5, installed by pip: pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp27-cp27mu-manylinux1_x86_64.whl
