### ISSUE TITLE
cuda runtime error (2) : out of memory at Siamese Network

### ISSUE THREAD

**Issue by MaximArtemev** [pytorch/pytorch#5249]
Hi
I'm trying to implement Siamese Network in pytorch with gpu support but constantly getting RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/generic/THCTensorMathPairwise.cu:102

My model is defined as follows

```
class SiameseNetwork(nn.Module):
    def __init__(self):
        super(SiameseNetwork, self).__init__()
        
        self.embedding = nn.Embedding(ru.vectors.size(0), ru.vectors.size(1), padding_idx=2)
        self.embedding.weight = nn.Parameter(ru.vectors)
        self.embedding.weight.requires_grad = False
        
        self.lstm = nn.LSTM(300, 300, 2, batch_first=True, bidirectional=True, dropout=.05)
        
        self.dropout = nn.Dropout(p=.2)
            #nn.LSTM(300, 300, 30, batch_first=True, bidirectional=True, dropout=.05),

        self.fc1 = nn.Sequential(
            nn.Linear(300*2*300, 1500),
            nn.Sigmoid(),#inplace=True),

            nn.Linear(1500, 100),
            nn.Sigmoid()
        )

    def forward_once(self, x):
        output = self.embedding(x)
        output, _ = self.lstm(output)
        output = self.dropout(output)
        output = output.view(output.size()[0], -1)
        output = self.fc1(output)
        return output

    def forward(self, input1, input2):
        output1 = self.forward_once(input1)
        output2 = self.forward_once(input2)
        return output1, output2
```

and I'm using a custom loss:

```
class ContrastiveLoss(torch.nn.Module):
    """
    Contrastive loss function.
    Based on: http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf
    """

    def __init__(self, margin=2.0):
        super(ContrastiveLoss, self).__init__()
        self.margin = margin

    def forward(self, output1, output2, label):
        euclidean_distance = F.pairwise_distance(output1, output2)
        loss_contrastive = torch.mean((1-label) * torch.pow(euclidean_distance, 2) +
                                       (label) * torch.pow(torch.clamp(self.margin - euclidean_distance, min=0.0), 2))
        return loss_contrastive
```

Then after

```
net = SiameseNetwork().cuda(1)
criterion = ContrastiveLoss()
parameters = filter(lambda p: p.requires_grad, net.parameters())
optimizer = optim.Adam(parameters, lr=0.1)
loss_history = [] 
iteration_number= 0

net.train()

for epoch in range(100):
    epoch_end = time()
    for i, data in enumerate(train_dataloader, 0):
        text1, text2 , label = data
        text1, text2 , label = Variable(text1).cuda(1), Variable(text2).cuda(1) , Variable(label).cuda(1)
        output1,output2 = net(text1,text2)
        optimizer.zero_grad()
        loss_contrastive = criterion(output1,output2,label)
        loss_contrastive.backward()

        loss_history.append(loss_contrastive.data[0])
        optimizer.step()

```

I'm getting 

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-33-e2c1dc9f69ec> in <module>()
     12         optimizer.zero_grad()
     13         loss_contrastive = criterion(output1,output2,label)
---> 14         loss_contrastive.backward()
     15 
     16         writer.add_scalar('data/step_loss', loss_contrastive.data[0])

~/anaconda3/envs/mrartemev/lib/python3.6/site-packages/torch/autograd/variable.py in backward(self, gradient, retain_graph, create_graph, retain_variables)
    165                 Variable.
    166         """
--> 167         torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
    168 
    169     def register_hook(self, hook):

~/anaconda3/envs/mrartemev/lib/python3.6/site-packages/torch/autograd/__init__.py in backward(variables, grad_variables, retain_graph, create_graph, retain_variables)
     97 
     98     Variable._execution_engine.run_backward(
---> 99         variables, grad_variables, retain_graph)
    100 
    101 

RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/generic/THCTensorMathPairwise.cu:102
```

I'm using cuda 8.0 and cudann 5, installed pytorch with conda.

**Comment by ezyang** [comment]
I read the code and didn't see any obvious history leaks. `loss_history` does look suspicious; if you get rid of it (or explicitly say `float(loss_contrastive.data[0])`) what happens? Does it OOM when you run it on CPU?

**Comment by ezyang** [comment]
Actually, your linear layer looks pretty big. The weights alone are 1G, and then you need another 1G for the gradients. Take a look at https://github.com/pytorch/pytorch/issues/958 for some guidance on the issue.

**Comment by MaximArtemev** [comment]
Yeah, I’ve checked, loss_contrastive.data[0] is a float. 
Thanks for the link, now I can calculate memory usage of my model. But the thing is, I’m running it on Tesla k40, so this 2Gb on fc layer is kinda ok. I’ll check it later today anyways.

**Comment by SsnL** [comment]
@MaximArtemev Well you are training a Siamese net. So it's 4G per iteration.

**Comment by MaximArtemev** [comment]
You were right, thank you!
The problem was in that linear layer.
Much thanks :)
