### ISSUE TITLE
Cpp frontend torch mask select has an effect on thrust::sort_by_key

### ISSUE THREAD

**Issue by Tomichi** [pytorch/pytorch#52663]
## 🐛 Bug
Hi, I use CPP torch fronted API  with thrust library (but independent). When I call torch function `mask_select` on tensor which is a store at GPU and mask which is store on GPU too (result is store on GPU), I get an error.

`terminate called after throwing an instance of 'thrust::system::system_error'
  what():  radix_sort: failed on 1st step: cudaErrorInvalidDevice: invalid device ordinal` 
which was called by `thrust::sort_by_key` function.

When I comment section with masking tensor, ```thrust::sort_by_keys``` works normally and fine. Or when I move mask tensor to CPU. But it works, I am not sure, if it a good approach to have a mask tensor on CPU and other tensors are store at GPU? (my second questions)

## To Reproduce
I create a small demo program, with the issue.
`main.cu`

```cpp
#include <thrust/execution_policy.h>
#include <torch/torch.h>
#include <iostream>
#include <thrust/host_vector.h>
#include <thrust/device_vector.h>
#include <thrust/sort.h>

int main() {
{
        std::vector<float> numbers = {15.1, 74.9, 16.2, 75.8, 17.3, 76.7};
        torch::Tensor t = torch::from_blob(numbers.data(), {static_cast<long>(numbers.size())},
                                           torch::TensorOptions().dtype(torch::kFloat32)).to(torch::kCUDA);
        torch::Tensor mask = (t < 20);
        std::cout << t.size(0) << " " << t.device() << "\n";
        std::cout << mask.size(0) << " " << mask.device() << "\n";
        auto gpu_result = t.masked_select(mask).view({-1});
        std::cout << gpu_result.size(0) << " " << gpu_result.device() << "\n";
        std::cout << gpu_result << "\n";
    }

    std::cout << "Thrust---\n";
    thrust::host_vector<int> keysOnHost(6);
   //fiill by
    keysOnHost[0] = 1;
    keysOnHost[1] = 4;
    keysOnHost[2] = 2;
    keysOnHost[3] = 8;
    keysOnHost[4] = 5;
    keysOnHost[5] = 7;
    thrust::host_vector<char> valuesOnHost(6);
    valuesOnHost[0] = 'a';
    valuesOnHost[1] = 'b';
    valuesOnHost[2] = 'c';
    valuesOnHost[3] = 'd';
    valuesOnHost[4] = 'e';
    valuesOnHost[5] = 'f';
    thrust::device_vector<int> keys = keysOnHost;
    thrust::device_vector<char> values = valuesOnHost;
    thrust::sort_by_key(keys.begin(), keys.end(), values.begin());
    thrust::copy(keys.begin(), keys.end(), keysOnHost.begin());
    thrust::copy(values.begin(), values.end(), valuesOnHost.begin());
    for (int i = 0; i < 6; ++i) {
        std::cout << keysOnHost[i] << " ";
    }
    std::cout << "\n";
    for (int i = 0; i < 6; ++i) {
        std::cout << valuesOnHost[i] << " ";
    }
    std::cout << "\n";
    std::cout << "END\n";
}
```

1. Code above reproduce bad behavior when call  `t.masked_select(mask)`  and after that call `thrust::sort_by_keys` function.
2. When I change row `torch::Tensor mask = (t < 20);` -> `torch::Tensor mask = (t < 20).to(torch::kCPU);` it works when another tensors are store at GPU. But I am not sure if, this approach could throw exception when i use different store tensors. 

## Expected behavior
My target is, that masking tensor on GPU, where the mask is stored at GPU, works the same as now, but not have an effect on the trust::sort_by_key function... 
## Environment

```
Collecting environment information...
PyTorch version: 1.7.1 for cuda 11.0
Is debug build: Yes
CUDA used to build PyTorch: Yes
ROCM used to build PyTorch: No

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.17.5

Python version: 3.8 (64-bit runtime)
Is CUDA available: Yes, cuda:11.0

CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 450.102.04
cuDNN version:  8.0.5.39
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
HIP runtime version: No
MIOpen runtime version: No

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```
I installed the torch by the source to /usr/local.
Thanks for the help.

**Comment by ngimel** [comment]
Bumping priority, as the surface of this bug is pretty big:
Extensions using thrust/cub cannot coexist with pytorch code using thrust/cub. The "invalid device ordinal" error comes from this line https://github.com/NVIDIA/cub/blob/499a7bad3416fcc71a7c50351d6b3cdbf3fbbc27/cub/util_device.cuh#L298, where DeviceCount() instead of correctly returning cached value returns 0. 
It seems to be related to pytorch build options, because in a small standalone repro of shared library and application both using cub I cannot reproduce this behavior, local static used for device count cache behaves correctly. 
A simpler reproduction:
```
import torch
from torch.utils import cpp_extension

cuda_source = """
#include <iostream>
#include <cub/cub.cuh>
void my_fun() {
    auto ndev = cub::DeviceCount();
    std::cout << "cub device count " << ndev << std::endl; // outputs 0, wrong!
    if (!ndev) {
        std::cout << "where did all my gpus go?" << std::endl;
    }
}
"""


cpp_source = """
    void my_fun(void);
"""

module = torch.utils.cpp_extension.load_inline(
    name="cuda_test_extension",
    cpp_sources=cpp_source,
    cuda_sources=cuda_source,
    functions="my_fun",
    extra_cuda_cflags=["--extended-lambda"],
    verbose=True,
)

a=torch.randperm(80000, device="cuda") #invoke pytorch cub code
module.my_fun()
```

**Comment by ngimel** [comment]
Related:
https://github.com/NVIDIA/cub/issues/260
https://github.com/NVIDIA/thrust/issues/1371
There's a fix for this in the latest cub
https://github.com/NVIDIA/cub/commit/bc209e69313dbf05492835afd56fe8408c113a3e
Later they brought back `inline` instead of `__forceinline__`, but looks like just `inline` is also problematic (or I could have messed up my build):
https://github.com/NVIDIA/cub/commit/f7cd601d0281de1a2c96b4979d727aa7828a0b6f

**Comment by ngimel** [comment]
Compiling torch with `-Xcompiler -fno-gnu-unique` solves this problem, we should add this to our regular and binary build scripts. Thanks  to @VoVAllen for the tip https://github.com/NVIDIA/thrust/issues/1401#issuecomment-806403746

**Comment by twmht** [comment]
@ngimel 

Do we have torch version compiled with `-Xcompiler -fno-gnu-unique`?

**Comment by ngimel** [comment]
This was (mostly) solved in pytorch 1.9

**Comment by jakkes** [comment]
I am getting this error using libtorch 1.10. How is it "mostly" solved, what can I do to work around the issue? I am not very keen on building from source..

**Comment by twmht** [comment]
@jakkes 

Did you mix with other library (for example, TensorRT?)

**Comment by jakkes** [comment]
Yes, I have another dependency (non-public lib) that is also using thrust. However, I managed to fix my issue by linking with that lib prior to libtorch in my cmake file. I'm not sure why it solved my issue, but it did...

**Comment by Ray-Eldath** [comment]
I met the same problem using torch v2.4.0 in:
```python
subseq_cci_kernel<<<chunk_len, 1>>>(chunk_st, chunk_ed, minimal_chunk_size, attn_ptr,
                                        attn.stride(0), attn.stride(1), tmp_ptr);
    cudaDeviceSynchronize();
    std::cout << "subseq_cci_kernel exited" << std::endl;
    ResultMinOperator ops;
    auto res = thrust::reduce(
        thrust::device, tmp_ptr, tmp_ptr + tmp_len,
        Result(chunk_st, chunk_ed, cuda::std::numeric_limits<float>::infinity()), ops);
    std::cout << "reduced" << std::endl;
    cudaFree(tmp_ptr);
```
with:
```python
subseq_cci_kernel exited
Traceback (most recent call last):
  File "/home/cadfd3db-f9fd-470b-b319-74fd83f27e89/subseq/test.py", line 11, in <module>
    print(ops.subseq_cci(attn, valid_chunks))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cadfd3db-f9fd-470b-b319-74fd83f27e89/subseq/ops.py", line 10, in subseq_cci
    return torch.ops.subseq.subseq_cci(attn, valid_chunks, 128)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaohan_li@idm.teecertlabs.com/.pyenv/versions/3.12.9/envs/lmcache/lib/python3.12/site-packages/torch/_ops.py", line 1061, in __call__
    return self_._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: after reduction step 1: cudaErrorInvalidDevice: invalid device ordinal
```

which is strange because the problem seems to be fixed according to this issue, and the test script in https://github.com/pytorch/pytorch/issues/52663#issuecomment-803642518 actually gives correct result (`cub device count 1`). Do we have any idea on how this problem manifested again?

**Comment by Ray-Eldath** [comment]
I met this problem when writing a custom CUDA kernel using THRUST:
```cuda
subseq_cci_kernel<<<chunk_len, 1>>>(chunk_st, chunk_ed, minimal_chunk_size, attn_ptr, stride_ai,
                                        stride_aj, tmp_ptr);
cudaDeviceSynchronize();
Result res;
void *d_temp_storage = nullptr;
size_t temp_storage_bytes = 0;
auto err = cub::DeviceReduce::Reduce(d_temp_storage, temp_storage_bytes, tmp_ptr, &res,
                                     chunk_len, ops, init);
if (err != cudaSuccess) {
  printf("CUDA Error: %s\n", cudaGetErrorString(err));
  exit(-1);
}
```
the code kept report
```
CUDA error 700 [~/cccl/cub/cub/util_device.cuh, 96]: an illegal memory access was encountered
PtxVersion -1
CUDA error 101 [~/cccl/cub/cub/util_device.cuh, 352]: invalid device ordinal
CUDA error 101 [~/cccl/cub/cub/device/dispatch/dispatch_reduce.cuh, 505]: invalid device ordinal
CUDA Error: invalid device ordinal
```
even I've already *manually* set include path to use the latest version of `cccl`. After adding some debugging printing it clearly shows there're some `device = -1` issue (`PtxVersion -1` which actually shows the `int device` argument of `PtxVersion`), despite that the debugging script used in https://github.com/pytorch/pytorch/issues/52663#issuecomment-803642518 actually returns *the correct* result. What's weird about this problem is that it only shows when directly running the code, attaching a debugger (`cuda-gdb`) would actually make it disappear. 🤔 

Does anyone knows why is the case? Seems all solutions so far do not work. I've tried adding `-Xcompiler=-fno-gnu-unique` to `extra_compile_args`, or using the latest version of `cccl`, or force the `CurrentDevice()` function to return `0`, but non of them works.

Any help would be much appreciated!
