### ISSUE TITLE
PyTorch 1.7.1 with RTX 3070 CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by thenamangoyal** [pytorch/pytorch#52736]
## 🐛 Bug

PyTorch 1.7.1 installed with CUDA 10.2 on a Geforce RTX 3070 produces `CUDA error: no kernel image is available for execution on the device`

GeForce RTX 3070 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.

## To Reproduce

```
>>> import torch
>>> torch.__version__
'1.7.1'
>>> torch.tensor([1.0]).cuda()
./lib/python3.6/site-packages/torch/cuda/__init__.py:104: UserWarning:
GeForce RTX 3070 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the GeForce RTX 3070 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./lib/python3.6/site-packages/torch/tensor.py", line 179, in __repr__
    return torch._tensor_str._str(self)
  File "./lib/python3.6/site-packages/torch/_tensor_str.py", line 372, in _str
    return _str_intern(self)
  File "./lib/python3.6/site-packages/torch/_tensor_str.py", line 352, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "./lib/python3.6/site-packages/torch/_tensor_str.py", line 241, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "./lib/python3.6/site-packages/torch/_tensor_str.py", line 89, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

## Environment

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 3070
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.7.1
[pip3] torchaudio==0.7.2
[pip3] torchvision==0.8.2
[conda] Could not collect

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Ubuntu 18.04.5 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.7
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: GeForce RTX 3070 
 - Any other relevant information:

## Additional context

https://github.com/pytorch/pytorch/issues/45028

cc @malfet @seemethere @walterddr @ngimel

**Comment by skyline75489** [comment]
The error message is clear. You’ll need CUDA 11.x to use the 30X0 cards

**Comment by malfet** [comment]
This is expected behavior, as CUDA-10.2 does not support sm_80+ capable GPU

**Comment by mohbattharani** [comment]
I have CUDA 11.4, Drivers: 470.86, PyTorch: 1.11.0+cu102
I got the same msg after running the code for a while.

**Comment by owardlaw** [comment]
I have cuda 11.3, GTX 3070 

import torch
torch.cuda.is_available()

output == true...

**Comment by mohbattharani** [comment]
Solution: I have solved the issue. 
CUDA: 11.4
Driver: 470.103.01
PyTorch: 1.11.0
