### ISSUE TITLE
libtorch 1.8.0 with CUDA 11.1: CUDA error: no kernel image is available for execution..

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#53476]
using libtorch 1.8.0 with CUDA 11.1 on linux is throwing the error:
 _CUDA error: no kernel image is available for execution on the device_
e.g. running code like
```
 auto t=torch::ones({2,1}).cuda();
 auto m=torch::nn::Linear(1,2);
 m->to(torch::kCUDA);
 auto r=m->forward(t);
```

normally I'd expect this to be some error in the NVIDIA device driver on my side,
but in this case something might be off with the new libtorch libraries for 11.1

on the same machine, i am able to run:
- libtorch 1.7.1 & cuda 11.0
- libtorch 1.8.0 & cuda 10.2
- pytorch 1.8.0 & cuda 11.1

and if I link my c++ code to the _pytorch_ installation instead of the _libtorch_ dirs,
e.g. _~/miniconda3/lib/python3.8/site-packages/torch_,
i'm also able to run cuda 11.1

more detail on the runtime error:
```
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: no kernel image is available for execution on the device
Exception raised from launch_unrolled_kernel at /pytorch/aten/src/ATen/native/cuda/CUDALoops.cuh:132 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f336c3702f2 in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f336c36d67b in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libc10.so)
frame #2: void at::native::gpu_kernel_impl<__nv_hdl_wrapper_t<false, true, __nv_dl_tag<void (*)(at::TensorIterator&, bool), &at::native::copy_device_to_device, 7u>, float (float)> >(at::TensorIteratorBase&, __nv_hdl_wrapper_t<false, true, __nv_dl_tag<void (*)(at::TensorIterator&, bool), &at::native::copy_device_to_device, 7u>, float (float)> const&) + 0x6dc (0x7f33f340af3c in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cuda_cu.so)
frame #3: void at::native::gpu_kernel<__nv_hdl_wrapper_t<false, true, __nv_dl_tag<void (*)(at::TensorIterator&, bool), &at::native::copy_device_to_device, 7u>, float (float)> >(at::TensorIteratorBase&, __nv_hdl_wrapper_t<false, true, __nv_dl_tag<void (*)(at::TensorIterator&, bool), &at::native::copy_device_to_device, 7u>, float (float)> const&) + 0x12b (0x7f33f3417d8b in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cuda_cu.so)
frame #4: at::native::copy_device_to_device(at::TensorIterator&, bool) + 0xaaf (0x7f33f33ff12f in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cuda_cu.so)
frame #5: <unknown function> + 0x18d9d27 (0x7f33f3400d27 in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cuda_cu.so)
frame #6: <unknown function> + 0xf151d9 (0x7f33e05cc1d9 in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xf14535 (0x7f33e05cb535 in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cpu.so)
frame #8: at::native::copy_(at::Tensor&, at::Tensor const&, bool) + 0x44 (0x7f33e05cc094 in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cpu.so)
frame #9: at::native::(anonymous namespace)::addmm_out_cuda_impl(at::Tensor&, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar) + 0x3f5 (0x7f33f3851c95 in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cuda_cu.so)
frame #10: at::native::addmm_out_cuda(at::Tensor&, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar) + 0x57 (0x7f33f3854837 in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cuda_cu.so)
frame #11: at::native::addmm_cuda(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar) + 0x73 (0x7f33f3854903 in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cuda_cu.so)
frame #12: <unknown function> + 0xb6cea7 (0x7f33f2693ea7 in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cuda_cu.so)
frame #13: <unknown function> + 0xb6cf3e (0x7f33f2693f3e in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cuda_cu.so)
frame #14: at::Tensor c10::Dispatcher::call<at::Tensor, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar)> const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar) const + 0x1ec (0x7f33e0ccae9c in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cpu.so)
frame #15: at::addmm(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar) + 0xc1 (0x7f33e0b32a41 in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x2bfce3b (0x7f33e22b3e3b in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x2bfd47e (0x7f33e22b447e in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cpu.so)
frame #18: at::Tensor c10::Dispatcher::call<at::Tensor, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar)> const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar) const + 0x1ec (0x7f33e0ccae9c in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cpu.so)
frame #19: at::addmm(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar) + 0xc1 (0x7f33e0b32a41 in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cpu.so)
frame #20: torch::nn::LinearImpl::forward(at::Tensor const&) + 0x9b (0x7f33e2f9078b in /home/t/libtorch.1.8.0/11.1/libtorch/lib/libtorch_cpu.so)
frame #21: cudatest + 0x135 (0x7f343fbe23f5 in /home/t/ktorch/ktorch.so)
frame #22: /home/t/q/l64/q() [0x4a3a59]
frame #23: /home/t/q/l64/q() [0x44a03e]
frame #24: /home/t/q/l64/q() [0x44a5f1]
frame #25: /home/t/q/l64/q() [0x44b26a]
frame #26: /home/t/q/l64/q() [0x448f8f]
frame #27: /home/t/q/l64/q() [0x44c458]
frame #28: /home/t/q/l64/q() [0x40bfd7]
frame #29: /home/t/q/l64/q() [0x4114e0]
frame #30: /home/t/q/l64/q() [0x4044d8]
frame #31: __libc_start_main + 0xe7 (0x7f344e507bf7 in /lib/x86_64-linux-gnu/libc.so.6)
frame #32: /home/t/q/l64/q() [0x4045b1]
```
 

cc @ngimel @aocsa

**Comment by skyline75489** [comment]
Thanks for the feedback! Please do not delete the issue template entirely and try to fill the context needed. There's [collect_env.py](https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py) that helps you do that.

**Comment by meganset** [comment]
ok, the collect_env.py information is below:

## Environment

Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py38h1e0a361_2    conda-forge
[conda] mkl_fft                   1.3.0            py38h5c078b8_1    conda-forge
[conda] mkl_random                1.2.0            py38hc5bc63f_1    conda-forge
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.8.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu111    pytorch

**Comment by meganset** [comment]
because collect_env is oriented toward the python environment (which is running fine with CUDA 11.1),
i'm also including the information from _torch::show_config_, 
which I can call from with the C++/libtorch environment where I'm having the problem:

## C++ torch::show_config

PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

**Comment by malfet** [comment]
@meganset so, can you please confirm that your code works fine using CUDA-11.1, but fails using CUDA-10.2?

**Comment by meganset** [comment]
No, other way.
libtorch 1.8.0 with the 10.2 zip is working fine
libtorch 1.8.0 with the 11.1 CUDA zip (libtorch-shared-with-deps-1.8.0+cu111.zip) is failing with the "no kernal image.." error.

but pytorch 1.8.0 with the conda environment for 11.1 CUDA also works.
to me, this means my GPU's & device driver are ok for 11.1 CUDA.

also, if i compile c++ code pointing to the pytorch (not libtorch) libraries,
i am also able to run a c++ only in a 11.1 CUDA environment.

this is what makes me suspicious of the libtorch .zip file for 1.8.0 for CUDA 11.1

**Comment by DrDryg** [comment]
Im experiencing issues in Windows 10 with LibTorch that might be related to this. It has been working fine with a nightly build of 1.8 from december. But after upgrading to 1.8.0 with cuda 11.1 all my unittests calling function with CUDA fails with this message:

The particular message below comes from comparing two tensors, i.e.:

Tensor cmp = t1.gt(t2);

Message: 
        Test method UnitTestCSTorch.UnitTest_CompareOperators.TestTensor_Gt_CUDA threw exception: 
        System.Exception: Could not run 'aten::empty.memory_format' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty.memory_format' is only available for these backends: [CPU, MkldnnCPU, SparseCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradNestedTensor, UNKNOWN_TENSOR_TYPE_ID, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].
        
        CPU: registered at aten\src\ATen\RegisterCPU.cpp:5925 [kernel]
        MkldnnCPU: registered at aten\src\ATen\RegisterMkldnnCPU.cpp:284 [kernel]
        SparseCPU: registered at aten\src\ATen\RegisterSparseCPU.cpp:557 [kernel]
        BackendSelect: registered at aten\src\ATen\RegisterBackendSelect.cpp:596 [kernel]
        Named: registered at ..\..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
        AutogradOther: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:8707 [autograd kernel]
        AutogradCPU: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:8707 [autograd kernel]
        AutogradCUDA: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:8707 [autograd kernel]
        AutogradXLA: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:8707 [autograd kernel]
        AutogradNestedTensor: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:8707 [autograd kernel]
        UNKNOWN_TENSOR_TYPE_ID: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:8707 [autograd kernel]
        AutogradPrivateUse1: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:8707 [autograd kernel]
        AutogradPrivateUse2: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:8707 [autograd kernel]
        AutogradPrivateUse3: registered at ..\..\torch\csrc\autograd\generated\VariableType_4.cpp:8707 [autograd kernel]
        Tracer: registered at ..\..\torch\csrc\autograd\generated\TraceType_4.cpp:10612 [kernel]
        Autocast: fallthrough registered at ..\..\aten\src\ATen\autocast_mode.cpp:250 [backend fallback]
        Batched: registered at ..\..\aten\src\ATen\BatchingRegistrations.cpp:1016 [backend fallback]
        VmapMode: fallthrough registered at ..\..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]

**Comment by DrDryg** [comment]
I downloaded the nighly build instead and it worked fine (cuda 11.1 - release). So there is for sure something not so stable with the stable v1.8.0 of libtorch with cuda11.1.

**Comment by DrDryg** [comment]
The stable 1.8 version with CUDA10.2 also works fine. I can probably do some more investigations and can provide some feedback if you ask for it. But Ill wait and see what you come up with here before doing some more investigations of my own.

**Comment by meganset** [comment]
This problem seems to be fixed in libtorch 1.8.1  with CUDA 11.1 -- I'm not getting the CUDA error in my initial tests.

**Comment by lamhoangtung** [comment]
@meganset I just did some test with libtorch 1.8.1 (my issue was #54053 and kinda similar to you) and the problem still there ...

**Comment by lamhoangtung** [comment]
@meganset I just the test again in libtorch 1.8.1 and the problem seems to be fixed

**Comment by meganset** [comment]
Very good, thanks for checking.

It looks like the libtorch version 1.8.0 problems reported here and in issue #54053 were fixed in 1.8.1
My guess is that some missing CUDA arch and CUDA gencodes were restored ( something like in issue #53164)
but not sure how to verify this easily.
I have another issue on deriving the arch and gencodes from torch::show_config (issue #54829)
I'm hoping that something similar to torch.cuda.get_arch_list() for the c++ environment

```
>>> torch.cuda.get_arch_list()
['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
```

Even with the fix to libtorch version 1.8.1, I'm not seeing this same list from the output of torch::show_config,
so not sure if I'm correct about gencodes..
