### ISSUE TITLE
hipErrorNoBinaryForGpu: Coudn't find binary for current devices!

### ISSUE THREAD

**Issue by styler00dollar** [pytorch/pytorch#53738]
## 🐛 Bug

Using pytorch or using the official install instructions result in ``hipErrorNoBinaryForGpu: Coudn't find binary for current devices!`` for the rocm version of pytorch.

## To Reproduce

- Installing rocm with ``yay -S rocm-dev rocm-utils rocm-libs``
- Fixing [Issue 53452](https://github.com/pytorch/pytorch/issues/53452) by installing ``yay -S ncurses5-compat-libs``

Then either:
- ``pip install torch -f https://download.pytorch.org/whl/rocm4.0.1/torch_stable.html``
(currently redirects to ``https://download.pytorch.org/whl/rocm4.0.1/torch-1.8.0%2Brocm4.0.1-cp39-cp39-linux_x86_64.whl``)
- ``import pytorch``
or
- ``pip install ninja && pip install 'git+https://github.com/pytorch/vision.git@v0.9.0'``

## Expected behavior

Both should work without errors.

## Environment

- PyTorch Version: 1.8 (https://download.pytorch.org/whl/rocm4.0.1/torch-1.8.0%2Brocm4.0.1-cp39-cp39-linux_x86_64.whl)
- rocm-dev 4.0.0-2, rocm-libs 4.0.0-2, rocm-utils 4.0.0-2
- OS: Arch Linux (Manjaro)
- Installed with pip inside anaconda
- Python 3.9.1
- RX470 (gfx803)+ I7 4770

## Additional context

[Issue 53452](https://github.com/pytorch/pytorch/issues/53452) can be fixed by installing ``yay -S ncurses5-compat-libs``, but errors still appear after fixing the initial ``ImportError: libtinfo.so.5: cannot open shared object file: No such file or directory``.

```
(pytorch_env) [x codes]$ pip install torch -f https://download.pytorch.org/whl/rocm4.0.1/torch_stable.html
*(installs without errors)*
(pytorch_env) [x codes]$ python
Python 3.9.1 (default, Feb  6 2021, 06:49:13) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
/data/jenkins_workspace/centos_pipeline_job_4.0/rocm-rel-4.0/rocm-4.0-26-20210119/7.7/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
Abgebrochen (Speicherabzug geschrieben)
(pytorch_env) [x codes]$ rocm-smi


========================ROCm System Management Interface========================
================================================================================
GPU  Temp   AvgPwr   SCLK    MCLK     Fan     Perf  PwrCap  VRAM%  GPU%  
0    38.0c  16.197W  751Mhz  1650Mhz  28.63%  auto  85.0W     3%   0%    
================================================================================
==============================End of ROCm SMI Log ==============================
```

I also noticed that the install instructions added the second command ``pip install ninja && pip install 'git+https://github.com/pytorch/vision.git@v0.9.0'``, but that also results in the same error.

```
(pytorch_env) [x codes]$ pip install ninja && pip install 'git+https://github.com/pytorch/vision.git@v0.9.0'
Defaulting to user installation because normal site-packages is not writeable
Collecting ninja
  Downloading ninja-1.10.0.post2-py3-none-manylinux1_x86_64.whl (107 kB)
     |████████████████████████████████| 107 kB 4.1 MB/s 
Installing collected packages: ninja
Successfully installed ninja-1.10.0.post2
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/pytorch/vision.git@v0.9.0
  Cloning https://github.com/pytorch/vision.git (to revision v0.9.0) to /tmp/pip-req-build-h9v0xa2z
    ERROR: Command errored out with exit status -6:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-h9v0xa2z/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-h9v0xa2z/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-34yl5z6o
         cwd: /tmp/pip-req-build-h9v0xa2z/
    Complete output (1 lines):
    /data/jenkins_workspace/centos_pipeline_job_4.0/rocm-rel-4.0/rocm-4.0-26-20210119/7.7/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
    ----------------------------------------
ERROR: Command errored out with exit status -6: python setup.py egg_info Check the logs for full command output.
```

cc @jeffdaily @sunway513

**Comment by TiagoMAntunes** [comment]
+1 same problem. RTX 480 ubuntu 18.02
<details>
<summary>rocminfo output</summary>

```ROCk module is loaded
Able to open /dev/kfd read-write
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
  Uuid:                    CPU-XX                             
  Marketing Name:          Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3300                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            4                                  
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    16333232(0xf939b0) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16333232(0xf939b0) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
    N/A                      
*******                  
Agent 2                  
*******                  
  Name:                    gfx803                             
  Uuid:                    GPU-XX                             
  Marketing Name:          Ellesmere [Radeon RX 470/480/570/570X/580/580X]
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26591(0x67df)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1326                               
  BDFID:                   256                                
  Internal Node ID:        1                                  
  Compute Unit:            36                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    4194304(0x400000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx803          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***             ```
</details>

**Comment by interfect** [comment]
Same problem here on Ubuntu 20.04 with an RX480, as soon as I import the (ostensibly lazily initialized) `torch.cuda`:

<details>
```
/opt/rocm/bin/rocminfo
ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 7 1700 Eight-Core Processor
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 7 1700 Eight-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3000                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            16                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    32880940(0x1f5b92c) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    32880940(0x1f5b92c) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
    N/A                      
*******                  
Agent 2                  
*******                  
  Name:                    gfx803                             
  Uuid:                    GPU-XX                             
  Marketing Name:          Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26591(0x67df)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1411                               
  BDFID:                   2048                               
  Internal Node ID:        1                                  
  Compute Unit:            36                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    4194304(0x400000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx803          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***             
```
</details>

Did the binaries never get built for `amdgcn-amd-amdhsa--gfx803`? Any clues as to how to build these "binaries" from source?

**Comment by interfect** [comment]
I'm going to give building from source on my machine a shot on the theory that it will maybe then build for my GPU.

Is there a good reason why the [build instructions](https://github.com/pytorch/pytorch#install-pytorch) seem to assume I am using Conda? All the dependencies it asks me to install are in Pip.

Anyway, the build fails like this:
```
-- Found HIP: /opt/rocm-4.1.0/hip (found suitable version "4.1.21072-c3eb5ccc", minimum required is "1.0") 
HIP VERSION: 4.1.21072-c3eb5ccc

***** ROCm version from /opt/rocm/.info/version-dev ****

ROCM_VERSION_DEV: 4.1.0
ROCM_VERSION_DEV_MAJOR: 4
ROCM_VERSION_DEV_MINOR: 1
ROCM_VERSION_DEV_PATCH: 0

***** Library versions from dpkg *****

rocm-dev VERSION: 4.1.0.40100-26
rocm-device-libs VERSION: 1.0.0.40100-26
hsakmt-roct VERSION: 20210118.1.551.40100-26
hsakmt-roct-dev VERSION: 20210118.1.551.40100-26
hsa-rocr-dev VERSION: 1.2.0.40100-26

***** Library versions from cmake find_package *****

-- ROCclr at /opt/rocm/lib/cmake/rocclr
hip VERSION: 4.1.21072
hsa-runtime64 VERSION: 1.2.40100
amd_comgr VERSION: 2.0.0
CMake Error at cmake/public/LoadHIP.cmake:138 (find_package):
  By not providing "Findrocrand.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "rocrand", but
  CMake did not find one.

  Could not find a package configuration file provided by "rocrand" with any
  of the following names:

    rocrandConfig.cmake
    rocrand-config.cmake

  Add the installation prefix of "rocrand" to CMAKE_PREFIX_PATH or set
  "rocrand_DIR" to a directory containing one of the above files.  If
  "rocrand" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  cmake/public/LoadHIP.cmake:197 (find_package_and_print_version)
  cmake/Dependencies.cmake:1189 (include)
  CMakeLists.txt:615 (include)


-- Configuring incomplete, errors occurred!
```

Are there more build dependencies not yet listed in the README? Like say [these](https://github.com/pytorch/pytorch/blob/8c798e062216278673a75bac0848ea69a8bd3f03/docker/caffe2/jenkins/common/install_rocm.sh#L20-L32)?

**Comment by interfect** [comment]
After I install those packages it complains of a missing `hipfft`.

I had missed that I need to run `python tools/amd_build/build_amd.py`, but running that hasn't helped.

Luckily `hipfft` is in `apt` as well with the ROCm repos, and once I install *that* the build starts.

**Comment by interfect** [comment]
OK, building on my machine didn't seem to solve the problem, but now I see I was mistaken when I thought the lazy initialization was broken; it doesn't actually throw until I call `is_available`. Granted, it should return false and not throw, but this at least is something an app could potentially catch:

```
$ python3 -i
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch.cuda
>>> torch.cuda.is_available()
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
Aborted
```

I will keep investigating to try and find where it decides what GPUs to build for.

**Comment by interfect** [comment]
Looks like this is meant to be controlled [via CMake's `GPU_TARGETS` variable](https://rocmdocs.amd.com/en/latest/Installation_Guide/Using-CMake-with-AMD-ROCm.html#using-hip-in-cmake).

I found this in `build/CMakeCache.txt`:

```
//AMD GPU targets to compile for
AMDGPU_TARGETS:STRING=gfx900;gfx906;gfx908
...
//GPU targets to compile for
GPU_TARGETS:STRING=gfx900;gfx906;gfx908
```

That clearly is missing `gfx803`. The docs say `GPU_TARGETS` is supposed to default to the "currently supported" ROCm GPUs. But I can't find anything in the changelogs about `gfx803` support having been dropped from ROCm; there's a point [here that it doesn't support "the XNACK target feature"](https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html#new-code-object-format-version-for-targetid), whatever that is, but that implies that in general it's still on the supported list.

It looks like the pytorch build system recognizes a `PYTORCH_ROCM_ARCH` environment variable, with a default of `gfx803;gfx900;gfx906;gfx908` in a couple places; I am not sure where the list `gfx900;gfx906;gfx908` is coming from, or how to get at CMake's `GPU_TARGETS` from where I am, running `setup.py`.

I think `AMDGPU_TARGETS` might be coming from `rocrand`, which [didn't build for `gfx803` until 2 days ago](https://github.com/ROCmSoftwarePlatform/rocRAND/commit/467824da5d312315dc97bf3590a1dd95ca0c6c55), and doesn't in any release, so I suspect the `rocrand` from the package manager (2.10.7) is too old and might itself be missing appropriate binaries. 

I will try building with `PYTORCH_ROCM_ARCH=gfx803` explicitly, with some hacks in `LoadHIP.cmake` to push that out to the other variables, and `rocrand` 467824da5d312315dc97bf3590a1dd95ca0c6c55 installed from source in `~/.local`.

**Comment by interfect** [comment]
OK, so I made this patch to `cmake/public/LoadHIP.cmake`:

```
diff --git a/cmake/public/LoadHIP.cmake b/cmake/public/LoadHIP.cmake
index 09ae6385cf..57ca5a6e72 100644
--- a/cmake/public/LoadHIP.cmake
+++ b/cmake/public/LoadHIP.cmake
@@ -127,6 +127,9 @@ if(NOT DEFINED ENV{PYTORCH_ROCM_ARCH})
 else()
   set(PYTORCH_ROCM_ARCH $ENV{PYTORCH_ROCM_ARCH})
 endif()
+# Copy to AMD's arch variables
+set(GPU_TARGETS ${PYTORCH_ROCM_ARCH} CACHE STRING "GPU targets to compile for")
+set(AMDGPU_TARGETS ${PYTORCH_ROCM_ARCH} CACHE STRING "AMD GPU targets to compile for")
 
 # Add HIP to the CMAKE Module Path
 set(CMAKE_MODULE_PATH ${HIP_PATH}/cmake ${CMAKE_MODULE_PATH})
```

Then I installed `rocrand` 2.10.9 (not yet released; I grabbed 467824da5d312315dc97bf3590a1dd95ca0c6c55 and more or less did the post-build install by hand).

Then I could do:

```
PYTORCH_ROCM_ARCH="gfx803" python setup.py install
```

And then I got a PyTorch that will return `true` from `torch.cuda.is_available()` on my RX480.

So that's *a* workaround. I'm not actually sure whether all those steps are actually necessary.

**Comment by interfect** [comment]
On top of this, the `torchvision` build complained it couldn't find `hip/hip_runtime.h`. I'm not sure if that's related to how I installed PyTorch. To fix it, I had to do this:

```
CXX=hipcc pip install 'git+https://github.com/pytorch/vision.git@v0.9.0'
```

**Comment by styler00dollar** [comment]
Took me 4 attempts and a day of compiling due to [a bad pr](https://github.com/pytorch/pytorch/pull/55163), but I managed to do it. Here an arch guide:
```
yay -S rocm-dev rocm-utils rocm-libs
yay -S ncurses5-compat-libs
yay -S rccl cmake
pip install typing_extentions

# WARNING: There is a recent pr that results in a bad compile. It took me some time to figure it out.
# https://github.com/pytorch/pytorch/pull/55163
# It is already reverted, but for now, make sure you don't clone a bad master.
git clone https://github.com/pytorch/pytorch
cd pytorch

git submodule init
git submodule update --init --recursive
python3 tools/amd_build/build_amd.py

# Edit cmake/public/LoadHIP.cmake, add that before the line "# Add HIP to the CMAKE Module Path" 
set(GPU_TARGETS ${PYTORCH_ROCM_ARCH} CACHE STRING "GPU targets to compile for")
set(AMDGPU_TARGETS ${PYTORCH_ROCM_ARCH} CACHE STRING "AMD GPU targets to compile for")

sudo su # To avoid permission issues and a failed install. I used after the compile failed and it worked.
PYTORCH_ROCM_ARCH="gfx803" python setup.py develop

CXX=hipcc pip install 'git+https://github.com/pytorch/vision.git@v0.9.0'
```

**Comment by Column01** [comment]
Can we please have an update on this issue? I've been spending hours installing dependencies that aren't listed to try and get pytorch to build and have been unsuccessful. Why can't pytorch just apply the fix mentioned above to the build to release gfx803 compatible ROCm builds?

AMD builds for gfx803, so it's not a matter of if they're going to drop support for them. Just have the same policy, if there is an issue post fixing of this one (aka just building for them like you already tried to do but missed one crucial part), then pytorch won't support it as it's not an actively supported card?

It's so ridiculous the number of hoops you have to jump through just to get ROCm working with pytorch on gfx803 when it's as easy as adding two lines to a build file for the CLI to build with support for them... everything else (slowness due to the above issue) can just be a worry for the user as its not a PyTorch limitation.

**Comment by Column01** [comment]
Side note:
The docs for building should be updated to include these ghost dependencies for ROCm... even without being on gfx803, pytorch's ROCm wheel will not build due to a lack of these dependencies.

**Comment by jithunnair-amd** [comment]
cc @ROCmSupport to comment on gfx803 support in ROCm stack.

**Comment by ROCmSupport** [comment]
Hi @styler00dollar 
We are not supporting gfx8 devices anymore.
Request you to check for the supported hardware @ [https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support](url)
So we can not work on this for now. Thanks for understanding.
This ticket can be closed.

**Comment by styler00dollar** [comment]
Closing since the official support is dropped.

**Comment by Column01** [comment]
> Hi @styler00dollar We are not supporting gfx8 devices anymore. Request you to check for the supported hardware @ [https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support](url) So we can not work on this for now. Thanks for understanding. This ticket can be closed.

If you look at the link that you sent it clearly states: 
> The following list of GPUs are enabled in the ROCm software, though full support is not guaranteed:
> GFX8 GPUs
> "Polaris 11" chips, such as on the AMD Radeon RX 570 and Radeon Pro WX 4100
> "Polaris 12" chips, such as on the AMD Radeon RX 550 and Radeon RX 540
> GFX7 GPUs
> "Hawaii" chips, such as the AMD Radeon R9 390X and FirePro W9100

I believe there is a misunderstanding on what you support. My card is still enabled (your words), and there is a big difference between not having full support (meaning not having certain aspects of ROCm working) and it being completely unusable on my graphics card. I have yet to find a single piece of software using ROCm that works on my card. If it not being supported is the case, why even build for it in the first place, @ROCmSupport?

Below is the sentence I think is being misunderstood despite being plain English:
> We do not support GFX8-class GPUs (Fiji, Polaris, etc.) on CPUs that do not have PCIe 3.0 with PCIe atomics.

This clearly states "We do not support" the cards, but the condition is "**on CPUs that do not have PCIe 3.0**" and I think this is the confusing part when you say you don't support them. Somewhere, someone misinterpretted this in ROCm's support team to mean that GFX8 was whole heartedly not supported anymore

I wouldn't have even made this comment on the issue if I hadn't exhausted every other avenue to try and get it working without assistance. I have literally spent approximately 24-48 hours over the span of multiple months debugging issues and trying to get pytorch to build. I finally turned to docker images where I could get pytorch to builds or get ones with it preinstalled and **every. single. one.** I tried either:
1. Hard crashed due the issue mentioned here regarding hip not locating a binary for my GPU (which the more I investigate seems to just be a bug and not actually a "your card is not supported." issue. See https://github.com/ROCm-Developer-Tools/HIP/issues/2166 as to why I think that) **OR**
2. Just didn't have support with `torch.cuda.is_available()` returning false

So what is it AMD? Is my card "not fully supported" or just not supported at all? If it's the latter, explain why you still build for it. If it's the former, explain what "not fully supported" **really** means.
