### ISSUE TITLE
torch-1.8.0 and nightly linux wheels are missing many cuda capabilities

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#53838]
```
pip install torch
Collecting torch
  Using cached torch-1.8.0-cp38-cp38-manylinux1_x86_64.whl (735.5 MB)
```
when run emits:
```
/home/stas/anaconda3/envs/test/lib/python3.8/site-packages/torch/cuda/__init__.py:104: UserWarning: 
GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
```
So it appears to be missing a whole bunch of capabilities. 

And so does nightly:
```
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html -U
```

Thank you.

cc @ezyang @seemethere @malfet @walterddr @ngimel

**Comment by stas00** [comment]
This is so strange. We can't run the main release pytorch and nobody is even trying to fix this? 

```
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

why won't it support an RTX-3090 card?

Am I missing something? 

Thank you!

```
Collecting environment information...
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1070 Ti
GPU 1: GeForce RTX 3090

Nvidia driver version: 455.45.01
```

**Comment by stas00** [comment]
Update, it doesn't look there is a way to have a nightly installed and not get another package kick it out.

I even tried adding: `-f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html  --pre` to the installs of other packages, but it ignores it and installs whatever random torch it finds on pypi.

If I don't have torch installed and I do:
```
git clone https://github.com/huggingface/transformers
cd transformers
pip install -e .[dev] -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html  --pre
```
it downloads the nightly, and then discards it (!!!) and installs `torch-1.8.1`, observe:

```
Collecting torch>=1.0
  Downloading https://download.pytorch.org/whl/nightly/cu111/torch-1.9.0.dev20210408%2Bcu111-cp38-cp38-linux_x86_64.whl (2025.1 MB)
     |████████████████████████████████| 2025.1 MB 4.5 kB/s 
[...]
Collecting torch>=1.0
  Using cached torch-1.8.1-cp38-cp38-manylinux1_x86_64.whl (804.1 MB)
Successfully installed torch-1.8.1
```

**Comment by stas00** [comment]
ok, traced it to `torchaudio` that was forcing a fixed pytorch version.

**Comment by malfet** [comment]
@stas00 can you elaborate a bit more? Are you saying that upgrading from release to nightly using instruction from  https://pytorch.org/get-started/locally/  does not work? Or that `pip install torch -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html` does not work if other dependencies has be pinned by `pip install package==version`?

**Comment by stas00** [comment]
I will post an update as soon as I find at least one version that actually works. 


So far everything I tried doesn't work in one way or another.

### installing conda pt-1.8 downgrades my python to 3.7 w/o asking me

```
$ python --version
Python 3.8.8

$ conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.10.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/stas/anaconda3/envs/py38-pt18

  added / updated specs:
    - cudatoolkit=11.1
    - pytorch
    - torchaudio
    - torchvision


The following NEW packages will be INSTALLED:

  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_llvm
  blas               pkgs/main/linux-64::blas-1.0-mkl
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  cudatoolkit        conda-forge/linux-64::cudatoolkit-11.1.1-h6406543_8
  ffmpeg             pytorch/linux-64::ffmpeg-4.3-hf484d3e_0
  freetype           conda-forge/linux-64::freetype-2.10.4-h0708190_1
  gmp                conda-forge/linux-64::gmp-6.2.1-h58526e2_0
  gnutls             conda-forge/linux-64::gnutls-3.6.13-h85f3911_1
  jpeg               pkgs/main/linux-64::jpeg-9b-h024ee3a_2
  lame               conda-forge/linux-64::lame-3.100-h7f98852_1001
  lcms2              pkgs/main/linux-64::lcms2-2.12-h3be6417_0
  libiconv           conda-forge/linux-64::libiconv-1.16-h516909a_0
  libpng             conda-forge/linux-64::libpng-1.6.37-h21135ba_2
  libtiff            pkgs/main/linux-64::libtiff-4.1.0-h2733197_1
  libuv              conda-forge/linux-64::libuv-1.41.0-h7f98852_0
  llvm-openmp        conda-forge/linux-64::llvm-openmp-11.1.0-h4bd325d_1
  lz4-c              conda-forge/linux-64::lz4-c-1.9.3-h9c3ff4c_0
  mkl                conda-forge/linux-64::mkl-2020.4-h726a3e6_304
  mkl-service        conda-forge/linux-64::mkl-service-2.3.0-py38h1e0a361_2
  mkl_fft            conda-forge/linux-64::mkl_fft-1.3.0-py38h5c078b8_1
  mkl_random         conda-forge/linux-64::mkl_random-1.2.0-py38hc5bc63f_1
  nettle             conda-forge/linux-64::nettle-3.6-he412f7d_0
  ninja              conda-forge/linux-64::ninja-1.10.2-h4bd325d_0
  numpy              pkgs/main/linux-64::numpy-1.19.2-py38h54aff64_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.19.2-py38hfa32c7d_0
  olefile            conda-forge/noarch::olefile-0.46-pyh9f0ad1d_1
  openh264           conda-forge/linux-64::openh264-2.1.1-h780b84a_0
  pillow             pkgs/main/linux-64::pillow-8.2.0-py38he98fc37_0
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  pytorch            pytorch/linux-64::pytorch-1.8.1-py3.8_cuda11.1_cudnn8.0.5_0
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  torchaudio         pytorch/linux-64::torchaudio-0.8.1-py38
  torchvision        pytorch/linux-64::torchvision-0.9.1-py38_cu111
  typing_extensions  conda-forge/noarch::typing_extensions-3.7.4.3-py_0
  zstd               conda-forge/linux-64::zstd-1.4.9-ha95c52a_0

The following packages will be UPDATED:

  certifi            pkgs/main::certifi-2020.12.5-py38h06a~ --> conda-forge::certifi-2020.12.5-py38h578d9bd_1
  libgcc-ng           pkgs/main::libgcc-ng-9.1.0-hdf63c60_0 --> conda-forge::libgcc-ng-9.3.0-h2828fa1_18
  libstdcxx-ng       pkgs/main::libstdcxx-ng-9.1.0-hdf63c6~ --> conda-forge::libstdcxx-ng-9.3.0-h6de172a_18

The following packages will be SUPERSEDED by a higher-priority channel:

  _libgcc_mutex           pkgs/main::_libgcc_mutex-0.1-main --> conda-forge::_libgcc_mutex-0.1-conda_forge
  ca-certificates    pkgs/main::ca-certificates-2021.1.19-~ --> conda-forge::ca-certificates-2020.12.5-ha878542_0
  openssl              pkgs/main::openssl-1.1.1k-h27cfd23_0 --> conda-forge::openssl-1.1.1k-h7f98852_0


Proceed ([y]/n)?

Preparing transaction: done
Verifying transaction: done
Executing transaction: / By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done

$ python --version
Python 3.7.4
```
and then things don't work with the weird:

```
Traceback (most recent call last):
  File "examples/language-modeling/run_clm.py", line 453, in <module>
    main()
  File "examples/language-modeling/run_clm.py", line 336, in main
    load_from_cache_file=not data_args.overwrite_cache,
  File "/home/stas/anaconda3/lib/python3.7/site-packages/datasets/dataset_dict.py", line 303, in map
    for k, dataset in self.items()
  File "/home/stas/anaconda3/lib/python3.7/site-packages/datasets/dataset_dict.py", line 303, in <dictcomp>
    for k, dataset in self.items()
  File "/home/stas/anaconda3/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 1259, in map
    update_data=update_data,
  File "/home/stas/anaconda3/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 157, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/stas/anaconda3/lib/python3.7/site-packages/datasets/fingerprint.py", line 158, in wrapper
    self._fingerprint, transform, kwargs_for_fingerprint
  File "/home/stas/anaconda3/lib/python3.7/site-packages/datasets/fingerprint.py", line 105, in update_fingerprint
    hasher.update(transform_args[key])
  File "/home/stas/anaconda3/lib/python3.7/site-packages/datasets/fingerprint.py", line 57, in update
    self.m.update(self.hash(value).encode("utf-8"))
  File "/home/stas/anaconda3/lib/python3.7/site-packages/datasets/fingerprint.py", line 53, in hash
    return cls.hash_default(value)
  File "/home/stas/anaconda3/lib/python3.7/site-packages/datasets/fingerprint.py", line 46, in hash_default
    return cls.hash_bytes(dumps(value))
  File "/home/stas/anaconda3/lib/python3.7/site-packages/datasets/utils/py_utils.py", line 389, in dumps
    dump(obj, file)
  File "/home/stas/anaconda3/lib/python3.7/site-packages/datasets/utils/py_utils.py", line 361, in dump
    Pickler(file, recurse=True).dump(obj)
  File "/home/stas/anaconda3/lib/python3.7/site-packages/dill/_dill.py", line 454, in dump
    StockPickler.dump(self, obj)
  File "/home/stas/anaconda3/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/home/stas/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/stas/anaconda3/lib/python3.7/site-packages/datasets/utils/py_utils.py", line 556, in save_function
    obj=obj,
  File "/home/stas/anaconda3/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/home/stas/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/stas/anaconda3/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
  File "/home/stas/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/stas/anaconda3/lib/python3.7/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/home/stas/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/home/stas/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/home/stas/anaconda3/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle _LazyModule objects
```

### nightly doesn't work

If I install pt-nightly I get the:

```
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
```

which has been report awhile ago.

I will post an update once I find at least one version that works.

I had a manually built a month ago nightly build that worked and I made the mistake to try to switch to the official version.

**Comment by ngimel** [comment]
For the error that you are getting on nightly, do you have smaller repro?

**Comment by stas00** [comment]
Sorry, I don't have a a small repro at the moment - it happens when running transformers under deepspeed under 2 different gpus.

So the problem:

1. happens with 1.8.0, 1.8.1 and nightly
2. happens only when I try to use 2 different gpus at the same time - sm_61 and sm_86 - if I test them separately all works just fine.
3. same code works just fine on other identical software setups but where gpus are the same - so I suspect it may have to do with the different gpus.

This is the last nightly that works:
 https://download.pytorch.org/whl/nightly/cu110/torch-1.8.0.dev20210208%2Bcu110-cp38-cp38-linux_x86_64.whl
and then when cu111 nightly tree is started it drops support for xm_61 till 03-05, and when it's re-added it already breaks.

I also built my own build around march 03 (just before 1.8.0 release) and it works too.

Going to build a manual one and see if it makes a difference.

I will update this when I have more information to share.

**Comment by stas00** [comment]
update: I managed to build pytorch manually on my machine and with this I don't get `CUBLAS_STATUS_EXECUTION_FAILED` - but it happens with any official 1.8.0, 1.8.1, nightly builds. So this indicates that this has something to do with the build.

I did my build using @ptrblck's awesome docker:

```
docker run --gpus all --ipc=host --rm -it -v ~/github/00pytorch/pytorch/docker:/tmp/output nvcr.io/nvidia/pytorch:20.12-py3

# once docker is running:
conda create -n pytorch-dev python=3.8 -y
bash
conda init bash
conda activate pytorch-dev
conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses -y
conda install -c pytorch magma-cuda111 -y

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
# if you are updating an existing checkout
git submodule sync
git submodule update --init --recursive
git pull

# to build a wheel
unset PYTORCH_BUILD_VERSION
unset PYTORCH_VERSION
TORCH_CUDA_ARCH_LIST="6.1 8.6" \
CUDA_HOME="/usr/local/cuda" \
CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
USE_SYSTEM_NCCL=1 \
NCCL_INCLUDE_DIR="/usr/include/" \
NCCL_LIB_DIR="/usr/lib/" \
python setup.py bdist_wheel 2>&1 | tee build.log
pip install dist/*whl
```

**Comment by malfet** [comment]
@stas00 i feel like this issue is used to track several independent problems at once:
 - Supported CUDA architecture regression between 1.7.1 and 1.8.0
   -  This was the reason why this issue was filed originally and it was fixed in 1.8.1
 - pip upgrade problems 
    - Can you please clarify whether it was a setup issue or  instructions for upgrading from 1.7 to 1.8 on pytorch.org are not correct
 - PyTorch-1.8.1 official build problem for trainings that uses both sm_61 and sm_86 GPUs 
    - This problem manifests in " CUDA error: CUBLAS_STATUS_EXECUTION_FAILED", rather than in "no kernel image is available for execution on the device"
 Do you mind filing a separate issue for the later and close this one if single GPU architecture workflows for above-mentioned architectures work out of the box using PyTorch-1.8.1 with CUDA-11.1 works ?

**Comment by stas00** [comment]
You're absolutely correct, @malfet. I derailed this Issue. My apologies.

> Can you please clarify whether it was a setup issue or instructions for upgrading from 1.7 to 1.8 on pytorch.org are not correct

The problem with pip downgrading pytorch was due to having `torchaudio` installed. That package has a fixed specific pytorch version. So in certain situations one can't update pytorch via pip without first uninstalling `torchaudio`, as it will bring back its fixed pytorch version. So basically one has to update or uninstall `torch`+`torchaudio`+`torchvision` as a group. Uninstalling just `torch` and then installing a different version is very likely going to cause pip to downgrade pytorch next time it installs anything that requires `torchaudio`.
