### ISSUE TITLE
Linear algebra GPU library function bug tracking issue [magma/cusolver/cublas]

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#53879]
## Linear algebra GPU library function bug tracking issue [magma/cusolver/cublas]

This issue is used to track known bugs in GPU library functions, e.g. MAGMA, cuSOLVER, cuBLAS. These known issues include **crash**, **large numerical mismatches**, **nan outputs**, etc.

| torch function | library function | affected library versions | workaround in pytorch? | related PR | what issue? |
| --- | --- | --- | --- | --- | --- |
| `torch.cholesky` | `cusolverDnXpotrfBatched` | current  | not used | #53104  | Function creates `nan` output for large ill-conditioned matrix, while single matrix version `cusolverDnXpotrf` gives correct results. | 
|   |  `magma_Xpotrf_batched` | ? | patched | #50957 | Function causes cuda illegal memory access for large inputs. |
| `torch.eigh` `torch.eigvalsh` | `cusolverDnXsyevjBatched` | current | not used | #53040 | Function creates wrong outputs sometimes. |

### See also

- Linear Algebra tracking issue #42666
- Linear algebra GPU backend tracking issue [magma/cusolver/cublas] #47953

**Comment by v0dro** [comment]
I noticed while working on #56887 that cuSOLVER 64-bit GETRF does not return the correct pivot array when given a small singular matrix such as `((1,1,1), (1,1,1), (1,1,1))`. This is specific to the 64 bit API. The present 32 bit API works fine.

Also, the 32 bit cuSOLVER GETRF returns `nan` for singular matrix factorization, whereas scipy and magma return `0` for the same factorization. We are now converting to `0` using `at::nan_to_num`.

**Comment by v0dro** [comment]
@xwang233 I benchmarked cuSOLVER vs. MAGMA vs. cuBLAS LU factorization for variety of problem sizes and it turns out that cuBLAS is the fastest for a very small subset of all the problem sizes. Here's my conclusions in text:
```
+ Single LU: always use cuSolver whenever available.
+ Batch size 2-8, sizes 2-512: always use cuSolver when available.
+ Batch size 2-8, sizes 1024: always use magma when available.
+ Batch size 16-64, sizes 2-64: always use cuBLAS
+ Batch size 16-64, sizes 128-1024: always use magma
```

Here's a plot of the data:
[conclusions.pdf](https://github.com/pytorch/pytorch/files/6409634/conclusions.pdf)

As a result of the above data, I think we skip implementing a cuBLAS path for the LU since cuSOLVER and MAGMA are faster for a much wider variety of use cases.
