### ISSUE TITLE
pytorch 1.8.0 installation -> CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by pfeatherstone** [pytorch/pytorch#53896]
## 🐛 Bug

pytorch 1.8.0 with cuda 10.2 and cudnn 7.6.5 does not work.

## To Reproduce

Run the following:
```
    x = torch.randn(1,3,256,256).cuda()
    n = torch.nn.Conv2d(3,3,3,1,1).cuda()
    y = n(x)
    print(x,y)
```

You get 
```
y = n(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```
## Expected behavior

I expect this to work.

## Environment

```
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.16.6

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2070 SUPER
GPU 1: GeForce RTX 2070 SUPER

Nvidia driver version: 440.33.01
cuDNN version: /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] msgpack-numpy==0.4.7.1
[pip3] numpy==1.19.4
[pip3] pytorch-metric-learning==0.9.85
[pip3] pytorch-ranger==0.1.1
[pip3] segmentation-models-pytorch==0.1.3
[pip3] torch==1.8.0
[pip3] torch-dct==0.1.5
[pip3] torch-lr-finder==0.2.0
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.8.0
[pip3] torchvision==0.9.0
[conda] Could not collect

```

**Comment by pfeatherstone** [comment]
I've updated cudnn. Now my environment is :
```
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.16.6

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2070 SUPER
GPU 1: GeForce RTX 2070 SUPER

Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] msgpack-numpy==0.4.7.1
[pip3] numpy==1.19.4
[pip3] pytorch-metric-learning==0.9.85
[pip3] pytorch-ranger==0.1.1
[pip3] segmentation-models-pytorch==0.1.3
[pip3] torch==1.8.0
[pip3] torch-dct==0.1.5
[pip3] torch-lr-finder==0.2.0
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.8.0
[pip3] torchvision==0.9.0
[conda] Could not collect

```

I still get the same error

**Comment by pfeatherstone** [comment]
And i entered ```sudo ldconfig```
So all the new shared libraries should be recognized.

**Comment by pfeatherstone** [comment]
Apparently, installing pytorch via pip, which is what i did, comes with pre-packaged CUDA and CUDNN. So updating my system's installation of either CUDA or CUDNN does nothing. Is torch version 1.8.0 built with CUDA 11?

**Comment by pfeatherstone** [comment]
If i revert back to torch==1.7.1, everything works again. However, torch 1.8.0 has some nice updates to the ONNX exporter, which is mostly what i care about. So would be great to get 1.8.0 working. And i don't want to have to develop in a docker container. A simple pip installation would be ideal.

**Comment by pfeatherstone** [comment]
I also installed CUDA 11.2 in order to get the most up to date nvidia drivers, i.e. 460. That also doesn't fix it. I know pytorch comes with it's own packaged CUDA, but since ```RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED``` typically indicates a bad driver installation, i thought it would be quicker and safer to simply install bundled cuda11.2 + nvidia driver 460

**Comment by pfeatherstone** [comment]
nvidia-smi works fine and correctly shows driver version 460.32.03 installed and cuda version 11.2 installed.

**Comment by pfeatherstone** [comment]
Right installed nightly build of pytorch and it works. I look forward to release 1.8.1 when this is all properly fixed and stable.

**Comment by ngimel** [comment]
This is a duplicate of #53336
