### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device on libtorch 1.8.0 with GPU NVIDIA GTX 1080Ti (compute capability 6.1)

### ISSUE THREAD

**Issue by lamhoangtung** [pytorch/pytorch#54053]
## 🐛 Bug

Hi, I'm trying to build a simple application with libtorch 1.8.0 to inference a simple TorchScript model on C++ but got the error `CUDA error: no kernel image is available for execution on the device` on my NVIDIA GTX 1080Ti (compute capability 6.1).

## To Reproduce

I had build a simple project to reproduce the error: https://github.com/lamhoangtung/dummy-libtorch/tree/no_execution_kernel_bug

To use it, setup everything on a machine that had a GPU with compute capability 6.1 like the GTX 1080Ti. Please install CUDA 11.1 or virtualize CUDA 11.1 inside the docker image `nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04` :
```bash
# Setup related dependencies
sudo apt update
sudo apt install unzip cmake git python3 python3-dev python3-pip wget

# Clone the repo and checkout related branch
git clone https://github.com/lamhoangtung/dummy-libtorch
cd dummy-libtorch
git checkout no_execution_kernel_bug

# Download libtorch and build the program
sh download_libtorch.sh
sh build.sh
```

You should see something like this:
```console
root@e43fcbbb4f19:/dummy-libtorch# ./build.sh
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found version "11.1")
-- Caffe2: CUDA detected: 11.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 11.1
-- Found CUDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so
-- Found cuDNN: v8.0.5  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
CMake Warning at libtorch/share/cmake/Caffe2/public/cuda.cmake:198 (message):
  Failed to compute shorthash for libnvrtc.so
Call Stack (most recent call first):
  libtorch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  libtorch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:5 (find_package)


-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Found Torch: /dummy-libtorch/libtorch/lib/libtorch.so
-- Configuring done
-- Generating done
-- Build files have been written to: /dummy-libtorch/build
Scanning dependencies of target simple_model
[ 50%] Building CXX object CMakeFiles/simple_model.dir/model.cpp.o
[100%] Linking CXX executable simple_model
[100%] Built target simple_model
```

The output indicate that `cmake` had detected a GPU with CUDA architecture(s):  6.1. And the binary `simple_model` can be use now.

Since I had created a dummy model in `python/dummy_model.py` and export a scripted model at `python/test.pt`. So, to run the program, just run:
```bash
./build/simple_model python/test.pt
```
And you should see an output like this:
```console
root@e43fcbbb4f19:/dummy-libtorch# ./build/simple_model python/test.pt
Loading model python/test.pt
Loaded model python/test.pt
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: no kernel image is available for execution on the device
Exception raised from distribution_nullary_kernel at /pytorch/aten/src/ATen/native/cuda/DistributionTemplates.h:158 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f5e8b9c02f2 in /dummy-libtorch/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f5e8b9bd67b in /dummy-libtorch/libtorch/lib/libc10.so)
frame #2: void at::native::(anonymous namespace)::distribution_nullary_kernel<float, float, 4, at::CUDAGeneratorImpl*, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, at::CUDAGeneratorImpl*, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::Tensor&, double, double, at::CUDAGeneratorImpl*), &(void at::native::templates::cuda::normal_kernel<at::CUDAGeneratorImpl*>(at::Tensor&, double, double, at::CUDAGeneratorImpl*)), 2u>, float, float>), &(void at::native::templates::cuda::normal_and_transform<float, float, 4ul, at::CUDAGeneratorImpl*, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::Tensor&, double, double, at::CUDAGeneratorImpl*), &(void at::native::templates::cuda::normal_kernel<at::CUDAGeneratorImpl*>(at::Tensor&, double, double, at::CUDAGeneratorImpl*)), 2u>, float, float> >(at::TensorIterator&, at::CUDAGeneratorImpl*, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::Tensor&, double, double, at::CUDAGeneratorImpl*), &(void at::native::templates::cuda::normal_kernel<at::CUDAGeneratorImpl*>(at::Tensor&, double, double, at::CUDAGeneratorImpl*)), 2u>, float, float>)), 2u>>, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::Tensor&, double, double, at::CUDAGeneratorImpl*), &(void at::native::templates::cuda::normal_kernel<at::CUDAGeneratorImpl*>(at::Tensor&, double, double, at::CUDAGeneratorImpl*)), 2u>, float, float> >(at::TensorIterator&, at::CUDAGeneratorImpl*, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, at::CUDAGeneratorImpl*, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::Tensor&, double, double, at::CUDAGeneratorImpl*), &(void at::native::templates::cuda::normal_kernel<at::CUDAGeneratorImpl*>(at::Tensor&, double, double, at::CUDAGeneratorImpl*)), 2u>, float, float>), &(void at::native::templates::cuda::normal_and_transform<float, float, 4ul, at::CUDAGeneratorImpl*, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::Tensor&, double, double, at::CUDAGeneratorImpl*), &(void at::native::templates::cuda::normal_kernel<at::CUDAGeneratorImpl*>(at::Tensor&, double, double, at::CUDAGeneratorImpl*)), 2u>, float, float> >(at::TensorIterator&, at::CUDAGeneratorImpl*, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::Tensor&, double, double, at::CUDAGeneratorImpl*), &(void at::native::templates::cuda::normal_kernel<at::CUDAGeneratorImpl*>(at::Tensor&, double, double, at::CUDAGeneratorImpl*)), 2u>, float, float>)), 2u>> const&, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::Tensor&, double, double, at::CUDAGeneratorImpl*), &(void at::native::templates::cuda::normal_kernel<at::CUDAGeneratorImpl*>(at::Tensor&, double, double, at::CUDAGeneratorImpl*)), 2u>, float, float>) + 0x76f (0x7f5e3f91602f in /dummy-libtorch/libtorch/lib/libtorch_cuda_cu.so)
frame #3: void at::native::templates::cuda::normal_kernel<at::CUDAGeneratorImpl*>(at::Tensor&, double, double, at::CUDAGeneratorImpl*) + 0x2f7 (0x7f5e3f917417 in /dummy-libtorch/libtorch/lib/libtorch_cuda_cu.so)
frame #4: at::native::normal_kernel(at::Tensor&, double, double, c10::optional<at::Generator>) + 0x17c (0x7f5e3f91441c in /dummy-libtorch/libtorch/lib/libtorch_cuda_cu.so)
frame #5: <unknown function> + 0xf51bea (0x7f5e2ca5bbea in /dummy-libtorch/libtorch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0xf52089 (0x7f5e2ca5c089 in /dummy-libtorch/libtorch/lib/libtorch_cpu.so)
frame #7: at::native::normal_(at::Tensor&, double, double, c10::optional<at::Generator>) + 0x23 (0x7f5e2ca52093 in /dummy-libtorch/libtorch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0xb916c8 (0x7f5e3eb0b6c8 in /dummy-libtorch/libtorch/lib/libtorch_cuda_cu.so)
frame #9: <unknown function> + 0xb91785 (0x7f5e3eb0b785 in /dummy-libtorch/libtorch/lib/libtorch_cuda_cu.so)
frame #10: <unknown function> + 0x1910934 (0x7f5e2d41a934 in /dummy-libtorch/libtorch/lib/libtorch_cpu.so)
frame #11: at::Tensor::normal_(double, double, c10::optional<at::Generator>) const + 0x91 (0x7f5e2d3fa901 in /dummy-libtorch/libtorch/lib/libtorch_cpu.so)
frame #12: at::native::randn(c10::ArrayRef<long>, c10::optional<at::Generator>, c10::TensorOptions const&) + 0x50 (0x7f5e2cca7f90 in /dummy-libtorch/libtorch/lib/libtorch_cpu.so)
frame #13: at::native::randn(c10::ArrayRef<long>, c10::TensorOptions const&) + 0x20 (0x7f5e2cca8080 in /dummy-libtorch/libtorch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x17a9bf9 (0x7f5e2d2b3bf9 in /dummy-libtorch/libtorch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x17a9e7a (0x7f5e2d2b3e7a in /dummy-libtorch/libtorch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x167e899 (0x7f5e2d188899 in /dummy-libtorch/libtorch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x1632c8e (0x7f5e2d13cc8e in /dummy-libtorch/libtorch/lib/libtorch_cpu.so)
frame #18: at::randn(c10::ArrayRef<long>, c10::TensorOptions) + 0x13b (0x7f5e2d00f9db in /dummy-libtorch/libtorch/lib/libtorch_cpu.so)
frame #19: torch::randn(c10::ArrayRef<long>, c10::TensorOptions) + 0x92 (0x55e493670271 in ./build/simple_model)
frame #20: main + 0x1b0 (0x55e49366bb10 in ./build/simple_model)
frame #21: __libc_start_main + 0xf3 (0x7f5db866a0b3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #22: _start + 0x2e (0x55e49366b7fe in ./build/simple_model)

Aborted (core dumped)
```

NOTE: You can re-export the model by running `python3 python/dummy_model.py` if you want. Just make sure to install pytorch 1.8.0 with `pip3 install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html`

## Expected behavior

No such error as `CUDA error: no kernel image is available for execution on the device` appear. And an output like this can be achieved:
```console
Loading model python/test.pt
Loaded model python/test.pt
0: 2449ms
1: 360ms
2: 27ms
3: 21ms
...
999: 21ms
1000: 20ms
```

## Environment

```console
Collecting environment information...
PyTorch version: 1.8.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 460.56
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.0+cu111
[pip3] torchaudio==0.8.0
[pip3] torchvision==0.9.0+cu111
[conda] Could not collect
```

## Additional context

1. In the cmake config log, you can see this warning:
```console
CMake Warning at libtorch/share/cmake/Caffe2/public/cuda.cmake:198 (message):
  Failed to compute shorthash for libnvrtc.so
Call Stack (most recent call first):
  libtorch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  libtorch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:5 (find_package)
```
I had reported this issue separated at #53350. I'm not sure if that warning is related to this issue or not. 

2. The environment information collected in this bug report was inside a docker container of the image `nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04` as I said above. I ran it with `docker run -it --rm --gpus 1 nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04` to make sure `nvidia-docker` only pass in the GTX 1080Ti to build and test the example.

Outside at the host machine, I actually has this configuration:
```console
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.19.7

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce RTX 3090

Nvidia driver version: 460.56
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py38h1e0a361_2    conda-forge
[conda] mkl_fft                   1.3.0            py38h5c078b8_1    conda-forge
[conda] mkl_random                1.2.0            py38hc5bc63f_1    conda-forge
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.8.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu111    pytorch
```

Which mean I had 2 GPU: 1 GeForce GTX 1080 Ti and 1 GeForce RTX 3090. During the same build outside the host machine (OS Version, CUDA version, ...etc is pretty similar). I can see this:
```console
-- Autodetected CUDA architecture(s):  6.1 8.6
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_86,code=sm_86
```
which means that cmake can detect both GPU and should build a binary that can work for both. But only the RTX3090 (with compute capability 8.6) can run the model. The GTX 1080Ti (with CC 6.1) will not work

When I try to set `export CUDA_VISIBLE_DEVICES=0` and do a rebuild, cmake seems to detected only the GTX 1080Ti (sm_61), which was what I expected. But again, the binary cannot run on the 1080Ti with the error `CUDA error: no kernel image is available for execution` while the RTX 3090 (sm_86) can run it fine, even though it was not detected by cmake ?? That's why I also tried to isolate everything using Docker like above.

I also tried to infer the TorchScript model on Python and both GPU works fine. Also as far as I known, NVIDIA GPU with compute capability 6.1 like the GTX 1080Ti are well supported by PyTorch? But why my binary only works with sm_86 GPU (I don't have other GPU to do futher test) ?

So what am I missing here ? Maybe there are something I'm doing wrong or is this a bug with libtorch 1.8.0. I haven't seen this problem before on libtorch 1.6 and 1.7.1. I'm also trying to reproduce this same error on libtorch 1.7.1 and will report the result back soon. In the meantime, thanks for checking by ;)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @malfet @seemethere @walterddr @ngimel

**Comment by lamhoangtung** [comment]
I can confirm that the this problem does not exist on libtorch 1.7.1. I just tested it using `nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04` and `libtorch-shared-with-deps-1.7.1+cu110.zip`

**Comment by meganset** [comment]
Thanks for reporting this.

I noticed something similar with libtorch 1.8.0 and CUDA 11.1
#53476

**Comment by skyline75489** [comment]
Hi @meganset thanks for the feedback, as always. I noticed that #53164 indicates similar issue, but it's specifically for nightly build. I wonder if it also causes the failure you mentioned.

**Comment by lamhoangtung** [comment]
Thanks @meganset. Your issue is very similar to mine. I also tested another RTX 2060 with sm_75 with libtorch 1.8.0 and can confirm it still works with CUDA 11.1

**Comment by seemethere** [comment]
Hello! Can you check if this is still an issue with `v1.8.1`?

**Comment by lamhoangtung** [comment]
@seemethere I can confirm this problem still happen with libtorch 1.8.1

**Comment by lamhoangtung** [comment]
@seemethere @malfet. My bad, I just did the test again and looks like the problem was fixed in libtorch 1.8.1, my testing setup was probably cached at some part. Thanks for the help guys.
