### ISSUE TITLE
DistributedDataParallel: `DDP(model)` hangs on non-master node

### ISSUE THREAD

**Issue by JiaRu2016** [pytorch/pytorch#54232]
## Issue description

I'm using `DistributedDataParallel` to train model in data-parallel distributed mode, here is a simplified, runnable code:

this is my training script:
```python
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.nn as nn
import torch.optim as optim
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import Dataset, IterableDataset, DataLoader
from torch.utils.data.distributed import DistributedSampler
import os
import time


class ToyModel(nn.Module):
    def __init__(self, m):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(m, m, bias=False)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(m, 1, bias=False)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))


def print_dist_info():
    host_name = os.uname()[1]
    pid = os.getpid()
    LOCAL_RANK = os.environ['LOCAL_RANK']
    RANK = os.environ['RANK']
    WORLD_SIZE = os.environ['WORLD_SIZE']
    log_string = f"""
    ===================== {RANK} / {WORLD_SIZE}, {host_name}: {LOCAL_RANK} =====================
    pid = {pid}
    RANK = {RANK}
    WORLD_SIZE = {WORLD_SIZE}
    LOCAL_RANK = {LOCAL_RANK}
    MASTER_ADDR = {os.environ['MASTER_ADDR']}
    MASTER_PORT = {os.environ['MASTER_PORT']}
    """
    print(log_string)


def setup(global_rank, global_world_size, local_rank):
    dist.init_process_group("nccl", rank=global_rank, world_size=global_world_size)
    print(f'=========> dist.init_process_group() done. global_rank={global_rank}, local_rank={local_rank}')


def cleanup(global_rank, global_world_size, local_rank):
    dist.destroy_process_group()
    print(f'=========> dist.destroy_process_group(). global_rank={global_rank}, local_rank={local_rank}')


def main():
    print_dist_info()

    RANK, WORLD_SIZE, LOCAL_RANK = int(os.environ['RANK']), int(os.environ['WORLD_SIZE']), int(os.environ['LOCAL_RANK'])
    setup(RANK, WORLD_SIZE, LOCAL_RANK)
    
    # model
    model = ToyModel(5)

    print('constructing DDP(model) ...')
    gpu_id = LOCAL_RANK
    device = torch.device(gpu_id)
    model.to(device)
    ddp_model = DDP(model, device_ids=[gpu_id])  # <---------- Node1 stick here
    print('constructed DDP(model).')
    
    print('sync...')
    dist.barrier()
    print('sync done.')

    time.sleep(5)
    cleanup(RANK, WORLD_SIZE, LOCAL_RANK)

if __name__ == '__main__':
    main()

```

I use two node, use `torch.distributed.launch` to start processes on each node:

```
# on Node 0: (master)
python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=0 --master_addr="10.1.80.121" --master_port=1240 myscript.py

# on Node 1 (worker)
python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=1 --master_addr="10.1.80.121" --master_port=1240 myscript.py
```

On master node, it works well, console output:

```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

    ===================== 1 / 4, emu: 1 =====================
    pid = 14216
    RANK = 1
    WORLD_SIZE = 4
    LOCAL_RANK = 1
    MASTER_ADDR = 10.1.80.121
    MASTER_PORT = 1240


    ===================== 0 / 4, emu: 0 =====================
    pid = 14215
    RANK = 0
    WORLD_SIZE = 4
    LOCAL_RANK = 0
    MASTER_ADDR = 10.1.80.121
    MASTER_PORT = 1240

=========> dist.init_process_group() done. global_rank=1, local_rank=1
=========> dist.init_process_group() done. global_rank=0, local_rank=0
constructing DDP(model) ...
constructing DDP(model) ...
constructed DDP(model).
sync...
constructed DDP(model).
sync...
```

but on Node 1, it hangs on `DDP(model, device_ids=[gpu_id])`

```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

    ===================== 3 / 4, ibis: 1 =====================
    pid = 25333
    RANK = 3
    WORLD_SIZE = 4
    LOCAL_RANK = 1
    MASTER_ADDR = 10.1.80.121
    MASTER_PORT = 1240


    ===================== 2 / 4, ibis: 0 =====================
    pid = 25332
    RANK = 2
    WORLD_SIZE = 4
    LOCAL_RANK = 0
    MASTER_ADDR = 10.1.80.121
    MASTER_PORT = 1240

=========> dist.init_process_group() done. global_rank=2, local_rank=0
=========> dist.init_process_group() done. global_rank=3, local_rank=1

constructing DDP(model) ...
constructing DDP(model) ...
```

## System Info

Node 0: (master)

```
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.17.1

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti
GPU 8: GeForce RTX 2080 Ti
GPU 9: GeForce RTX 2080 Ti

Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[pip3] torchviz==0.0.1
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.7.1                    pypi_0    pypi
[conda] torchvision               0.8.2                    pypi_0    pypi
[conda] torchviz                  0.0.1                    pypi_0    pypi
```

Node 1:

```
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti
GPU 8: GeForce RTX 2080 Ti
GPU 9: GeForce RTX 2080 Ti

Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.7.1                    pypi_0    pypi
[conda] torchvision               0.8.2                    pypi_0    pypi
```

- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source): conda
- Build command you used (if compiling from source):
- OS: ubuntu 18.04
- PyTorch version: 1.7.1
- Python version: 3.8
- CUDA/cuDNN version: 10.2
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by mrshenli** [comment]
I tried this locally, but cannot reproduce it:

```
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=0 --master_addr="localhost" --master_port=23456 test.py


CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=1 --master_addr="localhost" --master_port=23456 test.py
```

**Comment by mrshenli** [comment]
Since all processes successfully passed `init_process_group`, it means all peers can find the master. 

In today's DDP ctor, IIUC, the only communication is the model params broadcast operation linked below. 

https://github.com/pytorch/pytorch/blob/8cd4dac78f32cb82e9a983e1d13006250ba78223/torch/nn/parallel/distributed.py#L479-L483

And this is a blocking operation. So, as rank 0 and 1 on master node finished DDP ctor successfully, it means all peers have joined that broadcast too. 

Another possibility might be, rank 2 and 3 on Node 1 weren't able to allocate DDP comm buffers on CUDA:

https://github.com/pytorch/pytorch/blob/8cd4dac78f32cb82e9a983e1d13006250ba78223/torch/nn/parallel/distributed.py#L507-L514

@JiaRu2016  do you exclusively use Node 1? Could there be any other workload interfering with your job?

**Comment by mrshenli** [comment]
Since I cannot reproduce it, we will need your help to identify the cause. On your deployment env, is it possible to find the installation location of PyTorch and modify [this file](https://github.com/pytorch/pytorch/blob/8cd4dac78f32cb82e9a983e1d13006250ba78223/torch/nn/parallel/distributed.py) by inserting some prints to identify where it hangs?

**Comment by JiaRu2016** [comment]
I tried test it locally on Node 0:

```
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=0 --master_addr="localhost" --master_port=62001 myscritpt.py

CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=1 --master_addr="localhost" --master_port=62001 myscritpt.py
```

and both raise error in `dist.init_process_group()`: 

```
Traceback (most recent call last):
  File "/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py", line 144, in <module>
    main(args)
  File "/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py", line 86, in main
    setup(RANK, WORLD_SIZE, LOCAL_RANK)
  File "/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py", line 73, in setup
    dist.init_process_group("nccl", rank=global_rank, world_size=global_world_size)
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled cuda error, NCCL version 2.7.8
Traceback (most recent call last):
  File "/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py", line 144, in <module>
    main(args)
  File "/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py", line 86, in main
    setup(RANK, WORLD_SIZE, LOCAL_RANK)
  File "/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py", line 73, in setup
    dist.init_process_group("nccl", rank=global_rank, world_size=global_world_size)
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled cuda error, NCCL version 2.7.8
Traceback (most recent call last):
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/rjia/anaconda3/envs/cuda102/bin/python', '-u', '/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py', '--local_rank=1']' returned non-zero exit status 1.
```

I use this node (and Node1) with other people, when I test this script  no one is using GPU 0~ 3, but other people's process is running on GPU 4 ~ 8

For truely two-node case, Later I will try to add some prints into DDP source code to figure out where it hangs

**Comment by JiaRu2016** [comment]
two-node case debug: After adding some prints, found that DDP constructor hang here:

```python
    def _sync_params_and_buffers(self, authoritative_rank=0):
        module_states = list(self.module.state_dict().values())
        if len(module_states) > 0:
            self._distributed_broadcast_coalesced(  # <-------- here
                module_states,
                self.broadcast_bucket_size,
                authoritative_rank)
```

**Comment by mrshenli** [comment]
> RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled cuda error, NCCL version 2.7.8

There seems to be a NCCL error. Could you please try switching to gloo backend and see if it still hangs?

**Comment by mrshenli** [comment]
If gloo does not hang but NCCL does, could you please try setting the following two env vars and see if there is any suspicious logs?

```
export NCCL_DEBUG=INFO
export NCCL_DEBUG_SUBSYS=ALL
```

**Comment by JiaRu2016** [comment]
after change to gloo, it runs normally. Then I add NCCL_DEBUG's and I found some suspicious log:

1. for local case (on one machine but two terminal each start the one launch command), there is
```shell
...
emu:80511:81734 [1] NCCL INFO Could not enable P2P between dev 1(=61000) and dev 0(=60000)
emu:80510:81733 [0] NCCL INFO Could not enable P2P between dev 0(=60000) and dev 1(=61000)
emu:80510:81733 [0] NCCL INFO Channel 00 : 0[60000] -> 1[61000] via direct shared memory
emu:80511:81734 [1] NCCL INFO Channel 00 : 1[61000] -> 2[62000] via P2P/IPC
emu:80510:81733 [0] transport/p2p.cc:276 NCCL WARN failed to open CUDA IPC handle : 217 peer access is not supported between these two devices
...
```


<details>
<summary>
full log
</summary>

(cuda102) ➜ emu ~/dl/explore_torch_dist git:(master) ✗ CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=0 --master_addr="localhost" --master_port=62001 /home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

    ===================== 0 / 4, emu: 0 =====================
    pid = 80510
    RANK = 0
    WORLD_SIZE = 4
    LOCAL_RANK = 0
    MASTER_ADDR = localhost
    MASTER_PORT = 62001


    ===================== 1 / 4, emu: 1 =====================
    pid = 80511
    RANK = 1
    WORLD_SIZE = 4
    LOCAL_RANK = 1
    MASTER_ADDR = localhost
    MASTER_PORT = 62001

emu:80510:80510 [0] NCCL INFO Bootstrap : Using [0]enp134s0f0:10.1.80.121<0>
emu:80510:80510 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
emu:80510:80510 [0] NCCL INFO NET/IB : No device found.
emu:80510:80510 [0] NCCL INFO NET/Socket : Using [0]enp134s0f0:10.1.80.121<0>
emu:80510:80510 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda10.2
emu:80511:80511 [1] NCCL INFO Bootstrap : Using [0]enp134s0f0:10.1.80.121<0>
emu:80511:80511 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
emu:80511:80511 [1] NCCL INFO NET/IB : No device found.
emu:80511:80511 [1] NCCL INFO NET/Socket : Using [0]enp134s0f0:10.1.80.121<0>
emu:80511:80511 [1] NCCL INFO Using network Socket
emu:80511:81734 [1] NCCL INFO Attribute coll of node net not found
emu:80511:81734 [1] NCCL INFO === System : maxWidth 12.0 ===
emu:80511:81734 [1] NCCL INFO CPU/0 (1/1/2)
emu:80511:81734 [1] NCCL INFO + PCI[12.0] - PCI/5E000
emu:80511:81734 [1] NCCL INFO               + PCI[12.0] - GPU/60000 (0)
emu:80511:81734 [1] NCCL INFO               + PCI[12.0] - GPU/61000 (1)
emu:80511:81734 [1] NCCL INFO               + PCI[12.0] - GPU/62000 (2)
emu:80511:81734 [1] NCCL INFO               + PCI[12.0] - GPU/63000 (3)
emu:80511:81734 [1] NCCL INFO + SYS[9.0] - CPU/1
emu:80511:81734 [1] NCCL INFO CPU/1 (1/1/2)
emu:80511:81734 [1] NCCL INFO + SYS[9.0] - CPU/0
emu:80511:81734 [1] NCCL INFO + PCI[3.0] - NIC/86000
emu:80511:81734 [1] NCCL INFO ==========================================
emu:80511:81734 [1] NCCL INFO GPU/60000 :GPU/60000 (0/5000.000000/LOC) GPU/61000 (2/12.000000/PIX) GPU/62000 (2/12.000000/PIX) GPU/63000 (2/12.000000/PIX) CPU/0 (2/12.000000/PHB) CPU/1 (3/9.000000/SYS)
emu:80511:81734 [1] NCCL INFO GPU/61000 :GPU/60000 (2/12.000000/PIX) GPU/61000 (0/5000.000000/LOC) GPU/62000 (2/12.000000/PIX) GPU/63000 (2/12.000000/PIX) CPU/0 (2/12.000000/PHB) CPU/1 (3/9.000000/SYS)
emu:80511:81734 [1] NCCL INFO GPU/62000 :GPU/60000 (2/12.000000/PIX) GPU/61000 (2/12.000000/PIX) GPU/62000 (0/5000.000000/LOC) GPU/63000 (2/12.000000/PIX) CPU/0 (2/12.000000/PHB) CPU/1 (3/9.000000/SYS)
emu:80511:81734 [1] NCCL INFO GPU/63000 :GPU/60000 (2/12.000000/PIX) GPU/61000 (2/12.000000/PIX) GPU/62000 (2/12.000000/PIX) GPU/63000 (0/5000.000000/LOC) CPU/0 (2/12.000000/PHB) CPU/1 (3/9.000000/SYS)
emu:80511:81734 [1] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 12.000000/12.000000, type PIX/PIX, sameChannels 1
emu:80511:81734 [1] NCCL INFO  0 : GPU/0 GPU/1 GPU/2 GPU/3
emu:80511:81734 [1] NCCL INFO Pattern 2, crossNic 0, nChannels 1, speed 12.000000/12.000000, type PIX/PIX, sameChannels 1
emu:80511:81734 [1] NCCL INFO  0 : GPU/0 GPU/1 GPU/2 GPU/3
emu:80511:81734 [1] NCCL INFO Pattern 3, crossNic 0, nChannels 1, speed 12.000000/12.000000, type PIX/PIX, sameChannels 1
emu:80511:81734 [1] NCCL INFO  0 : GPU/0 GPU/1 GPU/2 GPU/3
emu:80510:81733 [0] NCCL INFO Attribute coll of node net not found
emu:80510:81733 [0] NCCL INFO === System : maxWidth 12.0 ===
emu:80510:81733 [0] NCCL INFO CPU/0 (1/1/2)
emu:80510:81733 [0] NCCL INFO + PCI[12.0] - PCI/5E000
emu:80510:81733 [0] NCCL INFO               + PCI[12.0] - GPU/60000 (0)
emu:80510:81733 [0] NCCL INFO               + PCI[12.0] - GPU/61000 (1)
emu:80510:81733 [0] NCCL INFO               + PCI[12.0] - GPU/62000 (2)
emu:80510:81733 [0] NCCL INFO               + PCI[12.0] - GPU/63000 (3)
emu:80510:81733 [0] NCCL INFO + SYS[9.0] - CPU/1
emu:80510:81733 [0] NCCL INFO CPU/1 (1/1/2)
emu:80510:81733 [0] NCCL INFO + SYS[9.0] - CPU/0
emu:80510:81733 [0] NCCL INFO + PCI[3.0] - NIC/86000
emu:80510:81733 [0] NCCL INFO ==========================================
emu:80510:81733 [0] NCCL INFO GPU/60000 :GPU/60000 (0/5000.000000/LOC) GPU/61000 (2/12.000000/PIX) GPU/62000 (2/12.000000/PIX) GPU/63000 (2/12.000000/PIX) CPU/0 (2/12.000000/PHB) CPU/1 (3/9.000000/SYS)
emu:80510:81733 [0] NCCL INFO GPU/61000 :GPU/60000 (2/12.000000/PIX) GPU/61000 (0/5000.000000/LOC) GPU/62000 (2/12.000000/PIX) GPU/63000 (2/12.000000/PIX) CPU/0 (2/12.000000/PHB) CPU/1 (3/9.000000/SYS)
emu:80510:81733 [0] NCCL INFO GPU/62000 :GPU/60000 (2/12.000000/PIX) GPU/61000 (2/12.000000/PIX) GPU/62000 (0/5000.000000/LOC) GPU/63000 (2/12.000000/PIX) CPU/0 (2/12.000000/PHB) CPU/1 (3/9.000000/SYS)
emu:80510:81733 [0] NCCL INFO GPU/63000 :GPU/60000 (2/12.000000/PIX) GPU/61000 (2/12.000000/PIX) GPU/62000 (2/12.000000/PIX) GPU/63000 (0/5000.000000/LOC) CPU/0 (2/12.000000/PHB) CPU/1 (3/9.000000/SYS)
emu:80510:81733 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 12.000000/12.000000, type PIX/PIX, sameChannels 1
emu:80510:81733 [0] NCCL INFO  0 : GPU/0 GPU/1 GPU/2 GPU/3
emu:80510:81733 [0] NCCL INFO Pattern 2, crossNic 0, nChannels 1, speed 12.000000/12.000000, type PIX/PIX, sameChannels 1
emu:80510:81733 [0] NCCL INFO  0 : GPU/0 GPU/1 GPU/2 GPU/3
emu:80510:81733 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 1, speed 12.000000/12.000000, type PIX/PIX, sameChannels 1
emu:80510:81733 [0] NCCL INFO  0 : GPU/0 GPU/1 GPU/2 GPU/3
emu:80510:81733 [0] NCCL INFO Channel 00/02 :    0   1   2   3
emu:80510:81733 [0] NCCL INFO Channel 01/02 :    0   1   2   3
emu:80510:81733 [0] NCCL INFO Latency/AlgBw |    Tree/    LL |    Tree/ LL128 |    Tree/Simple |    Ring/    LL |    Ring/ LL128 |    Ring/Simple | CollNet/    LL | CollNet/ LL128 | CollNet/Simple |
emu:80510:81733 [0] NCCL INFO  Max NThreads |            512 |            640 |            512 |            512 |            640 |            256 |            512 |            640 |            512 |
emu:80510:81733 [0] NCCL INFO     Broadcast |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     4.6/   4.0 |    12.5/   0.0 |    14.1/  12.0 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
emu:80510:81733 [0] NCCL INFO        Reduce |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     4.6/   3.0 |    12.5/   0.0 |    14.1/  12.0 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
emu:80510:81733 [0] NCCL INFO     AllGather |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     6.6/   5.3 |    17.5/   0.0 |    25.5/  16.0 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
emu:80510:81733 [0] NCCL INFO ReduceScatter |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     6.6/   5.3 |    17.5/   0.0 |    25.5/  16.0 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
emu:80511:81734 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
emu:80510:81733 [0] NCCL INFO     AllReduce |    10.4/   1.4 |    15.8/   0.0 |   168.0/   5.4 |     9.6/   2.0 |    25.0/   0.0 |    42.6/   8.0 |    15.4/   0.9 |    20.8/   0.0 |    43.7/   5.4 |
emu:80511:81734 [1] NCCL INFO Trees [0] 2/-1/-1->1->0|0->1->2/-1/-1 [1] 2/-1/-1->1->0|0->1->2/-1/-1
emu:80510:81733 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
emu:80511:81734 [1] NCCL INFO Setting affinity for GPU 1 to ff,ffff0000,00ffffff
emu:80510:81733 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
emu:80510:81733 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
emu:80511:81734 [1] NCCL INFO Could not enable P2P between dev 1(=61000) and dev 0(=60000)
emu:80510:81733 [0] NCCL INFO Could not enable P2P between dev 0(=60000) and dev 1(=61000)
emu:80510:81733 [0] NCCL INFO Channel 00 : 0[60000] -> 1[61000] via direct shared memory
emu:80511:81734 [1] NCCL INFO Channel 00 : 1[61000] -> 2[62000] via P2P/IPC

emu:80510:81733 [0] transport/p2p.cc:276 NCCL WARN failed to open CUDA IPC handle : 217 peer access is not supported between these two devices
emu:80510:81733 [0] NCCL INFO transport.cc:79 -> 1
emu:80510:81733 [0] NCCL INFO init.cc:766 -> 1
emu:80510:81733 [0] NCCL INFO init.cc:840 -> 1
emu:80510:81733 [0] NCCL INFO group.cc:73 -> 1 [Async thread]
Traceback (most recent call last):
  File "/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py", line 144, in <module>
    main(args)
  File "/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py", line 86, in main
    setup(RANK, WORLD_SIZE, LOCAL_RANK)
  File "/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py", line 73, in setup
    dist.init_process_group("nccl", rank=global_rank, world_size=global_world_size)
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled cuda error, NCCL version 2.7.8

emu:80511:81734 [1] transport/p2p.cc:238 NCCL WARN failed to open CUDA IPC handle : 217 peer access is not supported between these two devices
emu:80511:81734 [1] NCCL INFO transport.cc:68 -> 1
emu:80511:81734 [1] NCCL INFO init.cc:766 -> 1
emu:80511:81734 [1] NCCL INFO init.cc:840 -> 1
emu:80511:81734 [1] NCCL INFO group.cc:73 -> 1 [Async thread]
Traceback (most recent call last):
  File "/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py", line 144, in <module>
    main(args)
  File "/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py", line 86, in main
    setup(RANK, WORLD_SIZE, LOCAL_RANK)
  File "/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py", line 73, in setup
    dist.init_process_group("nccl", rank=global_rank, world_size=global_world_size)
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled cuda error, NCCL version 2.7.8
Traceback (most recent call last):
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/rjia/anaconda3/envs/cuda102/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/rjia/anaconda3/envs/cuda102/bin/python', '-u', '/home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py', '--local_rank=1']' returned non-zero exit status 1.


</details>



2. for two-node case, logs is similar (on node 1):

```
ibis:13595:13676 [3] NCCL INFO Could not enable P2P between dev 3(=1d000) and dev 2(=1c000)
ibis:13594:13679 [2] NCCL INFO Channel 00 : 1[61000] -> 2[1c000] [receive] via NET/Socket/0
ibis:13594:13679 [2] NCCL INFO Could not enable P2P between dev 2(=1c000) and dev 3(=1d000)
ibis:13594:13679 [2] NCCL INFO Channel 00 : 2[1c000] -> 3[1d000] via direct shared memory
ibis:13595:13676 [3] NCCL INFO Channel 00 : 3[1d000] -> 0[60000] [send] via NET/Socket/0
ibis:13594:13679 [2] NCCL INFO Could not enable P2P between dev 2(=1c000) and dev 3(=1d000)
ibis:13595:13676 [3] NCCL INFO Could not enable P2P between dev 3(=1d000) and dev 2(=1c000)
ibis:13595:13676 [3] NCCL INFO Channel 00 : 3[1d000] -> 2[1c000] via direct shared memory
ibis:13595:13676 [3] NCCL INFO Could not enable P2P between dev 3(=1d000) and dev 2(=1c000)
ibis:13594:13679 [2] NCCL INFO Channel 00 : 2[1c000] -> 1[61000] [send] via NET/Socket/0
ibis:13594:13679 [2] NCCL INFO Channel 01 : 1[61000] -> 2[1c000] [receive] via NET/Socket/0
ibis:13594:13679 [2] NCCL INFO Could not enable P2P between dev 2(=1c000) and dev 3(=1d000)
ibis:13594:13679 [2] NCCL INFO Channel 01 : 2[1c000] -> 3[1d000] via direct shared memory
ibis:13595:13676 [3] NCCL INFO Channel 01 : 3[1d000] -> 0[60000] [send] via NET/Socket/0
ibis:13594:13679 [2] NCCL INFO Could not enable P2P between dev 2(=1c000) and dev 3(=1d000)
ibis:13595:13676 [3] NCCL INFO Channel 01 : 0[60000] -> 3[1d000] [receive] via NET/Socket/0
ibis:13595:13676 [3] NCCL INFO Could not enable P2P between dev 3(=1d000) and dev 2(=1c000)
ibis:13595:13676 [3] NCCL INFO Channel 01 : 3[1d000] -> 2[1c000] via direct shared memory
```


<details>
<summary>
full log
</summary>

(cuda102) ➜ ibis ~ python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=1 --master_addr="10.1.80.121" --master_port=62007 /home/rjia/dl/explore_torch_dist/ddp_MultiMachine.py
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

    ===================== 2 / 4, ibis: 0 =====================
    pid = 13594
    RANK = 2
    WORLD_SIZE = 4
    LOCAL_RANK = 0
    MASTER_ADDR = 10.1.80.121
    MASTER_PORT = 62007


    ===================== 3 / 4, ibis: 1 =====================
    pid = 13595
    RANK = 3
    WORLD_SIZE = 4
    LOCAL_RANK = 1
    MASTER_ADDR = 10.1.80.121
    MASTER_PORT = 62007

ibis:13595:13595 [3] NCCL INFO Bootstrap : Using [0]enp96s0f0:10.1.80.120<0>
ibis:13595:13595 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
ibis:13595:13595 [3] NCCL INFO NET/IB : No device found.
ibis:13595:13595 [3] NCCL INFO NET/Socket : Using [0]enp96s0f0:10.1.80.120<0>
ibis:13595:13595 [3] NCCL INFO Using network Socket
ibis:13594:13594 [2] NCCL INFO Bootstrap : Using [0]enp96s0f0:10.1.80.120<0>
ibis:13594:13594 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
ibis:13594:13594 [2] NCCL INFO NET/IB : No device found.
ibis:13594:13594 [2] NCCL INFO NET/Socket : Using [0]enp96s0f0:10.1.80.120<0>
ibis:13594:13594 [2] NCCL INFO Using network Socket
ibis:13594:13679 [2] NCCL INFO Attribute coll of node net not found
ibis:13594:13679 [2] NCCL INFO === System : maxWidth 0.2 ===
ibis:13594:13679 [2] NCCL INFO CPU/0 (1/1/2)
ibis:13594:13679 [2] NCCL INFO + PCI[12.0] - PCI/18000
ibis:13594:13679 [2] NCCL INFO               + PCI[12.0] - GPU/1C000 (2)
ibis:13594:13679 [2] NCCL INFO               + PCI[12.0] - GPU/1D000 (3)
ibis:13594:13679 [2] NCCL INFO + PCI[6.0] - PCI/5E000
ibis:13594:13679 [2] NCCL INFO              + PCI[0.2] - NIC/60000
ibis:13594:13679 [2] NCCL INFO                           + NET[1.2] - NET/0 (0/0/1.250000)
ibis:13594:13679 [2] NCCL INFO ==========================================
ibis:13594:13679 [2] NCCL INFO GPU/1C000 :GPU/1C000 (0/5000.000000/LOC) GPU/1D000 (2/12.000000/PIX) CPU/0 (2/12.000000/PHB) NET/0 (5/0.187500/PHB)
ibis:13594:13679 [2] NCCL INFO GPU/1D000 :GPU/1C000 (2/12.000000/PIX) GPU/1D000 (0/5000.000000/LOC) CPU/0 (2/12.000000/PHB) NET/0 (5/0.187500/PHB)
ibis:13594:13679 [2] NCCL INFO NET/0 :GPU/1C000 (5/0.187500/PHB) GPU/1D000 (5/0.187500/PHB) CPU/0 (3/0.187500/PHB) NET/0 (0/5000.000000/LOC)
ibis:13594:13679 [2] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 0.120000/0.120000, type PIX/PHB, sameChannels 1
ibis:13594:13679 [2] NCCL INFO  0 : NET/0 GPU/2 GPU/3 NET/0
ibis:13594:13679 [2] NCCL INFO Pattern 2, crossNic 0, nChannels 1, speed 0.240000/0.120000, type PIX/PHB, sameChannels 1
ibis:13594:13679 [2] NCCL INFO  0 : NET/0 GPU/2 GPU/3 NET/0
ibis:13594:13679 [2] NCCL INFO Pattern 3, crossNic 0, nChannels 0, speed 0.000000/0.000000, type NVL/PIX, sameChannels 1
ibis:13595:13676 [3] NCCL INFO Attribute coll of node net not found
ibis:13595:13676 [3] NCCL INFO === System : maxWidth 0.2 ===
ibis:13595:13676 [3] NCCL INFO CPU/0 (1/1/2)
ibis:13595:13676 [3] NCCL INFO + PCI[12.0] - PCI/18000
ibis:13595:13676 [3] NCCL INFO               + PCI[12.0] - GPU/1C000 (2)
ibis:13595:13676 [3] NCCL INFO               + PCI[12.0] - GPU/1D000 (3)
ibis:13595:13676 [3] NCCL INFO + PCI[6.0] - PCI/5E000
ibis:13595:13676 [3] NCCL INFO              + PCI[0.2] - NIC/60000
ibis:13595:13676 [3] NCCL INFO                           + NET[1.2] - NET/0 (0/0/1.250000)
ibis:13595:13676 [3] NCCL INFO ==========================================
ibis:13595:13676 [3] NCCL INFO GPU/1C000 :GPU/1C000 (0/5000.000000/LOC) GPU/1D000 (2/12.000000/PIX) CPU/0 (2/12.000000/PHB) NET/0 (5/0.187500/PHB)
ibis:13595:13676 [3] NCCL INFO GPU/1D000 :GPU/1C000 (2/12.000000/PIX) GPU/1D000 (0/5000.000000/LOC) CPU/0 (2/12.000000/PHB) NET/0 (5/0.187500/PHB)
ibis:13595:13676 [3] NCCL INFO NET/0 :GPU/1C000 (5/0.187500/PHB) GPU/1D000 (5/0.187500/PHB) CPU/0 (3/0.187500/PHB) NET/0 (0/5000.000000/LOC)
ibis:13595:13676 [3] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 0.120000/0.120000, type PIX/PHB, sameChannels 1
ibis:13595:13676 [3] NCCL INFO  0 : NET/0 GPU/2 GPU/3 NET/0
ibis:13595:13676 [3] NCCL INFO Pattern 2, crossNic 0, nChannels 1, speed 0.240000/0.120000, type PIX/PHB, sameChannels 1
ibis:13595:13676 [3] NCCL INFO  0 : NET/0 GPU/2 GPU/3 NET/0
ibis:13595:13676 [3] NCCL INFO Pattern 3, crossNic 0, nChannels 0, speed 0.000000/0.000000, type NVL/PIX, sameChannels 1
ibis:13594:13679 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
ibis:13594:13679 [2] NCCL INFO Trees [0] 3/-1/-1->2->1|1->2->3/-1/-1 [1] 3/-1/-1->2->-1|-1->2->3/-1/-1
ibis:13594:13679 [2] NCCL INFO Setting affinity for GPU 2 to ff,ffff0000,00ffffff
ibis:13595:13676 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
ibis:13595:13676 [3] NCCL INFO Trees [0] -1/-1/-1->3->2|2->3->-1/-1/-1 [1] 0/-1/-1->3->2|2->3->0/-1/-1
ibis:13595:13676 [3] NCCL INFO Setting affinity for GPU 3 to ff,ffff0000,00ffffff
ibis:13595:13676 [3] NCCL INFO Could not enable P2P between dev 3(=1d000) and dev 2(=1c000)
ibis:13594:13679 [2] NCCL INFO Channel 00 : 1[61000] -> 2[1c000] [receive] via NET/Socket/0
ibis:13594:13679 [2] NCCL INFO Could not enable P2P between dev 2(=1c000) and dev 3(=1d000)
ibis:13594:13679 [2] NCCL INFO Channel 00 : 2[1c000] -> 3[1d000] via direct shared memory
ibis:13595:13676 [3] NCCL INFO Channel 00 : 3[1d000] -> 0[60000] [send] via NET/Socket/0
ibis:13594:13679 [2] NCCL INFO Could not enable P2P between dev 2(=1c000) and dev 3(=1d000)
ibis:13595:13676 [3] NCCL INFO Could not enable P2P between dev 3(=1d000) and dev 2(=1c000)
ibis:13595:13676 [3] NCCL INFO Channel 00 : 3[1d000] -> 2[1c000] via direct shared memory
ibis:13595:13676 [3] NCCL INFO Could not enable P2P between dev 3(=1d000) and dev 2(=1c000)
ibis:13594:13679 [2] NCCL INFO Channel 00 : 2[1c000] -> 1[61000] [send] via NET/Socket/0
ibis:13594:13679 [2] NCCL INFO Channel 01 : 1[61000] -> 2[1c000] [receive] via NET/Socket/0
ibis:13594:13679 [2] NCCL INFO Could not enable P2P between dev 2(=1c000) and dev 3(=1d000)
ibis:13594:13679 [2] NCCL INFO Channel 01 : 2[1c000] -> 3[1d000] via direct shared memory
ibis:13595:13676 [3] NCCL INFO Channel 01 : 3[1d000] -> 0[60000] [send] via NET/Socket/0
ibis:13594:13679 [2] NCCL INFO Could not enable P2P between dev 2(=1c000) and dev 3(=1d000)
ibis:13595:13676 [3] NCCL INFO Channel 01 : 0[60000] -> 3[1d000] [receive] via NET/Socket/0
ibis:13595:13676 [3] NCCL INFO Could not enable P2P between dev 3(=1d000) and dev 2(=1c000)
ibis:13595:13676 [3] NCCL INFO Channel 01 : 3[1d000] -> 2[1c000] via direct shared memory
ibis:13594:13679 [2] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
ibis:13594:13679 [2] NCCL INFO comm 0x7fbff4001060 rank 2 nranks 4 cudaDev 2 busId 1c000 - Init COMPLETE
ibis:13594:13594 [2] NCCL INFO AllReduce: opCount 0 sendbuff 0x7fbffb600000 recvbuff 0x7fbffb600000 count 1 datatype 1 op 0 root 0 comm 0x7fbff4001060 [nranks=4] stream 0x56489773d5f0
ibis:13595:13676 [3] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
ibis:13595:13676 [3] NCCL INFO comm 0x7fb274001060 rank 3 nranks 4 cudaDev 3 busId 1d000 - Init COMPLETE
ibis:13595:13595 [3] NCCL INFO AllReduce: opCount 0 sendbuff 0x7fb27b600000 recvbuff 0x7fb27b600000 count 1 datatype 1 op 0 root 0 comm 0x7fb274001060 [nranks=4] stream 0x558474a5ebc0
=========> dist.init_process_group() done. global_rank=2, local_rank=0
=========> dist.init_process_group() done. global_rank=3, local_rank=1
constructing DDP(model) ...
constructing DDP(model) ...
</details>

So I guess It is something related to network config? Is there anything special related to network config that is required for torch.dist to work?

**Comment by maqy1995** [comment]
Hi @JiaRu2016, have you solved this problem?
In my environment, an interesting phenomenon may be helpful.
I have 6 Tesla T4s in each node. When I do not use GPU 0, the program can run successfully. If I use all GPUs, the program can also run smoothly. But when I used gpu0 and not all GPUs, there will be some problems.
case1: node0 and node1 used gpus: 0,1,2,3,4,5 run sucessfully.
case2: node0 and node1 used gpus: 2,3,4,5 run sucessfully.
case3: node0 and node1 used gpus: 0,1,2,3 failed.

**Comment by dengjh-213** [comment]
> two-node case debug: After adding some prints, found that DDP constructor hang here:
> 
> ```python
>     def _sync_params_and_buffers(self, authoritative_rank=0):
>         module_states = list(self.module.state_dict().values())
>         if len(module_states) > 0:
>             self._distributed_broadcast_coalesced(  # <-------- here
>                 module_states,
>                 self.broadcast_bucket_size,
>                 authoritative_rank)
> ```

met same problem

**Comment by dengjh-213** [comment]
And in my case, it's worked when I test with a toy model, which just with few parameters.

When I try with a big model, all processes successfully passed init_process_group, but except the master node, all other nodes will hang in DDP constructor just like the post.

**Comment by dengjh-213** [comment]
I solved the problem by using the latest version nccl, which is v2.9.6.

You can have a try:

1. Install the latest nccl:sudo apt install libnccl2=2.9.6-1+cuda11.0 libnccl-dev=2.9.6-1+cuda11.0
