### ISSUE TITLE
CUDA error for some Conv2d dimensions

### ISSUE THREAD

**Issue by jcjohnson** [pytorch/pytorch#544]
I've run into some specific sizes of convolutions that work on CPU but crash on GPU:

```python
import torch

dtype = torch.cuda.FloatTensor

bad_sizes = [
  (1, 256, 109, 175),
  (1, 256, 80, 128),
  (1, 256, 120, 192),
]

x = torch.randn(*bad_sizes[2]).type(dtype)
x_var = torch.autograd.Variable(x)
print('x.size() = ', x.size())

conv = torch.nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1)
conv.type(dtype)

y = conv(x_var)
print(y.size())
```

Any of the bad sizes results in:

```
Traceback (most recent call last):
  File "foo.py", line 19, in <module>
    y = conv(x_var)
  File "/home/justin/code/env3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 210, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/justin/code/env3/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 235, in forward
    self.padding, self.dilation, self.groups)
  File "/home/justin/code/env3/lib/python3.5/site-packages/torch/nn/functional.py", line 37, in conv2d
    return f(input, weight, bias) if bias is not None else f(input, weight)
  File "/home/justin/code/env3/lib/python3.5/site-packages/torch/nn/_functions/conv.py", line 33, in forward
    output = self._update_output(input, weight, bias)
  File "/home/justin/code/env3/lib/python3.5/site-packages/torch/nn/_functions/conv.py", line 84, in _update_output
    self.groups, cudnn.benchmark)
RuntimeError: CUDA error
```

I'm using PyTorch installed from source at https://github.com/pytorch/pytorch/commit/f8e89fbe1123f6788992b70361f13ad498665327 on Ubuntu 16.04 with CUDA 8.0.44, CUDA driver 367.57, and cuDNN 5.1.5.

I get the same error on a Pascal Titan X and a Maxwell Titan X, and on both Python 2.7.12 and Python 3.5.2.

**Comment by soumith** [comment]
verified that this works with `torch` 

```lua
require 'cudnn'
cudnn.benchmark = true
x = torch.randn(1, 256, 109, 175):cuda()
conv = cudnn.SpatialConvolution(256, 256, 3, 3, 1, 1, 1, 1):cuda()
o = conv:forward(x)
```

**Comment by soumith** [comment]
verified that it fails only when using cudnn.
Verified it by disabling the cudnn backend at the beginning of the script:
```
import torch
torch.backends.cudnn.enabled = False
```

**Comment by soumith** [comment]
@ngimel do you have an idea of what's up here? I verified the code-path to not have obvious bugs like integer division

**Comment by ngimel** [comment]
I'm away from the computer now, will take a look at it tomorrow. First thing I'd look at are parameters passed to Cudnn in torch and pytorch - they must be different somehow. That said, getting cuda error is strange, Cudnn should have returned some Cudnn error status.

**Comment by qunluo** [comment]
I find that this is because of OOM, I fix this by https://github.com/qunluo/pytorch/commit/a00b77bb69904b864da39cab0bdf39bb0ebba6f6.
Maybe there are some errors in cudnnGetConvolutionForwardWorkspaceSize, but I didn't have the source code for debugging(Nvidia didn't open source).
I also recommend changing the cuda error to https://github.com/qunluo/pytorch/commit/44b79f70c337ea53a928bb79988b02b237f05b15.

**Comment by soumith** [comment]
fixed in master

**Comment by jarrelscy** [comment]
Hi, I've recently updated to Pytorch 0.4.0 from Conda and have been getting a similar error:
CUDA 9.0.176
CUDA driver 384.111
CuDNN 7.1
Ubuntu 16.04
Running on Titan Xp with 12GB of mem. 


Running the following:

```
from torch.autograd import Variable
import torch
#torch.backends.cudnn.enabled = False
b = Variable(torch.ones(16,1,512,512).cuda())
c = torch.nn.Conv2d(1,512,1,1).cuda()
print (c(b).size())
```

Gives the error:
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

Disabling CuDNN makes it work.
Changing the dimensions to 15x1x512x512 or 16x1x511x511 makes it run as well.

This code used to run in PyTorch 0.2.0 - so I'm unclear what the problem might be.

**Comment by jangho2001us** [comment]
> verified that it fails only when using cudnn.
> Verified it by disabling the cudnn backend at the beginning of the script:
> 
> ```
> import torch
> torch.backends.cudnn.enabled = False
> ```

@soumith 
Thanks for your comment.
By removing the line, 'cndnn.backend = True', I am able to solve this problem.
