### ISSUE TITLE
CUDA error: device-side assert triggered(torch1.8.1+cuda11.1)

### ISSUE THREAD

**Issue by WZMIAOMIAO** [pytorch/pytorch#55027]
## To Reproduce

There are two examples to reproduce this bug when I train official faster rcnn with pascal voc dataset.

example1:
```python
import torch
from torchvision.models.detection import fasterrcnn_resnet50_fpn


def main():
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print("using {}".format(device.type))

    img = [torch.rand((3, 442, 500), dtype=torch.float32, device=device)]

    target = [{'boxes': torch.as_tensor([[122., 1., 230., 176.],
                                         [336., 1., 443., 150.]], dtype=torch.float32, device=device),
                'labels': torch.as_tensor([5, 5], dtype=torch.int64, device=device),
                'image_id': torch.as_tensor([1], dtype=torch.int64, device=device),
                'area': torch.as_tensor([18900., 15943.], dtype=torch.float32, device=device),
                'iscrowd': torch.as_tensor([0, 0], dtype=torch.int64, device=device)}]

    model = fasterrcnn_resnet50_fpn(pretrained=False, pretrained_backbone=False).to(device)
    model.train()

    res = model(img, target)
    print(res)


if __name__ == '__main__':
    main()
```

example2:

```python
import torch
from torchvision.models.detection import fasterrcnn_resnet50_fpn


def main():
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print("using {}".format(device.type))

    img = [torch.rand((3, 442, 500), dtype=torch.float32, device=device)]
    target = [{'boxes': torch.as_tensor([[29., 87., 447., 420.],
                                         [211., 44., 342., 167.]], dtype=torch.float32, device=device),
               'labels': torch.as_tensor([13, 15], dtype=torch.int64, device=device),
               'image_id': torch.as_tensor([0], dtype=torch.int64, device=device),
               'area': torch.as_tensor([139194.,  16113.], dtype=torch.float32, device=device),
               'iscrowd': torch.as_tensor([0, 0], dtype=torch.int64, device=device)}]

    model = fasterrcnn_resnet50_fpn(pretrained=False, pretrained_backbone=False).to(device)
    model.train()

    with torch.cuda.amp.autocast(enabled=True):
        re = model(img, target)

    print(re)


if __name__ == '__main__':
    main()
```
In this example, When I delete ```with torch.cuda.amp.autocast(enabled=True):``` or using ```with torch.cuda.amp.autocast(enabled=False):```, this bug disappears.

------

Error messages as follows:
```
using cuda
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [32,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [33,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [34,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [76,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [78,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [80,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [81,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [82,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [84,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [85,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [86,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [88,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [89,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [90,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [92,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [96,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [97,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [98,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [100,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [101,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [102,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [103,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [104,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [105,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [106,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [107,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [108,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [109,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [110,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [111,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [112,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [113,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [114,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [116,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [117,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [118,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [120,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [121,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [122,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [124,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [125,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [126,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [4,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [5,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [6,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [7,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [8,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [9,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [10,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [11,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [12,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [13,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [14,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [15,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [16,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [17,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [18,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [19,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [20,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [21,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [22,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [24,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [25,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [26,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [27,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [28,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [29,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [30,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "bbbbbbbbug.py", line 34, in <module>
    main()
  File "bbbbbbbbug.py", line 28, in main
    re = model(img, target2)
  File "/usr/local/miniconda3/envs/torch18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/torch18/lib/python3.8/site-packages/torchvision/models/detection/generalized_rcnn.py", line 97, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/usr/local/miniconda3/envs/torch18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/torch18/lib/python3.8/site-packages/torchvision/models/detection/rpn.py", line 364, in forward
    loss_objectness, loss_rpn_box_reg = self.compute_loss(
  File "/usr/local/miniconda3/envs/torch18/lib/python3.8/site-packages/torchvision/models/detection/rpn.py", line 297, in compute_loss
    sampled_pos_inds = torch.where(torch.cat(sampled_pos_inds, dim=0))[0]
RuntimeError: CUDA error: device-side assert triggered
```

## Expected behavior

There should be no problems. 
When I using torch1.6/1.7.1 with cuda10.1, this bug disappears.

## Environment
 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Centos7
 - How you installed PyTorch (`conda`, `pip`, source): pip install 
 - Build command you used (if compiling from source): no
 - Python version: 3.8
 - CUDA/cuDNN version: cuda:11.1
 - GPU models and configuration: tesla v100
 - GPU driver: 460.32.03

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ngimel @mcarilli @ptrblck

**Comment by WZMIAOMIAO** [comment]
@gchanan Could you add a new label ```module: cuda```?  It's not just about the amp module.

**Comment by ppwwyyxx** [comment]
Confirmed using the above repro with CUDA11.1, official torch 1.8.1 package on GTX1070, so it's not just about 8.6 architecture. Also confirm that wrong results come from `torch.randperm` in both the above repro and in https://github.com/facebookresearch/detectron2/issues/2837

@gchanan can you mark this high-pri? because this is about silent wrong results of `torch.randperm`.

**Comment by zasdfgbnm** [comment]
I can reproduce this with 1.8.1 and nightly wheel, but I can not reproduce this with PyTorch built from source. Could this be related to: https://github.com/pytorch/pytorch/issues/54245? BTW, I am also seeing memory violation in https://github.com/pytorch/pytorch/pull/55175, could be related as well.

**Comment by ppwwyyxx** [comment]
I think this issue has the same root cause as #54245 and #52663 and it was actually not fixed by switching from thrust to cub. The cause should be the `STB_GNU_UNIQUE` symbols as pointed out by @VoVAllen in https://github.com/NVIDIA/thrust/issues/1401#issuecomment-806403746. 

To verify the above claim, I ran [this python script](http://ppwwyyxx.com/blog/2021/Patch-STB_GNU_UNIQUE/) on `libtorch_cuda_cpp.so` inside pytorch, and the bug disappears. The script hides all symbols with `STB_GNU_UNIQUE` type.

A proper fix is probably to try the `-fno-gnu-unique` option as mentioned in https://github.com/pytorch/pytorch/issues/52663#issuecomment-809092114.

**Comment by VoVAllen** [comment]
@ppwwyyxx The python script looks nice. And changing from thrust to cub won't solve the issue, defining own namespace for cub is also required to avoid conflict. The root cause is from cub. And due to thrust cannot change the cub namespace based on different project, we temporarily removed the thrust dependency.
Example: https://github.com/nv-dlasalle/dgl/blob/e27c9f2f6b7e08f89c42c6af3bcec6bc3444dccc/src/array/cuda/dgl_cub.cuh, https://github.com/dmlc/dgl/pull/2758

**Comment by ngimel** [comment]
Unfortunately even if torch is compiled with fno-gnu-unique, the cub cache related bugs are still present #55264, I also verified this locally. When `.sort` is called after `randperm`, cub doesn't correctly retrive the value of ptx_version. 
The fix is probably to completely get rid of non-trivial thrust functions in torch (those that rely on static cache of ptx version and num devices), currently `sort` calls `thrust::sort` and `randperm` calls cub sort, and to define a namespace for cub calls.

**Comment by zasdfgbnm** [comment]
Getting rid of `thrust::sort` is already on my plan. I already have one PR at https://github.com/pytorch/pytorch/pull/54626. And migrating more thrust sort to cub sort are my next things to do. Hope this will help.

**Comment by VoVAllen** [comment]
@ngimel @zasdfgbnm Another workaround I could suggest is setting macro `CUB_CPP_DIALECT` to `2003`, which turns off using static cache variable inside cub(You can see reference 1). However there might be some performance degradation. 

Reference:
- https://github.com/NVIDIA/cub/blob/f5ef160af684fcd00c76443c42a393cae5653f2e/cub/util_device.cuh#L428-L448
- https://github.com/NVIDIA/cub/blob/e4da22df11ed459e44f3e49cc4cfc5363d3a2021/cub/util_cpp_dialect.cuh

**Comment by VoVAllen** [comment]
@ngimel Also I guess the so in CI pipeline is not rebuilt with the new flags due to the build cache. The build process took almost no time https://app.circleci.com/pipelines/github/pytorch/pytorch/295663/workflows/2669acdb-3d8c-4634-89e3-0d0032715cd8/jobs/12095039

**Comment by ngimel** [comment]
@VoVAllen unfortunately we cannot disable caches, internal workloads would be significantly regressed in this case. 
That docker job you link doesn't rebuild pytorch, but others (without "docker" in the name) do. And I reproduced the failure with clean local rebuild adding `-fno-gnu-unique`, so it's definitely not a CI fluke.

**Comment by ysyyork** [comment]
> I think this issue has the same root cause as #54245 and #52663 and it was actually not fixed by switching from thrust to cub. The cause should be the `STB_GNU_UNIQUE` symbols as pointed out by @VoVAllen in [NVIDIA/thrust#1401 (comment)](https://github.com/NVIDIA/thrust/issues/1401#issuecomment-806403746).
> 
> To verify the above claim, I ran [this python script](http://ppwwyyxx.com/blog/2021/Patch-STB_GNU_UNIQUE/) on `libtorch_cuda_cpp.so` inside pytorch, and the bug disappears. The script hides all symbols with `STB_GNU_UNIQUE` type.
> 
> A proper fix is probably to try the `-fno-gnu-unique` option as mentioned in [#52663 (comment)](https://github.com/pytorch/pytorch/issues/52663#issuecomment-809092114).

Tested this and verified it's working by patching the libtorch_cuda_cpp.so file. The link here is in Chinese but basically just copy the sample code inside and run a python command on the libtorch_cuda_cpp.so file and it should resolve the issue. Haven't tried `-fno-gnu-unique` flag yet.

**Comment by ngimel** [comment]
The detectron error is fixed on master/nightlies with #55292. 3rd party projects depending on torch are advised not to use thrust, and wrap cub in its own namespace to avoid these errors. Longer term, pytorch should stop using thrust and rely on namespaced cub only.  #52663 is to track extension errors.

**Comment by sonamRinchen** [comment]
![Screenshot from 2021-06-29 15-34-52](https://user-images.githubusercontent.com/53063546/123857131-f38fc100-d8ef-11eb-9670-74bb4f8166eb.png)

Hi, I ran into similar issue as well. I tried almost all the fixes that you guys have mentioned above but sadly i still could not able to fix the problem. However, I could not able to perform what @ysyyork and @ppwwyyxx have suggested to do. Can someone please help me how to copy and run that python script (mentioned by @ysyyork  ) on libtroch_cuda_cpp.so (which is a binary file).

my system configurations: python3.7, pytorch 1.9.0+cu111, torchvision 0.10.0+cu111 and Cuda 11.1

**Comment by zlin0** [comment]
Same with sonamRinchen  >< 

I got same error `RuntimeError: CUDA error: device-side assert triggered` in the CUDA 11.1 with  pytorch-1.8.0-py3.8_cuda11.1_cudnn8.0.5_0 and pytorch-1.9.1-py3.8_cuda11.1_cudnn8.0.5_0 

when I call `.scatter_()` in the torch.DataParallel mode.                                                                                                                                                               


> 
> Hi, I ran into similar issue as well. I tried all the fixes that you guys have mentioned above but sadly i still could not able to fix the problem. I even tried the fix that @ysyyork and @ppwwyyxx have suggested to do. I still have the same issue though.
> 
> my system configurations: python3.7, pytorch 1.9.0+cu111, torchvision 0.10.0+cu111 and Cuda 11.1

**Comment by zhaochentju** [comment]
the same error "RuntimeError: CUDA error: device-side assert triggered" in the RTX3090 CUDA 11.1 + pytorch 1.8.1, is there any way to solve this problem? Thanks a lot!

**Comment by abhirooptalasila** [comment]
Did anyone manage to solve this? Facing the same issue

**Comment by VoVAllen** [comment]
@abhirooptalasila This is most likely due to some indexing operations are out of range. Could you open a separate issue to describe your situation?

**Comment by abhirooptalasila** [comment]
Will do. 
But for me, the error pops up at epoch ~ 200. So even if there are any indexing issues, they should've occurred in the first epoch itself right?

**Comment by kumuji** [comment]
Having the same issue with pytorch 1.10.0+cu113 and RTX3090. For me the error appears unpredictably on a `.reshape()` function.

**Comment by ppwwyyxx** [comment]
To people commenting after this issue is closed: the bug is __already fixed__. Seeing the same __error message__ does not necessarily mean you're meeting the same bug. It's 99% probability a different bug because the error message is very generic. Commenting on this issue will unlikely get you any useful information on other bugs.

**Comment by Rango-Zhang-Hang** [comment]
> Will do. But for me, the error pops up at epoch ~ 200. So even if there are any indexing issues, they should've occurred in the first epoch itself right?

Hi! I am facing the similar issue with yours. The CUDA device assert error occured at the middle of the training. May I ask u have u solve this problem? Though u raised it over one year :)

**Comment by abhirooptalasila** [comment]
@Rango-Zhang-Hang, as @ppwwyyxx mentioned, the error is a very generic one. To solve the issue, we'd need the proper stack trace and code. Try opening a new issue if you're sure your code has no issues. To get the full stack trace, run your program with `CUDA_LAUNCH_BLOCKING=1`

**Comment by vTuanpham** [comment]
For me, i set the wrong tokenizer for the dataloader on a different model :(, just a head-up for anyone using hf-transformers, silly mistake...
