### ISSUE TITLE
"Reduce Failed to Synchronise" in F.binary_cross_entropy 

### ISSUE THREAD

**Issue by angusturner** [pytorch/pytorch#5560]
Since upgrading PyTorch to the master branch, I am occasionally receiving the following error:

```
/home/user/cuda-ubuntu-16.04-ec2/pytorch/aten/src/THCUNN/BCECriterion.cu:30: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [223,0,0] Assertion `input >= 0. && input <= 1.` failed.
Traceback (most recent call last):
  File "train_model.py", line 138, in <module>
    train_model(config)
  File "train_model.py", line 105, in train_model
    worker.train(train_loader, plot_lr=plot_lr, on_iter=on_iter)
  File "/home/user/src/worker.py", line 204, in train
    time_loss = F.binary_cross_entropy(time_pred, time_hist.float())
  File "/home/user/miniconda3/envs/cuda/lib/python3.6/site-packages/torch/nn/functional.py", line 1507, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, size_average, reduce)
RuntimeError: reduce failed to synchronize: device-side assert triggered
```

In this trace, `time_loss` is the output of a linear network with `nn.Sigmoid()` on the output, and `time_hist` is from a binary dataset, which I am confident is correct (because I can complete multiple epoch before it fails).

I haven't checked if `F.binary_cross_entropy_with_logits` fixes the issue.

System details:
- OS: Ubuntu 16.0.4
- PyTorch version: 0.4.0a0+55c64e5
- How you installed PyTorch (conda, pip, source): source
- Python version: Python 3.6.1
- CUDA/cuDNN version: CUDA release 9.0, V9.0.176 / CUDNN 7005
- GPU models and configuration: 4x Nvidia M60
- GCC version (if compiling from source): GCC 4.4.7

**Comment by apaszke** [comment]
Can you try adding `assert (time_pred >= 0. & time_pred <= 1.).all()` and the same for `time_hist` before this line, and seeing if this assert is ever triggered?

**Comment by fac2003** [comment]
I am also seeing this exception, but running against release 0.3.1:
```
/pytorch/torch/lib/THCUNN/BCECriterion.cu:30: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [223,0,0] Assertion `input >= 0. && input <= 1.` failed.
Traceback (most recent call last):
  File "/home/campagne/genotypetensors/src/org/campagnelab/dl/genotypetensors/autoencoder/TrainAutoEncoder.py", line 307, in <module>
    train_once(args, problem, use_cuda)
  File "/home/campagne/genotypetensors/src/org/campagnelab/dl/genotypetensors/autoencoder/TrainAutoEncoder.py", line 305, in train_once
    testing_loop_method=testing_loop_method)
  File "/home/campagne/genotypetensors/src/org/campagnelab/dl/genotypetensors/autoencoder/common_trainer.py", line 282, in training_loops
    perfs += training_loop_method(epoch)
  File "/home/campagne/genotypetensors/src/org/campagnelab/dl/genotypetensors/autoencoder/adversarial_autoencoder_trainer.py", line 158, in train_semisup_aae
    semisup_loss = self.net.get_semisup_loss(input_s, target_s) * weight
  File "/home/campagne/genotypetensors/src/org/campagnelab/dl/genotypetensors/autoencoder/semisup_adversarial_autoencoder.py", line 312, in get_semisup_loss
    semisup_loss = self.semisup_loss_criterion(categories_input, categories_target)
  File "/scratchLocal/campagne/data/pytorch/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratchLocal/campagne/data/pytorch/pytorch/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 695, in forward
    return F.multilabel_soft_margin_loss(input, target, self.weight, self.size_average)
  File "/scratchLocal/campagne/data/pytorch/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1320, in multilabel_soft_margin_loss
    return binary_cross_entropy(input, target, weight, size_average)
  File "/scratchLocal/campagne/data/pytorch/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1200, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, size_average)
RuntimeError: reduce failed to synchronize: device-side assert triggered
```

System details:

OS: CentOS Linux release 7.4.1708 (Core)
PyTorch version: 0.3.1
How you installed PyTorch (conda, pip, source): pip
Python version: Python 3.6.0
CUDA/cuDNN version: CUDA release 8.0, V8.0.61 / CUDNN 5105
GPU models and configuration: GTX1080Ti

**Comment by hzxie** [comment]
The same in PyTorch 0.4.0.

**Comment by hzxie** [comment]
See also: #2209

BCELoss accepts only inputs that have all elements in range [0; 1] but this condition doesn't hold in your case

**Comment by ImMrMa** [comment]
I think it's a bug.
I check my data, all is in range[0;1],but it happened.

**Comment by pengshuang** [comment]
Same problem!

**Comment by stihl1210** [comment]
Same problem, i checked input/output, type of data. Very strange because I have changed only architecture a bit and then this this error was shown. 

I have found that I didn't added Sigmoid at the end. After adding - everything looks good.

**Comment by ImMrMa** [comment]
yeah!,add the sigmoid solve the problem.

**Comment by yf225** [comment]
@ImMrMa @pengshuang @stihl1210 Can you provide a minimal reproducible example?

**Comment by PuYuQian** [comment]
I have added the Sigmoid to be my output layer ,but this error was still shown.

**Comment by expectopatronum** [comment]
Strangely I also encounter this problem after a few epochs. Other models with the same setup (Sigmoid + BCELoss) work. I will try to create a minimal reproducible example.

**Comment by stihl1210** [comment]
I tried to create one example but I couldn't reproduce error easily. I
think that problem could be related to dataparallel and prediction that
were not aligned to 0-1 range. Adding sigmoid helped in my case and now I
have no problems with BCE loss


śr., 20 mar 2019, 14:28 użytkownik Verena Haunschmid <
notifications@github.com> napisał:

**Comment by aminekechaou** [comment]
I had the same problem and and the reason was that I forgot to set the device in the target tensors. Simply calling .to(device=device) fixed the problem

**Comment by Irlyue** [comment]
The error message is really confusing. Most of the time it's not because your target tensor is not in range [0, 1]. Usually it's some other error such that the logit tensor reaches infinity.

**Comment by selimarikan** [comment]
Can reproduce the error but still sporadic. I have 2 GPUs in the machine. An interesting detail is that this only happens on RTX 2080Ti but not on GTX Titan.
CentOS 7
Python 3.6.5
PyTorch 1.1.0
nvidia-smi 418.43
nvidia-driver 418.43
CUDA 10.1

**Comment by msobroza** [comment]
@selaselah same problem with RTX Titan, Python 3.6, Pytorch 1.1.0 and CUDA 10.0

**Comment by julclu** [comment]
I have the same problem; binary_cross_entropy_with_logits works, but binary_cross_entropy doesnt.

**Comment by ZaydH** [comment]
I have the same problem.  I even clamp the `input` tensor to the range [0,1] via the command `input = input.clamp(0,1)`.  However, I still get the error.  My specifications:

* Python 3.6.5
* PyTorch: 1.1.0
* CUDA: 9.1
* Tesla K80

**Comment by patricio-astudillo** [comment]
I have a similar problem and here is a reproducible example with the following frameworks:
- torch: 0.4.1
- Python: 2.7
- CUDA: 10.1

`a = torch.tensor([float('nan')])`
`b = torch.tensor([float(0.0)])`

for the 'device-side assert triggered' error:
`a = a.to('cuda')`
`b = b.to('cuda')`

`c = torch.nn.BSELoss()`
`c(a,b)`

if I don't push the tensors to a cuda device, I get the following error:
RuntimeError: Assertion `x >= 0. && x <= 1.' failed. input value should be between 0~1, but got nan at /pytorch/aten/src/THNN/generic/BCECriterion.c:62

with the following frameworks:
- torch: 1.2.0
- Python: 3.6
- CUDA: 10.1

`c(a,b)`
gives in both cases:
RuntimeError: Assertion `x >= 0. && x <= 1.' failed. input value should be between 0~1, but got nan at /pytorch/aten/src/THNN/generic/BCECriterion.c:62

**Comment by shirui-japina** [comment]
> See also: #2209
> 
> BCELoss accepts only inputs that have all elements in range [0; 1] but this condition doesn't hold in your case

I got the same error and I tried to use `nn.BCELoss()` like:

```
optimizer = optim.SGD(model.parameters(), lr=0.0001)
criterion = nn.BCELoss()
```

_loop epoch train part:_

```
prediction = model(batch_input)
loss = criterion(torch.sigmoid(prediction), label)

optimizer.zero_grad()
loss.backward()
optimizer.step()
```

Then I solved the problem. Thank you for your comment!
(But I don't know why optim.Adam() can't work well. It still errors: CUDA out of memory.)

**Comment by saeedalahmari3** [comment]
I had the same issue, after printing the values of softmax I found that some of them are nan. It turns out that I'm using Adam with `eps=0.0`. When I use the default value of `eps` it worked fine.

**Comment by shirui-japina** [comment]
> I had the same issue, after printing the values of softmax I found that some of them are nan. It turns out that I'm using Adam with `eps=0.0`. When I use the default value of `eps` it worked fine.

Maybe you need to set `eps>0.0`.
The reason is that in class [Adam()](https://pytorch.org/docs/master/_modules/torch/optim/adam.html#Adam), `def __init__ ()` will raise ValueError like `ValueError("Invalid epsilon value: {}".format(eps))`.
The code is here:
```
    def __init__(self, params, lr=1e-3, betas=(0.9, 0.999), eps=1e-8,
                 weight_decay=0, amsgrad=False):
        if not 0.0 <= lr:
            raise ValueError("Invalid learning rate: {}".format(lr))
        if not 0.0 <= eps:
            raise ValueError("Invalid epsilon value: {}".format(eps))
...
```

**Comment by sdhmdhr123** [comment]
same problem.

**Comment by fjchange** [comment]
> I had the same issue, after printing the values of softmax I found that some of them are nan. It turns out that I'm using Adam with `eps=0.0`. When I use the default value of `eps` it worked fine.

as @saeedalahmari3  said, set optimizer eps 0.0 or minus the fixed eps in labels can solve the problem.

**Comment by harshsha5** [comment]
This error still persists. I've used a softmax before the binary cross-entropy loss function. The code runs just fine for 18,000 iterations and then pops this error. Not sure why that happens.

**Comment by jimmycode** [comment]
Same problem still persist in torch 1.4.0. Can anyone fix this?

**Comment by cherepanovic** [comment]
are there some changes regarding this issue?

**Comment by matantsev** [comment]
Surprised that nobody hasn't mentioned, this error rises also either y_true or y_pred contains NaN values. You can check it via command torch.isnan(y).any()

**Comment by Charlene9698** [comment]
I am facing this problem as well. I checked many times that I have a sigmoid at the end of my network and my input images are also normalised from 0 to 255. It's extremely strange. Many of the epochs I don't face this but then it happens in epoch Xx and it's so frustrating. I have clip my gradients as well and it's still happening

**Comment by aaronzberger** [comment]
Can we reopen this issue, since I don't believe it's solved for everyone yet. I'm experiencing this issue as well.

**Comment by beibuwandeluori** [comment]
> I think it's a bug.
> I check my data, all is in range[0;1],but it happened.

maybe the numerical overflow
