### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by ggeo1992** [pytorch/pytorch#55736]
## 🐛 Bug

Hello,

I have an RTX 2070 GPU and I'm struggling for about 4 weeks to try and use it with pytorch.
I have tried different combinations of the offered binaries (pytorch nighlty + cuda10.2, pytorch nigthly + cuda11.1, pytorch installed from source + cuda 10.2, pytorch + cuda pip packages  , pytorch 1.9 installed from source + cuda 11.2) but ended up with the same result which I will describe in the next section.

Environment details:
1. Windows 10 19042.867
2. Nvidia Driver: 461.92
3. Cuda version: tried with both cuda 10.2 and cuda 11.2
4. cuDNN version: 8.1.133 (for cuda 11.2 attempt, i used the appropriate cuDNN)
5. Conda version:  4.10.0
6. Python versions: 3.8.8, 3.8.5
7. Torch versions: 1.8.1, 1.9 
## To Reproduce

1. Install pytorch with cuda support as described [here](https://pytorch.org/)
2.
```
>>> import torch
>>> x=torch.randn(1024, 1024).cuda() <---- this takes around 15-20 minutes to execute
>>> y = torch.matmult(x, x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`


<!-- If you have a code sample, error messages, stack traces, please provide it here as well -->

## Expected behavior

Expected behavior is for it to work.

## Environment

Collecting environment information...
PyTorch version: 1.9.0.dev20210409
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 461.92
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0.dev20210409
[pip3] torchaudio==0.9.0.dev20210409
[pip3] torchvision==0.10.0.dev20210409
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              h74a9793_1
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38h196d8e1_0
[conda] mkl_fft                   1.3.0            py38h46781fe_0
[conda] mkl_random                1.1.1            py38h47e9c7a_0
[conda] numpy                     1.19.2           py38hadc3359_0
[conda] numpy-base                1.19.2           py38ha3acd2a_0
[conda] pytorch                   1.9.0.dev20210409 py3.8_cuda10.2_cudnn7_0    pytorch-nightly
[conda] torchaudio                0.9.0.dev20210409            py38    pytorch-nightly
[conda] torchvision               0.10.0.dev20210409      py38_cu102    pytorch-nightly
## Additional context

I also tried building from source.  A desciption of the problems I faced is [here](https://discuss.pytorch.org/t/pytorch-cuda-11-2-build-from-source-runtimeerror-cuda-error-no-kernel-image-is-available-for-execution-on-the-device/116392)

Thank you in advance,

**Comment by peterjc123** [comment]
>  this takes around 15-20 minutes to execute

Do you want say `seconds` instead? Otherwise, it is crazy. Could you please show more details about your spec, e.g are you using a HDD? How much memory do you have?

**Comment by peterjc123** [comment]
BTW, I cannot find `torch.matmult` in my PyTorch installation. That's what I get when running your code.
```
AttributeError: module 'torch' has no attribute 'matmult'
```

**Comment by ggeo1992** [comment]
Hello @peterjc123 , thank you for replying.
Yes, _matmult_ was a typo, I apologize for that.
Regarding the time it takes to execute that instruction on the GPU, yes, it really takes that long (i really meant minutes). I forgot to mention that it takes this long only when first run on the python kernel. The succeeding instructions execute immediately.
I have run the following test:
```
import torch
from time import time

t = time()
x = torch.randn(1024, 1024).cuda()
print(x)
print('time={}'.format(time()-t))
y = torch.matmul(x, x)
print(y)

----------------
python .\test.py
tensor([[ 1.0558,  0.2174,  3.5354,  ...,  0.4834,  1.4344,  1.4402],
        [-0.6693, -0.3206,  0.9223,  ..., -0.3880,  0.8499, -0.5927],
        [-1.1885, -0.3269, -0.5373,  ...,  1.1715, -0.3991,  1.0818],
        ...,
        [ 0.7986, -0.4477, -0.6199,  ..., -0.2516,  1.5678,  0.9176],
        [ 2.4538, -0.0438,  0.2983,  ...,  0.1013,  2.2902,  1.3771],
        [ 1.5374,  0.4605, -1.0572,  ..., -1.1830,  0.4679,  1.6887]],
       device='cuda:0')
time=2187.4242935180664
Traceback (most recent call last):
  File ".\test.py", line 8, in <module>
    y = torch.matmul(x, x)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`


Regarding your question on my setup, the conda environment resides on an SSD which doesn't have any issues. Below, you cand find the output of msinfo32 on my PC:
 
```
OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	R2-D2
System Manufacturer	Gigabyte Technology Co., Ltd.
System Model	B85M-D3H
System Type	x64-based PC
System SKU	To be filled by O.E.M.
Processor	Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz, 3101 Mhz, 4 Core(s), 4 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. F15, 8/20/2015
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Gigabyte Technology Co., Ltd.
BaseBoard Product	B85M-D3H
BaseBoard Version	To be filled by O.E.M.
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.844"
Installed Physical Memory (RAM)	24.0 GB
Total Physical Memory	23.9 GB
Available Physical Memory	16.6 GB
Total Virtual Memory	27.4 GB
Available Virtual Memory	16.8 GB
Page File Space	3.50 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, DMA Protection
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not Modern Standby, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	
```

**Comment by peterjc123** [comment]
@ggeo1992 What is the output of `nvidia-smi -q`? BTW, does upgrading the GPU driver helps?

**Comment by ggeo1992** [comment]
> @ggeo1992 What is the output of `nvidia-smi -q`? BTW, does upgrading the GPU driver helps?
Please find the output below. Also, yes, i updated the nvidia driver 2 times while working on fixing this issue. Last time I used a clean install.

```C:\WINDOWS\system32>nvidia-smi -q

==============NVSMI LOG==============

Timestamp                                 : Tue Apr 13 10:56:47 2021
Driver Version                            : 465.89
CUDA Version                              : 11.3

Attached GPUs                             : 1
GPU 00000000:01:00.0
    Product Name                          : NVIDIA GeForce RTX 2070
    Product Brand                         : GeForce
    Display Mode                          : Enabled
    Display Active                        : Enabled
    Persistence Mode                      : N/A
    MIG Mode
        Current                           : N/A
        Pending                           : N/A
    Accounting Mode                       : Disabled
    Accounting Mode Buffer Size           : 4000
    Driver Model
        Current                           : WDDM
        Pending                           : WDDM
    Serial Number                         : N/A
    GPU UUID                              : GPU-2da518d3-e95b-41d0-5ec1-b3e4f76d5982
    Minor Number                          : N/A
    VBIOS Version                         : 90.06.3D.00.BD
    MultiGPU Board                        : No
    Board ID                              : 0x100
    GPU Part Number                       : N/A
    Inforom Version
        Image Version                     : G001.0000.02.04
        OEM Object                        : 1.1
        ECC Object                        : N/A
        Power Management Object           : N/A
    GPU Operation Mode
        Current                           : N/A
        Pending                           : N/A
    GPU Virtualization Mode
        Virtualization Mode               : None
        Host VGPU Mode                    : N/A
    IBMNPU
        Relaxed Ordering Mode             : N/A
    PCI
        Bus                               : 0x01
        Device                            : 0x00
        Domain                            : 0x0000
        Device Id                         : 0x1F0210DE
        Bus Id                            : 00000000:01:00.0
        Sub System Id                     : 0x3FDA1458
        GPU Link Info
            PCIe Generation
                Max                       : 3
                Current                   : 1
            Link Width
                Max                       : 16x
                Current                   : 16x
        Bridge Chip
            Type                          : N/A
            Firmware                      : N/A
        Replays Since Reset               : 0
        Replay Number Rollovers           : 0
        Tx Throughput                     : 5000 KB/s
        Rx Throughput                     : 4000 KB/s
    Fan Speed                             : 31 %
    Performance State                     : P8
    Clocks Throttle Reasons
        Idle                              : Active
        Applications Clocks Setting       : Not Active
        SW Power Cap                      : Not Active
        HW Slowdown                       : Not Active
            HW Thermal Slowdown           : Not Active
            HW Power Brake Slowdown       : Not Active
        Sync Boost                        : Not Active
        SW Thermal Slowdown               : Not Active
        Display Clock Setting             : Not Active
    FB Memory Usage
        Total                             : 8192 MiB
        Used                              : 691 MiB
        Free                              : 7501 MiB
    BAR1 Memory Usage
        Total                             : 256 MiB
        Used                              : 229 MiB
        Free                              : 27 MiB
    Compute Mode                          : Default
    Utilization
        Gpu                               : 2 %
        Memory                            : 5 %
        Encoder                           : 0 %
        Decoder                           : 0 %
    Encoder Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    FBC Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    Ecc Mode
        Current                           : N/A
        Pending                           : N/A
    ECC Errors
        Volatile
            SRAM Correctable              : N/A
            SRAM Uncorrectable            : N/A
            DRAM Correctable              : N/A
            DRAM Uncorrectable            : N/A
        Aggregate
            SRAM Correctable              : N/A
            SRAM Uncorrectable            : N/A
            DRAM Correctable              : N/A
            DRAM Uncorrectable            : N/A
    Retired Pages
        Single Bit ECC                    : N/A
        Double Bit ECC                    : N/A
        Pending Page Blacklist            : N/A
    Remapped Rows                         : N/A
    Temperature
        GPU Current Temp                  : 48 C
        GPU Shutdown Temp                 : 94 C
        GPU Slowdown Temp                 : 91 C
        GPU Max Operating Temp            : 89 C
        GPU Target Temperature            : 81 C
        Memory Current Temp               : N/A
        Memory Max Operating Temp         : N/A
    Power Readings
        Power Management                  : Supported
        Power Draw                        : 17.75 W
        Power Limit                       : 175.00 W
        Default Power Limit               : 175.00 W
        Enforced Power Limit              : 175.00 W
        Min Power Limit                   : 125.00 W
        Max Power Limit                   : 200.00 W
    Clocks
        Graphics                          : 300 MHz
        SM                                : 300 MHz
        Memory                            : 405 MHz
        Video                             : 540 MHz
    Applications Clocks
        Graphics                          : N/A
        Memory                            : N/A
    Default Applications Clocks
        Graphics                          : N/A
        Memory                            : N/A
    Max Clocks
        Graphics                          : 2100 MHz
        SM                                : 2100 MHz
        Memory                            : 7001 MHz
        Video                             : 1950 MHz
    Max Customer Boost Clocks
        Graphics                          : N/A
    Clock Policy
        Auto Boost                        : N/A
        Auto Boost Default                : N/A
    Processes
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 1300
            Type                          : C+G
            Name                          : Insufficient Permissions
            Used GPU Memory               : Not available in WDDM driver model
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 4288
            Type                          : C+G
            Name                          : C:\Program Files\WindowsApps\Microsoft.XboxGamingOverlay_5.521.3093.0_x64__8wekyb3d8bbwe\GameBar.exe
            Used GPU Memory               : Not available in WDDM driver model
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 5084
            Type                          : C+G
            Name                          : C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\InputApp\TextInputHost.exe
            Used GPU Memory               : Not available in WDDM driver model
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 6748
            Type                          : C+G
            Name                          : C:\Windows\explorer.exe
            Used GPU Memory               : Not available in WDDM driver model
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 7988
            Type                          : C+G
            Name                          : C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
            Used GPU Memory               : Not available in WDDM driver model
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 10512
            Type                          : C+G
            Name                          : C:\Windows\SystemApps\Microsoft.Windows.Search_cw5n1h2txyewy\SearchApp.exe
            Used GPU Memory               : Not available in WDDM driver model
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 11368
            Type                          : C+G
            Name                          : C:\Program Files\WindowsApps\Microsoft.YourPhone_1.21022.168.0_x64__8wekyb3d8bbwe\YourPhone.exe
            Used GPU Memory               : Not available in WDDM driver model
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 12432
            Type                          : C+G
            Name                          : C:\Program Files\NVIDIA Corporation\NVIDIA GeForce Experience\NVIDIA Share.exe
            Used GPU Memory               : Not available in WDDM driver model
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 12656
            Type                          : C+G
            Name                          : C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_10.2101.10.0_x64__8wekyb3d8bbwe\Calculator.exe
            Used GPU Memory               : Not available in WDDM driver model
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 13904
            Type                          : C+G
            Name                          : C:\Program Files\WindowsApps\Microsoft.WindowsStore_12101.1001.14.0_x64__8wekyb3d8bbwe\WinStore.App.exe
            Used GPU Memory               : Not available in WDDM driver model
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 14092
            Type                          : C+G
            Name                          : C:\Windows\ImmersiveControlPanel\SystemSettings.exe
            Used GPU Memory               : Not available in WDDM driver model
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 15028
            Type                          : C+G
            Name                          : C:\Program Files\WindowsApps\Microsoft.ZuneVideo_10.21021.10311.0_x64__8wekyb3d8bbwe\Video.UI.exe
            Used GPU Memory               : Not available in WDDM driver model
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 16304
            Type                          : C+G
            Name                          : C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.6.10571.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
            Used GPU Memory               : Not available in WDDM driver model
```

**Comment by ggeo1992** [comment]
Hmm..... It just hit me.... I don't know why _nvidia-smi_ says that I have cuda 11.3 since I currently should have cuda 10.2:
![image](https://user-images.githubusercontent.com/5611090/114518171-bf3d2a80-9c47-11eb-88cf-b7017e451ef5.png)

This is the version.txt file from my cuda install location: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
```CUDA Version 10.2.89```

**Comment by peterjc123** [comment]
> Hmm..... It just hit me.... I don't know why _nvidia-smi_ says that I have cuda 11.3 since I currently should have cuda 10.2:
> ![image](https://user-images.githubusercontent.com/5611090/114518171-bf3d2a80-9c47-11eb-88cf-b7017e451ef5.png)
> 
> This is the version.txt file from my cuda install location: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
> `CUDA Version 10.2.89`

Don't worry. The CUDA version field in nvidia-smi refers to the CUDA version that your driver can support.

**Comment by peterjc123** [comment]
https://github.com/NVIDIA/cuda-samples/tree/master/Samples/matrixMul Could you please try whether this sample project works on your machine?

**Comment by ggeo1992** [comment]
Hello, 
Tried this as well in the past and it worked. I will try it again and show you the output:
```
1>------ Rebuild All started: Project: matrixMul, Configuration: Debug x64 ------
1>Compiling CUDA source file matrixMul.cu...
1>
1>C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.2\0_Simple\matrixMul>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_37,code=\"sm_37,compute_37\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64" -x cu  -I./ -I../../common/inc -I./ -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\/include" -I../../common/inc -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static -Xcompiler "/wd 4819" -g   -DWIN32 -DWIN32 -D_MBCS -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64/Debug/vc142.pdb /FS /Zi /RTC1 /MTd " -o x64/Debug/matrixMul.cu.obj "C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.2\0_Simple\matrixMul\matrixMul.cu"
1>matrixMul.cu
1>LINK : ..\..\bin\win64\Debug\\matrixMul.exe not found or not built by the last incremental link; performing full link
1>   Creating library ../../bin/win64/Debug/matrixMul.lib and object ../../bin/win64/Debug/matrixMul.exp
1>matrixMul_vs2019.vcxproj -> C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.2\0_Simple\matrixMul\../../bin/win64/Debug/matrixMul.exe
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```
And this is the output of the program:
```
[Matrix Multiply Using CUDA] - Starting...
GPU Device 0: "Turing" with compute capability 7.5

MatrixA(320,320), MatrixB(640,320)
Computing result using CUDA Kernel...
done
Performance= 774.85 GFlop/s, Time= 0.169 msec, Size= 131072000 Ops, WorkgroupSize= 1024 threads/block
Checking computed result for correctness: Result = PASS

NOTE: The CUDA Samples are not meant for performancemeasurements. Results may vary when GPU Boost is enabled.

C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.2\0_Simple\matrixMul\../../bin/win64/Release/matrixMul.exe (process 7948) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

**Comment by peterjc123** [comment]
Well, then it means building locally should be working fine. As for your original question (first cuda call is slow), I guess you can try debugging by compiling a program with a similar call in LibTorch.

**Comment by compwiztobe** [comment]
Possible duplicate of #53336.  Resolved and closed.
