### ISSUE TITLE
Matrix multiplication broken on PyTorch 1.8.1 with CUDA 11.1 and Nvidia GTX 1080 Ti

### ISSUE THREAD

**Issue by JayThomason** [pytorch/pytorch#56747]
## 🐛 Bug

Matrix multiplication does not work properly on Torch 1.8.1 with CUDA 11.1 when running on a 1080Ti with 460 or 465 Nvidia drivers.

## To Reproduce

1. Save this test script as test.py:
```python
import torch

def matmul_test(mat_a, mat_b, dtype, device):
    print("matmul_test -- ", dtype, device)
    a = torch.tensor(mat_a, dtype=dtype, device=device,)
    b = torch.tensor(mat_b, dtype=dtype, device=device,)
    c = torch.matmul(b, a)
    print("ba:\n", c)

print("torch version: ", torch.__version__)
a, b = [[1, 2]], [[3], [4]]
print("a:", a, "\nb:", b)
matmul_test(a, b, torch.float16, torch.device("cpu"))
matmul_test(a, b, torch.float16, torch.device("cuda"))
matmul_test(a, b, torch.float32, torch.device("cuda"))
matmul_test(a, b, torch.float64, torch.device("cuda"))
matmul_test(a, b, torch.float16, torch.device("cuda"))
```

2. Save this Dockerfile in the same directory and build it with `docker build . -t torch_test`

```Dockerfile
FROM nvidia/cuda:11.2.1-devel-ubuntu18.04
RUN apt update && apt install -y python3-pip python3.7
RUN python3.7 -m pip install torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
COPY test.py test.py
ENV PYTHONUNBUFFERED=1gg
ENTRYPOINT python3.7 test.py
```

3. Run the test script with `docker run torch_test`

## Expected behavior

When running this on a machine with a 1080Ti with recent drivers the output will look something like:
```bash
torch version:  1.8.1+cu111
a: [[1, 2]]
b: [[3], [4]]
matmul_test --  torch.float16 cpu
ba:
 tensor([[3., 6.],
        [4., 8.]], dtype=torch.float16)
matmul_test --  torch.float16 cuda
ba:
 tensor([[3., 6.],
        [4., 8.]], device='cuda:0', dtype=torch.float16)
matmul_test --  torch.float32 cuda
ba:
 tensor([[  8208.5000, 131344.0000],
        [     0.0000,      0.0000]], device='cuda:0')
matmul_test --  torch.float64 cuda
ba:
 tensor([[6.9186e+38, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]], device='cuda:0', dtype=torch.float64)
matmul_test --  torch.float16 cuda
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    matmul_test(a, b, torch.float16, torch.device("cuda"))
  File "test.py", line 8, in matmul_test
    c = torch.matmul(b, a)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
```

Notably torch.float16 seems to work if you adjust test.py to just repeatedly do float16 matrix multiplications however float32 and float64 immediately have problems.

#### However, if you run this exact same test on other GPUs it will work perfectly. For example when running this test with a Quadro RTX 6000 it works as expected:
```
torch version:  1.8.1+cu111
a: [[1, 2]]
b: [[3], [4]]
matmul_test --  torch.float16 cpu
ba:
 tensor([[3., 6.],
        [4., 8.]], dtype=torch.float16)
matmul_test --  torch.float16 cuda
ba:
 tensor([[3., 6.],
        [4., 8.]], device='cuda:0', dtype=torch.float16)
matmul_test --  torch.float32 cuda
ba:
 tensor([[3., 6.],
        [4., 8.]], device='cuda:0')
matmul_test --  torch.float64 cuda
ba:
 tensor([[3., 6.],
        [4., 8.]], device='cuda:0', dtype=torch.float64)
matmul_test --  torch.float16 cuda
ba:
 tensor([[3., 6.],
        [4., 8.]], device='cuda:0', dtype=torch.float16)
```

#### Furthermore if you change the torch install in the Dockerfile to use CUDA 10.2 it also works fine.

I have also tried using nightly builds with CUDA 11.1, 11.2, and 11.3 and all of them had the same problem. I have tried using both 460 and 465 drivers and cuda 11.2 and 11.3 on the host with the same problem. So far the only fix I have seen is to use CUDA 10.2 and unfortunately this is not an option for us.

## Environment

collect_env output from host machine:
```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce GTX 1080 Ti
GPU 3: NVIDIA GeForce GTX 1080 Ti
GPU 4: NVIDIA GeForce GTX 1080 Ti
GPU 5: NVIDIA GeForce GTX 1080 Ti
GPU 6: NVIDIA GeForce GTX 1080 Ti
GPU 7: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 465.19.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.14.0
[pip] numpydoc==0.7.0
[conda] mkl                       2018.0.1             h19d6760_4
[conda] mkl-service               1.1.2            py36h17a0993_4
[conda] numpy                     1.14.0           py36h3dfced4_1
[conda] numpydoc                  0.7.0            py36h18f165f_0
```

inside of the docker container:
```
root@b654cf42e515:/# python3.7 collect_env.py
Collecting environment information...
PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.2.152
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce GTX 1080 Ti
GPU 3: NVIDIA GeForce GTX 1080 Ti
GPU 4: NVIDIA GeForce GTX 1080 Ti
GPU 5: NVIDIA GeForce GTX 1080 Ti
GPU 6: NVIDIA GeForce GTX 1080 Ti
GPU 7: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 465.19.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

## Related tickets

I don't know for sure but it is possible that this is related to:
* https://github.com/pytorch/pytorch/issues/54799
* https://github.com/pytorch/pytorch/issues/54975

Although those tickets already existed it seems that folks have had trouble reproducing them which is why I opened this ticket.

## Additional context

I do not know whether this is specific to the 1080Ti or all Pascal GPUs.

Please let me know if you need any help reproducing this issue because I tried to make this easy to reproduce.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @csarofeen @ptrblck @xwang233

**Comment by dementrock** [comment]
This issue has also been impacting our team. Would be great to have it resolved!

**Comment by pzqian** [comment]
Same here - hit a similar issue and we had to put our Pytorch upgrade on hold.

**Comment by imaginary-person** [comment]
It seems @ptrblck might be able to help.

**Comment by ptrblck** [comment]
Thanks for reporting this issue @JayThomason!
I'm able to reproduce this issue using the pip wheels with CUDA11.1 and the workload works using the conda binaries.

@malfet I guess we might run into a similar issue as with `sm_70`, `sm_75` in `1.8.0`, but this time it seems to be a bit different, since `sm_61` is missing in the pip wheels, but the error is also raised on a P100, which is `sm_60` (and is included in the wheels).
I'm also unable to let a standalone FP16 matmul crash by pruning the static cublas and cublasLt libs.

**Comment by JayThomason** [comment]
> the workload works using the conda binaries

By this do you mean it also reproduces with the conda binaries or do you mean it does not reproduce with the conda binaries?

**Comment by malfet** [comment]
> By this do you mean it also reproduces with the conda binaries or do you mean it does not reproduce with the conda binaries?

Conda likely shouldn't be effected, as dynamic linking is used there.

**Comment by ptrblck** [comment]
As @malfet said: the conda binaries do not reproduce the issue and work correctly.

**Comment by JayThomason** [comment]
Unfortunately I am unable to install the cuda 11 torch package using conda because it detects the cuda version of the host instead of the cuda version installed in the docker image (for example where the host cuda version is 11.3 whereas the container is 11.1).

**Comment by ptrblck** [comment]
The conda `cudatoolkit` package shouldn't check any host CUDA toolkit installations and I'm able to install it in different containers (ranging from CUDA11.0 to 11.3). Feel free to create a topic in the [forum](https://discuss.pytorch.org/) (and tag me) in case you have trouble installing the conda binaries in a container to keep this issue focused on the pip wheel error.

**Comment by ezyang** [comment]
@ngimel says this looks like a static linking problem again; since it works with conda (not statically linked) but pip (statically linked).

**Comment by theevann** [comment]
Same issue here. This is quite critical !
I have tested on Tesla P40, Titan RTX and GTX 1080 and all are impacted, but V-100s seem to work fine.
Hope to see a fix soon !

**Comment by EricCousineau-TRI** [comment]
Howdy! My coworker (@kunimatsu-tri) and I also ran into this issue, we're just using the `pip` build (`torch-1.8.0+cu111` + `torch-1.8.1+cu111`, CPython 3.6, 64-bit Linux).

Any chance this is an upstream CUDA issue? (e.g. static linking issue not specific to PyTorch?)

**Comment by kunimatsu-tri** [comment]
Just to add hardware information to the post right above, it passed on Titan RTX but failed on Titan Xp.

**Comment by ecm200** [comment]
I have come across this issue as well.
I have created two virtual environments, one which mainly has CONDA installed dependencies, and the other PIP installed dependencies.

I executed a training of a ResNet50 Torchvision model in both environments. The CONDA installed environment iterates and completes as expected, however the PIP installed version errors after the first iteration with the error shown below.

Any news on a potential fix for the PIP installation procedure?

# Environments

## Conda installed
```bash
Collecting environment information...
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.10 (x86_64)
GCC version: (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla P40
Nvidia driver version: 455.32.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] pytorch-ignite==0.4.4
[pip3] pytorchcv==0.0.65
[pip3] torch==1.8.1
[pip3] torch-lucent==0.1.8
[pip3] torchaudio==0.8.0a0+e4e171a
[pip3] torchvision==0.9.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] ignite                    0.4.4                      py_0    pytorch
[conda] mkl                       2021.2.0           h06a4308_296
[conda] mkl-service               2.3.0            py38h27cfd23_1
[conda] mkl_fft                   1.3.0            py38h42c9631_2
[conda] mkl_random                1.2.1            py38ha9443f7_2
[conda] numpy                     1.20.2           py38h2d18471_0
[conda] numpy-base                1.20.2           py38hfae3a4d_0
[conda] pytorch                   1.8.1           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] pytorchcv                 0.0.65                   pypi_0    pypi
[conda] torch-lucent              0.1.8                    pypi_0    pypi
[conda] torchaudio                0.8.1                      py38    pytorch
[conda] torchvision               0.9.1                py38_cu111    pytorch
```
## PIP installed
```bash
Collecting environment information...
PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.10 (x86_64)
GCC version: (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla P40
Nvidia driver version: 455.32.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] pytorch-ignite==0.4.4
[pip3] pytorchcv==0.0.65
[pip3] torch==1.8.1+cu111
[pip3] torch-lucent==0.1.8
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1+cu111
[conda] numpy                     1.20.2                   pypi_0    pypi
[conda] pytorch-ignite            0.4.4                    pypi_0    pypi
[conda] pytorchcv                 0.0.65                   pypi_0    pypi
[conda] torch                     1.8.1+cu111              pypi_0    pypi
[conda] torch-lucent              0.1.8                    pypi_0    pypi
[conda] torchaudio                0.8.1                    pypi_0    pypi
[conda] torchvision               0.9.1+cu111              pypi_0    pypi
```

# Error on execution of PIP installed environment

```bash
[INFO] Executing model training...
Epoch: 0001  TrAcc: 0.238 ValAcc: 0.005 TrPrec: 0.341 ValPrec: 0.000 TrRec: 0.238 ValRec: 0.005 TrF1: 0.203 ValF1: 0.000 TrTopK: 0.551 ValTopK: 0.025 TrLoss: 3.705 ValLoss: 5.298
Current run is terminating due to exception: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([16, 128, 28, 28], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(128, 128, kernel_size=[3, 3], padding=[1, 1], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_FLOAT
    padding = [1, 1, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x562fcc812170
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 16, 128, 28, 28,
    strideA = 100352, 784, 28, 1,
output: TensorDescriptor 0x562fcc7868b0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 16, 128, 28, 28,
    strideA = 100352, 784, 28, 1,
weight: FilterDescriptor 0x562f60eac190
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 128, 128, 3, 3,
Pointer addresses:
    input: 0x7f1d1e620000
    output: 0x7f1d1ec40000
    weight: 0x7f1d86ec0000
Forward algorithm: 7

Engine run is terminating due to exception: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([16, 128, 28, 28], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(128, 128, kernel_size=[3, 3], padding=[1, 1], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_FLOAT
    padding = [1, 1, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x562fcc812170
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 16, 128, 28, 28,
    strideA = 100352, 784, 28, 1,
output: TensorDescriptor 0x562fcc7868b0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 16, 128, 28, 28,
    strideA = 100352, 784, 28, 1,
weight: FilterDescriptor 0x562f60eac190
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 128, 128, 3, 3,
Pointer addresses:
    input: 0x7f1d1e620000
    output: 0x7f1d1ec40000
    weight: 0x7f1d86ec0000
Forward algorithm: 7

Traceback (most recent call last):
  File "local_train_clearml_pytorch_ignite_caltech_birds.py", line 104, in <module>
    trainer.run()
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/cub_tools/trainer.py", line 640, in run
    self.train_engine.run(self.train_loader, max_epochs=self.config.TRAIN.NUM_EPOCHS)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/ignite/engine/engine.py", line 702, in run
    return self._internal_run()
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/ignite/engine/engine.py", line 775, in _internal_run
    self._handle_exception(e)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/ignite/engine/engine.py", line 469, in _handle_exception
    raise e
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/ignite/engine/engine.py", line 745, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/ignite/engine/engine.py", line 850, in _run_once_on_dataset
    self._handle_exception(e)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/ignite/engine/engine.py", line 469, in _handle_exception
    raise e
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/ignite/engine/engine.py", line 833, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/cub_tools/trainer.py", line 448, in train_step
    y_pred = self.model(x)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/torchvision/models/resnet.py", line 249, in forward
    return self._forward_impl(x)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/torchvision/models/resnet.py", line 238, in _forward_impl
    x = self.layer2(x)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/torchvision/models/resnet.py", line 128, in forward
    out = self.conv2(out)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([16, 128, 28, 28], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(128, 128, kernel_size=[3, 3], padding=[1, 1], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_FLOAT
    padding = [1, 1, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x562fcc812170
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 16, 128, 28, 28,
    strideA = 100352, 784, 28, 1,
output: TensorDescriptor 0x562fcc7868b0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 16, 128, 28, 28,
    strideA = 100352, 784, 28, 1,
weight: FilterDescriptor 0x562f60eac190
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 128, 128, 3, 3,
Pointer addresses:
    input: 0x7f1d1e620000
    output: 0x7f1d1ec40000
    weight: 0x7f1d86ec0000
Forward algorithm: 7

^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/clearml/task.py", line 2878, in _at_exit
    self.__shutdown()
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/clearml/task.py", line 3053, in __shutdown
    BackgroundMonitor.wait_for_sub_process()
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/clearml/utilities/process/mp.py", line 431, in wait_for_sub_process
    sleep(0.03)
  File "/home/edmorris/.conda/envs/py38_pytorch18_pip/lib/python3.8/site-packages/clearml/task.py", line 3152, in signal_handler
    return org_handler if not callable(org_handler) else org_handler(sig, frame)
KeyboardInterrupt
Segmentation fault (core dumped)
```

**Comment by GoingMyWay** [comment]
Same problem

```
 "RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`\n"
```

**Comment by kajetanj** [comment]
Could someone put a link to this issue in version 1.8 / 1.8.1 release notes? Right now it seems that 1.8 LTS is the most stable / reliable version one could go for.

**Comment by UestcJay** [comment]
Same problem. And have not solved.

**Comment by blackmamba1122** [comment]
Same problem,
I got the UserWarning when i try to training tacotron2 with ljspeech. the warning is as below:

```
/media/DATA-2/TTS/coqui/TTS/TTS/tts/models/tacotron2.py:341: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  alignment_lengths = mel_lengths // self.decoder.r
```

and after epoch 8/1000 in step 1886/3243 i got error like this:

```
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

Is that the cause of the error? how to handle it?


### Environment
{
"CUDA": {
"GPU": [
"NVIDIA GeForce GTX 1660 Ti"
],
"available": true,
"version": "10.2"
},
"Packages": {
"PyTorch_debug": false,
"PyTorch_version": "1.11.0+cu102",
"TTS": "0.6.1",
"numpy": "1.19.5"
},
"System": {
"OS": "Linux",
"architecture": [
"64bit",
"ELF"
],
"processor": "x86_64",
"python": "3.8.0",
"version": "https://github.com/coqui-ai/TTS/discussions/118~18.04.1-Ubuntu SMP Thu Mar 3 13:53:15 UTC 2022"
}
}

### Additional context
I've reduced the batch size, currently I'm using batch size = 4. Is this also caused by reducing the batch size? But if it's not reduced it will be OOM.

**Comment by gsanya** [comment]
Same problem with the 1080ti but on torch 1.8.0.
I run it in a docker container, installed pytorch with pip and the matmul and bmm and @ produce different (and all wrong) results.
The same container produces the right results on 3080.
Also it worked with conda install on the 1080ti.

**Comment by bring-nirachornkul** [comment]
Have this problem too. Not solve yet.

GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...
(gdb) run
Starting program: /home/glassman555/miniconda3/envs/human3d/bin/python3 main.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007fffb1d220b5 in c10::detail::infer_schema::(anonymous namespace)::createArgumentVector(c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>) () from /home/glassman555/miniconda3/envs/human3d/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so

**Comment by malfet** [comment]
@bring-nirachornkul your backtrace does not feel related, please feel free to file a separate issue and provide details necessary for reproduction?

**Comment by nkalpakis21** [comment]
i see this has been open for awhile. is there trouble getting a dev to fix this issue? what is blocking this for so long

**Comment by ngimel** [comment]
This issue has been fixed long ago, please open new issues with repro instructions if you encounter some errors.
