### ISSUE TITLE
Problems when using a100 graphics card

### ISSUE THREAD

**Issue by Foreist** [pytorch/pytorch#57922]
UserWarning:
A100-SXM4-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.

When running a100 server, should I only use images provided by nvidia?
Can't I install torch myself?

**Comment by peterjc123** [comment]
You'll need the binaries that is built with CUDA > 11.0.

**Comment by Foreist** [comment]
> You'll need the binaries that is built with CUDA > 11.0.
I am already using Cuda 11.

**Comment by skyline75489** [comment]
Which version of PyTorch are you using?

**Comment by peterjc123** [comment]
@Foreist Would you please share the result of the command `python -m torch.utils.collect_env`?

**Comment by Foreist** [comment]
@peterjc123 @skyline75489 
Collecting environment information...
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: A100-SXM4-40GB
  MIG 3g.20gb Device 0:

Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.8.1
[pip3] torch-cluster==1.5.9
[pip3] torch-scatter==2.0.6
[pip3] torch-sparse==0.6.9
[pip3] torch-spline-conv==1.2.1
[conda] Could not collect

I installed torch with pip install torch because conda is currently not available, but cuda comes out as 102...

**Comment by Foreist** [comment]
I solved it.
pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by b3r-prog** [comment]
@Foreist what if i need to install a torch version greater 1.10?

**Comment by rfmiotto** [comment]
@b3r-prog, you can specify torch and cuda versions during build time as:
```
pip install torch==1.12.1+cu113 -f https://download.pytorch.org/whl/torch_stable.html
```
Then, if you run `python3 -m torch.utils.collect_env`, you should see a some information and this line:
(...)
<em>CUDA used to build PyTorch: 11.3</em>
(...)
