### ISSUE TITLE
untimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:32, unhandled cuda error, NCCL version 2.4.8

### ISSUE THREAD

**Issue by rkoystart** [pytorch/pytorch#58177]
## 🐛 Bug

i am not able to train a transformer model for the following command:

fairseq-train processed_paracrawl_wmt/ --arch transformer --share-all-embeddings --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000 --lr 0.0007 --min-lr 1e-09 --dropout 0.1 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 8000 --update-freq 16 --save-dir experiments/transformer_base_paracrawl_wmt_fr/ --no-progress-bar --ddp-backend=no_c10d --source-lang en --target-lang fr --max-epoch 40 --tensorboard-logdir logs/fr/ --fp16 --log-interval 1000

when i run the above command i get the following error:
```
 distributed init (rank 0): tcp://localhost:13357                                                                                                                                                         
| distributed init (rank 1): tcp://localhost:13357                                                                                                                                                         
| initialized host 104-171-200-210 as rank 1                                                                                                                                                               
| initialized host 104-171-200-210 as rank 0                                                                                                                                                               
104-171-200-210:62235:62235 [0] NCCL INFO Bootstrap : Using [0]enp1s0:104.171.200.210<0>                                                                                                                   
104-171-200-210:62235:62235 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).                                                                                                                   
104-171-200-210:62235:62235 [0] NCCL INFO NET/IB : No device found.                                                                                                                                        
104-171-200-210:62235:62235 [0] NCCL INFO NET/Socket : Using [0]enp1s0:104.171.200.210<0>                                                                                                                  
NCCL version 2.4.8+cuda10.2                                                                                                                                                                                
104-171-200-210:62236:62236 [1] NCCL INFO Bootstrap : Using [0]enp1s0:104.171.200.210<0>                                                                                                                   
104-171-200-210:62236:62236 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).                                                                                                                   
104-171-200-210:62236:62236 [1] NCCL INFO NET/IB : No device found.                                                                                                                                        
104-171-200-210:62236:62236 [1] NCCL INFO NET/Socket : Using [0]enp1s0:104.171.200.210<0>                                                                                                                  
104-171-200-210:62235:62930 [0] NCCL INFO Setting affinity for GPU 0 to 0fffffff                                                                                                                           
104-171-200-210:62236:62931 [1] NCCL INFO Setting affinity for GPU 1 to 0fffffff                                                                                                                           
104-171-200-210:62235:62930 [0] NCCL INFO Channel 00 :    0   1                                                                                                                                            
104-171-200-210:62235:62930 [0] NCCL INFO Channel 01 :    0   1                                                                                                                                            
104-171-200-210:62235:62930 [0] NCCL INFO Channel 02 :    0   1                                                                                                                                            
104-171-200-210:62235:62930 [0] NCCL INFO Channel 03 :    0   1                                                                                                                                            
104-171-200-210:62235:62930 [0] NCCL INFO Channel 04 :    0   1                                                                                                                                            
104-171-200-210:62235:62930 [0] NCCL INFO Channel 05 :    0   1                                                                                                                                            
104-171-200-210:62235:62930 [0] NCCL INFO Channel 06 :    0   1                                                                                                                                            
104-171-200-210:62235:62930 [0] NCCL INFO Channel 07 :    0   1                                                                                                                                            
104-171-200-210:62235:62930 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via P2P/IPC                                                                                                                               
104-171-200-210:62236:62931 [1] NCCL INFO Ring 00 : 1[1] -> 0[0] via P2P/IPC                                                                                                                               
104-171-200-210:62236:62931 [1] NCCL INFO Ring 01 : 1[1] -> 0[0] via P2P/IPC                                                                                                                               
104-171-200-210:62235:62930 [0] NCCL INFO Ring 01 : 0[0] -> 1[1] via P2P/IPC                                                                                                                               
104-171-200-210:62236:62931 [1] NCCL INFO Ring 02 : 1[1] -> 0[0] via P2P/IPC                                                                                                                               
104-171-200-210:62235:62930 [0] NCCL INFO Ring 02 : 0[0] -> 1[1] via P2P/IPC                                                                                                                               
104-171-200-210:62236:62931 [1] NCCL INFO Ring 03 : 1[1] -> 0[0] via P2P/IPC                                                                                                                               
104-171-200-210:62235:62930 [0] NCCL INFO Ring 03 : 0[0] -> 1[1] via P2P/IPC                                                                                                                               
104-171-200-210:62236:62931 [1] NCCL INFO Ring 04 : 1[1] -> 0[0] via P2P/IPC                                                                                                                               
104-171-200-210:62235:62930 [0] NCCL INFO Ring 04 : 0[0] -> 1[1] via P2P/IPC                                                                                                                               
104-171-200-210:62235:62930 [0] NCCL INFO Ring 05 : 0[0] -> 1[1] via P2P/IPC
104-171-200-210:62236:62931 [1] NCCL INFO Ring 05 : 1[1] -> 0[0] via P2P/IPC

104-171-200-210:62235:62930 [0] NCCL INFO Ring 06 : 0[0] -> 1[1] via P2P/IPC
104-171-200-210:62236:62931 [1] NCCL INFO Ring 06 : 1[1] -> 0[0] via P2P/IPC
104-171-200-210:62235:62930 [0] NCCL INFO Ring 07 : 0[0] -> 1[1] via P2P/IPC
104-171-200-210:62236:62931 [1] NCCL INFO Ring 07 : 1[1] -> 0[0] via P2P/IPC
104-171-200-210:62235:62930 [0] NCCL INFO Using 256 threads, Min Comp Cap 8, Trees disabled
104-171-200-210:62235:62930 [0] NCCL INFO comm 0x7fe75c0024c0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 - Init COMPLETE
104-171-200-210:62236:62931 [1] NCCL INFO comm 0x7f3acc0024c0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 - Init COMPLETE
104-171-200-210:62235:62235 [0] NCCL INFO Launch mode Parallel

104-171-200-210:62236:62236 [1] enqueue.cc:197 NCCL WARN Cuda failure 'invalid device function'
104-171-200-210:62236:62236 [1] NCCL INFO misc/group.cc:148 -> 1

104-171-200-210:62235:62235 [0] enqueue.cc:197 NCCL WARN Cuda failure 'invalid device function'
104-171-200-210:62235:62235 [0] NCCL INFO misc/group.cc:148 -> 1
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/translation/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/home/ubuntu/anaconda3/envs/translation/lib/python3.8/site-packages/fairseq_cli/train.py", line 314, in cli_main
    torch.multiprocessing.spawn(
  File "/home/ubuntu/anaconda3/envs/translation/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ubuntu/anaconda3/envs/translation/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/ubuntu/anaconda3/envs/translation/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/translation/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/ubuntu/anaconda3/envs/translation/lib/python3.8/site-packages/fairseq_cli/train.py", line 284, in distributed_main
    main(args, init_distributed=True)
  File "/home/ubuntu/anaconda3/envs/translation/lib/python3.8/site-packages/fairseq_cli/train.py", line 33, in main
    args.distributed_rank = distributed_utils.distributed_init(args)
  File "/home/ubuntu/anaconda3/envs/translation/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 90, in distributed_init
    dist.all_reduce(torch.rand(1).cuda())
  File "/home/ubuntu/anaconda3/envs/translation/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 898, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:32, unhandled cuda error, NCCL version 2.4.8

```

## Expected behavior
 normal training must have started .

 - PyTorch Version: 1.5.1
 - fairseq Version: 0.8.0
 - OS : ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: Build cuda_11.1.TC455_06.29190527_0
 - GPU models and configuration: rtx 6000
 - Any other relevant information:

Please let me know the mistake i have done or missed out anything

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by SciPioneer** [comment]
I saw you used PyTorch 1.5, while the latest version is 1.8. (The latest fairseq version is 0.10 now.)

Can you try a newer version which may already have some fixes?

Please also set `NCCL_DEBUG=INFO` for more debugging info. Thanks!

**Comment by rkoystart** [comment]
upgrading the torch version 1.8.0 worked. Thanks @SciPioneer

**Comment by rbareja25** [comment]
That solves the error, but pytorch data loader batches behave very differently and give different results
