### ISSUE TITLE
Not linked to libcudart.so.9.1 in conda installation.

### ISSUE THREAD

**Issue by 0h-n0** [pytorch/pytorch#5897]
Hi, pytorch developers

Thank you for developing one of the greatest deep learning framework.

I found the following error, after conda installation. 
```
conda install pytorch torchvision cuda91 -c pytorch
```
And then,  I run  an easy code,
```
Traceback (most recent call last):
    import torch
  File "/home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
```
There is libcudart-fc1f7f84.so.9.1 in lib directory, but it is not linked.

* conda information

```pytorch-0.3.1-py36_cuda9.1.85_cudnn7.0.5_2.json  
{
  "arch": "x86_64",
  "auth": null,
  "build": "py36_cuda9.1.85_cudnn7.0.5_2",
  "build_number": 2,
  "channel": "https://conda.anaconda.org/pytorch/linux-64",
  "depends": [
    "cffi",
    "mkl >=2018",
    "numpy >=1.11",
    "python >=3.6,<3.7.0a0"
  ],
 "features": "cuda91",
  "files": [
      ...
   ],
  "fn": "pytorch-0.3.1-py36_cuda9.1.85_cudnn7.0.5_2.tar.bz2",
  "has_prefix": false,
  "license": "BSD 3-Clause",
  "license_family": "BSD",
  "link": {
    "source": "/home/kono/miniconda/pkgs/pytorch-0.3.1-py36_cuda9.1.85_cudnn7.0.5_2",
    "type": 1
  },
  "md5": "c957d7b9cd70414ccae81b3db8363d86",
  "name": "pytorch",
  "noarch": null,
  "platform": "linux",
  "preferred_env": null,
  "priority": 0,
  "requires": [],
  "schannel": "pytorch",
  "size": 498099284,
  "subdir": "linux-64",
  "timestamp": 1518246118790,
  "url": "https://conda.anaconda.org/pytorch/linux-64/pytorch-0.3.1-py36_cuda9.1.85_cudnn7.0.5_2.tar.bz2",
  "version": "0.3.1",
  "with_features_depends": {}
}
```
* check libraries

```
 ldd _C.cpython-36m-x86_64-linux-gnu.so                                                                                                                                                      [kono@pc]
	linux-vdso.so.1 =>  (0x00007ffc226b0000)
	libshm.so => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libshm.so (0x00007f642bfc0000)
	libcudart-fc1f7f84.so.9.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libcudart-fc1f7f84.so.9.1 (0x00007f642bd4f000)
	libnvToolsExt-3965bdd0.so.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libnvToolsExt-3965bdd0.so.1 (0x00007f642bb44000)
	libcudnn-7a90c013.so.7 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libcudnn-7a90c013.so.7 (0x00007f641abb0000)
	libTH.so.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libTH.so.1 (0x00007f641a5ae000)
	libTHS.so.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libTHS.so.1 (0x00007f641a37b000)
	libTHNN.so.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libTHNN.so.1 (0x00007f641a035000)
	libATen.so.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libATen.so.1 (0x00007f641978e000)
	libTHC.so.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libTHC.so.1 (0x00007f640cb30000)
	libTHCS.so.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libTHCS.so.1 (0x00007f640c7ae000)
	libTHCUNN.so.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libTHCUNN.so.1 (0x00007f6408a31000)
	libnccl.so.1 => /home/kono/Downloads/nccl-master/build/lib/libnccl.so.1 (0x00007f64081c5000)
	libgcc_s.so.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./../../../libgcc_s.so.1 (0x00007f6407fb3000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6407d6b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f64079a9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f642dfaf000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f64077a1000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f640749f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f640729a000)
	libstdc++.so.6 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/../../../../libstdc++.so.6 (0x00007f6406f60000)
	libmkl_gf_lp64.so => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/../../../../libmkl_gf_lp64.so (0x00007f6406479000)
	libmkl_gnu_thread.so => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/../../../../libmkl_gnu_thread.so (0x00007f6404dbb000)
	libmkl_core.so => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/../../../../libmkl_core.so (0x00007f6402c28000)
	libgomp.so.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/../../../../libgomp.so.1 (0x00007f6402a04000)
	libcublas-a49371b9.so.9.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libcublas-a49371b9.so.9.1 (0x00007f63ff469000)
	libcurand-26c1d800.so.9.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libcurand-26c1d800.so.9.1 (0x00007f63fb4e4000)
	libcusparse-b2167406.so.9.1 => /home/kono/miniconda/envs/test/lib/python3.6/site-packages/torch/./lib/libcusparse-b2167406.so.9.1 (0x00007f63f7e09000)
	libcudart.so.8.0 => not found

```

**Comment by soumith** [comment]
the problem comes with `home/kono/Downloads/nccl-master/build/lib/libnccl.so.`. It is your own nccl, you have this in your `$LD_LIBRARY_PATH`, I think, and it is linking against `libcudart.so.8.0`.

Run:
```
unset LD_LIBRARY_PATH
```
that should fix things.

**Comment by 0h-n0** [comment]
Thank you for quick reply. I solved the problem and close this issue.
