### ISSUE TITLE
1.9.0.dev20210603+cu113 crashes HF transformers

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#59384]
## 🐛 Bug

pt-nightly crashes HF transformers - most tests

```
pytest tests/test_trainer.py -rA -sv
2021-06-03 10:25:40.346108: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Test session starts (platform: linux, Python 3.8.5, pytest 6.2.2, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /home/stas/hf/transformers-master
plugins: forked-1.3.0, xdist-2.2.0, sugar-0.9.4, instafail-0.4.2
collecting ... 
  0%|                                                                                                                          | 0/6 [00:00<?, ?it/s]terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL Error 1: unhandled cuda error
Fatal Python error: Aborted

Thread 0x00007ff40a943700 (most recent call first):
<no Python frame>

Thread 0x00007ff405941700 (most recent call first):
<no Python frame>

Current thread 0x00007ff408142700 (most recent call first):
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/cuda/nccl.py", line 89 in reduce
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/parallel/comm.py", line 96 in reduce_add
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/parallel/comm.py", line 143 in reduce_add_coalesced
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 45 in forward
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 34 in backward
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/autograd/function.py", line 87 in apply

Thread 0x00007ff411144700 (most recent call first):
<no Python frame>

Thread 0x00007ff3b9921700 (most recent call first):
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/threading.py", line 306 in wait
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/threading.py", line 558 in wait
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tqdm/_monitor.py", line 60 in run
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007ff3b7120700 (most recent call first):
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/threading.py", line 306 in wait
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/queue.py", line 179 in get
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 232 in run
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007ff54fdfb740 (most recent call first):
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147 in backward
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/_tensor.py", line 255 in backward
  File "/home/stas/hf/transformers-master/src/transformers/trainer.py", line 1759 in training_step
  File "/home/stas/hf/transformers-master/src/transformers/trainer.py", line 1263 in train
  File "/home/stas/hf/transformers-master/tests/deepspeed/../test_trainer.py", line 332 in setUp
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/unittest/case.py", line 630 in _callSetUp
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/unittest/case.py", line 672 in run
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/unittest/case.py", line 736 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/unittest.py", line 321 in runtest
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 162 in pytest_runtest_call
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 255 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 311 in from_call
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 215 in call_and_report
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 126 in runtestprotocol
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/main.py", line 323 in _main
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185 in console_main
  File "/home/stas/anaconda3/envs/py38-pt18/bin/pytest", line 8 in <module>
Aborted
```
## To Reproduce

```
git clone https://github.com/huggingface/transformers/
cd transformers
pip install -e .[dev]
pytest tests/test_trainer.py -rA -sv
```

env:
```
Collecting environment information...
PyTorch version: 1.9.0.dev20210603+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-62-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: 
GPU 0: A100-SXM4-40GB
GPU 1: A100-SXM4-40GB
GPU 2: A100-SXM4-40GB
GPU 3: A100-SXM4-40GB

Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.0.dev20210603+cu113
[pip3] torchaudio==0.10.0.dev20210603
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.9.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0                     8_mkl    conda-forge
[conda] libcblas                  3.9.0                     8_mkl    conda-forge
[conda] liblapack                 3.9.0                     8_mkl    conda-forge
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py38h1e0a361_2    conda-forge
[conda] mkl_fft                   1.3.0            py38h5c078b8_1    conda-forge
[conda] mkl_random                1.2.0            py38hc5bc63f_1    conda-forge
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] numpy-base                1.18.5           py38hde5b4d6_0
[conda] torch                     1.7.0+cu101              pypi_0    pypi
[conda] torchaudio                0.10.0.dev20210603          pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.9.0.dev20210128+cu110          pypi_0    pypi
```

Installed with:
```
pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html -U
```

All works with 1.8.1, when I installed it as:
```
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @Varal7 @ngimel @bhosmer @cpuhrsch

**Comment by cpuhrsch** [comment]
This doesn't look related to PyTorch's Transformer abstractions, which I don't think [HF's transformer library](https://github.com/huggingface/transformers) uses. I suspect this is related to recent issues in building nightlies instead. cc @malfet @seemethere

**Comment by stas00** [comment]
HF Transformers doesn't use PyTorch's Transformer abstractions as of this writing.

**Comment by stas00** [comment]
FWIW, 9.0 RC doesn't have this problem. I installed it with:

`pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/test/cu111/torch_test.html -U` 

But I see it was built against cuda-11.1

**Comment by ptrblck** [comment]
@stas00 For the first issue:
```python
what():  NCCL Error 1: unhandled cuda error
```
it seems as if NCCL is running into a previous CUDA error. Could you try to update the drivers e.g. to 465.19.01 to check, if the enhanced compatibility is not working correctly?

The second issue seems to be a code error, so you could check the shapes of the tensors:
```python
what():  The size of tensor a (4) must match the size of tensor b (8) at non-singleton dimension 1
```

**Comment by malfet** [comment]
CUDA-11.3 builds are still experimental so might contain occasional bugs. 
@stas00 can you please nightly builds using CUDA-11.1 and check if it will hit the same error?

**Comment by stas00** [comment]
> @stas00 For the first issue:
> 
> ```python
> what():  NCCL Error 1: unhandled cuda error
> ```
> 
> it seems as if NCCL is running into a previous CUDA error. Could you try to update the drivers e.g. to 465.19.01 to check, if the enhanced compatibility is not working correctly?

It's not my box, so unfortunately I can't update the drivers there.

But let me test it on my setup, where I have 465.

> The second issue seems to be a code error, so you could check the shapes of the tensors:
> 
> ```python
> what():  The size of tensor a (4) must match the size of tensor b (8) at non-singleton dimension 1
> ```

Could this be due to a missed earlier printed deprecation warnings? This same code works with 1.8.1 w/o any failures. The CI runs this version on the whole test suite.

It was just a random test that I quickly run. Let me investigate this closer.

**Comment by stas00** [comment]
> CUDA-11.3 builds are still experimental so might contain occasional bugs.
> @stas00 can you please nightly builds using CUDA-11.1 and check if it will hit the same error?

I now did:
```
pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html -U
```
and the initial crash as reported in OP is not there. So clearly this is cu113 issue then, as I retested cu113/torch_nightly.html just now and it crashes.

The 2nd problem as @ptrblck pointed out seems to be a code problem. and most likely it has to do with some deprecation removed in 1.9.0 - I will investigate that one now.

**Comment by stas00** [comment]
OK, I installed cu133 nightly on my box with 465.19.01:
```
pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html -U
```
and at least for the test module reported in OP I don't have any failures.

So that abort:
```
what():  The size of tensor a (4) must match the size of tensor b (8) at non-singleton dimension 1
```
is not there either.

So @ptrblck your proposition that perhaps the problem was in the nvidia-driver < 465 may be true. That box with 460 is a different hardware, but the same Ubuntu version.

So I will test RC-1.9.0 next on my box, which I suspect removed some deprecations making those errors.

**Comment by ptrblck** [comment]
> So @ptrblck your proposition that perhaps the problem was in the nvidia-driver < 465 may be true. That box with 460 is a different hardware, but the same Ubuntu version. (and also Amphere, but A100)

Which hardware was used in the 460 node, as I was trying to reproduce it on an A100 node with 450 (which would use forward compatibility)?

**Comment by stas00** [comment]
OK, I installed 1.9.0 RC on my box:
```
pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/test/cu111/torch_test.html -U
```
and the test module doesn't fail. So that:
```
what():  The size of tensor a (4) must match the size of tensor b (8) at non-singleton dimension 1
```
doesn't show up either.

**Comment by stas00** [comment]
> > So @ptrblck your proposition that perhaps the problem was in the nvidia-driver < 465 may be true. That box with 460 is a different hardware, but the same Ubuntu version. (and also Amphere, but A100)
> 
> Which hardware was used in the 460 node, as I was trying to reproduce it on an A100 node with 450 (which would use forward compatibility)?

```
lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Stepping:                        10
CPU MHz:                         800.002
CPU max MHz:                     4600.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6399.96
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        1.5 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm
                                 pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid ap
                                 erfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic
                                  movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti
                                 ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms i
                                 nvpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_no
                                 tify hwp_act_window hwp_epp md_clear flush_l1d
```

Let me know if you want anything else, @ptrblck

**Comment by stas00** [comment]
Update: 

1. Found the exact test that triggers the dimension abort:
```
pytest tests/test_trainer.py::TrainerIntegrationTest::test_fp16_full_eval
```

2. it succeeds if I limit the gpus to 0 or 0,1 
```
CUDA_VISIBLE_DEVICES=0 pytest tests/test_trainer.py::TrainerIntegrationTest::test_fp16_full_eval
```
but fails with 4. (the box has 4 gpus)

**Comment by stas00** [comment]
Next crash:

```
pytest tests/test_benchmark.py::BenchmarkTest::test_inference_torchscript
Test session starts (platform: linux, Python 3.8.5, pytest 6.2.2, pytest-sugar 0.9.4)
rootdir: /home/stas/hf/transformers-master
plugins: forked-1.3.0, xdist-2.2.0, sugar-0.9.4, instafail-0.4.2
collecting ... Fatal Python error: Aborted

Current thread 0x00007ffb64013740 (most recent call first):
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1054 in _call_impl
  File "/home/stas/hf/transformers-master/src/transformers/benchmark/benchmark.py", line 132 in encoder_forward
  File "<timeit-src>", line 6 in inner
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/timeit.py", line 177 in timeit
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/timeit.py", line 205 in repeat
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/timeit.py", line 238 in repeat
  File "/home/stas/hf/transformers-master/src/transformers/benchmark/benchmark.py", line 201 in _measure_speed
  File "/home/stas/hf/transformers-master/src/transformers/benchmark/benchmark.py", line 63 in _inference_speed
  File "/home/stas/hf/transformers-master/src/transformers/benchmark/benchmark_utils.py", line 670 in inference_speed
  File "/home/stas/hf/transformers-master/src/transformers/benchmark/benchmark_utils.py", line 710 in run
  File "/home/stas/hf/transformers-master/tests/test_benchmark.py", line 79 in test_inference_torchscript
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/unittest/case.py", line 633 in _callTestMethod
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/unittest/case.py", line 676 in run
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/unittest/case.py", line 736 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/unittest.py", line 321 in runtest
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 162 in pytest_runtest_call
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 255 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 311 in from_call
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 215 in call_and_report
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 126 in runtestprotocol
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/main.py", line 323 in _main
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185 in console_main
  File "/home/stas/anaconda3/envs/py38-pt18/bin/pytest", line 8 in <module>
Aborted
```

**Comment by stas00** [comment]
Hmm, in the full test module run I also got this:
```
pytest tests/test_benchmark.py -rA -sv
terminate called after throwing an instance of 'std::runtime_error'
  what():  nvrtc: error: failed to open libnvrtc-builtins.so.11.1.
  Make sure that libnvrtc-builtins.so.11.1 is installed correctly.
nvrtc compilation failed: 
#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)
template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}
template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}
extern "C" __global__
void fused_mul_pow_mul_add_mul_tanh_add_mul(float* tx_13, float* aten_mul) {
{
if (512 * blockIdx.x + threadIdx.x<64 ? 1 : 0) {
    float tx_13_1 = __ldg(tx_13 + (512 * blockIdx.x + threadIdx.x) % 64);
    aten_mul[512 * blockIdx.x + threadIdx.x] = (float)((double)(tx_13_1) * 0.5) * (float)((double)(tanhf((float)((double)(tx_13_1 + (float)((((double)(tx_13_1) * (double)(tx_13_1)) * (double)(tx_13_1)) * 0.044715)) * 0.7978845608028654))) + 1.0);
  }}
}

```

strangely it didn't show up when running the test separately.

**Comment by stas00** [comment]
bt via gdb:

```
Thread 1 "python" hit Catchpoint 1 (exception thrown), 0x00007ffdd916b762 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffdd916b762 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffdd82bf71b in pybind11::cpp_function::initialize<pybind11::make_iterator<(pybind11::return_value_policy)6, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::Node*>(torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>)::{lambda(pybind11::detail::iterator_state<torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, false, (pybind11::return_value_policy)6>&)#2}, torch::jit::Node*, pybind11::detail::iterator_state<torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, false, (pybind11::return_value_policy)6>&, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::return_value_policy>(pybind11::make_iterator<(pybind11::return_value_policy)6, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::Node*>(torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>)::{lambda(pybind11::detail::iterator_state<torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, false, (pybind11::return_value_policy)6>&)#2}&&, torch::jit::Node* (*)(pybind11::detail::iterator_state<torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, torch::jit::generic_graph_node_list_iterator<torch::jit::Node>, false, (pybind11::return_value_policy)6>&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::return_value_policy const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) ()
   from /home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#2  0x00007ffdd7c6d6ee in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) ()
   from /home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#3  0x00005555556d3f76 in cfunction_call_varargs (kwargs=<optimized out>, args=<optimized out>, func=0x7ffff2755c70)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:742
#4  PyCFunction_Call (func=0x7ffff2755c70, args=<optimized out>, kwargs=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:772
#5  0x000055555569185f in _PyObject_MakeTpCall (callable=0x7ffff2755c70, args=<optimized out>, nargs=<optimized out>, keywords=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:159
#6  0x00005555556dff64 in _PyObject_Vectorcall (kwnames=0x0, nargsf=1, args=0x7fffffff7498, callable=0x7ffff2755c70)
    at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:125
#7  method_vectorcall (method=<optimized out>, args=0x0, nargsf=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/classobject.c:67
#8  0x00005555555d1f36 in _PyObject_Vectorcall (callable=0x7ffff2727440, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#9  0x00005555556d2ec5 in _PyObject_FastCall () at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:147
#10 call_unbound (nargs=<optimized out>, args=<optimized out>, self=<optimized out>, func=<optimized out>, unbound=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/typeobject.c:1456
#11 call_method (nargs=0, args=0x0, name=0x5555558a9c20 <PyId___next__.15157>, obj=0x7ffff280df70)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/typeobject.c:1485
#12 slot_tp_iternext (self=0x7ffff280df70) at /tmp/build/80754af9/python_1599203911753/work/Objects/typeobject.c:6729
#13 0x00005555556ecb02 in zip_next (lz=0x7fffea042740) at /tmp/build/80754af9/python_1599203911753/work/Python/bltinmodule.c:2612
#14 0x000055555571546c in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--
    at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3202
#15 0x00005555556def9f in _PyEval_EvalCodeWithName (_co=0x7ffcf32efd40, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=<optimized out>, kwnames=0x0, kwargs=0x5556014a45f8, kwcount=<optimized out>, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, 
    closure=0x7ffff27f4c40, name=0x7ffcf32a4490, qualname=0x7ffcf32a2210) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4298
#16 0x00005555556df943 in _PyFunction_Vectorcall (func=<optimized out>, stack=0x5556014a45f8, nargsf=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:435
#17 0x0000555555652b84 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x5556014a45f8, callable=0x7ffff26ffe50)
    at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#18 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x5555558ec7e0)
    at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4963
#19 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3500
#20 0x00005555556def9f in _PyEval_EvalCodeWithName (_co=0x7ffcf32a5450, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=<optimized out>, kwnames=0x0, kwargs=0x7ffff2853258, kwcount=<optimized out>, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, 
    name=0x7ffcf32a7370, qualname=0x7ffcf32a7370) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4298
#21 0x00005555556df943 in _PyFunction_Vectorcall (func=<optimized out>, stack=0x7ffff2853218, nargsf=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:435
#22 0x0000555555691041 in PyVectorcall_Call (callable=0x7ffcf32ac280, tuple=<optimized out>, kwargs=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:199
#23 0x000055555571699b in do_call_core (kwdict=0x7ffddb494d40, callargs=0x7ffff2853200, func=0x7ffcf32ac280, tstate=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:5010
#24 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3559
#25 0x00005555556def9f in _PyEval_EvalCodeWithName (_co=0x7ffcf35a4c90, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=<optimized out>, kwnames=0x0, kwargs=0x555601053d40, kwcount=<optimized out>, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, 
    closure=0x7ffcf32ab340, name=0x7ffcf32a7370, qualname=0x7ffcf32a7370) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4298
#26 0x00005555556df943 in _PyFunction_Vectorcall (func=<optimized out>, stack=0x555601053d00, nargsf=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:435
#27 0x0000555555652b84 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x555601053d00, callable=0x7ffcf32ac3a0)
    at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#28 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x5555558ec7e0)
    at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4963
#29 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3500
#30 0x00005555556def9f in _PyEval_EvalCodeWithName (_co=0x7ffcf32a5a80, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=<optimized out>, kwnames=0x0, kwargs=0x555559b375b0, kwcount=<optimized out>, kwstep=1, defs=0x7ffcf32a63d8, defcount=8, kwdefs=0x0, 
    closure=0x0, name=0x7ffcf336e270, qualname=0x7ffcf336e270) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4298
#31 0x00005555556df943 in _PyFunction_Vectorcall (func=<optimized out>, stack=0x555559b37568, nargsf=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:435
#32 0x0000555555652b84 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x555559b37568, callable=0x7ffcf32ac700)
--Type <RET> for more, q to quit, c to continue without paging--
    at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#33 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x5555558ec7e0)
    at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4963
#34 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3500
#35 0x00005555556dea92 in _PyEval_EvalCodeWithName (_co=0x7ffcf32a5920, globals=<optimized out>, locals=<optimized out>, args=<optimized out>,
    argcount=<optimized out>, kwnames=0x0, kwargs=0x555559ad5f90, kwcount=<optimized out>, kwstep=1, defs=0x7ffcf32a6368, defcount=8, kwdefs=0x0,
    closure=0x0, name=0x7ffff72a3cb0, qualname=0x7ffff72a3cb0) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4298
#36 0x00005555556df943 in _PyFunction_Vectorcall (func=<optimized out>, stack=0x555559ad5f80, nargsf=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:435
#37 0x000055555565477f in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x555559ad5f80, callable=0x7ffcf32ac670)
    at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#38 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x5555558ec7e0)
    at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4963
#39 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3469
#40 0x00005555556def9f in _PyEval_EvalCodeWithName (_co=0x7ffce9e3a450, globals=<optimized out>, locals=<optimized out>, args=<optimized out>,
    argcount=<optimized out>, kwnames=0x0, kwargs=0x7ffff28033e8, kwcount=<optimized out>, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0,
    name=0x7ffce9f84f80, qualname=0x7ffce9f8a4b0) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4298
#41 0x00005555556df943 in _PyFunction_Vectorcall (func=<optimized out>, stack=0x7ffff28033c8, nargsf=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:435
#42 0x000055555565475e in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ffff28033c8, callable=0x7ffff283a9d0)
    at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#43 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x5555558ec7e0)
    at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4963
#44 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3486
#45 0x00005555556df86b in function_code_fastcall (globals=<optimized out>, nargs=4, args=<optimized out>, co=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:283
#46 _PyFunction_Vectorcall (func=<optimized out>, stack=0x7fffffff8600, nargsf=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:410
#47 0x00005555556dfe79 in _PyObject_Vectorcall (kwnames=0x0, nargsf=4, args=0x7fffffff8600, callable=0x7ffff283a820)
    at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#48 method_vectorcall (method=<optimized out>, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/classobject.c:89
#49 0x0000555555691041 in PyVectorcall_Call (callable=0x7ffff27259c0, tuple=<optimized out>, kwargs=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:199
#50 0x000055555571699b in do_call_core (kwdict=0x7ffddb49be40, callargs=0x7ffff2753400, func=0x7ffff27259c0, tstate=<optimized out>)
    at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:5010
#51 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3559
```

**Comment by stas00** [comment]
Big question: what's with the aborts? why are these not normal failures caught by python? 

Ideally I'd run the massive test suite and share the results, but it aborts `pytest`, so have to run each test separately.

**Comment by stas00** [comment]
More:

On my box I was able to get through 50% of the tests but got an abort as well:

```
pytest tests/test_pipelines_summarization.py::SimpleSummarizationPipelineTests::test_input_too_long
Test session starts (platform: linux, Python 3.8.8, pytest 6.2.3, pytest-sugar 0.9.4)
rootdir: /mnt/nvme1/code/huggingface, configfile: pytest.ini
plugins: sugar-0.9.4, monitor-1.6.0, flakefinder-1.0.0, forked-1.3.0, instafail-0.4.2, xdist-2.2.1
collecting ... Fatal Python error: Aborted

Current thread 0x00007fdd51717740 (most recent call first):
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/functional.py", line 2043 in embedding
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158 in forward
  File "/mnt/nvme1/code/huggingface/transformers/src/transformers/models/bart/modeling_bart.py", line 124 in forward
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1054 in _call_impl
  File "/mnt/nvme1/code/huggingface/transformers/src/transformers/models/bart/modeling_bart.py", line 754 in forward
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1054 in _call_impl
  File "/mnt/nvme1/code/huggingface/transformers/src/transformers/generation_utils.py", line 417 in _prepare_encoder_decoder_kwargs_for_generation
  File "/mnt/nvme1/code/huggingface/transformers/src/transformers/generation_utils.py", line 922 in generate
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28 in decorate_context
  File "/mnt/nvme1/code/huggingface/transformers/src/transformers/pipelines/text2text_generation.py", line 134 in _generate
  File "/mnt/nvme1/code/huggingface/transformers/src/transformers/pipelines/text2text_generation.py", line 117 in __call__
  File "/mnt/nvme1/code/huggingface/transformers/src/transformers/pipelines/text2text_generation.py", line 203 in __call__
  File "/mnt/nvme1/code/huggingface/transformers/tests/test_pipelines_summarization.py", line 77 in test_input_too_long
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/unittest/case.py", line 633 in _callTestMethod
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/unittest/case.py", line 676 in run
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/unittest/case.py", line 736 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/unittest.py", line 321 in runtest
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 162 in pytest_runtest_call
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 255 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 311 in from_call
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 215 in call_and_report
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 126 in runtestprotocol
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/main.py", line 323 in _main
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185 in console_main
  File "/home/stas/anaconda3/envs/py38-pt18/bin/pytest", line 8 in <module>
Aborted (core dumped)
```

**Comment by stas00** [comment]
Oddly `pytest` doesn't show the short bt when I run the specific test, but it does when I run the whole test module:
```
pytest tests/test_pipelines_summarization.py -sv -rA
Test session starts (platform: linux, Python 3.8.8, pytest 6.2.3, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /mnt/nvme1/code/huggingface, configfile: pytest.ini
plugins: sugar-0.9.4, monitor-1.6.0, flakefinder-1.0.0, forked-1.3.0, instafail-0.4.2, xdist-2.2.1
collecting ... Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
terminate called after throwing an instance of 'c10::IndexError'
  what():  index out of range in self
Exception raised from operator() at ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:849 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f4cbbcec412 in /home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x138043a (0x7f4cbd0c343a in /home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)

Fatal Python error: Aborted
(the rest is the same as the previous comment)
```

That's probably enough for now.

If you want me to test anything else please let me know.

**Comment by stas00** [comment]
It's pretty bad, I keep running into aborts, trying to run a very basic deepspeed on one layer 4 elements model in fp16 crashes:

```
terminate called after throwing an instance of 'c10::Error'
  what():  Input type (CPUFloatType) and weight type (CUDAHalfType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
Exception raised from _convolution at ../aten/src/ATen/native/Convolution.cpp:935 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f8a49e8d412 in /home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f8a49e89dab in /home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: at::native::_convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool, bool) + 0x36bb (0x7f8a4b04c07b in /home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
```

have to revert to a working version to be able to do work.

**Comment by malfet** [comment]
Asserts should be fixed by #59490

**Comment by stas00** [comment]
Thank you, @malfet!

I confirm that nightly no longer aborts. I see that RC hasn't landed this fix so can't validate that.

**Comment by malfet** [comment]
@stas00 Fix should have been picked into 1.9 release as https://github.com/pytorch/pytorch/commit/795df76568aba7c0891b94d1aea5bda8aacd475c and next RC should have been baked by now.

**Comment by stas00** [comment]
Great. Installed the latest incarnation of RC and the initial problem is gone. 

Will now run the full test suite and report back (probably in the morning/PST)

**Comment by stas00** [comment]
OK, things seem to be good with RC as far the non-slow HF transformers go. 

Will try to run the slow tests, but usually non-slow tests is a good indicator that in general things are good.

Thank you for the quick fix on the abort!

**Comment by ngimel** [comment]
Thanks for testing, @stas00!
