### ISSUE TITLE
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by YeskendirK** [pytorch/pytorch#5962]
Hello everyone!
Help with this error, please.

`Traceback (most recent call last):
  File "main.py", line 145, in <module>
    train(epoch)
  File "main.py", line 92, in train
    output = denormalize( model(normalize(input, mean, std)), mean, std)
  File "/mnt/home/..../.conda/envs/opt_anaconda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/home/...../...../model.py", line 263, in forward
    e = self.encoder(x)
  File "/mnt/home/..../...../model.py", line 228, in encoder
    x = self.en_conv1(x)
  File "/mnt/home/...../.conda/envs/opt_anaconda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/home/....../.conda/envs/opt_anaconda/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/mnt/home/....../.conda/envs/opt_anaconda/lib/python2.7/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR
`

**Comment by ezyang** [comment]
Hi, what version of PyTorch, cudnn and cuda are you using; can you post a repro script?

**Comment by YeskendirK** [comment]
@ezyang, seems there were problems with GPUs that I remotely access. Now everything works!
