### ISSUE TITLE
torch.cuda.is_available() returns False

### ISSUE THREAD

**Issue by tiagoft** [pytorch/pytorch#6041]
Hello,

I am having trouble using cuda with Pytorch. I am migrating from Theano (maybe this is a problem?). I tried installing pytorch from pip, then uninstalled and tried with conda, and tried compiling from source using `python setup install`.

It seems that CUDA works everywhere else in the system. I am supposing that this could be a permission issue or an issue with a broken path somewhere? I see that many people are having the same problem; have you been able to solve it somehow?

Thanks!

This is some info about my system and my installation:

- OS: Ubuntu 16.04
- PyTorch version: 0.4.0a0+1ab248d (as stated in torch.\_\_version\_\_)
- How you installed PyTorch (conda, pip, source): from source, although I have tried pip and conda and had the same problem.
- Python version: 2.7
- CUDA/cuDNN version: 8.0 / 7.2.1
- GPU models and configuration: Geforce GTX1070
- GCC version (if compiling from source): 5.4.1

~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44

~$ nvidia-smi 
Tue Mar 27 10:59:19 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.42                 Driver Version: 390.42                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   49C    P8     6W / 151W |    266MiB /  8118MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1452      G   /usr/lib/xorg/Xorg                           144MiB |
|    0      2751      G   compiz                                       118MiB |
+-----------------------------------------------------------------------------+

~$ python -c 'import torch; print torch.cuda.is_available()'
False

~$ python -c 'import torch; print torch.rand(2,3).cuda()'
THCudaCheck FAIL file=/home/username/pytorch/aten/src/THC/THCGeneral.cpp line=70 error=30 : unknown error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: cuda runtime error (30) : unknown error at /home/username/pytorch/aten/src/THC/THCGeneral.cpp:70

I was under the impression that pytorch was not finding CUDA in runtime, so I tried:
~$ CUDA_HOME="/usr/local/cuda" python -c 'import torch; print torch.cuda.is_available()'
False

**Comment by SsnL** [comment]
What's the relevant log when you compiled from source?

**Comment by tiagoft** [comment]
I am re-compiling pytorch from source (after cloning the repository again). It states:

**Comment by tiagoft** [comment]
Ok, problem seems to be solved! How I fixed it (after many, many tries):

1) Installed CUDA 9.1 using apt-get, following the instructions in this link: https://cryptoandcoffee.com/mining-gems/cuda-9-0-install-ubuntu-16-04-apt-get/
2) Installed PyTorch using pip
3) Rebooted

Now I get:
~$ python -c 'import torch; print torch.cuda.is_available()'
True

**Comment by StalVars** [comment]
"Installed PyTorch using pip", How did you do that?  I thought - 
PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).

**Comment by vinaykumar2491** [comment]
@StalVars PyTorch supports both `pip` and `conda` package managers. 
`pip3 install torch torchvision`
See https://pytorch.org/

**Comment by recolic** [comment]
But the source building is still broken, isn't it?

Now I'm suffering from the same problem. Stuck here after fixing many many compilation errors by hand.

**Comment by peturhelgi** [comment]
I did the same as @tiagoft and it worked. However, I had some problems after logging in as I just got to a blank screen. After reading [this thread](https://askubuntu.com/questions/41681/blank-screen-after-installing-nvidia-restricted-driver) I resolved the problem.

**Comment by bellonemauro** [comment]
Hello, 

comment here instead of opening a new issue, my device is well configured and works perfectly fine in windows 10 and ubuntu 16.04.
However,  I (sometimes) get the error that cuda.is_availble() = false: 

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.

reboot always solve, but I would like to know what generates this error (I get it ones a day! ) and I have to stop training, save state and reboot. 

Thanks
Mauro

**Comment by soumith** [comment]
hey @bellonemauro , we check with the NVIDIA driver if CUDA / driver is available and ready. If it reports False, we report False. I suspect some weird driver instability.

**Comment by bellonemauro** [comment]
thank you! this was also my suspect ... no much I can do as I have the latest driver so maybe with some future updates ...

**Comment by pyotr777** [comment]
Have the same problem.
Installed Pytorch with
```pip3 install torch torchvision```

Ubuntu 16.04

```print(torch.__version__)```
1.4.0

```
$ nvidia-smi
Wed Mar  4 12:07:52 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P2000        Off  | 00000000:01:00.0 Off |                  N/A |
| 50%   30C    P0    18W /  75W |      0MiB /  5058MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

```python
print(torch.cuda.is_available())
False
print(torch.backends.cudnn.enabled)
True
```

Reboot didn't help.

**Comment by nik31096** [comment]
See [https://stackoverflow.com/questions/58595291/runtime-error-999-when-trying-to-use-cuda-with-pytorch]. This was helped me without reboot every time.

**Comment by DarrenCook** [comment]
That worked for me. In fact all I needed was:

```
sudo rmmod nvidia_uvm
sudo modprobe nvidia_uvm
```

(Trying `rmmod nvidia` complained about "in use by: nvidia_modeset" - this is on a notebook, and I didn't want to crash the GUI. But it seems it was just nvidia_uvm that needed a kick.)
