### ISSUE TITLE
DISABLED test_jit_cuda_extension (__main__.TestCppExtensionJIT)

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#61655]
See: https://github.com/pytorch/pytorch/runs/3065374723
platforms: windows

```
======================================================================
ERROR [20.716s]: test_jit_cuda_extension (__main__.TestCppExtensionJIT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cpp_extensions_jit.py", line 109, in test_jit_cuda_extension
    z = module.sigmoid_add(x, y).cpu()
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

----------------------------------------------------------------------
```

also trying out the new platform DISABLED capability in #61427

cc @ezyang @gchanan @zou3519 @peterjc123 @mszhanyi @skyline75489 @nbcsm @malfet @bdhirsh @jbschlosser @anjali411 @gmagogsfm

**Comment by SplitInfinity** [comment]
What is the issue here? Should the test be disabled? Has it already been disabled?

**Comment by janeyx99** [comment]
It's currently breaking the Windows 11.3 periodic CI job so it should be disabled (but hasn't been because the new platform DISABLED capability in #61427 seems to not function as expected).

I'm going to remove the platforms line to make master green sooner and investigate the disabling functionality sooner.

**Comment by janeyx99** [comment]
Turns out the DISABLED capability is fine, but the disabling code was never called in this specific test case (more explained in #61922).

**Comment by janeyx99** [comment]
Readded the platforms key back to limit the platforms for which the test will be disabled to windows only.

**Comment by gmagogsfm** [comment]
This issue looks more like a configuration issue based on the error message:
```
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain
```

I will remove it from JIT triage queue for now since it looks unrelated to TorchScript. Feel free to add it back if this is incorrect

**Comment by davidberard98** [comment]
1. run `python test\test_cpp_extensions_jit.py -k test_jit_cuda_extension`; it succeeds
2. run `python test\test_cpp_extensions_jit.py`; it fails

so - might have something to do with some global state that's affected by earlier tests?

**Comment by davidberard98** [comment]
`test_jit_cuda_archflags` is setting some global flags that aren't being cleaned up

**Comment by huydhn** [comment]
Reopen this issue as this is happening now in trunk https://hud.pytorch.org/pytorch/pytorch/commit/550f98332bfd296bf10b50ae43f5677e1f04f4bd

**Comment by huydhn** [comment]
Closing this now to re-enable the test as this looks resolved after the switch to Windows G5 runners has been in place for a few days.  Verified by https://github.com/pytorch/pytorch/pull/93102

**Comment by huydhn** [comment]
This one is fixed, but is closed too soon.  I'll manually close it tomorrow
