### ISSUE TITLE
Wrong results for `topk` kernel with non-contiguous outputs on CUDA for 1D tensors.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#62940]
## 🐛 Bug

`topk` CUDA kernel gives wrong results when calling its out variant with non-contiguous output tensors. Apparently, when given non-contiguous out tensors, `topk` is ignoring its original strides.

## To Reproduce

```python
>>> a = torch.arange(12, device='cuda')
>>> indices = torch.zeros_like(a, dtype=torch.long)
>>> values = torch.zeros_like(a)
>>> # indices, values: get every 4th element
>>> torch.topk(a, 3, -1, out=(values[::4], indices[::4]))
torch.return_types.topk_out(
values=tensor([11,  0,  0], device='cuda:0'),
indices=tensor([11,  0,  0], device='cuda:0'))
>>> values
tensor([11, 10,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0], device='cuda:0')
>>> indices
tensor([11, 10,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0], device='cuda:0')
```

## Expected behavior

```python
>>> torch.topk(a, 3, -1, out=(values[::4], indices[::4]))
torch.return_types.topk_out(
values=tensor([11,  10,  9], device='cuda:0'),
indices=tensor([11,  10, 9], device='cuda:0'))
>>> values
tensor([11, 0, 0,  0,  10,  0,  0,  0,  9,  0,  0,  0], device='cuda:0')
>>> indices
tensor([11, 0, 0,  0,  10,  0,  0,  0,  9,  0,  0,  0], device='cuda:0')
```

## Environment

PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.9.5 (default, Jun 4 2021, 12:28:51) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-147-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX

Nvidia driver version: 460.27.04
cuDNN version: /usr/local/cuda-10.2.89/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.9.0
[conda] blas 1.0 mkl
[conda] cudatoolkit 10.2.89 hfd86e86_1
[conda] mkl 2021.2.0 h06a4308_296
[conda] mkl-service 2.3.0 py39h27cfd23_1
[conda] mkl_fft 1.3.0 py39h42c9631_2
[conda] mkl_random 1.2.1 py39ha9443f7_2
[conda] numpy 1.20.2 py39h2d18471_0
[conda] numpy-base 1.20.2 py39hfae3a4d_0
[conda] pytorch 1.9.0 py3.9_cuda10.2_cudnn7.6.5_0 pytorch

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @heitorschueroff

**Comment by gchanan** [comment]
I checked back to 1.8.1 and 1.6.0 and there is the same behavior, so doesn't look like a regression.

**Comment by ysiraichi** [comment]
@heitorschueroff I think I have fixed it in #62942.
I had unassigned myself because this issue was still under "triage review" at that time. Sorry for the confusion.

**Comment by heitorschueroff** [comment]
> @heitorschueroff I think I have fixed it in #62942.
> I had unassigned myself because this issue was still under "triage review" at that time. Sorry for the confusion.

Np, I'll review your PR. Thanks for working on this.
