### ISSUE TITLE
BatchNorm2d + SyncBatchNorm incorrect multi gpu behaviour in 1.10.0 (tested working in 1.8.0)

### ISSUE THREAD

**Issue by erees1** [pytorch/pytorch#62967]
## 🐛 Bug

SyncBatchNorm layers in torch 1.10.0 give different outputs on 2 gpus vs the equivalent BatchNorm layer on a single gpu. This wasn't a problem in torch 1.8.0

## To Reproduce
This code is based on the [PyTorch DDP demo](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html) but the model consists only of a `BatchNorm2d` layer.

```python
import os
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.multiprocessing as mp

from torch.nn.parallel import DistributedDataParallel as DDP
import argparse


def setup(rank, world_size):
    torch.manual_seed(0)
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "12355"

    # iniialize the process group
    dist.init_process_group("gloo", rank=rank, world_size=world_size)


def cleanup():
    dist.destroy_process_group()


class ToyModel(nn.Module):
    def __init__(self, num_features=10):
        super().__init__()
        self.bn = nn.BatchNorm2d(num_features=num_features)

    def forward(self, x):
        x = x.permute(0, 2, 1, 3)
        x = self.bn(x)
        x = x.permute(0, 2, 1, 3)
        return x


def demo_basic(rank, world_size, convert_sync_batchnorm):
    print(f"Running basic DDP example on rank {rank}.")
    setup(rank, world_size)

    # create model and move it to GPU with id rank
    model = ToyModel(num_features=10)
    # create model and move it to GPU with id rank
    if world_size > 1 and convert_sync_batchnorm:
        print("Converting BatchNorm to SyncBatchNorm")
        model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)

    model = model.to(rank)
    if world_size > 1:
        ddp_model = DDP(model, device_ids=[rank])
        model = ddp_model

    inputs = torch.randn(2, 2, 10, 1).to(rank)
    print(f"{rank=}, {inputs[0, 0].squeeze()=}")
    outputs = model(inputs)
    print(f"{rank=}, {outputs[0, 0].squeeze()=}")

    cleanup()


def run_demo(demo_fn, world_size, convert_bn):
    if world_size > 1:
        mp.spawn(demo_fn, args=(world_size, convert_bn), nprocs=world_size, join=True)
    else:
        demo_fn(0, world_size, convert_bn)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--n_gpus", default=2, type=int, help="Number of gpus")
    parser.add_argument(
        "--convert_bn",
        action="store_true",
        default=False,
        help="Whether to convert BatchNorm layers to SyncBatchNorm",
    )

    args = parser.parse_args()

    print(f"{torch.__version__=}")
    run_demo(demo_basic, args.n_gpus, args.convert_bn)
```

#### 1 - 2 gpus, convert to `SyncBatchNorm`
```
python3 ddp_demo.py --n_gpus 2 --convert_bn
torch.__version__='1.10.0a0+git63955b3'
Running basic DDP example on rank 0.
Running basic DDP example on rank 1.
Converting BatchNorm to SyncBatchNorm
Converting BatchNorm to SyncBatchNorm
rank=1, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
         0.3223, -1.2633], device='cuda:1')
rank=0, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
         0.3223, -1.2633], device='cuda:0')
rank=1, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7058,  0.7740,  0.1321,  0.6478,  0.2026, -0.1025,  1.0656,
        -1.3900,  0.9416], device='cuda:1', grad_fn=<SqueezeBackward0>)
rank=0, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7058,  0.7740,  0.1321,  0.6478,  0.2026, -0.1025,  1.0656,
        -1.3900,  0.9416], device='cuda:0', grad_fn=<SqueezeBackward0>)
```

#### 2 - 2 gpus, do not convert to `SyncBatchNorm`
```
python3 ddp_demo.py --n_gpus 2
torch.__version__='1.10.0a0+git63955b3'
Running basic DDP example on rank 0.
Running basic DDP example on rank 1.
rank=1, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
         0.3223, -1.2633], device='cuda:1')
rank=0, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
         0.3223, -1.2633], device='cuda:0')
rank=1, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7582, -0.7058, -1.2356,  0.7740,  1.4852,  0.1321, -1.1821,
         0.6478, -1.1941], device='cuda:1', grad_fn=<SqueezeBackward0>)
rank=0, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7582, -0.7058, -1.2356,  0.7740,  1.4852,  0.1321, -1.1821,
         0.6478, -1.1941], device='cuda:0', grad_fn=<SqueezeBackward0>)
```

#### 3 - 1 gpu
```
python3 ddp_demo.py --n_gpus 1
torch.__version__='1.10.0a0+git63955b3'
Running basic DDP example on rank 0.
False
rank=0, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
         0.3223, -1.2633], device='cuda:0')
rank=0, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7582, -0.7058, -1.2356,  0.7740,  1.4852,  0.1321, -1.1821,
         0.6478, -1.1941], device='cuda:0', grad_fn=<SqueezeBackward0>)
```

1 != 2 ❌
2 == 3 ✅

#### 1 - 2 gpus, convert to `SyncBatchNorm`
```
python3 ddp_demo.py --n_gpus 2 --convert_bn
torch.__version__='1.8.0a0+618cf40'
Running basic DDP example on rank 0.
Running basic DDP example on rank 1.
Converting BatchNorm to SyncBatchNorm
Converting BatchNorm to SyncBatchNorm
rank=1, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
         0.3223, -1.2633], device='cuda:1')
rank=0, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
         0.3223, -1.2633], device='cuda:0')
rank=0, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7582, -0.7058, -1.2356,  0.7740,  1.4852,  0.1321, -1.1821,
         0.6478, -1.1941], device='cuda:0', grad_fn=<SqueezeBackward0>)
rank=1, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7582, -0.7058, -1.2356,  0.7740,  1.4852,  0.1321, -1.1821,
         0.6478, -1.1941], device='cuda:1', grad_fn=<SqueezeBackward0>)
```

#### 2 - 2 gpus, do not convert to `SyncBatchNorm`
```
python3 ddp_demo.py --n_gpus 2
torch.__version__='1.8.0a0+618cf40'
Running basic DDP example on rank 0.
Running basic DDP example on rank 1.
rank=0, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
         0.3223, -1.2633], device='cuda:0')
rank=1, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
         0.3223, -1.2633], device='cuda:1')
rank=1, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7582, -0.7058, -1.2356,  0.7740,  1.4852,  0.1321, -1.1821,
         0.6478, -1.1941], device='cuda:1', grad_fn=<SqueezeBackward0>)
rank=0, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7582, -0.7058, -1.2356,  0.7740,  1.4852,  0.1321, -1.1821,
         0.6478, -1.1941], device='cuda:0', grad_fn=<SqueezeBackward0>)
```

#### 3 - 1 gpu
```
python3 ddp_demo.py --n_gpus 1
torch.__version__='1.8.0a0+618cf40'
Running basic DDP example on rank 0.
rank=0, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
         0.3223, -1.2633], device='cuda:0')
rank=0, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7582, -0.7058, -1.2356,  0.7740,  1.4852,  0.1321, -1.1821,
         0.6478, -1.1941], device='cuda:0', grad_fn=<SqueezeBackward0>)
```

1 == 2 == 3 ✅

## Expected behavior

I expect the behaviour in torch 1.10.0 to mirror that in 1.8.0 where options 1, 2 and 3 all produce the same output.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

### Torch 1.10.0a0+git63955b3 Env info
```bash
Collecting environment information...
PyTorch version: 1.10.0a0+git63955b3
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.21.1
Libc version: glibc-2.27

Python version: 3.8.11 (default, Jul  3 2021, 17:53:42)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-65-generic-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: 11.2.152
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.1
[pip3] pytorch-memlab==0.2.3
[pip3] torch==1.10.0a0+git63955b3
[pip3] torch-tb-profiler==0.2.1
[pip3] torchaudio==0.9.0a0-jit-kaldi-fa498ad
[pip3] torchpq==0.1.8.3
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.10.0

```

### Torch 1.8.0a0+618cf40 Env info
```bash
Collecting environment information...
PyTorch version: 1.8.0a0+618cf40
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.21.1
Libc version: glibc-2.27

Python version: 3.8.11 (default, Jul  3 2021, 17:53:42)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-65-generic-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: 11.2.152
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.1
[pip3] pytorch-memlab==0.2.3
[pip3] torch==1.8.0a0+618cf40
[pip3] torchaudio==0.9.0a0-jit-kaldi-fa498ad
[pip3] torchpq==0.1.8.3
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.10.0
[conda] Could not collect
``` 

cc @albanD @mruberry @jbschlosser

**Comment by samringer** [comment]
Seeing the exact same thing!

**Comment by erees1** [comment]
FWIW I also see the same error with backend = 'nccl' as well

**Comment by willwilliams** [comment]
Been seeing this issue on master for a while. IIRC, this problem isn't affecting the 1.9 release

**Comment by xwang233** [comment]
I see that you are using `permute` in your code. PyTorch has added native channels-last support for SyncBatchNorm in the past release. Would you try to modify the code from `permute` to `.to(memory_format=torch.channels_last)` and see if it helps?

**Comment by erees1** [comment]
Thanks for the reply -> you are correct removing the permute removes the difference between 2 gpus and 1 gpu although this is quite unexpected? I guess there is still inconsistent behaviour between `SyncBatchNorm` and `BatchNorm`. 

Is it possible to use SyncBatchNorm with a permuted input (we use them quite extensivley in our codebase). Fwiw we use BatchNorm2d to mirror BatchNorm1d as per  https://github.com/pytorch/pytorch/issues/41642#issuecomment-668115459 so our last dimension will always be 1 so I'm not sure that moving the memory to channels last helps our use case?


#### Updated code
```python 
import os
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.multiprocessing as mp

from torch.nn.parallel import DistributedDataParallel as DDP
import argparse


def setup(rank, world_size):
    torch.manual_seed(0)
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "12355"

    # iniialize the process group
    dist.init_process_group("gloo", rank=rank, world_size=world_size)


def cleanup():
    dist.destroy_process_group()


class ToyModel(nn.Module):
    def __init__(self, num_features=10):
        super().__init__()
        self.bn = nn.BatchNorm2d(num_features=num_features)

    def forward(self, x):
        x = self.bn(x)
        return x


def demo_basic(rank, world_size, convert_sync_batchnorm, permute):
    print(f"Running basic DDP example on rank {rank}.")
    setup(rank, world_size)

    # create model and move it to GPU with id rank
    model = ToyModel(num_features=3)
    # create model and move it to GPU with id rank
    if world_size > 1 and convert_sync_batchnorm:
        print("Converting BatchNorm to SyncBatchNorm")
        model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)

    model = model.to(rank)
    if world_size > 1:
        ddp_model = DDP(model, device_ids=[rank])
        model = ddp_model

    inputs = torch.randn(2, 3, 3, 1).to(rank)
    if permute:
        inputs = inputs.permute(0,2,1,3)
    print(f"{rank=}, {inputs[0].squeeze()=}")
    outputs = model(inputs)
    print(f"{rank=}, {outputs.squeeze()=}")

    cleanup()


def run_demo(demo_fn, world_size, convert_bn, permute):
    if world_size > 1:
        mp.spawn(demo_fn, args=(world_size, convert_bn, permute), nprocs=world_size, join=True)
    else:
        demo_fn(0, world_size, convert_bn, permute)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--n_gpus", default=2, type=int, help="Number of gpus")
    parser.add_argument(
        "--convert_bn",
        action="store_true",
        default=False,
        help="Whether to convert BatchNorm layers to SyncBatchNorm",
    )
    parser.add_argument(
        "--permute",
        action="store_true",
        default=False,
        help="Whether to convert BatchNorm layers to SyncBatchNorm",
    )
    args = parser.parse_args()

    print(f"{torch.__version__=}")
    run_demo(demo_basic, args.n_gpus, args.convert_bn, args.permute)
```

### Comparison without permute

#### 2 gpus - do not convert to `SyncBatchNorm` without `permute`
```
 python3 ddp_demo.py --n_gpus 2
torch.__version__='1.10.0a0+git63955b3'
Running basic DDP example on rank 0.
Running basic DDP example on rank 1.
rank=1, inputs[0].squeeze()=tensor([[-1.1258, -1.1524,  0.5667],
        [ 0.7935,  0.5988, -1.5551],
        [-0.3414,  1.8530,  0.4681]], device='cuda:1')
rank=0, inputs[0].squeeze()=tensor([[-1.1258, -1.1524,  0.5667],
        [ 0.7935,  0.5988, -1.5551],
        [-0.3414,  1.8530,  0.4681]], device='cuda:0')
rank=0, outputs.squeeze()=tensor([[[-1.2824, -1.3241,  1.3776],
         [ 0.1617, -0.0268, -2.1134],
         [-0.9727,  1.4099, -0.0938]],

        [[ 0.2391,  0.2145,  0.7754],
         [ 0.7390,  0.9298,  0.3098],
         [-1.5180,  0.4097,  0.7649]]], device='cuda:0',
       grad_fn=<SqueezeBackward0>)
rank=1, outputs.squeeze()=tensor([[[-1.2824, -1.3241,  1.3776],
         [ 0.1617, -0.0268, -2.1134],
         [-0.9727,  1.4099, -0.0938]],

        [[ 0.2391,  0.2145,  0.7754],
         [ 0.7390,  0.9298,  0.3098],
         [-1.5180,  0.4097,  0.7649]]], device='cuda:1',
       grad_fn=<SqueezeBackward0>)
```

#### 2 gpus, convert to `SyncBatchNorm` without `permute`
```bash
python3 ddp_demo.py --n_gpus 2 --convert_bn
torch.__version__='1.10.0a0+git63955b3'
Running basic DDP example on rank 0.
Running basic DDP example on rank 1.
Converting BatchNorm to SyncBatchNorm
Converting BatchNorm to SyncBatchNorm
rank=1, inputs[0].squeeze()=tensor([[-1.1258, -1.1524,  0.5667],
        [ 0.7935,  0.5988, -1.5551],
        [-0.3414,  1.8530,  0.4681]], device='cuda:1')
rank=0, inputs[0].squeeze()=tensor([[-1.1258, -1.1524,  0.5667],
        [ 0.7935,  0.5988, -1.5551],
        [-0.3414,  1.8530,  0.4681]], device='cuda:0')
rank=1, outputs.squeeze()=tensor([[[-1.2824, -1.3241,  1.3776],
         [ 0.1617, -0.0268, -2.1134],
         [-0.9727,  1.4099, -0.0938]],

        [[ 0.2391,  0.2145,  0.7754],
         [ 0.7390,  0.9298,  0.3098],
         [-1.5180,  0.4097,  0.7649]]], device='cuda:1',
       grad_fn=<SqueezeBackward0>)
rank=0, outputs.squeeze()=tensor([[[-1.2824, -1.3241,  1.3776],
         [ 0.1617, -0.0268, -2.1134],
         [-0.9727,  1.4099, -0.0938]],

        [[ 0.2391,  0.2145,  0.7754],
         [ 0.7390,  0.9298,  0.3098],
         [-1.5180,  0.4097,  0.7649]]], device='cuda:0',
       grad_fn=<SqueezeBackward0>)
```
### Comparison with permute

#### 1. 2 gpus converting to `SyncBatchNorm` with `permute`
```
python3 ddp_demo.py --n_gpus 2 --permute --convert_bn
torch.__version__='1.10.0a0+git63955b3'
Running basic DDP example on rank 0.
Running basic DDP example on rank 1.
Converting BatchNorm to SyncBatchNorm
Converting BatchNorm to SyncBatchNorm
rank=1, inputs[0].squeeze()=tensor([[-1.1258,  0.7935, -0.3414],
        [-1.1524,  0.5988,  1.8530],
        [ 0.5667, -1.5551,  0.4681]], device='cuda:1')
rank=0, inputs[0].squeeze()=tensor([[-1.1258,  0.7935, -0.3414],
        [-1.1524,  0.5988,  1.8530],
        [ 0.5667, -1.5551,  0.4681]], device='cuda:0')
rank=1, outputs.squeeze()=tensor([[[-1.2225, -1.7144,  0.2827],
         [ 0.9537, -0.0083, -2.0673],
         [-0.3331,  1.2135,  0.1735]],

        [[-0.1248, -0.7607, -0.1417],
         [ 1.6293,  0.9537,  0.7032],
         [-0.9026,  0.3161,  1.0496]]], device='cuda:1',
       grad_fn=<SqueezeBackward0>)
rank=0, outputs.squeeze()=tensor([[[-1.2225, -1.7144,  0.2827],
         [ 0.9537, -0.0083, -2.0673],
         [-0.3331,  1.2135,  0.1735]],

        [[-0.1248, -0.7607, -0.1417],
         [ 1.6293,  0.9537,  0.7032],
         [-0.9026,  0.3161,  1.0496]]], device='cuda:0',
       grad_fn=<SqueezeBackward0>)
```

#### 2. 2 gpus without conversion to `SyncBatchNorm` with `permute`
```
python3 ddp_demo.py --n_gpus 2 --permute
torch.__version__='1.10.0a0+git63955b3'
Running basic DDP example on rank 1.
Running basic DDP example on rank 0.
rank=1, inputs[0].squeeze()=tensor([[-1.1258,  0.7935, -0.3414],
        [-1.1524,  0.5988,  1.8530],
        [ 0.5667, -1.5551,  0.4681]], device='cuda:1')
rank=0, inputs[0].squeeze()=tensor([[-1.1258,  0.7935, -0.3414],
        [-1.1524,  0.5988,  1.8530],
        [ 0.5667, -1.5551,  0.4681]], device='cuda:0')
rank=1, outputs.squeeze()=tensor([[[-1.2225,  0.9537, -0.3331],
         [-1.7144, -0.0083,  1.2135],
         [ 0.2827, -2.0673,  0.1735]],

        [[-0.1248,  1.6293, -0.9026],
         [-0.7607,  0.9537,  0.3161],
         [-0.1417,  0.7032,  1.0496]]], device='cuda:1',
       grad_fn=<SqueezeBackward0>)
rank=0, outputs.squeeze()=tensor([[[-1.2225,  0.9537, -0.3331],
         [-1.7144, -0.0083,  1.2135],
         [ 0.2827, -2.0673,  0.1735]],

        [[-0.1248,  1.6293, -0.9026],
         [-0.7607,  0.9537,  0.3161],
         [-0.1417,  0.7032,  1.0496]]], device='cuda:0',
       grad_fn=<SqueezeBackward0>)
```

**Comment by xwang233** [comment]
> Is it possible to use SyncBatchNorm with a permuted input

`SyncBatchNorm` syncs batches across the 1st (0-index) dimension. If the 1st dimension of a input is permuted (e.g. `inputs.permute(0,2,1,3)`), I'm not sure if the result would still be correct.

cc @ngimel

**Comment by ngimel** [comment]
I can't repro on master (e55f271), and I can't find commit 63955b3. It's possible that it was fixed in #62839

**Comment by erees1** [comment]
> I can't repro on master ([e55f271](https://github.com/pytorch/pytorch/commit/e55f2718595fa0f0895b716ec0f7c95ccd5a700e)), and I can't find commit 63955b3. It's possible that it was fixed in #62839.
> Output of the original script:
> 
> ```
> (pytorch) [ngimel@devgpu ~/local/playground] python sync_bn1.py --n_gpus 2 --convert_bn 
> torch.__version__='1.10.0a0+gite55f271'
> Running basic DDP example on rank 0.
> Running basic DDP example on rank 1.
> Converting BatchNorm to SyncBatchNorm
> Converting BatchNorm to SyncBatchNorm
> rank=1, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
>          0.3223, -1.2633], device='cuda:1')
> rank=0, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
>          0.3223, -1.2633], device='cuda:0')
> rank=1, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7582, -0.7058, -1.2356,  0.7740,  1.4852,  0.1321, -1.1821,
>          0.6478, -1.1941], device='cuda:1', grad_fn=<SqueezeBackward0>)
> rank=0, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7582, -0.7058, -1.2356,  0.7740,  1.4852,  0.1321, -1.1821,
>          0.6478, -1.1941], device='cuda:0', grad_fn=<SqueezeBackward0>)
> (pytorch) [ngimel@devgpu ~/local/playground] python sync_bn1.py --n_gpus 2 
> torch.__version__='1.10.0a0+gite55f271'
> Running basic DDP example on rank 0.
> Running basic DDP example on rank 1.
> rank=1, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
>          0.3223, -1.2633], device='cuda:1')
> rank=0, inputs[0, 0].squeeze()=tensor([-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
>          0.3223, -1.2633], device='cuda:0')
> rank=1, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7582, -0.7058, -1.2356,  0.7740,  1.4852,  0.1321, -1.1821,
>          0.6478, -1.1941], device='cuda:1', grad_fn=<SqueezeBackward0>)
> rank=0, outputs[0, 0].squeeze()=tensor([-1.6701, -0.7582, -0.7058, -1.2356,  0.7740,  1.4852,  0.1321, -1.1821,
>          0.6478, -1.1941], device='cuda:0', grad_fn=<SqueezeBackward0>)
> ```

Thanks @ngimel to repro the error with the updated code you will need to pass the --permute flag (as per the second example above). Was this the one you were using or were you using the first code snippet I pasted? Thanks!

**Comment by ngimel** [comment]
cc @peterbell10. Implementation of syncBatchNorm was slightly changed in 1.9 as a part of generally improving speed of BatchNorm1d that shares the same kernels, but the difference should be within fp limits. If you have data to suggest otherwise, please share.

**Comment by peterbell10** [comment]
I have confirmed this is fixed in master, and that #62839 specifically was the fix.

The issue is that the input tensor has `shape=[2, 10, 2, 1]` and `strides=[20, 1, 10, 1]`. This doesn't strictly have the strides of a channels-last tensor (because of the last dimension) and so `suggest_memory_format` returns contiguous and a contiguous output is allocated. However,  `is_contiguous(MemoryFormat::ChannelsLast)` which is used to select the implementation did accept the tensor because it ignores the strides of length-1 dimensions. The end result is the channels last kernel being called with an NHCW contiguous output and so it's assuming the wrong strides.

So, the correctness bug is fixed but it's now using the slower generic kernel. I'll work on a PR to fix that.
