### ISSUE TITLE
Using net.cuda crashes the kernel

### ISSUE THREAD

**Issue by sarthak1996** [pytorch/pytorch#631]
I can train the model on the cpu but using`net.cuda()` crashes the kernel and the following message is displayed:
The kernel appears to have died. It will restart automatically.

The stack trace of the error in my terminal is: 
`THCudaCheck FAIL file=/data/users/soumith/miniconda2/conda-bld/pytorch-0.1.7_1485445763020/work/torch/lib/THC/THCGeneral.c line=66 error=30 : unknown error
terminate called after throwing an instance of 'THException'`
  `what():  cuda runtime error (30) : unknown error at /data/users/soumith/miniconda2/conda-bld/pytorch-0.1.7_1485445763020/work/torch/lib/THC/THCGeneral.c:66
`

**Comment by apaszke** [comment]
What system are you running on? What's your GPU and CUDA version? How did you install pytorch?

**Comment by sarthak1996** [comment]
Thanks for the help. Apparently nvidia drivers were not installed. But now I get another error:
`net.cuda()`
`train the model`
Error:
`TypeError: FloatSpatialConvolutionMM_updateOutput received an invalid combination of arguments - got (int, torch.FloatTensor, torch.FloatTensor, torch.cuda.FloatTensor, torch.cuda.FloatTensor, torch.FloatTensor, torch.FloatTensor, int, int, int, int, int, int), but expected (int state, torch.FloatTensor input, torch.FloatTensor output, torch.FloatTensor weight, [torch.FloatTensor bias or None], torch.FloatTensor finput, torch.FloatTensor fgradInput, int kW, int kH, int dW, int dH, int padW, int padH)`

**Comment by apaszke** [comment]
If you look into the list of types in the `got (...)` part, you'll find a mix of CPU and CUDA tensors, with `input` and `output` being on CPU, while `weight` and `bias` is on the GPU.

You probably forgot to send the input to the GPU. Alternatively, keep in mind that `.cuda()` is an out of place operation i.e.
```python
input.cuda()
model(Variable(input))
```
will fail. You need to overwrite the reference with a new CUDA tensor:
```python
input = input.cuda()
model(Variable(input))
```

**Comment by EmGarr** [comment]
When I run:
```python
input = Variable(torch.randn(30, 3, 10)).cuda()
```
I have exactly the same issue:
`THCudaCheck FAIL file=/home/****/****/pytorch/torch/lib/THC/THCGeneral.c line=66 error=30 : unknown error`

+ My system is Ubuntu 16.04.
+ I have cuda 8.0 and Cudnn 5.0 (everything works perfectly with Theano or tensorflow)
+ I did two installation: pip and in a virtual env he source installation for python 2.7.

Here the output of nvidia-smi:
+ NVIDIA-SMI 375.26
+ Driver version 375.26
+ One GPU GeForce GTX 850M (4043 MiB)

The strange thing is everything worked well when I used cuda 7.5.

**Comment by soumith** [comment]
@EmGarr 
it's surprising that it doesn't even work after a source install.
I cant find anything obviously wrong, unfortunately.
Is there any chance that I can ssh into this machine? Considering that the situation is supposed to be operational, but it is not, and it's a basic code that's failing, I am running out of ideas.

**Comment by EmGarr** [comment]
@soumith  
The error came from my driver installation. The installation was really messy with few conflicts. I purged my system from any traces of nvidia drivers and reinstalled them properly, followed by a reboot.
Everything works fine now.

Sorry for the disturbing.
