### ISSUE TITLE
Cuda memory leak with unpooling

### ISSUE THREAD

**Issue by aboulch** [pytorch/pytorch#642]
Hello,

I have tested the following code :

`import numpy as np`
`import torch`
`import torch.nn as nn`
`import torch.nn.functional as F`
`import torchvision.models as models`
`from torch.autograd import Variable`
`import torch.optim as optim`

`class Net(nn.Module):`
`    def __init__(self):`
`        super(Net, self).__init__()`
`        self.conv1 = nn.Conv2d(3, 64, kernel_size=3, padding=1)`
`        self.conv2 = nn.Conv2d(64, 3, kernel_size=3, padding=1)`
`    def forward(self, x):`
`        x = self.conv1(x)`
`        x, id1 = F.max_pool2d(x,kernel_size=2, stride=2,return_indices=True)`
`        x = F.max_unpool2d(x, id1, kernel_size=2, stride=2)`
`        x = self.conv2(x)`
`        return x`

`model = Net()`
`model.cuda()`

`optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.5)`

`model.train()`

`batch_= np.zeros((8,3, 224, 224), dtype=float)`
`data = Variable(torch.Tensor(batch_))`
`data = data.cuda()`
`while(True):`
`    output = model(data)`

I can see the memory usage of my GPU increasing until I get a "RuntimeError: cuda runtime error (2) : out of memory". When I comment the unpooling I get a stable memory usage. Am I missing something ? Could it be a memory leak in the unpooling layer ?

I use Ubuntu 14.04, GTX 1070, cuda 8.
I tested on python 2.7 and 3.4 and got the same result.

Thank you for your help.

**Comment by fmassa** [comment]
Thanks for the bug rrport Alexandre ! This issue has been fixed in https://github.com/pytorch/pytorch/pull/650

**Comment by aboulch** [comment]
Thanks !!

**Comment by dmarcosg** [comment]
Hello! The very same problem seems to still exist in maxunpool3d in pytorch 0.4.
Maybe the fix was only for 2d?
Thanks!

**Comment by soumith** [comment]
@dmarcosg this was fixed for MaxUnPool3d in pytorch 0.4.1

**Comment by dmarcosg** [comment]
Oh, perfect, I need to keep more up to date! Thanks a lot!
