### ISSUE TITLE
[PyTorch]nn.LSTM.cuda() leads to CuDNNError: 8 when adding dropout parameter

### ISSUE THREAD

**Issue by iamlockelightning** [pytorch/pytorch#6421]
## Information
- PyTorch or Caffe2: PyTorch
- OS: Ubuntu 16.04
- PyTorch version: 0.3.0.post4
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.5
- CUDA/cuDNN version:
>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
>cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR      6
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 21
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
#include "driver_types.h"
- GPU models and configuration: NVIDIA-SMI 384.111 Driver Version: 384.111
- GCC version (if compiling from source): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

## Code:
``` Python
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(RNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True) #, dropout=0.2
        self.fc = nn.Linear(hidden_size, num_classes)
    def forward(self, x):
        h0 = Variable(torch.zeros(self.num_layers, x.size(0), self.hidden_size).cuda())
        c0 = Variable(torch.zeros(self.num_layers, x.size(0), self.hidden_size).cuda())
        out, _ = self.lstm(x, (h0, c0))
        out = self.fc(out[:, -1, :])
        return out

rnn = RNN(100, 50, 3, 2)
rnn.cuda()
```

A simple rnn model. And it works.
But if I add **"dropout=0.2"** in nn.LSTM, when run rnn.cuda(), I get nothing but:
``` Shell
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    rnn.cuda()
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 102, in flatten_parameters
    fn.rnn_desc = rnn.init_rnn_descriptor(fn, handle)
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/rnn.py", line 42, in init_rnn_descriptor
    cudnn.DropoutDescriptor(handle, dropout_p, fn.dropout_seed)
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/__init__.py", line 207, in __init__
    self._set(dropout, seed)
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/__init__.py", line 232, in _set
    ctypes.c_ulonglong(seed),
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/__init__.py", line 283, in check_error
    raise CuDNNError(status)
torch.backends.cudnn.CuDNNError: 8: b'CUDNN_STATUS_EXECUTION_FAILED'
```
## Question
I wonder why? Or any other method I could use to add dropout after each layer of the lstm?
Thanks!

**Comment by Stonesjtu** [comment]
Is your CUDA memory sufficient?

**Comment by ailzhang** [comment]
Hi @iamlockelightning , I cannot repro the issue using your script on pytorch master. The errors seems to be related to the software environment instead of Pytorch.
Could you confirm if this issue is resolved on your side? Thanks!

**Comment by iamlockelightning** [comment]
Thanks, @ailzhang , it turns out to be a mistake in the software environment.

**Comment by simonwang517** [comment]
@iamlockelightning Cloud you please tell me what's your software enviroment mistake? I met the same issue as you.
Thx

**Comment by Edillower** [comment]
Hi @iamlockelightning, I encountered the same problem recently, and I believe its an environmental issue for me as well. However, I haven't been able to locate and fix it. Could you share more details about what's wrong and possible fixes?  Thanks!
