### ISSUE TITLE
Cuda Tensor IPC Does Not Work Properly With P2P Access

### ISSUE THREAD

**Issue by eedalong** [pytorch/pytorch#64504]
## 🐛 Bug

CUDA support both memory IPC and P2P Access, and also combination of them, which means If I allocate a block of memory on device A and send it to child process which runs on device B with CUDA IPC  API and device A and device B support P2P access,  child process can directly access data on device A through ptr created from cudaIPCMemHandle.

But in Pytorch, If I create a cuda tensor on deivce A and send it through queue to child process running on device B(P2P access enabled already), child process failed to access data on device B through ptr created from cudaIPCMemHandle.

## To Reproduce

1. create cuda Tensor on device A and enable P2P access between device A and device B
2. send tensor to child process which runs on device B through torch.multiprocessing.Queue 
3. launch a kernel on device B and try to access data through tensor's data ptr 

## Expected behavior
Everything should works fine but I encountered illegal memory access error 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux) Linux :
 - How you installed PyTorch (`conda`, `pip`, source) pip:
 - Build command you used (if compiling from source):
 - Python version 3.7.5 :
 - CUDA/cuDNN version 11.2 :

## Additional context

cc @VitalyFedyunin @ngimel

**Comment by eedalong** [comment]
I walked through source code about CUDA Tensor IPC, but I didnt find anything different from [cuda simpleIPC samples](https://github.com/NVIDIA/cuda-samples/tree/568b39bd5bea5924446d49d07a4c026a1ec945a5/Samples/simpleIPC). For now, i suspect this may relates to cache allocator.

**Comment by VitalyFedyunin** [comment]
Hi! `torch.multiprocessing` is designed to be inter-process communication, it will not work on cross device. Even if it passes CudaIPC handler there are much more to it, like shared memory (shm) ref counting object, connection to cuda caching allocator and potentially other things as well. Best you could do here at this moment is to find cached allocator block, create IPC handler manually and on the 'secondary' device copy its content to the new tensor.

**Comment by eedalong** [comment]
@VitalyFedyunin  Thx! Yes, for now I malloc cuda tensor and implement ipc and p2p access manually. It works for me
