### ISSUE TITLE
torch.irfft produces "cuFFT error: CUFFT_ALLOC_FAILED" when called after torch.rfft

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#6511]
@SsnL 

The code below produces:
```
(25088, 4001, 2)

  File "bug.py", line 28, in <module>
    layer(bottom1, bottom2)
  File "/home/cvlab/vadim/.wigwam/prefix/python/lib/python2.7/site-packages/torch/nn/modules/module.py", line 371, in __call__
    result = self.forward(*input, **kwargs)
  File "bug.py", line 20, in forward
    cbp = torch.irfft(fft_product, 1).view(len(bottom1), bottom1.size(-2), bottom1.size(-1), self.output_dim) * self.output_dim
RuntimeError: cuFFT error: CUFFT_ALLOC_FAILED
```

```python
import torch
import torch.nn as nn

class CompactBilinearPooling(nn.Module):
    def __init__(self, input_dim1, input_dim2, output_dim, sum_pool = True):
        super(CompactBilinearPooling, self).__init__()
        self.output_dim = output_dim
        self.sum_pool = sum_pool

        generate_sketch_matrix = lambda rand_h, rand_s, input_dim, output_dim: torch.sparse.FloatTensor(torch.stack([torch.arange(input_dim, out = torch.LongTensor()), rand_h.long()]), rand_s.float(), torch.Size([input_dim, output_dim])).to_dense()
        self.sparse_sketch_matrix1 = nn.Parameter(generate_sketch_matrix(torch.randint(output_dim, size = (input_dim1,)), 2 * torch.randint(2, size = (input_dim1,)) - 1, input_dim1, output_dim))
        self.sparse_sketch_matrix2 = nn.Parameter(generate_sketch_matrix(torch.randint(output_dim, size = (input_dim2,)), 2 * torch.randint(2, size = (input_dim2,)) - 1, input_dim2, output_dim))

    def forward(self, bottom1, bottom2):
        sketch_1 = bottom1.permute(0, 2, 3, 1).contiguous().matmul(self.sparse_sketch_matrix1).view(-1, self.output_dim)
        sketch_2 = bottom2.permute(0, 2, 3, 1).contiguous().matmul(self.sparse_sketch_matrix2).view(-1, self.output_dim)
        fft1_real, fft1_imag = torch.rfft(sketch_1, 1).permute(2, 0, 1)
        fft2_real, fft2_imag = torch.rfft(sketch_2, 1).permute(2, 0, 1)
        fft_product = torch.stack([fft1_real * fft2_real - fft1_imag * fft2_imag, fft1_real * fft2_imag - fft1_imag * fft2_real], dim = -1)
        print(fft_product.size())
        cbp = torch.irfft(fft_product, 1).view(len(bottom1), bottom1.size(-2), bottom1.size(-1), self.output_dim) * self.output_dim
        return cbp.sum(dim = 1).sum(dim = 1) if self.sum_pool else cbp.permute(0, 3, 1, 2)

bottom1 = torch.randn(128, 512, 14, 14).cuda()
bottom2 = torch.randn(128, 512, 14, 14).cuda()
layer = CompactBilinearPooling(512, 512, 8000)
layer.cuda()
layer.train()
layer(bottom1, bottom2)
```

Works without error, but there seems a shape misalignment:
```python
import torch
fft_product = torch.rfft(torch.cuda.FloatTensor(25088, 8000), 1)
print(fft_product.size())
# (25088, 4001, 2)
print(torch.irfft(fft_product, 1).size())
# (25088, 8001)
```

- PyTorch or Caffe2: PyTorch
- OS: Ubuntu 16.04
- PyTorch version: master
- How you installed PyTorch (conda, pip, source): source
- Python version: 2.7

**Comment by SsnL** [comment]
For shape misalignment, see `signal_sizes` option of [torch.irfft](http://pytorch.org/docs/master/torch.html#torch.irfft)

**Comment by SsnL** [comment]
A quick googling show that this is roughly saying cuda OOM. `(25088, 4001, 2)` might be just be too big. But I'll look at this in depth later today.

**Comment by vadimkantorov** [comment]
i have an equivalent old code using `pytorch_fft` that passes...

**Comment by SsnL** [comment]
:( sad news... btw, how much memory did your old code use?

**Comment by vadimkantorov** [comment]
same issue if I replace 512 with 64

**Comment by vadimkantorov** [comment]
ah, this is irrelevant, since dimension gets mapped to 8000 anyway...

**Comment by vadimkantorov** [comment]
old code used 7G at peak

**Comment by SsnL** [comment]
Thanks @vadimkantorov . I'll let you know what I find.

**Comment by SsnL** [comment]
@vadimkantorov I just tried again on master and am unabled to reproduce the OOM now. It seemed to use 5G after the `layer(bottom1, bottom2)` call. Could you try again? :)

**Comment by vadimkantorov** [comment]
Me either, it seems to work now. Maybe you fixed something along the way :) Maybe this can be closed, having fewer temp tensors along the way also helps. Might be even better if complex product gets implemented some day.

It would be nice if the OOM exception was some standard PyTorch exception, not a CUDA one.

**Comment by vadimkantorov** [comment]
A random idea:
1) allow attaching an arbitrary string to tensors - some sort of name or tag
2) impl `with AllocateWithTag('fft')` construct
3) allow enumerating diagnostics for tensors by tag - size, device, type etc

This would allow investigating such issues by mere mortals :)
