### ISSUE TITLE
cudatoolkit=11.3 reports "Torch not compiled with CUDA enabled"

### ISSUE THREAD

**Issue by Etienne66** [pytorch/pytorch#67069]
## 🐛 Bug

When trying the cudatookit 11.3 an error is received indicating the torch wasn't compiled for cuda. Works fine if cudatoolkit=10.2 instead.

## To Reproduce

1. `conda install -y pytorch=1.10 torchvision torchaudio cudatoolkit=11.3 -c pytorch`
2. run this with python
```
>>> import torch
>>> tensor = torch.tensor((), device='cuda')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Etienne\miniconda3\lib\site-packages\torch\cuda\__init__.py", line 208, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

## Expected behavior

I expected there not to be an error

## Environment
```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro for Workstations
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19042-SP0
Is CUDA available: False
CUDA runtime version: 11.5.50
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060 SUPER
Nvidia driver version: 496.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.0
[pip3] torch-lr-finder==0.2.1
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl
[conda] cpuonly                   2.0                           0    pytorch
[conda] cudatoolkit               11.3.1               h59b6b97_2
[conda] mkl                       2021.3.0           haa95532_524
[conda] mkl-service               2.4.0            py39h2bbff1b_0
[conda] mkl_fft                   1.3.1            py39h277e83a_0
[conda] mkl_random                1.2.2            py39hf11a4ad_0
[conda] numpy                     1.21.2           py39hfca59bb_0
[conda] numpy-base                1.21.2           py39h0829f74_0
[conda] pytorch                   1.10.0              py3.9_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torch-lr-finder           0.2.1                    pypi_0    pypi
[conda] torchaudio                0.10.0                 py39_cpu  [cpuonly]  pytorch
[conda] torchvision               0.11.1                 py39_cpu  [cpuonly]  pytorch
```
## Additional context

cc @ezyang @seemethere @malfet @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by dlangerm** [comment]
This is still an issue for me BTW. Clean environment didn't fix it. Cleaning out all cached packages and reinstalling with the exact command given in the instructions didn't fix it. 

I gave up and installed the LTS version, worked like a charm with no workarounds.

**Comment by cristianPanaite** [comment]
Hello @Etienne66 ,

I tried to reproduce this error on the latest versions, but I had no success. 

As I see @dlangerm overcame this issue but upgrading the latest version on WSL, and I think that can be the solution.

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.

**Comment by Etienne66** [comment]
I have a new rig with an RTX 3090 and no issues with the current version. Whatever this was I think it was probably resolved a long time ago by other changes.
