### ISSUE TITLE
DISABLED test_nccl_barrier_timeout_new_group_non_member (__main__.CommTest)

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#67154]
## 🐛 Bug

Platforms: rocm

test_nccl_barrier_timeout_new_group_non_member (__main__.CommTest) is flaky, see failure - 

```
ERROR [100.094s]: test_nccl_barrier_timeout_new_group_non_member (__main__.CommTest)
02:56:49 ----------------------------------------------------------------------
02:56:49 Traceback (most recent call last):
02:56:49   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 424, in wrapper
02:56:49     self._join_processes(fn)
02:56:49   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 643, in _join_processes
02:56:49     self._check_return_codes(elapsed_time)
02:56:49   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 695, in _check_return_codes
02:56:49     i, elapsed_time
02:56:49 RuntimeError: Process 1 terminated or timed out after 100.07976341247559 seconds
```

link to example failure: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/1309/console

Only seen it on ROCM so far. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by rohan-varma** [comment]
Removing oncall: distributed label as it appears to be ROCM specific. Please feel free to loop in distributed if it turns out to be a wider issue or debugging help is needed.

**Comment by janeyx99** [comment]
Added ROCm specific platform since this hsouldn't be flaky elsewhere

**Comment by jaglinux** [comment]
This test works fine after KFD upgrade to ROCm 5.3
cc @jithunnair-amd @jeffdaily , Can you please close this issue ?
(Note that distributed tests CI is disabled for ROCm)

**Comment by jithunnair-amd** [comment]
Closing this issue since it passed in our local testing with ROCm5.3 KFD. Reference: https://ontrack-internal.amd.com/browse/SWDEV-334828
