### ISSUE TITLE
TCPStore( TypeError: __init__(): incompatible constructor arguments. The following argument types are supported

### ISSUE THREAD

**Issue by AfrinaVT** [pytorch/pytorch#67172]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
I am trying to use distributed data parallel by import torch.utils.data.distributed using the funciton 
dist.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
                                    world_size=args.world_size, rank=args.rank, timeout=timedelta(seconds=300)). But running into this error 

torch._C._distributed_c10d.TCPStore(host_name: str, port: int, world_size: int = -1, is_master: bool = False, timeout: datetime.timedelta = datetime.timedelta(seconds=300),
 wait_for_workers: bool = True, multi_tenant: bool = False)
Invoked with: 'host_name', post, 8, False, datetime.timedelta(seconds=300); kwargs: multi_tenant=True
## Code example
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.backends.cudnn as cudnn
import torch.distributed as dist
import torch.optim
import torch.multiprocessing as mp
import torch.utils.data
import torch.utils.data.distributed
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import torchvision.models as models
from torchvision.datasets import CIFAR10, CIFAR100
# args.rank = 0,1,2,3,4,5,6,7 for 8 gpus
dist.init_process_group(backend='nccl', init_method='env://', world_size=8,
                                rank=args.rank, timeout=timedelta(seconds=300)) 
## System Info
Please copy and paste the output from our
dist.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "/home/user/.conda/envs/env_name/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 576, in init_process_group
    dist.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "/home/user/.conda/envs/env_name/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 576, in init_process_group
Traceback (most recent call last):
  File "/beegfs/work/afrina/folder/python_file.py", line 504, in <module>
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/user/.conda/envs/env_name/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 229, in _env_rendezvous_handler
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/user/.conda/envs/env_name/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 229, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/home/afrina/.conda/envs/
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).
Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.7.1908 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.3.0           h06a4308_520
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.21.2           py39h20f2e39_0
[conda] numpy-base                1.21.2           py39h79a1101_0
[conda] pytorch                   1.10.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.0               py39_cu113    pytorch
[conda] torchvision               0.11.1               py39_cu113    pytorch
                                                       
- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source): conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
- Build command you used (if compiling from source):
- OS:
- PyTorch version: 1.10.0
- Python version:3.9
- CUDA/cuDNN version:11.3
- GPU models and configuration: Nvidia Tesla T4
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

I can't understand what the problem is. I cant find anything is the interment too

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by skpig** [comment]
@cbalioglu I've also encountered the same error. 
1. environment
    Python: 3.6
    Pytorch: 1.10.1
2. Script
```
def init(rank, world_size):
    dist.init_process_group(
        backend='nccl',
        init_method='env://',
        world_size=world_size,
        rank=rank
    )

def debug_torch():
    world_size = 4
    os.environ['MASTER_ADDR'] = 'localhost'  #
    os.environ['MASTER_PORT'] = '123456'  #
    os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3'

    mp.spawn(init, nprocs=world_size, args=(world_size,))
```

**Comment by AfrinaVT** [comment]
I was having this issue with pytorch 1.10 . so I downgraded to pytorch 1.8 and the error went away.

**Comment by cbalioglu** [comment]
@AfrinaVT @skpig the problem in both use cases lie in the port number. `TCPStore` internally uses a 16-bit integer for representing the port. In both examples the specified port number (92345 for @AfrinaVT and 123456 for @skpig) is higher than the maximum 16-bit integer value (65536). I agree that the error description is not clear enough though. This is an area where we actively work on.

**Comment by skpig** [comment]
@cbalioglu Thank you, it works! BTW, the port number (123456) worked fine when I used torch 1.8 before. Maybe there is something different between the two versions.

**Comment by cbalioglu** [comment]
Most likely it was a bug and we were simply overflowing your port number, meaning 123456 was becoming 57920 (123456 - 65536). Technically there is no way to move beyond 65536 since this is a limit set by the operating system.

**Comment by H-Huang** [comment]
Added a small pr to provide a better error message https://github.com/pytorch/pytorch/pull/71863
