### ISSUE TITLE
OOM with a lot of GPU memory left

### ISSUE THREAD

**Issue by jakwisn** [pytorch/pytorch#67680]
## 🐛 Bug

When building models with transformers pytorch says my GPU does not have memory without plenty of memory being there at disposal. I have been trying to tackle this problem for some time now, I have tried switching os, lowering batch sizes etc/ Every time (both on personal machine and cluster) it gives me error like this: 

```
RuntimeError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 6.00 GiB total capacity; 4.26 GiB already allocated; 0 bytes free; 4.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
It always happens at the first/second step

There has ben similar problems but I did not find any solution for this. I also described my problem [here](https://github.com/explosion/spaCy/issues/9578) but now I think it is more of problem with pytorch.

## To Reproduce

1. I followed https://huggingface.co/transformers/training.html tutorial 

## Expected behavior

I would expect the tutorial to work. I expect there to be some logical answer to the problem. 

## Environment
```
PyTorch version: 1.10.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.11 (default, Nov  2 2021, 10:56:09)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti
Nvidia driver version: 510.06
cuDNN version: Probably one of the following:
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.5
[pip3] torch==1.10.0
[pip3] torchaudio==0.8.2
[pip3] torchvision==0.10.1
[conda] Could not collect
```

## Additional context
Putting all info if this helps: 

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_1721/1645165363.py in <module>
      7     for batch in train_dataloader:
      8         batch = {k: v.to(device) for k, v in batch.items()}
----> 9         outputs = model(**batch)
     10         loss = outputs.loss
     11         loss.backward()

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, labels, output_attentions, output_hidden_states, return_dict)
   1500         return_dict = return_dict if return_dict is not None else self.config.use_return_dict
   1501 
-> 1502         outputs = self.bert(
   1503             input_ids,
   1504             attention_mask=attention_mask,

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict)
    969             past_key_values_length=past_key_values_length,
    970         )
--> 971         encoder_outputs = self.encoder(
    972             embedding_output,
    973             attention_mask=extended_attention_mask,

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py in forward(self, hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict)
    566                 )
    567             else:
--> 568                 layer_outputs = layer_module(
    569                     hidden_states,
    570                     attention_mask,

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py in forward(self, hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, past_key_value, output_attentions)
    454         # decoder uni-directional self-attention cached key/values tuple is at positions 1,2
    455         self_attn_past_key_value = past_key_value[:2] if past_key_value is not None else None
--> 456         self_attention_outputs = self.attention(
    457             hidden_states,
    458             attention_mask,

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py in forward(self, hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, past_key_value, output_attentions)
    385         output_attentions=False,
    386     ):
--> 387         self_outputs = self.self(
    388             hidden_states,
    389             attention_mask,

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py in forward(self, hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, past_key_value, output_attentions)
    317         # This is actually dropping out entire tokens to attend to, which might
    318         # seem a bit unusual, but is taken from the original Transformer paper.
--> 319         attention_probs = self.dropout(attention_probs)
    320 
    321         # Mask heads if we want to

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/torch/nn/modules/dropout.py in forward(self, input)
     56 
     57     def forward(self, input: Tensor) -> Tensor:
---> 58         return F.dropout(input, self.p, self.training, self.inplace)
     59 
     60 

~/.cache/pypoetry/virtualenvs/mars-48yr609M-py3.8/lib/python3.8/site-packages/torch/nn/functional.py in dropout(input, p, training, inplace)
   1167     if p < 0.0 or p > 1.0:
   1168         raise ValueError("dropout probability has to be between 0 and 1, " "but got {}".format(p))
-> 1169     return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
   1170 
   1171 

RuntimeError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 6.00 GiB total capacity; 4.26 GiB already allocated; 0 bytes free; 4.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by lrongzheni** [comment]
The similar Problem:
Epoch 0:   0%|                                                                              | 3/12784 [00:07<8:32:20,  2.41s/it, loss=7.35, v_num=5]/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:129: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
saving checkpoint now
saving models now/22..
try calling the pl_module save
Epoch 0:   0%|                                                                              | 3/12784 [00:07<9:08:09,  2.57s/it, loss=7.35, v_num=5]
Traceback (most recent call last):
  File "/data/lirongzhen/PrefixTuning/seq2seq/finetune.py", line 878, in <module>
    main(args)
  File "/data/lirongzhen/PrefixTuning/seq2seq/finetune.py", line 779, in main
    trainer: pl.Trainer = generic_train(
  File "/data/lirongzhen/PrefixTuning/seq2seq/lightning_base.py", line 795, in generic_train
    trainer.fit(model)
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 470, in fit
    results = self.accelerator_backend.train()
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 68, in train
    results = self.train_or_test()
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 69, in train_or_test
    results = self.trainer.train()
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 521, in train
    self.train_loop.run_training_epoch()
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py", line 560, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py", line 687, in run_training_batch
    self.training_step_and_backward(
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py", line 816, in training_step_and_backward
    self.backward(result, optimizer, opt_idx)
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py", line 836, in backward
    result.closure_loss = self.trainer.accelerator_backend.backward(
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 98, in backward
    closure_loss = self.trainer.precision_connector.backend.backward(
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/pytorch_lightning/plugins/native_amp.py", line 46, in backward
    model.backward(closure_loss, optimizer, opt_idx)
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 1152, in backward
    loss.backward(*args, **kwargs)
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data/anaconda3/envs/PrefixTuning/lib/python3.9/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 1.20 GiB (GPU 0; 47.54 GiB total capacity; 41.43 GiB already allocated; 900.75 MiB free; 44.68 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by rastinbw** [comment]
I am fine-tuning bert with mlm and nsp tasks and have Same problem. I tried that on two systems and two operating systems (one with 4GB gpu ram and one with 2GB gpu ram): 

Some weights of BertForPreTraining were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['cls.predictions.decoder.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                                                                                          | 0/159 [00:00<?, ?it/s]test.py:75: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
  0%|                                                                                                                          | 0/159 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    outputs = model(input_ids, attention_mask=attention_mask,
  File "/home/rastinbw/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rastinbw/anaconda3/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 1093, in forward
    outputs = self.bert(
  File "/home/rastinbw/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rastinbw/anaconda3/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 995, in forward
    encoder_outputs = self.encoder(
  File "/home/rastinbw/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rastinbw/anaconda3/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 582, in forward
    layer_outputs = layer_module(
  File "/home/rastinbw/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rastinbw/anaconda3/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 470, in forward
    self_attention_outputs = self.attention(
  File "/home/rastinbw/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rastinbw/anaconda3/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 401, in forward
    self_outputs = self.self(
  File "/home/rastinbw/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rastinbw/anaconda3/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 305, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 1.96 GiB total capacity; 1.06 GiB already allocated; 256.00 KiB free; 1.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by oxyzchen** [comment]
maybe you can change CUDA runtime version: 10.1.243 to 10.2

**Comment by huangjin520** [comment]
Hi, I encounter the same error with you. After ten minutes, I run the code without change again, But it runs normally.  So confused.

**Comment by nikvaessen** [comment]
Downgrading to PyTorch 1.09 solved this issue for me. In particular, I noticed it only when I used CtcLoss, not cross-entropy loss.

**Comment by huangjin520** [comment]
I solved the problem by killing the PID to release the cache in Linux  `kill -9 PID_number` .  And then I run the network normally.

**Comment by JShull** [comment]
I am getting the exact same errors as @jakwisn . Same problem as well - building a Roberta model using MLM, It sucks up all the memory on the first step.
[MLM_Python_Error.txt](https://github.com/pytorch/pytorch/files/7557562/MLM_Python_Error.txt)

**Comment by nikvaessen** [comment]
I also have had success with downgrading the transformers library. This indicates that it might be related to transformers instead of PyTorch.

**Comment by JShull** [comment]
> I also have had success with downgrading the transformers library. This indicates that it might be related to transformers instead of PyTorch, for the Wav2Vec2 network in my case. I downgraded from 4.12 to 4.8.

I tried downgrading, used 4.8.0 and got the same error as above. I have not tried downgrading PyTorch - will try that next.

**Comment by JShull** [comment]
> Downgrading to PyTorch 1.09 solved this issue for me. In particular, I noticed it only when I used CtcLoss, not cross-entropy loss.

This worked for me. Thank you for the information! 💯  
I am now running 1.09 and also transformers 4.8.0 @nikvaessen

**Comment by loretoparisi** [comment]
I have the same error with

```
conda install -c pytorch pytorch==1.7.0 torchvision cudatoolkit=11.0 --yes 
pip install -U cython transformers==3.1.0 nltk pytorch-metric-learning joblib pytorch-lightning==1.1.8 pandas
```

**Comment by rmunia** [comment]
I am also facing the same issue. Can anyone tell me what is the solution for this?

**Comment by Anticonformiste** [comment]
Hi, I solved the problem using a context manager :
`with torch.no_grad():
    # Your eval code`

**Comment by aced125** [comment]
I am getting this issue as well on pt1.10

**Comment by flydragon2018** [comment]
I met this problem in colab pro.

I  reset factory runtime, It works.

**Comment by serhatataman** [comment]
@JShull , could you please share the code that you downgraded both PyTorch and transformers?

**Comment by JShull** [comment]
Hey @serhatataman I went back through my notes and this is what I had on the setup/install - this was after I had already setup the more recent versions which is sort of funky because I'm technically using CUDA 11.5

- ![CUDA 11.5](https://user-images.githubusercontent.com/12342337/147898133-54d4ad62-98e3-4e53-bb46-9003390915dc.png)

- Torch install code snippet was from their site and can be found [here](https://pytorch.org/get-started/previous-versions/)
  - `pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
  - ![TORCHVersion](https://user-images.githubusercontent.com/12342337/147898131-87563dfd-942b-4dc0-ae89-997b15d1fdb9.png)
- I ran the same transformer code you ran but I did uninstall the version prior to this
  - `pip uninstall transformers`
  - `pip install --upgrade transformers==4.8.0`
  - ![TRANSFORMERVersion](https://user-images.githubusercontent.com/12342337/147898129-af5c9415-2e6d-43f2-aefe-f73ba4c3b615.png)

**Comment by watchwater** [comment]
I encountered the same error. I increased dataloader's num_workers from 6 to 12 and didn't change anything, it worded. It's really confusing.

**Comment by quincytann** [comment]
> Hey @serhatataman I went back through my notes and this is what I had on the setup/install - this was after I had already setup the more recent versions which is sort of funky because I'm technically using CUDA 11.5
> 
> * ![CUDA 11.5](https://user-images.githubusercontent.com/12342337/147898133-54d4ad62-98e3-4e53-bb46-9003390915dc.png)
> * Torch install code snippet was from their site and can be found [here](https://pytorch.org/get-started/previous-versions/)
>   
>   * `pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
>   * ![TORCHVersion](https://user-images.githubusercontent.com/12342337/147898131-87563dfd-942b-4dc0-ae89-997b15d1fdb9.png)
> * I ran the same transformer code you ran but I did uninstall the version prior to this
>   
>   * `pip uninstall transformers`
>   * `pip install --upgrade transformers==4.8.0`
>   * ![TRANSFORMERVersion](https://user-images.githubusercontent.com/12342337/147898129-af5c9415-2e6d-43f2-aefe-f73ba4c3b615.png)

I am the same version of CUDA, same question: did you solve it?

> Hey @serhatataman I went back through my notes and this is what I had on the setup/install - this was after I had already setup the more recent versions which is sort of funky because I'm technically using CUDA 11.5
> 
> * ![CUDA 11.5](https://user-images.githubusercontent.com/12342337/147898133-54d4ad62-98e3-4e53-bb46-9003390915dc.png)
> * Torch install code snippet was from their site and can be found [here](https://pytorch.org/get-started/previous-versions/)
>   
>   * `pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
>   * ![TORCHVersion](https://user-images.githubusercontent.com/12342337/147898131-87563dfd-942b-4dc0-ae89-997b15d1fdb9.png)
> * I ran the same transformer code you ran but I did uninstall the version prior to this
>   
>   * `pip uninstall transformers`
>   * `pip install --upgrade transformers==4.8.0`
>   * ![TRANSFORMERVersion](https://user-images.githubusercontent.com/12342337/147898129-af5c9415-2e6d-43f2-aefe-f73ba4c3b615.png)

I am the same version of CUDA, same question: did you solve it?

**Comment by mitbal** [comment]
I've encountered the same error when I tried to extract bert embedding with more than 10 sentence as the input. Now I can only run it for one sentence at a time, which is incredibly slow. I'm using cuda version 11.5 and pytorch version 1.10

**Comment by aflah02** [comment]
> > Hey @serhatataman I went back through my notes and this is what I had on the setup/install - this was after I had already setup the more recent versions which is sort of funky because I'm technically using CUDA 11.5
> > 
> > * ![CUDA 11.5](https://user-images.githubusercontent.com/12342337/147898133-54d4ad62-98e3-4e53-bb46-9003390915dc.png)
> > * Torch install code snippet was from their site and can be found [here](https://pytorch.org/get-started/previous-versions/)
> >   
> >   * `pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
> >   * ![TORCHVersion](https://user-images.githubusercontent.com/12342337/147898131-87563dfd-942b-4dc0-ae89-997b15d1fdb9.png)
> > * I ran the same transformer code you ran but I did uninstall the version prior to this
> >   
> >   * `pip uninstall transformers`
> >   * `pip install --upgrade transformers==4.8.0`
> >   * ![TRANSFORMERVersion](https://user-images.githubusercontent.com/12342337/147898129-af5c9415-2e6d-43f2-aefe-f73ba4c3b615.png)
> 
> I am the same version of CUDA, same question: did you solve it?

I think he did based on this (https://github.com/pytorch/pytorch/issues/67680#issuecomment-974400702) and was sharing his fix

**Comment by serhatataman** [comment]
Hey guys, sorry for bein afk. Thank you so much @JShull . The code below solved my issue in Google Colab
`!pip install torch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 torchtext==0.10.0`
`!pip install transformers==4.8.0`

**Comment by scalaboy** [comment]
is anybody solve this problem?

**Comment by Omarnabk** [comment]
I was stuck on this problem for several hours. I had a machine with 5GPUs, each with 24G of RAM, and whatever I run it gives out of memory. I found that there was a process running on one GPU machine while the default behaviour is to distribute the same batch size across all the machines --> it gives OOM error. 

To solve it, I had to tell pytorch which GPU to use exactly. In this case, I can avoid the busy machine and use only the available ones!!!

```
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="0,1"

```

**Comment by PabloVD** [comment]
I had the same problem using pytorch-geometric. I just restarted the computer and then it ran normally... Probably the gpu memory was already full.

**Comment by twsl** [comment]
I proposed https://github.com/pytorch/pytorch/issues/72117 to deal with situations like this without having to restart the pc.

**Comment by TropComplique** [comment]
Hi. I have the similar problem.

My model trains like it should.
But when I reduce the number of layers, the training fails with the following error: 
```
RuntimeError: CUDA out of memory. Tried to allocate 4.38 GiB (GPU 0; 23.70 GiB total capacity; 12.78 GiB already allocated; 4.38 GiB free; 17.60 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

This is very weird and counterintuitive.

**Comment by 54724531** [comment]
I've been battling this memory issue for several weeks now; empty.cache() doesn't clear it for some reason, and I cannot kill anything in Windows Tastk Manger.  I'm hoping devs will add some sort of memory flush flag, back to google to look for a solution...lol

**Comment by TropComplique** [comment]
I solved my problem by downgrading to `torch==1.9.1`.

**Comment by lorellav** [comment]
> Hey guys, sorry for bein afk. Thank you so much @JShull . The code below solved my issue in Google Colab `!pip install torch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 torchtext==0.10.0` `!pip uninstall transformers` `!pip install transformers==4.8.0`

This solved my problem, thank you!

**Comment by LeanderK** [comment]
I also experience this. `5.61 GiB (GPU 3; 31.75 GiB total capacity; 10.91 GiB already allocated; 5.31 GiB free; 24.88 GiB reserved in total by PyTorch`. I only evaluate a model and work with huge batch-sizes, I can't share my code because my work isn't published yet but I think a reproduction would be to take a complicated model and evaluate it over and over with maximum batch-sizes. It's hard to adjust batch-sizes for me since interact with the rest of my code.

**Comment by gahdritz** [comment]
Same issue here, but my case is really extreme:

`RuntimeError: CUDA out of memory. Tried to allocate 7.63 GiB (GPU 0; 39.59 GiB total capacity; 23.86 GiB already allocated; 4.61 GiB free; 32.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I have a conspiracy theory that this only happens when the size of the attempted allocation plus the size of the "already allocated" memory happens to be less than the total reserved by PyTorch. Unless I'm mistaken, that is also true of every reported error in this thread. Could it be that whatever mechanism decides how much memory to reserve ignores the existence of memory fragmentation, erroneously making its decision not to allocate more memory based on that simple sum?

**Comment by lianghsun** [comment]
> > Hey guys, sorry for bein afk. Thank you so much @JShull . The code below solved my issue in Google Colab `!pip install torch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 torchtext==0.10.0` `!pip uninstall transformers` `!pip install transformers==4.8.0`
> 
> This solved my problem, thank you!

Hi all, I installed the exact same version as above however still facing the OOM problem
```
- torch                1.9.0
- torchaudio           0.9.0
- torchtext            0.10.0
- torchvision          0.10.0
- transformers         4.8.0.dev0
```

I use `run_clm.py` to run the [wikitext turtorial](https://github.com/huggingface/transformers/tree/main/examples/pytorch/language-modeling), and I use the version 4.8.0.dev0 of the `run_clm.py`. Is there anyone have the same problem?

**Comment by gauraviiita** [comment]
I faced same problem and resolve it by degrading the pytroch version from 1.10.1 to 1.8.1 with cuda 11.3.
In my case I am using GPU RTX 3060 which works only with cuda version 11.3 or above and when I installed cuda 11.3 it comes with pytorch 1.10.1. So I degraded the pytorch version and now it working fine.

$ pip3 install torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by outkastpharaoh** [comment]
Trying to follow this but having issues. Not sure how exactly to downgrade pytorch. I've tried pasting the codes listed. I think I am supposed to use conda and not pip.  I am using an Nvidia GForce RTX 3060. I am not familiar with any of this but I just want stable diffusion to stop the cuda out of memory. I've also looked into trying to run it off the gpu, with these instructions https://www.youtube.com/watch?v=tox47_WQmPw  --- but the part at the end, I'm not sure where I am supposed to be saving that information into or just run it in the spyder and its done? Please help.

**Comment by aleimu** [comment]
mark
