### ISSUE TITLE
sparse.mm: CUDA error: internal error when calling `cusparseSpGEMM_workEstimation [...]`

### ISSUE THREAD

**Issue by saluto** [pytorch/pytorch#68323]
Consider the following script:

```python
A = torch.sparse_coo_tensor(
  indices=[
    [1500, 1505, 1506],
    [8347, 8347, 8347],
  ],
  values = [1., 1., 1.],
  size = [2523, 13716],
  device = 'cuda:0',
)
B = torch.sparse_coo_tensor(
  indices=[
    [8347, 8347, 8347],
    [1500, 1505, 1506],
  ],
  values = [1., 1., 1.],
  size = [13716, 2523],
  device = 'cuda:0',
)
torch.sparse.mm(A, B)
```

Running it, I get this error:

```
[...]
  File "[...]/python3.8/site-packages/torch/sparse/__init__.py", line 90, in mm
    return torch._sparse_sparse_matmul(mat1, mat2)
RuntimeError: CUDA error: internal error when calling `cusparseSpGEMM_workEstimation( handle, opA, opB, &alpha, matA, matB, &beta, matC, computeType, CUSPARSE_SPGEMM_DEFAULT, spgemmDesc, &bufferSize1, dBuffer1)`
```

Is this a bug or a user error?
My thesis deadline is coming fast, so any help would be greatly appreciated.
Anyway, thanks for your valuable work!

---

PyTorch version: 1.10.0+cu113
GPU: Nvidia Titan Xp (via Slurm)
CUDA Version: 11.4
OS: Ubuntu 20.04.3 LTS

**Comment by saluto** [comment]
The error from above occurs when running e.g. on this hardware:

- (36 x) Intel Xeon CPU E5-2697 v4
- (8 x) Nvidia Titan Xp (each 12 GB VRAM)
- ca. 500 GB RAM

On the following hardware it runs **without** error:

- (36 x) Intel Xeon Gold 6254
- (8 x) Nvidia Rtx A6000 (each 48 GB VRAM)
- ca. 1.5 TB RAM

Though it is sparse, could the error be due to not enough (V)RAM, for some reason? Or a bug with the Titan Xp?

**Comment by cpuhrsch** [comment]
I tried reproducing this, but didn't get an error.
```
>>> import torch
>>> A = torch.sparse_coo_tensor(
...   indices=[
...     [1500, 1505, 1506],
...     [8347, 8347, 8347],
...   ],
...   values = [1., 1., 1.],
...   size = [2523, 13716],
...   device = 'cuda:0',
... )

>>> B = torch.sparse_coo_tensor(
...   indices=[
...     [8347, 8347, 8347],
...     [1500, 1505, 1506],
...   ],
...   values = [1., 1., 1.],
...   size = [13716, 2523],
...   device = 'cuda:0',
... )
>>> torch.sparse.mm(A, B)
tensor(indices=tensor([[1500, 1500, 1500, 1505, 1505, 1505, 1506, 1506, 1506],
                       [1500, 1505, 1506, 1500, 1505, 1506, 1500, 1505, 1506]]),
       values=tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]),
       device='cuda:0', size=(2523, 2523), nnz=9, layout=torch.sparse_coo)
```

I'm ran this on an A100. Could you collect more information by running https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py and posting the result?

**Comment by saluto** [comment]
[`collect_env.py`](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py) output on problematic machine:

```
PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-37-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.4.48
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000
GPU 4: NVIDIA RTX A6000
GPU 5: NVIDIA RTX A6000
GPU 6: NVIDIA RTX A6000
GPU 7: NVIDIA RTX A6000

Nvidia driver version: 470.74
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.3
[pip3] torch==1.10.0+cu113
[pip3] torch-scatter==2.0.9
[conda] Could not collect
```
The script uses `ldconfig -p | grep libcudnn | rev | cut -d" " -f1 | rev` to get the CuDNN versions, but this does not find any CuDNN libraries in our setup. So instead I run `ldconfig -N -v $(sed 's/:/ /' <<< $LD_LIBRARY_PATH) | grep libcudnn | rev | cut -d" " -f1 | rev` with the following output:

```
libcudnn_cnn_infer.so.8.2.4
libcudnn_adv_infer.so.8.2.4
libcudnn_cnn_train.so.8.2.4
libcudnn_ops_train.so.8.2.4
libcudnn_adv_train.so.8.2.4
libcudnn.so.8.2.4
libcudnn_ops_infer.so.8.2.4
```

I also tried with cuda 11.3.1 and cudnn 8.2.4.15 instead of the cuda 11.4.0 and cudnn 8.2.1.32 from above. (Otherwise same as above). This gave the same error.

I also tried on a GTX 1050 Ti. (Otherwise same as above.) This gave the same error.

As I already commented, I also tried with Rtx A6000. More concretely:

```
PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-37-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.4.48
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000
GPU 4: NVIDIA RTX A6000
GPU 5: NVIDIA RTX A6000
GPU 6: NVIDIA RTX A6000
GPU 7: NVIDIA RTX A6000

Nvidia driver version: 470.74
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.3
[pip3] torch==1.10.0+cu113
[pip3] torch-scatter==2.0.9
[conda] Could not collect
```

This did work without error, with all mentioned cuda and cudnn versions.

An all machines, running on CPU instead of GPU resulted in no error.

Let me know if there is anything else I can do to help.

**Comment by rusty1s** [comment]
I can also reproduce this on PyTorch 1.11:
```
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: glibc-2.27

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1059-aws-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 450.142.00
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.11.0
[pip3] torch-cluster==1.6.0
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.13
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.21.2           py39h20f2e39_0
[conda] numpy-base                1.21.2           py39h79a1101_0
[conda] pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-cluster             1.6.0                     dev_0    <develop>
[conda] torch-scatter             2.0.9                     dev_0    <develop>
[conda] torch-sparse              0.6.13                    dev_0    <develop>
[conda] torch-spline-conv         1.2.1                     dev_0    <develop>
[conda] torchaudio                0.11.0               py39_cu113    pytorch
[conda] torchvision               0.12.0               py39_cu113    pytorch
```

**Comment by cpuhrsch** [comment]
@IvanYashchuk - can you take a look?

**Comment by jeongwhanchoi** [comment]
I have the same issue on Pytorch 1.90 with CUDA 11.1:
```
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.9.6 (default, Aug 18 2021, 19:38:01)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-180-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.4.48
GPU models and configuration: 
GPU 0: Quadro RTX 8000
GPU 1: NVIDIA RTX A6000
GPU 2: Quadro RTX 8000
GPU 3: NVIDIA RTX A6000

Nvidia driver version: 470.129.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.0
[pip3] torchdiffeq==0.2.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.20.3           py39hf144106_0  
[conda] numpy-base                1.20.3           py39h74d4b33_0  
[conda] pytorch                   1.9.0           py3.9_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchdiffeq               0.2.2                    pypi_0    pypi
```

**Comment by im0qianqian** [comment]
I also encountered the same error, but I found that if the shape of the sparse matrix is modified, this error will not occur.  Is there a solution at present? My program often terminates due to this error halfway through.

```python
import torch

A = torch.sparse.FloatTensor(  indices=torch.tensor([
     [1500, 1505, 1506],
     [8347, 8347, 8347],
   ]),
   values = torch.tensor([1., 1., 1.]),
   size = [2524, 13716],).cuda()
B = A.t()
A @ B   # success

A = torch.sparse.FloatTensor(  indices=torch.tensor([
     [1500, 1505, 1506],
     [8347, 8347, 8347],
   ]),
   values = torch.tensor([1., 1., 1.]),
   size = [2523, 13716],).cuda()
B = A.t()
A @ B   # fail
```

Pytorch 1.13.1 with CUDA 11.6

```
Collecting environment information...
PyTorch version: 1.13.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Centos 7 (x86_64)
GCC version: (GCC) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.24

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.19.48-centos7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 460.106.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz
Stepping:              1
CPU MHz:               2494.202
BogoMIPS:              4994.64
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              40960K
NUMA node0 CPU(s):     0-63

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.1+cu116
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py38h7f8727e_0
[conda] mkl_fft                   1.3.1            py38hd3c417c_0
[conda] mkl_random                1.2.2            py38h51133e4_0
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] numpy-base                1.23.5           py38h31eccc5_0
[conda] torch                     1.13.1+cu116             pypi_0    pypi
```

**Comment by cpuhrsch** [comment]
@im0qianqian - Hm, can you try constructing these sparse Tensors using our factory function [sparse_coo_tensor](https://pytorch.org/docs/master/generated/torch.sparse_coo_tensor.html#torch.sparse_coo_tensor)? Then you can also set `check_invariants=True` at construction time. This way we can make sure this isn't due to the `torch.sparse.FloatTensor` class constructor, whose use we don't really advocate anymore. Unfortunately you'll need to install a nightly or wait for the next PyTorch release to try this.

**Comment by im0qianqian** [comment]
> @im0qianqian - Hm, can you try constructing these sparse Tensors using our factory function [sparse_coo_tensor](https://pytorch.org/docs/master/generated/torch.sparse_coo_tensor.html#torch.sparse_coo_tensor)? Then you can also set `check_invariants=True` at construction time. This way we can make sure this isn't due to the `torch.sparse.FloatTensor` class constructor, whose use we don't really advocate anymore. Unfortunately you'll need to install a nightly or wait for the next PyTorch release to try this.

Thank you very much!
I got a suggestion from your reply. I didn't encounter this error after trying to install the pytorch nightly. After that, I also tried to install pytorch 1.13.1+cu117, and there was no error. My problem has been solved. 👍
