### ISSUE TITLE
cuda runtime error (8) : invalid device function - adding cuda tensors

### ISSUE THREAD

**Issue by Jordan2386** [pytorch/pytorch#686]
Newly installed PyTorch in Conda; CUDA is available, but outputs error on simple cuda tensor addition:

```
print(torch.cuda.is_available())

x = torch.rand(5, 3)
y = torch.rand(5, 3)
x = x.cuda()
y = y.cuda()
x + y
```

```
True

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-91eb0104733f> in <module>()
      5 x = x.cuda()
      6 y = y.cuda()
----> 7 x+y

/home/scratch/root/anaconda3/lib/python3.5/site-packages/torch/tensor.py in __add__(self, other)
    395     # TODO: add tests for operators
    396     def __add__(self, other):
--> 397         return self.add(other)
    398     __radd__ = __add__
    399 

RuntimeError: cuda runtime error (8) : invalid device function at /data/users/soumith/miniconda2/conda-bld/pytorch-cuda80-0.1.8_1486040640754/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:246

```

About my system: Functioning CUDA 8.0 with GPU NVIDIA GeForce GT 720M

**Comment by apaszke** [comment]
It seems that your GPU has compute capability of only 2.1 and I'm not sure if we support that. You could try to rebuild from source, but I can't guarantee it will be ok.

@soumith what's the lowest cc we require?

**Comment by apaszke** [comment]
Also, #665 seems related

**Comment by soumith** [comment]
@Jordan2386 your GPU is old enough that it has a CUDA Capability < 3.0.
The pytorch binaries dont support it, but if you build from source it might work.
However, we dont support or recommend using the GPU on this card, as it will likely be slower than and has no benefits compared to using the CPU.

**Comment by Jordan2386** [comment]
I just ordered a laptop with GTX 970M, I hope it works on that one!

**Comment by soumith** [comment]
yes it does

**Comment by adelsalehali1982** [comment]
I am trying to run this code :
https://github.com/kuangliu/pytorch-cifar

but getting this error :
THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=84 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "main.py", line 136, in <module>
    train(epoch)
  File "main.py", line 86, in train
    outputs = net(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 57, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 68, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 30, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 25, in scatter
    return scatter_map(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 18, in scatter_map
    return tuple(zip(*map(scatter_map, obj)))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return Scatter(target_gpus, dim=dim)(obj)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/_functions.py", line 59, in forward
    outputs = comm.scatter(input, self.target_gpus, self.chunk_sizes, self.dim, streams)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/comm.py", line 162, in scatter
    with torch.cuda.device(device), torch.cuda.stream(stream):
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 132, in __enter__
    torch._C._cuda_setDevice(self.idx)
RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:84
--------------------------------------------
I have cuda 8.0 which works will with theano 
ubuntu 14.04 and my GPU card has more than 3.0 computation capability

**Comment by fmassa** [comment]
@adelsalehali1982 Your error is unrelated to this issue, and happens because the code you are running supposes that 4 GPUs are used (if gpus are enabled), and you probabmy have less than 4 GPUs in your machine. You can fix that by changing the line with DataParallel to only use 1 or 2 GPUs

**Comment by adelsalehali1982** [comment]
Problem solved! thanks @fmassa

**Comment by kedarpathak** [comment]
class Generator(nn.Module):

    def __init__(self, input_size, output_size, hidden_dims):

        super(Generator, self).__init__()

        self.layers = []

        

        prev_dim = input_size

        for hidden_dim in hidden_dims:

            self.layers.append(nn.Linear(prev_dim, hidden_dim))

            self.layers.append(nn.ReLU(True))

            prev_dim = hidden_dim

        self.layers.append(nn.Linear(prev_dim, output_size))

        

        self.layer_module = ListModule(*self.layers)

        

    def forward(self, x):

        out = x

        for layer in self.layers:

            out = layer(out)

        return out

​

class Discriminator(nn.Module):

    def __init__(self, input_size, output_size, hidden_dims):

        super(Discriminator, self).__init__()

        self.layers = []

        

        prev_dim = input_size

        for idx, hidden_dim in enumerate(hidden_dims):

            self.layers.append(nn.Linear(prev_dim, hidden_dim))

            self.layers.append(nn.ReLU(True))

            prev_dim = hidden_dim

            

        self.layers.append(nn.Linear(prev_dim, output_size))

        self.layers.append(nn.Sigmoid())

        

        self.layer_module = ListModule(*self.layers)

​

    def forward(self, x):

        out = x

        for layer in self.layers:

            out = layer(out)

        return out.view(-1, 1)

​

# network

hidden_dim = 128

g_num_layer = 3

d_num_layer = 5

​

G_AB = Generator(2, 2, [hidden_dim] * g_num_layer)

G_BA = Generator(2, 2, [hidden_dim] * g_num_layer)

​

D_A = Discriminator(2, 1, [hidden_dim] * d_num_layer)

D_B = Discriminator(2, 1, [hidden_dim] * d_num_layer)

​

G_AB.cuda()

G_BA.cuda()

D_A.cuda()

D_B.cuda()

​

# optimizer

lr = 0.0002

beta1 = 0.5

beta2 = 0.999

​

d = nn.MSELoss()

bce = nn.BCELoss()

​

optimizer_d = torch.optim.Adam(

    chain(D_A.parameters(), D_B.parameters()), lr=lr, betas=(beta1, beta2))

optimizer_g = torch.optim.Adam(

    chain(G_AB.parameters(), G_BA.parameters()), lr=lr, betas=(beta1, beta2))

​

# training

num_epoch = 50000

​

real_label = 1

fake_label = 0

​

real_tensor = Variable(torch.FloatTensor(batch_size).cuda())

_ = real_tensor.data.fill_(real_label)

print(real_tensor.sum())

​

fake_tensor = Variable(torch.FloatTensor(batch_size).cuda())

_ = fake_tensor.data.fill_(fake_label)

print(fake_tensor.sum())

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-b559c2ac8db1> in <module>()
     77 
     78 real_tensor = Variable(torch.FloatTensor(batch_size).cuda())
---> 79 _ = real_tensor.data.fill_(real_label)
     80 print(real_tensor.sum())
     81 

RuntimeError: cuda runtime error (8) : invalid device function at /py/conda-bld/pytorch_1493677666423/work/torch/lib/THC/generic/THCTensorMath.cu:15

**Comment by keon** [comment]
P6000 seem to have the same problem
```
>>> import torch
>>> x = torch.rand(5, 3)
>>> y = torch.rand(5, 3)
>>> x = x.cuda()
>>> y = y.cuda()
>>> x + y
```

THCudaCheck FAIL file=/home/paperspace/Desktop/pytorch/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu line=301 error=8 : invalid device function
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paperspace/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/tensor.py", line 293, in __add__
    return self.add(other)
RuntimeError: cuda runtime error (8) : invalid device function at /home/paperspace/Desktop/pytorch/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:301

**Comment by volf52** [comment]
GeForce GTX 960M : cuda capability 5.0

Gives the same error

`RuntimeError: cuda runtime error (8) : invalid device function at c:\anaconda2\conda-bld\pytorch_1519496000060\work\torch\lib\thc\generic/THCTensorMathPointwise.cu:301`

for 

`x = torch.rand(13, 13).cuda()`
`y = torch.rand(13,13).cuda()`
`print(x+y)`

**Comment by soumith** [comment]
@volf52 we need more information, like what OS, what pytorch version, etc.

**Comment by volf52** [comment]
@soumith 

Pytorch Version : 0.3.1.post2
Python : Python 3.6.5 (Miniconda 3)
OS : Windows 10
CUDA : V9.0.176 (9.1 also available)

I am working right now on either building it from source (do I need Microsoft VS for that) and/or downloading from 
https://ci.appveyor.com/project/peterjc123/pytorch-elheu/branch/v0.4.0 .

Would that work ... ?
Thank you.

**Comment by soumith** [comment]
0.3.1 has no support for 5.0 (your GPU), please upgrade to latest pytorch from instructions on the website https://pytorch.org/

**Comment by limusen123** [comment]
import argparse

import torch
import torch.nn as nn
import torch.optim as optim
import torchnet as tnt
import torchvision.transforms as transforms
from torch.autograd import Variable
from torch.optim.lr_scheduler import MultiStepLR
from torch.utils.data import DataLoader
from torchnet.engine import Engine
from torchnet.logger import VisdomPlotLogger
from tqdm import tqdm

from data_utils import DatasetFromFolder
from model import Net
from psnrmeter import PSNRMeter


def processor(sample):
    data, target, training = sample
    data = Variable(data)
    target = Variable(target)
    if torch.cuda.is_available():
        data = data.cuda()
        target = target.cuda()

    output = model(data)
    loss = criterion(output, target)

    return loss, output


def on_sample(state):
    state['sample'].append(state['train'])


def reset_meters():
    meter_psnr.reset()
    meter_loss.reset()


def on_forward(state):
    meter_psnr.add(state['output'].data, state['sample'][1])
    meter_loss.add(state['loss'].data[0])


def on_start_epoch(state):
    reset_meters()
    scheduler.step()
    state['iterator'] = tqdm(state['iterator'])


def on_end_epoch(state):
    print('[Epoch %d] Train Loss: %.4f (PSNR: %.2f db)' % (
        state['epoch'], meter_loss.value()[0], meter_psnr.value()))

    train_loss_logger.log(state['epoch'], meter_loss.value()[0])
    train_psnr_logger.log(state['epoch'], meter_psnr.value())

    reset_meters()

    engine.test(processor, val_loader)
    val_loss_logger.log(state['epoch'], meter_loss.value()[0])
    val_psnr_logger.log(state['epoch'], meter_psnr.value())

    print('[Epoch %d] Val Loss: %.4f (PSNR: %.2f db)' % (
        state['epoch'], meter_loss.value()[0], meter_psnr.value()))

    torch.save(model.state_dict(), 'epochs/epoch_%d_%d.pt' % (UPSCALE_FACTOR, state['epoch']))


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='Train Super Resolution')
    parser.add_argument('--upscale_factor', default=3, type=int, help='super resolution upscale factor')
    parser.add_argument('--num_epochs', default=100, type=int, help='super resolution epochs number')
    opt = parser.parse_args()

    UPSCALE_FACTOR = opt.upscale_factor
    NUM_EPOCHS = opt.num_epochs

    train_set = DatasetFromFolder('data/train', upscale_factor=UPSCALE_FACTOR, input_transform=transforms.ToTensor(),
                                  target_transform=transforms.ToTensor())
    val_set = DatasetFromFolder('data/val', upscale_factor=UPSCALE_FACTOR, input_transform=transforms.ToTensor(),
                                target_transform=transforms.ToTensor())
    train_loader = DataLoader(dataset=train_set, num_workers=4, batch_size=64, shuffle=True)
    val_loader = DataLoader(dataset=val_set, num_workers=4, batch_size=64, shuffle=False)

    model = Net(upscale_factor=UPSCALE_FACTOR)
    criterion = nn.MSELoss()
    if torch.cuda.is_available():
        model = model.cuda()
        criterion = criterion.cuda()

    print('# parameters:', sum(param.numel() for param in model.parameters()))

    optimizer = optim.Adam(model.parameters(), lr=1e-2)
    scheduler = MultiStepLR(optimizer, milestones=[30, 80], gamma=0.1)

    engine = Engine()
    meter_loss = tnt.meter.AverageValueMeter()
    meter_psnr = PSNRMeter()

    train_loss_logger = VisdomPlotLogger('line', opts={'title': 'Train Loss'})
    train_psnr_logger = VisdomPlotLogger('line', opts={'title': 'Train PSNR'})
    val_loss_logger = VisdomPlotLogger('line', opts={'title': 'Val Loss'})
    val_psnr_logger = VisdomPlotLogger('line', opts={'title': 'Val PSNR'})

    engine.hooks['on_sample'] = on_sample
    engine.hooks['on_forward'] = on_forward
    engine.hooks['on_start_epoch'] = on_start_epoch
    engine.hooks['on_end_epoch'] = on_end_epoch

    engine.train(processor, train_loader, maxepoch=NUM_EPOCHS, optimizer=optimizer)





D:\ProgramData\Anaconda3\envs\python36\python.exe "D:/ProgramData/Anaconda3/envs/python36/python Super-resolution/ESPCN-master/train.py"
WARNING:root:Setting up a new session...
# parameters: 59657
WARNING:root:Setting up a new session...
WARNING:root:Setting up a new session...
WARNING:root:Setting up a new session...
  0%|          | 0/261 [00:00<?, ?it/s]D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\torch\nn\functional.py:995: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
THCudaCheck FAIL file=c:\programdata\miniconda3\conda-bld\pytorch_1532500470552\work\aten\src\thc\generic/THCTensorMathPointwise.cu line=59 error=8 : invalid device function
Traceback (most recent call last):
  File "D:/ProgramData/Anaconda3/envs/python36/python Super-resolution/ESPCN-master/train.py", line 115, in <module>
    engine.train(processor, train_loader, maxepoch=NUM_EPOCHS, optimizer=optimizer)
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\torchnet\engine\engine.py", line 63, in train
    state['optimizer'].step(closure)
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\torch\optim\adam.py", line 57, in step
    loss = closure()
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\torchnet\engine\engine.py", line 52, in closure
    loss, output = state['network'](state['sample'])
  File "D:/ProgramData/Anaconda3/envs/python36/python Super-resolution/ESPCN-master/train.py", line 28, in processor
    output = model(data)
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\python36\python Super-resolution\ESPCN-master\model.py", line 16, in forward
    x = F.tanh(self.conv1(x))
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\torch\nn\functional.py", line 996, in tanh
    return input.tanh()
RuntimeError: cuda runtime error (8) : invalid device function at c:\programdata\miniconda3\conda-bld\pytorch_1532500470552\work\aten\src\thc\generic/THCTensorMathPointwise.cu:59


Process finished with exit code 1







My python is 3.6, cuda is 10.0, GPU computing power is 5.0, win10 is 5.0, and pytorch 0.4.1 tensorflow is 1.14.0. Please help me, I have been troubled by this problem for a long time

**Comment by limusen123** [comment]
@soumith，thank you！！
