### ISSUE TITLE
torch.cuda.is_available() ---> false

### ISSUE THREAD

**Issue by KAUSTIKR** [pytorch/pytorch#68611]
`torch.cuda.is_available() `
false
**pytorch installed** 
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch-nightly

**nvidia-smi**
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 461.72       Driver Version: 461.72       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 105... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   61C    P8    N/A /  N/A |     78MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     14616    C+G   ...n64\EpicGamesLauncher.exe    N/A      |
+-----------------------------------------------------------------------------+
```
**python -m torch.utils.collect_env**
C:\Users\rajra>python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19042-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] numpydoc==1.1.0
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h59b6b97_2
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py39h2bbff1b_0
[conda] mkl_fft                   1.3.1            py39h277e83a_0
[conda] mkl_random                1.2.2            py39hf11a4ad_0
[conda] mypy_extensions           0.4.3            py39haa95532_0
[conda] numpy                     1.20.3           py39ha4e8547_0
[conda] numpy-base                1.20.3           py39hc2deb75_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] pytorch                   1.10.0          py3.9_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.0               py39_cu113    pytorch
[conda] torchvision               0.11.1               py39_cu113    pytorch

cc @ezyang @seemethere @malfet @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by mszhanyi** [comment]
@KAUSTIKR 
I suggest you to install the pytorch in a clean virtual environment.
From your command, you installed the nightly version.
But nightly build version should be 1.11, not 1.10

**Comment by mszhanyi** [comment]
BTW, it'd better to upgrade your cudatoolkit to higher than 11.3.
Generally, the driver version shouldn't lower than runtime version.

**Comment by KAUSTIKR** [comment]
Hi Zhang,

Thanks, it worked for me.

**Comment by KAUSTIKR** [comment]
install the pytorch in a clean virtual environment.
