### ISSUE TITLE
Cannot use DDP with NCCL backend on A100 GPUs

### ISSUE THREAD

**Issue by jwohlwend** [pytorch/pytorch#68735]
## 🐛 Bug

Hi, I am unable to use DDP with the NCCL backend when using a machine with 8x A100 GPU's. I am currently running the latest pytorch 1.10 release and have tried multiple versions of CUDA: 11.3, 11.4 and 11.5. In all cases the pattern is the same: I can use DDP when using the gloo backend, but with nccl the code freezes during `dist.init_process_group`. The script to reproduce is the one provided by pytorch.

## To Reproduce

1. Run this script on a machine with A100 GPUs: https://github.com/pytorch/examples/blob/master/distributed/ddp/main.py

## Environment

 - PyTorch Version (e.g., 1.0): 1.10
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 11.3
 - GPU models and configuration: A100
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
I'm not able to reproduce this with nightly + CUDA 11.3 + NCCL 2.9.8, will check if it is an issue in 1.10. nvidia-smi indicates my GPUs are `A100-SXM4-40GB`. 

Does it work on V100 GPUs? Could you try upgrading to nightly/master pytorch and see if the issue still persists? In addition, the following might be valuable: 

- Run with env variable TORCH_DISTRIBUTED_DEBUG=DETAIL set across all workers
- Pass in a small `timeout` to init_process_group such as 1 min - so the code can crash quicker, default timeout is 30 mins.

**Comment by jwohlwend** [comment]
Yes it does work on V100, it only fails with A100 GPUs. I tried upgrading to nightly and still seeing the same problem.

Here is the output when setting timeout to 60 seconds, and using TORCH_DISTRIBUTED_DEBUG=DETAIL for both 1.10 and nighlty. I get the same message for both versions.

```
>> TORCH_DISTRIBUTED_DEBUG=DETAIL python test_ddp.py
Running basic DDP example on rank 3.
Running basic DDP example on rank 2.
Running basic DDP example on rank 4.
Running basic DDP example on rank 5.
Running basic DDP example on rank 0.
Running basic DDP example on rank 6.
Running basic DDP example on rank 7.
Running basic DDP example on rank 1.
[E ProcessGroupGloo.cpp:136] Rank 1 successfully reached monitoredBarrier, but received errors while waiting to be unblocked by rank 0. Please check rank 0 logs for faulty rank.
[E ProcessGroupGloo.cpp:2781] Rank 2 failed to pass monitoredBarrier in 60000 ms
[E ProcessGroupGloo.cpp:2781] Rank 3 failed to pass monitoredBarrier in 60000 ms
[E ProcessGroupGloo.cpp:2781] Rank 4 failed to pass monitoredBarrier in 60000 ms
[E ProcessGroupGloo.cpp:2781] Rank 5 failed to pass monitoredBarrier in 60000 ms
[E ProcessGroupGloo.cpp:2781] Rank 6 failed to pass monitoredBarrier in 60000 ms
[E ProcessGroupGloo.cpp:2781] Rank 7 failed to pass monitoredBarrier in 60000 ms
[E ProcessGroupGloo.cpp:136] Ranks 2, 3, 4, 5, 6, 7 failed to pass monitoredBarrier in 60000 ms
Traceback (most recent call last):
  File "test_ddp.py", line 149, in <module>
    run_demo(demo_basic, 8)
  File "test_ddp.py", line 57, in run_demo
    mp.spawn(demo_fn,
  File "/data/rsg/mammogram/jeremy/miniconda3/envs/cuda11/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/rsg/mammogram/jeremy/miniconda3/envs/cuda11/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/data/rsg/mammogram/jeremy/miniconda3/envs/cuda11/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data/rsg/mammogram/jeremy/miniconda3/envs/cuda11/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/afs/csail.mit.edu/u/j/jwohlwend/test_ddp.py", line 42, in demo_basic
    ddp_model = DDP(model, device_ids=[rank])
  File "/data/rsg/mammogram/jeremy/miniconda3/envs/cuda11/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 580, in __init__
    self._sync_params_and_buffers(authoritative_rank=0)
  File "/data/rsg/mammogram/jeremy/miniconda3/envs/cuda11/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 597, in _sync_params_and_buffers
    self._distributed_broadcast_coalesced(
  File "/data/rsg/mammogram/jeremy/miniconda3/envs/cuda11/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1334, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(
RuntimeError: Ranks 2, 3, 4, 5, 6, 7 failed to pass monitoredBarrier in 60000 ms
```

I also found another strange behavior. It seems that NCCL works when using GPUs 0 & 1, but not 1 & 2. Looking into this further it seems that any 2 consecutive GPUs starting with an even number (ex: [0, 1], [2, 3], ... [6, 7]) all work but any other combination of 2 or more GPUs doesn't. Note: our GPUs are equipped with nvlink, not sure if that can be related to the above..

**Comment by jwohlwend** [comment]
@rohan-varma Does the above help? Any other info that would be useful for diagnostic?

**Comment by shim94kr** [comment]
@jwohlwend Is there any progress on this issue?

**Comment by jwohlwend** [comment]
@shim94kr Nope, problem persists

**Comment by jwohlwend** [comment]
@rohan-varma Any updates on this? I still cannot get this to work on nccl

**Comment by rohan-varma** [comment]
@jwohlwend Thanks for the ping, taking a look today

**Comment by rohan-varma** [comment]
@jwohlwend Do you know the NCCL version for which you're seeing this failure? If you're able to downgrade your NCCL version, could you also test with that?

**Comment by jwohlwend** [comment]
@rohan-varma looks like it is currently 2.10.3. Is there a version that would recommend downgrading to? And would I also need to downgrade cuda and pytorch?

**Comment by hhuytho** [comment]
Do we have any updates on this? We're still waiting on this in order to use our A100s. Thanks.

**Comment by jiayisuse** [comment]
Suspecting it's something wrong with NCCL p2p on a particular topology. Could you try the following:

* Wondering what's the topology of the 8 A100 GPUs. The output of `nvidia-smi topo --matrix` could tell.
* Run again with `NCCL_DEBUG=INFO` and `NCCL_DEBUG_SUBSYS=INIT,P2P`, and see if the log could disclose more clues.
* Run with `NCCL_P2P_DISABLE=1`

**Comment by jwohlwend** [comment]
@jiayisuse Thanks for following-up. Here's the output of `nvidia-smi topo --matrix`:

```
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	CPU Affinity	NUMA Affinity
GPU0	 X 	NV12	NODE	NODE	SYS	SYS	SYS	SYS	0-23,48-71	0
GPU1	NV12	 X 	NODE	NODE	SYS	SYS	SYS	SYS	0-23,48-71	0
GPU2	NODE	NODE	 X 	NV12	SYS	SYS	SYS	SYS	0-23,48-71	0
GPU3	NODE	NODE	NV12	 X 	SYS	SYS	SYS	SYS	0-23,48-71	0
GPU4	SYS	SYS	SYS	SYS	 X 	NV12	NODE	NODE	24-47,72-95	1
GPU5	SYS	SYS	SYS	SYS	NV12	 X 	NODE	NODE	24-47,72-95	1
GPU6	SYS	SYS	SYS	SYS	NODE	NODE	 X 	NV12	24-47,72-95	1
GPU7	SYS	SYS	SYS	SYS	NODE	NODE	NV12	 X 	24-47,72-95	1
```

Just to reemphasize I have noticed that DDP runs successfully for any NV12  pair above but not any other pair of 2 GPU's.

I then tried with `NCCL_DEBUG=INFO` and `NCCL_DEBUG_SUBSYS=INIT,P2P`. It prints a lot of stuff and gets stuck after these lines:

```
[HOST]:35145:36132 [3] NCCL INFO comm 0x7fa924002f70 rank 3 nranks 8 cudaDev 3 busId 61000 - Init COMPLETE
[HOST]:35144:36136 [2] NCCL INFO comm 0x7f08ac002f70 rank 2 nranks 8 cudaDev 2 busId 41000 - Init COMPLETE
[HOST]:35142:36081 [0] NCCL INFO comm 0x7f7cc8002f70 rank 0 nranks 8 cudaDev 0 busId 1000 - Init COMPLETE
[HOST]:35143:36137 [1] NCCL INFO comm 0x7f36d8002f70 rank 1 nranks 8 cudaDev 1 busId 25000 - Init COMPLETE
[HOST]:35142:35142 [0] NCCL INFO Launch mode Parallel
[HOST]:35148:36135 [6] NCCL INFO comm 0x7f1e44002f70 rank 6 nranks 8 cudaDev 6 busId c1000 - Init COMPLETE
[HOST]:35146:36133 [4] NCCL INFO comm 0x7ff4d8002f70 rank 4 nranks 8 cudaDev 4 busId 81000 - Init COMPLETE
[HOST]:35149:36131 [7] NCCL INFO comm 0x7fd240002f70 rank 7 nranks 8 cudaDev 7 busId e1000 - Init COMPLETE
[HOST]:35147:36134 [5] NCCL INFO comm 0x7f7830002f70 rank 5 nranks 8 cudaDev 5 busId a1000 - Init COMPLETE
```

Then I tried with `NCCL_P2P_DISABLE=1` and it ran successfully!

**Comment by rohan-varma** [comment]
@jwohlwend @jiayisuse Does this appear like an issue with NCCL 2.10.3 + NCCL p2p transport?

**Comment by jwohlwend** [comment]
@rohan-varma I very much doubt that the issue is specific to NCCL 2.10.3. I think the reason you cannot reproduce is likely due to us having a different topology as highlighted by @jiayisuse. I can try 2.9.8, but could also try to replicate on your end with 2.10.3?

**Comment by kwen2501** [comment]
> ```
> 	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	CPU Affinity	NUMA Affinity
> GPU0	 X 	NV12	NODE	NODE	SYS	SYS	SYS	SYS	0-23,48-71	0
> GPU1	NV12	 X 	NODE	NODE	SYS	SYS	SYS	SYS	0-23,48-71	0
> GPU2	NODE	NODE	 X 	NV12	SYS	SYS	SYS	SYS	0-23,48-71	0
> GPU3	NODE	NODE	NV12	 X 	SYS	SYS	SYS	SYS	0-23,48-71	0
> GPU4	SYS	SYS	SYS	SYS	 X 	NV12	NODE	NODE	24-47,72-95	1
> GPU5	SYS	SYS	SYS	SYS	NV12	 X 	NODE	NODE	24-47,72-95	1
> GPU6	SYS	SYS	SYS	SYS	NODE	NODE	 X 	NV12	24-47,72-95	1
> GPU7	SYS	SYS	SYS	SYS	NODE	NODE	NV12	 X 	24-47,72-95	1
> ```
> 
> Just to reemphasize I have noticed that DDP runs successfully for any NV12 pair above but not any other pair of 2 GPU's.
> 
> Then I tried with `NCCL_P2P_DISABLE=1` and it ran successfully!

Hi @jwohlwend, based on the above symptoms, it looks like GPU Direct (i.e. P2P) does not work or works very slowly across NUMA domains or CPU bridges on your machine. 

A few questions:
- What CPU models do you have?
- Do you have special virtualization settings or BIOS settings? 

You may follow [this section](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#gpu-direct) of the NCCL doc to troubleshoot the issue. For example, first run a CUDA level `p2pBandwidthLatencyTest` to confirm if it is a GPU Direct issue.

**Comment by kwen2501** [comment]
As discussed in these two issues: NVIDIA/nccl#606, NVIDIA/nccl#631, P2P not being functional is usually tied to ACS (for crossing PCI switches), VT-d or IOMMU being enabled. 

In your case, you can check the VT-d or IOMMU settings on the machine, and disable them if they are on, and/or passing iommu=pt to the linux kernel command line. 

See the following two comments:
https://github.com/NVIDIA/nccl/issues/606#issuecomment-990098186
https://github.com/NVIDIA/nccl/issues/631#issuecomment-1030136691

**Comment by kwen2501** [comment]
Thanks.

Oh, I forgot to mention that as a **temporary workaround**, you can use `NCCL_P2P_LEVEL` to define the maximum distance between GPUs where NCCL will use the P2P transport.

In your specific case, you can set `NCCL_P2P_LEVEL=PXB` to disable P2P for `NODE` or `SYS`, while still enabling P2P for NVLinks.

Ref: https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-p2p-level

**Comment by jwohlwend** [comment]
@kwen2501 I'm happy to report that turning off both AMD SVM (virtualization) and IOMMU in the BIOS did the trick! It turns out that this issue wasn't about the A100's specifically but something to do with the AMD CPU's (did not happen on our intel based setups). Super grateful for the help, thank you!

**Comment by yjcaimeow** [comment]
For me, the reason is that I only save the model for local rank 0. Maybe saving model process some resources are not release??

In short, open the model save if-else branch for all rank, the bug is fixed for me.

**Comment by yjcaimeow** [comment]
> Hi, I have a setup with Intel CPUs, but I have this issue. @yjcaimeow could you please give some tips for saving/loading models for all ranks?

save model for all local rank

**Comment by EmreOzkose** [comment]
It is very strange, but I set rank of second server as 0 and rank of first server as 1. After that, freezing stage is changed.

**Comment by monajalal** [comment]
I am having the same exact problem in a cluster with 4 nodes each with 4 K80 GPUs.

https://github.com/NVIDIA/nccl/issues/849

```
CPython
3.8.10
uname_result(system='Linux', node=number', release='5.15.0-1029-azure', version='#36~20.04.1-Ubuntu SMP Tue Dec 6 17:00:26 UTC 2022', machine='x86_64', processor='x86_64')
System information: Linux #36~20.04.1-Ubuntu SMP Tue Dec 6 17:00:26 UTC 2022
Python version: 3.8.10
MLflow version: 2.3.2
MLflow module location: /usr/local/lib/python3.8/dist-packages/mlflow/__init__.py
Tracking URI:URI
Registry URI: URI
MLflow environment variables: 
  MLFLOW_DISABLE_ENV_MANAGER_CONDA_WARNING: True
  MLFLOW_EXPERIMENT_ID: 021dec90-c7d3-4233-813e-799d15e43f9a
  MLFLOW_EXPERIMENT_NAME: dev_DOPE_FAT_test2
  MLFLOW_RUN_ID: 54be70c6-c1a9-4433-8943-e1678667884b
  MLFLOW_TRACKING_TOKEN: token
  MLFLOW_TRACKING_URI: URI
MLflow dependencies: 
  Flask: 2.3.2
  Jinja2: 3.1.2
  alembic: 1.11.1
  click: 8.1.3
  cloudpickle: 2.2.0
  databricks-cli: 0.17.7
  docker: 6.1.2
  entrypoints: 0.4
  gitpython: 3.1.31
  gunicorn: 20.1.0
  importlib-metadata: 5.1.0
  markdown: 3.4.1
  matplotlib: 3.7.0
  numpy: 1.24.2
  packaging: 22.0
  pandas: 1.5.2
  protobuf: 3.20.1
  pyarrow: 9.0.0
  pytz: 2022.6
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.1
  scikit-learn: 0.24.2
  scipy: 1.10.1
  sqlalchemy: 2.0.15
  sqlparse: 0.4.4
2023/05/23 15:48:00 WARNING mlflow.tracking.fluent: Exception raised while enabling autologging for sklearn: No module named 'sklearn.utils.testing'
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO Bootstrap : Using eth0:10.0.0.4<0>
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v6 symbol.
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO NET/Plugin: Loaded net plugin NCCL RDMA Plugin (v5)
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol.
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO NET/Plugin: Loaded coll plugin SHARP (v5)
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO cudaDriverVersion 11040
NCCL version 2.14.3+cuda11.7
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO P2P plugin IBext
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NET/IB : No device found.
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NET/Socket : Using [0]eth0:10.0.0.4<0>
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Using network Socket
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0001-0000-3130-444531303244/pci0001:00/0001:00:00.0/../max_link_speed, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0001-0000-3130-444531303244/pci0001:00/0001:00:00.0/../max_link_width, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0002-0000-3130-444531303244/pci0002:00/0002:00:00.0/../max_link_speed, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0002-0000-3130-444531303244/pci0002:00/0002:00:00.0/../max_link_width, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0003-0000-3130-444531303244/pci0003:00/0003:00:00.0/../max_link_speed, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0003-0000-3130-444531303244/pci0003:00/0003:00:00.0/../max_link_width, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0004-0000-3130-444531303244/pci0004:00/0004:00:00.0/../max_link_speed, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0004-0000-3130-444531303244/pci0004:00/0004:00:00.0/../max_link_width, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection: network path /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/6045bd7e-6943-6045-bd7e-69436045bd7e is not a PCI device (vmbus). Attaching to first CPU
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO === System : maxBw 5.0 totalBw 12.0 ===
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO CPU/0 (1/1/1)
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO + PCI[5000.0] - NIC/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO                 + NET[5.0] - NET/0 (0/0/5.000000)
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO + PCI[12.0] - GPU/100000 (0)
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO + PCI[12.0] - GPU/200000 (1)
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO + PCI[12.0] - GPU/300000 (2)
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO + PCI[12.0] - GPU/400000 (3)
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO ==========================================
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO GPU/100000 :GPU/100000 (0/5000.000000/LOC) GPU/200000 (2/12.000000/PHB) GPU/300000 (2/12.000000/PHB) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO GPU/200000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (0/5000.000000/LOC) GPU/300000 (2/12.000000/PHB) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO GPU/300000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (2/12.000000/PHB) GPU/300000 (0/5000.000000/LOC) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO GPU/400000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (2/12.000000/PHB) GPU/300000 (2/12.000000/PHB) GPU/400000 (0/5000.000000/LOC) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NET/0 :GPU/100000 (3/5.000000/PHB) GPU/200000 (3/5.000000/PHB) GPU/300000 (3/5.000000/PHB) GPU/400000 (3/5.000000/PHB) CPU/0 (2/5.000000/PHB) NET/0 (0/5000.000000/LOC) 
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Setting affinity for GPU 0 to 0fff
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, bw 5.000000/5.000000, type PHB/PHB, sameChannels 1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO  0 : NET/0 GPU/0 GPU/1 GPU/2 GPU/3 NET/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Pattern 1, crossNic 0, nChannels 1, bw 6.000000/5.000000, type PHB/PHB, sameChannels 1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO  0 : NET/0 GPU/0 GPU/1 GPU/2 GPU/3 NET/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 0, bw 0.000000/0.000000, type NVL/PIX, sameChannels 1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Tree 0 : -1 -> 0 -> 1/8/-1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Tree 1 : 4 -> 0 -> 1/-1/-1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 00/02 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 01/02 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Ring 00 : 15 -> 0 -> 1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Ring 01 : 15 -> 0 -> 1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Trees [0] 1/8/-1->0->-1 [1] 1/-1/-1->0->4
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 00/0 : 15[400000] -> 0[100000] [receive] via NET/Socket/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 01/0 : 15[400000] -> 0[100000] [receive] via NET/Socket/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 00 : 0[100000] -> 1[200000] via SHM/direct/direct
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 01 : 0[100000] -> 1[200000] via SHM/direct/direct
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Connected all rings
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 01/0 : 0[100000] -> 4[100000] [send] via NET/Socket/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 00/0 : 8[100000] -> 0[100000] [receive] via NET/Socket/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 00/0 : 0[100000] -> 8[100000] [send] via NET/Socket/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 01/0 : 4[100000] -> 0[100000] [receive] via NET/Socket/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NDownloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /root/.cache/torch/hub/checkpoints/vgg19-dcbb9e9d.pth
training script path:  /mnt/azureml/cr/j/aa54f8a6f177420ea912cde147fec47b/exe/wd
start: 15:48:00.718630
object of interest is: cracker
manual seed set to 8346
opt.checkpoints = /mnt/azureml/cr/j/aa54f8a6f177420ea912cde147fec47b/cap/data-capability/wd/checkpoints
world size is:  16
global rank is 0 and local_rank is 0
is_distributed is True and batch_size is 1
os.getpid() is 39 and initializing process group with {'MASTER_ADDR': '10.0.0.4', 'MASTER_PORT': '6105', 'LOCAL_RANK': '0', 'RANK': '0', 'WORLD_SIZE': '16'}
device is cuda:0
load data
train data size:  246000
training data len:  246000
batch size is:  1
training data: 15375 batches
load models
torch.cuda.device_count():  4
type opt.gpuids: <class 'list'>
gpuids are: [0, 1, 2, 3]
Training network pretrained on imagenet.

  0%|          | 0.00/548M [00:00<?, ?B/s]
  1%|▏         | 7.99M/548M [00:00<00:08, 68.6MB/s]
  3%|▎         | 15.8M/548M [00:00<00:10, 51.2MB/s]
  4%|▍         | 20.9M/548M [00:00<00:13, 39.5MB/s]
  5%|▍         | 24.9M/548M [00:00<00:16, 34.3MB/s]
  6%|▌         | 32.0M/548M [00:00<00:13, 39.0MB/s]
  7%|▋         | 40.0M/548M [00:00<00:11, 46.8MB/s]
  9%|▉         | 48.0M/548M [00:01<00:10, 48.4MB/s]
 10%|█         | 56.0M/548M [00:01<00:09, 53.4MB/s]
 12%|█▏        | 64.0M/548M [00:01<00:11, 43.7MB/s]
 13%|█▎        | 73.4M/548M [00:01<00:09, 54.4MB/s]
 15%|█▍        | 82.1M/548M [00:01<00:07, 62.4MB/s]
 16%|█▌        | 88.9M/548M [00:01<00:07, 64.1MB/s]
 18%|█▊        | 99.7M/548M [00:01<00:06, 76.3MB/s]
 20%|█▉        | 108M/548M [00:02<00:06, 71.0MB/s] 
 21%|██        | 115M/548M [00:02<00:07, 62.2MB/s]
 22%|██▏       | 121M/548M [00:02<00:07, 58.7MB/s]
 23%|██▎       | 128M/548M [00:02<00:07, 57.9MB/s]
 24%|██▍       | 134M/548M [00:02<00:07, 57.5MB/s]
 25%|██▌       | 139M/548M [00:02<00:08, 48.1MB/s]
 26%|██▋       | 144M/548M [00:02<00:09, 45.8MB/s]
 27%|██▋       | 150M/548M [00:02<00:08, 49.6MB/s]
 28%|██▊       | 155M/548M [00:03<00:09, 45.7MB/s]
 29%|██▉       | 160M/548M [00:03<00:10, 39.9MB/s]
 30%|███       | 166M/548M [00:03<00:09, 43.9MB/s]
 31%|███       | 171M/548M [00:03<00:11, 33.9MB/s]
 32%|███▏      | 176M/548M [00:03<00:11, 34.3MB/s]
 34%|███▎      | 184M/548M [00:03<00:09, 41.3MB/s]
 35%|███▌      | 192M/548M [00:04<00:07, 47.2MB/s]
 36%|███▋      | 200M/548M [00:04<00:08, 42.2MB/s]
 38%|███▊      | 208M/548M [00:04<00:07, 49.4MB/s]
 39%|███▉      | 216M/548M [00:04<00:06, 55.3MB/s]
 41%|████      | 224M/548M [00:04<00:06, 51.2MB/s]
 42%|████▏     | 229M/548M [00:04<00:06, 49.5MB/s]
 43%|████▎     | 234M/548M [00:04<00:07, 45.7MB/s]
 44%|████▍     | 242M/548M [00:05<00:05, 54.3MB/s]
 45%|████▌     | 248M/548M [00:05<00:06, 49.8MB/s]
 47%|████▋     | 256M/548M [00:05<00:05, 57.9MB/s]
 48%|████▊     | 263M/548M [00:05<00:04, 61.7MB/s]
 49%|████▉     | 269M/548M [00:05<00:04, 59.4MB/s]
 50%|█████     | 275M/548M [00:05<00:05, 50.1MB/s]
 51%|█████     | 280M/548M [00:05<00:06, 40.8MB/s]
 53%|█████▎    | 288M/548M [00:06<00:05, 48.2MB/s]
 54%|█████▍    | 296M/548M [00:06<00:05, 52.5MB/s]
 55%|█████▌    | 302M/548M [00:06<00:05, 50.7MB/s]
 56%|█████▌    | 307M/548M [00:06<00:05, 44.8MB/s]
 57%|█████▋    | 312M/548M [00:06<00:05, 42.9MB/s]
 58%|█████▊    | 320M/548M [00:06<00:05, 47.1MB/s]
 60%|█████▉    | 328M/548M [00:06<00:04, 55.1MB/s]
 61%|██████    | 333M/548M [00:07<00:04, 50.8MB/s]
 62%|██████▏   | 338M/548M [00:07<00:04, 49.8MB/s]
 63%|██████▎   | 344M/548M [00:07<00:04, 48.4MB/s]
 64%|██████▍   | 352M/548M [00:07<00:03, 54.6MB/s]
 66%|██████▌   | 361M/548M [00:07<00:03, 63.8MB/s]
 67%|██████▋   | 368M/548M [00:07<00:03, 53.6MB/s]
 69%|██████▊   | 376M/548M [00:07<00:03, 52.0MB/s]
 70%|███████   | 384M/548M [00:07<00:03, 57.0MB/s]
 72%|███████▏  | 392M/548M [00:08<00:02, 55.6MB/s]
 73%|███████▎  | 400M/548M [00:08<00:02, 59.5MB/s]
 74%|███████▍  | 408M/548M [00:08<00:02, 65.7MB/s]
 76%|███████▌  | 417M/548M [00:08<00:01, 71.3MB/s]
 77%|███████▋  | 424M/548M [00:08<00:01, 70.7MB/s]
 79%|███████▉  | 432M/548M [00:08<00:01, 68.0MB/s]
 80%|████████  | 440M/548M [00:08<00:01, 71.3MB/s]
 82%|████████▏ | 448M/548M [00:08<00:01, 70.9MB/s]
 83%|████████▎ | 456M/548M [00:09<00:01, 73.8MB/s]
 85%|████████▍ | 464M/548M [00:09<00:01, 69.4MB/s]
 86%|████████▌ | 472M/548M [00:09<00:01, 68.7MB/s]
 88%|████████▊ | 480M/548M [00:09<00:01, 66.0MB/s]
 89%|████████▉ | 488M/548M [00:09<00:01, 55.9MB/s]
 91%|█████████ | 496M/548M [00:09<00:00, 58.0MB/s]
 92%|█████████▏| 504M/548M [00:09<00:00, 54.4MB/s]
 93%|█████████▎| 512M/548M [00:10<00:00, 58.0MB/s]
 94%|█████████▍| 518M/548M [00:10<00:00, 51.1MB/s]
 95%|█████████▌| 523M/548M [00:10<00:00, 46.4MB/s]
 97%|█████████▋| 533M/548M [00:10<00:00, 58.9MB/s]
 98%|█████████▊| 539M/548M [00:10<00:00, 59.1MB/s]
 99%|█████████▉| 545M/548M [00:10<00:00, 58.0MB/s]
100%|██████████| 548M/548M [00:10<00:00, 53.7MB/s]CCL INFO Connected all trees
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO threadThresholds 8/8/64 | 128/8/64 | 512 | 512
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NCCL_P2P_PXN_LEVEL set by environment to 0.
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO comm 0x2bb6f090 rank 0 nranks 16 cudaDev 0 busId 100000 - Init COMPLETE
[E ProcessGroupGloo.cpp:2803] [Rank 0]: Rank 4 failed to pass monitoredBarrier in 2000000 ms
[E ProcessGroupGloo.cpp:2803] [Rank 0]: Rank 5 failed to pass monitoredBarrier in 2000000 ms
[E ProcessGroupGloo.cpp:2803] [Rank 0]: Rank 6 failed to pass monitoredBarrier in 2000000 ms
[E ProcessGroupGloo.cpp:2803] [Rank 0]: Rank 7 failed to pass monitoredBarrier in 2000000 ms
[E ProcessGroupGloo.cpp:137] [Rank 0]: Ranks 4, 5, 6, 7 failed to pass monitoredBarrier in 2000000 ms

Traceback (most recent call last):
  File "train.py", line 1467, in <module>
    net = torch.nn.parallel.DistributedDataParallel(net, device_ids=[local_rank], output_device=local_rank) # do we need output_device=local_rank?
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 655, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/utils.py", line 112, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: [Rank 0]: Ranks 4, 5, 6, 7 failed to pass monitoredBarrier in 2000000 ms
517cc60b90264a01ac05aafd5e6ca61e000000:39:304 [0] NCCL INFO [Service thread] Connection closed by localRank 0
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO comm 0x2bb6f090 rank 0 nranks 16 cudaDev 0 busId 100000 - Abort COMPLETE

```

code:
```
# DISTRIBUTED: this is required to initialize the pytorch backend
dist_url = "env://" # default
# dist_url = "auto"
dist.init_process_group(
    backend=distributed_backend,
    init_method=dist_url,
    timeout=datetime.timedelta(seconds=2000), #default is 30 min
    world_size=world_size,
    rank=world_rank  
)


torch.cuda.set_device(local_rank)
device = torch.device("cuda", local_rank) if torch.cuda.is_available() else 'cpu'
print("device is {}".format(device))
# this will make all .cuda() calls work properly

# synchronize all the threads to reach this point before moving on
dist.barrier() 
```

How can I fix this?

Here are my NCCL flags:

`Dockerfile`:
```
# check release notes https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/index.html
# FROM nvcr.io/nvidia/pytorch:22.04-py3
#FROM nvcr.io/nvidia/pytorch:23.02-py3 #requires GPUs with compute capability of 5+
FROM nvcr.io/nvidia/pytorch:22.12-py3

##############################################################################
# NCCL TESTS
##############################################################################
ENV NCCL_TESTS_TAG=v2.11.0

# NOTE: adding gencodes to support K80, M60, V100, A100
RUN mkdir /tmp/nccltests && \
    cd /tmp/nccltests && \
    git clone -b ${NCCL_TESTS_TAG} https://github.com/NVIDIA/nccl-tests.git && \
    cd nccl-tests && \
    make \
    MPI=1 MPI_HOME=/opt/hpcx/ompi \
    NVCC_GENCODE="-gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80" \
    CUDA_HOME=/usr/local/cuda && \
    cp ./build/* /usr/local/bin && \
    rm -rf /tmp/nccltests

# Install dependencies missing in this container
# NOTE: container already has matplotlib==3.5.1 tqdm==4.62.0
COPY requirements.txt ./
RUN pip install -r requirements.txt


# add ndv4-topo.xml
RUN mkdir /opt/microsoft/
ADD ./ndv4-topo.xml /opt/microsoft

# to use on A100, enable env var below in your job
# ENV NCCL_TOPO_FILE="/opt/microsoft/ndv4-topo.xml"

# adjusts the level of info from NCCL tests
ENV NCCL_DEBUG="INFO"
ENV NCCL_DEBUG_SUBSYS="GRAPH,INIT,ENV"

# Relaxed Ordering can greatly help the performance of Infiniband networks in virtualized environments.
# do we need to disable IB?
# suggested to set ENV NCCL_IB_PCI_RELAXED_ORDERING to 0 for NCCL 2.18.1
ENV NCCL_IB_PCI_RELAXED_ORDERING="0" 
#ENV NCCL_IB_PCI_RELAXED_ORDERING="1"
ENV NCCL_P2P_PXN_LEVEL="0"
ENV CUDA_DEVICE_ORDER="PCI_BUS_ID"
ENV NCCL_SOCKET_IFNAME="eth0"
ENV NCCL_IB_DISABLE="1"  
# ENV NCCL_P2P_DISABLE="1"
```
Here's my `pipeline.yaml`:
```
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline



# <inputs_and_outputs>
inputs:

  training_data:
    type: uri_folder
    mode: download # pick ro_mount, rw_mount or download

outputs:
  checkpoints:
    type: uri_folder
    mode: upload
    path: azureml:my_model:1
  
    

# <jobs>
settings:
  default_datastore: azureml:mydatastore
  continue_on_step_failure: true

jobs:
  train:
    type: command
    component: file:train.yaml
    compute: azureml:mona-gpu-cluster # 16 GPUs
    resources:
      instance_count: 4    # number of nodes
    distribution:
      type: pytorch
      process_count_per_instance: 4 # number of gpus

    # NOTE: set env var if needed
    environment_variables:
      NCCL_DEBUG: "INFO" # adjusts the level of info from NCCL tests

      # NCCL_TOPO_FILE: "/opt/microsoft/ndv4-topo.xml" # Use specific topology file for A100

      # NCCL_IB_PCI_RELAXED_ORDERING: "1" # Relaxed Ordering can greatly help the performance of Infiniband networks in virtualized environments.
      NCCL_IB_DISABLE: "1" # force disable infiniband (if set to "1")  # even if commented NCCL INFO NCCL_IB_DISABLE set by environment to 1.
      # NCCL_NET_PLUGIN: "none" # to force NET/Plugin off (no rdma/sharp plugin at all)
      # NCCL_NET: "Socket" # to force node-to-node comm to use Socket (slow)
      NCCL_SOCKET_IFNAME: "eth0" # to force Socket comm to use eth0 (use NCCL_NET=Socket)
      NCCL_P2P_PXN_LEVEL: "0"
      

      # UCX_IB_PCI_RELAXED_ORDERING: "on"
      # UCX_TLS: "tcp"
      # UCX_NET_DEVICES: "eth0" # if you have Error: Failed to resolve UCX endpoint...

      CUDA_DEVICE_ORDER: "PCI_BUS_ID" # ordering of gpus

      TORCH_DISTRIBUTED_DEBUG: "DETAIL"
      # NCCL_P2P_DISABLE: "1"

    inputs:
      train_data: ${{parent.inputs.training_data}}

      # data loading
      # batch_size: 256
      batch_size: 16
      manualseed: 42
      num_workers: 5
      prefetch_factor: 4
      persistent_workers: true
      pin_memory: true
      non_blocking: false

      # model
      model_arch: "vgg16"
      model_arch_pretrained: true

      # training
      num_epochs: 5 #need 60 for full training
      learning_rate: 0.0001
      momentum: 0.9

      # profiling
      enable_profiling: false
      # multiprocessing_sharing_strategy: "file_system" # WARNING: this can cause hang at job completion

      # Model Registrataion
      register_model_as: "mymodel"

# </jobs>

```
here's the `requirements.txt`:
```
albumentations==1.3.0
ConfigParser==5.3.0
horovod==0.27.0
matplotlib==3.7.0
numpy==1.24.2
nvisii==1.1.72
Pillow==9.4.0
profiling==0.1.3
psutil==5.9.0
pyquaternion==0.9.9
pyrealsense2==2.53.1.4623
pyrender==0.1.45
pyrr==0.10.3
PyYAML==6.0
scipy==1.10.1
seaborn==0.12.2
simplejson==3.18.4
tensorboardX==2.6
tqdm==4.64.1
opencv-python-headless==4.1.2.30
torch==1.13.0
torchvision==0.14.0
mlflow==2.3.2
azureml-mlflow==1.50.0
```

here's `train-env.yaml`:
```
$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: nvidia_pytorch
build:
  path: ../../../data-science/environment/
tags:
  os: ubuntu
  os_version: 20.04
  hpcx: 2.10
  mpi: openmpi
  mpi_version: 4.1.2rc4
  ucx: 1.12.0
  cuda: 11.6.2
  cudnn: 8.4.0.27
  # nccl: 2.12.10
  # nccl: 2.17.1
  nccl: 2.18.1
  rdma_core: 36.0
  nsight_compute: 2022.1.1.2
  nsight_systems: "2022.2.1.31-5fe97ab"
  nccl_test: 2.11.0
```
