### ISSUE TITLE
test_linalg_solve_triangular_large fails "CUDA error: too many resources requested for launch" on win cuda

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#70111]
### 🐛 Describe the bug

Windows shard1 tests have been silently not running since the deletion of caffe2. In my attempt to add it back, there have been several test failures along the way, including 

test_linalg.py:4947:TestLinalgCUDA.test_linalg_solve_triangular_large_cuda_float64

```
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 381, in instantiated_test
    raise rte
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 907, in only_fn
    return fn(slf, *args, **kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "test_linalg.py", line 4960, in test_linalg_solve_triangular_large
    for A, B, left, upper, uni in gen_inputs(shape, dtype, device, well_conditioned=True):
  File "test_linalg.py", line 4887, in _gen_shape_inputs_linalg_triangular_solve
    PLU = torch.lu_unpack(*torch.lu(make_randn(*size_a)))
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\_jit_internal.py", line 422, in fn
    return if_false(*args, **kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\functional.py", line 1754, in _lu_no_infos
    result = _lu_impl(A, pivot, get_infos, out)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\functional.py", line 1720, in _lu_impl
    return torch._lu_with_info(A, pivot=pivot, check_errors=(not get_infos))
RuntimeError: CUDA error: too many resources requested for launch
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

@Lezcano it looks like you added this test ~3 wks ago. Do you know why this may be the case? 
For more details, click here https://hud.pytorch.org/pr/pytorch/pytorch/70010 (the attempt to fix windows tests commit). 

### Versions

Occurs for both Windows 11.3 and 11.5 CUDA tests.

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @ngimel @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Lezcano** [comment]
I don't know what's going on there... Perhaps we should just skip it in Windows?

**Comment by mszhanyi** [comment]
But it works with cuda 11.1
`2021-12-17T02:06:56.0213969Z   test_linalg_solve_triangular_large_cuda_float64 (__main__.TestLinalgCUDA) ... ok (0.678s)`

**Comment by Lezcano** [comment]
cc @xwang233, could you have a look at this one?

**Comment by xwang233** [comment]
Can we get C++ stacktraces with `TORCH_SHOW_CPP_STACKTRACES=1`?

**Comment by mszhanyi** [comment]
stacktrace in GHA could be fine in  https://github.com/pytorch/pytorch/issues/57482.

**Comment by janeyx99** [comment]
> I don't know what's going on there... Perhaps we should just skip it in Windows?

It's currently disabled already--is this test ultimately not important for Windows? @Lezcano

**Comment by Lezcano** [comment]
Windows support is incomplete at best, so I don't think that it's problematic to skip this one. cc @mruberry

**Comment by mszhanyi** [comment]
I run the test locally. It works with cu113 and cu115.
![image](https://user-images.githubusercontent.com/16190118/147024905-c2174a13-35e4-429b-b55a-73898eadf423.png)

**Comment by mszhanyi** [comment]
@janeyx99 
circleCI has the same error and GPU in Tesla is Tesla T4?
what's GPU on GHA?

**Comment by mszhanyi** [comment]
some test results

|              | Quadro P620 | Geforce T1080 | Geforce T2080 |  Tesla T4
| ---------| -----------      | ------                |--------------    |  ------
| cu11.3   |  :white_check_mark:  |:white_check_mark:|:x:|:x:
| cu11.1   |  :white_check_mark:  |:white_check_mark:| :white_check_mark: | :white_check_mark: 

At first glance, it works on cheap GPU and old cuda runtime

**Comment by mruberry** [comment]
Skipping this seems like a good way to mitigate the issue, but let's keep this open because maybe we do have a genuine Windows issue.

**Comment by atalman** [comment]
Small update on this, I can confirm this is still not fixed in CUDA 11.6

**Comment by IvanYashchuk** [comment]
What GPU is used in this Windows CI?

**Comment by iremyux** [comment]
After trying it locally, I can confirm this issue still exits in CUDA 11.8 .
