### ISSUE TITLE
specific batchsize illegal memory access

### ISSUE THREAD

**Issue by yunkaili** [pytorch/pytorch#7129]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
specific batchsize illegal memory access
running with batchsize=2 will cause illegal memory access
while batchsize=4 will not

## Code example

```
import torch
 
  data = torch.autograd.Variable(torch.rand(2,2048,4,8,11)).cuda()
  data_success = torch.autograd.Variable(torch.rand(4,2048,4,8,11)).cuda()

  conv3 = torch.nn.Conv3d(2048, 512, kernel_size=(3,1,1), stride=(1,1,1),padding=(1,0,0),
                                              bias=False).cuda()
 
  out = conv3.forward(data)
  print(out)
```
  
## System Info

```
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCTensorCopy.c line=70 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    print(out)
  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 57, in __repr__
    return torch._tensor_str._str(self)
  File "/usr/local/lib/python3.5/dist-packages/torch/_tensor_str.py", line 218, in _str
    fmt, scale, sz = _number_format(self)
  File "/usr/local/lib/python3.5/dist-packages/torch/_tensor_str.py", line 79, in _number_format
    tensor = torch.DoubleTensor(tensor.size()).copy_(tensor).abs_().view(tensor.nelement())
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/generic/THCTensorCopy.c:70
```

[environment collection script]
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX TITAN X
Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/cuda/lib64/libcudnn.so.7.0.5
/usr/local/cuda-8.0/cuda/lib64/libcudnn_static.a
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.20
/usr/local/cuda-8.0/lib64/libcudnn.so.7.0.5
/usr/local/cuda-8.0/lib64/libcudnn.so.7.old
/usr/local/cuda-8.0/lib64/libcudnn_static.a
/usr/local/cudnn-v50/lib64/libcudnn.so.5.0.5
/usr/local/cudnn-v50/lib64/libcudnn_static.a
/usr/local/cudnn-v60/lib64/libcudnn.so
/usr/local/cudnn-v60/lib64/libcudnn.so.6
/usr/local/cudnn-v60/lib64/libcudnn.so.6.0.20
/usr/local/cudnn-v60/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.14.2)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.0)
[conda] Could not collect

- PyTorch or Caffe2: Pytorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source): sudo -HE pip3 install -U pytorch-0.4.0.wheel
- OS: ubuntu
- PyTorch version: 0.4.0
- Python version: 3.5.2
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by albanD** [comment]
I can't reproduce this from master on a titanX.
What GPU are you using? Also you may want to run with `CUDA_LAUNCH_BLOCKING=1` to get a proper error message.

**Comment by zou3519** [comment]
I can reproduce this on master, on a machine with 2 GPUs. This is the stack trace with CUDA_LAUNCH_BLOCKING=1:
```
$ CUDA_LAUNCH_BLOCKING=1 python batchsize.py
Traceback (most recent call last):
  File "batchsize.py", line 9, in <module>
    out = conv3.forward(data)
  File "/private/home/rzou/pytorch/pytorch/torch/nn/modules/conv.py", line 421, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
```
not really sure what to make of it

**Comment by zou3519** [comment]
Both batch sizes fail for me. My theory is that you're running out of GPU memory (I saw this post: https://discuss.pytorch.org/t/cudnn-status-execution-failed/4441/19)

**Comment by yunkaili** [comment]
due to the fact that i am using cuda-8.0
i reinstall the pytorch with pip3 install -U torch torchvision

**Comment by yunkaili** [comment]
using CUDA_LAUNCH_BLOCKING=1
i got the following info

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    out = conv3.forward(data)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 421, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

**Comment by adizhol** [comment]
with CUDA_LAUNCH_BLOCKING=1
python 3.5
Win 10
CUDA 8.0
cudnn 6

I get the following stack trace:

>   File "C:\Users\owner\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\nn\functional.py", line 1334, in nll_loss
>     return torch._C._nn.nll_loss2d(input, target, weight, size_average, ignore_index, reduce)
> RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at c:\users\administrator\downloads\new-builder\win-wheel\pytorch\aten\src\thcunn\generic/SpatialClassNLLCriterion.cu:131
> 

**This code is using CrossEntropyLoss, but another code that uses BCEWithLogits doen't throw any exceptions.**

**Comment by zou3519** [comment]
@adizhol could you post a reproducing code snippet, possibly in a new issue? The code at the top of this issue doesn't call CrossEntropyLoss.

**Comment by xyang35** [comment]
@zou3519 Any updates to this thread? I have a very similar problem with pytorch 0.4 and CUDA 9.0. The Conv3d model works on some batch sizes but crashes on many others. Thanks

**Comment by simonwang517** [comment]
Hi all, I met the same situation, this error occurs when I have a large batchsize, and it disappear when I reduce beamsize. Meanwhile I watched GPU memery with nvidia-smi, it's not a problem about OOM.
It's weird beacasue when I debug with pdb, this error occurs later than before.

**Comment by yasheshgaur** [comment]
Any update on this? I get the same error. I am sure it is not a GPU OOM issue.

**Comment by xyang35** [comment]
@yasheshgaur I found a workaround actually. By setting torch.backends.cudnn.enabled=False, the problem is gone... I'm still not sure why but I got the idea from https://discuss.pytorch.org/t/cudnn-status-execution-failed/4441/9, and it works for my case...

**Comment by yasheshgaur** [comment]
@xyang35 this would mean that I won't be able to use CUDNN. Won't be happy with that. :(

**Comment by junwenchen** [comment]
I am still facing this problem. 
torch.backends.cudnn.enabled=False did not work for me.
Does anyone solve it?

**Comment by Chenfeng1271** [comment]
Have you solved it? I meet the same problem

**Comment by yiwei1994** [comment]
Hi, has someone solved this problem? I have also meet this annoying problem.

**Comment by ezyang** [comment]
Does not reproduce for me on master (32777231730983aa38bb92624ca0b30fd75fb521) with:

```
PyTorch version: 1.1.0a0+3277723
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla M60
GPU 1: Tesla M60

Nvidia driver version: 390.57
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] mkl_fft                   1.0.6            py37hd81dba3_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] torch                     1.1.0a0+3277723           <pip>
```

For those of you who are seeing this problem, please post your system configuration as collected by https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py it will help us get more information about how to debug the problem.

**Comment by danFromTelAviv** [comment]
I have narrowed it down to this like.
in thie case ( pytorch ) ac_output is a mat, out ones_like(ac_output) - float32 . inds and out_inds are the same size ( m x 2) int64. 
out[out_inds[:, 0], :, out_inds[:, 1]] = ac_output[inds[:, 0], :, inds[:, 1]]

**Comment by soumith** [comment]
@danFromTelAviv the way to reproduce illegal memory access is highly dependent on the value of `inds`, because `inds` might be referring to an out of bounds value.
In such a case, we do want to give you a device assert, rather than "illegal memory access". Can you provide example snippets of code to construct the `x` and `inds` and reproduce the error?

**Comment by danFromTelAviv** [comment]
@soumith thanks. I actually got it to work eventually. To be frank I have been jugelling a few things this week and i cant remember how i got it to work... i'll try to reproduce it with some git magic for tye benefit of others. 
in my case inds were calculated with nonzeros on a tensor of the same shape as x... so it would have to explicitly be within range.

**Comment by Virgiliok** [comment]
I am facing a very similar problem (possibly the same described here), but with the number of output channels of a 2D convolution. I have found a simple way to reproduce the error. Please indicate if I should open a new issue.

Notice that it works with 40 output channels, it does not work with 41:

```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch import nn
>>> device = torch.device("cuda")
>>> ones = torch.ones(32, 32, 57, 35).to(device)
>>> n = nn.Conv2d(32, 40, 5, 2).to(device)
>>> out = n(ones)
>>> n = nn.Conv2d(32, 41, 5, 2).to(device)
>>> out = n(ones)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vkmetzsc/.conda/envs/env36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vkmetzsc/.conda/envs/env36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

The output of collect_env.py is:

```
Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 410.48
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] numpydoc==0.8.0
[pip] torch==1.0.1.post2
[pip] torchvision==0.2.1
[conda] Could not collect
```

**Comment by SsnL** [comment]
@Virgiliok CUDA 9 doesn't work with RTX cards. Could you try a CUDA 10 build?

**Comment by Virgiliok** [comment]
Thank you, @SsnL. Using a CUDA 10 build solved my problem.

**Comment by ezyang** [comment]
I'm going to go ahead and close this as a CUDA/CuDNN bug that is fixed in the latest version. If you are still seeing this problem with CUDA 10, please file a new bug.
