### ISSUE TITLE
Effective memory leak due to head-of-line blocking in CUDACachingAllocator `process_events`.

### ISSUE THREAD

**Issue by nelhage** [pytorch/pytorch#71616]
### 🐛 Describe the bug

We have a large training job which makes heavy use of overlapping NCCL communications and local computation by queueing ops on separate streams.

We are seeing intermittent OOMs on some of our large jobs. These are surprising because they are just executing an identical train step repeatedly, which should have identical behavior on each step, and we normally see rock-solid memory usage from these jobs.

The OOMs show allocated memory << reserved; e.g. here's the output from a recent failure:

> RuntimeError: CUDA out of memory. Tried to allocate 648.00 MiB (GPU 5; 39.59 GiB total capacity; 22.96 GiB already allocated; 228.19 MiB free; 36.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

By grabbing CUDA allocator statistics during training and around failures, we're seeing that the difference between "allocated" and "reserved" is explained by the "active" memory statistic; here's an example memory statistics dump from a different job:

```
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 7                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 1            |        cudaMalloc retries: 72        |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |   31420 MB |   31542 MB |    1270 GB |    1239 GB |
|       from large pool |   31414 MB |   31536 MB |    1269 GB |    1239 GB |
|       from small pool |       6 MB |       7 MB |       0 GB |       0 GB |
|---------------------------------------------------------------------------|
| Active memory         |   31420 MB |   36134 MB |    1270 GB |    1239 GB |
|       from large pool |   31414 MB |   36128 MB |    1269 GB |    1239 GB |
|       from small pool |       6 MB |       7 MB |       0 GB |       0 GB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |   36882 MB |   36978 MB |  101984 MB |   65102 MB |
|       from large pool |   36874 MB |   36970 MB |  101976 MB |   65102 MB |
|       from small pool |       8 MB |       8 MB |       8 MB |       0 MB |
|---------------------------------------------------------------------------|
| Non-releasable memory |    5461 MB |    5621 MB |     929 GB |     924 GB |
|       from large pool |    5459 MB |    5619 MB |     928 GB |     923 GB |
|       from small pool |       1 MB |       2 MB |       0 GB |       0 GB |
|---------------------------------------------------------------------------|
| Allocations           |    1100    |    1110    |   63600    |   62500    |
|       from large pool |    1024    |    1033    |   50297    |   49273    |
|       from small pool |      76    |      85    |   13303    |   13227    |
|---------------------------------------------------------------------------|
| Active allocs         |    1100    |    1236    |   63600    |   62500    |
|       from large pool |    1024    |    1159    |   50297    |   49273    |
|       from small pool |      76    |      85    |   13303    |   13227    |
|---------------------------------------------------------------------------|
| GPU reserved segments |     514    |     686    |    1574    |    1060    |
|       from large pool |     510    |     682    |    1570    |    1060    |
|       from small pool |       4    |       4    |       4    |       0    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |     343    |     366    |   35346    |   35003    |
|       from large pool |     335    |     358    |   31735    |   31400    |
|       from small pool |       8    |      11    |    3611    |    3603    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|
```

Setting `max_split_size_mb` does fix the OOMs, but at an unacceptable performance cost.

Based on my debugging and reviewing our code and PyTorch source, we believe the problem arises from our use of concurrent computation and NCCL communications, coupled with the [head-of-line blocking behavior](https://github.com/pytorch/pytorch/blob/9f0227a0ebde20eb50ff2ddc7e224a3a28a40ad2/c10/cuda/CUDACachingAllocator.cpp#L1275-L1279) in the CUDA allocator's `process_events`.

I've written a toy example which can "leak" an unbounded amount of memory by exploiting this behavior. If you run this script on a machine with at least two GPUs, you'll witness allocated memory staying constant, but "Active" growing without bound. The script is extensively commented with my understanding of what's going on.

e.g. here's output near a recent test run:

```
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |    4608 B  |    8704 B  |    2503 MB |    2503 MB |
|---------------------------------------------------------------------------|
| Active memory         |    2503 MB |    2503 MB |    2503 MB |    1024 B  |
|---------------------------------------------------------------------------|
| GPU reserved memory   |    2506 MB |    2506 MB |    2506 MB |       0 B  |
|---------------------------------------------------------------------------|
| Non-releasable memory |    3003 KB |    4095 KB |    2503 MB |    2500 MB |
|---------------------------------------------------------------------------|
| Allocations           |       2    |       3    |  640789    |  640787    |
|---------------------------------------------------------------------------|
| Active allocs         |  640787    |  640787    |  640789    |       2    |
|---------------------------------------------------------------------------|
| GPU reserved segments |    1253    |    1253    |    1253    |       0    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       3    |       3    |    1254    |    1251    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|
```

Reproducer: 
https://gist.github.com/nelhage/c5f9b2831014963a4b35d2e0311f93c7

One fix would be for the allocator to keep a list of events per-CUDA-stream, but I'm not sure if that would be too expensive.

### Versions

Collecting environment information...
PyTorch version: 1.10.0a0+git302ee7b
Is debug build: False
CUDA used to build PyTorch: 11.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.27

Python version: 3.8.10 (default, Jun  4 2021, 15:09:15)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.156-83.273.amzn2.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.4.120
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.930
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] pytorch-memlab==0.2.4
[pip3] torch==1.10.0a0+git302ee7b
[pip3] torchtyping==0.1.4
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-include               2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py38h7f8727e_0
[conda] mkl_fft                   1.3.1            py38hd3c417c_0
[conda] mkl_random                1.2.2            py38h51133e4_0
[conda] mypy                      0.930                    pypi_0    pypi
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.21.2           py38h20f2e39_0
[conda] numpy-base                1.21.2           py38h79a1101_0
[conda] pytorch-memlab            0.2.4                    pypi_0    pypi
[conda] torch                     1.10.0a0+git302ee7b          pypi_0    pypi
[conda] torchtyping               0.1.4                    pypi_0    pypi

cc @ngimel

**Comment by ezyang** [comment]
cc @colesbury @ngimel @mcarilli

**Comment by nelhage** [comment]
One quick update:

The attached reproducer used an `allgather` and has a comment about how the bug doesn't work with `isend` or `irecv`; I realized while thinking harder and looking at our model code that you can stumble on this just as well if you have multiple `isend` or `irecv`s; [the gist now has a second version](https://gist.github.com/nelhage/c5f9b2831014963a4b35d2e0311f93c7#file-torch_leak_irecv-py) which uses two chained `irecv`s to achieve the same effect.

I suspect that's a bit closer to the version we're actually running into. Also, after grabbing more memory statistics from our running jobs, we're seeing jobs with ~25% of GPU memory locked up in [active but not available]; Doing regular `torch.cuda.synchronize()`s gets that memory back, but has a substantial performance hit. So this is a bigger hit for our jobs than we'd originally realized.

**Comment by mcarilli** [comment]
That's a good question. I'm a little concerned my approach in https://github.com/pytorch/pytorch/pull/65365 for freeing memory used in multiple streams arrives at the same head-of-line blocking behavior by a completely different route.

The PR is WIP and could fail on your workload for god knows what other reasons, but I'm steadily ironing out bugs and as of https://github.com/pytorch/pytorch/pull/65365/commits/6fbb8ccaca1e0315ef6282ea78545a4b89caf3bb 167 out of 169 tests in test_cuda.py pass on my machine, so it might be stable enough to try.

**Comment by nelhage** [comment]
Keeping this ticket updated from the other PR: https://github.com/pytorch/pytorch/pull/71745#issuecomment-1023625542

#71745 fixes about half the (active - allocated) gap. We were able to close essentially the rest by enforcing that we only keep a fixed number of queued-but-not-completed NCCL ops in flight at a time; I believe we were letting the CPU run too far ahead of the GPU, which in hindsight of course makes the allocator hold on to all of the tensors involved in the queued comms.

I'll see if I get a chance to try out #65365 but probably can't prioritize it since we've resolved the for now on our end.
