### ISSUE TITLE
`test_neg_view_linalg_det_singular_cuda_float64` fails with Illegal Memory Access failure for singular matrices

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#72204]
### 🐛 Describe the bug

```
======================================================================
ERROR: test_neg_view_linalg_det_singular_cuda_float64 (__main__.TestMathBitsCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/fsx/users/chourdiaanjali/pytorch/torch/testing/_internal/common_utils.py", line 1753, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/chourdiaanjali/pytorch/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    raise rte
  File "/fsx/users/chourdiaanjali/pytorch/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/fsx/users/chourdiaanjali/pytorch/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/fsx/users/chourdiaanjali/pytorch/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/fsx/users/chourdiaanjali/pytorch/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/fsx/users/chourdiaanjali/pytorch/torch/testing/_internal/common_device_type.py", line 753, in test_wrapper
    return test(*args, **kwargs)
  File "/fsx/users/chourdiaanjali/pytorch/test/test_ops.py", line 1296, in test_neg_view
    self._test_math_view(device, dtype, op, samples, math_op_physical, math_op_view, is_bit_set,
  File "/fsx/users/chourdiaanjali/pytorch/test/test_ops.py", line 1262, in _test_math_view
    forward_with_mathview.sum().backward(retain_graph=True)
  File "/fsx/users/chourdiaanjali/pytorch/torch/_tensor.py", line 352, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/fsx/users/chourdiaanjali/pytorch/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

----------------------------------------------------------------------
Ran 152 tests in 20.836s

FAILED (errors=1, skipped=90)
srun: error: dev-st-p3dn24xlarge-2: task 0: Exited with exit code 1
```

### Versions

master

cc @ezyang @gchanan @zou3519

**Comment by nikitaved** [comment]
This is interesting. If I do the following diff:

**Comment by malfet** [comment]
@anjali411 is there a PR in progress already? If not, perhaps we should remove the milestone/move it to 1.12

**Comment by anjali411** [comment]
Removing the 1.11 milestone since the issue was in the sample inputs that the test was being run on and not in `torch.linalg.det`

**Comment by Lezcano** [comment]
I believe this one should be fixed, right @nikitaved ?

**Comment by nikitaved** [comment]
I think so, yes.
