### ISSUE TITLE
libtorch with Cuda 11.3 not linked properly on Windows using Visual Studio 2022

### ISSUE THREAD

**Issue by Xargonus** [pytorch/pytorch#72396]
### 🐛 Describe the bug

I don't seem to be able to use libtorch CUDA 11.3 with Visual studio 2022.

I have set up my already existing project to use libtorch using one of the available resources online, for example https://programmer.group/visual-sudio-2019-libtorch-pytorch-c-library-environment-configuration.html

CPU works well but CUDA is not available. I added the following libraries to Additional dependencies:
```
c10.lib
c10_cuda.lib
torch_cpu.lib
torch_cuda.lib
```

If I try the fix described in #31611 by adding `/INCLUDE:"?warp_size@cuda@at@@YAHXZ"`,
I get  `LINK : error LNK2001: unresolved external symbol "int __cdecl at::cuda::warp_size(void)" (?warp_size@cuda@at@@YAHXZ)`

If I also add `torch_cuda_cpp.lib` to additional dependencies, CUDA is available but now I get the following error:
```
Could not run 'aten::empty_strided' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty_strided' is only available for these backends: [CPU, Meta, BackendSelect, Python, Named, Conjugate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].

CPU: registered at aten\src\ATen\RegisterCPU.cpp:18433 [kernel]
Meta: registered at aten\src\ATen\RegisterMeta.cpp:12703 [kernel]
BackendSelect: registered at aten\src\ATen\RegisterBackendSelect.cpp:665 [kernel]
Python: registered at ..\..\aten\src\ATen\core\PythonFallbackKernel.cpp:47 [backend fallback]
Named: registered at ..\..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: fallthrough registered at ..\..\aten\src\ATen\ConjugateFallback.cpp:22 [kernel]
Negative: fallthrough registered at ..\..\aten\src\ATen\native\NegateFallback.cpp:22 [kernel]
ADInplaceOrView: fallthrough registered at ..\..\aten\src\ATen\core\VariableFallbackKernel.cpp:64 [backend fallback]
AutogradOther: registered at ..\..\torch\csrc\autograd\generated\VariableType_2.cpp:10483 [autograd kernel]
AutogradCPU: registered at ..\..\torch\csrc\autograd\generated\VariableType_2.cpp:10483 [autograd kernel]
AutogradCUDA: registered at ..\..\torch\csrc\autograd\generated\VariableType_2.cpp:10483 [autograd kernel]
AutogradXLA: registered at ..\..\torch\csrc\autograd\generated\VariableType_2.cpp:10483 [autograd kernel]
AutogradLazy: registered at ..\..\torch\csrc\autograd\generated\VariableType_2.cpp:10483 [autograd kernel]
AutogradXPU: registered at ..\..\torch\csrc\autograd\generated\VariableType_2.cpp:10483 [autograd kernel]
AutogradMLC: registered at ..\..\torch\csrc\autograd\generated\VariableType_2.cpp:10483 [autograd kernel]
AutogradHPU: registered at ..\..\torch\csrc\autograd\generated\VariableType_2.cpp:10483 [autograd kernel]
AutogradNestedTensor: registered at ..\..\torch\csrc\autograd\generated\VariableType_2.cpp:10483 [autograd kernel]
AutogradPrivateUse1: registered at ..\..\torch\csrc\autograd\generated\VariableType_2.cpp:10483 [autograd kernel]
AutogradPrivateUse2: registered at ..\..\torch\csrc\autograd\generated\VariableType_2.cpp:10483 [autograd kernel]
AutogradPrivateUse3: registered at ..\..\torch\csrc\autograd\generated\VariableType_2.cpp:10483 [autograd kernel]
Tracer: registered at ..\..\torch\csrc\autograd\generated\TraceType_2.cpp:11423 [kernel]
UNKNOWN_TENSOR_TYPE_ID: fallthrough registered at ..\..\aten\src\ATen\autocast_mode.cpp:466 [backend fallback]
Autocast: fallthrough registered at ..\..\aten\src\ATen\autocast_mode.cpp:305 [backend fallback]
Batched: registered at ..\..\aten\src\ATen\BatchingRegistrations.cpp:1016 [backend fallback]
VmapMode: fallthrough registered at ..\..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]

Exception raised from reportError at ..\..\aten\src\ATen\core\dispatch\OperatorEntry.cpp:431 (most recent call first):
00007FFEE7CAA29200007FFEE7CAA230 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFEE7C843C500007FFEE7C84350 c10.dll!c10::NotImplementedError::NotImplementedError [<unknown file> @ <unknown line number>]
00007FFD5F015C7100007FFD5F015AA0 torch_cpu.dll!c10::impl::OperatorEntry::reportError [<unknown file> @ <unknown line number>]
00007FFD5F6C6AF000007FFD5F66DBB0 torch_cpu.dll!at::_ops::xlogy_Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFD5F8E73F100007FFD5F8CF610 torch_cpu.dll!at::_ops::zeros_out::redispatch [<unknown file> @ <unknown line number>]
00007FFD5F8E3F7400007FFD5F8CF610 torch_cpu.dll!at::_ops::zeros_out::redispatch [<unknown file> @ <unknown line number>]
00007FFD5F6EB6E800007FFD5F6EB520 torch_cpu.dll!at::_ops::empty_strided::call [<unknown file> @ <unknown line number>]
00007FFD5EF259CB00007FFD5EF258D0 torch_cpu.dll!at::empty_strided [<unknown file> @ <unknown line number>]
00007FFD5F2C24D100007FFD5F2C2130 torch_cpu.dll!at::native::_to_copy [<unknown file> @ <unknown line number>]
00007FFD5FA7C3D600007FFD5FA7BF10 torch_cpu.dll!at::compositeexplicitautograd::xlogy_ [<unknown file> @ <unknown line number>]
00007FFD5FA5A8FB00007FFD5FA3F310 torch_cpu.dll!at::compositeexplicitautograd::bitwise_xor_outf [<unknown file> @ <unknown line number>]
00007FFD5F4EB5AD00007FFD5F45B290 torch_cpu.dll!at::TensorMaker::make_tensor [<unknown file> @ <unknown line number>]
00007FFD5F8DED7700007FFD5F8CF610 torch_cpu.dll!at::_ops::zeros_out::redispatch [<unknown file> @ <unknown line number>]
00007FFD5F8E36EB00007FFD5F8CF610 torch_cpu.dll!at::_ops::zeros_out::redispatch [<unknown file> @ <unknown line number>]
00007FFD5F4EB5AD00007FFD5F45B290 torch_cpu.dll!at::TensorMaker::make_tensor [<unknown file> @ <unknown line number>]
00007FFD5F56326800007FFD5F563190 torch_cpu.dll!at::_ops::_to_copy::redispatch [<unknown file> @ <unknown line number>]
00007FFD60A27F0000007FFD60A27A30 torch_cpu.dll!at::redispatch::_thnn_fused_lstm_cell_backward [<unknown file> @ <unknown line number>]
00007FFD60A4031D00007FFD60A34930 torch_cpu.dll!torch::jit::Node::c_ [<unknown file> @ <unknown line number>]
00007FFD5F50C12B00007FFD5F50BF70 torch_cpu.dll!at::_ops::_to_copy::call [<unknown file> @ <unknown line number>]
00007FFD5F2C2E7900007FFD5F2C2BD0 torch_cpu.dll!at::native::to_dense_backward [<unknown file> @ <unknown line number>]
00007FFD5F2C2B0C00007FFD5F2C29E0 torch_cpu.dll!at::native::to [<unknown file> @ <unknown line number>]
00007FFD5FB6A66800007FFD5FB63F10 torch_cpu.dll!at::compositeimplicitautograd::where [<unknown file> @ <unknown line number>]
00007FFD5FB4DB5D00007FFD5FB1BE50 torch_cpu.dll!at::compositeimplicitautograd::broadcast_to [<unknown file> @ <unknown line number>]
00007FFD5F7E6F4600007FFD5F7E6D70 torch_cpu.dll!at::_ops::to_dtype_layout::call [<unknown file> @ <unknown line number>]
00007FFD5EF4AA8800007FFD5EF4A970 torch_cpu.dll!at::Tensor::to [<unknown file> @ <unknown line number>]
00007FFD5EF9EAE900007FFD5EF9E9F0 torch_cpu.dll!at::tensor [<unknown file> @ <unknown line number>]
00007FF7714295A200007FF7714294B0 SplinterlandsSimulator.exe!main [C:\Users\xargo\source\repos\SplinterlandsSimulator\SplinterlandsSimulator\SplinterlandsSimulator.cpp @ 390]
00007FF77144164C00007FF771441540 SplinterlandsSimulator.exe!__scrt_common_main_seh [d:\a01\_work\20\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288]
00007FFF47C554E000007FFF47C554D0 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
00007FFF48DA485B00007FFF48DA4830 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]
```

Adding `torch_cuda_cu.lib` to additional dependencies does not solve this issue. The only way I can run CUDA successfully is by calling `LoadLibraryA("torch_cuda.dll")`

## To reproduce

The following script throws "Torch is not linked against CUDA" and gets 0 as output.
```
#include <ATen/ATen.h>
#include <torch/torch.h>
#include <iostream>

int main() {
    try {    
        std::cout << torch::cuda::is_available() << std::endl;
        torch::Tensor tensor = at::tensor({ -1, 1 }, at::kCUDA);
    }
    catch (exception& ex) {
        std::cout << ex.what() << std::endl;
    }
}
```

The following one is working correctly and gets 1 as output.
```
#include <ATen/ATen.h>
#include <torch/torch.h>
#include <iostream>
#include <Windows.h>

int main() {
    LoadLibraryA("torch_cuda.dll");
    try {    
        std::cout << torch::cuda::is_available() << std::endl;
        torch::Tensor tensor = at::tensor({ -1, 1 }, at::kCUDA);
    }
    catch (exception& ex) {
        std::cout << ex.what() << std::endl;
    }
}
```

## Expected behavior
The behaviour keeps consistent in code snippet 1 and code snippet 2.

### Versions

PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1060 with Max-Q Design
Nvidia driver version: 497.09
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.5
[pip3] pytorch-model-summary==0.1.2
[pip3] torch==1.10.0+cu113
[pip3] torchaudio==0.10.0+cu113
[pip3] torchvision==0.11.1+cu113
[conda] Could not collect

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @jbschlosser @ngimel

**Comment by mruberry** [comment]
@malfet Should this be high priority? (Should we have a separate OnCall for build issues?)

**Comment by malfet** [comment]
@mruberry actually I wonder if `module: build` is appropriate here, as it has nothing to do with building PyTorch, but rather with using `libtorch` (which should be `module: cpp` isn't it?)

**Comment by malfet** [comment]
Thank you for reporting. I guess what you need to do here is add [WHOLEARCHIVE](https://docs.microsoft.com/en-us/cpp/build/reference/wholearchive-include-all-library-object-files?view=msvc-170) option for both libtorch_cuda_cu and libtorch_cuda_cpp

**Comment by mruberry** [comment]
> @mruberry actually I wonder if `module: build` is appropriate here, as it has nothing to do with building PyTorch, but rather with using `libtorch` (which should be `module: cpp` isn't it?) An imo it should not be high priority, as we do not currently support linking with libtorch using any build systems other than `CMake`, as described in https://pytorch.org/cppdocs/installing.html

A fine distinction that's hard for us nonexperts to appreciate ;)

**Comment by mszhanyi** [comment]
@Xargonus For pytorch 1.10 with cuda11.3, the additional link option should be 
`-INCLUDE:?warp_size@cuda@at@@YAHXZ" "-INCLUDE:?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z" `

You could install the [ visual studio extension ](https://marketplace.visualstudio.com/items?itemName=YiZhang.LibTorch001) to setup the libtorch VC project. 
So far, the extension is for VS2019, I will add the support to VS2022 once I have time.

And I tried, there's no problem to open the VS2019 project  with VS2022

**Comment by Xargonus** [comment]
@mszhanyi Thank you, adding `-INCLUDE:?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z` fixed the issue. I know that this is probably included in the VS extension, but it would be nice if it was documented somewhere, preferably [here](https://pytorch.org/cppdocs/installing.html).

I did not use the extension not only because it currently does not support VS2022 but also because I was adding libtorch to an existing library. My workflow would be to create an empty project and copy the settings from it to my project which seems needlessly difficult when the actual setup is so simple (Although I am not sure how does the setup vary between different versions of CUDA and PyTorch.), so I searched for online resources instead.

**Comment by mszhanyi** [comment]
cudnn-10.2-XXX is about 436M and cudnn-11.3-XXX is about 1.28G. 
There're some improvements to solve the issues caused by the big size, which might change the setup.
Generally, the additional link options is transparent to users. 

You could check out https://github.com/janeyx99/builder/blob/7758ae34a8b1b6105d6964599f08b66d6bc958c1/windows/internal/smoke_test.bat#L220
to find the latest change.

PS. 
For next version, the additional link option should be `/INCLUDE:?warp_size@cuda@at@@YAHXZ /INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z`

**Comment by xbbkok** [comment]
> cudnn-10.2-XXX is about 436M and cudnn-11.3-XXX is about 1.28G. There're some improvements to solve the issues caused by the big size, which might change the setup. Generally, the additional link options is transparent to users.
> 
> So far, You could check out https://github.com/pytorch/builder/blob/6f4bfa9625932cf44a0845d5bc23c8d2aaf62278/windows/internal/smoke_test.bat#L231 to find the latest change.
> 
> PS. For next version, the additional link option should be `/INCLUDE:?warp_size@cuda@at@@YAHXZ /INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z`


Thanks, it works in VS2022+cuda11.3

**Comment by mszhanyi** [comment]
> > @mszhanyi
> > > PS. For next version, the additional link option should be `/INCLUDE:?warp_size@cuda@at@@YAHXZ /INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z`
> > 
> > 
> > Thanks, it works in VS2022+cuda11.3
> 
> Hello, when I add this link option, it had a building error like: ![image](https://user-images.githubusercontent.com/26076957/273916406-3213e978-a301-4323-bf63-4d550e116b8a.png)
> 
> ![image](https://user-images.githubusercontent.com/26076957/273915842-28827bba-9901-476f-954e-9fba055b8c96.png)
> 
> Do you know how to solve it? Looking forward your reply.

Could you try my VS extension https://marketplace.visualstudio.com/items?itemName=YiZhang.libtorch2022
