### ISSUE TITLE
PyTorch not recognizing GPU on WSL - installed cudnn and cuda

### ISSUE THREAD

**Issue by AH-Merii** [pytorch/pytorch#73487]
### Version

Microsoft Windows [Version 10.0.22000.527] 

### WSL Version

- [X] WSL 2

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

* Install Cuda requirements as per [official wsl guide](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) 
* Run BlackScholes sample  -> Test Passes
* Install PyTorch on conda virtual environment using `conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`
* Activate conda environment 
* Run python 
* Import torch
* Run `torch.cuda.is_available()

### Expected Behavior

Expected behaviour is for `torch.cuda.is_available()` to return `True`

### Actual Behavior

`torch.cuda.is_available()` returns `False` instead

### Diagnostic Logs

```
❯ nvidia-smi
Sun Feb 27 23:12:27 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.52       Driver Version: 511.79       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   50C    P8    13W /  N/A |   2140MiB /  8192MiB |      6%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

```
❯ /usr/local/cuda-11/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Oct_11_21:27:02_PDT_2021
Cuda compilation tools, release 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0
```

```
❯ ./BlackScholes
[./BlackScholes] - Starting...
GPU Device 0: "Ampere" with compute capability 8.6

Initializing data...
...allocating CPU memory for options.
...allocating GPU memory for options.
...generating input data in CPU mem.
...copying input data to GPU mem.
Data init done.

Executing Black-Scholes GPU kernel (512 iterations)...
Options count             : 8000000
BlackScholesGPU() time    : 0.259223 msec
Effective memory bandwidth: 308.614999 GB/s
Gigaoptions per second    : 30.861500

BlackScholes, Throughput = 30.8615 GOptions/s, Time = 0.00026 s, Size = 8000000 options, NumDevsUsed = 1, Workgroup = 128

Reading back GPU results...
Checking the results...
...running CPU calculations.

Comparing the results...
L1 norm: 1.741792E-07
Max absolute error: 1.192093E-05

Shutting down...
...releasing GPU memory.
...releasing CPU memory.
Shutdown done.

[BlackScholes] - Test Summary

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

Test passed
```
## Running Python
```
❯ python
Python 3.9.7 (default, Sep 16 2021, 13:09:58)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.10.2+cu113'
>>> torch.cuda.is_available()
False
```

### Versions

```
❯ python collect_env.py
Collecting environment information...
PyTorch version: 1.10.2+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 11.4.152
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU
Nvidia driver version: 511.79
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] torch==1.10.2+cu113
[pip3] torchvision==0.11.3+rocm4.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.21.2           py39h20f2e39_0
[conda] numpy-base                1.21.2           py39h79a1101_0
[conda] pytorch                   1.10.2          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.2               py39_cu113    pytorch
[conda] torchvision               0.11.3               py39_cu113    pytorch
```

**Comment by malfet** [comment]
Hmm, can you please run `ldd -r path/to/libtorch_cuda.so`? (path can be inferred by running `import torch;print(torch.__file__)`

**Comment by AH-Merii** [comment]
### Running ```ldd -r path/to/libtorch_cuda.so```

```
❯ ldd -r .venv/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so
        linux-vdso.so.1 (0x00007ffc16575000)
        libtorch_cuda_cpp.so => /home/amerii/silence/activity_predictor/.venv/lib/python3.9/site-packages/torch/lib/libtorch_cuda_cpp.so (0x00007f4ada4c0000)
        libtorch_cpu.so => /home/amerii/silence/activity_predictor/.venv/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so (0x00007f4ac3b7c000)
        libtorch_cuda_cu.so => /home/amerii/silence/activity_predictor/.venv/lib/python3.9/site-packages/torch/lib/libtorch_cuda_cu.so (0x00007f4a80732000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4a80708000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4a80516000)
        libcudart-a7b20f20.so.11.0 => /home/amerii/silence/activity_predictor/.venv/lib/python3.9/site-packages/torch/lib/libcudart-a7b20f20.so.11.0 (0x00007f4a80277000)
        libc10_cuda.so => /home/amerii/silence/activity_predictor/.venv/lib/python3.9/site-packages/torch/lib/libc10_cuda.so (0x00007f4a80018000)
        libnvToolsExt-24de1d56.so.1 => /home/amerii/silence/activity_predictor/.venv/lib/python3.9/site-packages/torch/lib/libnvToolsExt-24de1d56.so.1 (0x00007f4a7fe0e000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4a7fdeb000)
        libc10.so => /home/amerii/silence/activity_predictor/.venv/lib/python3.9/site-packages/torch/lib/libc10.so (0x00007f4a7fb6b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4a7fa1c000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4a7fa14000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4a7fa09000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4a7f827000)
        libgomp-a34b3233.so.1 => /home/amerii/silence/activity_predictor/.venv/lib/python3.9/site-packages/torch/lib/libgomp-a34b3233.so.1 (0x00007f4a7f5fd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4b465bb000)
```

**Comment by AH-Merii** [comment]
> Also, can you please check if the same setup works natively on Windows?
```
(cuda) PS C:\Users\Abdul Hamid Merii> python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
```

**Comment by mszhanyi** [comment]
It looks Neither Pytorch nor Tensorflow can recognize the GPU

**Comment by mszhanyi** [comment]
@AH-Merii 
I couldn't reproduce it locally.
I guess you were running in WSL 1.
Please run `wsl -l -v` to check it.

**Comment by AH-Merii** [comment]
@mszhanyi 
```
PS C:\Users\Abdul Hamid Merii> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
```

**Comment by mszhanyi** [comment]
@AH-Merii did you install cudatoolkit in WSL ?
From you log, I see
```
Is CUDA available: False
CUDA runtime version: 11.4.152
```
I remember the cudatoolkit should be only installed in Windows native, not in WSL

**Comment by mszhanyi** [comment]
`I remember it's not necessary install cudatoolkit in WSL`
I don't find the source now.

But there isn't cuda directory in /usr/local

```
(py39) zhanyi@pengwa-z8:/mnt/c/Users/zhanyi$ ls /usr/local
bin  etc  games  include  lib  man  sbin  share  src
(py39) zhanyi@pengwa-z8:/mnt/c/Users/zhanyi$ pip show torch
Name: torch
Version: 1.10.2
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/zhanyi/miniconda3/envs/py39/lib/python3.9/site-packages
Requires: typing_extensions
Required-by: torchvision, torchaudio
(py39) zhanyi@pengwa-z8:/mnt/c/Users/zhanyi$ python -c "import torch; print(torch.cuda.is_available())"
True
```

**Comment by AH-Merii** [comment]
> @AH-Merii did you install cudatoolkit in WSL ? From you log, I see
@mszhanyi, yes I installed nvidia-cuda-toolkit on WSL. Are you saying that I should uninstall it? The [wsl user guide](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) states that you need to install it.

**Comment by mszhanyi** [comment]
If you have time, I suggest you to install a new WSL2 environment, for examples Ubuntu 18, to test. (it seems we couldn't create 2 WSL Ubuntu 20 )
You should run `/mnt/c/Windows/system32/nvidia-smi.exe` in WSL to check cuda status.

`WSL 2 GPU acceleration will be available on Pascal and later GPU architecture on both GeForce and Quadro product SKUs in WDDM mode. It will not be available on Quadro GPUs in TCC mode or Tesla GPUs yet.`
https://docs.nvidia.com/cuda/wsl-user-guide/index.html#wsl2-system-requirements
From your snapshot, it looks running in TCC mode.

**Comment by AH-Merii** [comment]
I will try doing that later today, thank you so much for your help!

**Comment by wqh17101** [comment]
I have the same problems for my WSL  Ubuntu 18

**Comment by mszhanyi** [comment]
@wqh17101 did you run `pip uninstall torch`  and use `pip show torch` to check the status before running conda install

**Comment by wqh17101** [comment]
> @wqh17101 did you run `pip uninstall torch` and use `pip show torch` to check the status before running conda install


@mszhanyi right，i use `pip install torch` and `pip install torch-1.10.2+cu113xxxx.whl` to compare. Also try conda but get the same issue.

**Comment by wqh17101** [comment]
What makes me confused is that `pip install torch` will install torch for cu102,`pip install torch-1.10.2+cu113xxxx.whl` will install torch for cu113,why `pip install torch` can recognize the gpu for my cuda is 116,and `pip install torch-1.10.2+cu113xxxx.whl` can not.

**Comment by mszhanyi** [comment]
`What makes me confused is that pip install torch will install torch for cu102,pip install torch-1.10.2+cu113xxxx.whl will install torch for cu113`
For this question, the reason is cudnn size exceeds the pypi limit since cuda 11.
So, pytorch packages with cuda 11.X are hosted in Pytorch site, not in PyPI

**Comment by wqh17101** [comment]
> `What makes me confused is that pip install torch will install torch for cu102,pip install torch-1.10.2+cu113xxxx.whl will install torch for cu113` For this question, the reason is cudnn size exceeds the pypi limit since cuda 11. So, pytorch packages with cuda 11.X are hosted in Pytorch site, not in PyPI

@malfet what i mean is that why `pip install torch` can recognize the gpu for my cuda is 116, and torch+cu113 can not

**Comment by mszhanyi** [comment]
related to https://github.com/pytorch/pytorch/issues/45028

**Comment by wqh17101** [comment]
So let me guess that torch`s cuda module does not support the system whose kernel  built without NUMA support.

**Comment by lkn2993** [comment]
I've been able to recreate this issue by installing pytorch or one of its dependencies as root.
This could be a permission issue.
You should make sure that all users can access:
/usr/local/cuda/
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/proc/driver/nvidia/version

**Comment by wqh17101** [comment]
@lkn2993 There is no `/proc/driver/nvidia/version`. The others can be accessed normally.

**Comment by lkn2993** [comment]
@wqh17101 [wqh17101](https://github.com/wqh17101)

Try in python shell:
>>> import tensorflow as tf
>>> tf.test.is_gpu_available()
>>> import torch
>>> torch.cuda.is_available()
Please enter all the commands in the specified order in a single shell and share the results.

**Comment by wqh17101** [comment]
```
>>> import tensorflow as tf
>>> tf.test.is_gpu_available()
WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2022-04-30 17:28:54.172793: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-30 17:28:54.379935: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-04-30 17:28:54.386758: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-04-30 17:28:54.387133: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-04-30 17:28:54.889972: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-04-30 17:28:54.890520: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-04-30 17:28:54.890554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1609] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.
2022-04-30 17:28:54.891010: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-04-30 17:28:54.891068: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /device:GPU:0 with 21634 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6
True
```

**Comment by wqh17101** [comment]
```
>>> import torch
>>> torch.cuda.is_available()
False
```

**Comment by wqh17101** [comment]
However, i can not run them together.
```
>>> import tensorflow as tf
>>> import torch
>>> tf.test.is_gpu_available()
WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2022-04-30 17:30:57.748349: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-30 17:30:57.899825: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-04-30 17:30:57.899865: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-QOESEPM): /proc/driver/nvidia/version does not exist
False
>>> torch.cuda.is_available()
False
```

**Comment by lkn2993** [comment]
I'm a bit confused about your reply.
Did you enter all 4 commands in a single python shell session in the specified order? From your replies it seems like you entered them two by two in two different sessions, and then entered them in wrong order. Just asking for clarification.

**Comment by wqh17101** [comment]
> I'm a bit confused about your reply.
> Did you enter all 4 commands in a single python shell session in the specified order? From your replies it seems like you entered them two by two in two different sessions, and then entered them in wrong order. Just asking for clarification

Each code block is an independent session.

Maybe you can write a doc about how to install your env as an example?

**Comment by kivle** [comment]
I have had the exact problem as described here when installing pytorch today. I found a solution in this thread in the pytorch forums: https://discuss.pytorch.org/t/trouble-installing-torch-with-cuda-using-conda-on-wsl2/136911/3.

I installed torch and torchvision with the following command on my system, and it now detects my GPU:

```
pip install torch==1.11.0+cu115 torchvision==0.12.0+cu115 -f https://download.pytorch.org/whl/torch_stable.html
```

Note that I download the latest wheels from the pytorch website directly (-f switch). These seem to function properly. I haven't figured out a workaround to get tensorflow working yet tho.

After this:

```
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.tensor(1).cuda()
tensor(1, device='cuda:0')
```

**Comment by wqh17101** [comment]
@kivle Sounds great. So the version of your cuda is 11.5?  Or 1.11.0+cu115 can fix this problem.

**Comment by haykh** [comment]
@kivle can confirm that this worked for me too. what was surprising is i tried the default thing on clean wsl2 instance: 
```sh
conda create -n torch python=3.8
conda activate torch
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
```
which worked flawlessly (i.e., `torch.cuda.is_available() == True`). on my normal wsl2 instance though i had to do the trick with `+cu111` (although actually the cuda on my host is 11.6). to be clear, i installed/uninstalled drivers/cudatoolkit a lot on my normal wsl2, so that might have messed things up. but by the time i was trying this i actually did not have any of them installed (just drivers/cudatoolkit on Win 11 host).

**Comment by wqh17101** [comment]
Amazing！I uninstall all torch torchvision torchaudio and try `pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`, and it works now

**Comment by CarlossShi** [comment]
> Amazing！I uninstall all torch torchvision torchaudio and try `pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`, and it works now. Follow this one https://discuss.pytorch.org/t/trouble-installing-torch-with-cuda-using-conda-on-wsl2/136911/4

@wqh17101 It work for me, thanks!

**Comment by geometrikal** [comment]
> @kivle can confirm that this worked for me too. what was surprising is i tried the default thing on clean wsl2 instance:
> 
> ```shell
> conda create -n torch python=3.8
> conda activate torch
> conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
> ```
> 
> which worked flawlessly (i.e., `torch.cuda.is_available() == True`). on my normal wsl2 instance though i had to do the trick with `+cu111` (although actually the cuda on my host is 11.6). to be clear, i installed/uninstalled drivers/cudatoolkit a lot on my normal wsl2, so that might have messed things up. but by the time i was trying this i actually did not have any of them installed (just drivers/cudatoolkit on Win 11 host).

I tried every single command I could find on the web but no luck, until I tried the above on a **clean** WSL2 instance (Ubuntu 20.04 LTS)

**Comment by cfwen** [comment]
I found I have to uninstall nvidia-cuda-toolkit in wsl2 in order to detect cuda inside conda

**Comment by taesiri** [comment]
> > > @kivle can confirm that this worked for me too. what was surprising is i tried the default thing on clean wsl2 instance:
> > > ```shell
> > > conda create -n torch python=3.8
> > > conda activate torch
> > > conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > which worked flawlessly (i.e., `torch.cuda.is_available() == True`). on my normal wsl2 instance though i had to do the trick with `+cu111` (although actually the cuda on my host is 11.6). to be clear, i installed/uninstalled drivers/cudatoolkit a lot on my normal wsl2, so that might have messed things up. but by the time i was trying this i actually did not have any of them installed (just drivers/cudatoolkit on Win 11 host).
> > 
> > 
> > I can confirm the same. If you're stuck, try uninstalling and reinstalling your wsl2 distribution (e.g., Ubuntu). Make sure you've installed the Nvidia driver on the Windows side (follow the official wsl2 setup docs). Let conda manage cudatoolkit for you; don't follow Nvidia's guide for installing cudatoolkit system-wide.
> 
> It actually works. Thank you.

Same for me, it works!

**Comment by leoleoasd** [comment]
From my side, sometimes installing from conda doesn't work, but installing from pip works. Make sure to use CUDA version greater or equal than the one shown in `nvidia-smi`.

**Comment by Cipher-zzz** [comment]
> I have had the exact problem as described here when installing pytorch today. I found a solution in this thread in the pytorch forums: https://discuss.pytorch.org/t/trouble-installing-torch-with-cuda-using-conda-on-wsl2/136911/3.
> 
> I installed torch and torchvision with the following command on my system, and it now detects my GPU:
> 
> ```
> pip install torch==1.11.0+cu115 torchvision==0.12.0+cu115 -f https://download.pytorch.org/whl/torch_stable.html
> ```
> 
> Note that I download the latest wheels from the pytorch website directly (-f switch). These seem to function properly. I haven't figured out a workaround to get tensorflow working yet tho.
> 
> After this:
> 
> ```
> Python 3.9.12 (main, Apr  5 2022, 06:56:58)
> [GCC 7.5.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> >>> torch.cuda.is_available()
> True
> >>> torch.tensor(1).cuda()
> tensor(1, device='cuda:0')
> ```

This worked for my case as well! Thank you.

**Comment by mattheweallen** [comment]
I am using mamba, which does the same thing as conda.

I was trying this
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

and getting

>>> import torch
>>> torch.cuda.is_available()
False

When installed with pip, it worked. I had uninstalled and reinstalled wsl Ubuntu before this. After running
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

it is working.

>>> import torch
>>> torch.cuda.is_available()
True

I wonder why conda is not working.

**Comment by hunglxtp** [comment]
This work for me too with new conda env python=3.8 
`(torch) xhle@PCP0051:~/Dev/Python/Medical-SAM-Adapter$ python
Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())
True
>>> torch.tensor(1).cuda()
tensor(1, device='cuda:0')`
