### ISSUE TITLE
NCCL Error 2: unhandled system error of `DataParallel`

### ISSUE THREAD

**Issue by BodyCSoulN** [pytorch/pytorch#73775]
### 🐛 Describe the bug

When I try to use mutil-GPUs with `DataParallel`, it occurs the error infos after servel times.

```python
batch_size, time_steps = 256, 35
train_iter, vocab = load_data_novel(batch_size, time_steps)
num_hiddens, num_layers = 256, 1
lstm_layer = nn.GRU(len(vocab), num_hiddens)
model = RNNModel(lstm_layer, len(vocab))
device, lr, num_epochs = d2l.try_gpu(), 1, 500
model = model.to(device)
model = nn.DataParallel(model, device_ids=[0, 1])
```
The outputs is below:
```bash
RuntimeError: NCCL Error 2: unhandled system error
```

And I try to print the debug info  by add `os.environ["NCCL_DEBUG"] = "INFO"`
The outputs is below:
```bash
198b6766dc7e:305:395 [0] NCCL INFO Could not enable P2P between dev 1(=1b000) and dev 0(=1a000)
198b6766dc7e:305:395 [0] NCCL INFO Could not enable P2P between dev 0(=1a000) and dev 1(=1b000)
198b6766dc7e:305:395 [0] NCCL INFO Could not enable P2P between dev 1(=1b000) and dev 0(=1a000)
198b6766dc7e:305:395 [0] NCCL INFO Could not enable P2P between dev 0(=1a000) and dev 1(=1b000)
198b6766dc7e:305:396 [1] NCCL INFO Could not enable P2P between dev 1(=1b000) and dev 0(=1a000)
198b6766dc7e:305:396 [1] NCCL INFO Could not enable P2P between dev 0(=1a000) and dev 1(=1b000)
198b6766dc7e:305:396 [1] NCCL INFO Could not enable P2P between dev 1(=1b000) and dev 0(=1a000)
198b6766dc7e:305:396 [1] NCCL INFO Could not enable P2P between dev 0(=1a000) and dev 1(=1b000)
198b6766dc7e:305:395 [0] NCCL INFO Channel 00/02 :    0   1
198b6766dc7e:305:396 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
198b6766dc7e:305:396 [1] NCCL INFO Setting affinity for GPU 1 to 0fffff00,000fffff
198b6766dc7e:305:395 [0] NCCL INFO Channel 01/02 :    0   1
198b6766dc7e:305:395 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
198b6766dc7e:305:395 [0] NCCL INFO Setting affinity for GPU 0 to 0fffff00,000fffff
198b6766dc7e:305:396 [1] NCCL INFO Could not enable P2P between dev 1(=1b000) and dev 0(=1a000)
198b6766dc7e:305:395 [0] NCCL INFO Could not enable P2P between dev 0(=1a000) and dev 1(=1b000)

198b6766dc7e:305:395 [0] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
198b6766dc7e:305:395 [0] NCCL INFO include/shm.h:41 -> 2

198b6766dc7e:305:395 [0] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-3e9ce13f22c8c69e-0-1-0 (size 9637888)
198b6766dc7e:305:395 [0] NCCL INFO transport/shm.cc:100 -> 2
198b6766dc7e:305:395 [0] NCCL INFO transport.cc:34 -> 2
198b6766dc7e:305:395 [0] NCCL INFO transport.cc:84 -> 2
198b6766dc7e:305:395 [0] NCCL INFO init.cc:778 -> 2
198b6766dc7e:305:395 [0] NCCL INFO init.cc:904 -> 2
198b6766dc7e:305:395 [0] NCCL INFO group.cc:72 -> 2 [Async thread]

198b6766dc7e:305:396 [1] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
198b6766dc7e:305:396 [1] NCCL INFO include/shm.h:41 -> 2

198b6766dc7e:305:396 [1] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-3e9ce13f22c8c69e-0-0-1 (size 9637888)
198b6766dc7e:305:396 [1] NCCL INFO transport/shm.cc:100 -> 2
198b6766dc7e:305:396 [1] NCCL INFO transport.cc:34 -> 2
198b6766dc7e:305:396 [1] NCCL INFO transport.cc:84 -> 2
198b6766dc7e:305:396 [1] NCCL INFO init.cc:778 -> 2
198b6766dc7e:305:396 [1] NCCL INFO init.cc:904 -> 2
198b6766dc7e:305:396 [1] NCCL INFO group.cc:72 -> 2 [Async thread]
198b6766dc7e:305:354 [0] NCCL INFO init.cc:973 -> 2
```
What can I do?
Thanks

### Versions

torch: 1.10.0
cuda: 11.3
platform: Ubuntu docker contianer of pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel

**Comment by cdeepali** [comment]
https://github.com/NVIDIA/nccl/issues/290#issuecomment-582524869

**Comment by BodyCSoulN** [comment]
> [NVIDIA/nccl#290 (comment)](https://github.com/NVIDIA/nccl/issues/290#issuecomment-582524869)
> 
> Looks like shared memory is not sufficient.

Thanks for your kind reminder.

Why this didn't happen at the first few times of my training？

And if I want to keep this docker container, do you have any suggestions?

**Comment by cdeepali** [comment]
I think best is to start a new container.

**Comment by BodyCSoulN** [comment]
> I think best is to start a new container.

Thanks so much,
I have solved this problem.

**Comment by Vaycold** [comment]
could you explain how to fix it? I struggle to fix this same error.... Like you, I wanna keep this docker container... isn't a solution..?? Also I wonder why this problem occur
