### ISSUE TITLE
A6000 Docker Ligthning ddp NCCL WARN Failed to open libibverbs.so 

### ISSUE THREAD

**Issue by johngrabner** [pytorch/pytorch#73790]
### 🐛 Describe the bug

[pytorch-lightning](https://pytorch.org/docs/stable/distributed.html) say "NCCL backends are built and included in PyTorch distributed (NCCL only when building with CUDA)"

When I upgrade my driver and docker from
> nvidia-driver-470 on the host
> FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime

to

> nvidia-driver-510 on the host
> FROM pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime 
> or later

and train with lightning ddp I get the error
`misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]`

I just upgraded my 2x (Titan RTX with nvlink) to 2x (A600 with no nvlink), pl version pytorch-lightning==1.0.7 and same error for version 1.5 . With Titan RTX, nvidia-driver-470,  and  pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime my pytorch-lighting code ran ddp flawlesly.

My call to train is as follows:

```
trainer = pl.Trainer( gpus=[0,1],  
        distributed_backend='ddp', # strategy='ddp' for pl=1.5
        ...
```

I can't stay on pytorch:1.6.0-cuda10.1-cudnn7 since A6000 needs sm_86 support.

Is pytorch-ligthing not doing something correctly with respect to NCCL or does the following docker images missing something or is the A6000 at fault?
```
FROM pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime
FROM pytorch/pytorch:1.9.1-cuda11.1-cudnn8-runtime 
FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime
FROM pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime 
```
### Demo of Issue
https://github.com/johngrabner/NCCL-WARN-Failed-to-open-libibverbs.git

### Versions

docker image pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime

bug_1  | Collecting environment information...
bug_1  | PyTorch version: 1.10.0
bug_1  | Is debug build: False
bug_1  | CUDA used to build PyTorch: 11.3
bug_1  | ROCM used to build PyTorch: N/A
bug_1  | OS: Ubuntu 18.04.6 LTS (x86_64)
bug_1  | GCC version: Could not collect
bug_1  | Clang version: Could not collect
bug_1  | CMake version: Could not collect
bug_1  | Libc version: glibc-2.17
bug_1  | Python version: 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0] (64-bit runtime)
bug_1  | Python platform: Linux-5.4.0-100-generic-x86_64-with-debian-buster-sid
bug_1  | Is CUDA available: True
bug_1  | CUDA runtime version: Could not collect
bug_1  | GPU models and configuration: 
bug_1  | GPU 0: NVIDIA RTX A6000
bug_1  | GPU 1: NVIDIA RTX A6000
bug_1  | 
bug_1  | Nvidia driver version: 510.47.03
bug_1  | cuDNN version: Could not collect
bug_1  | HIP runtime version: N/A
bug_1  | MIOpen runtime version: N/A
bug_1  | Is XNNPACK available: True
bug_1  | Versions of relevant libraries:
bug_1  | [pip3] numpy==1.21.2
bug_1  | [pip3] pytorch-lightning==1.5.10
bug_1  | [pip3] torch==1.10.0
bug_1  | [pip3] torchelastic==0.2.0
bug_1  | [pip3] torchmetrics==0.7.2
bug_1  | [pip3] torchtext==0.11.0
bug_1  | [pip3] torchvision==0.11.0
bug_1  | [conda] blas                      1.0                         mkl  
bug_1  | [conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
bug_1  | [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
bug_1  | [conda] mkl                       2021.3.0           h06a4308_520  
bug_1  | [conda] mkl-service               2.4.0            py37h7f8727e_0  
bug_1  | [conda] mkl_fft                   1.3.1            py37hd3c417c_0  
bug_1  | [conda] mkl_random                1.2.2            py37h51133e4_0  
bug_1  | [conda] numpy                     1.21.2           py37h20f2e39_0  
bug_1  | [conda] numpy-base                1.21.2           py37h79a1101_0  
bug_1  | [conda] pytorch                   1.10.0          py3.7_cuda11.3_cudnn8.2.0_0    pytorch
bug_1  | [conda] pytorch-lightning         1.5.10                   pypi_0    pypi
bug_1  | [conda] pytorch-mutex             1.0                        cuda    pytorch
bug_1  | [conda] torchelastic              0.2.0                    pypi_0    pypi
bug_1  | [conda] torchmetrics              0.7.2                    pypi_0    pypi
bug_1  | [conda] torchtext                 0.11.0                     py37    pytorch
bug_1  | [conda] torchvision               0.11.0               py37_cu113    pytorch
bug_1  | ****************************
bug_1  | initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
bug_1  | /opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/configuration_validator.py:120: UserWarning: You passed in a `val_dataloader` but have no `validation_step`. Skipping val loop.
bug_1  |   rank_zero_warn("You passed in a `val_dataloader` but have no `validation_step`. Skipping val loop.")
bug_1  | initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
bug_1  | ----------------------------------------------------------------------------------------------------
bug_1  | distributed_backend=nccl
bug_1  | All distributed processes registered. Starting with 2 processes
bug_1  | ----------------------------------------------------------------------------------------------------
bug_1  | 
bug_1  | 
bug_1  | be7823cc7810:7:7 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
bug_1  | NCCL version 2.10.3+cuda11.3
bug_1  | 
bug_1  | be7823cc7810:72:72 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]

The small minimal demo code [small minimal demo code](https://github.com/johngrabner/NCCL-WARN-Failed-to-open-libibverbs.git) runs to completion in 2 minutes on 1 GPU and no DPP. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by ptrblck** [comment]
`NCCL WARN Failed to open libibverbs.so[.1]` shouldn't be an issue as it would enable RDMA only, but shouldn't create a hang (I'm seeing the same warning when trying to reproduce).
So far I wasn't able to reproduce the hang on an 8xA100 and 2x3090 node (I don't have a node with multiple A6000s available yet) using `pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime` and the `bug-demo.py` script. 

I assume you are directly seeing the hang?
 If so, do you see any other outputs from NCCL by using `export NCCL_DEBUG=INFO`?
 If not, could you run the [nccl-test](https://github.com/NVIDIA/nccl-tests) in your setup and see if the communication works?

**Comment by pritamdamania87** [comment]
> If so, do you see any other outputs from NCCL by using export NCCL_DEBUG=INFO?

@johngrabner If this is indeed a hang in addition to `NCCL_DEBUG=INFO` can you also set the environment variable `TORCH_DISTRIBUTED_DEBUG=DETAIL`. That would provide a lot more detailed debug information to enable troubleshooting this issue further.

**Comment by johngrabner** [comment]
Updated [minimal example of issue](https://github.com/johngrabner/NCCL-WARN-Failed-to-open-libibverbs.git) with suggested TORCH_DISTRIBUTED_DEBUG=DETAIL and  NCCL_DEBUG=INFO
The output is now:
```
bug_1  | start =  2022-03-05 15:37:57.762277
bug_1  | initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
bug_1  | initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
bug_1  | ----------------------------------------------------------------------------------------------------
bug_1  | distributed_backend=nccl
bug_1  | All distributed processes registered. Starting with 2 processes
bug_1  | ----------------------------------------------------------------------------------------------------
bug_1  | 
bug_1  | 5b925186e432:8:8 [0] NCCL INFO Bootstrap : Using eth0:172.20.0.2<0>
bug_1  | 5b925186e432:8:8 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
bug_1  | 
bug_1  | 5b925186e432:8:8 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
bug_1  | 5b925186e432:8:8 [0] NCCL INFO NET/Socket : Using [0]eth0:172.20.0.2<0>
bug_1  | 5b925186e432:8:8 [0] NCCL INFO Using network Socket
bug_1  | NCCL version 2.10.3+cuda11.3
bug_1  | 5b925186e432:72:72 [1] NCCL INFO Bootstrap : Using eth0:172.20.0.2<0>
bug_1  | 5b925186e432:72:72 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
bug_1  | 
bug_1  | 5b925186e432:72:72 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
bug_1  | 5b925186e432:72:72 [1] NCCL INFO NET/Socket : Using [0]eth0:172.20.0.2<0>
bug_1  | 5b925186e432:72:72 [1] NCCL INFO Using network Socket
bug_1  | 5b925186e432:8:152 [0] NCCL INFO Channel 00/04 :    0   1
bug_1  | 5b925186e432:72:153 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1 [2] -1/-1/-1->1->0 [3] 0/-1/-1->1->-1
bug_1  | 5b925186e432:8:152 [0] NCCL INFO Channel 01/04 :    0   1
bug_1  | 5b925186e432:8:152 [0] NCCL INFO Channel 02/04 :    0   1
bug_1  | 5b925186e432:8:152 [0] NCCL INFO Channel 03/04 :    0   1
bug_1  | 5b925186e432:8:152 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1 [2] 1/-1/-1->0->-1 [3] -1/-1/-1->0->1
bug_1  | 5b925186e432:72:153 [1] NCCL INFO Channel 00 : 1[4a000] -> 0[21000] via P2P/IPC
bug_1  | 5b925186e432:8:152 [0] NCCL INFO Channel 00 : 0[21000] -> 1[4a000] via P2P/IPC
bug_1  | 5b925186e432:72:153 [1] NCCL INFO Channel 01 : 1[4a000] -> 0[21000] via P2P/IPC
bug_1  | 5b925186e432:8:152 [0] NCCL INFO Channel 01 : 0[21000] -> 1[4a000] via P2P/IPC
bug_1  | 5b925186e432:72:153 [1] NCCL INFO Channel 02 : 1[4a000] -> 0[21000] via P2P/IPC
bug_1  | 5b925186e432:8:152 [0] NCCL INFO Channel 02 : 0[21000] -> 1[4a000] via P2P/IPC
bug_1  | 5b925186e432:72:153 [1] NCCL INFO Channel 03 : 1[4a000] -> 0[21000] via P2P/IPC
bug_1  | 5b925186e432:8:152 [0] NCCL INFO Channel 03 : 0[21000] -> 1[4a000] via P2P/IPC
bug_1  | 5b925186e432:72:153 [1] NCCL INFO Connected all rings
bug_1  | 5b925186e432:72:153 [1] NCCL INFO Connected all trees
bug_1  | 5b925186e432:72:153 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
bug_1  | 5b925186e432:72:153 [1] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
bug_1  | 5b925186e432:8:152 [0] NCCL INFO Connected all rings
bug_1  | 5b925186e432:8:152 [0] NCCL INFO Connected all trees
bug_1  | 5b925186e432:8:152 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
bug_1  | 5b925186e432:8:152 [0] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
bug_1  | 5b925186e432:8:152 [0] NCCL INFO comm 0x7fa0f8002f70 rank 0 nranks 2 cudaDev 0 busId 21000 - Init COMPLETE
bug_1  | 5b925186e432:72:153 [1] NCCL INFO comm 0x7f4e64002f70 rank 1 nranks 2 cudaDev 1 busId 4a000 - Init COMPLETE
bug_1  | 5b925186e432:8:8 [0] NCCL INFO Launch mode Parallel

```

**Comment by johngrabner** [comment]
Working on [nccl-test](https://github.com/NVIDIA/nccl-tests). My host only has nvidia driver installed, everything else (CUDA, pytorch, etc) is in docker.  So working on dockerizing ncc-test.

**Comment by johngrabner** [comment]
[ptrblck](https://github.com/ptrblck) when you say
> So far I wasn't able to reproduce the hang on an 8xA100 and 2x3090 node (I don't have a node with multiple A6000s available yet) using `pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime` and the `bug-demo.py` script.
does this mean you ran inside docker ie: run.sh or that you ran 'bug-demo.py' in a terminal on your host?

The reason I ask is to eliminate the possibility that docker, docker-compose, or nvidia plugin for docker is contributing to the issue.

**Comment by johngrabner** [comment]
I installed CUDA, pytorch, etc on the host directly. Same behavior, so docker, docker-compose and nvidia plugin not implicated. Here is the output of a local run:
`

(base) john@john-trx40-designare:/Disk2/Documents/GitHub/NCCL-WARN-Failed-to-open-libibverbs$ python bug-demo.py 
****************************
Collecting environment information...
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A
OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27
Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-100-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000

Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] numpydoc==1.1.0
[pip3] pytorch-lightning==1.5.10
[pip3] torch==1.10.2
[pip3] torchaudio==0.10.2
[pip3] torchmetrics==0.7.2
[pip3] torchvision==0.11.3
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] mypy_extensions           0.4.3            py39h06a4308_0  
[conda] numpy                     1.20.3           py39hf144106_0  
[conda] numpy-base                1.20.3           py39h74d4b33_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1  
[conda] pytorch                   1.10.2          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-lightning         1.5.10                   pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.2               py39_cu113    pytorch
[conda] torchmetrics              0.7.2                    pypi_0    pypi
[conda] torchvision               0.11.3               py39_cu113    pytorch
****************************
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
start =  2022-03-05 12:01:18.458594
****************************
Collecting environment information...
initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A
OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27
Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-100-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000

Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] numpydoc==1.1.0
[pip3] pytorch-lightning==1.5.10
[pip3] torch==1.10.2
[pip3] torchaudio==0.10.2
[pip3] torchmetrics==0.7.2
[pip3] torchvision==0.11.3
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] mypy_extensions           0.4.3            py39h06a4308_0  
[conda] numpy                     1.20.3           py39hf144106_0  
[conda] numpy-base                1.20.3           py39h74d4b33_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1  
[conda] pytorch                   1.10.2          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-lightning         1.5.10                   pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.2               py39_cu113    pytorch
[conda] torchmetrics              0.7.2                    pypi_0    pypi
[conda] torchvision               0.11.3               py39_cu113    pytorch
****************************
start =  2022-03-05 12:01:21.519819
initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

john-trx40-designare:115664:115664 [0] NCCL INFO Bootstrap : Using enp68s0:99.153.71.9<0>
john-trx40-designare:115664:115664 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

john-trx40-designare:115664:115664 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
john-trx40-designare:115664:115664 [0] NCCL INFO NET/Socket : Using [0]enp68s0:99.153.71.9<0> [1]br-59eaa4e42ac2:172.18.0.1<0> [2]br-3d49efffbc73:172.20.0.1<0> [3]cali1076d8e8af2:fe80::ecee:eeff:feee:eeee%cali1076d8e8af2<0> [4]cali0c52663fc35:fe80::ecee:eeff:feee:eeee%cali0c52663fc35<0> [5]calie16d311fc06:fe80::ecee:eeff:feee:eeee%calie16d311fc06<0> [6]cali131248ab6e9:fe80::ecee:eeff:feee:eeee%cali131248ab6e9<0> [7]cali5121ec8cf25:fe80::ecee:eeff:feee:eeee%cali5121ec8cf25<0> [8]calia95dbd6fa2b:fe80::ecee:eeff:feee:eeee%calia95dbd6fa2b<0> [9]calif539d814c76:fe80::ecee:eeff:feee:eeee%calif539d814c76<0> [10]cali2c18a725646:fe80::ecee:eeff:feee:eeee%cali2c18a725646<0> [11]cali83cea9e8363:fe80::ecee:eeff:feee:eeee%cali83cea9e8363<0> [12]calie09d3bd71b5:fe80::ecee:eeff:feee:eeee%calie09d3bd71b5<0> [13]cali908066cb99b:fe80::ecee:eeff:feee:eeee%cali908066cb99b<0> [14]cali1284eb98b46:fe80::ecee:eeff:feee:eeee%cali1284eb98b46<0> [15]cali30793a6fc52:fe80::ecee:eeff:feee:eeee%cali30793a6fc52<0>
john-trx40-designare:115664:115664 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda11.3
john-trx40-designare:115828:115828 [1] NCCL INFO Bootstrap : Using enp68s0:99.153.71.9<0>
john-trx40-designare:115828:115828 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

john-trx40-designare:115828:115828 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
john-trx40-designare:115828:115828 [1] NCCL INFO NET/Socket : Using [0]enp68s0:99.153.71.9<0> [1]br-59eaa4e42ac2:172.18.0.1<0> [2]br-3d49efffbc73:172.20.0.1<0> [3]cali1076d8e8af2:fe80::ecee:eeff:feee:eeee%cali1076d8e8af2<0> [4]cali0c52663fc35:fe80::ecee:eeff:feee:eeee%cali0c52663fc35<0> [5]calie16d311fc06:fe80::ecee:eeff:feee:eeee%calie16d311fc06<0> [6]cali131248ab6e9:fe80::ecee:eeff:feee:eeee%cali131248ab6e9<0> [7]cali5121ec8cf25:fe80::ecee:eeff:feee:eeee%cali5121ec8cf25<0> [8]calia95dbd6fa2b:fe80::ecee:eeff:feee:eeee%calia95dbd6fa2b<0> [9]calif539d814c76:fe80::ecee:eeff:feee:eeee%calif539d814c76<0> [10]cali2c18a725646:fe80::ecee:eeff:feee:eeee%cali2c18a725646<0> [11]cali83cea9e8363:fe80::ecee:eeff:feee:eeee%cali83cea9e8363<0> [12]calie09d3bd71b5:fe80::ecee:eeff:feee:eeee%calie09d3bd71b5<0> [13]cali908066cb99b:fe80::ecee:eeff:feee:eeee%cali908066cb99b<0> [14]cali1284eb98b46:fe80::ecee:eeff:feee:eeee%cali1284eb98b46<0> [15]cali30793a6fc52:fe80::ecee:eeff:feee:eeee%cali30793a6fc52<0>
john-trx40-designare:115828:115828 [1] NCCL INFO Using network Socket
john-trx40-designare:115664:115974 [0] NCCL INFO Channel 00/04 :    0   1
john-trx40-designare:115828:115975 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1 [2] -1/-1/-1->1->0 [3] 0/-1/-1->1->-1
john-trx40-designare:115664:115974 [0] NCCL INFO Channel 01/04 :    0   1
john-trx40-designare:115664:115974 [0] NCCL INFO Channel 02/04 :    0   1
john-trx40-designare:115664:115974 [0] NCCL INFO Channel 03/04 :    0   1
john-trx40-designare:115664:115974 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1 [2] 1/-1/-1->0->-1 [3] -1/-1/-1->0->1
john-trx40-designare:115828:115975 [1] NCCL INFO Channel 00 : 1[4a000] -> 0[21000] via P2P/IPC
john-trx40-designare:115828:115975 [1] NCCL INFO Channel 01 : 1[4a000] -> 0[21000] via P2P/IPC
john-trx40-designare:115828:115975 [1] NCCL INFO Channel 02 : 1[4a000] -> 0[21000] via P2P/IPC
john-trx40-designare:115664:115974 [0] NCCL INFO Channel 00 : 0[21000] -> 1[4a000] via P2P/IPC
john-trx40-designare:115828:115975 [1] NCCL INFO Channel 03 : 1[4a000] -> 0[21000] via P2P/IPC
john-trx40-designare:115664:115974 [0] NCCL INFO Channel 01 : 0[21000] -> 1[4a000] via P2P/IPC
john-trx40-designare:115664:115974 [0] NCCL INFO Channel 02 : 0[21000] -> 1[4a000] via P2P/IPC
john-trx40-designare:115664:115974 [0] NCCL INFO Channel 03 : 0[21000] -> 1[4a000] via P2P/IPC
john-trx40-designare:115664:115974 [0] NCCL INFO Connected all rings
john-trx40-designare:115664:115974 [0] NCCL INFO Connected all trees
john-trx40-designare:115664:115974 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
john-trx40-designare:115664:115974 [0] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
john-trx40-designare:115828:115975 [1] NCCL INFO Connected all rings
john-trx40-designare:115828:115975 [1] NCCL INFO Connected all trees
john-trx40-designare:115828:115975 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
john-trx40-designare:115828:115975 [1] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
john-trx40-designare:115828:115975 [1] NCCL INFO comm 0x7f16a0002f70 rank 1 nranks 2 cudaDev 1 busId 4a000 - Init COMPLETE
john-trx40-designare:115664:115974 [0] NCCL INFO comm 0x7fb178002f70 rank 0 nranks 2 cudaDev 0 busId 21000 - Init COMPLETE
john-trx40-designare:115664:115664 [0] NCCL INFO Launch mode Parallel

`

**Comment by ptrblck** [comment]
Thanks for the updates @johngrabner. Were you able to build and run the `nccl-test`s? Based on the current output I cannot see any obvious issues (yet).

**Comment by ptrblck** [comment]
@johngrabner Could you check if disabling `IOMMU` helps as described [here](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#pci-access-control-services-acs) as it could also cause a hang?

**Comment by johngrabner** [comment]
**re: Were you able to build and run the nccl-tests?**

ncc-test needs a link to CUDA and NCCL , I can't seem to find these inside the docker image  pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime or any later docker image. Other than that I wrapped everything into a [docker nccl-test](https://github.com/johngrabner/nccl-tests.git) 

I never installed NCCL on my host, at least not intentionally. I assume this should be in the image.

**re: IOMMU**

I will start on this right after I post for help find location of CUDA and NCCL inside the pytorch docker images.

**re: logs**

I noticed "NCCL INFO Using network Socket" in the logs.  I would assume that PCIe4 would be a lot faster. Both A6000 and DesignAre have pcie4.  Does this not look wrong?

**Comment by ptrblck** [comment]
> I can't seem to find these inside the docker image pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime or any later docker image

Use the `-devel` container, which should ship with the CUDA toolkit and would allow you to build the tests.

Also, make sure to use the CUDA 11 toolkit for your A6000s. E.g. `pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel` should work.

**Comment by johngrabner** [comment]
will do

**Comment by johngrabner** [comment]
Not confident with the above results.
```
root@365eece4b928:/nccl-test# find / -name nccl
/opt/conda/lib/python3.7/site-packages/caffe2/contrib/nccl
/opt/conda/pkgs/pytorch-1.10.0-py3.7_cuda11.3_cudnn8.2.0_0/lib/python3.7/site-packages/caffe2/contrib/nccl
```
So I don't see nccl in /usr
and readme of nccl-test says

```
To build the tests, just type make.

If CUDA is not installed in /usr/local/cuda, you may specify CUDA_HOME. Similarly, if NCCL is not installed in /usr, you may specify NCCL_HOME.

$ make CUDA_HOME=/path/to/cuda NCCL_HOME=/path/to/nccl

```
but I just did the default make as in 
```
root@365eece4b928:/nccl-test# make
Compiling  all_reduce.cu                       > ../build/all_reduce.o
....
```

**Comment by johngrabner** [comment]
uploaded the updated [docker image of nccl-test for 2 GPUs](https://github.com/johngrabner/nccl-tests.git)
Could someone try 
`sh run.sh`
to verify that it works correctly. On my system, it freezes as I indicated in the log above.

**Comment by johngrabner** [comment]
[ptrblck](https://github.com/ptrblck) your suggestion  [to disable IOMMU](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#pci-access-control-services-acs) was the solution.  Now everything started working. Thank you so much. I would have never found this without your help. Thank you.

The [docker of nccl-test for 2 gpu](https://github.com/johngrabner/nccl-tests.git) now does not get locked up.
```
Attaching to nccl-test_nccl-test_1
nccl-test_1  | # nThread 1 nGpus 2 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 1 
nccl-test_1  | #
nccl-test_1  | # Using devices
nccl-test_1  | #   Rank  0 Pid      7 on 573d30dd91e4 device  0 [0x21] NVIDIA RTX A6000
nccl-test_1  | #   Rank  1 Pid      7 on 573d30dd91e4 device  1 [0x4a] NVIDIA RTX A6000
nccl-test_1  | #
nccl-test_1  | #                                                       out-of-place                       in-place          
nccl-test_1  | #       size         count      type   redop     time   algbw   busbw  error     time   algbw   busbw  error
nccl-test_1  | #        (B)    (elements)                       (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
nccl-test_1  |            8             2     float     sum     6.52    0.00    0.00  0e+00     6.60    0.00    0.00  0e+00
nccl-test_1  |           16             4     float     sum     6.60    0.00    0.00  0e+00     6.56    0.00    0.00  0e+00
nccl-test_1  |           32             8     float     sum     6.64    0.00    0.00  0e+00     6.56    0.00    0.00  0e+00
nccl-test_1  |           64            16     float     sum     6.67    0.01    0.01  0e+00     6.56    0.01    0.01  0e+00
nccl-test_1  |          128            32     float     sum     6.67    0.02    0.02  0e+00     6.64    0.02    0.02  0e+00
nccl-test_1  |          256            64     float     sum     6.73    0.04    0.04  0e+00     6.78    0.04    0.04  0e+00
nccl-test_1  |          512           128     float     sum     6.79    0.08    0.08  0e+00     6.67    0.08    0.08  0e+00
nccl-test_1  |         1024           256     float     sum     6.82    0.15    0.15  0e+00     6.93    0.15    0.15  0e+00
nccl-test_1  |         2048           512     float     sum     6.97    0.29    0.29  0e+00     6.88    0.30    0.30  0e+00
nccl-test_1  |         4096          1024     float     sum     7.38    0.56    0.56  0e+00     7.29    0.56    0.56  0e+00
nccl-test_1  |         8192          2048     float     sum     7.99    1.03    1.03  0e+00     7.94    1.03    1.03  0e+00
nccl-test_1  |        16384          4096     float     sum    10.17    1.61    1.61  0e+00     9.99    1.64    1.64  0e+00
nccl-test_1  |        32768          8192     float     sum    11.63    2.82    2.82  0e+00    11.24    2.92    2.92  0e+00
nccl-test_1  |        65536         16384     float     sum    14.27    4.59    4.59  0e+00    13.70    4.78    4.78  0e+00
nccl-test_1  |       131072         32768     float     sum    26.72    4.90    4.90  0e+00    26.55    4.94    4.94  0e+00
nccl-test_1  |       262144         65536     float     sum    32.31    8.11    8.11  0e+00    32.23    8.13    8.13  0e+00
nccl-test_1  |       524288        131072     float     sum    43.38   12.09   12.09  0e+00    43.32   12.10   12.10  0e+00
nccl-test_1  |      1048576        262144     float     sum    66.38   15.80   15.80  0e+00    66.35   15.80   15.80  0e+00
nccl-test_1  |      2097152        524288     float     sum    118.8   17.66   17.66  0e+00    129.7   16.17   16.17  0e+00
nccl-test_1  |      4194304       1048576     float     sum    224.5   18.69   18.69  0e+00    223.2   18.79   18.79  0e+00
nccl-test_1  |      8388608       2097152     float     sum    441.8   18.99   18.99  0e+00    470.7   17.82   17.82  0e+00
nccl-test_1  |     16777216       4194304     float     sum    915.9   18.32   18.32  0e+00    910.8   18.42   18.42  0e+00
nccl-test_1  |     33554432       8388608     float     sum   1833.0   18.31   18.31  0e+00   1725.2   19.45   19.45  0e+00
nccl-test_1  |     67108864      16777216     float     sum   3591.1   18.69   18.69  0e+00   3431.6   19.56   19.56  0e+00
nccl-test_1  |    134217728      33554432     float     sum   6939.5   19.34   19.34  0e+00   6853.9   19.58   19.58  0e+00
nccl-test_1  | # Out of bounds values : 0 OK
nccl-test_1  | # Avg bus bandwidth    : 7.2876 
nccl-test_1  | #
nccl-test_nccl-test_1 exited with code 0
(base) john@john-trx40-designare:/Disk2/Documents/GitHub/nccl-tests$ 
```

The [small code demo of issue](https://github.com/johngrabner/NCCL-WARN-Failed-to-open-libibverbs.git) now works too.
`
bug_1  |   | Name | Type   | Params
bug_1  | --------------------------------
bug_1  | 0 | l1   | Linear | 7.9 K 
bug_1  | --------------------------------
bug_1  | 7.9 K     Trainable params
bug_1  | 0         Non-trainable params
bug_1  | 7.9 K     Total params
bug_1  | 0.031     Total estimated model params size (MB)
Epoch 0:   0%|          | 0/118 [00:00<?, ?it/s] [W reducer.cpp:1303] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
bug_1  | [W reducer.cpp:1303] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
Epoch 99: 100%|██████████| 118/118 [00:01<00:00, 107.27it/s, loss=0.401, v_num=0]end =  2022-03-05 22:42:19.640865
bug_1  | 
bug_1  | end =  2022-03-05 22:42:19.643567
bug_bug_1 exited with code 0
`

**Comment by zzm-hl** [comment]
Hello, I have the same problem, but my running platform is on a cluster, not a personal computer, so I can't disable IOMMU. I would like to ask if there are other ways. The graphics card is eight A100

**Comment by bradfox2** [comment]
@zzm-hl Did you ever find a solution, disabling IOMMU is also not an option for me.  TIA

**Comment by jeongwhanchoi** [comment]
@zzm-hl @bradfox2 I have the same problem. Did you ever find a solution?

**Comment by johngrabner** [comment]
I disable IOMMU in the bios

**Comment by jeongwhanchoi** [comment]
@johngrabner Thank you, I will try it.

**Comment by eliasbaumann** [comment]
Since i first found this issue while encounting a similar problem, this fixed the issue for me: https://github.com/pytorch/pytorch/issues/1637#issuecomment-730423426 

`export NCCL_P2P_DISABLE=1 `
before running torchrun / python code
