### ISSUE TITLE
Any bug triggers device-side assert

### ISSUE THREAD

**Issue by cemde** [pytorch/pytorch#74079]
### 🐛 Describe the bug

**Any** pytorch error involving a tensor on a GPU results in a  `CUDA error: device-side assert triggered`. Once that happens nothing involving cuda tensors works anymore.

To replicate, we produce a simple error. First, on the CPU

``` python
import torch
import torch.nn.functional as F

a = torch.randint(0,10,(100,))
F.one_hot(a, num_classes=9)
```
results in the predicted error:
``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Class values must be smaller than num_classes.
```
which is what we want :)

Now running this on the GPU
``` python
F.one_hot(a.cuda(), num_classes=9)
```
results in 
``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cornelius/anaconda3/envs/quantml/lib/python3.9/site-packages/torch/_tensor.py", line 305, in __repr__
    return torch._tensor_str._str(self)
  File "/home/cornelius/anaconda3/envs/quantml/lib/python3.9/site-packages/torch/_tensor_str.py", line 434, in _str
    return _str_intern(self)
  File "/home/cornelius/anaconda3/envs/quantml/lib/python3.9/site-packages/torch/_tensor_str.py", line 409, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/cornelius/anaconda3/envs/quantml/lib/python3.9/site-packages/torch/_tensor_str.py", line 264, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/cornelius/anaconda3/envs/quantml/lib/python3.9/site-packages/torch/_tensor_str.py", line 96, in __init__
    value_str = '{}'.format(value)
  File "/home/cornelius/anaconda3/envs/quantml/lib/python3.9/site-packages/torch/_tensor.py", line 627, in __format__
    return self.item().__format__(format_spec)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
>>> ../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [99,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [33,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [50,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [52,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [3,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [9,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [21,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [22,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [77,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [86,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [94,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
```

Following the advice for debugging, I ran `CUDA_LAUNCH_BLOCKING=1 python` and repeated the steps above which yields this error message:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Class values must be smaller than num_classes.
>>> F.one_hot(a.cuda(), num_classes=9)
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [68,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [85,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [93,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [104,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [117,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [120,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [125,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [41,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [47,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [50,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [62,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [4,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [19,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [25,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [30,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: device-side assert triggered
```

After this, any operation will trigger `RuntimeError: CUDA error: device-side assert triggered`. This makes debugging almost impossible.

### Versions

**System**:

Linux version 5.13.0-35-generic

Ubuntu 20.04.4 LTS

Cuda driver (according to nvidia-smi): 495.29.05
GPU: 3090 FE

**Python**:

Python 3.9.7
```
# Name                    Version                   Build  Channel
pytorch                   1.10.2          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
cudatoolkit               11.3.1               h2bc3f7f_2  
```

I can further replicate the error in the same system with:
pytorch 1.11 and pytorch 1.10.2 built from PyPI.

I **CANNOT** replicate the error in the same system with:
```
# Name                    Version                   Build  Channel
pytorch                   1.8.2           py3.8_cuda11.1_cudnn8.0.5_0    pytorch-lts
```

cc @ngimel

**Comment by ngimel** [comment]
This is expected behavior, and not a regression. Providing better error messages would either require checking all the data in advance, which results in perf penalty, or using some sophisticated mechanisms that are hard to get right (see #26776 for an attempt).

**Comment by albanD** [comment]
Closing as expected behavior and there is work towards a different approach already.

**Comment by cemde** [comment]
> This is expected behavior, and not a regression. Providing better error messages would either require checking all the data in advance, which results in perf penalty, or using some sophisticated mechanisms that are hard to get right (see #26776 for an attempt).

I cannot imagine this is wanted. I replicated this script on a different machine and the error messages on GPU and CPU are the same and useful. I was able to get multiple *different* and *useful* error messages on GPU and CPU and not just 1 single error message for *all* errors.

If this is wanted, what is the rational for removing thousands of useful error messages with a single one that tells you nothing about the error?

Whatever is wanted, the behaviour is inconsistent.

**Comment by ngimel** [comment]
Invalid indices trigger illegal memory access on the GPU. After that, GPU context is invalidated, and GPU operations can only produce the last (context invalidating) error message. This is a consistent behavior across all GPUs, and, unfortunately, due to asynchronous nature of GPU execution we cannot provide messages that are as helpful as on the CPU.

**Comment by LindaSt** [comment]
@cemde how did you resolve this problem? Downgrading to 1.8.2?

**Comment by halqadasi** [comment]
You have a problem with the number of classes, you have 10 classes and you provide 9 classes to F.hot_code:


```
import torch
import torch.nn.functional as F

a = torch.randint(0,10,(100,))
F.one_hot(a, num_classes=10)  # corrected from 9 to 10
```

**Comment by cemde** [comment]
@halqadasi  yes, correct. The purpose was to trigger `RuntimeError: CUDA error: device-side assert triggered`.

**Comment by halqadasi** [comment]
I solved my problem which is very similar to your problem by moving all my model and data from GPU to CPU and then running the code. Then, the error log explained to me the error clearly and I solved it 🥇  :)
