### ISSUE TITLE
Caffe2 install failure

### ISSUE THREAD

**Issue by tarlen5** [pytorch/pytorch#7426]
## Issue description

I'm getting a build/compilation error when I try to install caffe2 on Ubuntu 16.04, with CUDA v9.1. This looks to me like it's some sort of cuda error, but I can't for the life of me figure out what's going wrong, because the errors appear to be coming from the cuda header files, like this:

```
/usr/local/cuda/include/crt/common_functions.h:64:24: error: token ""__CUDACC_VER__ is no
longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD_
_ instead."" is not valid in preprocessor expressions
```
Then it tells me cmake error:

```
CMake Error at caffe2_gpu_generated_math_gpu.cu.o.Release.cmake:215 (message):
  Error generating
  /home/ubuntu/local/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/utils/./caffe2_gpu_gen
erated_math_gpu.cu.o
```

See below screenshots for full output errors.

## Code example

I'm simply trying to build caffe2 from source, using anaconda, following [these instructions](https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile#custom-anaconda-install): 

`cmake -DCMAKE_PREFIX_PATH=~/anaconda2/envs/caffe2/ -DCMAKE_INSTALL_PREFIX=~/anaconda/envs/caffe2 ..`

`make install`

## System Info

- PyTorch or Caffe2: caffe2
- How you installed PyTorch (conda, pip, source): Following instructions from [here](https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile#custom-anaconda-install) to install caffe2 on my system with anaconda python in a clean environment.
- Build command you used (if compiling from source): 

`cmake -DCMAKE_PREFIX_PATH=~/anaconda2/envs/caffe2/ -DCMAKE_INSTALL_PREFIX=~/anaconda/envs/caffe2 ..`

`make install`

- OS: ubuntu 16.04
- PyTorch version: none
- Python version: 2.7.15 (anaconda)
- CUDA/cuDNN version: cuda version 9.1, cuDNN version 7.0.5
- GPU models and configuration: Tesla M60 (on AWS EC2)
- GCC version (if compiling from source): 5.4.0
- CMake version: 3.5.1
- Versions of any other relevant libraries: not sure?

I ran the cmake command and outputted the information to this log file:
[cmake.log](https://github.com/pytorch/pytorch/files/1988638/cmake.log)

Here is the complete error output from the `make install`  command:

![screen shot 2018-05-09 at 9 25 06 am](https://user-images.githubusercontent.com/6472638/39826882-06dd6810-536b-11e8-9983-c4ba66fe8641.png)

![screen shot 2018-05-09 at 9 25 48 am](https://user-images.githubusercontent.com/6472638/39826886-0c0d32b6-536b-11e8-946d-70cd60a4a774.png)

**Comment by tarlen5** [comment]
Incredibly, I was able to eventually find the solution to my problem. I will post my solution here, in case someone else stumbles upon this same problem, then I'll close this issue. 

1. Someone else had a similar issue on the caffe2 repo: https://github.com/caffe2/caffe2/issues/2487 and the solution was to re-install the eigen3 library from the master branch at the [github mirror](https://github.com/eigenteam/eigen-git-mirror.git). So that solved this particular issue.
2. Next, I had another problem with cuda/cudnn somehow (that I did not screenshot) but it was similar to [this problem](https://discuss.pytorch.org/t/solved-source-compile-error/9490). Incredibly, as this link suggests, the solution was to change a line in the file: /usr/include/cudnn.h from
```c++
#include “driver_types.h”
```
to
```c++
#include <driver_types.h>
```
So that it looks in the correct location for the header file `driver_types.h`...Now everything is installed properly and hopefully this helps someone else down the road.
