### ISSUE TITLE
Profiler SegFault on a single Linear layer

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#75369]
### 🐛 Describe the bug

```python
import torch
from torch.profiler import profile, ProfilerActivity

l = torch.nn.Linear(10, 10).cuda(0)
with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA]) as prof:
    l(torch.zeros(10, 10).cuda(0))
```

```
Segmentation fault (core dumped)
```

### Versions

Nvidia driver version: 450.119.03
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.1
[pip3] torch==1.12.0a0+git9a8e605
[pip3] torchtext==0.10.0a0+8f5267c
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-include               2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.20.1           py38h93e21f0_0  
[conda] numpy-base                1.20.1           py38h7d8b39e_0  
[conda] torch                     1.12.0a0+git9a8e605           dev_0    <develop>
[conda] torchtext                 0.10.0a0+cbf8af7          pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

cc @ezyang @gchanan @zou3519 @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by mrshenli** [comment]
I switched back to v1.10 (1.10.0a0+git71f889c), that works. So, this seems like a regression.

**Comment by robieta** [comment]
Thanks for the report. I'm able to repro. How in the world did this get past CI?

**Comment by guotuofeng** [comment]
@mrshenli, would you please try the nightly build? I am supposing the crash should be fixed in the latest nightly build.

**Comment by robieta** [comment]
> @mrshenli, would you please try the nightly build? I am supposing the crash should be fixed in the latest nightly build.

I ran into this building from head, so this is something new.

**Comment by ngimel** [comment]
I can't repro on my setup (cuda 11.5, python 3.9.7, fresh master build), so it's probably setup dependent, and thus sneaked past CI. @Chillee had some profiler segfaults recently too.

**Comment by robieta** [comment]
I'm on CUDA 11.0, @Chillee is on 11.5. But definitely it's env dependent. One of the interesting things is that the failure is in the kernel rather than the actual profiler code. (In both cases, so I assume it's the same issue.) So my guess is that we're doing something to put the GPU in a bad state. Running a bisect now, though CUDA builds are sloooowwwwww.

**Comment by robieta** [comment]
(Oh, and I don't even have to call the linear layer to repro: `torch.zeros(10, 10).cuda(0)` is enough)

**Comment by Chillee** [comment]
If it helps, this is a backtrace of the segfault: https://pastebin.com/0yh12uGP

I think it also has something to do with the particular settings it's being built with - installing pyTorch nightly works for me, building from source doesn't.

**Comment by ngimel** [comment]
Hm, why is there libcupti.so.9 in the stacktrace? Should it be libcupti.so.11, so there's something wrong with the linking?

**Comment by ngimel** [comment]
Could it be #74009?

**Comment by robieta** [comment]
> Could it be #74009?

eec994fc16c3553686ff348e8029862491ca4968 is good, so thankfully no.

**Comment by robieta** [comment]
I have discovered (after two bisects that made no sense) that this only repros if I `make clean` between steps.

**Comment by robieta** [comment]
Confirmed that https://github.com/pytorch/pytorch/pull/74009 is the culprit. (which also explains why I have to `make clean` each time) @ezyang How do you want to proceed? Normally it's an obvious revert hammer, but it sounds like this was fixing *other* issues so...

**Comment by robieta** [comment]
Update: I have `CUDA_HOME=/usr/local/cuda-11.0/` set. Before #74009 I see:
`CUDA_cupti_LIBRARY = /usr/local/cuda-11.0/extras/CUPTI/lib64/libcupti_static.a`
but after:
`CUDA_cupti_LIBRARY = /usr/lib/x86_64-linux-gnu/libcupti.so`
which is a symlink to `libcupti.so.9.1` (Which explains the strange symbols @ngimel) So the question is: why is CMake finding the wrong `.so`? Sadly, my CMake-fu is far too weak to delve into that.

**Comment by ezyang** [comment]
If you are running into this, there is a workaround: set USE_CUPTI_SO=0

The logic for searching for CUPTI is:

```
    find_library(CUPTI_LIBRARY_PATH ${CUPTI_LIB_NAME} PATHS
        ${CUDA_SOURCE_DIR}
        ${CUDA_SOURCE_DIR}/extras/CUPTI/lib64
        ${CUDA_SOURCE_DIR}/lib64)
```

on my cuda machine, I have

```
                    --   CUDA_SOURCE_DIR = /public/apps/cuda/11.2                                                        
--   CUDA_INCLUDE_DIRS = /public/apps/cuda/11.2/include                                              --   CUPTI_INCLUDE_DIR = /public/apps/cuda/11.2/extras/CUPTI/include
--   CUDA_cupti_LIBRARY = /public/apps/cuda/11.2/extras/CUPTI/lib64/libcupti.so   
```

So I also cannot repro. @robieta can you tell us what your `CUDA_SOURCE_DIR` is

**Comment by robieta** [comment]
> So I also cannot repro. @robieta can you tell us what your CUDA_SOURCE_DIR is

Unset. All my CUDA environment variables are:
```
USE_CUDA=1
CUDA_NVCC_EXECUTABLE=/data/shared/bin/cuda/nvcc
CUDA_HOME=/usr/local/cuda-11.0/
TORCH_CUDA_ARCH_LIST=8.0

```

**Comment by ezyang** [comment]
err, specifically, what does cmake report it as?

**Comment by robieta** [comment]
> CUDA_SOURCE_DIR

Oops. Sorry.
```
--   CUDA_SOURCE_DIR = /usr/local/cuda-11.0
--   CUDA_INCLUDE_DIRS = /usr/local/cuda-11.0/include
--   CUPTI_INCLUDE_DIR = /usr/local/cuda-11.0/extras/CUPTI/include
--   CUDA_cupti_LIBRARY = /usr/lib/x86_64-linux-gnu/libcupti.so
```

**Comment by ngimel** [comment]
cc @peterbell10. Peter, in #62445 you've updated CMake to use native cuda support, can it be used to reliably find the correct cupti library? Currently it looks like search for cupti is done in an ad-hoc way. Also, can our copy of FindCUDA be deleted now?

**Comment by ezyang** [comment]
yeah, just need to find the correct libcupti. Just to confirm, I hope /usr/local/cuda-11.0/extras/CUPTI/lib64/libcupti.so (or something similar) exists on your system

**Comment by peterbell10** [comment]
I've opened #76082 to track modernizing the CUDA toolkit search. Will see if the situation can be improved.
