### ISSUE TITLE
Profiling graphed callables or cuda graphs raises a RuntimeError

### ISSUE THREAD

**Issue by amarckal** [pytorch/pytorch#75504]
### 🐛 Describe the bug

When using the profiler with `ProfilerActivity.CUDA` to profile code that involves a cuda graph or a graphed callable results in a `RuntimeError: CUDA error: an illegal memory access was encountered`

Workaround is to use the nvprof or Nvidia Nsight Systems

Minimal example:

```python
import os

import torch
from torch.profiler import ProfilerActivity, profile

os.environ["CUDA_LAUNCH_BLOCKING"] = "1"


def add_one(in_: torch.Tensor):
    return in_ + 1


sample_arg = torch.zeros(10, device="cuda").requires_grad_(True)
add_one_graphed = torch.cuda.graphs.make_graphed_callables(add_one, sample_args=(sample_arg,))

zeros = torch.zeros(10, device="cuda")
out = add_one_graphed(zeros)
assert out[0] == 1

# This works
with profile(activities=[ProfilerActivity.CPU]):
    add_one_graphed(zeros)

# RuntimeError: CUDA error: an illegal memory access was encountered
with profile(activities=[ProfilerActivity.CUDA]):
    add_one_graphed(zeros)
```

Resulting traceback

```
Traceback (most recent call last):
  File "/home/amarckal/repro.py", line 26, in <module>
    add_one_graphed(zeros)
  File "/home/amarckal/miniconda3/envs/py39torch1.11.0/lib/python3.9/site-packages/torch/profiler/profiler.py", line 456, in __exit__
    self.stop()
  File "/home/amarckal/miniconda3/envs/py39torch1.11.0/lib/python3.9/site-packages/torch/profiler/profiler.py", line 467, in stop
    self._transit_action(self.current_action, None)
  File "/home/amarckal/miniconda3/envs/py39torch1.11.0/lib/python3.9/site-packages/torch/profiler/profiler.py", line 493, in _transit_action
    action()
  File "/home/amarckal/miniconda3/envs/py39torch1.11.0/lib/python3.9/site-packages/torch/profiler/profiler.py", line 104, in stop_trace
    self.profiler.__exit__(None, None, None)
  File "/home/amarckal/miniconda3/envs/py39torch1.11.0/lib/python3.9/site-packages/torch/autograd/profiler.py", line 212, in __exit__
    torch.cuda.synchronize()
  File "/home/amarckal/miniconda3/envs/py39torch1.11.0/lib/python3.9/site-packages/torch/cuda/__init__.py", line 495, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
```

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080 Ti Laptop GPU
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.942
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] pytorch-lightning==1.5.10
[pip3] torch==1.11.0
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.11.0
[pip3] torchelastic==0.2.0
[pip3] torchmetrics==0.7.2
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
[conda] mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
[conda] mkl_random                1.2.2            py39hde0f152_0    conda-forge
[conda] mypy                      0.942                    pypi_0    pypi
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.21.5                   pypi_0    pypi
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-lightning         1.5.10                   pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchaudio                0.11.0               py39_cu113    pytorch
[conda] torchelastic              0.2.0                    pypi_0    pypi
[conda] torchmetrics              0.7.2                    pypi_0    pypi
[conda] torchvision               0.12.0               py39_cu113    pytorch
```

cc @ezyang @gchanan @zou3519 @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @mcarilli

**Comment by troyappel** [comment]
Experiencing this same issue in current training, using DDP + cuda graphs.

**Comment by rkindi** [comment]
I encountered the same issue as well. I was able to work around it by constructing the cuda graph inside the `with profile(activities=[ProfilerActivity.CUDA]):` block.

**Comment by amarckal** [comment]
I also found another workaround, you can construct the cuda graph in another profile block and use it later. Extending on my code from before, it would look like this:

```py
with profile(activities=[ProfilerActivity.CPU]):
    add_one_graphed = torch.cuda.graphs.make_graphed_callables(add_one, sample_args=(sample_arg,))
    out = add_one_graphed(zeros)
    assert out[0] == 1

# not this works as well
with profile(activities=[ProfilerActivity.CUDA]):
    add_one_graphed(zeros)
```

**Comment by wzhao18** [comment]
> I also found another workaround, you can construct the cuda graph in another profile block and use it later. Extending on my code from before, it would look like this:
> 
> ```python
> with profile(activities=[ProfilerActivity.CPU]):
>     add_one_graphed = torch.cuda.graphs.make_graphed_callables(add_one, sample_args=(sample_arg,))
>     out = add_one_graphed(zeros)
>     assert out[0] == 1
> 
> # now this works as well
> with profile(activities=[ProfilerActivity.CUDA]):
>     add_one_graphed(zeros)
> ```

Thank you this resolves my issue!

**Comment by robieta** [comment]
We can actually further distill @amarckal's workaround to:

```
with profile():  # passing `activities=[ProfilerActivity.CPU]` also works here
    pass

add_one_graphed = torch.cuda.graphs.make_graphed_callables(add_one, sample_args=(sample_arg,))

with profile():
    add_one_graphed(zeros)
```

In other words, the cuda graph does not need to be created under a profiling context; it just needs to be created after the first one. So that got me thinking about initialization, and I found that:

```
if (!libkineto::api().isProfilerRegistered()) {
  libkineto_init(/*cpuOnly=*/false, /*logOnError=*/true);
}
```
is the magic invocation to stop the CUDA errors. So until the real Kineto stability issue is resolved it is probably a reasonable mitigation to just pull that part of `prepareTrace` into a standalone method and call it during `torch` init.

CC @chaekit @aaronenyeshi @davidberard98 @ngimel

**Comment by davidberard98** [comment]
FYI, I'm actually seeing the process hanging instead of an illegal memory access. https://gist.github.com/davidberard98/198353c75241f221b1ba38a5f80cb05e.

And thanks Taylor for the investigation!

**Comment by Jovp** [comment]
Was facing the hanging issue when using graphs and profiler, seems to be fixed in the nightly!

**Comment by aaronenyeshi** [comment]
Issue is fixed, closing this now.
