### ISSUE TITLE
GET “CUDA error: an illegal memory access was encountered” with nn.Conv2d

### ISSUE THREAD

**Issue by lijiong20** [pytorch/pytorch#75734]
### 🐛 Describe the bug

I get this error with 2080ti, pytorch 1.11 and 1.10, but the code runs well on kaggle or colab with same pytorch and cuda version
```import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
import pdb
pst=pdb.set_trace
import os
os.environ['CUDA_LAUNCH_BLOCKING']='1'
device = 'cuda:0'
convx = nn.Conv2d(1, 100, (5,128)).to(device)
torch.cuda.empty_cache()
y = convx(torch.randn(64, 1, 128, 128).to(device))
```

Here is the error
```RuntimeError                              Traceback (most recent call last)
<ipython-input-6-4918f17a7909> in <module>
      2 convx = nn.Conv2d(1, 100, (5,128)).to(device)
      3 torch.cuda.empty_cache()
----> 4 y = convx(torch.randn(64, 1, 128, 128).to(device))
      5 y

C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\conv.py in forward(self, input)
    445 
    446     def forward(self, input: Tensor) -> Tensor:
--> 447         return self._conv_forward(input, self.weight, self.bias)
    448 
    449 class Conv3d(_ConvNd):

C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\conv.py in _conv_forward(self, input, weight, bias)
    442                             _pair(0), self.dilation, self.groups)
    443         return F.conv2d(input, weight, bias, self.stride,
--> 444                         self.padding, self.dilation, self.groups)
    445 
    446     def forward(self, input: Tensor) -> Tensor:

RuntimeError: CUDA error: an illegal memory access was encountered
```
I tried to run it in cpu and it works well.
I tried to change kernel size to `nn.Conv2d(1, 100, (5,127))` and it works well
I tried to change input, it can work from `torch.randn(1, 1, 18, 128)` to `torch.randn(6, 1, 18, 128)`, but can't be bigger than 7.
I think there must be someting wrong with conv2d with cuda.

### Versions

PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: (Rev5, Built by MSYS2 project) 5.3.0
Clang version: Could not collect
CMake version: version 3.11.0-rc4
Libc version: N/A

Python version: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 512.15
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] audtorch==0.6.4
[pip3] numpy==1.21.4+mkl
[pip3] numpydoc==1.1.0
[pip3] pytorch-lightning==1.2.8
[pip3] torch==1.11.0+cu113
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==2.0.1
[pip3] torch-scatter==2.0.6
[pip3] torch-sparse==0.6.9
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.11.0+cu113
[pip3] torchmetrics==0.2.0
[pip3] torchstat==0.0.7
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.12.0+cu113
[conda] audtorch                  0.6.4                    pypi_0    pypi
[conda] autotorch                 0.0.1                    pypi_0    pypi
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] cudatoolkit               11.1.1               heb2d755_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] libblas                   3.9.0                     8_mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] libcblas                  3.9.0                     8_mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] liblapack                 3.9.0                     8_mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] mkl                       2020.4             hb70f87d_311    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] mkl-service               2.3.0            py37h4ab8f01_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] mkl_fft                   1.3.0            py37hda49f71_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] mkl_random                1.2.0            py37h414f9d2_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] numpy                     1.19.3                   pypi_0    pypi
[conda] numpy-base                1.18.5           py37hc3f5095_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpydoc                  1.1.0                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] pytorch-lightning         1.2.8              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] torch                     1.8.1                    pypi_0    pypi
[conda] torch-cluster             1.5.9                    pypi_0    pypi
[conda] torch-geometric           2.0.1                    pypi_0    pypi
[conda] torch-scatter             2.0.6                    pypi_0    pypi
[conda] torch-sparse              0.6.9                    pypi_0    pypi
[conda] torch-spline-conv         1.2.1                    pypi_0    pypi
[conda] torchaudio                0.11.0+cu113             pypi_0    pypi
[conda] torchmetrics              0.2.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] torchstat                 0.0.7                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.12.0+cu113             pypi_0    pypi

cc @ezyang @gchanan @zou3519 @csarofeen @ptrblck @xwang233 @ngimel

**Comment by zou3519** [comment]
Tentatively marking hi-pri for investigation because convolution is a common operation. FWIW I am unable to reproduce this

**Comment by lijiong20** [comment]
I tried1.10+cu102 and it also works， maybe the cause of error is cu113

**Comment by eqy** [comment]
I can reproduce the issue, but only in an environment with cuDNN 8.2. Since the nightly builds are using cuDNN 8.3, could you check if using one of those resolves the issue? e.g., installing
```
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch-nightly
```

**Comment by lijiong20** [comment]
> I can reproduce the issue, but only in an environment with cuDNN 8.2. Since the nightly builds are using cuDNN 8.3, could you check if using one of those resolves the issue? e.g., installing
> 
> ```
> conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch-nightly
> ```

I tried nightly builds '1.12.0.dev20220413' , and it works. thanks for your reply!
