### ISSUE TITLE
torch.linalg method cause cusolver error when run for the first time

### ISSUE THREAD

**Issue by yanivnik** [pytorch/pytorch#77248]
### 🐛 Describe the bug

torch.linalg methods cause wierd cusolver errors when run for the first time in an interpreter context. For example - 

```python
import torch

a = torch.eye(3).to(device='cuda:0')
try:
    torch.linalg.cholesky(a)   # Throws error, see error message in bottom
except Exception as e:
    print(e)

torch.linalg.cholesky(a)   # When run for the second time, doesn't throw error
```

The code above causes the following error to be thrown, only on the first call to a torch.linalg method - 
```
_LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnXsyevd( handle, params, jobz, uplo, n, CUDA_R_32F, reinterpret_cast<void*>(A), lda, CUDA_R_32F, reinterpret_cast<void*>(W), CUDA_R_32F, reinterpret_cast<void*>(bufferOnDevice), workspaceInBytesOnDevice, reinterpret_cast<void*>(bufferOnHost), workspaceInBytesOnHost, info)`. This error may appear if the input matrix contains NaN.
```

The error is only thrown in the first call to a `torch.linalg` method. On the second call (when run from the same python process) the error isn't thrown and the method completes well.

Other methods (such as `torch.linalg.eigh`, for example) also cause the error, it is not limited to `torch.linalg.cholesky`.

Also, it occurs only when the relevant tensor is initialized on the GPU.

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 7.5.17
GPU models and configuration:
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB
GPU 2: Tesla V100-PCIE-16GB
GPU 3: Tesla V100-PCIE-16GB

Nvidia driver version: 455.32.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] libblas                   3.9.0            12_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            12_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            12_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            12_linux64_mkl    conda-forge
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.21.2           py39h20f2e39_0
[conda] numpy-base                1.21.2           py39h79a1101_0
[conda] pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-lightning         1.5.10             pyhd8ed1ab_0    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchmetrics              0.7.2              pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.12.0               py39_cu113    pytorch

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Lezcano** [comment]
I believe this was laready reported sometime ago, but I don't remember what did we find, and/or whether we solved it in the end. Do you guys know / remember @xwang233 @IvanYashchuk ?

**Comment by xwang233** [comment]
Thank you for raising this issue. Sorry about the inconvenience. I think this is a duplicate of https://github.com/pytorch/pytorch/issues/70669. Let's track the update over there.

**Comment by ngimel** [comment]
Closing as duplicate
