### ISSUE TITLE
MPS backend has problems with printing non-contiguous tensors

### ISSUE THREAD

**Issue by lhoenig** [pytorch/pytorch#78001]
### 🐛 Describe the bug

Built `main` @ 734a97a7c8. The MPS backend seems to have trouble with non-contiguous tensors:
```python
import torch as pt

# this crashes
print(pt.ones(100, 100, device='mps').nonzero())
# this works
print(pt.ones(100, 100, device='mps').nonzero().contiguous())
```
Output:
```
$ python3 bug2.py
/Users/lukas/bug2.py:4: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/lukas/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  print(pt.ones(100, 100, device='mps').nonzero())
/Users/lukas/bug2.py:4: UserWarning: The dst MTL buffer in copy_to_mps is non-contiguous (Triggered internally at  /Users/lukas/pytorch/aten/src/ATen/native/mps/operations/Copy.mm:323.)
  print(pt.ones(100, 100, device='mps').nonzero())
Traceback (most recent call last):
  File "/Users/lukas/bug2.py", line 4, in <module>
    print(pt.ones(100, 100, device='mps').nonzero())
  File "/opt/homebrew/lib/python3.9/site-packages/torch/_tensor.py", line 338, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/opt/homebrew/lib/python3.9/site-packages/torch/_tensor_str.py", line 481, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/opt/homebrew/lib/python3.9/site-packages/torch/_tensor_str.py", line 447, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/opt/homebrew/lib/python3.9/site-packages/torch/_tensor_str.py", line 270, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/opt/homebrew/lib/python3.9/site-packages/torch/_tensor_str.py", line 302, in get_summarized_data
    return torch.stack([get_summarized_data(x) for x in (start + end)])
RuntimeError: Placeholder buffer size (256) is not large enough to contain the Tensor storage of size 160000
```
Note the non-contiguous warning being correctly issued. The crash does not happen with tensors of smaller dimensions. Interestingly, the crash also doesn't happen when you switch the order of the lines with `print` in the minimal example, i.e. first create a contiguous version (is the contiguous memory being reused? normally, the result of `Tensor.nonzero()` seems to be non-contiguous).

Is there a deeper problem with contiguous tensors on MPS? Is it possible to fix this?

### Versions

```
Collecting environment information...
PyTorch version: 1.12.0a0+git734a97a
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.1
Libc version: N/A

Python version: 3.9.12 (main, May  8 2022, 17:57:49)  [Clang 13.1.6 (clang-1316.0.21.2)] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.0
[pip3] torch==1.12.0a0+git734a97a
[pip3] torch-scatter==2.0.9
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] Could not collect
```

**Comment by albanD** [comment]
Hi,

This is due to the printing not working fine indeed. THanks for the report.

**Comment by kulinseth** [comment]
This is working fine on the `master`, please check with next nightly.

**Comment by lhoenig** [comment]
Can confirm it works now, thanks.

**Comment by FadouaKhm** [comment]
I am facing the same issue. How can I fix it? I believe I am using the latest nightly. Thanks!

**Comment by albanD** [comment]
Hi,

This does work locally for me.
Can you share what you're doing that is not working?

**Comment by FadouaKhm** [comment]
I have this function: 
`def get_matches_and_diffs(labels, ref_labels=None):
    if ref_labels is None:
        ref_labels = labels
    labels1 = labels.unsqueeze(1)
    labels2 = ref_labels.unsqueeze(0)
    matches = (labels1 == labels2).byte()
    diffs = matches ^ 1
    if ref_labels is labels:
        matches.fill_diagonal_(0)
    return matches, diffs`
    
   When calling it as follows:
   
   `matches, diffs = get_matches_and_diffs(labels, ref_labels)
    a1_idx, p_idx = torch.where(matches)
    a2_idx, n_idx = torch.where(diffs)`

I get the following error:

> UserWarning: The dst MTL buffer in copy_to_mps is non-contiguous (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Copy.mm:323.)
>   a2_idx, n_idx = torch.where(diffs)

**Comment by albanD** [comment]
That is missing a little bit of details to reproduce locally (in particular the inputs).

**Comment by lhoenig** [comment]
The warnings as reported by @FadouaKhm are still there, for example with the original test input (`print(pt.ones(100, 100, device='mps').nonzero())`). It doesn't crash anymore, however.

The warning also doesn't go away with the second version (`print(pt.ones(100, 100, device='mps').nonzero().contiguous())
 `), and I think at some point it did make the warning go away, and the line work.

**Comment by FadouaKhm** [comment]
Thanks for your time! This is a sample input:

```
labels = torch.tensor([1,1,0,1], device='mps')
ref_labels = torch.tensor([1,0,0,1], device='mps')
```

**Comment by FadouaKhm** [comment]
I am wondering whether these warnings can have an impact on the computation precision or they can just be ignored 🤔

**Comment by albanD** [comment]
In this case, there result do look correct. So it should be fine to ignore these.
cc @kulinseth should we re-open this until we can safely remove the warning?

**Comment by kulinseth** [comment]
Hi @albanD , the warning is fine to ignore . We can remove the warning in next commit . We probably don’t need this issue to be open

**Comment by bikcrum** [comment]
Has this issue been solved already?

**Comment by albanD** [comment]
Hi, not yet, but https://github.com/pytorch/pytorch/pull/79185 is taking care of it!

**Comment by kulinseth** [comment]
This can be now closed, please re-open it if issue exists.
