### ISSUE TITLE
MPS: crashes and strange behavior with `bool` Tensors

### ISSUE THREAD

**Issue by lhoenig** [pytorch/pytorch#78020]
### 🐛 Describe the bug

With the MPS backend, `bool` dtype Tensors produce different behavior than on CPU or even crash:
```python
import torch as pt

pt.tensor(True, device="mps") * 0  # segmentation fault
pt.tensor(True, device="mps") * 1  # segmentation fault
pt.tensor(True, device="mps") + 0  # segmentation fault
pt.tensor(True, device="mps") + 1  # segmentation fault
pt.tensor(False, device="mps") + 0  # segmentation fault
pt.tensor(True, device="mps") * 2  # tensor(255, device='mps:0'), same for every number > 2 tested
pt.tensor(True, device="cpu") * 2  # tensor(2)
```

### Versions

```
Collecting environment information...
PyTorch version: 1.12.0a0+git734a97a
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.1
Libc version: N/A

Python version: 3.9.12 (main, May  8 2022, 17:57:49)  [Clang 13.1.6 (clang-1316.0.21.2)] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.0
[pip3] torch==1.12.0a0+git734a97a
[pip3] torch-scatter==2.0.9
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] Could not collect

```

**Comment by sasasagagaga** [comment]
I have the same issue with bool tensors on MPS.

**Comment by lhoenig** [comment]
I've looked at the code for a few hours to try to understand whats going on. First time digging into the PyTorch C++ code, so I might be missing many things, but it seems like:
- When you call `.to(dtype)`, generally, the method `at::_to_copy` is called, found in `aten/src/ATen/native/TensorConversions.cpp`.
- The idea is to create a new Tensor with requested data type, and then copy the contents of the original Tensor over.
- So I think the conversion should happen when copying into the new Tensor (?)
- Copying code for the MPS backend is found in `aten/src/ATen/native/mps/operations/Copy.mm`
- Depending on whether `src`, `dst`, or both Tensors are on the MPS device, different methods are called (`copy_to_mps_`, `copy_from_mps`, `copy_kernel_mps`), this logic is found in `mps_copy_`
- But, I can't find the actual conversion, which I guess should happen using some Metal/MPS APIs, as the `dataptr` of the Tensor will point to some Metal native buffer (?)
- What is used is in all cases the function `[MTLBlitCommandEncoder copyFromBuffer:sourceBuffer:toBuffer:destinationOffset:size:]`, but I don't think it does any conversion, just copying (?)
- So that would explain the bugs related to conversion, as just the PyTorch dtype is adjusted, but no actual conversion of the underlying data is taking place

**Comment by lhoenig** [comment]
I really think no conversion is going on at the moment, for any data type.. though at least the data isn't corrupted:
```
>>> pt.tensor(5.3, device='cpu').to(pt.bool).to(pt.float)
tensor(1.)
>>> pt.tensor(5.3, device='mps').to(pt.bool).to(pt.float)
tensor(5.3000, device='mps:0')
>>> pt.tensor(42.8, device='mps').to(pt.int)
tensor(1110127411, device='mps:0', dtype=torch.int32)
>>> pt.tensor(42.8, device='mps').to(pt.int).to(pt.float)
tensor(42.8000, device='mps:0')
```
Actually trying to fix this for fun now, reporting back in case of success..

**Comment by razarmehr** [comment]
Hi @lhoenig . This issue was fixed in [PR 79185](https://github.com/pytorch/pytorch/pull/79185). Please try with the latest build and feel free to reopen the issue if you still see the problem. Thank you.
