### ISSUE TITLE
FFT operators are not supported on MPS device

### ISSUE THREAD

**Issue by pzelasko** [pytorch/pytorch#78044]
### 🐛 Describe the bug

# Extra comments

The error happens regardless of whether `PYTORCH_ENABLE_MPS_FALLBACK=1` env var is set or not.

# Code to reproduce:

```python
import torch
x = torch.randn(1, 16000, device="mps")
y = torch.fft.rfft(x)
y_abs = y.abs()
```

# Script output message:

```
$ python test2.py
test2.py:4: UserWarning: The operator 'aten::_fft_r2c' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  y = torch.fft.rfft(x)
libc++abi: terminating with uncaught exception of type c10::TypeError: Trying to convert ComplexFloat to the MPS backend but it does not have support for that dtype.
Exception raised from getMPSDataType at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/OperationUtils.mm:124 (most recent call first):
frame #0: at::native::mps::getMPSDataType(c10::ScalarType) + 452 (0x113dc690c in libtorch_cpu.dylib)
frame #1: at::native::mps::mpsGraphRankedPlaceHolder(MPSGraph*, at::Tensor const&) + 60 (0x113dc838c in libtorch_cpu.dylib)
frame #2: invocation function for block in at::native::mps::unary_op(at::Tensor const&, at::Tensor const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, MPSGraphTensor* (MPSGraph*, MPSGraphTensor*) block_pointer) + 96 (0x113e33d84 in libtorch_cpu.dylib)
frame #3: invocation function for block in at::native::mps::MPSGraphCache::CreateCachedGraph(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::native::mps::MPSCachedGraph* () block_pointer) + 216 (0x113dd0dec in libtorch_cpu.dylib)
frame #4: _dispatch_client_callout + 20 (0x1984d01b4 in libdispatch.dylib)
frame #5: _dispatch_lane_barrier_sync_invoke_and_complete + 56 (0x1984df414 in libdispatch.dylib)
frame #6: at::native::mps::MPSGraphCache::CreateCachedGraph(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::native::mps::MPSCachedGraph* () block_pointer) + 160 (0x113dc8e90 in libtorch_cpu.dylib)
frame #7: at::native::mps::unary_op(at::Tensor const&, at::Tensor const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, MPSGraphTensor* (MPSGraph*, MPSGraphTensor*) block_pointer) + 984 (0x113e33b70 in libtorch_cpu.dylib)
frame #8: at::native::abs_out_mps(at::Tensor const&, at::Tensor&) + 76 (0x113e351a4 in libtorch_cpu.dylib)
frame #9: at::_ops::abs_out::call(at::Tensor const&, at::Tensor&) + 280 (0x110f268e0 in libtorch_cpu.dylib)
frame #10: at::native::abs(at::Tensor const&) + 232 (0x110aadcd4 in libtorch_cpu.dylib)
frame #11: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::DispatchKeySet, at::Tensor const&), &(torch::autograd::VariableType::(anonymous namespace)::abs(c10::DispatchKeySet, at::Tensor const&))>, at::Tensor, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&> >, at::Tensor (c10::DispatchKeySet, at::Tensor const&)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&) + 968 (0x1125fa24c in libtorch_cpu.dylib)
frame #12: at::_ops::abs::call(at::Tensor const&) + 264 (0x110f25c84 in libtorch_cpu.dylib)
frame #13: torch::autograd::THPVariable_abs(_object*, _object*) + 188 (0x106de8904 in libtorch_python.dylib)
frame #14: method_vectorcall_NOARGS + 136 (0x104e5ee4c in python3.8)
frame #15: call_function + 128 (0x104f859a0 in python3.8)
frame #16: _PyEval_EvalFrameDefault + 19988 (0x104f7c91c in python3.8)
frame #17: _PyEval_EvalCodeWithName + 616 (0x104f75cc8 in python3.8)
frame #18: pyrun_file + 280 (0x104fea0d0 in python3.8)
frame #19: pyrun_simple_file + 448 (0x104fe980c in python3.8)
frame #20: PyRun_SimpleFileExFlags + 120 (0x104fe95ec in python3.8)
frame #21: pymain_run_file + 444 (0x105011040 in python3.8)
frame #22: pymain_run_python + 328 (0x10501040c in python3.8)
frame #23: Py_RunMain + 40 (0x105010268 in python3.8)
frame #24: pymain_main + 52 (0x105011c50 in python3.8)
frame #25: main + 56 (0x104e25a08 in python3.8)
frame #26: start + 520 (0x10534508c in dyld)

[1]    17751 abort      python test2.py
```

### Versions

# Env information

```
$ python collect_env.py
Collecting environment information...
PyTorch version: 1.13.0.dev20220521
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.22.4
Libc version: N/A

Python version: 3.8.13 (default, Mar 28 2022, 06:13:39)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] k2==1.15.1.dev20220520+cpu.torch1.12.0.dev20220519
[pip3] numpy==1.22.3
[pip3] torch==1.13.0.dev20220521
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] k2                        1.15.1.dev20220520+cpu.torch1.12.0.dev20220519          pypi_0    pypi
[conda] numpy                     1.22.3           py38h25ab29e_0
[conda] numpy-base                1.22.3           py38h974a1f5_0
[conda] torch                     1.13.0.dev20220521          pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @peterbell10 @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Changed the title, as it MPS does not support any FFT ops at the moment

**Comment by malfet** [comment]
Though following indeed crashes:
```
>>> torch.rand(3,3,dtype=torch.complex64).to("mps").abs()
libc++abi: terminating with uncaught exception of type c10::TypeError: Trying to convert ComplexFloat to the MPS backend but it does not have support for that dtype.
Exception raised from getMPSDataType at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/OperationUtils.mm:124 (most recent call first):
```

**Comment by kulinseth** [comment]
@pzelasko , thanks for filing the issue. Can you please provide a concrete use-case where you are using FFT?

**Comment by pzelasko** [comment]
> @pzelasko , thanks for filing the issue. Can you please provide a concrete use-case where you are using FFT?

@kulinseth Yes. It's a part of a common feature extraction methods (fbank, mfcc) for audio and speech processing models. E.g. here's an implementation that leverages it in Lhotse, a speech data handling library that I'm maintaining: https://github.com/lhotse-speech/lhotse/blob/master/lhotse/features/kaldi/layers.py

**Comment by dbl001** [comment]
Here are concrete use cases:

https://github.com/zongyi-li/fourier_neural_operator

**Comment by kulinseth** [comment]
Thanks @pzelasko and @dbl001 this is helpful.

**Comment by tdgrant1** [comment]
I am also curious about getting FFTs (in particular 3D FFTs) on MPS backend. Right now I get an error trying to convert to complex numbers, which apparently is not supported on MPS (but which are virtually required for most FFT operations):

```
In [1]: import torch
In [2]: a = torch.tensor([1.0, 2.0], dtype=torch.float32, device="mps")
In [3]: b = a.type(torch.complex64)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [3], line 1
----> 1 b = a.type(torch.complex64)

TypeError: Trying to convert ComplexFloat to the MPS backend but it does not have support for that dtype.
```

**Comment by hmartiro** [comment]
+1 for implementing this

**Comment by JulienSiems** [comment]
+1 for this

**Comment by seanslice** [comment]
I need this too

**Comment by brandus1** [comment]
+1

**Comment by mouryarahul** [comment]
Cannot generate random matrix in complex domain on MPS backend!

`>>> x = torch.rand(3,3, dtype=torch.cfloat)`
`>>> x`
`tensor([[0.5130+0.9478j, 0.7609+0.9535j, 0.2583+0.2870j],`
`        [0.2544+0.2614j, 0.7714+0.3653j, 0.1810+0.0990j],`
`        [0.1051+0.6867j, 0.8632+0.4609j, 0.7654+0.1736j]])`
`>>> y = torch.rand(3,3, dtype=torch.cfloat, device='mps')`
`Traceback (most recent call last):`
 ` File "<stdin>", line 1, in <module>`
`RuntimeError: "check_uniform_bounds" not implemented for 'ComplexFloat'`
`>>> `


PyTorch version: 2.0.0.dev20230124
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.1 (arm64)
GCC version: (Homebrew GCC 12.2.0) 12.2.0
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.0 (default, Mar  3 2022, 03:54:28) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-13.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0.dev20230124
[pip3] torchaudio==2.0.0.dev20230124
[pip3] torchvision==0.15.0.dev20230124
[conda] numpy                     1.23.5          py310hb93e574_0  
[conda] numpy-base                1.23.5          py310haf87e8b_0  
[conda] pytorch                   2.0.0.dev20230124        py3.10_0    pytorch-nightly
[conda] torchaudio                2.0.0.dev20230124       py310_cpu    pytorch-nightly
[conda] torchvision               0.15.0.dev20230124       py310_cpu    pytorch-nightly

**Comment by gr1pcoding** [comment]
+1 Same thing, trying to run an audio processing model on MPS and crashing due to aten::_fft_r2c. Hopefully this can be considered for a future update

**Comment by srikeshnagoji** [comment]
+1

**Comment by dbl001** [comment]
'MPS' doesn't support complex numbers ... how could this work?
```
In [3]: x = torch.randn(2,2, dtype=torch.complex32, device='mps')
libc++abi: terminating with uncaught exception of type c10::TypeError: Trying to convert ComplexHalf to the MPS backend but it does not have support for that dtype.
Exception raised from getMPSDataType at /Users/runner/work/pytorch/pytorch/pytor
```

**Comment by ChenkaiMao97** [comment]
+1

**Comment by Glimmer1083** [comment]
I also need this operator.

**Comment by kulinseth** [comment]
@ezyang , we are tracking to add support of this in MPS. I don't have a timeline on it. But we will keep it open to adopt it in PyTorch.

**Comment by dbl001** [comment]
Will PyTorch support complex numbers?
```
% ipython
Python 3.10.10 (main, Mar 21 2023, 13:41:39) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.10.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch

In [2]: a = torch.randn(10,2, device='mps', dtype=torch.cfloat)
libc++abi: terminating due to uncaught exception of type c10::TypeError: Trying to convert ComplexFloat to the MPS backend but it does not have support for that dtype.
Exception raised from getMPSDataType at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/OperationUtils.mm:34 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) + 81 (0x1011f9ec1 in libc10.dylib)
frame #1: at::native::mps::getMPSDataType(c10::ScalarType) + 450 (0x121762aa2 in libtorch_cpu.dylib)
frame #2: invocation function for block in at::Tensor& at::native::mps::random_mps_impl<double>(at::Tensor&, double, double, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, MPSGraphRandomDistribution, c10::optional<at::Generator>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, MPSGraphTensor* (at::native::mps::RandomCachedGraph*, MPSGraphTensor*) block_pointer) + 515 (0x1217a07d3 in libtorch_cpu.dylib)
frame #3: invocation function for block in at::native::mps::MPSGraphCache::CreateCachedGraph(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, at::native::mps::MPSCachedGraph* () block_pointer) + 330 (0x12176766a in libtorch_cpu.dylib)
frame #4: _dispatch_client_callout + 8 (0x7ff809fe8033 in libdispatch.dylib)
frame #5: _dispatch_lane_barrier_sync_invoke_and_complete + 60 (0x7ff809ff5ba1 in libdispatch.dylib)
frame #6: at::native::mps::MPSGraphCache::CreateCachedGraph(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, at::native::mps::MPSCachedGraph* () block_pointer) + 181 (0x121766fd5 in libtorch_cpu.dylib)
frame #7: at::Tensor& at::native::mps::random_mps_impl<double>(at::Tensor&, double, double, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, MPSGraphRandomDistribution, c10::optional<at::Generator>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, MPSGraphTensor* (at::native::mps::RandomCachedGraph*, MPSGraphTensor*) block_pointer) + 1020 (0x12179f88c in libtorch_cpu.dylib)
frame #8: at::native::mps::normal_mps_impl(at::Tensor&, double, double, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Generator>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) + 637 (0x12179ef2d in libtorch_cpu.dylib)
frame #9: at::native::normal_mps_(at::Tensor&, double, double, c10::optional<at::Generator>) + 109 (0x1217a2ded in libtorch_cpu.dylib)
frame #10: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor& (at::Tensor&, double, double, c10::optional<at::Generator>), &at::(anonymous namespace)::(anonymous namespace)::wrapper_MPS__normal_(at::Tensor&, double, double, c10::optional<at::Generator>)>, at::Tensor&, c10::guts::typelist::typelist<at::Tensor&, double, double, c10::optional<at::Generator>>>, at::Tensor& (at::Tensor&, double, double, c10::optional<at::Generator>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor&, double, double, c10::optional<at::Generator>) + 76 (0x11edaabcc in libtorch_cpu.dylib)
frame #11: at::Tensor& c10::callUnboxedKernelFunction<at::Tensor&, at::Tensor&, double, double, c10::optional<at::Generator>>(void*, c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor&, double&&, double&&, c10::optional<at::Generator>&&) + 73 (0x11debb5b9 in libtorch_cpu.dylib)
frame #12: at::_ops::normal_::call(at::Tensor&, double, double, c10::optional<at::Generator>) + 431 (0x11ded88cf in libtorch_cpu.dylib)
frame #13: at::Tensor::normal_(double, double, c10::optional<at::Generator>) const + 50 (0x11d37d532 in libtorch_cpu.dylib)
frame #14: at::native::randn(c10::ArrayRef<long long>, c10::optional<at::Generator>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 265 (0x11d6f76e9 in libtorch_cpu.dylib)
frame #15: at::native::randn(c10::ArrayRef<long long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 51 (0x11d6f7523 in libtorch_cpu.dylib)
frame #16: at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeExplicitAutograd__randn(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 94 (0x11e6013ee in libtorch_cpu.dylib)
frame #17: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeExplicitAutograd__randn(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)>, at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>>>, at::Tensor (c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 39 (0x11e6010b7 in libtorch_cpu.dylib)
frame #18: at::Tensor c10::Dispatcher::redispatch<at::Tensor, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>>(c10::TypedOperatorHandle<at::Tensor (c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)> const&, c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) const + 98 (0x11dcc87c2 in libtorch_cpu.dylib)
frame #19: at::_ops::randn::redispatch(c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 116 (0x11dcc86b4 in libtorch_cpu.dylib)
frame #20: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>), &at::(anonymous namespace)::randn(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)>, at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>>>, at::Tensor (c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 134 (0x11e392b76 in libtorch_cpu.dylib)
frame #21: at::_ops::randn::call(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 280 (0x11dcc7788 in libtorch_cpu.dylib)
frame #22: torch::randn_symint(c10::ArrayRef<c10::SymInt>, c10::TensorOptions) + 273 (0x10347ab71 in libtorch_python.dylib)
frame #23: torch::autograd::THPVariable_randn(_object*, _object*, _object*) + 5651 (0x10340ec03 in libtorch_python.dylib)
frame #24: cfunction_call + 52 (0x100a380c4 in python3.10)
frame #25: call_function + 637 (0x100b2096d in python3.10)
frame #26: _PyEval_EvalFrameDefault + 8640 (0x100af1c20 in python3.10)
frame #27: _PyEval_Vector + 545 (0x100aedcc1 in python3.10)
frame #28: builtin_exec + 343 (0x100ae8937 in python3.10)
frame #29: cfunction_vectorcall_FASTCALL + 103 (0x100a38e17 in python3.10)
frame #30: call_function + 187 (0x100b207ab in python3.10)
frame #31: _PyEval_EvalFrameDefault + 8971 (0x100af1d6b in python3.10)
frame #32: gen_send_ex2 + 193 (0x1009f30b1 in python3.10)
frame #33: _PyEval_EvalFrameDefault + 65348 (0x100aff9a4 in python3.10)
frame #34: gen_send_ex2 + 193 (0x1009f30b1 in python3.10)
frame #35: _PyEval_EvalFrameDefault + 65348 (0x100aff9a4 in python3.10)
frame #36: gen_send_ex2 + 193 (0x1009f30b1 in python3.10)
frame #37: gen_send + 42 (0x1009f364a in python3.10)
frame #38: method_vectorcall_O + 121 (0x1009e8d79 in python3.10)
frame #39: _PyEval_EvalFrameDefault + 35327 (0x100af845f in python3.10)
frame #40: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #41: call_function + 187 (0x100b207ab in python3.10)
frame #42: _PyEval_EvalFrameDefault + 8971 (0x100af1d6b in python3.10)
frame #43: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #44: _PyEval_EvalFrameDefault + 35327 (0x100af845f in python3.10)
frame #45: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #46: method_vectorcall + 158 (0x1009de52e in python3.10)
frame #47: call_function + 187 (0x100b207ab in python3.10)
frame #48: _PyEval_EvalFrameDefault + 8640 (0x100af1c20 in python3.10)
frame #49: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #50: _PyEval_EvalFrameDefault + 35327 (0x100af845f in python3.10)
frame #51: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #52: _PyEval_EvalFrameDefault + 35327 (0x100af845f in python3.10)
frame #53: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #54: _PyEval_EvalFrameDefault + 35327 (0x100af845f in python3.10)
frame #55: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #56: method_vectorcall + 158 (0x1009de52e in python3.10)
frame #57: _PyEval_EvalFrameDefault + 68323 (0x100b00543 in python3.10)
frame #58: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #59: call_function + 187 (0x100b207ab in python3.10)
frame #60: _PyEval_EvalFrameDefault + 8971 (0x100af1d6b in python3.10)
frame #61: _PyEval_Vector + 545 (0x100aedcc1 in python3.10)
frame #62: run_mod + 240 (0x100b76410 in python3.10)
frame #63: pyrun_file + 133 (0x100b761d5 in python3.10)

zsh: abort      ipython

```

**Comment by kargarisaac** [comment]
I get this error and trying to set the backend to cpu to avoid this error. I set `PYTORCH_ENABLE_MPS_FALLBACK=1` and also set `torch.device` to `cpu` but it doesn't help. How can I solve this problem? I want to test my code on CPU and then transfer it to a server to use GPU, so no need for mps.

**Comment by kulinseth** [comment]
We had FFT as one of the default operators registered with fallback. In latest 2.0 release we ended up removing it because in some unit tests and scenarios there were crashes and from UX standpoint it was not good. Till we figure out a more permanent solution , I can propose to bring it back .

**Comment by kargarisaac** [comment]
yeah. At least a solution that doesn't block us from development. Thanks :)

**Comment by qqaatw** [comment]
Hey @kargarisaac,

just seeing your comment here. I tested this on my side and didn't see any error on my system with M1 chip:

```
x = torch.randn(1, 16000, device="cpu")
y = torch.fft.rfft(x)
y_abs = y.abs()
```

If you don't need mps then it should work.

**Comment by thomaskvnze** [comment]
Do I understand it correctly, you will work on this at some point? I'm going to use this use case to learn how to implement a custom kernel.

**Comment by ebellumat** [comment]
Using CPU instead of MPS worked here but is really slow. 
<img width="1017" alt="image" src="https://github.com/pytorch/pytorch/assets/26942680/e7d2ceb0-b55a-4f41-b6ae-a70d98c96634">

**Comment by dbl001** [comment]
Will PyTorch support complex numbers?
```
% ipython
Python 3.10.10 (main, Mar 21 2023, 13:41:39) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.10.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch

In [2]: a = torch.randn(10,2, device='mps', dtype=torch.cfloat)
libc++abi: terminating due to uncaught exception of type c10::TypeError: Trying to convert ComplexFloat to the MPS backend but it does not have support for that dtype.
Exception raised from getMPSDataType at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/OperationUtils.mm:34 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) + 81 (0x1011f9ec1 in libc10.dylib)
frame #1: at::native::mps::getMPSDataType(c10::ScalarType) + 450 (0x121762aa2 in libtorch_cpu.dylib)
frame #2: invocation function for block in at::Tensor& at::native::mps::random_mps_impl<double>(at::Tensor&, double, double, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, MPSGraphRandomDistribution, c10::optional<at::Generator>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, MPSGraphTensor* (at::native::mps::RandomCachedGraph*, MPSGraphTensor*) block_pointer) + 515 (0x1217a07d3 in libtorch_cpu.dylib)
frame #3: invocation function for block in at::native::mps::MPSGraphCache::CreateCachedGraph(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, at::native::mps::MPSCachedGraph* () block_pointer) + 330 (0x12176766a in libtorch_cpu.dylib)
frame #4: _dispatch_client_callout + 8 (0x7ff809fe8033 in libdispatch.dylib)
frame #5: _dispatch_lane_barrier_sync_invoke_and_complete + 60 (0x7ff809ff5ba1 in libdispatch.dylib)
frame #6: at::native::mps::MPSGraphCache::CreateCachedGraph(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, at::native::mps::MPSCachedGraph* () block_pointer) + 181 (0x121766fd5 in libtorch_cpu.dylib)
frame #7: at::Tensor& at::native::mps::random_mps_impl<double>(at::Tensor&, double, double, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, MPSGraphRandomDistribution, c10::optional<at::Generator>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, MPSGraphTensor* (at::native::mps::RandomCachedGraph*, MPSGraphTensor*) block_pointer) + 1020 (0x12179f88c in libtorch_cpu.dylib)
frame #8: at::native::mps::normal_mps_impl(at::Tensor&, double, double, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Generator>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) + 637 (0x12179ef2d in libtorch_cpu.dylib)
frame #9: at::native::normal_mps_(at::Tensor&, double, double, c10::optional<at::Generator>) + 109 (0x1217a2ded in libtorch_cpu.dylib)
frame #10: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor& (at::Tensor&, double, double, c10::optional<at::Generator>), &at::(anonymous namespace)::(anonymous namespace)::wrapper_MPS__normal_(at::Tensor&, double, double, c10::optional<at::Generator>)>, at::Tensor&, c10::guts::typelist::typelist<at::Tensor&, double, double, c10::optional<at::Generator>>>, at::Tensor& (at::Tensor&, double, double, c10::optional<at::Generator>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor&, double, double, c10::optional<at::Generator>) + 76 (0x11edaabcc in libtorch_cpu.dylib)
frame #11: at::Tensor& c10::callUnboxedKernelFunction<at::Tensor&, at::Tensor&, double, double, c10::optional<at::Generator>>(void*, c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor&, double&&, double&&, c10::optional<at::Generator>&&) + 73 (0x11debb5b9 in libtorch_cpu.dylib)
frame #12: at::_ops::normal_::call(at::Tensor&, double, double, c10::optional<at::Generator>) + 431 (0x11ded88cf in libtorch_cpu.dylib)
frame #13: at::Tensor::normal_(double, double, c10::optional<at::Generator>) const + 50 (0x11d37d532 in libtorch_cpu.dylib)
frame #14: at::native::randn(c10::ArrayRef<long long>, c10::optional<at::Generator>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 265 (0x11d6f76e9 in libtorch_cpu.dylib)
frame #15: at::native::randn(c10::ArrayRef<long long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 51 (0x11d6f7523 in libtorch_cpu.dylib)
frame #16: at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeExplicitAutograd__randn(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 94 (0x11e6013ee in libtorch_cpu.dylib)
frame #17: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>), &at::(anonymous namespace)::(anonymous namespace)::wrapper_CompositeExplicitAutograd__randn(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)>, at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>>>, at::Tensor (c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 39 (0x11e6010b7 in libtorch_cpu.dylib)
frame #18: at::Tensor c10::Dispatcher::redispatch<at::Tensor, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>>(c10::TypedOperatorHandle<at::Tensor (c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)> const&, c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) const + 98 (0x11dcc87c2 in libtorch_cpu.dylib)
frame #19: at::_ops::randn::redispatch(c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 116 (0x11dcc86b4 in libtorch_cpu.dylib)
frame #20: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>), &at::(anonymous namespace)::randn(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)>, at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>>>, at::Tensor (c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 134 (0x11e392b76 in libtorch_cpu.dylib)
frame #21: at::_ops::randn::call(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 280 (0x11dcc7788 in libtorch_cpu.dylib)
frame #22: torch::randn_symint(c10::ArrayRef<c10::SymInt>, c10::TensorOptions) + 273 (0x10347ab71 in libtorch_python.dylib)
frame #23: torch::autograd::THPVariable_randn(_object*, _object*, _object*) + 5651 (0x10340ec03 in libtorch_python.dylib)
frame #24: cfunction_call + 52 (0x100a380c4 in python3.10)
frame #25: call_function + 637 (0x100b2096d in python3.10)
frame #26: _PyEval_EvalFrameDefault + 8640 (0x100af1c20 in python3.10)
frame #27: _PyEval_Vector + 545 (0x100aedcc1 in python3.10)
frame #28: builtin_exec + 343 (0x100ae8937 in python3.10)
frame #29: cfunction_vectorcall_FASTCALL + 103 (0x100a38e17 in python3.10)
frame #30: call_function + 187 (0x100b207ab in python3.10)
frame #31: _PyEval_EvalFrameDefault + 8971 (0x100af1d6b in python3.10)
frame #32: gen_send_ex2 + 193 (0x1009f30b1 in python3.10)
frame #33: _PyEval_EvalFrameDefault + 65348 (0x100aff9a4 in python3.10)
frame #34: gen_send_ex2 + 193 (0x1009f30b1 in python3.10)
frame #35: _PyEval_EvalFrameDefault + 65348 (0x100aff9a4 in python3.10)
frame #36: gen_send_ex2 + 193 (0x1009f30b1 in python3.10)
frame #37: gen_send + 42 (0x1009f364a in python3.10)
frame #38: method_vectorcall_O + 121 (0x1009e8d79 in python3.10)
frame #39: _PyEval_EvalFrameDefault + 35327 (0x100af845f in python3.10)
frame #40: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #41: call_function + 187 (0x100b207ab in python3.10)
frame #42: _PyEval_EvalFrameDefault + 8971 (0x100af1d6b in python3.10)
frame #43: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #44: _PyEval_EvalFrameDefault + 35327 (0x100af845f in python3.10)
frame #45: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #46: method_vectorcall + 158 (0x1009de52e in python3.10)
frame #47: call_function + 187 (0x100b207ab in python3.10)
frame #48: _PyEval_EvalFrameDefault + 8640 (0x100af1c20 in python3.10)
frame #49: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #50: _PyEval_EvalFrameDefault + 35327 (0x100af845f in python3.10)
frame #51: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #52: _PyEval_EvalFrameDefault + 35327 (0x100af845f in python3.10)
frame #53: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #54: _PyEval_EvalFrameDefault + 35327 (0x100af845f in python3.10)
frame #55: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #56: method_vectorcall + 158 (0x1009de52e in python3.10)
frame #57: _PyEval_EvalFrameDefault + 68323 (0x100b00543 in python3.10)
frame #58: _PyFunction_Vectorcall + 582 (0x1009d9a56 in python3.10)
frame #59: call_function + 187 (0x100b207ab in python3.10)
frame #60: _PyEval_EvalFrameDefault + 8971 (0x100af1d6b in python3.10)
frame #61: _PyEval_Vector + 545 (0x100aedcc1 in python3.10)
frame #62: run_mod + 240 (0x100b76410 in python3.10)
frame #63: pyrun_file + 133 (0x100b761d5 in python3.10)

zsh: abort      ipython

```

**Comment by dbl001** [comment]
+1 for project fourier neural operator

https://github.com/neuraloperator/neuraloperator

**Comment by Meowzz95** [comment]
+1 this would be really useful

**Comment by danielraffel** [comment]
+1 would be handy to run on macOS with MPS https://github.com/facebookresearch/audiocraft#installation

**Comment by sriege** [comment]
+1 for this, FFTs are fundamental for a lot of MIR

**Comment by nahuel89p** [comment]
Speech diarization from Pyannote is too slow on cpu and setting device to mps won't work because of this apparently. Would be great to have a fix on place.

**Comment by zou3519** [comment]
@malfet says this is coming in the next macos

**Comment by danielraffel** [comment]
Nice, FFT support is coming to MPS in Mac OS Sonoma! Just learned a bit more about it here: https://developer.apple.com/videos/play/wwdc2023/10050

**Comment by sriege** [comment]
@danielraffel thanks for the heads up!

Going to install the public beta and see if that does the trick. Will report back

**Comment by sriege** [comment]
On Sonoma public beta, and funnily enough can't get Xcode running to test myself, but seems like there's every indication that MPSGraph supports FFTs:

https://developer.apple.com/documentation/metalperformanceshadersgraph/filtering_images_with_mpsgraph_fft_operations

I'm not hugely familiar with this stuff, but also seems from their promotional material like these MPSGraph functions should be accessible to pytorch.

So seems like we will still need an addition to current pytorch to pass along fft requests to MPSGraph when using the mps backend.

**Comment by kulinseth** [comment]
> On Sonoma public beta, and funnily enough can't get Xcode running to test myself, but seems like there's every indication that MPSGraph supports FFTs:
> 
> https://developer.apple.com/documentation/metalperformanceshadersgraph/filtering_images_with_mpsgraph_fft_operations
> 
> I'm not hugely familiar with this stuff, but also seems from their promotional material like these MPSGraph functions should be accessible to pytorch.
> 
> So seems like we will still need an addition to current pytorch to pass along fft requests to MPSGraph when using the mps backend.

That’s indeed correct . Is anyone interested in working on it ? Let us know , we are happy to provide help if anyone is interested

**Comment by beveradb** [comment]
> Let us know , we are happy to provide help if anyone is interested

I'm interested, at least to make a start on it! I've never touched PyTorch code before, only been a consumer till now so please have low expectations 😅 
It'll take me a bit to get up to speed with local dev/test workflow and wrap my head around the existing code!
If anybody more experienced/familiar with the existing code wants to tackle it, please do!

Is [contributing](https://github.com/pytorch/pytorch/blob/main/CONTRIBUTING.md#developing-pytorch) the best place to start for me?
Any specific tests in place which I should pay attention to, or anything else which might help me know where to start? Do you have a particular approach in mind or anything @kulinseth?

**Comment by sriege** [comment]
@beveradb I was going to offer the same. I'm also not very familiar with the mps integration in pytorch but am pretty motivated to see this happen at this point, I have my own models I'm trying to train with mel spectrograms and MFCCs on my m1 Max chip

Will pour over the [the wiki](https://github.com/pytorch/pytorch/wiki/MPS-Backend) and report back if I make any headway?

**Comment by beveradb** [comment]
@sriege sounds good, I'll do the same! Feel free to reach out direct if you want to jump on a meet and pair, or get a second pair of eyes on anything 👀

**Comment by sriege** [comment]
@beveradb same! Just emailed you

**Comment by sriege** [comment]
@kulinseth quick question: I'm not seeing any of the new Sonoma FFT functions (realToHermiteanFFT, HermiteanToRealFFT) in the [MPSGraph API](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph)

Do you know if Apple is planning on adding these or will we need something more complicated than an API call to perform the op on MPS? Thanks

**Comment by danielraffel** [comment]
I wonder if @DenisVieriu97 might be able to answer your question about the new Sonoma FFT functions (realToHermiteanFFT, HermiteanToRealFFT) in the [MPSGraph API](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph) @sriege

**Comment by DenisVieriu97** [comment]
> @kulinseth quick question: I'm not seeing any of the new Sonoma FFT functions (realToHermiteanFFT, HermiteanToRealFFT) in the [MPSGraph API](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph)

Thanks @sriege. We are working on fixing this out.

In the meantime, if you want to use the APIs, please look in the **MPSGraphFourierTransformOps.h** header file for the function signatures, I am leaving down below the full path of this file (part of **Xcode.app**):
```cat /Applications/Xcode2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/MetalPerformanceShadersGraph.framework/Versions/A/Headers/MPSGraphFourierTransformOps.h```

You should see there the function signatures for `fastFourierTransformWithTensor` / `realToHermiteanFFTWithTensor` and more information about their parameters, e.g:
```
/// Creates a Fast Fourier Transform op and returns the result tensor.
///
/// This operation computes the Fast Fourier Transform of the input tensor according to the following formulae.
/// ```md
///     output[mu] = scale * sum_nu exp( +/- i * 2Pi * mu * nu / n ) input[nu], where
/// ```
/// `scale = 1` for `scaling_mode = none`,
/// `scale = 1/V_f` for `scaling_mode = size`,
/// `scale = 1/sqrt(V_f)` for `scaling_mode = unitary`, where
/// `V_f` is the volume of the transformation defined by the dimensions included in `axes`
/// (`V_f = prod_{i \in axes} shape(input)[i]`) (see ``MPSGraphFFTDescriptor/scalingMode``),
/// `+` is selected in `+/-` when `inverse` is specified, otherwise `-` is used
/// and the sum is done separately over each dimension in `axes` and `n` is the
/// dimension length of that axis.
///
///  > Tip: Currently transformation is supported only within the last four dimensions of the input tensor. In case
///  you need to transform higher dimensions than the last four, you can tranpose the higher dimensions of the input
///  with ``MPSGraph/transposeTensor:permutation:name:``  to be within that last four and then transpose
///  the result tensor back with the inverse of the input transpose.
///
/// - Parameters:
///   - tensor: Complex-valued input tensor. Must have datatype ``MPSDataTypeComplexFloat32`` or ``MPSDataTypeComplexFloat16``.
///   - axes: Specifies over which axes MPSGraph performs the Fourier Transform - all axes must be contained within last four dimensions of the input tensor.
///   - descriptor: Defines details of the Fourier transform operation - see ``MPSGraphFFTDescriptor``.
///   - name: The name for the operation.
/// - Returns: A valid MPSGraphTensor of the same type as ``tensor``.
-(MPSGraphTensor *) fastFourierTransformWithTensor:(MPSGraphTensor *) tensor
                                              axes:(NSArray<NSNumber *> *) axes
                                        descriptor:(MPSGraphFFTDescriptor *) descriptor
                                              name:(NSString * _Nullable) name
```

Let me know if you have any issues in using the APIs / accessing the MPSGraphFourierTransformOps.h file.

**Comment by sriege** [comment]
@DenisVieriu97 wonderful, thank you!!

**Comment by turian** [comment]
This is also useful for https://github.com/csteinmetz1/auraloss

**Comment by beveradb** [comment]
Hey @malfet hope you had a lovely new year!

I just started looking at this again now I've finally been allowed to upgrade my work laptop to Sonoma 😅 

I've just synced the fork branch (which me and @sriege were working on 3+ months ago, but we got stuck and lost momentum) with main, and resolved conflicts with your changes in PR #115512 - https://github.com/pytorch/pytorch/compare/main...beveradb:pytorch:78044-FFT-ops-on-MPS-device

The code on that branch is still pretty rough but may save you a bit of time as a starting point if you haven't already started  on it!
I'll try and get back up to speed with how to build and test pytorch in the meantime, see if I can actually get that code running on my macbook now 🤞

**Comment by sriege** [comment]
Cheers @beveradb for binging this back to the surface, I was doing some training literally yesterday and thinking about how I need to dig back in with this. Will see if anyone else wants to hop into the deep end with us

**Comment by richard-vogl** [comment]
+1
