### ISSUE TITLE
Non-contiguous tensor fails on MPS backend for `.cat` and `.stack` 

### ISSUE THREAD

**Issue by Willian-Zhang** [pytorch/pytorch#78043]
### 🐛 Describe the bug

> moved from comments on https://github.com/pytorch/pytorch/issues/77886
```python
generator = transformers.pipeline(task="text-generation", model=model.to('mps'), tokenizer=tokenizer, device=torch.device("mps"))
generator("This shall brake. ", max_length=200, use_cache=True)
```

would crash in:
```python
File /opt/homebrew/anaconda3/envs/torch/lib/python3.10/site-packages/transformers/models/gptj/modeling_gptj.py:72, in rotate_every_two(x)
     70 x1 = x[:, :, :, ::2]
     71 x2 = x[:, :, :, 1::2]
---> 72 x = torch.stack((-x2, x1), axis=-1)
     73 return x.flatten(-2)

RuntimeError: Placeholder buffer size (14336) is not large enough to contain the Tensor storage of size 114688
```

changing to this resolves this issue.
```python
    x1 = x[:, :, :, ::2].contiguous()
    x2 = x[:, :, :, 1::2]
```

this also happened to `.cat`
```python
File /opt/homebrew/anaconda3/envs/hf/lib/python3.10/site-packages/transformers/models/gptj/modeling_gptj.py:233, in GPTJAttention.forward(self, hidden_states, attention_mask, layer_past, head_mask, use_cache, output_attentions)
    230     q_rot = apply_rotary_pos_emb(q_rot, sincos, offset=offset)
    232     key = torch.cat([k_rot, k_pass], dim=-1)
--> 233     query = torch.cat([q_rot, q_pass], dim=-1)
    234 else:
    235     sincos = fixed_pos_embedding(key, 1, seq_len=seq_len)

RuntimeError: Placeholder buffer size (86016) is not large enough to contain the Tensor storage of size 114688
```

### Versions
```
Collecting environment information...
PyTorch version: 1.13.0.dev20220521
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.1
Libc version: N/A

Python version: 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.13.0.dev20220521
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     1.13.0.dev20220521          pypi_0    pypi
```

**Comment by Willian-Zhang** [comment]
After using `. contiguous()` fixes, it runs.

However, other issue occurs only when using MPS backend:
Using [opt-13b](https://huggingface.co/facebook/opt-13b) as model, the generated test would always be `<s>` (`[  713,  5658,  2058,   328,  1437, 50140, 50118, 50118]`) as an end of sentence.

And for [gpt-j-6B](https://huggingface.co/EleutherAI/gpt-j-6B) it always be ` invention` (`[ 1212,  2236,  7014,     0,   220, 14250]`)

**Comment by lhoenig** [comment]
The contiguous-related problem is probably the same underlying problem as #78001.

**Comment by razarmehr** [comment]
This issue is fixed in PR #78496 (nightly build 1.13.0.dev20220531 or later).
