### ISSUE TITLE
Slice operator on tensor generates wrong results on 'mps' device

### ISSUE THREAD

**Issue by WuChengbin** [pytorch/pytorch#78074]
### 🐛 Describe the bug

import torch

test = torch.tensor([[1,2,3],[4,5,6]])
test = test.to('mps')
test[:,0] = 7
print(test)
'''
Results:
tensor([[7, 0, 3],
        [4, 5, 6]], device='mps:0')
'''

test = torch.tensor([[1,2,3],[4,5,6]])
test[:,0] = 7
print(test)
'''
Results:
tensor([[7, 2, 3],
        [7, 5, 6]]) 
'''

operate: test[:,0] = 7 on mps:
tensor([[7, 0, 3],
        [4, 5, 6]], device='mps:0')
operate: test[:,0] = 7 on cpu:

tensor([[7, 2, 3],
        [7, 5, 6]])

### Versions

Collecting environment information...
PyTorch version: 1.12.0.dev20220518
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:14)  [Clang 12.0.1 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220518
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] numpy                     1.22.3           py39h64940a9_2    conda-forge
[conda] torch                     1.12.0.dev20220518          pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

**Comment by WuChengbin** [comment]
Did anyone notice this issues ? I have tested the latest PyTorch-nightly and it still not work correctly.

**Comment by PuckCh** [comment]
Same here with nightly 1.13.0.dev20220525:
```
▶ ipython
Python 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch
In [2]: test_cpu = torch.tensor([[1,2,3],[4,5,6]])
In [3]: test_mps = torch.tensor([[1,2,3],[4,5,6]]).to("mps")
In [4]: test_cpu[:,0] = 7
In [5]: test_mps[:,0] = 7

In [7]: test_cpu
Out[7]: 
tensor([[7, 2, 3],
        [7, 5, 6]])

In [8]: test_mps
Out[8]: 
tensor([[7, 7, 3],
        [4, 5, 6]], device='mps:0')

In [9]: torch.__version__
Out[9]: '1.13.0.dev20220525'
```

**Comment by kulinseth** [comment]
The [PR](https://github.com/pytorch/pytorch/commit/9355dcf5bb7b3ebe413eb2a4b7d8ff3762ee1838) has merged, please take a look at latest nightly to see if issue is fixed.
