### ISSUE TITLE
MPS 16Bit Not Working correctly

### ISSUE THREAD

**Issue by justusschock** [pytorch/pytorch#78168]
### 🐛 Describe the bug

When i try to use half-precision together with the new mps backend, I get the following:

```python
>>> import torch
>>> a = torch.rand(1, device='mps')
>>> a
tensor([0.4496], device='mps:0')
>>> a.item()
0.4495652914047241
>>> a.half()
tensor([4.4957e-01], device='mps:0', dtype=torch.float16)
>>> a.half().item()
0.084716796875
```

whereas with double precision it correctly fails with

`"TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead."`

I would expect half-precision to either work correctly or to fail with a similar error message.

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220523
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.3)
CMake version: version 3.23.1
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:52:34)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] pytorch-lightning==1.7.0.dev0
[pip3] torch==1.13.0.dev20220523
[pip3] torchmetrics==0.8.2
[pip3] torchtext==0.12.0
[pip3] torchvision==0.12.0
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] pytorch-lightning         1.7.0.dev0                dev_0    <develop>
[conda] torch                     1.13.0.dev20220523          pypi_0    pypi
[conda] torchmetrics              0.8.2                    pypi_0    pypi
[conda] torchtext                 0.12.0                   pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

**Comment by kulinseth** [comment]
@justusschock , the issue seems to be fixed on the latest nightly. Please re-open if it exists.

**Comment by aaronknudtson** [comment]
> @justusschock , the issue seems to be fixed on the latest nightly. Please re-open if it exists.

Unfortunately I see the error even on the latest nightly build, running on an M1 Max

**Comment by gench** [comment]
With the latest nightly build,  I am also still seeing the error on M1 Max.

**Comment by sgt101** [comment]
I'm seeing it trying to run hugging face stable diffusion (https://huggingface.co/CompVis/stable-diffusion-v1-4/discussions/13), when I try mps instead of cuda on an M1 pro I get 

TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

I'm on 1.13.0.dev20220826

**Comment by shepherd1530** [comment]
Having issues with fp's also.

```
Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

on 1.13.0.dev20220902.

**Comment by justusschock** [comment]
afaik, float64 isn't supposed to work at all. This is mostly about float16 and bfloat16.

**Comment by kulinseth** [comment]
> 
> I'm on 1.13.0.dev20220826
>afaik, float64 isn't supposed to work at all. This is mostly about float16 and bfloat16.

Thanks @justusschock 
Right Metal doesn't have FP64 support. You would need to run the operations in FP32 by casting them.

**Comment by rockyyliang** [comment]
trying to get a minimal example of moving a tensor to MPS working, I'm also getting
```libc++abi: terminating with uncaught exception of type c10::TypeError: Cannot convert a float64 Tensor to MPS as the MPS framework doesn't support float64. Please use float32 instead.```

how do I cast to fp32? tensor.toType() is not working for me. my code:

```cpp
#include <torch/torch.h>
#include <iostream>

int main()
{

    torch::Tensor tensor = torch::ones({3,3}).toType(torch::ScalarType::Half);//.to(torch::kMPS);
    std::cout <<tensor.scalar_type()<<std::endl;
    tensor = tensor.to(torch::kMPS);

    std::cout << tensor << std::endl;    
}
```
the scalar_type() line prints `Half`

call stack:
```
frame #0: at::native::mps::getMPSDataType(c10::ScalarType) + 312 (0x10c5ecd38 in libtorch_cpu.dylib)
frame #1: at::native::mps::copy_cast_mps(at::Tensor&, at::Tensor const&, id<MTLBuffer>, objc_object<MTLBuffer>) + 176 (0x10c610fa4 in libtorch_cpu.dylib)
frame #2: at::native::mps::mps_copy_(at::Tensor&, at::Tensor const&, bool) + 5176 (0x10c612940 in libtorch_cpu.dylib)
frame #3: at::native::copy_impl(at::Tensor&, at::Tensor const&, bool) + 1412 (0x108e8f734 in libtorch_cpu.dylib)
frame #4: at::native::copy_(at::Tensor&, at::Tensor const&, bool) + 100 (0x108e8f0f0 in libtorch_cpu.dylib)
frame #5: at::_ops::copy_::call(at::Tensor&, at::Tensor const&, bool) + 288 (0x109933548 in libtorch_cpu.dylib)
frame #6: at::native::_to_copy(at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>) + 2432 (0x10917b4dc in libtorch_cpu.dylib)
frame #7: at::_ops::_to_copy::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>) + 188 (0x10956253c in libtorch_cpu.dylib)
frame #8: at::_ops::_to_copy::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>) + 188 (0x10956253c in libtorch_cpu.dylib)
frame #9: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::DispatchKeySet, at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>), &(torch::autograd::VariableType::(anonymous namespace)::_to_copy(c10::DispatchKeySet, at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>))>, at::Tensor, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat> > >, at::Tensor (c10::DispatchKeySet, at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>) + 1104 (0x10ad2b1c4 in libtorch_cpu.dylib)
frame #10: at::_ops::_to_copy::call(at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>) + 340 (0x1095621ac in libtorch_cpu.dylib)
frame #11: at::_ops::to_device::call(at::Tensor const&, c10::Device, c10::ScalarType, bool, bool, c10::optional<c10::MemoryFormat>) + 320 (0x1096e19b0 in libtorch_cpu.dylib)
frame #12: at::print(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, at::Tensor const&, long long) + 188 (0x108cde5c0 in libtorch_cpu.dylib)
frame #13: at::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, at::Tensor const&) + 36 (0x100751398 in main)
frame #14: main + 304 (0x100750d94 in main)
frame #15: start + 520 (0x10079108c in dyld)
```

**Comment by kulinseth** [comment]
@rockyyliang , can you please create a separate issue and instructions on how to build the C++ code after checking with latest nightly if the issue still exists. 
I should mention that indeed we don't have FP64 support in MPS backend but your code snipped should work.

**Comment by kulinseth** [comment]
@justusschock , we verified that the original code it works with the latest nightly
```
Python 3.8.11 (default, Jul 29 2021, 14:57:32)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> a = torch.rand(1, device='mps')
>>> a
/Users/kulinseth/miniconda3/lib/python3.8/site-packages/torch/_tensor_str.py:115: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(
tensor([0.9857], device='mps:0')
>>> a.item()
0.9857476949691772
>>> a.half()
tensor([0.9858], device='mps:0', dtype=torch.float16)
>>> a.half().item()
0.98583984375

**Comment by DGKang234** [comment]
I am getting the same error when I do:
```trainer.fit(segformer_finetuner)```
Error message:
```
Traceback (most recent call last):
  File "/Users/tonggihkang/test_2.py", line 296, in <module>
    trainer.fit(segformer_finetuner)
  File "/Users/{}/ML/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/Users/{}/ML/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/{}/ML/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/Users/{}/ML/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/Users/{}/ML/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/Users/{}/ML/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _run_train
    self._run_sanity_check()
  File "/Users/{}/ML/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_sanity_check
    val_loop.run()
  File "/Users/{}/ML/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 207, in run
    output = self.on_run_end()
  File "/Users/{}/ML/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 183, in on_run_end
    self._evaluation_epoch_end(self._outputs)
  File "/Users/{}/ML/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 293, in _evaluation_epoch_end
    self.trainer._call_lightning_module_hook(hook_name, output_or_outputs)
  File "/Users/tonggihkang/ML/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/Users/tonggihkang/test_2.py", line 191, in validation_epoch_end
    self.log(k,v)
  File "/Users/tonggihkang/ML/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 451, in log
    value = apply_to_collection(value, (torch.Tensor, numbers.Number), self.__to_tensor, name)
  File "/Users/tonggihkang/ML/lib/python3.10/site-packages/pytorch_lightning/utilities/apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/Users/tonggihkang/ML/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 587, in __to_tensor
    else torch.tensor(value, device=self.device)
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

**Comment by henryleemr** [comment]
Got this, suspect it is from running this function `torchaudio.transforms.MelSpectrogram()` when training a model using the M1 Pro Max MacBook.

Rough code:
```
import torch
import torch.nn as nn
import torchaudio
import torchvision.models as models


class ResNet(nn.Module):
	def __init__(self, dataset, pretrained=True):
		super(ResNet, self).__init__()
		num_classes = 4

		self.transform = torchaudio.transforms.MelSpectrogram(sample_rate=16000, n_fft=400, n_mels=80, hop_length=160)
		self.model = models.resnet50(pretrained=pretrained)
		self.model.fc = nn.Linear(2048, num_classes)
		
    def forward(self, raw_audio_tensor):
        spectrogram = self.transform(raw_audio_tensor)
        output = self.model(spectrogram)
        return output
```

Got this error:
```
/Users/env/lib/python3.9/site-packages/torch/_tensor_str.py:103: UserWarning: The operator 'aten::bitwise_and.Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))

libc++abi: terminating with uncaught exception of type c10::TypeError: Trying to convert ComplexFloat to the MPS backend but it does not have support for that dtype.
Exception raised from getMPSScalarType at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/OperationUtils.mm:137 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 81 (0x109e09541 in libc10.dylib)
frame #1: at::native::mps::getMPSScalarType(c10::ScalarType) + 179 (0x1285d8653 in libtorch_cpu.dylib)
frame #2: at::native::mps::mpsGraphRankedPlaceHolder(MPSGraph*, at::Tensor const&) + 52 (0x1285d9f44 in libtorch_cpu.dylib)
frame #3: invocation function for block in at::native::mps::unary_op(at::Tensor const&, at::Tensor const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, MPSGraphTensor* (MPSGraph*, MPSGraphTensor*) block_pointer) + 95 (0x128676a5f in libtorch_cpu.dylib)
frame #4: invocation function for block in at::native::mps::MPSGraphCache::CreateCachedGraph(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::native::mps::MPSCachedGraph* () block_pointer, void*) + 330 (0x1285db74a in libtorch_cpu.dylib)
frame #5: _dispatch_client_callout + 8 (0x7ff81cfd3a44 in libdispatch.dylib)
frame #6: _dispatch_lane_barrier_sync_invoke_and_complete + 60 (0x7ff81cfe136b in libdispatch.dylib)
frame #7: at::native::mps::MPSGraphCache::CreateCachedGraph(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::native::mps::MPSCachedGraph* () block_pointer, void*) + 195 (0x1285db0b3 in libtorch_cpu.dylib)
frame #8: at::native::mps::unary_op(at::Tensor const&, at::Tensor const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, MPSGraphTensor* (MPSGraph*, MPSGraphTensor*) block_pointer) + 580 (0x128676604 in libtorch_cpu.dylib)
frame #9: at::native::abs_out_mps(at::Tensor const&, at::Tensor&) + 57 (0x1286788a9 in libtorch_cpu.dylib)
frame #10: at::_ops::abs_out::call(at::Tensor const&, at::Tensor&) + 292 (0x12560fe64 in libtorch_cpu.dylib)
frame #11: at::native::abs(at::Tensor const&) + 142 (0x12515305e in libtorch_cpu.dylib)
frame #12: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&), &(at::(anonymous namespace)::(anonymous namespace)::wrapper__abs(at::Tensor const&))>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&> >, at::Tensor (at::Tensor const&)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&) + 17 (0x125c5e0d1 in libtorch_cpu.dylib)
frame #13: at::_ops::abs::redispatch(c10::DispatchKeySet, at::Tensor const&) + 85 (0x12560f5c5 in libtorch_cpu.dylib)
frame #14: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::DispatchKeySet, at::Tensor const&), &(torch::autograd::VariableType::(anonymous namespace)::abs(c10::DispatchKeySet, at::Tensor const&))>, at::Tensor, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&> >, at::Tensor (c10::DispatchKeySet, at::Tensor const&)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&) + 957 (0x126e10f9d in libtorch_cpu.dylib)
frame #15: at::_ops::abs::call(at::Tensor const&) + 271 (0x12560f32f in libtorch_cpu.dylib)
frame #16: torch::autograd::THPVariable_abs(_object*, _object*) + 175 (0x10b08227f in libtorch_python.dylib)
frame #17: method_vectorcall_NOARGS + 92 (0x1091d5275 in Python)
frame #18: _PyEval_EvalFrameDefault + 22263 (0x1092b78d0 in Python)
frame #19: _PyEval_EvalCode + 398 (0x1092b1058 in Python)
frame #20: _PyFunction_Vectorcall + 376 (0x1091c99a8 in Python)
frame #21: _PyEval_EvalFrameDefault + 26962 (0x1092b8b2b in Python)
frame #22: _PyFunction_Vectorcall + 192 (0x1091c98f0 in Python)
frame #23: method_vectorcall + 365 (0x1091cc550 in Python)
frame #24: _PyEval_EvalFrameDefault + 3304 (0x1092b2ec1 in Python)
frame #25: _PyEval_EvalCode + 398 (0x1092b1058 in Python)
frame #26: _PyFunction_Vectorcall + 376 (0x1091c99a8 in Python)
frame #27: _PyObject_FastCallDictTstate + 87 (0x1091c90fc in Python)
frame #28: slot_tp_call + 187 (0x109236ae1 in Python)
frame #29: _PyObject_MakeTpCall + 127 (0x1091c8efe in Python)
frame #30: _PyEval_EvalFrameDefault + 31005 (0x1092b9af6 in Python)
frame #31: _PyFunction_Vectorcall + 192 (0x1091c98f0 in Python)
frame #32: method_vectorcall + 365 (0x1091cc550 in Python)
frame #33: _PyEval_EvalFrameDefault + 3304 (0x1092b2ec1 in Python)
frame #34: _PyEval_EvalCode + 398 (0x1092b1058 in Python)
frame #35: _PyFunction_Vectorcall + 376 (0x1091c99a8 in Python)
frame #36: _PyObject_FastCallDictTstate + 87 (0x1091c90fc in Python)
frame #37: slot_tp_call + 187 (0x109236ae1 in Python)
frame #38: _PyObject_MakeTpCall + 127 (0x1091c8efe in Python)
frame #39: _PyEval_EvalFrameDefault + 31005 (0x1092b9af6 in Python)
frame #40: _PyFunction_Vectorcall + 192 (0x1091c98f0 in Python)
frame #41: method_vectorcall + 365 (0x1091cc550 in Python)
frame #42: _PyEval_EvalFrameDefault + 3304 (0x1092b2ec1 in Python)
frame #43: _PyEval_EvalCode + 398 (0x1092b1058 in Python)
frame #44: _PyFunction_Vectorcall + 376 (0x1091c99a8 in Python)
frame #45: _PyObject_FastCallDictTstate + 87 (0x1091c90fc in Python)
frame #46: slot_tp_call + 187 (0x109236ae1 in Python)
frame #47: _PyObject_MakeTpCall + 127 (0x1091c8efe in Python)
frame #48: _PyEval_EvalFrameDefault + 27328 (0x1092b8c99 in Python)
frame #49: _PyFunction_Vectorcall + 192 (0x1091c98f0 in Python)
frame #50: _PyEval_EvalFrameDefault + 21418 (0x1092b7583 in Python)
frame #51: _PyEval_EvalCode + 398 (0x1092b1058 in Python)
frame #52: _PyFunction_Vectorcall + 376 (0x1091c99a8 in Python)
frame #53: _PyEval_EvalFrameDefault + 21418 (0x1092b7583 in Python)
frame #54: _PyEval_EvalCode + 398 (0x1092b1058 in Python)
frame #55: run_eval_code_obj + 128 (0x10930be00 in Python)
frame #56: run_mod + 96 (0x10930bd58 in Python)
frame #57: pyrun_file + 167 (0x109309513 in Python)
frame #58: pyrun_simple_file + 271 (0x109308f03 in Python)
frame #59: PyRun_SimpleFileExFlags + 67 (0x109308dce in Python)
frame #60: pymain_run_file + 326 (0x10932880b in Python)
frame #61: Py_RunMain + 993 (0x109328079 in Python)
frame #62: Py_BytesMain + 42 (0x1093293d4 in Python)
frame #63: start + 2432 (0x200aad310 in dyld)
```

I suspect it's because running `torchaudio.transforms.MelSpectrogram` will yield a tensor with some elements containing Complex numbers from this line in the error stack:
```
Trying to convert ComplexFloat to the MPS backend but it does not have support for that dtype.
```

Is there anything I can do?

**Comment by hmartiro** [comment]
^ I have the same error using torchaudio GriffinLim

**Comment by laravelpro** [comment]
I have the same error, please fix this

**Comment by mac137** [comment]
the same error with the stable pytorch version 1.13.1

**Comment by krsh888** [comment]
Having an issue with BFloat16 as well on M1 Max on MPS backend.
TypeError: Trying to convert BFloat16 to the MPS backend but it does not have support for that dtype.

**Comment by krsh888** [comment]
> It's intended behavior for pytorch not to support the BFloat16 datatype with the MPS backend ([see here](https://github.com/pytorch/pytorch/blob/31f311a816c026bbfca622d6121d6a7fab44260d/aten/src/ATen/mps/EmptyTensor.cpp#L46)).
> 
> I believe this is because the M1 chip doesn't support BFloat16. The M1 chip uses the ARMv8.5-A instruction set (only source I could find was [Wikipedia](https://en.wikipedia.org/wiki/Apple_M1) which cites an [archived GitHub link](https://web.archive.org/web/20220504192056/https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/Support/AArch64TargetParser.def#L256-L257)), and BFloat16 support was added in [ARMv8.6-A](https://community.arm.com/arm-community-blogs/b/architectures-and-processors-blog/posts/arm-architecture-developments-armv8-6-a).
> 
> You should be able to check if your system supports the BFloat16 architecture by running `systemctl hw.optional.arm.FEAT_BF16` ([see Apple's documentation on determining instruction set characteristics for more details](https://developer.apple.com/documentation/kernel/1387446-sysctlbyname/determining_instruction_set_characteristics)).

This is very helpful, thanks a lot

**Comment by mallman** [comment]
> It's intended behavior for pytorch not to support the BFloat16 datatype with the MPS backend ([see here](https://github.com/pytorch/pytorch/blob/31f311a816c026bbfca622d6121d6a7fab44260d/aten/src/ATen/mps/EmptyTensor.cpp#L46)).
> 
> I believe this is because the M1 chip doesn't support BFloat16. The M1 chip uses the ARMv8.5-A instruction set (only source I could find was [Wikipedia](https://en.wikipedia.org/wiki/Apple_M1) which cites an [archived GitHub link](https://web.archive.org/web/20220504192056/https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/Support/AArch64TargetParser.def#L256-L257)), and BFloat16 support was added in [ARMv8.6-A](https://community.arm.com/arm-community-blogs/b/architectures-and-processors-blog/posts/arm-architecture-developments-armv8-6-a).
> 
> You should be able to check if your system supports the BFloat16 architecture by running `systemctl hw.optional.arm.FEAT_BF16` ([see Apple's documentation on determining instruction set characteristics for more details](https://developer.apple.com/documentation/kernel/1387446-sysctlbyname/determining_instruction_set_characteristics)).

Incidentally, it appears the M2[^1] supports the BFloat16 type. Source: https://qiita.com/zacky1972/items/5deec6b139a76246aeee

Does this mean BFloat16 support will come to the MPS device on supported hardware?

[^1]: Disclaimer: I don't have an M2 and cannot verify personally. Would someone with an M2 like to comment?

**Comment by ingo-m** [comment]
I checked this on a mac with an "Apple M2 Pro" chip:
```
> sysctl hw | grep BF16
hw.optional.arm.FEAT_BF16: 1
```

So, looks like the M2 supports bfloat16.

But pytorch (`torch==2.0.1`) does not support it yet (`TypeError: Trying to convert BFloat16 to the MPS backend but it does not have support for that dtype.`).

**Comment by mallman** [comment]
> I checked this on a mac with an "Apple M2 Pro" chip:
> 
> ```
> > sysctl hw | grep BF16
> hw.optional.arm.FEAT_BF16: 1
> ```
> 
> So, looks like the M2 supports bfloat16.
> 
> But pytorch (`torch==2.0.1`) does not support it yet (`TypeError: Trying to convert BFloat16 to the MPS backend but it does not have support for that dtype.`).

Sounds like an excellent candidate for a PR...

**Comment by kulinseth** [comment]
> > I checked this on a mac with an "Apple M2 Pro" chip:
> > ```
> > > sysctl hw | grep BF16
> > hw.optional.arm.FEAT_BF16: 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So, looks like the M2 supports bfloat16.
> > But pytorch (`torch==2.0.1`) does not support it yet (`TypeError: Trying to convert BFloat16 to the MPS backend but it does not have support for that dtype.`).
> 
> Sounds like an excellent candidate for a PR...

@mallman , we will update here when we have support for BF16 in our stack.

**Comment by phdykd** [comment]
M2 max chip does not provide output and tells "mps does not support torch.bfloat16".
this is the code I tried to get:
"from transformers import AutoTokenizer, AutoModelForCausalLM
import transformers
import torch

# model = AutoModelForCausalLM.from_pretrained("tiiuae/falcon-40b-instruct", trust_remote_code=True)


# model = "tiiuae/falcon-40b-instruct"
model = "tiiuae/falcon-40b"
# model = model.to('mps')

tokenizer = AutoTokenizer.from_pretrained(model)
pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    # torch_dtype=torch.bfloat16,
    # torch_dtype=torch.float32,
    trust_remote_code=True,
    device = torch.device('mps'),
    # device_map="auto",
)"

**Comment by derekelewis** [comment]
I found this issue when getting the error reported by the submitter. 

TypeError: Trying to convert BFloat16 to the MPS backend but it does not have support for that dtype.

After doing some research and reviewing some of the comments here, it appears the M2 CPUs have support for BF16; however, it is unclear whether or not Metal, itself, has support. 

https://github.com/google/jax/issues/16417#issuecomment-1593566220 seems to imply that Metal does support BF16.

Are there any updates on getting bfloat16 enabled with MPS?  Thanks!

**Comment by ohmygenie** [comment]
> I found this issue when getting the error reported by the submitter.
> 
> TypeError: Trying to convert BFloat16 to the MPS backend but it does not have support for that dtype.
> 
> After doing some research and reviewing some of the comments here, it appears the M2 CPUs have support for BF16; however, it is unclear whether or not Metal, itself, has support.
> 
> [google/jax#16417 (comment)](https://github.com/google/jax/issues/16417#issuecomment-1593566220) seems to imply that Metal does support BF16.
> 
> Are there any updates on getting bfloat16 enabled with MPS? Thanks!
> 
> Edit: Nevermind - found PR #99272

Hello @derekelewis , what is your estimate time to generate an image in M1/M2 macbook with MPS? And are you able to use it successfully?

I cannot on my end because of this error every time I select MPS as the device: NotImplementedError: The operator 'aten::index.Tensor' is not current implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable PYTORCH_ENABLE_MPS_FALLBACK=1 to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

Here's a snippet of my code

`from diffusers import StableDiffusionControlNetPipeline, ControlNetModel
import torch
import PIL.Image as Image


SDV5_MODEL_PATH = "/Users/user/stable-diffusion-v1-5/"
CONTROL_PATH = "/Users/user/sd-controlnet-depth/"


controlnet = ControlNetModel.from_pretrained(
    CONTROL_PATH, 
    torch_dtype=torch.float32)
    
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    SDV5_MODEL_PATH,
    torch_dtype=torch.float32,
    controlnet=controlnet, 
    safety_checker=None).to("cpu") 

pipe.enable_attention_slicing()
generator = torch.Generator(device="cpu").manual_seed(-1)
prompt = "Space station, pro photography, RAW photo, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3"

image = pipe(
    prompt,
    width=500,
    height=500,
    generator=generator,
    image=Image.open("/Users/user/Downloads/test101.png"),
    num_inference_steps=20,
).images[0]

image.save('/Users/user/Downloads/output101.png')

Here's the image I generated using CPU (which took 6 minutes): [`](https://imgur.com/a/TFuwy9d)

**Comment by AtharvJaju** [comment]
> M2 max chip does not provide output and tells "mps does not support torch.bfloat16". this is the code I tried to get: "from transformers import AutoTokenizer, AutoModelForCausalLM import transformers import torch
> 
> # model = AutoModelForCausalLM.from_pretrained("tiiuae/falcon-40b-instruct", trust_remote_code=True)
> # model = "tiiuae/falcon-40b-instruct"
> model = "tiiuae/falcon-40b"
> 
> # model = model.to('mps')
> tokenizer = AutoTokenizer.from_pretrained(model) pipeline = transformers.pipeline( "text-generation", model=model, tokenizer=tokenizer, # torch_dtype=torch.bfloat16, # torch_dtype=torch.float32, trust_remote_code=True, device = torch.device('mps'), # device_map="auto", )"

Is this solved?
