### ISSUE TITLE
torch.embedding raise "CUDA error: invalid device function" when running scripted 

### ISSUE THREAD

**Issue by Cory-M** [pytorch/pytorch#78497]
### 🐛 Describe the bug

when scripting a torch model with nn.Embedding layers, the scripted model will raise `CUDA error: invalid device function` at `torch.embedding(weight, input, tensor_padding_idx, sclae_grad_by_freq, sparse)` if running on GPU in Java. the scripted model can run without issue with CPU/GPU in Python, and CPU in Java.

```python
import torch
import torch.nn as nn

class EmbeddingModel(nn.Module):
    def __init__(self, ):
        super(EmbeddingModel, self).__init__()
        self.layer = nn.Embedding(49500, 5)

    def forward(self, x): 
        return self.layer(x)

model = EmbeddingModel()
scr = torch.jit.script(model)
torch.jit.save(scr, 'embedding.pt')
```

error message i got (running with GPU in Java):
```
Traceback of TorchScript, original code (most recent call last):
  File "test/embedding.py", line 10, in forward
    def forward(self, x):
        return self.layer(x)
               ~~~~~~~~~~ <--- HERE
  File "/home/keyu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    def forward(self, input: Tensor) -> Tensor:
        return F.embedding(
               ~~~~~~~~~~~ <--- HERE
            input, self.weight, self.padding_idx, self.max_norm,
            self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/keyu/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: CUDA error: invalid device function
```

### Versions

**Pytorch**
```
PyTorch version: 1.10.2+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.4
Libc version: glibc-2.10

Python version: 3.7.6 (default, Jan  8 2020, 19:59:22)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-109-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: GPU 0: NVIDIA TITAN RTX
Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] numpydoc==0.9.2
[pip3] torch==1.10.2+cu113
[pip3] torch-scatter==2.0.9
[pip3] torchaudio==0.10.2+cu113
[pip3] torchvision==0.11.3+cu113
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.21.5                   pypi_0    pypi
[conda] numpydoc                  0.9.2                      py_0  
[conda] torch                     1.10.2+cu113             pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torchaudio                0.10.2+cu113             pypi_0    pypi
[conda] torchvision               0.11.3+cu113             pypi_0    pypi

```

**Other relevants**
```
<groupId>org.bytedeco</groupId>
            <artifactId>pytorch-platform</artifactId>
            <version>1.10.2-1.5.7</version>
<groupId>org.bytedeco</groupId>
            <artifactId>pytorch-platform-gpu</artifactId>
            <version>1.10.2-1.5.7</version>
LibTorch: libtorch-shared-with-deps-1.10.2
```

**Comment by Cory-M** [comment]
### Debug attempt
I'm suspecting the issue comes from the `padding_idx` parameter of torch.embedding. it is a scalar and in this example case it equals to -1. i tried to change L2044 in _torch/nn/functional.py_
```python
return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
```
to 
```python
tensor_padding_idx = torch.tensor(padding_idx)
if torch.jit.is_scripting():
    print('input device', input.get_device())
    print('padding_idx device', tensor_padding_idx.get_device())
return torch.embedding(weight, input, torch.tensor_padding_idx, scale_grad_by_freq, sparse)
```
when excuting `script_model.cpu()(sample_input.cpu())` the printing output is 
```
input device -1
padding_idx device -1
```
and when excuting `script_model.cuda()(sample_input.cuda())` the printint output is
```
input device 0
padding_idx device -1
```
(the padding_idx device doesn't change when switching the scripted model from GPU to CPU).
Could this be an issue?

**Comment by Cory-M** [comment]
turns out to be irrelavant with torch or torchscript. closing this issue.
