### ISSUE TITLE
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation. The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.

### ISSUE THREAD

**Issue by mikami520** [pytorch/pytorch#78893]
## Bug Description
The Torch version is not compatible to current CUDA version so that the following error happens:
```
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
```
## Problem 
I tried to use torch to run U-Net training, however, the torch version is not compatible to my GPU card, and the error above happens, is there a way to solve this issue? Thanks!

## Versions
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.8.8 (default, Apr 13 2021, 19:58:26)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.4.48
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 470.94
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.2.2
/usr/lib64/libcudnn_adv_infer.so.8.2.2
/usr/lib64/libcudnn_adv_train.so.8.2.2
/usr/lib64/libcudnn_cnn_infer.so.8.2.2
/usr/lib64/libcudnn_cnn_train.so.8.2.2
/usr/lib64/libcudnn_ops_infer.so.8.2.2
/usr/lib64/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-ignite==0.4.8
[pip3] torch==1.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.20.1           py38h93e21f0_0  
[conda] numpy-base                1.20.1           py38h7d8b39e_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1

**Comment by znmeb** [comment]
You need a PyTorch built with CUDA 11 - CUDA 10.2 does not support your GPU. You can probably find a suitable PyTorch here: https://pytorch.org/get-started/locally/.

I ran into this in December (Windows WSL) and this is how I fixed it.

**Comment by mikami520** [comment]
> You need a PyTorch built with CUDA 11 - CUDA 10.2 does not support your GPU. You can probably find a suitable PyTorch here: https://pytorch.org/get-started/locally/.
> 
> I ran into this in December (Windows WSL) and this is how I fixed it.

@znmeb Thanks for your reply. So you mean I need to find a way to install torch version build for CUDA 11.4, right? However, the module I used for my project requires the torch version 1.11.0 (shown in the version section) which is not compatible to CUDA 11. What should I do next?

**Comment by znmeb** [comment]
> > You need a PyTorch built with CUDA 11 - CUDA 10.2 does not support your GPU. You can probably find a suitable PyTorch here: https://pytorch.org/get-started/locally/.
> > I ran into this in December (Windows WSL) and this is how I fixed it.
> 
> @znmeb Thanks for your reply. So you mean I need to find a way to install torch version build for CUDA 11.4, right? However, the module I used for my project requires the torch version 1.11.0 (shown in the version section) which is not compatible to CUDA 11. What should I do next?

You''ll at least need to install CUDA 11. The instructions are here: <https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html>. Warning - it's very detailed and dense - you may need to read through it a few times.

**Comment by mikami520** [comment]
> > > You need a PyTorch built with CUDA 11 - CUDA 10.2 does not support your GPU. You can probably find a suitable PyTorch here: https://pytorch.org/get-started/locally/.
> > > I ran into this in December (Windows WSL) and this is how I fixed it.
> > 
> > 
> > @znmeb Thanks for your reply. So you mean I need to find a way to install torch version build for CUDA 11.4, right? However, the module I used for my project requires the torch version 1.11.0 (shown in the version section) which is not compatible to CUDA 11. What should I do next?
> 
> You''ll at least need to install CUDA 11. The instructions are here: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html. Warning - it's very detailed and dense - you may need to read through it a few times.

I already installed CUDA 11.4, the problem is that the version of PyTorch I used for my project is not compatible to CUDA 11.4.

**Comment by znmeb** [comment]
> I already installed CUDA 11.4, the problem is that the version of PyTorch I used for my project is not compatible to CUDA 11.4. If I change the version of Pytorch to be compatible to CUDA 11.4, some python modules of the project may not work

Can you downgrade to CUDA 11.3? It looks like the PyTorch binaries at https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html use CUDA 11.3. CUDA 11.3 will support your GPUs.

**Comment by mikami520** [comment]
> PyTorch version: 1.11.0+cu102 Is debug build: False CUDA used to build PyTorch: 10.2 ROCM used to build PyTorch: N/A
> 
> OS: CentOS Linux 7 (Core) (x86_64) GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44) Clang version: Could not collect CMake version: version 2.8.12.2 Libc version: glibc-2.17
> 
> Python version: 3.8.8 (default, Apr 13 2021, 19:58:26) [GCC 7.3.0] (64-bit runtime) Python platform: Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.10 Is CUDA available: True CUDA runtime version: 11.4.48 GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090 GPU 1: NVIDIA GeForce RTX 3090
> 
> Nvidia driver version: 470.94 cuDNN version: Probably one of the following: /usr/lib64/libcudnn.so.8.2.2 /usr/lib64/libcudnn_adv_infer.so.8.2.2 /usr/lib64/libcudnn_adv_train.so.8.2.2 /usr/lib64/libcudnn_cnn_infer.so.8.2.2 /usr/lib64/libcudnn_cnn_train.so.8.2.2 /usr/lib64/libcudnn_ops_infer.so.8.2.2 /usr/lib64/libcudnn_ops_train.so.8.2.2 HIP runtime version: N/A MIOpen runtime version: N/A Is XNNPACK available: True
> 
> Versions of relevant libraries: [pip3] numpy==1.22.3 [pip3] pytorch-ignite==0.4.8 [pip3] torch==1.11.0 [pip3] torchvision==0.12.0 [conda] blas 1.0 mkl [conda] mkl 2021.2.0 h06a4308_296 [conda] mkl-service 2.3.0 py38h27cfd23_1 [conda] mkl_fft 1.3.0 py38h42c9631_2 [conda] mkl_random 1.2.1 py38ha9443f7_2 [conda] numpy 1.20.1 py38h93e21f0_0 [conda] numpy-base 1.20.1 py38h7d8b39e_0 [conda] numpydoc 1.1.0 pyhd3eb1b0_1

Yep, I am using the virtual environment, I think the problem is caused by the version cuDNN, it should be cu11x

**Comment by znmeb** [comment]
> Yep, I am using the virtual environment, I think the problem is caused by the version cuDNN, it should be cu11x

I don't think so - the problem is your PyTorch version `PyTorch version: 1.11.0+cu102`. It was compiled with CUDA 10.2.

Try uninstalling the `pip3` `torch` and `torchvision`, downgrading to CUDA 11.3 and using this command line:

```
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
```

The `-c pytorch` is the important part - the `pytorch` channel has the right packages for GPU access.'

**Comment by mikami520** [comment]
> https://pytorch.org/get-started/locally/

What if I install the PyTorch version 1.11.x made for cuda11.x? As I checked the PyTorch website, it had stable build Torch 1.11.0 for CUDA 11.3. Also, is Torch 1.11.0+cu11.3 works for CUDA 11.4?

**Comment by znmeb** [comment]
> What if I install the PyTorch version 1.11.x made for cuda11.x? As I checked the PyTorch website, it had stable build Torch 1.11.0 for CUDA 11.3. Also, does Torch 1.11.0+cu11.3 works for CUDA 11.4? I thought CUDA is backward compatible right?

I think if you follow the directions at https://pytorch.org/get-started/locally/ you'll get compatible binaries. The `conda` installs include compatible binary builds of CUDA Toolkit and `cudnn `- I don't know about the `pip` installs because I've always used the `conda` ones.

I have an RTX 3090 and the directions have worked for me on Ubuntu Linux. The `conda` packaging system tries to supply everything you need regardless of what's on your host.

**Comment by mikami520** [comment]
> > What if I install the PyTorch version 1.11.x made for cuda11.x? As I checked the PyTorch website, it had stable build Torch 1.11.0 for CUDA 11.3. Also, does Torch 1.11.0+cu11.3 works for CUDA 11.4? I thought CUDA is backward compatible right?
> 
> I think if you follow the directions at https://pytorch.org/get-started/locally/ you'll get compatible binaries. The `conda` installs include compatible binary builds of CUDA Toolkit and `cudnn `- I don't know about the `pip` installs because I've always used the `conda` ones.
> 
> I have an RTX 3090 and the directions have worked for me on Ubuntu Linux. The `conda` packaging system tries to supply everything you need regardless of what's on your host.

Thank you so much, the problem has been solved.
