### ISSUE TITLE
MPS: Add support for TopK (k>16) on M1 GPU

### ISSUE THREAD

**Issue by luikore** [pytorch/pytorch#78915]
### 🐛 Describe the bug

I'm using M1 and installed pre release PyTorch. When trying the new mps support, the following simple code gives incorrect result:

```python
import torch
xs = torch.arange(30).to('mps')
print(xs.topk(30))
```

The output:

```python
torch.return_types.topk(
values=tensor([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], device='mps:0'),
indices=tensor([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], device='mps:0'))
```

Results except top 16 are incorrectly filled with 0.

If I remove the `.to('mps')`, the result is correct.

### Versions

I'm using M1 MacBook Pro (13-inch, M1, 2020)

PyTorch version is: 1.13.0a0+gitb7caf40

PyTorch is installed with `pip3 install --pre torch --extra-index-url https://download.pytorch.org/whl/nightly/cpu`

I also compiled PyTorch from source (b7caf402aa), the result is the same.

cc @ezyang @gchanan @zou3519 @kulinseth @albanD

**Comment by xsacha** [comment]
Thanks! This explains why I was getting no detections. I didn't look in to it thoroughly and just went back to CPU.

**Comment by Djordi97** [comment]
Any updates on this issue?

**Comment by kulinseth** [comment]
> Any updates on this issue?

We are currently working on this and I will update when we have the PR up for it.

**Comment by Djordi97** [comment]
> We are currently working on this and I will update when we have the PR up for it.

Alright, thanks a lot!

**Comment by kvyb** [comment]
Would be great to get an update regarding this. Thanks!

**Comment by xsacha** [comment]
Likewise. This is the main limitation for us right now.

**Comment by anshulcgm** [comment]
Same here, using cpu on the mac is much slower

**Comment by kulinseth** [comment]
Okay, we will prioritize this.

**Comment by malyshevig** [comment]
Greetings, 
Any news on this? It really hurts. 

Thanks In advance

**Comment by briancpark** [comment]
I'm waiting on an update on this as well. Any way or temporary workaround to fallback to CPU for topk > 16 for now?

**Comment by xsacha** [comment]
Yes, just do .cpu () before calling took. This is how I do it now.
Of course this is much slower due to the conversion to/from.

**Comment by andstor** [comment]
I am also eagerly waiting for this to be resolved! 🙏

**Comment by darren-pei** [comment]
Upvote from me too

**Comment by pastorsj** [comment]
Here too

**Comment by lozhn** [comment]
Still. Fails on `efficientnet_b0` KeypointRCNN :(

**Comment by Stijnp** [comment]
Awaiting this too

**Comment by xsacha** [comment]
Is this anything non-Apple employees can help with? Is it a hardware errata that is being worked around?
Is it faster to do a full sort and slice the tensor rather than the current workaround of using CPU?

**Comment by thanish** [comment]
How long is this going to take any tentative ETA? I feel like no point buying a M1 when I can't train on GPU.

**Comment by kulinseth** [comment]
@thanish , the CLA issues are resolved, we will fix this soon. I will update here with the nightly which has the fix.

**Comment by adalgu** [comment]
Look forward to solving the issues, too!

**Comment by yrik** [comment]
> @thanish , the CLA issues are resolved, we will fix this soon. I will update here with the nightly which has the fix.

Any simple way to help you with this?

**Comment by leedrake5** [comment]
Just checking into watch for this release.

**Comment by ozogxyz** [comment]
Is there a way to change topk for torch.nn.utils.prune?

**Comment by malyshevig** [comment]
2.0.0.dev20230103
Traceback (most recent call last):
  File "/Users/im/PycharmProjects/nn/nn/test.py", line 13, in <module>
    a2mps = torch.topk(input=a.to("mps"), k=20) # not working at all
RuntimeError: Currently topk on mps works only for k<=16 

Process finished with exit code 1

Seems not fixed yet

**Comment by malyshevig** [comment]
Greetings,  Is there any estimated date on fixing the issue?

**Comment by Tofriev** [comment]
It just hurts so much so be banned to colab again :(

**Comment by Janus289** [comment]
Posting to watch.

**Comment by chintan-ushur** [comment]
Posting to watch.

**Comment by lozhn** [comment]
For all of you commenting here "just to watch", on the right there's a seemingly undervalued button. You're welcome 
<img width="329" alt="image" src="https://user-images.githubusercontent.com/1782287/214007233-0305fdf3-d184-4265-bac5-6b5fea2d2acc.png">

**Comment by vashat** [comment]
> Yes, just do .cpu () before calling topk. This is how I do it now.
> Of course this is much slower due to the conversion to/from.

Anybody can explain in more detail on how to do this workaround? The code where it crashes for me is this one:

`indices_to_remove = scores < torch.topk(scores, top_k)[0][..., -1, None]`

Where do I call .cpu()?

**Comment by xsacha** [comment]
indices_to_remove = scores < torch.topk(scores **.to_cpu()** , top_k)[0][..., -1, None]

**Comment by horsto** [comment]
Would be awesome to get this implemented!

**Comment by adalgu** [comment]
I finally escaped this error message "RuntimeError: Currently topk on mps works only for k<=16", but I got another error message like this:
"RuntimeError: MPS does not support cumsum op with int64 input"

What more should I do?
I have an M1 PRO MacBook and am trying to run GPT.

**Comment by emrahnazif** [comment]
> MPS does not support cumsum op with int64 input

https://github.com/pytorch/pytorch/issues/77764

**Comment by kulinseth** [comment]
> I finally escaped this error message "RuntimeError: Currently topk on mps works only for k<=16", but I got another error message like this: "RuntimeError: MPS does not support cumsum op with int64 input"
> 
> What more should I do? I have an M1 PRO MacBook and am trying to run GPT.

@adalgu Thanks for reporting this issue. I will update here with fix/workaround.

**Comment by ahoho** [comment]
Looks like an apparent fix was reverted by #94530?

**Comment by kulinseth** [comment]
Hi @ahoho , support for cumsum `int64` was added in MacOS 13.3. can you please [upgrade and check](https://developer.apple.com/news/releases/?id=02282023c) with latest nightly?

**Comment by ahoho** [comment]
Ah that would explain it! 

> Hi @ahoho , support for cumsum `int64` was added in MacOS 13.3. can you please [upgrade and check](https://developer.apple.com/news/releases/?id=02282023c) with latest nightly?

Ah damn, I was all ready to get the 13.3 beta, but I'm not an Apple Developer. Will have to wait until official release. This explains the documentation mismatch

**Comment by ahoho** [comment]
@kulinseth, yep, the `cumsum` issue is solved with 13.3 beta 3 and I see a slight speedup.

For posterity: I'm encoding ~1700 paragraphs with `sentence-transformers` using the `all-mpnet-base-v2` model, and I go from 25.5s to 21.5s on an M2 Max. Batch size 32, median tokens-per-paragraph about 500. For reference, running on CPU takes 7x the time: 2m37s.

**Comment by jacobmlloyd** [comment]
> Hi @ahoho , support for cumsum `int64` was added in MacOS 13.3. can you please [upgrade and check](https://developer.apple.com/news/releases/?id=02282023c) with latest nightly?

I'm on a Macbook Pro M1 Pro and I've upgraded to 13.3 Beta 3 - I am running into the cumsum issue as well. I've created a new conda environment and installed the nightly version on 3/11/2023 at 12PM PST using 
`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu` 
but I'm still getting 
`RuntimeError: MPS does not support cumsum op with int64 input. Support has been added in macOS 13.3`. 
Any idea how to fix it?

**Comment by oscarwzt** [comment]
Any updates? I'm trying to use yolo-nas from super-gradients, and I get the "Currently topk on mps works only for k<=16 " message when trying to inference. The machine I'm using is macbook m1 pro

**Comment by kulinseth** [comment]
> Any updates? I'm trying to use yolo-nas from super-gradients, and I get the "Currently topk on mps works only for k<=16 " message when trying to inference. The machine I'm using is macbook m1 pro

@oscarwzt the topk issue has been fixed on latest PyTorch release . Which OS version and pytorch version you are using

**Comment by oscarwzt** [comment]
I'm using Ventura 13.4.1, and PyTorch 2.1.0.dev20230716. I'll try to reinstall torch.

**Comment by menithya** [comment]
I had below version of torch
torch.__version__
'1.13.1'
Upgrading torch into  2.2.0, did not solve the problem
 ```
Uninstalling torch-1.13.1:
 Successfully uninstalled torch-1.13.1
Successfully installed torch-2.2.0 typing-extensions-4.9.0
```
Got below error while running neural network, code
`    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute '_six'` 

So what I have done is upgrading torchvision, which solved problem
`Installing collected packages: torchvision
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.14.1
    Uninstalling torchvision-0.14.1:
      Successfully uninstalled torchvision-0.14.1
Successfully installed torchvision-0.17.0`
