### ISSUE TITLE
Cannot import onnx_caffe2.backend

### ISSUE THREAD

**Issue by martinbel** [pytorch/pytorch#7899]
## Issue description

The interpreter gives a Segmentation fault (core dumped) after:
`import onnx_caffe2.backend`

## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.2

Versions of relevant libraries:
[pip3] numpy (1.14.0)
[pip3] numpydoc (0.7.0)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.1)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

I've installed PyTorch with conda [here](https://yangcha.github.io/Onnx/) is what I've used.

**Comment by Pipoderoso** [comment]
You don't have to install onnx-caffe2 anymore, it is merged into the base caffe2. The backend module is found here `import caffe2.python.onnx.backend`

**Comment by Khrylx** [comment]
I finally resolved it. Seems like I need to use the protobuf that caffe2 depends on instead of the one from conda-forge (they are both 3.5.2 though), to do this just install caffe2 before onnx. And I have to build onnx from source.

**Comment by apexprs** [comment]
@Khrylx, Could you please elaborate the steps you took to build onnx from source. Thanks!

**Comment by mruberry** [comment]
Closing due to age and lack of follow-up. If this issue is still occurring please update and reopen this issue.
