### ISSUE TITLE
Multi-node training meets unknown error

### ISSUE THREAD

**Issue by 1049451037** [pytorch/pytorch#79847]
### 🐛 Describe the bug

Multi-node training meets unknown error!

The code I use is 

```python
import os
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim
import torch.multiprocessing as mp

from torch.nn.parallel import DistributedDataParallel as DDP

dist.init_process_group("nccl", rank=int(os.environ["RANK"]), world_size=int(os.environ["WORLD_SIZE"]))
rank = int(os.environ["LOCAL_RANK"])
print(rank)

torch.cuda.set_device(rank)
# create model and move it to GPU with id rank
model = nn.Linear(10, 5).to(rank)
print(model)
ddp_model = DDP(model, device_ids=[rank], output_device=rank)

loss_fn = nn.MSELoss()
optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)

for _ in range(10):
    optimizer.zero_grad()
    outputs = ddp_model(torch.randn(20, 10))
    labels = torch.randn(20, 5).to(rank)
    loss_fn(outputs, labels).backward()
    optimizer.step()
print(ddp_model.module.weight)

dist.destroy_process_group()
```

Then I use the following commands to run:

```
torchrun --nnode 2 --node_rank 0 --nproc_per_node 2 --master_addr 10.1.4.144 --master_port 13579 main.py
torchrun --nnode 2 --node_rank 1 --nproc_per_node 2 --master_addr 10.1.4.144 --master_port 13579 main.py
```

where node 0 ip is 10.1.4.144.

This error occurs on node_rank 0:

```
Traceback (most recent call last):                          
  File "main.py", line 18, in <module>                                                                   
    ddp_model = DDP(model, device_ids=[rank], output_device=rank)
  File "/data/qingsong/anaconda3/envs/th110/lib/python3.8/site-packages/torch/nn/parallel/distributed.py"
, line 578, in __init__
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:891, internal error, NCC
L version 21.0.3
ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption
Linear(in_features=10, out_features=5, bias=True)
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 20640 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 20639) of bi
nary: /data/qingsong/anaconda3/envs/th110/bin/python
```

While node_rank 1 is hanging.

### Versions

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-163-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 3090
GPU 2: GeForce RTX 3090
GPU 3: GeForce RTX 3090
GPU 4: GeForce RTX 3090
GPU 5: GeForce RTX 3090
GPU 6: GeForce RTX 3090
GPU 7: GeForce RTX 3090
GPU 8: GeForce RTX 3090
GPU 9: GeForce RTX 3090

Nvidia driver version: 455.23.04
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.10.1+cu111
[pip3] torchaudio==0.10.1+rocm4.1
[pip3] torchvision==0.11.2+cu111
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     1.10.1+cu111             pypi_0    pypi
[conda] torchaudio                0.10.1+rocm4.1           pypi_0    pypi
[conda] torchvision               0.11.2+cu111             pypi_0    pypi

**Comment by 1049451037** [comment]
This error fixed after I update torch to torch1.11

**Comment by 1049451037** [comment]
I want to run 4 processes with 2 procs per node. It is weird that after the running of multi-node distributed failed, even single node code will meet same error.

```
(th110) qingsong@ubuntu:/data/qingsong/cv$ CUDA_VISIBLE_DEVICES=6 torchrun ini.py
Running basic DDP example on rank 0.
Traceback (most recent call last):                                
  File "ini.py", line 66, in <module>                       
    demo_basic(int(os.environ["RANK"]), int(os.environ["WORLD_SIZE"]))
  File "ini.py", line 51, in demo_basic                     
    ddp_model = DDP(model, device_ids=[rank])
  File "/data/qingsong/anaconda3/envs/th110/lib/python3.8/site-packages/torch/nn/parallel/distributed.py"
, line 578, in __init__                                     
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:891, internal error, NCC
L version 21.0.3                 
ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 51428) of bi
nary: /data/qingsong/anaconda3/envs/th110/bin/python
Traceback (most recent call last):
  File "/data/qingsong/anaconda3/envs/th110/bin/torchrun", line 8, in <module>            
    sys.exit(main())                                        
  File "/data/qingsong/anaconda3/envs/th110/lib/python3.8/site-packages/torch/distributed/elastic/multipr
ocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/data/qingsong/anaconda3/envs/th110/lib/python3.8/site-packages/torch/distributed/run.py", line 7
19, in main
    run(args)
  File "/data/qingsong/anaconda3/envs/th110/lib/python3.8/site-packages/torch/distributed/run.py", line 7
10, in run
    elastic_launch(
  File "/data/qingsong/anaconda3/envs/th110/lib/python3.8/site-packages/torch/distributed/launcher/api.py
", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/qingsong/anaconda3/envs/th110/lib/python3.8/site-packages/torch/distributed/launcher/api.py
", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
ini.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-06-20_11:47:23
  host      : ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 51428)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

where the running code is

```python
import os
import sys
import tempfile
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim
import torch.multiprocessing as mp

from torch.nn.parallel import DistributedDataParallel as DDP

def setup(rank, world_size):
    # initialize the process group
    dist.init_process_group("nccl", rank=rank, world_size=world_size)

def cleanup():
    dist.destroy_process_group()

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))
def demo_basic(rank, world_size):
    print(f"Running basic DDP example on rank {rank}.")
    setup(rank, world_size)

    # create model and move it to GPU with id rank
    model = ToyModel().to(rank)
    ddp_model = DDP(model, device_ids=[rank])

    loss_fn = nn.MSELoss()
    optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)

    optimizer.zero_grad()
    outputs = ddp_model(torch.randn(20, 10))
    labels = torch.randn(20, 5).to(rank)
    loss_fn(outputs, labels).backward()
    optimizer.step()

    cleanup()


if __name__ == '__main__':
    demo_basic(int(os.environ["RANK"]), int(os.environ["WORLD_SIZE"]))
```

which is demo code of PyTorch tutorial.
