### ISSUE TITLE
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:70

### ISSUE THREAD

**Issue by narunask** [pytorch/pytorch#8039]
## Issue description

```
$ python pytorch.py 
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=70 error=30 : unknown error
Traceback (most recent call last):
  File "pytorch.py", line 3, in <module>
    a = torch.ones(3,3).to('cuda')
  File "/usr/lib/python3.6/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:70
```

## Code example

```
import torch

a = torch.ones(3,3).to('cuda')
b = torch.ones(3,3).to('cuda')

print(a + b)
```

## System Info

```
$ python collect_env.py 
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Arch Linux
GCC version: (GCC) 8.1.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 9.2.88
GPU models and configuration: GPU 0: GeForce GTX 970
Nvidia driver version: 396.24
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy (1.14.3)
[pip3] numpydoc (0.7.0)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect
```

`collect_env.py` does not detect `cuDNN` even though it's installed:

```
# pacman -Q | egrep 'cud(a|nn)'
cuda 9.2.88.1-2
cudnn 7.1.3-1
pycuda-headers 2017.1.1-5
python-pycuda 2017.1.1-5
python-tensorflow-opt-cuda 1.8.0-2
```

**Comment by soumith** [comment]
is there something in your LD_LIBRARY_PATH that might override general RPATH? For example do you have cuda 9.2 in your LD_LIBRARY_PATH?

**Comment by Tomato3351** [comment]
The most possible reason is that the version of CUDA is different from the one needed by pytorch .Secondly, you may have no cudnn. What's more, the cudnn also need the right version of CUDA.
I got the same Error at the same line,now it goes right. I have no cudnn before.

**Comment by elcantador** [comment]
i had this error, indeed cuda was installed in an unknow location and the environement path not set properly. i reinstalled cuda with custom location and it resolved the problem. It looks like when the cuda installer suggest an installation directory that doesn't exist, it failed my install, at least i didn't know where it was and could not set my path properly. With the latest installation the path environement variable was set alone tho.
