### ISSUE TITLE
c10d connectivity issues with Torchx

### ISSUE THREAD

**Issue by streamnsight** [pytorch/pytorch#80772]
### 🐛 Describe the bug

I'm trying to use DDP with torchx on a Kubernetes cluster, 

I am running with:
```
torchx run --scheduler kubernetes dist.ddp -j 8x1 --script cifar_dist.py
```

and I am running into a similar issue to this https://github.com/pytorch/pytorch/issues/74824 but for a different reason.

The rank 0 pod rendezvous timeout with the following error trace:

```
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 538, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1024, in next_rendezvous
    self._op_executor.run(join_op, deadline)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 637, in run
    raise RendezvousTimeoutError()
torch.distributed.elastic.rendezvous.api.RendezvousTimeoutError
```

and that is because the pods for the other ranks just can't initialize the server as they error with the following:

```
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 408, in sync
    get_response = self._backend.get_state()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 73, in get_state
    base64_state: bytes = self._call_store("get", self._key)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 115, in _call_store
    raise RendezvousConnectionError(
torch.distributed.elastic.rendezvous.api.RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.
```
the inner exception being:

```
[W socket.cpp:558] [c10d] The IPv6 network addresses of (cifardist-jqgm64sggdw9dd-cifardist-0-0.cifardist-jqgm64sggdw9dd, 29500) cannot be retrieved (gai error: -2 - Name or service not known).
WARNING:torch.distributed.elastic.rendezvous.dynamic_rendezvous:The node 'cifardist-jqgm64sggdw9dd-cifardist-1-0.cifardist-jqgm64sggdw9dd.default.svc.cluster.local_1_0' has failed to shutdown the rendezvous 'cifardist-jqgm64sggdw9dd' due to an error of type RendezvousConnectionError.
```

As you can see, the server address is referenced by the hostname of the pod, which should work. In fact, I have seen it work sometimes, so there is no bug in the code per say, but it fails most of the time for me.

My assumption is that there is a race condition between the pod of rank 0 registering with the DNS service and the c10d service starting up in the other rank pods. C10d servers on rank 1-n try to start before the pod rank 0 is completely registered with DNS and the name lookup fails, causing the c10d server to fail to connect. 

I'm posting this here, (and will cross-reference on the torchx repo), because I believe the solution is in implementing some sort of retry strategy in the store init procedure when looking up a host by hostname.

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.17-2136.306.1.3.el8uek.x86_64-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] botorch==0.6.0
[pip3] gpytorch==1.6.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.5.10
[pip3] torch==1.11.0
[pip3] torch-model-archiver==0.6.0
[pip3] torchelastic==0.2.2
[pip3] torchmetrics==0.9.1
[pip3] torchserve==0.6.0
[pip3] torchtext==0.12.0
[pip3] torchvision==0.12.0
[pip3] torchx==0.2.0
[conda] blas                      1.0                         mkl  
[conda] botorch                   0.6.0                    pypi_0    pypi
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] gpytorch                  1.6.0                    pypi_0    pypi
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.21.2           py38h20f2e39_0  
[conda] numpy-base                1.21.2           py38h79a1101_0  
[conda] pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-lightning         1.5.10                   pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-model-archiver      0.6.0                    pypi_0    pypi
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchmetrics              0.9.1                    pypi_0    pypi
[conda] torchserve                0.6.0                    pypi_0    pypi
[conda] torchtext                 0.12.0                     py38    pytorch
[conda] torchvision               0.12.0               py38_cu113    pytorch
[conda] torchx                    0.2.0                    pypi_0    pypi
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by hchoi-moveworks** [comment]
I'm getting the same error when using multi-node `torchrun` script as well. Any solutions?

**Comment by streamnsight** [comment]
@hchoi-moveworks I posted this this morning, so I'm waiting for an answer from the PyTorch team.
my 'work-around' so far has been to try many, many times, until eventually I'm lucky and the pod rank 0 gets registered first and the whole run works. The more worker nodes, the less likely this works, so that is of course not ideal.

**Comment by streamnsight** [comment]
I see this PR https://github.com/pytorch/pytorch/pull/74641
that apparently was meant to fix this issue, but it was closed and not merged.

**Comment by atinsood** [comment]
I think there are a couple of issues here:

1. the simplest one being that since you are running in kube `cifardist-jqgm64sggdw9dd-cifardist-0-0.cifardist-jqgm64sggdw9dd, 29500` , the hostname `cifardist-jqgm64sggdw9dd-cifardist-0-0.cifardist-jqgm64sggdw9dd` cannot be resolved by kube easily since it doesn't know what that name is. 

this issue here has a good discussion about it https://github.com/pytorch/pytorch/issues/65992#issuecomment-953930352

I think the easiest fix that they are suggesting is rather than using c10d just use etcd so that you can use an etcd based store and back it by a service so that it is always resolvable. 

2. assuming that you don't want to use etcd, and want to stick with c10d, I think there is another bug that you will end up running into 

in this case ```export MASTER_ADDR="192.168.9.104"
export MASTER_PORT="1234"
export LOGLEVEL="DEBUG"
torchrun \
    --nnodes=1:3\
    --nproc_per_node=2\
    --max_restarts=3\
    --rdzv_id=1\
    --rdzv_backend=c10d\
    --rdzv_endpoint="192.168.9.104:1234"\
    --master_addr="192.168.9.104" \
    --master_port=1234 \
    train_elastic.py
``` here is the script that they are running, but if you look at the logs 

```[435] Initializing process group with: {'MASTER_ADDR': 'iZ2ze9q3ftqtxtqlkrk6tuZ', 'MASTER_PORT': '43007', 'WORLD_SIZE': '4', 'LOCAL_WORLD
_SIZE': '2'}
[434] Initializing process group with: {'MASTER_ADDR': 'iZ2ze9q3ftqtxtqlkrk6tuZ', 'MASTER_PORT': '43007', 'WORLD_SIZE': '4', 'LOCAL_WORLD
_SIZE': '2'}
[W socket.cpp:558] [c10d] The IPv6 network addresses of (iZ2ze9q3ftqtxtqlkrk6tuZ, 43007) cannot be retrieved (gai error: -2 - Name or ser
vice not known).
``` the rdvz endpint is getting ignored and still the master_addr is getting set to hostname, as they mentioned over here https://github.com/pytorch/pytorch/issues/74824#issuecomment-1082293477 for some reason `elastic/agent/server/api.py,` is not picking up the right address and I think that;s a bigger issue
https://github.com/pytorch/pytorch/issues/74824

**Comment by streamnsight** [comment]
torchx is the tool creating this dynamic config and passing a hostname, because IPs are not knows before pod creation.
So it is not possible to pass a MASTER_ADDR as an IP in this configuration.

**Comment by atinsood** [comment]
correct, and that's why the etcd solution. the etcd then becomes the address for rndvz and your rndvz store become etcd. that's what this comment is about https://github.com/pytorch/pytorch/issues/65992#issuecomment-953930352

if you want kube to dynamically pick the rdvz server for you, then you need to make sure that all those addresses are resolvable and even then you hav this issue https://github.com/pytorch/pytorch/issues/74824

**Comment by streamnsight** [comment]
@atinsood 
I don't understand your suggestion abot usingetcd.
first, you said yourself that with dist.ddp, the rdvz backend is hard coded to c10d, so not sure how you'd override to use etcd, but even then, how do you use it?
Pod IPs need to be resolved at some point, for the rank 1+ to be able to reach rank0. Whether the rank0 pod is registered in etcd (some way that I still don't understand) or in DNS so c10d can resolve it, it is the same issue: if pod rank 1+ are spinned up before rank0 and there is no retry, the other ranks won't be able to resolve rank0
This is a kubernetes specific issue, where all pods are spinned at once, with no garantee rank0 starts first, and that is the issue.

**Comment by d4l3k** [comment]
@streamnsight can you test out PyTorch 1.12.0? In PyTorch 1.11.0 DNS lookup wouldn't be retried but under 1.12.0 dns failure is a retryable error.

https://github.com/pytorch/pytorch/pull/74641 fixes the issue (it was merged, pytorch just has a weird merge process)

**Comment by streamnsight** [comment]
closing as I got it to work with custom image and torch 1.12
