### ISSUE TITLE
RuntimeError: cuda runtime error (7) : too many resources requested for launch at

### ISSUE THREAD

**Issue by waszy110** [pytorch/pytorch#8103]
Hi,
I am running SegNet on TX1 and I get this error:

RuntimeError: cuda runtime error (7) : too many resources requested for launch at /home/nvidia/pytorch/torch/lib/THCUNN/generic/SpatialUpSamplingBilinear.cu:63

I want to know how to fix it ?
I tried to add '__launch_bounds__(1024)' in '/home/nvidia/pytorch/torch/lib/THCUNN/generic/SpatialUpSamplingBilinear.cu ', but it dose not work.
What is difference between '/pytorch/torch/lib/THCUNN/generic/xx.cu' and '/pytorch/torch/lib/THCUNN/xx.cu' ?

- PyTorch : v0.3.0
- install PyTorch : source
- Build command : 	python setup.py build_deps 
                                sudo python setup.py develop
- Python version: 2.7
- CUDA/cuDNN version: CUDA9.0/cuDNN 7.0
- GPU models and configuration: Maximum number of threads per multiprocessor:  2048
                                                     Maximum number of threads per block:  1024
- GCC version : 5.4.0
- CMake version:3.11.3

**Comment by soumith** [comment]
@waszy110 after you added `launch_bounds`, did you recompile?

**Comment by waszy110** [comment]
Yes, I did  recompile it, but error always occur. Should I change somewhere else?
My change at 'THCUNN/generic/SpatialUpSamplingBilinear.cu ' is  :
#ifndef THC_GENERIC_FILE
#define THC_GENERIC_FILE "generic/SpatialUpSamplingBilinear.cu"
#else
__launch_bounds__(1024)  #### add launch_bounds
static inline void THNN_(SpatialUpSamplingBilinear_shapeCheck)
                        (THCState *state,
                         THCTensor *input, THCTensor *gradOutput,
                         int nBatch, int nChannels,
                         int inputHeight, int inputWidth,
                         int outputHeight, int outputWidth)

**Comment by joe-devv** [comment]
I got around this issue by hard coding the num_threads around line 65 to 512. I'm running on Jetson TX2

**Comment by andrewssobral** [comment]
Hi @joe-devv do you have fixed this? I have the same issue, please look:
https://github.com/pytorch/pytorch/issues/7680#issuecomment-424117317

**Comment by joe-devv** [comment]
Hi @andrewssobral , I have pytorch working on my TX2. I'm at SHA1 ID cfa05706efa and have only done the following change in "aten/src/THCUNN/generic/SpatialUpSamplingBilinear.cu":

Around line 62:
comment out THCState_getCurrentDeviceProperties(state)->maxThraedsPerBlock;
Set
const int num_threads = 512;

Around line 97
comment out THCState_getCurrentDeviceProperties(state)->maxThraedsPerBlock;
Set
const int num_threads = 512;

I followed this guide for installation: https://gist.github.com/dusty-nv/ef2b372301c00c0a9d3203e42fd83426 using the install mode command "sudo python setup.py install"

Hope this helps

**Comment by andrewssobral** [comment]
Great, now it works fine! Thank you @joe-devv !

**Comment by andrewssobral** [comment]
Hi @taodeng , did you re-compiled PyTorch after modification?
Please, find below the source code of my SpatialUpSamplingBilinear.cu, it's working fine for me.
https://gist.github.com/andrewssobral/42ccdd84b65b55f5b8b47ad30e9c82d5

**Comment by geonseoks** [comment]
Hi @ andrewssobral , I have changed 'SpatialUpSamplingBilinear.cu' on my TX2 as you mentioned(https://gist.github.com/andrewssobral/42ccdd84b65b55f5b8b47ad30e9c82d5) and re-compiled PyTorch ('sudo python setup.py install' at Pytorch directory). 
But it also showed the error: 
RuntimeError: cuda runtime error (7) : too many resources requested for launch at /home/nvidia/pytorch/torch/lib/THCUNN/generic/SpatialUpSamplingBilinear.cu:66
How can I fix it? Please give me a advice.

**Comment by perry0418** [comment]
@andrewssobral  
I also face the similar error, however my error track to HCTensorSort.cu.
and I tried your comments to modify both  SpatialUpSamplingBilinear.cu and HCTensorSort.cu, to constant the num_threads. after the recompile, the problem still there. 
I have post my detail error log : https://github.com/pytorch/pytorch/issues/17144
hope you can give me some advice.  thx

**Comment by VitalyFedyunin** [comment]
This is known issue for TX1 and TX2, right now no one is working on it, so we will gladly accept PR which will introduce num_threads customization.

**Comment by dusty-nv** [comment]
@VitalyFedyunin this patch against `v1.1.0` addresses the issue on Jetson platforms for functions that use `getCurrentDeviceProperties()->maxThreadsPerBlock` or `CUDA_NUM_THREADS` or `NUM_BLOCKS`:

```
diff --git a/aten/src/ATen/cuda/CUDAContext.cpp b/aten/src/ATen/cuda/CUDAContext.cpp
index 70a7d05b6..48bf1173e 100644
--- a/aten/src/ATen/cuda/CUDAContext.cpp
+++ b/aten/src/ATen/cuda/CUDAContext.cpp
@@ -24,6 +24,8 @@ void initCUDAContextVectors() {
 void initDeviceProperty(DeviceIndex device_index) {
   cudaDeviceProp device_prop;
   AT_CUDA_CHECK(cudaGetDeviceProperties(&device_prop, device_index));
+  // patch for "too many resources requested for launch"
+  device_prop.maxThreadsPerBlock = device_prop.maxThreadsPerBlock / 2;
   device_properties[device_index] = device_prop;
 }
 
diff --git a/aten/src/ATen/cuda/detail/KernelUtils.h b/aten/src/ATen/cuda/detail/KernelUtils.h
index e535f4d83..ac057c504 100644
--- a/aten/src/ATen/cuda/detail/KernelUtils.h
+++ b/aten/src/ATen/cuda/detail/KernelUtils.h
@@ -12,7 +12,10 @@ namespace at { namespace cuda { namespace detail {
   for (int i = blockIdx.x * blockDim.x + threadIdx.x; i < (n); i += blockDim.x * gridDim.x)
 
 // Use 1024 threads per block, which requires cuda sm_2x or above
-constexpr int CUDA_NUM_THREADS = 1024;
+//constexpr int CUDA_NUM_THREADS = 1024;
+
+// patch for "too many resources requested for launch"
+constexpr int CUDA_NUM_THREADS = 512;
 
 // CUDA: number of blocks for threads.
 inline int GET_BLOCKS(const int N)
diff --git a/aten/src/THCUNN/common.h b/aten/src/THCUNN/common.h
index 9e3ed7d85..08fcb4532 100644
--- a/aten/src/THCUNN/common.h
+++ b/aten/src/THCUNN/common.h
@@ -9,7 +9,10 @@
   "Some of weight/gradient/input tensors are located on different GPUs. Please move them to a single one.")
 
 // Use 1024 threads per block, which requires cuda sm_2x or above
-const int CUDA_NUM_THREADS = 1024;
+//const int CUDA_NUM_THREADS = 1024;
+
+// patch for "too many resources requested for launch"
+const int CUDA_NUM_THREADS = 512;
 
 // CUDA: number of blocks for threads.
 inline int GET_BLOCKS(const int N)
```

However for functions that use neither of these methods, unfortunately I think they may need to manually be modified with `launch_bounds()`.  Perhaps you may have a better understanding of the PyTorch internals.

Also, regarding `getCurrentDeviceProperties()`, it is possible to detect the Jetson GPU string at runtime and only decrease the thread limits in that case.  However for `CUDA_NUM_THREADS`, those are a compile-time constant.  Regardless the builds for aarch64 aren't portable to x86 (and vice versa), so that modification could be `#ifdef`'d only on aarch64.

**Comment by dusty-nv** [comment]
BTW, here are built PyTorch v1.1.0 pip wheels for JetPack 4.2.1 for Jetson Nano, TX1/TX2, and Xavier:

Python 2.7:   https://nvidia.box.com/shared/static/n9p7u0tem1hqe0kyhjspzz78xpka7f5e.whl
Python 3.6:   https://nvidia.box.com/shared/static/mmu3xb3sp4o8qg9tji90kkxl1eijjfc6.whl

**Comment by heethesh** [comment]
@dusty-nv Thanks! Just rebuilt PyTorch on TX2 with JetPack 3.3 and it solved the issue.

**Comment by GerardMaggiolino** [comment]
@dusty-nv Thank you for this patch! However, I'm getting segmentation faults importing torch on the Jetson Nano after installing like so: 
```
wget https://nvidia.box.com/shared/static/mmu3xb3sp4o8qg9tji90kkxl1eijjfc6.whl -O torch-1.1.0-cp36-cp36m-linux_aarch64.whl
pip3 install numpy torch-1.1.0-cp36-cp36m-linux_aarch64.whl
```
Are you aware of any issue that might be Nano specific?

**Comment by dusty-nv** [comment]
@GerardMaggiolino those wheels work on my Nano, both for Python 2.7 and 3.6.

It is possible that PyTorch 1.2.0 fixes this particular `SpatialUpSamplingBilinear` function with launch_bounds, however my patch that above aims to fix a wider group of functions is not included in 1.2.0.  So I will re-patch and re-build wheels for 1.2.0.

**Comment by dusty-nv** [comment]
OK, the new PyTorch v1.2.0 wheels for Jetson are built and are posted [here](https://devtalk.nvidia.com/default/topic/1049071/jetson-nano/pytorch-for-jetson-nano-with-new-torch2trt-converter/).  

They have the resources patch from above applied.

I also found out what went wrong  on external systems with the previously-posted patched v1.1.0 wheel for Python 3.6, so I am re-building that too.

**Comment by OscarSoto6** [comment]
Thanks, finally it works for me on a Jetson tx2 using ESPNet V.2 for semantic segmentation

**Comment by GerardMaggiolino** [comment]
@dusty-nv Thank you! I've tried v1.2.0 on the Jetson Nano and can confirm these patched wheels work on my side as well. Much appreciated!

**Comment by jlevy44** [comment]
I'm still getting this issue with 1.3.0

**Comment by t-vi** [comment]
I think the original problem report by @wxs has been fixed with PyTorch 1.2.
Note that the launch bounds in the patch of the June 5 message seems to be in a wrong place.
I verified that we do seem to have proper launch bounds for Bilinear 2d upscaling and it works as expected on the Jetson Nano.

@jlevy44: Could you provide a reproducing example + information on your environment?

If we don't have confirmation that this still is an issue with recent PyTorch and a reproducing example I would suggest closing the bug.

**Comment by storm12t48** [comment]
Do you have version for torch2.0.0?
