### ISSUE TITLE
distributed training hanging

### ISSUE THREAD

**Issue by upwindflys** [pytorch/pytorch#81313]
### 🐛 Describe the bug

when i run the shell on two node,the program hanging,but i have no idea how it happened.
```python
torchrun --nproc_per_node=2 --nnodes=2 --node_rank=0 --master_addr='10.110.158.1' --master_port=3456 main.py  
torchrun --nproc_per_node=2 --nnodes=2 --node_rank=1 --master_addr='10.110.158.1' --master_port=3456 main.py
```
```python
#main.py
import argparse
import os
import sys
import tempfile
from urllib.parse import urlparse

import torch
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim

from torch.nn.parallel import DistributedDataParallel as DDP

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))


def train():
    local_rank = int(os.environ["LOCAL_RANK"])
    rank = int(os.environ["RANK"])
    print(f"[{os.getpid()}] (rank = {rank}, local_rank = {local_rank}) training...")
    model = ToyModel().cuda(local_rank)
    ddp_model = DDP(model, [local_rank])

    loss_fn = nn.MSELoss()
    optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)

    optimizer.zero_grad()
    outputs = ddp_model(torch.randn(20, 10).to(local_rank))
    labels = torch.randn(20, 5).to(local_rank)
    loss = loss_fn(outputs, labels)
    loss.backward()
    print(f"[{os.getpid()}] (rank = {rank}, local_rank = {local_rank}) loss = {loss.item()}\n")
    optimizer.step()

def run():
    env_dict = {
        key: os.environ[key]
        for key in ("MASTER_ADDR", "MASTER_PORT", "WORLD_SIZE", "LOCAL_WORLD_SIZE")
    }
    print(f"[{os.getpid()}] Initializing process group with: {env_dict}")
    dist.init_process_group(backend="nccl")
    train()
    dist.destroy_process_group()


if __name__ == "__main__":
    run()
```
###Outputs
node0
```python
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[28332] Initializing process group with: {'MASTER_ADDR': '10.110.158.1', 'MASTER_PORT': '3456', 'WORLD_SIZE': '4', 'LOCAL_WORLD_SIZE': '2'}
[28333] Initializing process group with: {'MASTER_ADDR': '10.110.158.1', 'MASTER_PORT': '3456', 'WORLD_SIZE': '4', 'LOCAL_WORLD_SIZE': '2'}
[28332] (rank = 0, local_rank = 0) training...
[28333] (rank = 1, local_rank = 1) training...

```
node1
```python
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2815] Initializing process group with: {'MASTER_ADDR': '10.110.158.1', 'MASTER_PORT': '3456', 'WORLD_SIZE': '4', 'LOCAL_WORLD_SIZE': '2'}
[2816] Initializing process group with: {'MASTER_ADDR': '10.110.158.1', 'MASTER_PORT': '3456', 'WORLD_SIZE': '4', 'LOCAL_WORLD_SIZE': '2'}
[2816] (rank = 3, local_rank = 1) training...
[2815] (rank = 2, local_rank = 0) training...

```
### Versions

node0
Collecting environment information...
PyTorch version: 1.10.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.0
Clang version: Could not collect
CMake version: version 3.23.0-rc2
Libc version: glibc-2.17

Python version: 3.6.8 (default, Sep 25 2019, 11:05:12)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] (64-bit runtime)
Python platform: Linux-3.10.0-1160.59.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
Is CUDA available: True
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 450.172.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.10.1
[pip3] torchvision==0.11.2
[conda] Could not collect

node1
Collecting environment information...
PyTorch version: 1.10.2+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.3.4

Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] (64-bit runtime)
Python platform: Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 450.191.01
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.2
[pip3] torchvision==0.11.2
[conda] Could not collect

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by aazzolini** [comment]
- Where does it get stuck exactly? Are you able to add more print statements to check what's the last line the you go through?
- You should also be able to set debug flags to get more debugging info (TORCH_DISTRIBUTED_DEBUG=DETAIL): https://pytorch.org/docs/stable/distributed.html#torch-distributed-debug
- You may not need to pass the device ID to the constructor of DDP (although I don't think this should cause issues).

**Comment by upwindflys** [comment]
@aazzolini Thanks, I soloved the problem by setting NCCL_SOCKET_NAME

**Comment by helios2k6** [comment]
For those of you who have also gotten stuck on this running the toy model example on the Pytorch (website)[https://pytorch.org/tutorials/intermediate/ddp_tutorial.html#initialize-ddp-with-torch-distributed-run-torchrun], the actual environment variable name is: `NCCL_SOCKET_IFNAME` [ref](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-socket-ifname).

Set this environment variable equal to the network interface that your nodes need to communicate over. e.g.

1. Run `ip link show`
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 ...
2: enpxxx: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 ...
3: wlpxxxx: <BROADCAST,MULTICAST> mtu 1500 ...
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 ...
```
2. Export your variable: `export NCCL_SOCKET_IFNAME=enpxxx`
3. Do this on all of your nodes
4. You now should be able to run the ToyModel example.

**Comment by getchebarne** [comment]
thanks @helios2k6! this worked for me too
