### ISSUE TITLE
NCCL WARN NET/IB : Got completion from peer 192.168.17.147<38560> with error 12, opcode 0, len 0, vendor err 129

### ISSUE THREAD

**Issue by upwindflys** [pytorch/pytorch#81628]
### 🐛 Describe the bug

When i used method 
```python
dist.init_process_group(backend='nccl', init_method=args.init_method, world_size=args.world_size, rank=rank)
```
on two nodes,setting args.init_method='10.110.158.147:3456' args.world_size=2,rank=0 or rank=1 on diffirent nodes,
an error occured.
```python
tf144:143468:143468 [1] NCCL INFO Bootstrap : Using enp88s0:192.168.17.144<0>
tf144:143468:143468 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
tf144:143468:143468 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
tf144:143468:143468 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE [1]mlx5_1:1/RoCE [2]i40iw0:1/RoCE ; OOB enp88s0:192.168.17.144<0>
tf144:143468:143468 [1] NCCL INFO Using network IB
tf144:143468:143535 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] 0/-1/-1->1->-1 [3] 0/-1/-1->1->-1
tf144:143468:143535 [1] NCCL INFO Setting affinity for GPU 1 to fff0,00fff000
tf144:143468:143535 [1] NCCL INFO Channel 00 : 0[2f000] -> 1[86000] [receive] via NET/IB/1
tf144:143468:143535 [1] NCCL INFO Channel 01 : 0[2f000] -> 1[86000] [receive] via NET/IB/0
tf144:143468:143535 [1] NCCL INFO Channel 02 : 0[2f000] -> 1[86000] [receive] via NET/IB/1
tf144:143468:143535 [1] NCCL INFO Channel 03 : 0[2f000] -> 1[86000] [receive] via NET/IB/0
tf144:143468:143535 [1] NCCL INFO Channel 00 : 1[86000] -> 0[2f000] [send] via NET/IB/1
tf144:143468:143535 [1] NCCL INFO Channel 01 : 1[86000] -> 0[2f000] [send] via NET/IB/0
tf144:143468:143535 [1] NCCL INFO Channel 02 : 1[86000] -> 0[2f000] [send] via NET/IB/1
tf144:143468:143535 [1] NCCL INFO Channel 03 : 1[86000] -> 0[2f000] [send] via NET/IB/0
tf144:143468:143535 [1] NCCL INFO NCCL_IB_GID_INDEX set by environment to 0.
tf144:143468:143535 [1] NCCL INFO Connected all rings
tf144:143468:143535 [1] NCCL INFO Connected all trees
tf144:143468:143535 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
tf144:143468:143535 [1] NCCL INFO 4 coll channels, 4 p2p channels, 1 p2p channels per peer
tf144:143468:143535 [1] NCCL INFO comm 0x7f22f0000fa0 rank 1 nranks 2 cudaDev 1 busId 86000 - Init COMPLETE

tf144:143468:143537 [0] transport/net_ib.cc:882 NCCL WARN NET/IB : Got completion from peer 192.168.17.147<38560> with error 12, opcode 0, len 0, vendor err 129
tf144:143468:143537 [0] NCCL INFO include/net.h:28 -> 2
tf144:143468:143537 [0] NCCL INFO transport/net.cc:459 -> 2
tf144:143468:143537 [0] NCCL INFO proxy.cc:351 -> 2
tf144:143468:143537 [0] NCCL INFO proxy.cc:452 -> 2 [Proxy Thread]

```
But if i run it with ```torchrun```, the program runs successfully.
What are the possible reasons for this？

### Versions

Info for rank0:
Collecting environment information...
PyTorch version: 1.10.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.0
Clang version: Could not collect
CMake version: version 3.23.0-rc2
Libc version: glibc-2.17

Python version: 3.6.8 (default, Sep 25 2019, 11:05:12)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] (64-bit runtime)
Python platform: Linux-3.10.0-1160.59.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
Is CUDA available: True
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 450.172.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.10.1
[pip3] torchvision==0.11.2

Info for rank1:
Collecting environment information...
PyTorch version: 1.10.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.3.4

Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] (64-bit runtime)
Python platform: Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 450.191.01
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.1
[pip3] torchvision==0.11.2
[conda] Could not collect

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by anj-s** [comment]
I found a similar error in another [issue](https://github.com/NVIDIA/nccl/issues/426) Is this something that can help?
cc @kwen2501  and @H-Huang  who may have seen this NCCL error before

**Comment by H-Huang** [comment]
I have not seen this error before, but I am curious about your init method. The setting `args.init_method='10.110.158.147:3456'` is supposed to fail, is that mistyped?

For example, something like 
`dist.init_process_group(backend='nccl', init_method="127.0.0.1:7777", world_size=1, rank=0)` errors with `RuntimeError: No rendezvous handler for ://`

**Comment by kwen2501** [comment]
vendor err 129 is usually a timeout.
When it happens right away, it usually means the NICs can't talk to each other using IB or RoCE. 
Maybe see this solved NCCL issue for diagnosis and solution:
https://github.com/NVIDIA/nccl/issues/426
@H-Huang @anj-s

**Comment by yangjian41727** [comment]
my problem was solved  by adding “-x NCCL_IB_GID_INDEX=3”
The gpu machines are under different switches，the default gid can't create link to each other

**Comment by awgu** [comment]
Marking as stale
