### ISSUE TITLE
Topk: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by byphilipp** [pytorch/pytorch#82569]
### 🐛 Describe the bug

Nvidia driver crash if number of elements argument of torch.topk  > 60000000 

```
x = torch.randn((50, 1000,1000),device='cuda')
torch.topk (x,10,-1) # Works
x = torch.randn((60, 1000,1000),device='cuda')
torch.topk (x,10,-1) # Crash

```
> RuntimeError: CUDA error: an illegal memory access was encountered

### Versions

1st system
Windows 10
Anaconda3 2021.11
Python3 3.9.7
torch 1.12.0+cu116
Nvidia GeForce RTX 2070 
Nvidia Driver 516.01

2nd system 
Ubuntu 2022.04
Python 3.8.13
torch 1.12.0+cu116
Nvidia RTX A4000
Nvidia Driver 515.48.07

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by byphilipp** [comment]
torch 1.11.0+cu115 works correctly

**Comment by ngimel** [comment]
cc @zasdfgbnm, @yueyericardo

**Comment by yueyericardo** [comment]
Sorry, I could not reproduce, my environment is the following
```
Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-91-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: GPU 0: NVIDIA A100 80GB PCIe
Nvidia driver version: 510.73.08
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] blas                      2.16                        mkl    conda-forge
[conda] cudatoolkit               11.6.0              hecad31d_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.8.0                    16_mkl    conda-forge
[conda] libcblas                  3.8.0                    16_mkl    conda-forge
[conda] liblapack                 3.8.0                    16_mkl    conda-forge
[conda] liblapacke                3.8.0                    16_mkl    conda-forge
[conda] mkl                       2020.2                      256
[conda] numpy                     1.22.3           py38h99721a1_2    conda-forge
[conda] pytorch                   1.12.0          py3.8_cuda11.6_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.12.0               py38_cu116    pytorch
[conda] torchvision               0.13.0               py38_cu116    pytorch
```

**Comment by zasdfgbnm** [comment]
I can not reproduce either. Master pytorch + CUDA 11.7...

**Comment by byphilipp** [comment]
torch 1.13.0.dev20220801+cu116 not contain issue too

**Comment by byphilipp** [comment]
This config with torch1.11.0+cu115 works correctly
conda list

```
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0
absl-py                   1.2.0                    pypi_0    pypi
affine                    2.3.1              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1            py39hb82d6ee_1    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
albumentations            1.2.1                    pypi_0    pypi
altair                    4.2.0              pyhd8ed1ab_1    conda-forge
anaconda-client           1.8.0              pyhd8ed1ab_0    conda-forge
anaconda-navigator        2.2.0            py39haa95532_0    anaconda
antialiased-cnns          0.3                      pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.6.1            py39hcbf5309_0    conda-forge
aom                       3.4.0                h0e60522_1    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39hb82d6ee_2    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
arrow-cpp                 8.0.0            py39hbd6f097_0
asciitree                 0.3.3                    pypi_0    pypi
astroid                   2.5.8            py39hcbf5309_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
atomicwrites              1.4.1              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
autopep8                  1.6.0              pyhd8ed1ab_1    conda-forge
aws-c-common              0.4.57               ha925a31_1
aws-c-event-stream        0.1.6                hd77b12b_5
aws-checksums             0.1.9                ha925a31_0
aws-sdk-cpp               1.8.185              hd77b12b_0
axial-attention           0.6.1                    pypi_0    pypi
babel                     2.10.3             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
backports.tempfile        1.0                        py_0    conda-forge
backports.weakref         1.0.post1       pyhd8ed1ab_1003    conda-forge
bcrypt                    3.2.2            py39hb82d6ee_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     22.6.0             pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blinker                   1.5                      pypi_0    pypi
blosc                     1.21.1               h74325e0_3    conda-forge
bokeh                     2.4.3            py39hcbf5309_0    conda-forge
boost-cpp                 1.74.0               h9f4b32c_8    conda-forge
botorch                   0.6.5                    pypi_0    pypi
bqplot                    0.12.33            pyhd8ed1ab_0    conda-forge
branca                    0.5.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-ares                    1.18.1               h8ffe710_0    conda-forge
c-blosc2                  2.2.0                hdf67494_0    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.2.0                    pypi_0    pypi
cairo                     1.16.0            h0ac17fb_1011    conda-forge
cdsapi                    0.5.1                    pypi_0    pypi
cenpy                     1.0.0.post4              pypi_0    pypi
certifi                   2022.6.15                pypi_0    pypi
cffi                      1.15.1           py39h0878f49_0    conda-forge
cfgrib                    0.9.10.1           pyhd8ed1ab_0    conda-forge
cfitsio                   4.1.0                h5a969a9_0    conda-forge
cftime                    1.6.1            py39h5d4886f_0    conda-forge
chardet                   5.0.0            py39hcbf5309_0    conda-forge
charls                    2.3.4                h39d44d4_0    conda-forge
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py39hcbf5309_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
colorcet                  3.0.0              pyhd8ed1ab_0    conda-forge
colour                    0.1.5                    pypi_0    pypi
commonmark                0.9.1                      py_0    conda-forge
conda                     4.13.0           py39hcbf5309_1    conda-forge
conda-build               3.21.9           py39hcbf5309_1    conda-forge
conda-content-trust       0.1.3              pyhd8ed1ab_0    conda-forge
conda-env                 2.6.0                         1
conda-package-handling    1.8.1            py39hb3671d1_1    conda-forge
conda-repo-cli            1.0.5            py39haa95532_0
conda-token               0.3.0              pyhd3eb1b0_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
contextily                1.2.0                    pypi_0    pypi
cookiecutter              2.1.1              pyh6c4a22f_0    conda-forge
cryptography              37.0.4           py39h7bc7c5c_0    conda-forge
cudatoolkit               11.6.0              hc0ea762_10    conda-forge
curl                      7.83.1               h789b8ee_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cykhash                   2.0.0                    pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
cytoolz                   0.12.0           py39hb82d6ee_0    conda-forge
daal                      2021.5.0           haa95532_796
daal4py                   2021.5.0         py39hefe7e4c_0    conda-forge
dal                       2021.5.0           h0e2418a_796    conda-forge
dask                      2022.7.1           pyhd8ed1ab_0    conda-forge
dask-core                 2022.7.1           pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
datasets                  2.4.0                    pypi_0    pypi
datashader                0.14.1             pyh6c4a22f_1    conda-forge
datashape                 0.5.4                      py_1    conda-forge
dav1d                     1.0.0                h8ffe710_1    conda-forge
debugpy                   1.6.0            py39h415ef7b_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
deprecated                1.2.13                   pypi_0    pypi
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
dill                      0.3.5                    pypi_0    pypi
distributed               2022.7.1           pyhd8ed1ab_0    conda-forge
docker                    5.0.3                    pypi_0    pypi
docstring-parser          0.8.1                    pypi_0    pypi
docutils                  0.19             py39hcbf5309_0    conda-forge
earthengine-api           0.1.317            pyhd8ed1ab_0    conda-forge
earthpy                   0.9.4              pyhd8ed1ab_0    conda-forge
eccodes                   2.26.0               h36aa8e7_0    conda-forge
ecmwflibs                 0.4.17                   pypi_0    pypi
ee_extra                  0.0.14             pyhd8ed1ab_0    conda-forge
efficientnet-pytorch      0.6.3                    pypi_0    pypi
einops                    0.4.1                    pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h39d44d4_0    conda-forge
fasteners                 0.17.3                   pypi_0    pypi
ffmpeg                    4.4.2           gpl_ha0349d7_106    conda-forge
ffmpeg-python             0.2.0                      py_0    conda-forge
filelock                  3.7.1              pyhd8ed1ab_0    conda-forge
findlibs                  0.0.2              pyhd8ed1ab_0    conda-forge
fiona                     1.8.21           py39h0a5cb73_2    conda-forge
flake8                    4.0.1              pyhd8ed1ab_2    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
folium                    0.12.1.post1       pyhd8ed1ab_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hce3cb01_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.34.4           py39hb82d6ee_0    conda-forge
freeglut                  3.2.2                h0e60522_1    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
frozenlist                1.3.0            py39hb82d6ee_1    conda-forge
fsspec                    2022.7.1           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py39hcbf5309_5    conda-forge
fuzzywuzzy                0.18.0                   pypi_0    pypi
gdal                      3.5.1            py39h3f5efd6_1    conda-forge
gdown                     4.5.1              pyhd8ed1ab_0    conda-forge
geeadd                    0.5.4              pyhd8ed1ab_0    conda-forge
geemap                    0.16.1             pyhd8ed1ab_0    conda-forge
geeviz                    2022.7.2                 pypi_0    pypi
geocoder                  1.38.1                     py_1    conda-forge
geographiclib             1.52                     pypi_0    pypi
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.11.1             pyhd8ed1ab_0    conda-forge
geopandas-base            0.11.1             pyha770c72_0    conda-forge
geopy                     2.2.0                    pypi_0    pypi
geos                      3.11.0               h39d44d4_0    conda-forge
geotiff                   0.2.7                    pypi_0    pypi
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
gflags                    2.2.2             ha925a31_1004    conda-forge
giflib                    5.2.1                h8d14728_2    conda-forge
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.27             pyhd8ed1ab_0    conda-forge
glib                      2.72.1               h7755175_0    conda-forge
glib-tools                2.72.1               h7755175_0    conda-forge
glob2                     0.7                        py_0    conda-forge
glog                      0.6.0                h4797de2_0    conda-forge
google-api-core           2.8.2                    pypi_0    pypi
google-api-python-client  1.12.11                  pypi_0    pypi
google-auth               2.9.1                    pypi_0    pypi
google-auth-httplib2      0.1.0              pyhd8ed1ab_1    conda-forge
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-cloud-core         2.3.2                    pypi_0    pypi
google-cloud-storage      2.4.0                    pypi_0    pypi
google-crc32c             1.3.0                    pypi_0    pypi
google-resumable-media    2.3.3              pyhd8ed1ab_0    conda-forge
googleapis-common-protos  1.56.4           py39h35db3c3_0    conda-forge
gpytorch                  1.8.0                    pypi_0    pypi
graph-weather             1.0.15                   pypi_0    pypi
grpcio                    1.48.0                   pypi_0    pypi
gst-plugins-base          1.20.3               he07aa86_0    conda-forge
gstreamer                 1.20.3               hdff456e_0    conda-forge
h3                        3.7.4                    pypi_0    pypi
h5py                      3.7.0           nompi_py39hd4deaf1_100    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
httplib2                  0.20.4             pyhd8ed1ab_0    conda-forge
httplib2shim              0.0.3              pyh9f0ad1d_0    conda-forge
huggingface-hub           0.8.1                    pypi_0    pypi
humanize                  4.2.3                    pypi_0    pypi
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagecodecs               2022.7.31        py39h8730835_0    conda-forge
imageio                   2.21.0                   pypi_0    pypi
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py39hcbf5309_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipyevents                 2.0.1              pyhd8ed1ab_0    conda-forge
ipyfilechooser            0.6.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.15.1             pyh025b116_0    conda-forge
ipyleaflet                0.17.0             pyhd8ed1ab_0    conda-forge
ipympl                    0.9.1                    pypi_0    pypi
ipyparallel               8.4.1                    pypi_0    pypi
ipysheet                  0.5.0              pyhd8ed1ab_0    conda-forge
ipython                   7.33.0           py39hcbf5309_0    conda-forge
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipytree                   0.2.1              pyhd8ed1ab_0    conda-forge
ipywidgets                7.7.1              pyhd8ed1ab_0    conda-forge
isort                     5.10.1             pyhd8ed1ab_0    conda-forge
jasper                    2.0.33               h77af90b_0    conda-forge
jedi                      0.18.1           py39hcbf5309_1    conda-forge
jellyfish                 0.9.0            py39hb82d6ee_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonpatch                 1.32                     pypi_0    pypi
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.9.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py39hcbf5309_0    conda-forge
jupyter_server            1.18.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.4.4              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.15.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
kealib                    1.4.15               h8995ca9_0    conda-forge
keopscore                 2.1                      pypi_0    pypi
keplergl                  0.3.2              pyhd8ed1ab_0    conda-forge
keyring                   23.7.0           py39hcbf5309_0    conda-forge
kiwisolver                1.4.4            py39h2e07f2f_0    conda-forge
kornia                    0.6.6                    pypi_0    pypi
krb5                      1.19.3               h1176d77_0    conda-forge
lazy-object-proxy         1.7.1            py39hb82d6ee_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
leafmap                   0.10.3             pyhd8ed1ab_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h39d44d4_0    conda-forge
libarchive                3.5.2                hb45042f_3    conda-forge
libavif                   0.10.1               h8ffe710_1    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  14.0.6          default_h77d9078_0    conda-forge
libclang13                14.0.6          default_h77d9078_0    conda-forge
libcrc32c                 1.1.2                h0e60522_0    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge
libdeflate                1.12                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.5.1                h7a56975_1    conda-forge
libglib                   2.72.1               h3be07f2_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
liblapacke                3.9.0              12_win64_mkl    conda-forge
liblief                   0.11.5               h0e60522_1    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_102    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopencv                 4.6.0            py39hbfd931d_3    conda-forge
libpng                    1.6.37               h1d00b33_3    conda-forge
libpq                     14.4                 hfcc5ef8_0    conda-forge
libprotobuf               3.20.1               h7755175_0    conda-forge
libpysal                  4.6.2                    pypi_0    pypi
librttopo                 1.1.0               h2842628_11    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1               ha17912d_18    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libthrift                 0.15.0               h636ae23_1    conda-forge
libtiff                   4.4.0                ha17eb64_2    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.2.3                h8ffe710_1    conda-forge
libwebp-base              1.2.3                h8ffe710_2    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.14               hf5bbc77_3    conda-forge
libzip                    1.9.2                hfed4ece_0    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
llvmlite                  0.38.1           py39ha0cd8c8_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
logzero                   1.7.0            py39hcbf5309_2    conda-forge
lz4                       4.0.0            py39h0878066_2    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2-msys2-runtime          2.5.0.17080.65c939c               3    conda-forge
m2-patch                  2.7.5                         2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1            py39hb82d6ee_1    conda-forge
matplotlib                3.5.2                    pypi_0    pypi
matplotlib-base           3.5.2            py39h581301d_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.18           py39h59b6b97_0
mercantile                1.2.1                    pypi_0    pypi
metnet                    4.0.0                    pypi_0    pypi
mistune                   0.8.4           py39hb82d6ee_1005    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0            py39h6b0492b_0    conda-forge
momepy                    0.5.3                    pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
msgpack-python            1.0.4            py39h2e07f2f_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 6.0.2            py39hb82d6ee_1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
multiprocess              0.70.12.2                pypi_0    pypi
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           0.4.3            py39hcbf5309_5    conda-forge
navigator-updater         0.2.1            py39haa95532_0
nbclassic                 0.4.3              pyhd8ed1ab_0    conda-forge
nbclient                  0.6.6              pyhd8ed1ab_0    conda-forge
nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
netcdf4                   1.6.0           nompi_py39hf113b1f_100    conda-forge
networkx                  2.8.5              pyhd8ed1ab_0    conda-forge
nibabel                   4.0.1                    pypi_0    pypi
ninja                     1.11.0               h2d74725_0    conda-forge
noise                     1.2.2           py39hb82d6ee_1003    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
notebook-shim             0.1.0              pyhd8ed1ab_0    conda-forge
numba                     0.55.2           py39hb8cd55e_0    conda-forge
numcodecs                 0.10.1                   pypi_0    pypi
numexpr                   2.8.3            py39hb80d3ca_0
numpy                     1.23.1                   pypi_0    pypi
numpydoc                  1.4.0              pyhd8ed1ab_1    conda-forge
oauth2client              4.1.3                    pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
omegaconf                 2.2.2                    pypi_0    pypi
opencv                    4.6.0            py39hcbf5309_3    conda-forge
opencv-python-headless    4.6.0.66                 pypi_0    pypi
openh264                  2.2.0                h0e60522_2    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
osmnx                     1.2.1                    pypi_0    pypi
packaging                 21.3               pyhd8ed1ab_0    conda-forge
palettable                3.3.0                    pypi_0    pypi
pandas                    1.4.3            py39h2e25243_0    conda-forge
pandoc                    2.18                 h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
param                     1.12.2             pyh6c4a22f_0    conda-forge
paramiko                  2.11.0             pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pathlib                   1.0.1            py39hcbf5309_6    conda-forge
pathos                    0.2.8                    pypi_0    pypi
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0                    pypi_0    pypi
pip                       22.2.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pkginfo                   1.8.3              pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
planetary-computer        0.4.6                    pypi_0    pypi
platformdirs              2.5.2              pyhd8ed1ab_1    conda-forge
plotly                    5.9.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py39hcbf5309_3    conda-forge
ply                       3.11                       py_1    conda-forge
poppler                   22.04.0              h24fffdf_1    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
portalocker               2.5.1                    pypi_0    pypi
postgresql                14.4                 h1c22c4f_0    conda-forge
powershell_shortcut       0.0.1                         3
pox                       0.3.1                    pypi_0    pypi
ppft                      1.7.6.5                  pypi_0    pypi
pretrainedmodels          0.7.4                    pypi_0    pypi
proj                      9.0.1                h1cfcee9_1    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
protobuf                  3.19.4                   pypi_0    pypi
pscript                   0.7.5              pyhd3deb0d_0    conda-forge
psutil                    5.9.1            py39hb82d6ee_0    conda-forge
psycopg2                  2.9.3                    pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-lief                   0.11.5           py39h415ef7b_1    conda-forge
py-opencv                 4.6.0            py39h832f523_3    conda-forge
pyarrow                   8.0.0                    pypi_0    pypi
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                    pypi_0    pypi
pybind11                  2.10.0                   pypi_0    pypi
pycodestyle               2.8.0              pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py39hb82d6ee_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycrs                     1.0.2                      py_0    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pydantic                  1.9.1                    pypi_0    pypi
pydeck                    0.7.1              pyh6c4a22f_0    conda-forge
pydeprecate               0.3.2                    pypi_0    pypi
pydevd                    2.8.0                    pypi_0    pypi
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyflakes                  2.4.0              pyhd8ed1ab_0    conda-forge
pygeoda                   0.0.8.post1              pypi_0    pypi
pygeos                    0.12.0                   pypi_0    pypi
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pygrib                    2.1.4            py39h417709b_5    conda-forge
pyhdf                     0.10.5           py39h3813cc5_0    conda-forge
pyjwt                     2.4.0              pyhd8ed1ab_0    conda-forge
pykeops                   2.1                      pypi_0    pypi
pylint                    2.7.2            py39hcbf5309_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pympler                   1.0.1              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0            py39hb3671d1_1    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.1            py39h380ba8d_1    conda-forge
pyqt                      5.15.7           py39hb08f45d_0    conda-forge
pyqt5                     5.15.4                   pypi_0    pypi
pyqt5-plugins             5.15.4.2.2               pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.11.0          py39h415ef7b_0    conda-forge
pyqt5-tools               5.15.4.3.2               pypi_0    pypi
pyqtwebengine             5.15.7           py39hb08f45d_0    conda-forge
pyqtwebengine-qt5         5.15.2                   pypi_0    pypi
pyre-extensions           0.0.29                   pypi_0    pypi
pyro-api                  0.1.2                    pypi_0    pypi
pyro-ppl                  1.8.1                    pypi_0    pypi
pyrobuf                   0.9.3                    pypi_0    pypi
pyrosm                    0.6.1                    pypi_0    pypi
pyrsistent                0.18.1           py39hb82d6ee_1    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hcbf5309_5    conda-forge
pystac                    1.6.1              pyhd8ed1ab_1    conda-forge
pystac-client             0.4.0              pyhd8ed1ab_0    conda-forge
python                    3.9.7                h6244533_1
python-box                6.0.2            py39hb82d6ee_3    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-dotenv             0.20.0                   pypi_0    pypi
python-eccodes            1.4.2            py39h5d4886f_0    conda-forge
python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
python-libarchive-c       4.0              py39hcbf5309_1    conda-forge
python-lsp-black          1.2.1              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.5.0              pyhd8ed1ab_0    conda-forge
python-rapidjson          1.8                      pypi_0    pypi
python-slugify            6.1.2              pyhd8ed1ab_0    conda-forge
python-snappy             0.6.1                    pypi_0    pypi
python-tzdata             2022.1             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytoolconfig              1.2.2              pyhd8ed1ab_0    conda-forge
pytorch-ignite            0.5.0.dev20220802          pypi_0    pypi
pytorch-lightning         1.6.5                    pypi_0    pypi
pytorch-msssim            0.2.1                    pypi_0    pypi
pytorch-ranger            0.1.1                    pypi_0    pypi
pytorch-tabnet            3.1.1                    pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pytz-deprecation-shim     0.1.0.post0      py39hcbf5309_2    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0            py39h5d4886f_1    conda-forge
pywin32                   227                      pypi_0    pypi
pywin32-ctypes            0.2.0           py39hcbf5309_1005    conda-forge
pywinpty                  2.0.6            py39h99910a6_0    conda-forge
pyyaml                    6.0              py39hb82d6ee_4    conda-forge
pyzmq                     23.2.0           py39he46f08e_0    conda-forge
qdarkstyle                3.0.3              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.1              pyhd8ed1ab_0    conda-forge
qt-main                   5.15.4               h467ea89_2    conda-forge
qt-webengine              5.15.4               h7325c83_3    conda-forge
qt5-applications          5.15.2.2.2               pypi_0    pypi
qt5-tools                 5.15.2.1.2               pypi_0    pypi
qtawesome                 1.1.1              pyhd8ed1ab_0    conda-forge
qtconsole                 5.3.1              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.3.1              pyha770c72_0    conda-forge
qtpy                      2.1.0              pyhd8ed1ab_0    conda-forge
qudida                    0.0.4                    pypi_0    pypi
rasterio                  1.3.0                    pypi_0    pypi
rasterstats               0.17.0                   pypi_0    pypi
ratelim                   0.1.6                      py_2    conda-forge
re2                       2022.04.01           h0e60522_0    conda-forge
regex                     2022.7.25                pypi_0    pypi
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1                    pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
rich                      12.5.1             pyhd8ed1ab_0    conda-forge
rioxarray                 0.11.1             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               h7f3b576_2    conda-forge
rope                      1.3.0              pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
rtree                     1.0.0            py39h09fdee3_1    conda-forge
ruamel.yaml               0.17.21          py39hb82d6ee_1    conda-forge
ruamel.yaml.clib          0.2.6            py39hb82d6ee_1    conda-forge
ruamel_yaml               0.15.80         py39hb82d6ee_1007    conda-forge
sankee                    0.2.0              pyhd8ed1ab_0    conda-forge
scikit-image              0.19.3           py39h2e25243_0    conda-forge
scikit-learn              1.1.1            py39he931e04_0    conda-forge
scikit-learn-intelex      2021.5.0         py39hcbf5309_1    conda-forge
scipy                     1.9.0            py39h316f440_0    conda-forge
scooby                    0.6.0              pyhd8ed1ab_0    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
segmentation-models-pytorch 0.2.1                    pypi_0    pypi
semver                    2.13.0             pyh9f0ad1d_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                63.3.0           py39hcbf5309_0    conda-forge
setuptools-scm            7.0.5                    pypi_0    pypi
shapely                   1.8.2            py39he0923fe_3    conda-forge
simpleitk                 2.1.1.2                  pypi_0    pypi
simplejson                3.17.6           py39hb82d6ee_1    conda-forge
sip                       6.6.2            py39h415ef7b_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.0                    pypi_0    pypi
snappy                    1.1.9                h82413e6_1    conda-forge
sniffio                   1.2.0            py39hcbf5309_3    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
spatialpandas             0.4.4                    pypi_0    pypi
sphinx                    5.1.1              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
spyder                    5.3.2            py39hcbf5309_0    conda-forge
spyder-kernels            2.3.2            py39hcbf5309_0    conda-forge
sqlite                    3.39.2               h8ffe710_0    conda-forge
statsmodels               0.13.2           py39h5d4886f_0    conda-forge
streamlit                 1.11.1             pyhd8ed1ab_0    conda-forge
streamlit-folium          0.6.14             pyhd8ed1ab_0    conda-forge
svt-av1                   1.1.0                h0e60522_1    conda-forge
sympy                     1.10.1                   pypi_0    pypi
sympytorch                0.1.1                    pypi_0    pypi
tbb                       2021.5.0             h2d74725_1    conda-forge
tbb4py                    2021.5.0         py39hd0a9cb8_1    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
tensorboard               2.9.1                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
terminado                 0.15.0           py39hcbf5309_0    conda-forge
terminaltables            3.1.10                   pypi_0    pypi
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.3.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tifffile                  2022.4.26                pypi_0    pypi
tiledb                    2.9.5                h5689973_0    conda-forge
timm                      0.4.12                   pypi_0    pypi
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tokenizers                0.12.1                   pypi_0    pypi
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
torch                     1.11.0+cu115             pypi_0    pypi
torch-assimilate          0.2.1                    pypi_0    pypi
torch-cluster             1.6.0                    pypi_0    pypi
torch-complex             0.4.3                    pypi_0    pypi
torch-geometric           2.0.4                    pypi_0    pypi
torch-optimizer           0.3.0                    pypi_0    pypi
torch-pruning             0.2.8                    pypi_0    pypi
torch-scatter             2.0.9                    pypi_0    pypi
torch-sparse              0.6.14                   pypi_0    pypi
torch-spline-conv         1.2.1                    pypi_0    pypi
torch-yolo3               0.1.1                    pypi_0    pypi
torchaudio                0.11.0+cu115             pypi_0    pypi
torchdata                 0.3.0                    pypi_0    pypi
torchfile                 0.1.0                    pypi_0    pypi
torchfunc                 0.2.0                    pypi_0    pypi
torchgeo                  0.3.0                    pypi_0    pypi
torchinfo                 1.7.0                    pypi_0    pypi
torchio                   0.18.83                  pypi_0    pypi
torchmetrics              0.9.3                    pypi_0    pypi
torchtext                 0.12.0                   pypi_0    pypi
torchvision               0.12.0+cu115             pypi_0    pypi
torchx                    0.2.0                    pypi_0    pypi
tornado                   6.1              py39hb82d6ee_3    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
traittypes                0.2.1              pyh9f0ad1d_2    conda-forge
transformers              4.21.0                   pypi_0    pypi
typed-ast                 1.5.4            py39hb82d6ee_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing-inspect            0.7.1                    pypi_0    pypi
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
tzlocal                   4.2              py39hcbf5309_1    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
ujson                     5.3.0            py39h415ef7b_0    conda-forge
unicodedata2              14.0.0           py39hb82d6ee_1    conda-forge
unidecode                 1.3.4              pyhd8ed1ab_0    conda-forge
uritemplate               3.0.1                      py_0    conda-forge
urllib3                   1.26.11                  pypi_0    pypi
utf8proc                  2.6.1                h2bbff1b_0
validators                0.20.0                   pypi_0    pypi
vc                        14.2                 hb210afc_6    conda-forge
visdom                    0.1.8.9                  pypi_0    pypi
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
watchdog                  2.1.9            py39hcbf5309_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.3.3              pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.1                    pypi_0    pypi
wget                      3.2                      pypi_0    pypi
whatthepatch              1.0.2              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
whitebox                  2.1.4              pyhd8ed1ab_0    conda-forge
whiteboxgui               0.7.0              pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.1              pyha770c72_0    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_4    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.11.2           py39h4cdbadb_1    conda-forge
x264                      1!161.3030           h8ffe710_1    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xarray                    2022.6.0           pyhd8ed1ab_1    conda-forge
xarray-spatial            0.3.5              pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h0e60522_5    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libx11               1.7.2                hcd874cb_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xxhash                    3.0.0                    pypi_0    pypi
xyzservices               2022.6.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yapf                      0.32.0             pyhd8ed1ab_0    conda-forge
yarl                      1.7.2            py39hb82d6ee_2    conda-forge
zarr                      2.12.0                   pypi_0    pypi
zeromq                    4.3.4                h0e60522_1    conda-forge
zfp                       0.5.5                h0e60522_8    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h8ffe710_2    conda-forge
zlib-ng                   2.0.6                h8ffe710_0    conda-forge
zstd                      1.5.2                h6255e5f_2    conda-forge
```

**Comment by ngimel** [comment]
Can't repro with source build + cuda 11.6.

**Comment by byphilipp** [comment]
This issue fixed after 

conda install -c conda-forge cudatoolkit==11.6

**Comment by byphilipp** [comment]
I'm upgraded to torch 1.13.0+cu116 and Driver Version: 526.98 have some error but with other symptomatic

The error is hidden e.g. the cuda kernel drops at next operation with topk outputs !!

The error occurs in two cases
1. if the number of elements is 1024**3 and bigger and the sorting dimension is 32768 and bigger


> import torch
> x=torch.randn([32768,32768],dtype=torch.float16,device='cuda')
> 
> x=torch.topk(x,16,-1) # Without error
> 
> print(x)  
> RuntimeError: CUDA error: an illegal memory access was encountered



2. if the sorting dimension is 1024 and bigger and the product of other dimensions is 65536 and bigger 

> import torch
> x=torch.randn([65536,1024],dtype=torch.float16,device='cuda')
> 
> x=torch.topk(x,16,-1) # Without error
> 
> print(x)  
> RuntimeError: CUDA error: an illegal memory access was encountered

> import torch
> x=torch.randn([256, 256,1024],dtype=torch.float16,device='cuda')
> 
> x=torch.topk(x,16,-1) # Without error
> 
> print(x)  
> RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by colobas** [comment]
Seeing the same errors as @byphilipp on `1.13.1+cu117`

**Comment by Interpause** [comment]
Also having the same issue `pip install torch==1.13.1`.

**Comment by zasdfgbnm** [comment]
Could you try nightly to see if you still get the same error? There is a recent fix not in 1.13.1:
https://github.com/pytorch/pytorch/pull/93095

**Comment by byphilipp** [comment]
problem solved in 2.0.0
