### ISSUE TITLE
torch.nn.MaxPool1d dont accept 0-batch dim tensors on gpu

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#83325]
### 🐛 Describe the bug

torch.nn.MaxPool1d accept 0-batch dim tensors on cpu, however I found that torch.nn.MaxPool1d don’t accept 0-batch dim tensors on gpu. I think cpu’s result should be consistent with gpu’s result.
```
results = dict()
import torch
arg_1 = 2
arg_2 = 50
arg_3 = True
arg_class = torch.nn.MaxPool1d(arg_1,stride=arg_2,return_indices=arg_3,)
arg_4 = torch.rand([0, 1, 49], dtype=torch.float32)
try:
  results["res_cpu"] = arg_class(arg_4)
except Exception as e:
  results["err_cpu"] = "ERROR:"+str(e)
arg_class = arg_class.cuda()
arg_5 = arg_4.clone().cuda()
try:
  results["res_gpu"] = arg_class(arg_5)
except Exception as e:
  results["err_gpu"] = "ERROR:"+str(e)
print(results)
```
Above snippet code outputs: {‘res_cpu’: (tensor([], size=(0, 1, 1)), tensor([], size=(0, 1, 1), dtype=torch.int64)), ‘err_gpu’: ‘ERROR:CUDA error: invalid configuration argument’}.

### Versions

pytorch: 1.8.1
python: 3.8.3
os: win11

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by ezyang** [comment]
It should accept 0 numel tensors; it's probably an easy fix, send us a patch and tag me on it.

**Comment by khushi-411** [comment]
Hi,
I think this error is fixed in the master branch (`'1.13.0a0+git016fcca'`). Please see:
```python
In [2]: torch.nn.MaxPool1d(2, stride=50, return_indices=True)
Out[2]: MaxPool1d(kernel_size=2, stride=50, padding=0, dilation=1, ceil_mode=False)

In [5]: x = torch.rand([0, 1, 49], dtype=torch.float32, device='cpu')

In [7]: torch.nn.MaxPool1d(2, stride=50, return_indices=True)(x)
Out[7]: (tensor([], size=(0, 1, 1)), tensor([], size=(0, 1, 1), dtype=torch.int64))

In [8]: x = torch.rand([0, 1, 49], dtype=torch.float32, device='cuda')

In [9]: torch.nn.MaxPool1d(2, stride=50, return_indices=True)(x)
Out[9]: 
(tensor([], device='cuda:0', size=(0, 1, 1)),
 tensor([], device='cuda:0', size=(0, 1, 1), dtype=torch.int64))
```

Could you please upgrade your pytorch version and re-check it? Thanks!
