### ISSUE TITLE
[caffe2] segmentation fault for running 'from caffe2.python import core'

### ISSUE THREAD

**Issue by krumo** [pytorch/pytorch#8377]
## Issue description

I followed [official instruction](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=prebuilt) to install caffe2-cuda8.0-cudnn7 with conda. When I run `from caffe2.python import core` in Python, the console will output a segmentation fault error. Plus, even if I set up CUDA8, cudnn7 and build nccl from the [source](https://github.com/NVIDIA/nccl), caffe2 still cannot find the GPU. I also tried using symbolic link to link libnccl.so.2 to libnccl.so.1 or libnccl.so, but it still doesn't work. Could you give me some help?

## Console output

> WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libnccl.so.2: cannot open shared object file: No such file or directory
Segmentation fault

## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Debian GNU/Linux 8 (jessie)
GCC version: (GCC) 5.4.0
CMake version: version 3.11.3

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 8.0.44
GPU models and configuration: 
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X
GPU 2: GeForce GTX TITAN X
GPU 3: GeForce GTX TITAN X
GPU 4: GeForce GTX TITAN X
GPU 5: GeForce GTX TITAN X

Nvidia driver version: 384.130
cuDNN version: 7

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] torch                     0.4.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

**Comment by pjh5** [comment]
Where did you install nccl? Run ldd on your libcaffe2.so (should be in anaconda_root_dir/envs/your_env/lib/libcaffe2.so) to see where it expects nccl to be installed.

**Comment by krumo** [comment]
@pjh5 Thank you for you answer. I have solved this problem. Because I am installing caffe2 on a debian OS without sudo right, I cannot use `apt install` to install nccl. My solution is to install nccl on my own laptop and copied libnccl.2.x.x to this PC. Now it works well. Thank you again!
