### ISSUE TITLE
RuntimeError: CUDA error: device not ready

### ISSUE THREAD

**Issue by qq1243196045** [pytorch/pytorch#85796]
## Issue description
**when I use torch.cuda.Event for Record the time that my model used, an error has occurred.**

## Code example
here is my test code
```python
from transformers import Wav2Vec2Processor, Wav2Vec2Model
import torch
from datasets import load_dataset

dataset = load_dataset("hf-internal-testing/librispeech_asr_demo", "clean", split="validation")
dataset = dataset.sort("id")
sampling_rate = dataset.features["audio"].sampling_rate

processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base-960h")
model = model.cuda()

inputs = processor(dataset[0]["audio"]["array"], sampling_rate=sampling_rate, return_tensors="pt")
input_values = inputs["input_values"].cuda()
start = torch.cuda.Event(enable_timing=True)
end = torch.cuda.Event(enable_timing=True)
with torch.no_grad():
    start.record()
    # outputs = model(**inputs)
    outputs = model(input_values)
    end.record()
```
Traceback (most recent call last):
  File "/home/crj/PycharmProjects/huggincface/test.py", line 23, in <module>
    elapsed_time = start.elapsed_time(end)
  File "/home/crj/anaconda3/envs/wav2vec2/lib/python3.7/site-packages/torch/cuda/streams.py", line 204, in elapsed_time
    return super(Event, self).elapsed_time(end_event)
RuntimeError: CUDA error: device not ready
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

## System Info
Collecting environment information...
PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.10

Python version: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-41-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.20.0
[pip3] torch==1.12.0+cu116
[pip3] torchaudio==0.12.0+rocm5.1.1
[pip3] torchvision==0.13.0+cu116
[conda] numpy                     1.20.0                   pypi_0    pypi
[conda] torch                     1.12.0+cu116             pypi_0    pypi
[conda] torchaudio                0.12.0+rocm5.1.1          pypi_0    pypi
[conda] torchvision               0.13.0+cu116             pypi_0    pypi

Process finished with exit code 0

```

**Comment by duggi-9977** [comment]
I had the same issue and this code worked for me :
import gc
gc.collect()
torch.cuda.empty_cache()

If is still doesn't work for you then please check this link, there are multiple ways people have discussed this issue. It might be helpful :
https://stackoverflow.com/questions/54374935/how-to-fix-this-strange-error-runtimeerror-cuda-error-out-of-memory

**Comment by qq1243196045** [comment]
> I had the same issue and this code worked for me : import gc gc.collect() torch.cuda.empty_cache()
> 
> If is still doesn't work for you then please check this link, there are multiple ways people have discussed this issue. It might be helpful : https://stackoverflow.com/questions/54374935/how-to-fix-this-strange-error-runtimeerror-cuda-error-out-of-memory

thanks,when I add torch.cuda.synchronize() after end.record(),It word well!
people discussed this issue here too:
https://stackoverflow.com/questions/6551121/cuda-cudaeventelapsedtime-returns-device-not-ready-error
