### ISSUE TITLE
Direct approach to free up GPU memory allocated to a tensor

### ISSUE THREAD

**Issue by yzs981130** [pytorch/pytorch#87015]
### 🚀 The feature, motivation and pitch

I need to free some CUDA tensors (e.g., tensor `a` as the model parameters) to avoid OOM on GPU during the model forward. I have tried `del a` and call `torch.cuda.empty_cache()` t free both `a` and PyTorch GPU cache. However, the `del a` does not free the underlying GPU memory. After searching in the [PyTorch forum](https://discuss.pytorch.org/t/cuda-memory-not-released-by-torch-cuda-empty-cache/129913/2?u=yzs), the GPU memory may not be freed due to other references. 

I believe it is not very difficult to expose a `tensor.free()` or sth else for a contiguous tensor, by directly call `delete` or `cudaFree` on the underlying `data`. 

Related discussion on the forum:

- https://discuss.pytorch.org/t/cuda-memory-not-released-by-torch-cuda-empty-cache/129913
- https://discuss.pytorch.org/t/pytorch-cuda-free-gpu-memory/74946

**Comment by awgu** [comment]
The foremost question is probably why are there still references. However, if you are sure you want to free the tensor despite there still being references, I think you can try `t.storage().resize_(0)` for a tensor `t`.

**Comment by yzs981130** [comment]
> I think you can try `t.storage().resize_(0)` for a tensor `t`.

Thanks for your explanation! The `t.storage().resize_(0)` works like a charm and the `torch.cuda.memory_allocated()` also decreases. 


> May I ask: Is this for DeepSpeed? 😮

I'm afraid not. Just some personal trials. 🤣
