### ISSUE TITLE
*** RuntimeError: CUDA error: device-side assert triggered for this : tmp = torch.ones([3, 8]).cuda()

### ISSUE THREAD

**Issue by HuangChiEn** [pytorch/pytorch#87835]
### Enviroment 

Collecting environment information...
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8.8 (default, Feb 24 2021, 21:46:12)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-1086-azure-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB

Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.0
[pip3] pytorch-lightning==1.6.1
[pip3] torch==1.8.1
[pip3] torchelastic==0.2.2
[pip3] torchmetrics==0.8.0
[pip3] torchtext==0.9.1
[pip3] torchvision==0.9.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.3.0            py38h54f3939_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.22.0                   pypi_0    pypi
[conda] pytorch                   1.8.1           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] pytorch-lightning         1.6.1                    pypi_0    pypi
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchmetrics              0.8.0                    pypi_0    pypi
[conda] torchtext                 0.9.1                      py38    pytorch
[conda] torchvision               0.9.1                py38_cu111    pytorch

### 🐛 Describe the bug

---
The first run i encountered the assertion error
![image](https://user-images.githubusercontent.com/52521165/198168845-2aa9a800-347b-49f6-bb3c-b6866b6e09b3.png)

---

There have several similar issuese, however most of them do not match with my content.
while the first time i run the code and `*** RuntimeError: CUDA error: device-side assert triggered` raised in this line
`assert torch.all(match_quality_matrix >= 0)`, so i setup the breakpoint before it to debug in pdb.

![image](https://user-images.githubusercontent.com/52521165/198167282-c7eca131-e0e2-497b-85f0-bb4ebf1554b3.png)
---

then i try to run `assert torch.all(match_quality_matrix >= 0)` and **it success!! without any error** (i try to run after 2~3 line of code, see below figure). However, when i continue (c) in pdb, the error is raised. 
![image](https://user-images.githubusercontent.com/52521165/198167856-f8454629-c06c-42a0-8e57-4422451a5b2d.png)

The **assert error** (yes, it just assertion, i can remove, but i thnk it may not be the real problem) message : 
![image](https://user-images.githubusercontent.com/52521165/198167956-b48a2fdc-1586-4e39-8a16-db3888f6e827.png)

--- 
then the amazing error occurs : 
I even can not declare the variable on cuda device!!
![image](https://user-images.githubusercontent.com/52521165/198166959-69cd7200-685b-4e90-9762-622474b41b60.png)
![image](https://user-images.githubusercontent.com/52521165/198168487-4e2e5fe5-b881-4394-a97d-9ddc36d76c6a.png)

---
Note that : Before the aforementioned assertion occurs (`assert torch.all(match_quality_matrix >= 0)`), i have try to confirm the cuda works fine !!
![image](https://user-images.githubusercontent.com/52521165/198168190-861d4fdb-db08-49d1-b18f-a489bb9f0cb4.png)

Any suggestion will be appreciated !!

**Comment by soumith** [comment]
please use the forums for questions: https://discuss.pytorch.org/
As far as I can see, this is not a bug.

**Comment by HuangChiEn** [comment]
@soumith 
### Thanks for your guidance, i may post this issue in torch forums, instead of here in free time. We solved this issue by install the other stable suit of pytorch (`pip install torch==1.9.1+cu111`). 

However, i think it may be called the bug due to the mutually incompatible suit (`pip install torch==1.8.1+cu111`) recommended by the [official website](https://pytorch.org/get-started/previous-versions/).

Although most of function is works fine, but some potential incompatible part between torch_1.8.1ver and cuda-toolkit_11.1ver caused the aforementioned error.
