### ISSUE TITLE
CUFFT_INTERNAL_ERROR on RTX 4090

### ISSUE THREAD

**Issue by Yujia-Yan** [pytorch/pytorch#88038]
### 🐛 Describe the bug

```
>>> import torch
>>> torch.fft.rfft(torch.randn(1000).cuda())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR
```

There is a discussion on https://forums.developer.nvidia.com/t/bug-ubuntu-on-wsl2-rtx4090-related-cufft-runtime-error/230883/7 .

### Versions

Using pytorch installed with 
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

cc @ezyang @gchanan @zou3519 @peterjc123 @mszhanyi @skyline75489 @nbcsm @ngimel @mruberry @peterbell10

**Comment by malfet** [comment]
Just to clarify, this happen only in Windows Subsystem for Linux or elsewhere as well?

**Comment by Yujia-Yan** [comment]
> Just to clarify, this happen only in Windows Subsystem for Linux or elsewhere as well?

Actually I am using ubuntu Server 22.04. 
Update:
 I later tried to compile pytorch with CUDA 11.8 and this problem disappears.

**Comment by ngimel** [comment]
So in this case it looks like cufft library doesn't support forward compatibility guarantee (you can run code compiled with older toolkit version, as long as driver on the system supports the new hardware). cc @ptrblck, and we should start producing 11.8 nightlies.

**Comment by Blackhex** [comment]
I don't have 4090 available so I can only add that it is not reproducible on Windows 11 and Ubuntu WSL with 3080.

**Comment by ptrblck** [comment]
> can you please confirm that this indeed happens when with 4090 on Linux or only in WSL config?

Yes, this is a cuFFT error which is also visible on Linux.

> and we should start producing 11.8 nightlies.

Also yes, and I've already started with its bringup, e.g. in: https://github.com/pytorch/builder/pull/1186

**Comment by malfet** [comment]
Some updates: 
- this seems to be the bug in CuFFT in CUDA-11.7 that happens on both Linux and Windows, but seems to be fixed in 11.8
- It worth trying (and I think some investigation has already been done) to use CuFFT from 11.8 in 11.7 build to see if the fix could be deployed/verified to nightlies first

**Comment by malfet** [comment]
First thing, that worries me a lot is 2x binary size increase for cuda-11.8:
```
$ ls -lah 11.7/libcufft/lib64/libcufft.so.10.7.2.50 11.8/libcufft/lib64/libcufft.so.10.9.0.58 
-rwxr-xr-x 1 nshulga nshulga 131M Nov 29 21:48 11.7/libcufft/lib64/libcufft.so.10.7.2.50
-rwxr-xr-x 1 nshulga nshulga 267M Nov 29 21:49 11.8/libcufft/lib64/libcufft.so.10.9.0.58
```

**Comment by malfet** [comment]
Removing high priority label, as this is a bug in a 3rd party library and there were big changes between cufft in 11.7 and 11.8

**Comment by pranavmalikk** [comment]
Still getting this error on RTX 4090 with Cuda 11.7 on Ubuntu, any recommendations?

**Comment by ptrblck** [comment]
@pranavmalikk Yes, please use the nightly binaries with CUDA 11.8.

**Comment by pranavmalikk** [comment]
> @pranavmalikk Yes, please use the nightly binaries with CUDA 11.8.

I'm still getting this on CUDA 11.8

**Comment by ptrblck** [comment]
Could you post the output of `torch.__version__` as well as `python -m torch.utils.collect_env`, please, as I cannot reproduce the error in the CUDA 11.8 nightly binaries anymore:
```python
import torch
print(torch.__version__)
out = torch.fft.rfft(torch.randn(1000).cuda())
print(out.sum())
```
with 11.7 it fails as reported:
```python
python tmp.pt 
2.0.0.dev20230204+cu117
Traceback (most recent call last):
  File "tmp.pt", line 3, in <module>
    torch.fft.rfft(torch.randn(1000).cuda())
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR
```
Update the nightlies to the 11.8 build:
```
pip uninstall torch -y
Found existing installation: torch 2.0.0.dev20230204+cu117
Uninstalling torch-2.0.0.dev20230204+cu117:
  Successfully uninstalled torch-2.0.0.dev20230204+cu117
pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu118
...
Successfully installed torch-2.0.0.dev20230204+cu118
```
and it works:
```python
python tmp.py 
2.0.0.dev20230204+cu118
tensor(670.6870+11.1756j, device='cuda:0')
```

**Comment by pranavmalikk** [comment]
> Could you post the output of `torch.__version__` as well as `python -m torch.utils.collect_env`, please, as I cannot reproduce the error in the CUDA 11.8 nightly binaries anymore:
> 
> ```python
> import torch
> print(torch.__version__)
> out = torch.fft.rfft(torch.randn(1000).cuda())
> print(out.sum())
> ```
> 
> with 11.7 it fails as reported:
> 
> ```python
> python tmp.pt 
> 2.0.0.dev20230204+cu117
> Traceback (most recent call last):
>   File "tmp.pt", line 3, in <module>
>     torch.fft.rfft(torch.randn(1000).cuda())
> RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR
> ```
> 
> Update the nightlies to the 11.8 build:
> 
> ```
> pip uninstall torch -y
> Found existing installation: torch 2.0.0.dev20230204+cu117
> Uninstalling torch-2.0.0.dev20230204+cu117:
>   Successfully uninstalled torch-2.0.0.dev20230204+cu117
> pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu118
> ...
> Successfully installed torch-2.0.0.dev20230204+cu118
> ```
> 
> and it works:
> 
> ```python
> python tmp.py 
> 2.0.0.dev20230204+cu118
> tensor(670.6870+11.1756j, device='cuda:0')
> ```

Thank you for the help, it works now as everytime i did 'pip install torchaudio' it set me back to an older version of torch. I fixed this by installing the nightly version of torchaudio

**Comment by Selimonder** [comment]
Also came across this issue
```python
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR
```
with the following environment (WSL-2, 4090)
```
Collecting environment information...
PyTorch version: 2.1.0.dev20230314
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 531.18
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz
CPU family:                      6
Model:                           158
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        13
BogoMIPS:                        6192.02
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi ept vpid ept_ad fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves flush_l1d arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        2 MiB (8 instances)
L3 cache:                        16 MiB (1 instance)
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Mitigation; TSX disabled
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.1.0.dev20230314
[pip3] torchaudio==2.0.0.dev20230315
[pip3] torchvision==0.15.0.dev20230314
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.5           py39h14f4228_0  
[conda] numpy-base                1.23.5           py39h31eccc5_0  
[conda] pytorch                   2.1.0.dev20230314 py3.9_cuda11.7_cudnn8.5.0_0    pytorch-nightly
[conda] pytorch-cuda              11.7                 h778d358_3    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                2.0.0.dev20230315      py39_cu117    pytorch-nightly
[conda] torchtriton               2.1.0+2c32f43999            py39    pytorch-nightly
[conda] torchvision               0.15.0.dev20230314      py39_cu117    pytorch-nightly
```

**Comment by bensonbs** [comment]
Due to package dependency issues, I am limited to using versions of PyTorch that are below 2.0.0. I understand that PyTorch 1.13.1 supports up to CUDA 11.7. Could you kindly advise if there are any alternative solutions apart from upgrading to CUDA 11.8?

**Comment by dhruv-acog** [comment]
> Due to package dependency issues, I am limited to using versions of PyTorch that are below 2.0.0. I understand that PyTorch 1.13.1 supports up to CUDA 11.7. Could you kindly advise if there are any alternative solutions apart from upgrading to CUDA 11.8?

You can upgrade to a higher PyTorch version like 2.0.0 (CUDA 11.8) - it has backward compatibility

**Comment by bigmover** [comment]
> torch.fft.rfft(torch.randn(1000).cuda())

Hi @bensonbs Have you succeed in solving this on torch 1.13? Would you mind to give some advice ? Thank you very much !

**Comment by anas-zafar** [comment]
@bigmover were you able to fix this issue?

**Comment by Syclus123** [comment]
On my Ubuntu system, the original CUDA version was 12.1 and Torch version was 1.13.1. Considering that CUDA version cannot be adapted, I downgraded CUDA version to 11.7, but it cannot solve the problem.
