### ISSUE TITLE
'RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR' when using torch.nn.GRU

### ISSUE THREAD

**Issue by Jerry-jwz** [pytorch/pytorch#90011]
### 🐛 Describe the bug

The example is very simple, just using the torch.nn.GRU() to build a neural network and conduct model inference.

```python
import torch.nn as nn 
import torch

device = torch.device(f'cuda:2' if torch.cuda.is_available() else 'cpu')

bs = 32
T = 12
d = 8
e = 10
x = torch.rand(bs, T, d).to(device)
init_hidden = torch.rand(1, bs, e).to(device)

model = nn.GRU(input_size=d, hidden_size=e, num_layers=1, batch_first=True)
model = model.to(device)
output, _ = model(x, init_hidden)
```

Then I got the following error, which, however, did not show up when I ran this code on CPU.
```
  File "/home/jiangwenzhao/ASTGNN/my_test.py", line 27, in <module>
    output, _ = model(x, init_hidden)
  File "/home/jiangwenzhao/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiangwenzhao/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 849, in forward
    result = _VF.gru(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
```

It is very strange, since the day before yesterday the error did not show up even if I ran it on GPU. Hope that anyone could help!

### Versions

```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Clang version: Could not collect
CMake version: version 3.15.5
Libc version: glibc-2.17

Python version: 3.8.0 (default, Nov  6 2019, 21:49:08)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.48.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] pytorch-lightning==1.8.0.post1
[pip3] torch==1.10.0
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.1.0.post1
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.13
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.10.0
[pip3] torchmetrics==0.10.2
[pip3] torchvision==0.11.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h8d4b97c_729    conda-forge
[conda] mkl-service               2.4.0            py38h95df7f1_0    conda-forge
[conda] mkl_fft                   1.3.1            py38h8666266_1    conda-forge
[conda] mkl_random                1.2.2            py38h1abd341_0    conda-forge
[conda] numpy                     1.23.1           py38h6c91a56_0  
[conda] numpy                     1.23.3                    <pip>
[conda] numpy-base                1.23.1           py38ha15fc14_0  
[conda] pytorch                   1.10.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-lightning         1.8.0.post1               <pip>
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-cluster             1.6.0                     <pip>
[conda] torch-geometric           2.1.0.post1               <pip>
[conda] torch-scatter             2.0.9                     <pip>
[conda] torch-sparse              0.6.13                    <pip>
[conda] torch-spline-conv         1.2.1                     <pip>
[conda] torchaudio                0.10.0               py38_cu113    pytorch
[conda] torchmetrics              0.10.2                    <pip>
[conda] torchvision               0.11.0               py38_cu113    pytorch
```

cc @csarofeen @ptrblck @xwang233 @ngimel

**Comment by malfet** [comment]
Can you please try updating to PyTorch-1.13 (using cuda-11.6 or 11.7) and try again?

**Comment by drisspg** [comment]
Hello Jerry, I was not able to reproduce this issue on the torch 1.13. I see that you are using 1.10, would it be possible to upgrade your torch version

**Comment by ptrblck** [comment]
FYI: I also cannot reproduce the issue on a 3090 using `1.10.0+cu113`.

**Comment by Jerry-jwz** [comment]
Thanks for your feedbacks! 

Strange things happen again, the error disappeared today without any modification of the code or environment.

But I might have found the reason. I checked the gpustat while the code was running. I found that although I set the device to be **_'cuda:2'_** as shown in the code, there was some memory usage on both gpu 0 and gpu 2. I tried to take up all the memory on gpu 0 and then run the same code above. The error is reproduced!

Therefore, the question now comes to why gpu 0 is used in this code? Does anyone have experience?

**Comment by Jerry-jwz** [comment]
> Thanks for your feedbacks!
> 
> Strange things happen again, the error disappeared today without any modification of the code or environment.
> 
> But I might have found the reason. I checked the gpustat while the code was running. I found that although I set the device to be **_'cuda:2'_** as shown in the code, there was some memory usage on both gpu 0 and gpu 2. I tried to take up all the memory on gpu 0 and then run the same code above. The error is reproduced!
> 
> Therefore, the question now comes to why gpu 0 is used in this code? Does anyone have experience?

It turns out to be a problem in torch 1.10.0.

I just updated to torch 1.12.1 and the weird memory allocation phenomenon disappears.
