### ISSUE TITLE
Can Pytorch2.0(the current nightly build) be installed on CUDA11.4? I got the errors when built from source

### ISSUE THREAD

**Issue by lindylin1817** [pytorch/pytorch#90135]
### 🐛 Describe the bug

I'm using Python3.8 and A100 with CUDA 11.4 . Can I install Pytorch2.0 (nightlybuilt) on this environment? 

When I tried compiling the source of Pytorch, I always got the error to fail the compiliation of nccl_external. I don't know if it is the reason of CUDA11.4. 

But I'm using a docker environment where I might not be able to change the CUDA version. Thanks for your help!

### Versions

python: 3.8
CUDA 11.4
A100

cc @malfet @seemethere @ezyang @soumith

**Comment by ptrblck** [comment]
Yes, source builds should be possible using CUDA 11.4.Could you post the error message you are seeing, please?

**Comment by ezyang** [comment]
I wonder if it's this one: https://github.com/pytorch/pytorch/issues/78882

In the end I fixed the problem by upgrading CUDA. If you don't need distributed you could also compile with USE_DISTRIBUTED=0 but that may not be acceptable.

**Comment by malfet** [comment]
Can you please share the build log? And how did you install CUDA-11.4? (I always have to fix nccl makefile if CUDA is installed from RPMs rather than from a runfile installer)

**Comment by ezyang** [comment]
ok, i'll close this for now, but feel free to reopen if you try 11.4 and get another log.
