### ISSUE TITLE
After pytorch encapsulates the custom operator, the output cannot be obtained。RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by zhangapeng** [pytorch/pytorch#92123]
### 🐛 Describe the bug

I have customized the operation through pytorch's c++ and cuda extensions. After the compilation is completed, testing the operator alone without encapsulation can obtain normal output, but after encapsulating it with torch.autograd Function, the printout result will report an CUDA runtime error：an illegal memory access was encountered. 

### Versions

Collecting environment information...
PyTorch version: 1.12.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.3.58
CUDA_MODULE_LOADING set to:
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 470.161.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==1.12.0+cu113
[pip3] torchvision==0.13.0+cu113
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     1.12.0+cu113             pypi_0    pypi
[conda] torchvision               0.13.0+cu113             pypi_0    pypi

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @ngimel

**Comment by zhangapeng** [comment]
`import torch
from torch.autograd import Function
import torch.nn as nn
from torch import Tensor
from torch.nn.modules.utils import _pair
from torch.nn.parameter import Parameter
import scipy.sparse as sp
import my_ops

class MyConvF(Function):
    @staticmethod
    def forward(ctx,
                input: torch.Tensor,
                weight: torch.Tensor,
                bias,
                A_rowptr,
                A_colind,
                A_csrVal,
                stride=1,
                padding=0,
                dilation=1,
                groups=1,
                im2col_step=8):
        if input is not None and input.dim() != 4:
            raise ValueError(
                f'Expected 4D tensor as input, got {input.dim()}D tensor \
                  instead.')
        ctx.stride = _pair(stride)
        ctx.padding = _pair(padding)
        ctx.dilation = _pair(dilation)
        ctx.groups = groups
        ctx.im2col_step = im2col_step

        weight = weight.type_as(input)
        ctx.save_for_backward(input, weight)
        # 这里计算卷积的输出的维度
        output = input.new_empty(MyConvF._output_size(ctx, input, weight))

        ctx.bufs_ = [input.new_empty(0), input.new_empty(0)]  # columns, ones
        
        cur_im2col_step = min(ctx.im2col_step, input.size(0))
        assert (input.size(0) % cur_im2col_step
                ) == 0, 'batch size must be divisible by im2col_step'

        if bias is None:
            # print(weight.device)
            # bias = torch.zeros(weight.size(0)).to(input.device)
            bias = input.new_empty(0).to(weight.device)
            # print(bias.size(0))
        # 
        my_ops.my_conv_forward(
            input,
            weight,
            bias,
            output,
            ctx.bufs_[0],
            kW=weight.size(3),
            kH=weight.size(2),
            dW=ctx.stride[1],
            dH=ctx.stride[0],
            padW=ctx.padding[1],
            padH=ctx.padding[0],
            dilationW=ctx.dilation[1],
            dilationH=ctx.dilation[0],
            group=ctx.groups,
            im2col_step=cur_im2col_step,
            A_rowptr=A_rowptr,
            A_colind= A_colind,
            A_csrVal=A_csrVal)
        # print(output)
        
        return output

    @staticmethod
    def _output_size(ctx, input, weight):
        channels = weight.size(0)
        output_size = (input.size(0), channels)
        for d in range(input.dim() - 2):
            in_size = input.size(d + 2)
            pad = ctx.padding[d]
            kernel = ctx.dilation[d] * (weight.size(d + 2) - 1) + 1
            stride_ = ctx.stride[d]
            output_size += ((in_size + (2 * pad) - kernel) // stride_ + 1, )
        if not all(map(lambda s: s > 0, output_size)):
            raise ValueError(
                'convolution input is too small (output would be ' +
                'x'.join(map(str, output_size)) + ')')
        return output_size`

**Comment by drisspg** [comment]
Can you give us some more information?

**Comment by ptrblck** [comment]
@zhangapeng The description points towards a memory violation in your custom CUDA kernel and I would recommend to run your code via `compute-sanitizer python script.py args` and/or `cuda-gdb` to get more information where the illegal memory access is caused.

**Comment by ngimel** [comment]
Closing, reopen if turns out to be a pytorch bug.

**Comment by zhangapeng** [comment]
Thank you for your attention, I have solved the problem, it is caused by not putting custom variables on cuda。I will close this question
