### ISSUE TITLE
Got CUDNN_STATUS_NOT_INITIALIZED although PyTorch recognizes CUDA & CuDNN

### ISSUE THREAD

**Issue by Amir-Arsalan** [pytorch/pytorch#9289]
**environment**

    OS: Ubuntu 16.04.3 LTS
    PyTorch version: 0.5.0a0+1483bb7
    How you installed PyTorch (conda, pip, source): source
    Python version: 3.5.2
    torch.backends.cudnn.version(): 7104
    CUDA version: 9.0.176
    NVIDIA driver version: 390.48 (tried with 390.67 as well)
    GPU: Pascal Titan-X (CUDA compute capability 6.1)

I compiled PyTorch from source and tried to run the CIFAR classification code from [here](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#sphx-glr-beginner-blitz-cifar10-tutorial-py). I only move the network and mini batches to GPU and do the training. However, I get the following error at the beginning of training:

`RuntimeError: CuDNN error: CUDNN_STATUS_NOT_INITIALIZED`

Doing `device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")` will correctly show me `cuda:0`. Then I do `net.to(device)` and `inputs, labels = inputs.to(device), labels.to(device)`.

Can anyone give me a clue why I get this error?

**Comment by Amir-Arsalan** [comment]
Forgot to mention that I build PyTorch in a Singularity container and bootstrap the container with an NVIDIA docker as follow:

```
BootStrap: docker
From: nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
```

**Comment by Amir-Arsalan** [comment]
This does not happen if I install PyTorch 0.4 through `pip` for Python3.

**Comment by soumith** [comment]
pytorch via 0.4 has it's own CUDA / CuDNN binaries (which are part of the package). Maybe your locally installed CUDA / CuDNN are in a wonky state?

**Comment by Amir-Arsalan** [comment]
@soumith Well I'm pulling CUDA/CuDNN from NVIDIA's docker hub. Shouldn't it be working properly?

**Comment by Amir-Arsalan** [comment]
@soumith @ngimel Do you think this could be happening because the latest version of CUDA/CuDNN might have some dependencies on driver version? I know the latest driver version for Ubuntu is 390.67 but the one that I'm using is 390.48.

**Comment by Amir-Arsalan** [comment]
@soumith I am getting the exact same error message when trying to do a forward pass on a Lua Torch model after converting its modules to CuDNN modules. Do you think this could be related?

**Comment by soumith** [comment]
@Amir-Arsalan I wouldn't rule out driver upgrade solving the issue.

**Comment by Amir-Arsalan** [comment]
I will give it a try in a few days.

**Comment by Amir-Arsalan** [comment]
@soumith @ngimel I tried with the latest driver but still get the same error. What else do you think could be potentially causing this?

**Comment by Amir-Arsalan** [comment]
@soumith I also sent an email to _Felix Abecassis_ from NVIDIA and told him about this issue and asked him if he thinks the updates on CuDNN might be causing this. This is his reply:

> The versions of cuBLAS and cuDNN for CUDA 9.0 were updated, but I think that's all. These are the only potential culprits I see on the image side.

I think what he means by image side is the Docker image.

**Comment by ngimel** [comment]
Have you tried official docker file (docker/pytorch/Dockerfile)? I've just rebuilt an image with it, it starts with `nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04` image, the same you are using, has cudnn 7.1.4, and it works for me. The fact that you also have issues with lua torch points to the problems with your environment rather than cuda libraries.

**Comment by Amir-Arsalan** [comment]
@ngimel I didn't do this using the official Docker file but it looks like the [PyTorch Conda package](https://anaconda.org/pytorch/magma-cuda90) has been built about 5 months ago. Based on the above comment @soumith gave it looks like the pre-build packages of PyTorch use their own binaries for CuDNN. If that holds true for the Conda package, PyTorch will not use the CuDNN supplied through the official Docker file from NVIDIA (`nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04`). To make sure that PyTorch is using CuDNN 7.1.4 you may run `torch.backends.cudnn.version()`

Can you try building PyTorch from **source** using [Singularity](https://www.sylabs.io/guides/2.5.1/user-guide/)? Below I share my Singularity definition script that I've been using for the past 6-7 months so that you can use it to build a container for PyTorch. I've not changed any part of this script for a long time and never faced the issue I described above until recently:

```
BootStrap: docker
From: nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

apt-get -y update && apt-get -y install locales
locale-gen en_US.UTF-8
apt-get -y update && apt-get -y install make \
                                        dpkg \
                                        wget \
                                        g++ \
                                        gcc \
                                        xvfb \
                                        libyaml-cpp-dev \
                                        git \
                                        cmake \
                                        vim \
                                        curl \
                                        ca-certificates \
                                        software-properties-common \
                                        python3 \
                                        python3-pip \
                                        zlib1g-dev \
                                        freeglut3-dev \
                                        mesa-utils \
                                        libreadline-dev \
                                        gnuplot \
                                        gnuplot-qt \
                                        unzip \
                                        libboost-all-dev

pip3 install --upgrade pip==9.0.3
yes y | pip3 uninstall setuptools
pip3 install -U setuptools
pip3 install -U pyyaml
pip3 install multiprocess \
                        joblib \
                        scipy \
                        numpy \
                        transforms3d \
                        matplotlib \
                        mkl \
                        mkl-devel \
                        cffi \
                        Pillow \
                        h5py 

apt-get install -y python3-setuptools

# PyTorch
cd /
mkdir /repo-src && cd /repo-src
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
python3 setup.py install

# TorchVision
cd /
mkdir torchvision && cd torchvision
git clone --recursive https://github.com/pytorch/vision.git
cd vision
python3 setup.py install
```

**Comment by ngimel** [comment]
The Dockerfile that I referenced builds pytorch from source using `nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04` as the base image. It does not install pre-built conda package, and thus dynamically links to cudnn from base image (that is, cudnn 7.1.4). sorry, I don't have singularity environment to try your script.

**Comment by soumith** [comment]
@Amir-Arsalan please adopt the given Dockerfile to your singularity based env and see if it works out.

**Comment by Amir-Arsalan** [comment]
@ngimel @soumith I hope you didn't get me wrong. I never meant PyTorch does not compile with CuDNN 7.1.4. In fact, it compiles and doing `torch.backends.cudnn.version()` shows the correct CuDNN version. The problem is training does not work. I just compiled PyTorch using the same Singularity definition file with the only difference being I downgraded the CuDNN version (I tried a couple of versions below 7.1.4). Now everything works fine! I'm still very suspicious at the newest CuDNN version. This issue does not only happen for PyTorch and I get the same error message in Lua Torch as well when I want to convert my model modules into CuDNN modules and start training.

**Comment by Amir-Arsalan** [comment]
It looks like the new version of the Docker file does not set the environmental variables after making the container; it only sets them while making the container and that's why PyTorch/Torch and other framewkros recognize CuDNN while compilation. Setting the environmental variables manually after the container is built fixed the issue. Sorry for the confusions.

**Comment by Amir-Arsalan** [comment]
@ngimel After copying my container to our servers things broke down again. Our servers use CentOS 7.4 and I'm afraid the new Docker file does not account for that :( I wonder, since you work at NVIDIA, could you please let the team behind CuDNN know about this issue? I could fix things on my side if I knew what environmental variables of the mother OS (CentOS 7.4 in this case) the Docker image depend on.

**Comment by ngimel** [comment]
I'm not quite sure what your issue is. If you think problem is with nvidia-docker file an issue at nvidia-docker https://github.com/NVIDIA/nvidia-docker, if you think base images are faulty file an issue at https://gitlab.com/nvidia/cuda/. Docker image should not depend on host OS environment variables.

**Comment by Amir-Arsalan** [comment]
@ngimel Moved the Singularity containers built with older versions of CuDNN to our servers. Everything works okay with older versions. I'm gonna file an issue to NVIDIA repos.

**Comment by Amir-Arsalan** [comment]
@soumith As mentioned [here](https://github.com/NVIDIA/nvidia-docker/issues/793) too, This does not happen anymore after the latest updates to the Docker image contents from NVIDIA.

**Comment by KrnTneja** [comment]
For my single-GPU task, I just specified the GPU to use using `export CUDA_VISIBLE_DEVICES=0` and it worked. No idea why this worked but I hope it helps someone.
