### ISSUE TITLE
Run Error CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by qimw** [pytorch/pytorch#9456]
## Issue description
I build the caffe2 from source on ubuntu 16,and then run the detectron with 
`
python2 tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo
` as [this](https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md).
But It reports that:

`
Traceback (most recent call last):
  File "tools/infer_simple.py", line 156, in <module>
    main(args)
  File "tools/infer_simple.py", line 126, in main
    model, im, None, timers=timers
  File "/mnt/workspace/wqm/detection/detectron/detectron/core/test.py", line 66, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/mnt/workspace/wqm/detection/detectron/detectron/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/mnt/workspace/wqm/caffe2-for-detectron/pytorch/build/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/mnt/workspace/wqm/caffe2-for-detectron/pytorch/build/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at context_gpu.h:100] status == CUDNN_STATUS_SUCCESS. 1 vs 0. , Error at: /mnt/workspace/wqm/caffe2-for-detectron/pytorch/caffe2/core/context_gpu.h:100: CUDNN_STATUS_NOT_INITIALIZED E
rror from operator: 
input: "gpu_0/data" input: "gpu_0/conv1_w" output: "gpu_0/conv1" name: "" type: "Conv" arg { name: "kernel" i: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 3 } arg { name: "order" s: "NCHW" } 
arg { name: "stride" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
`
When I build the caffe2 it can find the cuda and cudnn:

  89 --   USE_CUDA              : ON     
  90 --     CUDA static link    : OFF
  91 --     USE_CUDNN           : ON
  92 --     CUDA version        : 9.1
  93 --     cuDNN version       : 7.1.4
  94 --     CUDA root directory : /usr/local/cuda
  95 --     CUDA library        : /usr/local/cuda/lib64/stubs/libcuda.so
  96 --     cudart library      : /usr/local/cuda/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
  97 --     cublas library      : /usr/local/cuda/lib64/libcublas.so;/usr/local/cuda/lib64/libcublas_device.a
  98 --     cufft library       : /usr/local/cuda/lib64/libcufft.so
  99 --     curand library      : /usr/local/cuda/lib64/libcurand.so
 100 --     cuDNN library       : /usr/local/cuda/lib64/libcudnn.so
 101 --     nvrtc               : /usr/local/cuda/lib64/libnvrtc.so
 102 --     CUDA include path   : /usr/local/cuda/include
 103 --     NVCC executable     : /usr/local/cuda/bin/nvcc
 104 --     CUDA host compiler  : /usr/bin/cc

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:caffe2
- How you installed PyTorch (conda, pip, source):source
- Build command you used (if compiling from source):cmake .. &&make install DESTDIR=path/to/my/caffe2
- OS:ubuntu16
- Python version:2.7
- CUDA/cuDNN version:9.1/7
- GPU:titan x
- GCC version (if compiling from source):5.4.0
- CMake version:3.5.1

**Comment by Amir-Arsalan** [comment]
@soumith  @ngimel 
This could be relevant to what I posted earlier [here](https://github.com/pytorch/pytorch/issues/9289).

**Comment by Amir-Arsalan** [comment]
@qimw Try setting the environmental variables manually and see if things work.

```
export CUDNN_INCLUDE_DIR=/usr/local/cuda/include
export CUDNN_LIB_DIR=/usr/local/cuda/lib64
```

**Comment by qimw** [comment]
@Amir-Arsalan @SsnL @eklitzke @huitseeker @jfsantos Thank you very much! I have solved this problem. This is because detectron do not support cuda9.1, so I use cuda8.0 and it is ok now.
