### ISSUE TITLE
[MPS] `nn.Linear` has incorrect output for certain tensor shapes on macOS 13.2.1

### ISSUE THREAD

**Issue by brkirch** [pytorch/pytorch#95188]
### 🐛 Describe the bug

Recently I've noticed that inference with Stable Diffusion using MPS (in AUTOMATIC1111's web UI) is producing bad output for certain image sizes. After some testing, I determined that `nn.functional.linear` is producing incorrect output for larger image sizes on the current version of macOS (13.2.1). The following code demonstrates that `nn.Linear` produces different results from CPU with certain tensor shapes on macOS 13.2.1:
```python
import torch
from copy import deepcopy

def test_linear(x_shape):
    x = torch.randn(x_shape)
    linear_cpu = torch.nn.Linear(320,320)
    linear_mps = deepcopy(linear_cpu).to('mps')
    cpu_result = linear_cpu(x)
    mps_result = linear_mps(x.to('mps'))
    torch.testing.assert_close(mps_result, cpu_result, check_device=False, msg="MPS result not equal to CPU result for shape " + str(x_shape))

# 512x512 image size
test_linear([2, 4096, 320])
# 1152x1152 image size
test_linear([2, 20736, 320])
```

If run on macOS 13.1, no output should be produced. If run on macOS 13.2.1, the following output is produced:
```
Traceback (most recent call last):
  File "/Users/brkirch/Desktop/test4.py", line 13, in <module>
    test_linear([2, 20736, 320])
  File "/Users/brkirch/Desktop/test4.py", line 10, in test_linear
    torch.testing.assert_close(mps_result, cpu_result, check_device=False, msg="MPS result not equal to CPU result for shape " + str(x_shape))
  File "/Users/brkirch/stable-diffusion-webui/venv-torch-nightly/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1511, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: MPS result not equal to CPU result for shape [2, 20736, 320]
```

~~Also note that with `bias=False` for `nn.Linear` this issue doesn't seem to occur.~~

Edit: With more testing I've found that `bias=False` can also produce an incorrect result, but I haven't been able to yet find a consistent way to reproduce that.

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20230219
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.25.1
Libc version: N/A

Python version: 3.10.10 (main, Feb  8 2023, 05:34:50) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-13.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] open-clip-torch==2.7.0
[pip3] pytorch-lightning==1.7.6
[pip3] torch==2.0.0.dev20230219
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.11.1
[pip3] torchsde==0.2.5
[pip3] torchvision==0.15.0.dev20230219
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by 925-Studio** [comment]
No wonder I can't get the correct result when upscale 512x768 image by 2. Thanks for this info, I hope PyTorch team will fix this soon enough.

**Comment by Adreitz** [comment]
Note that above ~1472x1472, output from Stable Diffusion seems to resolve again on Apple Silicon, at least in my previous testing. I haven't had a chance to test on nightly versions, though.

**Comment by kulinseth** [comment]
@brkirch , can you please upgrade to latest MacOS 13.3 beta and check. This issue has been indeed fixed there. I could repro this issue on 13.2 :
```
  File "/Users/local/torch-nightly/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1514, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: MPS result not equal to CPU result for shape [2, 20736, 320]
```

But it works fine on 13.3

**Comment by brkirch** [comment]
@kulinseth @DenisVieriu97 Thank you for the update, I can confirm this issue as fixed. I'm encountering other issues with image generation that need workarounds however because cumsum on MPS gives incorrect results for bool tensors (see #96614) and crashes occur after using `torch.narrow()` (I have to clone the tensor from `torch.narrow()` to prevent them, it's likely related to #96153).
