### ISSUE TITLE
Buffer not large enough on simple tensor assignment with mps backend 

### ISSUE THREAD

**Issue by Haydnspass** [pytorch/pytorch#96181]
### 🐛 Describe the bug

Python kernel crashes when using mps backend for elementary broadcasted tensor assignment.

To reproduce
```python
import torch

x = torch.rand(1120, 3, device="mps:0")
x[..., -1] = 1  # fails with kernel crash
x[:, -1] = 1  # same
```

#### Error message:
```
>>> x[..., -1] = 1
/AppleInternal/Library/BuildRoots/c651a45f-806e-11ed-a221-7ef33c48bc85/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:794: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 4480 bytes
'
[1]    86942 abort      python

```

### Versions

Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] pytorch-lightning==1.8.6
[pip3] torch==1.13.1
[pip3] torchmetrics==0.11.0
[conda] cpuonly                   2.0                           0    pytorch
[conda] numpy                     1.21.6          py310h2e04ed8_0    conda-forge
[conda] pytorch                   1.13.1                 py3.10_0    pytorch
[conda] pytorch-lightning         1.8.6                    pypi_0    pypi
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchmetrics              0.9.3                    pypi_0    pypi

cc @ezyang @gchanan @zou3519 @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by Haydnspass** [comment]
Addendum: The problem seems to be broadcasting; this works without problems

```python
>>> import torch
>>> x = torch.rand(1120, 3, device="mps:0")
>>> x[..., -1] = torch.ones(1120, device="mps:0")
```

**Comment by kulinseth** [comment]
@Haydnspass , can you check latest nightly or 2.0 RC, the issue has been fixed:

```
>>> import torch
>>> x = torch.rand(1120, 3, device="mps:0")
>>> x[..., -1] = 1  # fails with kernel crash
>>> x[:, -1] = 1  # same
>>> x
tensor([[0.6754, 0.7410, 1.0000],
        [0.5041, 0.1524, 1.0000],
        [0.8119, 0.6621, 1.0000],
        ...,
        [0.4229, 0.3219, 1.0000],
        [0.9498, 0.5650, 1.0000],
        [0.3275, 0.5937, 1.0000]], device='mps:0')
>>>
```

**Comment by kulinseth** [comment]
@Haydnspass  you can get 2.0 RC from here:
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cpu
```

**Comment by Haydnspass** [comment]
> @Haydnspass , can you check latest nightly or 2.0 RC, the issue has been fixed:
sorry missed this, works well
