### ISSUE TITLE
Expose MPS to C++ (like cuda)

### ISSUE THREAD

**Issue by bsergean** [pytorch/pytorch#96425]
### 🚀 The feature, motivation and pitch

There is torch::cuda::is_available(), but there is no torch::mps::is_available(), so it looks like mps/metal is not exposed as a backend to C++.

Some apps might want to run inference on metal using the very nice to use pytorch apis + it would be very helpful to be able to test cuda like flows (like sending tensors to gpu etc...) locally on a mac by using MPS (Metal).

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
Actually you can leverage mps backend on the c++ frond end by sending tensors to a mps device, like so:

```c++
auto t = torch::tensor({7, 2, 3, 5, 8}, torch::device(torch::kMPS));
// or
auto t2 = torch::tensor({7, 2, 3, 5, 8}).to("mps");
```

There is no apis like `is_available` for now indeed.

**Comment by bsergean** [comment]
That’s very interesting, thanks for the note. I will try to see if sending to a device this way works.

I tried a python script and that one definitely worked (like sending to an MPS device).

**Comment by albanD** [comment]
Also there is `at::mps::is_available()` available. Not sure what we need to do to properly expose it on `torch::`

**Comment by bsergean** [comment]
I tried to call at::mps::is_available

With 1.13.1 but I couldn’t find that symbol. Maybe it is only present in 

Cuda code has an explicit such thing inside cuda.h

namespace torch {
namespace cuda {

/// Returns the number of CUDA devices available.
size_t TORCH_API device_count();

/// Returns true if at least one CUDA device is available.
bool TORCH_API is_available();

**Comment by albanD** [comment]
It is very likely to have been added after 1.13 yes. 2.0 should be out next week where you can find it!

**Comment by qqaatw** [comment]
> Also there is `at::mps::is_available()` available. Not sure what we need to do to properly expose it on `torch::`

It seems that `at::mps::is_available()` isn't exposed in the c++ frond end by simply using `<torch/torch.h>` header. (unless you include `aten/src/ATen/mps/MPSDevice.h`)

**Comment by bsergean** [comment]
Great, thanks for the wealth of information.

Once I can use this code, my next question will be to understand if the jit is supported with MPS.

This is the module we use

torch::jit::script::Module

I know lots of things are changing in 2.0 so not sure if there will be a better plan. But we’ve played with 2.0 and it works well so far.

**Comment by razarmehr** [comment]
The `torch::mps::is_available()` for C++ was initially added in [this commit](https://github.com/pytorch/pytorch/pull/94417/commits/2b650845a9e1ded37d78df798c9ea4b8fbf6ad40#diff-46701bb5876c77c75fc9577322d64f2f41daa5112d8ac83c3da9641679b1d854), but was later removed to address [this comment](https://github.com/pytorch/pytorch/pull/94417/commits/2b650845a9e1ded37d78df798c9ea4b8fbf6ad40#r1100535075).
We could bring it back if it helps (along with `synchronize()` and `manual_seed()`).

**Comment by bsergean** [comment]
You are all much more versed with PyTorch than myself, so you’ll understand consequences better.

For me I’m developing most of the time on macOS, but my code needs to be able to run on cuda on linux too, and I broke this recently because the code change I made was just working with device = kCPU.

If I had been trying to use kMPS on macOS, I would probably have caught my problem.

**Comment by kulinseth** [comment]
@bsergean , thanks for bringing this up. Its important to expose the API to have parity. We will priortize this.

**Comment by bsergean** [comment]
thanks !
