### ISSUE TITLE
GPU：7900xtx Pytorch2.0.0  rocBLAS error:

### ISSUE THREAD

**Issue by hexpayload** [pytorch/pytorch#96964]
### 🐛 Describe the bug

```python
import torch
A = torch.ones(5, 5).to('cuda')
B = torch.ones(5, 5).to('cuda')
C = torch.matmul(A, B)
```
when program runing to calc C,i get this Message: 
```
rocBLAS error: Cannot read /home/kali/miniconda3/envs/pytorch2/lib/python3.9/site-packages/torch/lib/rocblas/library/TensileLibrary.dat: No such file or directory
```

It is found that the reason is the lack of the rocblas library file with the architecture of gfx1100, so putting the gxf1100 library file into the rocblas directory in the python environment of conda can solve this problem

### Versions

GPU：AMD 7900XTX
OS：Ubuntu 22.04
Pytorch: 2.0.0
install by: pip install 

Compiling the source code or repackaging the whl file containing the gfx1100 library files can solve this problem

cc @ezyang @seemethere @malfet @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by sunway513** [comment]
Hi @hexpayload 7900xtx (Navi31) is not yet supported by ROCm stack, please stay tuned on the ROCm future release announcements. 
Once the baseline support of Navi3x architecture is in place on ROCm stack, we'll integrate and enable it with PyTorch.

**Comment by pierluigizagaria** [comment]
I was having the same issue on a RX6700 and [this issue](https://github.com/RadeonOpenCompute/ROCm/issues/1698) helped me.

**Comment by chiboreache** [comment]
same on 5700xt 

![2023-11-17x06:03:05](https://github.com/pytorch/pytorch/assets/16459251/e8bf03e2-ab36-4960-b189-9bc9afe070f6)

**Comment by qb-0** [comment]
Is this still a open issue? Having the same problem with arch and 7900 xt. 

> Compiling the source code or repackaging the whl file containing the gfx1100 library files can solve this problem

Is there a guide how to do this?

**Comment by hongxiayang** [comment]
@hexpayload  Please check below documentation about Pytorch on 7900XTX.

https://rocm.docs.amd.com/projects/radeon/en/latest/index.html

https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/install-pytorch.html

**Comment by nejcpetan** [comment]
Im using Rocm 5.6, my GPU is Radeon RX 6600, Ubuntu 22.0.4 LTS, using miniconda. To get around the error, I've added:

`export HSA_OVERRIDE_GFX_VERSION=10.3.0`

Into the start_linux.sh file under `# environment isolation`

Just added that and the model loaded without any issue. I'm also using Stable Diffusion with these parameters with A1111 and ComfyUI without any issues.

**Comment by hongxiayang** [comment]
For 7900XTX, please install pytorch using one of the opations in https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/install-pytorch.html:
For example:
```
sudo docker pull rocm/pytorch:rocm5.7_ubuntu22.04_py3.10_pytorch_2.0.1
```
And then follow instructions in the above documentation to start the docker container, and then you should be fine.
```
sudo docker run -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --ipc=host --shm-size 8G rocm/pytorch:rocm5.7_ubuntu22.04_py3.10_pytorch_2.0.1
```
I tested on one 7900XTX (gfx1100), and it works fine.
![image](https://github.com/pytorch/pytorch/assets/62075498/f6571d7c-f164-4311-bec8-0baeb5105863)

**Comment by hongxiayang** [comment]
> Is this still a open issue? Having the same problem with arch and 7900 xt.
> 
> > Compiling the source code or repackaging the whl file containing the gfx1100 library files can solve this problem
> 
> Is there a guide how to do this?
Please check: (try wheel or docker method first before trying to build from source)
https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/install-pytorch.html

**Comment by hongxiayang** [comment]
close this issue as new document is available, and no response for a while.
