### ISSUE TITLE
Convolutions are broken for PyTorch-2.0 CUDA-11.8 wheel builds

### ISSUE THREAD

**Issue by kzkadc** [pytorch/pytorch#97041]
### 🐛 Describe the bug

Forward pass generates error with pytorch 2.0.

```python
import torch
from torchvision.models import resnet18

net = resnet18().cuda()
x = torch.zeros((1, 3, 224, 224)).float().cuda()
y = net(x)

# Could not load library libcudnn_cnn_infer.so.8. Error: libnvrtc.so: cannot open shared object file: No such file or directory
# Aborted (core dumped)
```

This seems to be torchvision's issue since such an error do not occur with hand-crafted models.

```python
import torch
from torch import nn

net = nn.Sequential(nn.Linear(10,10), nn.Sigmoid(), nn.Linear(10,1)).cuda()
x = torch.zeros((1, 10)).float().cuda()
y = net(x)    # OK
```

### Versions
```
Collecting environment information...
PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.10 (main, Mar 16 2023, 16:15:30) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.19.0-32-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080 Ti
Nvidia driver version: 525.78.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       GenuineIntel
Model name:                      11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz
CPU family:                      6
Model:                           167
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        1
CPU max MHz:                     5300.0000
CPU min MHz:                     800.0000
BogoMIPS:                        7008.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap avx512ifma clflushopt intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       384 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        16 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.0.0+cu118
[pip3] torchaudio==2.0.1+cu118
[pip3] torchvision==0.15.1+cu118
[pip3] triton==2.0.0
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @seemethere @malfet @csarofeen @ptrblck @xwang233

**Comment by ptrblck** [comment]
@malfet would it work if we `RPATH` `libcudnn*` to the mangled `libnvrtc` in `torch/lib` for the "large" binary builds?

**Comment by malfet** [comment]
Ok, I can reliably reproduce the problem and indeed a bit confused how validation framework could have missed it. I I guess the reason why it does not reproduce with CUDA-11.7 is that different versions of cudnn library is used for 11.7 and 11.8 builds.

**Comment by ptrblck** [comment]
> I guess the reason why it does not reproduce with CUDA-11.7 is that different versions of cudnn library is used for 11.7(8.5) and 11.8(8.7) builds.

I don't think the version update is related to this issue, but the different build processes (11.7 uses the cuDNN wheels while 11.8 uses our "large" binary build).
In the 11.8 build `libnvrtc-672ee683.so.11.2` is shipped, which cuDNN cannot detect while in 11.7 `nvidia/cuda_nvrtc` is installed as a dependency and ships with `libnvrtc.so.11.2`. I guess the SHA is added [here](https://github.com/pytorch/builder/blob/d7ad1b3890642cd3a2ae66b2d690b8f249df82b2/manywheel/build_common.sh#L344) to the `libnvrtc` we are using in the "large" binaries.

**Comment by ngimel** [comment]
Should we deprecate "large" binary build process now that cuda wheels are generally available?

**Comment by malfet** [comment]
> I don't think the version update is related to this issue, but the different build processes (11.7 uses the cuDNN wheels while 11.8 uses our "large" binary build). In the 11.8 build `libnvrtc-672ee683.so.11.2` is shipped, which cuDNN cannot detect while in 11.7 

Above comparison were run using two "large" builds: one for 11.7 and another for 11.8. And based on `strings` both cudnn depends on "libnvrtc.so", though cudnn-8.5 does not need nvrtc for (3x3) convolution.

**Comment by ddelange** [comment]
is dynamic linking to the shared libraries an option?

can't it be reasonably expected from a cuda user that is installing the cuda wheels, is doing so on a system that was set up with cuda (and if they want to use it, cudnn/tensorrt/...)?

and hence that system has the correct `libnvrtc.so` available for the cuda/cudnn versions they are running (probably coherently installed from nvidia apt)?

as long as they request a [compatible](https://docs.nvidia.com/deploy/cuda-compatibility/index.html) cuda wheel from the pytorch index, it will find the right libraries and all will be good?

the cuda wheels would end up much smaller, and this might even alleviate some version management hell for the team as it would essentially be 'outsourced' to the nvidia repository.

e.g. mxnet just says on their [cuda pypi page](https://pypi.org/project/mxnet-cu116/1.9.1/) to apt/yum install libquadmath and for the rest expect cuda & friends to be installed with shared libraries in place: the resulting cuda wheels are only ~500MB

**Comment by ptrblck** [comment]
> Should we deprecate "large" binary build process now that cuda wheels are generally available?

Yes, I think this would make sense and we should reconsider it, unless we see any benefits in having the "large" wheels (I'm not aware of any). I also believe the needed infra changes for 11.7 and 11.8 landed here: https://github.com/pytorch/builder/pull/1248.
However, I don't know if these "small" wheel builds were triggered for 11.8 or tested, so unsure if more changes are currently missing.

> Above comparison were run using two "large" builds: one for 11.7 and another for 11.8. And based on strings both cudnn depends on "libnvrtc.so", though cudnn-8.5 does not need nvrtc for (3x3) convolution. 

That's interesting to hear, so thanks for sharing it! I initially assumed cuDNN's runtime fusion API was called, but am apparently wrong. I'll try to check why it's needed in the conv layer to understand the dependency better.

> Also as libnvrtc.so is missing in wheel installation I'm not sure how it will work.

I'm currently also unsure why I cannot reproduce the issue using `2.0.0+cu118` using the original code or your code snippet after removing `/usr/local/cuda-11.7/targets/x86_64-linux/lib/libnvrtc.so` from my env.
Running the code again with `LD_DEBUG=files` gives:
```
    860875:	file=libnvrtc.so [0];  dynamically loaded by /home/pbialecki/miniforge3/envs/2.0.0_cu118/lib/python3.8/site-packages/torch/lib/libcublasLt.so.11 [0]
    860875:	file=libnvrtc-672ee683.so.11.2 [0];  needed by /home/pbialecki/miniforge3/envs/2.0.0_cu118/lib/python3.8/site-packages/torch/lib/libnvfuser_codegen.so [0]
    860875:	file=libnvrtc-672ee683.so.11.2 [0];  generating link map
    860875:	calling init: /home/pbialecki/miniforge3/envs/2.0.0_cu118/lib/python3.8/site-packages/torch/lib/libnvrtc-672ee683.so.11.2
    860875:	file=libnvrtc.so [0];  dynamically loaded by /home/pbialecki/miniforge3/envs/2.0.0_cu118/lib/python3.8/site-packages/torch/lib/libcudnn_cnn_infer.so.8 [0]
    860875:	calling fini: /home/pbialecki/miniforge3/envs/2.0.0_cu118/lib/python3.8/site-packages/torch/lib/libnvrtc-672ee683.so.11.2 [0]
```
seems to show `torch/lib/libnvrtc-672ee683.so.11.2` is used. In any case, I will follow up with you to recreate the breaking environment or will experiment a bit more.

> can't it be reasonably expected from a cuda user that is installing the cuda wheels, is doing so on a system that was set up with cuda

No, since depending on a locally installed CUDA toolkit will create a lot of issues for less experienced users. 
The PyTorch binaries should depend on a properly installed NVIDIA driver and should install or package all needed CUDA dependencies to allow even novice users to directly execute any PyTorch workload (with the exception of building custom CUDA extensions).

> the cuda wheels would end up much smaller, and this might even alleviate some version management hell for the team as it would essentially be 'outsourced' to the nvidia repository.

In contrary this could create a debugging hell trying to reproduce each new user environment when something fails.

**Comment by kzkadc** [comment]
Thank you all for your help!
The CUDA-11.7 wheel works in my environment and I'm using it for now.

**Comment by malfet** [comment]
Did a bit more digging with @ptrblck : looks like it's Ubuntu specific: if one bases container on Ubuntu-20.04 it works, but on Ubuntu-22.04 it fails

**Comment by priiice** [comment]
Hi, I wanted to chime in and say that I have experienced the same problem. In my case it was from a fresh install of Arch Linux (live iso 2023.03.01-x86_64).

From a fresh installation (and full system update):
1. Installed Python 3.10, pip, virtualenv
2. Installed nvidia package (version 525.89.02-11: linux 6.2.6.arch1-1) via pacman and ensured loading of nvidia, nvidia_modeset, nvidia_uvm, and nvidia_drm modules
3. Created and enabled a virtual environment
4. Installed Pytorch via "pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118"
5. Running a simple model produced the same "Could not load library libcudnn_cnn_infer.so.8. Error: libnvrtc.so: cannot open shared object file: No such file or directory" abort

I worked around it by symlinking site-packages/torch/lib/libnvrtc-672ee683.so.11.2 to libnvrtc.so

Unfortunately, I'm traveling for work and am away from my ML machine so I can't pull any config details from it at the moment, but I wanted to share that this isn't purely an issue with Ubuntu containers/docker.

**Comment by malfet** [comment]
Ok, I did a bit more debugging, and it boils down to the following curious behavior:
```cpp
// Compile me as gcc foo.c -ldl -Wl,-rpath=.
#include <stdio.h>
#include <dlfcn.h>

void *try_open(const char* name) {
	void *handle = dlopen(name, RTLD_NOW);
	const char *err = dlerror();
	if (!handle) {
		printf("Failed to open %s: %s\n", name, err);
	} else {
		printf("Opened %s as %p, dlerror is %s\n", name, handle, err);
	}
	return handle;
}

int main(void) {
	// This captures dlerror on Ubuntu-22.04, but works in Ubuntu-20.04
	try_open("libcudnn_cnn_infer.so.8");

	return 0;
}
```

On Ubuntu-20.04 it somehow swallows the error raised by cudnn:
```
# cat /etc/issue; ./a.out 
Ubuntu 20.04.5 LTS \n \l
Opened libcudnn_cnn_infer.so.8 as 0x5595a241d2d0, dlerror is (null)
```
But on 22.04 error is preserved:
```
# cat /etc/issue; ./a.out 
Ubuntu 22.04.2 LTS \n \l

Opened libcudnn_cnn_infer.so.8 as 0x56323a5d72d0, dlerror is libnvrtc.so: cannot open shared object file: No such file or directory
```

**Comment by ddelange** [comment]
potentially related not just for cuda 12.1 but also for 11.8?

> In cuDNN 8.8.0, the runtime fusion engine failed with NVRTC from CUDA 12.1. This bug is fixed in cuDNN 8.8.1, but the limitation still remains that the runtime fusion engine is not forward compatible beyond CUDA 12.1. This limitation will be addressed in a future release.

https://docs.nvidia.com/deeplearning/cudnn/release-notes/index.html#rel-881

**Comment by a-storm** [comment]
what helped me:

# I have conda env named torch
cd /home/user/anaconda3/envs/torch/lib
# link to lib, it tries to use lib without versions
sudo ln -sfn libnvrtc.so.11.8.89 libnvrtc.so

**Comment by malfet** [comment]
Following seems to fix the issue, so adding this logic before first call to `cudnnCreateBackend`:
```cpp
// Compile me as gcc foo.c -lcudnn -Wl,-rpath=.
#include <stdio.h>
#include <dlfcn.h>

int cudnnBackendCreateDescriptor(int, void**);

int main(void) {
  // Removing next line witll cause cudnnBackendCreateDescriptor call abort()	
  void *h = dlopen("libcudnn_cnn_infer.so.8", RTLD_LAZY);
  printf("h=%p, dlerror=%s\n", h, dlerror());

  void *handle = NULL;
  printf("About to create backend\n");
  int rc = cudnnBackendCreateDescriptor(1, &handle);
  printf("rc=%d handle=%p\n", rc, handle);

  return 0;
}
```

**Comment by sbfkcel** [comment]
```shell
cd /usr/local/lib/python3.10/dist-packages/torch/lib

cp libnvrtc-builtins.so.11.8 libnvrtc.so
```

**Comment by NightMachinery** [comment]
This warning still happens on the latest PyTorch for CUDA 11.8:
```
# https://pytorch.org/get-started/previous-versions/
pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu118
```

Should we just ignore the warning?
