### ISSUE TITLE
Memory access fault by GPU node-1 when Training NanoGPT with ROCm

### ISSUE THREAD

**Issue by stanleyshly** [pytorch/pytorch#97074]
### 🐛 Describe the bug

I'm currently running  `python train.py config/train_shakespeare_char.py` in Andrej Karpathy's nanoGPT repo, to no avail. When running on my Cuda or on the CPU, the script works just fine. But when executing the all of the new Pytorch 2 features like fused AdamW, flash attention, compile, etc I get this error:
```
# baby GPT model :)
n_layer = 6
n_head = 6
n_embd = 384
dropout = 0.2

learning_rate = 1e-3 # with baby networks can afford to go a bit higher
max_iters = 5000
lr_decay_iters = 5000 # make equal to max_iters usually
min_lr = 1e-4 # learning_rate / 10 usually
beta2 = 0.99 # make a bit bigger because number of tokens per iter is small

warmup_iters = 100 # not super necessary potentially

# on macbook also add
# device = 'cpu'  # run on cpu only
compile = False # do not torch compile the model

found vocab_size = 65 (inside data/shakespeare_char/meta.pkl)
Initializing a new model from scratch
number of parameters: 10.65M
using fused AdamW: True
step 0: train loss 4.2862, val loss 4.2811
Memory access fault by GPU node-1 (Agent handle: 0x55e92f082620) on address (nil). Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```

I can't figure out when this is happening, even after doing `export HSA_OVERRIDE_GFX_VERSION=10.3.0` and turning off compile. Any thoughts for why it isn't working on ROCm?

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0+rocm5.4.2
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.4.22803-474e8620

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Radeon RX 6600 XT
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.4.22803
MIOpen runtime version: 2.19.0
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          6
On-line CPU(s) list:             0-5
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
CPU family:                      6
Model:                           158
Thread(s) per core:              1
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        10
CPU max MHz:                     4000.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5599.85
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust sgx bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        1.5 MiB (6 instances)
L3 cache:                        9 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-5
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT disabled
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.1
[pip3] pytorch-triton-rocm==2.0.0
[pip3] torch==2.0.0+rocm5.4.2
[pip3] torchaudio==2.0.0.dev20230310+rocm5.4.2
[pip3] torchvision==0.15.0.dev20230310+rocm5.4.2
[conda] Could not collect

```

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by jeffdaily** [comment]
Is this related to https://github.com/pytorch/pytorch/issues/95808?

**Comment by stanleyshly** [comment]
@jeffdaily Yes, seems to be related. I tried the docker container, and it works well. However, I'm unable to build the pull request from source on my system, so I can't test it right now. Hopefully it gets merge soon.

**Comment by jglaser** [comment]
it should be fixed now (for ROCm/no triton) in `main`.... maybe this issue can be closed?

**Comment by jeffdaily** [comment]
This issue was confirmed to be a duplicate of #95808 which was closed automatically when #95810 merged with https://github.com/pytorch/pytorch/commit/933166e5c0bfe599bcfa9dc3470af05864c7a05e.  Closing this as well.
