### ISSUE TITLE
Potential 0.4.1 Memory Leak for a Fairseq Model

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [pytorch/pytorch#9942]
Yesterday, when I was on 0.4.0 I was training a fairseq model (self_att_wp) I could train it fine with batch size of around 4 (technically I control the number of tokens fed into the model). After upgrading to 0.4.1, when training the same model with the same arguments it runs out of memory. Even decreasing the batch size it still runs out of memory after a bit of time with memory just increasing after every couple of batches.

There's an issue in fairseq mention this as well, https://github.com/pytorch/fairseq/issues/232. The issue mentions the memory leak with a different fairseq model, so I'd guess that multiple fairseq models now have this issue. The command used to train the fairseq model I've been using are:

python3.6 train.py data-bin/wikitext_outline_to_target -
a fconv_self_att_wp --lr 0.25 --clip-norm 0.1 --max-tokens 4000 --lr-scheduler reduce_lr_on_plateau --source-lang wikitext_outline --target-lang wikitext_target --max-epoch 25 --no-epoch-checkpoints --save-di
r model4_checkpoints/

You'll need to replace source-lang/target-lang and the data-bin argument by whatever dataset you end up using. The readme here, https://github.com/pytorch/fairseq/tree/master/examples/stories, describes the commands in some more detail to cover that part and trains the same architecture (some variation in exact arguments, but I don't think they'll matter).

edit: More specifically the error was a cuda out of memory error and doing nvidia-smi I could see the memory increasing over time. I also had upgraded to cuda 9.2/cudnn 7.1.4 so it might be an issue there. The OS was ubuntu 16.04.

**Comment by zou3519** [comment]
We're glad that you found that it's not 0.4.1!

**Comment by hmc-cs-mdrissi** [comment]
If you look at the edit, while I don't think it was caused solely by 0.4.1, I think part of it was caused by either it or cuda 9.2. I didn't check to see which of the two was having the harmful effect (mostly due to a deadline in a few days that needs working code). I can investigate it more properly this weekend.

**Comment by soumith** [comment]
that's good to know. Please reopen the issue once you investigate. thanks

**Comment by amrsharaf** [comment]
@soumith  I had a similar problem and I'm pretty sure `ReduceLROnPlateau` has a memory leak issue. The issue is in this line:

 https://github.com/pytorch/pytorch/blob/master/torch/optim/lr_scheduler.py#L444

I fixed this by just moving the `_cmp` function outside of the class. Seems like the partial function over self._cmp keeps a pointer over the optimizer parameters and the memory is not released correctly.

Also could be related is this issue here: https://github.com/pytorch/pytorch/issues/17630

**Comment by soumith** [comment]
@amrsharaf can you please open a new issue and tag @vincentqb
